### ISSUE TITLE
Use http proxy to request trusted 3rd party sources

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#10002]
### Proposal

Switch calls to 3rd party sources to use http proxy, similar to as is done in this internal PR:
https://git.archive.org/ia/petabox/-/merge_requests/4518/diffs

e.g.
```
requests.get("http://example.org/", proxies = {"https" : "http-proxy.us.archive.org:8080"})
```

### Justification

Calls to several 3rd party data sources no longer work due to our most recent network security changes.

Until this list is fixed, we'll be missing amazon & bwb prices and imports, recaptcha, wikidata, and several other sources

#### Requirements Checklist

The following services calls need to be proxied, preferably using some DRY approach that "proxifies" our existing `requests` calls.

We should also check out js `fetch` requests to make sure we don't make any calls there to 3rd party sources... We should also check that proxy calls fail from js (e.g. we currently lazy load affiliate prices... we should make sure the actualy API call for price data is happening on the backend and that the proxy rejects cross-origin requests from js).

* [ ] Recaptcha
  * https://github.com/internetarchive/openlibrary/blob/b8cea030784732e5ce02895b56b9344426f6e9fa/openlibrary/plugins/recaptcha/recaptcha.py#L8

* [ ] Amazon API (may be **difficult** because we're using a library)
  * https://github.com/internetarchive/openlibrary/blob/0621e75c0cea30be3902b606198247d6c1b2dc23/openlibrary/core/vendors.py#L115-L118
* [ ] BWB
  * https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L567
* [ ] Wikidata

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by jimchamp** [comment]
It doesn't seem to be possible to use the Amazon SDK with a proxy.  We can use `requests` to hit their API, though.  Saving this for last.
