### ISSUE TITLE
Restore localizations

### ISSUE THREAD

**Issue by asereze** [internetarchive/openlibrary#10003]
### Problem

Since the last attacks and downtime, changing the language of the interface does nothing.

![Screenshot_20241107-152508_Firefox](https://github.com/user-attachments/assets/9f928058-8a81-40aa-8443-7a392ab121e9)

### Reproducing the bug

1. Go to openlibrary.org
2. Do nothing (if your browser's language is not English), or try to set up a different interface language

* Expected behavior: the translated strings should appear
* Actual behavior: Everything (with the exception of the dates and times) remains in English

### Context

- Browser (Chrome, Safari, Firefox, etc): Firefox, Chromium and others
- OS (Windows, Mac, etc): Linux, Windows and Android
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Should now be fixed :+1:

**Comment by asereze** [comment]
Thank you!
