### ISSUE TITLE
Move "Yearly Reading Goals" from My Books body to Sidebar menu

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#10011]
## Description, Patron Story

- What is the design change?

Move "Yearly Reading Goals" from My Books home to the My Books Sidebar. Also, consider removing the modal / alert banner if no goal is set from the books page and instead showing text in this area that says, "set 2024 reading goal".

- Why is this design change necessary?

So its always visible on each page and also takes up less prime real estate 

- Who is it for?

All registered patrons

## Relevant Designs

Before
![image](https://github.com/user-attachments/assets/57765250-892a-44dd-8409-fe14efd82f13)

After
<img width="603" alt="Screenshot 2024-11-07 at 9 34 43 PM" src="https://github.com/user-attachments/assets/aa57f371-2749-487f-82e0-c717180bf906">

See: https://www.figma.com/design/dYQkIJOJeMo9hx7ewZQH9x/Open-Library%3A-Design-System-%26-Component-Library?node-id=1956-427&node-type=frame&t=ny7I7uZBshygPSsH-0

**Comment by schu96** [comment]
@jimchamp I'd like to be assigned to this issue
