### ISSUE TITLE
Error "Uploading Cover Image," "Reporting a Problem"

### ISSUE THREAD

**Issue by computerstimulation** [internetarchive/openlibrary#10012]
### Problem

I get the following error message when attempting to upload a book cover, or reporting a problem on the Open Library website.

Message:

Hmm...
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2024-11-08/153249131309 and will look into it as soon as possible. Head for home?

<img width="622" alt="Screenshot 2024-11-08 at 6 54 16 PM" src="https://github.com/user-attachments/assets/fe60f439-a2e9-45f9-a415-8133d1b641ab">
<img width="1113" alt="Screenshot 2024-11-08 at 6 56 00 PM" src="https://github.com/user-attachments/assets/59da460c-aebb-466f-aabb-d8d133eb9db5">

### Reproducing the bug

1. Go to https://openlibrary.org/books/OL56960756M/Minor_Philosophical_Treatises when signed in to Open Library.
2. Add a cover image.
3. Choose a file.
4. Click upload on Open Library.

* Expected behavior: The cover image will be uploaded successfully.
* Actual behavior: The cover image fails to be uploaded.

### Context

- Browser (Chrome, Safari, Firefox, etc): Brave, Safari
- OS (Windows, Mac, etc): macOS 15.1
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by cdrini** [comment]
Cover uploading should now be fixed; closing this issue and creating a separate one to monitor the contact form error.
