### ISSUE TITLE
"ebooks only" Search Page Radio-button for Book Filtering is confusing users

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1002]
In 2015 we had a checkbox in our header which allowed readers to "show ebooks only"
![screen shot 2018-06-26 at 13 02 08pmpdt](https://user-images.githubusercontent.com/978325/41936173-33235b40-7941-11e8-9fd6-c02148bc14f5.png)
 
In 2017 we tried an experiment of saving the user's preference within the **search** page using radio buttons:
![screen shot 2018-06-26 at 12 58 40pmpdt](https://user-images.githubusercontent.com/978325/41936077-d2f13080-7940-11e8-9a74-4dfe8c544199.png)

We've received feedback that this interface is confusing to users. Also, the mechanism by which we persist the user's settings (`mode=everything`, `mode=ebooks`) is flawed in that it screws up our get parameters across pages (in ol.js)

The fix should be (a) to use localstorage to save the user's preference, (b) instead of differentiating between `everything` and `ebooks only`, just make `ebooks only` a checkbox again on the search page (because `ebooks only` is just a facet over `everything`), and (c) and to inject a hidden `<input type="hidden" value="ebooks-only" name="mode"/>` into the search form rather than to modify GET parameters

**Comment by Num170R** [comment]
Long time but still on progress!

![work_search](https://user-images.githubusercontent.com/9248823/46016808-73085a00-c0de-11e8-8574-550337de8130.png)
