### ISSUE TITLE
Sync button throws error

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#10038]
### Problem

Using the "Sync Archive.org ID" throws the following error:
Hmm...
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2024-11-18/083520001434 and will look into it as soon as possible. Head for [home](https://openlibrary.org/)?

This is a new issue since the October incident.

### Reproducing the bug

1. Go to ... an openlibrary record that is linked to an IA item.
2. Do ... Click the sync button

* Expected behavior: JSON response (success/fail)
* Actual behavior: Hmmm error

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
We may have temporarily disabled this while other work was happening ; @jimchamp can you take a look and see if that is the case.
