### ISSUE TITLE
Contact form errors on submit

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#10030]
### Problem

![image](https://github.com/user-attachments/assets/4c390625-d7b7-477c-b7d1-8afccbf84772)

Triggered in our code from here: https://github.com/internetarchive/openlibrary/blob/067edbc80e50e9317a2889cc2bc2f1540c19b88d/openlibrary/plugins/openlibrary/support.py#L96-L97

### Reproducing the bug

1. Go to https://openlibrary.org/contact
2. Submit the form

* Expected behavior: The email is sent and a success message appears
* Actual behavior: An error screen appears

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Consider switching to a `mailto:` link to just circumvent this whole problem!

**Comment by jimchamp** [comment]
Noting that this is intermittent:

![image](https://github.com/user-attachments/assets/f5c93194-8478-4629-94ae-f44837401866)
