### ISSUE TITLE
Removing duplicate or deprecated template code

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1003]
See #819 which was closed because it became stale and also targeted things which were still in use (accidentally)

**Comment by cdrini** [comment]
Started looking into the templates to see what's still in use; here's what I've found so far: https://docs.google.com/spreadsheets/d/1pBB0MrcGamn8HqCdnkUd7Mj9VAaVQZ3JQj_osqf3QG0

**Comment by jdlrobson** [comment]
Can I have some context on this? E.g. the reversion and the reopening? I assume a conversation happened on this subject somewhere I was not participating but I really would love to understand what went wrong!

**Comment by cdrini** [comment]
No stress, nothing's gone wrong :) Did you see my comments on #1831 ? In short, this issue has a broader scope. In the spreadsheet above, there are still a number of templates which need to be removed, and there are a bunch of templates which aren't in the spreadsheet at all yet :P

**Comment by cdrini** [comment]
As per the reversion, I didn't follow that too closely. I imagine @mekarpeles might have more information on that?

**Comment by jdlrobson** [comment]
How can we make progress on this?
Is there a tool we can build that will programatically check this?
I think cleaning up this would make a huge difference to the frontend modernization efforts but I am worrying this will stagnate without a plan.

Could we delete templates we think are unused, stress test dev.openlibrary.org and check the logs for example to identify any mistakes?

**Comment by cdrini** [comment]
I'm hoping continuing work on this spreadsheet would help; I don't think there's really an automatic way to do it :/ Note the sheet is outdated and needs some updating.

https://docs.google.com/spreadsheets/d/1pBB0MrcGamn8HqCdnkUd7Mj9VAaVQZ3JQj_osqf3QG0/edit#gid=0

**Comment by jdlrobson** [comment]
Regarding an automatic method - I would suggest adding a counter, that keeps track of all templates being used. Enable that in production for a week, and delete any templates which had no hits.

**Comment by guyjeangilles** [comment]
It looks like this issues is stalled. I'm adding a backlogged and needs assessment label. Let me know if you agree or disagree @cdrini @jdlrobson

**Comment by mekarpeles** [comment]
I am going to close this issue, it's going to inevitably be cleaned up as we move forward w/ cleaning templates and this conversation is way behind master. Thank you for the bump @guyjeangilles
