### ISSUE TITLE
Registration issues

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10035]
### Problem

FYI I just tried to create a new account on OL and got a 504
Now when I go back it says that email address is already taken
I check my email and see an archive.org verification link
I click it and get another error page saying “we’re kinda busy”
I hit refresh and now it says my email is verified.
I go to OL again and now sign in works.

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
The verification error is being worked on by IA staff ; the 504 before that could potentially be on our end, but we haven't been able to verifiably repro, so it might be sporadic.

Next step on this one is to try to repro to see if there are any clues when/if it happens.

**Comment by mekarpeles** [comment]
I think maybe things are working now?

**Comment by mekarpeles** [comment]
It seems like 504 failure is intermittent, possibly due to xauthn and maybe specifically blocked by sendmail time?

This issue can be closed once we have **stats** for how often openlibrary registration fails with 504 and better error messages / handling + possibly reporting when this happens (currently we see a raw 504).

**Comment by mekarpeles** [comment]
When we hit an error with `xauth` request
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L725-L731

Call by this `create` step...
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L668-L677

We should identify the specific 504 case that's occurring here (i.e. xauthn gets stuck on email or something for a long time?) and add some sort of exception that gets raised back to the registration view / handler and shows, e.g.

"Servers are experiencing unusually high traffic, please try again later or email openlibrary@archive.org for help." (verify email)
