### ISSUE TITLE
Add an option to "add a new book" when no results are found on the book search page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10049]
### Proposal

When the books search page has no results. We should show an option to "add a new book"
For example: https://openlibrary.org/search?q=%22institutional+thickness+999%22

This is per @cdrini 's suggestion [here](https://github.com/internetarchive/openlibrary/issues/8891#issuecomment-1992169033)

### Justification

The problem is that when there are no search results we leave the user with nothing to do.
If they're looking for a book and can't find it then we should let them know they can add it.

#### Requirements Checklist

* [ ]

#### Related files

*

#### Stakeholders

* @cdrini 

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by longbui23** [comment]
Hi @RayBB,

I'm Long a group of 5 students in Dickinson who really want to contribute to Open Library. We're really interested in this issue and want to ask whether you could grant us this issue. Looking forward to your guidance. Thank you!

**Comment by RayBB** [comment]
@longbui23 you're assigned now.
Please read the contributing.md (especially watching the technical walkthrough)
Let me know if you have any questions.

Good luck!

**Comment by longbui23** [comment]
Hello @RayBB , we have successfully implemented a feature that allows users to add a new book when no search results are found, as demonstrated in the video. However, we are uncertain whether we should create a template for this button or feature. 

We have thoroughly reviewed all previous files but haven't encountered any similar types of book-adding buttons or features. We would be very grateful if you could advise on the best approach for this functionality.

https://github.com/user-attachments/assets/52081866-c177-4f7d-ae8b-344c73b9eba4

**Comment by RayBB** [comment]
That looks good. A link like that should work. I don't think it needs to be a button since it's not an action only a navigation.

**Comment by cdrini** [comment]
Nice! Let's go with "Add a new book?" as the markup, and let's put it on the same lane with the other text (adding a period!)
