### ISSUE TITLE
Borrowing a book that is only on IA (not on OL) causes errors when viewing my books page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#10047]
### Problem

![image](https://github.com/user-attachments/assets/2bf370fc-bbce-4d5c-8bbf-76dfc162bc4f)

### Reproducing the bug

1. Borrow a book only on IA, eg https://archive.org/details/isbn_9781849352260
2. Try to go to my books

* Expected behavior: My books loads normally
* Actual behavior: My books errors

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by tfmorris** [comment]
Why isn't that scan linked to this work? https://openlibrary.org/works/OL21284005W
