### ISSUE TITLE
Author's search result page has extra blank space under search bar

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10050]
### Problem

We should remove that blank space to make it uniform with the rest of the pages.

https://github.com/user-attachments/assets/52088840-c0d2-4a12-b0d8-7918ec3a2408

### Reproducing the bug

1. Go to https://openlibrary.org/search/authors?q=cory+doctorow
2. See the blank space

It should have less space, like the other pages.

### Context

This is a followup to https://github.com/internetarchive/openlibrary/issues/8891

#### Requirements Checklist
* [ ] There is no blank space, it matches the rest of the pages.

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by QuangPhung15** [comment]
Hi @RayBB. I'm Quang, a member of the Dickinson Seminar Group of five members. We are interested in contributing to this issue, as it would help us start with OpenLibrary and build a solid foundation to tackle the other problems. However, we're fairly new to this, so could you provide some suggestions on which file we should start to look into? I'm looking forward to hearing from you soon. Thank you so much!

**Comment by RayBB** [comment]
@QuangPhung15 and team. 
First, if you haven't already please read the [contributing docs](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md). They are a wonderful resource, especially the technical walk through.

I _think_ the file you will want to look at for this is.
`openlibrary/openlibrary/templates/search/authors.html`

Good luck!
