### ISSUE TITLE
Textarea on generic edit pages should be full width

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#10058]
### Problem

![image](https://github.com/user-attachments/assets/a17e44d7-2fa9-47b2-b58b-682509a7db21)

### Reproducing the bug

1. Login & go to your profile page by clicking the hamburger icon and selecting "My Profile"
2. Click Edit

* Expected behavior: The text area is full width
* Actual behavior: The text area only fills half the screen

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod
 

#### Requirements Checklist
* [ ]

#### Related files

* 

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by lee14334** [comment]
Hi @RayBB, would it be alright if I took up this issue?

**Comment by yunjia1** [comment]
Hi @RayBB, could I help with this issue? It is my first time contributing to open-source so this seems like a great project to start with!

**Comment by RayBB** [comment]
@lee14334 and @yunjia1 can you please both confirm you've read the [CONTRIBUTING.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md) and are ready to start working on this project?

@lee14334 if so, let me know soon and I'll assign you to this issue. 

@yunjia1 as you can see, @lee14334 already asked to work on this, so we will give them a few days to respond. If not, then you can work on it. Feel free to look into the issue and see how you'd do it even if Lee does as it's a great learning opporunity.

Thanks both

**Comment by lee14334** [comment]
Hi @RayBB, I’ve gone through the CONTRIBUTING.md and am ready to take on the issue. Please assign it to me when you can. Thanks for coordinating!

**Comment by RayBB** [comment]
@lee14334 you're assigned now. Good luck!
