### ISSUE TITLE
Cannot leave the waitlist for a book

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10061]
### Problem

Seems I cannot leave a waitlist for this book
https://openlibrary.org/books/OL1732780M/The_Annotated_Charlotte%27s_Web

No idea what's going on here but I don't think I've seen this reported in the things broken anywhere.
CC: @cdrini 

https://github.com/user-attachments/assets/493ba336-7299-477a-a14b-d96cb1ea4e49

### Reproducing the bug

1. Go to the homepage
2. Click join waitlist
3. Click leave waitlist

* Expected behavior: no longer on waitlist
* Actual behavior: still on waitlist

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
Hi @DachiCharkviani, thank you for the offer, I think this issue may be difficult for non-staff to work on as it may require access to APIs that are limited to staff.

**Comment by mekarpeles** [comment]
@jimchamp thinks this one may have gone away?
