### ISSUE TITLE
Waiting list text breaks out of left sidebar

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10060]
### Problem

`You are #21 of 21 on the waiting list.` should probably wrap instead of going outside of that box.

<img width="1085" alt="image" src="https://github.com/user-attachments/assets/e0a174c3-e7a0-40a5-bc36-026512c19ade">

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by ronibhakta1** [comment]
hey @RayBB  can you assign this to me :)

**Comment by RayBB** [comment]
@rohitjain00 you're assigned.
Good luck!

**Comment by ronibhakta1** [comment]
> @rohitjain00 you're assigned. Good luck!

its a different user you have assigned too my username is different

**Comment by ronibhakta1** [comment]
@RayBB can you mention more about the issue exactly where you are facing this issue it would be better !

**Comment by ronibhakta1** [comment]
hey @RayBB  i have fixed the issue :) its mot overlapping now 
<img width="1115" alt="Screenshot 2024-11-23 at 9 05 14 PM" src="https://github.com/user-attachments/assets/005d58d9-18a8-4de5-8285-2d2dd1611472">

**Comment by ronibhakta1** [comment]
@RayBB can you resign me the fix i have updated the new fresh file with no other issues like past and fixed the only thing needed
