### ISSUE TITLE
Archive.org header bar: brand consistency amendments

### ISSUE THREAD

**Issue by psyked** [internetarchive/openlibrary#1008]
_Disclaimer: I couldn't find definitive information on any official "Internet Archive" brand guidelines, so I'm going to make some suggestions based on interpreting the current appearance of content on archive.org and openlibrary.org._

### Proposed design amendments for cross-domain consistency:

* Increase the bar size to to bring the appearance more in line with archive.org:
** Increase the height of the top bar to 50px from the current 39px
** Update the bar padding to be 8px (top/bottom), 13px (left/right)
** Increase the logo dimensions accordingly (36px high instead of 28px)
* Remove the 3px corner radius currently present in the top corners of the banner.
* Remove the existing bottom border (dark beige) on the bar (because it's getting lost, anyway)

### Proposed design tweaks, because it doesn't look great:
* Tweak the baseline of the heart logo on the 'donate' button - the heart icon is currently appearing to high on the line, when compared to the text label

### Proposed content changes, for greater clarity:
* Better identify the 'Internet Archive' as a separate entity or parent brand to 'Open Library', for example with the wording "Part of the [Internet Archive logo]", with the aim of not literally having two different brands in the top left corner of the page.
* Identify that activating the "Internet Archive" or "Donate" links will launch an external domain, either with the external link icon or by introducing tooltips in the same way archive.org uses them.

**Comment by tfmorris** [comment]
Increasing the size of the extraneous bar is going the wrong direction. How about getting rid of the archive.org double header , since the footer already says that OpenLibrary is an Internet Archive property. That way you don't need to deal with the muddled mishmash of brands (and lost space) in the header.

And speaking of the "Donate" link, won't users who want to contribute to OpenLibrary find it confusing that there's not one single mention of it on the landing page?

**Comment by mekarpeles** [comment]
All of these seems like reasonable approaches, including removing the bar.

@bfalling do you have opinions on these feedback?

@tfmorris can you help me understand what you mean by:
> And speaking of the "Donate" link, won't users who want to contribute to OpenLibrary find it confusing that there's not one single mention of it on the landing page?

i.e. there should be some mention to donating / contributing on the landing page?

**Comment by tfmorris** [comment]
@mekarpeles Sorry, "it" == "OpenLibrary" As a potential donor, when I click "Donate" on the OpenLibrary home page, I expect to see something like "Thank you for offering to donate to OpenLibrary. How much would you like to give?" Instead, there's a wall of text that blathers on about Internet Archive without a single mention of Open Library. Even more confusingly, the one thing it *does* mention is the incredibly confusingly named "OpenLibraries" project which is completely unrelated to the decade-old OpenLibrary.

Off the topic of website content, but bonus points for earmarking my contribution to be spent on the thing I think I'm contributing to. As an example, when the Big Red Marching Band solicits me for donations, I can designate my donation to be used for the band, or anywhere in the athletic department, or the university at large.

**Comment by tfmorris** [comment]
This seems straightforward to implement once we make a decision. Does anyone else want to vote which way we go?

**Comment by LeadSongDog** [comment]
I agree with @tfmorris about the confusing landing page: that really should be fixed. However, I'm not sure that the earmarking suggestions will play out well in practice. When creating budgets for different activities in most organizations it leads to a choice: either (a) the earmarked funds are layered over independently allocated levels for each budgeted activity as extra icing on the cake; or (b) the earmark becomes just a guaranteed minimum for that activity, and allocations are adjusted based on the knowledge that those earmarks are already addressing part of the funding needs. In either case the result is unsatisfactory to someone, but at minimum if earmarks are adopted it should be made clear to donors which approach will be in play.

**Comment by guyjeangilles** [comment]
So should we only focus on changing the donation page as this thread suggests?

**Comment by tfmorris** [comment]
@guyjeangilles I would love to see focus on fixing any piece of this, but not sure who your question was directed at.

@mekarpeles is probably the only one who can even lobby for changes in this space.

**Comment by mekarpeles** [comment]
@tfmorris, I have been talking to @bfalling -- in fact, I am going to assign this specific issue to him.

We're discussing a coherent Internet Archive branded topbar across Archive.org + OpenLibrary.org.

@bfalling, do you mind commenting here to confirm you've seen the above feedback?

I am going to close this issue (OL side) as I think IA Product team should be driving this one.

**Comment by bfalling** [comment]
Hey, everyone. Thanks for all the ideas. We're in the process of doing some "tidying" of the top nav on the IA side as well. It's also acknowledged that we're probably soon due for a more complete re-consideration of the IA logo and branding, but that's futureward TBD...

For OL, the question of whether to remove the top IA stripe altogether or really jump in and embrace some aspect of the new IA top nav for clear consistency remains open. We're looking at both. Ultimately, it will be Brewster's (our founder's) call. Stay tuned!
