### ISSUE TITLE
Weird white gap at bottom of preview dialog

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#10095]
### Problem

![image](https://github.com/user-attachments/assets/147d194d-de03-4ee1-aa3d-8f862cff0ae8)

### Reproducing the bug

1. Go to https://openlibrary.org/books/OL4667107M/Die_Angestellten_vor_dem_Nationalsozialismus
2. Click "Preview"

* Expected behavior: The modal should not have a white 
* Actual behavior: It has a white gap

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by DachiCharkviani** [comment]
Hello, can I please work on this issue? I am tasked from college course to successfully contribute to an open source code.

**Comment by cdrini** [comment]
Thank you @DachiCharkviani ! Assigned.

**Comment by RayBB** [comment]
@DachiCharkviani are you still working on this? If so let me know otherwise we'll unassign so someone else can pick it up.

**Comment by Craig-Rosario** [comment]
If no one is working on this issue, I'd like to work on this.

**Comment by RayBB** [comment]
@Craig-Rosario as you can see there is someone assigned to the issue.
However, if we don't hear from the assignee this week I will look at your PR.

**Comment by Craig-Rosario** [comment]
@RayBB Sure, no problem

**Comment by DachiCharkviani** [comment]
@RayBB ,  I am going to raise PR today or tomorrow.

**Comment by DachiCharkviani** [comment]
Hello, I opened a PR for this main branch to merge with the main branch of my forked repo. I believe everything should be working without any issues.

**Comment by Craig-Rosario** [comment]
@DachiCharkviani Sorry, a bit out of track but did you face any issues while changing the CSS properties? they don't seem to update on the localhost, because I am trying to fix other issues but changes in css don't reflect on the website
