### ISSUE TITLE
Is it possible to recover an account?

### ISSUE THREAD

**Issue by edent** [internetarchive/openlibrary#10093]
### Question

How can a user recover an account when OL / AI says the account's email address does not exist?

### Additional context

I have an Open Library account at https://openlibrary.org/people/edent

If I try to log in to OL, I get the error:

> No account was found with this email. Please try again

If I try to recover my password, I get the error

> Open Library Account not linked. Login with your Open Library credentials to connect or create an Archive.org account

If I try to log in to Internet Archive, I get the error

> Email address and/or Password incorrect.

If I try to recover my password on IA, I get the error

>  No user registered with this email address 

### Issue resolution criteria

A user should be able to recover their account. Either by sending a password to the email address associated with an account, or via a manual process.

**Comment by edent** [comment]
The official answer seems to be "Sign up for a new Internet Archive account, but with the same email address as your Open Library account".

This isn't made very clear on the website. And, if the system knows what my account's email address *was* - why can't it send me a password reset?

**Comment by mekarpeles** [comment]
You may want to try with `openlibrary.org` with your email domain. I checked the account on openlibrary.org... @seabelis should be able to help you further!

**Comment by edent** [comment]
I've recovered my OL account by signing up for a new IA account, but with the old email address.

When I did that, it gave me access to my OL account.

I appreciate the cyber attack had an impact on your systems. But it should be made clearer that the only way to recover is to sign up again.

**Comment by edent** [comment]
@seabelis I can access my OL account, but my IA account has been deleted due to "admin error".

Please can you put in place a proper account recovery system for OL?

You needed to know my (old) OL email address to associate my new account. If so, you should have been able to send a recovery link.

**Comment by seabelis** [comment]
I see your archive.org account was recreated and is linked to your Open Library account. I see you have logged into both accounts recently. Please clarify what it is you still need to recover.

**Comment by edent** [comment]
I want to recover my @edent username on archive.org. I had it for several years.

My "recovered" account is now https://archive.org/details/@edent_1

I don't understand how or why my account was removed in the first place. I received no notifications about it. And now I am told that it is impossible for me to recover it - despite having the same email address as the original account.

Please can you let me know how I can get my *original* username ("edent") as my IA username?

**Comment by seabelis** [comment]
This is not an Open Library issue. That archive.org account was deleted and the username cannot be reused as far as I know. You may send an email to info@archive.org if you'd like to follow up.
