### ISSUE TITLE
Update team page JavaScript to prevent XSS

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#10097]
### Problem

The content of our team page is largely generated with JavaScript.  When new elements are constructed for this page, text content is often added by setting the [`innerHTML` property](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML).  This way of creating elements could leave us vulnerable to cross-site scripting attacks (more information [here](https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML#security_considerations)).
 

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc): Any
- OS (Windows, Mac, etc): All
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

### Breakdown

Since none of the text content used to generate the team member cards contains markup, it may be easiest to use `textContent` instead of `innerHTML` when creating the cards.

#### Requirements Checklist
* [ ] In `team.js`, replace all instances of `innerHTML` with `textContent`

#### Related files

* [`team.js`](https://github.com/internetarchive/openlibrary/blob/6224dce456619cbdbe740e40994b707b31f80019/openlibrary/plugins/openlibrary/js/team.js)

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by ronibhakta1** [comment]
> Hey @jimchamp will you assign me the issue i will make the required changes as you have mentioned and get the checks done :)

i'm waiting for your response !!1

**Comment by phoenix7815** [comment]
Hello @jimchamp, I’m new to open source and contributing to projects. I’d be glad to get started as soon as you assign me this issue. Thank you!

**Comment by prasad14070** [comment]
Hello @jimchamp , we had discussion on slack as well, I would like to contribute on this issue , it would be great if you assign this to me.  I’ll ensure that the usage of `textContent` is correctly implemented and tested. Thank you!

**Comment by yrpatel24** [comment]
Hi @jimchamp! I am looking to contribute to this issue as well. If no one is currently working on it I can help!

**Comment by jimchamp** [comment]
Go for it @ronibhakta1!
