### ISSUE TITLE
Clear searchbar when we tab off of the search bar input

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10103]
### Problem

Follow up to https://github.com/internetarchive/openlibrary/pull/9845#pullrequestreview-2465501109

https://github.com/user-attachments/assets/261e3bb7-e080-4418-aeb7-b5baccffb7af

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by DachiCharkviani** [comment]
Hello @RayBB . Could you please consider assigning me to the next issue you raise please? I have a college assignment to contribute to open source projects on open issues. I have already been assigned to one of the issues which I am working on. I need on more. I am enjoying this project and would gladly contribute a solution on one more issue in this project. I already have everything, development mode replicated locally and explored, set up to work on.

**Comment by RayBB** [comment]
@DachiCharkviani I cannot assign you to an issue you haven't commented on. GitHub will not allow it. Please feel free to open a new issue if you find a problem and you can be assigned to that. 
Perhaps you can do this one. Please read all the comments carefully. https://github.com/internetarchive/openlibrary/issues/8929
