### ISSUE TITLE
[Reopened] Openlibrary.org website is down

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#10102]
### Problem

The openlibrary.org website is down.

![OL](https://github.com/user-attachments/assets/9d8b4717-f8cd-4f3a-8489-427b979eebe8)

### Reproducing the bug

1. Go to any https://openlibrary.org URL.
2. The following message is displayed;
`{"error": "internal_error", "message": "get_site(openlibrary.org) failed"}`

Thank you for looking into this bug.

### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome
- OS (Windows, Mac, etc): Android
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by el4ctr0n** [comment]
The website is now back up.

**Comment by el4ctr0n** [comment]
Unfortunately, this bug has returned.
Openlibrary.org is down again.

**Comment by cdrini** [comment]
Resolved; we'll be spending some time this week to work on a longer term fix which should hopefully prevent this from happening again. Apologies for the disruption!
