### ISSUE TITLE
xhtml pages break due to injected banner

### ISSUE THREAD

**Issue by emilio** [internetarchive/openlibrary#10108]
### Problem

https://web.archive.org/web/20150103001137/http://quotes.burntelectrons.org/browse?start=30 shows an error like:

```
XML Parsing Error: not well-formed
Location: https://web.archive.org/web/20150103001137/http://quotes.burntelectrons.org/browse?start=30
Line Number 148, Column 15:
	  <img align=right src="http://archiveteam.org/images/e/e6/Archiveteam.jpg" width=200> Formed in 2009, the Archive Team (not to be confused with the archive.org Archive-It Team) is a rogue archivist collective dedicated to saving copies of rapidly dying or deleted websites for the sake of history and digital heritage. The group is 100% composed of volunteers and interested parties, and has expanded into a large amount of related projects for saving online and digital history.
---------------------^
```

Note the missing quotes in the align attribute and width attribute (also missing slash) that would make that valid xhtml.

It seems the archive should either not inject the banner on xhtml pages, or should inject valid xhtml.

I'd be happy to fix this if pointed to the relevant code, but I couldn't find it from a quick grep :)

### Reproducing the bug

1. Go to https://web.archive.org/web/20150103001137/http://quotes.burntelectrons.org/browse?start=30
2. Stare at an error message.

* Expected behavior: An archived website.
* Actual behavior: An error.

### Context

- Browser (Chrome, Safari, Firefox, etc): All
- OS (Windows, Mac, etc): All
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by ronibhakta1** [comment]
hey @emilio i can go through the issues as you mentioned and update you as soon i finish

**Comment by mekarpeles** [comment]
I believe this issue is for team Wayback and not Open Library, cc: @ibnesayeed
