### ISSUE TITLE
Page numbers broken for TOC with only one pipe per line

### ISSUE THREAD

**Issue by zorae** [internetarchive/openlibrary#10120]
### Problem

When saving a TOC with only a single pipe character per line, an additional pipe is always appended to the line. This results in page numbers being rendered incorrectly.

When a book’s table of contents only contains chapter titles and page numbers, the obvious way to input these on OL is as follows:
```
Welcome | 7 
The German Working Group on Stately Homes and Gardens | 9 
Historical rooms as works of art | 10 
```

### Current behaviour
Upon saving, OL appends an additional pipe character at the end of each line, resulting in the following format:
```
Welcome | 7 | 
The German Working Group on Stately Homes and Gardens | 9 | 
Historical rooms as works of art | 10 | 
```

The resulting table of contents is rendered with only a dot between each chapter title and page number:

> Welcome. 7
The German Working Group on Stately Homes and Gardens. 9
Historical rooms as works of art. 10

### Desired behaviour
Instead, OL should either be able to handle lines with a single pipe, or recognise the page number and insert the pipe in front of it:
```
Welcome | | 7 
The German Working Group on Stately Homes and Gardens | | 9 
Historical rooms as works of art | | 10 
```

In any case, the resulting ToC should be rendered approximately like this:

> Welcome ………………………………………………………………………………. Page 7
The German Working Group on Stately Homes and Gardens … Page 9
Historical rooms as works of art ……………………………………………. Page 10

### Context

- Browser (Chrome, Safari, Firefox, etc): Safari
- OS (Windows, Mac, etc): iPad
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by DachiCharkviani** [comment]
Hello, I would like to work on this issue please.

**Comment by cdrini** [comment]
The correct form of the table of contents should be:

```
| Welcome | 7
| The German Working Group on Stately Homes and Gardens | 9
| Historical rooms as works of art | 10
```

I.e. 
```
LABEL? | TITLE | PAGENUM
```

E.g.
```
Chapter 1 | Welcome to Narnia! | 2
```

Apologies this format is quite finnicky ! We want to create a proper UI for it at some point so librarians don't have to deal with the raw format directly. Closing this as unplanned as a result, since trying to come up with a special case here would make the code difficult to maintain, and could cause issues on other parts of the code that rely on the old fallback, where 1 pipe is interpreted as `LABEL | TITLE`. Let us know if adding the extra pipe does the trick!

**Comment by zorae** [comment]
Okay, I can see your point. Yeah, it does work if you add the pipe character at the beginning of the line.
