### ISSUE TITLE
Don't import Createspace published items

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#10128]
### Problem

Createspace is = to "independently published" in that it's almost all low-quality, print on demand, public domain works. 

Example of a very recent import (one of many) that not only should not have been imported, but was imported to the wrong author (one of many in that bunch). https://openlibrary.org/books/OL56192651M/Rise_of_Silas_Lapham
<img width="1114" alt="Screenshot 2024-12-06 at 19 13 45" src="https://github.com/user-attachments/assets/2da05228-d119-4158-872e-b8fa6fbab598">

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by DebbieSan** [comment]
Hi everyone, I would like to tackle this one if possible. TIA :)
