### ISSUE TITLE
Profile page 

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#10133]
The current profile page looks a bit dull. It would be nice to have it look a bit more like the author page with optional picture, maybe links to other profile pages on wikipedia, wikidata, social media like mastodon on the right side like the IDs on an author page. In the main field could be the description as is followed by a selected books, lists and collections area.

**Comment by mekarpeles** [comment]
We've had these discussions before, for now I am closing.

I think the general idea is to consolidate the /profile and my books page(s). Perhaps we keep the profile page as a the edit / backend for My Books, but moving forward we'll likely have e.g. 
https://openlibrary.org/people/mekBot redirect to https://openlibrary.org/people/mekBot/books

and **also** to enhance https://openlibrary.org/people/mekBot/books with also a summary of friends' activity feed from the friends that patron follows.
