### ISSUE TITLE
Added Book IDs on new books aren't set

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#10148]
### Problem

/books/add dialogue does not set the given IDs for the next form.

![image](https://github.com/user-attachments/assets/307a1a49-5227-4d12-a90a-38b61138341b)

One can set one ID in the first add book dialogue, which is lost in the next dialogue and has to be set again. 

### Reproducing the bug

1. add new book from existing one, author page or the general dialogue
2. fill out every field
3. fill out any ID
4. save
5. check IDs

* Expected behavior: given ID is carried on
* Actual behavior: but it isn't

### Context

- Browser (Chrome, Safari, Firefox, etc): Firefox
- OS (Windows, Mac, etc): macOS
- Logged in (Y/N): y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by SharkyBytes** [comment]
Hello @bitnapper & @mekarpeles! 
I’d love to work on fixing this and ensure that the entered ID is properly carried over as expected. Could you please assign this issue to me?

**Comment by mekarpeles** [comment]
I wasn't sure whether to make P2 or P3 -- @SharkyBytes if you don't mind doing some investigation and looping in @scottbarnes I think we'd both appreciate that as a first step, thank you!

**Comment by SharkyBytes** [comment]
Thank you, @mekarpeles! I'll start investigating the issue and loop in @scottbarnes for further insights or clarifications as needed. I'll focus on replicating the bug consistently and identifying where the form logic might be breaking. Once I have some findings, I’ll share them here before proceeding with the fix.

Also, I had filled out the volunteer form but haven’t received the Slack invitation email yet. Could you help me connect with the Slack community or point me in the right direction to resolve this? I’d really appreciate it!

If there's any additional context or pointers you'd like to highlight, please let me know!

**Comment by SharkyBytes** [comment]
Hey @bitnapper! Are you referring to these changes specifically? If so, they are already implemented and let me know are they correct?

![image](https://github.com/user-attachments/assets/0696f9f7-12fc-476a-b032-f5db3c60b801)
![image](https://github.com/user-attachments/assets/019aabaa-3403-443d-9e5d-cd76464b2711)

**Comment by bitnapper** [comment]
Yes, I mean exactly that dialogue. It seems to work with isbn13 but not with Internet-Archive-ID.

**Comment by SharkyBytes** [comment]
Thanks for pointing that out @bitnapper! It seems that the "Internet Archive ID" field is visible in the admin and developer instances, but it's missing in the user portal. Although the dialog box for the field exists, it's not appearing for regular users.

User portal
![image](https://github.com/user-attachments/assets/5f9fe37a-f251-445f-965f-fb6d09ed1b45)

Admin Portal
![image](https://github.com/user-attachments/assets/bb693f7d-3c4c-4fe4-8e22-986bc7ed884c)
![image](https://github.com/user-attachments/assets/01c1c3a5-e1d9-4873-8530-71f05e710bfb)

**Comment by bitnapper** [comment]
Thanks, @SharkyBytes. I wasn't aware, that it's only visible to some users. It would be nice if it could be fixed.

**Comment by seabelis** [comment]
The visibility is not an error. Only accounts with permissions can edit that field.

**Comment by SharkyBytes** [comment]
Hey @mekarpeles @scottbarnes @bitnapper,

I have resolved the issue from the code, but I’m facing a new problem. Whenever I try to log in using my personal details on Open Library, it redirects me to the Open Library account. Can anyone please help me understand how to log in with my personal account on localhost? I’m new to Open Library and not connected to any community yet so it is difficult for me

**Comment by SharkyBytes** [comment]
Thank you, team, for all your help. The issue has been completely resolved, and I’m now able to add new users successfully. Special thanks to @scottbarnes for referring the document on adding new users—I tested it with my test username, and everything is working perfectly. The dialogue box is also appearing as expected.

Is there anything else you'd like me to address or resolve, @bitnapper @scottbarnes? Once everything looks good, I will raise the PR for this.

Regarding the Slack invite, I understand you’ve escalated it to @mekarpeles. Can you confirm if that will be handled soon? Appreciate it!

![image](https://github.com/user-attachments/assets/264a90e4-4d73-495b-a02d-d7e615626f20)
![image](https://github.com/user-attachments/assets/5163ff9d-4270-497e-89bb-ebe4b0b4f8bf)

**Comment by scottbarnes** [comment]
@SharkyBytes, looks good so far. :)

I'd say go ahead and raise a PR and we can go from there.

As for the Slack invite, you should hopefully have it in your email as of around 8 or 9 hours ago.

**Comment by bitnapper** [comment]
Cool, thank you @SharkyBytes

**Comment by scottbarnes** [comment]
@bitnapper, I was just trying to replicate this issue, and I have a follow up question. If "Internet Archive" is _still_ selected as the ID once you click "Add", does the ID show up in the new book?

I ask because I noticed that when I was entering an Internet Archive ID and then clicking away, the dropdown would change back to "Select", so nothing would be selected when I clicked "Add". When this happens, the Internet Archive ID does not show up in the new book. If I first re-select Internet Archive as the ID, the ID shows up in the new book.

I am not sure of all the ways to cause this 'reset', but for me if I do the following, it reliably occurs:
- Start from the "And optionally, an ID number -- like an ISBN -- would be helpful..." boxes being empty.
- Select "Internet Archive" for the ID type from the dropdown.
- Enter an Internet Archive ID in the box to the right.
- Click somewhere else, in another box, and the menu where I had selected "Internet Archive" goes back to "Select".

This behavior appears to happen with every ID. :( 


![image](https://github.com/user-attachments/assets/ba076d05-6e76-424d-ba63-43ca128d4ced)

**Comment by SharkyBytes** [comment]
Hey @bitnapper @scottbarnes @mekarpeles,

I’ve updated my PR #10195 and applied the changes in the JS as well to persist the Book IDs. Now, if anyone enters the id_value, the id_name will no longer reset to "Select."

Please let me know if I missed anything or if you need me to commit anything else in this PR. Thanks again to @scottbarnes for the issue clarification!
