### ISSUE TITLE
Issue w/ Koha & Bookcovers

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1014]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=21001

> Owen Leonard 2018-06-26 16:31:07 UTC
OpenLibrary book covers don't appear on the search results or detail page in the OPAC. The console shows an error, "SyntaxError: missing ) after argument list books:1:16246"

> Jonathan Druart 2018-06-27 13:55:06 UTC
I suspect a bug on their side:
The answer of:
`https://openlibrary.org/api/books?bibkeys=ISBN%3A067002662X%2CISBN%3A1847727808%2CISBN%3A1780335792&callback=KOHA.OpenLibrary.olCallBack&jscmd=data` is:
`KOHA.OpenLibrary.olCallBack(KOHA.OpenLibrary.olCallBack({"ISBN:067002662X": {"publish_date": "2013", [SKIP]`

**Comment by mekarpeles** [comment]
> It seems that the callback function is duplicated in the answer.

**Comment by mekarpeles** [comment]
The code which serves this endpoint is https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/books/code.py

**Comment by brevilo** [comment]
We're experiencing this as well. So if you guys need someone for testing, let me know...

**Comment by brevilo** [comment]
FYI: adding "format=json" as additional query parameter resolves the problem but I still think that the new behavior is a regression caused by c1e1803e3.

**Comment by hornc** [comment]
Trying to figure out the correct behaviour here, I think the problem behaviour
https://openlibrary.org/api/books?callback=foo
which currently returns: `foo(foo({}););`
should actually produce `foo({});`  to give the simplest illustration of what is wrong.

The Koha bug report gives this real example: https://openlibrary.org/api/books?bibkeys=ISBN%3A067002662X%2CISBN%3A1847727808%2CISBN%3A1780335792&callback=KOHA.OpenLibrary.olCallBack&jscmd=data

**Comment by hornc** [comment]
@mekarpeles is the fix here to reinstate `web.header('Content-Type', 'text/javascript')` if there is a `callback`  param? (not 100% sure of the intent behind the c1e1803 changes, but I can see  + agree how this broke)

**Comment by hornc** [comment]
@brevilo I have made a fix for this issue and it is live now, can you please test and let me know if there is anything else that needs changing?

The example URL https://openlibrary.org/api/books?bibkeys=ISBN%3A067002662X%2CISBN%3A1847727808%2CISBN%3A1780335792&callback=KOHA.OpenLibrary.olCallBack&jscmd=data now returns a single
`KOHA.OpenLibrary.olCallBack({ ... });`

**Comment by brevilo** [comment]
Thanks @hornc, I can confirm that your fix works for me. Nice one!
