### ISSUE TITLE
Google login fails

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#10166]
### Problem

Patrons who try to login with Google get the error, “we cannot verify your account. You may try again.”

### Reproducing the bug

1. Go to ... https://openlibrary.org/account/login
2. Do ... try to login with using the Google login button

* Expected behavior: login achieved
* Actual behavior: login fails with “we cannot verify your account. You may try again.”

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
This has to do with CSP changes on archive.org

![image](https://github.com/user-attachments/assets/74365d62-3d1f-46bd-b7b8-99a55652e605)
![image](https://github.com/user-attachments/assets/1a505371-47fd-46da-bd89-d200587854a2)

See (internal) PR:
https://git.archive.org/ia/petabox/-/merge_requests/4771

**Comment by 5usu** [comment]
I couldn't recreate this issue on my end. It works fine on my end.

**Comment by mekarpeles** [comment]
> I couldn't recreate this issue on my end. It works fine on my end.

@5usu confirmed this has been fixed upstream, thank you!
