### ISSUE TITLE
Remove unused `pytest` fixtures

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#10161]
### Proposal

It looks like there are some unused fixtures in [`openlibrary/tests/core/conftest.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/core/conftest.py).  Let's determine which, if any, of these fixtures are unused, and remove them.

### Justification

Some of these fixtures use deprecated functions that will need to be updated if the fixture is actively used by our tests.  It's better to remove the fixture altogether than it is to update the deprecated function if the fixture is unused.

#### Requirements Checklist

* [ ] All unused fixtures in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/core/conftest.py are removed
* [ ] No new test failures (expected or otherwise)

#### Related files

* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/core/conftest.py

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Spaarsh** [comment]
@jimchamp I am interested in working on this issue!
