### ISSUE TITLE
Make the ruff pre-commit hook fix issues when possible

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10181]
### Proposal

```
scripts/expire_accounts.py:1:1: I001 [*] Import block is un-sorted or un-formatted
  |
1 | / from datetime import datetime, UTC
2 | | import web
3 | | 
4 | | 
5 | | def delete_old_links():
  | |_^ I001
6 |       for doc in web.ctx.site.store.values(type="account-link"):
7 |           expiry_date = datetime.strptime(doc["expires_on"], "%Y-%m-%dT%H:%M:%S.%f")
  |
  = help: Organize imports

Found 1 error.
[*] 1 fixable with the `--fix` option.
```

> Can we add the --fix option to our import linting rule to fix some common errors?

~ Mek (in a Slack DM)

#### Requirements Checklist

* [ ]

#### Related files

*

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by drona-gyawali** [comment]
Yes, we successfully added and utilized the `--fix` option to address common linting errors. Initially, the imports in `scripts/expire_accounts.py` were flagged as unorganized. We configured `ruff` properly in `pyproject.toml` by using `[tool.ruff.lint]` for lint-specific rules. Afterward, we ran:

```bash
ruff check --fix scripts/expire_accounts.py
```

This resolved the issue by automatically organizing the imports. Additionally, we ensured the linting configurations in `pyproject.toml` followed best practices for clarity and maintainability.

This approach ensures smoother development workflows by reducing manual fixes and maintaining code quality consistently.
![Screenshot 2024-12-23 165037](https://github.com/user-attachments/assets/c4037067-ad76-4adb-aa63-f3ffd65a5326)
