### ISSUE TITLE
Change "report a problem" footer link to "contact us"

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#10200]
### Problem

Sometimes patrons want to contact us, but not about a problem. Please change the wording of the link to include non-problematic correspondence.

<img width="208" alt="Screenshot 2024-12-24 at 17 13 34" src="https://github.com/user-attachments/assets/749266ed-3a24-4e5f-82fb-544c0287f2cc" />

#### Related files

https://github.com/internetarchive/openlibrary/blob/4bc59c8306a0417218c7516672cd6b50a6277e1f/openlibrary/templates/lib/nav_foot.html#L43

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by SharkyBytes** [comment]
Hey @seabelis , @mekarpeles!

I’d like to work on this issue. My plan is as follows:

->Update the footer text from "Report a problem" to "Contact us" to broaden its scope.
->Ensure the link redirects correctly to the contact page without breaking functionality.
->Update any related tests or documentation referencing the old text.

Could you please assign this issue to me?

**Comment by MillerJ20** [comment]
Should the title also be changed to be less problematic? it is currently "Problems", would something like "Contact" make sense for a replacement and then "Contact us" to replace "Report a problem"?

**Comment by seabelis** [comment]
Yes, that makes sense. Thank you.

**Comment by Craig-Rosario** [comment]
I have a suggestion regarding the "**Report a problem**" link, another link could be created, named "**Contact us**" which leads us to this page: https://openlibrary.org/help

![image](https://github.com/user-attachments/assets/ed3a1109-9eb2-4661-97fc-9d6dcd33cf31)

This approach would preserve both functionalities, patrons can Report a problem and Contact us, without creating confusion.

If no one is currently working on this, I'd be happy to take up this issue.

**Comment by seabelis** [comment]
A second link is not needed. Please just update the wording for now. I see there is outdated content on the other page.

**Comment by Craig-Rosario** [comment]
Sure, I'll update the wording then.

**Comment by Craig-Rosario** [comment]
Also should I change the title from 'Problems' to 'Contact' as suggested above?
