### ISSUE TITLE
BUG: Entering an ID Number Causes Clearing of ID Selections in Add-Book Form 

### ISSUE THREAD

**Issue by SharkyBytes** [internetarchive/openlibrary#10203]
### Problem

This issue is a follow-up to #10148, raised by @scottbarnes. It addresses the behavior where selections in the Add-Book form are cleared when an value is entered in the id_value input field.

### Reproducing the bug

1. Go to ...
-> Open the Add-Book form.
-> Enter an invalid identifier value for ISBN-10, ISBN-13, or LCCN.
-> Observe that the `id_name` field is cleared.

* Expected behavior:
The selected ID should be preserved in the dropdown after entering the input, to avoid multiple clicks for selecting the ID again.
![image](https://github.com/user-attachments/assets/6fac2c92-7e90-43d6-9547-90207a3ae492)

* Actual behavior:
The dropdown resets to the "select" option when you press Enter or move to any other field.
![image](https://github.com/user-attachments/assets/0daf0abe-e4cc-45a3-ae23-9c406c46d4df)

When you enter the input, the dropdown reverts to the default "select" option. 
![image](https://github.com/user-attachments/assets/aaad4ab5-4cbe-4d10-9b00-9bf8e662fe35)

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

* @scottbarnes 
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by SharkyBytes** [comment]
I’m currently working on a PR to address this behavior, and I’ll be raising it shortly. I’ll ensure the dropdown selection is preserved as expected to prevent the need for multiple clicks when entering an ID value.

**Comment by scottbarnes** [comment]
I _think_ this may be the issue raised by #10148, at least as I understand that issue.

**Comment by SharkyBytes** [comment]
Solved this issue in #10148, so closing it here. :)
