### ISSUE TITLE
Stop Showing Pagination Buttons When There is only one page

### ISSUE THREAD

**Issue by SharkyBytes** [internetarchive/openlibrary#10210]
### Problem

This issue of hiding the pager when there is only one page was proposed by @RayBB. I am raising the issue on his behalf.

I also believe that if certain buttons are unclickable, we should stop giving false indications to users. For example, when we are already on first page, there's no use in showing the 'First' and 'Previous' buttons, as they serve no purpose. It's better to avoid showing these buttons.

What do you think about this, @RayBB, @mekarpeles?

![image](https://github.com/user-attachments/assets/28071faf-66e3-4427-8c30-d252ce67d28f)

### Reproducing the bug

1. Go to ... Any of the Author's works -> View all Editions (https://openlibrary.org/works/OL20929W/The_Spanish_gypsy?mode=all)

* Expected behavior:

![image](https://github.com/user-attachments/assets/b2a6bfff-b1ad-4732-a223-ca9b8bb9e093)
![image](https://github.com/user-attachments/assets/d13248fe-e783-4095-a1ef-720b7e164314)
![image](https://github.com/user-attachments/assets/e7f29f50-f4ad-4759-af55-028a3faf37fe)

* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

* [Related Slack discussion](https://internetarchive.slack.com/archives/C0ETZV72L/p1734830635395769) 

#### Stakeholders

* @RayBB
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by RayBB** [comment]
@SharkyBytes this looks good. I assigned you and you can go ahead and work on it.

**Comment by SharkyBytes** [comment]
Hi @RayBB and @mekarpeles,

I’ve implemented the fix you mentioned, Ray, and I wanted to share some updates along with a suggestion I’ve worked on. I’ve addressed the issue as per your request, but I also made an additional improvement that I believe aligns with how pagination is handled elsewhere in the application (e.g., on the [Trending page Video](https://drive.google.com/file/d/1QydjHCRD30zBYtlNQajgm9E1jRPFrsBr/view?usp=sharing)).

To give you a clear view, I’ve recorded two versions for comparison:

->The implementation based on your suggestion
Here’s the version with the fix you asked for:
[Video Link](https://drive.google.com/file/d/1zcd4wHNtJsRGHVsIM0jjDzbkhn5gyywY/view?usp=sharing)

->The version with my additional suggestion
In this version, I’ve implemented your fix as well as a behavior where navigation buttons (e.g., "Previous" and "First") are hidden when they aren’t needed on the first page, and similarly, "Next" and "Last" are hidden on the last page. This approach is consistent with how pagination works on the trending page.
[Video Link](https://drive.google.com/file/d/1j7NO4wmfB50fb1vuxv98ed32kDkBoK3U/view?usp=sharing)

Could you please have a look and let me know your thoughts? I’d love to hear your feedback on both implementations and understand which one you feel works best.
