### ISSUE TITLE
Improve wording around adding book descriptions

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10214]
### Problem

Here's the current way things work if there is no work or edition description:
- On the [work page](https://openlibrary.org/works/OL20929W/The_Spanish_gypsy?mode=all), it says "This edition doesn't have a description yet. Can you add one?" and then links you to the work description edit form
- On the [edition page](https://openlibrary.org/books/OL6684484M/The_Spanish_gypsy) it says the same thing but still links you to the work description edit form.

At a bare minimum I think we should change it so:
- The work page says "This work doesn't have..." (keep linking to the work description)
- The edition page says "This edition doesn't have..." (as it already does) but link to the edition description edit field.

Edit: I now realize that the work/edition view templates are symlinked. So that complicates things a tad.

[Slack discussion](https://internetarchive.slack.com/archives/C0ETZV72L/p1734830515052499)

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by prasad14070** [comment]
@RayBB can I work on this issue or if you are working can we collaborate.

**Comment by RayBB** [comment]
As you can see there is already an open PR and the issue is assigned to me. Please read issues fully before asking to work on them.
