### ISSUE TITLE
Fix the subject search

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#103]
Search results for pages like this are confusing, and seem wrong.

http://openlibrary.org/search/subjects?q=london&search=

Some results should be collapsed when there are capitalization differences, like:
- London   10,518 books, place
- london   10,483 books, place
- LONDON   10,465 books, place
&
- London   268 books, subject
- london   239 books, subject

It would be ideal if there was time to do some clean-up of extraneous characters, like:
- London,   9,407 books, place
or
- Jack London (1876-1916,)   170 books, person
- Jack London (1876-1916)   170 books, person

It's just, well, broken at the moment. Let's make it awesome!

Also, why is there the "&search=" at the end of the URL?

**Comment by hornc** [comment]
I believe capitalisation differences are no longer an issue in the subject search results. PR #300 addresses the `&search=` at the end of the URL though.

Once that is merged I think this issue can be closed.
