### ISSUE TITLE
Remove residual `number_of_editions` references

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#1041]
Looks like there are some dead merging code: https://github.com/internetarchive/openlibrary/search?q=number_of_editions&unscoped_q=number_of_editions

**Comment by guyjeangilles** [comment]
@cdrini Assigning you per our slack discussion since it seems you're leading the refactoring code charge.

**Comment by cdrini** [comment]
Cannot find `number_of_editions` anywhere in the code. It is in the dev pg dump in some places though, but that's probably fine.
