### ISSUE TITLE
Duplicate + Invalid ocaids (i.e. archive.org IDs) on OL Editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1045]
@hornc + @mekarpeles let's come up with a document which details which commands to use in order to evaluate how many duplicates or bad `ocaid`s are in Open Library `edition`s.

My understanding is as of 2018-07 we had ~65k duplicate / bad `ocaid`s on OL

**Comment by hornc** [comment]
Commands to get full list of OCAIDs from Open Library monthly edition dump:
`sed -n 's/^.*"ocaid": "\([^"]*\)".*$/\1/p' /storage/openlibrary/ol_dump_editions_2019-03-31.txt | sort > all-ocaids-2019-03-31.lst`

Total for March 2019: 2925159

Count the duplicates:
`uniq -d all-ocaids-2019-03-31.lst | wc -l`
65803

Some commands for identifying bad OCAIDs from the dumps:

```
#empty ocaids:
egrep '"ocaid": ""' /storage/openlibrary/ol_dump_editions_2019-03-31.txt
```

```
#Invalid initial characters, including spaces, tabs, and slashes which can often be removed to produce valid ocaids:
egrep '"ocaid": "[^0-9a-zA-Z]' /storage/openlibrary/ol_dump_editions_2019-03-31.txt
```

Some items have `ISBN` or variants in the ocaid field, others have ark numbers: e.g. ark:/13960/t64520w6q on OL26399099M

```
# find anything with a space or semicolon in the ocaid

```

**Comment by hornc** [comment]
some remaining ol items have multiple source ia records, which seems valid: e.g.
https://openlibrary.org/books/OL4947315M.json

Unfortunately the single `ocaid` is for a non-borrowable copy. Next step, do an audit of ol items with multiple ia source records and ensure the 'best' copy is linked from the item.

**Comment by hornc** [comment]
Update for the data dumps @ 2019-05-31
`sed -n 's/^.*"ocaid": "\([^"]*\)".*$/\1/p' /storage/openlibrary/ol_dump_editions_2019-05-31.txt | sort > all-ocaids-2019-05-31.lst`

`uniq -d all-ocaids-2019-05-31.lst | wc -l`

**Comment by tfmorris** [comment]
What was the result?

**Comment by hornc** [comment]
65825 duplicates -- unfortunately that has _increased_ slightly

**Comment by guyjeangilles** [comment]
Was the purpose of this issue to determine a way to find duplicate ocaids or a way to _remove_ ocaids? If it's the former, I'm proposing we close this issue. @mekarpeles @hornc @tfmorris Let me know if you agree or disagree.

**Comment by tfmorris** [comment]
I'll defer to @mekarpeles since it was his issue. As literally stated, it's probably complete, but I think we create a ticket to fix the bad ids before closing this, if this ticket isn't going to cover that part.

**Comment by guyjeangilles** [comment]
Perhaps we rename the ticket to specifically remove these duplicate ocaids to keep the context.
