### ISSUE TITLE
Merge orphaned editions w/ duplicate un-orphaned editions sharing same ISBN 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1048]
We have thousands of orphaned editions in Open Library (maybe that were added by some import bot) which have duplicate existing un-orphaned editions (i.e. they belong to works) with the same ISBN.

## Solution

For now, we are not going to merge the editions, but instead to move the orphaned edition into the work (so the work will unfortunately for now have 2 editions with the same ISBN)

**Comment by hornc** [comment]
Depends on https://github.com/internetarchive/openlibrary/issues/893 so the merging of these items is reflected in search results.

**Comment by tfmorris** [comment]
What would be the downside of merging the editions if there are identical?

**Comment by hornc** [comment]
If they are identical in terms of 'identical metadata' it is fine and easy, but there are many examples where the metadata differs and it is hard to determine the best merge result without losing or duplicating fields. Fixing orphans was stalling on finding a perfect merge algorithm, and merging is hard to fully automate. It should probably be handled by providing tools and UI to enable fast human review + merge as a separate problem to solve.

**Comment by hornc** [comment]
Works are easier to merge because they in general have less complex metadata, and are more likely to be identical. My thoughts were that if all duplicate editions were at least collected under one work they will be easier to identify later as duplicates, so merging works is something we can do now to improve the data, with less chances of making mistakes or losing data.

**Comment by hornc** [comment]
I have identified 666,474 orphaned editions with ISBNs that are duplicates of ISBNs on other records, and am running through and linking the set that look like good matches.


Amazon sourced ISBNs less than 9780000004000 tend to be either non books, or have garbled data.

After 9780000005000 there is a run of Ordinance Survey maps, which look legitimate, even if the ISBNs are somehow incorrect, and a number of HarperCollins Publishers items from 1979 / 80s which also may or may not be correct, but at least they are recognisable books with seemingly consistent metadata.

**Comment by seabelis** [comment]
Amazon data is questionable in general. I think they have a lot of ISBNs that were never actually issued, ISBNs that are for retail use only, general merchandise, etc. 

As far as duplicates go, ISBN alone is not perfect. Publishers reuse them so there can be multiple editions sharing an ISBN. ISBN + OCLC would be much better, but of course, most records do not have OCLC #s. 

Is it possible to look at the original source for duplicates? There are a number of records I've come across that are imported from the same source as if the same batch was imported twice. These are usually library imports. These are sure duplicates, but maybe a drop in the bucket compared to the whole. I will see if I can find some examples.

**Comment by LeadSongDog** [comment]
@hornc @seabelis @tfmorris 
Just a thought: perhaps it would be useful (at least as an interim measure) to show "Related:" links from edition pages to other editions sharing the same identifiers.

**Comment by seabelis** [comment]
Hmmm. What was the bot thinking here? https://openlibrary.org/works/OL19686422W/Tales_of_horror_and_suspense

**Comment by cdrini** [comment]
@seabelis Created a new issue for that: https://github.com/internetarchive/openlibrary/issues/1048

**Comment by seabelis** [comment]
I think it's #2304 .

**Comment by cdrini** [comment]
Whoops! :P Fixed.

**Comment by LeadSongDog** [comment]
@hornc @cdrini 
Can someone explain why
https://openlibrary.org/books/OL7318605M/Understanding_Power?m=history
and
https://openlibrary.org/books/OL9273260M/Understanding_Power?m=history
still both exist?
As far as I can tell, the only difference is that one shows "The physical object" size and weight whilst the other does not. Both were created by the same sequence of bots, making six edits on closely parallel timelines, starting from the same amazon source record. Should not at least one of these bot edits caught and somehow noted the duplication?

**Comment by tfmorris** [comment]
The bug was creating the 2nd [OL record ](https://openlibrary.org/books/OL9273260M.json?v=1) from the same Amazon record, but that was back in 2008. I wouldn't expect any of the other bots to clean it up unless they were specifically looking for items to merge. That's a separate task from other types of cleanups.

**Comment by hornc** [comment]
Using the dump for 2020 Jan 31 there are only **7631** duplicate ISBNs of orphaned editions that can be matched to non-orphans. I'll run a pass that collects the work for each of the isbns, and associate the orphans.

**Comment by LeadSongDog** [comment]
@hornc 
Does that include a check for isbn10 on one vs isbn13 on the other, that is, just the 9 significant digits?

**Comment by cdrini** [comment]
@hornc Would you be able to attach a csv of editions with conflated isbns? That might let someone else take the torch if they're interested.

**Comment by hornc** [comment]
I recently resolved 8385 orphaned editions by ISBN from the following data file: 
[orphans-resolved.txt](https://github.com/internetarchive/openlibrary/files/4916564/orphans-resolved.txt)

That should be the last of these. :crossed_fingers:
