### ISSUE TITLE
'Favorite' UX - Icon color, notification modal display, unfavorite feature

### ISSUE THREAD

**Issue by whns** [internetarchive/openlibrary#1052]
A few suggestions/potential issues around the handling of Favorites:

1. The collection view should change the Favorite icon color from black to yellow when a collection is favorited, like the item view does. Maybe the label should change from "Favorite" to "Favorited" as well.

2. Is the notification modal needed? If so, ideally it would only be displayed when an item or collection has been favorited, not each time the link is pressed. The "Favorited" text and star icon displayed in the body of the Favorite notification modal are misaligned. The icon could also use some padding between it and the bottom of the modal.

3. If the current item or collection has already been favorited by the user, clicking the favorite link could remove the item from list of favorites (unfavorite).

4. Not sure if there's a compelling reason for this, but it seems a little strange to me that a user can favorite their own favorites collection.

I'll look into contributing these, but at least wanted to share my thoughts.

**Comment by whns** [comment]
Oh thanks, sorry about that!

**Comment by mekarpeles** [comment]
@whns I forwarded your comment to the Archive.org team -- would you be interested in joining our newly created community slack? We're considering doing a monthly call to get feedback and better involve our digital neighbors!
