### ISSUE TITLE
Code cleanup: residual FIXMEs and hacks

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1054]
Code comments show a residual of 10 FIXMEs and 36 hacks. Some of these date back a decade and many have no clear reason for being there. At minimum they should be better documented, if they can't be actually fixed. Perhaps start with the IE6 javascript hacks?

**Comment by guyjeangilles** [comment]
This would be a major refactor. @cdrini would usually head this but @mekarpeles is taking over for him in the time being so I'm assigning him.

**Comment by LeadSongDog** [comment]
The count is now 24 FIXMEs and 30 Hacks. Should this be an epic with 54 subissues?

**Comment by guyjeangilles** [comment]
We may be able to lump some of the fixmes/hacks into one issues. First, I think we need to identify the files/modules that need to be addressed and then functionalities that would be affected. Some of these might be already captured in pre-existing issues.

**Comment by mekarpeles** [comment]
I agree this is a valid means for an issue, but it's telling that it hasn't been closed by resolution.

I think @xayhewalo has the right idea. We should try to start smaller + show some/any of the exact files where these hacks are so someone can solve a specific case. Going to close this issue and invite a more specific issue towards this goal (or a re-opening of this issue with clear next steps to help a contributor act on it)
