### ISSUE TITLE
Make improvements to Work page

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#106]
http://home.us.archive.org/~georgeo/mocks/work-page-v2.png
- Improve the list of editions so the available ones are way more obvious!
- Add a link to Merge Editions (when Edward's finished)
- Perhaps we should just simply hide the records that don't have read/borrow/buy info, or meet a minimum metadata level (like, Title, Publish Date, Publisher, at least 1 ID other than OL)

**Comment by mekarpeles** [comment]
Closing; no way to access mocks in question
