### ISSUE TITLE
Consider merging olbase and oldev

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#1064]
The split between these seems a little less necessary with the introduction of docker-compose. We should merge these to simplify the development process and speed it up.

**Comment by hornc** [comment]
@cdrini The main reason I split them was so that there was a base version of OL that could be used for production, and things like the dev db population would exist only in the dev image, which built on top. We'll need to think how we want to operate the dev db.

**Comment by guyjeangilles** [comment]
Since @mekarpeles is taking over for @cdrini for the time being, I'm assigning the former to this issue.

**Comment by mekarpeles** [comment]
This is pretty old... Going to close for now; the historical record exists for us to re-open should we need it.
