### ISSUE TITLE
Adding a back to top button on side for ease of access

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1066]
Going down in a search makes coming back up for search bar difficult. A button on the side which redirects to the top would be helpful.

**Comment by Alakhator** [comment]
I am unable to link the js file in the html file? Where to add the html code? Please help new to open source!

**Comment by jdlrobson** [comment]
Hey @Alakhator!
Right now, all JavaScript code is concatenated via the script inside static/js/all.jsh 
Right now any file you insert inside "openlibrary/plugins/openlibrary/js" will be added to the HTML file when you run `make js` inside the root folder.

I suggest creating a file openlibrary/plugins/openlibrary/js/backtotop.js with content:
`
alert('hello world');
`
Run `make js` and verify that the code was included!
Once verified, feel free to add any code to that file.

Excited to see your first contribution. Feel free to ping me in slack/here if you need any other pointers!

**Comment by Alakhator** [comment]
Thanks @jdlrobson for your help.
I have made the changes on local machine. But finding issues to test the code. Please help me out on that as well so that I can successfully submit a PR. Thanks in advance

**Comment by tabshaikh** [comment]
@Alakhator what are your issues please specify and can you upload the design of the button which you have added.

**Comment by Alakhator** [comment]
I have made the changes:
![selection_057](https://user-images.githubusercontent.com/34680620/45454382-4842fc80-b701-11e8-8b61-e60fd3057033.png)
The button disappears on the top of page and while scrolling only it appears

**Comment by Alakhator** [comment]
How to check whether the code is following coding standards or not?

**Comment by tabshaikh** [comment]
@Alakhator you can make a pr, see our pr template for doing so and if any changes are needed we can discuss it there

**Comment by Alakhator** [comment]
Okay Thank you for help @tabshaikh

**Comment by jdlrobson** [comment]
Per https://github.com/internetarchive/openlibrary/pull/1107#issuecomment-432033672 let's close this.
