### ISSUE TITLE
Separate infobase into separate docker-compose service

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#1069]
Subtask of #1071

**Comment by guyjeangilles** [comment]
@cdrini I'm adding a `Backlogged`, `Refector/clean-up`, and `Needs Assessment` labels. Let me know your thoughts.

**Comment by cdrini** [comment]
@guyjeangilles Epics/Subtasks of Epics don't really need another type; they're usually more like strategies to solving other issues (which might be bugs/feature requests). They're very rarely a bug or a feature request; just steps to solve a larger issue.
