### ISSUE TITLE
Markdown editor create link throws an error (and breaks markdown editor) in CHROME

### ISSUE THREAD

**Issue by huibvg** [internetarchive/openlibrary#107]
When you use a link in the markdown editor, an error is thrown and the editor will stop working 

The error shown is 
Uncaught illegal access in vendor.js:525

This error can also be found in the open library WMD branch: https://github.com/openlibrary/wmd
That's where I found it actually

Do you know how to fix this? I would be much obliged.

**Comment by brad2014** [comment]
Old browser errors may be impossible to reproduce.  I'll leave the disposition of this to @mekarpeles

**Comment by jdlrobson** [comment]
Ping @mekarpeles that I'm closing. Reopen if necessary.
