### ISSUE TITLE
Star Rating Widget shouldn't show up for orphaned editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1075]
Edition which have (belong to) no work don't work with ratings or reading log (i.e. want to read, currently reading, already read)

**Comment by jdlrobson** [comment]
Can you give an example of a orphaned edition?

**Comment by mekarpeles** [comment]
@seabelis has a list of orphaned works in a list -- https://openlibrary.org/people/seabelis/lists/OL129155L

https://openlibrary.org/books/OL24652731M/Room is an orphaned edition (as of today)

**Comment by hornc** [comment]
I'd vote for not adding UI to support orphans here and simply fix the data.

**Comment by guyjeangilles** [comment]
Agreed with @hornc, addressing #153 will resolve this issue. I'm going to assign Charles solely so he remembers to close this once #153 is a closed.

**Comment by hornc** [comment]
I don't think we are going to add more workaround code to do this. Closing as won't fix.
