### ISSUE TITLE
Book page "related" carousels now missing borrow link (regression)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1076]
`Borrow` link no longer showing up on books page in the "You might also like" and "More by [...]" carousels.

E.g.
https://openlibrary.org/works/OL303643W/Ludwig_Feuerbach_und_der_Ausgang_der_klassischen_deutschen_Philosophie

![screen shot 2018-09-18 at 11 04 40 pm](https://user-images.githubusercontent.com/148752/45733888-3ea11500-bb97-11e8-8f40-294579fb94bf.png)

**Comment by mekarpeles** [comment]
Might be work locally rolling back a few revisions and seeing what may have changed w/ css rules?

**Comment by jdlrobson** [comment]
Pretty sure this is not CSS related.

The link is there.. it just has no label. If the label appears, the borrow button appears. It looks like there have been no recent changes to openlibrary/templates/books/carousel_item.html

Are we sure this is a recent regression and not an old one? Do we know if this was working say a week ago with 100% certainty?

I can't seem to get "borrowed books" showing locally.
@mekarpeles how can I get some local data to test on?
 I don't see "You might also like" or "More by Mark Twain" and not finding any clues here: https://github.com/internetarchive/openlibrary/wiki/Getting-Started

**Comment by mekarpeles** [comment]
So I think this may have been introduced quite some time ago -- when I look back at `b69133cd2e29f9711337297d41ac51aae6bac8e2` I do see borrow btns:
![2018-09-29-023420_1600x900_scrot](https://user-images.githubusercontent.com/978325/46244215-4ed3a400-c390-11e8-802a-6c3a16c3af5a.png)

**Comment by mekarpeles** [comment]
You're right, it looks like the html has changed for those components. Going to re-assign to myself. Thanks for investigating @jdlrobson!

**Comment by mekarpeles** [comment]
This has been solved by @jdlrobson's latest set of changes (deployed in 75ce2b8) which move books page(s) to use slick! 🎉
