### ISSUE TITLE
Open Library error when no results are returned in full-text search

### ISSUE THREAD

**Issue by razzius** [internetarchive/openlibrary#1079]
I tried searching for

`In a nice world the air doesn't vibrate`<sup>1</sup>

searching Text selected from openlibrary.org, which took me to:

https://openlibrary.org/search/inside?q=in+a+nice+world+the+air+doesn%27t+vibrate&mode=everything

Result: `Unable to render this page.`

![image](https://user-images.githubusercontent.com/2244895/45272825-62ac7a00-b464-11e8-9c11-190c2fc2a808.png)

[1] https://openlibrary.org/works/OL2625528W/Blind_Willow_Sleeping_Woman, specifically https://en.wikipedia.org/wiki/Blind_Willow,_Sleeping_Woman#%22New_York_Mining_Disaster%22

**Comment by mekarpeles** [comment]
https://dev.openlibrary.org/search/inside?q=In+a+nice+world+the+air+doesn%27t+vibrate&mode=everything&debug=true

in `openlibrary/openlibrary/templates/search/inside.html`

`local variable 'num_found' referenced before assignment`

Before line 16 --

```
        $# <-- Here
        $if results and 'error' not in results and results['hits']:
            $ hits = results['hits'].get('hits', [])
            $ num_found = results['hits'].get('total', 0)
```

`num_found` should be initialized to `0` (in the event of no results)

**Comment by mekarpeles** [comment]
@razzius would you be down to tackle this one? :)

**Comment by CyberDrudge** [comment]
can i work on this?

**Comment by razzius** [comment]
@CyberDrudge Feel free. Haven't gotten around to it

**Comment by CyberDrudge** [comment]
How can i reproduce this?

**Comment by tfmorris** [comment]
> How can i reproduce this?

Umm, click on the link in the original problem report? Or, click on the one below to get a stack trace included:

https://openlibrary.org/search/inside?q=in+a+nice+world+the+air+doesn%27t+vibrate&mode=everything&debug=true
