### ISSUE TITLE
Make Recent Changes / add-cover show covers in the comments

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#108]
For this view:

http://openlibrary.org/recentchanges/add-cover

We should try to show the cover image in the comment column. I believe we do that sometimes in the history view, so should do it here too. Makes it _much_ easier to spot dodgy covers.

**Comment by rohitjain00** [comment]
On #29 similar issue is reported I think one of them needs to be closed

**Comment by mekarpeles** [comment]
agreed, duplicate of #29 thank you @rohitjain00
