### ISSUE TITLE
Minify CSS assets

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1085]
Currently CSS assets (by nature of CSS) are render blocking. They are also not-minified. Right now on a 3G connection from Singapore it can take up to 12 seconds for the user to see anything 
 -https://www.webpagetest.org/result/180907_N8_824f77c230ea0a2939484f3e5657bb18/

Minification of all these assets should be a top priority.

This is easily achieved via LESS (using -x) but given there is also CSS these will need to be built using LESS as well for this to be viable.

We can expect the site to be a lot lot faster with changes in this arena.

**Comment by skeeterblaster** [comment]
have a leak
*we *

**Comment by jdlrobson** [comment]
This is not fixed. @mekarples can you reopen?

**Comment by jdlrobson** [comment]
Closing this in favor of #1123
