### ISSUE TITLE
Add npm test to CI

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1089]
Recently we added a package.json and an npm test entry point. Right now this runs stylelint to enforces a small set of CSS standards (including making it hard for developers to introduce new colors without using a less variable).

I'd like to expand those standards and later add linting for JavaScript.

It would thus be useful for the Travis job to run `npm test` on every commit and forbid us introducing regressions.

**Comment by skeeterblaster** [comment]
how about a way to measure external verses internal energy. projectile and
house made devises would be considered external
