### ISSUE TITLE
Validate IA identifier on Edition edit

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#109]
It's important that only real IA identifiers are entered on the Edit Edition form.
- Need to add AJAX validation on that field - make sure it resolves to an IA item
- Need to handle the case where the IA ID isn't valid 
- Parse and trim identifiers if people enter full archive.org URLs

We should also accept full URLs as identifiers in that form, I think. For other types of IDs.

**Comment by LeadSongDog** [comment]
This problem still persists after five years. The IA identifier is not validated before first creating an edition record, nor is it checked for uniqueness and as having an extant IA target. 

Example: 
searching for an IAid may find it in two places, whereas it should be unique: 
https://openlibrary.org/search?q=corollasanctiead00hervuoft finds it at both: https://openlibrary.org/works/OL11080612W/Corolla_Sancti_Eadmundi and at https://openlibrary.org/works/OL16742827W/Corolla_Sancti_Eadmundi by dint of edition records https://openlibrary.org/books/OL26221263M/Corolla_Sancti_Eadmundi and https://openlibrary.org/books/OL7041407M/Corolla_Sancti_Eadmundi respectively.

**Comment by mekarpeles** [comment]
thank you for bumping this (cc: @bfalling). 

@LeadSongDog, we're going to start doing community calls bi-weekly (we're still converging on a date/time -- those interested can vote here: http://doodle.com/poll/hrqphgaw2k9zhfbsyeuis638/admin#table). 

We'd love you to join us if this aligns with your style, and alternatively, if you prefer, we invite you to submit an update prior to our meeting so we can represent the issues and features which are most important to you.

As per this issues, I'm hearing what you're saying -- I think it's worth discussing strategies for addressing this, whether it is through something like an edition merge (which is an available feature for admins) and whether we write some script to identify duplicates like the one you uncovered.

I am going to defer to @bfalling for the prioritization. Right now we're working to fix our bookserver/opds service (as it stopped working when we decommissioned SOLR in favor of ES).

@LeadSongDog, thank you for your continued passion and contributions!

**Comment by LeadSongDog** [comment]
Still no one assigned, and still broken. 
Some measures of success:
1. Each and every OCAID seen in OL should be assigned to exactly one edition OLID.  
2. Each and every OCAID seen in OL should have a valid target available in IA.
3.  Each and every IA catalog record at these OCAIDs should have a back link to that edition OLID.
4. The above can be demonstrated by an automated query.

**Comment by tfmorris** [comment]
@bfalling was tagged for prioritization a year and a bit ago. Through what channel does he communicate IA's priority (at least I assume IA is what he's in charge of communicating priority for). Will he do that through the Tuesday development team meetings or some other channel?

**Comment by mekarpeles** [comment]
@tfmorris, brenton's invited to join us on Tuesday so we can all make cases for the issues/features we feel are important. He and I will likely have a followup mtg later this week (Friday) w/ internal stakeholders to see if there are separate needs which require addressing. Next Tuesday (March 20) I'll hopefully have a Q2 github project board organized and we'll entertain a final round of community feedback so we can make sure everyone's feedback has been incorporated.

As per this specific issue, we do still have `ocaid`s which get our of sync or are invalid and writing a checker for them wouldn't be too hard. A question is at what points should the check be called? Edit? Creation? We can also (at create time) add a check to make sure the `ocaid` is not already accounted for within OL.

The case of `ocaid`s  becoming stale (at least for now) I think should be addressed by editing the entry. We could hypothetically add this to our solr updater process or have some cron which checks periodically, but for the meantime, I think preventing duplicate `add book`s is the more critical and the simpler of the two cases.

**Comment by mekarpeles** [comment]
It's unclear what resolution means in this context, let's please create another issue to address specific cases e.g. validate ocaid on edit or create.

**Comment by tfmorris** [comment]
George had three very specific requests for the Edit Edition form. I don't know what she thinks, but I'd consider this resolved when those were done. They all sound like good ideas to me. If people want to 1+ things, sure, they should create new issues.

The more general issue of "Accept a full URL anyplace an identifier can be entered" deserves a separate issue for the cases other than OCAIDs on the Edit Edition page. I've created #866 for this.
