### ISSUE TITLE
Fix  unused solr/work_subject.py code

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1091]
openlibrary/openlibrary/solr/work_subject.py
  and
openlibrary/openlibrary/tests/solr/test_work_subjects.py

Appears to be unused, and `get_marc_subjects()` relies on `openlibrary.catalog.get_ia` `get_data()` which has been broken since 2014
(undefined `rc` variable)

**Comment by tfmorris** [comment]
I think it would be preferable to fix the subject indexing (#1896) rather than ripping it out.

**Comment by guyjeangilles** [comment]
I think @hornc has found the files that aren't properly indexing subjects into solr. As @tfmorris proposed, we should fix these files instead of deleting them.

I propose closing this.

**Comment by hornc** [comment]
Can we rename this to "repair" or investigate rather than remove? The value of this issue is that I had discovered that sone specific code existed and wasn't and can't be used.

**Comment by tfmorris** [comment]
I've updated the subject, but consider it a duplicate of #1896.

**Comment by hornc** [comment]
unused code removed in https://github.com/internetarchive/openlibrary/pull/3054/commits/cd8daeda3c977308532c22a4191388ff3ad06685
