### ISSUE TITLE
Search should neither be case-sensitive nor macron/diacritic-sensitive

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#11]
Comment: Titles of books in Oriental and South Asian languages - like
Arabic, Persian, Urdu &amp; Hindi - are often Romanized or transliterated
using macrons &amp; diacritics for elongated sounds of vowels. Sometimes,
instead of macrons &amp; diacritics, double vowels (aa, ee or oo) are
used. Similarly, there are letters whose sound is represented in more than
one way, e.g. the Arabic, Persian &amp; Urdu letter ( Ø« ) Seh is
represented by both th and S. Similarly Ø¶ is represented by dh, d &amp;
even Z. Thus the transliteration or Romanization of, say, proper names
etc. has never been standardized with the result that more than one
spelling are used for them. When filling the Search Box, usually macrons
are not available on the PC keyboard. May I suggest the search feature
ignore this requirement. It should neither be case-sensitive nor
macron/diacritic-sensitive.
For example, the following variations of spellings or transliterations are
used for the complete poetry collection of Mirza Ghalib (1797-1869), the
famous Indian poet. There can still be few more varieties:
DÄ«vÄn-e-GhÄlib, DÄ«vÄn-i-GhÄlib, DÄ«wÄn-i-GhÄlib,
Deevaan-e-Ghaalib, Deevaan-i-Ghaalib, Deewaan-e-Ghaalib,
Deewaan-i-Ghaalib. The search should be programmed in a manner so that any
of the above-mentioned spellings (or even more) should get us the book
entry.
Thank you &amp; kind regards,

Riaz Ahmad Barni
Karachi, Pakistan
riaz_44@yahoo.com

**Comment by bfalling** [comment]
Closing in favor of #178
