### ISSUE TITLE
Stylelint: Add whitespace rules to our CSS and fix offenders 

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1100]
We should be consistent in our use of whitespace within our CSS file. We can use tooling to enforce this. We should limit the number of empty lines to 1, make sure our lines are never longer than 100 characters and that we don't put whitespace on empty lines.

[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`)  can detect these if configured with the following:
`
		"no-eol-whitespace": true,
		"max-empty-lines": 1,
		"no-missing-end-of-source-newline": true,
		"max-line-length": 100,
`

### Checklist
- [x] Update .stylelintrc.json
- [x] Add ``` "max-empty-lines": 1 ``` rule
- [x] fix any offenders detected via `npm run lint:fix`
- [x] Add ``` "no-eol-whitespace": true ``` rule
- [x] fix any offenders detected via `npm run lint:fix`
- [x] Add ``` "no-missing-end-of-source-newline": true ``` rule
- [x] fix any offenders detected via `npm run lint:fix`
- [x] Add ``` "max-line-length": 100 ``` rule
- [x] fix any offenders detected via `npm run lint:fix`

As the issue involves a lot of css change independant pull request would be suitable for each change of rule, then if a breakdown occurs it can be easily debugged

**Comment by jdlrobson** [comment]
Better to have sooner rather than later... will work on this if nobody else does.

**Comment by tabshaikh** [comment]
@jdlrobson I will began working on this issue

**Comment by jdlrobson** [comment]
Looks like no-missing-end-of-source-newline and "max-line-length still need fixing.
I've unticked those boxes as I'm not seeing them address in master.

let me know if i've missed something!

**Comment by tabshaikh** [comment]
@jdlrobson I made the changes in my local repo changed this issue here and forget to get the pull request up , I will do that today.
