### ISSUE TITLE
Stylelint: Add selector-max-specificity and temporarily allow offenders

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1118]
Many of Open Library's CSS selectors are overly and unnecessarily verbose. For instance, we should rarely be using ID's to select and style elements and we certainly should not be using more than one id.

Given there are a lot of offenders, we should start with a lenient configuration for selector-max-specificity, which we can later.

[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`)  can detect these if configured with the following:
`
		"selector-max-specificity": "1,4,0",
`

Since fixing these will be complicated, we'll disable the rules for the existing offenders. The goal is to prevent us adding more inappropriate selectors to the codebase!

### Checklist
- [ ] Update .stylelintrc.json
- [ ] Disable the rule for any offenders - disable only on a block level NOT the file level

e.g.
```
  // stylelint-disable selector-max-specificity
  #widget-lists {
    margin: 0;
    clear: both;

    li {
      padding-left: 0;
    }
  }
  // stylelint-enable selector-max-specificity
```

### Notes to signer-offer/reviewer
Don't forget to create a new task to change the values of selector-max-specificity slightly again, to improve things further.

**Comment by koderjoker** [comment]
Hi, could I start working on this issue? Also, do I have to disable the rule for all offenders in all css files of the repo, separately for each block?

**Comment by jdlrobson** [comment]
Yup. Try to limit the size of the block the disables apply to. The goal would be to keep specific selectors from being added in future.
