### ISSUE TITLE
Find long term minification solution for css (-x is deprecated)

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1123]
Right now we are minifying our css using less -x but as the command line output shows this is deprecated. 

Going forward we will need to find a better solution for minification.

**Comment by jdlrobson** [comment]
Many options.. including gulp, webpack...

**Comment by rohitjain00** [comment]
According to the documentation given on thofficial [LESS.js](http://lesscss.org/usage/) page
It is Instructed to use **Clean CSS plugin**
![cleanCSSPlugin](https://user-images.githubusercontent.com/17525863/54460362-57c5ff80-478f-11e9-868d-00d6bded8024.png)
So I think rather than using lessc-x (Which is depriciated), We should switch to [Clean CSS plugin](https://github.com/less/less-plugin-clean-css)

**Comment by rohitjain00** [comment]
I think we should also add a autoprefixer along with clean CSS and remove any manually added autoprefixing

**Comment by jdlrobson** [comment]
@rohitjain00 #1995 would give us a head start on that. I'm not sure about using an autoprefixer but if we do we're blocked on the webpack move in #1936

**Comment by rohitjain00** [comment]
@jdlrobson thanks for update. I got what you wanted to say.

**Comment by jdlrobson** [comment]
The following would give us CSS files inside JS files. e.g. static/build/page-admin.js
It might be possible to use  https://github.com/webpack-contrib/mini-css-extract-plugin to pull out the CSS into separate files. Haven't explored that yet. Using one tool for asset generation seems a plus to me.

```
diff --git a/webpack.config.js b/webpack.config.js
index fa552fb3d..e373b3b66 100644
--- a/webpack.config.js
+++ b/webpack.config.js
@@ -26,6 +26,18 @@ module.exports = {
 
     // A map of ResourceLoader module / entry chunk names to JavaScript files to pack.
     entry: {
+        'page-admin': './static/css/page-admin.less',
+        'page-book': './static/css/page-book.less',
+        'page-edit': './static/css/page-edit.less',
+        'page-form': './static/css/page-form.less',
+        'page-home': './static/css/page-home.less',
+        'page-lists': './static/css/page-lists.less',
+        'page-plain': './static/css/page-plain.less',
+        'page-subject': './static/css/page-subject.less',
+        'page-user': './static/css/page-user.less',
+        'page-book-widget': './static/css/page-book-widget.less',
+        'page-design': './static/css/page-design.less',
+        'page-dev': './static/css/page-dev.less',
         'all': './openlibrary/plugins/openlibrary/js/index.js'
     },
 
@@ -49,7 +61,14 @@ module.exports = {
             loader: [
                 'style-loader',
                 'css-loader',
-                'less-loader' // compiles Less to CSS
+                {
+                    loader: 'less-loader', // compiles Less to CSS
+                    options: {
+                        paths: [
+                            path.resolve(__dirname, 'static/css/')
+                        ]
+                    }
+                }
             ]
         } ]
     },


```

**Comment by guyjeangilles** [comment]
@jdlrobson Adding feature and work in progress labels per this thread. Let me know if you agree or disagree.
