### ISSUE TITLE
requirements.txt lists unused modules

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1129]
`requirements.txt` has many unused modules

I could not find any uses of 
```Fabric==1.10.1
Jinja2==2.6
amqplib==1.0.2
anyjson==0.3.1
```

Also, the docker images 'accidentally' only pip installed `test_requirements.txt`, which includes `requirements_common.txt` and there was no obvious consequence. 

This needs to be investigated further before simply deleting `requirements.txt`, but I think it may be sufficient to only use `requirements_common.txt`.

**Comment by mekarpeles** [comment]
I think this can now be closed
