### ISSUE TITLE
Review need for moment js library

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1139]
I see we use moment js but am not clear why (yet)

Let's review usage as 
https://github.com/you-dont-need/You-Dont-Need-Momentjs/blob/master/README.md

**Comment by jdlrobson** [comment]
We seem to only use this in one place.. to render the green labels here on https://openlibrary.org/account/loans ...
![screen shot 2018-09-26 at 4 40 18 pm](https://user-images.githubusercontent.com/148752/46115244-f1323280-c1aa-11e8-8a59-a34e9a961ce5.png)

What this means is we are pulling in a 69.6K library (After gzipping) to render a single line like so:

```
moment('2018-10-04T16:45:51Z').format('LLL')
```

How would people feel like not doing that?
We could instead use:
```
> (new Date('2018-10-04T16:45:51Z')).toLocaleString([], {hour: '2-digit', minute:'2-digit', month:'2-digit', day:'2-digit', year:'numeric'} )
> "04/10/2018, 09:45"
```
which uses the browsers locale...

Thoughts?

**Comment by mekarpeles** [comment]
enthusiastically for making this switch and rm'ing dependency on `moment`

**Comment by jdlrobson** [comment]
I need to add feature detection so we dont break ie10 and below and other browsers
