### ISSUE TITLE
Dead code?

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1144]
What was intended here? Anything?
https://github.com/internetarchive/openlibrary/blob/d883f91229b4f4d13fa2e6d4da6343dc78417d64/openlibrary/catalog/edition_merge/merge.py#L234

**Comment by mekarpeles** [comment]
I think it was born-dead, with aspirations of being activated. I think there may be useful tidbits there which probably belong on a feature branch and commented in an issue rather than in the live repo

**Comment by LeadSongDog** [comment]
@mekarpeles 
I stumbled on it while looking for an explanation for the problem of search results showing works with one edition that (on clickthrough to the work record's page) have zero editions remaining. Typically I see this after moving the last edition to a merged work.  Either there's an error calculating number_of_editions or there`s stale cache somewhere. I suspect the former, because the count is correct until the very last edition delinks a work record.

**Comment by jdlrobson** [comment]
.. can we get it removed? :)

**Comment by tabshaikh** [comment]
This code can be seen in the branch https://github.com/internetarchive/openlibrary/tree/1144/edition-merge-deadcode
