### ISSUE TITLE
dropper component doesn't gracefully degrade without JavaScript

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1147]
Visit https://openlibrary.org/books/OL23053293M/Ranma_1_2. and disable JavaScript.

Attempt to add the page to a reading list.

Expected:
Either:
* I should see a browser drop down. Upon selecting a drop down I should be able to add to a list
* the element should be hidden without JavaScript support and I should not be able to perform the action.

Actual:
* Clicking the arrow to the right has no effect. Clicking "Currently reading" refreshes the page without any change to the status of which lists the book is on.

**Comment by koderjoker** [comment]
@jdlrobson I'll give this a go!

**Comment by koderjoker** [comment]
@jdlrobson just reaffirming, but do we want to hide the dropper when js is disabled? 

I could do that by giving dropper the style `display: none` and switching it with js.

**Comment by jdlrobson** [comment]
Ideally this would work, but if there is no fallback we should hide it. When hiding it you may need to use visibility: hidden to avoid CSS repaints/reflows/flash of unstyled content (https://en.wikipedia.org/wiki/Flash_of_unstyled_content)
