### ISSUE TITLE
BWB lookup can't get through

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1156]
@mekarpeles 
I was looking at #1153 and it seems that there are two problems with the BWB lookup at:
https://github.com/internetarchive/openlibrary/blob/97e6fd5392726828de2193b1ebcb3a64a9198d7c/openlibrary/macros/AffiliateLinks.html#L26

First, it is still using http (as is the amazon link above).
Second, http://www.anrdoezrs.net is being consistently redirected by its domain administrator, (conversant.com) to a very persistent "privacy options" information page.

What is the point in going through anrdoezrs.net anyhow? It seems to be owned by akami so presumably it's something about advertising.

Why not go directly to https://www.betterworldbooks.com/product/detail/-%s instead?

**Comment by mekarpeles** [comment]
a la the filename, those are all affiliate links to support/sustain OL

**Comment by mekarpeles** [comment]
Price info is reliably being shown on open library page and redirects seem to be working. Closing issue.
