### ISSUE TITLE
Design consolidation: Merge ButtonBtn and ButtonGeneric

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1158]
We appear to have many ways of rendering a button. We should pick one of them and use it for them all.

Right now we should focus on merging the styles for ButtonBtn, ButtonGeneric and Book "book-cta" as well as ".borrow-btn, .read-btn, .wait-btn, .unwait-btn"

= Sign off checklist
- [ ] One CSS class name to rule them all!

**Comment by guyjeangilles** [comment]
Tagging jdlrobson (not tagging as requested) per slack discussions. The solution to this issue is closely coupled to #1184

**Comment by jdlrobson** [comment]
Declining in favor of the epic. This issue is not actionable until we have the larger conversation and plan how we want to do this.
