### ISSUE TITLE
Enable gzipping for text-based assets on dev.openlibrary.org

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1162]
https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/optimize-encoding-and-transfer

I think we have this on production but not on dev which makes it hard for us to performance test it.

**Comment by guyjeangilles** [comment]
@jdlrobson Was this ever implemented?

**Comment by jdlrobson** [comment]
Synced with @mekarpeles today and dev.openlibrary.org now gzips resources. Thanks for the ping!

**Comment by cdrini** [comment]
Let's leave this open until it's on prod; otherwise I can almost guarantee it'll fall through the cracks.

**Comment by cdrini** [comment]
It doesn't look like this is happening on openlibrary.org yet. Since this requires server configuration, assigning @mekarpeles

**Comment by jdlrobson** [comment]
Wait what?
Last time I checked we had gzipping in production and this ticket was only getting it on dev where it was absent.

(I am not at my computer right now so can't confirm)

**Comment by cdrini** [comment]
Oh jeez, I'm sorry; I entirely misread what I was looking at 😅 You are completely correct! Closing.

**Comment by jdlrobson** [comment]
Phew you had me worried then. That sort of thing can take down a site haha
