### ISSUE TITLE
Conflicting addbook endpoints?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1163]
Are plugins/upstream/addbook.py `addbook` and plugins/openlibrary/code.py `addbook` clobbering each other?

**Comment by hornc** [comment]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/addbook.py#L116

path = /books/add , is the UI add book page.

vs.

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L193

path = /addbook  Looks like it deliberately redirects to /books/add -- what does it add?

```curl -I https://openlibrary.org/addbook
HTTP/1.1 301 Moved Permanently
Server: nginx/1.4.6 (Ubuntu)
Date: Wed, 08 May 2019 10:44:59 GMT
Content-Type: text/html
Connection: keep-alive
Location: https://openlibrary.org/books/add
X-OL-Stats: ""
```

**Comment by hornc** [comment]
The answer to this question is _No_, there is no path clobbering going on, the paths have different names, even though one redirects to the other. I'm not sure why there is a re-direct, probably for historical reasons, but I'm not aware of any cost to this. It could be refactored when someone is working on a specific feature in this area in future.
