### ISSUE TITLE
Undo this bad author-merge

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#117]
There is an [active support case](http://openlibrary.org/admin/support/590) to fix a wrong author-merge. The current undo button didn't work in this case. 

http://openlibrary.org/recentchanges/2011/05/31/merge-authors/43575781

Need to write a script to undo this merge and make undo more robust, if possible.

**Comment by LeadSongDog** [comment]
The merge was created by https://openlibrary.org/people/mcolmene who evidently has only logged onto OL twice. Should probably just close this.

**Comment by bfalling** [comment]
Closing, but note that script `undo-author-merge.py` exists and could be used in the future.
