### ISSUE TITLE
Compress SVG assets

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1170]
SVG assets, for example https://openlibrary.org/static/images/categories/textbooks.svg are huge.
They should be compressed before being shipped to users.

**Comment by tfmorris** [comment]
Rather than compressing assets individually, gzip should be turned on in the web server (or nginx) so that all responses are compressed. Responses don't appear to be served using gzip currently even when the browser says it'll accept gzip.

**Comment by jdlrobson** [comment]
😯

**Comment by jdlrobson** [comment]
Gzip aside we can and should minify local assets and it's at low cost to ourselves. The tooling is there and tried and tested - https://www.npmjs.com/package/svgo - we use it for Wikipedia.

**Comment by jdlrobson** [comment]
Superseded by #1368
