### ISSUE TITLE
What does our browser support matrix look like?

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1180]
It's unclear which browsers we need to support.
Ideally, we should base this on data showing what browsers are users are using. Do we have this information?

If not, we should probably follow a browser matrix similar to other projects e.g. [MediaWiki](https://www.mediawiki.org/wiki/Compatibility#Modern_(Grade_A))

Once defined we can likely through away a lot of CSS code (and maybe JS).

**Comment by jdlrobson** [comment]
Looks like json2 is probably not needed for example

**Comment by jdlrobson** [comment]
This may also help #1054.

**Comment by jdlrobson** [comment]
@mekarpeles any ideas on how to think about this?

**Comment by jdlrobson** [comment]
mekarpeles i plan to drop support for any browser with less than 1-5% traffic. Can you get that information?

**Comment by shaneriley** [comment]
I typically drop browsers with < 2% traffic, but in the case of this project's global scope that may be difficult. I'd be interested to know how many versions back we're seeing used and filtered by country.

**Comment by mekarpeles** [comment]
@bfalling or @rchrd2 can one of you please weigh in here re: archive.org's browser support matrix? We'd love to add this to our Open Library wiki. Is this documented somewhere for IA?

**Comment by shaneriley** [comment]
In scanning through the JS, I noticed an [`Array.prototype.filter` method call](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/availability.js#L85), which made me think we're not supporting IE too many versions back. If we are, there's probably a few spots in the JS that need to be downgraded to IE7 style solutions.

**Comment by jdlrobson** [comment]
>In scanning through the JS, I noticed an Array.prototype.filter method call,

Yeh this is one of the reasons why I brought this up. There is modern JS, strict JS, old JS... vendor prefixes galore and even IE5 hacks! Thus knowing this will help drive a bunch of things.

**Comment by jdlrobson** [comment]
Okay.. I want to make progress on this, so in lieu of traffic information I'm going to propose we follow Wikipedia's browser support matrix: https://www.mediawiki.org/wiki/Compatibility#Modern_(Grade_A)

Patch to follow.
