### ISSUE TITLE
SAVE buttons are invisible on edit page

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1181]
Visiting the edit page as in https://openlibrary.org/people/username?m=edit one observes a missing Save button on the bottom of the page. Hovering over with the mouse shows that the button is just hidden.

![edit_page](https://user-images.githubusercontent.com/9248823/46075305-c340f400-c192-11e8-9d4c-1b0fe3f76691.png)

**Comment by tabshaikh** [comment]
@Num170R But why must the button be hidden

**Comment by Num170R** [comment]
@tabshaikh it shouldn't be hidden. It should show up normally.

**Comment by seabelis** [comment]
Also missing from the IDs section and covers window (scroll arrows also missing).

**Comment by jdlrobson** [comment]
@mekarpeles can youtake a look at my patch and pull these to production?

**Comment by mekarpeles** [comment]
Yes, one moment :)
