### ISSUE TITLE
Implement merge-editions API

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#119]
It will be nice to expose merge the editions through an API.

Calling the API should be equivalent to doing the merge manually and going ahead with the defaults presented in the merge-preview page.

If we are going to use `/books/merge` as the endpoint for merge, then the API should be `/books/merge.json`.

**Comment by bfalling** [comment]
See #118 "Finish Merge Editions" and #117 "Undo bad merge"

**Comment by mekarpeles** [comment]
duplicated by #805 and partially solved by @cdrini #700
