### ISSUE TITLE
JS: Remove Flickr and Twitter vendor js usage

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1191]
I see we include 2 JS files to add feeds to Twitter and [Flickr](https://github.com/seaofclouds/tweet). However, I can't see where these are used ($.fn.flickr is not called anywhere, neither is.

xcat $VENDORJS/jquery-flickr/jquery.flickr-1.0-min.js
xcat $VENDORJS/jquery-tweet/jquery.tweet.js | $JSMIN

Is there any reason to keep them?
It's possible they might be being used on the admin pages, but I can't access those locally to see.

If they are used on the admin page, that's fine - we can restrict to those pages, but we certainly shouldn't load for everyone.
Removing them saves us 2kb after gzipping.

**Comment by jdlrobson** [comment]
Looks like they were added in c2202538 by @anandology and never used?

**Comment by himanshuc3** [comment]
Should i just delete em off and commit?

**Comment by himanshuc3** [comment]
In ```jquery-tweet``` folder, there are html, css and js files. Should I delete all of them off as well, as they are just for demo purposes.

**Comment by jdlrobson** [comment]
You can safely delete all!
