### ISSUE TITLE
Drop fontawesome usage

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1193]
[Font awesome free](https://fontawesome.com/free) is used to display two icons in the [footer component](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#footer) - fa-twitter and fa-github

There are various reasons to remove this.

-  We currently load this library via JavaScript, meaning on the home page they do not show if JavaScript is disabled:
![screen shot 2018-09-26 at 5 40 08 pm](https://user-images.githubusercontent.com/148752/46116915-440fe800-c1b3-11e8-83cc-14fa411b6013.png)
- These icons and the shareLink icons are inconsistent in style (https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#sharelinks )
- The  woff webfont is 75.7kb but we only use 2 of the many icons it provides
- 6kb of CSS (after gzipping) is required to render these 2 icons

Instead, we should find 2 svg/png icons for Flickr and Github and make use of those instead.

**Comment by jdlrobson** [comment]
Do we have a designer who can provide us with open source friendly icons for these 2 services (ideally consistent with the facebook, twitter, pinterest and embed icons in https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#sharelinks ) ?

**Comment by LeadSongDog** [comment]
Alternatively, https://www.iconfinder.com/iconsets/social-network-9 may be more useful if the license is acceptable

**Comment by LeadSongDog** [comment]
@jdlrobson 
I notice also that the login page shows greyscale versions of the Twitter and Github icons, while the /works/ pages show colour for Facebook, Twitter, Pinterest, and Embed. Consistency would be nice...

**Comment by jdlrobson** [comment]
@mekarpeles are there any designer friends we can get input for this from? If not, how can we make this kind of decision?

Like @LeadSongDog I'd like these to be consistent across the site as well as with an appropriate license.
