### ISSUE TITLE
Fix highlight on category items inside carousel

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1195]
When tapping a category a single box should surround the whole category not 3 boxes like so:

![2018-09-23 10 33 26](https://user-images.githubusercontent.com/148752/46125555-8864ad80-c1de-11e8-8773-bbcea8fbfb3b.jpg)

**Comment by rohitjain00** [comment]
@jdlrobson I don't think this is an Android specific issue. The same boxes get highlighted while using the website on PC.

**Comment by jdlrobson** [comment]
@rohitjain00 ideally this orange box should wrap the entire think, preferably the html should be:
```
<a>
<img>
<span>
</a>
```
for each carousel item

**Comment by cdrini** [comment]
I just checked the HTML and it's got that structure. The anchor element needs to be `display:block`, which it currently isn't.
