### ISSUE TITLE
Trash area off screen in Book Covers window

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1199]
Cannot delete cover. Trash area off screen. (Workaround by modifying .trashposition in browser.)

![fullscreen capture 9272018 24753 pm bmp](https://user-images.githubusercontent.com/17739465/46147093-ce645480-c264-11e8-9ed8-d0a5c53bde95.jpg)

**Comment by LeadSongDog** [comment]
#905 relates: on iOS there's no way to drag/drop the cover, so deletion is impossible. There should be another way (click to select, click to delete?).

**Comment by seabelis** [comment]
This was in Chrome btw. I have not tried other browsers.

**Comment by mekarpeles** [comment]
It looks like the modal is being loaded as an iframe and thus the
`#placement { width: 960px }` and `div#position { width: 960px }` (which is set on its body) is proving to be problematic.

**Comment by mekarpeles** [comment]
p.s. thank you @seabelis, great catch! very thankful for your careful eye! :)
