### ISSUE TITLE
When comparing revisions two buttons are inactive

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1200]
After you click in order to compare two revisions in work history page, there are two buttons "View" and "History" that are inactive but were supposed to lead you somewhere
1) View button should exit comparison view
2) History button should lead you to work history page 

![compare_revisions](https://user-images.githubusercontent.com/9248823/46161581-94a84380-c28e-11e8-8c5d-41ab8455a6bf.png)

**Comment by yogeshjdeshmukh** [comment]
Similar issue is also present on another page.

**Comment by yogeshjdeshmukh** [comment]
I think I can solve this would you please assign me this issue.

**Comment by tabshaikh** [comment]
@yogeshjdeshmukh I think @Num170R has already begun solving this issue so you can choose from our other issue's labeled with easy or good first issue tag

**Comment by mekarpeles** [comment]
@yogeshjdeshmukh feel free to send a PR :) everyone's work is welcome. We'll choose whichever solution looks like the right one for the problem. Thanks for your work!

**Comment by Num170R** [comment]
@yogeshjdeshmukh I have not worked on this just opened an issue. Please feel free to send a PR

**Comment by yogeshjdeshmukh** [comment]
Sir thank you for your support. Actually I am new to open source and this
was my first issue solving. I wonder if you can guide me through.

**Comment by tabshaikh** [comment]
@yogeshjdeshmukh sure, you can begin by reading our contributor guide, the various technologies we use. Feel free to work on any easy issue for the beginning

**Comment by yogeshjdeshmukh** [comment]
Yes sir.. Surely

**Comment by Num170R** [comment]
I can't seem to be able to reproduce the fix in prod, for example [here]

![compare_revs](https://user-images.githubusercontent.com/9248823/46300492-89b22380-c5ac-11e8-9d09-155220669d95.png)

[here]: https://openlibrary.org/books/OL19242897M/Goethe?b=2&a=1&_compare=Compare&m=diff

**Comment by yogeshjdeshmukh** [comment]
Yup... When I ran my changed code on vagrant sever it worked well. Even I
checked the website while ago. The changes aren't visible yet.
