### ISSUE TITLE
Finish ils_search API

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#121]
FInish the ils_search API using the new import library that you are building.

http://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=7152

Once the API is ready, document it in the dev blog. We can add it to dev/docs once beta-testing is over.

**Comment by guyjeangilles** [comment]
Closing this given how old this is and [the documentionSearch API](https://openlibrary.org/developers/api)
