### ISSUE TITLE
Add to list button overlaps page

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1218]
In some works, after navigating to the work page the `Add to List` button overlaps the adjacent area.
For example:

![add_to_list](https://user-images.githubusercontent.com/9248823/46298286-5faa3280-c5a7-11e8-9896-023b059f72a9.png)

**Comment by mekarpeles** [comment]
reproducible at: https://openlibrary.org/books/OL19242897M/Goethe

**Comment by Num170R** [comment]
I'll also take that , please assign
