### ISSUE TITLE
Search bar extends beyond appropriate limits

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1224]
Search bar width is getting modified in html template file, so that the third criterion "Print Disabled" spans two lines. 

![search-bar](https://user-images.githubusercontent.com/9248823/46322176-1b8f5000-c5f0-11e8-90c8-23286d87108a.png)

**Comment by jdlrobson** [comment]
What page are you seeing this?
The issue is a little vague at current time so I am not 100% sure where to test this to understand the problem.

**Comment by Num170R** [comment]
yes, that was on firefox. on chrome it seems to be ok

**Comment by jdlrobson** [comment]
Thanks for the clarification!

**Comment by jdlrobson** [comment]
I can only replicate this on Firefox if window.innerWidth === 1800
Can you confirm you are seeing this on a large resolution?

**Comment by Num170R** [comment]
It is crucial to have this straight as I'd like also to remove the remaining inline styles in other templates.

**Comment by jdlrobson** [comment]
Sure but it's crucial when communicating in an open source project that we all have a mutual understanding of the issue so that we can both be confident it's the best way to fix the problem.

I just want to confirm the size of your browser window to check you are seeing this issue where I am.

**Comment by Num170R** [comment]
@jdlrobson I can currently replicate when window.innerWidth == 1280

**Comment by Num170R** [comment]
@jdlrobson and [here] is on prod.

[here]: https://openlibrary.org/search?q=home&mode=ebooks&m=edit&m=edit&has_fulltext=true
