### ISSUE TITLE
External links exceed width of panel

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1228]
When displaying external links under tools panel, the text should not exceed the width of the above panel.

![external-links](https://user-images.githubusercontent.com/9248823/46328766-c2d0af00-c611-11e8-8528-3047bb4f855a.png)

**Comment by jdlrobson** [comment]
Please remember to add a URL and replication instructions when creating a new issue.

In this case looks like the "Contributor biographical information" label is too long or using whitespace wrapping.

Can you provide replication instructions so I can help test? Which book is this?

**Comment by Num170R** [comment]
Please, for example look [here]. the <li> 's are constrained by the width of their container. but the whole panel one can easily observe that extends beyond appropriate limits.

[here]: https://openlibrary.org/books/OL24493794M/Odyssey
