### ISSUE TITLE
Load covers for all archive.org scans

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#123]
Once the `ils_cover_upload` API is ready, use it to load covers for all editions with ocaid. 

Most editions with ocaid have covers, but some of them don't have. You can find the editions with ocaid and without cover from the latest openlibrary dump.

The [Book urls](http://openlibrary.org/dev/docs/bookurls) page has documentation about how to construct urls for cover image pages using itemid.

Here are sample URLs to access cover and title page of a book.

http://www.archive.org/download/chefwymansdailyh00wyma/chefwymansdailyh00wyma/page/cover.jpg
http://www.archive.org/download/chefwymansdailyh00wyma/chefwymansdailyh00wyma/page/title.jpg

Sometimes the cover image just contains the library binding. You can use some heuristic to decide whether to use cover or title. I think published-year might be a very good to start with.

**Comment by hornc** [comment]
relates to #2875
