### ISSUE TITLE
When no ebook available, display consistent "No eBook Available" button

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1235]
Not all Open Library records have ebooks -- this is a source of confusion for our users.

On such books, readers click "Want to Read" because they think this will bring them to read the book. There was discussion on #855 about changing the text of "Want to Read" to something different, but I think the real problem is that we don't make it explicit (in a way which is stylistically consistent with the available actions when there is an ebook available) that no ebook is available.

This issue proposes that no changes are made to the "Want to Read" button, but rather that we add a disabled button on the book page side bar where it usually says "Borrow eBook" or "Read eBook" so that users understand we don't have the book.

Bonus points: When you click "No eBook Available" and the reader **hasn't** yet marked as "Want to Read", we *could* ask the user:

> We don't have this item as an ebook yet, but we add new books every day. Would you like to add this title to books you want to read?  -- [No Thanks] [ Want to Read ]

![](https://user-images.githubusercontent.com/978325/46275322-59697700-c511-11e8-9e3c-4b7ecda47df7.png)

**Comment by KhalidRmb** [comment]
Hey! May I know the status on this? (I did check out the a book without no ebooks available, and although it shows "no ebooks available" there's no button as described in this issue.

Shall I go ahead?

**Comment by tabshaikh** [comment]
You can surely go ahead and work this issue
