### ISSUE TITLE
Add README.md for internationalization

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1236]
Currently, we have a page on our wiki which describes contributing to internationalization (i18n): 
https://github.com/internetarchive/openlibrary/wiki/Contributing-to-Internationalization-(i18n)

I think it makes more sense for us migrate this document out of the wiki and into the `openlibrary/i18n` directory as a README.md.
https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n

The wiki page would then be removed and the link in the right side bar of the wiki (called `Contributing to Internationalization`) should point to this new `openlibrary/i18n/README.md`.

There's also existing documentation in the comments of
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/__init__.py which should be moved to this README.

While we're at it, this README should include a section on "Testing i18n"

Other relevant pages: https://openlibrary.org/i18n

**Comment by tabshaikh** [comment]
I will look out for what can be done for testing :)

**Comment by mekarpeles** [comment]
@leadsongdog has also had questions about testing i18n; @hornc may be able to shed some light

**Comment by MauAraujo** [comment]
I can do the internationalization document migration.

**Comment by hornc** [comment]
I have just added a paragraph to the wiki instructions here https://github.com/internetarchive/openlibrary/wiki/Contributing-to-Internationalization-(i18n)

**Comment by mekarpeles** [comment]
@hornc can you make sure @MauAraujo's README has everything from the wiki and then point the wiki to that document?

**Comment by tabshaikh** [comment]
This issue had some left out tasks:
Things to be done:
- [ ] Add testing to the Readme
- [ ] Point wiki to the readme

**Comment by LeadSongDog** [comment]
It is quite unrealistic and unnecessary to expect that someone willing to translate a few UI strings will be prepared to endure installation of the entire build toolchain to do so. This is no doubt the reason why 
https://openlibrary.org/books/OL17479512M/Il_Principe?lang=de
https://openlibrary.org/books/OL17479512M/Il_Principe?lang=en
https://openlibrary.org/books/OL17479512M/Il_Principe?lang=fr
https://openlibrary.org/books/OL17479512M/Il_Principe?lang=it
https://openlibrary.org/books/OL17479512M/Il_Principe?lang=es
are barely distinguishable. We need a much lower bar to entry for people to provide basic translation: they shouldn't need to be software gurus and VM wranglers. We just need them to translate a few strings, such as: 
"Edit" "of" "found in the catalog" "by" "want to read" "Subjects" "Places" "Times" "About the book" "The physical object" "ID numbers" "Last edited by" "History" "Buy this book" "Share this book" "You might also like" "Created" and "Download catalog record"
Why not just let interested polyglots fill one or more columns in a spreadsheet, and then leave the conversion to .po format up to someone who doesn't necessarily speak 209 languages?
