### ISSUE TITLE
make /api/import endpoint return HTTP 201 + Location header on creating new record

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1243]
Currently the import endpoints return HTTP 200 responses on success with a body like

`{"edition": {"status": "created", "key": "/books/OL5M"}, "work": {"status": "created", "key": "/works/OL1W"}, "success": true}`

This should be changed to a 201 response, and the response header should include a `Location` pointing to the newly created _edition_ record.

If no item is created, but existing items are modified then the response should be `200`.

**Comment by guyjeangilles** [comment]
@hornc Was this implemented? Also, I'm not sure if this issue is referring to import bots or to users adding books via the site's UI.
