### ISSUE TITLE
error in processing template: /openlibrary/static/build/vendor-v2.js not found

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1255]
I keep getting this error when I search something on dev instance.

![not-found](https://user-images.githubusercontent.com/9248823/46432379-cde12780-c756-11e8-8832-ff21aacd2ed9.png)

**Comment by mekarpeles** [comment]
Have you tried using make to rebuild js?

**Comment by jdlrobson** [comment]
Yeh this was an issue with not running `make js`
https://internetarchive.slack.com/archives/C0ETZV72L/p1538592534000100
