### ISSUE TITLE
Covers not working locally

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1258]
[Per slack](https://internetarchive.slack.com/archives/C0ETZV72L/p1538668611000100), with a vanilla instance I am not seeing covers
![screen shot 2018-10-04 at 2 46 11 pm](https://user-images.githubusercontent.com/148752/46504962-62459b80-c7e4-11e8-884a-11f4d3f10b88.png)

There should be some easy to find guidelines  on how to get this working (or even better.. it should work from the offset!)

**Comment by LeadSongDog** [comment]
Reminds me of #398. Welcome to my world

**Comment by jdlrobson** [comment]
I've got this working and have updated the docs: https://github.com/internetarchive/openlibrary/wiki/Getting-Started/_compare/1800a00a5194729f0d362000ee2a0b262cd45cca...12c04813f3732a2e44db00b55f72994c1a484fa7

\o/

Not sure if there is a more long term solution though. Would be great if this was configured this way out of the box.

**Comment by jdlrobson** [comment]
Resolved by wiki. closing on assumption docker will make this easier.

**Comment by jdlrobson** [comment]
Reopening as Docker has not made this easier and this is hitting people other than me including our new contributor @koderjoker 

I've discovered the config flag upstream_base_url is supposed to make this easier.. by first trying to get a cover locally, and if that 404s trying to obtain the image from the upstream_base_url instead. However this code (openlibrary/coverstore/code.py) doesn't seem to be kicking in for whatever reason (maybe because http://0.0.0.0/covers/ doesn't exist by default? Should that be http://0.0.0.0:8080/covers/ ?).

So from what I can see, disregarding the way cover urls generation is inconsistent the issue is that the covers service is not setup by default and also a problem with the initial data offering (#1846).

Right now the only way to work around this is to edit conf/openlibrary.yml and update the cover uri but that needs to be done every time before you run docker-compose up (which I often forget to do) and opens up the possibility of uploading images accidentally to openlibrary.org.

Can we please prioritise getting this fix? Covers are integral to the frontend, and this is only going to become more important.

**Comment by hornc** [comment]
@jdlrobson  what would unblock you for development here? Going the route of fully dockerizing a local dev coverstore would add overhead of keeping the local ol db and local coverstore in sync -- I'm not sure that is what you want. Do you simply want a representative fallback image for all of the covers in dev, if they have a cover id?

**Comment by jdlrobson** [comment]
The minimum is fixing the fallback... when importing content the thumbnails are in the production cover store but they are attempted to be served by a non existent cover store.

Given the current state of the repo it seems more useful to be able to /view/ covers rather than uploading/changing them.

For me that might be changing the default in the config (basically https://github.com/internetarchive/openlibrary/pull/1753#issuecomment-449538618 but making it read only) and documenting additional steps to get a working and local cover store setup.
