### ISSUE TITLE
Add stylelint error protection

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1259]
[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`)  can detect various errors if configured with the following:

```
		"unit-no-unknown": true,
		"property-no-unknown": true,
		"declaration-block-no-shorthand-property-overrides": true,
		"selector-pseudo-class-no-unknown": true,
		"selector-pseudo-element-no-unknown": true,
		"selector-type-no-unknown": true,
		"media-feature-name-no-unknown": true,
		"at-rule-no-unknown": true,
		"comment-no-empty": true,
		"no-duplicate-at-import-rules": true,
		"no-extra-semicolons": true,
		"no-empty-source": true,
		"font-family-no-duplicate-names": true,
		"font-family-no-missing-generic-family-keyword": true,
```

Fix any offenders you encounter.

**Comment by weatherwaxed** [comment]
Hi! I'd like to take this up!

**Comment by tabshaikh** [comment]
@weatherwaxed sure go ahead :)

**Comment by weatherwaxed** [comment]
This is my first PR, so just to be clear, do you intend for these rules to be added to the existing ones, with configurations that ignore the same files (currently .css, for example)

**Comment by jdlrobson** [comment]
@weatherwaxed this would be a good one!

Stylelint is already set up to check the right files, so this should just be a case of updating the config, fixing any issues and committing the result. It will be a good introduction to the codebase and help guide us writing better CSS on the long run!

**Comment by jdlrobson** [comment]
Well done @weatherwaxed on your first completed pull request!!
