### ISSUE TITLE
Rating form broken on subject page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1265]
When I visit https://openlibrary.org/subjects/fantasy as an anonymous user, I see the ratings form.

The ratings form should be disabled when I am no logged in.
However when I click a star I am taken to ratings.json

When I log in and try to rate the subject again, I also getting ratings.json

Should the ratings form be removed from the subject page?

**Comment by mekarpeles** [comment]
Closing in favor of https://github.com/internetarchive/openlibrary/issues/1244
