### ISSUE TITLE
Lists are broken: Adding subject to list throws JS error

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1274]
Visit https://openlibrary.org/subjects/science
Scroll to "add to list" and try to add the subject to a new list.

When hitting save in the overlay that opens, I hit a JS error.
Seems to be a misnamed variable.

```
VM300:1 Uncaught ReferenceError: pageurl is not defined
    at <anonymous>:1:1
(anonymous) @ VM300:1
science:1773 Uncaught ReferenceError: pageurl is not defined
    at reload_widget (science:1773)
    at Object.success (science:1845)
    at I (vendor.js?v=2ea74a8f8aba88d7fa77b786c5561d57:19)
    at N (vendor.js?v=2ea74a8f8aba88d7fa77b786c5561d57:19)
```

**Comment by Redarcher9** [comment]
Hi.. Can I work on this issue?

**Comment by jdlrobson** [comment]
Go for it!

**Comment by jdlrobson** [comment]
@Redarcher9 how are you getting on with this issue?

**Comment by Redarcher9** [comment]
Sorry I didn't get time to work on this issue.

**Comment by Redarcher9** [comment]
@changezkhan Nope... Feel free to assign it to someone else

**Comment by ChangezKhan** [comment]
@Redarcher9 I'll take it then. Thanks btw.

**Comment by mekarpeles** [comment]
Apologies -- this is a critical bug affecting users and I have a working solution so I think I'm going to step in w/ a fix!

Sorry to step on anyone's toes! <3
