### ISSUE TITLE
Migrate/port to BeautifulSoup4 (bs4)

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1275]
The first error thrown by our new Python 3 Travis CI job, thanks to PR #1273, relates to BeautifulSoup.

The current module will never have Python3 support, but its successor does, so we need to move to the new version. It doesn't look like we make very extensive use of the functionality, so this should be straightforward.

Instructions here: https://www.crummy.com/software/BeautifulSoup/bs4/doc/#porting-code-to-bs4

**Comment by AmulyaReddy99** [comment]
Can I take this?

**Comment by tfmorris** [comment]
@AmulyaReddy99 Sure! No need to ask permission. If you're worried about duplicating work, just post a note to say that you're starting work on it so that others know and can minimize conflicts.

I did a quick scan of the uses of BeautifulSoup and it looks minimal, so hopefully it's a straightforward port (perhaps just a 1 line change and a bunch of testing)

**Comment by cclauss** [comment]
#1454 fixes this issue but opens several more...
* Breaks our Python 2.7 tests
    * [Genshi==0.7.1](https://travis-ci.org/internetarchive/openlibrary/jobs/447905524#L1285)
* Will not pip install on Python 3
    * [pystatsd==0.1.10](https://travis-ci.org/internetarchive/openlibrary/jobs/447928152#L535)
    * [supervisor==3.3.4](https://travis-ci.org/internetarchive/openlibrary/jobs/447914150#L521)
    * [web.py==0.39](https://travis-ci.org/internetarchive/openlibrary/jobs/447918496#L521)
