### ISSUE TITLE
./openlibrary/core/connections.py needs a code review

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1278]
There are a series of at least three syntax errors in ./openlibrary/core/connections.py that can be found by doing:
* __flake8 ./openlibrary/core/connections.py --show-source --select=E901,E999,F821,F822,F823__. 
 
The first syntax error can be solved merely by adding a __pass__ statement but the ones that follow seem to be more complex to resolve.

**Comment by tfmorris** [comment]
Do we know if it's actually used anywhere?

**Comment by cclauss** [comment]
* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/connections.py#L4 defined one class __ConnectionMiddleware__
* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/connection.py#L17 defines a different class __ConnectionMiddleware__

**Comment by mekarpeles** [comment]
@tfmorris I believe this is used in `plugins/openlibrary/connection.py` where it is extended by `IAMiddleware` which is used by `OLConnection` which is used by `openlibrary/plugins/openlibrary/code.py` --

```
# setup special connection with caching support
import connection
client._connection_types['ol'] = connection.OLConnection
infogami.config.infobase_parameters = dict(type="ol")
```

**Comment by cclauss** [comment]
Which of the two ConnectionMiddleware classes does AIMiddleware extend?  Given the lack of imports, I believe it is the one that is in the same file, not the one in core.

**Comment by tfmorris** [comment]
Sounds like the one in core is unused and should be deleted (the only commit to it since creation is mek's removal of whitespace), but I'll double check.

**Comment by cclauss** [comment]
Doh!  One file is __connections.py__ (plural, with a trailing s) and the other is __connection.py__ (singular).
