### ISSUE TITLE
Carousels: Padding regression?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1284]
Proposal is that the padding below the borrow button should be the same as the area above the bookcover.

Not sure if this is regression or just a request for style improvement. @rchrd2 suggests (and @jdlrobson informs) there's a `.carousel-container .slick-slider margin-bottom` that can be removed to make it so the padding is the same above the bookcover (to the top of the carousel container) and below blue button (to the bottom of the carousel container).

Image for reference:
<img width="80" alt="screen_shot_2018-10-08_at_11 22 51_am_160" src="https://user-images.githubusercontent.com/978325/46634026-70f1c280-cb04-11e8-8761-3d7223f2f82d.png">

**Comment by jdlrobson** [comment]
I think I see what's going on here.
The margin-bottom prevents a reflow when moving from the non-js version to the JS version.
Without the margin-bottom the page repaints which is bad for performance.

Not quite as easy as I first thought... any solution will need to ensure they don't break that JS to non-JS transition (most easily replicated using a simulation of a 2g connection).
