### ISSUE TITLE
openlibrary.org is too excellent

### ISSUE THREAD

**Issue by bnewbold** [internetarchive/openlibrary#1289]
I feel openlibrary.org sets too high a bar for a non-profit, community/volunteer-supported project. You make it look too easy!

**Comment by bnewbold** [comment]
cc: @mekarpeles

**Comment by mekarpeles** [comment]
I just did a `git blame` and I think I found the problem:

I think @Num170R, @tabshaikh, @hornc, @jdlrobson, @salman-bhai, @cclauss, @weatherwaxed, @tfmorris, @leadsongdog, @gramstrong, @cbolgiano, @ozzyz, @cdrini et al. are the ones responsible for this issue. 🎉🎉🎉

will not fix? 😅
