### ISSUE TITLE
Move html inline styles to stylesheet 

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1296]
In #1261 @weatherwaxed discovered many inline styles within the html.

While inline styles in themselves are not problematic, having them inside templates makes for difficult to maintain css. It also means repeating css across pages with no central definition which can lead to ui inconsistency.

We should review these inline styles and where it makes sense move them into legacy.less or one of the existing components. If there are any styles on a page not using legacy.less (e.g. homepage) be careful to check they are loaded by the page that needs them.

## How to fix

1) Find places where styles are defined in templates.
2) Check if those styles are duplicated anywhere in static/css folder. If so delete the inline style and explain any differences! (see example below)  
3)  If the styles are unique and not already added, please comment on this github issue and we'll set up some tasks.

Example:
In openlibrary/templates/admin/inspect/store.html there is a rule
```
form.olform tr {
        border: none;
    }
```
However tr's never have borders.
Thus this rule can be removed.

```
colorboxlists x ~/git/openlibrary $ ag "<style" openlibrary/templates/
openlibrary/templates/account/borrow.html
5:<style type="text/css">

openlibrary/templates/account/not_verified.html
6:<style>

openlibrary/templates/admin/cases.html
11:<style type="text/css">

openlibrary/templates/admin/imports.html
157:<style type="text/css">

openlibrary/templates/admin/inspect/store.html
5:<style type="text/css">

openlibrary/templates/admin/inspect/thing.html
2:<style type="text/css">

openlibrary/templates/admin/memory/index.html
11:<style type="text/css">

openlibrary/templates/admin/memory/object.html
11:<style type="text/css">

openlibrary/templates/admin/people/view.html
8:<style type="text/css">

openlibrary/templates/admin/people/index.html
15:<style type="text/css">

openlibrary/templates/admin/waitinglists.html
99:<style type="text/css">

openlibrary/templates/borrow_admin.html
32:<style type="text/css">
357:<style type="text/css">

openlibrary/templates/lists/export_as_html.html
5:    <style type="text/css">

openlibrary/templates/lists/lists.html
16:    <style type="text/css">

openlibrary/templates/status.html
5:<style type="text/css">

openlibrary/templates/type/object/view.html
5:<style type="text/css">
```

## How do we know when we're done?

- [] Searching for <style tags inside the openlibrary/templates folder returns no results.

**Comment by jtj9817** [comment]
Can I try to work on this issue?

**Comment by jdlrobson** [comment]
@weatherwaxed  made a start to this, so please sync up with him before tackling this! I think he's mostly got this problem addressed!

**Comment by mekarpeles** [comment]
Ah, thanks @jdlrobson! @weatherwaxed is there a PR or a `WIP` we can link this to?

**Comment by weatherwaxed** [comment]
Hi, sorry for the delay, I'm at work presently so unable to access my laptop. I'll push my WIP in about 6 hours.

**Comment by Isfaaq** [comment]
Can I contribute to resolve this issue too?

**Comment by weatherwaxed** [comment]
Yes, sorry I have been busy and it slipped out of my mind

**Comment by mekarpeles** [comment]
@jdlrobson can this be closed? How do we know when it can be closed?

**Comment by jdlrobson** [comment]
Probably. It's a bit too broad in scope to be actionable right now.
