### ISSUE TITLE
Carousel buttons overlap border

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1305]
Easily reproducible selecting `Browse` and some subject eg `Fantasy` or `Browse by Subject` and the some subject eg `Fantasy`.

![dropper_buttons](https://user-images.githubusercontent.com/9248823/46741543-ebaa1180-ccad-11e8-9744-bf20fec6ccdf.png)

**Comment by jdlrobson** [comment]
This code will be removed soon as part of #1241 so probably not worth thinking too much about.

**Comment by jdlrobson** [comment]
This was reported about the old jCarousel (which has now been removed) so I'm bolding resolving this. Please open a new bug if there is something wrong with the current implementation.
