### ISSUE TITLE
Advanced search by ISBN breaks

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1308]
Attempt to search ISBN under More | Advanced Search gives this result:
/opt/openlibrary/deploys/openlibrary/0397e81/openlibrary/templates/work_search.html: error in processing template: ValueError: is not in list (falling back to default template)

**Comment by shreyansh23** [comment]
@mekarpeles  
I couldn't reproduce this issue.
I tried searching for a book by ISBN 0689710682 using the advanced search and it searched the correct book.

**Comment by rohitjain00** [comment]
@mekarpeles When I tried searching for "the". It reproduces the error
Try opening this : 
- https://openlibrary.org/search?q=the&mode=everything&m=edit
