### ISSUE TITLE
Create dump of ia metaxml dump regularly

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#131]
Create a dump of ia collections info from metaxml for all the archive.org items referenced in Open Library.

The dump should have 3 columns, ol-book-key, itemid, ia-collection-info-as-json.

I've generated on dump manually and it is available at:

http://www.archive.org/download/ol_dump_2011-12-31/ol_dump_iameta_2011-12-31.txt.gz

The metaxml of an item be downloaded by new metadata API. http://www.archive.org/metadata/opticksortreatisnewt

Edward has a script to download metaxml of all the items on a node. 

http://ia700405.us.archive.org/~edward/ls_dir.php
gives you all the drives on a machine

this reads all the meta XML on that drive:
http://ia700405.us.archive.org/~edward/read_all_meta.php?dir=0

**Comment by brad2014** [comment]
I am presuming these dumps are either for reference or for disaster recovery, yes?

**Comment by hornc** [comment]
I think this relates to #102 although I'm not sure of the end goal. With the custom tag I have just added to these two I have been trying to consolidate all of the archive.org / Open Library synchronisation tasks and figure out the current higher level synchronisation requirements, and then split out some specific issues.

**Comment by hornc** [comment]
closing in tandem with #102 , unsure of the end requirement. Availability API mechanism now exists to provide this information dynamically, and we are deprecating the "subject as tags" mechanism which used to reflect the availability and IA collection info, see #2107
