### ISSUE TITLE
EPIC: Simplify CSS on works and books page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1313]
With #1249 resolved books and works pages were made mobile friendly, however there is still more work to be done.

Much of the render blocking CSS (static/build/page-user.css) which is 24.87KB after gzipping is unused. I reckon we can get that down to at most 10kb and help identify missing and similar components in the styleguide in the process which will help 1092.

Goals
* Books and works page will share a stylesheet page-books.css, which only ships the CSS that's required.
* Non-JS experience will be improved in the process.

**Comment by mekarpeles** [comment]
As we think of children tasks, let's please reference #1313 so we can gauge progress :)

**Comment by jdlrobson** [comment]
This is not really an epic. It's just blocked on #1092
