### ISSUE TITLE
If no search results, import by ISBN (amz)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1322]
Today we are using Amazon to fetch price information for our books, but we can't do that in the case where a user enters an ISBN of a book we don't have.

Proposing that in the case no isbn match is found, we use the same Amazon API to fetch enough information to create the record and then fetch/cache the price.

## Code

In our `openlibrary.yml` file, the following needs to be added:

```
amazon_api:
    key:
    secret:
    id:
```

These keys are then set within `core/lending.py`. The code for fetching price is in `plugins/upstream/code.py` (although there's probably a better place for them). We currently have a method (which we cache the results of) `get_amazon_metadata`. As of now, it only fetches price information.

## Proposal

Consider renaming `get_amazon_metadata` to more accurately reflect its purpose: `get_amazon_price`. Add a new function `get_amazon_edition_data` which can be called from `/search` (i.e. `class search` -- `search.GET()` in `plugins/worksearch/code.py`) to call `plugins.upstream.code.get_amazon_metadata` in conjunction with `plugins/upstream/addbook.py` `addbook.POST` to create the record on Open Library and then redirect to the created work/edition.

When a user hits `https://openlibrary.org/isbn/xxx` and there's no match, we should fetch the `get_amazon_edition_data` and then redirect on success

**Comment by tabshaikh** [comment]
@mekarpeles i think this issue can be closed:)
