### ISSUE TITLE
Requirements.txt missing packages, causing docker build of olbase to fail

### ISSUE THREAD

**Issue by Zacharius** [internetarchive/openlibrary#1324]
Currently docker build of olbase fails with the message '/usr/bin/python: No module named flake8'.  Pyflakes has also been identified as missing. 

I believe the fix is simply adding these packages to the requirements.txt file.

**Comment by tfmorris** [comment]
@Zacharius It looks like @hornc already fixed this. Sorry you weren't given credit for it. For future reference, you don't need to create the PR branch in this repo, it can be in any repo that you have commit rights to. Github knows how to do cross-repository pull requests.

**Comment by mekarpeles** [comment]
@Zacharius p.s. please do still create a PR (pull request) for your changes! @hornc submitted a hotfix to unblock you but it sounds like the solution you have working is a good one moving forward! 🎉

**Comment by mekarpeles** [comment]
> okay the packages have been added to requirments_common.txt and the olbase docker image is building correctly on my machine.

@hornc @Zacharius would this still benefit from Zachary's commits?

**Comment by Zacharius** [comment]
super sorry for late reply. I made a pull request. Tried to follow naming scheme for my branch but I'm not sure about that. I appreciate you humoring me with the hacktoberfest tag, not sure I deserve the credit for such a low effort issue.

Please let me know if I did anything incorrectly with the branch naming convention or the way I made the pull request so I can do things better in the future.
