### ISSUE TITLE
Librarian mode and edit form drop-downs broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1328]
Cannot access librarian mode when editing an edition. Author and language drop-downs

 are broken. Also (and maybe this is intentional) the works form opens at the top of the edition form. This could end up causing users to add edition-specific information to the works page. (I realize the works page is ultimately going away, so disregard if this is just a work in progress.)![fullscreen capture 10122018 91749 am bmp](https://user-images.githubusercontent.com/17739465/46853967-dcd37400-cdff-11e8-827c-7740ceea39f9.jpg)

**Comment by mekarpeles** [comment]
@seabelis always greatly appreciate your feedback. This seems like an issue to me.

**Comment by seabelis** [comment]
Just noticed the ADD ID button is also not working.

**Comment by mekarpeles** [comment]
Thank you, opening this as a 2nd issue so it doesn't get lost!
