### ISSUE TITLE
Book Covers: drag and drop broken, button almost off screen

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1329]
Trash position fixed, but drag and drop does not work at all. Also, SUBMIT button almost off screen. 
![fullscreen capture 10122018 100536 am bmp](https://user-images.githubusercontent.com/17739465/46856530-fb893900-ce06-11e8-804e-b9458a1a189a.jpg)

**Comment by mekarpeles** [comment]
Ah, this is in an iframe. This a regression and a problem likely of the scheme @jdlrobson and I are using with respect to setting <body id="">. With these new changes, we critically need some special case to avoid displaying the header, etc.
