### ISSUE TITLE
Removal of Internet Archive indentifiers by Clean Up Bot

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#1336]
Hi,

[Clean Up Bot](https://openlibrary.org/people/horncBot) is deleting some Internet Archive identifiers. For example, [this change](https://openlibrary.org/books/OL26478341M/La_fantas%C3%ADa_de_la_individualidad?b=10&a=9&_compare=Compare&m=diff). I have detected similar deletions in other books added by me.

The IDs are correct. What is the problem?

Thank you.

Regards,
Daniel

Mentions: @hornc

**Comment by dcapillae** [comment]
Thank you, @mekarpeles .
 
> is it possible an item with the same ID already exists on OL?

No, I do not think so. The [example](https://openlibrary.org/books/OL26478341M/La_fantas%C3%ADa_de_la_individualidad) is a first edition, a book recently published (2018), and it did not exist in Open Library. I uploaded a [copy](https://archive.org/details/2018LaFantasiaDeLaIndividualidad) to IA and created a page for the book in Open Library (I do this very often).

The same bot has removed other IA IDs from books added by me. Some of them are new editions/books that did not exist in Open Library. I do not know why the bot does this. The IDs were correct.

**Comment by hornc** [comment]
Thank you for reporting this @dcapillae. I ran the clean up bot to perform some bulk policy clean ups, and it looks like your items were altered unintentionally. Apologies for that! I will endeavour to identify and re-instate the item ids that I removed incorrectly. Lets' keep this issue open until we agree they are fixed.

**Comment by dcapillae** [comment]
Thank you, @hornc. The most important thing for me is to avoid the deletion of new IDs in the future. The IDs accidentally deleted can be recovered, no problem.

Thanks again for your collaboration.

**Comment by hornc** [comment]
409 archive.org items re-checked and synced both ways with open library. These links should now be all back to how they were, appologies for the over zealous id removal in the first place! Won't happen again!
