### ISSUE TITLE
Editions component on mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1339]
On mobile visit http://openlibrary.org/works/OL15203543W/Meistersinger_von_Nürnberg

![screen shot 2018-10-12 at 12 43 57 pm](https://user-images.githubusercontent.com/148752/46890720-87599000-ce1c-11e8-9d8c-9bb027fa27eb.png)

The interface is very cramped.

Using media queries I think this could be improved to look like this:

![screen shot 2018-10-12 at 12 49 19 pm](https://user-images.githubusercontent.com/148752/46890954-444bec80-ce1d-11e8-8d01-9a4b9d012429.png)

With PDF links:
![screen shot 2018-10-12 at 12 51 48 pm](https://user-images.githubusercontent.com/148752/46891075-a0af0c00-ce1d-11e8-86b5-289b1f3012f9.png)

CSS should live in styles/components/editions.less

**Comment by jdlrobson** [comment]
Help from an actual designer would be appreciated here!

**Comment by dylsteck** [comment]
I can help out with this @jdlrobson 
The main issue is that since some of them have these buttons and some don't, the interface looks cluttered on mobile.

**Comment by jdlrobson** [comment]
I also wonder if a carousel would make sense here.... it would look nicer on both desktop and mobile. Tables are not great ways to display information across different mediums.

**Comment by dylsteck** [comment]
Either a carousel or a re-formatted table would be fine. The only issue with a carousel is click-ability on mobile. I will explore both options

**Comment by jdlrobson** [comment]
@dylsteck any news to report ? I'd like to fix this and several other things early next year!

**Comment by koderjoker** [comment]
@jdlrobson could I take on this issue?

**Comment by jdlrobson** [comment]
@koderjoker right now it's not clear what we want to build. I'd like to see some mocks of the design before jumping into solution mode!

**Comment by koderjoker** [comment]
@jdlrobson after reformatting the interface for mobiles to something like this.
![ttable](https://user-images.githubusercontent.com/30471843/52520135-fee4e200-2c8b-11e9-8c6e-28821fb5ccbe.png)
should we replace the table header with a dropdown menu on top to allow users to select whether they want to sort on the basis of title, availability etc?

Also, after editing I partly feel that we should now use flexbox instead of a table.

**Comment by jdlrobson** [comment]
I think as a first pass we can hide the table header in mobile. Your design looks great!

Let's think about sorting separately. Yes we will probably need JavaScript and some kind of dropdown but what you've got so far is already a massive improvement!

**Comment by koderjoker** [comment]
@jdlrobson  Due to using a table for layout and overlapping of various styles, trying to make the edition component responsive is using far too much css than it should and is getting messy in its approach. For the sake of simpler css, I think that instead of going forward with the table design we should replace the table layout with flexbox.

**Comment by jdlrobson** [comment]
I think it makes sense to retain the table HTML as semantically this is a table (not to mention the table column sorting feature)

On mobile screens we are currently defaulting to making table elemets display block by the method described here:

https://css-tricks.com/responsive-data-tables/

Can you share the CSS you have now? Two sets of eyes might help identify opportunities to simplify it!

**Comment by koderjoker** [comment]
Sure, I'll send a draft pr for the same! 😄

**Comment by cdrini** [comment]
That looks good, @koderjoker ! Would it be possible to develop something a little closer to @jdlrobson 's prototype? The current proposal takes up a LOT of vertical space rather unnecessarily. Coming up with some user stories about who exactly this section is for would make designing it easier. What do you think a user is looking for when they come to this section of the page? How can we make what they're looking for easier to find? How does that change when they're on mobile? But I think this is good progress nonetheless! Also don't be afraid to play around with something more radical; I don't think the current desktop version is particularly well designed :P Like maybe we can have a drop down to contain that extra download information? Etc.

**Comment by koderjoker** [comment]
Sure @cdrini, I'll think this over and give it another shot! 🙂

**Comment by jdlrobson** [comment]
This looks really good to me. While I agree completely with @cdrini about the vertical space and improving this experience, I think what we have so far is clearly superior to what's currently in production (remember it looks like this: :-)) and I'd be willing to merge what we have now on the understanding we'll continue to iterate on it. I leave that decision up to others, but I've removed the WIP tag to encourage that conversation!

![screen shot 2019-03-01 at 3 47 29 pm](https://user-images.githubusercontent.com/148752/53672887-606bf100-3c39-11e9-860b-47a2ef682087.png)
