### ISSUE TITLE
Search bar: drop down clickable area extends over input area

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1347]
When clicking into the search input area, one must go several placeholders into the text input box to avoid activating the drop down - About where the "r" in the default "Search" label is (in Chrome). 

Sorry to be the bearer of bad news once again.

**Comment by jdlrobson** [comment]
Just to clarify that I understand this one.. are you referring to the yellow boxes in these screenshots being click area for the dropdown?

![screen shot 2018-10-15 at 9 49 25 am](https://user-images.githubusercontent.com/148752/46965404-9bd99a80-d05f-11e8-8746-5e0c7fccfc68.png)
![screen shot 2018-10-15 at 9 49 12 am](https://user-images.githubusercontent.com/148752/46965406-9e3bf480-d05f-11e8-80f5-425bd4654619.png)

**Comment by jdlrobson** [comment]
Thanks @glatteis
Can you post some screenshots of how this works with javascript disabled?

**Comment by mekarpeles** [comment]
This (noted by @JeffKaplan is also preventing people from clicking on the first letter of their search to change it

**Comment by mekarpeles** [comment]
This may be addressed by #1362 I'll try to review this today.
