### ISSUE TITLE
Archive.org site search

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1359]
I'm not sure if this should be posted elsewhere given it's regarding the site search on archive.org rather than OL.

The magnifying glass icon disappears when one clicks into the search bar. This causes the text to shift over which is annoying, but sometimes results in the wrong text being highlighted if trying to change existing text; sometimes the new text appears at the end rather than replacing as intended.
![fullscreen capture 10172018 113907 am bmp](https://user-images.githubusercontent.com/17739465/47077707-d5e2a200-d201-11e8-8004-895a46ce58d5.jpg)
![fullscreen capture 10172018 113912 am bmp](https://user-images.githubusercontent.com/17739465/47077709-d713cf00-d201-11e8-8271-409b06ee0f04.jpg)

**Comment by mekarpeles** [comment]
Tagging @bfalling so he can transfer to the archive.org Jira and closing :)
