### ISSUE TITLE
Let's lint our JavaScript with eslint!

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1360]
Stylelint gives us protection from various CSS issues. Let's do the same for our JS.
eslint is the most mature and provides a list of rules [we can make use of if we deem the need.](https://eslint.org/docs/rules/)
```
npm install eslint --save-dev
```
In package.json, add a new command
```
"lint:js": "eslint openlibrary/plugins/openlibrary/js/"
```
Add an .eslintrc.json
```
{
	"root": true,
	"env": {},
	"globals": {
	},
	"rules": {
		"no-extra-semi": "warn"
	}
}
```

We'll set the errors to warn for the time being and as soon as the config is merged we should coordinate with someone to run the fixes and merge to avoid any merge conflicts!

- [ ] npm run lint:js will show me warnings relating to the "no-extra-semi" rule.
- [ ] "npm run lint:js" happens in when I run "npm run test"
- [ ] Do not fix any errors as part of this change!

**Comment by Isfaaq** [comment]
Hi. Can you assign me to resolve this issue?

**Comment by tamtamchik** [comment]
Question, why you do not use one of the presets like https://standardjs.com or https://github.com/airbnb/javascript ?

**Comment by jdlrobson** [comment]
@tamtamchik i can create an issue later but anything that is under  "possible Errors" snd and autofixable is fair game.

We should coordinate with @mekarpeles to run and commit the autofixes and make eslint error rather than warn. 

I want us to get rid of the low hanging fruit !
