### ISSUE TITLE
Hide the page banner on mobile.

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1371]
It's great that you can embed open library books on your website, but I'm not sure such messaging makes sense on mobile and it detracts from using the other features of the site.

![screen shot 2018-10-18 at 9 02 54 pm](https://user-images.githubusercontent.com/148752/47197168-4b8d6180-d319-11e8-8be0-f3c0c365102e.png)

How do we feel about hiding this at mobile resolutions?

![screen shot 2018-10-18 at 9 03 04 pm](https://user-images.githubusercontent.com/148752/47197169-4c25f800-d319-11e8-98ef-a5d00a3fb87b.png)

= checklist
- [] banner doesnt show by default e.g. mobile
- [] banner should show at desktop threshold

**Comment by linkel** [comment]
It does take up 1/5th of the screen, doesn't it? I vote for removing it from mobile.

**Comment by FilippoGuarda** [comment]
i'd be for removing it, someone working on a website probably would open a tab in his computer browser, while a smartphone user is more likely to be looking for informations about a particular book.

**Comment by mekarpeles** [comment]
Enough votes to justify. Let's do it.

**Comment by FilippoGuarda** [comment]
i'd like to work on this, where is the html/ css file related?
