### ISSUE TITLE
ListsLists component shows up with bullet styling

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1388]
Should look like
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#listslists

**Comment by mekarpeles** [comment]
It looks like the styling in general has regressed for this component

**Comment by tabshaikh** [comment]
Okay will began working on this :)

**Comment by mekarpeles** [comment]
@tabshaikh any thoughts on how we should solve this?

**Comment by jdlrobson** [comment]
oh this is an easy fix.. i know what's wrong here.
