### ISSUE TITLE
Author page "Add link" recently broken 

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1396]
Similar to #1328  and #1351 
Precludes adding links to VIAF, ISNI, etc from the Links tab on the Author edit page. Button twinkles when clicked, but no link is added

Replication steps:

* visit https://openlibrary.org/authors/OL5797335A/L._M._Montgomery/edit
* click links tab
* click add link
* expected: a link with a cross shows.

**Comment by jdlrobson** [comment]
Any javascript errors in the console?
