### ISSUE TITLE
Eslint fix no-unused-vars

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1397]
We have eslint linting for our JS. Let's add a rule for [no-unused-vars](https://eslint.org/docs/rules/) as this will remove a lot of dead code. There are 67 errors in the existing codebase that need to be fixed manually. Let's get those fixed.
```
    "no-unused-vars": "error",
```

- [ ] Add the rule no-unused-vars to .eslintrc.json
- [ ] Fix all offenders

Note: some offenders may be exposed by globals and needed by templates. If that's the case make sure the variable is marked with a eslint-disable-next-line comment

**Comment by Atul9** [comment]
@jdlrobson I would like to work on this.
