### ISSUE TITLE
acs4 shows book checked out, but datastore does not

### ISSUE THREAD

**Issue by mangtronix** [internetarchive/openlibrary#14]
This book shows as checked out in ACS4, but current loan is not recorded.

http://openlibrary.org/books/OL6178818M/Shad_run./borrow_admin

Book can be borrowed = True

Borrowed by: None

Available? (what's been borrowed = false)
BookReader = True
PDF = True
ePub = False

ePub fulfillment info:

[
    {
        "loanuntil": "2011-05-11T20:28:31", 
        "resourceid": "urn:uuid:fbe146e4-b766-49b6-81d0-4407cdc816f5", 
        "returned": "F", 
        "until": "2011-05-11T20:28:31"
    }
]

~ $ date -u
Wed May 11 18:40:56 UTC 2011

Check if there is a timezone conversion error (datastore expired early) or other issue.

**Comment by brad2014** [comment]
Old bug.  Just checked to make sure the given title check-out/check-in works.  Reopen if still an issue.
