### ISSUE TITLE
No module named opds?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1409]
```
Traceback (most recent call last):
...
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/plugins/openlibrary/code.py", line 445, in GET
    import opds
ImportError: No module named opds
```

**Comment by tabshaikh** [comment]
I was not able to duplicate the error as opds.py is present in the same folder as code.py then that should not have been a problem

**Comment by hornc** [comment]
@tabshaikh The line that imports it is https://github.com/internetarchive/openlibrary/blob/b0c1152a1785f2cd7c2e52565a6abf00256e33d5/openlibrary/plugins/openlibrary/code.py#L446

and the file it is trying to target, as you say, looks to be https://github.com/internetarchive/openlibrary/blob/b0c1152a1785f2cd7c2e52565a6abf00256e33d5/openlibrary/plugins/openlibrary/opds.py

I think it should be imported in a similar format to all the other openlibrary plugins in that file like
`import openlibrary.plugins.openlibrary.opds`

**Comment by tabshaikh** [comment]
@hornc ya I think just writing it as import opds is causing the error

**Comment by cclauss** [comment]
@tabshaikh wrote:
> opds.py is present in the same folder as code.py then that should not have been a problem

That is true for Python 2 but not for Python 3 or on Python 2 if [`from __future__ import absolute_import` is at the top of the file](https://github.com/internetarchive/openlibrary/blob/b0c1152a1785f2cd7c2e52565a6abf00256e33d5/openlibrary/plugins/openlibrary/code.py#L4).
