### ISSUE TITLE
eslint: no-mixed-spaces-and-tab  rule

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1419]
We have eslint linting for our JS. Let's add a rule for [no-mixed-spaces-and-tab](https://eslint.org/docs/rules/) for consistency.

- [ ] Add the rule no-mixed-spaces-and-tab to .eslintrc.json 
- [ ] Run npm run lint:js and fix all offenders

**Comment by garethmcc** [comment]
I'll grab this
