### ISSUE TITLE
Clean up lists of identifier and classification types

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#142]
Please clean up the lists of classification and identifier types people can choose from in the edit form when editing books.
I know that in the past everyone could add to these lists, but now it's time to get rid of some of them to prevent more junk from being entered.

There are identifiers in the list of classifications (only visible in librarian mode):
- LCCN permalink (same content as LCCN)
- Identicativo SBN (identifier of records in the Italian national
  library, I believe)

I noticed that the number of books with such a LCCN permalink 'classification' has grown in February alone by almost 50%: from 81 to 121 :)

And there are classifications in the list of identifiers:
- Dewey Decimal Classification (DDC)
- Library of Congress Classification (LCC)
- Universal Decimal Classification
- Mathematic Subject Classification

Duplicate identifiers:
- "International Article Number (EAN)" and "EAN". 
- "Deutsche Nationalbibliothek (URN:NBN)", different form of "Deutsche National Bibliothek" (which should be "Deutsche Nationalbibliothek")
## Incorrect identifiers:

The types listed above are just examples of types in the wrong category or duplicate or incorrect types. I propose to add any other identifier and classification types in the comments here.

**Comment by LeadSongDog** [comment]
@bencomp AMICUS is a national union catalogue, administered by Library and Archives Canada. It includes the 10% held _at_ the National Library of Canada. There are distinct Z39.50 services for the two: full AMICUS requires registration every 6 months, NLC-only service does not. Details are at http://www.collectionscanada.ca/amicus/006002-400-e.html

**Comment by LeadSongDog** [comment]
Many of the URLs given at https://openlibrary.org/config/edition should change to https vice http.  Needs an admin to correct.

**Comment by tfmorris** [comment]
Since this is four years old and it sounds like the bulk of the problems were fixed, perhaps the best thing to do is close this ticket and open individual tickets for any remaining issues.

@LeadSongDog In particular, your HTTPS request is a good one, but it's going to get lost here. If you create a new issue with a list of the URLs that need to get changed and their new values, I'm sure someone get it fixed in short order.

**Comment by tfmorris** [comment]
The HTTPS clean was done as part of #725. If there are other issues remaining, please open specific issues for them.
