### ISSUE TITLE
Eslint: Audit global variable usage

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1426]
We have eslint linting for our JS. Let's add a rule for [no-undef](https://eslint.org/docs/rules/) for consistency.

Define the environment in .eslintrc.json:

```
  "env": {
    "browser": true,
    "jquery": true
  },
```

Make sure all other undefined variables are accounted for (see below)

# Checklist

- [ ] Enable no-undef eslint rule.
- [ ] Define the global environment (browser:
- [ ]  Make sure  --config .eslintrc.json is passed in the lint:js scripts section in package.json
- [ ] Beware openlibrary/plugins/openlibrary/js/lazy.js - don't make any changes to minified blocks of JavaScript. Instead disable the rule for these blocks
- [ ] Where a variable is not defined, fix the error.
- [ ]  Where a variable is defined outside the file, disable the rule and note where it comes from
e.g.
```
// startTime is defined inside openlibrary/plugins/openlibrary/js/ol.js
// eslint-disable-next-line no-undef
'loadtime':(endTime.getTime() - startTime.getTime()),

**Comment by ajluong** [comment]
I'm going to take a look at this
