### ISSUE TITLE
Allow deletion of (incorrect) contributors

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#143]
It seems to be impossible to delete contributors from Editions. When I edit an Edition, click the [x] next to a contributor, it dissappears. But after saving the record, all deleted contributors are still there.
Of course I have only tried to delete bogus contributors, like the one on http://openlibrary.org/books/OL25114356M/Book_of_Pure_Logic (it is hard to say what was meant here, my best guess is "the author is also designer, editor and publisher of this book"). But also trying to correct typos I made myself is not possible.

**Comment by salman-bhai** [comment]
@mekarpeles could this be a first timer issue for a feature that we'd like to have under Hacktoberfest?

**Comment by guyjeangilles** [comment]
This is still a bug. Specifically when I try to edit only the contributors in the above URL, my change is not saved. 

@mekarpeles defaulting to assigning you per our slack discussion
