### ISSUE TITLE
Add Realtime Validation to Account Registration Page Realtime

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1433]
The proposal for this issue is (as a progressive enhancement) to use js to show users real-time as-they-type feedback as to whether their username and/or email are available, and if their password meets the criteria.

## Sub-Tasks
The following issues should be created and resolved before this task may be closed.  
- [ ] #2053 - update backend API endpoints
- [ ] #2055 - Add real-time field validation for email, username, password to Account Registration Form front-end

## Reasoning
We recently had a regression #1431 to our account creation page which showed up as a server error when a user tried to register a new account but their username or email was already taken.

We spotted the error because our daily registered users dropped from ~2300 to ~1700 (-500). Our hypothesis is, these 500 users were hitting error-cases but instead of being shown feedback of what went wrong, they assumed account creation was broken and then [the potential patron] bounced.

This also tells us, a shocking 1/5 of users (i.e. 500 a day) are hitting issues when creating an account (either email or username taken, or captcha broken).

**Comment by schalkneethling** [comment]
@mekarpeles I would like to take this one. Three questions:

1. This is only client side work, the backend already handles these scenarios?
2. Do you have an existing regex you use to validate the passwords currently on the backend?
3. What are the API calls that needs to be made in order to determine whether the username or email has already been taken?

Thanks!

**Comment by mekarpeles** [comment]
@schalkneethling I'm **deeply** sorry for dropping the ball and missing your last message -- we've been making it a priority to better delegate the various facets of the Open Library code-base and user experience (including User Registration) to have clearer leads so we're better equipped to deal with the volume of enthusiasm from the community :) this one is on me and my sincere apologies for leaving you hanging.

I'm not assuming you're still available to work on this because a lot can happen in half a year. The questions you asked are the right ones and dignify an answer so I'll do my best to answer them here for whomever is interested in taking this on! :) 

1. There are front-end and back-end components to this task, outlined in #2053.
2. 2. I believe password validation is done within https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/forms.py#L32 (see: `vpass`) but I'm not seeing this password validation enforced where I expect it (https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L30) 🙊(perhaps a followup issue is appropriate to enforce password validation in the accounts/model.py APIs.
3. See #2053 for details as they become available

@schalkneethling thank you for getting us started here with these important questions 🙇

**Comment by guyjeangilles** [comment]
Assigning @mekarpeles per slack discussions since you're assigned to related issues
