### ISSUE TITLE
Developer Data Dumps Download page should present size (gb) for each download file

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1439]
re: @LeadSongDog's comment on #476 
https://openlibrary.org/developers/dumps should show size of dumps (gb)

**Comment by brad2014** [comment]
Assigned to @hornc for tracking, since he has #476, but reassign as appropriate.

**Comment by hornc** [comment]
Done, see: https://openlibrary.org/developers/dumps?b=10&a=8&_compare=Compare&m=diff
