### ISSUE TITLE
The scripts/20YY (year) directories should be removed

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1449]
These scripts were written in legacy Python and [will not be upgraded to run on Python](https://github.com/internetarchive/openlibrary/pull/1272#issuecomment-427703777) so they should be zipped or moved to an archive repo or removed so that this repo contains valid Python code.

**Comment by mekarpeles** [comment]
We can move them to an archive.org item or a separate repo e.g. `openlibrary-archive`.

In general, moving away from python2 is going to be rather challenging (given it will require a port of webpy and infogami

**Comment by cclauss** [comment]
[Webpy is now looking better.](https://github.com/webpy/webpy/pull/483)  It passes the key flake8 tests and passes runtests.sh on all currently supported CPythons _except_ 3.7.

**Comment by mekarpeles** [comment]
Would rather just exclude scripts from our check

**Comment by cdrini** [comment]
Re-opening this as a low priority thing for us to work on later. Here's a processed grep of all such scripts in `olsystem`. Not a _guarantee_ of what's being used on prod, but not a bad measuring stick.

```
./bin/cron/oldump.sh:#python $SCRIPTS/2012/dump-ia-items.py --host db-current --user archive --password $ARCHIVE_DB_PASSWORD --database archive | gzip -c > $iadump.txt.gz &
./bin/cron/oldump.sh:#python $SCRIPTS/2011/09/generate_deworks.py $dump/$dump.txt.gz $dump/$iadump.txt.gz | gzip -c > $dump/ol_dump_deworks_${date}.txt.gz
./etc/cron.d/openlibrary.allnodes:REPORT_ERRORS=/opt/openlibrary/openlibrary/scripts/2010/01/report_errors.py
./etc/cron.d/openlibrary.allnodes:59 23 * * * openlibrary /olsystem/bin/verify-node.sh ol-home && /olsystem/bin/olenv $SCRIPTS/openlibrary-server /olsystem/etc/openlibrary.yml runscript $SCRIPTS/2011/08/expire_accounts.py
```

**Comment by cdrini** [comment]
Actually, this might be a blocker for python 3 migration; we need to know which of these scripts are actively being used...
