### ISSUE TITLE
Check simplejson vs. json in Python files

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1451]
Mentioned by @mekarpeles at https://github.com/internetarchive/openlibrary/pull/1317#discussion_r224674662

[__simplejson__](https://github.com/internetarchive/openlibrary/search?q=simplejson) is used broadly.  Do we want to remove simplejson and just use the Python standard library [__json__](https://docs.python.org/3/library/json.html) module instead?

**Comment by cclauss** [comment]
@cdrini

**Comment by cdrini** [comment]
I'm not too familiar with this ecosystem; is there merit these claims: https://dataweave.com/blog/json-vs-simplejson-vs-ujson-2887b2c128b2 ?

**Comment by cclauss** [comment]
That article was written 4+ years ago.  I see simplejson almost nowhere these daze.

**Comment by cclauss** [comment]
Here are modern benchmarks https://github.com/ijl/orjson#performance

**Comment by cdrini** [comment]
It seems like it's comparable to `json` for small inputs, but `json` seems to be more performant for larger inputs. Those benchmarks are on Python 3; any chance they might be different with python 2?

**Comment by cclauss** [comment]
Who cares about Python 2 anymore?  It is only 140 daze.

**Comment by cdrini** [comment]
:P Ok, let's backlog this until after we get Python 3. JSON is used _extensively_ throughout OL, and I don't want to deal with potential perf issues for some number of months. There's plenty of other stuff to do in the mean time. :)

**Comment by cdrini** [comment]
Created issue here now that we've decided: #2308
