### ISSUE TITLE
Make Search Results page navigable by Screen Readers

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1463]
When a printdisabled reader lands on the search results page, there are a lot of links and information before the actual list of results, and there is no “skip to content” or “skip to results” link at the top of the page.

**Comment by koderjoker** [comment]
@mek with new changes to the search results page it seems that it is more difficult to reach the filters rather than reaching the search results on a screen reader (it reaches the filters after going through all the results on a page). Will this issue change accordingly now?

**Comment by guyjeangilles** [comment]
![new_searh_printdisabled](https://user-images.githubusercontent.com/7256157/68168100-8c293e80-ff5f-11e9-8a78-5c48a3a486e4.png)

It looks like both issues identified in the comments above are no longer a problem. There's nothing in between the search bar and results, and the filters are side-by-side with results. Closing.
