### ISSUE TITLE
How should we concatenate our codebase going forward?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1489]
~~Use __eslint —fix__ to resolve 32 __Unnecessary semicolon  no-extra-semi__ warnings in the Travis output: https://travis-ci.org/internetarchive/openlibrary/jobs/449176082#L1164~~

Notes from @jdlrobson : 
eslint was showing warnings for semi colons. These have since been suppressed.
Fixing them might lead to JavaScript reference errors.
The fundamental problem is that we blindly concatenate JS via a shell script which is highly dangerous.

We need to introduce a JS bundler such as webpack or gulp or rollup and stop relying on `cat` concatenation. It's dangerous.

**Comment by jdlrobson** [comment]
I hope you don't mind but I added some context above. autofixing these is a little dangerous...

**Comment by jdlrobson** [comment]
I'd like us to add some kind of JS tooling into Openlibrary. I'm not sure what people are comfortable with though. Webpack is obviously the gladiator in this arena but it might be a little heavyweight for what we need.

**Comment by jdlrobson** [comment]
A short term solution ^^

**Comment by mekarpeles** [comment]
i'd be in support of moving toward webpack

**Comment by shaneriley** [comment]
Started migrating to Webpack and there's some strict mode errors. Looks like this will require a light refactor of some JS in addition to adding Webpack.

**Comment by jdlrobson** [comment]
I actually have a working webpack migration on my local machine. My approach was to turn all the existing files into exports and adding a new file that does the wiring up. I can share that later today.

The bit I haven't had time to look into is how to incorporate this into the deploy process.

**Comment by shaneriley** [comment]
Sounds like you got as far as I have. While migrating to Webpack, are we adding in Babel transpilation? I was going that route and just creating an all.js manifest with import directives.

Looked like the only file that violated strict rules was lazy.js, and the `with` block was easy to replace.

**Comment by jdlrobson** [comment]
Here's my patch: https://github.com/jdlrobson/openlibrary/commit/533a7df5c911cad01376bf0f1ac57fe2fc43bd9a
Feel free to  pick up where I left off or adapt your patch as necessary... I guess if nothing else it would be good to clarify we're on the same page (and yes.. the patch I have has the with problem :)

> are we adding in Babel transpilation?
I think our code is a long way away from being able to benefit from it, so I don't think this is a blocker - we could easily do this in a follow up. I think we'll need to make use of require/import/exports though, so that might be enough to warrant adding some kind of transpilation.

**Comment by jdlrobson** [comment]
Before adding webpack we'll probably also want to make a decision on #1180 so we know what we need to support (@babel/preset-env, .babelrc, .browserslistrc )

**Comment by shaneriley** [comment]
The level of Babel support I was planning to add was core and transform-class-properties, since I've found class level getters and setters useful. In this project, it might not be. Here was my added dependency list:

```
+    "@babel/core": "^7.2.2",
+    "@babel/preset-env": "^7.3.1",
+    "babel-loader": "^8.0.5",
+    "babel-plugin-transform-class-properties": "^6.24.1"
```

**Comment by shaneriley** [comment]
Regarding the changes, I think this is greater than what I had already started on. I was just making an initial pass at incorporating Webpack by still concatenating the files, figuring the rewriting would come at a later step. This already jumps us ahead a step.
