### ISSUE TITLE
Stylelint: Consistent quotes via 'string-quotes' rule.

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1498]
We use a mix of quote styles in our codebase. Let's standardise on one and add them t [stylelint docs](https://stylelint.io/user-guide/rules/string-quotes/):

[Stylelint ](https://stylelint.io/user-guide/rules/) (which can be run by using `npm install && npm run lint:fix`) 

449 problems with double, and only 324 with single so it seems single is the prefered one here!
```
    "quotes": [ "error", "single" ],
```
### Checklist
- [ ] Update .stylelintrc.json with the correct definition (single quotes suggested, but go with the majority of cases)
- [ ] fix any offenders detected via `npm run lint:fix`

Note to implementor: Make sure you coordinate with somebody with merge rights to submit your fixes as there is a high likelihood you might hit merge conflicts.

**Comment by sameshl** [comment]
I am new and would like to start contributing through this issue.Can I take it up?

**Comment by tabshaikh** [comment]
@sameshl sure you can go ahead and solve this issue :)

**Comment by sameshl** [comment]
I installed stylelint but when I run any stylelint command,I am getting error:
_stylelint: command not found_

**Comment by jdlrobson** [comment]
Try the following
`
cd docker
docker-compose exec web bash
npm install
npm run lint:fix
`

**Comment by utkarsh-raj** [comment]
Does the issue need work @jdlrobson ?

**Comment by jdlrobson** [comment]
I think given the inactivity on this task you can give this a go!

**Comment by utkarsh-raj** [comment]
All right I will get to work.

**Comment by jdlrobson** [comment]
Any updates?

**Comment by shreyansh23** [comment]
@jdlrobson, I think this task again went inactive. Can I give a try please.

**Comment by shreyansh23** [comment]
@jdlrobson @tabshaikh 
`npm run lint:fix` is throwing many linting errors without any change done by me. But earlier my tests were running fine. I am not able to understand why suddenly those errors started coming.
![screenshot from 2019-03-04 01-24-04](https://user-images.githubusercontent.com/32803230/53700808-3e7e9400-3e1c-11e9-80f4-6551aae31d62.png)

**Comment by shreyansh23** [comment]
At majority of places double quotes had been used. So, rule for enforcing double quotes has been added in the PR.
@jdlrobson @tabshaikh Please review the PR
