### ISSUE TITLE
print() is a function in Python 3 in plugins/upstream/acs4.py

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1501]
Fixed in #1661

Part of our __make lint__ output when run on Python 3 is:

$ __python -m flake8 . --count --exclude=scripts/20*,vendor/*  --select=E901,E999,F822,F823 --show-source --statistics__
```
./openlibrary/plugins/upstream/acs4.py:294:21: E999 SyntaxError: invalid syntax
        print request
                    ^
1    E999 SyntaxError: invalid syntax
1
```
While [this fix](https://github.com/internetarchive/acs4_py/pull/1/files) is quite simple to make, ./openlibrary/plugins/upstream/acs4.py is [not in this repo](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/plugins/upstream) but is symlinked in via our __vendor__ directory from https://github.com/internetarchive/acs4_py which has not been modified in the past six years.

There are a few ways to resolve:
1. Merge the fix made in internetarchive/acs4_py#1
2. Remove the symlink and move the acs4.py file into this repo
3. Make sure that this repo is not reliant on acs4.py functionality and remove it from this repo.

**Comment by tfmorris** [comment]
That's actually configured as a `git submodule` so the submodule needs to be udpated.
