### ISSUE TITLE
Activating Reading Log List dropdown shouldn't displace other content

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1507]
One thing which is a bit strange about the want to read button / Lists dropdown is that clicking the dropdown pushes the rest of the content on the page down (e.g. the position of its component -- I think prehaps it's `dropit` -- is `relative` rather than `absolute` and high `z-index`)

**Comment by KhalidRmb** [comment]
Hello! I would like to take this one up as my first issue.

**Comment by mekarpeles** [comment]
Yay! Please do @KhalidRmb! We've got your back, as us as many questions as you'd like :)
