### ISSUE TITLE
116 undefined names on Python 2.7

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1508]
Running __make lint__ on Python 2.7 currently produces this list of _undefined names_
* https://travis-ci.org/internetarchive/openlibrary/jobs/463408266#L493

Each of these have the potential to raise __NameError__ at runtime.  In a compiled language these would be caught by the compiler but more dynamic languages like Python have fewer checks so linting with tools like flake8 becomes more important.

These issues can be typos, missing imports, refactoring mistakes (like the `self` issues), etc.  Please look through the list and try to __solve a few at a time__.  Think like a compiler and try to resolve the name in question.  If it is tricky then leave that one and try to move onto another.  __Don’t try to solve them all in one PR.  ;-)__

**Comment by cclauss** [comment]
@YBthebest Would you be willing to invest a bit of time on this one?

**Comment by YBthebest** [comment]
@cclauss Yes, sounds like a nice one. I have some time today so I'll try to get started on some of them !

**Comment by YBthebest** [comment]
So I managed to bring down the number of undefined names from 127 to 87 in a first run, skipping the ones I didn't fully understand. By mistake I pushed it to the same branch as the other PR that was accepted. How can we fix that little mess? Thanks !

**Comment by cclauss** [comment]
Those mods do not belong on the __pprint()__ pull request.  Perhaps someone can mentor you through rolling them back.

Can you please create a new branch (git checkout master ; git checkout -b fix-some-undefined-names) and make those changes on that _separate_ branch and create a new PR (without the staggering comments).

**Comment by cclauss** [comment]
@YBthebest great work on #1674.  Now I think you see why it says above to only try to solve a few at a time and don’t try to solve them all in one pull request.  The review process becomes quite complex when a single PR contains many unrelated changes to multiple modules of a large codebase.  Smaller PRs _might_ move faster thru the review process.
