### ISSUE TITLE
Original writing system and Romanization

### ISSUE THREAD

**Issue by moyogo** [internetarchive/openlibrary#151]
It would be nice to be able to have entries with title, names, etc. in both original writing system and Romanization, instead of just Romanization.

**Comment by tfmorris** [comment]
Writing system will take care of most needs for author's name (and we have the alternate names field for them), but for works, we also need to be able to have the work title, work & author descriptions, etc in different languages as well as writing systems.  Ideally, text should be tagged with its language as well, so the best version can be selected to present to the user.

**Comment by guyjeangilles** [comment]
@hornc Since you added one of your labels I'm assuming you are willing to be assignee for this issue? 
Note: being assignee doesn't necessarily mean you are the one doing the work for the issue but responsible for collecting information needed to devise a solution. From the wiki:
>At submission and prior to triage, the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on the issues age and context. Let me know your thoughts.

**Comment by kevinc16** [comment]
Hey is this feature still desired? If so I would like to work on this - can I also have some more context to the issue? It seems like for some books there are titles and authors in the alternative scripts of the respective language, is that related to this issue?

**Comment by tfmorris** [comment]
#7652 should have significantly improved things on the MARC import side.
