### ISSUE TITLE
Consistent whitespacing in our JavaScript

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1515]
We use a mix of indentation style in our codebase. Let's apply the [eslint indentation rule](https://eslint.org/docs/rules/indent#enforce-consistent-indentation-indent) rule:

[Eslint](https://eslint.org/) (which can be run by using `npm install && npm run lint:js`) 

```
    "indent": 2,
```
### Checklist
- [ ] Update .eslintrc.json with the correct definition
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

**Comment by usmanmuhd** [comment]
Hey, Can I take this one up?

**Comment by usmanmuhd** [comment]
@jdlrobson Could I get a slack invite on `me@usmanmuhd.com`?

**Comment by jdlrobson** [comment]
@usmanmuhd  did you get one? Let me know if you get stuck with setup or anything!

**Comment by usmanmuhd** [comment]
@jdlrobson I have problems with setting up the docker environment. When I `docker-compose up` I get the error
```
Pulling web (oldev:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling web (oldev:)...
ERROR: pull access denied for oldev, repository does not exist or may require 'docker login'
``` 
If I give N also I get the same error.

**Comment by jdlrobson** [comment]
Hey @usmanmuhd i just switched to docker myself

Did you run

```
docker build -t olbase:latest -f Dockerfile.olbase ..
docker build -t oldev:latest -f Dockerfile.oldev ..
docker build -t olsolr:latest -f Dockerfile.olsolr ..
```

**Comment by usmanmuhd** [comment]
@jdlrobson I ran all he above commands as well.

**Comment by jdlrobson** [comment]
Let's see if we can debug this over Slack (#686) it's going to be tricky to do so over a github issue! cc @hornc

**Comment by usmanmuhd** [comment]
Requested an invite on slack.
