### ISSUE TITLE
Consistency!: Trailing spaces and spaces in parens

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1516]
We use a mix of indentation style in our codebase. Let's apply some  [eslint  rules](https://eslint.org/docs/rules/) and fix these

[Eslint](https://eslint.org/) can be run by using `npm install && npm run lint:js`

```
    "no-trailing-spaces": "error",
    "space-in-parens": "error",
```
At time of writing there are 38 problems to fix (38 errors, 0 warnings)

### Checklist
- [ ] Update .eslintrc.json with the correct definition
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

**Comment by cclauss** [comment]
Similar things could be done on the Python code with __autopep8__, __black__ (my personal favorite) or __yapf__.  These would make mods to pretty much every Python file but the readability improvements are palpable.
