### ISSUE TITLE
It should be possible to run "make" commands outside Docker

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1545]
Run

```
vi static/css/less/colors.less
(sets @beige: red; )

make css
```

Expected:
* BEHOLD! The Open library header has a wonderful red background
Actual:
It's still beige.

```
sudo scratch-head
cd docker
docker-compose exec web bash
make css
```
The header is now red.

This is super confusing..

Ask: Can docker watch for file changes in static/build/ and run `make css js` where necessary?

**Comment by tfmorris** [comment]
How was this done in the non-docker build environment? Wouldn't a tool like Gulp which has watch capabilities built in be more appropriate than make?

**Comment by jdlrobson** [comment]
In a non-docker build, we simply ran `make css` or `make js` or `npm run build-assets`. We didn't need to do `vagrant ssh` to do that. The thing that's confusing is a frontend dev can now run these builds and see the files change, but not see them reflected which has confused at least 2 people so far (myself included). 
 
I'm not so well-versed in docker-development, but at very least we need to make this crystal clear to new contributors so they don't get stuck. #1570 should be the bare minimum to do here to call this done.

Yup something like gulp would definitely be more appropriate (see #1489) but that's a little tangental. We are a long way from getting that, but having some input in that issue will move us along in the decision front!

**Comment by tfmorris** [comment]
Perhaps the following from openlibrary/docker/README.md needs to be moved somewhere that front end devs look:

-----
## Code Updates

While running the `oldev` container, gunicorn is configured to auto-reload modified files. To see the effects of your changes in the running container, the following apply:

* Editing python files or web templates => simply save the file, gunicorn will auto-reload it.
* Working on frontend css or js => you must run `docker-compose exec web make css js`. This will re-generate the assets in the persistent `ol-build` volume mount, so the latest changes will be available between stopping / starting and removing `web` containers. Note, if you want to view the generated output you will need to attach to the container (`docker-compose exec web bash`) to examine the files in the volume, not in your local dir.

**Comment by hornc** [comment]
@jdlrobson it might be good if we talk it through on the call tomorrow morning, but the short(ish) version is that the generated assets (css and js) are stored in what Docker calls a "persistent volume" https://docs.docker.com/storage/volumes/  named `ol-build` and you can get a list of these volumes by running `docker volume list`

These are not directly accessible from the host system (like they were under Vagrant), but the Docker container has control over them. The volumes link above explains the benefits of this approach, but it's possible + likely that not all apply to our situation. On balance I thought it was still the right way to manage the js + css assets to avoid issues with host filesystems.

`make css` runs a command on your host machine, and uses whatever sw and tools you have on your local machine environment which could differ between developers. Running `make` commands inside the container ensures everyone is running and generating the same thing.

`cd docker` + 
`docker-compose exec web make css`
will run the command on the Ubuntu system that runs Open Library and put the results in the volume that the container has access to.

.... now, the `cd docker` part should not be necessary which _is_ extra typing, and not convention. The project root should be the place to run this command from, and we should fix that. The `docker-compose.yml` file should live in the root, the various Dockerfiles should be in `docker/` but all build and compose commands should be run from the project root, as that is the context (this paragraph is mostly an aside, but I think getting the Docker context correct will make running make commands easier)
