### ISSUE TITLE
Make sure donation banner doesn't require jquery before defined

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1550]
You can see the donation banner here:
https://archive.org/includes/donate.php?ymd=2017-11-28&platform=ol
https://openlibrary.org/subjects/biographies?ymd=2017-12-12

The donation banner currently requires the following js (which has a a dependency on jquery):
https://archive.org/includes/donation_banner/donation.js?v=c43a448

The problem we're experiencing is that the donation banner is being loaded at the top of the openlibrary page and its dependency (donation.js) requires jquery to be defined, however, we define it at the bottom of the site (which causes a reference error).

The proposed solution is to remove jquery as a dependency and to instead use https://github.com/js-cookie/js-cookie which has the same contract/signature.

The benefit of removing jquery dependency and switching to js-cookie is:
1) it's lighter weight
2) it removes requirement on 3rd party partners needing additional js
3) it doesn't conflict w/ OL's strategy of including jquery at the bottom of file

cc: @bfalling, @iisa

**Comment by mekarpeles** [comment]
Related issue on Internet Archive's side: https://webarchive.jira.com/browse/WEBDEV-1860

**Comment by himanshuc3** [comment]
Hi. I would like to work on this. Where is this file located in directory structure?

**Comment by mekarpeles** [comment]
This was merged on petabox side
