### ISSUE TITLE
Cache entire homepage to reduce high TTFB

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1553]
The home page currently has a time to first byte (TTFB) [of almost 6 seconds](https://www.webpagetest.org/result/181107_6D_b5d5d65a5c06ce14ee0eefa12a5a4332/).
Every time a user hits this page, many Python functions must execute in different parts, hitting solr numerous times.

Each of these solr hits is cached, but in the case of this page, it might make much more sense to cache the final HTML.

Since memcached is the only caching layer we have right now we'll store the generated HTML for the homepage in memcached.

To be extremely conservative, the cache time should be 5 minutes - as if the loan status of a book changes, a user will think the book's still available.

After this change we will investigate the impacts on memcached memory and TTFB. From this information, we'll have learned about how caching helps our TTFB and improves user performance.

**Comment by LeadSongDog** [comment]
How often is a front page book borrowed? That should inform the cache time, unless the loan itself can trigger a flush.

**Comment by jdlrobson** [comment]
I'm guessing 5 minutes is far too conservative, but means we can defer the problem of caching to later while improving that crucial first visit to our home page. 

two possible ways we can solve this in future and bump the cache time higher:
* using an api/javascript to check the loan status
* not worrying about it until the user clicks the loan button.

**Comment by jdlrobson** [comment]
Related: #1264

I ran another webpagetest job, this time in Singapore (so minimising closeness to data center) but TTFB still very high.. :/ (7s!)

https://www.webpagetest.org/result/181116_WE_2c442a0fcd48562f2e0def3d55ef6a53/

**Comment by jdlrobson** [comment]
I'm also seeing significant HTML savings post-gzip when the HTML is minified. We don't minify any HTML from what I can see.

We could use a library like so:
```
from htmlmin import minify
minify(html)
```
Is there any reason we don't?

Also where would this live? I feel like this would require changes in infogami? (https://github.com/internetarchive/infogami)

@mekarpeles any interest in pairing on this?

**Comment by tfmorris** [comment]
Note that 3 seconds of your TTFB is DNS lookup and SSL negotiation, so not amenable to improvement via caching.

re: minifying HTML - that seems weird. Where does the savings come from? HTML parsing?

The graph from a day ago still shows SVGs not being compressed. That seems like an easy win. On the somewhat artificial 2G test, it looks like it could save 4-5 seconds.

It still shows 40+ covers being downloaded -- almost all of which are probably invisible.

Why is SSL negotiation for covers.openlibrary.org 4-5 seconds when it's only a second for openlibrary.org? Is that a particularly slow server? Does it need some SSL acceleration?

Why are we loading analytics from both archive.org and analytics.archive.org, incurring an extra DNS lookup? Heck, why are we loading anything from archive.org at all? It's bad enough that we need to deal with both covers.openlibrary.org and openlibrary.org just for our own content.

**Comment by jdlrobson** [comment]
The TTFB i am concerned about is the HTML. The image downloads will impact the time for the page to fully load but not the page itself. 

> Note that 3 seconds of your TTFB is DNS lookup and SSL negotiation, so not amenable to improvement via caching
Yes there's not much we can do about dns lookup aside from new servers. but 2/3s is a small portion of that 8s of TTFB... we can minimise the 5s that follows with better use of caching.

Minifying html would shave off about 3kb of the homepage after gzipping meaning less data to transfer to slow connections. The less data to ship the quicker it will ship.

If we had something like varnish that would also minify the html.

**Comment by jdlrobson** [comment]
I noticed during the banner campaign that every visit to Open Library also hits the banner website. This means every page visit in OpenLibrary is making 2 sequential server side http requests.

I'm curious if we moved this call to JS whether we would see a dent in TTFB.

**Comment by LeadSongDog** [comment]
For clarity, will that "entire" homepage cache include at least the first screenful of cover images? As for @tfmorris , I too am mystified why the design for the homepage of openlibrary.org forces fetching from archive.org: it just begs to be misinterpreted as malware.

**Comment by mekarpeles** [comment]
@LeadSongDog because we're missing a ton of covers in our coverstore, we haven't had the resources to fix coverstore and add them, and rather than show blank covers, we fall back to archive.org's cover API when that is the only cover available.

**Comment by LeadSongDog** [comment]
@mekarpeles If that's the only reason, it would seem simpler to either avoid putting those editions on the home page or simply put the placeholder thumbnail there (which will be preferred anyhow for low-graphic users).

**Comment by jdlrobson** [comment]
Could we maintain a local cached proxy to archive.org ?

**Comment by mekarpeles** [comment]
If I understand correctly, I'm not sure we can beyond what caching we're doing (we rely on them for availability, bookcovers, etc)

**Comment by tfmorris** [comment]
Did we ever do a comparison of before and after timings/performance? How much did things improve (or not)?
