### ISSUE TITLE
Adding a code of conduct and issues template to our repo

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1560]
We should probably add a code of conduct and issues template to our repo this will help us getting a defined form of issues.
![community-standards](https://user-images.githubusercontent.com/31198893/48315747-334ef080-e600-11e8-9cb6-43288e0116df.png)

**Comment by himanshuc3** [comment]
I would try to do this.

**Comment by shreyansh23** [comment]
@tabshaikh
 https://archive.org/about/terms.php Will this serve the purpose of CODE_OF_CONDUCT?

**Comment by tabshaikh** [comment]
@shreyansh23 something more like this https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md

**Comment by mekarpeles** [comment]
I think in general we shouldn't create paperwork to create paperwork. this would be a great place for us to document regressions and resolutions as we encounter issues.

At the present it needs say little more than: Be open, inclusive, respectful, and suportive

**Comment by shreyansh23** [comment]
Okay @mekarpeles

I will try if I can submit a simpler version of CONTRIBUTING.md as described by you.

**Comment by shreyansh23** [comment]
@tabshaikh Any suggestion for #1974?

**Comment by cdrini** [comment]
@tabshaikh I'm going to close this, since we now have an issue template, and #2319 is tracking adding a code of conduct.
