### ISSUE TITLE
Broken /account/preferences page

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1561]
![account-preferences](https://user-images.githubusercontent.com/31198893/48315783-9c366880-e600-11e8-88f3-3985f5b17b29.png)

**Comment by himanshuc3** [comment]
Ima try to fix it.

**Comment by tabshaikh** [comment]
@himanshuc3 We are planning to remove the page if it is not used elsewhere before beginning you can wait a bit and as the decision gets finalized that we should direct our time and energy towards this then you could began

**Comment by himanshuc3** [comment]
Fair enough. Thanks for the heads up @tabshaikh .

**Comment by jdlrobson** [comment]
We chatted about this today in the call and decided to remove the frontend for this (but keep backend)

**Comment by himanshuc3** [comment]
Cool. Can i also be added in slack group.My mail is himichhabra14@gmail.com.

**Comment by jdlrobson** [comment]
@himanshuc3 you can ask on #686!
