### ISSUE TITLE
Don't stem author searches

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1567]
This search returns completely unusable results https://openlibrary.org/search/authors?q=berning
I'm guessing that this is because it's being stemmed to "bern" and matched with other things with that stem, including Berne, Berns, etc.

The net results that the handful of Bernings are mixed in among over 500 other search hits.

**Comment by tfmorris** [comment]
I also suspect stop words are being removed from author queries, so that "William A Smith" is equivalent to "William Smith"

**Comment by tfmorris** [comment]
Probably related to #715

**Comment by guyjeangilles** [comment]
This too is still an issue. @tfmorris @cdrini Are one of you willing to be assignee for this issue? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
Definitely related to, and a near duplicate of, #715. Removing the stop word analyzer on indexing is a third issue which needs fixing in addition to the two other problems mentioned.

**Comment by tfmorris** [comment]
Merged with #715 since it's basically the same problem.
