### ISSUE TITLE
Add a field to the Edit form for Distributor

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#157]
In many (older) records in the OpenLibrary, the publisher's name starts with "distributed by". There is a separate key in the definition of Edition records called "distributors", which could be used to hold the distributor's name.
However, there is no field in the Edit form to allow that name to be entered.

**Comment by guyjeangilles** [comment]
@bencomp Can you provide an example url that showcases this issue?

@hornc This seems like an issue in your purview. Can you confirm that this is still the case? Also are you willing to be assignee for this issue?

Note: being assignee doesn't necessarily mean you are the one doing the work for the issue but responsible for collecting information needed to devise a solution. From the wiki:

>At submission and prior to triage, the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on the context of this issue. Let me know your thoughts.

**Comment by bencomp** [comment]
I get 58,000+ results when I search for books published by "distributed by": <https://openlibrary.org/search?q=publisher%3A%22distributed+by%22&mode=everything&m=edit>

To get to an edition, I have to click through some pages and find an edition in the list, like:

- https://openlibrary.org/books/OL23245240M/Pride_and_prejudice
- https://openlibrary.org/books/OL1449213M/Pride_and_Prejudice

These editions have at least one publisher whose name starts with "Distributed by".

**Comment by LeadSongDog** [comment]
@bencomp 
The top six entries account for ca. 21k of those 58k results, that might be addressed en bloc:

Turtleback Books Distributed by Demco Media 8,824
Tandem Library 3,176
Distributed by Random House 2,848
Knopf 2,323
Distributed by Publishers Group West 1,724
Manchester University Press 1,580
Distributed by Crown Publishers 1,203
Sold and distributed in the U.S.A. and Canada by Kluwer Academic Publishers 658
Distributed exclusively in the USA and Canada by St. Martin's Press 652

While there might be some utility to adding that field, we'd need to determine how to handle the subset of cases where the distributor is known but not the publisher. For ISBN-era books, this isn't really a problem, but for older ones it can be.

**Comment by tfmorris** [comment]
I question whether this adds enough user value to invest programming effort in.

@bencomp I know it was a long time ago, but do you remember what definition of the "Edition records" include distributors? 

I don't see it mentioned either here: https://openlibrary.org/about/schema
or here:  https://github.com/internetarchive/openlibrary-client/blob/master/olclient/schemata/edition.schema.json
