### ISSUE TITLE
Docker build and compose context should be project root

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1572]
Docker build and compose commands should be run from the project root, not the `docker/` directory.

I believe this is Docker convention, and is in keeping with other tools such as `make` which expect to be to be run from the project root. The `docker/` dir is there to group multiple docker files to keep the project root cleaner.

Any Docker file / compose that uses `../` as the context will need to be updated, and the README

This will allow in container `make` commands to be run for the OL container from the project root using `docker-compose web exec make {command}` without having to cd to another dir.

I realise this make some `make` commands more verbose to invoke, but I think there are advantages to having a clear separation between commands that are run inside the OL system, and ones that are run on a local dev host. There probably are solutions to make it easier to run these in Docker containers.

As I see it, the commands in the Makefile are meant to be run on the system running OL, and is not for local dev macros etc. Maybe this needs discussion and clarification, because I'm not exactly sure where dev macros _should_ live.

Relates to, and created because of my comment on #1545

**Comment by tfmorris** [comment]
I always thought the subdirectory context was a little unusual, so would support to switching to the top-level directory.
