### ISSUE TITLE
Deprecate /libraries route, keep backend logic

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1579]
We are trying to get to one by making all our pages "v2". 

The following entry points do not need porting but should not be accessible.  Remove any associated templates and get handlers:
https://openlibrary.org/libraries
https://openlibrary.org/libraries/register

**Comment by jdlrobson** [comment]
We chatted about this today in the call and decided to remove the frontend for this (but keep backend)

**Comment by hornc** [comment]
See also #337

**Comment by jdlrobson** [comment]
Hey @hornc  @mekarpeles

so i took a look at this and want to clarify what we mean by keeping backend logic. Is removing all GET and POSTs that use templates fine? Many of the posts render templates on the frontend but im not sure if this counts as "backend" logic.
