### ISSUE TITLE
Mobile: edit book experience needs optimising

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1585]
https://openlibrary.org/books/OL26506403M/212/edit

Various form elements are not rendering in a mobile friendly way.

![2018-11-14 07 50 31](https://user-images.githubusercontent.com/148752/48496410-cba6ca00-e7e6-11e8-9fb8-95aab3fc3fe6.jpg)

![2018-11-14 07 56 12](https://user-images.githubusercontent.com/148752/48496432-d8c3b900-e7e6-11e8-89f6-c0f67401d6fb.jpg)
![2018-11-14 07 56 33](https://user-images.githubusercontent.com/148752/48496441-dc574000-e7e6-11e8-8f1c-e69900290436.jpg)
![2018-11-14 07 56 37](https://user-images.githubusercontent.com/148752/48496457-e24d2100-e7e6-11e8-9b12-96346029b49c.jpg)

### Fixing
The problematic styles (width+float) should be scoped to the tablet threshold defined in static/css/less/breakpoints.less

For instance
```
.formBack {
    float: left;
    width: 830px;
    padding: 10px;
    background-color: #ededed;
}
```
should become
```
.formBack {
    padding: 10px;
    width: 100%; // make it full screen on mobile
    background-color: #ededed;
}
@media all and ( min-width: @width-breakpoint-desktop ) {
.formBack {
    float: left;
    width: 830px;
}
}
```
You will find similar issues with formBackLeft, formBackRight amongst others.

**Comment by iem5** [comment]
I am going to try to work on this over the next couple of weeks.

**Comment by iem5** [comment]
Are those changes supposed to happen in ,less files?
I can't seem to find those lines of code in the breakpoint.less file

**Comment by iem5** [comment]
Correction: I found it in the v2.less file but it was already fixed

**Comment by jdlrobson** [comment]
@anthonyattipoe just assigned myself to make sure I see any follow ups you make! Looking forward to seeing this land!
