### ISSUE TITLE
Removing the last book from a list on list page throws an exception

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1588]
Visit a list you own which just has one item.

e.g.
https://openlibrary.org/people/jdlrobson/lists/OL131254L/new_list

- Click "remove this item"
- A dialog shows. The close icon is off-centered

![screen shot 2019-01-11 at 1 54 14 pm](https://user-images.githubusercontent.com/148752/51061538-7994e180-15a8-11e9-8aba-0c5c890f162f.png)

- Click "Yes i'm sure"

![screen shot 2018-11-27 at 8 49 35 pm](https://user-images.githubusercontent.com/148752/49129890-59be8e00-f286-11e8-805a-3e8a36fcda2b.png)

Expected: the book is removed from the list and the page is reloaded e.g. history.reload();
Actual: The book is removed successfully but a JS exception is thrown instead of some nice user feedback!

```
vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2 Uncaught Error: cannot call methods on dialog prior to initialization; attempted to call method 'close'
    at Function.error (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2)
    at Object.<anonymous> (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:34)
    at Function.each (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2)
    at e.fn.init.each (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2)
    at e.fn.init.t.fn.(anonymous function) [as dialog] (https://openlibrary.org/static/build/vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:34:5357)
    at Object.success (Jon's_favorite_books:687)
    at j (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2)
    at Object.fireWith [as resolveWith] (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2)
    at x (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4)
    at XMLHttpRequest.b (vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4)
error @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2
(anonymous) @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:34
each @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2
each @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2
t.fn.(anonymous function) @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:34
(anonymous) @ Jon's_favorite_books:687
j @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2
fireWith @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:2
x @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4
b @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4
XMLHttpRequest.send (async)
send @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4
ajax @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4
$.ajax @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:224
n.(anonymous function) @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:4
Yes, I'm sure @ Jon's_favorite_books:686
(anonymous) @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:39
dispatch @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:3
r.handle @ vendor-v2.js?v=9aed0c5aac43e3e7d9941b1c8d05ace9:3
```

**Comment by anthonyattipoe** [comment]
I'd like to take a shot at this over the next couple of weeks if that's okay!

**Comment by jdlrobson** [comment]
@anthonyattipoe I've taken another look at this and the bug as originally reported is now fixed, but there's another problem with it. Please see updated description if you are interested in working out what's going wrong here!

**Comment by anthonyattipoe** [comment]
@jdlrobson ok, thanks for the heads up. I'm pivoting to that now. I noticed some js code within the loaded html page for a book list:
<img width="415" alt="html-js-snippet" src="https://user-images.githubusercontent.com/23226524/49467580-cbd82b00-f7d0-11e8-8d1b-62b98c23208f.png">

I tried to trace where that code was generated & added to the html file and found the following in "utils.js":
<img width="291" alt="old_js" src="https://user-images.githubusercontent.com/23226524/49467691-0a6de580-f7d1-11e8-9c79-2db21cd3e0a1.png">

I've tried editing it but seems to have no effect. Any ideas please?

**Comment by jdlrobson** [comment]
Sorry for the late reply @anthonyattipoe  I've been on vacation.
I'm back now and keen to help you with this!

First things first, right now, any changes to JS need to be followed by:
```
docker-compose exec web bash
make js
```

does that make your changes show up?

**Comment by ayushshivani** [comment]
@jdlrobson I would like to work on this issue.

**Comment by jdlrobson** [comment]
Yes regression is still there. utkarsh-raj or ayushshivani either of you can work on this.

Don't worry too much if we end up with multiple patches. That feels like a good problem to have and we have plenty of issues to go round. :)

If you get stuck or learn something while attempting to fix it please report back- it's extremely useful to share problems!

**Comment by Mr-Magnificent** [comment]
Is this issue still open? Can I work on it?

**Comment by jdlrobson** [comment]
@Mr-Magnificent yes please!

**Comment by Mr-Magnificent** [comment]
@jdlrobson sorry I am having trouble running the command `docker-compose up`. Can you tell a workaround or if I can do without docker as a whole?
```
:~/Documents/opens/openlibrary$ sudo docker-compose up
Pulling solr (olsolr:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling solr (olsolr:)...
ERROR: pull access denied for olsolr, repository does not exist or may require 'docker login'

```

**Comment by Mr-Magnificent** [comment]
@jdlrobson  sorry I am having trouble running the command `docker-compose up`. Can you tell a workaround or if I can do without docker as a whole?

```
:~/Documents/opens/openlibrary$ sudo docker-compose up
Pulling solr (olsolr:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling solr (olsolr:)...
ERROR: pull access denied for olsolr, repository does not exist or may require 'docker login'
```

**Comment by hornc** [comment]
@Mr-Magnificent looks like you need to run `docker build -t olsolr:latest -f docker/Dockerfile.olsolr .` to create the ol-solr image

**Comment by Mr-Magnificent** [comment]
@jdlrobson kindly check whether this solves the issue. My best guess was that `this` was not in context in the code and since reload is anyway required then we can just simply reload than to close the dialog and then reload. If you can please do confirm if my assumptions are correct about `this` and whether this solves the purpose. Thanks.

**Comment by qawbecrdteyf** [comment]
Just tested what @jdlrobson had suggested and it seems that it should work. Created a pull request to therefore solve this issue. internetarchive#2474

**Comment by jdlrobson** [comment]
Thank you @qawbecrdteyf for the patch
