### ISSUE TITLE
Add Previews to Open Library editions pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1592]
There are a lot of OL books we don't have -- but maybe we can at least provide google previews for these editions?

**Comment by tabshaikh** [comment]
Yup this is a nice idea to atleast give link to google books previews, can we do this for all books as if a book is not available for borrow we can still show the link

**Comment by LeadSongDog** [comment]
@mekarpeles @tabshaikh 
The first step is to capture the pertinent google id. Where an ISBN is known, it can be found at 
https://www.google.com/search?tbm=bks&hl=en&q=0710062206

Then, other details can be determined from the google id at
https://books.google.com/books?id=jAM6AAAAMAAJ&output=bibtex

**Comment by mekarpeles** [comment]
I'm updating the title to generalize this ticket to adding a "Preview" feature.
We have millions of books which are also previewable through Archive.org which we don't surface to patrons on Open Library.

An idea Preview feature would provide as many integrated options as possible (especially where an Internet Archive copy is unavailable).

I'll create a branch to mock something up.

**Comment by mekarpeles** [comment]
![preview](https://user-images.githubusercontent.com/978325/63645534-37db2600-c6b5-11e9-824c-59ec1564b030.png)
![preview-modal](https://user-images.githubusercontent.com/978325/63645535-3873bc80-c6b5-11e9-9b3e-b66ca9f3b322.png)
