### ISSUE TITLE
It should be possible to edit "fake records"

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1596]
Not missing everywhere. This is the only time I've encountered this. https://openlibrary.org/books/ia:desperation00king_0/Desperation

**Comment by seabelis** [comment]
Another one. https://openlibrary.org/books/ia:desperation00king_1/Desperation

**Comment by jdlrobson** [comment]
Looking at the code this can only happen if a page is a fake record
```
$if not page.is_fake_record():
```
A record appears to be fake if the book was created on the fly and not a real record from the database. Developers should note  this function definition:
```
        """Returns True if this is a record is not a real record from database,
        but created on the fly.

        The /books/ia:foo00bar records are not stored in the database, but
        created at runtime using the data from archive.org metadata API.
        """
        return "/ia:" in self.key
```
This is not obvious to a user, so we really need to make it easy for a user to edit and turn those "fake records" into real books.

**Comment by LeadSongDog** [comment]
If this is generally the case there may be a programmatic fix possible. If the record was created on the fly check the details page on archive.org to get the OLxxxM id then test to see if it has a current target on OL. If not then reimport the is entry and delete the problem fake book.

**Comment by seabelis** [comment]
I don't mind adding the new "real" records, but I cannot delete.

**Comment by hornc** [comment]
Thanks @LeadSongDog for finding that record, I have undeleted OL22398814M as it looks like it is a valid book. If it is a dupe, redirects should be used, or the edition moved to an appropriate work.

@seabelis Where are you finding these fake records linked from? They can't really be deleted because they are generated on the fly based on the id in the URL, it looks like they either redirect, or display what content they can from the archive.org item.  

I don't think users should be seeing these kinds of records, unless they are entering the URLs themselves?

**Comment by seabelis** [comment]
@hornc I've made it a little project of mine to try and consolidate records for books on my own Read/TBR lists. At some point I realized that not all IA books have corresponding records on OL. So when I'm working on a title, I'll search IA to see if there are any unrepresented books there. This was the first time I'd encountered a "fake record". I have since encountered only one more. https://openlibrary.org/books/ia:isbn_0451128915/The_Godfather. It is searchable from IA only, but it does show up on my loans page when borrowed or waiting.

**Comment by seabelis** [comment]
Alright, so now I'm not sure if I should add a record for the second book or not. There are two scanned copies desperation00king_0 and desperation00king_1. One now shows as a valid record on OL OL22398814M and the other is redirected.

**Comment by seabelis** [comment]
Should this be closed. When encountering such an edition, I will usually create a "real" record. Hopefully this does not have any adverse effects.

**Comment by hornc** [comment]
@seabelis I think this can be closed. The risk is you will be creating a duplicate, but I think the 'fake' id will redirect correctly if there already is an edition with the identifier, so the fact that you even end up on one of these records means something is missing.

If there are  a lot of these, it raises the question of how they were left un-synchronised, and that would fall under what I'm trying to collate under the label https://github.com/internetarchive/openlibrary/labels/CH%3A%20sync-ia-ol to improve the ongoing synchronisation between archive.org and OL. From what I've seen, I think these are historical issues?
