### ISSUE TITLE
Author create edit record should show source link

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1619]
Edition records include a link to the source MARC record that was used to create them. Author records used to include the same, but don't any more. This isn't a new issue because I've seen 2017 author records which also exhibit the issue.

Here's a recent one which does. The comment on this record: https://openlibrary.org/authors/OL7433603A/Stefan_Ap%C2%A9%C5%81thy

should look like it's complementary edition record: https://openlibrary.org/books/OL26582866M/Die_Mikrotechnik_der_thierischen_Morphologie

which points back to: https://openlibrary.org/show-records/ia:diemikrotechnikd2190apth

**Comment by tfmorris** [comment]
I suspect this is because the importer is not including the correct `machine_comment` in the update.
Here's an earlier example:
https://openlibrary.org/authors/OL2666900A.json?m=history

```
{
comment: "initial import",
author: "/people/ImportBot",
ip: "127.0.0.1",
created: "2008-10-19T23:55:47.958486",
data: "{"machine_comment": "marc_university_of_toronto/uoft.marc:2679117007:1081"}",
key: "/authors/OL2666900A",
action: "update",
author_id: 17874995,
changes: "[{"key": "/authors/OL2666900A", "revision": 2}]",
id: 26984722,
machine_comment: "marc_university_of_toronto/uoft.marc:2679117007:1081",
revision: 2
},
```

This gets rendered in the web interface as:

October 19, 2008 | Edited by ImportBot | Found a [matching record](https://openlibrary.org/show-records/marc_university_of_toronto/uoft.marc:2679117007:1081) from [University of Toronto](https://archive.org/details/marc_university_of_toronto) .

**Comment by hornc** [comment]
Some authors have `source_records` as a field, which is a general source field which does not have to be added at the first import. 
https://openlibrary.org/authors/OL104493A.json

Having all these `source_records` displayed consistently on the Works, Editions, and Authors pages would be nice.

This `machine_comment` isn't well named, but I guess indicates where the _first_ import came from and therefore is appropriate to be shown in the history.
