### ISSUE TITLE
List of records from CC0 sources

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#162]
There is a lot of data available from other CC0 sources, like:
- [CERN bibliographic data](http://datahub.io/dataset/cern-library-bibliographic-data)
- [Cambridge University Library data set](http://datahub.io/dataset/culds_1)
- [Harvard Library data](http://datahub.io/dataset/harvard-library-catalog)
- [other sets (not all CC0, some probably are)](http://datahub.io/group/bibliographic)

There are a lot of records in these sets. The Harvard set has about 12 million records, which will overlap with existing records, but OL users can never add so many records and OL could use more records. There is MARC21, MARCXML and possibly other formats.

**Comment by guyjeangilles** [comment]
This seems like an `Epic` that should have an issue assigned for each data source.

**Comment by tfmorris** [comment]
My 2013 comment about prioritizing cleanup and dedupe before attempting import large quantities of data still applies. We've made a little bit of progress, but there are still tons of duplicates, conflated records, and other data issues which make it very difficult to do a good job of importing new data.

**Comment by mekarpeles** [comment]
This issue is a useful record of sources that are available to us. We're in the process of loading more sources, but this issue as written isn't actionable (and is more of an epic). Will let @hornc spec out our next import epic and am going to close this one.

**Comment by hornc** [comment]
Actionable:  
For each source identify and validate format.

If the format is MARC21 (or can be neatly converted to MARC21 using yaz-marcdump): upload to an ol-data item to hook into the bulk-MARC import pipeline.

**Comment by hornc** [comment]
datahub.io looks to be stale. We already had data taken from these sources on archive.org.

The CERN and Harvard data did not have the binary MARC exposed suitable for bulk importing. I have put the .mrc files on the items:

https://archive.org/details/cern_marcxml
and
https://archive.org/details/harvard_bibliographic_metadata

**Comment by tfmorris** [comment]
Yes, datahub.io is very stale. Some of the data sets, like CERN, haven't changed in a decade, but others like Harvard's should probably be checked to see if there's a more current version before using. Bibliographic data is relatively stable, but they have hundreds of librarians improving their cataloging over the years.
