### ISSUE TITLE
Don't import bad data

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1620]
The import: https://openlibrary.org/recentchanges/2018/11/21/bulk_update/54739187
which created three records, is faulty in a number of respects.

The author record contains the highly improbably character sequence "©Ł" as part of the author name. Bad data such as this shouldn't be imported.

An author record with the correct spelling already exists (albeit with no works attached); https://openlibrary.org/authors/OL6659409A/Stefan_Ap%C3%A1thy

The work already exists: https://openlibrary.org/works/OL17771105W/Die_Mikrotechnik_der_thierischen_Morphologie_eine_Kritische_Darstellung_der_Mikroskopischen_...
yet a new duplicate work was created.

Harvard's catalog record for the two volumes indicates the correct spelling for the author name, so it got corrupted someplace in the processing pipeline: http://fig.lib.harvard.edu/fig/?bib=004953004

And I won't even ask why it was scanned again when a perfectly good set of scan existed

**Comment by hornc** [comment]
@tfmorris this is https://openlibrary.org/people/ImportBot which is an existing bot that has its own existing and long term mechanisms in place, my recent imports have been performed by https://openlibrary.org/people/horncBot   The plan is to bring the existing ImportBot updates in line with my recent work. I don't control ImportBot though.

**Comment by tfmorris** [comment]
@hornc Who controls ImportBot and where does its code live?

**Comment by LeadSongDog** [comment]
Between ImportBot and the old WorksBot, we now have five (count 'em) different work records and a corresponding five edition records for a single published edition. 

https://openlibrary.org/works/OL15875778W/L'%C3%A9volution_du_dogme 
has https://openlibrary.org/books/OL24784310M/L'%C3%A9volution_du_dogme
https://openlibrary.org/works/OL15847455W/L'%C3%A9volution_du_dogme
has https://openlibrary.org/books/OL24756718M/L'%C3%A9volution_du_dogme
https://openlibrary.org/works/OL15745260W/L'%C3%A9volution_du_dogme
has https://openlibrary.org/books/OL24656394M/L'%C3%A9volution_du_dogme
https://openlibrary.org/works/OL12312861W/L'_%C3%A9volution_du_dogme
has https://openlibrary.org/books/OL18062198M/L'_%C3%A9volution_du_dogme
https://openlibrary.org/works/OL12312860W/L'_evolution_du_dogme
has https://openlibrary.org/books/OL21872777M/L'_evolution_du_dogme

All have the same author. The title representations vary in whitespace and accentuation. The publisher representation vary in spelling (omitted particles in some versions). The dates are all 1919. Three have the same OCLCn shown, though all five imported MARC records showed it..  (The three shown came from IA, showing "035    $a(OCoLC)7373965", while the two not shown were from BCL, showing "035    $a(OCoLC)ocm07373965")

Until these very common variations can be handled properly, should we really continue importing them? They're just going to have to be retro-merged.

**Comment by LeadSongDog** [comment]
@tfmorris 
ImportBot appears to be the work of @EdwardBetts but he may have moved on from OpenLibrary to other activities: http://edwardbetts.com/wiki/programming_journal/

**Comment by tfmorris** [comment]
@hornc @mekarpeles repeating my May 21 question - who controls ImportBot and where does its code live?

**Comment by cdrini** [comment]
@tfmorris Does this help (see `import-bot.conf`): https://github.com/internetarchive/openlibrary/issues/2149#issuecomment-496978069

**Comment by tfmorris** [comment]
@cdrini Yes, perfect. 

To quote:

> command=/olsystem/bin/olenv HOME=/home/openlibrary OPENLIBRARY_RCFILE=/olsystem/etc/olrc-importbot python /opt/openlibrary/openlibrary/scripts/manage-imports.py --config /olsystem/etc/openlibrary.yml import-all

So, this code:

https://github.com/internetarchive/openlibrary/blob/9655f1d0fd21777465e6ed60de5257d32ffc416c/scripts/manage-imports.py#L136

with the `import-all` subcommand.

**Comment by hornc** [comment]
I think the root of this problem was bad handling and conversion of MARC8 encoded MARC records on archive.org, which contributed to bad matching. I've fixed some big issues on how those are handled, so we should not be encountering more of these with new data imported from archive.org.
