### ISSUE TITLE
Bulk importer creating new works unnecessarily

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1621]
This newly imported edition: https://openlibrary.org/books/OL26584284M
caused the creation of a new work: https://openlibrary.org/works/OL18007010W
instead of reusing the work: https://openlibrary.org/works/OL199732W
that already had five editions attached to it.

I won't get into the debate about how to delineate editions, because, even though the printings, separated by a couple of years, appear to share identical texts, the image plates are ordered slightly differently between the two.

Independent of that, these are clearly the same work and should have been attached to the existing work, rather than creating a new one.

**Comment by tfmorris** [comment]
Here's another recent example:

work with 5 editions: https://openlibrary.org/works/OL3959261W/England_Ireland_and_America
newly created redundant worK: https://openlibrary.org/works/OL18005594W/England_Ireland_and_America
source record: https://openlibrary.org/show-records/ia:englandirelandam01cobd

**Comment by hornc** [comment]
Again, my recent work was not on ImportBot directly but on the public API endpoints. I was using my own bot to make reimport edits by hitting the API I had improved.

ImportBot _should_ be using those enpoints, and does in at least some cases (as noted in the wiki page) - I've just tried following its code to see exactly what is doing, and it looks like it may also have a more direct access to the db via https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/imports.py

(Which I think is yet another import path not currently listed on the wiki :( )

**Comment by tfmorris** [comment]
@mekarpeles re: the comment by @hornc above - Who owns ImportBot? Where is the source code located?

**Comment by LeadSongDog** [comment]
> @mekarpeles re: the comment by @hornc above - Who owns ImportBot? Where is the source code located?

@tfmorris I can't be certain, but it looks like ImportBot was the work of @EdwardBetts 
(http://edwardbetts.com/wiki/programming_journal/ may refer)

**Comment by hornc** [comment]
@tfmorris The importbot code is committed in the main repo, https://github.com/internetarchive/openlibrary/blob/master/scripts/manage-imports.py is the entry point to the bot. It is run regularly on a cron schedule on one of the main Openlibrary servers. @LeadSongDog is correct that Edward created it. I have not worked on ImportBot directly, but have been focusing on the shared API that ImportBot uses.

I have a suspicion that importBot may sometimes bypass some of the API interface, and that it needs a full review, but I have not begun this.

**Comment by hornc** [comment]
Here are some recent examples created sequentially from imports via the bulk MARC endpoint /api/import/ia

more recent sequential work imports:
https://dev.openlibrary.org/recentchanges/2019/07/17/bulk_update/58741594
https://dev.openlibrary.org/recentchanges/2019/07/17/bulk_update/58741595
https://dev.openlibrary.org/recentchanges/2019/07/17/bulk_update/58741596

In the following example, the matching was able to tell the Author it just created already existed so re-used that, but was the work not found?

https://openlibrary.org/recentchanges/2019/07/17/bulk_update/58734159
https://openlibrary.org/recentchanges/2019/07/17/bulk_update/58734160
https://openlibrary.org/recentchanges/2019/07/17/bulk_update/58734161
https://openlibrary.org/recentchanges/2019/07/17/bulk_update/58734162

**Comment by hornc** [comment]
The above specific examples that show the successful matching  in the case of newly created Authors, but failing matches in the case of Works should hopefully be enough to identify what is going wrong here, there is a matching mechanism, but it's not functioning for recently created works.

**Comment by hornc** [comment]
looks like my recent examples are both examples of series, and those are different volumes.  The import is not pulling the available volume number from `245$n`  , and is also doing something incorrect with the 880 fields in `edition_name`

**Comment by LeadSongDog** [comment]
Some explanation of those 880 fields is available at:
(https://www.loc.gov/marc/bibliographic/bd880.html)
(https://www.loc.gov/marc/bibliographic/concise/bd880.html)
{https://www.oclc.org/bibformats/en/8xx/880.html)
