### ISSUE TITLE
source_records not visible anywhere

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1623]
When I look at: https://openlibrary.org/books/OL22235433M/Gra_mmaire_au_secondaire_100?m=diff&b=3
I see "source_record" fields being added which aren't visible anywhere in the UI. 

In this particular case, it's the same as the `ocaid` so it is possible to click through to the source, but I've seen other cases where this isn't true.

If these `source_records` are going to be important, it should be possible to easily view them.

**Comment by guyjeangilles** [comment]
Seems like a front-end issue. Assigning jdlrobson (not tagging per request) per slack discussions.

**Comment by jdlrobson** [comment]
Are source records important for the product.  If so how should they be displayef in interface?

**Comment by tfmorris** [comment]
I suspect it was @hornc who added the `source_records`, so he could probably provide information on their intended use and if/how they should be displayed.

**Comment by tfmorris** [comment]
@mekarpeles Did you mean to close this after saying it would be useful for librarians like @seabelis ? 

I agree that it would be very useful for editors (aka librarians) as well as software/data engineers tracking the provenance of problems.

As an example, [this edition](https://openlibrary.org/books/OL44269942M) has an easy to find link at the bottom of the page that goes to a nicely formatted [MARC record](https://openlibrary.org/show-records/marc_columbia/Columbia-extract-20221130-027.mrc:76220368:1145) where we can see that the author's given name is included in a `100$q` subfield. Having such a link at the bottom of the [author page](https://openlibrary.org/authors/OL11780500A?v=1) would make it easier to discover that information got lost during the import.

**Comment by seabelis** [comment]
Source records are extremely helpful.

**Comment by seabelis** [comment]
Reopened because having the source record available is super helpful when dealing with conflation. For example, [this](https://openlibrary.org/authors/OL559396A/Robert_Cooper?m=history) says the record was imported, but doesn't say where from.
