### ISSUE TITLE
Should "Is it known by any other titles? Perhaps in another language?" field be moved from edition to work level?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1625]
I don't usually bother filling this out for each edition because it seems redundant. The title of the work record already provides the original title (or should). The "translated from" field provides this as well and it's not practical to add the titles of all translations to each edition record. I do make an exception when there has been a change to the title in that edition's language (i.e. title has been changed to tie into film release) and for transliterated titles. But I'm not even sure how useful this is because I don't think that field is included in title search. 
Possibly related to https://github.com/internetarchive/openlibrary/issues/412.

**Comment by LeadSongDog** [comment]
The "Is it known by any other titles? Perhaps in another language?" field is useful to distinguish variant cataloguing of one edition. I would leave it there. Some librarians will have left "A" or "The" prefixes intact while others remove them, for example.  The union list of distinct edition titles that are linked to a single work is usually shorter than the full list of editions. A count of edition titles and of languages could be sensible summary data to present to the user: "I, Robot has editions in 7 languages". This would also be a useful metric of the universality of the work. The first of all the editions' publication dates should be treated as the original language and that edition title should be used for the work title.
