### ISSUE TITLE
Fix HTML Validator errors for Edition page

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#163]
When I paste an Edition page into the W3C Markup validator, it returns a lot of errors.

The XHTML Transitional validator returns errors like;
- `<meta>`, `<link>`, `<input>`, `<br>`, `<img>` tags not closed
- there is no attribute "charset" on `<style>`
- there is no attribute "placeholder" on `<input>`
- `<p>` found in `<span>`
- `<style>` found in `<div>`
- `<h3>` and `<div>` found in `<a>`
- `<div>` found in `<ul>`
- `<div>` found in `<h2>`
- some unknown attributes on `<div>`: "aria-labelledby", "role", "tabindex", "unselectable"

Furthermore I have been wondering whether putting title, by-line, edition with `<strong>` and `<br>` inside `<h1>` is good markup. I think it isn't and it may influence the semantic markup as proposed in #84.

**Comment by anandology** [comment]
+1 for switching to HTML5.

**Comment by hornc** [comment]
w3c validator url to validate an Edition:
https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fbooks%2FOL8870170M%2FThe_War_of_the_Worlds_%28Barnes_Noble_Classics_Series%29_%28B_N_Classics%29

Ol now uses the HTML5 doctype `<!DOCTYPE html>` so that is progress. There are still many validation errors though.

I'm hoping the many "Element div not allowed as child of element span in this context." will be removed with the planned reworking of works and edition pages.

**Comment by salman-bhai** [comment]
@mekarpeles @hornc is this still an Issue? Is it possible to add a `Hacktoberfest` label to it or will it be too complicated?

**Comment by hornc** [comment]
This is still an issue. Probably a larger issue around standardising html across all pages and moving to HTML5. Bumping for discussion and looking for volunteers.

**Comment by mekarpeles** [comment]
@jdlrobson do you have thoughts on this re: priority? @koderjoker expressed interest in being point on this or finding someone to lead this. Would love your thoughts if there are other front-end tasks you think should be taking priority

**Comment by jdlrobson** [comment]
Yes. Let's switch to html5 doctype and fix these errors. Invalid HTML can be a huge nuisance (ui regressions, failing js, unreadable content.. even security problems).

They should also be straightforward to fix so if we know about problems lets resolve them with high priority.

**Comment by brad2014** [comment]
@koderjoker, let me know if you are still working on this.

**Comment by koderjoker** [comment]
@brad2014 since I'm not in the middle of working on it and will pick it up most likely after 2-3 weeks, feel free to un-assign me in case a newcomer wants to work on it.

**Comment by brad2014** [comment]
I'll leave it as is, no rush! When you pick it up, set the "State: Work In Progress" label.

**Comment by guyjeangilles** [comment]
@koderjoker Any updates to share?

**Comment by koderjoker** [comment]
@guyjeangilles I paused this issue in favour of working on the navbar at iaux at that time. If no one takes on this issue by the time I'm back (~3 weeks) I'll start working on it and breaking it up to make it more accessible to newcomers.

**Comment by mekarpeles** [comment]
@koderjoker this issue is currently marked as Work In Progress, how would you like us to label this issue?

**Comment by koderjoker** [comment]
Paused working on it for the meantime, please remove the Work in Progress label
