### ISSUE TITLE
Should author names and titles be in their native alphabets?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1630]
I don't see this addressed anywhere and I'm not sure what the preference is. If a title or author name is in a non-latin alphabet, should the original be used or the transliteration?

**Comment by LeadSongDog** [comment]
I would say list alternates in all alphabets for which we have reliable transliterations. VIAF and Wikidata are useful for ascertaining these. The primary entry should likely be either in the native alphabet or Latin transliteration.

**Comment by LeadSongDog** [comment]
@tfmorris, The thing is, we’ve not had any progress on changing “What’s the original book” to a work identifier: it is still just a string. Only by putting the translation under the original language work do we have a sensible
