### ISSUE TITLE
Regression on Home Page (Bookcover Height)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1642]
### Please Describe the problem (or idea)

> What did you expect to see that you didn't?

expected bookcovers to be same height

### Please show us where to look

`https://dev.openlibrary.org`

![2018-11-25-122236_1600x900_scrot](https://user-images.githubusercontent.com/978325/48984150-08a77200-f0ad-11e8-9092-35a2d4a83c66.png)

**Comment by mekarpeles** [comment]
setting a `height` of ~200px on `.book img.bookcover` looks about right

**Comment by cdrini** [comment]
Hmmm, I think this might actually be better. Setting the height messes the aspect ratio (which is what we had in the past) so that landscape books look "crushed". Maybe just aligning the borrow buttons might be enough?

**Comment by cdrini** [comment]
Actually, aligning everything to the bottom might be best; then it'll look like the display shelves at a physical library 😍

![example library display](http://creativelibraryconcepts.com/wp-content/uploads/2017/06/oval-library-display-shelf-1024x683.jpg)
src: http://creativelibraryconcepts.com/library-displays/

**Comment by jdlrobson** [comment]
These were previously aligned to the bottom so something has broken that. Using height alone wont cut it as these covers are variable heights and width also needs to be fixed.

Let's do a git bisect and work out when the issue arrived... once we have that information its probably just making sure that css rule doesnt interfere with this one.

**Comment by mekarpeles** [comment]
Removing `height: auto` from `common.less` `div#contentBody img` does the trick
