### ISSUE TITLE
New Issue Template?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1655]
## Bug

> **Evidence**: What is happening? What are the symptoms? (screenshot here if possible)

> **Expectation**: What should by happening?

> **Details**: Logged in? Browser type/version? Operating system? Production/dev/local? (if relevant)

> **Reproduce**: Steps to reproduce problem:

`https://openlibrary.org/...`

> **Solution**: Proposed solution? Solution requirements?

> **Stakeholders**: @ tag stakeholders of this bug

## Feature

> **Problem**: What problem are we solving?

> **Audience**: Who is the audience which benefits from this feature?  e.g. power-users of lists

> **Need**: What evidence do you have this feature is important to this audience? What can't we do because this feature does not exist? What must we do instead because this feature doesn't exist? How many users will be impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

> **Examples**: Has this feature pattern be proven? What other service does something similar?

> **Constraints**: Are there requirements for how this feature needs to appear or be implemented?

> **Implementation**: How would you go about implementing this?

> **Risks**: What are the tradeoffs? What could go wrong? Who may be affected by this feature?

> **Stakeholders**: Tag stakeholders / parties invested in this feature

**Comment by mekarpeles** [comment]
See also: #1656

**Comment by jdlrobson** [comment]
I'm not sure about "Solution: Proposed solution"

If youre non technical this is offputting if you are technical you are likely wrong 😂

Could we phrase this as "Possible solutions" to keep this open ended?" and encourage discussion (and consideration of other solutions) rather than diving in and writing code?

Apart from that this seems good to me.

**Comment by jdlrobson** [comment]
@mekarpeles any thoughts on my feedback above..?
