### ISSUE TITLE
Fix author pages UI regression

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1658]
## Bug

> **Evidence**: What is happening? What are the symptoms? (screenshot here if possible)

![screen shot 2018-11-26 at 11 19 33ampst](https://user-images.githubusercontent.com/978325/49041472-2c84b980-f17a-11e8-9ae7-d3dc30d20fd6.png)

> **Expectation**: What should by happening?

- no `stars` component should be showing on authors page
- `Add to list` should be full width
- floating issues should be resolved

> **Details**: Logged in? Browser type/version? Operating system? Production/dev/local? (if relevant)

> **Reproduce**: Steps to reproduce problem:

https://openlibrary.org/authors/OL1165820A/James_Patrick_Chaplin on production

> **Solution**: Proposed solution? Solution requirements?

- Clearfix
- fix logic so stars don't show up

> **Stakeholders**: @ tag stakeholders of this bug
@jdlrobson

**Comment by jdlrobson** [comment]
Looks like previously the stars were in the html but hidden by CSS.

Time for a proper solution... removing this in the html.

That should also take care of the floating issue.

**Comment by jdlrobson** [comment]
(Will take a look tonight)

**Comment by jdlrobson** [comment]
Poking at this now.

Im also seeing different things on dev and production...https://dev.openlibrary.org/authors/OL1165820A/James_Patrick_Chaplin is more mobile friendly.

Given the earlier issue with the subjects homepage  i think something went wrong in a rebase somewhere...

**Comment by LeadSongDog** [comment]
On production, Î can no longer add links fromage authors to VIAF or ISNI urls.

**Comment by jdlrobson** [comment]
@LeadSongDog can you open a new bug with replication instructions? I'll look into that tomorrow.
I'd like to keep this conversation focused on the UI regressions... which I believe 
61d02ea should take care of.
