### ISSUE TITLE
Moving edition sometimes strips data from target work

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1662]
### Please Describe the problem (or idea)
I moved a stray edition of Hamlet to the primary work and almost all work-associated data was deleted from the target work.

### Please show us where to look
https://openlibrary.org/works/OL15203981W/Hamlet?b=52&a=51&_compare=Compare&m=diff

### Browser, version, and operating system
Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Windows 7 Professional

### Reproduce
I have seen this only one other time so I cannot give steps to reproduce. There was nothing out of the ordinary in the method used to move the edition.

**Comment by cdrini** [comment]
Related PRs where feature was introduced:
- #661
- #700

**Comment by cdrini** [comment]
@seabelis A few questions for you:
1) Could you post the link of the edition as well?
2) How did you restore the lost information?

**Comment by cdrini** [comment]
None of that code seems to be relevant to this issue. This is the python command that's called after the "Submit" button is hit:
https://github.com/internetarchive/openlibrary/blob/345e2815ea5f5b5895bcbb2c1b2d1f6113284391/openlibrary/plugins/upstream/addbook.py#L631-L660

Note specifically lines 647 and 652. The edition is loaded from the database (so it's the latest version before the changes), and its work is loaded from this version. Only these 2 items are edited (as far as I can tell; I looked at the meat of operation in the [SaveBookHelper](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/addbook.py#L377) class).

My current hypothesis is that double-clicking the save button might cause a weird race condition where the first request operates successfully, but then the second request has the *old* work data in the formdata, but the *new* work key, because it polls from the database.

**Comment by cdrini** [comment]
This would also be an issue if 2 users are editing the file at the same time. 
Consider:

| Time | User 1 | User 2 | 
|------|--------|--------|
| 00:00 | Starts editing edition X (work: A) | Starts editing edition X (work: A) |
| 00:01 | Changes work to work: B; saves. | |
| 00:02 | | Changes anything and saves. |

User 2's edits will cause Work B to be updated with Work A's data.

**Comment by seabelis** [comment]
> @seabelis A few questions for you:
> 
> 1. Could you post the link of the edition as well?
> 2. How did you restore the lost information?

Not sure if you still need this, but I restored manually and I've moved several editions of Hamlet; I'm afraid I don't know exactly which edition corresponded to this issue.

**Comment by seabelis** [comment]
Looks like the same happened here. https://openlibrary.org/works/OL166971W/%D0%91%D0%B5%D1%81%D1%8B_Bi%EF%B8%A0e%EF%B8%A1sy_(The_possessed_The_demons_The_devils)?a=33&b=32&_compare=Compare&m=diff

I recently noticed all the tags were gone, but thought they'd been removed them because the work is in Russian and that all the work-level data should be in its native language. Now I see that may not have been the case after all.

**Comment by hornc** [comment]
thanks for investigating this @cdrini and for reporting it @seabelis, this is a new one to me, and the data loss look serious, thanks for the reminder re. revert. I think it should be included for any `librarian` user by default -- TBH I did not realise it wasn't!

**Comment by tfmorris** [comment]
To go with @cdrini's edition change, I think this is the work change where the data loss actually happened

https://openlibrary.org/works/OL15203981W/Hamlet?b=52&a=51&_compare=Compare&m=diff

**Comment by cdrini** [comment]
Yep; steps forward for anyone who has some time (and an up-to-date dev env for testing :P) would be:

1) check to see if double clicking the save button causes this (this would be easy to fix and would probably prevent most cases of error)
2) confirm concurrent edits to an edition page behave as described (test with two browser windows). There might already be checks to prevent errors like this.

**Comment by LeadSongDog** [comment]
The corresponding edit to the edition OL25105972M which remapped it from OL16290875W to OL15203981W was done at: https://openlibrary.org/books/OL25105972M/Hamlet?m=diff&b=7 immediately preceding the change that @tfmorris linked:
https://openlibrary.org/works/OL15203981W/Hamlet?b=52&a=51&_compare=Compare&m=diff
Presumably these both occurred following @seabelis click on "Save".

**Comment by seabelis** [comment]
Just happened again. https://openlibrary.org/works/OL762601W/The_Barrytown_Trilogy?b=17&a=16&_compare=Compare&m=diff
