### ISSUE TITLE
Re-enable "revert" feature

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#1668]
I believe we disabled this because of misuse; I feel like enough time has passed that we can bring it back. It would be useful for @seabelis and I on #1662 .

**Comment by cdrini** [comment]
If I recall correctly, this worked correctly, we just disabled it because of an edit war. To clarify, this is the revert button that appears on the view history page. I would argue we should enable it for all users if possible.

**Comment by jdlrobson** [comment]
How do I enable this locally? I was having trouble trying to test some code relating to this?

**Comment by cdrini** [comment]
Not sure... Searching GitHub, https://github.com/internetarchive/openlibrary/pull/567 might be related? But @mekarples would know for sure.

**Comment by guyjeangilles** [comment]
I'm assuming this would be fairly easy to implement. @mekarpeles assigning you since you appear to be the subject matter expert.

**Comment by tfmorris** [comment]
This started working again for me in the last few months. I'm not sure if my permissions got changed or it get reeenabled for folks generally. Even if it's currently librarians only, they would appear to meet the needs of @cdrini and @seabelis.

**Comment by cdrini** [comment]
It's been re-enabled for librarians here #2228 . I still think it should be re-enabled for any "trusted" user, like most wikis (Wikipedia, Wikidata). I would say this is blocked by adding a "trusted" user class.

**Comment by SouthGoingZax** [comment]
Is there still a desire to create a trusted user class?  Would that just be creating a new "trusted-user" usergroup, adding an is_librarian()-like check for it, and then adding the check into the revert permission check (and whatever else these users would be trusted to do)?

**Comment by SouthGoingZax** [comment]
Discussed on a community call, and it seems like this can be closed.  There is a trusted-user tag, already, which could potentially be leveraged if we have more places we want to use it.  But revert functionality has already been restored, and it is only enabled for librarians and admins.
