### ISSUE TITLE
Saving an edit results in offline message. 

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1670]
## Bug

> **Evidence**: Saving an edit results in offline message. Edits are saved, however.
![fullscreen capture 1232018 122143 pm bmp](https://user-images.githubusercontent.com/17739465/49371004-5566fa80-f6f6-11e8-8c3e-e294888bf725.jpg)

> **Expectation**: View mode of edited item.

> **Details**: Logged in? Yes
Browser type/version? Chrome Version 70.0.3538.110 (Official Build) (64-bit)
Operating system? Windows 7 Professional
Production/dev/local? N?A

> **Reproduce**: Edit and save an edition record. (Have not tried with edits to work.)

**Comment by LeadSongDog** [comment]
Seems to come up often when assigning a different work to an edition. Not sure but the donation banner may be causing more timeouts.
