### ISSUE TITLE
Refactor/DRY amazon.py and catalog/merge/merge.py to duplicate less code

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1677]
> [...] this module is a 90% duplicate with amazon.py, so a better solution might be to sort that out." from https://github.com/internetarchive/openlibrary/pull/1674#discussion_r238899318

**Comment by guyjeangilles** [comment]
Amazon.py still exists. @cdrini had been refactoring coding but @mekarpeles is taking over his duties for the time being so I'm assigning him per slack discussions.

**Comment by hornc** [comment]
This sounds like it relates to some of the code I was looking at as part of import changes, especially around figuring out which parts of the code to test. I'll take this one...

**Comment by scottbarnes** [comment]
@hornc, I can't find `amazon.py` and I am wondering if you think this issue can be closed.

**Comment by hornc** [comment]
@cclauss Yes, this can be closed. I believe that code was unused and kept around "just in case" for a very long time.

It was likely removed around the time I made these clean ups: https://github.com/internetarchive/openlibrary/commit/ead7ce298b4974b66673f78da4e7781c612838f6  (not the exact commit, but that commit removes the bulk of the catalog/amazon code.)   the catalog/ tree does not currently do anything with Amazon imports now, it's all about library MARC records.
