### ISSUE TITLE
Changing Edition title causes an incorrect temporarily offline message

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1703]
## Bug

> **Evidence**: What is happening? What are the symptoms? (screenshot here if possible)
Here, changing Le to La in the edition title yields this result
![closed](https://user-images.githubusercontent.com/11435431/49761174-45ba5980-fc94-11e8-92d4-dc00bdddb353.jpg)

> **Expectation**: What should by happening?
Loaded page should be 
https://openlibrary.org/books/OL18885401M
which would then correctly redirect to the slugged
https://openlibrary.org/books/OL18885401M/La_France_sous_le_Directoire_1795-1799
instead of going back to 
https://openlibrary.org/books/OL18885401M/Le_France_sous_le_Directoire_1795-1799/edit

> **Details**: Logged in? Browser type/version? Operating system? Production/dev/local? (if relevant)
Logged in. Chrome on Win7

**Comment by seabelis** [comment]
I'm getting this after saving almost any edit, works and editions.

**Comment by guyjeangilles** [comment]
I have not gotten this error recently when making edits. Closing. Reopen with a screenshot if this still occurs.
