### ISSUE TITLE
Most of Edit Mode Broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1709]
## Bug

> **Evidence**: Tabs have been replaced by links. Also cannot save links.
![fullscreen capture 12112018 85639 am bmp](https://user-images.githubusercontent.com/17739465/49786101-ea837800-fd22-11e8-88ee-dbff68e7431f.jpg)

**Comment by seabelis** [comment]
Author drop-down is also unresponsive.

**Comment by seabelis** [comment]
Seems pretty much all of edit mode is broken, author, language, librarian mode, covers...

**Comment by cdrini** [comment]
It looks like none of the JS is working on the page. My guess is an error is occurring which is preventing the rest of the JS from loading. The console displays this:

```
ReferenceError: Checks is not defined[Learn More] vendor-v2.js:19304
TypeError: wmdBase is not a function[Learn More] vendor-v2.js:18424
working! edit:2536:9 
```

The first error links to here: 

```js
WMDEditor.position = position;
WMDEditor.TextareaState = TextareaState;
WMDEditor.Checks = Checks;
WMDEditor.InputPoller = InputPoller;
```

This makes me think it's related to this commit: 9095d7ca30da7190cb73c78730d6ade50e92cca2 (Update all submodules) which updated the WMD editor (the markdown editor).

**Comment by cdrini** [comment]
Yep, that's the issue. The version we updated to has this error: https://github.com/internetarchive/wmd/pull/1 .

**Comment by cdrini** [comment]
Pinging @tfmorris

**Comment by LeadSongDog** [comment]
I'm pretty sure it started at the same time as #1707 hit production. Since then, I've been unable to do any but the most trivial edits. Whether it is a problem with all js or something more specific, I can't be sure. The first error is inability to load https://archive.org/includes/js-cookie.js?v=d3427d7

**Comment by mekarpeles** [comment]
@seabelis + @LeadSongDog I think I've just pushed a fix -- do you want to see if these latest changes solve the problems you're facing?

thank you!

**Comment by tfmorris** [comment]
@cdrini Wasn't my fault! (But I think @mekarpeles has already fixed it).

**Comment by seabelis** [comment]
Seems okay now.

**Comment by mekarpeles** [comment]
@tfmorris the reason you got tagged was because those are the benefits of being super knowledgable about reliable for a codebase 🤣  

ok! Things seems resoled :)

**Comment by LeadSongDog** [comment]
ty. seems to be working more or less as-normal

**Comment by cdrini** [comment]
Haha, wasn't trying to fault you, @tfmorris! My apologies if it appeared like that. Just thought since you made the commit, you might know how to revert it quickly. I don't know how to change the submodule versions, and my dev env is super out of date, so it would take me too much time to fix this.
