### ISSUE TITLE
Optimise people page (historyPager) for mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1726]
## Bug

> **Evidence**: What is happening? What are the symptoms? (screenshot here if possible)

When I visit https://openlibrary.org/people/horncBot on a mobile device, my browser suffers from horizontal scrolling

![screen shot 2018-12-14 at 3 15 14 pm](https://user-images.githubusercontent.com/148752/50034733-17e65500-ffb3-11e8-9240-128e084e94fe.png)

> **Expectation**: What should by happening?

There should be no horizontal scrolling

> **Details**: Logged in? Browser type/version? Operating system? Production/dev/local? (if relevant)

All browsers

> **Solution**: Proposed solution? Solution requirements?

![screen shot 2018-12-14 at 3 15 48 pm](https://user-images.githubusercontent.com/148752/50034748-27fe3480-ffb3-11e8-8375-404077ddaa39.png)

The issue appears to be the historyPager element at the bottom of the page!
It defines  width: 848px;

This CSS rule (found in static/css/legacy.less) should be limited to a media query

- [ ] Limit the CSS rule to an appropriate breakpoint defined in static/css/less/breakpoints.less 
- [ ] Document the CSS rule with an inline comment in legacy.less to make clear for the next person working with this file on which page(s) that element can appear and thus be used.

**Comment by Pratyush1197** [comment]
@jdlrobson  Please assign me this issue. I want to work on it

**Comment by jdlrobson** [comment]
Let me know @Pratyush1197 if I can help!

**Comment by Pratyush1197** [comment]
@jdlrobson I made the PR. Please check it if it's not wrong. Also can you guide me how can i join slack group?
