### ISSUE TITLE
Remove the need for jquery-migrate and upgrade jQuery to version 3

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1732]
## Feature

> **Problem**: What problem are we solving?

We are using jquery-1.11.0.min.js which is 5 years old and adds IE < 8 support (if we jump to jquery 2 we can drop that support but that's another story).
However, we are also using jquery-migrate to provide backwards compatibilities to older jQuery versions.

When you use the minified version of jquery-migrate, any errors are quietly silenced.

We should surface these errors in the JavaScript console by replacing the line static/js/vendor.jsh
```
xcat $VENDORJS/jquery-migrate/jquery-migrate-1.2.1.min.js
```
with the non-compressed version
```
xcat $VENDORJS/jquery-migrate/jquery-migrate.min.js  | $JSMIN
```

> **Need**: What evidence do you have this feature is important to this audience? What can't we do because this feature does not exist? What must we do instead because this feature doesn't exist? How many users will be impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

We are shipping code that is meant to be temporary to help with migrations. We might as well be using an older version of jquery (1.11.0) if we are not doing anything about them!

> **Implementation**: How would you go about implementing this?

= Goal
- [x] switch to uncompressed jquery migrate (we can minify it manually)
- [x] after running `make js` warnings are exposed in the console thanks to us using the development version
- [ ] any deprecation notices are addressed
- [ ] jquery-migrate is dropped from the codebase \o/
- [ ] We make the jump to a newer jQuery version \o/.

**Comment by jdlrobson** [comment]
We might want to add unit tests before doing this as this will give us much more confidence that our JS code is jquery ready!

**Comment by guyjeangilles** [comment]
Assigning jdlrobson (not tagging as requested) per slack discussions since he's making PRs for this issue.
