### ISSUE TITLE
Unable to implement setup.py commands

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1736]
Under the **Basic developer commands section**  setup.py commands are not executing. While I cannot find the **setup_commands.py** file mentioned in screenshot and the link is also not working. I tried downloading setuptools and then executing the commands but the effort went in vain 
Here is the screenshot.

![screenshot_2018-12-16 internetarchive openlibrary](https://user-images.githubusercontent.com/32239181/50056886-ddceac00-0188-11e9-9011-38dd522f9cc5.png)

**Comment by guyjeangilles** [comment]
Closing because this looks like pre-Docker test instructions. The [current test commands](https://github.com/internetarchive/openlibrary#running-tests) are 
```
cd docker/
docker-compose exec web make test
```
