### ISSUE TITLE
Can't select unpopular short author names in works edit page

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#174]
If you want to choose an author like Robert May b. 1588, there's no way to do it from the web edit interface because he doesn't appear in the top 10 results for his name, there's no way to make the name more specific, no way to specify dates and no way to get more choices.

This plus the fact that there's a "create new" button, but no "more choices" button will encourage people to create unnecessary duplicate author records.

**Comment by LeadSongDog** [comment]
Yes, this is still a problem. "Walter Scott" gets 151 hits, most of which are not available in the edit interface. This is aggravated by the fact that recently created or changed author name records take a **very** long time to be made current in the search results.

**Comment by LeadSongDog** [comment]
A change to the work-edit interface that also took a year to narrow the results would go a long way, though in the long run, it should accept a VIAF or other identifer.

**Comment by bfalling** [comment]
@LeadSongDog, @tfmorris: Thanks for the comments! I'm helping spearhead getting fixes implemented but am new to some of the interfaces.

Can you toss up some URLs for the issues above you're seeing? e.g. What are you calling the "web edit" and "work-edit" interfaces?

**Comment by tfmorris** [comment]
Here's a trail for the example I gave:

1. Start at the undifferentiated "Robert May" author record (as an aside all two name authors with no dates need to be weeded out) - https://openlibrary.org/authors/OL1913368A/Robert_May
2. Select one of the "The acommplisht cook" works like this one: https://openlibrary.org/works/OL6912375W/The_Accomplisht_Cook_or_The_Art_of_Mystery_of_Cookery
3. Click "Edit" so you can fix the author record - https://openlibrary.org/books/OL8294018M/The_Accomplisht_Cook_or_The_Art_of_Mystery_of_Cookery/edit
4. Go to the Author field and replace the generic Robert May with the correct one b. 1588 -- Oops, that's impossible!

**Comment by jessamynwest** [comment]
This is a weird problem -- there are some odd fails in the way the author-select pulldown populates and I've definitely had issues with this before.

**Comment by LeadSongDog** [comment]
Yes, it should be very accepting of variations in spelling, punctuation, and word order. It isn't. Using an established authority record would also go a long way (lc auth, VIAF, etc).

**Comment by LeadSongDog** [comment]
Is there an issue with openlibrary/openlibrary/plugins/openlibrary/js/autocomplete.js ???
