### ISSUE TITLE
Cannot move past first page of reading log

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1740]
## Bug

Only the first 100 results are being shown on users' Reading Log.

https://openlibrary.org/account/books/want-to-read

**Comment by mekarpeles** [comment]
@tabshaikh as a first step hotfix, maybe we should remove the 100 book limit and increase it to e.g. 500.

I think this will have performance implications on the site and the user's experience (load and render time). We'll likely want to ultimately have a "load more" button which loads 100 more at a time. Or have pages, similar to how the `search` page works. Your call. Please do some research on what option you think is best and report back here :)

**Comment by tabshaikh** [comment]
With Loading the reading log like the search page we are planning to have a search bar in the reading log by which the user can directly search for the required book

**Comment by tfmorris** [comment]
I was just about to comment that search isn't a replacement for pagination, so I'm glad to see that thought didn't last long.
