### ISSUE TITLE
Blob of JS in default_edit template can likely be removed

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1741]
In https://github.com/internetarchive/openlibrary/pull/1731#discussion_r242253471 we discovered a blob of JS inside openlibrary/templates/default_edit.html

Firstly, what pages use this template?
Secondly, are we confident it can be removed?

**Comment by jdlrobson** [comment]
Similar question to #818 ... how do default_input.html, default_rdf.html, dedault_view and default_edit get registered/used? I think infogami has some magic to default to these if no templates are required, but it makes it very hard to discover what might be using them.

I'd much rather have view's return a Not Implemented status code in this situation to force us to handle different types with their own templates rather than a default that can easily code-rot.

**Comment by brad2014** [comment]
@jdlrobson This issue is already closed - did you have some specific additional review in mind?
