### ISSUE TITLE
Cleanup openlibrary/plugins/openlibrary/js/lazy.js

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1742]
The file openlibrary/plugins/openlibrary/js/lazy.js contains various plugins that do not seem to be used anywhere.

* $.hoverIntent
* $.scrollTo (http://flesler.blogspot.com/2007/10/jqueryscrollto.html)
* $.highlight
* $.dataTable
* Columnize Plugin for jQuery
* jTruncate

I think the only parts in this file that are relevant are 2 global functions exported to the global namespace:
* plot_tooltip_graph
* plot_minigraph

Unless anyone can confirm the plugins are used, I plan to remove these prior to fixing our JavaScript build process.

**Comment by brad2014** [comment]
@jdlrobson , who do you think would be a good person to review this?

**Comment by jdlrobson** [comment]
Closing this in favour of #2314 and  #2315
