### ISSUE TITLE
ReadPanel book prices cramped together

### ISSUE THREAD

**Issue by Num170R** [internetarchive/openlibrary#1752]
## Bug
Not really a bug, just a minor glitch. It would be nice if we could include some space between the item providers and the prices.
> **Evidence**: What is happening? What are the symptoms? (screenshot here if possible)

![buy_this_book_section](https://user-images.githubusercontent.com/9248823/50344241-df0a2b00-0532-11e9-9f6d-972e89c11729.png)

> **Expectation**: What should be happening?

![buy-options-table](https://user-images.githubusercontent.com/9248823/50344249-e598a280-0532-11e9-8486-58337a541c48.png)

> **Details**: Logged in? Browser type/version? Operating system? Production/dev/local? (if relevant)

The screenshots are from firefox dev edition on win10 but it most probably looks like that irrelevant of browser/os. This is on prod.

> **Reproduce**: Steps to reproduce problem:

Visit [a book page] (for which a price can be fetched) and observe that providers and prices are not properly aligned so that when provider's name is long there is no gap.

[a book page]:  https://openlibrary.org/books/OL2001233M/Thoughts_for_the_free_life

> **Solution**: Proposed solution? Solution requirements?

A possible solution would be to change `buy-option-table` width to match the above elements.
for example, as in the second screenshot but need to be verified. 

edit: It seems that `border-collapse: separate` would be more appropriate.

edit by @jdlrobson: Setting table's inside read panel to width: 100%;  and table .price to text-align: right should be all that's needed here.

> **Stakeholders**: @ tag stakeholders of this bug

@jdlrobson @mekarpeles

**Comment by jdlrobson** [comment]
https://dev.openlibrary.org/books/OL20941603M/The_perfect_storm

There are a few problems with the read panel component.
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#read-panel

I think @mekarpeles is fixing some issues with font sizes that may help here.

**Comment by jdlrobson** [comment]
I suspect because tables use display block up to tablet threshold but will take a look
