### ISSUE TITLE
Readme for scripts

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1755]
## Description
> What problem are we solving?

Add readme to scripts dir

## Evidence 
> What does the experience look like today? What are the symptoms?

> Relevant url:

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by guyjeangilles** [comment]
There is a Readme but it's just two lines
># Open Library scripts.
>Commonly used scripts will be in this directory and scratch scripts will be organized by $year/$month/$scriptname.

@mekarpeles defaulting to assigning you per slack discussions

**Comment by mekarpeles** [comment]
Closing as not an issue -- scripts have been drastically improved

There technically is a README https://github.com/internetarchive/openlibrary/blob/master/scripts/Readme.txt which could be improved
