### ISSUE TITLE
Harry Potter doesn't render !!!

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1761]
## Description
> What problem are we solving?

A url fails with a render error

## Evidence 

> What does the experience look like today? What are the symptoms?
![screen shot 2018-12-25 at 6 03 37 pm](https://user-images.githubusercontent.com/148752/50428855-78a54580-086f-11e9-9673-054bfb68514e.png)

?debug=true amongst other information shows:
```

Python | /opt/openlibrary/venv/local/lib/python2.7/site-packages/simplejson/encoder.py in iterencode, line 377
-- | --
GET https://openlibrary.org/books/OL24239956M

```

> Relevant url:
https://openlibrary.org/books/OL24239956M/Harry_Potter_and_the_Sorcerer's_Stone

## Expectation
> What should by happening? What will it look like / how will it behave?

It should render! People need their Harry Potter fix!!!

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by tfmorris** [comment]
This is a single edition which fails to render, so I'm doubtful that it warrants three exclamation points.

I haven't full investigated, but I'm suspicious that the book record: https://openlibrary.org/books/OL24239956M.json
points to a work record which is a redirect: https://openlibrary.org/works/OL13716949W.json

Additional random weirdness - the work record has subjects attached to it.

**Comment by mekarpeles** [comment]
This seems to be an issue with caching which is recurrent. My suspicion is something like our cache system having trouble serializing web.ctx Storage objects. The issue in this case is solved with the following patch (which seems like a hack, treating the symptoms):

```
diff --git a/openlibrary/core/lending.py b/openlibrary/core/lending.py
index bb04915..a41119a 100644
--- a/openlibrary/core/lending.py
+++ b/openlibrary/core/lending.py
@@ -109,9 +109,12 @@ def get_work_authors_and_related_subjects(work_id):

 @public
 def cached_work_authors_and_subjects(work_id):
-    return cache.memcache_memoize(
-        get_work_authors_and_related_subjects, 'works_authors_and_subjects',
-        timeout=dateutil.HALF_DAY_SECS)(work_id)
+    try:
+        return cache.memcache_memoize(
+            get_work_authors_and_related_subjects, 'works_authors_and_subjects',
+            timeout=dateutil.HALF_DAY_SECS)(work_id)
+    except AttributeError:
+        return {'authors': [], 'subject': []}
```

**Comment by mekarpeles** [comment]
Specifically, in this case, the issue appears to be caching `work_subjects_authors = cached_work_authors_and_subjects(work.key) `

**Comment by tfmorris** [comment]
Even if the redirect is a red herring, we shouldn't have internal links to redirects. That's inefficient and wasteful. They should be reserved for helping external clients who've saved a now invalid reference.

Can you expand a bit on the details of the cache issue? Is it storing a partial/corrupted object which is triggering the error on a cache hit? Are we sure that it's following/resolving the redirect before attempting to fetch the authors/subjects?

**Comment by tfmorris** [comment]
I investigated further and it looks to me like it's trying to memoize/cache the [redirect object](https://openlibrary.org/works/OL13716949W.json), which, of course, doesn't have authors (and shouldn't have subjects).

Either `lending.get_work_authors_and_related_subjects()` or the method that it calls, `web.ctx.site.get(work_id)` needs to resolve the redirect, but I'm not sure where the main redirect machinery is in this stack (or how it interacts with the cache).

**Comment by jdlrobson** [comment]
As the creator of this issue, the issue I originally reported has been addressed and I am happy that has been fixed.

If there are other related issues, please open a new ticket to clearly described the problem.

**Comment by tfmorris** [comment]
Sorry for the delayed reply.

@mekarpeles The comment associated with the patch seemed to say that it wasn't an actual fix, but just hiding the problem. 

The reporter of the problem and you are both happy to just have it hidden, so that works for me. I'm not going to insist on correctness.
