### ISSUE TITLE
Thumbnails get cut up/squished on list pages (on mobile) and in search results

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1762]
## Description
> What problem are we solving?

Thumbnails are getting cut off on list pages.

In search autocomplete results......... and inside lists (e.g http://localhost:8080/account/books/want-to-read) they sometimes get squished.

![screen shot 2018-12-26 at 2 55 53 pm](https://user-images.githubusercontent.com/148752/50459251-5e767080-091e-11e9-9749-e0a37660404b.png)

This seems to be caused by mixing height and width definitions such that the image is forced to be outside its aspect ratio

## Evidence 
> What does the experience look like today? What are the symptoms?

See screenshot below.

> Relevant url:

https://openlibrary.org/people/jdlrobson/lists

> Screenshot (if possible):
![screen shot 2018-12-25 at 6 12 05 pm](https://user-images.githubusercontent.com/148752/50429015-a3dc6480-0870-11e9-9a99-f6d2c1d97485.png)

## Expectation
> What should by happening? What will it look like / how will it behave?

The thumbnail should not be cut in half.

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by rohitjain00** [comment]
We could just have the image to full row and the information of the same image below it.
![screenshot from 2018-12-29 13-04-19](https://user-images.githubusercontent.com/17525863/50534973-61fe3780-0b6a-11e9-97ab-7be08d2de633.png)

**Comment by jdlrobson** [comment]
Agreed! I think rather than centering though it would make sense to keep the left alignment to be kept consistent with the rest of the site!

**Comment by jdlrobson** [comment]
@rohitjain00 did you want to have a go at fixing this?

**Comment by rohitjain00** [comment]
@jdlrobson yes, I make a pull request as soon as possible

**Comment by jdlrobson** [comment]
Any updates @rohitjain00 ?

**Comment by koderjoker** [comment]
Hi @jdlrobson, can I have a go at fixing this?

**Comment by jdlrobson** [comment]
@koderjoker we haven't heard back from @rohitjain00 so I think you can go ahead. Important thing is to get the bug fixed - we have plenty of these kind of tasks!

**Comment by rohitjain00** [comment]
I am sorry I was not able to follow up on this issue. So I lost a track of it. thanks @koderjoker for fixing this.
