### ISSUE TITLE
Fix v2 books page (standardize font sizes and colors)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1767]
## Description
> What problem are we solving?

Books page font sizes are inconsistent (e.g. the .meta .object table), the "manage covers" button text is too large, read-options sidebar needed padding + font-size fixes

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

Blocking deploy to production

## Stakeholders
> @ tag stakeholders of this bug / feature

@jdlrobson, @psyked, @tabshaikh, @hornc, @cdrini

**Comment by jdlrobson** [comment]
(I thought #1765 was merged.. but this fixes  the most noticeable padding and font-size issues IMO)

**Comment by jdlrobson** [comment]
The fix has created some new problems.. I've left some comments on the pull request.
