### ISSUE TITLE
Certain cover images are too small (<200px)

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1778]
## Description
> What problem are we solving?

When sharing OpenLibrary books on social media sometimes I don't see the cover when a cover exists.

## Evidence 
> What does the experience look like today? What are the symptoms?

A visit to the debut tool:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fopenlibrary.org%2Fbooks%2FOL7885696M%2FCharlotte%27s_Web

shows the og:image tag exists but  the cover image is too small. Charlottes Web is 180x255

> Relevant url:

https://openlibrary.org/books/OL7885696M/Charlotte's_Web

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?
We should ensure cover images are at least 200x200.

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by tfmorris** [comment]
The first URL says I have to log in. The second URL shows a 295x420 pixel image.  We can make any image have an arbitrarily large number of pixels without improving its quality at all. Conversely, we can't generate information where there is none.

Do we care about Facebook users? If so, what is their experience now and how do we want to change that?

Obviously higher quality cover images benefit everyone, but, absent that, do we just want to scale 50x50 images to 200x200 to meet some arbitrary pixel count threshold (w/o improving quality)?

**Comment by jdlrobson** [comment]
> Do we care about Facebook users? If so, what is their experience now and how do we want to change that?
Facebook whether you like the service or not is a big potential traffic source and studies have shown posts with images get clicked a lot more than posts without. If we can entice even one user into OpenLibrary's world that seems like a pretty good thing to do.

The experience right now when sharing an OpenLibrary link is an image in some cases doesn't appear. This is trivial on our side to fix - we need to use the large images rather than the small images.

> Obviously higher quality cover images benefit everyone, but, absent that, do we just want to scale 50x50 images to 200x200 to meet some arbitrary pixel count threshold (w/o improving quality)?
The image only appears in the og:image tag. The end user doesn't get punished by the download.

The fix is simple and hopefully not controversial in the slightest with the above in mind.
