### ISSUE TITLE
Contact and support path paramter doesnt work

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1780]
## Description
What problem are we solving?
When contact and support is called from a specific page it should contain its path in the parameter.

## Evidence 
What does the experience look like today? What are the symptoms?
Just click on contact and support in the footer

## Expectation
What should by happening? What will it look like / how will it behave?
it should show the path of the page from where it is being called in the url

## Proposal
What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?
Dont hard wire the path / and put the current path in it

**Comment by tabshaikh** [comment]
And according to a suggestion by @tfmorris, we should rename it to **report a problem** as contact and support do not mean the same

**Comment by LeadSongDog** [comment]
If it’s not too much to ask, the user should see the report that is logged.

**Comment by tabshaikh** [comment]
@LeadSongDog the report is logged like a dialogue box showing up that his request has been registered

**Comment by LeadSongDog** [comment]
Well, I don’t think form matters much just as long as the user can tell their concern is captured.

**Comment by TZubiri** [comment]
In what page can I find the 'contact and support' button?
