### ISSUE TITLE
I could not add ISBN 13 978​0923891213 for the book "Human sexual response".

### ISSUE THREAD

**Issue by GerardMeijssen** [internetarchive/openlibrary#1796]
## Description
> What problem are we solving?

## Evidence 
> What does the experience look like today? What are the symptoms?

> Relevant url:

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by GerardMeijssen** [comment]
https://openlibrary.org/works/OL11040083W/Human_sexual_response

**Comment by tfmorris** [comment]
Are we sure that #1798 fixes this? I don't even see what the original error was.

When I try to cut & paste that ISBN, I get "ISBN must be exactly 13 digits" because there's a weird invisible character after the 978 causing the validation code to reject it.
