### ISSUE TITLE
Option to add Wikidata IDs to works

### ISSUE THREAD

**Issue by GerardMeijssen** [internetarchive/openlibrary#1797]
In the same way that you can add Wikidata IDs to editions or to authors, there should be a way to add them to works. Wikidata has a notion of Works as well.

e.g. https://www.wikidata.org/wiki/Q43361

**Comment by LeadSongDog** [comment]
The reverse is also possible: wikidata items for a book may have an OLID parameter P648 identified. For example Q1639633 "Vingt ans après" has P648 with value "OL36858W"

**Comment by guyjeangilles** [comment]
`Wikidata` is in the identifier dropdown for editions now. Closing.

**Comment by cdrini** [comment]
This is a separate issue; it asks to have wikidata links on the work.

Related: https://github.com/internetarchive/openlibrary/issues/856

**Comment by guyjeangilles** [comment]
Noted.

Assigning @hornc per slack discussions. Seems like this would require a schema change.

**Comment by RayBB** [comment]
Closing this as it will be addressed as part of #3430 (which currently has a nice PR opened by @davidscotson)

**Comment by hornc** [comment]
When the PR is merged the issue will automatically get closed. It shouldn't be closed early in case the currently Draft PR changes, or does not get merged.

**Comment by tfmorris** [comment]
@hornc I think since this issue is a subset of issue #3430, it's OK to close this and use that issue to track the status of the PR.

**Comment by cdrini** [comment]
I'm cleaning up/finishing a few issues related to adding identifiers. I added wikidata to the https://openlibrary.org/config/work file, which, once #3430 is completed, will allow Wikidata to automatically be added via the UI. That is the issue to track for this; closing since there's no more work to be done on this one!
