### ISSUE TITLE
Full text search authors incorrectly showing as "Unknown Author"

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1805]
## Description
> What problem are we solving?

## Evidence 

> What does the experience look like today? What are the symptoms?

even when author info available, renders as Unknown Author on fulltext results page 

> Relevant url:

https://openlibrary.org/search/inside?q=nicodemus

> Screenshot (if possible):

![image](https://user-images.githubusercontent.com/978325/50668181-5cda2780-0f72-11e9-8a7c-e031dea9d711.png)
<img width="1403" alt="screen shot 2019-01-03 at 3 53 47 pm" src="https://user-images.githubusercontent.com/978325/50668186-64013580-0f72-11e9-9a04-92adc3981c86.png">

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

low / minor

## Stakeholders
> @ tag stakeholders of this bug / feature
@mekarpeles

**Comment by tfmorris** [comment]
That page appears to be returning editions, not works. The highlighted edition doesn't have an author listed, so I suspect the page doesn't know how to traverse to the work and get the author from there (and it's probably showing the wrong author in the case where the two records don't match).

https://openlibrary.org/books/OL2728386M.json

**Comment by shreyansh23** [comment]
@mekarpeles @tfmorris I was seeing this issue and I observed two bugs.

For the same search endpoint (https://openlibrary.org/search/inside?q=nicodemus)
![search-bug](https://user-images.githubusercontent.com/32803230/53959612-1fc51980-410a-11e9-9e70-8229c4804f9a.png)

Type 1
Here the author exists ( I followed the URL and checked the JSON too) but it is not showing.
Type 2 
As @tfmorris mentioned in earlier comment, the author is not coming in the json itself.

**Comment by guyjeangilles** [comment]
I can duplicate all of the above issues. I'm defaulting to assigning @mekarpeles per slack discussions. I'm why data in the json wouldn't reach the template.

**Comment by hippothebrave** [comment]
I can't duplicate these issues on the current OpenLibrary, and the issue seems to be rather old. Should this be closed?

**Comment by jimchamp** [comment]
@scottbarnes says he also cannot replicate.  Closing this for now.  If this is still an issue please re-open.
