### ISSUE TITLE
Some isbn lookups from Amazon fail, resulting in 404s

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1807]
Some isbns from Amazon fail, resulting in 404s

006222526X: <Response [404]>
0800788036: <Response [404]>
144947425X: <Response [404]>
159514188X: <Response [404]>

Unsure why these are failing -- it looks like `create_edition_from_amazon_metadata(isbn)` is failing somewhere.
see https://github.com/internetarchive/openlibrary/blob/b5aa71e06f36351ada1eff1842690a7a028e09ff/openlibrary/core/vendors.py#L89

## Description
> What problem are we solving?

## Evidence 
> What does the experience look like today? What are the symptoms?

> Relevant url:

https://openlibrary.org/isbn/159514188X  and other example isbns listed above

## Expectation
> What should by happening? What will it look like / how will it behave?

Book page should display since the books are on Amazon

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal
> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

## Constraints
> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by LeadSongDog** [comment]
That edition existed and had isbn13 but not isbn10. Once I manually added the isbn10 it is found. Of course that should not be necessary. Either one should automatically populate the other but that’s a different issue.

**Comment by LeadSongDog** [comment]
Related: #27 #42 #1456 #1457 
I'm not at all sure that #42 should have been closed. It seems not to have been fully dealt with.
@hornc I noticed that an "All" search on the isbn10 value resulted in a hit even before I manually added it, but that may be a coincidence: I couldn't tell which edition matched, just the work (yes, that issue is still open too...) . If it is a pattern, you may want to explore why it happens.

**Comment by LeadSongDog** [comment]
From your list of 404's, an "All" search on "0800788036" finds https://openlibrary.org/books/OL25175041M/Laugh_Out_Loud_Jokes_For_Kids even though it only shows the isbn13 of 9780800788032. The only place I see a possibility for a match is embedded in the vendor link to:  http://www.amazon.com/dp/0800788036/?tag=internetarchi-20

**Comment by tabshaikh** [comment]
@tfmorris please can you explain on the 2nd point, is it happening because of no price field in Amazon data

**Comment by hornc** [comment]
After investigating and checking the Amazon API results, it turns out there is no price because the Amazon API sometimes returns more than one product result (a list), and OL is only expecting one product, which it gets the majority of the time. Fixing now.
