### ISSUE TITLE
List export fails

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#181]
Same or very similar problem as in #78: the export of lists function fails for every list, not just large lists. I verified this for an 18 item list and a 1 item list. Below is the traceback for the 18 item list.
http://openlibrary.org/people/bencompanjen/lists/OL8736L/Collection/export?format=json&debug=true

Traceback (innermost first)

```
/usr/lib/python2.6/urllib2.py in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) ...
▶ Local vars
/usr/lib/python2.6/urllib2.py in _call_chain
    result = func(*args) ...
▶ Local vars
/usr/lib/python2.6/urllib2.py in error
    return self._call_chain(*args) ...
▶ Local vars
/usr/lib/python2.6/urllib2.py in http_response
    'http', request, response, code, msg, hdrs) ...
▶ Local vars
/usr/lib/python2.6/urllib2.py in open
    response = meth(req, response) ...
▶ Local vars
/usr/lib/python2.6/urllib2.py in urlopen
    return _opener.open(url, data, timeout) ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/openlibrary/core/lists/model.py in _editions_view
    json = urllib2.urlopen(url).read() ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/openlibrary/core/lists/model.py in get_edition_keys
    d = self._editions_view(seeds, limit=10000, stale="ok") ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/openlibrary/core/lists/model.py in get_all_editions
    keys.update(get_edition_keys(seeds)) ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/openlibrary/plugins/openlibrary/lists.py in get_editions
    editions = sorted(list.get_all_editions(), key=lambda doc: doc['last_modified']['value'], reverse=True) ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/openlibrary/plugins/openlibrary/lists.py in GET
    data = {"editions": self.get_editions(list, raw=True)} ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/infogami/utils/app.py in delegate
    return getattr(cls(), method)(*args) ...
▶ Local vars
/opt/openlibrary/deploys/openlibrary/f8551a6/infogami/utils/app.py in <lambda>
    HEAD = GET = POST = PUT = DELETE = lambda self: delegate() ...
▶ Local vars
/opt/openlibrary/venv/lib/python2.6/site-packages/web.py-0.33-py2.6.egg/web/application.py in handle_class
    return tocall(*args) ...
▶ Local vars
/opt/openlibrary/venv/lib/python2.6/site-packages/web.py-0.33-py2.6.egg/web/application.py in _delegate
    return handle_class(cls) ...
▶ Local vars
/opt/openlibrary/venv/lib/python2.6/site-packages/web.py-0.33-py2.6.egg/web/application.py in handle
    return self._delegate(fn, self.fvars, args) ...
▶ Local vars
/opt/openlibrary/venv/lib/python2.6/site-packages/web.py-0.33-py2.6.egg/web/application.py in process
    return self.handle() ...
▶ Local vars 
```

Reported by John Rigdon to OL support ([according to Jessamyn West](http://openlibrary.org/community/projects)); this has been going on for a couple of months, apparently.

**Comment by sethwoodworth** [comment]
This remains an open issue.  There is a workaround via the restful api: https://openlibrary.org/dev/docs/api/lists by enumerating and getting the seeds of a list.

**Comment by bfalling** [comment]
See #78 for additional info.

**Comment by bfalling** [comment]
More info reported: "This was a thing that wasn't working for a long time, Anand fixed it and it appears to be not working again, not sure why. From the user's email...."

> List export is not working properly. For example, when I go to my list at:
> https://openlibrary.org/people/oddhack/lists/OL67478L/Hardbacks_Loanable
> 
> and try to 'Export As' JSON, HTML, or BibTeX, I get what looks like
> valid data in the corresponding formats, but only containing three
> entries from the list (the same three entries every time, and they're
> not the first three that show up at the link above). For example, the
> data returned by:
> https://openlibrary.org/people/oddhack/lists/OL67478L/Hardbacks_Loanable/export?format=bibtex
> 
> is:
> `@Book{OL7407894M, title: {Great Mambo Chicken and the Transhuman Condition}, author: {Ed Regis}, publisher: {Basic Books}, year: {1991}, } @Book{OL3558338M, title: {The dark lord}, author: {Harlan, Thomas.}, publisher: {Tor}, year: {2002}, place: {New York}, } @Book{OL9868463M, title: {Rogue Star (Firestar)}, author: {Michael Flynn}, publisher: {Tor Science Fiction}, year: {1999}, }`

So I (@bfalling) have done some preliminary digging, and I see that exports sometimes work and sometimes don't: sometimes showing empty data sets, sometimes incomplete sets, and sometimes the whole correct set. Also, JSON worked some times that Biblio and HTML didn't.

The export results are being drawn from SOLR (ol-solr2, I believe, used for the OL metadata).

At this point, I suspect that the inconsistent results are due to flaws in the indexing of OL content. FYI: Was getting an error in `openlibrary/openlibrary/core/lists/model.py:get_all_editions()`. 

> No method "type" found for string "seed".

**Comment by anandology** [comment]
Pro tip: add debug=true query parameter to the URL to see the trackback of
where it is failing.

**Comment by hornc** [comment]
In https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/lists/model.py#L147
`result` sometimes contains `<Storage {}>` instead of a doc like `<Storage {'edition_key': ['OL21974749M', 'OL20351819M']}>`

The problem does seem to be with solr indexing, but a 
```
if 'edition_key' not in doc:
     continue
```
will skip over the problematic indexes and prevent the export from blowing up.

**Comment by dokterbob** [comment]
Note: this issue does not seem relevant anymore. The URL in the description just works.

**Comment by hornc** [comment]
Unfortunately the problem still exists, here is an example of one of my lists:
https://openlibrary.org/people/hornc/lists/OL108777L/Curation/export?format=json&debug=true

I think there is a solr indexing component to the bug, so older static lists are likely to come right as solr catches up.
