### ISSUE TITLE
OL header regression

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1810]
## Description
> What problem are we solving?

main logo looks 30px tall (too small), the menu buttons are misaligned, and no login button appears
(possibly https://github.com/internetarchive/openlibrary/pull/1794/files)

## Evidence 

> Relevant url:

All urls

> Screenshot (if possible):

![screen shot 2019-01-07 at 12 46 50pmpst](https://user-images.githubusercontent.com/978325/50792604-703f0880-127a-11e9-957c-57647dc82bb9.png)

## Details
> What page(s) are impacted?
e.g. `https://openlibrary.org/...`

> Logged in (Y/N)? both

## Priority
> What evidence do you have this feature or bug is important to this audience? What can't we do because this bug exists or this feature doesn't  exist? How many users will be (or are) impacted? What is the value to us and/or to each user impacted? How much time/money can be earned/saved?

blocker

## Stakeholders
> @ tag stakeholders of this bug / feature

@jdlrobson, @mekarpeles

**Comment by LeadSongDog** [comment]
The OPEN sign is blurred in that version, while it was clean at 5372b389de986611d00a11c98cd2071566d83620 (currently on prod)

**Comment by jdlrobson** [comment]
This revert makes no sense to me as there is nothing in that diff that looks like it could lead to this kind of problem (unless caching problems exist). At the same time we are introducing the potential danger of css rendering issues anywhere the header class is used notably banners.

There is a more serious issue lurking somewhere in here.

I've just finished work and am gonna see if I can work this out.

Interestingly I am not seeing any issues with the img on my localhost.

**Comment by jdlrobson** [comment]
^ Tracked down the real fix. mystery solved.
