### ISSUE TITLE
Regarding Gsoc 2019

### ISSUE THREAD

**Issue by JackFrost7030** [internetarchive/openlibrary#1815]
Hello Mentors and Developers,

I am Anish Mulay, a student at BITS Pilani Goa Campus. I went through the Internet Archive GSoC 2018 ideas page and found most of the projects to be very interesting.
I found openlibrary intresting and would love to contribute and participate in GSoC 2019.

I do have some open source experience and I would like to try my hand by implementing a small new feature and/or resolving bugs.
I will be extremely thankful if someone could guide me regarding the same.

Thanking you.

Regards,
Anish Mulay.

**Comment by tabshaikh** [comment]
@JackFrost7030 I am closing this issue, if you need any help with moving forward you can ping us. :)
