### ISSUE TITLE
Twitter icon's image changes to Github's icon on certain browsers

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/openlibrary#1820]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

The image of the Twitter icon transforms into a Github icon on scrolling the page on Redmi mobile devices (so far occurs in Chrome and Mi browser, and not on Firefox)

## Evidence 

> Relevant urls with screenshots?

The issue seems to occur after scrolling a good amount of text.

Examples:

The twitter icon image completely transforms into a github one on the home page
https://openlibrary.org/
<img src="https://user-images.githubusercontent.com/30471843/51081899-bdf7bd00-1721-11e9-8369-6e595d1d4aed.png"  width="200"/>

The twitter icon image partially transforms into a github one on one's account page
https://openlibrary.org/account
<img src="https://user-images.githubusercontent.com/30471843/51083276-5fd8d300-173d-11e9-8ac7-74d069b9d705.png"  width="200"/>

This issue doesn't occur on pages like add a book, where less scrolling is involved
https://openlibrary.org/books/add
<img src="https://user-images.githubusercontent.com/30471843/51083289-9c0c3380-173d-11e9-8500-23c18e7fe610.png"  width="200"/>

## Expectation
> What should be happening? What will it look like / how will it behave?

The twitter icon image shouldn't transform on scrolling.

## Details

> Logged in (Y/N)?

Happens both while being logged in and being logged out

> Browser type/version?

This issue occurs on Google Chrome (71.0.3578.99) and Mi browser (V 10.3.6-g), only on Redmi devices as observed so far

> Operating system?

Android (7.1.2 N2G47H)

>Observations with DevTools

1. There is no change in the style of the icon when the icon image changes
2. It seems as if the the first icon is copying the second icon's image, as on changing the second icon's image the first icon's image changes to match it
3. However, disabling the background-image property of the first icon makes the first icon imageless

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by jdlrobson** [comment]
Interesting. I cannot replicate this myself on an Android Samsung phone in chromeor samsung browser.

@koderjoker we will probably need your help debugging this but so far looks like an issue specific to Redmi 

I think best next step would be for us to create a minimum test case for the problem.

**Comment by tfmorris** [comment]
This sounds like the kind of thing that could easily be a graphics driver bug rather than an application bug.

**Comment by koderjoker** [comment]
@jdlrobson Ready to help in any way possible 😄 

I tested the issue on a Redmi 4, Redmi Y1 and Samsung Galaxy J7 Prime and it only occurred on the 2 Redmi models, and that too not for Firefox's browser.

**Comment by jdlrobson** [comment]
I don't think there's much we can do here. It's likely to be a hardware or browser issue. I think just having this bug existing and searchable should be enough.

Should we close this task? I don't think there's actually anything we can do here.

**Comment by jdlrobson** [comment]
Per https://github.com/internetarchive/openlibrary/issues/1820#issuecomment-457850696

**Comment by shreyansh23** [comment]
Got the same issue on mobile Chrome Mobile Browser. But worked correctly in Firefox Mobile Browser!

**Comment by jdlrobson** [comment]
@shreyansh23 can you provide any replication steps that are device agnostic?

**Comment by shreyansh23** [comment]
@jdlrobson I am trying to find proper steps. I tried different mobile phones.
Mi Redmi Note 4 and Mi5 had problem.
Rest of the mobile phones (Samsung J7prime, Vivo Y53, Vivo Y66, IPhoneX) twitter icon rendered as it should be.
So it seems there is something with Xiaomi mobiles that is causing the problem.
