### ISSUE TITLE
Docker issue installing infogami at docker-compose

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1827]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

From @ayushnawal:
```
i have built the docker images and then on writing the command docker-compose up . it's just pausing with these last lines .
web_1 | [2019-01-17 09:50:41 +0000] [53] [INFO] Worker exiting (pid: 53)
web_1 | [2019-01-17 09:50:41 +0000] [46] [INFO] Shutting down: Master
web_1 | [2019-01-17 09:50:41 +0000] [46] [INFO] Reason: Worker failed to boot.
openlibrary_web_1 exited with code 3
Also in many lines in between , it is displaying that ImportError: No module named infogami
```

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Operating system?

OS: ubuntu 16.04
Docker Version: 18.06.1-ce

## Stakeholders
> @ tag stakeholders of this bug / feature

@mekarpeles , @hornc , @cdrini @tfmorris

**Comment by ayushnawal** [comment]
@mekarpeles i am attaching a screenshot too .. in case it helps you !
![screenshot from 2019-01-18 02-27-07](https://user-images.githubusercontent.com/36100944/51348405-a70ded80-1ac8-11e9-944a-38f22c91e115.png)

**Comment by ayushnawal** [comment]
screenshot after completing the building of Docker.olbase 
![screenshot from 2019-01-18 02-48-11](https://user-images.githubusercontent.com/36100944/51349513-a1fe6d80-1acb-11e9-8e19-0a5433d21b02.png)
Also an error message was shown in between !
![screenshot from 2019-01-18 02-50-12](https://user-images.githubusercontent.com/36100944/51349609-df62fb00-1acb-11e9-8c1f-0c59af65c274.png)

**Comment by cdrini** [comment]
This seems like symlink issue or a submodules issue. `static/js/../../vendor` symlinks to `vendor/`; the code also accesses infogami through a symlink. Everything in `vendor/` is a submodule. These lines in the Dockerfile downloads the stuff that should be in `vendor/` by calling `git submodule init` (through `make`), and creates the symlink.

https://github.com/internetarchive/openlibrary/blob/8e6c19e72ab9bb9f9e88064e654b1f976c9d0c5b/docker/Dockerfile.olbase#L52-L54

@ayushnawal Could you take a screenshot of the screen after your **3rd** screenshot? The `pip install` is Step 14/19; I want to see if the above lines (Steps 15, 16, and 17) completed successfully.

I recall Claus saying that that python error doesn't mean anything; pip just makes a lot of noise.

**Comment by hornc** [comment]
@mekarpeles I have not had this specific error before, but agree with @cdrini that it is symlink related, all the main error messages point to things that are symlinked.

I can also confirm that any pip version warnings are expected, annoying, but not a problem. Also the `lessc` warning is expected and know, but should not prevent anything from working.

**Comment by ayushnawal** [comment]
@cdrini @hornc @mekarpeles i am attaching the screenshot which displays the status of step 15,16,17 .
i also think that pip version and lessc warning should not prevent anything from working .

![screenshot from 2019-01-18 12-41-39](https://user-images.githubusercontent.com/36100944/51370906-a011ca00-1b1e-11e9-8319-ee21757f64de.png)

**Comment by hornc** [comment]
I'm not sure what is happening here, from further debugging it looks like the `make git` submodules task is not doing anything on this one install

**Comment by ayushnawal** [comment]
@mekarpeles @hornc Sir , i think we can close this issue as i have opened an another issue which is specific according to me . i think its more closer towards the actual problem https://github.com/internetarchive/openlibrary/issues/1834 
please have a look at it !
Thank you sir !
