### ISSUE TITLE
Twitter preview blocked for IA hosted images

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1841]
## Description

The Twitter preview for [E.B. White](https://openlibrary.org/authors/OL30250A/E._B._White) fails to render his image when viewed in the [Twitter validator
](https://cards-dev.twitter.com/validator)

The Twitter Cards markup is:

`<meta content="https://covers.openlibrary.org/a/id/6390049-L.jpg" property="twitter:image" />
`

but that URL apparently is a redirect to: https://ia800609.us.archive.org/zipview.php?zip=/5/items/olcovers639/olcovers639-L.zip&file=6390049-L.jpg

and the robots.txt there is 
```
User-agent: *
Disallow: /
```
(as an aside https://covers.openlibrary.org/robots.txt is a 404, which seems like an oversight)

## Screenshot:
![Screenshot from 2020-03-19 17-23-27](https://user-images.githubusercontent.com/31198893/77064980-7431f300-6a06-11ea-92f4-d9c27c569d9c.png)

## Expectation

Images get rendered properly in the preview, not matter where they are sourced from.

## Proposal & Constraints

One possible solution would be to whitelist Twitterbot for the viewer script:
```
User-agent: *
Allow: /zipview.php
```
but this would need to be done on any/all IA servers that host this content.

## Stakeholders

@mekarpeles

**Comment by guyjeangilles** [comment]
@tfmorris Are there still twitter previews? I haven't seen any when browsing Open Library

**Comment by tfmorris** [comment]
Still broken. Go to https://cards-dev.twitter.com/validator
paste in https://openlibrary.org/authors/OL30250A/E._B._White
observe that the preview shows no image and that it warns
> WARN:  The image URL https://covers.openlibrary.org/a/id/6390049-L.jpg specified by the 'og:image' metatag may be restricted by the site's robots.txt file, which will prevent Twitter from fetching it.

**Comment by guyjeangilles** [comment]
I see. This seems like a metadata problem so assigning @hornc per slack discussions

**Comment by hornc** [comment]
```
curl -I https://covers.openlibrary.org/a/id/6390049-L.jpg
HTTP/1.1 302 Found
Server: nginx/1.4.6 (Ubuntu)
Date: Tue, 17 Dec 2019 06:02:38 GMT
Content-Type: text/html
Connection: keep-alive
Location: https://ia800609.us.archive.org/zipview.php?zip=/5/items/olcovers639/olcovers639-L.zip&file=6390049-L.jpg
```
and
```
curl https://ia800609.us.archive.org/robots.txt
User-agent: *
Disallow: /
```
The msg from Twitter seems accurate.

**Comment by mekarpeles** [comment]
I've asked internally if 

```
User-agent: *
Allow: /zipview.php
```

is a change we can make on datanodes

**Comment by tfmorris** [comment]
Note: previews have been removed from https://cards-dev.twitter.com/validator 

You need to preview using twitter.com or a mobile Twitter client by starting to compose a tweet and observing the preview.

**Comment by hornc** [comment]
Is this still an issue or even relevant? #7587 is closed, and Twitter is an ex-platform.

**Comment by tabshaikh** [comment]
Doesn't seem an issue as this https://openlibrary.org/authors/OL30250A/E._B._White works when viewed in compose tweet
<img width="541" alt="Screenshot 2023-09-11 at 3 01 01 PM" src="https://github.com/internetarchive/openlibrary/assets/31198893/e1981413-5b74-4973-8f93-73d9272cc3c8">
