### ISSUE TITLE
Improve Twitter preview for author, work & edition pages

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1842]
## Description

The most obvious issue is that the Twitter preview uses the information-free description of "View the author on Open Library" while the Facebook preview uses the more informative "Books by E. B. White, Charlotte's Web, The Elements of Style, Stuart Little, The Trumpet of the Swan, One man's meat, The second tree from the corner, Letters of E. B. White, Essays of E. B. White"

## Evidence 

view-source:https://openlibrary.org/authors/OL30250A/E._B._White

```
<meta content="summary" property="twitter:card" />
<meta content="@openlibrary" property="twitter:site" />
<meta content="E. B. White \| Open Library" property="twitter:title" />
<meta content="View the author on Open Library." property="twitter:description" />
<meta content="https://covers.openlibrary.org/a/id/6390049-L.jpg" property="twitter:image" />
<meta content="E. B. White \| Open Library" property="og:title" />
<meta content="books.author" property="og:type" />
<meta content="https://covers.openlibrary.org/a/id/6390049-L.jpg" property="og:image" />
<meta content="https://openlibrary.org/authors/OL30250A/E._B._White" property="og:url" />
<meta content="Open Library" property="og:site_name" />
<meta content="Books by E. B. White, Charlotte&#39;s Web, The Elements of Style, Stuart Little, The Trumpet of the Swan, One man&#39;s meat, The second tree from the corner, Letters of E. B. White, Essays of E. B. White" property="og:description" />
```

## Expectation

The Twitter and Facebook previews should be equivalent.

## Proposal & Constraints

Since the Twitter parser will fallback to reading Facebook markup in cases where it's equivalent according to the [developer docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#twitter-cards-and-open-graph), one easy solution would be to just eliminate the overlapping Twitter markup.

Since "Books by E. B. White. <titles>" repeats information available elsewhere in the preview (and is grammatically suspect), I'd prefer the more succinct "Author of <titles".

Overlapping elements which could be deduplicated include: title, description, url, and image

The " | Open Library" after the author's name is another redundant element that I'd like to see eliminated. The space could be used for birth-death dates instead.

**Comment by tfmorris** [comment]
Equivalent issues exist with work and edition pages, so expanding the scope to include those as well.

**Comment by feat7** [comment]
@tfmorris Any progress on this? I would like to work if the work on this isn't started yet.

**Comment by shreyansh23** [comment]
@jdlrobson 
I would like to work on this issue. I haven't used twitter/facebook cards before so currently, I am reading about them.

**Comment by shreyansh23** [comment]
@jdlrobson 
Also, I was checking the current card for the author's page and got the following error.
![twitter](https://user-images.githubusercontent.com/32803230/54608478-ca2c2d80-4a76-11e9-94c2-af126bb9627d.png)
The image was not able to load.

**Comment by mekarpeles** [comment]
Good catch! Will investigate
