### ISSUE TITLE
Refresh dev instance data (bugs and lacking)

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1846]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

A new install of OpenLibrary will make use of scripts/dev-instance/dev_db.pg_dump to populate a new working instance. Many of the data here could potentially be outdated in its format  and leading to issues such as covers not appearing on the home page or broken URIs

Let's remove this data or refresh (and encourage importing data via https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data) or replace it with more recent data.
I believe this is super important as many new potential contributors are hitting this problem and it is a barrier to working with our code where having local data is vitally important. Even I, who have been coding here for 6 months still find myself working less efficient then I would like to due to bad data/missing data.

We may also want to take this opportunity to expand the data added to include reading list data for example.

## Evidence 
Create a fresh install and notice how images do not appear. Inspect and notice the ia has been converted to string from an array.

![screen shot 2019-01-26 at 9 22 05 am](https://user-images.githubusercontent.com/148752/51790559-e339f180-214b-11e9-8678-7e86e8750f3c.png)

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by tfmorris** [comment]
I'm having a hard time following the different aspects of this. An updated database dump would be good & useful, but it sounds like there are also some plain bugs that need to be fixed. Is the string vs array thing a problem with the data dump or some piece of code?

I don't think forcing developers to input their test data piece by piece is a good answer. I'd rather see us come up with a more representative set of test data that fills most developers' needs. Having the ability to easily augment that on an individual basis is useful, but the base set should satisfy 90%.

**Comment by jdlrobson** [comment]
I've broken out this specific issue into its own task.As you say, I think there are other reasons to update the database dump so probably best to think about that issue separately.

**Comment by mekarpeles** [comment]
@jdlrobson can you please review to see if this can be closed?

**Comment by jdlrobson** [comment]
The database dump is still outdated.
If someone can provide guidance on how to update the initial database data I will happily work on this task.

**Comment by guyjeangilles** [comment]
Assigning @hornc per slack discussions. Is this still an issue?

**Comment by SouthGoingZax** [comment]
Instructions for updating the dev database can be found [here](https://github.com/internetarchive/openlibrary/issues/4090#issuecomment-728382622).  Is there a set of specific things people think should be added at this point?

**Comment by mekarpeles** [comment]
Let's close this because we do have docs (i.e. a solution exists) to get new data into one's test instance. Here are the docs:

https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

https://github.com/internetarchive/openlibrary/blob/0d992241c5c37b40b131b2424e82722d16fedcad/scripts/copydocs.py
