### ISSUE TITLE
jQuery .live method is deprecated - please update all usages

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1851]
## Description
We use `.live` throughout our codebase but this has long been deprecated. It only works as we use jquery migrate which we are looking to remove (#1732)

To fix this we'll need to update like so:

Example:

```
$('.dropclick').live('click', fn);
```
becomes:
```
$( document ).on('click', '.dropclick', fn);
```

Please fix all instances in:
- [ ] openlibrary/plugins/
- [] openlibrary/templates/

## Stakeholders
@jdlrobson

**Comment by Owicca** [comment]
Hey, can I get assigned to this task?

**Comment by tabshaikh** [comment]
@Owicca you can go ahead to do this :)

**Comment by ayushshivani** [comment]
@tabshaikh i worked on this issue and want to submit a pr unless Owicca is still working on it.Can i?

**Comment by tabshaikh** [comment]
@ayushshivani if you have solved this issue go ahead and open the pr will be happy to review it :)

**Comment by shreyansh23** [comment]
@tabshaikh since no PR has been submitted yet, I would like to take this issue.

**Comment by tabshaikh** [comment]
@shreyansh23 sure

**Comment by shreyansh23** [comment]
@tabshaikh I am getting linting errors, which is failing the travis CI build.
How to avoid those errors?

**Comment by tabshaikh** [comment]
@shreyansh23 that is a nice question. To remove linting errors use "npm run lint:fix". Hopefully this will fix your linting problems and please can you make that one pr

**Comment by shreyansh23** [comment]
> @shreyansh23 that is a nice question. To remove linting errors use "npm run lint:fix". Hopefully this will fix your linting problems and please can you make that one pr

@tabshaikh I have submitted the PR
