### ISSUE TITLE
Remove Broken "List" feature on Publishers Pages

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1861]
Visit https://openlibrary.org/publishers/Barnes_&_Noble
Click "Create a new list"

Nothing happens.

Try to add to an existing list and see:
```
Request URL: https://openlibrary.org/people/jdlrobson/lists/OL131254L/seeds.json
Request Method: POST
Status Code: 500 Internal Server Error
```

Seems like this is a problem with the API.
(We've noted the error 2019-02-05/012800436803 and will look into it as soon as possible. Head for home?)

**Comment by brad2014** [comment]
I reproduced this today.

**Comment by guyjeangilles** [comment]
+1 can reproduce

**Comment by mekarpeles** [comment]
Proposing we remove the list element from Publisher pages and mark as a first good issue.

Any disagreements?

**Comment by Shubhayu-Das** [comment]
From what I understand, I have to remove 
`#: widget.html:193
msgid "Add to List"
msgstr ""
` from `messages.pot` and the corresponding `div` from `widget.html` right?

In that case, I would like to claim this issue

**Comment by jdlrobson** [comment]
Yup after doing that we will also need to review the css of the page too and likely remove the feature's CSS from the subject page.

**Comment by Shubhayu-Das** [comment]
Ok, I'll work on this

**Comment by Aj-KamaL** [comment]
@mekarpeles: Does #3197 seem like a good fit for the [issue](https://github.com/internetarchive/openlibrary/issues/1861#issuecomment-564855084) or the problem still persists?
