### ISSUE TITLE
What should I do if I face a 404 page error on local / on openlibrary.org site ?

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1864]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?
Here is the problem of landing on a 404 page error
![e1](https://user-images.githubusercontent.com/31198893/52408997-33c12f80-2afa-11e9-85d9-5f4a852b1099.png)

**Comment by tabshaikh** [comment]
What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Comment by hornc** [comment]
404s are just page / resource not found messages, meaning the server cannot find anything that matches whatever URL you requested, it's a perfectly acceptable and informative response code.  It could be a bigger problem if a page that really should exist gives a 404, but that depends on the URL.

https://openlibrary.org/soijfsofwegfewungsdmfsd  should always give a 404, and that is not a problem, the 404 is actually a good, informative, thing.

Adding `debug=true` to the end of a 404ing URL won't give any extra information unfortunately -- the page was simply not found. Nothing went wrong as far as the server was concerned, so it has no more details to give.

`debug=true` is useful when a server error occurs, which is a different kind of error. 5xx HTTP response codes and possibly other errors that are caught and result in 'this error has been logged' messages on the resulting page.

We could perhaps put more info on our 404 pages to make that clearer, or go for something cute  like most big sites:
https://github.com/404.html  (yes, githhub, this is exactly the page I was looking for!)
https://www.docker.com/404.html  Docker has always had interesting 404s
https://www.amazon.com/404.html shows different Amazon dogs...

**Comment by tabshaikh** [comment]
@hornc Thanks for your detailed answer :)

**Comment by mekarpeles** [comment]
See https://github.com/internetarchive/openlibrary/wiki/Beginner's-FAQ :)

**Comment by liaozhuzhu** [comment]
Came here from the [FAQs](https://github.com/internetarchive/openlibrary/wiki/Getting-Started#faqs) where the title is marked: "**Why do I hit a 404-page on local when the page shows up on openlibrary.org site?**" which is exactly the issue I have right now; however, is not what this issue #1864 is addressing? I may be completely wrong, but based off the title of this issue, OP seemed to get a 404 on both local and on openlibrary.org.

After following all the guides of setting up docker, setting up frontend, adding test data, etc. I not only still can't see any books on dev, but also links to /about, /subjects, etc. (essentially any of the nav links) go to 404 even though https://openlibrary.org is just fine. The exception is "/trending/now" though again no books are shown. I've attached some images of what I see. I wanted to ask in the slack, but I know the slack is on an invite only basis.

**No books / sections rendered (could possibly be related)**
<img width="1439" alt="Screen Shot 2024-01-04 at 3 55 20 AM" src="https://github.com/internetarchive/openlibrary/assets/105901847/c9b7c84d-6e90-41af-aa5f-95b8a39a4644">

**localhost:8080/subjects**
<img width="461" alt="Screen Shot 2024-01-04 at 3 57 04 AM" src="https://github.com/internetarchive/openlibrary/assets/105901847/b605c427-c258-40c2-b848-08244cf85cad">

**openlibrary.org/subjects**:
<img width="646" alt="Screen Shot 2024-01-04 at 3 57 45 AM" src="https://github.com/internetarchive/openlibrary/assets/105901847/82d551b7-5b01-4836-80b4-edae901177b1">

Thank you

**Comment by scottbarnes** [comment]
@liaozhuzhu, I think things are actually working normally for you. If you click on "Science Fiction" on the main page you should see a book called 'Flatland', though the cover may not appear properly: http://localhost:8080/works/OL118420W/Flatland.

With respect to the broken links for `/about` and the like, I think that is because they are pages on a wiki rather than being html pages generated from a template. The wiki-backed pages aren't present in the local development environment.

**Comment by liaozhuzhu** [comment]
@scottbarnes ah got it. Thank you so much for the reassurance. I was worried because the video attached under installation showed almost no difference from prod for the hosts machine. Are the exact differences from dev and prod noted somewhere in the repo and maybe I missed it?

**Comment by scottbarnes** [comment]
> Are the exact differences from dev and prod noted somewhere in the repo and maybe I missed it?

I don't think think there is such a list, but this is a good idea. I created #8687 to reflect this. Thanks, @liaozhuzhu!
