### ISSUE TITLE
What should I do to find the endpoints/files relating to the components I want to contribute to?

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1865]
## Description

> What problem are we solving? What does the experience look like today? What are the symptoms?

Openlibrary has a huge codebase so sometimes finding the files for your frontend components can be a cumbersome process so what should we do.

**Comment by tabshaikh** [comment]
https://dev.openlibrary.org/developers/routes

**Comment by mekarpeles** [comment]
See: https://github.com/internetarchive/openlibrary/wiki/Beginner's-FAQ! :D
