### ISSUE TITLE
travis ci build fails due to linting errors ?

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#1868]
## Description
What problem are we solving? What does the experience look like today? What are the symptoms?
We use Stylelint which gives us protection from various CSS issues, so if the pr doesn't follow the linting rules of the css the travis build fails.

## Evidence 
The travis error log will look something like this ->
![linting_fix](https://user-images.githubusercontent.com/31198893/52360718-b3032480-2a62-11e9-905b-9ea663b4d280.png)

**Comment by tabshaikh** [comment]
**What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?**
To fix the build failure due to linting errors in the local dev we may want to change all the statements that violate the linting rules. This can be done by running `npm run lint:fix`

**Comment by shreyansh23** [comment]
I installed open library using using docker, so to check the linting errors I had to do

`docker-compose exec web bash`
`make test`

**Comment by tabshaikh** [comment]
@shreyansh23 i also use docker but i can use the command normally outside too can you confirm

**Comment by shreyansh23** [comment]
Yes @tabshaikh I can also run the command outside but to see the errors I had to go inside the container.
Using `npm run lint:fix,`
![screenshot from 2019-02-06 23-25-26](https://user-images.githubusercontent.com/32803230/52362445-9668eb80-2a66-11e9-8d96-f489671e74ae.png)

Using `make test`
![screenshot from 2019-02-06 23-27-16](https://user-images.githubusercontent.com/32803230/52362537-d039f200-2a66-11e9-970d-28b9427580ec.png)

**Comment by tabshaikh** [comment]
@shreyansh23 Thanks for the confirmation. Updated my answer, we are trying to build a faq for new contributions where all questions and answers would be stored in this wiki https://github.com/internetarchive/openlibrary/wiki/Beginner's-FAQ. If you have some questions feel free to add them to it :)

**Comment by mekarpeles** [comment]
This is great! @tabshaikh has linked this question on our wiki -- closing this as an issue :)
