### ISSUE TITLE
Lazy-load more carousel items on subjects page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1871]
Similar to #602 -- support browsing experience on openlibrary

https://openlibrary.org/subjects/fantasy only shows 2 pages of results with no way to browse

related to https://stackoverflow.com/questions/36908678/slick-js-carousel-detect-last-thumb-to-load-more
```
$('.carousel').on('afterChange', function(e, slick, cur) {
  if (cur === slick.$slides.length - 1) {
    //Replace with your "Load More" logic
    console.log('Load More');
  }
});
```

**Comment by tabshaikh** [comment]
@mekarpeles maybe we can close this issue as the title is lazy-load more carousel items on subjects page which is accomplished :)
