### ISSUE TITLE
Last edit text and edit icon misaligned on mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1874]
![screenshot_20190210-150726_chrome](https://user-images.githubusercontent.com/148752/52541097-24362680-2d46-11e9-8e38-377149f5bc8b.jpg)
Expected: selected text should be aligned vertically with the edit icon

**Comment by Saichethan** [comment]
@jdlrobson is this issue still open 
can I work on this

**Comment by jdlrobson** [comment]
@shaneriley has an open patchset! Check good first issues for ones with no open patchset!
