### ISSUE TITLE
Refactor CSS step in makefile

### ISSUE THREAD

**Issue by shaneriley** [internetarchive/openlibrary#1879]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

In preparation of adding the Less clean CSS plugin, refactoring the `lessc` command to a for loop and function call provides a single point of update when updating the flags passed to the plugin.

## Evidence 

> Relevant url?

N/A

> Screenshot (if possible):

N/A

## Expectation
> What should by happening? What will it look like / how will it behave?

Running `make css` process Less files in the same fashion as before, however editing which Less files are converted becomes much simpler, as does changing the command line argument and flags.

## Details

> Logged in (Y/N)?

N/A

> Browser type/version?

N/A

> Operating system?

All

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

Create a lessc function that works from a single argument to iterate over the targeted Less file names.

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by jdlrobson** [comment]
@shaneriley I'm curious what you think about using Webpack (with extract styles plugin) to generate the stylesheets using a single JS file, e.g.

static/css/page-book.js
would have a single line like so:
```
@import "static/css/page-book.less"
```

I want to use Webpack for loading CSS that is JS only (per #2003) but I could be convinced to use Less clean plugin instead.

Very keen to hear your thoughts!

**Comment by shaneriley** [comment]
I've never set up a project this way, but I like not having to explicitly start up the CSS loading in the layout. I think the next step would be to set up a Less watcher for other assets to eliminate the need to run make to compile any changes made.

**Comment by jdlrobson** [comment]
Totally. How about to start off with I keep lessc for styles loaded on critical path and less-loader/webpack for styles loaded via JS. I think the first step is to at least move this from Makefile to package.json. watcher will improve our productivity for sure.

**Comment by jdlrobson** [comment]
This can be closed. Shane's patch was merged in b9e44b8 (but annoyingly it looks like it was squashed somehow into 402e3b3d45f44dcd8e785064e81972a00386b9a4 without attribution - is there some way we can fix that?)
