### ISSUE TITLE
Background image alignment in account dropdown

### ISSUE THREAD

**Issue by shaneriley** [internetarchive/openlibrary#1881]
## Description

I'm not sure if this is an issue, but it seems the background image of the `button#userToggle` element is not positioned properly. Setting a `background-position: 50% 50%;` made it more appealing to me.

## Evidence 

`https://openlibrary.org` (all pages)

![bg_position](https://user-images.githubusercontent.com/39553/52754307-1263b600-2fc8-11e9-8099-cadaeeaba134.jpg)

## Expectation

See above screenshot for proposed change.

## Details

- *Logged in (Y/N)?* Yes
- *Browser type/version?* All
- *Operating system?* All

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

Proposing the background image be centered.

**Comment by jdlrobson** [comment]
Is that your profile icon?
If so, could you share the URL for the profile avatar so I can replicate this?

I'm guessing it's assuming the avatar is a certain width/height.
(FYI We're using    background-size: cover; for avatars)

**Comment by shaneriley** [comment]
That must be the default icon it gave my admin user. I ran the Docker setup based on https://github.com/internetarchive/openlibrary/blob/master/docker/README.md, so must be it gives the admin an icon smaller than the button size. I can check it out again in the morning to know for certain.

**Comment by jdlrobson** [comment]
Thanks! Just knowing what URL it's pointing to will allow me to see if I can replicate the same issue.
I'm seeing https://archive.org/services/img/@jdlrobson on openlibrary.org so maybe this is just a problem with development setup.

**Comment by shaneriley** [comment]
Started it up again this morning, and now it points to a different image. Maybe the archive.org avatar assigned to the `@openlibrary` account was changed? This is what's there now. https://archive.org/services/img/@openlibrary

I'd try to recreate it, but I can't find anywhere to change the avatar on either the profile or account page. Is this controlled elsewhere?

**Comment by shaneriley** [comment]
Got it again tonight. I'm not sure of the exact steps, but what changed since this morning:

1. Stopped Docker containers
2. Unplugged Cinema display, moving Chrome to a retina display from a non-retina one
3. Started Docker containers
4. Visited home page in development.

Here's a screenshot of the element with a different inline background image.

<img width="1110" alt="screen shot 2019-02-14 at 7 03 34 pm" src="https://user-images.githubusercontent.com/39553/52828952-e6fccc00-3098-11e9-9788-dc8666910689.png">

**Comment by jdlrobson** [comment]
Looks like a malformed URI - https://archive.org/services/img/
Are you logged in when this happened or anonymous? If the former, something's not passing on the username correctly...

**Comment by shaneriley** [comment]
Yes, I'm logged in. What's really strange is that when first logging in, I get the default avatar image, and I can refresh all I want without it switching to the URL above. It's only once I stop and restart the Docker containers that I get the URL missing the account name.

**Comment by jdlrobson** [comment]
I don't think this is a frontend issue.  get_internet_archive_id in openlibrary/accounts/model.py is returning an empty string.

Should we throw an exception when this happens or source the URI in a different way?
```
<button class="avatar" id="userToggle" aria-label="My account" style="background-image: url('https://archive.org/services/img/$(get_internet_archive_id(ctx.user.key))');"></button>
```

**Comment by guyjeangilles** [comment]
@mekarpeles would you know why `get_internet_archive_id` would throw an empty string?

**Comment by jdlrobson** [comment]
Per 1881#issuecomment-503506793 not a frontend issue. I'd suggest @hornc as a more appropriate assignee here but feel free to pass on to someone else.
