### ISSUE TITLE
Saving edits to works and editions produces error.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1886]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?
Editing a work or edition produces

"Hmm...
Sorry. There seems to be a problem with what you were just looking at."

We've noted the error 2019-02-15/173231579101 and will look into it as soon as possible. Head for home?"

Changes are successfully committed, however. This also happens when moving an edition.

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)?

> Browser type/version? Chrome Version 71.0.3578.98 (Official Build) (64-bit)

> Operating system? Windows 7 Pro

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by mekarpeles** [comment]
related to #1891?

**Comment by mekarpeles** [comment]
@seabelis is there a url you can direct us to? I don't have enough info to verify so I'm going to close for now until you update. Thank you!

**Comment by seabelis** [comment]
Stopped happening at some point.
