### ISSUE TITLE
Cannot add new edition.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1887]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?
Error when adding new edition to existing work. Item not successfully added.
"Hmm...
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2019-02-15/173231579101 and will look into it as soon as possible. Head for home?"

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)? y

> Browser type/version? Chrome Version 71.0.3578.98 (Official Build) (64-bit)

> Operating system? Windows 7 Pro

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by mekarpeles** [comment]
@seabelis is this still a problem on dev? Thank you for discovering!

**Comment by seabelis** [comment]
Working on dev.

**Comment by mekarpeles** [comment]
Yay, this should also be on production now. Marking issue as resolved
