### ISSUE TITLE
ID Numbers drop-down cut off on edit form.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1888]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?
ID Numbers drop-down cut off on edit form.

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):
![fullscreen capture 2152019 70326 pm bmp](https://user-images.githubusercontent.com/17739465/52875427-99459980-3154-11e9-9691-99c9e8691303.jpg)
## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)? y

> Browser type/version? Chrome Version 71.0.3578.98 (Official Build) (64-bit)

> Operating system? Windows 7 pro

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by eddydg** [comment]
This happens on all `.input select` elements when window's width >= 960px (the @width-breakpoint-desktop).
CSS rule that causes that: https://github.com/internetarchive/openlibrary/blob/20098819aa72cb2290a1ed9f0d1546ba0c412a94/static/css/components/form.olform.less#L135-L139

I think this rule should be removed since this makes `selects` smaller when there is more space. I am not sure about the impact on other pages though.

**Comment by jdlrobson** [comment]
I think the only thing to be careful about here is making sure that select dropdown fits into a mobile screen. 

The input to the right of the select was designed to be on the same line and that needs to fit into a mobile screen.

I wonder what it would look like if those 2 elements were stacked instead.. would the UI be confusing?

**Comment by eddydg** [comment]
@jdlrobson it should be fine on mobile because this CSS rule is only applied for desktops screen size: `@media all and (min-width: @width-breakpoint-desktop )`.

Current behavior:
![example](https://i.imgur.com/7w1HsYb.gif)

**Comment by LeadSongDog** [comment]
Why is the styling different between Identifiers and Classifications? Was the latter just overlooked when updating the former?

**Comment by seabelis** [comment]
I see this has been fixed.
