### ISSUE TITLE
Cannot add translation information to edition

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1892]
## Description

Indicating edition is a translation does not open the translation fields. 
![translation options not showing](https://user-images.githubusercontent.com/6251786/61542044-c8677c00-aa0e-11e9-84ea-8032d88d603a.gif)

## Expectation

Previously, once a work was identified as a translation, the additional related fields would be activated.

![image](https://user-images.githubusercontent.com/6251786/61542088-dc12e280-aa0e-11e9-94cd-ace9c346ed79.png)

## Details

Ideally, this information would come from the work's data, however there is no language field identified with the work itself.

**Comment by brad2014** [comment]
- It sounds like this is a regression.
- I'm going to ask @hornc if he can assess or reproduce this.

**Comment by cdrini** [comment]
It looks like the css is getting updated (`display:none` -> `display:block`), but the `hidden` class uses `display:none !important` so they don't show up. @jdlrobson it looks like you added this as part of https://github.com/internetarchive/openlibrary/commit/0f9030c1047d5a337fc292a09085d7c353c85424 . Is it ok if I remove the `!important` or will it break something else?
