### ISSUE TITLE
Book covers wont load locally

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/openlibrary#1897]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

Book covers won't load locally.

## Details
The following issue has been raised as a question for the [beginner's FAQ](https://github.com/internetarchive/openlibrary/wiki/Beginner's-FAQ)

**Comment by koderjoker** [comment]
In order to solve this go to conf/openlibrary.yml and update `coverstore_url` to https://covers.openlibrary.org

**Comment by rohitjain00** [comment]
I have replaced the link and created a pull request.

**Comment by koderjoker** [comment]
@rohitjain00 my apologies since it wasn't clear, but this issue was raised to be added to the[ beginner's FAQ](https://github.com/internetarchive/openlibrary/wiki/Beginner's-FAQ), and not as an issue to send a pull request for.

Please try your hand at another issue, and reach out if you need any help!

**Comment by tabshaikh** [comment]
@koderjoker Thank you so much for your contributions to this wiki :)

**Comment by rohitjain00** [comment]
Then should I close the PR?

**Comment by tabshaikh** [comment]
@rohitjain00 probably yes

**Comment by liaozhuzhu** [comment]
Is this still a working solution? I can't seem to get covers still even after changing `coverstore_url`
