### ISSUE TITLE
Cannot delete or add authors

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1901]
## Description

With the latest deployment it's no longer possible to either delete or add authors on the Work Edit page. The affordances to both add (+) and remove (x) an author are missing from the page.

> Screenshot (if possible): 
![fullscreen capture 2182019 41033 pm bmp](https://user-images.githubusercontent.com/17739465/52959973-f54c3000-3397-11e9-8851-390710c1d29a.jpg)

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)? Y

> Browser type/version? Chrome Version 72.0.3626.109 (Official Build) (64-bit)

> Operating system? Windows 7 pro

## Stakeholders

@mekarpeles This is a critical bug that severely impacts the user experience.

**Comment by tfmorris** [comment]
I can confirm that this bug exists in both production and dev. I've expanded the description to include adding authors as well as deleting authors as missing functionality.

There's probably someone other than @mekarpeles who should be tagged here, but I've lost track of who's been hacking on which parts of the CSS.

**Comment by tfmorris** [comment]
Here's an example where a bad author record can't be removed:

https://openlibrary.org/books/OL23271756M/Soul_made_flesh/edit

**Comment by jdlrobson** [comment]
Not on computer at moment but are there an JS errors in the developer console? That would be my first guess.

**Comment by tfmorris** [comment]
I don't understand the relevance, but, no, there aren't any JS console errors.

No computer is needed. The screenshot here clearly shows that there no affordances rendered for "Add an author" or the red "X" to delete an author.

I would start by reviewing what got removed/changed on this page. I'm guessing it'll be pretty easy to spot.

**Comment by shaneriley** [comment]
This is likely another casualty of the jQuery update from `live` to `on` to bind events. I can try to debug it tomorrow morning.

**Comment by tfmorris** [comment]
@shaneriley Thanks for offering to help debug, but I suspect it's not related to the .live() problems (unless it's a secondary effect).

Sadly, we don't have a screenshot of the previous state of affairs, but, as I best remember it, authors 2-N would have a red X next to their edit field which would allow you to delete them and there would an additional button at the end which said something to the effect of "Add another author" and clicking it would add a new input field which could be used to select an author record.

**Comment by shaneriley** [comment]
The template has a `hidden` class on both the add author and remove inputs, but I believe those are supposed to be removed by JS in the event the CSS media type is not print. If I simply remove those classes to begin with, I see partial functionality. The add author link, when clicked, adds another input and adds a remove link to both author fields. If you click the add author link again, nothing happens. Clicking the remove link on the new input does nothing. Clicking the remove link on the initial input removes the first input. All of those misbehaviors point to an issue with the switch from `live` to `on`, as with the more greedy `live` binding there would have been a single event bound on a parent element that would always fire if these actions were clicked.

![edit-book_add-author](https://user-images.githubusercontent.com/39553/53010395-cff90980-340b-11e9-8804-1e9d1b7b8ee2.gif)

I'll try to continue my debugging this evening and come up with a solution.
