### ISSUE TITLE
Clean Up Bot creating duplicate works

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1904]
## Description

The Clean Up Bot is creating duplicate works with sequential serial numbers.

## Evidence 

> Relevant url?

https://openlibrary.org/works/OL18903545W/Welfare_for_politicians
https://openlibrary.org/works/OL18903546W/Welfare_for_politicians

## Expectation

Importing should not create duplicate records.

## Stakeholders

@hornc @mekarpeles

**Comment by LeadSongDog** [comment]
See what works are linked in the three revisions to the single edition record:
https://openlibrary.org/books/OL3311907M/Welfare_for_politicians?b=5&a=4&_compare=Compare&m=diff
https://openlibrary.org/books/OL3311907M/Welfare_for_politicians?b=6&a=5&_compare=Compare&m=diff
https://openlibrary.org/books/OL3311907M/Welfare_for_politicians?b=7&a=6&_compare=Compare&m=diff

**Comment by hornc** [comment]
Unfortunately in this case there is only one edition and multiple works.

This specific edition was an existing orphaned edition, and it looks like there were two identical MARC records in a row that were processed sequentially. The first import found that the edition had no work, and created. When the subsequent passes happened, the search index hadn't updated to reflect the recent change so another work was created....

Actually, the code shouldn't be relying on search results to determine whether the edition has a work or not at this point, it has found the correct edition, and should just look at whether `works` is set, which it would have been the second time. It's more likely it is a stale cache that does not reflect the updated works value.

To be clear, it is not the bot code that decides to create a work at this page, it's the OL import API logic that determines what to do here. 

Have we had others issues with inappropriate caching masking changes that were just made? It feels familiar, but I can't think of a specific example.

**Comment by brad2014** [comment]
@hornc does resolving this involve both cleaning up the existing corrupted data, and fixing the import process?  Should this be split into two issues?

**Comment by LeadSongDog** [comment]
Here's another instance:

https://openlibrary.org/books/OL26419305M/A_testament_of_revolution
duplicated an existing edition (and work) long present at:
https://openlibrary.org/books/OL8816701M/A_Testament_of_Revolution?v=6
then Clean Up Bot applied the same ocaid to the older edition record: 
https://openlibrary.org/books/OL8816701M/A_Testament_of_Revolution?b=7&a=6&_compare=Compare&m=diff

**Comment by hornc** [comment]
I think this can be closed due the bug fix in #2437 which closed #947
