### ISSUE TITLE
Cover upload javascript appends the form again and again.

### ISSUE THREAD

**Issue by feat7** [internetarchive/openlibrary#1911]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

This is a simple js problem. We are appending an upload form to some DOM node. If we try to add a cover (click to add cover and open the modal) but don't add and click X (close) and again open the modal to upload the cover, we can see that the upload form is appended to previous one (the forms are repeated)

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

https://openlibrary.org/authors/OL27349A/F._Scott_Fitzgerald

Click to add cover and close (X) the modal and open again.

> Screenshot (if possible):

![screenshot from 2019-02-20 02-45-31](https://user-images.githubusercontent.com/12556455/53048263-5bc96f00-34ba-11e9-8822-17c2200a0b98.png)

## Expectation
> What should by happening? What will it look like / how will it behave?

![screenshot from 2019-02-20 02-51-56](https://user-images.githubusercontent.com/12556455/53048377-992dfc80-34ba-11e9-9b31-e414245f3b2e.png)

## Details

> Logged in (Y/N)?

Y

> Browser type/version?

Chrome (Latest)

> Operating system?

Fedora 27

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

A simple js fix might do the work.

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

@cdrini @mekarpeles @jdlrobson

**Comment by shreyansh23** [comment]
Yes! I also faced the same problem

**Comment by shreyansh23** [comment]
@feat7 
I would like to like to fix this bug.
