### ISSUE TITLE
Work page is not fully responsive 

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1912]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

Textareas are larger than the screen leading to a usable but jarring editor interface on mobile 

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

https://openlibrary.org/works/OL457172W/Haroun_and_the_Sea_of_Stories_(Khalifa_Brothers_1)/edit

 Screenshot (if possible):

![screenshot_20190219-174548_chrome](https://user-images.githubusercontent.com/148752/53060165-57776480-346e-11e9-9e02-969402cd9331.jpg)
![screenshot_20190219-174535_chrome](https://user-images.githubusercontent.com/148752/53060172-5c3c1880-346e-11e9-860a-6b88a940dd76.jpg)

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by shreyansh23** [comment]
I have submitted the PR. @jdlrobson you can review.
