### ISSUE TITLE
Lists on profile page not responsive on mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1913]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

https://openlibrary.org/people/jdlrobson

> Screenshot (if possible):
![screenshot_20190219-174833_chrome](https://user-images.githubusercontent.com/148752/53060272-b2a95700-346e-11e9-8856-5731281627b0.jpg)

## Expectation
> What should by happening? What will it look like / how will it behave?

It should be styled like https://openlibrary.org/people/jdlrobson/lists

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by rohitjain00** [comment]
Should I add a scroll on overflow on this component?
![screenshot from 2019-02-22 05-49-10](https://user-images.githubusercontent.com/17525863/53193684-9f95b300-3637-11e9-9313-11bd4b84160b.png)

**Comment by jdlrobson** [comment]
No, these should horizontally stack

Both of these are mybooks-list component (static/css/components/mybooks-list.less)
but the page with the issue uses the clean variant of this component which seems incompatible with the .searchResultItem styles

This might be an HTML-only change or require additional CSS rules for mybooks-list--clean

Does that make sense?

**Comment by rohitjain00** [comment]
Adding a CSS rule flex-wrap to (".mybooks-list--clean ul") would solve the problem on all viewports.

Below are the Screenshots to show the behaviour of the list.

![screenshot from 2019-02-27 12-54-29](https://user-images.githubusercontent.com/17525863/53472938-15ae7580-3a8f-11e9-9917-97950b6b1ed0.png)
![screenshot from 2019-02-27 12-54-33](https://user-images.githubusercontent.com/17525863/53472939-15ae7580-3a8f-11e9-813e-c982163bf50a.png)
![screenshot from 2019-02-27 12-54-39](https://user-images.githubusercontent.com/17525863/53472942-16470c00-3a8f-11e9-90a6-4a7343e6b38e.png)
