### ISSUE TITLE
Editions pages breaking when & in title

### ISSUE THREAD

**Issue by GLBW** [internetarchive/openlibrary#1914]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

The book [OL26625701M](https://openlibrary.org/books/OL26625701M/Liebe_Revolution) can't be displayed (or edited) since creation two months ago. I think the problem is the ampersand in the title _Liebe & Revolution_. As a workaround the book could perhaps be renamed to _Liebe und Revolution_. (But that is not possible via the web interface.)

There are other books with ampersand in the title that are displayed correctly, i.e. [OL21642539M](https://openlibrary.org/books/OL21642539M/A_pocket_book_on_pickles_preserves). 🤷‍♂️

## Evidence 

> Relevant url?

https://openlibrary.org/books/OL26625701M/Liebe_Revolution

Further information about the book:

* [Publisher](https://www.infoverlag.de/programm/biografie/439/liebe-revolution.-hedwig-lachmann-und-gustav-landauer-zwischen-kunst-und-politik)
* [Deutsche Nationalbibliothek](http://d-nb.info/1161685235)
* [Wordcat](https://www.worldcat.org/title/liebe-revolution-hedwig-lachmann-und-gustav-landauer-zwischen-kunst-und-politik/oclc/1043118436)

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

The book should be displayed and one should be able to edit it via the web interface.

## Details

Original discussion was in slack:
https://internetarchive.slack.com/archives/C0ETZV72L/p1550611872147000

> Logged in (Y/N)?

Y

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by tfmorris** [comment]
As was pointed out (a couple of times) in chat, there are existing books with ampersands (&s) in the title which render fine. 

Two possibilities come to mind: 
* The character isn't correctly JSON encoded for that particular record, for whatever reason
* It's a different problem altogether.

**Comment by GLBW** [comment]
Thank you! My first intend in slack was to get the title changed by an admin. Please see:

https://internetarchive.slack.com/archives/C0ETZV72L/p1550611872147000

I was told there to open an issue here under that title. And I also wrote above:

> There are other books with ampersand in the title that are displayed correctly, i.e. [OL21642539M](https://openlibrary.org/books/OL21642539M/A_pocket_book_on_pickles_preserves). 🤷‍♂️

**Comment by GLBW** [comment]
The book can be displayed now (with ampersand) thanks to Charles and I want to close this issue. https://openlibrary.org/books/OL26625701M/Liebe_Revolution
