### ISSUE TITLE
Unused code? core/init.py

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1917]
## Description

I'm not sure that this code is being used: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/init.py

It has tests which currently require root to run. I discovered this while trying to get the Coverstore tests passing in #1916 

From a quick check, neither Open Library or the infamous olsystem appear to be using this code.

Raising it here for discussion so we can potentially remove extraneous code.

## Stakeholders
@mekarpeles

**Comment by brad2014** [comment]
For ref: The code was committed by @anandology in 2011.

**Comment by cdrini** [comment]
Pycharm found no references to this file (except for its test cases). The docstring also says this was for the dev env. Not sure if this means dev.openlibrary.org or the actual local dev environment. If it's for the local, then we can delete it. What do we use to launch dev.openlibrary.org, @mekarpeles ?

https://github.com/internetarchive/openlibrary/blob/058c6ce374d4eb2c3ff514ef2e5420794a2ff1ee/openlibrary/core/init.py#L1-L9

**Comment by guyjeangilles** [comment]
@mekarpeles Can you answer @cdrini 's question about whether this is used for dev.openlibrary.org

**Comment by hornc** [comment]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/init.py no longer exists / has been removed. I consider this resolved.
