### ISSUE TITLE
Create a page with current Solr index delay / update stats

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1918]
## Description

In order to be confident in our data, users (and admins!) need to know that their edits will be reflected in search results. Since there is a delay between making an edit and seeing the results in search, we want a page that gives the expected wait time and alerts if there are longer than usual delays or problems that need to be resolved.

Wikidata has https://www.wikidata.org/wiki/Special:DispatchStats

We would like a similar status display for current Solr index queue and timings so users can understand how long to expect to wait for their edits to appear in search, or to highlight whether there are system problems that need to be addressed.

Need to investigate what stats we can gather from solr and what would be useful to display.

## Stakeholders
@hornc @tfmorris @cdrini

**Comment by guyjeangilles** [comment]
Making this a sub-task of #789.

**Comment by tfmorris** [comment]
There's no real reason for this to be coupled to other Solr work. The update queue is maintained in a separate service.

**Comment by hornc** [comment]
Solr indexing seems to be a lot better and doesn't appear to be a major cause of issues. I am withdrawing my feature request as things have moved on.
