### ISSUE TITLE
support.py overrides some built-ins

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#192]
- support.Case overrides type within Case locals()
- support.Case.load overrides 'id' builtin. Recommended change to 'id_'
- support.Case.all dict call uses reduce builtin as a key: dict(reduce=False). In general, it is dangerous using builtins as keywords (assuming it is not getting passed in as a **kwargs -- in this case it is), as the built-in can be overriden within the new scope. As a result, recommended change to {'reduce': False}

**Comment by guyjeangilles** [comment]
@mekarpeles Is this still an issue? I didn't the above functions in the support.py file in the directory. 

If this is still an issue, are you willing to be assignee?

**Comment by tfmorris** [comment]
The closest match that I can find is openlibrary/plugins/openlibrary/support.py but I don't see any of the relevant code.

Given that there was no response from the original poster, I'm closing this. Please feel free to reopen with more details.
