### ISSUE TITLE
Publishing History graph not responsive on mobile screens

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1926]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?
The publishing history graph is not responsive on the mobile screens as we have to horizontal scroll to see the full graph
## Evidence 

> Relevant url?
https://openlibrary.org/subjects/romance

> Screenshot (if possible):
![screenshot_2019-02-25 romance open library](https://user-images.githubusercontent.com/32239181/53317309-288b4380-38f1-11e9-9ae1-49cd98cc9fd5.png)

## Expectation
> What should by happening? What will it look like / how will it behave?

Horizontal scrolling should be disabled

## Details

> Logged in (Y/N)?

Yes

> Browser type/version?
Any browser

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

We can specify the breakpoints and decrease the length of x co-ordinate and even skip some of the points on further decrease in the size of screen

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by shreyansh23** [comment]
Wanted to add that the Yaxis label is not in correct position even on desktop view.
Therefore both desktop and mobile view css needs to be fixed.

**Comment by shreyansh23** [comment]
I want to take this issue @Pratyush1197
