### ISSUE TITLE
Ebook available in facets but not in listing

### ISSUE THREAD

**Issue by nemobis** [internetarchive/openlibrary#1929]
## Description

It often happens, e.g. when searching titles from the wishlist (let's say 5 % of cases), that the facet shows "ebook: 1" but the work listing doesn't have any. Usually the other facets in such cases include DAISY, which makes me suspect there's a DAISY-only borrowing available which is not listed for other purposes but nevetheless surfaces.

## Evidence 

https://openlibrary.org/search?q=Guide+to+Methods+for+Students+of+Political+Science
https://openlibrary.org/works/OL1976259W/Guide_to_methods_for_students_of_political_science

## Expectation

Always show the digitised edition even if I can't borrow it, and/or match the facet with what actually shown.

## Details

> Logged in (Y/N)?

Yes.

**Comment by tfmorris** [comment]
I suspect your analysis regarding DAISY is correct or close. I've seen other indications that perhaps a not-quite-right query is being used for availability.

**Comment by tfmorris** [comment]
The context for my comment about was #1016 which uses an IA query that includes the dubious terms Collection:inlibrary and loan_status_status:Available (sic). It's the latter term which I think is problematic and relevant for this case, because if you remove it, you get:

> Availability
> 2,934 Available to Borrow
> 2,151 Always Available
> 740 Waitlist

vs the default

> Availability
> 2,934 Available to Borrow

The details may be different for this case, but I suspect it's a similar misconception about what's relevant to include in the search results.

**Comment by guyjeangilles** [comment]
Still a bug several months later.

**Comment by mekarpeles** [comment]
Not sure how to assess / solve problem (other than show previewable books under ebooks toggle?) Closing for now, please re-open if there's more details about how the correct solution should look

**Comment by nemobis** [comment]
Mek, 23/01/21 15:11:
> Not sure how to assess / solve problem (other than show previewable books under ebooks toggle?)

Yes, that's one solution (you mean what I called "Always show the 
digitised edition even if I can't borrow it", if I understand 
correctly). It might be a bit too noisy when there are many search results.

Otherwise, it should "only" be a matter of fixing the facets, so that 
they only count things I can actually see. I've not looked at the code 
(or I forgot), but I suppose you're doing some ElasticSearch query and 
then performing some additional filter on the application side. If 
ElasticSearch already contains the needed information, I suppose you 
could fix it by generating the facets with two different queries: one 
for users who can borrow all the books (e.g. because they have DAISY 
permissions), another for the generic user.

There are probably several abuses of terminology above, I hope it's 
still understandable.
