### ISSUE TITLE
Add "PUT" to lists api, to update lists.

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1930]
## Description

In the list api we do not have the feature of updating a list by using put method. I can work on this.
## Evidence 

`https://openlibrary.org/dev/docs/api/lists`

![screenshot_2019-02-27 upcoming lists api open library](https://user-images.githubusercontent.com/32239181/53479539-4ac2c400-3a9f-11e9-9560-2d5429f8060a.png)

**Comment by guyjeangilles** [comment]
@Pratyush1197 What's the status of this issue?
