### ISSUE TITLE
GSOC leaderboard for keeping track of participants

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1932]
## Description
I have a suggestion which can help in keeping the track of number of pull requests, opened issues and count total number of commits by a user to know who has given the maximum number of contributions to the organization in this period.
The web application can be deployed and accessed by all the users and mentors

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

> Screenshot (if possible):

## Expectation
> What should by happening? What will it look like / how will it behave?

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by tabshaikh** [comment]
@Pratyush1197 that's a great idea but currently we are small group of motivated open source contributors and developing and managing this for a small community would be difficult and our focus as a community for this year is to remove bad experiences for users therefore we are targeting priority issues which can have a huge impact on user's experience of OL

**Comment by tfmorris** [comment]
Github already tracks much of this automatically by default:

https://github.com/internetarchive/openlibrary/pulse/monthly
https://github.com/internetarchive/openlibrary/graphs/contributors

**Comment by mekarpeles** [comment]
Thanks for your comments all -- I think this could be a great idea for the Google Summer of Code program but the Open Library issue tracker probably isn't the best place for this -- I agree fully with @tabshaikh's response.

Closing for now :)
