### ISSUE TITLE
Regensburger Verbundklassifikation has wrong article

### ISSUE THREAD

**Issue by GLBW** [internetarchive/openlibrary#1933]
## Description

The classification _Regensburger Verbundklassifikation_ has a wrong article _der_. _Der_ is either the male article, but _Regensburger Verbundklassifikation_ is female in german, see [Klassifikation](https://en.wiktionary.org/wiki/Klassifikation) in Wiktionary. Or _der_ could also be the female article, but then it would be genitive. In this case it would mean _of the Regensburger Verbundklassifikation_.

I think it was found by a person who doesn't speak german on the net in the first place. For example on the [Regensburger Verbundklassifikation website](https://rvk.uni-regensburg.de/). The sentence

> Herzlich Willkommen im Portal _der_ Regensburger Verbundklassifikation!

means:

> Welcome to the portal _of the_ united (or union) classification of Regensburg!

## Expectation

Simply drop the _Der_.

**Comment by Pratyush1197** [comment]
Can you please provide the link where this error is occuring

**Comment by GLBW** [comment]
![bildschirmfoto von 2019-03-04 10-22-42](https://user-images.githubusercontent.com/47823517/53737073-cb146b00-3e8b-11e9-9ba7-a83eed413f21.png)

https://openlibrary.org/books/OL12691582M/Die_Deutsche_Bank_und_die_Arisierung./edit

https://dev.openlibrary.org/books/OL12691582M/Die_Deutsche_Bank_und_die_Arisierung./edit

**Comment by Pratyush1197** [comment]
Thank you. I will fix this issue

**Comment by hornc** [comment]
relates to #2062

**Comment by hornc** [comment]
I have updated the production config to remove the article: https://openlibrary.org/config/edition
Here is an example edition with a classification now displayed as "Regensburger Verbundklassifikation":

https://openlibrary.org/books/OL758259M/Relativna_re%C4%8Denica
