### ISSUE TITLE
Characters stripped from excerpts.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1935]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

Some characters are stripped from excerpts.

## Evidence 
I added the first sentence: How come "Unofficial"?
The last "? are dropped after save, leaving it as: How come "Unofficial

> Relevant url?

https://openlibrary.org/works/OL5104582W/The_Unofficial_Guide_to_Disneyland

## Expectation
> What should by happening? What will it look like / how will it behave?

Text should be saved as entered.

> Logged in (Y/N)?

Y

> Browser type/version?

Chrome Version 72.0.3626.109 (Official Build) (64-bit)

> Operating system?

Windows Pro 7

**Comment by LeadSongDog** [comment]
Looking at the json, we see:
"excerpts": [{"comment": "first sentence", "excerpt": "How come \"Unofficial",
so it looks like the escaping of the double quote was somehow borked. 

@seabelis could you please be very explicit about how you placed the quotation marks in your edit attempt?

**Comment by seabelis** [comment]
How come "Unofficial"?

**Comment by LeadSongDog** [comment]
Hmm, when I copypasted the above clip from the json, github dropped an escape (I forgot to treat it as code): there is a backslash before the double quote following _come _  so it reads
`"excerpts": [{"comment": "first sentence", "excerpt": "How come \"Unofficial"`
but I think it should have been
`"excerpts": [{"comment": "first sentence", "excerpt": "How come \"Unofficial\"`
instead if the functionality was working. We should not require users to think _that_ hard about what they type.

**Comment by mekarpeles** [comment]
Let's reserve priority 0 for "multiple users are complaining, mek needs to get out of bed and fix this now"

**Comment by hornc** [comment]
related to, or at least same code area as #228

**Comment by guyjeangilles** [comment]
@hornc I'm labeling this as backlogged since it doesn't seem like much progress is happening. Let me know your thoughts.

**Comment by seabelis** [comment]
This actually seems fixed. Not sure when that happened, but I just tried it on the work originally posted and it worked as it should.
