### ISSUE TITLE
Provide padding in Add to list button on authors page

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1937]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

This is to Provide padding in Add to list button on authors page as shown in the screenshot 
## Evidence 

> Relevant url?
https://openlibrary.org/authors/OL659442A/Keith_Park

> Screenshot (if possible):
![screenshot_2019-03-02 keith park open library](https://user-images.githubusercontent.com/32239181/53679921-940e5000-3cf9-11e9-81a2-a38ccf33ec0d.png)

## Expectation
> What should by happening? What will it look like / how will it behave?

Proper padding should be present

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by rohitjain00** [comment]
I'll look into it
