### ISSUE TITLE
Add to list page do not give any response when a list is removed

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1938]
## Description

When we select a list from the dropdown of 'Add to list' one of the list is selected. Now when we remove the selected list and again click on 'Add to list' then the button gets unresponsive and it only response when we click refresh button

## Evidence 

https://openlibrary.org/authors/OL2188410A/Calvin_Collier_Bishop

![screenshot_2019-03-02 calvin collier bishop open library](https://user-images.githubusercontent.com/32239181/53680070-eea8ab80-3cfb-11e9-8849-414e7f1fdef9.png)

## Expectation

On removing the list the 'Add to list' button should work without refreshing the page.

**Comment by brad2014** [comment]
Perhaps related to #1890 ?

**Comment by jdlrobson** [comment]
This is fixed now. Was likely #1890
