### ISSUE TITLE
Make the table of loan page look neater

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/openlibrary#1949]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

Currently the buttons seem to overlap, creating bit of confusion for the user. Moreover, there is a misalignment date vertically.

## Evidence 

> Relevant url?
`https://openlibrary.org/...`

https://openlibrary.org/account/loans

> Screenshot (if possible):
![first-issue](https://user-images.githubusercontent.com/32803230/53759966-90402080-3ee7-11e9-9b00-d3fda146b174.png)

## Expectation
> What should by happening? What will it look like / how will it behave?

This page could be made much more neater and pleasant looking.

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by shreyansh23** [comment]
@mekarpeles @hornc @jdlrobson If you find this issue valid, I would like to work on it.

**Comment by brad2014** [comment]
@shreyansh23 can you chat with @jdlrobson about if/how to proceed?

**Comment by jdlrobson** [comment]
How can I get loans locally?

**Comment by guyjeangilles** [comment]
@jdlrobson #782 and #1285 may be helpful. It looks like @mekarpeles could elaborate

**Comment by Yashs911** [comment]
@jdlrobson I guess we can close this issue.
![image](https://user-images.githubusercontent.com/64412143/104346876-eccde700-5525-11eb-83b5-5477b01b7523.png)

**Comment by jdlrobson** [comment]
@Yashs911  thanks for flagging. Yes this page looks good, so this issue no longer makes sense.
