### ISSUE TITLE
Make search button on Subjects page match the theme of the website

### ISSUE THREAD

**Issue by yash-kedia** [internetarchive/openlibrary#1951]
## Description
The search button needs some redesigning to match it with the color pallete and theme of the wesite.

## Evidence 

https://openlibrary.org/subjects/science

![screenshot 14](https://user-images.githubusercontent.com/39669117/53763528-0b5a0480-3ef1-11e9-8417-82a8a9293add.png)

## Expectation
The button  should match the color pallette of the site and it color should be blue and needs a design too. 

## Details

> Logged in (Y/N)?Y

> Browser type/version?Chrome

> Operating system?Windows

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by yash-kedia** [comment]
@mekarpeles @hornc  i am willing to work on this issue if it is ok

**Comment by mekarpeles** [comment]
Please check on dev.openlibrary.org/search as some effort has been put into this issue.

Also feel free to work on it but please also propose what it might look like in giving the community an opportunity to weigh in on the design

**Comment by jdlrobson** [comment]
See also #1184 !

**Comment by yash-kedia** [comment]
i saw the issue #1184  i have made the button blue by applying the correct class
![screenshot 16](https://user-images.githubusercontent.com/39669117/53809521-ea3df600-3f7a-11e9-81bb-b2310d7ea39e.png)
this is what i propose it to be

**Comment by yash-kedia** [comment]
@mekarpeles @jdlrobson now the search button is not looking odd on the webpage and is matching with the theme of the page

**Comment by jdlrobson** [comment]
@yash-kedia I understand what you are trying to achieve and would support this change given I think it's better if we have less classes for describing buttons (and I'd like to remove https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#buttonbrowserdefault-was-buttonsearch-- from the styleguide! 😄  )

I do however wonder if the search should be a white button like the edit icon:
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#buttonlink
or even better, maybe it should be a magnifying glass for consistency with the search box in the header.

Standardization is hard! ⚒

**Comment by yash-kedia** [comment]
yup i beliveve and support your changes and would sure do it

**Comment by manishupadhyaya** [comment]
@mekarpeles @hornc @yash-kedia I would also like to work on this issue

**Comment by jdlrobson** [comment]
I would prefer not making any design changes at the current moment of time and rather spend energy on making these components easier to create.

All components should have associated macros otherwise we will end up with multiple definitions referencing these classes all over the place.

Changing the style of something will then be much easier. 

What would be more useful is finding any templates that mention say the cta-btn class and making them use a macro. Is that something you would be interested in doing?

**Comment by brad2014** [comment]
Note to self and @jdlrobson - if there is another issue related to refactoring classes into macros (fixing that will fix this), then refer to it here and close this one.  Or, retitle this one to "Replace cta-btn class with macro", and label it `type: refactor`.

**Comment by guyjeangilles** [comment]
Making this a subtask of #1184

**Comment by jdlrobson** [comment]
This looks like a duplicate to me. Thanks for poking.
