### ISSUE TITLE
Adding Rules and Regulations regarding pull request

### ISSUE THREAD

**Issue by rohitjain00** [internetarchive/openlibrary#1957]
## Description [ feature ]
Going through this project I saw that there are no rules regarding the PR a  user creates. Only a template for PR is provided.

> Relevant url?
https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md

> Screenshot (if possible):
![screenshot from 2019-03-07 18-58-01](https://user-images.githubusercontent.com/17525863/53960013-20aa7b00-410b-11e9-861b-2eebaf75202a.png)

## Expectation
>I think proper guidelines must be prepared for new contributors about how to name a branch he/she creates and what details are necessary for the PR. 

## Proposal & Constraints
**Here are some of the blogs regarding this issue**
- https://opensource.com/article/18/6/anatomy-perfect-pull-request
- https://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/

**Comment by guyjeangilles** [comment]
[Contributing.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md) has been updated with new guidelines. Closing.
