### ISSUE TITLE
Help us meet librejs requirements openness/license requirements

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1962]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

I was talking to RMS and he was emphatic that he'd like openlibrary.org to pass https://www.gnu.org/software/librejs/ validation. Not top priority, but it would be great for us to do better about licensing our code :)

**Comment by jdlrobson** [comment]
@mekarpeles let me know if there is anything actionable you would like me to do on the frontend, but I'm not the right person to lead this :)

**Comment by mekarpeles** [comment]
I think this is a bigger effort that we can afford to bite off given resources, going to close.
