### ISSUE TITLE
Fixing tab order (on works editions table entries)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1963]
Using flex order has affected the tab order. Got to resolve that!

![tab order](https://user-images.githubusercontent.com/30471843/54015593-286b2d80-41a6-11e9-901d-11522f0ec380.gif)

Another thing I noticed while tabbing through the page with voice over is that a user isn't informed when an eBook isn't available, and the library links' placement isn't clear on the mobile and tablet version of the component. Could work on those features too, or add them in another PR.

_Originally posted by @koderjoker in https://github.com/internetarchive/openlibrary/pull/1899#issuecomment-470865551_

**Comment by jdlrobson** [comment]
I'm not 100% sure I understand the problem here. It seems useful that the read eBook is the third tab as screen reader users can get to the "read" action quicker.

The HTML and thus the tabIndex reflects the order of importance. I'm not sure it matters visually what the order is.

Are you asking for tabIndex to be removed on certain elements?

**Comment by koderjoker** [comment]
@jdlrobson I guess I was too fixated on making the visual order match the dom order as I thought the tab jumping around would make it irksome for someone using a keyboard. 😅 

The changes I want to propose for making it easier for screen readers are
-Give all library links a title description (Library.link)
-Inform the user when an eBook isn't available (tabbing just jumps over "No ebook available")

![new](https://user-images.githubusercontent.com/30471843/54084426-732ba780-4356-11e9-8910-447cf81ea0d8.gif)

**Comment by jdlrobson** [comment]
Found a little more guidance on this issue.

"CSS Flexbox can create a disconnect between the DOM order and visual presentation of content, causing keyboard navigation to break. For this reason, the CSS Flexible Box Layout module warns against resequencing content logic, but asking authors not to use flexbox in this way seems illogical in itself."

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items
https://tink.uk/flexbox-the-keyboard-navigation-disconnect/

**Comment by brad2014** [comment]
@koderjoker , I assigned this to you since I see you are doing assessment.  Feel free to work with @jdlrobson to change assignment as needed.

**Comment by Yashs911** [comment]
@jdlrobson I guess we can close this issue.
In current version:
Tabbing order is same as visual order.
We can tab "Not in Library" button.
![image](https://user-images.githubusercontent.com/64412143/104481276-9a56fe00-55eb-11eb-9626-fc74e3bd82a8.png)

**Comment by jdlrobson** [comment]
I will let @mekarpeles confirm whether this is resolved.

**Comment by mekarpeles** [comment]
Resolved!
