### ISSUE TITLE
Dispensable underline on Add to List button (dropper list component)

### ISSUE THREAD

**Issue by rohitjain00** [internetarchive/openlibrary#1968]
## Description
> Unnecessarily underlined button

> Relevant url?
https://openlibrary.org/subjects/fantasy#sort=date_published&ebooks=true

> Screenshot (if possible):
![addToListButtonUnderlined](https://user-images.githubusercontent.com/17525863/54101815-918fb280-43eb-11e9-8896-a8aae86e9d9f.png)

## Expectation
> Button should not be underlined

## Details
Text decoration is set to underlined which should be removed

> Logged in (Y/N)?
Y

**Comment by jdlrobson** [comment]
Please submit  a patch to https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#dropper-list component!
