### ISSUE TITLE
Login Page looks Dull, changes in the login Button and maintaining uniform font size is required

### ISSUE THREAD

**Issue by manishupadhyaya** [internetarchive/openlibrary#1969]
I would like To make changes to the login Page UI
> Relevant url?
'https://openlibrary.org/account/login?redirect=/books/OL24206976M/Ferno_the_fire_dragon/borrow?action=borrow'

> Screenshot (if possible):
https://screenshots.firefox.com/jp5RciUDxxCN35Qi/openlibrary.org

## Expectation
Some basic Changes in the UI is required.

**Comment by shreyansh23** [comment]
@manishupadhyaya 
What kind of changes do you expect?

**Comment by manishupadhyaya** [comment]
@shreyansh23 I mean the Basically changes in the button color and giving border radius to it. And Hovering over links gives a greenish Color. If it would Be greyish it would go with the site's color maintaining a uniformity

**Comment by jdlrobson** [comment]
Please see my comments on #1951. standardization is hard and this is not really a top priority right now. What's more important is documenting existing components and how they are constructed. 

I'd rather have a designer go over the component library [1] we have been documenting and make these decisions with the whole site in mind.


[1] https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library

**Comment by manishupadhyaya** [comment]
https://screenshots.firefox.com/7Ay9qaQ1Ex637XOK/openlibrary.org

Well a little padding makes it more attractive.

**Comment by mekarpeles** [comment]
I agree with @jdlrobson on this point. More thought is required on consolidating our buttons so that they are consistent across the website. We should try not to design components on a per page basis
