### ISSUE TITLE
Fix CSS for modals

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/openlibrary#1971]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

The modals in openlibrary work fine but have many CSS issues in them. 
- The cross button goes out of the box
- The content inside the modal starts touching the border

## Evidence 

> Relevant url?

https://openlibrary.org/works/OL1487362W/Charlotte_Temple
Then click add cover

>Screenshot (if possible):
![cross-padding](https://user-images.githubusercontent.com/32803230/54110622-e17c7280-4407-11e9-8f00-57e4135c21c9.gif)

## Expectation
> What should by happening? What will it look like / how will it behave?

Cross button position should be fixed along with adding necessary padding to the content.
The modal should look similar to the design proposed in https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library

## Details

> Logged in (Y/N)? Y

> Browser type/version? Firefox

> Operating system? Ubuntu 18.04

## Stakeholders
> @ tag stakeholders of this bug / feature
@mekarpeles @seabelis

**Comment by shreyansh23** [comment]
I would like to work on this! :smiley:

**Comment by jdlrobson** [comment]
We actually have multiple ways to make overlay modal windows. I'd like to consolidate on a single JavaScript construction for them. Provided this is a css only fix I support this change but if it requires Javascript changes i think we should be more ambitious!

**Comment by shreyansh23** [comment]
@jdlrobson 
The above issue needed only CSS fixes. But yes! we can adopt better ways of having overlay modals (or dimmer) if javascript changes are required.

**Comment by jdlrobson** [comment]
> Inside colorbox, .floater elements have their widths hardcoded in cbox.less
div.floater { position: relative; font-family: @lucida_sans_serif-1; width: 640px; min-height: 670px; ........ } 
> But the default value of border-sizing of colorbox is box-sizing: border-box. This is causing the problem. As we are giving width:640px in .floater class we need box-sizing rule of colorbox to be content-box.
[Ref]
> So just one addition box-sizing:content-box in colorbox will make things work without modifying CSS of it's child elements.

> Would this be fine?
> [Ref] https://developer.mozilla.org/en-US/docs/Web/CSS/box-sizing

This sounds fine to me! If I understand your analysis correctly, we can just fix this with one line of CSS:

```
#cboxContent {
    box-sizing: content-box;
}
```

and yes.. that would be a lot better as it would avoid the !important's entirely!
