### ISSUE TITLE
Css issues in list of Editions

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/openlibrary#1972]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

On work page the list of editions is displayed. I found some CSS flaws in it:
- The sorting icons on the top row collide into one.
- The cover image size is too small.
- There is horizontal overflow in the td.book element (as shown in the screenshot).

> Relevant url?
`https://openlibrary.org/...`

https://openlibrary.org/works/OL13101191W/Alice's_Adventures_in_Wonderland

> Screenshot (if possible):

![editions-list](https://user-images.githubusercontent.com/32803230/54116554-04f9ea00-4415-11e9-8186-8ea7b7446a43.jpeg)

## Expectation
> What should by happening? What will it look like / how will it behave?
The edition list should be responsive.

## Details

> Logged in (Y/N)? Y

> Browser type/version? Chrome Mobile Browser

> Operating system? n/a

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature
@mekarpeles @seabelis

**Comment by shreyansh23** [comment]
I would like to correct this.

**Comment by koderjoker** [comment]
@shreyansh23 this issue already exists (issue [#1339](https://github.com/internetarchive/openlibrary/issues/1339)) and is being worked on (pull request [#1899](https://github.com/internetarchive/openlibrary/pull/1899))

Feel free to work on another issue! 🙂

**Comment by shreyansh23** [comment]
Oh! I see. Thanks for telling :relaxed:   @koderjoker

**Comment by shreyansh23** [comment]
Duplicate of #1339
Closing this issue.
