### ISSUE TITLE
Bad imports, with title "<>"

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1985]
The following are books that were imported in a way that caused them to end up with `<>` as their titles. The two that I checked were both foreign languages/script with one Korean and one Russian. One was imported by horncbot and the other by ImportBot. Neither had a machine comment pointing to the original source record making provenance more or less impossible to trace.

/works/OL18170370W
/works/OL17947315W
/works/OL16977993W
/works/OL16939727W
/works/OL17862028W
/works/OL16916682W
/works/OL17717004W
/works/OL18170369W
/works/OL17698451W
/works/OL16987885W
/works/OL17947379W
/works/OL17947339W
/works/OL17729768W
/works/OL18170393W
/works/OL16993638W
/works/OL16993614W
/works/OL16951128W
/works/OL17730326W
/works/OL16961108W
/works/OL17866591W
/works/OL18170396W
/works/OL18161809W
/works/OL16929827W
/works/OL16968044W
/works/OL16949601W
/works/OL17728155W
/works/OL18170392W
/works/OL16949885W
/works/OL16921310W
/works/OL18170377W
/works/OL18170565W
/works/OL18170371W
/works/OL16954419W
/works/OL17911286W
/works/OL16916220W
/works/OL16978654W
/works/OL16915488W

This was originally reported as a client library bug:  https://github.com/internetarchive/openlibrary-client/issues/138

**Comment by hornc** [comment]
The source records are all from archive.org items that had the `<>.` title in their source MARC records. This title was propagated to the archive.org items, and hence to openlibrary. The archive.org items generally had correct alt-title fields populated from the MARC data so I used these with a bit of tidy up in some cases to fix the source titles. I'll pull the updated titles into the OL works and editions next.

The source items are:
```
isbn_9788953117693
excavationreport0094kang
atlascaesiumdepo00comm
isbn_5899282742
unset0000unse_y9e9
isbn_5891470144
isbn_9788993985177
isbn_9788953111882
isbn_9788953110847
isbn_594278177X
donghaemangsangd0095unkn
heruinsofmandeok0023bucc
secretpaperback00linx
isbn_9788993227154
isbn_9282777057
isbn_5222064891
isbn_9789290215912
isbn_9787302075554
isbn_5902172047
isbn_0782115101
isbn_9788996244998
goasexchangestud00unkn
lapoursuitedepi00arnd
lapoursuitedepi00jrga
isbn_5939721540
isbn_5860070020
isbn_9787508418803
isbn_9788991359413
isbn_5860073488
artanaloglayout00ahas
isbn_9788973317790
isbn_9789745373839
isbn_9788965623427
isbn_5807100239
unset0002unse_v1a6
commandehinfinie00ducg
isbn_5170000685
isbn_5938780314
```
The editions associated with the works above have source data.

**Comment by hornc** [comment]
All of these works + their editions have titles now and can be viewed properly.
