### ISSUE TITLE
Edit page not responsive on mobile

### ISSUE THREAD

**Issue by Pratyush1197** [internetarchive/openlibrary#1986]
## Description
>The edit  page is not mobile responsive as the classification box is going out of boundary as seen in screenshot

> Screenshot (if possible):
![Screenshot_2019-03-16 The Deutsche Bank and the Nazi Economic War Against the Jews Open Library](https://user-images.githubusercontent.com/32239181/54470894-17d63b00-47d6-11e9-9ed3-d2086b1afa13.png)

## Details

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @ tag stakeholders of this bug / feature

**Comment by Pratyush1197** [comment]
I want to work on this issue

**Comment by jdlrobson** [comment]
@Pratyush1197 please do!
I think the problems here are as followings
* Use of size attribute
* Use of width attribute
* There needs to be a `select { width: 100%; }` rule inside static/css/base/common.less

**Comment by Saichethan** [comment]
is this still open ?
I would like to work on it

**Comment by mekarpeles** [comment]
@Saichethan I believe this is still open and you're welcome to work on it.

@Ifeanyijasper had also expressed interest in looking into it -- send me an email mek@archive.org and I'll make sure you receive an invite, we'll can help you with next steps or help you find other issues

**Comment by mekarpeles** [comment]
@illseption mentioned he wanted to take a stab at this. Is this right? If so, I'll add you as the owner.

**Comment by illseption** [comment]
Yes, thanks!

**Comment by illseption** [comment]
Hi, what all files do I need to make the changes to? Is it the above mentioned common.less file?

**Comment by guyjeangilles** [comment]
Not seeing this anymore. Closing.
![Screenshot_20191122-150418_Firefox_crop](https://user-images.githubusercontent.com/7256157/69457480-0b42b300-0d65-11ea-8d0b-73b4c5078cd2.jpg)
