### ISSUE TITLE
Move all vendor prefix usages into mixins

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1995]
**Description**
> What problem are we solving? What does the experience look like today? What are the symptoms?

In preparation for auto-prefixing/removing vendor prefixes and making our rules consistent we should move all vendor prefixes into mixins defined inside static/css/less/mixins.less

**Expectation**

We know it's done when a search for the following yields one result (+ any lib usages):
```
ag "\-webkit-" static/css/
ag "\-moz-" static/css/
ag "\-ms-" static/css/
```

DO NOT touch the files inside the lib folder. These are from vendors and we shouldn't tamper with them.

Here is an example:

```
div.siteSearch {
    -ms-flex-order: 3;
    order: 3;

}
```
becomes:
```
div.siteSearch {
  .flex-order();
}
```

**Stakeholders**
@jdlrobson

**Comment by ShreyashApp** [comment]
Hi,
 I would like to work on this, if no on else is doing something similar to it.

**Comment by ShreyashApp** [comment]
Hi, 
Which all files should I make changes too. Or is to all of them?

**Comment by jdlrobson** [comment]
All files! I recommend doing this over several patches doing one mixin at a
time.

**Comment by ShreyashApp** [comment]
Hey, I am the working on this. I have made the necessary changes but there is no way to find out if the are being call on to all the implementations. As many of the css isn't even being used by templates. If you have any suggestions please let me know.

**Comment by cdrini** [comment]
Are there plugins we can use to make Less or webpack do this automatically?

**Comment by guyjeangilles** [comment]
@shreyansh23 Where is the code you were working on? A search for `mixin` in the PRs didn't find anything. Is it on your local fork?

**Comment by tabshaikh** [comment]
@jdlrobson Cant, we use autoprefix plugin to prefix the properties in Less v2 https://github.com/less/less-plugin-autoprefix

**Comment by jdlrobson** [comment]
Yes we can, but we should review the existing css rules we havea and get them using mixins as an intermediate step. code will look a little messy and confusing if we have vendor prefixes in source code too, right?

**Comment by cdrini** [comment]
Closing in favour of adding auto-prefixing to less, and then removing all prefixes -- like was done in #3738
