### ISSUE TITLE
Merged author redirects broken

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1998]
**Description**
> What problem are we solving? What does the experience look like today? What are the symptoms?
1. Redirects are still appearing in author search results. 
2. The redirect target's appearance is delayed.

**Evidence / Screenshot (if possible)**

**Relevant url?**
>`https://openlibrary.org/...`
https://openlibrary.org/search/authors?q=frances+milton+trollop&mode=everything

**Expectation**
> What should by happening? What will it look like / how will it behave?
After a merger, the redirected author pages should no longer appear in the author search results, nor in the author dropdown, but rather the merge target should.

**Details**
I merged the different author records for Frances Milton Trollope to OL7174882A, which had the most works. Afterwards, that OLID did not appear in the search results, but the others still did:
![missing author](https://user-images.githubusercontent.com/11435431/54837899-d9d98b00-4c9d-11e9-9df9-0e1f34c4a689.jpg)
Only after a wait (I estimate about 20 minutes, but I wasn't keeping track) did the correct target appear and the wrong ones start to vanish:
![found author](https://user-images.githubusercontent.com/11435431/54837997-0b525680-4c9e-11e9-89ea-4cfdece52986.jpg)
After more than an hour, there was still one redirect showing, OL7181226A
Perhaps this might help determine why it is still there: 
https://openlibrary.org/authors/OL7181226A.json
shows 
{"created": {"type": "/type/datetime", "value": "2014-07-24T09:16:11.384207"}, "last_modified": {"type": "/type/datetime", "value": "2017-03-31T08:54:01.585065"}, "latest_revision": 3, "location": "/authors/OL7174882A", "key": "/authors/OL7181226A", "remote_ids": {"viaf": "34551336", "wikidata": "Q271961"}, "type": {"key": "/type/redirect"}, "revision": 3}

> Logged in (Y/N)?
y, to production: c0e48d8 
> Browser type/version?
Chrome
> Operating system?
Win7 Pro
**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?
If possible, hasten the indexing of the corrected record, if not, then at the very least we should advise the user that there will be a significant delay, so they don't think they've done something wrong.

**Stakeholders**
> @ tag stakeholders of this bug

**Comment by hornc** [comment]
I added the extra author to a manual solr reindex, and it has been cleared up. I think this is another case of records dropping off the standard solr update process when there is a problem with an earlier item. Being addressed in current WIP Solr updates and switch over to a newer version.
