### ISSUE TITLE
catalog/onix/onix.py attempts to use a global variable in init(), but doesn't declare it global

### ISSUE THREAD

**Issue by bowlofeggs** [internetarchive/openlibrary#2]
onix_codelists and onix_shortnames are both initialized to None. Later in the module loading, init() gets called, which attempts to set them to useful dictionaries. Because they aren't declared global in init(), new variables are created within init() that exist only within the scope of that method. The fix is to add these lines to the top of init():

global onix_codelists
global onix_shortnames

I've forked the project and intend to make a push that will fix this issue soon. I'll post back here with the revision that you can pull to get the fix. Thanks!

**Comment by salman-bhai** [comment]
@mekarpeles I think we should close this!
