### ISSUE TITLE
Recommendation System

### ISSUE THREAD

**Issue by karankharecha** [internetarchive/openlibrary#2000]
### Proposal

The aim of recommendation system in idea number 3 (Building the World’s Open Library, Together) is about giving the most from library to users. Identification of user's behaviour and patterns can actually help us in providing suggestions to users. As there are plenty of books that are users are completely unaware of. On the basis of user's interest, recommendation system will recommend books to the users (just like online shopping website).

Apart from this idea, it would be great to increase interactivity between the users and our system. This can be done using a chatbot. Integrating chatbot with our system will actually help users in querying about books. Users can, instead of searching and going through the library, query the chatbot and get link to download / access / read / purchase (whatever we prefer to provide) in response. By doing so, users can get results more quickly,  in addition to this natural language processing could boost our recommendation system too.

**Comment by tfmorris** [comment]
This sounds very similar to #857

**Comment by mekarpeles** [comment]
@tfmorris is right, closing as duplicate; also no clear scope to this issue or implementation proposal.
