### ISSUE TITLE
Sorting should be possible on mobiles and tablets (not hidden)

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/openlibrary#2007]
**Is your feature request related to a problem? Please describe.**

Continuation of #1339. For screen widths <=789px the table header (which helps one sort by edition, availability, libraries and buying location) is hidden. 

**Describe the solution you'd like**

A dropdown can be added in replacement to allow users to sort editions.

_First discussed in_ [#1399(comment)](https://github.com/internetarchive/openlibrary/issues/1339#issuecomment-462036928)

**Comment by jdlrobson** [comment]
This task needs a bit more detail.
What URL are we talking about here and can we have a screenshot of the hidden element
(I can't remember the details of this discussion) :(

**Comment by koderjoker** [comment]
This issue was regarding the table header (that helps in sorting by edition, availability, location and buying) that gets hidden in edition tables below a certain width.
![Screen Shot 2019-08-01 at 9 18 27 PM](https://user-images.githubusercontent.com/30471843/62307843-f7b3c980-b4a1-11e9-84fb-f7dc1d21a898.png)
![Screen Shot 2019-08-01 at 9 18 40 PM](https://user-images.githubusercontent.com/30471843/62307847-f8e4f680-b4a1-11e9-8965-e306d6c85c1a.png)

Can be seen for screen widths <=789px over here
https://openlibrary.org/works/OL15203543W/Meistersinger_von_N%c3%bcrnberg

The discussion at that time was to add a dropdown to add back the sorting feature for screens of smaller widths.

**Comment by jdlrobson** [comment]
Ah got it! Thanks for the added context @koderjoker !

**Comment by jdlrobson** [comment]
I don't think there is an obvious solution for this. On Wikipedia we disable sorting complex tables 
on mobile so I propose we decline this issue.

We could later add a simplified sort by link when the code is in a better state but I would not want to add complexity to the product at this stage.
