### ISSUE TITLE
Deleting list from edition page also deletes button above

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2008]
**Description**
> What problem are we solving? What does the experience look like today? What are the symptoms?
New as of this morning. When one deletes a list from an edition page. The "Want to read" button also disappears. Can be fixed by refreshing the page.

**Evidence / Screenshot (if possible)**
![Fullscreen capture 3262019 92622 AM bmp](https://user-images.githubusercontent.com/17739465/54982025-13660b00-4faa-11e9-809f-7194c745e685.jpg)

**Relevant url?**
>`https://openlibrary.org/...`

**Expectation**
> What should by happening? What will it look like / how will it behave?
The list should disappear without affecting any other elements on the page.
**Details**

> Logged in (Y/N)?
Y
> Browser type/version?
Chrome Version 72.0.3626.121 (Official Build) (64-bit)
> Operating system?
Win 7 Pro
**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**
> @ tag stakeholders of this bug

**Comment by jdlrobson** [comment]
Hmm, I can't seem to replicate this locally, but can in production.. it's a bit of a mystery to ,me.
The problem is an inline style on the .dropit element but I can't see any code that's adding that:
```
visibility: visible;
```
The only reference to visibility is in openlibrary/plugins/openlibrary/js/lazy.js but that doesn't seem related so a bit stumped about this. What code commit is deployed? Maybe this can be replicated locally with that commit?

**Comment by mekarpeles** [comment]
It looks like by default the component has an inline style of `visibility: visible;` and then the `dropit` component is having its style cleared

In `openlibrary/plugins/openlibrary/js/ol.js`:
```
    // Show dropdown only when javascipt is enabled                                                                                                                                                                                 
    $('.dropit').css('visibility', 'visible');
```

**Comment by jdlrobson** [comment]
Ahh i guess i didn't pull from upstream 
😑🔨
