### ISSUE TITLE
This Work displays really weird due to invalid wikitext markup with unclosed code block

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2009]
**Relevant url?**
https://openlibrary.org/works/OL16427W/Poems

**Description**
I'm not sure why, but this specific work has a lot of random whitespace. I think it's because the description has an unclosed code block (the <code>``</code> if you view the description). This looks like it's causing the rest of the page to displayed with `whitespace: pre`.

**Evidence / Screenshot (if possible)**
![image](https://user-images.githubusercontent.com/6251786/55027158-fac21900-4fda-11e9-92f4-916bf57c4434.png)

**Details**
- Logged in (Y/N)? Y
- Browser type/version? Firefox 66.0.1 (64-bit)
- Operating system? Windows 10

**Stakeholders**
> @ tag stakeholders of this bug

**Comment by jdlrobson** [comment]
I fixed the problem with an edit, so it looks like a problem with the HTML produced by the wiki markup ``  syntax was not getting closed. Is this something we want editors to fix (I just did this now?) or protect against (can we protect against it?)

Since I've fixed it, here's the broken version:
https://openlibrary.org/works/OL16427W/Poems?v=18

**Comment by jdlrobson** [comment]
Looks like an issue in infogami to me - infogami/utils/markdown/markdown.py

**Comment by brad2014** [comment]
@jdlrobson I'm putting this on your plate for tracking, and you and @mekarpeles can decide if/when/who, or to backlog it.

**Comment by jdlrobson** [comment]
Garbage in garbage out is my current assessment.

**Comment by jdlrobson** [comment]
Please reopen if you don't agree with https://github.com/internetarchive/openlibrary/issues/2009#issuecomment-491487284
