### ISSUE TITLE
Re evaluating our search results page

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/openlibrary#2011]
Our users are facing the following issues with the search results page!
**Url:** https://openlibrary.org/search?q=hello&mode=ebooks&m=edit&m=edit&has_fulltext=true

- **Issue1:** In order to reach the search facet one must tab through all the search results on the page. This effects keyboard users/screen readers.
**Solution:** To place the search facet before search results in the DOM and give a user the option to "Skip to search results" OR Give a user the option to "Skip to filters". An implementation of a "Skip to ___" option can be seen at [archive.org](archive.org)

- **Issue2:** Even though visually the pagination is placed below the search results (screens >=960px), one can reach the page numbers only after tabbing through all the search results and search facet. This effects keyboard users/screen readers.
**Solution:** To bring pagination after search results in the tab order/DOM

- **Issue3:** Our mobile users expect an infinite scroll/page buttons to move on to the next page. However, users are unable to realise the existence of page buttons because the search facet appears after the search results, instead of pagination (< 960px). Also, the placement of the search facet after search results deprives users the option to choose filters at the start of the page (< 960px).
**Solution:** To move the pagination right below the search results visually and make the search facet a toggle option for screens <960px right above the search results.

**Additional suggestion:** Should we reduce the number of book results shown on a page to save loading and traversing so many books at once?

**Comment by mekarpeles** [comment]
Can someone from the community help @koderjoker turn these 3 sub-issues into their own issues (and link to this parent issue) so members of the community can start working on them? In its current form, this issue will be hard to close as we make incremental progress.

**Comment by mekarpeles** [comment]
This issue is supplanted by #2013, #2014, and #2015 -- thank you!
