### ISSUE TITLE
Unable to reach pagination numbers using the keyboard

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/openlibrary#2014]
Child issue of #2011
Sibling issues: #2013, #2015 

**Description**
Even though visually the pagination is placed below the search results (screens >=960px), one can reach the page numbers only after tabbing through all the search results and search facet. This effects keyboard users/screen readers.

**Relevant url?**
https://openlibrary.org/search?q=hello&mode=ebooks&m=edit&m=edit&has_fulltext=true

**Expectation**
The pagination button should be more accessible

**Proposed solution**
To bring pagination after search results in the tab order/DOM

**Additional suggestion** 
Should we reduce the number of book results shown on a page to save loading and traversing so many books at once?

**Stakeholders**
@mekarpeles @koderjoker 

Issue credit: @koderjoker

**Comment by guyjeangilles** [comment]
@shreyansh23 I don't think "pagination" is on the search results page anymore. Is this still relevant?

**Comment by cdrini** [comment]
@guyjeangilles This is the pagination:

![image](https://user-images.githubusercontent.com/6251786/69172469-db2cb300-0acb-11ea-9c45-f2fa47bc9b1e.png)

This was fixed by #2153 ; the pagination is now before the search facets in the html/tab order.
