### ISSUE TITLE
Pagination appears below facets on mobile device, not obvious multiple pages exist

### ISSUE THREAD

**Issue by shreyansh23** [internetarchive/openlibrary#2015]
Child issue of #2011
Sibling issues:  #2013, #2014

**Description**
Our mobile users expect an infinite scroll/page buttons to move on to the next page. However, users are unable to realise the existence of page buttons because the search facet appears after the search results, instead of pagination (< 960px). Also, the placement of the search facet after search results deprives users the option to choose filters at the start of the page (< 960px).

**Relevant url?**
https://openlibrary.org/search?q=hello&mode=ebooks&m=edit&m=edit&has_fulltext=true

**Expectation**
The mobile version of the search page result page should be more accessible

**Proposed solution**
To move the pagination right below the search results visually and make the search facet a toggle option for screens <960px right above the search results.

**Additional suggestion** 
Should we reduce the number of book results shown on a page to save loading and traversing so many books at once?

**Stakeholders**
@mekarpeles @koderjoker 

Issue credit: @koderjoker

**Comment by mekarpeles** [comment]
**Steps to reproduce:** 
1) search for a query with more than 100 results (e.g. moby dick: http://openlibrary.org/search?q=moby%20dick)
2) scroll past the first 100 results, you will see the facets (but no pagination)
3) scroll **past** the facets and you will finally see pagination

**Recommendation:**
On mobile, show pagination before facets with flex-order and a mediaquery

**Comment by jdlrobson** [comment]
I think long term, we really need some design input on how to handle facets on a mobile device.
Can you share any details on what users are complaining about?

My worry about putting the facets above the search results is that it will push down search results. If we were able to collapse them that might be a good compromise but I don't feel like the code is in a place where doing that is comfortable.

The most straight forward thing to do here, **might be to add a link above search results** saying "refine these results" which is an anchor link https://openlibrary.org/search?q=hello&mode=ebooks&m=edit&m=edit&has_fulltext=true#searchFacets o we think that would be a suitable interim solution?

**Comment by jdlrobson** [comment]
Given this is urgent, I'd appreciate some input on https://github.com/internetarchive/openlibrary/issues/2015#issuecomment-482788346 to help fix this. Would an anchor link suffice?

**Comment by cdrini** [comment]
For simplicity, I think the bare minimum solution to this should ensure the page numbers appear directly after the results list—that's the bug. So either a) just placing the page numbers above the facets and leaving the facets alone, or b) placing the facets at the top behind a toggle, fixes the bug. A link wouldn't fix the issue (unless (a) is also done).
