### ISSUE TITLE
Make ISBN visible on edition list

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2017]
**Is your feature request related to a problem? Please describe.**

The current search makes it difficult to locate a specific ISBN unless that ISBN belongs to a single record only. This is frequently not the case; either due to duplicates or ISBN re-use, but in the end this means one must click into each individual record when searching for a specific ISBN.

**Describe the solution you'd like**

Would it be possible to include the ISBN in the list view?

**Proposal & Constraints**

**Additional context**

Having the ISBN visible on the list could potentially prevent more duplicates from being added. (I'm guessing about this, but I could imagine someone having the impression that the edition does not exist if they are not already familiar with the limitations of the search functionality.)

**Comment by LeadSongDog** [comment]
@seabelis
To clarify, do you intend that it should be easy to _identify which_ editions on the work page returned for a query ISBN, or do you want to _see only_ those matching editions?

**Comment by seabelis** [comment]
@LeadSongDog, for identification.

**Comment by seabelis** [comment]
If the search results displayed all items with the ISBN exclusively, this would probably not be necessary.

**Comment by LeadSongDog** [comment]
@seabelis Ok, so then this is distinct from the new epic #2064.

**Comment by guyjeangilles** [comment]
@seabelis @LeadSongDog For ISBNs I've search, it usually takes me straight to an edition page. I.e: https://openlibrary.org/search?q=0743273567&mode=ebooks&m=edit&m=edit&has_fulltext=true

**Comment by seabelis** [comment]
Yes. An ISBN can exist on more than one edition. When searching by ISBN, the current behaviour is to land on **one** of the editions rather than see results for  **all** of the matching editions. If someone wants to locate the other(s) they must click into each edition record to see the ISBN.

**Comment by seabelis** [comment]
Find or filter within results would also suffice. The end goal is not visibility of the ISBN, but the ability to find all results with a given ISBN.

**Comment by SouthGoingZax** [comment]
@seabelis are you asking for something like this (just a rough prototype)?
![2017-prototype](https://user-images.githubusercontent.com/72705998/97794720-bb967980-1bba-11eb-9dba-37b5a00a0f3d.png)

**Comment by seabelis** [comment]
@SouthGoingZax Yes, exactly.

**Comment by mekarpeles** [comment]
I'm not opposed to there being a single value, isbn13. I know it's not perfect and there may be cases where there are multiple isbns...

**Comment by SouthGoingZax** [comment]
@seabelis are you okay with just displaying ISBN13 for each edition, or would you prefer to be able to use the edition filter to filter on both ISBN numbers (and possibly other information)?

**Comment by seabelis** [comment]
@mekarpeles Good point. 
@SouthGoingZax Yes, the edition filter would also suit the purpose. Thank you.

**Comment by SouthGoingZax** [comment]
@mekarpeles do you have pointers to how that filtering works and how to add hidden, searchable fields?
