### ISSUE TITLE
Edit page no longer displays with columns

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2019]
**Description**
Anything that used to show up in 'columns' now shows up un-columned. Possibly related to some of the recent mobile site improvements.

**Evidence / Screenshot (if possible)**
![image](https://user-images.githubusercontent.com/6251786/55239268-b1591000-520c-11e9-89e3-efb27a48474a.png)
![image](https://user-images.githubusercontent.com/6251786/55239278-bae27800-520c-11e9-8141-52418cb102a9.png)
![image](https://user-images.githubusercontent.com/6251786/55239296-c33ab300-520c-11e9-9a76-713c6adbc9b3.png)

**Relevant url?**
Every edit page, but for ex: https://openlibrary.org/books/OL3020703M/Alice's_adventures_in_Wonderland/edit

**Details**
- Logged in (Y/N)? Y
- Browser type/version? Firefox 66.0.1 (64-bit)
- Operating system? Windows 10

**Stakeholders**
@jdlrobson

**Comment by jdlrobson** [comment]
Could you explain what you mean by columned? An old screenshot perhaps? Also why were "columns" important? (Important to note as table based layouts - which columns hint might be at play here - will not work on mobile)

Just to check - this is the case on all resolutions? Is the form usable on mobile?

**Comment by cdrini** [comment]
I can't seem to find an old screenshot of an edit page; here are some I concocted:

![image](https://user-images.githubusercontent.com/6251786/55248472-3f8ac180-5220-11e9-8c5d-0e02f324b7bc.png)

Basically anywhere you see the right half of the screen entirely empty, the content used to flow through 2 columns (ex: the book weight/dimensions fields should appear in the right half of the screen).

This a desktop issue; there shouldn't be columns on mobile because there isn't enough screen real-estate. This is why I think it's related to the mobile changes.

**Comment by cdrini** [comment]
(Renamed; broken is too ambiguous a word)

**Comment by cdrini** [comment]
Oh, forgot to address your question. This is important mainly because this is a regression; the UI is clearly meant to have columns. The input fields' widths are such that they leave enough room for the second column (ex: the book cover should be to the right of the stunted "title" input). There's still clearly CSS for columns left in here; it looks like they were removed unintentionally. The CSS is probably entirely still there, it's just a class changed or something probably made them break. If you're asking whether or not we should have columns at all, I trust that whoever added them in the first place did that research. Let's not remove them unintentionally. It's less work to fix the regression than it is to redesign/discuss whether or not we should have columns.
