### ISSUE TITLE
Missing captcha causes Edit changes to not save!

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2021]
Whenever patron tries to edit, website complains about captcha (which doesn't seem to exist)

**Comment by bitnapper** [comment]
Hi, I‘ve experienced the same problem but it seems to be limited to Firefox and Firefox Mobile. I could not reproduce the Problem in Safari.

It seem the captcha is blocked by the activity tracking blocker which is not very surprising. After turning it off completely the captcha will appear. But that does not solve the problem. One can check the box and press the save button but it still reports „Recaptcha solution was incorrect“. The changes wont be saved.

When the captcha is not blocked and the blocker turned off it still kind of reports an error. The changes wont be saved an in the top of the page it shows a warning symbol but nothing more.

https://twitter.com/Bitnapper/status/1112430470971707393/photo/1

**Comment by mekarpeles** [comment]
Wondering if there are any similarities between #613, related to #1886 #1891

**Comment by bitnapper** [comment]
The second bug does also occur on Safari on IOS and MacOS and Chrome on MacOS.

**Comment by jdlrobson** [comment]
I think first thing we need here is replication steps to understand what is going wrong!

**Comment by nimbus98** [comment]
I agree with @jdlrobson , I'm not able to reproduce this issue as of now.

**Comment by mekarpeles** [comment]
@bitnapper can you please help provide instructions on how we can reproduce? I think @nimbus98 is blocked on working on this until we have more specific feedback on reproducing.

**Comment by bitnapper** [comment]
I’m sorry, I can’t. I don’t know whats more. I have this problem whenever I want to edit a book.

**Comment by jdlrobson** [comment]
![Screenshot_20190413-074054_Firefox](https://user-images.githubusercontent.com/148752/56071221-94e9d580-5dbf-11e9-9ea3-896ab3f250ce.jpg)
![Screenshot_20190413-074037_Firefox](https://user-images.githubusercontent.com/148752/56071224-974c2f80-5dbf-11e9-8425-5948c3d5cc40.jpg)

My guess is that the captcha is not loading. @bitnapper are you seeing a big gap like in the screenshot where the captcha should be?

If it's not loading I can take a look at reasons it may fail to load and provide some beta fallbscks.

**Comment by bitnapper** [comment]
No, when I deactivate the activity tracker in firefox, the captcha link is there. But still I get an error: https://twitter.com/Bitnapper/status/1112430470971707393/photo/1

**Comment by brad2014** [comment]
I'll note (as a firefox user) that recent firefox has several settings related to blocking trackers, 3rd party items, and per-user and per-site blocking of cookies.  Any or all of these might affect either presentation or verification of captcha.  If we are unable to reproduce it, I'd guess it is likely to be related to customized anti-tracking settings or plugins.

**Comment by tfmorris** [comment]
The div with the icon of a red triangle with the exclamation point (!) in the tweet is supposed to contain an error message. The fact that it doesn't indicates a separate bug which will make debugging this one difficult.

**Comment by guyjeangilles** [comment]
@nimbus98 Are you still working on this issue? It seems rather complex. I've labeled it as backlogged for the time being. Considering it's a high priority issue we should devise a plan to move foreward.

@mekarpeles @tfmorris @jdlrobson @bitnapper @brad2014 Do you have anything to add?

**Comment by mekarpeles** [comment]
@bitnapper are you able to reproduce this still? Going to close until we have more reliable repro case.

**Comment by StoppingBuck** [comment]
Hi @mekarpeles , I think I am experiencing this. I am trying to edit a book, but unable to save because "Recaptcha solution was incorrect". However, as you can see from the attached, I get no recaptcha where others seem to do so:
![image](https://user-images.githubusercontent.com/8426548/113477619-7afd9d80-9483-11eb-8d1d-bb7e0345ed26.png)

I have tried in Mozilla Firefox, Chrome and even Microsoft Edge (without any extensions at all) and the problem persists in all three so the problem seems to be on your end...

**Comment by RayBB** [comment]
I am not experience this in production. But when developing locally instance I am experiencing this on FF/Chrome/Brave regardless of what extensions I turn on or off.
