### ISSUE TITLE
Edit button on works with single edition opens edit page for edition

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2033]
**Description**

When clicking the edit button from a work page with one edition the edit form for the edition opens instead of the edit form for the work.

**Expectation**

When clicking the edit button from the work page, it should always open the work details form regardless of edition count.

**Details**

Logged in: Y
Browser: Chrome Version 73.0.3683.86 (Official Build) (64-bit)
Operating system:  Win 7 Pro

**Comment by mekarpeles** [comment]
May be residual related to edge case special "show edition as work" page when work only has 1 edition.

One work page, EDIT should always edit work (url)

**Comment by mekarpeles** [comment]
It is as @cdrini and @seabelis expected -- in `openlibrary/macros/databarView.html` there is a block of code that (legacy) checks whether we're on a work with only 1 edition, and makes the EDIT button use the edition's edit url (in this case) instead of the work. Removing the following line(s) should resolve the issue:

```
$if page.type.key == '/type/work' and page.edition_count == 1:
    $ edit_url = page.get_one_edition().get_url(suffix="/edit") or page.url(suffix="/edit")
```

**Comment by mekarpeles** [comment]
Here's the solution if anyone wants to open a PR (my development branch is a bit of a mess at the moment):
```
index 79cf8b1..e3aaf1e 100644
--- a/openlibrary/macros/databarView.html
+++ b/openlibrary/macros/databarView.html
@@ -1,8 +1,6 @@
 $def with (page)

-$if page.type.key == '/type/work' and page.edition_count == 1:
-    $ edit_url = page.get_one_edition().get_url(suffix="/edit") or page.url(suffix="/edit")
-$elif page.type.key in ["/type/work", "/type/edition", "/type/author"]:
+$if page.type.key in ["/type/work", "/type/edition", "/type/author"]:
     $ edit_url = page.url(suffix="/edit")
 $else:
     $ edit_url = page.key + "?m=edit"
```
