### ISSUE TITLE
Extend isbn lookup to work with ASIN

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2037]
### Is your feature request related to a problem? Please describe.
Pre-isbn books should be importable by asin.

**Comment by hornc** [comment]
Amazon API library being used: https://github.com/yoavaviram/python-amazon-simple-product-api

**Comment by seabelis** [comment]
Does this have the potential to cause duplication? Third party sellers use ASINs for non-ISBN books and ISBN books that vary from amazon's catalog. Digital items use only ASINs; will the import identify the corresponding e and audiobook records if they exist?

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/blob/781791fe16096857b52ea757a38c205b1019483c/openlibrary/plugins/upstream/code.py#L86

The code used to be `product = amazon_api.lookup(ItemId=isbn)` which accepted `asin` v. now where the code is specific to `isbn`: `product = lending.amazon_api.lookup(ItemId=isbn, IdType="ISBN", SearchIndex="Books")`
