### ISSUE TITLE
Updating "Testing Procedures" Wiki Documentation

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2041]
@tfmorris reports that the [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing) page seems pretty out of date with our current setup (and assumes things like access to private OL machines)

_Originally posted by @tfmorris in https://github.com/internetarchive/openlibrary/issues/1134#issuecomment-482142442_

**Comment by hornc** [comment]
wiki page refers to docker now, latest docker instructions are at https://github.com/internetarchive/openlibrary/tree/master/docker  repo testing instructions are in the main readme https://github.com/internetarchive/openlibrary/blob/master/Readme.md#running-tests
