### ISSUE TITLE
Make postgres quieter during docker build

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2046]
Some of the postgres commands in [/docker/Dockerfile.oldev](https://github.com/internetarchive/openlibrary/blob/master/docker/Dockerfile.oldev) are outputting a lot of noise during docker builds. We should find a way to make it only show errors.

```
RUN /etc/init.d/postgresql start   && createuser -s openlibrary   && createdb openlibrary   && psql openlibrary < openlibrary/core/schema.sql   && createdb coverstore   && psql coverstore < openlibrary/coverstore/schema.sql   && psql openlibrary < scripts/dev-instance/dev_db.pg_dump   && pg_ctlcluster 9.5 main stop
 ---> Running in be56a97153ed
 * Starting PostgreSQL 9.5 database server
   ...done.
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
CREATE TABLE
CREATE TABLE
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE TABLE
CREATE INDEX
SET
SET
SET
SET
SET
SET
CREATE EXTENSION
COMMENT
SET
CREATE FUNCTION
ALTER FUNCTION
CREATE FUNCTION
ALTER FUNCTION
SET
SET
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
... 200 more lines of garbage
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
ALTER TABLE 
REVOKE      
REVOKE      
GRANT       
GRANT       
```

**Comment by cdrini** [comment]
@rohitjain00 from slack:
> Adding "-q" or "--quiet" after the psql command in the oldevDocker file must quite the postgres, but I am not sure about the errors being quite. https://www.postgresql.org/docs/9.2/app-psql.htm (quite feature is same for all versions of psql)

**Comment by cdrini** [comment]
That sounds good! Do you have the time to try it? This seems like it has some info as well: https://stackoverflow.com/questions/3530767/disable-notices-in-psql-output

**Comment by mekarpeles** [comment]
@rohitjain00 did you have a chance to try this out? Could we assign this one to you? :)

**Comment by mekarpeles** [comment]
@rohitjain00, one more bump just in case you happened to test this, it would be great to be able to resolve if you're close :)

**Comment by metabr** [comment]
Created pull request incorporating proposed change with using `--quiet` option. While output includes still something except for errors, it is much cleaner. See #3276 for details.
