### ISSUE TITLE
Fix dev instance login to fail if incorrect admin credentials

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2050]
If user on dev enters wrong admin email + password and spoofs login, unable to login as admin. The flow should be fixed

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/1197#issuecomment-483417983_

= Notes from @jdlrobson
A workaround exists while this problem remains in https://github.com/internetarchive/openlibrary/issues/1197#issuecomment-479752932

**Comment by jdlrobson** [comment]
Where is the workaround for users that have accidentally entered wrong email? I can't find the link an y more :(

**Comment by cdrini** [comment]
https://github.com/internetarchive/openlibrary/issues/1197#issuecomment-479752932

**Comment by Yashs911** [comment]
@mekarpeles any update on this cause I am unable to login as admin even after clearing my cookies

**Comment by RayBB** [comment]
For anyone who didn't have luck clearing the cookies and restarting the service as mentioned in the workaround. Resetting the database fixed the issue for me. You can find the command here https://github.com/internetarchive/openlibrary/blob/master/docker/README.md

```
# remove all volumes (i.e. reset all databases); perform WHILE RUNNING
docker-compose stop
docker-compose rm -v
```

**Comment by mekarpeles** [comment]
This should no longer be an issue
