### ISSUE TITLE
Typo in error messages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2054]
Typo of `atleast` => `at least` in https://github.com/internetarchive/openlibrary/blob/c0b92e60050abe84574ae73c03086b4e66ebf514/openlibrary/plugins/openlibrary/i18n/account/register/strings.en#L5

**Comment by jeyadosstimothy** [comment]
Hi, can I work on this issue?

**Comment by hornc** [comment]
sure @jeyadosstimothy please do!
