### ISSUE TITLE
Audit/Inventory Bad Edits Caused by Cache Issues (Followup to #2040)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2057]
@hornc believes this issue has been resolved by reverting openlibrary.yml and infobase.yml on production to a state before ol-mem4 was added.

It's hypothesized perhaps `infobase` needed to be restarted on `ol-home` via `supervisorctl` after deploy (prior to restarting `ol-web3` and `ol-web4`) in addition to restarting `ol-mem*`.

I'm very tentatively marking this as resolved and hoping doing so will cause others who are still noticing a problem to speak up here.

I'm opening a new issue for us to evaluate how many records / edits were affected during this time period (and what strategy we should take, e.g. potentially reverting edits during this time?

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/2040#issuecomment-483821029_

**Comment by hornc** [comment]
(Discussed in a group on community call 2019-05-14) -- no one has noticed any data problems from when we had memcache issues in production. There is not a reliable way to detect data corruption from this specific period. It was agreed on the call to close this issue. The problems seemed to be restricted a specific short period, and we noticed bad examples as they occurred. Agreement was to close this issue and accept that if anything slipped through, it can be fixed organically like any other data improvement edit on OL.
