### ISSUE TITLE
Allow Patrons to Enable "Public" Reading Log at Account Creation

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2058]
Followup on #740 and #826 

### Is your feature request related to a problem? Please describe.

Right now, most users don't know that they can make their reading log public. In general, other than borrow history, nearly everything on Open Library (e.g. existing Lists) is public. We'd like to give users the opportunity to make their `reading log` lists public to support the ability to follow patrons with similar interests #1966.

There's already a backend setting for making one's reading log public via #740. This task entails modifying the user registration page (front-end) + https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L203 (back-end) to support enabling this setting from the account creation form.

Perhaps copy like:
[x] I want to share my Reading Log book recommendations with other book lovers

**Comment by tabshaikh** [comment]
We are moving forward in making the reading log public by default when creating a new account as Google Books and Goodreads by default makes the reading log of users public at the time of account creation and going public by default and giving the ability to go private is a responsible approach forward.
https://books.google.ca/books?uid=117464657237458903377
![Screenshot from 2020-05-13 23-50-06](https://user-images.githubusercontent.com/31198893/81912042-aec1a180-95eb-11ea-927d-a201ad82bb33.png)

**Comment by tfmorris** [comment]
> Perhaps copy like:
> [x] I want to share my Reading Log book recommendations with other book lovers

Except that they're not "recommendations," but rather a personal list of things I've read or want to read, for whatever reason. Perhaps more accurate copy would be something like "Make public everything I'm reading, have read, or want to read."

> going public by default and giving the ability to go private is a responsible approach forward.

That's just an opinion, even though it's stated like it's a fact.

It's kind of like Goodreads saying "This access is granted in the spirit of openness with the goal of spreading the love of reading" when it's actual purpose is to increase Amazon's marketing reach and drive more traffic to their e-commerce site. The goal here is to improve Internet Archive's monetization of the Open Library users.

**Comment by tabshaikh** [comment]
@tfmorris Both the approaches were proposed as you stated and looking at a variety of sites it was agreed unanimously that we think moving in this direction would open us for more possibilities :) Screenshot below of the design 
![Screenshot from 2020-05-13 23-06-28](https://user-images.githubusercontent.com/31198893/81959928-d6d1f480-962d-11ea-986c-99a20b4e19c7.png)
