### ISSUE TITLE
Load and link SFPL MARC data into Open Library

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2061]
Source data: https://archive.org/details/marc_openlibraries_sanfranciscopubliclibrary

- [x] confirm the above item has the latest suitable data for import
- [x] create SFPL /type/local_id https://openlibrary.org/local_ids
- [x] confirm local ids can be extracted from MARC
  - barcodes for SFPL are in 945$i
- [x] import / link up data, initial pass
- [x] Investigate failed imports (= issues with redirected existing records), resolve and reimport

**Comment by hornc** [comment]
make sure documentation is up-to-date  see, https://github.com/internetarchive/openlibrary/wiki/Data-Importing#Bulk-MARC-Import and https://github.com/internetarchive/openlibrary/issues/788

**Comment by LeadSongDog** [comment]
Please, Please, Please, do not open these floodgates without first ensuring that there is correct (or at least tolerably incorrect) handling of ambiguous author strings in the imported records. A search for author John Smith (https://openlibrary.org/search/authors?q=john+smith&mode=everything) finds 625 author records as of today. Consider the impact of dumping works upon the wrong author record.

**Comment by mekarpeles** [comment]
@LeadSongDog point well taken, even though there are actually more like ~100 (not 625) https://openlibrary.org/search/authors?q=name%3A%22John+Smith%22. We'll make sure authors are handled sanely.

As background reference, this issue blocks Internet Archive from digitizing SFPL's books and so from that perspective, we need to move as quickly as our scanning center needs to. Just fyi

**Comment by LeadSongDog** [comment]
@mekarpeles  Ok, so incorrect reporting of the search totals is a known issue #628, but the point stands.  We don't seem to be getting anywhere much on #352 #357 #512 #756 #977 #1571 despite what seems to be broad agreement that it needs doing. 

I also think your #513 was closed prematurely: the add-a-book work-edit, and edition-edit pages' author dropdown certainly only offers up ten "John Smith" matches of the ~100: those with the highest book counts. See https://openlibrary.org/books/OL18996126M/England's_improvement_reviv'd/edit for example.

**Comment by hornc** [comment]
example first MARC record (as yet un-imported): https://openlibrary.org/show-records/marc_openlibraries_sanfranciscopubliclibrary/sfpl_chq_2018_12_24_run01.mrc:0:1983

**Comment by hornc** [comment]
copydocs.py Commands to test SFPL `local_id` locally:

```
docker-compose exec web scripts/copydocs.py /type/local_id
docker-compose exec web scripts/copydocs.py /local_ids/sfpl
```

**Comment by guyjeangilles** [comment]
@hornc I changed the state of this issue from Work In Progress since that's the category it's in in the Continuous Import Pipeline project.  I also changed the priority since a backlogged, high priority issue seems counter intuitive. 

Let me know if you agree or disagree

**Comment by hornc** [comment]
The bulk of this issue has been done, but the final part is blocked by redirects preventing the imports.  Completing #2553 will unblock this and allow the failed items to be imported successfully.

**Comment by hornc** [comment]
**Remaining ERRORS in logs to reimport:**

- [ ] sfpl001.log
- [ ] sfpl002.log
- [ ] sfpl003.log
- [ ] sfpl004.log
- [ ] sfpl005.log
- [ ] sfpl006.log
- [ ] sfpl007.log
- [ ] sfpl008.log
- [ ] sfpl009.log
- [ ] sfpl010.log
- [ ] sfpl011.log
- [ ] sfpl012.log
- [ ] sfpl013-01redo.log
- [ ] sfpl014-02redo.log
- [ ] sfpl015-03redo.log
- [ ] sfpl016-03redo.log
- [ ] sfpl017-03redo.log
- [ ] sfpl018-04redo.log
- [ ] sfpl019-04redo.log
- [ ] sfpl020-04redo.log
- [ ] sfpl021-04redo.log
- [ ] sfpl022-05redo.log
- [ ] sfpl023-05redo.log

**Comment by hornc** [comment]
Failed imports have been re-run, and the bulk have succeeded as a result of a targeted approach to #2553 
There are a relatively small number of imports that failed that fall into the #2621 category. That can be followed up with that issue. The SFPL collection data has been imported in preperation for book scanning.
