### ISSUE TITLE
Synchronize prod's edition.json with repo's config_edition.page

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2062]
Follows up from #881

The production edition.json config at https://openlibrary.org/config/edition.json is behind what's committed on master:
https://raw.githubusercontent.com/internetarchive/openlibrary/master/openlibrary/plugins/openlibrary/pages/config_edition.page

The live config_edition.page likely needs to be edited wiki-style (as admin) to ensure it is not behind what's committed.

## Challenges
Note: the changes are committed in json format but the wiki only seems to support this page being edited as yml by an admin. :confounded: 

## Followup Task
- How do we automate this to prevent the live infogami config from falling out of sync with what's been committed?

**Comment by mekarpeles** [comment]
@hornc can we POST to `https://openlibrary.org/config/edition.json`? Why can't we remove the `json` suffix and edit the https://openlibrary.org/config/edition page?

**Comment by cdrini** [comment]
Yaml is a superset of Json, so you should be able to paste it in.

**Comment by hornc** [comment]
@mekarpeles the Edit button looks like it is meant to do something sensible, but I don't see any values I can work with when I click on it, it just prompts for an edit summary. The YAML editor looks like the familiar admin only editor I sometimes use for editing books. 

POSTing to the json might work -- will need to test locally first to avoid breaking things, but that would be a nice simple way of doing this. Now that I think about it, this should just work, as it parallels what happens with API book edits -- we could use the ol-client for this sort of update in future. :+1:

@cdrini I haven't tried pasting json in the yaml field. I could try that locally and see what happens.

**Comment by brad2014** [comment]
@hornc To close this, there needs to be a script and a cron job deployed, right?

**Comment by hornc** [comment]
From looking into what needs to be done for this issue, it looks like sane way to proceed is for the production config to take precedence over what is committed here. 

The only purpose for this committed file would be to seed a new instance of Open Library, so it should be updated from production when deemed appropriate.

The production version of this file has diverged, but does seem to be missing some of the edits here.
I have made sure the recent change to resolve #2735 has been made in production. 

There was some confusion about the effects of modifying this committed file, but it is clear that changing this config does not alter production, and there is no deployment mechanism to do so. This is example config at best.

**Comment by hornc** [comment]
Commands to regenerate this file:
```
wget https://openlibrary.org/config/edition.json
jq --indent 4 . edition.json > config_edition.page
```

(the default of 2 spaces would be better, but messes up the diff on this test PR: #2967

**Comment by hornc** [comment]
To sync the committed file to production:
```
from olclient.openlibrary import OpenLibrary
import json
ol = OpenLibrary()

with open('config_edition.page', 'r') as f:
    page = json.load(f)
    r = ol.session.put(ol.base_url + '/config/edition.json?debug=true', data=json.dumps(page))
    print(r)
```

I'm not sure this is the best way to proceed, it is easier and makes more sense to edit the configuration in production, as designed. If needed, the raw json can be copied back to the repo, but I'm not sure where and how this `config_edition.page` is used by the code.

Also, the history diff for the page seems broken; it's not showing a sensible diff and seems to be getting stuck on list item 0?  https://openlibrary.org/config/edition?_compare=Compare&b=571&a=570&m=diff

**Comment by hornc** [comment]
Closing as DONE, see https://openlibrary.org/config/edition.json?v=571
