### ISSUE TITLE
Should be able to search at the edition level

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2064]
i.e. don't just show a matching work, show the edition which caused the work to be a match.
e.g. goodreads and google books

## Stakeholders
cc: @seabelis, @leadsongdog, @tfmorris, @cdrini, @hornc 

## Related
#448, #643, and was also discussed in #684
_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/342#issuecomment-484179607_

**Comment by tfmorris** [comment]
This is closely related to #448, #643, and was also discussed in #684.

**Comment by seabelis** [comment]
Something has changed, but not for the better. Now when searching by ISBN, the result is an edition page in cases where there should be more than one match, A list of editions should be produced if there are multiple matches. For example, ISBN 0307302016 is associated with three editions that I am aware of, but only one can be found with an ISBN search.

**Comment by seabelis** [comment]
Is this a duplicate of #889 ?

**Comment by LeadSongDog** [comment]
> Is this a duplicate of #889 ?
Certainly related. Per @tfmorris 27 Nov 2019, fixing this should also fix that.

**Comment by mekarpeles** [comment]
Duplicate of #6377
