### ISSUE TITLE
Search API - How to Determine Which Books are Unrestricted?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2065]
@waldenn asks:

> Can someone comment on why the Search API returns books with "has_fulltext: true" but which are not readable online? The "ebook_count_i" value also does not indicate read access.

> How can the user of the search API make sure a book is directly readable? Thanks!

_Originally posted by @waldenn in https://github.com/internetarchive/openlibrary/issues/1754#issuecomment-484301534_

**Comment by waldenn** [comment]
I now see there is another API endpoint ["Books"](https://openlibrary.org/dev/docs/api/read) which gives more book info and a field of "preview" and "preview_url". This solves the issue. I see you can call the API with multiple IDs. Thanks!

**Comment by mekarpeles** [comment]
Sounds like you found a work-around. Also, you may be able to specify `&jscmd=data` on the endpoint and get the additional info you need.

IN http://openlibrary.org/search.json?q=lord%20of%20the%20rings&jdcmd=data the `public_scan_b` field tells you that the work has a public / unrestricted edition.

Note that search results return a **work** and not an edition, so this `public_scan_b` will only tell you one of the work's editions is public.

In the near future we'll be adding `availability` to the search.json endpoint which should tell you which edition is public.

**Comment by waldenn** [comment]
Thats great, thanks for the help.
