### ISSUE TITLE
Add "Listen 🎧" Call-to-Action Button which launches BookReader in Text-To-Speech Mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2068]
## Is your feature request related to a problem? Please describe.

Most readers don't know all of our readable/borrowable books are available in audio/text-to-speech format through our BookReader. This issue proposes a `[Listen 🎧]` button which allows users to jump directly from Open Library into a text-to-speech audiobook experience.

## Sub-Tasks
- [ ] Create a `Audiobook` user-group for a pilot
- [ ] Propose a design for the [call-to-action Read Panel](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#read-panel) on the books (editions) page for a `[Listen 🎧]` or `[Read Aloud 🎧]` button.

## Describe the solution you'd like

According to one of our Directors who used to work with Amazon, their text-to-speech was very successful.

## Proposal & Constraints

The text-to-speech of our current bookreader is very unideal.
1. The voice quality is not great
2. There is no pause/restart
3. No ability to change voice languages
4. No ability to chance speed of voice

We have a prototype (https://archive.org/~mek/audioreader/index.html?ocaid=adventuresofbobw00burg&page=85) for a better text-to-speech audio-reading experience (which we hope will be integrated into BookReader: https://github.com/internetarchive/bookreader/issues/94 -- This is a pre-requisite to this issue)

For policy reasons, it may make sense to first release this feature for unrestricted and public domain content only.

**Comment by brad2014** [comment]
I'm not sure if @mekarpeles should own this (because we need to decide how to schedule it) or @jdlrobson (because it affects the UI).  Either of you want to opine on its priority?

**Comment by mekarpeles** [comment]
@brad2014 I'm actually going to assign this one to @bfalling (Brenton on Archive.org) as he will likely set priority on the Archive.org Book Reader changes which enable this. That way he can keep us updated as there are developments.

Unless someone wants to propose designs here (happy to assign others)
