### ISSUE TITLE
"More" in search facets not working

### ISSUE THREAD

**Issue by JeffKaplan** [internetarchive/openlibrary#2074]
## Description
After searching, click "more" under, say, authors. Just adds a bullet after the word "more" and does not expand list.

## Evidence / Screenshot (if possible)
![tmp](https://user-images.githubusercontent.com/6251786/56463876-171f5e80-63ab-11e9-975b-0f5d5172e9ac.gif)

## Relevant url?
https://openlibrary.org/search?q=title%3A+%22the+art+of+war%22&mode=everything

## Expectation
Should show more items

## Details
- Logged in (Y/N)? N
- Browser type/version? Firefox
- Operating system? Windows 10

## Stakeholders
@jdlrobson (deputy of frontend).

**Comment by cdrini** [comment]
Can reproduce; expanded issue

**Comment by cdrini** [comment]
No errors are logged to the JS console on click.

**Comment by jdlrobson** [comment]
Likely another jquery live migration problem based on symptoms :(

**Comment by jdlrobson** [comment]
The more function is defined in openlibrary/templates/work_search.html and uses slideDown on an element that has the class .hidden however .hidden uses !important and means always hide this thing.

Two ways to solve this and changes in 2 files necessary: openlibrary/templates/work_search.html
openlibrary/plugins/search/templates/advanced_search.html


1) Replace the class hidden with style="display:none"
Replace
```
<div class="facetEntry hidden">
```
with
```
<div class="facetEntry" style="display:none;">
```

2) In the JS make sure you remove the `hidden` class before doing slideDown. If you do this, tests are necessary.

I'm traveling so cannot submit a fix myself right now but that should be all the information anyone needs to fix and review this....

**Comment by brad2014** [comment]
What remaining review does this need?  @jdlrobson, if no further review is needed, can you remove the label?

**Comment by jdlrobson** [comment]
This is merged now and resolved. The awaiting review tag can safely be ignored on any closed issues (is there an automated way we could do that?)
