### ISSUE TITLE
Add book titles to carousels

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2084]
## Is your feature request related to a problem? Please describe.

Should we add titles beneath our carousels? Especially when a book has a non-descript bookcover, it's difficult to tell what the book is.

UPDATE:
The results of the vote suggest adding titles may be a worth-while change (especially for books in carousels without covers)

## Examples
![overdrive-carousel-titles](https://user-images.githubusercontent.com/978325/56547467-6c39ac80-6532-11e9-8bff-07f5037dd1d5.png)

Ideally, the carousels would provide additional information + interactive/clickable elements (e.g. Amazon includes title, author, etc).
![www amazon com_s_bbn=1000 rh=n%3A283155%2Cn%3A5267710011 dc qid=1613118991 rnid=1000 ref=lp_1000_nr_n_30](https://user-images.githubusercontent.com/978325/107746298-7231ec00-6cca-11eb-9e46-90a3649fb57f.png).

## Stakeholders
Stakeholders: @jdlrobson, @koderjoker, @hornc, @charstarstars, @seabelis

**Comment by jdlrobson** [comment]
How will we deal with long titles/authors? I expect this will need some kind of fixed height to work. e.g. `...`

**Comment by LeadSongDog** [comment]
@jdlrobson Can't the alt text be set to the full title and author, and then rendered by a browser as hovertext or read aloud?

**Comment by mekarpeles** [comment]
@LeadSongDog I don't think this is a viable option for mobile users.

@jdlrobson not sure yet, one proposal was removing the read buttons to make room for title / author.

**Comment by jdlrobson** [comment]
The read buttons are a little repetitive. This would reduce visual clutter
but we'd still need to truncate or shrink longer titles to retain the fixed
card format.

**Comment by LeadSongDog** [comment]
@mekarpeles Agree it only helps accessibility on desktops and screenreaders, but it does not degrade the mobile rendering either.

**Comment by seabelis** [comment]
I'd try to keep titles to one line; maybe have a character count limit followed by ... when exceeded? Perhaps the year is not necessary.

**Comment by LeadSongDog** [comment]
Related: #496 #837 #841 #1005 #2368  
Discussions on these issues identified several problems ancillary to their main thrust that never got their own issues.
@mekarpeles  I like your idea of showing a title below the cover. It is a useful way to make alt-text more normalized, not requiring a hover action to display it.  It is also good for low-bandwidth usage where images are expensive or blocked. For mobile usage, perhaps the alt-text could crawl through a one-line window below a (static) cover image, as on cable news?

**Comment by seabelis** [comment]
Would it be possible to do something like this, not auto-scrolling (and not circles), but displaying a central image with details and borrow link? We shouldn't rely on covers to provide the title as plenty of legit covers don't have one, but I think it may look cluttered to show so much information all at once. http://demo7.dnngo.net/20047/en-us/sliders/contentslider.aspx
Or maybe some kind of mouseover action: http://demo7.dnngo.net/20047/en-us/sliders/carousel.aspx

**Comment by jdlrobson** [comment]
Is there a decision here? #2368 has been reopened, but if we want to add titles per this task it doesn't make sense to invest time in that ticket.

**Comment by BrittanyBunk** [comment]
Here's my thought: 
- Main site: the selection for book covers should have the title and author clearly visible, preferably with a picture that visually describes what the book's about and differentiates it from other editions
- Mobile: have the cover image and when a person taps it, it'd display (as an overlay over the cover, making the cover go opaque in the back behind): the 1) title, 2) read/borrow button, 3) details button.
 
Vision:
![image](https://user-images.githubusercontent.com/55302685/71505497-3ae84d80-2832-11ea-8143-ac7957c981b8.png)
It's clear to see that the first cover shows exactly what's going on with the title, imaging, and even the author (although that's smaller), the 2nd cover is what I'd imagine for mobile (it would be more centered than what's shown here, but I'm too lazy to redo it - just pretend for now :)).

**Comment by seabelis** [comment]
Overdrive's approach omits subtitles and if the title is longer than one line, uses ... .
<img width="818" alt="Screenshot 2020-02-04 at 10 08 50" src="https://user-images.githubusercontent.com/17739465/73730349-ea201a80-4736-11ea-8186-0145860673a3.png">
No significant difference on mobile; just fewer items displayed on carousel.

**Comment by BrittanyBunk** [comment]
Although to me, there's too much added with Overdrive (which is why I tend not to use it much), they do use titles, which I do think is important. Plus, it has the 'borrow' button. One thing that is interesting and not really noticeable, but important in the picture is the bookmark icon. I think that's kind of cool.

**Comment by Yashs911** [comment]
@mekarpeles I would like to work on this issue.
![image](https://user-images.githubusercontent.com/64412143/106092472-5ec44400-6154-11eb-916a-035a4660f95a.png)

**Comment by BrittanyBunk** [comment]
@Yashs911 I don't get the picture if you don't mind helping me out here. Is this your vision?

@mekarpeles I do not like this idea. My idea of putting the titles in the empty boxes really was great enough - I'm 100% super happy that that was made possible. For me, I only look at the cover - the title would mislead me and I'll get lost. It's too much clutter and could make it harder to load. The real issue isn't the name of the books there - but having a book cover that is explanatory - one with a title and author already in there. I just see all these ones that are just an image of a book cover without its sleeve - those need an inner cover. So if every cover was ideal, we wouldn't need this.

I'm thinking, if you really want it, what if the title appears when hovering over the book cover, rather than on the bottom?

**Comment by Yashs911** [comment]
@BrittanyBunk, by default, the title appears when we hover over the book cover due to the title attribute added to the image.
![image](https://user-images.githubusercontent.com/64412143/106093729-d2675080-6156-11eb-95da-0e71faac801c.png)

**Comment by Yashs911** [comment]
@mekarpeles @BrittanyBunk Will this work? Ignore the color scheme :)


https://user-images.githubusercontent.com/64412143/106097561-853aad00-615d-11eb-8e8e-197546397df1.mp4

**Comment by BrittanyBunk** [comment]
@Yashs911 yesssssss! I like the first - as it matches the color scheme better (imo).

**Comment by BrittanyBunk** [comment]
I really do like this idea. It's much better to have the actual cover - so people are matching what they know to what they see, than me manually attaching the name to the cover that doesn't have it in reality. Much nicer looking and a lot less work on my (and likely others') parts :). I mean, some covers, no matter what I do - it won't be possible to read a title on it anyway, so this is great.

One suggestion though - how does everyone feel about adding authors to this too? Like title + author? Title might be enough, but not quite sure it's 100% sufficient.

I mean, what if we take it a step further - get rid of the buttons underneath the books and streamline it - just when someone hovers (especially for computers, as this may not work on phones), then it shows the title, author (optional), and button there.

@mekarpeles @Yashs911

**Comment by mekarpeles** [comment]
As mentioned in @Yashs911's PR #4498, I'd like to close this issue for now until such a time as we have a designed available to help us rethink how we want to present our carousels. Right now given the other efforts fighting for our attention, this doesn't seem like the biggest priority/opportunity. Thanks all for compiling these perspectives so we can return to this research in the future.
