### ISSUE TITLE
Consistency: JavaScript quotes

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2085]
We use a mix of quoting style in our codebase. Sometimes we use `"` and sometimes we use `'` with single quotes being most prevalent. We should use single quotes, and [prefer template](https://eslint.org/docs/rules/prefer-template) where possible.  Let's apply some  [eslint  rules](https://eslint.org/docs/rules/) and fix these.

[Eslint](https://eslint.org/) can be run by using `npm install && npm run lint:js`

```
    "prefer-template": "error",
   "quotes": ["error", "single"]
```
At time of writing there are  ✖ 385 problems (385 errors, 0 warnings)
  381 errors and 0 warnings potentially fixable with the `--fix` option.

### Checklist
- [ ] Update .eslintrc.json with the correct definition
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

**Comment by tfmorris** [comment]
That's a very large change with limited value add. Let's make sure that it's well isolated from any functional changes so that we don't pollute the revision history.

**Comment by jdlrobson** [comment]
It's a low risk change. The linter can autofix all these issues.

**Comment by jdlrobson** [comment]
In terms of importance, single quotes are usually better to make it easier to detect escaping problems when using html templating. Having a common language also helps us focus code review on code content by making it easier to read. I don't consider that limited value.

**Comment by philihp** [comment]
Would love to take this on and get involved, if that's all right?
