### ISSUE TITLE
Consistency: Spacing

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2087]
Our spacing is inconsistent. Let's apply some  [eslint  rules](https://eslint.org/docs/rules/) and fix these.

[Eslint](https://eslint.org/) can be run by using `npm install && npm run lint:js`

```
    "keyword-spacing": ["error", { "before": true, "after": true } ],
```
At time of writing there are  ✖ 13 problems (13 errors, 0 warnings)

### Checklist
- [ ] Update .eslintrc.json with the correct definition
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

**Comment by brad2014** [comment]
(@jdlrobson I'm using "refactor" for cleanup, "bug" for features that implemented but broken)

**Comment by jdlrobson** [comment]
@musayann will you send a pull request? I can review.
