### ISSUE TITLE
Move ctx.setdefaults('bodyid', ...) out templates, into controller

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2089]
Open Library CSS style sheets (which are named according to the `page-*` convention) may be on a per-template basis by specifying a `bodyid`. Unless specified otherwise, a template will default to a `user` value for `bodyid` which results in the loading of `page-user.css`.

Many templates which require custom style sheets instead of `user` declare this `bodyid` (i.e. the filename suffix they need) by using e.g. `$ctx.setdefault('bodyid', 'home')` from within the template (see: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html#L3). This makes the `bodyid` variable accessible to the template's parent, furhter up in the rendering chain, which uses this `bodyid` to dynamically load the right css (and other variable, e.g. js). This same functionality can be achieved equivalently within the controller using the `delegate.context` variable (e.g. `delegate.context.setdefault('bodyid', 'home')`.

We're currently inconsistent about where we set this ctx variable, but my opinion/preference is this should happen exclusively in the controller, cc: @hornc, @jdlrobson
 
e.g. for the homepage template, `ctx.setdefault('bodyid', 'home')` would be moved out of the template and into the controller as `delegate.context.setdefault('bodyid', 'home')`

This has the added benefit of enabling us to cache these templates because currently, when the template is cached, it does not have the chance to set the `$ctx.setdefault('bodyid', 'xxx')` resulting in the default `page-user` stylesheet being loaded.

To compound the confusion (as @hornc and I discovered) there are many ways to d things, even within the controller. `delegate.context.setdefault` can also be achieved directly via `web.template.Template.globals['ctx']['bodyid'] https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/home.py#L71. We should *remove* this case and instead commit to using `delegate.context.setdefault`. This was a mistake introduced because we didn't know `delegate.context` was an available precedent.

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/pull/2067/review_comment/create_

**Comment by jdlrobson** [comment]
Ideally this would have its own method that is called prior to template rendering but i seem to remember there were issues with infogami that made this impossible for ingogami provided routes

**Comment by mekarpeles** [comment]
I think this issue has served its purpose by eliciting general consensus from stakeholders on an approach. There isn't bandwidth to solve this one, so I'm closing for now. Nothing is blocked on further action.
