### ISSUE TITLE
Decimal values now broken on physical dimensions and weight

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2095]
## Description

When editing an edition record, existing decimal values under height, width, depth, and weight are sometimes being rejected with the balloon message “Enter a valid value”. I don’t find that string in searching the code base. Further, the up/down arrow widgets to adjust the value are not always visible, and the edit cannot be saved. 

## Evidence / Screenshot (if possible)

<img src="https://user-images.githubusercontent.com/11435431/57311426-a326cb00-70b9-11e9-8794-e5b444f95b17.jpg" width="300">

## Expectation
Existing values should not block saves

## Details
This seems to have some interaction to #1891: the edit cannot be saved, but the edition's link to the work is lost.

Logged in (Y/N)? 
Yes

Browser type/version?
Chrome or Safari

Operating system? 
iOS

**Comment by LeadSongDog** [comment]
Ah, it seems similar issues are already known, with an identified fix: https://github.com/jsonform/jsonform/issues/197

**Comment by cdrini** [comment]
To clarify, we need to add `step="0.01"` to all our number inputs where we except decimal values.

**Comment by LeadSongDog** [comment]
The missing mobile widget is separately addressed at #2146

**Comment by jdlrobson** [comment]
While working on this I noticed some UI problems with the fields.
Before:
![Screen Shot 2019-05-30 at 2 31 51 PM](https://user-images.githubusercontent.com/148752/58633078-ba875b80-82e7-11e9-8474-534bd9b528c1.png)

After:
![Screen Shot 2019-05-30 at 2 04 10 PM](https://user-images.githubusercontent.com/148752/58633041-9f1c5080-82e7-11e9-9da4-3f607eb4438d.png)
![Screen Shot 2019-05-30 at 2 24 06 PM](https://user-images.githubusercontent.com/148752/58633043-9f1c5080-82e7-11e9-88ea-a2d6cfc1fe0c.png)
![Screen Shot 2019-05-30 at 2 24 19 PM](https://user-images.githubusercontent.com/148752/58633044-9f1c5080-82e7-11e9-8de4-22dad96d85e9.png)
