### ISSUE TITLE
Allow for searching (and linking to) an OCLC ID

### ISSUE THREAD

**Issue by waldenn** [internetarchive/openlibrary#2099]
## Is your feature request related to a problem? Please describe.

I would like to link/search for an OCLC book ID via openlibrary, eg for "OCLC:1744006":

  https://openlibrary.org/search?q=OCLC:1744006

This is already possible for ISBNs:

  https://openlibrary.org/search?q=ISBN:9780394404288

Some Wikipedia articles use OCLC ID's instead of ISBNs. For now I am using a link to WorldCat ([example](https://wikischool.org/explore/The%20Prophet%20(book)?l=en)), but would prefer to link to the OpenLibrary. 

## Describe the solution you'd like

See above.

## Proposal & Constraints

See above. I know there is a search API, but I don't want to make an API call for each encountered OCLC ID to find its OpenLibrary page. For  such a clear identifier a direct link / search should be fine. Non-developers also might want to link to OCLC ID's.

**Comment by waldenn** [comment]
I just realized that this might be a data licensing issue. If that is the case I will close the issue.

Is searching with "OCLC:<ID>" possible if that data is available in OpenLibrary?

**Comment by LeadSongDog** [comment]
Shouldn’t be a problem. Check the license out.

**Comment by LeadSongDog** [comment]
See https://www.oclc.org/research/themes/data-science/fast/odcby.html

**Comment by LeadSongDog** [comment]
In the absence of an oclcn, it is also feasible to link by title: http so://worldcat.org/title/hitchhikers-guide-to-the-galaxy

**Comment by waldenn** [comment]
> In the absence of an oclcn, it is also feasible to link by title: https://worldcat.org/title/hitchhikers-guide-to-the-galaxy
> will find many editions. Note the apostrophe and caps are stripped, spaces replaced by hyphens.

I already have a working link... I do what Wikipedia also does, which is [link to](https://en.m.wikipedia.org/wiki/The_Prophet_(book)] WorldCat. However, I want to link to OpenLibrary (without too much data processing). This is a reasonable feature for OpenLibrary I think (link by OCLC or some other commercial ID like ASINs). Even if the OpenLirbary search for such an ID fails, it could point / redirect to the right page. "One link for each book" :-)

Also a search for  title on WorldCat will yield many [false-positives](https://www.worldcat.org/search?q=ti%3A%22the+prophet%22&qt=results_page).

**Comment by tfmorris** [comment]
The correct syntax is https://openlibrary.org/search?oclc=28464329

Of course it only works if the particular OCLC ID that the wikis picked is one of the ones that we catalog. If the OCLC ID represents an edition rather than a work, I don't see what value it is adding over a more universally recognized ISBN.

Of course, Wikipedia could store the OpenLibrary work ID directly (since it's usually the work which is being discussed, not a particular edition).

**Comment by waldenn** [comment]
Ok great thanks!

Where was this search attribute documented? I did not see it in the advanced search-form. Maybe some more documentation is needed here, and link it to the advanced search page.

Also, it would be nice if the same syntax "ISBN:" could also work for other ID-forms, but this indeed solve this issue.

**Comment by tfmorris** [comment]
> Of course, Wikipedia could store the OpenLibrary work ID directly (since it's usually the work which is being discussed, not a particular edition).

Wikidata had an OL ID, but it was for an edition, not the work. I've corrected it. https://www.wikidata.org/wiki/Q1196302

For some reason this ID isn't included in the Authority Control section at the bottom of https://en.wikipedia.org/wiki/The_Prophet_(book) but it is available from Wikidata.

> Where was this search attribute documented? I did not see it in the advanced search-form. Maybe some more documentation is needed here, and link it to the advanced search page.

I'm not sure whether/where it is documented, but I'd look in the developer API docs, not the end user docs. I wouldn't expect to see it in the Advanced Search form documentation since it's not offered on that form.

> Also, it would be nice if the same syntax "ISBN:" could also work for other ID-forms, but this indeed solve this issue.

If you need consistency, you can use https://openlibrary.org/search?isbn=9780394404288

**Comment by LeadSongDog** [comment]
@tfmorris There are many older editions that have no isbn, so for those an OCLCno is a good substitute. There are also many editions with multiple isbns (often from multiple publishers or distributors in different countries).

**Comment by BrittanyBunk** [comment]
I wonder why this got closed. As @LeadSongDog said, without an ISBN, other #'s help. If we don't want to go with the OCLC, then go with Dewey Decimal, LIC PCN, etc.

**Comment by tfmorris** [comment]
It got closed because the original question was answered (they were using the wrong search syntax).

As for all this other side conversation - sure, go ahead and add OCLC numbers to your hearts content.

**Comment by LeadSongDog** [comment]
For the example that @waldenn gave, one can try the search at Worldcat:
https://www.worldcat.org/search?q=28464329&qt=owc_search 
and then find (by clicking editions) 
https://www.worldcat.org/title/yeonja/oclc/28464329/editions?editionsView=true&referer=br
or just go directly to 
https://www.worldcat.org/oclc/28464329/editions?editionsView=true&referer=di
It appears there are at present 27 distinct oclc numbers for various Korean editions, several of which are for duplicated ISBNs, but that particular oclc number is the only one for the 1992 first Korean edition, ISBN 9788931000238 translated by Ŭn-gyo Kang. 

Most catalogues permit various sloppy searches.   Any identifier or classification number should be usable, complete or partial, by itself or in combination with other:
https://www.worldcat.org/search?q=284643*+prophet+1992&qt=results_page
We should be able to do similar things

**Comment by tfmorris** [comment]
To reiterate https://openlibrary.org/search?oclc=28464329
brings you to the work which lists 63 editions (yay more duplicates than OCLC).

If you want wildcard identifier searching or some other feature, please create a ticket for it and it'll get prioritized along with all the other stuff (like making search work for basic stuff).

**Comment by BrittanyBunk** [comment]
I think it would be good to have WorldCat as a number to search for. Granted, not everything's on there or complete, but it's an alternative.

**Comment by BrittanyBunk** [comment]
Should we reopen this for this purpose or start a new github issue on it?
