### ISSUE TITLE
Inconsistent resizing of edit windows

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2100]
## Description

Cosmetic:
In the edition edit, the "Table of Contents" window behaves differently than the "Any notes about this specific edition?" and the "Description of this edition" windows. The first can only be resized vertically, while the other two can resize horizontally too. It's also pretty wierd that the grey background under "This Edition" scales horizontally independent of the rest of the page.

## Evidence / Screenshot (if possible)

![resize](https://user-images.githubusercontent.com/11435431/56835965-b1682200-6843-11e9-8e9a-71dd5a5dd3fd.png)

## Expectation

consistency

## Details

Yes

Chrome

Win 7 Pro

**Comment by jdlrobson** [comment]
Unable to replicate this for table of contents on https://openlibrary.org/books/OL24982896M/Pioneers/edit 👎 
![Screen Shot 2019-05-30 at 2 02 00 PM](https://user-images.githubusercontent.com/148752/58631663-8ad65480-82e3-11e9-8adf-9abc31f2bc53.png)

I am seeing an issue with IDs and classifications

![Screen Shot 2019-05-30 at 2 04 10 PM](https://user-images.githubusercontent.com/148752/58631760-d7ba2b00-82e3-11e9-99d4-a501c78a362c.png)

A follow up patch will fix that.

**Comment by LeadSongDog** [comment]
@jdlrobson 
You could not replicate there because you were using a mobile browser, for which the edit windows do not show any resizing handle in the bottom right corner. Perhaps this could be seen to argue that independent resizing of the edit windows is an unnecessary feature, but I often find the scrolling within an edit window on mobile to be somewhat dysfunctional, particularly when trying to select a block of text with the device in landscape orientation. Maybe I'm just doing it wrong?

**Comment by jdlrobson** [comment]
Is the screenshot up to date? I was actually using desktop browser with mobile resolution.

I'm now not sure what issue you are referring to.. the textareas you have circled are all resizable to me and all non-multiline are not.

Maybe autoresizing would be most useful for both mobile and desktop? Is the issue that you want to avoid scrolling text areas with lots of text?

**Comment by LeadSongDog** [comment]
@jdlrobson It was current when posted. I’ll revisit later today.
