### ISSUE TITLE
Import alternate author names from MARC $q subfield

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2103]
from #1530

In MARC21, some fields have a $q subfield which can store a single "Fuller form of name" 

relevant code:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/marc/parse.py#L276

in `read_author_person()`

Fuller form of names `$q`:
https://www.loc.gov/marc/bibliographic/bd100.html
https://www.loc.gov/marc/bibliographic/bd700.html

and
https://www.loc.gov/marc/bibliographic/bd600.html , although this is a subject and we are not making use of this field to create objects. 

Implement for 100 and 700

**Comment by tfmorris** [comment]
What's blocking the importing of MARC 100$q fields? It's seems straightforward, bordering on trivial.

Skipping them means that the archive.org display has more information than the OpenLibrary display
https://archive.org/details/legionofmarching00blaciala
https://openlibrary.org/books/OL7058654M

Also, ignoring the additional information that's included in the MARC record:
https://openlibrary.org/show-records/ia:legionofmarching00blaciala
makes the author record more ambiguous and harder to match.

Even though it's not the kind of "bling" that the IA execs crave, it's a solid data quality win that's easy to achieve.

**Comment by tfmorris** [comment]
Actually, support for both 100$q and 700$q was implemented in 2010, but the 100$q had a bug in it which I just fixed. However, all it does is populate the `fuller_name` field for author records which will not be visible or editable anywhere.

There is a smattering of author records with this field, but only 1028 instances in the 2022-11-30 database.

**Comment by hornc** [comment]
Closing this in favor of #7408  as this title of this issue isn't correct 

-- despite the official description "Fuller form of name" `100$q` doesn't in practice appear to contain 'full name' forms, so isn't a drop in 'alternate author name' value.

All the examples I have seen require some form of assumption to expand some sub-section of an existing  full name to a 'fuller' version.

**Comment by tfmorris** [comment]
It's not ideal, but name with fuller form appended as an AKA might be a good enough start. It won't be pretty, but it'll help (a lot) with search discoverability and finding duplicate authors.
