### ISSUE TITLE
Incorrect title displayed on list of works

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2105]
## Description
Title of work was spammed on 19 April. It was changed back to the proper title the same day, but the incorrect title is displayed on the author's list of works.

## Evidence / Screenshot (if possible)
![Fullscreen capture 522019 53820 PM bmp](https://user-images.githubusercontent.com/17739465/57087995-92fd9d00-6d01-11e9-84ef-3332695b5a1b.jpg)

## Relevant url?
https://openlibrary.org/authors/OL1394359A/Suzanne_Collins?merge=true&duplicates=OL7469814A

## Expectation
Title on list view should match that of work.

**Comment by hornc** [comment]
Fixed by forcing a manual solr reindex of the work.
