### ISSUE TITLE
Remove fake subjects from Works

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2107]
## Description

Three of the top five "subjects" are not subjects at all:
* `Accessible book` - 2.5 million
* `Protected DAISY` - 1.2 million
* `In library` - 0.5 million

The are also some lower frequency noise terms like `Lending library` and `Internet Archive Wishlist` but the three above represent the bulk of the noise.

## Expectation

The subject list should contain things which are actually subjects of the work.

## Proposal & Constraints

Remove the three subjects above. If they're needed to provide functionality move them to a hidden portion of the Solr index where they don't pollute the UI.

**Comment by LeadSongDog** [comment]
@tfmoorris Perhaps these tags should be supplanted by a new entry under _The Physical Object_ / _Format_ prior to deletion, or is there a better way?

**Comment by hornc** [comment]
We should also remove this code which looks like it is trying to protect these subjects:

https://github.com/internetarchive/openlibrary/blob/47c72f9ed8e831f098edcba968aa2532ec52c19b/openlibrary/plugins/upstream/addbook.py#L38

https://github.com/internetarchive/openlibrary/blob/47c72f9ed8e831f098edcba968aa2532ec52c19b/openlibrary/plugins/upstream/addbook.py#L597

https://github.com/internetarchive/openlibrary/blob/47c72f9ed8e831f098edcba968aa2532ec52c19b/openlibrary/plugins/upstream/addbook.py#L600

These subjects should no longer be used as there are other ways to get the information they were trying to convey.

**Comment by LeadSongDog** [comment]
@hornc 
Are those "other ways to get the information" all working and documented to users?

**Comment by hornc** [comment]
Checking ol_dump_editions_2019-12-31.txt

- [ ] Lending library appears to be clear
- [ ] Internet Archive Wishlist 0, also clear

ol_dump_works_2019-12-31.txt
- [ ] Lending library 0
- [ ] Internet Archive Wishlist  - 382004 remaining
- [ ] In Library - 436321 remaining

**Comment by hornc** [comment]
Subjects search for quicker testing of current numbers:

- https://openlibrary.org/subjects/accessible_book
- https://openlibrary.org/subjects/protected_daisy
- https://openlibrary.org/subjects/in_library

**Comment by hornc** [comment]
The last `accessible book` subjects found in the ol_dump_works_2020-07-31.txt.gz have been processed and had these subjects removed.
