### ISSUE TITLE
solr-updater error on invalid character

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2123]
The main error is: `ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters`.

Here are some more specific cases:

http://openlibrary.org/works/OL23125901M

```
2019-05-13 10:17:06,789 [ERROR] Error in normalizing u'Hompajtotokyc\x1b$1\x7f \x19\x1b(Bom'
2019-05-13 10:17:06,790 [ERROR] failed to update work /works/OL23125901M
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1157, in openlibrary.solr.update_work.update_work
    dict2element(d)
  File "openlibrary/solr/update_work.py", line 668, in openlibrary.solr.update_work.dict2element
    add_field_list(doc, k, v)
  File "openlibrary/solr/update_work.py", line 148, in openlibrary.solr.update_work.add_field_list
    add_field(doc, name, value)
  File "openlibrary/solr/update_work.py", line 131, in openlibrary.solr.update_work.add_field
    raise
  File "openlibrary/solr/update_work.py", line 128, in openlibrary.solr.update_work.add_field
    field.text = normalize('NFC', six.text_type(strip_bad_char(value)))
  File "src/lxml/etree.pyx", line 1020, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 711, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 699, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1439, in lxml.etree._utf8
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

http://openlibrary.org/works/OL18362971M

```
2019-05-13 13:27:23,800 [ERROR] Error in normalizing u'Kontur Swedish design annual \x12.'
2019-05-13 13:27:23,801 [ERROR] failed to update work /works/OL18362971M
...
```

https://openlibrary.org/works/OL13706004W (references https://openlibrary.org/books/OL22912784M )

```
2019-05-13 10:03:43,073 [ERROR] Error in normalizing u'Reproduction of Thompson and West\x1b$1\x7f \x19\x1b(Bs History of Sacramento County, California. With Illustrations'
2019-05-13 10:03:43,074 [ERROR] failed to update work /works/OL13706004W
...
```

**Comment by hornc** [comment]
The Work example in the error message above on the text: "Reproduction of Thompson and West\x1b$1\x7f \x19\x1b(Bs History of Sacramento County, California. With Illustrations" associated with the work /works/OL13706004W is actually in the edition: https://openlibrary.org/books/OL22912784M (I found this by searching the db dump for an edition with that work reference)

**Comment by cdrini** [comment]
Thanks! Added to the description. This also works: https://openlibrary.org/works/OL13706004W/editions.json

**Comment by tfmorris** [comment]
I've fixed update_work.py to handle this better, but there's nothing it can do if given bad data. The records themselves need to be fixed (and traced back to where the corruption was introduced).

**Comment by guyjeangilles** [comment]
https://openlibrary.org/works/OL18362971M is producing
>Bad Request
Invalid HTTP Header: "'https://openlibrary.org/books/OL18362971M/Kontur_Swedish_design_annual_\\x12.'" 

@hornc @tfmorris It sounds like the bad request is a problem that should be tracked in a separate issue.

**Comment by tfmorris** [comment]
> It sounds like the bad request is a problem that should be tracked in a separate issue.

I think that's #2269

**Comment by guyjeangilles** [comment]
Should this issue be closed?

**Comment by tfmorris** [comment]
I'm trying to confirm that the problem has actually been fixed, since, unfortunately, I didn't cite a commit with my claim that I'd fixed it.

The original code is here: https://github.com/internetarchive/openlibrary/blob/670a4cf9957125e09bd567c79b62bdf13d8431c9/openlibrary/solr/update_work.py#L125
and I made the error message more specific here:
https://github.com/internetarchive/openlibrary/blob/1cbc07251d6e684b1fe65449631167f51dd10576/openlibrary/solr/update_work.py#L130
but I don't see a fix or any tests (and even that commit with the improved error logging is still on branch). What probably needs to be done is to enhance this regex: https://github.com/internetarchive/openlibrary/blob/02ccb3da30f4bed47f240bbf99a31135c244d427/openlibrary/solr/update_work.py#L31 
to be something more like this: https://stackoverflow.com/a/22273639/167425

```Python
_illegal_unichrs = [(0x00, 0x08), (0x0B, 0x0C), (0x0E, 0x1F), 
                        (0x7F, 0x84), (0x86, 0x9F), 
                        (0xFDD0, 0xFDDF), (0xFFFE, 0xFFFF)] 
if sys.maxunicode >= 0x10000:  # not narrow build 
        _illegal_unichrs.extend([(0x1FFFE, 0x1FFFF), (0x2FFFE, 0x2FFFF), 
                                 (0x3FFFE, 0x3FFFF), (0x4FFFE, 0x4FFFF), 
                                 (0x5FFFE, 0x5FFFF), (0x6FFFE, 0x6FFFF), 
                                 (0x7FFFE, 0x7FFFF), (0x8FFFE, 0x8FFFF), 
                                 (0x9FFFE, 0x9FFFF), (0xAFFFE, 0xAFFFF), 
                                 (0xBFFFE, 0xBFFFF), (0xCFFFE, 0xCFFFF), 
                                 (0xDFFFE, 0xDFFFF), (0xEFFFE, 0xEFFFF), 
                                 (0xFFFFE, 0xFFFFF), (0x10FFFE, 0x10FFFF)]) 

_illegal_ranges = ["%s-%s" % (unichr(low), unichr(high)) 
                   for (low, high) in _illegal_unichrs] 
_illegal_xml_chars_RE = re.compile(u'[%s]' % u''.join(_illegal_ranges)) 
```

That should be enough detail (and we've example data for tests) to make this easy for someone to tackle.

**Comment by mekarpeles** [comment]
@cdrini do you mind taking this one over (that means assigning yourself rather than charles, so we can consolidate who is assigned / has visibility over our various solr issues?

**Comment by hornc** [comment]
I have fixed the specific items mentioned above. Most seem to be MARC21 field separators which have been included in some fields from older bot imports (bypassing the built in imports). Any similar issues will be data clean up.

The refactoring required for #3584 and Python3 is going to introduce better bytes to Unicode conversion.
