### ISSUE TITLE
Empty author for new works created from Author page "Add another" link

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2128]
## Description

New works added by using the link from "Add another?" on the author page create works with an empty author field.

Author: https://openlibrary.org/authors/OL2720361A/Alex_Hutchinson
link: https://openlibrary.org/books/add?author=/authors/OL2720361A
work: https://openlibrary.org/works/OL19677694W/Endure?v=1

The form is correctly pre-populated with the author name, but the corresponding ID doesn't get written into the record that is created. Because of this it's fairly likely that the user won't notice that the data is missing

**Comment by seabelis** [comment]
Received a user inquiry about this today.

**Comment by seabelis** [comment]
Received another user message about this.

**Comment by LeadSongDog** [comment]
Sounds a lot like #351, perhaps closed prematurely?
The "Save" button should presumably be grayed out until the key values are populated: that's what users are accustomed to on other interfaces.

**Comment by tfmorris** [comment]
Is this supposed to have two assignees? ( @mekarpeles & @cdrini )

**Comment by tfmorris** [comment]
This is a duplicate of #1716
