### ISSUE TITLE
Make dev.openlibrary.org visually distinct from production openlibrary

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2129]
## Is your feature request related to a problem? Please describe.
We use dev a lot for testing, and it's currently **super** easy to forget whether you're in dev or production. Let's make the dev site more obviously different.

## Stakeholders
@hornc

**Comment by cdrini** [comment]
Idea No1:
![image](https://user-images.githubusercontent.com/6251786/57896361-557b3280-781e-11e9-8cb0-eb7943d08f96.png)
`background: repeating-linear-gradient(-45deg, #e2dcc5 10px 40px, #e2dcc5b3 10px 50px)`

**Comment by jdlrobson** [comment]
We have a separate file for dev:
```
    $if "dev" in ctx.features:
        <link href="$static_url('build/page-dev.css')" rel="stylesheet" type="text/css"/>

```
Adding background there makes sense to me.
```
    background-color: yellow;
```
(assuming dev feature is enabled there)

**Comment by jdlrobson** [comment]
I suggest something as subtle as
![Screenshot 2019-12-06 at 3 42 31 PM](https://user-images.githubusercontent.com/148752/70363879-0b4fb200-183f-11ea-8d5b-6ccfbce66e8f.png)
Patches welcomed in that direction. I don't plan on working on this.

```
{
.logo-txt::after {

    content: 'beta';
    position: absolute;
    transform: rotate(10deg);
    background: 

#C6FFE0;

opacity: 0.8;

pointer-events: none;

padding: 0 .7em;

font-size: 1em;

line-height: 1.75;

border-radius: 2px;

    border-top-left-radius: 2px;
    border-top-right-radius: 2px;
    border-bottom-right-radius: 2px;
    border-bottom-left-radius: 2px;

box-shadow: 1px 1px 1px
rgba(0,0,0,0.1);

left: 206px;

top: 43px;

z-index: 2;
}
```

**Comment by mekarpeles** [comment]
@jdlrobson's implementation seems to address the problem:
https://github.com/internetarchive/openlibrary/issues/2129#issuecomment-517080942

There is not consensus on colors or component; e.g. IA topbar? Background?

1) Some colors (yellow, stripes) as proposed have accessibility/contrast issues (or are too close to production)
2) The background color may be too distracting for demos or disrupt designers trying to work on dev.

Proposing we follow @jdlrobson's implementation details.
Proposing additionally we set a
`border-bottom: 3px solid red;` on `body` for dev.

**Comment by mekarpeles** [comment]
P.S. I'm really hoping we can avoid bike shedding here and keep it as practical as possible. 

1) It sounds like staff (@hornc + @cdrini) are voting for this
2) If we're going to do it, it should meet some basic accessibility considerations for our community (i.e. achieve it's goal of being visible)
3) This is not a feature we should invest time on: let's get it done -- this requires us to make a decision, or the community can't even help by working on it.
4) Not disrupt anyone's contributions (e.g. not make it harder for designers)
5) Not require code bloat (i.e. no adding new colors, minimal css, no new config paths)

**Comment by jdlrobson** [comment]
Pushed https://github.com/internetarchive/openlibrary/pull/2730 - simplest solution here.
This is for development only. I think worrying about accessibility etc is overkill. The purpose is to stop people creating test content accidentally in production and this solves that.
