### ISSUE TITLE
Adding FictFact.com as an book indentifier

### ISSUE THREAD

**Issue by briankirsten** [internetarchive/openlibrary#213]
Would it be possible to add FictFact.com as a book identifier? The url template looks like this:

url: http://www.fictfact.com/book/details/@@@
name: fictfact
label: FictFact

Here's a working example:

http://www.fictfact.com/book/details/92

**Comment by guyjeangilles** [comment]
Closing this issue as it seems fictfact.com is defunct [source 1](https://community.qvc.com/t5/Book-Club/FICT-FACT-IS-NOW-CLOSED/td-p/5471560) [source 2](https://the-digital-reader.com/2019/05/21/fictfact-is-shutting-down/).

@briankirsten It appears you're a team member of FictFact. The social media accounts still seem active. Are there plans to make a similar service?

**Comment by briankirsten** [comment]
> 
> 
> Closing this issue as it seems fictfact.com is defunct [source 1](https://community.qvc.com/t5/Book-Club/FICT-FACT-IS-NOW-CLOSED/td-p/5471560) [source 2](https://the-digital-reader.com/2019/05/21/fictfact-is-shutting-down/).
> 
> @briankirsten It appears you're a team member of FictFact. The social media accounts still seem active. Are there plans to make a similar service?

We're planning on a new service, but real life has been in the way so we don't have a release date.
