### ISSUE TITLE
Merged works break on lists

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2131]
## Description
When a work that has been added to a user's list has been merged, the link from the list breaks and becomes useless to the user. The appearance provides no information to the user about what the work was nor does it redirect to the new work, i.e. /works/OL151925W unknown - 0 works

## Evidence / Screenshot (if possible)
![Fullscreen capture 5192019 124810 PM bmp](https://user-images.githubusercontent.com/17739465/57981224-5e921c80-7a35-11e9-8d37-5eb7de6810db.jpg)

## Relevant url?
https://openlibrary.org/works/OL151925W
https://openlibrary.org/people/vivisoesanty/lists/OL99633L/Authors_for_children's_books?page=5

## Expectation
That a work has been merged should be invisible to the user. The old work on their list should, at the very least, point to the new work. Preferably, the list would be updated so that the old work on their list would be replaced with the new work and subsequently their list would also be visible from the new work's page. (I'm not sure how the relationship is set up. In the end I think either the new work has to be migrated to the list or the list be migrated to the new work.)

## Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by cdrini** [comment]
I thought there might be something like this :( Looking through the history, it looks like we've hit on this before: #501 . I guess I'll close this as a duplicate.
