### ISSUE TITLE
No visual indicator when selecting a cover when editing work

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2132]
## Description
Go to an edition page which lists more than 1 edition - it should show 3 ways to upload a cover.

Select a cover from the "Pick one from the existing covers" list when editing a work. Clicking the cover shows no visual indicator that it's been selected. I just assumed it wasn't working.

## Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/57995718-ac3c7280-7a91-11e9-9476-5dc3789e81e8.png)

## Relevant url?
Any work, but for example: https://openlibrary.org/works/OL5780488W/Silurian_(Late_Llandovery-Ludlow)_Atrypid_Brachiopods

## Expectation
Clicking the cover should select it.

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 66.0.5 (64-bit)
- **Operating system?** Windows 10

## Stakeholders
@jdlrobson

**Comment by seabelis** [comment]
This is working normally for me.

**Comment by seabelis** [comment]
Although I think there used to be better visual indicators for choosing a cover. Maybe it was highlighted in some way.

**Comment by cdrini** [comment]
Ahhh, I think you're right. It looks like some CSS that used to run isn't running. There's no visual indicator after clicking the cover that it's been selected.

**Comment by jdlrobson** [comment]
There is no CSS for this specific rule, but slick-active is the selector to use. This needs some design e.g.
```
.slick-active { border: solid 1px red; }
```
@brad2014 do we have a "needs: design" tag for these kind of things?

**Comment by cdrini** [comment]
@koderjoker If you're looking for an issue, this would be a good quick one :)

Turns out the email was about something else, but putting this to Priority: Normal because it's got a relatively easy fix and is kind of frustrating.

**Comment by jdlrobson** [comment]
Just to note there's a mergeable solution here > https://github.com/internetarchive/openlibrary/pull/2699
