### ISSUE TITLE
Styling of author edit page has regressed

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2133]
## Description
It looks like some CSS is not being applied that should be. For example, most of the inputs should be full width. The author's image (I think) used to be near the top, not at the bottom.

## Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/57997126-07259800-7a99-11e9-9df2-0c4c4aadb3be.png)

## Relevant url?
Any author, but for example: https://openlibrary.org/authors/OL232066A/Nancy_Cartwright/edit

## Expectation
This isn't on waybackmachine, but I'll see if I can find a screenshot of what it used to look like.

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 66.0.5
- **Operating system?** Windows 10

## Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
At (min-width: 960px) a rule width: 475px; kicks in. I don't see why that cannot be removed but not totally sure if that will break other things.
