### ISSUE TITLE
Create work independent of edition

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2138]
## Description
Changing title in "What work is this an edition of?" no longer creates new work. And since it is not possible to create a new work without an actual edition to associate with it, it is not possible to move incorrectly associated editions if the work does not already exist.

## Relevant url?
https://openlibrary.org/books/OL1889320M/The_book_of_questions
This is not the same as the work it is associated with. It does not exist yet as a work.
## Expectation
Previously, I would change the title in the "What work is this an edition of?" field and the edition would be moved to a new work.

## Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 74.0.3729.157 (Official Build) (64-bit)
- **Operating system?** Win 7 Pro

**Comment by mekarpeles** [comment]
@cdrini do you mind taking a look at this? Is this related to recent changes we've made?

**Comment by mekarpeles** [comment]
Feature requires move edition drop-down to have "change work" should have a create new

Fact that this used to work was a bug (or undocumented feature).

**Comment by LeadSongDog** [comment]
As currently on prod, this does seem to function better than previously. That said, when the merged work ID is inserted, there is only a brief appearance of the work title. Once the user clicks on the title, it returns to showing just the work id. It would be better if _both_ the ID _and_ the work title were visible.  A similar thing could be said about edits to the author field. Once the suggestion is clicked, it is hard to tell which John Smith has been accepted except by saving and remembering to click-through to verify. Actually showing the author ID beside the author name would improve transparency.

**Comment by seabelis** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/352?

**Comment by LeadSongDog** [comment]
@seabelis 
Well, peripherally related, but when an orphan edition record exists, an author OLID also exists already and should be referenced in that edition record. Creating a work record should remove the reference to the author OLID from the extant edition at the same time it adds a linked work OLID. Normally this should happen when someone hits the "add another" [edition] link.
