### ISSUE TITLE
Dev environment should use supervisord for prod-parity

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2149]
## Description
Prod is using supervisord to manage running solrupdater, infobase, and importbot. We should have a copy of their conf files in the repo and use them on our Docker dev instance.

## Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
@mekarpeles could you provide the `.conf` files for those (and any other) supervisord sevices?

**Comment by mekarpeles** [comment]
@cdrini -- yes; these should probably be moved **out** of olsystem and into openlibrary. Punting on "moving out of olsystem" as a short term goal (hopefully we'll be able to just deprecate olsystem instead of doing surgery): let's make sure they're in openlibrary

Notice that configs in `olsystem` are often referenced in the scripts below.

**openlibrary.conf**
```
[program:openlibrary]
command=/olsystem/bin/upstart-service openlibrary-server :7071
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/openlibrary.log
environment=USER=openlibrary
```

**solr-updater.conf**
```
[program:solr-updater]
command=/olsystem/bin/olenv python /opt/openlibrary/openlibrary/scripts/new-solr-updater.py --config /olsystem/etc/openlibrary.yml --state-file /var/run/openlibrary/solr-update.offset --socket-timeout 600
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/solr-updater.log
environment=USER=openlibrary
```

**infobase.conf**
```
[program:infobase]
command=/olsystem/bin/olenv python /opt/openlibrary/openlibrary/scripts/infobase-server /olsystem/etc/infobase.yml fastcgi 7050
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/infobase.log
environment=USER=openlibrary
```

**coverstore-7076.conf**
```
[program:coverstore-7076]
command=/olsystem/bin/upstart-service coverstore-server :7076
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/coverstore-7076.log
environment=USER=openlibrary
```

**coverstore-7075.conf**
```
[program:coverstore-7075]
command=/olsystem/bin/upstart-service coverstore-server :7075
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/coverstore-7075.log
environment=USER=openlibrary
```


**import-bot.conf**
```
[program:import-bot]
command=/olsystem/bin/olenv HOME=/home/openlibrary OPENLIBRARY_RCFILE=/olsystem/etc/olrc-importbot python /opt/openlibrary/openlibrary/scripts/manage-imports.py --config /olsystem/etc/openlibrary.yml import-all
user=openlibrary
directory=/opt/openlibrary/openlibrary
redirect_stderr=true
stdout_logfile=/var/log/openlibrary/import-bot.log
environment=USER=openlibrary
```

**Comment by hornc** [comment]
I think this issue should be re-phrased to not require supervisord specifically. Prod and dev _should_ be in line with each other, but following what is most appropriate for the Dockerized direction we are pursuing. My thought is supervisord will not be involved, but we'll need to investigate and do it properly once we have settled on the production goal.

**Comment by guyjeangilles** [comment]
@cdrini @hornc What's the current status of changing the dev environment?

**Comment by cdrini** [comment]
Was this closed by accident?

**Comment by cdrini** [comment]
No longer applicable; these have been moved into separate docker services. The last outstanding items are import-bot and solr-updater (tracked in #4060 )
