### ISSUE TITLE
Collect data on whether carousel pattern is useful to users

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2160]
## Is your feature request related to a problem? Please describe.
OpenLibrary makes heavy use of the carousel UI pattern but it's not clear whether our users engage with these. They have accessibility problems ([e.g](https://www.creativebloq.com/accessibility-expert-warns-stop-using-carousels-7133778) and many designers advise more effective alternatives ([e.g.](https://www.justinmind.com/blog/building-better-ux-patterns-3-alternatives-to-rotating-carousels/))) and potentially don't drive the engagement one might expect. We should collect some data around usage to test the assumption that our users find them useful.

## Describe the solution you'd like
- Click track clicks to the arrows
- Click track clicks to items within carousel
- An A/B test could test the carousel against a 2nd UX pattern (e.g. scrollable horizontal DIV or no carousel at all)

## Proposal & Constraints
- Can we split traffic to run an A/B test (e.g serve different HTML to 2 groups)?
- Can we run an A/B test using JS if necessary?

**Comment by cdrini** [comment]
What's the difference between a carousel and a scrollable horizontal div?

**Comment by jdlrobson** [comment]
> What's the difference between a carousel and a scrollable horizontal div?
Not much but seemed like a good starting point. The question would be "Is a JavaScript heavy interactive carousel more engaging to users then a horizontal scrolling DIV that's made entirely from HTML and no JavaScript. I'd guess the answer would be yes, but by how much is not clear to me.

Imagine if the front page was an infinite scrollable list of images? e.g. like this: http://trending.wmflabs.org/wiki/Special:Random

**Comment by jdlrobson** [comment]
Other interesting data point > #2375

**Comment by mekarpeles** [comment]
I'm open to considering alternatives -- I do not foresee a replacement to carousels being on our 2020 staff roadmap. I am open to considering something like https://trending.wmflabs.org/wiki/Special:Random for #2072. This issue will remain referenced there, but given there isn't a clear scope for this specific issue, I'd like to close until we can figure out how to apply this good advice.

Sorry @jdlrobson, this is definitely not a vote against your proposal: it's not being rejected. I'd like to preserve its context in the scope of #2072 so we can have a better idea of what actionable and critical issues are on our plate.

**Comment by tfmorris** [comment]
How hard would it be to start collecting click counts for the existing design to gauge usage, even if there isn't a separate design to compare against?

**Comment by jdlrobson** [comment]
I'm fine with this being folded into an epic but I'm not seeing any mention on #2072 of performing user research or collecting data around carousel usage.
