### ISSUE TITLE
Create Database of Book Sponsorships

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2163]
Creating a database for recording book sponsorships which would be later used to display book sponsorship information on the accounts page and creating a leaderboard of Sponsorships. 

The steps needed to be done are:
- [ ] Design database schema sql
- [ ] Write models (see: Reading Log & User Follows examples)

We can use to database via the Policy Check API to see `Has book already been sponsored?`

**Comment by tabshaikh** [comment]
@mek we would need to discuss about the attributes in the database too :)

**Comment by mekarpeles** [comment]
@bfalling it seems like this data may actually be stored on Archive.org and we'll need to use the XAuthn API (using Open Library patrons s3 keys) to fetch the information we need:

- sponsorship per user
- leaderboard of sponsors

Will this be coming from an Archive.org database?

**Comment by mekarpeles** [comment]
This will mostly be managed by Civi

**Comment by tfmorris** [comment]
What's a "Civi" ? Link?

**Comment by tabshaikh** [comment]
@tfmorris Civi is the internal database of archive.org which stores the data of each book and the user who has sponsored it ... @mekarpeles  can explain it in detail :)
