### ISSUE TITLE
Thank you page + email receipt

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2167]
After the payment, the user will be redirected to a thank you page and will also receive an email receipt of the payment whose design and contents are yet to be decided.

Tasks to be done are:
- [ ] Design and implementation. 
- [ ] For testing, getting feedback, merging of pr.

**Comment by mekarpeles** [comment]
@bfalling, we're under the impression that we can just use Archive.org donate's thank you page -- is there a way we can easily see the design or flow for these steps by making a test payment?

**Comment by tabshaikh** [comment]
@bfalling this is going to done on archive.org so closing here
