### ISSUE TITLE
View My Sponsored Books page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2178]
Child of #659 

## Is your feature request related to a problem? Please describe.

How does a patron keep track of the books they're sponsoring?

## Describe the solution you'd like

https://openlibrary.org/account UI will need to be edited to also show “Your Sponsored Books” *if* the user is in the sponsorship usergroup (edited) 

The URL we’ll probably want is: https://openlibrary.org/account/books/sponsorship
Which will show a list of books the user is sponsoring

## Proposal & Constraints

The results of this page page will need to come from either querying archive.org for a metadata key like `sponsorship` or using privileged access to the user's archive.org item via xauthn + s3. i.e. We'll rely on Archive.org to tell us what books a user have sponsored and then render them on openlibrary.org

**Comment by tabshaikh** [comment]
@mekarpeles is this issue same as the one I created earlier #2168

**Comment by mekarpeles** [comment]
Closing this as duplicate of #2168
