### ISSUE TITLE
General search by Internet Archive ID produces inaccurate results

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2191]
### Description
Using the Internet Archive ID as a general search term does not produce reliable results. 

### Evidence / Screenshot (if possible)
General search: https://openlibrary.org/search?q=alicesadventures00carr_16&mode=everything&m=edit
Search with ia prefix: https://openlibrary.org/search?q=ia%3Aalicesadventures00carr_16&mode=everything
(Still not ideal since it only produces the work rather than edition, but it at least confirms that it exists.)
Oddly, unrelated searches frequently produce this same result:
![Fullscreen capture 6122019 92442 AM bmp](https://user-images.githubusercontent.com/17739465/59331417-332ce580-8cf4-11e9-8cf0-cc585a0fb537.jpg)
![Fullscreen capture 6122019 92439 AM bmp](https://user-images.githubusercontent.com/17739465/59331423-3627d600-8cf4-11e9-9d05-c9ebca7981f4.jpg)
Note: searching by IA id with no prefix was previously a reliable way to tell if an IA edition existed in the OL catalog and would produce the edition record (except in cases where the IA ID was duplicated.) Yesterday was the first time I noticed a difference in behavior.
### Expectation
If there is an associated record in Open Library, a general search by IA ID should produce it. This is important because IA records do not always include OL Work and Edition IDs, even if they exist in the catalog.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by SouthGoingZax** [comment]
Is this still an issue?  All of these seem to return the right thing:

https://openlibrary.org/search?q=grasscrown00mccu&mode=everything
https://openlibrary.org/search?q=kiterunne00hoss&mode=everything
 https://openlibrary.org/search?q=alicesadventures00carr_16&mode=everything&m=edit

**Comment by seabelis** [comment]
Thank you, @SouthGoingZax . It does seem to be working correctly now.
