### ISSUE TITLE
Add /account/sponsorships url endpoint

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#2197]
### Subtask of #2168 

http://localhost:8080/account/books/sponsorships

### Proposal & Constraints
To allow the user to view their sponsorship status we are proposing a new endpoint which we are naming /account/books/sponsorships from where the user would be able to view their sponsorships just like they view their book loans

**Comment by tapaswenipathak** [comment]
Hi @tabshaikh: Can you outline more?

**Comment by tabshaikh** [comment]
Hi, @tapaswenipathak Thank you for showing interest to work on this but this issue is pr for this issue has been merged :)
