### ISSUE TITLE
Edit form is ignoring some options

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2210]
### Description

Selecting the "Yes, its a translation" option when editing https://openlibrary.org/books/OL27083670M/The_Black_Tulip is ignored.

### Relevant url?

https://openlibrary.org/books/OL27083670M/The_Black_Tulip

### Details
User-Agent: Mozilla/5.0 (Windows NT 6.1; rv:67.0) Gecko/20100101 Firefox/67.0

Reported by kevin61

**Comment by LeadSongDog** [comment]
Well, there are several issues with edit forms that need to be addressed, some _very_ longstanding:
#228 #352 #610 #853 #1716 #2033 #2073 
@mekarples Perhaps librarianship and editing issues don't feel as important to devs as cosmetics?

**Comment by seabelis** [comment]
Duplicate of #1892

**Comment by cdrini** [comment]
Closing as duplicate of #1892
