### ISSUE TITLE
Non-MARC archive.org import data issues

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2220]
Issues with No MARC import:
an example:
https://openlibrary.org/books/OL27042435M/Self-Study_and_Evaluation_Guide_Section_D-26_Residential_Living_Program

* Subject not split on semi-colon
* Publisher not populated
* Pages not populated

relates to original features #1029 ,  code in #1058

**Comment by guyjeangilles** [comment]
@hornc did this get fixed when #1058 got merged?

**Comment by hornc** [comment]
@guyjeangilles no, this issue relates to imports from archive.org _without_ MARC records. That PR only applies to archive.org MARC items
