### ISSUE TITLE
Remove unnecessary and redundant contributors from dropdown

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2227]
### Is your feature request related to a problem? Please describe.
The current edit form is set up in a way that suggests adaptations and retold works should be filed under the original by the presence of the "Adaptation" and "Retold by" labels in the Contributors dropdown options.

Add a label "Based on a work by".

### Describe the solution you'd like
Adaptations/Re-tellings should be considered independent works and attributed to the adapter (or copyright holder if unattibuted) in order to differentiate the records. While it may be easier from a data management perspective to lump everything with a given title together, it ultimately makes it harder for the end-user to locate or identify adaptations of the original. i.e. A picture book based on an animated movie based on part of a classic work is not equal to the original work.

### Proposal & Constraints

Existing information should not be purged, of course, but the option to add a re-teller should be removed to avoid confusion. 

### Additional context
![Fullscreen capture 7202019 112139 AM bmp](https://user-images.githubusercontent.com/17739465/61576929-b6560e00-aae0-11e9-9c03-5c10756e15bb.jpg)

**Comment by LeadSongDog** [comment]
@seabelis 
I can't agree that derivative works should be treated as original: Where would it end? Translations? Disnefications? Read-aloud bot renditions? By all means improve the tracking and reporting of additional contributory roles, but the original creation of a work is distinct and should be treated as such.

**Comment by seabelis** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/1808

**Comment by seabelis** [comment]
The difference between translations and adaptations, in short, is essentially that a translator is usually trying to remain as true to the original as possible where as an adaptation has been changed according to the adapter's individual objective.

**Comment by cdrini** [comment]
I agree with that definition; I think it's a good compromise. I like to think of it as: reading an edition of a work should approximately imply you've read _all_ editions of that work. They might differ in language/paratexts, but they should be essentially the same. E.g. I want the Fr/En editions of _The Count of Monte Cristo_ to be one work, but I don't want the Great Illustrated Classics edition (which is <300 pages) to be part of that work, because reading that does not imply you've read the 1200 page original.

**Comment by seabelis** [comment]
I think the original author should be credited at the work level rather than the edition level as the credit would apply to all editions, but does this risk improper merges?

**Comment by cdrini** [comment]
I'm not sure I follow; can you give a concrete example?

**Comment by seabelis** [comment]
How likely is https://openlibrary.org/works/OL16042299W/Winnie-the-Pooh to be merged with https://openlibrary.org/works/OL476641W/Winnie-the-Pooh?

**Comment by cdrini** [comment]
I don't think they should be merged (the disney one looks like it's only one story); I do think it's likely someone will accidentally merge them because they have the same title, thought :/

**Comment by seabelis** [comment]
No, they are not the same. I mean how likely is a bot to come along and merge them?

**Comment by seabelis** [comment]
The Disney one is based on the film, so twice removed in a way.

**Comment by cdrini** [comment]
Oh, I don't think there are any bots currently merging works; @hornc ?

**Comment by seabelis** [comment]
Also relevant for imported records.

**Comment by LeadSongDog** [comment]
If those roles are removed from the dropdown, the balancing change could be to provide a way to link the derivative work or edition as *Based on* one (or more) work or edition identifier. This would be useful for linking workbooks to corresponding textbooks; translations, condensations, adaptations etc to originals; collections, compilations, and twofers to individual works; scans, ocrs, eprints and re-keys to paper.

**Comment by seabelis** [comment]
Agreed. I have a larger issue regarding relationships. https://github.com/internetarchive/openlibrary/issues/1808

**Comment by tfmorris** [comment]
Enhancing the metadata model is a much bigger task than fine tuning the contributor roles. If we think pruning or editing the list of contributor roles will add significant value for our patrons, let's focus on what those edits should be. Otherwise, let's close this.

**Comment by seabelis** [comment]
I think the list does need to be pruned a bit. There are also contributor roles in other languages, which should probably be handled differently as well. I will not be able to revisit this thoroughly until end of November.

**Comment by seabelis** [comment]
Publisher should probably go as well, unless there's a specific reason it's in the contributors list. Perhaps to list an actual person's name? This information is sometimes included on an edition, but infrequently. Having it listed in the dropdown menu may be confusing for some as there is a field specifically for the publisher.

**Comment by guyjeangilles** [comment]
Assigning @hornc per slack discussions since this is meta data related.

**Comment by seabelis** [comment]
Old list:
roles:
- Author
- Adaptation
- Afterword
- Book Designer
- Contributor
- Colorist
- Copy Editor
- Cover Design
- Curator
- Decorator
- Designer
- Editor
- Epilogue
- Foreword
- Graphic Design
- Illustrator
- Indexer
- Introduction
- Narrator
- Photographer
- Printmaker
- Prologue
- Proofreader
- Screenplay
- Translator
- Technical Reviewer
- Text Design
- Typesetter
- '---'
- Accountability
- Acquisition Editor
- Additional Research
- Advisory Editor
- Agent
- Also known as
- Appendix
- Archival photos
- Art Director
- Arte final
- As told to
- Asesoria metodologica
- Assistant Editor
- Assisted by
- Associate Editor
- Associated book
- Author Photographer
- Bookbinder's label
- Botanical Illustrator
- Capa
- Cartographer
- Chapter Author
- Chef
- Chief editor
- Co-Author
- Collected by
- Collection dirigée par
- Colour Separations
- Commentary
- Commissioning Editor
- Compiler
- Composition
- Conductor
- Consulting Editor
- Consultant
- Contributeur
- Contributing artist
- Contributing Editor
- Coordenação editorial
- Coordinating author
- Copyright
- Corrección de estilo
- Cover and Text Design
- Cover Art
- Cover Art and Illustrations
- Cover Photographs
- Cover Printer
- Creator
- Crítico de Arte
- Dedicated to
- Development Editor
- Distributors
- Diagramación
- Diffuseur
- Director
- Direttore dello scavo
- Direzione scientifica
- Discípulo del autor
- Drawings
- Editor
- Editor-in-Chief
- Editorial
- Editorial Assistant
- Editorial Director
- Editorial Intern
- Editorial Team Leader
- Einbandentwurf
- Engineering Practice
- Engraver
- Explanatory notes
- Export Assistant
- Food Photographer
- Food Stylist
- From the Library of
- Frontispiece
- General Editor
- Glossary
- Graphic Layout
- Hersteller
- Home Economist
- Imprimatur
- Information Director
- Information Officer
- Interior Design
- Interior Photos
- Inspirador
- Interviewer
- Jacket Design
- Jacket Photo
- Jacket Printer
- Korrektor
- Language activities
- Lettering
- Librorum Censor
- Logo Designer
- Lyricist
- Map and Artwork
- Map Design and Cartography
- Meterological tables
- Musical Director
- Notes by
- Obra de arte de la portada
- Orchestra
- Owner
- Pagination
- Photograph
- Photo Editor
- Photo Scanning Specialist
- Photo Research
- Photo Library
- Poet
- Portrait
- Posfácio
- Preface
- Preparação
- Printer
- Producer
- Production Assistant
- Production Controller
- Production Coordinator
- Production Editor
- Project Coordinator
- Project Editor
- Project Team Leader
- Reading Director
- Recenzent
- Recipe Tester
- Recording Producer
- Recording Studio
- Redactor
- Redakteur
- Researcher
- Research Director
- Reviewer
- Revisão
- Revised by
- Script
- Secretaria editorial
- Selected by
- Senior Editor
- Soloist
- Sponsor
- Stylist
- Technical draftsman
- Technical Editor
- Tests and evaluations
- Thanks
- Titelillustration
- Translated for
- Typography
- Umschlagentwurf
- Vorauskorrektor
- Vorwort
- Web Programming & Design
- Woodcuts
- Writer
- Brand Manager
- Editorial Manager
- Inspirador
- Songs translated by
- Book Design
- Essayist
- Publishing Director
- Science Editor
- Lithography
- Series General Editor
- Editorial Board Member
- Publisher
- Board of Consultants
- Marketing Manager
- Managing Editor
- Scientific advisor
- Retold by
- interviewee
- Cover photograph
- Image editor
- Lektor
- Acquisitions Coordinator
- Computer Designer
- Series Design
- Map
- Typografische Gestaltung
- Premessa
- Epigraph
- Reviewers
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''
- ''

**Comment by seabelis** [comment]
New list:
roles:
- Adapted from original work by
- Additional Author (this edition)
- Afterword
- Collected by
- Commentary
- Compiler
- Consultant
- Foreword
- Editor
- Illustrator
- Introduction
- Narrator/Reader
- Notes by
- Revised by
- Selected by
- Translator
- '---'
- Accountability
- Acquisition Editor
- Acquisitions Coordinator
- Additional Research
- Advisory Editor
- Agent
- Appendix
- Archival photos
- Art Director
- Assistant Editor
- Assisted by
- Associate Editor
- As told to
- Author Photographer
- Board of Consultants
- Book Designer
- Brand Manager
- Cartographer
- Chapter Author
- Chef
- Chief editor
- Co-Author
- Colorist
- Colour Separations
- Commissioning Editor
- Composition
- Computer Designer
- Conductor
- Consulting Editor
- Contributing artist
- Contributing Editor
- Contributor
- Coordinating author
- Copy Editor
- Copyright
- Cover and Text Design
- Cover Art
- Cover Design
- Cover Photographer
- Cover Printer
- Creator
- Curator
- Decorator
- Dedicated to
- Designer
- Development Editor
- Diffuseur
- Director
- Distributors
- Drawings
- Editor-in-Chief
- Editorial
- Editorial Assistant
- Editorial Board Member
- Editorial Director
- Editorial Intern
- Editorial Manager
- Editorial Team Leader
- Engraver
- Epigraph
- Epilogue
- Essayist
- Export Assistant
- Food Photographer
- Food Stylist
- From the Library of
- Frontispiece
- General Editor
- Glossary
- Graphic Design
- Graphic Layout
- Home Economist
- Image editor
- Indexer
- Information Director
- Information Officer
- Interior Design
- Interior Photos
- interviewee
- Interviewer
- Jacket Design
- Jacket Photo
- Jacket Printer
- Language activities
- Lettering
- Librorum Censor
- Lithography
- Logo Designer
- Lyricist
- Managing Editor
- Marketing Manager
- Meterological tables
- Musical Director
- Orchestra
- Photo Editor
- Photographer
- Photo Library
- Photo Research
- Photo Scanning Specialist
- Poet
- Portrait
- Preface
- Prepared by
- Printer
- Printmaker
- Producer
- Production Assistant
- Production Controller
- Production Coordinator
- Production Editor
- Project Coordinator
- Project Editor
- Project Team Leader
- Prologue
- Proofreader
- Publishing Director
- Reading Director
- Recipe Tester
- Recording Producer
- Recording Studio
- Redactor
- Research Director
- Researcher
- Reviewer
- Science Editor
- Scientific advisor
- Screenplay
- Script
- Senior Editor
- Series Design
- Series General Editor
- Soloist
- Songs translated by
- Sponsor
- Stylist
- Technical draftsman
- Technical Editor
- Technical Reviewer
- Tests and evaluations
- Text Design
- Thanks
- Typesetter
- Typography
- Web Programming & Design
- Woodcuts
- Writer

**Comment by seabelis** [comment]
The problem of contributor titles in other languages remains an issue, but the non-English words have been removed from the list.
