### ISSUE TITLE
Remove "Description" header from issue/pr templates

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2239]
### Is your feature request related to a problem? Please describe.
It's kind of evident that the first thing is the description, so let's drop the heading. It'll also clean up the issue tooltips, which now always begin with the word "Description". Let's also move the "Closes: blah" text to the top so that it's visible in the tooltip (like below!)

![image](https://user-images.githubusercontent.com/6251786/62068481-18f78a00-b204-11e9-8322-527307dd4425.png)

### Describe the solution you'd like
- [ ] Move "Description" to an HTML comment wherever it appears
- [ ] Move the "Closes: XXX" in PR templates text to the top of the description.

**Comment by imnotjames** [comment]
@cdrini since you submitted - just want to make sure that you're happy with the changes :)
