### ISSUE TITLE
Consolidate duplicate toggleText methods

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2243]
### Description
There are 2 identical `toggleText` methods, one in `utils.js` and one in `jquery.toggleText.js`. Let's consolidate these.

### Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
I'm wondering if we can remove both...
There is one usage of this function in openlibrary/plugins/search/templates/advanced_search.html

```
                    <a href="javascript:;"  onClick="\$(this).toggleText('more','less');jQuery('div.$header').toggle();false" class="orange">more</a></span>
```

Is this template even being used?
openlibrary/templates/work_search.html seems to be what's being used on searches and I can't find a way to trigger the above template...
