### ISSUE TITLE
Carousels no longer show titles and authors for items without covers (Regression)

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2247]
### Description

Example URL https://openlibrary.org/subjects/industrial_relations_--_great_britain.

For editions withotu covers, it is impossible to tell what the book is without mouse hovering on any carousel , e.g. Subject carousels, and the 'You might also like' ones.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/905545/62171000-909ef380-b381-11e9-8ecd-b4242125057b.png)

### Expectation

The title and author should be shown for books without cover images, similar to how the cover is displayed on the editions details page:
https://openlibrary.org/books/OL22368042M/Employment_relations_in_industrial_society

![image](https://user-images.githubusercontent.com/905545/62171085-e7a4c880-b381-11e9-8fb3-67246a91973b.png)

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Stakeholders

@jdlrobson
 @tabshaikh ?
@mekarpeles ?

**Comment by tfmorris** [comment]
And, of course, hovers aren't really a thing on touch screens making it doubly frustrating for mobile users.

**Comment by jdlrobson** [comment]
Yeh this seems like a big design flaw. It's always been this way though... right?

**Comment by jdlrobson** [comment]
To achieve 
https://openlibrary.org/books/OL22368042M/Employment_relations_in_industrial_society

This would be an exercise in breaking down the Book cover component:
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#book
static/css/components/book.less

and consolidating with the undocumented illustration component with:
static/css/components/illustration.less

I'd hope any refactor here would result in less code.

This is quite a bit of work, that I can't commit to right now. It's important work, but given this has been the case for some time (not a regression) I've dropped the priority.

**Comment by hornc** [comment]
@jdlrobson I'm pretty sure this is a regression, I'm not sure when it was introduced though.

**Comment by cdrini** [comment]
I think this was introduced when we switched to slick for our carousels.

**Comment by tfmorris** [comment]
I agree that it's a regression, but don't have any insight into what front-end change it's correlated with.

**Comment by cdrini** [comment]
I think your proposed fix sounds reasonable. Consolidate the templates and use the same logic as on the work's page (if it has a cover, display it; if it doesn't, display the title/author).

Note the wayback link shows the case from _broken_ image links; the discussion here is for when the book simply doesn't have an associated cover.

**Comment by cdrini** [comment]
(Note this is what I'm seeing on that wbm link:)
![image](https://user-images.githubusercontent.com/6251786/63955765-3e6df280-ca53-11e9-98a2-9d5488d1156c.png)

**Comment by jdlrobson** [comment]
While doing some code archaeology, I've found some dead (brittle) code that probably relates to this. I'll see if I can restore it at some point in the future. Seems if a cover was absent we'd hide the cover via JS and reveal a hidden blank cover element instead. Since we've moved to Slick none of these templates are active.

```
export function bookCovers(){
    $('img.cover').error(function(){
        $(this).closest('.SRPCover').hide();
        $(this).closest('.coverMagic').find('.SRPCoverBlank').show();
    });
}
```

```
    <div class="SRPCoverBlank">
        <div class="innerBorder">
            <div class="BookTitle">$:macros.TruncateString(title, 70)
                <div class="Author">$:macros.TruncateString(author_names, 30)</div>
            </div>
        </div>
    </div>
```

**Comment by jdlrobson** [comment]
Let's fix this as part of #2084

**Comment by cdrini** [comment]
I think this should be solved separately regardless of the decision on #2084 ; displaying "blank" covers isn't useful. (I'm also personally not completely sold on the proposal on #2084 as it stands.)

**Comment by jdlrobson** [comment]
I was a little confused by the context for reopening. After investigating this some more I assume this relates to the slack conversation between @mekarpeles and Brittany. For those who missed it, apparently this fix is not applying to:
https://openlibrary.org/subjects/in_library#ebooks=true&sort=edition_count
when you click right arrow.

The carousel item is rendered on the server side so this is likely an issue in the template.

```
div class="book carousel__item">
  <div class="book-cover">
    <a href="/works/OL55532W">
      <img class="bookcover" loading="lazy"
        width="130" height="200"
        title="The three sisters by Anton Pavlovich Chekhov"
        data-lazy="//covers.openlibrary.org/b/ia/t-M.jpg?default=https://openlibrary.org/images/icons/avatar_book.png"/>
    </a>
  </div>
  <div class="book-cta"><a class="cta-btn cta-btn--available borrow-link" href="/borrow/ia/threesistersdram00chek?ref=ol" data-ol-link-track="subjects" title="Borrow The three sisters"
    data-key="subjects" data-ocaid="threesistersdram00chek">Borrow</a></div>
</div>

```
I suspect it only applies to carousel items which mark their images as lazy loaded. 
I suspect this templating code would benefit from some refactoring as part of this fix. The very fact that there is a different code path for lazy loaded items is a bad code smell! :)

**Comment by jdlrobson** [comment]
After some investigation @mekarpeles this bug has nothing to do with the new issue. I've raised #3393 to describe it better.
