### ISSUE TITLE
Access-Control-Allow-Origin missing for ?output=json

### ISSUE THREAD

**Issue by fijimunkii** [internetarchive/openlibrary#226]
https://archive.org/help/json.php has instructions on using the ```?output=json``` query parameter. This works great, but not when I try to use the api in my apps. The issue is that Access-Control-Allow-Origin is missing for Archive.org

OpenLibrary has this feature enabled. Here is a jsfiddle showing that OpenLibrary works while Archive.org does not http://jsfiddle.net/q9fVr/3/

**Comment by chrisguttandin** [comment]
Are there any news regarding this issue?

**Comment by ryanfb** [comment]
As a heads up to anyone else struggling with this issue, you can access the OpenLibrary JSON metadata for an Internet Archive book identifier at the URL:

    http://openlibrary.org/ia/#{identifier}.json

As I had no success with e.g.

    http://openlibrary.org/api/get?key=/ia/#{identifier}

Or other ways of programmatically finding the redirect using the API in an AJAX call.

**Comment by hornc** [comment]
I think this is an issue with archive.org rather than Open Library. OL seems to be doing the correct thing here. The jsfiddle is still active and gives the results as reported.

@bfalling , Is there a way to move this to an appropriate place for archive.org as it still seems to be current?

**Comment by mekarpeles** [comment]
Closing this issue and adding it to our (unfortunately) private archive.org tracker. Will try to update this issue when it's been addressed on archive.org side.

**Comment by webmaven** [comment]
Why does archive.org keep a private issue tracker? I mean, I understand why this is good practice for security-related issues, but otherwise it's a head scratcher.

**Comment by mekarpeles** [comment]
@webmaven, this likely isn't the most appropriate place for me to respond, but the best reason I can give is that historically (10+ years ago), archive.org emerged from the Internet Archive's petabox (core infrastructure -- i.e. hardware cluster management) technology. As a digital archive and library (far before such things as AWS) there didn't exist terribly well formed standards about how highly scalable and performant software should be architected (e.g. MVC, or even separation between systems level orchestration and service development for that matter). In many cases, IA had to work with partners to help pioneer their own standards (OAI-PMH, opds, warcs, etc). Taking into considering the reality of these circumstances, having a public tracker would make it difficult for engineers to individually track and address concerns which happen to span both Internet Archive specific infrastructure and the many services of archive.org. And for these legacy reasons, the tracker remains internal. 

Fortunately, in the past few years, there have been a myriad of progressive changes, including the use of docker and ansible provisioning, a move to git, monitoring and logging pipelines, continuous integration and deployment. This all said, we have 15+ years of technology which currently works really well which partners and users all over the world rely on staying the same and so changes take time. I can only speak for myself, but it would be nice if archive.org had a public tracker and volunteers were more easily able to make pull requests. It's been a topic of conversation, I thank you for the question, and apologize for what might be a frustrating answer!

**Comment by webmaven** [comment]
Hmm..
> having a public tracker would make it difficult for engineers to individually track and address concerns which happen to span both Internet Archive specific infrastructure and the many services of archive.org. And for these legacy reasons, the tracker remains internal.

I don't quite see how the difficulty or ease of tracking issues across multiple domains of infrastructure and services changes based on the public visibility of the tracker...

>  it would be nice if archive.org had a public tracker and volunteers were more easily able to make pull requests.

Those would both be nice, but just to be clear, those two issues are largely orthogonal to each other. Even without the ability to contribute changes to the code, there is quite a bit of value in having a publicly visible issue tracker (not least of which is that it would provide a more-appropriate venue for discussions such as this).

**Comment by mekarpeles** [comment]
@webmaven, I've temporarily created a placeholder archive.org project at https://github.com/ArchiveLabs/archive.org (our community run Labs program) and I can do my best to triage them as they're reported. Feel welcome to continue discussion by opening issues there (so we can keep the OpenLibrary issues focused).
