### ISSUE TITLE
clicking 'Create new list' twice creates two identical lists

### ISSUE THREAD

**Issue by equivalentideas** [internetarchive/openlibrary#227]
The application should stop duplicate requests being made from the form once input has been submitted.

Should be a quick fix and must be creating tasks for admins deleting dupe lists—or there must be a bunch of duplicate content.

**Comment by ahvigil** [comment]
#252 fixes this by disabling the form when submitted and re-enabling it after the request is complete

**Comment by hornc** [comment]
I have tested this PR locally and the add-list functionality seems to be good, so I think this can be merged, however I haven’t been able to reproduce (using the current master) the problem it claims to fix locally  -- the page refreshes too fast and I don't seem to have time to double click to cause the problem.

**Comment by equivalentideas** [comment]
Thanks @hornc . Could throttling your browser connection with dev tools help? https://css-tricks.com/throttling-the-network/

**Comment by hornc** [comment]
Thanks for the testing tip @equivalentideas! I was able to reproduce the original issue and confirm this fixes it.

**Comment by equivalentideas** [comment]
No worries @hornc , thanks for your work on this great project :saxophone:

**Comment by hornc** [comment]
Fixed with tested and merged PR https://github.com/internetarchive/openlibrary/pull/252
@gdamdam can you please close this issue (I thought I could close issues, but I can't! :) )
