### ISSUE TITLE
consider moving sitemap script to root scripts dir

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2276]
### Is your feature request related to a problem? Please describe.

The currently used sitemaps script lives in https://github.com/internetarchive/openlibrary/tree/master/scripts/2009/01/sitemaps

Which looks like an archived script. 

### Describe the solution you'd like

Suggestion: create openlibrary/scripts/sitemaps and move the currently used scripts there.

**Comment by cdrini** [comment]
100% agree. If this is actively used, it should _definitely_ not be archived :P
