### ISSUE TITLE
Local environment displaying non-existant works in carousels/search

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2278]
### Description
The local environment lists works which in the carousels/search results which throw "404 - Page Not Found" errors.

### Relevant url?
- Carousels here: http://192.168.99.100:8080/
- Search results here: http://192.168.99.100:8080/search?q=title%3A*&mode=everything
- Sample error: http://192.168.99.100:8080/works/OL5096778W

### Expectation
Only books in the database should be accessible via carousels/search.

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Firefox 68
- **Operating system?** Windows 10

### Proposal & Constraints
It looks like there's some live querying happening somewhere. We should strive to have the local dev environment be entirely functional even when there's no internet available, so let we should spoof/mock whatever queries are happening to return books from the local database.

**Comment by BrittanyBunk** [comment]
Good someone mentioned it. This does keep happening. Like this book appears: https://openlibrary.org/books/OL26571069M/Critical_studies_in_the_Cynewulf_group._-/resolve. It shoudn't be in the carousel.

**Comment by LeadSongDog** [comment]
That edition was named https://openlibrary.org/books/OL26571069M/Critical_studies_in_the_Cynewulf_group._- 
I assume searching for fails to resolve because something in the trailing “. _-“ invalidates the url

**Comment by cdrini** [comment]
Ah; the issue is the link is being formed incorrectly. Created an issue here: https://github.com/internetarchive/openlibrary/issues/2506

**Comment by cdrini** [comment]
(That's different from this issue; this issue applies only to the environment that developers use, not to the public, production website).

**Comment by cdrini** [comment]
Closing this one; this happens when you copydocs books into openlibrary, they stick around in the solr between restarts even they they do not stick around in db between restarts
