### ISSUE TITLE
Duplicate the compare button on history pages

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2279]
### Is your feature request related to a problem? Please describe.
For records with long histories, it's annoying to scroll all the way to the bottom of the page to the compare button. 

Like https://openlibrary.org/people/vivisoesanty/lists/OL99633L/Authors_for_children's_books?m=history :
![image](https://user-images.githubusercontent.com/6251786/62560838-e543e200-b84b-11e9-8f21-d03775b277bd.png)

### Describe the solution you'd like
We should display a compare button also at the top, like Wikipedia does:

![image](https://user-images.githubusercontent.com/6251786/62560904-01478380-b84c-11e9-9e1b-79223f2b0a3d.png)

**Comment by tapaswenipathak** [comment]
Hi @cdrini: Can you please assign the priority as well, I would PR.

**Comment by cdrini** [comment]
Sure! I'd say this is priority normal. Go for it :)

**Comment by ManishAradwad** [comment]
Which HTML files am i supposed to edit for this?? Also how can i generate the webpage, is there a command like `make html` or should i just add the button in html file and submit a pr??

**Comment by jdlrobson** [comment]
@cdrini can you review the patch from @ManishAradwad - code-wise looks fine but I can't speak/review for the goal.
