### ISSUE TITLE
First Sentence field not editable

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#228]
This was first reported in 2010, but it appears that the Launchpad bug never got transferred here. https://bugs.launchpad.net/openlibrary/+bug/623499

In addition to the book in the original bug report below, another example is:
https://openlibrary.org/books/OL23818172M/Harry_Potter_and_The_Sorcerer's_Stone
which has a vandalized first_sentence field which is uncorrectable.

If the edit functionality can't be restored, perhaps the field should just be removed from the display UI.

------- original from https://bugs.launchpad.net/openlibrary/+bug/623499 -----------
> It seems that the field "First Sentence" is not editable, if it has been added with the old OL catalog/interface.
>
> http://openlibrary.org/books/OL3958441M/Herbal_Vade_Mecum
> 
> First Sentence: "Sample Chapters: ACEROLA Other Common ..."
> 
> Add Excerpts: Empty.

**Comment by hornc** [comment]
@tfmorris It looks like only admins can edit the First Sentence. I've moved some of that content (I had to truncate it to fit) into the excerpt field. https://openlibrary.org/books/OL3958441M/Herbal_Vade_Mecum Is that better? The original large summary chapters text is still available in the edit history if you want to add more, or re-arrange it.

**Comment by bfalling** [comment]
@tfmorris: Is this okay to close?

**Comment by tfmorris** [comment]
@bfalling Has it been fixed by either hiding the field in the UI or restoring the edit functionality?

**Comment by jessamynwest** [comment]
I really suggest allowing this to be open to the public. Anything admin-only bottlenecks support requests. My future vision of OL has a queue where we can check this stuff for abuse, but otherwise let users interact with it (similar publisher's names)

**Comment by tfmorris** [comment]
My first preference would be the same as @jessamynwest but I'd be happy having the field just hidden or algorithmically derived as well (provided we could find a reliable algorithm).

To keep ourselves honest, though, let's look at the context here. This bug was reported in 2010. I transferred it here two years ago at the end of 2014. We're triaging it now because it's an "anniversary" year.

If we fixed the bug tomorrow, what impact would that have on Launchpad user "Patrick" who reported it in 2010. Are they still around to care? What effect does a 6 year lag between report & triage have on OpenLibrary community building efforts?

**Comment by bfalling** [comment]
@tfmorris: We are not fixing issues to please the users who reported them but to make Open Library better.

As to your repeatedly expressed frustrations about the lack of activity and support between half a decade ago and now, I'm really sorry about that, but as someone newly on-board and newly in charge of OL, there's really nothing I can do about that, other than to try start fresh from where we are right now and try to make a positive difference. I welcome and appreciate your efforts to join me in that.

**Comment by seabelis** [comment]
I'm wondering what ever became of this. It is possible to add an excerpt and indicate it is the first sentence, however, one still must comment that it is the first sentence for that to be indicated on the page.

**Comment by seabelis** [comment]
![fullscreen capture 342019 55835 pm bmp](https://user-images.githubusercontent.com/17739465/53749320-69fa9080-3ea7-11e9-8272-f14f041189bf.jpg)
The checkbox should be removed then. It does nothing. It is still necessary to state that it is the first sentence in the text box.

**Comment by LeadSongDog** [comment]
I think there's no real reason it should be admin-only. Anyone should be able to remove an excerpt.

**Comment by seabelis** [comment]
Removing the excerpt isn't the issue. Adding the first sentence--or at least designating it as such via the checkbox--is the issue. Checked or not, one must comment that it is the first sentence otherwise it is not specified as such.

**Comment by seabelis** [comment]
I take it back, removing an excerpt is also an issue. I can remove it, but then it just displays on the work page in larger text.

**Comment by guyjeangilles** [comment]
@hornc What's stopping us from making the first sentence editable by any registered user?

**Comment by hornc** [comment]
@guyjeangilles nothing, it looks like we are all agreed, and the relevant code is highlighted above, someone just needs to remove that check and ensure the admin only styles are removed. 

It would be lovely to have a front-end volunteer pick this up. I have added good first issue tags and UI.

**Comment by mekarpeles** [comment]
A slight modification on @LeadSongDog's comment above, here is the region:

https://github.com/internetarchive/openlibrary/blob/7195f181742af7389843f275eefb2e675055b727/openlibrary/templates/books/edit/edition.html#L662-L674

The first line `$if ctx.user and ctx.user.is_admin():` (the admin check) needs to be removed
