### ISSUE TITLE
Recent-edits interface is not showing recent new imports by ImportBot or CleanupBot

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2297]
### Description
https://openlibrary.org/recentchanges/add-book?page=1#bots shows very little bot import activity.

I know https://openlibrary.org/people/horncBot has imported some new items from SFPL MARC records within the last few months.

ImportBot https://openlibrary.org/people/ImportBot especially is constantly importing new books.

This relates to the planning doc at https://github.com/internetarchive/openlibrary/wiki/Open-Library-Importing where I am trying to gather ongoing metrics around importing.

### Expectation

Imports from these bots should appear on the recent add-books edit bots tab. This will indicate that our catalog is being updated, and provide an interface for users to QA recent imports.

### Stakeholders
@hornc  @mekarpeles

**Comment by hornc** [comment]
Ok, there might be something strange and sporadic going on here, this is what I saw that made me raise the issue:
![image](https://user-images.githubusercontent.com/905545/62993354-11dea600-beab-11e9-8380-9f2338bceadf.png) which shows very out-of-date edits.

but on one refresh I did see a  large list of ImportBot edits, which is looked in line with my expectations. I'm going to investigate how to reproduce the different page results. It would be helpful for someone else to take a look at the recent changes page and report back whether they see this problem, or the latest edits.

**Comment by hornc** [comment]
Have figured it out: 

Viewing https://openlibrary.org/recentchanges#bots shows _all_ edits by bots, which will correctly list all books imported by bots, if they have happened recently.

Viewing https://openlibrary.org/recentchanges/add-book#bots shows all edits made by bots using the add-book UI endpoint, and not anything imported using the more powerful import API

This is still an issue, as it is misleading, and hides the majority of the bot imports, and the add-book endpoint is deprecated for bot imports. If we are trying to get more visibility on what we are importing and feedback on what needs to be improved, we need to correct this.

**Comment by cdrini** [comment]
Ok, so the fix is to make the imports show up in "Books Added", right? Is this still `Priority: High`?

**Comment by hornc** [comment]
@cdrini re. priority, probably not -- I put that priority there before I understood the cause. I thought the problem was more fundamental that it is. I'll remove it.

**Comment by hornc** [comment]
Related -- there is an admin interface /admin/imports that also claims to show imports, but doesn't give the full picture. It only shows edits by ImportBot, and graphs data available from ImportBot's user page.

I'd not worry about this, phrasing this issue as a feature: Anyone should be able to get an indication of number of recent imports from all relevant sources, and be able to check the quality of the added items.

This will help improve the ongoing efforts to improve the import process -- currently it is difficult to even locate what has been recently imported to judge whether we are doing a good job.

**Comment by hornc** [comment]
More investigation shows how to make added books show up on https://openlibrary.org/recentchanges/add-book#bots

Looks like `web.ctx.site.save_many` takes an `action` param, `edit-book` or `add-book`
e.g. https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/addbook.py#L344

**Comment by hornc** [comment]
PR #2602 will hopefully address the recent-changes list view issues.

A better place to view the ongoing import process is https://openlibrary.org/stats

and I have also PR #2618 to label the graphs better.
