### ISSUE TITLE
Investigate fa95544 for dead code red flags

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2299]
### Description
This commit removed a number of Python `undefined` variable references: https://github.com/internetarchive/openlibrary/commit/fa95544d2ac7639ed8c8d6a397502523b050e887 . Some of these deletions look like dead code red flags; these should be investigated and removed.

Do in small chunks; no giants PRs, svp.

Related to #1684

### Stakeholders
@cclauss

**Comment by RayBB** [comment]
@cdrini is this still an issue? I've poked around a bit at the code but don't see anything that looks too worth digging into.
Many of the files have long since changed.
