### ISSUE TITLE
/admin/imports fails to load locally

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2316]
### Description
Follow up on conversation between myself, @cdrini and @hornc 
https://internetarchive.slack.com/archives/C0ETZV72L/p1565797192464100

When visiting http://localhost:8080/admin/imports I am unable to render the page.

debug=true shows the following stack trace:
```
Python | /usr/local/lib/python2.7/dist-packages/DBUtils/SteadyDB.py in tough_method, line 604
-- | --
GET http://localhost:8080/admin/imports
````

Questions:
1) Does https://openlibrary.org/admin/imports work?
2) Is the page still relevant
3) How can we get the page to render locally?

### Evidence/Screenshot
| On Local | On Prod |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/6251786/63545689-036d3b80-c4f6-11e9-8a8f-b0205bda2b55.png) | ![image](https://user-images.githubusercontent.com/905545/63562591-50164c80-c5b2-11e9-9fff-e61b5b21e2c4.png) |

### Relevant url
http://localhost:8080/admin/imports ; https://openlibrary.org/admin/imports

### Stakeholders
@cdrini @hornc

**Comment by jdlrobson** [comment]
Is it possible we just need to create a database table import_items ?

**Comment by cdrini** [comment]
@hornc could you add a picture of what this page looks like on prod?

**Comment by hornc** [comment]
@cdrini 
![image](https://user-images.githubusercontent.com/905545/63562591-50164c80-c5b2-11e9-9fff-e61b5b21e2c4.png)

**Comment by cdrini** [comment]
Thanks! Added to the desc.

**Comment by guyjeangilles** [comment]
What else needs to be done considering #2326 is merged?

**Comment by jdlrobson** [comment]
I still can not visit this page locally seeing:
```
/openlibrary/openlibrary/templates/admin/imports.html: error in processing template: ProgrammingError: relation "import_item" does not exist LINE 1: SELECT count(*) as count FROM import_item WHERE status='pend... ^ (falling back to default template)
```
I am not the right assignee for this bug...

**Comment by cclauss** [comment]
@cdrini I can replicate on Python 3.  This looks like the database SELECT method is incorrect.

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/imports.py#L92-L93
