### ISSUE TITLE
Remove unused plugins: copyright, scod, heartbeat, theme and mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2317]
### Description
https://github.com/internetarchive/openlibrary/tree/master/openlibrary/plugins

While combing through the frontend I came across some plugins (and TEMPLATES) that do not seem to be enabled anywhere. Those are: copyright,heartbeat, scod, theme and mobile (there may be others but these ones i can confirm). I wasted a lot of time trying to cleanup the frontend in these files. I'd rather not waste this time ago.

These were added around 10 years ago, and have only recently seen linting improvement.
If these are not enabled in production can they be removed? It would make the codebase a lot easier to work with if we cleaned out things that are no longer active.

scod = Scan on Demand plugin
mobile = a separate mobile site. We don't have one.

### Evidence / Screenshot (if possible)
When I remove these folders in the plugins folder nothing breaks. The site continues as it always has but with less lines of code.

### Expectation
We should not be wasting time having to sift through files that are unused when trying to do things like revamp frontend and backend architecture.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Stakeholders
@cclauss and @mekarpeles

**Comment by cclauss** [comment]
Highly supportive.  There are no bugs in code that does not exist.  ;-)

**Comment by guyjeangilles** [comment]
@mekarpeles @hornc I'm not sure who should be assignee to this issue, but I assumed it would be one of you two. Let me know if your thoughts.

**Comment by tfmorris** [comment]
I don't know anything about these plugins, but it seems like if there were a PR per plugin that removed it, they could be reviewed individually and cleaned up. ie make this a series of PRs instead of an issue.

**Comment by guyjeangilles** [comment]
@jdlrobson Since it sounds like you tested removing these unused plugins would you like to be assignee for this issue?

Note: being assignee doesn't necessarily mean you are responsible for doing the work. From the Managed Label Wiki:
>At submission and prior to triage, the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

**Comment by jdlrobson** [comment]
It would be better to assign this to someone who knows how the Python plugins system works and that's not me.

**Comment by guyjeangilles** [comment]
@cclauss @salman-bhai Since you are the Python3 leads, are either one of you willing to be assignee for this issue/make PRs for each plugin per @tfmorris suggestion?

**Comment by cclauss** [comment]
Not me, sorry!  We have 70 days until Python 2 EOL and the time that I can dedicate to web.py, Infogami, and Open Library will be focused on compatibility with Python 3.  I am supportive of this effort but will not directly engage.

**Comment by tfmorris** [comment]
I'm not sure why ever issue needs an assignee. We have way more issues than people to work on them all the employees are being tasked to work on things just for show, so they're not even available.

I think we should adjust the guidelines to acknowledge that there are some things which are important, but not assigned to anyone.

**Comment by guyjeangilles** [comment]
@tfmorris

This issue isn't the best place to hold this discussion, so I'll respond to your comment on #2028

**Comment by tfmorris** [comment]
I don't think something can be both a refactoring and a bug. They seem mutually exclusive. This seems to clearly be a refactoring. It's also exceedingly unlikely that a refactoring, particularly dead code removal, would be considered high priority.

**Comment by guyjeangilles** [comment]
Assigning @cdrini per slack discussions since he's doing a lot of the refactoring

**Comment by mekarpeles** [comment]
Going to move to @cclauss to equalize our `Lead` load and lowering the priority

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/2317#issuecomment-545270829

not every issue needs an assignee, but it makes sense in our new world #4282 for every issue to have a Lead (a point capable of prioritizing, reviewing, answering questions + fielding comments on issues, finding others to help out, and helping them get setup / find the right files).

**Comment by Yashs911** [comment]
@cclauss I would like to work on this issue. Any starting point?

**Comment by cclauss** [comment]
Was this issue closed in #2318 er what?

**Comment by cclauss** [comment]
@Yashs911 perhaps search on each of the five keywords and see if there is any cruft lying around in our codebase.  If so, separate PRs for each keyword found please.

**Comment by Yashs911** [comment]
@cclauss Yes, so we can close this issue, and if you are free, I can work on #3483

**Comment by Yashs911** [comment]
> @Yashs911 perhaps search on each of the five keywords and see if there is any cruft lying around in our codebase. If so, separate PRs for each keyword found please.
@cclauss I just found some old comments and few keyword
![image](https://user-images.githubusercontent.com/64412143/105577877-53fb5f00-5da2-11eb-96bf-3ed307653135.png)
![image](https://user-images.githubusercontent.com/64412143/105577898-742b1e00-5da2-11eb-9c6b-aaca44086edc.png)

**Comment by cclauss** [comment]
Cool.  Let’s keep the separate from #3483 because I think we can land these mods quickly whereas the “unnecessary imports” require careful review because of import side effects which flake8 can not detect.

**Comment by Yashs911** [comment]
@cclauss Okay, So should I create a PR and remove all these comments and references?

**Comment by cclauss** [comment]
On PR for each keyword (copyright, scod, heartbeat, theme, mobile) found.

**Comment by Yashs911** [comment]
@cclauss Should I remove this folder: https://github.com/internetarchive/openlibrary/tree/master/scripts/2009/01/scod_stats
