### ISSUE TITLE
Adding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by tapaswenipathak** [internetarchive/openlibrary#2319]
### Is your feature request related to a problem? Please describe.

Suggestion.

### Describe the solution you'd like
Hey folks: can the project has https://github.com/internetarchive/iaux/blob/master/CODE_OF_CONDUCT.md added in the most contributed repository of internetarchive GitHub org?

### Proposal & Constraints
https://github.com/internetarchive/iaux/blob/master/CODE_OF_CONDUCT.md

### Additional context
None.

**Comment by cdrini** [comment]
Related resource: https://opensource.guide/code-of-conduct/

**Comment by cdrini** [comment]
Just a note; as we talked about in the call, this would require some work from the maintainers' side to make sure we have processes to enforce a Code of Conduct. @brad2014 Also said that it would need approval from Internet Archive's HR team. That being said, I think this is a terrific a great idea :)

**Comment by brad2014** [comment]
Other resources: https://www.contributor-covenant.org/ 
A large list of projects and their coc's: https://opensourceconduct.com/projects.html
and on enforcement: https://medium.com/mozilla-open-innovation/how-were-making-code-of-conduct-enforcement-real-and-scaling-it-3e382cf94415

**Comment by tapaswenipathak** [comment]
Hi folks: How are things w/ the document? I would love reading the final document.

**Comment by tapaswenipathak** [comment]
Hi folks: How are things w/ the document? I would love reading the final document?

**Comment by cdrini** [comment]
Hey! This is still stationary; we've got a few other things on our plate right now before we work to set this up, but will get to it when we get the chance! Note this is more complicated than copying a file over; I think it's important to get this right:

> A code of conduct that isn’t (or can’t be) enforced is worse than no code of conduct at all: it sends the message that the values in the code of conduct aren’t actually important or respected in your community.
— Ada Initiative

**Comment by tapaswenipathak** [comment]
On Tue, 3 Sep 2019, 19:21 Drini Cami, <notifications@github.com> wrote:

> Hey! This is still stationary; we've got a few other things on our plate
> right now before we work to set this up, but will get to it when we get the
> chance! Note this is more complicated than copying a file over; I think
> it's important to get this right:
>
> A code of conduct that isn’t (or can’t be) enforced is worse than no code
> of conduct at all: it sends the message that the values in the code of
> conduct aren’t actually important or respected in your community.
> — Ada Initiative
>
>
Hey! I agree. Feel free doing when time permits.

**Comment by guyjeangilles** [comment]
We should start working on this again @mekarpeles
