### ISSUE TITLE
Correctly pluralize edition number on Works page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2330]
### Description

On works page which only have 1 edition, the grammar is wrong and says, "1 editions" instead of 1 edition

### Evidence/Screenshot
![image](https://user-images.githubusercontent.com/6251786/63542240-ed5b7d00-c4ed-11e9-8f8a-742cfc3dd0ed.png)

### Relevant url?
All works, but e.g. https://openlibrary.org/works/OL8048917W/Adiamante

### Proposal & Constraints

See:
https://github.com/internetarchive/openlibrary/blob/fedbb9b9cf00ff50f05018912c59867faa4f63cf/openlibrary/templates/type/work/view.html#L22-L23 and https://github.com/internetarchive/openlibrary/blob/fedbb9b9cf00ff50f05018912c59867faa4f63cf/openlibrary/templates/type/work/view.html#L66

**Comment by tfmorris** [comment]
Neither implementation will internationalize correctly.

p.s. I updated the original with permalinks so the code gets rendered in-line.

**Comment by mekarpeles** [comment]
Thanks @tfmorris, do you have a recommendation around internationalization? Does it need to be wrapped in `$_()`?

**Comment by guyjeangilles** [comment]
Fixed in #2474 . It looks like it's wrapped in $_() so internationalization should be less of a problem. Closing.

**Comment by tfmorris** [comment]
Pluralization support is described here: http://babel.pocoo.org/en/latest/api/plural.html

Using >1 isn't correct, even for English, because we use 0 editions.

**Comment by guyjeangilles** [comment]
I've reopened and edited the title of this issue to reflect Tom's comment
