### ISSUE TITLE
'No Ebook Available' confusing users

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2346]
### Is your feature request related to a problem? Please describe.
Some users are confused about the difference between an ebook on OL and an ebook format in general. I think the term ebook has been used on OL from the start to designate the items in the library, so I'm not sure changing this is the right action to take. I'm posting this to start a discussion on the topic.

### Additional context
I've received user emails noting that the "No ebook available" statement should be removed for certain titles that are available in ebook format, just not on OL.

**Comment by seabelis** [comment]
Received another email about this.

**Comment by guyjeangilles** [comment]
I believed we talked about this on the November 21st Community Call. Changing the text to "No lend-able copy available" would be an easy fix

**Comment by hornc** [comment]
Suggested fix: Change: "No ebook available" to "No lendable copy"  (for brevity)
