### ISSUE TITLE
Accounts made before Reading Log have issues w/ their profile pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2347]
### Description

https://openlibrary.org/people/breity?debug=true

We need to check that `settings` exist and default `settings.get('public_readlog', 'no')`
```
/opt/openlibrary/deploys/openlibrary/fedbb9b/openlibrary/templates/type/user/view.html in __template__
        $for url in page.website:
            <a href="$url" rel="nofollow">$url</a><br/>
        </p>
    $:sanitize(format(page.description))
    <h2>Reading Log</h2>
    $if settings.get('public_readlog') == "yes": 
```

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by cbolgiano** [comment]
I'd be happy to work on this one.

**Comment by cbolgiano** [comment]
It seems that the default for `public_readlog` is already no based on what I see here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/models.py#L540

I can still add the check to make sure `settings` is populated before the call to `get` though.

**Comment by cbolgiano** [comment]
I see what you mean now by checking for `settings.get('public_readlog', 'no')` now.  We want to check for `settings.get('public_readlog', 'no') == 'yes'` instead of `settings.get('public_readlog') == "yes"`.  Will make that change and have a PR out soon.  If this is not the case please let me know.
