### ISSUE TITLE
Subtitle excluded from title search

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2355]
### Description
Searching for a work using only its subtitle produces no results.

### Relevant url?
https://openlibrary.org/search?q=title%3A+%22Le+Grand+Livre+des+cr%C3%A9atures%22&mode=everything should include https://openlibrary.org/works/OL17605693W/Harry_Potter in results.
### Expectation

Sometimes the subtitle is the most important part of the title. This should be searchable when title field is specified for search.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 76.0.3809.100 (Official Build) (64-bit)
- **Operating system?** macOS Mojave 10.14.6

**Comment by tfmorris** [comment]
The five title related fields are:
* title
* subtitle
* alternative_title
* alternative_subtitle
* title_suggest (a copy of title with different indexing)

The first four should probably all be included in title searches.

**Comment by seabelis** [comment]
The last three are not accessible via the form?

**Comment by cdrini** [comment]
The fields stored on solr are slightly different from the fields accessible from the form; the fields available from the form aren't publicly defined anywhere (I don't think).

**Comment by tfmorris** [comment]
There would still only be a single user visible form field for entry (ie "Title"), but internally it would search all four relevant fields for matches.

**Comment by seabelis** [comment]
So can each edition title be an alternative title at the work level?

**Comment by seabelis** [comment]
Or better yet [edition_title: edition_subtitle].

**Comment by cdrini** [comment]
I think that's what the field was created for, but whether it does that is an open question :P

**Comment by seabelis** [comment]
I think it doesn't since search by title only sees the work's title.

**Comment by guyjeangilles** [comment]
Making this a sub-task of #789. Assigning @cdrini per slack discussions

**Comment by tfmorris** [comment]
This doesn't appear to have anything to do with #789, but is related to #889. The given search string is an **edition** subtitle, not the subtitle of the work. The work isn't found for the same reason that title searches on any edition title, subtitle, etc don't work.

**Comment by seabelis** [comment]
This appears to be resolved.
