### ISSUE TITLE
Replace slick copy with npm version

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2362]
### Description
We're currently storing a copy of slick 1.6.0 in `vendor/js` folder. Let's replace it by adding it to package.json https://www.npmjs.com/package/slick-carousel/v/1.6.0

### Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
Cool you are right. I think I was looking at a different slick library on npm :) I think we should just go ahead and pull the npm one (but make sure we check the contents of it match the one we currently ship.
