### ISSUE TITLE
Manage Bookcovers popup gets cut off

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2373]
### Description
Select the book cover popup is cut off

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/64541518-fd49ce00-d2ef-11e9-81c4-c6f6ac45b6ce.png)

### Relevant url?
1. go to e.g. https://openlibrary.org/works/OL16313124W/Harry_Potter_and_the_Chamber_of_Secrets
2. Hover over the cover
3. click "Manage covers"

### Expectation
Should not be cutoff

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 68.02
- **Operating system?** Windows 10

**Comment by LeadSongDog** [comment]
This dialog has quite different behavior between FF and Chrome. Looking at the frame source, 
Chrome sees the book carousel__item filled with medium-sized book-cover images in 100px fixed-width versions.  It shows three of up to 100 items in a single scrolling row.
FF sees portlets with small-sized book cover images in 60px fixed-height versions. It shows just 10 items in two rows (one of six items, the other of four).

**Comment by cdrini** [comment]
@LeadSongDog Can you provide a screenshot? I'm seeing the same on Chrome 76:
![image](https://user-images.githubusercontent.com/6251786/64547993-c5488800-d2fb-11e9-8749-284eafac03b8.png)

**Comment by LeadSongDog** [comment]
Sure. Below only have placeholder covers (the firewall here blocks archive.org).
All on Win7 Pro.
Chrome 76, zoomed 50%
![chrome76zoom50](https://user-images.githubusercontent.com/11435431/64630772-ccd36400-d3c3-11e9-8895-6b7f28510754.jpg)

Chrome 76, zoomed 33% (this is the one that shows the problem)
![chrome76zoom33](https://user-images.githubusercontent.com/11435431/64630796-d6f56280-d3c3-11e9-9476-eb58127596d9.jpg)

FF 68, zoomed 50%
![ff68zoom50](https://user-images.githubusercontent.com/11435431/64630811-dceb4380-d3c3-11e9-8a14-22156228b557.jpg)

FF 68, zoomed 30%
![ff68zoom30](https://user-images.githubusercontent.com/11435431/64630817-e07eca80-d3c3-11e9-917d-7b4389c7cb3a.jpg)

My earlier comment on the browsers seening different frames seems to have been overtaken by events. Now both browsers see one row of 100 covers, medium size, 100px width.

**Comment by guyjeangilles** [comment]
My be a different issue, but the Manage BookCovers popup is also not responsive on mobile.

Assigning jdlrobson (not tagging as requested) per slack discussions

**Comment by mekarpeles** [comment]
appears resolved
