### ISSUE TITLE
Discussion: Questions of attribution

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2379]
### Description
How should works with uncertain authorship be entered? For example, the play Sir Thomas More. It has been attributed to a few different playwrights. VIAF has no author associated with it. https://viaf.org/viaf/188331879/#Sir_Thomas_More_(Drama) 

### Proposal & Constraints
Should the author be "Unattributed", "Unknown", or perhaps all of the possible authors?

**Comment by LeadSongDog** [comment]
@seabelis 
http://id.loc.gov/authorities/names/n50075223.html provides some hints.  Another option is simply to create an author record for "Author of [work]", then in the biography section, provide links to the academic bibliographic publications discussing attribution of [work].
