### ISSUE TITLE
Have the full size of a cover's upload

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2385]
Right now, the book covers, when uploaded, shrink. However, if a bot upload's it from the INternet Archive's books, that doesn't happen. If when a person uploads a cover, it's the size that they upload it, then it'll be better.

**Comment by cdrini** [comment]
Hey, could you give an example? Note that e.g. https://covers.openlibrary.org/b/id/8596368-L.jpg does not store the highest quality version; you have to remove the `-L`, e.g. https://covers.openlibrary.org/b/id/8596368.jpg

**Comment by cdrini** [comment]
I tried downloading the cover from https://openlibrary.org/books/OL17047098M/Bel-ami and uploading it again, and it didn't shrink it.
To see the highest quality image stored, right click on the cover, and click "view image" or "Open image". For https://openlibrary.org/books/OL6061943M/The_Peabody_Sisters_of_Salem , that should open a page like this: https://covers.openlibrary.org/b/id/8784090-M.jpg . From here, you can remove the `-M` (or `-L`) to get the highest quality image -> https://covers.openlibrary.org/b/id/8784090.jpg . Does this look similar to the size you uploaded it as?

**Comment by BrittanyBunk** [comment]
I was just thinking that as I read what you said. That's genius! Thanks. I'll close this now.

**Comment by BrittanyBunk** [comment]
It didn't work.

**Comment by cdrini** [comment]
What didn't work?

**Comment by BrittanyBunk** [comment]
I followed your steps on the https://openlibrary.org/books/OL6061943M/The_Peabody_Sisters_of_Salem. I'll try it again and see if it helps.

**Comment by BrittanyBunk** [comment]
Your link didn't work either. You could see the cover didn't change its size on that book.

**Comment by mekarpeles** [comment]
Could not reproduce

**Comment by BrittanyBunk** [comment]
@mekarpeles I'm still having this issue. It might be on your account that it works on, but it's still an issue on my account.
