### ISSUE TITLE
Open more opportunities to expand OL info

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2388]
Yes, there's the 'Internet Archive Wishlist', but there should be something better than that, where the website has a default that any book that has an expired copyright have a button on its page (where the 'no ebook available' button is now) to click to upload the book to the Internet Archive.

**Comment by cdrini** [comment]
One project which is in progress is adding a "sponsor" button to such books. The user would donate a book's physical/scanning/etc price and then track its progress as it makes its way to available to borrow. Does this solve the problem?

**Comment by BrittanyBunk** [comment]
I think that's a different issue. What I'm talking about is a section, similar to the ones on the Open Library home page that would show books that have 'no ebook available', but have expired copyrights and need a book. Now if that book's in the Internet Archive, it just needs to be linked and the book removed from the list. However, if it's not, then it's in the queue until it's scanned in.

**Comment by BrittanyBunk** [comment]
![Untitled](https://user-images.githubusercontent.com/55302685/65169817-396de480-d9fc-11e9-92d3-db1668692977.png)

**Comment by BrittanyBunk** [comment]
![Untitled](https://user-images.githubusercontent.com/55302685/65169849-4ab6f100-d9fc-11e9-9f5a-84a308787660.png) like this, but a carousel called 'books we need'. This doesn't need money, as people could scan for free.

What you may be talking about is if a book doesn't have an expired copyright, in which people donate the value of the book to an author and then when people borrow the book, the author's compensated I'm presuming.

**Comment by guyjeangilles** [comment]
To add my two cents: having the Internet Archive scan books assures the quality of the scan. While it's definitely possible for patrons to provide quality scans, we'd also have to have some quality assurance program that prevented trolls from uploading unrelated content for books with expired copyright. We can incorporate such a program, but are user uploaded scans worth the operating cost?

**Comment by BrittanyBunk** [comment]
@guyjeangilles I'm not sure what the issue with trolls is here specifically if anyone can upload to the IA. If that's an issue about only the IA scanning books, then the website should say that. However, the website says that it's a website designed for anyone to scan books. I'm also not sure what the operating cost of users scanning to the IA is, as I'm presuming $0 (outside of making the list). 

It really is supposed to help the IA with decreasing costs, if maybe the IA knows what books to scan and could let the public know which they don't have. I feel it's not really needed anymore with the sponsorship (as I wrote it before then). So since there is a sponsorship carousel, I guess I could close it, but it's not my vision.

My vision was a carousel with 'no ebook available' on books that are before 1920 (which should be easy to create, as that info's already with books). Then people could scan and add those in, as they should be within the public domain. This would be different than the sponsorship, which is donation-based. I was hoping that this carousel would lead to more books in the IA, but without it asking for money. So there would be 2 carousels with this idea - the sponsorship and the scan and upload ones.

**Comment by BrittanyBunk** [comment]
the sponsor carousel is sufficient for now, as it's kind of the vision, and the rest will come later.

**Comment by BrittanyBunk** [comment]
This issue is getting solved where libraries now can post the books they have in their libraries on the IA. There is a vision to what I was talking about here, but it's a little hard to describe, but is in the works:
- instead of saying 'sponsor', an option is in the works to be written in 'donate' if someone has the book, so the IA doesn't have to buy the book if it already exists. This is really important for rare books. So if there's a 'not in library' button - changing it to 'add to library' would be a great benefit. It encourages people to bring in their books. That's kind of what I'm trying to go for/bring up here with this idea.
- another idea is if there's a book that someone has that is out of copyright, why not encourage people to scan and upload those books - like walk people through the copyright process and explain what is acceptable and what is not. I think that would be really helpful in getting people to realize what's acceptable and what's not so that they don't upload what they shouldn't. Right now, it's not that clear and that's why I worry about copyright violations potentially popping up on the IA - this catches/fixes those problems early on.

Of course there are multiple approaches to everything - so these are the ideas/lines to get started on, but definitely it's not limited to these ideas. People can pitch in theirs. But what I'm trying to get at is to improve the 'not in library' button to be more interactive and give people more options to expand the OL properly by giving people the opportunity to where they have it. Like make the OL more open!

No, I'm not going to make these separate github issues right now, as they all go together and I don't want them to be lost - and in all, it's just a brainstorm at this point.

**Comment by mekarpeles** [comment]
Resolving as the sponsorship and donation paths are already available, as are edit options.
