### ISSUE TITLE
Show the size limit for cover image uploads

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2390]
It's 30 MB

**Comment by cdrini** [comment]
:+1: Sounds good to me; @mekarpeles is the max 30mb? Where is that defined?

**Comment by guyjeangilles** [comment]
Signal boost @mekarpeles

**Comment by BrittanyBunk** [comment]
@seabelis since you know how to edit the FAQs, what do you think about adding it there?

**Comment by devarshigoswami** [comment]
Can I take this up?

**Comment by BrittanyBunk** [comment]
I'm not working on this any further, so whoever wants to is fine by me.

**Comment by devarshigoswami** [comment]
@BrittanyBunk @mekarpeles  what I can do is add a small script right inside `templates/covers/add.html` that validates the size of the locally selected file that will `alert` if filesize exceeds 30mb.
But the **upload image using URL from the web** confuses me a little. no matter what image URL i post, this comes up 

**Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2020-04-01/172635766108 and will look into it as soon as possible. Head for home?**

**Comment by BrittanyBunk** [comment]
@devarshigoswami that sounds like a different issue. 

For this issue:
1) an alert is a good idea, but is complementary to the starting point
2) The starting point is putting in the [instructions](https://openlibrary.org/help/faq/editing#picture) about how images over 30MB won't upload. The alert will complement that.

I'm not sure you'll be able to edit the instructions, so I really like your idea. @seabelis since you wrote in the instructions last, would that be a possibility to add in?

**Comment by devarshigoswami** [comment]
@BrittanyBunk Is the FAQ page maintained somewhere outside the sourcecode repo? because It's not showing if I open a local instance of Openlibrary on my PC using docker.

**Comment by seabelis** [comment]
@devarshigoswami FAQ page is https://openlibrary.org/help/faq/editing#picture. It's been updated with the size limit.

**Comment by devarshigoswami** [comment]
Awesome! @seabelis can I open a new issue for validation of that 30mb limit via a script?

**Comment by tfmorris** [comment]
@devarshigoswami There is already #3208 (and associated PR)

**Comment by BrittanyBunk** [comment]
Awesome. Thanks everyone for helping out with this. I'll close it now!

**Comment by BrittanyBunk** [comment]
@devarshigoswami I agree, #3208 is where you'd place your proposal I believe.
