### ISSUE TITLE
Add a 'printed by' section under 'publisher'

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2391]
It's found in many books to be different than the publisher. Also, the location of where it's printed (as it's different from the publisher location) would help too.

**Comment by cdrini** [comment]
Could you provide a concrete example? I've always been confused by what exactly applied to what with respect to publisher/location/printer

**Comment by seabelis** [comment]
Due to changes in the industry, older editions will frequently show a printer and not a publisher. In these cases the printer should be used for the publisher. Modern editions (from 19th century) that have a publisher will sometimes include printing information. So the significance varies by edition.

**Comment by seabelis** [comment]
Examples,
1. https://archive.org/stream/hamletprinceofde00shak_1?ref=ol#page/n6/mode/2up
2. https://archive.org/details/hamlet0000shak/page/n5

In the first example, the printer and printer's city are essential pieces of information. In the second, the publisher and city are more important than the fact that it was printed in Singapore. 

If printer fields are added, would we want cases as in the first example to be listed as publisher or printer and how would this affect the ability to search by publisher?

**Comment by BrittanyBunk** [comment]
Good questions. Here's my example in the Open Library: https://openlibrary.org/books/OL27305075M/All_of_Science. I had no place to put 'printed', so I just had to put it alongside the publisher. That creates confusion. The reasons I would say we would need to add the printer, in addition to the publisher is:
1. People could get confused when looking at the copyright section of a book as to who's the publisher and who's the printer.
2. As seen in the example, books get reprinted, so that's important too. So that's another bit of information, in addition to printer and city. The reason is that knowing that something's reprinted relates to copyrights - and whether a book's out of print or not.

Should it be under publisher or printer?
If a book's just printed without a publisher, wouldn't it say 'self-published' in the publisher section? Or, maybe it could be blank. Who publishes is, I believe, quite complicated sometimes. In general, whatever people know gets filled in. So if people know the printer, but not the publisher, that gets filled in and vice versa.

How does it affect the ability to search by publisher?
It's going to be more accurate, as now instead of unavoidably added a printer to the publisher section, it gets its own section. So if people can't find what they need to by publisher, they find the book by printer. So the info doesn't go away, just switches to another category. 

How do we categorize each example?
If the first example is the printer, then add that info to that section and likewise for the other example. The only thing is that when adding a book, adding the publisher/publication date should not be a requirement. Instead, we would need new identifiers. I would suggest the copyright date and having either a printer or publisher to add the new book in.

**Comment by seabelis** [comment]
Turns out there is a printer in the contributors list, so in most cases it can go there. 

In the case of printer only, I think it's appropriate to use the publisher's field. 

Self-published books vary; sometimes it's just the author's name. If it has something listed at the bottom of the title page in the publisher area, you should use that. Sometimes the copyright page will say "published by" and you should use that in the absence of title page information. If neither are present, I'd say use your judgement for the given edition. In the case of Lulu, for example, I think the publisher is usually listed as Lulu unless something else is stated. If you really don't know, you can leave it blank.

For the edition year, you should use the year of that specific edition, so if it's a reprint, that's the date you should use. You can state reprint in the edition field. The stated copyright date should go in the copyright field; sometimes there is more than one date; in this case the most recent is what's important.

When using the add book form, I believe the form is checking for potential matches already in the system (not sure about this maybe @hornc knows?), therefore the date specific to the edition is more important than the copyright date which usually spans editions. (It is possible for a publisher to print multiple editions within a single year, but this is less common.)

**Comment by BrittanyBunk** [comment]
It's good that there's that option, but publisher is also there too, yet we have a separate box for that. So that's not quite a reason for me. 

It's confusing, but it's not my call.

Ok, but it shouldn't be a requirement when adding a book if none are present in some books - especially if it's an edition - as it's likely to have the same publisher. 

Some reprints are not another edition though, as the example I showed. It's just a display of a copyright still in use. 

I'm just saying if you add a box for printers, then the 'add book' fields need to be redone. It's ok if the copyright dates are the same, as it says 'the year's enough'. So likely people will add just the year anyway and could be more specific after the book's added in right?

**Comment by guyjeangilles** [comment]
To try to distill the info in this thread:

- `Printer` and `Publisher` data are key pieces of information to identify some editions, particularly pre-19th century editions.
- `Printer` is available as a dropdown in the `Contributor` menu but that's confusing(?)
- In the case where there is no `Publisher` just put the `Printer` in the `Publisher` field

@seabelis @BrittanyBunk Would you agree with this breakdown? Feel free to edit this comment per you liking.

**Comment by BrittanyBunk** [comment]
@guyjeangilles I think it's confusing to have a field for publishers, as it's located in the dropdown menu too. The issue with just leaving the printer to the dropdown menu is that they have an address that's different from the publisher - so it prevents confusion. Also, it's really confusing to put the printer in the publisher field. That's one of the reasons I brought this up.

**Comment by seabelis** [comment]
@guyjeangilles Yes. Printer is less 'key' if edition has a publisher. 
In cases of printer only, then printer is listed as publisher as can be seen in [this example on OCLC](https://www.worldcat.org/title/hamlet-a-tragedy/oclc/642659711&referer=brief_results).

I may be wrong about this, but the publisher drop-down may be a legacy from when users could freely add fields to the dropdown options. I've not received any emails from users expressing confusion about this (this doesn't mean there aren't any, but I've not heard from them if there are).

**Comment by guyjeangilles** [comment]
I'm not an expect on this matter, but it sound like leaving things as is and adding help text could deal with the confusion

**Comment by BrittanyBunk** [comment]
@guyjeangilles why not say 'printer/publisher'. @seabelis It's good to use OCLC for inspiration on how to format OL, and in some ways it's ok to keep the formatting consistent with them. At the same time, it's not like it needs to be followed 100% (as their website's editable by anyone, just like this one is), especially if it's needed (talking in general, not this issue specifically).

I think the reason why people may not be talking about if there's an issue is maybe because they assume what they see is true and that the publisher is the printer and likely they don't look at the book itself when looking at the OL. 

It's on the editing side that I see the issue surface (as if I never edited with the book in-hand, I would never think there's a problem either). Only after editing 100s of books that I started to notice that the info doesn't line up 100%. This is where I get confused when reading on the OL books I don't edit. 

I don't like bringing up info more than once, but I did mention that the printers have more info than the drop-down menu allows and if we don't have a 'printer' section, due to the drop-down menu, then why do we have a separate box for 'publishers' when that's in the dropdown menu too?

**Comment by hornc** [comment]
I agree with @seabelis on this, and @guyjeangilles 's summary,
* Printer is available as a dropdown in the Contributor menu 
* In the case where there is no Publisher the Printer is used in the Publisher field (in line with standard bibliographic practice)

**Comment by BrittanyBunk** [comment]
@hornc That's true, but we should also mention that for all the other info, it does in the same box as the publisher's info for address and date printed and under edition info for number of times printed.
