### ISSUE TITLE
Editions show "No matching records found" after revisions

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2393]
One example is https://openlibrary.org/works/OL4467823W/The_Macmillan_College_Handbook. It has 2 editions, but they don't show up. This happens frequently when something didn't save fully for some reason.

**Comment by BrittanyBunk** [comment]
appears but then disappears

**Comment by cdrini** [comment]
This is related to solr (our search engine) missing edits or just being generally slow to update :( There is work in progress on improving these.
