### ISSUE TITLE
Add a "Barnes and Noble" Identifier

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2395]
Barnes and Noble is a top seller and is surprising to not be one of the options to select to identify books

**Comment by hornc** [comment]
Do have an example Barnes and Noble id, or information about their ids? From a quick glance it looks like they use ISBNs to identify a specific product (hardcover / softcover books) example: https://www.barnesandnoble.com/w/?ean=9780143110439

**Comment by mekarpeles** [comment]
Closing as we already support isbn. We could potentially provide buy links to barnes and noble but at this time there are several other vendors who have asked to be included, and many will require API integration (as showing prices is also a requirement which staff requested as a requirement). Closing for now.

**Comment by BrittanyBunk** [comment]
@mekarpeles not going to make this a new issue, but adding onto this one, another one to add when buying links is Goodreads, as they have identifiers for editions too, and it's not on the list.
