### ISSUE TITLE
https://openlibrary.org/fullsearch errors with unable to render

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2396]
### Description
The page https://openlibrary.org/fullsearch is broken. I don't think it is linked to anywhere.
I see one reference in openlibrary/macros/Search.html but I don't think that macro is active either.

Can this code be deleted?

### Evidence / Screenshot (if possible)
https://openlibrary.org/fullsearch

### Relevant url?
https://openlibrary.org/fullsearch

### Expectation
iF it's supposed to work it shouldn't error out.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by BrittanyBunk** [comment]
is it different than https://openlibrary.org/advancedsearch?

**Comment by jdlrobson** [comment]
Yup. I don't know much about the history of this page. Maybe @hornc or @mekarpeles know..

**Comment by cdrini** [comment]
I would say the html template and the corresponding python class (in search/code.py) should be deleted (if code is also unused).

These commits seem relevant:
- https://github.com/internetarchive/openlibrary/commit/8517e10dbb46fb0fb89d0e1c40e30177ea6fa41e - introduced the code
- https://github.com/internetarchive/openlibrary/commit/06b4df861f8c30c48db93093dbea8d56cbe3a84c - made mods to the python class

**Comment by cdrini** [comment]
Whatever it was this was introduced for, this endpoint has effectively replaced it https://openlibrary.org/search/inside?q=a+rose+by+any+other+name&mode=everything

**Comment by guyjeangilles** [comment]
Page still errors. This seems like a good pruning job for a newcomer

**Comment by nsudarsanam** [comment]
@tabshaikh would this be a good first issue to look at? I can take a stab this week if so.

**Comment by nsudarsanam** [comment]
@mekarpeles would this be a good first issue to look at? I have my local environment setup however the previous first-timer issue was resolved.

**Comment by mekarpeles** [comment]
Sure, @nsudarsanam we'd appreciate your help with this one if you're interested :)

**Comment by cdrini** [comment]
This page 404s now; I believe it was deleted already.
