### ISSUE TITLE
"My loans" error when using Chrome or Edge

### ISSUE THREAD

**Issue by majkaz** [internetarchive/openlibrary#2400]
### Description
When logged in, opening "My loans" from openlibrary.org results in error message if the browser is Chrome or Edge. Firefox displays the correct page. 

### Evidence / Screenshot (if possible)
![2019-09-16_163940](https://user-images.githubusercontent.com/23097386/64969613-89399800-d8a4-11e9-8d20-14f652f291c1.png)

### Relevant url?
https://openlibrary.org/account/loans  

### Expectation
Display the current loans.

### Details
Looking at loans is possible from Firefox
![2019-09-16_171204](https://user-images.githubusercontent.com/23097386/64969929-21378180-d8a5-11e9-9319-418697bc5133.png)

No error when opening loans from [archive.org](https://archive.org/details/@mzem?tab=loans)
![2019-09-16_171240](https://user-images.githubusercontent.com/23097386/64970071-665bb380-d8a5-11e9-931e-2a6408c80837.png)

Edge is old version, Chrome (Chrome portable) version 71.0.3578.80 and 77.0.3865.75 both give the same error. OS - Win 10, connection through proxy.

**Comment by cdrini** [comment]
Thanks for the bug report, @majkaz ! Could you visit the page with the debug parameter? `https://openlibrary.org/account/loans?debug=true` ? Then save the page `ctrl+s` and upload it here. That would help a lot!

**Comment by cdrini** [comment]
Actually, nevermind; that file might contain sensitive information about your account (e.g. IP address).

**Comment by majkaz** [comment]
> Actually, nevermind; that file might contain sensitive information about your account (e.g. IP address).
I have overwritten the IP addresses, these are probably of no real interest in the error log. The remaining info shouldn't be that sensitive besides what is already visible in the screenshots and links above...
[Debug, older Chrome portable](https://github.com/internetarchive/openlibrary/files/3619859/errorlog.zip)

**Comment by cdrini** [comment]
Ah, this seems to _specifically_ happen when you have 1 item in your waiting list, and are looking at the site in Czech :/ Opening a new issue accordingly.

**Comment by cdrini** [comment]
Created a new issue now that we know what's causing it; monitor it here: https://github.com/internetarchive/openlibrary/issues/2420

**Comment by tfmorris** [comment]
This appears to be a duplicate of #2420. Isn't standard practice to keep the earliest of a set of duplicates rather than the latest?

**Comment by cdrini** [comment]
All the information on this issue was useful for me finding out what the true cause of the bug was. But this information is no longer useful, so there's no point in keeping it around.
