### ISSUE TITLE
Add favorites as a tab to a user's profile in the Internet Archive

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2401]
### Is your feature request related to a problem? Please describe.
Instead of having to click on the profile name and going to the drop down menu to do so. Makes for easier switching between pages.

### Describe the solution you'd like
A tab on the profile page (e.g. https://archive.org/details/@{USERNAME} ) linking to favourites

![image](https://user-images.githubusercontent.com/6251786/65526353-f958a700-debe-11e9-8bb5-cc8e0cce7d89.png)

**Comment by cdrini** [comment]
Sorry, which list is this? Are you talking about the menu here (below)? Or is this a favorites list somewhere on archive.org?
![image](https://user-images.githubusercontent.com/6251786/64989881-8a66c700-d89c-11e9-9ad4-33545b3f8475.png)

**Comment by BrittanyBunk** [comment]
Ok. Here's what I mean: 
![Untitled](https://user-images.githubusercontent.com/55302685/65169451-65d53100-d9fb-11e9-8097-8c90159a0306.png)

**Comment by cdrini** [comment]
Ohhh, I understand now; thanks for the clarification!

**Comment by cdrini** [comment]
(Issue opened on the Archive.org team's JIRA (private) https://webarchive.jira.com/browse/WEBDEV-2673 )

**Comment by BrittanyBunk** [comment]
@cdrini thanks. I think it'll really help

**Comment by guyjeangilles** [comment]
Should we close this since it's techinically not OL related?

**Comment by BrittanyBunk** [comment]
@guyjeangilles where's a good place to put IA related stuff?

**Comment by guyjeangilles** [comment]
@BrittanyBunk It sounds like there's a private repo, so it may be best to ping the slack and request it be added to their internal tracking system.

@mekarpeles @cdrini @hornc Would you agree with this?

**Comment by BrittanyBunk** [comment]
@guyjeangilles I'm guessing it might be good to make a github for the IA. That way, there could still be a private repo, but at least there's a way for the public to communicate their thoughts on it.
