### ISSUE TITLE
Error when trying to upload a book cover

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2402]
### Description
A user reported an error when trying to upload a book cover. The displayed error is just the generic "error recorded" error. 

### Evidence / Screenshot (if possible)
The direct error:
![image](https://user-images.githubusercontent.com/6251786/65065618-c3f90a00-d950-11e9-9878-46bcfb6833f5.png)

The closest error in "our" code
![image](https://user-images.githubusercontent.com/6251786/65065524-9318d500-d950-11e9-8f6e-39548e406f11.png)

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Stakeholders
@seabelis

**Comment by seabelis** [comment]
He said it happens with all editions he tries to edit. This is one he sent as an example. https://openlibrary.org/works/OL20071945W/Bletchley_Park_Souvenir_Guidebook

**Comment by cdrini** [comment]
Hmmm :/ Could you ask them for the image file he was trying to upload? Or if he was trying to upload a link; that way we can try to reproduce the error to see if its an error with the specific account, or with the file, or with something else.

**Comment by seabelis** [comment]
From the email: The Book Cover popup doesn't allow me to select an existing cover, so I have to upload covers twice, once for the edition and once for the work. I am using Firefox 68.0.1 (32-bit) on Windows 7.

**Comment by cdrini** [comment]
I'm having trouble reproducing this

**Comment by guyjeangilles** [comment]
Has anyone been able to reproduce this? If all book covers the user is uploading is failing, it sounds like a problem on their end.

**Comment by guyjeangilles** [comment]
I'm going to close since we couldn't reproduce. We can reopen if this issue pops up again.
