### ISSUE TITLE
Exclude dvds from non MARC imports

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2404]
### Description

Part of #2220

A trial import picked up these items which are DVDs with isbns, and have junk author names. These should have been immediately discarded because of their `physical_format: "dvd"` data
The items _do_ have ISBNs, and appear under `product_group: "Book"`, but should be excluded.

Edition | Work | Author
-- | -- | --
OL27268594M | OL20088565W | OL7619837A
OL27268595M | OL20088566W | OL7619838A

The source isbns are:
https://openlibrary.org/prices?isbn=0788826859
https://openlibrary.org/prices?isbn=0788821237

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by LeadSongDog** [comment]
I don`t think I've ever seen them, but theoretically an ebook or audiobook could be on a DVD or DVD-R medium as easily as on CD or CD-R.

**Comment by seabelis** [comment]
The only DVD items I've encountered so far have been movies. Perhaps a policy of don't import but allow users to add them would work here.

**Comment by tfmorris** [comment]
I think we've used the author name pattern to delete some of these in the past, so there may be some regexes lying around to help with the task.

Found the relevant issues: #152 #896

There are currently 16 "xxx ddwd 99999 xxx" authors (mostly from 2008): https://openlibrary.org/search/authors?q=ddwd

**Comment by LeadSongDog** [comment]
Here's a couple of examples:
https://www.worldcat.org/title/national-geographic-life-british-english-pre-intermediate-students-book/oclc/769545852
https://www.worldcat.org/search?q=9783803229427&qt=owc_search
I actuallly own a copy of the latter set.

**Comment by hornc** [comment]
I'm marking this as priority low since I am working around this problem as I encountered it by making better choices in what gets sent to the importer.

**Comment by seabelis** [comment]
Should we still alert you if we notice recent imports?

**Comment by guyjeangilles** [comment]
> I'm marking this as priority low since I am working around this problem as I encountered it by making better choices in what gets sent to the importer.

@hornc Could this be a solution to this issue? At least as it's worded now.
