### ISSUE TITLE
Show star ratings in search results

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2405]
### Is your feature request related to a problem? Please describe.
We have ratings now; we should show them on the search results improve our SEO.

### Describe the solution you'd like
Ratings appear alongside openlibrary search results.

### Proposal & Constraints
Google has documentation about how to do stuff like this: https://developers.google.com/search/docs/data-types/review-snippet

### Additional context
E.g. compare openlibrary results with GoodReads results:

| Open Library | GoodReads |
| ---- | ---- |
| ![image](https://user-images.githubusercontent.com/6251786/65351235-65c06700-db9c-11e9-84fe-298aa21d5e98.png) | ![image](https://user-images.githubusercontent.com/6251786/65351254-6e18a200-db9c-11e9-93a5-a6cf121429aa.png) |

**Comment by hunterji** [comment]
Google pulls these from schemas for each item defined by schema.org.  In GoodRead's case they are using [schema.org/Book](https://schema.org/Book) which makes sense.

How Google does what it does is a black box, but it looks like they want you to pull reviews from your own site (as opposed to an external site). You can't guarantee yourself the stars, but if you put in the schema it should take a week or less for them to pop up (if they are going to at all).

**Comment by cdrini** [comment]
Here's google's documentation: https://developers.google.com/search/docs/data-types/review-snippet ( added to issue ). The displayed rating on e.g. https://openlibrary.org/books/OL383855M/Harry_Potter_and_the_Chamber_of_Secrets is the average of all ratings; we don't have a feature to display individual reviews.

**Comment by samuelpetroline** [comment]
This would require implementing [microdata ](https://developer.mozilla.org/en-US/docs/Web/HTML/Microdata) across many UI components. 

However, I think maybe #163 has some impediments over this?

**Comment by cdrini** [comment]
@samuelpetroline There is already microdata for a lot of UI components. This would require adding some more to probably this line in the Edition's template: https://github.com/internetarchive/openlibrary/blob/310e4d55904033905aa7caa5fabeb82e78b9f71e/openlibrary/templates/type/edition/view.html#L200

Note that file already has `schema.org/Book` microdata.
