### ISSUE TITLE
Show when a book's restricted in the 'no ebook available' area

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2406]
The reason is that people don't go searching for the book when it's not there and also people don't upload the book when they shouldn't.

**Comment by guyjeangilles** [comment]
@BrittanyBunk can you provide a screenshot? I'm not exactly sure what you're referring to.

**Comment by BrittanyBunk** [comment]
https://openlibrary.org/books/OL7444969M/Quantum_Computation_in_Solid_State_Systems. If you click on the Internet Archive ID, it's restricted.

**Comment by BrittanyBunk** [comment]
For this case, instead of it saying 'no ebook available', it should say 'ebook restricted', so that people don't click on the IA ID or try to upload it themselves.

**Comment by guyjeangilles** [comment]
I see know, I'm assuming there's an API we call that can display something to a user

**Comment by BrittanyBunk** [comment]
@seabelis not sure what you're asking. I'll do, not a screenshot, but a visual of what I am asking to be shown. I'm not sure of the right wording to use, so I just made up my own:
![image](https://user-images.githubusercontent.com/55302685/69470502-cd856080-0d4b-11ea-88ad-e784f3034798.png)

**Comment by seabelis** [comment]
Related to #1235 and #2346.

**Comment by seabelis** [comment]
That's essentially what the lock icon is saying, but the text is not very clear about that. I think the button itself in independent of the DAISY-only books, but there are others more qualified to answer that.

**Comment by LeadSongDog** [comment]
In the interests of transparency, patrons should know _why_ a book is not available. These could be "no scan known", "we don't have a scan", "access is withheld by the rights holder", "all our copies are on loan", "Daisy etext is only available to print-disabled Americans", etc.

However, a much better answer might be to offer a different edition of the same work that _is_ available: "That edition is on loan. Would you like to read **this edition**?

**Comment by BrittanyBunk** [comment]
@LeadSongDog I agree that the site should be more clear about its intentions on what it includes and doesn't and why - as many libraries do that.

For the offering of similar, it would be beneficial to add that as a new issue on github if it's not there already.

**Comment by mekarpeles** [comment]
This is now resolved by #4490
