### ISSUE TITLE
Somehow connect what comes with a book to the book

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2409]
If a book has a DVD or some other component that comes with a book, idk how, but maybe it could be uploaded alongside the book and connected to it?

**Comment by guyjeangilles** [comment]
Seems to conflict with #2404. Thoughts @hornc ?

**Comment by BrittanyBunk** [comment]
@guyjeangilles that's different. That's isbn's with only DVDs. I'm talking about ibsn's with book + DVD.

**Comment by hornc** [comment]
I think this is currently supported by the notes field. If there are enough items the share the same kind of data requirement, and a case is made for why it would be better as a structured metadata field, then we could consider adding one. I don't think we ate there yet though.

**Comment by guyjeangilles** [comment]
@BrittanyBunk Does the notes field satisfy your request? Can you provide some examples of books that had accompanying media?

**Comment by BrittanyBunk** [comment]
I think I have to agree with @hornc where it might be a new field that would have a link to material included in it. Just like how there's a link to the IA, it would have a place to add a link from the [software](https://archive.org/details/software), [audio](https://archive.org/details/audio), [image](https://archive.org/details/image), or [video](https://archive.org/details/movies) sections. The reason why I don't have an example in place is because that feature's not there. 

Let's just use a hypothetical example. https://openlibrary.org/books/OL7364657M/Gardner's_Art_Through_the_Ages_(with_ArtStudy_Student_CD-ROM_and_InfoTrac_) has a CD rom accompanying it. It has images on it. Let's pretend that this book is in the public domain, along with all the images. So someone would upload the software in the software section with the images, or just the images (if that's all a person can do), and add in the ID, just like the IA ID for books. 

I don't really know how many books that it's possible to do this with, as since the field wasn't there, I didn't look. However, I would assume that it would be for newer books, language learning ones, etc., so likely not older books. However, it would be a nice option for creative commons books with open source software that's free to share. Idk 100%, just my brainstorm of what it's applicable to.

**Comment by hornc** [comment]
closing as per comments, notes field (and or external links) currently provides this functionality.
