### ISSUE TITLE
Remove databari18n.html

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2417]
This doesn't look like it's used; let's remove it and any corresponding CSS.

## Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
Eek another!

**Comment by cdrini** [comment]
(this one also has a good chunk of dead css that will go with it! 😍 )

**Comment by guyjeangilles** [comment]
This issue needs an assignee. I'm assuming it would be @jdlrobson. Let me know if you agree or disagree. Also, adding a work in progress label.

**Comment by guyjeangilles** [comment]
Assigning jdlrobson (not tagging as request) per slack discussions

**Comment by mekarpeles** [comment]
Nothing requires this issue to be solved urgently today or this week. Decreasing priority.

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue.

**Comment by jdlrobson** [comment]
Great
