### ISSUE TITLE
Remove `focusin` and `focusout` polyfill from vendor/ jquery-validate

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2419]
### Description
Inside vendor/js/jquery-validate/jquery.validate.js is some code  that "provides cross-browser focusin and focusout events"

Support for these events is pretty good now, so this code is no longer necessary

### Evidence / Screenshot (if possible)
https://developer.mozilla.org/en-US/docs/Web/API/Element/focusin_event

### Expectation
- Everything continues to work the same as before.
- Explicitly test the form validation code 
- Fixing this will remove the console warning "jquery-migrate.js:41 JQMIGRATE: jQuery.browser is deprecated"

**Comment by cbolgiano** [comment]
I'd be happy to take a look at this one.

**Comment by cbolgiano** [comment]
I updated jquery-validation to 1.19.1 and the warning went away.

A pull request has been opened.
