### ISSUE TITLE
Just like how the Open Library links to the Internet Archive book, the reverse should exist

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2429]
When viewing a book in the Internet Archive, it would help to have a link saying 'see details in the Open Library' or something. That will help to know which books are not linked to the Open Library when they should.

**Comment by tfmorris** [comment]
These links exists. See Openlibrary_edition and Openlibrary_work on  https://archive.org/details/cuairtoilthirich00buny for example.

There use to be a more obvious "This work has an editable catalog page at OpenLibrary" or something similar. I'm not sure whether it was removed from all pages or just missing from this page.

**Comment by BrittanyBunk** [comment]
@tfmorris you're right, it is there, but I wouldn't notice unless I asked. It really would be nice under the title or something to put it back to the way it was before.

**Comment by cdrini** [comment]
The see also section might be a good spot: 
![image](https://user-images.githubusercontent.com/6251786/65967992-8b692e00-e430-11e9-8087-a784e3b95679.png)

**Comment by BrittanyBunk** [comment]
@cdrini that seems a little hidden, but I believe we'll find a good spot

**Comment by mekarpeles** [comment]
This issue seems resolved. Archive.org is also out of scope of this project board.
