### ISSUE TITLE
Show the language availability of a book when clicked on or have a translator

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2430]
If a book's written in multiple languages, when a person clicks on a book to read, a place that shows 'other translations' with other languages to bring a reader to a language translation they would like to read it in would help. Another idea is just to have a book, but to make it readable in any language. Like people could click a language at the top and the book converts to a translated version.

**Comment by tfmorris** [comment]
We don't have good metadata about translations, but we do have the language of each edition (mostly), so we could provide a facet/ which selected one or more languages to filter the editions by.

**Comment by BrittanyBunk** [comment]
It's too bad. Maybe there's a way to put it through Google Translations or have that overlayed on the Archive site one day.

**Comment by guyjeangilles** [comment]
+1 for making other translations available.

I'm not sure there's a translation service that exists that could reliable translate an entire book into something that's true to the original work unfortunately.

**Comment by BrittanyBunk** [comment]
@guyjeangilles thanks. I do know of which service could provide this (and possibly for free or something), but I would need to make contacts with my contacts. I could do that if you'd like me to. I've been thinking about it since I first wrote it, but I think I could make it possible (if not, I'll say why not at that time). Would you like me to move forward with this?

**Comment by guyjeangilles** [comment]
@BrittanyBunk I'm not necessarily the decision maker but it may be a good idea to find a dev dedicated to making this reality. @cdrini This sounds like a cool enhancement for TTS

**Comment by BrittanyBunk** [comment]
I did research and couldn't find much, but I think it's a matter of embedding a translator for images of the book pages or the entire document all at once in the web app that allows the book to be visible in the IA. For the OL, having a way to click the language a person wants to read in would be a temporary help.

**Comment by mekarpeles** [comment]
This is a good idea, and ideally something we can do a good job about during #684 -- Archive.org does give us language codes so we could conceivably at least identify books meaningfully by language. This current issue (as presented) is great context as to what path would be good for users, but it's not something we're positioned to directly act on, and so I am going to close it for now.

**Comment by BrittanyBunk** [comment]
@mekarpeles Sorry to bug, but it's a little ambiguous why it's closed related to #684. Is it because that's the priority being the infrastructure to set this up with, and this a secondary one to proceed that. Or, is the focus of the OL not on languages at this time altogether? The clarification will prevent future accidental potential raising of the issue again.

I'm really glad there's a method to carry it out and an understanding, so that's great.
