### ISSUE TITLE
Not all non-MARC import items have covers

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2438]
### Is your feature request related to a problem? Please describe.

e.g. https://dev.openlibrary.org/books/OL27325724M/Unti_on_Broderick_Murder_Case

https://www.betterworldbooks.com/product/detail/Unti-on-Broderick-Murder-Case-9780061432613

suggest not importing these until we can get a better source of metadata.

**Comment by tfmorris** [comment]
I'm not sure whether just a missing cover should be enough, but this also has no author, and doesn't exist in WorldCat or Library.lnk. We should definitely have a minimum quantity/quality of metadata to bother importing something. I don't think a UPC code and a title meets that minimum.

**Comment by hornc** [comment]
Agreed. Missing covers seem to be an indicator that the other metadata is less good also, so I was thinking of using it as a heuristic. No author with minimal other details should also be a red flag.

From a little more investigation I am finding the no covers and poor metadata issues drop away when I get a little more selective on which ISBNs are imported. I'm working on using ISBNs which appear in library holdings to determine similar ISBNs which appear in seller lists, which seems to do a good job of filtering out items which do not have very coherent metadata.

This issue should be addressed though, and the system should reject data that does not meet minimum standards.

**Comment by guyjeangilles** [comment]
To add my two cents: I think it'd good sensible to have a minimum requirements list before something is added to import. Example list.
- Author
- Title
- Publisher/Printer
- ?

**Comment by seabelis** [comment]
I wouldn't consider an absent cover to be a sole reason not to import (frequently the covers used on oclc, amazon, other sellers are incorrect anyway). Checking library holdings is a big + in my book. In the provided example, there is no corresponding oclc record and this would suggest an actual book with that isbn never existed beyond an isbn. This is common for amazon imports.

**Comment by tfmorris** [comment]
I don't think requiring an ISBN list to be pre-filtered is a viable long term. The system should have minimum thresholds built in and reject things that don't meet the thresholds.

**Comment by jimchamp** [comment]
@mekarpeles says that we should reject imports missing critical fields, but missing book covers is insufficient.
