### ISSUE TITLE
Sample query on restful api documentation returns unexpected results

### ISSUE THREAD

**Issue by mvolz** [internetarchive/openlibrary#244]
I tried one of the sample queries on https://openlibrary.org/dev/docs/restful_api:
```
curl -s -H 'Accept: application/json' http://openlibrary.org/books/OL1M
```
The response I got was
```
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.1.19</center>
</body>
</html>
```
Instead of the expected JSON.

**Comment by nibrahim** [comment]
On Fri, Apr 03 2015, M. Volz wrote:

> I tried one of the sample queries on https://openlibrary.org/dev/docs/restful_api:
>
> curl -s -H 'Accept: application/json' http://openlibrary.org/books/OL1M

[...]

That's an obvious bug either in the docs on in the software. However,
using the .json suffix does work as expected.

curl -s  http://openlibrary.org/books/OL1M.json

**Comment by mvolz** [comment]
Thanks!

**Comment by nibrahim** [comment]
You're very welcome!

**Comment by gdamdam** [comment]
you need to call it through https and not http:
```curl -s -H 'Accept: application/json' https://openlibrary.org/books/OL1M ```

we updated the restful api documentation
