### ISSUE TITLE
Subject search doesn't return JSON

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2443]
### Description

Currently there's no way to get subject search to return JSON.

While https://openlibrary.org/search/authors.json?q=teen
correctly returns results in JSON format,
the corresponding subjects search https://openlibrary.org/search/subjects.json?q=teen
always returns HTML.

### Expectation
Subject search should return JSON the same as all the other search endpoints.

**Comment by imnotjames** [comment]
Same issue applies to `lists` search and `edition_search`

**Comment by luxorv** [comment]
I can take this! :)

**Comment by imnotjames** [comment]
It seems like the test environment doesn't index subjects correctly?

**Comment by imnotjames** [comment]
I'm going to open a few more PRs to handle `lists` and `edition` search JSON formats as well.

**Comment by cdrini** [comment]
Thanks @imnotjames ! You're correct, subject search doesn't work on the local env (as a side-effect of #1896 ); we can test that for your :+1:

Lists sound good. Which endpoint are you talking about when you say `edition` search?

**Comment by imnotjames** [comment]
`/search/editions` and `/search/lists`

**Comment by cdrini** [comment]
`/search/lists` should work, but `/search/editions` is dead code; there are only 36 books searchable through that endpoint :P Let me double check

**Comment by imnotjames** [comment]
Bizarre.  Ok, perhaps it should be removed.

**Comment by cdrini** [comment]
Yep! Looks dead. This is an old codebase :) Creating an issue to remove it now.

**Comment by cdrini** [comment]
#2460
