### ISSUE TITLE
Get non-author contributors from amazon API

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2444]
### Is your feature request related to a problem? Please describe.

Test import https://dev.openlibrary.org/books/OL27326660M  missed the 'author' field as it is listed as a contributor `editor` on the source record.

The prices response excludes the other contributor info:
https://dev.openlibrary.org/prices?asin=0708322298
The data appears to be available from the api, we are just not asking for it, or exposing it.

This probaby affects other roles such as illustrator etc, but `editor` is likely to be a common case where there is no other author supplied.

### Describe the solution you'd like

Expose other contributors on the prices API, to make that data available to the import process.
Ideally set the author with the appropriate role https://openlibrary.org/type/author_role at the work level.

**Comment by hornc** [comment]
Another example with 2 editors: https://dev.openlibrary.org/books/OL27326668M/Bellamy_Child

**Comment by guyjeangilles** [comment]
Assigning @hornc per slack discussions since imports are his purview

**Comment by hornc** [comment]
duplicate of #3084
