### ISSUE TITLE
Works w/ Missing Covers Should Fallback to Available Edition Cover

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2447]
When looking through the books on the main page, many of them have no cover. However, one edition is likely to have a cover. So I need to go through each and every book to add the cover that's on one edition to the book's home page. It would be nice to have a cover automatically posted to the book's main page the second a cover on even one of the editions is posted.

**Comment by guyjeangilles** [comment]
By "book" I assume you mean "work"? If so, I'm assuming it'd be easy to check if 1) a work has no cover 2) this coverless work has editions with a cover and 3) add the editions cover id to a work

**Comment by BrittanyBunk** [comment]
@guyjeangilles yes, I think that would work!

**Comment by mekarpeles** [comment]
I'm going to assign to myself; this falls under #684

**Comment by BrittanyBunk** [comment]
@mekarpeles I think you are the right person for this, as you fixed the other similar bug :)

**Comment by xayhewalo** [comment]
Closing as #684 addresses this
