### ISSUE TITLE
Make the first Internet Archive ID changeable

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2448]
Right now, if I add the wrong Internet Archive ID, I can't change it, which creates issues where it shows up as an error for the wrong url, while the correct one won't post.

**Comment by BrittanyBunk** [comment]
I can't even add the right one, as it just deletes it the moment I press save in the open library.

**Comment by LeadSongDog** [comment]
This would be covered by #2281

**Comment by mekarpeles** [comment]
@BrittanyBunk thanks, this is a valid issue! Closing it only because there's another existing issue open which addresses the technical problem. (this issue will remain linked, since @LeadSongDog tagged #2281 from here)

**Comment by BrittanyBunk** [comment]
It's #2329
