### ISSUE TITLE
Can't fully delete an upload

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2449]
I uploaded an item twice, but would like to delete one. I don't see how. Is it possible to?

**Comment by cdrini** [comment]
What is "item" here? A book cover on openlibrary?

**Comment by cdrini** [comment]
Or an upload to archive.org?

**Comment by BrittanyBunk** [comment]
right, it's an upload to archive.org

**Comment by mekarpeles** [comment]
This board is specifically for openlibrary.org :) info@archive.org can answer Archive.org related questions.

**Comment by BrittanyBunk** [comment]
How come there's no board for the archive?

**Comment by cdrini** [comment]
It's just the way their team is organized.
