### ISSUE TITLE
Subtitles for books

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2453]
Right now, books (not talking about the editions) don't have a box to add their subtitle and it would benefit from having one.

**Comment by LeadSongDog** [comment]
@BrittanyBunk 
I think you mean "works", not "books". 

Directly above the unnamed "Title" field, the work edit interface instructs:
"**Title** Use _**Title: Subtitle**_ to add a subtitle. *Required field"
This is indeed different from and arguably inferior to the interface at the edition level which has separate edit boxes, one for **Title** and another for **Subtitle**

**Comment by LeadSongDog** [comment]
@BrittanyBunk 
I think you mean to say "works", not "books". The latter term is so ambiguous that it should be avoided here.

See for instance https://openlibrary.org/books/OL1238676M/On_the_way_home/edit

Directly above the unnamed "Title" field, the work edit interface instructs:
"**Title** Use _**Title: Subtitle**_ to add a subtitle. *Required field"
This is indeed different from and arguably inferior to the interface at the edition level which has separate edit boxes, one for **Title** and another for **Subtitle**

**Comment by BrittanyBunk** [comment]
right, but that should be for the Internet Archive, as the Open Library uses the word 'books', so it's to not get confused. Otherwise, shouldn't the Open Library be changed to that too?
