### ISSUE TITLE
Add Pagination help text instructing how to add lowest page number

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2454]
Right now, it only shows highest number, but a useful bit of info are the lowest numbers to, to know where a book starts at.

**Comment by mekarpeles** [comment]
Hi @BrittanyBunk thanks for this issue! When you say highest number -- highest number of what? Editions? Date?

**Comment by BrittanyBunk** [comment]
Highest number pages. Like the lowest number might start at page 3, not 1.

**Comment by seabelis** [comment]
You can format the pagination like this if you'd like to include the lowest page number, [3]-357 p.

**Comment by BrittanyBunk** [comment]
it would be good to add it to the instructions, as it says 'max' right now

**Comment by guyjeangilles** [comment]
I've changed the title to account for this threads context

**Comment by seabelis** [comment]
I've self-assigned. I have a lot of issues involving the edit form, so it's probably good to group them.

**Comment by seabelis** [comment]
> You can format the pagination like this if you'd like to include the lowest page number, [3]-357 p.

I'm correcting myself. After reading technical documentation, I've realised the square brackets has a designated purpose when used in the pagination area. 

@BrittanyBunk , please do not use square brackets for noting the lowest page number. You are not expected to revise any records you've added with this pagination. Going forward you may note the lowest page number without the brackets, i.e. 100-300p., but this is not typically necessary unless the paging is continuous across multiple volumes.

**Comment by BrittanyBunk** [comment]
@seabelis it's true that I'm able to do it, but if it's not written in the field instructions, no one else will follow it and then the formatting will be uneven - and that has consequences like everyone undoing each other's work. That's why I propose for it to be in the instructions for all books, as some books would have say 100 pages but end on 300p. I find it a necessity and I don't think anyone really knows the best format to use without the instructions (even you got confused and I still am).

**Comment by seabelis** [comment]
@BrittanyBunk It does need to be clearer on the form. I also wanted to note the correction here so that you would see it.

**Comment by BrittanyBunk** [comment]
@seabelis thanks

**Comment by tfmorris** [comment]
We have fields for both pagination and number of pages. Pagination is mainly a classical librarian thing and perhaps it does add enough value for us to keep in addition to number of pages which is a single number rather than a fancy text string.

**Comment by LeadSongDog** [comment]
OL’s “pagination” is more properly called “extent”. 
There is a good short explanation at https://collation.folger.edu/2016/05/physical-description-book-cataloging/#easy-footnote-bottom-3-12574
Perhaps a simpler write up for the wiki, to be linked from the edit form?

**Comment by BrittanyBunk** [comment]
@LeadSongDog cool. Thanks for letting me know about extent. This website doesn't use the International Standard Bibliographic Description though, so what should we do?

**Comment by mekarpeles** [comment]
I like @LeadSongDog's suggestion. And I think this thread demonstrates that clarification (instructions) may be useful in this case.

**Comment by BrittanyBunk** [comment]
@cdrini I'm confused why it got closed. It helps me when there's a description of the closure. Everything moved so quickly here.

**Comment by BrittanyBunk** [comment]
thanks everyone for solving this.

**Comment by BrittanyBunk** [comment]
I actually don't think this is 100% closed though, as the 'help' button doesn't address the numbers with brackets. @seabelis said not to touch them, so I feel a note should be added for this @cdrini
