### ISSUE TITLE
Be able to privately message/forum for members

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2456]
The issue is that sometimes I feel there's a lack of coordination with edits among users. So to have some ability to chat with others, to be able to have cohesive efforts in making the Archive efficient and productive, would be awesome.

**Comment by guyjeangilles** [comment]
A tangential suggestion: a discussion page per work, book, and author similar to Wikipedia.

**Comment by BrittanyBunk** [comment]
@guyjeangilles I looked on Wikipedia and didn't see what you're talking about (like the community portal's not it). Someone on slack said a wiki, so a public wiki, but I'm envisioning more like how wikihow looks (like an article + comments section), but the front page would have a search bar, link to the FAQs, and common faqs topics underneath. Each faqs page has a comments section. I feel this could be within the OL website and doesn't need a new one, but that's my thought.

**Comment by guyjeangilles** [comment]
The discussion pages are are called "Talk Pages." For example the page for Open Library is https://en.wikipedia.org/wiki/Talk:Open_Library

**Comment by BrittanyBunk** [comment]
@guyjeangilles ok, then that. It's easier to access on Wikihow than Wikipedia, but I see what you mean.

**Comment by BrittanyBunk** [comment]
@guyjeangilles https://archive.org/details/texts&tab=forum for the OL is what I'm thinking, as it's needed there with all the editing. Hope that helps.

**Comment by mekarpeles** [comment]
no plan to implement
