### ISSUE TITLE
Remove dead `/search/editions` endpoint

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2460]
This endpoint https://openlibrary.org/search/editions.json?q=the is dead. There are only 36 books which this can search for. Double check to make sure they're unused, and then let's remove the class (located in `worksearch/code.p`) it's template (`search/editions.html`), and any other related files (maybe CSS). It looks like this commit introduced this code; looking at nearby commits might reveal other related files worth deleting.

- 4d83b943c8183a6734e58c2b7e2019a1bcf931c4

**Comment by MatsLanGoH** [comment]
Hi, I'd like to give this a shot - haven't had a good look at the codebase yet, so this looks like a neat way in :)

> Double check to make sure they're unused
Asking for confirmation: With "they" do you mean the 36 books? Or the editions endpoint?

**Comment by cdrini** [comment]
Go for it, @MatsLanGoH ! I mean the class/endpoint 👍

**Comment by MatsLanGoH** [comment]
Thanks for the response!
Apparently @imnotjames has already started working on this in #2470, so I'll keep my eyes open for something else!

**Comment by imnotjames** [comment]
Ah, sorry!  I hadn't sent your update here.  ): I'm still digging into any extras that aren't needed of this is removed.
