### ISSUE TITLE
Flickr badge is deprecated and broken

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2463]
https://openlibrary.org/about has a script pointing to http://www.flickr.com/badge_code_v2.gne?count=3&display=random&size=t&layout=v&source=user&user=41108298%40N06

Looking at the script it is deprecated

![Screenshot 2019-10-04 at 2 44 09 PM](https://user-images.githubusercontent.com/148752/66242047-82d55980-e6b5-11e9-8732-d3e25b9b7f68.png)

### Expectation
We should remove the script and the  column "Open Library on Flickr".

The template lives in openlibrary/templates/type/about/view.html

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Stakeholders

@mekarpeles @cdrini

**Comment by imskr** [comment]
Can I work on this issue?

**Comment by tfmorris** [comment]
I agree that removing Flickr is the right call. Nothing has been uploaded since 2011. Not sure what, if anything, to replace it with.

**Comment by jdlrobson** [comment]
@imskr I think that's fine but please sync with @mekarpeles if he's okay to remove it and the blank space associated with it thT removing it will leave.

**Comment by jdlrobson** [comment]
@imskr are you planning on working on this?

**Comment by cdrini** [comment]
I think that would be a good place for a twitter feed (which is active); but let's just remove flickr as part of this. 

Related code: https://github.com/internetarchive/openlibrary/blob/630386df5b7b6d980697ccb1ef856df6a828c3f0/openlibrary/templates/type/about/view.html#L35

But also check for other CSS/JS which might be dead.

**Comment by imskr** [comment]
@cdrini should I just remove that h3?

**Comment by cdrini** [comment]
@imskr You can probably remove the entire ` <div class="contentQuarter">` containing that h3. Also do a search in the code base for any IDs or classes that appear in that HTML, to see if it's referenced in other spots. We might be able to also remove related JS/CSS.

**Comment by jdlrobson** [comment]
For completeness after removing the contentQuarter element the element besides it will want to change from contentQuarter to contentHalf class.

**Comment by imskr** [comment]
@cdrini I have made the PR. Please review.
