### ISSUE TITLE
Unique visitors graph levelled off

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2481]
The unique visitors seems like it's down to 0 for some reason since ~Oct 2. (date determined by looking at "view source" and searching for `graph-json-visitors`.)

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/66503246-e506d380-ea94-11e9-937e-1bede7e7f238.png)

### Relevant url?
https://openlibrary.org/

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 69
- **Operating system?** Windows 10

**Comment by jdlrobson** [comment]
Confirmed. Not an issue on the client though. When I view source the data feeding those graphs is clearly saying 0.

**Comment by mekarpeles** [comment]
@samuel-archive do you have any idea why this is happening? It seems like it may be server side.

**Comment by mekarpeles** [comment]
`plugins/openlibrary/home.py` -> `core.admin.get_stats()` -> `visitors    = Stats(docs, "visitors", "visitors")`

`$:commify(stats["visitors"].get_summary(28))`

**Comment by mekarpeles** [comment]
data for openlibrary looks fine from here: https://catalogd.archive.org/stats

**Comment by mekarpeles** [comment]
Related historical issue: #1026

**Comment by mekarpeles** [comment]
I have a suspicion. @hornc is it possible that `ipstats.py` is being run after our importbot cron, that there's an error occurring, and the rest of the cron is aborting??

**Comment by mekarpeles** [comment]
I just ran `sudo /olsystem/bin/olenv /opt/openlibrary/openlibrary/scripts/ipstats.py  /opt/openlibrary/olsystem/etc/openlibrary.yml` on `ol-home` and that succeeded w/o problems but no dice on solution. Trying to also run `/olsystem/bin/olenv /opt/openlibrary/openlibrary/scripts/store_counts.py /opt/openlibrary/olsystem/etc/infobase.yml /opt/openlibrary/olsystem/etc/openlibrary.yml /opt/openlibrary/olsystem/etc/coverstore.yml 1` first

**Comment by mekarpeles** [comment]
I'm also seeing `/dev/vdb1       3.6T  3.4T  188G  95% /1` low disk space on `ol-backup0` which we should make sure is not related.

**Comment by mekarpeles** [comment]
@cdrini and I ran `ssh -A ol-www1` and then `sudo -u www-data` then `source /opt/openlibrary/venv/bin/activate` and finally `python`:

`from scripts import ipstats;from datetime import datetime as d;ipstats.main('/opt/openlibrary/olsystem/etc/openlibrary.yml', d.strptime('2019-10-01', '%Y-%m-%d'), d.strptime('2019-10-29', '%Y-%m-%d'))`

**Comment by mekarpeles** [comment]
Also related, for those who have access, the raw logs get rotated from /var/log/nginx to https://archive.org/download/ia_webserverlogs_20191028/openlibrary/ (change date as appropriate)

**Comment by cdrini** [comment]
Rerunning today

**Comment by cdrini** [comment]
Rerunning now

**Comment by mekarpeles** [comment]
@cdrini @hornc this seems like the type of thing we should probably add to our milestone (due end of month). @hornc is this something you may be able to help us with so @cdrini doesn't have to rerun the code manually? It seem olsystem cron related.

**Comment by mekarpeles** [comment]
This is also now happening to our user borrow counts graph (which we temporarily disable on the homepage live on ol-web3, ol-web4)

**Comment by mekarpeles** [comment]
This looks like our problem:
```
(venv)mek@ol-www1:/opt/openlibrary/olsystem$ sudo -u openlibrary /olsystem/bin/olenv /opt/openlibrary/openlibrary/scripts/ipstats.py  /opt/openlibrary/olsystem/etc/openlibrary.yml
Traceback (most recent call last):
  File "/opt/openlibrary/openlibrary/scripts/ipstats.py", line 12, in <module>
    import infogami
ImportError: No module named infogami
```

**Comment by mekarpeles** [comment]
We need our new Crons on `ol-home0` to run or trigger the following via ssh on `ol-www1`:
 
```source /opt/openlibrary/venv/bin/activate;sudo /opt/openlibrary/venv/bin/python /opt/openlibrary/openlibrary/scripts/ipstats.py  /opt/openlibrary/olsystem/etc/openlibrary.yml from ol-www1```
