### ISSUE TITLE
Have a 'see all' link when looking at a subject

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2484]
Difficult to know what's in the library if it's a google search style where you need to know what to type in in order to find a book

**Comment by cdrini** [comment]
Is this the sort of view you would like? https://openlibrary.org/search?q=subject%3Atravel&mode=everything

**Comment by BrittanyBunk** [comment]
Yes, but it would be for the subjects: https://openlibrary.org/subjects/science. The picture is a rough draft, but that's how it should show.
![Untitled](https://user-images.githubusercontent.com/55302685/66708294-108ef580-ed03-11e9-878e-7a34d32c3b56.png)

**Comment by mekarpeles** [comment]
A lot of these books are powered by archive.org queries behind the scenes, so there isn't a super easy way to "see more" without clicking the link (e.g. Books We Love). There is a similar issue which proposes a solution #602

**Comment by BrittanyBunk** [comment]
@mekarpeles it is really similar. I guess we can close this then.
