### ISSUE TITLE
Slick carousels do not cache requests when loading new items

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2501]
The slick carousel makes multiple requests to the same URI and continues to do so when the right button is clicked even if it has exhausted all available.

### Evidence / Screenshot (if possible)

For example visit https://openlibrary.org/subjects/bacon
Click the right arrow. Notice how the right arrow always triggers an HTTP request.
Click the left  arrow and click the right arrow again - you'll see a repeat HTTP request
When the right arrow becomes inactive, when you click it, there is still another HTTP request!

### Relevant url?
https://openlibrary.org/subjects/bacon

### Expectation
These HTTP requests should be cached and never repeated. When the arrow is inactive there should be no HTTP requests at all.
This might be a bug in Slick or a bug in how we're using Slick-  please investigate and report back!

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by shucon** [comment]
I would like to start working on this issue.
