### ISSUE TITLE
Possibly remove /templates/account/{email, password}.html

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2502]
It looks like these files are unused since we use archive.org for change email / change password. https://openlibrary.org/account 's "update email address" and "change password" now link to archive.org . Also http://openlibrary.org/account/email 405s ( http://openlibrary.org/account/password doesn't, but probably should). (Found on #2494 )

## Stakeholders
@jdlrobson

**Comment by LeadSongDog** [comment]
See #969 
There is value in having access to OL even if one can't access archive.org, please do not throw this out the window.

**Comment by jdlrobson** [comment]
If we keep them we should remove all script tags from the template and document it. I'm okay with either of these outcomes. Assigning to Mek to decide.

**Comment by cdrini** [comment]
@LeadSongDog Note either way the openlibrary change email/password forms don't work; because the accounts are linked to IA, they have to be changed there. So these templates are broken and dead code.

**Comment by mekarpeles** [comment]
These seem removable.
