### ISSUE TITLE
Clean up of the UI of the Subjects page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2504]
https://openlibrary.org/subjects should not look like https://imgur.com/a/DWnYhA2. Instead, it would benefit from looking like https://imgur.com/a/FqazntY. The page could be a very nice directory then. Everything else on the page now can go underneath the re-imagined picture.

**Comment by tfmorris** [comment]
The current page includes:

- separate listings for four different types of subjects (people, places,...)
- hand picked examples for each subject type
- textual listings without pictographic icons

Which are you proposing changing? Or all of the above?

**Comment by BrittanyBunk** [comment]
I'm not proposing changing those - just to push those down the page and add in the layout in the picture to it. I mean, that part could be improved, but idk how right now.

**Comment by mekarpeles** [comment]
I have a demo redesign of https://github.com/internetarchive/openlibrary/tree/refactor/everything and will followup on this post October

**Comment by mekarpeles** [comment]
Merging as duplicate of #2072
