### ISSUE TITLE
Editions in carousels sometimes 404

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2506]
Sometimes, editions that appear in carousels are suffixed with the `/resolve` path, which should only be added to works. This causing these books to 404 when clicked.

### Relevant url?
1. Go to https://openlibrary.org/books/OL26571069M/Critical_studies_in_the_Cynewulf_group
2. Click on the "You might also like" without a cover ( https://openlibrary.org/books/OL26571069M/x/resolve )
3. Get a 404 error.

### Expectation
`/resolve` shouldn't be added and it shouldn't error

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10

### Stakeholders
@BrittanyBunk

**Comment by BrittanyBunk** [comment]
I think you asked where I see it. I see them after clicking on a book - it shows a list of related or books by the author. Want me to start forming a list here of links that I see?

**Comment by cdrini** [comment]
@BrittanyBunk If you could find 2 or 3 books that have this issue in their related books section, that would be great. The only one I've found so far is this one: https://openlibrary.org/books/OL26571069M/Critical_studies_in_the_Cynewulf_group

**Comment by BrittanyBunk** [comment]
When I find them, I'll post here. I saw a lot of them today, but I might not get the chance to do more research, as I pretty much added covers to books that needed them (which is how I found them) and now there's not many left.

**Comment by BrittanyBunk** [comment]
https://openlibrary.org/books/OL26535495M/Mansfield_Park/resolve https://openlibrary.org/books/OL26562070M/Letters_to_her_sister_Cassandra_and_others/resolve. I mean, there's more, but it would take a lot of time for me to look through.

**Comment by cdrini** [comment]
@BrittanyBunk could you provide the page where the carousel was? All those links are correct (if you remove the `/resolve` at the end); but it's unclear why the carousel is adding `/resolve` at the end, so the links to the pages with the carousels would be useful :)

**Comment by tfmorris** [comment]
@cdrini It looks to me like it's happening in the "You might also like" and "More by <author name>" carousels at the bottom of book editions pages like https://openlibrary.org/books/OL26571069M when there's no cover image.

**Comment by BrittanyBunk** [comment]
@cdrini there's too many to list. Even if I gave the few that I know - I mean the last 2 are from the Louisa May Alcott author carousel, that wouldn't resolve the issue.

**Comment by mekarpeles** [comment]
I think specifically this is a cacheing issue as `/x/resolve` has been deprecated (in favor of using `?edition=` to avoid SEO consequences. Had we done this to begin with, regression would have had no breaking changes. Live and learn :)
