### ISSUE TITLE
Book Sponsorship Reading Log wrong book count

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2510]
book count may be incorrect for patron's Reading Log page (for sponsorships tab)

_Originally posted by @cdrini in https://github.com/internetarchive/openlibrary/diffs_

**Comment by cdrini** [comment]
@mekarpeles I fixed this here: https://github.com/internetarchive/openlibrary/pull/2507/commits/54a659581107af316d0516c611732ee975528ddb#diff-b826113089762d07fdb19427b2f9c731R34 ; does that look good, or have you observed this error on prod?

**Comment by mekarpeles** [comment]
@cdrini thanks, yes, lgtm!
