### ISSUE TITLE
Current edition appears in "You might also like" carousel

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2512]
The currently open edition appears in the "You might also like" and "More by {author}" carousels of that edition.

### Relevant url?
https://openlibrary.org/books/OL26571069M/Critical_studies_in_the_Cynewulf_group

### Expectation
It shouldn't show the current book.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10

**Comment by mekarpeles** [comment]
There should be a way to exclude the current title in the Authors carousel within `$:macros.RelatedWorksCarousel(work)`.
It can be filtered out within:
`$ authors = ', '.join([author if isinstance(author, basestring) else author.name for author in work_subjects_authors.get('authors', [])])`

**Comment by lgoenner** [comment]
I'll give this a shot.

**Comment by guyjeangilles** [comment]
@lgoenner Did you make any progress?

**Comment by shaswa123** [comment]
Hey, can I work on this?

**Comment by tabshaikh** [comment]
@shaswa123 sure you can go ahead with it

**Comment by manav014** [comment]
I think the issue is solved as when i opened the link and in the More by {author} section the same book was not mentioned.
![Screenshot at 2020-03-17 23-15-54](https://user-images.githubusercontent.com/51242628/76910198-4c774980-68a5-11ea-8598-d25173bd6928.png)

**Comment by guyjeangilles** [comment]
Also cant duplicate
