### ISSUE TITLE
Work covers not appearing in carousel, even though they have an image

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2514]
Adding onto #2486 
https://openlibrary.org/books/OL2527509M/PX_a_computational_logic is one example of the many in the Authors Alliance & MIT Press with no cover in the carousel, but they have a cover already and it should appear.

**Comment by samuelpetroline** [comment]
Do you have a screenshot or something that could clarify this error?

**Comment by samuelpetroline** [comment]
Also, https://openlibrary.org/publishers/MIT_Press doesn't seem to be working properly, though.

**Comment by BrittanyBunk** [comment]
@samuelpetroline it's not the grey box within a box, but it looks like an off-white box with nothing in it.

**Comment by tfmorris** [comment]
A screenshot would be much better than words for describing a visual problem and an actual URL for the carousel is needed as well.

**Comment by tfmorris** [comment]
@samuelpetroline You don't describe how the page isn't working properly, but I just filed #2519 which likely affects all publisher pages.

**Comment by BrittanyBunk** [comment]
![Untitled](https://user-images.githubusercontent.com/55302685/67058726-f1310780-f10a-11e9-8d13-47c71774d4ea.png)
I didn't really know what to take a screenshot of, but maybe this helps.

**Comment by BrittanyBunk** [comment]
@tfmorris thanks for working on the bug

**Comment by mekarpeles** [comment]
Duplicated by #2550 and #2514

**Comment by guyjeangilles** [comment]
I edited @mekarpeles comment as I don't he meant that this issue is a duplicate of itself
