### ISSUE TITLE
Bad author page is linked to existing author

### ISSUE THREAD

**Issue by samuelpetroline** [internetarchive/openlibrary#2518]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/22039767/67050293-93062380-f10e-11e9-8496-63e518eb2fe0.png)

### Relevant url?

https://openlibrary.org/authors/OL5631454A/James_Tyler_Kent?page=5

### Expectation

There should be only books related to James Tyler Kent

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Proposal & Constraints

Maybe create a new author page for books with unknown/undetected authors?

**Comment by tfmorris** [comment]
Thanks for the report. It looks like a user repurposed ["No name"]( https://openlibrary.org/authors/OL5631454A/?b=5&a=3&_compare=Compare&m=diff) author record

You can find the actual James Tyler Kent record here: https://openlibrary.org/authors/OL2746340A
