### ISSUE TITLE
Publishing History graph doesn't load - missing graph data

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2519]
The publishing history graph never loads, instead displaying the spinning barber pole icon.

The error message in the Javascript console is:

```
MIT_Press:1 A cookie associated with a cross-site resource at http://archive.org/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
jquery-migrate.js:21 JQMIGRATE: Logging is active
index.js:248 Possible Unhandled Promise Rejection: Error: No data associated with ebooks - make sure a script tag with type text/json and id "graph-json-ebooks" is present on the page.
    at plot.js:221
    at r (plot.js:248)
    at r (index.js:21)
    at Module.l (index.js:32)
    at index.js:102
    at index.js:57
    at setImmediate.js:40
    at f (setImmediate.js:69)
    at r (setImmediate.js:109)
```

### Relevant url?
https://openlibrary.org/publishers/MIT_Press

### Details

Google Chrome Version 77.0.3865.120 (Official Build) (64-bit)

### Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
The relevant error is
Error: No data associated with ebooks - make sure a script tag with type text/json and id "graph-json-ebooks" is present on the page

The data for the graph is not being added to the html.

**Comment by tfmorris** [comment]
There's an element:

`<script type="text/json+graph" id="graph-json-chartPubHistory">[[1485, 1], ...]</script>`

which looks pretty close. Not sure whether it's the type or id (or both) that it's unhappy about.

**Comment by tfmorris** [comment]
@mekarpeles @jdlrobson #2360 https://github.com/internetarchive/openlibrary/commit/01a260e25f9ff89a87224530447fa71d4557a1d7#diff-283bc0ed7283cd22eecfd541b629cd77 looks like a likely suspect.

**Comment by jdlrobson** [comment]
If one graph fails to not be found the ones that follow will also fail.

I think what's happening here is the id ebooks is being used for two purposes:

class="ebookcount"><span id="ebooks">2,909 ebooks</span>

Fix should be changing this id or the id of the ebooks graph and associated json wherever it is.

**Comment by guyjeangilles** [comment]
It looks like @jdlrobson is working on a PR to fix this issue. I recommend he be assigned to this issue. Let me know if you agree or disagree.
