### ISSUE TITLE
Improve mobile CTA on Editions pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2531]
Read/borrow button appears far below the fold on mobile UI for editions page

### Screenshot

<img alt="openlibrary org_books_OL25930651M_The_Three-Body_Problem(Pixel 2)" src="https://user-images.githubusercontent.com/978325/67164980-ca561980-f334-11e9-9188-62c47e5ee829.png" width="300">

### Relevant url?

https://openlibrary.org/books/OL25930651M/The_Three-Body_Problem

### Expectation

Show CTA much higher -- e.g. under the bookcover

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Proposal & Constraints

The read/borrow CTA button may be duplicated under or above the Want to Read button and show when the right mobile breakpoints are triggered

**Comment by cecyc** [comment]
I can work on this! 🙋

**Comment by guyjeangilles** [comment]
@cecyc Since you volunteered to work on this project, I am making you assignee and changing the state of this project to work in progress.

**Comment by mekarpeles** [comment]
@cecyc do you have a proposal for how this should be implemented? You may want to look at `macros/LoanStatus.html` and how it's used already within `openlibrary/templates/type/edition/view.html`. 

We'll probably want the LoanStatus button to be above the `Want to Read` -- i.e. `$:render_template("lists/widget", page, include_header=False)` -- button, but hidden on desktop (and visible when mobile) within the `editionCover` block.

If you're wondering where the read/borrow button is coming from...

`openlibrary/templates/type/edition/view.html` is the edition page which calls...
`$:macros.databarWork(page, editions_page=True)` which is in `openlibrary/macros/databarWork.html` which calls..
`$:macros.LoanStatus(page, ctx.user, editions_page=editions_page, block_name="read-options-panel")` -- this call will need to be adjusted slightly and added into the `editionCover` block described above.

**Comment by cecyc** [comment]
@mekarpeles thank you! I was a bit stuck trying to figure out the best way to pull in that element, but this should hopefully set me in the right path, thank you!

**Comment by cecyc** [comment]
@mekarpeles have a PR [here](https://github.com/internetarchive/openlibrary/pull/2586). Let me know your thoughts! Thanks!

**Comment by mekarpeles** [comment]
We'll take a look as soon as we can! Thank you for your hard work on this @cecyc
