### ISSUE TITLE
Discussion: In which cases should illustrators be considered work-level authors?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2539]
In general, illustrators should be added at the edition-level. However, there are cases where it may be appropriate to list the illustrator at the work-level. 

One fairly obvious case would be works that are graphic-only. But how about children's picture books where the illustrator gets top billing on the cover? Many adapted classics do not list the author responsible for the adapted text but list only the original author and the illustrator; including the illustrator at the work-level can help differentiate between various adaptations.

How about graphic novels?

**Comment by guyjeangilles** [comment]
Adding a work in progress label per the [Managed label wiki](https://github.com/internetarchive/openlibrary/wiki/Using-Managed-Labels-to-Track-Issues)

**Comment by LeadSongDog** [comment]
Opinion: this should hinge on the question “Is the original work graphic or textual?” Captions don’t make a photo narrative into a storybook. An “illustrator” bases their graphics on existing text without changing that text. If the publisher of the first edition identifies an “illustrator”, it should be clear.

**Comment by seabelis** [comment]
For example, in this work I would argue the illustrator should be top-level even though the text is Shakespeare's. Any arguments against in such cases? https://openlibrary.org/books/OL8065444M/Shakespeare's_Garden

**Comment by dcapillae** [comment]
Hi,

I've consulted a bibliographic description manual. It says that the illustrator's name should be registered as top-level author only if it appears prominently in the document.

In the case of _[Shakespeare's Garden](https://openlibrary.org/books/OL8065444M/Shakespeare's_Garden)_, the illustrator's name appears prominently in the document, and the illustrations seem to be an essential part of the work. I think it would be a good idea to consider the illustrator as an top-level author/co-author in this case.

**Comment by BrittanyBunk** [comment]
@seabelis I personally don't believe an illustrator is an author unless they wrote words in the pictures or the captions. I mean, there is the saying 'a picture is worth 1000 words', so if we start counting pictures as words from this saying, sure. I just don't agree with that line of reasoning. However, if the bibliographic description manual says yes, I'd go with the standards, not me.

**Comment by seabelis** [comment]
In some cases the illustrations are the reason the book exists. As in the case I linked to, Shakespeare's text was added to the illustrations, but as @dcapillae points out, the illustrations are an essential part of the work. 

In agreement with @dcapillae . Closing.

**Comment by BrittanyBunk** [comment]
@seabelis I'm not discrediting that the illustrator plays an author-status role. The issue is that adding them as an author there doesn't make sense. The issue is that OL doesn't distinguish roles at the work level. This probably should be another, new issue if we do add illustrators to the work level. Then, the most important contributors would be there, but it'll be shown who they are (otherwise it'll show that the illustrator is the author when they may not be).

**Comment by LeadSongDog** [comment]
@BrittanyBunk #2500 relates, discussion is closely parallel. 
@seabelis The difficulty with your example of _Shakespeare's Garden_ is that Pallan's contribution was to a late edition, after J. Harvey Bloom's copyright had expired in the US. The 1903 Lippincott / Methuen edition had only four illustrations.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I think your right and onto something. There was another discussion I was in (I can't find it) where it was about separating works and editions more clearly in the editing section. If works are separated out from editions more, then it could have its own profile. Do you know the #?

My opinion is that it's not about who's important enough to be up there, but who is listed in a work that should be there - there's no priority of one over another outside of an author.

Do you think I should create a new issue as I outlined 2 comments up? Should I also create one about separating the works from editions in the editing page?

**Comment by seabelis** [comment]
> Should I also create one about separating the works from editions in the editing page?

Check if there is already an issue. This has come up, but maybe only on the community call.

**Comment by seabelis** [comment]
@LeadSongDog 

> The difficulty with your example of Shakespeare's Garden is that Pallan's contribution was to a late edition, after J. Harvey Bloom's copyright had expired in the US. The 1903 Lippincott / Methuen edition had only four illustrations.

I would not consider https://archive.org/details/shakespearesgard00nanc/page/n11 an edition of https://archive.org/details/shakespearesgar00bloogoog/page/n7. True they share the same name and general concept, but one is not simply a later version of the other with the addition of illustrations. The Pallan version is primarily a book of illustrations accompanied by Shakespeare's words. Bloom's is a book of quotations and is primarily text.

**Comment by seabelis** [comment]
@BrittanyBunk A better label for the work-level field would be 'Responsibility', but that's a different topic.

**Comment by LeadSongDog** [comment]
@seabelis You’re right. The newer book discards most of the older.

**Comment by BrittanyBunk** [comment]
> > Should I also create one about separating the works from editions in the editing page?
> 
> Check if there is already an issue. This has come up, but maybe only on the community call.

@seabelis I looked all night (like for 1-2 hours) and couldn't find it. I need help finding it.

**Comment by BrittanyBunk** [comment]
> @BrittanyBunk A better label for the work-level field would be 'Responsibility', but that's a different topic.

@seabelis "responsibility' is a confusing term, as everyone's responsible for the book. Maybe 'top contributors', or 'creators' would be better. Like the top contributors could be starred?

**Comment by LeadSongDog** [comment]
@seabelis The issue you are recalling is #2241 

@BrittanyBunk The term Responsibility is explained clearly on the OCLC site:

> Responsibility | Statement of responsibility for an item. For a book, this is typically the author(s); for other types, this statement may include: editor, actor, producer, composer, director, and production company, or other creative participant.
-- https://help.oclc.org/Discovery_and_Reference/WorldCat-org/WorldCat-org_Item_Details_screen/About_the_Item_Details_screen

It is, perhaps a bit simplistic in its use of "book" to mean a printed text, but the general idea is correct.

**Comment by BrittanyBunk** [comment]
@LeadSongDog since that's not the same as the issue I'm thinking about, do you know of the # on github? If not, I'll create it. 

For your link, it's the one with the sole responsibility. Illustrator is not that person. The examples listed are replacements for author: some use 'editor', which is fine. Producer is the equivalent of an author too. I don't see 'illustrator' as replacing the author (unless they wrote words in the illustrations themselves, in which they truly are the author, or the book is only a picture book with no words - in which the replacement is fine). What @seabelis and you are talking about is a co-author, in which that requires a new designation, which I suggested 'top contributor' or 'creators' or even 'top creators' for that. I like the last one best.
