### ISSUE TITLE
Add a box for copyright company name

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2542]
It's different than the publisher and I feel it would help to have - to prevent confusion.

**Comment by cdrini** [comment]
@BrittanyBunk can you provide an example? That will help make it easier to see what the final format should look like.

**Comment by BrittanyBunk** [comment]
http://ce.sharif.edu/courses/96-97/1/ce153-6/resources/root/Books/C%20How%20to%20Program%20(Deitel%206e).pdf
Deitel & Associates, Inc. http://www.deitel.com/Deitel/AboutDeitelAssociatesInc/tabid/196/Default.aspx content provider and did the publication (I believe Prentice Hall did too http://prenticehall.com/)
Prentice Education Inc. is the company who the copyright is under (https://www.pearson.com/us/higher-education.html - shows they have 'products and services')

**Comment by BrittanyBunk** [comment]
If that's not a good example, I could try to find another

**Comment by seabelis** [comment]
It is fine to enter the full copyright statement in the copyright field.
