### ISSUE TITLE
Book sponsorship carousel is not optimised for mobile

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2547]
### Evidence / Screenshot (if possible)
<img src="https://user-images.githubusercontent.com/148752/67410897-a0d60180-f571-11e9-9776-660ecb3a9152.jpg" width="300px">

This is likely due to this issue further down the page
<img src="https://user-images.githubusercontent.com/148752/67411147-032f0200-f572-11e9-82a6-cc385fdb36b5.jpg" width="300px">

### Relevant url?

https://openlibrary.org/sponsorship
### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by mekarpeles** [comment]
Relates to #2566

**Comment by guyjeangilles** [comment]
Looks like the image isn't being scaled but I haven't investigated the templates

**Comment by tabshaikh** [comment]
Taking up this one :)

**Comment by tabshaikh** [comment]
This is due to the image size and same bug occurs here too https://openlibrary.org/help/faq/editing

**Comment by mekarpeles** [comment]
@tabshaikh any updates on this? Do we have a PR in review?

**Comment by tabshaikh** [comment]
Closing this issue as pr merged by @mekarpeles  #2756
