### ISSUE TITLE
Borrowable works should always have bookcover (fallback to IA)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2550]
On the search page, we have a lot of books on Open Library that are borrowable and don't have (work) bookcovers. In these cases, if we are seeing the borrow button, it's because we've identified an `ocaid` (i.e. archive.org identifier) for a book which is available. We should fallback to this archive.org item's cover URL if no work cover exists.

`https://archive.org/download/%s/page/cover_w%s_h%s.jpg` (see plugins/upstream/models)

### Evidence / Screenshot (if possible)

![openlibrary org_search_q=doctor mode=ebooks m=edit m=edit has_fulltext=true](https://user-images.githubusercontent.com/978325/67494131-96793d80-f62d-11e9-9661-813d55e7e1b1.png)

### Relevant url?

https://openlibrary.org/search?q=doctor&mode=ebooks&m=edit&m=edit&has_fulltext=true

### Expectation

Works in search results should always show a bookcover if there is a an edition which is borrowable (because we know we have at least 1 edition which is scanned / has a cover)

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 

### Proposal & Constraints

I know that (due to services being blocked in certain geographic locations) @leadsongdog feel strongly about not having openlibrary.org depend on archive.org where possible. Open to alternative solutions, e.g. an OL proxy for archive.org covers (via coverstore -- covers.openlibrary.org -- which maybe exists already) or saving the cover in coverstore (which seems like it could be wasteful)

**Comment by BrittanyBunk** [comment]
Why not let the bot use the preview feature you implemented to do so? Or, when a book's uploaded, it could ask the uploader to match it with the Open Library page and add a book cover. That way, the uploader can set it up rather than relying on a bot to do so - as they don't get it right a lot of the time.

**Comment by Ignatiusdork** [comment]
Hi, am new to the oss, and i would like to be assigned to this issue, some pointers will be helpful alot @mekarpeles .Thanks

**Comment by mekarpeles** [comment]
@Ignatiusdork yes please!
Related to: #2514 

Any time a cover doesn't exist for a book on Open Library and we have an Archive.org identifier (i.e. an `ocaid`) for that book, we can fallback to https://archive.org/services/img/{ocaid}

e.g. https://archive.org/services/img/TheGeometry

There's two files to look at:
1) openlibrary/templates/books/custom_carousel.html
2) openlibrary/macros/SearchResultsWork.html

**Comment by mekarpeles** [comment]
![67058726-f1310780-f10a-11e9-8d13-47c71774d4ea](https://user-images.githubusercontent.com/978325/67731702-51029a80-f9b6-11e9-8435-c93a6bc626c0.png)
Here's another screenshot provided by @BrittanyBunk

**Comment by mekarpeles** [comment]
More important context here:
https://github.com/internetarchive/openlibrary/issues/2486#issuecomment-546663814

**Comment by guyjeangilles** [comment]
@Ignatiusdork Have you made any progress on this issue?

**Comment by guyjeangilles** [comment]
Also #2447 is tangentially related

**Comment by hornc** [comment]
One of the effects of my https://github.com/internetarchive/openlibrary/pull/2838 work (which is not properly merged yet) is that books imported from archive.org are substantially more likely to have covers directly in coverstore. It plugs a loophole where fully scanned books would not save an image because the importer wasn't trying all the available options.

There is a potential re-import task to pass over all books with lendable copies to retrieve a cover image using this new code.

**Comment by guyjeangilles** [comment]
There's a bandaid in the works for this at [the bits repo](github.com/internetarchive/openlibrary-bots/pull/38)

**Comment by BrittanyBunk** [comment]
@guyjeangilles says page not found - is this an admin-only page?

**Comment by manav014** [comment]
Hi. I am looking for projects to participate in for the GSoC. Based on listening to others, looking at the effort on this Github issue, and seeing no one assigned to this yet, After adding some more features, I decided this is a great project to be assigned to (as I can work alongside others that are currently focusing on this too). Would it be ok for me to be assigned to this project for the GSoC?

**Comment by guyjeangilles** [comment]
@brittanybunk the url is https://github.com/internetarchive/openlibrary-bots/pull/38

@manav014 feel free to make a pull request with a proposed solution

**Comment by BrittanyBunk** [comment]
@guyjeangilles Mind if I add some descriptors to these files? It's really difficult for me to know what's going on just by the file title alone. Like I would put something into the readme so I could follow along better.

**Comment by guyjeangilles** [comment]
@BrittanyBunk feel free to comment on the PR. The script is still just a draft.

**Comment by manav014** [comment]
@mekarpeles  @guyjeangilles  Please review this proposal for GSoC 2020 which will not only solve the above problem but even have many other proposed ideas.
[💻 GSoC Proposal - Internet Archive [Open Library].docx](https://github.com/internetarchive/openlibrary/files/4384784/GSoC.Proposal.-.Internet.Archive.Open.Library.docx)
