### ISSUE TITLE
RedirectBot Phase 1: Fix past stale redirect backrefs

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2553]
#2552

There are 524k redirects as of Oct 1, 2019. How many of these redirects are referenced by 
Should be able to run as a 1-off task (w/ option to be run monthly)

- [x] Find where backrefs to olids occur between types e.g. a list->?(redirect), edition->Work(redirect), edition(orphan)->Authors(redirect).
  * Authors can contain user added links in their descriptions, but not it the data model. 15 authors have descriptions which link to redirects. Not a high priority?
  * Works link to Authors
  * Editions link to Works, and sometimes Authors.
- [x] #5999
- [x] Correct/enforce that there are no chains of redirects (there are unfortunately quite a few: 29K )
  - Use dumps to replace any redirect olid with its target
    - [x] Works (1114)
    - [ ] Editions (115551)
    - [ ] Lists (?)

**Comment by hornc** [comment]
some commands to extract the first steps:
`# extract olids -> location in tsv`
`fgrep "/type/redirect" ol_dump_2019-09-30.txt | sed 's/^\/type\/redirect\t\([^\t]*\).*location": "\([^"]*\)".*$/\1\t\2/' > redirects_2019-09-30.tsv`


Number of redirects found:
`526416 redirects_2019-09-30.tsv`

Number of 'chains'  (where a target location itself is a loop) in redirects:
```
comm -12 <(cut -f1 redirects_2019-09-30.tsv|sort) <(cut -f2 redirects_2019-09-30.tsv|sort) | wc -l
9904
```

**Comment by hornc** [comment]
"types" with redirects:

```
about
authors
books
dev
type
work
works
```

these are the id prefixes, e.g. ` /about/<id>`  or `/dev/docs/wikilanguage` => `/dev/docs/infogami`

Ids with `work` were unexpected, but should be easy enough to resolve.

**Comment by hornc** [comment]
These are some more author redirects discovered in the data to clean up specifically:

Not found: https://openlibrary/a/OL3208068A
Not found: https://openlibrary/a/OL6811959A
Not found: https://openlibrary/a/OL18298A
Not found: https://openlibrary/a/OL1776193A
Not found: https://openlibrary/a/OL6199832A

OL1122551A	Jean Little
OL581085A	André Bernard
OL5622415A	Nigel Hamilton
OL66452A	Miguel de Cervantes Saavedra
OL18404A	Homer
OL22105A	Aristotle
OL18290A	Brothers Grimm

**Comment by cdrini** [comment]
Useful queries (as run on OJF dump)

Find redirects. All occurrences of `"Key"` in the db will need to be replaced with the second `"Location"`
```sql
SELECT "Key", "JSON" ->> 'location' as "Location"
FROM "test"
WHERE "Type" = '/type/redirect'
LIMIT 10
```

Sample output:


Key | Location
-- | --
/authors/OL1015899A | /authors/OL281117A
/authors/OL102364A | /authors/OL6048760A
/authors/OL1065799A | /authors/OL524120A
/authors/OL1115140A | /authors/OL105507A
/authors/OL1149754A | /authors/OL129416A
/authors/OL1162915A | /authors/OL953789A
/authors/OL1199834A | /authors/OL918621A
/authors/OL1220109A | /authors/OL321048A
/authors/OL1230900A | /authors/OL707251A
/authors/OL125161A | /authors/OL116384A

**Comment by cdrini** [comment]
Query to get all references of a document:

```sql
SELECT
    "Key",
    unnest(regexp_matches("JSON"::text, '/[^/]+/OL\d+[A-Z]', 'g')) as "References",
    "JSON"
FROM (SELECT * FROM "test" WHERE "Type" = '/type/work' LIMIT 50) AS sample
```

**Comment by cdrini** [comment]
And then some joining. We want the list of document we have to edit, and the find/replace we have to do. i.e. we want a table with columns `Key | ReferenceToReplace | ToReplaceWith`.

That'll look something like (untested; still waiting for previous)

```sql
SELECT
    "references"."Key",
    "references"."References" as "ReferenceToReplace",
    "redirects"."Location" as "ToReplaceWith"
FROM "references", "redirects"
WHERE "redirects"."Key" = "references"."References"
LIMIT 5
```
