### ISSUE TITLE
Better integration of project gutenberg's material

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2565]
Right now, the 'text's are in a txt or img format. That's difficult to integrate into the Open Library. I would like to recommend contacting Project Gutenberg to create complementary pdf's for their html texts to incorporate into the Open Library.
project gutenberg: https://archive.org/details/gutenberg/downloader/index.php?tab=collection
example: https://archive.org/details/cookeryanddining29728gut
ideal html of example to convert to pdf: http://www.gutenberg.org/files/29728/29728-h/29728-h.htm
example location on open library: https://openlibrary.org/search?q=apicius&author_key=OL4645453A&m=edit&mode=ebooks&has_fulltext=true

**Comment by tfmorris** [comment]
They also distribute texts in HTML and ePUB formats. I would have thought that ePub which is supported natively by online bookreaders would be much more desirable than PDF.

**Comment by BrittanyBunk** [comment]
I prefer PDF, because while the epub format's for tablets, PDF's for both tablets and computers. Also, it doesn't capture the formatting well enough to always use.

**Comment by mekarpeles** [comment]
I think this is going to have to be solved by the IA Product team (they know about it), tagging @bfalling and closing.

**Comment by BrittanyBunk** [comment]
@mekarpeles Awesome. I should've closed this sooner. Thanks!
