### ISSUE TITLE
Close button is underlined/hard to press in dialog popup

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2583]
Continuation of #2489

- [ ] Close button shouldn't be underlined
- [ ] increase padding of close button so it's easier to click

### Evidence / Screenshot (if possible)
Underlined:
![image](https://user-images.githubusercontent.com/6251786/67715209-99a25f80-f986-11e9-9c11-19f3fe88c05a.png)

And hard to hit
![image](https://user-images.githubusercontent.com/6251786/67715589-5bf20680-f987-11e9-8d1f-9ea5b4dc3a68.png)

### Relevant url?
e.g. click preview  http://localhost/books/OL2058361M on local

- **Logged in (Y/N)?** N
- **Browser type/version?** FF69
- **Operating system?** Win10

### Stakeholders
@jdlrobson

**Comment by jdlrobson** [comment]
Last time i checked 44×44 pixels was the recommended size for anything displayed on mobile.

**Comment by imskr** [comment]
Can I work on this issue?

**Comment by jdlrobson** [comment]
@imskr yes. To be clear - we want to remove the underline and expand the touch area to 44×44 per https://www.w3.org/WAI/WCAG21/Understanding/target-size.html (make sure to document that in the code pointing to this url!)

Thank you!

**Comment by guyjeangilles** [comment]
@imskr Have you made any progress on this issue?

**Comment by mekarpeles** [comment]
Howdy @imskr just double checking, would you like to try this good first issue? If so, let me know and I'd be happy to help you.
