### ISSUE TITLE
Edition page, tablet mode: Include full-width want-to-read + add read button

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2597]
The UI looks a bit funky in tablet mode (looks good in mobile / desktop). We should probably show both the read button and the full-width want-to-read button in this tablet mode.

@jdlrobson @cecyc do you think this should be a followup issue or fixed in this branch? I'm supportive of either.

**Today:**
![dev openlibrary org_books_OL25930651M_The_Three-Body_Problem (1)](https://user-images.githubusercontent.com/978325/68061665-44868680-fcc3-11e9-9a12-b6c46148d3ba.png)

**Should be**
![image](https://user-images.githubusercontent.com/978325/68061907-75b38680-fcc4-11e9-8e50-e2041d3889a7.png)

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/pull/2596#issuecomment-548981603_

**Comment by guyjeangilles** [comment]
Assigning jdlrobon (not tagging per request) per slack discussions

**Comment by jdlrobson** [comment]
@mekarpeles I think we hid lists in the new redesign and this is not relevant any more so closing this out. Please reopen if I'm wrong.
