### ISSUE TITLE
Homepage "Features" Carousel

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2599]
Folks often get confused when they land on our homepage. We can fix that!

### Describe the solution you'd like

A carousel of cards on the homepage which explain what Open Library is (and how you may use it). e.g.

1) We have 3M+ books to read, borrow, and listen to
2) You can sponsor a book
3) Full-text search across millions of books
4) Want-to-Read

### Project Proposal

https://docs.google.com/document/d/1fjZ2udF9ZfdfRqNJ8hmPd90ip34tzbXiNpVx4PRBKfk/edit

### Additional context

Design inspiration
![testing openlibrary org_1337_ (2)](https://user-images.githubusercontent.com/978325/120879008-222aae00-c575-11eb-979d-eed2908ba843.png)

**Comment by prakashaditya369** [comment]
I would like to work on this issue.
It would be really helpful if we can tell people what they can do at open-library and help them explore.

**Comment by ArunTeltia** [comment]
I have been working on my gsoc proposal and was looking for the carousal , and as discussed in the meeting that we are looking for some kind of carousal library like slider.js we can also have a look at owl carousal
https://owlcarousel2.github.io/

Here is the image of it
![carousal](https://user-images.githubusercontent.com/43555219/112731319-79504900-8f5c-11eb-8824-e98f49672b1c.PNG)

Please have a look @mekarpeles

**Comment by mekarpeles** [comment]
@RayBB is there any chance you may be willing to spec some of this out with me and @cdrini? I'm going to be annoying and add you as a placeholder assignee :D

**Comment by RayBB** [comment]
@mekarpeles I may be able to help out with this but have a few questions for everyone.

> Folks often get confused when they land on our homepage. 

* How do we know this? (is it bounce rate or patron messages or ?)
* Do we know where these folks are coming from?
* How would we measure success with this feature?


Based on the original post it seems that this ticket may be narrowly focused on first time visitors to the site. Basically a way to show them the ropes really quickly.

In my opinion, the quickest way to get something out there would be a short dismissable banner that says something like: "New to Open Library? Watch this short video to see what we offer"

If we wanted to engage all users by showing them tips for features (especially new ones) that could be another cool project but perhaps not the most efficient way to address the problem of new visitors bouncing (if that is the problem).


# Related examples

Pycharm's [tip of the day](https://www.jetbrains.com/help/pycharm/using-tips-of-the-day.html)
<img width="607" alt="image" src="https://user-images.githubusercontent.com/921217/116946942-2e8ab680-ac17-11eb-9d6c-6c72430adf7b.png">

* [Wikipedia has a tip of the day](https://en.wikipedia.org/wiki/Wikipedia:Tip_of_the_day)
* Apple's [Tip's app](https://apps.apple.com/us/app/tips/id1069509450)
* Google's [Pixel tips app](https://www.youtube.com/watch?v=3-7NbkSSuNk).

Trello has a tips section:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/921217/116947958-c1c4eb80-ac19-11eb-9878-b98eea67b9eb.png">

[Examples of using tooltips for onboarding](https://www.appcues.com/blog/feature-adoption-tooltips)

There's also the idea of new user (or first time visitor welcome banners) welcome banner [like msft has](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/administration/onboarding-welcome-banner).

There is also product tours / feature tours / boarding flows [like Intercom's](https://www.youtube.com/watch?v=TyWefNd1Tlc).

**Comment by mekarpeles** [comment]
@Sabreen-Parveen do you mind commenting on this thread so I may add you as the assignee?

**Comment by Sabreen-Parveen** [comment]
@mekarpeles I would like to work on this issue :D

**Comment by mekarpeles** [comment]
This has been merged :tada:
