### ISSUE TITLE
Lists are not stored in any of the dumps

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2609]
The full dump on https://openlibrary.org/developers/dumps does not include lists.

### Expectation
Since they are public, they should be included. Note there are concerns because the key for a list includes the user's name (e.g. https://openlibrary.org/people/ScarTissue/lists/OL139466L/Test_Sep_2019 ).

### Proposal & Constraints
Have a separate dump with keys that do not include username; e.g. https://openlibrary.org/people/ScarTissue/lists/OL139466L/Test_Sep_2019 can use as a key `/lists/OL139466L` (maybe)

### Related Files
https://github.com/internetarchive/openlibrary/blob/60175f143dcdc7db15992f29e0ab5cc2d620ab72/scripts/oldump.py

### Stakeholders
@hornc

**Comment by tfmorris** [comment]
Private lists (#3456) and reading logs should **NOT** be included in the dump.
