### ISSUE TITLE
Display "Sponsor" button in editions table

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2617]
Display the sponsor button on the editions table in the works page for easier discoverability.

### Proposal & Constraints

- There are rate limits on the APIs we access to determine sponsor-ability, so we can't call it for every edition of a work. We should have some heuristic functions (that don't hit those APIs) that can filter out the majority of editions, so we perform the check on max 1 edition per work.
- If sponsorability exists in cache, we should display it.
- Questions exist about how to display the price; we don't want to display the little blurb for every sponsorship button in the table.
- We probably won't have a lot of API rate issues; works with a lot of editions are likely already readable/lendable, so we only have to worry about works which have few editions already.

### Additional context

e.g. https://openlibrary.org/works/OL16029764W/Green_is_the_new_red

### Stakeholders
@mekarpeles

**Comment by worldpartner-0322** [comment]
アホか！こっちは40000円以上負けてるんやぞ！何で金払わなアカンねん。

**Comment by guyjeangilles** [comment]
Deleted [worldpartner-0322's](https://github.com/worldpartner-0322) comment as it was almost certainly spam (they made there account the same day as making the below comment).
![2617](https://user-images.githubusercontent.com/7256157/69584311-c7ee7b80-0fd4-11ea-9f46-e6c6f1cb63f6.png)

**Comment by mekarpeles** [comment]
Sponsorship program is currently on hiatus
