### ISSUE TITLE
MARC Import accepts some AV material

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2622]
Example: https://openlibrary.org/show-records/marc_openlibraries_sanfranciscopubliclibrary/sfpl_chq_2018_12_24_run01.mrc:174046:685

https://openlibrary.org/books/OL26881959M/ASL_Bible_Luke_1-3_(30_min_clr_1982)_VHS

The import process does reject non-book items, and also serials. Why dis this item get through?

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by hornc** [comment]
relates to #2404

**Comment by mekarpeles** [comment]
@hornc should we close this? Is there anything more we're actively positioned to do?
