### ISSUE TITLE
ISBN star queries no longer work

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2623]
### Relevant url?
https://openlibrary.org/search?q=isbn%3A02620%2A&mode=everything

### Expectation
It should give results

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10

### Stakeholders
@LeadSongDog @tfmorris

**Comment by hornc** [comment]
@cdrini I had no idea this ever was a feature ;)

**Comment by cdrini** [comment]
Haha, me neither actually; but now I want to use it :P Found the link on #372

**Comment by hornc** [comment]
@cdrini actually, I think some of the recent ISBN processing standardisation may be catching the `isbn` query strings and sanitising them , as discussed in #609 

I wasn't aware the passing `isbn:978*` to Solr was a feature, so it hasn't be catered for in the ISBN standardising.

**Comment by LeadSongDog** [comment]
With standardizing, what form is the ISBN being stored in? A string of 13 digits without hyphens?

**Comment by cdrini** [comment]
This appears to work now! Note `isbn:978*` fails as a result of search sometimes erroring if there are tooo many results (there's an issue I can't find...)

**Comment by LeadSongDog** [comment]
Well, it sort of works now, but these queries should get the same results (and don’t):
https://openlibrary.org/search?q=isbn%3A978-02*&mode=everything
https://openlibrary.org/search?q=isbn%3A97802*&mode=everything
