### ISSUE TITLE
Amstrad CPC is missing from the Archive Library

### ISSUE THREAD

**Issue by nonom** [internetarchive/openlibrary#2630]
Emularity supports Amstrad CPC6128/CPC464 emulation it and it's working flawessly in any browser, so I would like to contribute the full Amstrad CPC archive since its legit to share. But seems the Amstrad metatags aren't allowed yet.

DSK images from Amstrad cpc6128 / cpc464 are much like ZX Spectrum. 

Any clue how to make them to work? They aren't already listed
https://www.archiveteam.org/index.php?title=Emularity
http://digitize.archiveteam.org/index.php/Internet_Archive_Emulation
Thanks and congratulations <3

**Comment by hornc** [comment]
Hi @nonom thanks for finding Open Library! Technically this is not the right place for archive.org upload questions (which I think is what you are asking), but I'm trying to find out who to pass this on to get you an answer. Hang tight, I'll see what I can do.

**Comment by nonom** [comment]
Thanks horn, I tested with https://archive.org/details/amstrad_abadia_del_crimen_64 buy maybe the Emulator value could be wrong.

Sorry if not is the right place. Got the point. And thanks again for your effort.

**Comment by hornc** [comment]
@nonom I have reached out to @textfiles, but I also was cheeky and guessed a change to your item, which I think solves the problem, at least it runs for me, but the screen resolution looks off. There may be further metadata settings for that. but  `emulator` should be `cpc6128` which I got from https://wiki.mamedev.org/index.php/Driver:Amstrad    

 You should be able to set emulator to `cpc6128` for anything you upload. It probably wasn't provided as an option if these are the first items of that type.  Hope that helps, I think you should be good to keep uploading and if there are any other issues they can be cleared up later.

Apologies to others for continuing being off-topic ;) -- in general this sort of qn should go to info@archive.org , but I happened to be interested, and saw a way to help. Open Library is specifically books related, although any readable book data are stored on archive.org exactly in the same way the emulator/software items are.

Closing the issue as done / off-topic, but if you reply here, I'll see. Cheers!
