### ISSUE TITLE
Clicking "history" on wiki pages does not open history

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2637]
The history link doesn't seem to work on wiki pages.

### Relevant url?
e.g. https://openlibrary.org/help/faq/editing , but any non-edition/non-work/non-author page

### Steps to Reproduce

1. Go to any wiki page (e.g. https://openlibrary.org/help/faq/editing )
2. Click the "History" link at the top

* Actual: Nothing happens
* Expected: Navigates to https://openlibrary.org/help/faq/editing?m=history

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
Haven't done serious investigation but it looks like some HTTP requests are made but they redirect back to the original page.

**Comment by tfmorris** [comment]
I don't think it's a redirect. It's just a self link to the same page because the href is missing the `?m=history` query string.

**Comment by mbasil09** [comment]
> I don't think it's a redirect. It's just a self link to the same page because the href is missing the `?m=history` query string.

where can i find the html file for this page?
