### ISSUE TITLE
Possibility for multiple subtitles

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2639]
Right now, it's possible to have only one subtitle per work/edition. Yet, I see many books with 2 subtitles (I'm not sure what to call it, a subtitle and something else - maybe secondary subtitle). To have an option for an additional description box for the extra subtitle would help. Here's an example: https://openlibrary.org/books/OL2029162M/untitled

**Comment by tfmorris** [comment]
What do you consider the "secondary subtitle" for this? Library cataloging standards don't provide for more than one subtitle. 

The MARC record for this has it cataloged as:

> 245 $aThe healing herbs :$bthe ultimate guide to the curative power of nature's medicines /$cby Michael Castleman ; medical reviewer, Sheldon Saul Hendler.

which comprises  the title ($a), subtitle ($b) and "by statement" ($c)

**Comment by BrittanyBunk** [comment]
Someone removed it, but it's supposed to have: "remedies for over 200 diseases & conditions" somewhere. A lot of books have some attention grabber, like "New York Times Bestseller", "Now with a CD", etc. It'll be good to have maybe a "feature" box or something like that that's on the cover.

**Comment by seabelis** [comment]
Those blurbs would not really qualify as subtitles. That's more marketing/cover design although it can be ambiguous. The title should be taken from the title page if you have access to it. In this case, there is an LCCN; if you're not sure if something is the subtitle or not and you have the LCCN, you can see how it's listed there. VIAF is also a good resource; especially for early works. OCLC (Worldcat) is another place to check.

**Comment by BrittanyBunk** [comment]
@seabelis that's true, which is why I'm proposing a new box for this information (as it's important, at least to me, to read - as it distinguishes editions from each other at the very least - as I look at editions and wonder what the difference is and this would help. It also helps me see what's on the cover without having to click the cover image and look around).
