### ISSUE TITLE
Separate new accounts/lists from rest of 'recent changes' 'by humans

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2640]
https://openlibrary.org/recentchanges?#humans

**Comment by BrittanyBunk** [comment]
it may help with preventing people from writing over each other's work and also increases the capability for double-checking/adding on

**Comment by tfmorris** [comment]
Like https://openlibrary.org/recentchanges/edit-book#humans, https://openlibrary.org/recentchanges/add-book#humans,
and https://openlibrary.org/recentchanges/merge-authors#humans ?

**Comment by BrittanyBunk** [comment]
yes, that would be good. Where does one access those?

**Comment by guyjeangilles** [comment]
So is this about make an existing feature more accessible or adding new functionality? It looks like recents lists made by humans exists or am I misunderstanding the question?

**Comment by tfmorris** [comment]
Tagging it as a feature enhancement is fine. Invisible features don't really count. It's just a matter of adding a few more labels at the top of the page with links to the URLs I posted.

**Comment by BrittanyBunk** [comment]
@guyjeangilles on https://openlibrary.org/recentchanges, the links @tfmorris shows are not on that page. Those are valuable to me to add there.

**Comment by BrittanyBunk** [comment]
@guyjeangilles @cdrini I was wondering if we could revisit this, as it's a really simple fix to add the one link ('edit books') to the recent changes page. Then it could get closed. That is, if everyone thinks is good to add. I think it's really helpful to see the actual changes happening that are not just everything (which is mostly accounts and lists created). It would be called "book edits" and would be the first on the list before 'author merges'

**Comment by BrittanyBunk** [comment]
I don't think that'll make the issue closed, as then there are still the 'new accounts' to add too. Those two are what's left.

**Comment by SouthGoingZax** [comment]
@BrittanyBunk I sent #4137 to add a link to recent book edits, but I didn't add a link to new accounts because of #4136.  My experience with /recentchanges is that it's usually flooded with new account creations, so I don't think there's a lack of visibility there.  Given that, I'd be fine closing this issue once/if the referenced PR is merged.  What do you think?

**Comment by BrittanyBunk** [comment]
@SouthGoingZax hey, the fact that you're moving this forward means a lot. I kind of agree that we wouldn't really need a /newaccounts tab, but hey, separation never hurts (unless it's too much effort)! Hope that helps.

**Comment by SouthGoingZax** [comment]
It's a one-line change to link to /recentchanges/new-account.  Given that it often times out (#4136), I thought it might not make sense to link to it yet.

**Comment by hornc** [comment]
I think this is resolved by #4137 , closing as completed
