### ISSUE TITLE
Randomize the 'Authors Alliance & MIT Press' carousel

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2642]
Shows up with the same books everyday

**Comment by guyjeangilles** [comment]
Maybe related to #2628 @cdrini @jdlrobson thoughts?

**Comment by cdrini** [comment]
Could you post a screenshot, @BrittanyBunk @guyjeangilles ? This is what it looks for me:
![image](https://user-images.githubusercontent.com/6251786/68970578-9942fa80-07b5-11ea-93d7-dd3ea8d32a65.png)

I notice it changing every ~day or so, I think.

**Comment by cdrini** [comment]
I'll post another screenshot tomorrow as well to see if it's changed

**Comment by guyjeangilles** [comment]
![mit_pub](https://user-images.githubusercontent.com/7256157/68970829-184d2880-07e0-11ea-969b-a54be223fd30.png)

**Comment by BrittanyBunk** [comment]
It's the same

![](https://user-images.githubusercontent.com/7256157/68970829-184d2880-07e0-11ea-969b-a54be223fd30.png)

**Comment by tfmorris** [comment]
We could save the effort of fixing it by removing it. It's always seemed weird to me that we highlight offerings from one random publisher.

**Comment by BrittanyBunk** [comment]
Me too. I'd rather see another genre put in there, like recipes or something.

**Comment by cdrini** [comment]
Forgot to update this, but it does look like it's changing (here it is today). I'm closing this specific issue; feel free to open a new one for adding a new type of carousel :+1:
![image](https://user-images.githubusercontent.com/6251786/69115484-b813ec00-0a56-11ea-8875-e7799f464187.png)

**Comment by tfmorris** [comment]
Do we have a root cause or a link to the fix?

**Comment by cdrini** [comment]
The issue was that the carousel was not randomizing; the picture above indicates that it _is_ randomizing; so closing this as can't repro.

**Comment by BrittanyBunk** [comment]
@cdrini Thanks. I do notice that it is now randomizing. I'll start a new issue for new carousels. Thanks for helping this in the right direction.
