### ISSUE TITLE
If I don't add a title to the edition, then it shows up as 'title unknown'

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2647]
The title appears on the page, but in lists, they don't appear. It'll be good to transfer the work's title to these, as when filling in an edition title it says "There are occasionally title variants amongst editions." So I assume I don't have to put one there if it's the same.

**Comment by seabelis** [comment]
I agree, the variants field is confusing. You always need to add an edition title; this is the one specific to the exact edition you are making a record for. Even if it's the same as the work, you still need to populate the field. 

The variants field could be worded better, but one scenario where you might use it is when the cover title is different from the title page. For example, this book's title is [The Works of William Shakespeare](https://archive.org/details/worksofwilliamsh00shak_0/page/n4). The cover title is just _Shakespeare_; I would put this into the variant field. All of the titles of the works contained in this collection would also be variant titles. The 'uniform' title is just _Works_ and that's what is used at the work-level, this could go into the variant field but that's redundant The text suggests including the titles of translations in there, but I think this should be changed as there is already a translation section. I do frequently put transliterations in that field, however.

**Comment by BrittanyBunk** [comment]
I think that the 'other titles' box should be taken out, as if there are other titles in other languages, they should be made into a new edition. Do you write in that it's a transliteration and may not represent the title's actual work? It would be good to have I feel to not confuse people.

**Comment by seabelis** [comment]
The field does not need to be removed, but does need to be clearer as noted. There is no obligation to use it on every edition, but in the cases such as those mentioned above, it's useful to have.

**Comment by BrittanyBunk** [comment]
The reason I say it is because it would be nice to have translations underneath editions, as mentioned earlier. Then the covers/info could be shown for them. Just having another title underneath an edition may not be enough. I may be mistaken though.

**Comment by seabelis** [comment]
The text suggests including the titles of translations in there, but I think this should be changed as there is already a translations section.

**Comment by BrittanyBunk** [comment]
@seabelis I agree, but what would you like it to be changed to?

**Comment by LeadSongDog** [comment]
Perhaps just “(publisher) (year) (language) edition” of (work title)“ would suffice in lieu of an edition title.

**Comment by BrittanyBunk** [comment]
@LeadSongDog subtitle's ok too. I'd prefer instead of a title maybe the name of the edition: like 1st edition (that's for the list underneath the works in lieu of the title, not what would show on the edition's page).

**Comment by seabelis** [comment]
I've opened an issue here #2648.

**Comment by seabelis** [comment]
> Perhaps just “(publisher) (year) (language) edition of (work title)“ would suffice in lieu of an edition title.

In lieu of? I think the edition does need to have its own title field as it's not always same as the work.  Maybe it's better if it auto-populates? My feeling is that  people may not complete it, even when they should. There should be a warning on save if not populated; blank should not be allowed.

Movie tie-ins, translations, UK/US market plenty of other cases have a different titles than the original, so this still has to be captured in some way. The translation field does not have a field for title of edition; (just original work as has been discussed elsewhere).

**Comment by BrittanyBunk** [comment]
There's issues in multiple places:
- book list: 
![image](https://user-images.githubusercontent.com/55302685/68954961-df7a6880-0779-11ea-99c5-b895290a7e1d.png)
- edition list: 
![image](https://user-images.githubusercontent.com/55302685/68955085-19e40580-077a-11ea-9d87-7034f82fb164.png)
The edition list goes back to the issues of the information presented here. Suggested layout:
- columns (in order): "Title"/subtitle, 
"edition"/date, "language"/format, "read", "locate/buy"
- grouped by: edition, then language
- format: 
![image](https://user-images.githubusercontent.com/55302685/68956317-adb6d100-077c-11ea-8208-d45d374d05cc.png)

**Comment by LeadSongDog** [comment]
@seabelis 
The issue addresses lists, not the underlying metadata, so yes, "in lieu of". Until an actual title can be identified for the edition, leaving a blank on patron's lists will be counterproductive. Once the metadata can be corrected to show the actual edition title, of course that should appear.

**Comment by seabelis** [comment]
@LeadSongDog  Gotcha.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I thought that the work's title would go in for a blank edition title if it's the same. I guess I'm still confused.

**Comment by seabelis** [comment]
@BrittanyBunk I thought I understood the issue, but maybe not. Let me step back for a moment. 
As I understand it, this wording above the edition title field, 

> There are occasionally title variants amongst editions

indicated to you that it is not necessary to populate the edition's title field unless different from the work. You have left this field blank and now the titles do not appear on your lists. Is this correct?

**Comment by LeadSongDog** [comment]
So your "edition list" is at https://openlibrary.org/works/OL1895541W/The_Healing_Herbs
Was the "book list" taken from https://openlibrary.org/people/hawaiisunfun/lists/OL106255L/my_edited_books

Anyhow, examining https://openlibrary.org/books/OL2029162M.json makes it clear, the edition title was never saved, just the edition subtitle. In most of these cases Worldcat indicates the edition title for the isbn should be set to the same as the work title, so feel free to go ahead and fix those.

**Comment by BrittanyBunk** [comment]
@LeadSongDog yes. How come we're using the format that's on WorldCat?

**Comment by seabelis** [comment]
@BrittanyBunk Has your question been answered? Can this be closed?

**Comment by BrittanyBunk** [comment]
@seabelis no, it wasn't answered by @LeadSongDog. Also, this issue shouldn't be closed, as the issue is still present on the OL.

**Comment by LeadSongDog** [comment]
@BrittanyBunk You asked "How come we're using the format that's on WorldCat?"
It is only one of many that we use, but it is widely accessible, verifiable, curated, and fairly stable (unlike most of the bookseller sites). It has by far the largest scope, as a multinational union catalog, so most books that are actually published wind up in WorldCat. Specific national libraries (BL, LoC, BNF, eg.) may be higher quality curation, but can't match the scope. The "format", though, is all our own.

**Comment by BrittanyBunk** [comment]
I think there should be something mentioned somewhere that this will happen if that's the case (unless it already is).

**Comment by seabelis** [comment]
There is a separate issue requesting a change in wording on the form field. If you understand how to prevent 'title unknown' from appearing, please close the issue.

**Comment by BrittanyBunk** [comment]
@seabelis Could you post the number here? I'm not sure about closing it, as it's still a developer issue, but when you add the number, I'll try to add a closing statement and see to what I could do to close it. Sounds good?

**Comment by seabelis** [comment]
I've opened an issue here #2648.

**Comment by BrittanyBunk** [comment]
Closing statement:
- The most temporary solution is to write in the title
- Better wording in #2648 will help this issue from further happening
- If this issue gets reopened again, it's on the developer side to have the website automatically fill in the name of the work for the edition if it's blank (as it does for the edition's page).

**Comment by BrittanyBunk** [comment]
@seabelis I didn't know, but it's actually placed in triage/librarian issues. I feel that it has meaning there, and removing it will cause issues (as it's about the automation side). You don't mind me reopening it up, so that whoever put this issue there can continue to work on it?

**Comment by seabelis** [comment]
I placed it in Librarian Issues. If the question has been answered and you now understand that by populating an edition title, you will no longer see 'title unknown,' then the issue should be closed. Closing this issue does not prevent #2648 from being worked on.

**Comment by BrittanyBunk** [comment]
@seabelis thanks. I was worried about that, as the temporary fix is manual, but the automation was a concern on the developer side, which is why it was placed there. So I appreciate you putting it back, so it can be worked on for the developer side, and closed for the manual one.
