### ISSUE TITLE
Change confusing text on edit form's title and variant title fields

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2648]
On the edition form there is 'helper text' above the Title field stating 'There are occasionally title variants amongst editions.' This has been interpreted by some users as an optional field to be  populated only if different from the work's title. Field should be required.

Additionally, the title variants field aka "Is it known by any other titles?" Has text suggesting it is the appropriate place for translation information. This should be revised as there is a section for translation information elsewhere on the form. Perhaps the wording could be changed to "If the title on the cover or spine is different from that on the title page, enter that here.'

### Evidence / Screenshot (if possible)
<img width="475" alt="Screenshot 2019-11-14 at 17 44 44" src="https://user-images.githubusercontent.com/17739465/68877562-8fae8980-0706-11ea-8f60-49ac58d5e3ff.png">
<img width="607" alt="Screenshot 2019-11-14 at 17 49 00" src="https://user-images.githubusercontent.com/17739465/68877879-12374900-0707-11ea-8b99-dc767a71f58f.png">

### Related files
Related to #2647

**Comment by seabelis** [comment]
I'd like to change the wording next to **Title** to "Enter the title of this specific edition."
I'd like to remove the "Perhaps in another language?" and the example text from "**Is it known by any other titles?**" field and replace the example text with "Uniform titles, cover/spine titles, and transliterated titles may be entered here." 
The "other languages" example is poor as the original title is/should be captured in the Translation section and languages other than the original would be entered as editions themselves. A Greek edition of Harry Potter does not need to mention the titles in Russian, German, Persian, etc.

**Comment by BrittanyBunk** [comment]
@seabelis this isn't really related to #2654 insomuch as #2601 where we have subrecords (of editions) for each translation, instead of saying other titles, in other languages (as I feel there's too many, and there's already records of other translations in the editions section).

**Comment by BrittanyBunk** [comment]
I really appreciate that you're making these fixes, and I think the FAQs really does need more detail. Do we even need a box for other titles? I guess I might just wait for the end product to truly evaluate and reevaluate what your vision is.

**Comment by seabelis** [comment]
Yes, the field for title variants is useful information for the reasons stated. These are edition-specific, not at the work level. The field is not required.

**Comment by BrittanyBunk** [comment]
I think you're adding too much into one field with your rewrite, unless you plan to split it up. Adding in the transliteration of every single language (unless the plan is to allow users a 'primary language' that they see the site with) is going to be overwhelming.

cover/spine titles - I think that's a good substitute, as they likely are different from the cover. I mean, my wish is to also see the OL have a slideshow style for cover images, where it shows the front cover, spine, and back cover - as that's what a person sees when taking a book off a shelf.

**Comment by seabelis** [comment]
Not the translitertion of every language. If that title is in Korean then the transliteration of the Korean title would be added into that field.

**Comment by cdrini** [comment]
Proposed changes to **title** field seems good to me; For **other titles** field, maybe something like:

> Do different titles appear on the cover, spine, or title page? Transliterated titles (e.g. [JAPANESE CHARS] -> [ROMAN CHARS]), or the individual titles of collections or anthologies may be entered here as well as. 

That would help clear up the meaning of transliteration. Although, I believe transliteration is something that machines can do (one of the planned improvements to Solr is allowing searching by transliteration or by the real characters, which solr is capable of). So maybe just:

> Do different titles appear on the cover, spine, or title page? The individual titles of collections or anthologies may be entered here as well as.

**Comment by seabelis** [comment]
Yes, if the transliteration is addressed elsewhere, it doesn't need to go into that field.

**Comment by seabelis** [comment]
The title page is where the edition title should be coming from, so maybe I will specify that and then for the **other titles**...

> Use this field if the title is different on the cover or spine. If the edition is a collection or anthology, you may also add the titles of each work here.

**Comment by BrittanyBunk** [comment]
@seabelis I see what you mean. That's cool the transliteration idea :)

**Comment by BrittanyBunk** [comment]
@cdrini I'm assuming there's a scenario where the title will be translated. In that case, it would be good to have both the translation and transliteration to prevent confusion, right? However, I agree with you that this would be automated. If a machine can do this automatically, why would people manually enter it in?
