### ISSUE TITLE
Ratings don't work in local dev env

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2649]
### Relevant url?
e.g. http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain

### Steps to Reproduce

1. Login to the local dev env with `openlibrary@example.com`/`admin123`
1. Go to http://localhost:8080/books/OL2058361M/The_wit_wisdom_of_Mark_Twain
2. Try setting the rating

* Actual: Page reloads and looks the same
* Expected: Page reloads and displays the highlighted rating

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10
- **Environment (prod/dev/local)?** local

### Related files

- UI: https://github.com/internetarchive/openlibrary/blob/9f16159e6972eb0029fcb11c513f54f788252057/openlibrary/macros/StarRatings.html
- API endpoint called on rating submitted: https://github.com/internetarchive/openlibrary/blob/0a97d766e6d6844918de9a77ccc19d17caa51a52/openlibrary/plugins/openlibrary/api.py#L85

**Comment by SouthGoingZax** [comment]
I can't reproduce this.  I can set, change, and clear ratings in my dev environment.  @cdrini can you still reproduce this?

**Comment by mekarpeles** [comment]
I'm going to assume this is resolved.
