### ISSUE TITLE
Some OL records have references to archive.org scans but not in the usable `ocaid` field

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2651]
Some OL records have refs to archive.org scans, but not in the `ocaid` field, which means a readable copy is not linked, and other matching + sync up processes will miss them too, which could result in duplicate records added (at least this appears to have happened historically) and makes it harder to audit collection coverage.

example edition: https://openlibrary.org/books/OL21296940M/Too_close_for_comfort

Shows no readable copy, yet it has 
`"ia:toocloseforcomfo00inse"` is `source_records` and 
`"ia_loaded_id": ["toocloseforcomfo00inse"]`

I think both these fields need to be checked in general since they seem to be independant at least in some cases.

**Fix:** check for items with these fields populated but _without_ `ocaid` -- then populate `ocaid`.

* I don't think it is a requirement to remove the older fields or values (no effect of doing so)
* Note, some of these ocaids can point to removed archive.org items e.g. https://openlibrary.org/books/OL6272124M.json points to https://archive.org/details/lecturesonfrench00acto , which no longer exists , so check whether the item exists before writing to `ocaid`

... this implies that it going to be okay for items to have `source_records` of `ia:<ocaid>` but no `ocaid` if the item has since been deleted. I think this makes sense. `source_record` is to indicate where the original metadata was imported from, and has value for the provenance. `ocaid` is for the current link to a readable item. I think ``"ia_loaded_id"` is legacy and is not used for anything currently.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
@hornc is there a way to add an `ocaid` to an edition? The openlibrary-client has an `add-id` method but `ocaid` is not a valid identifier, which seems wrong.

**Comment by guyjeangilles** [comment]
I wrote a script to identify the malformed editions. @hornc please review

https://github.com/internetarchive/openlibrary-bots/pull/39

**Comment by tfmorris** [comment]
Here's a 1-liner that will filter the dump according to the given criteria:

`time zgrep ^/type/edition ol_dump_2020-01-31.txt.gz | grep -v '"ocaid":' | grep -E '("ia_loaded_id|"ia:)' | gzip > ol_dump_2020-01-31-olid-missing.tsv.gz`

and generate a 16 MB 50K line subset for further processing.

@hornc Is a HEAD request checking for 404s sufficient to screen out the items that have been removed from IA or is more required? Should we be checking whether the IA item correctly points to the OL work & edition?

> I think `ia_loaded_id` is legacy and is not used for anything currently.

Should we remove it, so we don't have to worry about discrepancies or keeping it in sync?

**Comment by guyjeangilles** [comment]
Between 2020-01-31 and 2020-02-29 8,000+ editions were created/edited that have an Internet Archive in it's metadata but no `ocaid` attribute.

@hornc Is 8k editions a reasonable number or should this trigger some root cause analysis?

**Comment by hornc** [comment]
With #1046 completed I'm not sure what else is left to do here. Are there more unlinked records?

**Comment by hornc** [comment]
Unsure what is left to do here. Closing as stale as there is is other syncing work in progress to manage ocaid linkage,
