### ISSUE TITLE
Add a dedication box for editions

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2654]
Expansion on #2542. The issue is 'by statement' is a little confusing and likely unnecessary, as all the information there can be added in elsewhere (and it doesn't even show up on the edition's page), so I'm proposing the by-statement section be changed to the dedication section (unless it violates copyrights). I don't just mean 'dedicated to' as that's already there, but the description of the dedication past that (it's usually the reason for the dedication).

**Comment by BrittanyBunk** [comment]
This should be open.

**Comment by seabelis** [comment]
This feature exists in the contributors section (perhaps misplaced).
<img width="552" alt="Screenshot 2019-11-15 at 23 28 25" src="https://user-images.githubusercontent.com/17739465/68980085-bac8d400-07ff-11ea-8296-64df87c715e2.png">

The byline is useful as the author's name on the edition is not always the same as on the work. i.e. Ellis Bell for Emily Brontë.

**Comment by BrittanyBunk** [comment]
@seabelis I don't really follow. Also, I'm aware of that feature. I'm talking about the dedication section, like "to my ____, for ____"

**Comment by seabelis** [comment]
So what you would like is a free text field, am I understanding correctly?

**Comment by BrittanyBunk** [comment]
yes please, separated from the drop down menu. It helps with understanding the dedication section (as it's short). It's better than the by-statement that doesn't show up (maybe the dedication field doesn't need to either). It's ok that the by-statement is redundant, as it doesn't show up in the edition's page anyway, so that's no longer an issue with me.

**Comment by seabelis** [comment]
Closing for now. In the future there may be a better place for this.
