### ISSUE TITLE
Customize recommendations based on language/geo

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2655]
I'm not a huge fan of the carousel's which dominate the home page, but if we're going to keep them we should make them less static and more customized to the user.

### Describe the solution you'd like

One easy win would be to use language to provide more appropriate content to non-English speakers. Another possibility would be to use geo-ip, which I think we already use, to provide a geographical customization, although that might be harder to get right.

**Comment by guyjeangilles** [comment]
Related to #791 

I also put the `Internationalization` label even though this is more localization based

**Comment by cdrini** [comment]
I usually prefer to keep the older issue, but in this case I'm going to close in favour of #2906 since it has more context both in the issue and in comments.

**Comment by tfmorris** [comment]
My April 2020 comment on the duplicate was apparently part of the justification for closing this, so copying it here for more detail:

> Having the carousels hardwired to English-only definitely shows a huge amount of cultural tone deafness, but the queries are so baroque that I'm not sure whether we should try to fix them.
> 
> - Who decided that those 5 authors, and they alone, should represent an entire genre of fiction?
> - Why aren't we using OpenLibrary subjects to filter things?
> - Why is "Books to Sponsor" the only carousel above the fold?
> - Why is MIT Press the publisher that gets pride of place on the homepage?
> - Why is Reader's Digest blacklisted?
> 
> I think we should probably just scrap the entire thing and start over.

Since creating the issue 15 months ago, I've become less equivocal about carousels. They are space inefficient and poorly designed. They should be replaced with a design that is more user focused instead of just shovelling random drek.
