### ISSUE TITLE
Edits should have a time stamp in addition to the date.

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2658]
![image](https://user-images.githubusercontent.com/55302685/69266882-e0980500-0b80-11ea-9253-5f7157cd87b4.png)
Right now, it shows only the date, but if someone says they made a change and want me to look at it, I can't tell what time they made the change. Having that would really help

**Comment by guyjeangilles** [comment]
I assume that the history is logged server-side with a timestamp, it's just not being exposed to the client? @hornc @mekarpeles @cdrini ?

**Comment by tfmorris** [comment]
History entry timestamps look like this `2012-11-22T11:05:36.657364` so we can expose as much of that as is useful, but I'm not sure I understand the use case. If the user made multiple edits today, they'll be in order. Is it important to understand whether they were made 2 hours ago or 4 hours ago?

**Comment by 29sxiao** [comment]
--sean

**Comment by BrittanyBunk** [comment]
If a time stamp has HH:MM:SS DD:MM:YY, that would be great. I do need down to the second, as well as minute, to see changes that I made to make sure they go through.

**Comment by hornc** [comment]
Full edit timestamps are available if needed from the Json view: e.g. https://openlibrary.org/works/OL77950W.json?m=history closing as functionality already exists
