### ISSUE TITLE
It should be possible to delete a list with entries

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2665]
Users must request admin assistance to delete their own lists.

### Evidence / Screenshot (if possible)
<img width="745" alt="Screenshot 2019-11-24 at 09 37 09" src="https://user-images.githubusercontent.com/17739465/69492092-0f262080-0e9e-11ea-9bec-60c356108140.png">

### Steps to Reproduce

1. Create a list or go to one of your existing lists.
2. Try to find a way to delete your list.

* Actual: No way to delete the list; only a message stating that admins are required for deletions.
* Expected: To be able to delete lists I've created.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**  Chrome Version 78.0.3904.97 (Official Build) (64-bit)
- **Operating system?** macOS Catalina
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Users should not have to contact admins to delete their own lists.

**Comment by tfmorris** [comment]
The functionality exists. It's just broken, perhaps due to this Javascript error:

> jquery.js:358 Uncaught TypeError: Cannot read property 'length' of undefined
>     at Function.each (jquery.js:358)
>     at availability.js:212
>     at n (availability.js:65)
>     at availability.js:210
>     at n (availability.js:65)
>     at o (availability.js:209)
>     at a (ol.js:183)
>     at HTMLDocument.<anonymous> (jquery-migrate.js:1)
>     at c (jquery.js:3099)
>     at Object.fireWith [as resolveWith] (jquery.js:3211)

There appear to be both "delete list" and "remove seed (ie list entry" functions on the page which are currently inoperative.

**Comment by jdlrobson** [comment]
It seems a list deletes itself after all its items are removed, so it is actually possible to delete a list - it's just not straightforward in cases.

If we allow list deletion, we'll likely need a method to delete all items and remove the record. We'd also need to make sure we have a confirmation step.

I'm dropping to low relative to other open frontend tasks given that this functionality is possible, just a bit cumbersome.

**Comment by seabelis** [comment]
@jdlrobson That's not quite what happened in this case. I thought the list would delete itself once it had no items, but this was not the case. It does work if you go to the list and remove all items from it. However, if you remove the list from each item (as it was in this case) the list remains.

**Comment by cdrini** [comment]
Closed by #2776
