### ISSUE TITLE
Regression? Carousel scroll buttons have degraded

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2669]
Within the last day or two, the left and right scroll buttons on the home page carousels have changed to plain arrows which load very late. They seem to wait for the page to fully populate, until then there is no arrow at all (see screenshot). 

By contrast the carousels on the edition and work pages still have the round buttons, but there the tiles with placeholder covers are very slow to load. 

This seems to have coincided with the reappearance of the absurd quadruplicate IA begging banner.

### Evidence / Screenshot (if possible)
![noscroll](https://user-images.githubusercontent.com/11435431/69658588-78e32d80-104a-11ea-83f7-9f9c9263f065.jpg)

![quadbeg](https://user-images.githubusercontent.com/11435431/69659445-31f63780-104c-11ea-89e0-e406f315a13a.jpg)

### Relevant url?

https://openlibrary.org/

### Details

- **Logged in (Y/N)?** either
- **Browser type/version?** both Chrome and FF
- **Operating system?** Win7Pro
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
I'm seeing the opposite. Can anyone duplicate this?
![#2669_cropped](https://user-images.githubusercontent.com/7256157/69677422-d7d09300-109a-11ea-9a60-840a49317f19.png)

**Comment by tfmorris** [comment]
I was missing the arrows until I did a hard browser refresh

**Comment by LeadSongDog** [comment]
Without logging in:
Back to normal today on Chrome, not sure what has changed. Might have been an effect of a very slow local network at my end.

On FF I'm seeing the same as @guyjeangilles does, even after refreshing. Hovering on the tiles I see the alt-text in the hover bubble, but there is nothing shown in the default cover, just an empty box. The entire "Classic Books" carousel is missing on FF.

When logged in:
Chrome seems normal.
FF now displays the "Classic Books" but still the default covers are blank.

Logging out again:
as when logged in, on both

**Comment by tfmorris** [comment]
If it's no long a problem, please close this issue.

**Comment by guyjeangilles** [comment]
I gonna go ahead and close this. If the issue becomes reproducible again we can reopen.
