### ISSUE TITLE
Change associated work

### ISSUE THREAD

**Issue by adius** [internetarchive/openlibrary#267]
There should be the possibility to change the associated work while editing an edition.

**Comment by mekarpeles** [comment]
@adius we now have this thanks to @cdrini! If you /edit an `edition` and then click on **Librarian Mode** you'll see an option to re-assign the edition to a different work 🎉  🎉

**Comment by LeadSongDog** [comment]
This seems to be working nicely, but when the old work is left with no editions, it creates a different problem. It would be more robust if it were not necessary to have users request admins manually delete these emptied works. Should they just become redirects to the new work?
