### ISSUE TITLE
Classic Books carousel shows works while others show editions

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2670]
### Relevant url?

https://openlibrary.org/

### Steps to Reproduce

1. Go to a book in the carousel
2. Hover or click on it

* Actual: Works pages are linked only in the Classic Books carousel
* Expected: Works pages are linked in all carousels when they exist, editions only when it is orphaned (no work exists)

### Details

- **Logged in (Y/N)?** either
- **Browser type/version?** multiple
- **Operating system?** multiple
- **Environment (prod/dev/local)?** prod

### Related files

#496 had earlier related discussion

**Comment by mekarpeles** [comment]
This is known / intentional; closing as not an issue / will not fix (unless there's a critical reason it should be changed)
