### ISSUE TITLE
Add a a definition of pagination to the FAQ

### ISSUE THREAD

**Issue by adius** [internetarchive/openlibrary#269]
I don't understand what the pagination field in the "The Physical Object" section is good for.
Maybe the answer can also be added to the faq page.

**Comment by tfmorris** [comment]
It holds the pagination information in a form that would make sense to a librarian.  It's a free form text field which is lightly structured in a way that would make sense to a human, but is not consistent enough for a machine to easily parse.  A typical value might be something like "ix; 167 p." which means 9 pages of preferatory materal, followed by 167 numbered pages in the main text.  Other information included could be number of volumes in a set, descriptions of illustrations, foldouts, etc.

**Comment by hornc** [comment]
I went looking for the answer to this too, the relevant standard is the International Standard Bibliographic Description (ISBD), and I managed to find a copy online.

Here is a link to the Physical Description section: http://www.ifla.org/files/assets/cataloguing/isbd/isbd-cons_2007-en.pdf#page=177   The bit that relates to pagination of "resources in one physical unit" starts here: http://www.ifla.org/files/assets/cataloguing/isbd/isbd-cons_2007-en.pdf#page=182

The faq should probably have a simplified version included. I'm posting the links here mainly so I can find them again later.

**Comment by LeadSongDog** [comment]
For many of the present edition records, the pagination string includes a height, e.g. "19 cm" or "19cm" This info should really be put into the correct field and then removed from the pagination.
e.g. https://openlibrary.org/books/OL21278276M/Making_money_on_the_stock_exchange?b=3&a=2&_compare=Compare&m=diff

**Comment by LeadSongDog** [comment]
There should probably be radio button options for 8vo 4vo etc. Often this is the only available indication of physical dimensions in source records.

**Comment by LeadSongDog** [comment]
#477 relates. @salman-bhai, how would this work on the Wiki? Sure it can clarify the proper use of the field, but it takes code to automate the cleanup. It is far too widespread to attack manually.

**Comment by hornc** [comment]
Add this question and answer to the FAQ editing page: https://openlibrary.org/help/faq/editing and close.

**Comment by guyjeangilles** [comment]
I've changed the title to an actionable item.

**Comment by seabelis** [comment]
Added to the FAQs section. https://openlibrary.org/help/faq/editing
