### ISSUE TITLE
What is a book? Boxed Sets?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2691]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

There's already been some discussion about this, but let's make a final decision.

My take...Boxed sets are retail packages. Even when they contain editions by the same author, it's the individual editions that should be in the catalog; the fact that it's sold together in a box has little significance in the context of Open Library and should not be considered a 'book'.

**Comment by LeadSongDog** [comment]
@seabelis 
There are many variations on this retail packaging problem, not all are about curation. https://github.com/internetarchive/openlibrary-client/issues/79 addresses one specific package, the "Dumpbin". There are many others misplaced title words such as "Pack", "Display", "Unit" and "Copy", that are difficult to automatically catch, but usually signify packaging rather than a book title.

**Comment by seabelis** [comment]
Yes, those too. Not books.

**Comment by tfmorris** [comment]
We've mentioned it in the past and it's probably still linked from past discussions, but perhaps it's time for a periodic mention of Goodreads "Not A Book" definitions.
https://help.goodreads.com/s/article/Librarian-Manual-NOT-A-BOOK-NABbing-a-book

If you look at the top few entries here: https://www.goodreads.com/author/show/1000834.NOT_A_BOOK
they apparently consider plagiarized works to be "Not A Book" too, which interesting.

**Comment by seabelis** [comment]
I would agree with all of their items listed and add boxed sets to the list for the reason I've stated earlier. GR considers boxed sets books. 

The NABing functionality would be great to implement, but with some things to consider. When a book is NABed on GR, it blocks the ISBN from being reimported (good) or added by a user (not always good). An ISBN may be valid for each volume in a box AND for the box itself. If we were to implement a similar feature, we would not want to block the individual volumes from being added, just the box itself. NABing does not prevent non-ISBN items from being reimported or added. 

Maybe provide a way to suppress a record so that it does not show in standard results, but for a direct ISBN hit show a message along the lines of "an item with this ISBN has been flagged as 'not a book'" an give the user the option to review the flag to either agree or re-activate along with some additional helper text about what's a book, etc.

**Comment by mekarpeles** [comment]
As per our previous conversation, I'm going to close this issue now that feedback has been collected and leave it to @seabelis to drive next steps. (Lisa, feel free to re-open if you feel that's the right step)
