### ISSUE TITLE
ISBN10 and ISBN13 should be interchangeable

### ISSUE THREAD

**Issue by singpolyma** [internetarchive/openlibrary#27]
For search, all APIs, and cover retrieval, if either an ISBN10 or ISBN13 is set for an edition, then the equivalent other number (13 to 10 conversion only valid for 978 prefix) should work as well.  This allows application developers to normalise on one number instead of keeping track of both.

**Comment by LeadSongDog** [comment]
This still doesn't seem right. The example at http://openlibrary.org/books/OL24972205M/Terms_of_Engagement 
was built from an initial imported IA MARC record that had three ISBN_13 and one (equivalent) ISBN_10 shown in field 020, yet all that was generated in the record was a single ISBN_13. 
This was also somewhat redundant to  https://openlibrary.org/books/OL24791680M/Terms_of_engagement 
which was generated from the LC MARC import a month earlier.

**Comment by LeadSongDog** [comment]
Further, on those two OL records for the same edition, the "Borrow: Physical copy, local" Worldcat URLs are different, one searching for the ISBN_10, the other for the ISBN_13
http://worldcat.org/isbn/1605094471
http://worldcat.org/isbn/9781605094489
They are both resolved to 
http://www.worldcat.org/title/terms-of-engagement-new-ways-of-leading-and-changing-organizations/oclc/671632684 
so there's no clear value in having two different formats.

**Comment by brad2014** [comment]
@mek: I suggest we close this bug.  If there is interest in moving isbn handling onto pyisbn or isbntools, let's open that as a separate feature request (which we can backlog and schedule).

**Comment by tfmorris** [comment]
@brad2014 Stories are typically about user facing features, not implementation details.

Having said that, this feature request was mostly complete in Nov 2011 and finished up in Mar 2012, so this issue can be safely closed.

The items mentioned by @LeadSongDog in Apr 2016 (not all ISBNs imported from MARC 020  and cosmetic issue of multiple WorldCat URLs) can be made into separate tickets if they still exist and don't already have tickets covering them.
