### ISSUE TITLE
dev.openlibrary.org shows up in search engine results

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2706]
dev.openlibrary.org links are showing up in search engine results; that's likely hurting our main site's SEO (by splitting our traffic), as well as confusing people. It seems less of an issue with Google (anecdotally).

### Evidence / Screenshot (if possible)
| Bing | Duck Duck Go |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/6251786/70445282-47fef180-1a69-11ea-8aae-a55ad543819b.png) | ![image](https://user-images.githubusercontent.com/6251786/70445205-2dc51380-1a69-11ea-9270-8c6c6b86a5aa.png) |
| https://www.bing.com/search?q=The+Life-Changing+Magic+of+Tidying+Up+openlibrary | https://duckduckgo.com/?q=The+Life-Changing+Magic+of+Tidying+Up+openlibrary |

### Reproduction Steps
1. Search for a book on a search engine with the word "openlibrary"

* Actual: Also see dev.openlibrary.org results
* Expected: Only openlibrary.org results

### Proposal & Constraints
Change the robots.txt on dev to be:

```
User-agent: *
Disallow: / 
```

(src: https://moz.com/community/q/block-an-entire-subdomain-with-robots-txt )

### Related files
- https://github.com/internetarchive/openlibrary/blob/01f7cb3417522b9398e3d0158606a02947f8e718/openlibrary/plugins/openlibrary/code.py#L331 (Endpoint that serves the robots.txt file)
- https://github.com/internetarchive/openlibrary/blob/master/static/robots.txt
- https://github.com/internetarchive/openlibrary/blob/86528bce1c0b23530b49f084dfe445b745272d03/static/norobots.txt (meant for dev.openlibrary.org, but looks unused)
- https://openlibrary.org/robots.txt
- https://dev.openlibrary.org/robots.txt

### Stakeholders
@mekarpeles

**Comment by guyjeangilles** [comment]
As another datapoint: I'm seeing the same problem with Startpage which purportedly anonymizes Google searches: https://www.startpage.com/do/dsearch?query=green+eggs+and+ham+openlibrary.org&cat=web&pl=ext-ff&language=english&extVersion=1.3.0

**Comment by hornc** [comment]
This seems like it should be quite high priority.

Subdomain blocking in robots.txt doesn't seem as easy as it should be, the existing `/static/norobots.txt` 
(I prefer the nobots.txt name that some of the suggestions on the net use :) ) implies that we should have apache rewrite rules in place to sort this out. @mekarpeles do you know where the the existing config is for this? Is there a standard set of Apache rules we can add to?
