### ISSUE TITLE
Homepage cache ignores user's locale

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2707]
The homepage is stored in memcache without locale information, so the page will always appear in e.g. English if that's what gets into memcache first.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/70455435-4c7fd600-1a7a-11ea-8a48-113782dc0807.png)

### Steps to Reproduce

1. Go to https://openlibrary.org/?lang=fr ; or https://openlibrary.org/?lang=es

* Actual: Displays dates in whatever language was last in cache
* Expected: "Latest blog posts" section displays dates in user's language

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF71
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Related files
https://github.com/internetarchive/openlibrary/blob/b9fe411578a4587f786236c3622d6332d0e816fa/openlibrary/plugins/openlibrary/home.py#L59-L60

**Comment by tfmorris** [comment]
This was introduced in #2067 and appears to only affect the home page.

**Comment by cdrini** [comment]
@tfmorris is this by any chance something you'd be willing to tackle? It just involves editing the above line to include the user's lang (`web.ctx.lang` or something) in the key, and then testing to see if it works.

**Comment by tfmorris** [comment]
Sure, it's a 30 second change.
