### ISSUE TITLE
Sponsorship page breaks mobile display

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2710]
### Evidence / Screenshot (if possible)
![2019-10-23 07 48 02](https://user-images.githubusercontent.com/148752/70493608-20d20f80-1abd-11ea-83e2-ed66e8717122.jpeg)

### Relevant url?
https://openlibrary.org/sponsorship

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@tabshaikh

**Comment by tabshaikh** [comment]
Closing this issue as it is similar to this #2547 which is a bit more detailed
