### ISSUE TITLE
Add Reading Log button directly on search results

### ISSUE THREAD

**Issue by hahla** [internetarchive/openlibrary#2716]
This issue was originally opened by @hahla for Archive.org as: **"Favorite item directly from search result tile view"**

@mekarpeles adds:

> This feature request issue (Favorite item directly from search result tile view) was originally for Archive.org though it is being repurposed as it is one we've also thought about for Open Library: i.e. add the "Want to Read" button to search results page.

## Original Comment

What: Hopefully makes sense just from the title but also here is a screenshot to be explicit. 

Why? It would be nice to quickly favorite a large number of books at one time, and then view them via favorites more efficiently. For example I wanted to fill my kindle up with some Isaac Asmiov classics, but going to individual pages is just really inefficient.

Expected result:  Click Star on list page will favorite the item immediately just like you were on the item detail view.

<img width="592" alt="Screen Shot 2019-12-11 at 4 32 44 PM" src="https://user-images.githubusercontent.com/2063061/70635393-1be39c00-1c34-11ea-8767-a66fc5bb304b.png">

**Comment by hahla** [comment]
Note that I have not setup a docker environment but am considering it and reading on it, so for now will simply file the idea and possibly come back to take it since I am a python developer.

**Comment by guyjeangilles** [comment]
@hahla The screenshot looks like Archive.org. Are you suggesting we mimic the style of the Internet Archive or you suggesting that Internet Archive site be changed? If it's the later this is the wrong repo.

**Comment by mekarpeles** [comment]
This feature request issue (Favorite item directly from search result tile view) was originally for Archive.org though it is being repurposed as it is one we've also thought about for Open Library: i.e. add the "Want to Read" button to search results page.

**Comment by jimchamp** [comment]
Fairly certain that this has been solved by #6159.  Feel free to re-open this if I am misunderstanding things.
