### ISSUE TITLE
Homepage memcache not clearing regularly

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2717]
The homepage's memcache is supposed to clear every 5 minutes (according to the code). That doesn't seem to be happening; the sponsorship carousel was updated last night, but still showed outdated ~10 hours later until the `home.homepage-` cache was forcefully cleared.

### Steps to Reproduce

1. Update something that will affect the homepage

* Expected: The homepage to be up-to-date within ~10 minutes
* Actual: The homepage doesn't seem to update at all

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** FF71
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Related files
https://github.com/internetarchive/openlibrary/blob/b9fe411578a4587f786236c3622d6332d0e816fa/openlibrary/plugins/openlibrary/home.py#L57-L60

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
May be an issue still but no longer essential to track because our cache takes into consideration language, etc.
