### ISSUE TITLE
Don't include duplicate anchor text in title

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2718]
We shouldn't specify the title attribute on an anchor element if it's the same as the text contents of the anchor

According to https://www.seoinc.com/seo-blog/how-to-use-the-link-title-attribute/ :

> Focus on using the TITLE attribute for your users rather than search engines – and don’t use the same text as your anchor text, as this can negatively impact usability. Blind users will end up hearing the same text twice in this case.

- [ ] Check HTML files see where anchor with titles are used
- [ ] Fix these cases

The footer section contains several of these

**Comment by iwtga** [comment]
Hey, can I take up this issue?
If I'm wrong we have to find anchor tags which have **TITLE** attribute same as the text contents of the anchor and then delete the title attribute right?
