### ISSUE TITLE
Resolve (with redirects) Works w/ 0 Editions resulting from Workbot translation associations historical bug

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2727]
Residual data cleanup re: #44 & #88

- [x] http://openlibrary.org/works/OL3536507W/Hong_lou_meng
- [x] https://openlibrary.org/works/OL16252229W/Kinder_des_weltalls
- [x] http://openlibrary.org/works/OL15344034W/Handel_en_bestuur
- [x] http://openlibrary.org/works/OL15344038W/L%27_economia_delle_citt%C3%A0
- [x] http://openlibrary.org/works/OL15344035W/La_econom%C3%ADa_de_las_ciudades
- [x] http://openlibrary.org/works/OL15344045W/Vita_e_morte_delle_grandi_grandi_citt%C3%A0
- [x] http://openlibrary.org/works/OL15344041W/Muerte_y_vida_de_las_grandes_ciudades
- [x] http://openlibrary.org/works/OL15344039W/Les_villes_et_la_richesse_des_nations
- [x] http://openlibrary.org/works/OL15344043W/Stadt_im_Untergang

Scope of affected data: First Work Bot edit: October 5, 2009 ( https://openlibrary.org/people/WorkBot?page=111517 )
Any WorkBot edit (October 5, 2009 to January 21, 2012) with a description of `merge works` has potentially left a work without editions.

**Comment by hornc** [comment]
There are specific examples of a bigger issue #44,  deleting these specifically is low value and the incorrect thing to do. (IMO)

**Comment by hornc** [comment]
I have some specific work in progress that has been paused on this, which is most of the way to a solution, so when it is prioritised, I can resume form where I left off.

**Comment by BrittanyBunk** [comment]
Can't we have it to where if someone moves all the editions out of the work, it goes away (especially because it was an error for it to exist)?

**Comment by tfmorris** [comment]
> I have some specific work in progress that has been paused on this, which is most of the way to a solution

@hornc Is there a branch with this work on it?

**Comment by hornc** [comment]
The index hasn't quite caught up, but many classical authors had 100s or 1000s of extra (empty) works,
e.g Plutarch
![image](https://user-images.githubusercontent.com/905545/89284256-99b45600-d6a2-11ea-92e1-27915f3c6836.png)

Now has 892 works: https://openlibrary.org/authors/OL58120A/Plutarch

**Comment by BrittanyBunk** [comment]
So glad this is being worked on. It would take forever to do this manually.

**Comment by LeadSongDog** [comment]
@hornc Of those 892 work records, there are currently about 722 that have editions. Of course the ultimate number should be far lower as redundant works get merged.

**Comment by hornc** [comment]
My bot made ~104108 redirects from works left without editions. The WorkBot history contained the work id to which the editions were moved, so the redirect targets contain the original editions.

The bot examined _all_ of Work Bot's history and used the available data on any edit with the comment `merge works` to resolve the editionless works. If there editionless works created by other means, they will have to be located by some other means.
