### ISSUE TITLE
Allow the reading log to log editions instead of works

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#2733]
The Reading Log feature lets keep track of the books you’re currently reading, have finished reading, or want to read. Currently it only logs works, not editions.

![reading-log-screenshot](https://user-images.githubusercontent.com/7125952/70839674-1346bd80-1e0e-11ea-8f0e-ab7cf452a00b.png)

### Description of the solution I would like

I suggest changing this point to be able to log editions better than works (or editions and works alike).

### Stakeholders

I think this solution is more appealing to readers. Although often readers only share the title of the book they are reading (work), being an online reading log, I think it is more interesting to be able to share which particular book (edition) they are reading, have read, or want to read, not just the title of the original works.

**Comment by BrittanyBunk** [comment]
@dcapillae this seems to be more of a bug. It's a really good idea.

**Comment by mekarpeles** [comment]
Thank you @dcapillae! Noted! :)

**Comment by seabelis** [comment]
Versatility would be nice. When I want to read a work, I don't necessarily have a particular edition in mind, but when I am reading or have read then it is a specific edition. If it has to be either/or, I think logging an edition is preferred. I agree with @dcapillae that users would usually want to indicate the specific edition; especially if the original work is in a different language than the edition read.

**Comment by LeadSongDog** [comment]
@seabelis Absolutely. Wanted lists should accommodate a) specific edition; b) any edition; c) any edition in a specific language. 

Related, for sponsoring acquisitions: if we already have multiple copies in one language we shouldn't tell potential sponsors an unqualified "Not In Library" for other editions in that language.

**Comment by cdrini** [comment]
Bumping in priority ; this experience is utterly broken for non-English\* patrons, since they'll mark a book as "Want to read", and then when they go to their reading log they'll see a book in an entirely different language :/

\* Technically broken for all patrons when logging a book that's not in its original edition, but effectively this most effects non-English patrons due to the biases in our catalogue.

**Comment by benbdeitch** [comment]
Hello, could you assign me to this issue? I've worked with both Solr queries and the Reading Log at this point, so I'd love to give this a shot.
