### ISSUE TITLE
Classification and ID # is the same for LCCN

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2735]
continuation of #142 https://github.com/internetarchive/openlibrary/issues/142 where the "LC Control Number" in the "ID Numbers" is the same as the "LCCN Permalink" in "Classifications". Example: https://lccn.loc.gov/n80090600 I suggest removing one. 

A solution would be for the name "LCCN" to be underneath "Classifications"

**Comment by LeadSongDog** [comment]
@BrittanyBunk Sorry but you have conflated different concepts. That permalink URL is for an author name identity not a classification (LC class) nor a work identity ( LCCN)

**Comment by BrittanyBunk** [comment]
@LeadSongDog no, I didn't. It doesn't matter about author, object, title, etc. They're all the same for LCCN and permalink: https://catalog.loc.gov/vwebv/search?searchCode=LCCN&searchArg=2001001114&searchType=1&permalink=y

**Comment by BrittanyBunk** [comment]
I did look into it though, and the LCCN and permalink are slightly different here: https://lccn.loc.gov/lccnperm-faq.html#n10. However, since there are rules that say what the LCCN would be with the permalink, it's better to just have the LCCN, as the permalink can be generated from it.

**Comment by BrittanyBunk** [comment]
I guess people could enter in the entire url for the permalink, but same thing - the permalink url could be generated from the LCCN, so it's redundant.

**Comment by hornc** [comment]
It looks like the 'LCCN Permalink' should not be in the Classifications section at all, as they are different things. The LCCN number is stored under 'ID Numbers' -> 'LC Control Number'

**Comment by LeadSongDog** [comment]
The LCCN is a catalogue number, (approximately) serially assigned by publication date.
The LC Class (a.k.a. LC Call number) usually encodes information descriptive of subject.
@BrittanyBunk identified a permalink https://lccn.loc.gov/n80090600 which is to a _Personal name_ LCCN (note the prefix "n"). If we used that anywhere on OL, it should be as an external link from an author record, not in a work or edition record. I've done so for that one in this edit:
https://openlibrary.org/authors/OL150437A/Rie_Cramer?_compare=Compare&b=3&a=2&m=diff

**Comment by BrittanyBunk** [comment]
@LeadSongDog maybe there's confusion (on my part at least), but LCCN's are not only for authors, but also books: 2001001114. As you said, 'n' is for authors. I think there's other letters in front of numbers to signify a non-book too. 

I think you did bring up a bigger issue, and that is that books (like editions) have ID #'s and authors don't, even though there are #'s that are assigned to authors in catalogs.  I will bring this up as another, new issue on github.

It's awesome that you made that edit, but it doesn't address the concern here about the LCCN and LCCN permalink duplication though.

What's an LC call number, and why isn't it in OL?

**Comment by LeadSongDog** [comment]
@BrittanyBunk for that example you give, the LC Classification or LC call no is QB90 .V55 2002. You can see this by clicking your permalink then selecting the MARC tab

**Comment by BrittanyBunk** [comment]
@LeadSongDog awesome. I see. @mekarpeles idk why this was closed. It's still duplicating.
