### ISSUE TITLE
Drop MARC 59X local notes fields on import

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2739]
This edition: https://openlibrary.org/books/OL27794599M/Tractatus_logico-philosophicus
was imported with two local notes fields from the [MARC record](https://openlibrary.org/show-records/marc_marygrove/marygrovecollegelibrary.full.D20191108.T213022.internetarchive2nd_REPACK.mrc:202990862:1752
) which don't add any value:

> 590    $bInternet Archive - 2
> 590    $bInternet Archive 2

https://www.loc.gov/marc/bibliographic/bd59x.html

Since there's no way for us to interpret 59X fields, we should just drop them on import.

@hornc

**Comment by guyjeangilles** [comment]
@hornc I've added you personal label as I thought it was relevant
