### ISSUE TITLE
Sanity check MARC 300$a Extent before using for number_of_pages

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2740]
This edition: https://openlibrary.org/books/OL27092523M/Tractatus_logico-philosophicus
has an incorrectly coded MARC 300$a field:

> 300    $a23 cm. ;$c23 cm.

https://openlibrary.org/show-records/ia:tractatuslogicop00witt_010

which got promoted to the number_of_pages field in the edition record.

We should attempt to do more sanity checking on this field before blindly accepted it. It would be better to have no number_of_pages rather than an incorrect value.

Similar to #2711 

@hornc

**Comment by guyjeangilles** [comment]
@hornc I added your personal label because it seems relevant

**Comment by tfmorris** [comment]
A related number_of_pages issue are these two editions which claim to have 6 and 7 pages for audio cassette and audio CD editions, respectively. Not sure if that was 6/7 hours on the original record or 6 cassettes and 7 CDs or ...

https://openlibrary.org/books/OL8106819M/Paco's_Story_UNABRIDGED
https://openlibrary.org/books/OL8108013M/Paco's_Story_UNABRIDGED

**Comment by LeadSongDog** [comment]
There are many records that show just "p. cm." which is clearly worse than showing nothing.

**Comment by tfmorris** [comment]
It looks like the current code will only store numeric values in the `number_of_pages` field, using the max integer value from all the 300$a subfields:
https://github.com/internetarchive/openlibrary/blob/94143fbd81ce5c43bb0852091bb51f9e016884b9/openlibrary/catalog/marc/parse.py#L419-L431
so I think this is mainly a cleanup task
