### ISSUE TITLE
Search bar on author pages

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2741]
On an author page, an author can have a lot of books there. It's really difficult to go through all of them, so I'm suggesting a search bar specifically for author pages, like https://openlibrary.org/authors/OL9388A/William_Shakespeare

**Comment by guyjeangilles** [comment]
Related: #2064

**Comment by tfmorris** [comment]
A large part of the problem is the massive number of duplicates. If there weren't dozens of "works" all named "King Henry IV, Part 1" there'd be a lot less to plow through. A "search within author" facility would be useful, but only for a tiny fraction of the authors in the system.

**Comment by BrittanyBunk** [comment]
@tfmorris Another issue (I was thinking about creating one) is that you can't sort from a->z. That's what also takes forever too.

I feel that you may be right about that for this moment. However, there are so many books that are not on OL or are but with no author. I can see this becoming an issue in the future. However, it is an issue happening right now (at least for me).

**Comment by mekarpeles** [comment]
@BrittanyBunk please only 1 issue per thread. An issue should addresses exactly one problem (unless it's designed as an epic/project). :)

> @tfmorris Another issue (I was thinking about creating one) is that you can't sort from a->z. That's what also takes forever too.

**Comment by BrittanyBunk** [comment]
@mekarpeles right. I was just kind of brainstorming whether it goes with this issue or a new one. I guess it didn't come across that way, so I apologize.

**Comment by SouthGoingZax** [comment]
Was the search bar that is now on author pages added after this issue was opened (i.e., can this issue be closed?), or is this a request for different search functionality?

**Comment by guyjeangilles** [comment]
Yep this should be closed
