### ISSUE TITLE
Add GitHub tips for beginners

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2742]
Getting started as a contributor can be tricky and some people have trouble with setting up a repository if they are new to GitHub. 

### Describe the solution you'd like
Per community call discussion on 10 December 2019 I've created a step-by-step guide for setting up an openlibrary repository for beginners. This PR is for modifying the CONTRIBUTING file with the link to the [tips wiki page](https://github.com/internetarchive/openlibrary/wiki/New-to-Git%3F).

### Stakeholders
Link added per @cdrini 's request.

**Comment by BrittanyBunk** [comment]
@seabelis I was talking a lot about this with @mekarpeles about my tips for helping this out. You can see them here: https://app.slack.com/client/T03ST9K7K/threads/thread/C0ETZV72L-1576003003.013400

**Comment by BrittanyBunk** [comment]
Also, nothing's written there.

**Comment by seabelis** [comment]
Updated and moved to https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet.

**Comment by cdrini** [comment]
Oh, #2743 is merged now; is this good to close, @seabelis ?
