### ISSUE TITLE
ID #'s for authors: community input preferred

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2744]
As brought up https://github.com/internetarchive/openlibrary/issues/2735#issuecomment-566146908 from #2735, authors have ID #'s too, not just editions. I believe that there should be a field for adding in #'s to author pages, instead of having to manually add them as links, as @LeadSongDog had to.

The first # is obviously their LCCN, but I would like this to issue to have community input for other #'s too. This is in line with the other requests to improve the author pages, such as #2741 

List so far of possible options (in no order, will get updated per community input):
LCCN, OL, Wikidata, VIAF, ISNI

**Comment by tfmorris** [comment]
We should focus on one or a few widely known identifiers such as VIAF or Wikidata. We already store those, but they're not currently editable. See the `remote_identifiers` section here: https://openlibrary.org/authors/OL19690A.json

Is there anyone who's got an LCCN, who's not in VIAF?

**Comment by BrittanyBunk** [comment]
@tfmorris idk, but VIAF is OCLC, so I doubt there's every author there.

**Comment by LeadSongDog** [comment]
As a general principle, it's the author's home country that establishes their identity. VIAF is a federated authority record, pulled from all the member libraries' authority files, so it tends to be comprehensive even at the cost of correctness. ISNI is more carefully curated, so it has lower error rates, and links back to the specific national-level library on which it relied. If an ISNI entry is available, it is more trustworthy than the VIAF record, but both are useful. Wikidata entries can be corrected more readily if both VIAF and ISNI are known to be defective. Usually, however, all three are helpful, and should be linked. Increasingly they cross-link, so when you find one, you have them all. Any of them would be better than leaving OL author records devoid of any provenance.

@tfmorris Probably there are a few recent LCCN name identities that have not yet been picked up by VIAF. I think it's a cataloging-in-process thing: there's some sort of threshold for promulgation. No doubt someone at OCLC could say for sure.

**Comment by hornc** [comment]
Duplicate of #853 ?

**Comment by BrittanyBunk** [comment]
@hornc yes, will close
