### ISSUE TITLE
Remove dead addcover.html file

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2745]
This file looks dead; https://github.com/internetarchive/openlibrary/blob/310e4d55904033905aa7caa5fabeb82e78b9f71e/openlibrary/templates/books/edit/addcover.html . It was mainly only edited at its inception 8 years ago (except for some generic ~formatting fixes). It seems to have been replaced by https://github.com/internetarchive/openlibrary/blob/310e4d55904033905aa7caa5fabeb82e78b9f71e/openlibrary/templates/covers/add.html

## Summary of Requirements
- [x] Confirm no references exist
- [ ] Remove addcover.html
- [ ] Remove any CSS/JS that is no longer relevant

## Stakeholders
@seabelis

**Comment by mekarpeles** [comment]
@ScarlettRed thanks for submitting a PR for this!
