### ISSUE TITLE
Should "Printing" be listed?

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2751]
Continuation of issues #561. The reasons I bring this up
- usually a person can tell if a book is still in copyright if it's still getting printed
- it's listed in physical books
- it's an identifier
- demonstrates the popularity of the book or the publisher's needs/wants/capabilities of a time period
- a further subcategory to categorize books

why it shouldn't be added in:
- it's not going to be a different book from the first printing. It's all the same edition.
 (rebuttal): could be added in as fields instead (1st printing: 1890, 2nd printing, 1891, etc.)

**Comment by tfmorris** [comment]
In my opinion, we don't want a separate record for every printing of every edition. Edition is plenty.

**Comment by seabelis** [comment]
For the scanned books I usually add it.

**Comment by BrittanyBunk** [comment]
@tfmorris Good insight, and I thought that way, until after reading what you wrote. When there's a different printing, it'll look different, and thus be kind of a different 'book' (as in the two print copies are no longer the same). But you helped with forming my opinion, which is awesome.

@seabelis I think you have a good point there. Didn't think of that. However, as @tfmorris said, it kind of shouldn't be like that. I usually add it in the description of the edition, but it just doesn't make sense, as not every edition will have the same number of prints on it. That's why I'm bringing it up - as how it's set up creates confusion (for me).

Maybe there should be subrecords for editions, to show each printing. It wouldn't be a full record, but just something to show it's not the same, exact book.

**Comment by seabelis** [comment]
Here are two paperbacks with identical information, but different covers and printer's keys. https://openlibrary.org/books/OL22141062M/The_Celestine_Prophecy, https://openlibrary.org/books/OL27255471M/The_Celestine_Prophecy. If these were books in hand  and wanted you to enter them, it would be appropriate to include the printing information to differentiate and to indicate which is earlier.

**Comment by seabelis** [comment]
I agree that it would sometimes be useful for the edition records to have children so that one could note each printing without creating a new record; this has been raised before in a somewhat different context, but I don't think this would be considered a priority.

**Comment by BrittanyBunk** [comment]
Continuation of #2391. @seabelis I talked a little about it there in a different context, but this was different, as it was about who printed vs published, although it does relate (as maybe where it's printed changed, and some books change publishers with each printing, so these are really important to know, to prevent confusion - as then a book has multiple publishers - and an edition may only show 1 without separating into each print: this is where I feel it is important to separate by print).

I just worry about creating 'new editions', as they're not new editions - which creates more confusion. I just feel no matter what I do, without separating out the prints from the editions, confusion is created.

It's true that it's not a great priority right now, as there is the bigger issue of how to categorize on OL (seen by all the issues raised in your #1586 and other ones too). This just is a continuation of that. When that gets prioritized, this will too. I mean, there may be a need for an overhead directory for pages that shows 'series -> work -> edition -> printing' (or some other setup), where printing will be listed - if print's are going to be in that list.

**Comment by seabelis** [comment]
This isn't really the same as series or volumes. To keep this simple, if the printing number is specified, it is fine to note that with the edition information.  Example: https://archive.org/details/dubliners00joyc_3/page/n3

**Comment by BrittanyBunk** [comment]
that's a link to the archive page. See the question for me that would help me decide whether new records or subrecords should be in the OL for prints is if we should upload every new print to the IA and count it as a new book. Personally, I am leaning towards yes, as the covers and writing is different enough to necessitate separating from each other and noting it. On the other hand, this could be more advanced and past what the IA/OL is attempting to do at this time, so it's kind of situational for the moment to me too.

**Comment by seabelis** [comment]
Yes. That is an example of an edition where the printing is specified.

**Comment by BrittanyBunk** [comment]
@seabelis ok, I get it now. Do you believe writing out different prints in editions is sufficient?

**Comment by seabelis** [comment]
> Do you believe writing out different prints in editions is sufficient?

Yes. Edition and printing if stated. If there's a stated printing + printer's key include the lowest number of the key in parenthesis.  See https://openlibrary.org/works/OL53180W/The_Celestine_Prophecy for many examples.

Here is information about the printer's key if you are not already familiar with it. https://en.wikipedia.org/wiki/Printer%27s_key Not all publishers use this or use this, so only include the information if you're sure it's correct.

**Comment by BrittanyBunk** [comment]
@seabelis I see what you're saying, but I don't get that impression when I look at your edits to understand it's a printing. The reason is that books will have a # given by the publisher as it's # in a series, so it's difficult to distinguish your printed # from the # of the book in a series. https://openlibrary.org/books/OL9573539M/Accent_on_Achievement_Book_1_Flute - the #7081. How can I tell the difference between that and a printing #. Because it's difficult for me, that's why I would like more separation. It's still confusing.

I always wondered why the numbers at the bottom were there. Thanks for helping me with that.

I mean, to standardize everything, why don't we have a 'printer's key', along with 'print #' - like which print it is or how many it's done (the work would show this, or edition if we have print subrecords), to help people understand this distinction - like you showed me - and maybe they'll learn something new too - as well as be clear about which print they're looking at? Is this something that's necessary?

**Comment by seabelis** [comment]
@BrittanyBunk If an edition is part of a series, that should go into the field labeled

> Is the book part of a series? The name of the publisher's series. For example: The Story of Civilization, Part III
Any information in the edition field will not (should not) be about the series (with the exception that there are some series names that include the word edition, this may end up there). 

In your example, the #7081 seems to be a catalog number, not a series number. The series, in this case, is pretty also the books title, subtitle:
Title: Accent on Achievement: A comprehensive band method that develops creativity and musicianship
ST: Flute, Book 1

The edition field is sufficient for the imprint information as well; there really doesn't need to be a designated field for imprint or printer's key as the terms 'edition' and 'printing' are sometimes used interchangeably. The information can all go together into the edition field. For example '1st edition, 5th printing'; it kind of belongs together. Having too many fields on a form will make it unnecessarily long and ultimately less convenient to use.

**Comment by BrittanyBunk** [comment]
@seabelis I see. Where does the catalog # go then? Also, if we're putting the printing next to the edition, would we be able to state that designation there (like name of edition and print)?

**Comment by seabelis** [comment]
There is no field for catalog number, you can put it into the notes section,

**Comment by BrittanyBunk** [comment]
@seabelis Is it ok where I have it in the series section? The issue is that 'series' is not clear, as is it the catalog number in the series, or its placement in the series? This comes up when I look at TV shows, where it has both the placement number and number in the series. It's just really all so confusing.

**Comment by LeadSongDog** [comment]
Going back to the issue at hand, @BrittanyBunk asked "Should "Printing" be listed?" 
I would have to say "no, except in highly exceptional cases". Most printings are not significantly different from each other, and they normally carry the same information, word for word. Where there are differences, it is usually restricted to packaging trivia (esp. cover drivel), and not any sort of content editing. Any associated identifiers and classification will be the same between printings.

The exception we may see will be multiple IA, Hathitrust, or Google scans of the same printed edition, each with their own identifier.  If these are of distinct printings, then that could be captured, though it is unlikely to matter. Variations in the quality or completeness of scanning is likely of greater importance.,  unless there is important marginalia captured.

**Comment by BrittanyBunk** [comment]
Also, another reason for 'printing' to be listed is to reveal books that are out-of-print - as it's really important to know - for the value/difficulty in finding. I really think about it's status like that.

**Comment by mekarpeles** [comment]
This is a very long conversation. Given the feedback I've seen here, it seems like action is not required -- the notes section seems sufficient. Leaving/deferring to @seabelis in case she disagrees :)

**Comment by seabelis** [comment]
Just to clarify; I mentioned the catalog number can go into the notes section. The imprint, if stated, should go with the edition information.

**Comment by BrittanyBunk** [comment]
@seabelis that seems like a conversation for another github issue. Should we create one and add our concerns there - like where (and how) to put the catalog # in? I think we could do better than making it lost in the notes section (to me, it's more valuable than that), so creating a new github issue's a good way to go for me at least.

**Comment by BrittanyBunk** [comment]
@mekarpeles I think this is still causing great strife, as seen with the meeting today, 3-1-22 https://docs.google.com/document/d/1LEbzsLZ1F9_YIQOoZzO7GoZnG1z-rudhZ9HNtsameTc/edit# . I agree this shouldn't be looked at until the editions is indexed in solr, but when we get rid of the works level, this will be great to reopen to talk about. I actually think it might help to reopen this now, as the reason it got closed was for the wrong reasons - as I said in the previous comment - there was a divergence from this issue that would be its own github issue, so this one shouldn't be closed for that or because it's been talked about too much. It's still a problem and I believe something we'll have to address to avoid the overabundance of editions that aren't editions.
