### ISSUE TITLE
author data dump json malformed for names ending with quote

### ISSUE THREAD

**Issue by brierjon** [internetarchive/openlibrary#2772]
Using the ol_dump_authors_2019-11-30 and open refine I found that applying the grel transform to extract the name values from the json provided in the dump results in most correctly being extracted, but 2644 failing. 

Transform applied in OpenRefine Version 3.2 [55c921b]: grel:parseJson(value).get("name")

### Evidence / Screenshot (if possible)
I produced the following TSV of the subset of affected Authors in case its more than just the ending quote causing the value exaction from failing. [Download TSV of author json parse errors.](https://drive.google.com/file/d/1oh_ti-2U1Sqs-uxgihI-CJUUqIp57C6f/view?usp=sharing)

TSV of failures with first three columns being original to the dump and the fourth column named "Name" which should just output the value of the key "name", but where the parse fails the error produced is provided. 

Example Author which produces invalid JSON in the dump:
OL1846932A which lists as Denmark. Arbejdsgruppen vedrørende "Meddelelser om Grønland."

### Steps to Reproduce

1. Download Author Dump
2. Open as TSV in OpenRefine
3. Transform cells with "Edit Cells > Transform > parseJson(value).get("name")"
Most should correctly parse, but a number will fail as detailed above.

* Actual: parse errors
* Expected: Extraction of names from JSON structure

Example of Errors in the TSV:

`parseJson failed: Unexpected character ('n' (code 110)): was expecting comma to separate Object entries at [Source: (String)"{"bio": {"type": "/type/text", "value": "> \"Eversley, William Pinder, B.C.L. Queen's Coll., Oxon, M.A., a member of the South-eastern circuit, reporter for Law Times in Queen's Bench division, a student of the Inner Temple 14 April, 1874 (then aged 23), called to the bar 25 April, 1877 (eldest son of William Eversley, Esq., of London); born \u2060, 1851. \r\n> \r\n> 7, King's Bench Walk, Temple, E.C.\" \r\n> ...[in Foster's _Men at the Bar_][1]\r\n\r\n\r\n  \r\n\r\n[1]: https://en.wikisource.or"[truncated 482 chars]; line: 1, column: 571]`

`parseJson failed: Unexpected character ('k' (code 107)): was expecting comma to separate Object entries at [Source: (String)"{"last_modified": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "type": {"key": "/type/author"}, "name": "Denmark. Arbejdsgruppen vedr\u00f8rende \"Meddelelser om Gr\u00f8nland.\", "key": "/authors/OL1846932A", "revision": 1}"; line: 1, column: 205]`

`parseJson failed: Unexpected character ('k' (code 107)): was expecting comma to separate Object entries at [Source: (String)"{"last_modified": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "type": {"key": "/type/author"}, "name": "Salzburg (Austria). Galerie \"Kunst der Gegenwart.\", "key": "/authors/OL2168653A", "revision": 1}"; line: 1, column: 184]`

`parseJson failed: Unexpected character ('k' (code 107)): was expecting comma to separate Object entries at [Source: (String)"{"last_modified": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "type": {"key": "/type/author"}, "name": "Belgium. Commission de la \"Belgica.\", "key": "/authors/OL2504291A", "revision": 1}"; line: 1, column: 170]`

`parseJson failed: Unexpected character ('p' (code 112)): was expecting comma to separate Object entries at [Source: (String)"{"name": "German correspondent of \"The Continental echo.\", "personal_name": "German correspondent of \"The Continental echo.\", "last_modified": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "key": "/authors/OL2596999A", "type": {"key": "/type/author"}, "revision": 1}"; line: 1, column: 64]`

### Proposal & Constraints

Fix JSON dump to account for errors noted in the file:
1. make sure to that the quote closes the values for the authors ending with a quote.
2. ??? maybe others in the 2644 parse errors that I overlooked

**Comment by cdrini** [comment]
When I grep for the second record, I get:

`/type/author    /authors/OL1846932A     1       2008-04-01T03:28:50.625462      {"last_modified": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "type": {"key": "/type/author"}, "name": "Denmark. Arbejdsgruppen vedr\u00f8rende \"Meddelelser om Gr\u00f8nland.\"", "key": "/authors/OL1846932A", "revision": 1}`

i.e. the quotes are escaped. Some implementations of TSV treat double quotation marks as the escape instead of backslash `\"`. The above record in the dump contains a double quotation mark at the end of the `name` field. My guess would be that's what's causing the issue. In e.g. Postgres when importing from a TSV, you can specify the escape char; does OpenRefine give any options when importing a TSV?

**Comment by tfmorris** [comment]
`jq` can parse those entries without a problem and, as @cdrini points out, your extract doesn't match the contents of the original file. Here's an extract with 3 of the problematic records as they exist in the original file:
[authors-with-quotes.tsv.txt](https://github.com/internetarchive/openlibrary/files/3992990/authors-with-quotes.tsv.txt)

The only characters which need to be escaped for TSVs are TAB (obviously) and EOL (ie \r \n) characters. The double quote characters are being escaped for the JSON encoding and shouldn't be touched as part of the TSV parsing. Unfortunately, I don't see any import options which will force OpenRefine to do this correctly.

As a workaround, import the TSV as a plain text file, then, separately, use "Split into several columns" with \t as the separator and a max of 5 columns, then use `parseJson()` on the results of that. Or, if you don't care about any of the intermediary data, just use `value.split('\t')[4].parseJson().get('name')` to do it all in one operation.

**Comment by cdrini** [comment]
Here are the options I used in postgres: `delimiter E'\t' escape '\' quote E'\b' csv`. I used a "dummy" character that shouldn't appear anywhere as the quote character (i.e. `\b`). Unfortunately it looks like OpenRefine doesn't let you use backslash chars in the TSV options :/ But I was able to think of a  character which OpenRefine _did_ accept which might work...

![image](https://user-images.githubusercontent.com/6251786/71327522-8d92d400-24d7-11ea-9967-a166fb10b12c.png)

:P That fixes the row in question, but it would error on any rows that happen to contain 😭

**Comment by brierjon** [comment]
Thanks for the notes, obviously issue created without full review (or reviewing the initial data due to haste of getting the data in after not using openrefine in a while). I've excluded the selection for now and will circle back on this.
