### ISSUE TITLE
Frequently used float to top in language input box

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2775]
Instead of typing in the language in the box repeatedly, if someone already typed in the language before, they could just click the box and the most recent languages that were typed in before will appear.

When adding another language, the frequently used will appear there too.
![image](https://user-images.githubusercontent.com/55302685/71380782-73173400-2585-11ea-862d-5d5c21df0fe4.png)

**Comment by mekarpeles** [comment]
A dropdown may be a better affordance (i.e. autocomplete).

**Comment by BrittanyBunk** [comment]
@mekarpeles It's already like it. It's just the most frequently used (like if I typed it in 3 times) would be at the top of the dropdown menu that currently exists: 
Like if my top 2 languages were English and Latin, this is what it would look like (different for someone else):
![image](https://user-images.githubusercontent.com/55302685/71625323-052dc680-2b9c-11ea-83c3-6679c24988dd.png)
Definitely the 1st would work for the first view. The second view (when typing in) could be the 2nd or 3rd, but I'm opting for the 3rd.

**Comment by mekarpeles** [comment]
Ah, I don't think this is worth the engineering effort to implement. It's not a common enough operation to optimize. Tagging as will-not-fix.

**Comment by BrittanyBunk** [comment]
@mekarpeles I agree that it's not worthwhile to do something expensive (I prefer costs stay low, so I don't feel compelled to donate). It's just out there when the time comes that it's needed :)
