### ISSUE TITLE
Return book button should go to loans page not editions page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2777]
"Return Book" workflow. when you return a book through your "My Loans" page you are redirected to the edition page of the book you just returned. is that because there is an assumption that many want to re-borrow? i'd think you would 1) remain on the "My Loans" page, 2) that book would disappear and then 3) you could possibly return others. redirecting to the page of the book you just returned seems a bit non-intuitive.

Reported by @JeffKaplan

**Comment by mekarpeles** [comment]
I think this can be done within the return code in plugins/upstream/borrow.py or core/lending.py?

**Comment by MayankVir** [comment]
I can work on this issue!!

**Comment by Bhavna777** [comment]
I would like to work on this issue.

**Comment by b-thebest** [comment]
Can I work on this issue

**Comment by khabdrick** [comment]
Hello @mekarpeles , this issue has been open for a while, is it still available to be worked on, or there's no need to work on it anymore?

**Comment by jamesachamp** [comment]
@b-thebest Sorry for the delay!  Are you still interested in working on this?

**Comment by Evazisouli** [comment]
Hello! Could I work on this issue?

**Comment by b-thebest** [comment]
> @b-thebest Sorry for the delay! Are you still interested in working on this?

Yes, I am interested. Please assign this issue to me

**Comment by cloudguruab** [comment]
I would like to contribute and work on this issue, is that possible?

**Comment by ujjwaltwitx** [comment]
I am new to open source contribution and I would love to work on this issue if it can be assigned to me.

**Comment by jimchamp** [comment]
@ujjwaltwitx welcome!  Let me know if you need any help getting started.
