### ISSUE TITLE
Add 'recipes' carousel to home page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2780]
The recipe books that I've uploaded seem to be popular. So adding them to the front page would make them more accessible, as I feel people would use them a lot and it's a way to encourage good health.

What I'm trying to figure out, is what's included in here?
- Since the health ones are popular too, I would assume that this would include maybe remedies too - as the popular ones talk about individual ingredients and their medicinal use. I don't think saying 'recipes/remedies' makes sense - as remedies are recipes to some extent - but it's good to know.
- The DIY ones too are popular. Should recipes be exclusive to food, or do DIY instructions count too? Would it then be called 'instructions' instead of 'recipes', as 'recipes' are instructions?

**Comment by mekarpeles** [comment]
We're actually going to be moving away from having Book Subjects on the homepage.

Instead the plan is to have the /subjects page be a landing page with subject-specific carousels.

It may in fact even have a Recipes carousel!

**Comment by BrittanyBunk** [comment]
@mekarpeles cool. Another thought: what if the book subjects are on the home page and when clicked on, people can view the carousels - so the info's easy to get to? Like I wouldn't want to go through 20 carousels just to get to the recipes one. It's too cluttered that way. Icons (for mobile at least) would be nice. I mean, I don't want to get in the way of the progress/thoughts of what you're working on, but throwing it out there for options.
