### ISSUE TITLE
Create better pages for libraries on OL

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2781]
https://openlibrary.org/libraries/boston_public_library looks really bad (all of the library links I looked at do - but I only saw 2). I mean, I think something simplistic like the author pages would work. What's missing:
1) similarity to author pages (except, should libraries put their entire catalog on their page - like link every OL work onto their page? If so, maybe they'll need more structure, like a bookshelf style - where it's a walkthrough by dewey decimal rows, which includes genre - since it'll be more books than a regular author page)
2) open library ID - it would help for libraries to have these
3) editable by the community

**Comment by mekarpeles** [comment]
We used to have a /libraries page. These libraries are a part of a legacy program which Brewster decided to discontinue. It's more likely we'd delete these then invest time in fixing them. Classifying as `Will Not Fix`
