### ISSUE TITLE
Separate stats by date (s2)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2782]
I can't click on stats individually to know what's going on. When I click anywhere, it just shows me from the most recent edits without being able to filter by date. It would be awesome if I click on a date, then it'd take me to that date in the stats direct page. Then I could see individually what's going on.

Overall, there's just a lack of interactivity with the data for users that I would like to see more of.

**Comment by mekarpeles** [comment]
What individual stat do you need? How many people will need this feature? What's the compelling use case? Is there no way to get this information from the data? If not, then how will we get this data? If we need to build something, why is the engineering effort justified for the outcome (how valuable, e.g. in $'s) is the outcome? Consider that a project which takes 1 week may cost ~$5k in engineering resources

**Comment by BrittanyBunk** [comment]
@mekarpeles it's kind of tricky to talk about this and answer all the questions if it's closed, as I'm confused as to whether it makes sense to answer it all.
