### ISSUE TITLE
Better directs for stats pages (s1)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2783]
Right now, here's the pages when clicked on for each stat:
Around the Library  Here's what's happened over the last 28 days. More recent changes.
1. Unique visitors -> https://archive.org/stats
2. New members -> https://openlibrary.org/recentchanges
3. Catalog edits -> https://openlibrary.org/recentchanges
4. Lists created -> https://openlibrary.org/lists
5. Ebooks borrowed -> https://openlibrary.org/borrow

Issues:
1) two go to the same page (#'s 2 and 3). 3 should be https://openlibrary.org/recentchanges/edit-book#everything (I can't get the url to automatically go to the 'everything' tab, but that's where it should start at). I don't see a 'new accounts' tab, but if it was created, it'd be used for 2.
2) 1 is the legit stats page I'm looking and hoping to see. However, what I see is not what I was looking at from the front page. There's too many of the same graphs for the top part and not really useful stuff on the bottom. Where's filtering by metrics, like human (location, age, etc.), computer (Google analytics style - browser, operating system, electronic device, etc.), website status (a.k.a. standing on the internet, or klout: Alexa), views (unique IPs, pageviews requests, etc.), website management (capacity (i.e. bandwidth), servers (i.e. headend) etc.)? 
Newcomers and website standing should be separated.
Views and website management is more backend, so it should be labeled so. 
3) https://openlibrary.org/lists looks a little botched. It'd be good to have a banner with the stats, where people can click on individual dates - and there'd be two columns for that day: 1) recently added, 2) recently changed. The top description and search bar are ok to keep (the page is almost there - just the bottom needs a fix).
4) 5 goes to all the books with 'read' on them, when it should go to the 'borrowed'. An idea page to go to is a page like now, but with all the recently returned items instead - in order - like how it is on the front page (although there's no separate page for it - which would be good to create for this purpose)

**Comment by mekarpeles** [comment]
This groups far too many things together to be able to solve. Let's please create very specific issues w/ clear beginning and ends (e.g. "List page styling broken"). As is, this issue is a collection of notes and it would be very difficult for a developer to come in and start working on one of them.

**Comment by BrittanyBunk** [comment]
@mekarpeles I'm not sure I understand. Should I delete all my examples, create individual issues per example, or start with a new issue (maybe close this out) and add 'list page styling broken'? This will help me write clearer issues to work on.

**Comment by BrittanyBunk** [comment]
I guess this is a continuation of issue #1607
