### ISSUE TITLE
Better homepage stats (s3)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2784]
1) a separation of catalog edits by humans and bots would be cool to compare.
2) All time stats (a.k.a. accumulation updates): show the current total number of each stat and list it underneath the monthly breakdown (like under 'lists', it'd have the # for the total of lists on the entire website underneath)

After this, it's community discussion. Should there be more or less? Should it have, say 'most popular genre' or something? What would be good and work here?

**Comment by BrittanyBunk** [comment]
@jessamynwest since you're a stats person :)

**Comment by hornc** [comment]
The bots vs users and different  kinds of edits breakdown are available from https://openlibrary.org/recentchanges and there are a few other url parameters that could have better links if we need them. Does this cover some of these requirements?

**Comment by BrittanyBunk** [comment]
@hornc I think I meant that the separation's on the home page - as what you're talking about is the page one gets directed to when clicked on. If those stats could be separated on the home page, that would be cool.

**Comment by mekarpeles** [comment]
I think, at this point, our display of stats should serve very specific use cases from the community which aren't being served. We do have an issue regarding our stats #2481 but we just don't have the engineering bandwidth to implement stats across the website.

**Comment by BrittanyBunk** [comment]
@mekarpeles I have an idea. There are many free plugins and widgets on the internet. I found this one: https://clustrmaps.com/. Just having that on the unique visitor's page would be better. I mean. it might be better if the pages aren't able to be clicked on, as it doesn't really have usable stats for users. Or, a lot of the ones that aren't usable to the community are removed, so the ones that developers need are on the developer's site (the dev.openlibrary.org). That way, it is going to be more user-friendly.

Yes, there's issues with the stats, but this issue is different. I mean, if I'm provided a chance, I could go though and show the free widgets that could be added that are needed for the community and what should be removed. These shouldn't take much engineering bandwidth to accomplish (if they're free and copy/paste), but are more helpful than now.
