### ISSUE TITLE
"Cover guidelines" link shows up when adding authors images

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2785]
This should not appear when doing so. Instead, maybe 'author guidelines' could go there.

**Comment by mekarpeles** [comment]
@seabelis tagging you in case you feel there's a useful change in copy we may want to apply, or if we should e.g. hide cover instructions for authors covers.

Thanks @BrittanyBunk !

**Comment by seabelis** [comment]
@mekarpeles I was aware that it would be visible in the upload screen, but is this an issue?

**Comment by mekarpeles** [comment]
cc: @Sabreen-Parveen if you'd like to try this issue and ask questions

The issue occurs here:
https://openlibrary.org/authors/OL6784512A/Toni_Morrison -- when you **log in** and then hover over the author image and click "Manage Author Photos" it pulls up a modal (popup) which contains a link: "Cover Guidelines".

This popup calls an iframe and loads it with this page:
https://openlibrary.org/authors/OL6784512A/Toni_Morrison/add-photo

This add-photo page gets rendered by this template:
https://github.com/internetarchive/openlibrary/blob/37bc6df47eb23db15059310eebf45b71949d32bc/openlibrary/templates/covers/add.html

At the end there's a block that looks like:
```
<div class="imageIntro smallest"><a href="/help/faq/editing#picture" target="blank">$:_("Cover Guidelines")</a></div>
```

We could make this conditional using similar logic at the top of the file, e.g:
```
https://github.com/internetarchive/openlibrary/blob/37bc6df47eb23db15059310eebf45b71949d32bc/openlibrary/templates/covers/add.html#L6-L8
```

i.e. `$if doc.type.key == "/type/author":`

![openlibrary org_authors_OL6784512A_Toni_Morrison](https://user-images.githubusercontent.com/978325/100947064-a8c4dc80-34b9-11eb-8314-a44de309184d.png)

**Comment by mekarpeles** [comment]
@seabelis it may make even more sense for us to just change "Cover Guidelines" to "Image Guidelines" and then add a small section to the existing FAQ for authors.

I don't think there's really anything wrong with leaving it Cover Guidelines, personally :P 
I think completely removing the link from the Authors image manager would be the worst of the options.

@seabelis do you have a proposal for @Sabreen-Parveen? Perhaps we should just update the text so it doesn't say "Cover"?

**Comment by BrittanyBunk** [comment]
good idea - I like 'image guidelines' better - there it could be separated based on which image. "Cover" doesn't make sense for authors, as people may accidentally add in cover images instead of author faces.

**Comment by seabelis** [comment]
@mekarpeles No objection to a change in wording. There are no specific guidelines for author images, however. There are issues with people changing covers to editions other than what is specified on the record, but I've really not seen people change author photos to other authors.
