### ISSUE TITLE
Grouping edit ideas for author page layout here (a2)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2786]
The author pages layout right now, I feel, are creating issues due to vagueness. People are adding books to the wrong author and also creating multiple authors (and even bots too). So I'm grouping everything here:
- title tab: #2663
- ID's: #853, #2786
- identifiers: Birthplace, Education (degrees and university), Companies worked at (and when), profession (extremely important, #145), pseudonym (different from 'other names')
- UI layout: will create new github issue for later, but #2785 is a start, pseudonym's great underneath the author's name

Example page with identifier ideas and issues created: https://openlibrary.org/authors/OL463607A/Mark_Williams. The page shows that books that aren't by the author were placed there, possibly due to multiple authors named Mark Williams.

**Comment by tfmorris** [comment]
> https://openlibrary.org/authors/OL463607A/Mark_Williams. The page shows that books that aren't by the author were placed there, possibly due to multiple authors named Mark Williams.

@BrittanyBunk Exactly right. That was a record with books from many authors conflated together. The correct solution is to move them to the correct specific author pages and then delete this page when it's empty. By converting it to be about just one of the authors represented, you've changed the meaning/identity of the record.

The mess was caused by bad MARC import code, not by a bad UI.

**Comment by BrittanyBunk** [comment]
@tfmorris the page shouldn't be deleted, as it's for the musician. It's just that the ones that don't belong need to go. 

I thought it was supposed to be about the one author I made it to be, which is why I put all the books there. What should I do now?

**Comment by mekarpeles** [comment]
@BrittanyBunk this seems like a conversation which should be continued on slack; the solution likely requires human intervention, I believe (and not an engineering solution).

**Comment by BrittanyBunk** [comment]
@mekarpeles I don't get what needs to be continued on Slack. Maybe some of it where we take out the works from underneath the author that don't belong. The rest of it should stay open: the part about having fields for identifiers. This is an engineering solution, requiring codes to add in field boxes onto author pages with the identifiers and other items I mentioned on author pages.

 I mean, we could delete the other conversation part about an author being conflated, as it's not the main topic. What part were you hoping I'd continue on Slack?

**Comment by BrittanyBunk** [comment]
the author page should have a field box for genres they are a part of too.
