### ISSUE TITLE
Add authors in by OL ID # (a3)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2787]
This is not the most important issue for improving the author pages. When there're multiple authors, it's difficult to pick the right one. However, if a person (or bot) knows of the OL ID, then they could add that in - instead of choosing among different ones and accidentally picking the wrong one.

It is however an important issue, because I can't add some authors (that already exist) on a work's page. The only way is to create a 'new author' for the same person to add them into the work. This may be one of the reasons for so many duplications of the same author. This is why I'm proposing an alternative solution by also being able to add in by ID, as then it overrides this generated problem.

**Comment by tfmorris** [comment]
The author autocomplete dialog accepts OL IDs. If you find a place where it doesn't, please be specific about where and it can be fixed.

The time lag for index updates is a separate, unrelated issue which also affects usability of the author autocomplete dialog.

**Comment by BrittanyBunk** [comment]
@tfmorris You're right, I see it now - it does work. I guess the issue is when I first create a new author, it doesn't use the OL ID right away. So I think that's where the website should work on accepting it - like allowing people to enter in the new author ID in right after it's created.

**Comment by BrittanyBunk** [comment]
so should I leave it open to be worked on for being faster in acceptance of the newly created authors, or close it, as it's not an issue?

**Comment by mekarpeles** [comment]
This issue should be closed; the issue has been resolved.
