### ISSUE TITLE
Edit wording for counts under author's name in search (a4)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2788]
One example is on https://openlibrary.org/search/authors?q=john+o%27reilly where if I click on https://openlibrary.org/authors/OL7317095A it shows 1 work. There are so many like this:
![image](https://user-images.githubusercontent.com/55302685/71531571-20e75300-28a4-11ea-9660-ad7d3c2e0a5b.png)

So I'm proposing a reword from "**0 books**, including") to say instead: "**# Ebooks**, # Works, # Editions". Then the number will show the true number of works for books, followed by the sum total of editions for all the works combined. 

I understand now that 'books' meant 'ebooks' - and since there's an ambiguity between the cataloged works in the OL and the actual scans in the IA - using 'ebooks' would discern that it's about the IA availability, not the OL records.

I mean, better yet would be: "**# Ebooks Available**, # Ebooks, # Works, # Editions"

**Comment by tfmorris** [comment]
We don't currently track total edition count, so this would need to be added to the index.

What value would it add to the user?

**Comment by BrittanyBunk** [comment]
@tfmorris me personally - if I see that the editions number is lower - when it's supposed to be higher (and another author's vice versa) - I know something's wrong and I can correct it.

For the average user, maybe they like looking through many editions, or maybe they don't. It helps them decide when it's there. Maybe one day, they don't want to scroll through a lot, and other days they do. So comparing the edition to the number of works helps with that. It's just a preference is all.

**Comment by mekarpeles** [comment]
"books" in this case means works, not ebooks. 

The real problem is the `solr` Author indexing seems to be completely stale, which is documented in #628.

Closing this issue now that it's use case is linked to #628. Thank you!
