### ISSUE TITLE
BWB prices/sponsorship not working

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2789]
### Summary
- Functional outage of sponsorship from 2019-12-27 00:09 EST - 18:00 EST (~18 hours)
- Investigators: @mekarpeles @cdrini 
- Cause: BWB API updated to using https exclusively, causing some outdated python packages to start failing
- Fix: Update the packages and `pip`

### Time Log

- @cdrini **2019-12-27 00:09 EST** noticed BWB prices/sponsorship button missing; notified @mekarpeles 
  - Used https://openlibrary.org/books/OL9700306M ; which should be sponsorable
- @mekarpeles **2019-12-27 00:11 EST** Began investigation
- @mekarpeles **2019-12-27 00:25 EST** Restarted memcache, no luck
- @mekarpeles **2019-12-27 01:09 EST** Notified BWB
- @mekarpeles **2019-12-27 01:34 EST** Switched to using python `requests` module; fixed on dev, but still broken on prod (#2779). This suggested it was something config related.
- **2019-12-27 08:54 EST** BWB said they recently "enforced https across our domain because of a PCI compliance scan"
- Minimal test used on dev/prod: `import requests; requests.get('https://products.betterworldbooks.com/service.aspx?ItemId=9780375806704')`
```
/opt/openlibrary/venv/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:380: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning,
/opt/openlibrary/venv/local/lib/python2.7/site-packages/urllib3/util/ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/opt/openlibrary/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='products.betterworldbooks.com', port=443): Max retries exceeded with url: /service.aspx?ItemId=9780375806704 (Caused by SSLError(SSLError(1, '_ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))
```
- https://serverfault.com/questions/866062/easy-install-and-pip-fail-with-ssl-warnings Suggested updating pyOpenSSL and cryptography (which varied on the 2 servers)
- @mekarpeles ~ **2019-12-27 17:00 EST** updated pyOpenSSL and cryptography to match dev0; no luck
    - pyOpenSSL is prod: 17.5.0; ol-dev0: 19.1.0
    - cryptography is prod 2.3.1; ol-dev0: 2.8
- @mekarpeles Instructions at https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2 suggested running `import urllib3.contrib.pyopenssl` which errored
- https://stackoverflow.com/questions/47369117/python-cryptography-error-cannot-import-name-certificate-transparency suggested this was related to our pip version
- @mekarpeles Updated pip on prod from `1.5.4` to `19.3.1`
- @mekarpeles Issue resolved

**Comment by tfmorris** [comment]
It seems like another useful/necessary followup would be to audit all of our outbound requests to see if there are any remaining which use http instead of https. These are bad practice to start with and are likely to start failing as folks tighten up their security. Any endpoints which offer https support should be switched immediately.
