### ISSUE TITLE
Input boxes on /edit pages too small

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2792]
Boxes that have a lot in it are too small to write in. When I'm trying to look through them or highlight to copy/paste, it's really difficult and tedious when working with the small boxes. Recommendations:
- "How would you describe this book?"
- Table of Contents
- Any notes about this specific edition?
- Description of this edition

There's space on the pages for this, so it shouldn't be an issue.

**Comment by LeadSongDog** [comment]
Boxes used to be resizable. This is some kind of regression.

**Comment by mekarpeles** [comment]
@LeadSongDog is there any /edit page in the wayback machine which may be able to show us what these used to look like?

**Comment by BrittanyBunk** [comment]
@mekarpeles the wayback machine wouldn't save something like that, as you need an account to access that part - and the wayback doesn't allow for that.

**Comment by LeadSongDog** [comment]
@mekarpeles 
Just as the input box I am now typing in on github. The bottom right corner has a grab handle for resizing. It seems to be present today on Win7Pro (both Chrome and FF). Not sure what has changed.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I see the grab handle on mine too. I'll close it out.
