### ISSUE TITLE
Record updating API 500s when utf8 characters present

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2794]
Not sure if I this is the actual cause of the problem, but that's my leading hypothesis right now. Could be an error in the JS as well, maybe?

### Steps to Reproduce

1. Login and go to https://openlibrary.org
2. Try to run the following in the browser's console:

```js
var url = 'https://openlibrary.org/works/OL8135503W.json';
var data = await fetch(url).then(r => r.json());
await fetch(url, {method: 'PUT', body: JSON.stringify(data)});
```

* Actual: status 500: Internal Error
* Expected: status 200

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF71
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@hornc

**Comment by hornc** [comment]
Cannot reproduce, or resolved:

```
var url = 'https://openlibrary.org/works/OL8135503W.json';
var data = await fetch(url).then(r => r.json());
await fetch(url, {method: 'PUT', body: JSON.stringify(data)});

-> Response { type: "basic", url: "https://openlibrary.org/works/OL8135503W.json", redirected: false, status: 200, ok: true, statusText: "OK", headers: Headers(9), body: ReadableStream, bodyUsed: false }
```
