### ISSUE TITLE
Create user language preference setting

### ISSUE THREAD

**Issue by justcomplaining** [internetarchive/openlibrary#2815]
As discussed in #791, internationalization is currently only available through browser settings. This creates problems especially for those who use the site in a language that is ill-supported and who would rather be using it in (e.g.) English without changing their overall browser settings.

It should be possible for visitors to override the browser settings on a site-specific basis, ie just for openlibrary.org. This should **not** require an account, so needs to work on a cookie basis, although having a user preference setting for logged in users would also be useful.

The language selection dialog should use the name of the language in its own language, ie Deutsch, Ελληνικά, English, Español, Français, so that users can recognize it easily. The default should be set from the browser settings, if available.

The initial set of languages is: Čeština (cs), Deutsch (de), English (en), Español (es), Français (fr), తెలుగు (te). The default for any unsupported language is English.

Language selection widget placement should be someplace prominent in the header or footer, perhaps upper right corner for users not logged in and on the user preference menu for those that are logged in.

**Comment by LeadSongDog** [comment]
@guyjeangilles 
Please tag as "Affects UI"
This is an obvious first step towards #791. Without knowing what language to render, i18n goes nowhere. @justcomplaining is quite right: browser settings are not a substitute for allowing the patron an explicit choice. That is why good multilingual websites put up that selection in a prominent place, either on the menu bar, e.g. 
https://www.europeana.eu/portal/en/TEL.html
or on the splash page, e.g. 
https://www.wikipedia.org/

**Comment by BrittanyBunk** [comment]
since people can create accounts, it would be beneficial for a person to say which language they'd like to see the site in.

**Comment by tfmorris** [comment]
I've added additional detail to the issue to describe what needs to be done.

**Comment by BrittanyBunk** [comment]
@tfmorris where? I would like to read it.

**Comment by justcomplaining** [comment]
@BrittanyBunk He edited my original description.

**Comment by 0dysseas** [comment]
Hello, may I be assigned to this? I've worked on a solution (cookie based) and I'd like to open a PR.

**Comment by khabdrick** [comment]
Hello @mekarpeles is this issue still open
