### ISSUE TITLE
Avoid syntax-sensitive translation strings

### ISSUE THREAD

**Issue by justcomplaining** [internetarchive/openlibrary#2817]
These are strings such as:
"Add another edition of"

A lot of strings use placeholders that allow for restructuring of the sentence, which is great. If the string is intended to preface a text field or dropdown menu, it should not be an unfinished sentence but either a complete question or a netural description of the field to avoid the grammar hassle.

**Comment by tfmorris** [comment]
This is already against the coding/UI guidelines. To make this actionable, please either:
* provide suggestions on how to improve the [style guide](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#internationalization-i18n---for-programmers) & translation guidelines 
* provide a list of places where these guidelines aren't followed (bonus points if this is in the form of a pull request which fixes them)

or both!

**Comment by justcomplaining** [comment]
Thanks a lot for the speedy reply! I will try to look into it soon-ish and collect those that I find.

**Comment by tfmorris** [comment]
Closing as a duplicate since #2998 is a superset of this. I've added the specific phrase from the original issue to the list there.
