### ISSUE TITLE
Supplementing Open Library w/ Reading Age Levels 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2821]
### Question

This is an investigation to see if there are sources (APIs) w/ Reader Age recommendations, e.g.
https://www.commonsensemedia.org/book-reviews

This issue is closed after it's discussed during a community call

**Comment by BrittanyBunk** [comment]
It's pretty beneficial to show the grade levels, so kids can read more at their level. Importing the info from a website like the one you posted would make the process of adding in much easier (as it'd be a lot of work to catch up - if possible - manually).

**Comment by mekarpeles** [comment]
Marking as resolved as @finnless is currently driving some of these changes from https://github.com/Open-Book-Genome-Project/sequencer

https://github.com/Open-Book-Genome-Project/sequencer/issues/1
