### ISSUE TITLE
Show all button

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2823]
For editions, authors, and lists. This would circumvent needing to add in a sort a->z or search bar for searching/browsing through these, as I could just use ctrl+f to find what I need.

**Comment by guyjeangilles** [comment]
Do you mean, for example, showing every single Work in Open Library's database on one page?

**Comment by BrittanyBunk** [comment]
@guyjeangilles no. I mean show all editions on a work's page, all the works on an author/list page too.

**Comment by guyjeangilles** [comment]
I see.

I'll voice my opinion and say that I'm cautious to implement this feature. One of the reasons pages have pagination is to reduce load time. Some Works have hundreds if not thousands of editions and it could cause quite a bit of network strain to load them all onto a page.

**Comment by BrittanyBunk** [comment]
@guyjeangilles I don't believe that's a good reason, as the first mode that's loaded is the show all -> then it transforms into the pagination. So the pagination takes longer for me to load.

**Comment by seabelis** [comment]
I also use CRTL+F at times, but a search/filter within results would be a better solution.

**Comment by BrittanyBunk** [comment]
this got solved, but is still being debated to this day
