### ISSUE TITLE
"Preview Only" Button: Supporting Print-Disabled Previews

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2829]
Open Library's UI should reflect upstream changes affecting preview support for print-disabled material.

### Describe the problem that you'd like solved

Currently, in (1) work search results -- including authors works, (2) works edition tables, (3) lists, and (4) editions pages show "Not in Library" when a book is unavailable or print-disabled. For books which are print-disabled only, the primary call to action should be e.g. "Preview Only" (copy pending).

### Proposal & Constraints

The same `cta-btn` styling should be used as the other "Preview" buttons. The `protected print-disabled` link should still be displayed.

![openlibrary org_search_q=cracking+code mode=everything](https://user-images.githubusercontent.com/978325/71931917-bd86dc00-3153-11ea-9540-dabe0f33288f.png)

https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#cta-btn--preview

![openlibrary org_books_OL18628948M_Cracking_the_communication_code](https://user-images.githubusercontent.com/978325/71932174-338b4300-3154-11ea-8c78-c7f1561316c4.png)

### Additional context

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/LoanStatus.html
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/ReadButton.html
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/AvailabilityButton.html

Out of scope for this issue, but also relevant: AvailabilityButton (used by work search) should be refactored to use LoanStatus (which uses ReadButton).

### Stakeholders

@cdrini, @bfalling

**Comment by BrittanyBunk** [comment]
shouldn't these say 'print disabled preview', as it's not a preview for everyone?

**Comment by mekarpeles** [comment]
@BrittanyBunk it will indeed be a preview for everyone, that's the point of the ticket.
