### ISSUE TITLE
Date field error when using non-numeric characters

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2833]
When using text in the 'When was it published? ' field an error is thrown. /opt/openlibrary/deploys/openlibrary/4ba4afd/openlibrary/templates/type/edition/view.html: error in processing template: ValueError: invalid literal for int() with base 10: ‘20XX’ (falling back to default template) 
This is a new error. I have been able to use text in that field as well as the copyright field in the past.

### Relevant url?
https://openlibrary.org/books/OL27877477M/The_Stock-Broker's_Clerk

### Steps to Reproduce

1. Add an edition using Xs to substitute digits (as if year is unknown)

* Actual: Error thrown as stated above.
* Expected: Record should be saved as usual, without error.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 79.0.3945.88 (Official Build) (64-bit)
- **Operating system?** macOS catalina 10.15.2
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cdrini

**Comment by seabelis** [comment]
Also throws error when using hyphens, https://openlibrary.org/books/OL27233549M/Defensive_Eating_with_Morrissey

**Comment by mekarpeles** [comment]
Finished (in a different repo) -- it's on production!
