### ISSUE TITLE
Books without covers not showing title/author in carousels on 3+ page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2836]
Books which don't have covers should show title/author even if on 3+ page of carousel.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/72107543-8d7c3c00-32ff-11ea-8ebc-a1e2d8a2092b.png)

### Relevant url?
e.g. https://openlibrary.org/publishers/John_Bartholomew_&_Son

### Steps to Reproduce

1. Go to https://openlibrary.org/publishers/John_Bartholomew_&_Son
2. Scroll forward 2 pages

* Actual: Books display empty covers
* Expected: Books to still show the gray "placeholder" cover if missing cover

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF71
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
- Create a `jsdef` block with the template in https://github.com/internetarchive/openlibrary/blob/caff690d44794f93866f9e48dca4f4858da53d13/openlibrary/templates/books/custom_carousel.html and use it in https://github.com/internetarchive/openlibrary/blob/f9ac7d477140988592744bb104cf8a39b179b35c/openlibrary/plugins/openlibrary/js/carousel/Carousel.js

### Related files

- See the files here: https://github.com/internetarchive/openlibrary/pull/2729/files ; but the template rendering the covers when dynamically loaded is likely in the JS
- https://github.com/internetarchive/openlibrary/blob/f9ac7d477140988592744bb104cf8a39b179b35c/openlibrary/plugins/openlibrary/js/carousel/Carousel.js

**Comment by BrittanyBunk** [comment]
@cdrini idk why, but it shows a blank cover instead of no cover at all. If that's removed, then the screen behind it (with the title and author) can show.

**Comment by jdlrobson** [comment]
Still an issue.
The images in question are pointing to URIs such as
//covers.openlibrary.org/b/id/undefined-M.jpg

This is because a cover id is not defined in https://openlibrary.org/publishers/John_Bartholomew_&_Son.json?limit=12&offset=12

Not sure if this is the client side handling or the API itself.

**Comment by jdlrobson** [comment]
this appears to be fixed

<img width="911" alt="Screen Shot 2021-01-07 at 10 15 45 AM" src="https://user-images.githubusercontent.com/148752/103928897-4fac2200-50d1-11eb-9daa-fe120b2211d2.png">

**Comment by BrittanyBunk** [comment]
that is amazing! Not having to deal with those blank covers is a big weight/load off here. Great work everyone.
