### ISSUE TITLE
Banner code should not load JS when no banner (Remove Stripe (stripe.com) tracking)

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2839]
Almost a dozen requests to stripe.com are being made on every page load, even if the page doesn't have any "Buy" buttons. This is both a performance suck and a privacy concern. There should be no reason to contact stripe.com at all for any page that doesn't have a Buy button.

### Evidence / Screenshot (if possible)
![OL-Stripe-Tracking](https://user-images.githubusercontent.com/82178/72111212-1dbe7f00-3308-11ea-8b82-2d792d0141d5.png)

### Relevant url?

https://openlibrary.org/authors/OL3811818A/S._Mukherjee_undifferentiated

### Steps to Reproduce

Load any OpenLibrary web page. Watch the browser status updates as it waits for GET after GET from stripe.com

I expect zero requests to stripe.com unless I'm in the process of buying something.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jdlrobson
@mekarpeles

**Comment by jdlrobson** [comment]
Pretty sure this is the banner code. I complained about this in slack.

**Comment by jdlrobson** [comment]
this is definitely coming from https://archive.org/includes/donate.php (specifically donation-banner.min.js). It also loads another version of jquery. All the JS it loads is **render blocking** (no use of async attribute). We can do better than this!

Can I suggest we update get_donation_include to be configuration based (And disable it now as part of that) so it is not included in the page for every request? This will likely also increase performance for the site by not requiring every openlibrary URI to be routed through archive.org on the server side which I've always thought was a bit strange (we should do this on the client if really necessary and load the banner via JS).

Bumping to urgent as this has been this way for over a month now and the banners are gone. As Tom says this is a privacy and performance concern (a big one IMO).

**Comment by cdrini** [comment]
I've notified the UX team; if a quick-fix isn't possible on their side, I'll disable the banner on prod in our repo for this week's deploy. Note this is loading ~1.7+ MB, 1.2M from/to stripe.com .

It (I think) is the cause of poor load times in our SEO (banner went up ~start of dec)

![image](https://user-images.githubusercontent.com/6251786/72302277-7b6c0780-3637-11ea-9e96-ed352afa3a2d.png)

**Comment by cdrini** [comment]
UX team was aware and is on it! :+1: I've disabled on OL for now until their fix is deployed.

**Comment by jdlrobson** [comment]
Thanks all!!
