### ISSUE TITLE
/search.json doesn't set Content-Type: json

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2846]
/search.json doesn't set content type JSON.

### Steps to Reproduce

1. Open browser console
2. Go to https://openlibrary.org/search.json?q=isbn:9780062935045&mode=everything
3. Check networks tab

* Actual: No `Content-Type` specified
* Expected: `Content-Type: application/json`

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF72
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Related files
Checking https://openlibrary.org/developers/routes , we see it's in:
https://github.com/internetarchive/openlibrary/blob/bc59b7c942c6eef29e76eb82c585c59d1d240d81/openlibrary/plugins/worksearch/code.py#L757

**Comment by nilshah98** [comment]
Hey, I would like to take this issue.

**Comment by cdrini** [comment]
Go for it! Let us know if you have any questions :+1:

**Comment by nilshah98** [comment]
Sure thing, I will get started on it.
Can you maybe assign me and label it as in progress as well?

**Comment by nilshah98** [comment]
Opened a PR resolving the same at - #2861 
Please, review @cdrini
