### ISSUE TITLE
LCCN incorrectly imported when containing alpha characters

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2851]
Significant, non-numeric, characters are being dropped from LCCNs on import from MARC records. This is a long standing bug, so perhaps this is a duplicate report, but I can't find it in the current bug tracker. Perhaps it's in one of the previous trackers and didn't get transferred.

As an example, this MARC 010$a [field](https://openlibrary.org/show-records/OpenLibraries-Trent-MARCs/tier1.mrc:17197530:566)

`010    $aa  47003377`

got imported [here](https://openlibrary.org/books/OL26546996M/Greek_studies?v=1) as `47003377` instead of `a47003377`.

These leading alpha prefixes are significant for LCCNs, so must be preserved. 

Note that https://lccn.loc.gov/a%2047003377 doesn't resolve, so we need to either strip spaces when constructing the URL. 

The full structure of the LCCN is described here: https://www.loc.gov/marc/lccn_structure.html

### Stakeholders
@hornc 

Not a showstopper, but should be fixed before doing any more MARC imports.

**Comment by hornc** [comment]
Thanks for adding this issue @tfmorris -- I wasn't aware of this unfortunately, it shouldn't be broken and I want to fix it ASAP!
