### ISSUE TITLE
Re-enable donation banner import (once stripe import fixed)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2853]
@iisa if you can give us a 👍 update here (once changes are complete on petabox) @cdrini may re-instate on our side.

Here's the issue #2855 causing it to close

**Comment by cdrini** [comment]
I marked myself as a watcher on https://webarchive.jira.com/browse/WEBDEV-3040 , so I'll receive an email once it's fixed and then can be fixed here :+1:

**Comment by cdrini** [comment]
In the PR I put a super obvious notice that it's not working, so less likely to go unnoticed; so dropping to  P2

**Comment by iisa** [comment]
@cdrini, @mek - just released the code on archive.org side.

**Comment by SouthGoingZax** [comment]
Is there anything blocking this at this point?  Is this still a P2?

**Comment by mekarpeles** [comment]
I believe this should be done -- cc: @cdrini
