### ISSUE TITLE
/isbn returns 404 no result, when really API timeout

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2857]
/isbn endpoint often fails to fetch metadata because of a suspected API timeout / rate limit. Instead of showing such an error, a 404 page not found is displayed to the user. The endpoint should fail/respond accurately (both in .json mode, as an API, and to users) 

Similar to 
https://github.com/internetarchive/openlibrary/issues/1807

**Comment by hornc** [comment]
relevant code in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/api.py  and https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py
