### ISSUE TITLE
Canonical link should only include page and sort parameters

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2864]
Google search results include multiple copies of author pages because we're not setting the canonical link correctly. This is probably diluting the authority of the pages and hurting their search results placement.

### Evidence / Screenshot (if possible)

The search results for: https://www.google.com/search?q=%22the+art+of+nonfiction%22+openlibrary
include both: https://webcache.googleusercontent.com/search?q=cache:iydBXvzKMQUJ:https://openlibrary.org/authors/OL59188A/Ayn_Rand+&cd=2&hl=en&ct=clnk&gl=us
and
https://webcache.googleusercontent.com/search?q=cache:7fLLKIz0fpYJ:https://openlibrary.org/authors/OL59188A/Ayn_Rand%3Fsort%3Dnew+&cd=4&hl=en&ct=clnk&gl=us

in the second case the HTML header includes 

`    <link rel="canonical" href="https://openlibrary.org/authors/OL59188A/Ayn_Rand?sort=new" />
`

which should instead be

`    <link rel="canonical" href="https://openlibrary.org/authors/OL59188A/Ayn_Rand" />
`

ie the canonical URL shouldn't include any sort parameters.

### Stakeholders

@jdlrobson @mekarpeles

**Comment by tfmorris** [comment]
The offending code is here: https://github.com/internetarchive/openlibrary/blob/2f1f2806c5bf3c0aeb65753a08614cab9086e874/openlibrary/plugins/upstream/utils.py#L730-L739

There may be some cases where we want to include the query parameters, both `sort=` definitely isn't one of them. I guess we could start by blacklisting it and then add more exceptions as we find them.

**Comment by tfmorris** [comment]
Something I didn't consider when writing this up is pagination of multi-page results. In that case, the `sort` order changes not only the ordering of items on a page, but the contents of the page itself. The [SO answer](https://webmasters.stackexchange.com/a/114624) posted by @flankstaek on #2880 discusses the considerations of significant vs insignificant query parameters.

I'm not sure whether we want to drop the `sort` query parameter only when the results fit on a single page (adding additional complexity) or abandon the idea altogether or ...?

Thoughts?

**Comment by jdlrobson** [comment]
Do we want search results showing up in search results?
I wonder if the canonical URI should be the URI minus the query string.

In fact is there any case where including the query string in the canonical URI makes sense?

**Comment by flankstaek** [comment]
An (attempted) exhaustive list of query parameters include: `results, offset, m, page, type, sort, mode`

I can see how page, results, sort, & offset all change the content of the page and might want to be included in search results. But I also see how it can crowd search results with similar pages, certainly when considering single page results.

I think the decision on whether to remove or retain query strings in canonical URIs comes down to what search results open library intends to provide.

If the goal is to rank higher for a search directed towards an author, e.g. "Ayn Rand" hoping to land on https://openlibrary.org/authors/OL59188A/Ayn_Rand then I think removing the query will help that page rank higher.

If the goal is to rank higher for a search directed towards a specific work, e.g. "Why businessmen need philosophy" hoping to land on https://openlibrary.org/authors/OL59188A/Ayn_Rand?sort=new&page=2 which will include the result, then the query string should be retained.

**Comment by tfmorris** [comment]
> Do we want search results showing up in search results?

No, and we already blacklist /search in robots.txt

> In fact is there any case where including the query string in the canonical URI makes sense?

I think pagination may be one such case, unless we want the search results biased to an author's most popular works (which might be reasonable since works also have their own pages).

We definitely want to exclude `sort, mode, type, v, debug` or we could just whitelist `page` and drop everything else.

@mekarpeles Any opinions?

**Comment by mekarpeles** [comment]
I think mode, type, v, and debug are definite ones to exclude.

I am not sure about sort.

Page makes sense to me though I imagine sort affects page (so perhaps page and sort are two to allow)
