### ISSUE TITLE
Covers in lists with images show up blank

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2875]
example: 
In list:
![image](https://user-images.githubusercontent.com/55302685/72486481-e0526980-37bf-11ea-923d-d052a7e476b4.png)
Edition: https://openlibrary.org/books/OL9462743M/Words_to_Own
Work: https://openlibrary.org/works/OL20410001W/Words_to_Own

This is one of other examples I've seen with this issue.

**Comment by tfmorris** [comment]
The list appears to be here: https://openlibrary.org/people/hawaiisunfun/lists/OL106255L/my_edited_books (please include all relevant details when reporting a problem)

The edition is what was added to the list and it doesn't have a cover on OpenLibrary, which is, I suspect, at least part of the problem. The OL edition page appears to be falling back to a cover from Internet Archive https://archive.org/download/elementsoflitera0000unse_e8b4/page/cover_w180_h360.jpg

**Comment by BrittanyBunk** [comment]
@tfmorris where's that edition?

**Comment by tfmorris** [comment]
It's the same edition you posted the link to.
