### ISSUE TITLE
dependabot -- disable python checking, but re-enable it once we move to Python3 properly

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2878]
dependabot -- disable python checking, but re-enable it once we move to Python3 properly

We know many of our dependencies are painfully out of date, the many PRs opened by dependabot for python muddy the waters, and we want to minimise complexity and risk of breaking behaviour while working towards moving to python3.

I suspect some of these "dependencies" are not used, and we should remove them rather than carry them forward. 

**Note:** Dependabot checking for javascript is fine, those alerts are currently useful,. Do not disable those.

**Comment by cclauss** [comment]
My preference would be that you close individual PRs which will cause dependant to ask you if it should stop notifying you about that dependancy.
