### ISSUE TITLE
Don't use internal action/state names in user interface

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2881]
Our internal action names and state names are always in English, so can't be used directly in the user interface (and such close coupling between implementation and appearance isn't a great idea even in a monolingual system).

There are a few places where this is done, but one that came up in #2442 is:

https://github.com/internetarchive/openlibrary/blob/63d80c064d71de4d7feab7848869ae58ecaafe00/openlibrary/macros/ReadButton.html#L3-L5

I think that loan status may be another area where this is an issue. One red flag to look for is the use of .capitalize() or TitleCase css which is used to convert a lowercase internal name to a more reasonable looking external form. e.g. https://github.com/internetarchive/openlibrary/blob/63d80c064d71de4d7feab7848869ae58ecaafe00/openlibrary/macros/ReadButton.html#L16

### Proposal 

Internal action/state names should be decoupled from the web presentation and should indirect through a lookup table with the natural language forms in it. This lookup table can then be internationalized.

### Stakeholders

@mekarpeles @jdlrobson

**Comment by mekarpeles** [comment]
These are now internationalized as of https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/ReadButton.html
