### ISSUE TITLE
Remove Iptools and GeoIP dependencies

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2896]
These dependencies appear to only be used by the deprecated `Libraries` class and endpoint.

Rather than concern ourselves about modern version numbers and compatibility of modules we are not using, let's remove them and their references.

relates to #1694 
should replace #2893
and #2866

**Comment by hornc** [comment]
@mekarpeles are you able to confirm whether this method for getting loan stats is fully deprecated?

https://github.com/internetarchive/openlibrary/blob/457e6d6cbd12d79d1b1ac1fad16d2dea0a857190/openlibrary/plugins/books/readlinks.py#L114-L141

I beleive the current used method which uses the latest API (not fake subjects) is here:
https://github.com/internetarchive/openlibrary/blob/836044c3db8d590cd569ee31529f171e2eb86758/openlibrary/core/ia.py#L123-L127

**Comment by tfmorris** [comment]
I think @hornc said he was going to do this (any progress on this blocker?) so it should probably be assigned to him, not @cclauss.

**Comment by hornc** [comment]
#2944 should remove iptool rather than update it.

**Comment by hornc** [comment]
If someone wants to help with removing these modules please feel free to begin.

**Comment by cclauss** [comment]
#2953 demonstrates that I will not be able to resolve this one.  I still think that #2866 is a safe way for us to remove the roadblock.
