### ISSUE TITLE
"add-cover" edits in Recent Changes table should display Cover as comment (for review)

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#29]
It would be very useful to review new covers uploaded to watch for spam.

So, in entries where add-cover is used, like all these - http://openlibrary.org/recentchanges/add-cover - let's start displaying the actual cover as the comment.

**Comment by kryptc** [comment]
Hi, can I work on this issue?

**Comment by mekarpeles** [comment]
Sure! We'd love that @kryptc!

**Comment by kryptc** [comment]
Sorry for the delay, I was having some trouble installing docker on my system

**Comment by kryptc** [comment]
Hi, I had a question regarding where the file corresponding to the add-cover section is. In the recentchanges directory in templates, there is no add-cover directory. Where do I make the changes?

**Comment by rohitjain00** [comment]
@kryptc I think you need to ask these kind of questions on Slack or Gitter. There you will find the help you needed.

**Comment by mekarpeles** [comment]
@kryptc can we send you an invitation to our slack channel?

**Comment by f20190104** [comment]
Hey, Can I work on this issue?
