### ISSUE TITLE
Upgrade required of Amazon Affiliate Product API

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2908]
We would like to inform you that all of your applications making calls to Amazon’s Product Advertising API version 4.0 (PA API 4.0) will need to upgrade to Amazon’s Product Advertising API version 5.0 (PA API 5.0) by March 9, 2020.

PA API 5.0 is a more simple, granular, and consistent API that enables you to quickly and easily link your content to Amazon.

Key Features & Changes
* Access information about the latest offers and products in the entire Amazon product database/catalog, such as Prime discounts, multi-currency formats, and shipping eligibility
* Newer, improved ways to get the most relevant and up to date product information
* Rapid integration and easier development with lower engineering cost through use of popular tools and languages | Key Features & Changes
* Access information about the latest offers and products in the entire Amazon product database/catalog, such as Prime discounts, multi-currency formats, and shipping eligibility
* Newer, improved ways to get the most relevant and up to date product information
* Rapid integration and easier development with lower engineering cost through use of popular tools and languages

You may continue to use both PA API 4.0 and PA API 5.0 without disruption through March 9, 2020. After that date, we will shut down PA API 4.0, and any application calling it will no longer be able to retrieve Amazon product information. | You may continue to use both PA API 4.0 and PA API 5.0 without disruption through March 9, 2020. After that date, we will shut down PA API 4.0, and any application calling it will no longer be able to retrieve Amazon product information.

**Comment by tfmorris** [comment]
An upgrade window of less than two months? That's pretty obnoxious of Amazon.

The upgrade guide is here: https://webservices.amazon.com/paapi5/documentation/migration-guide/pa-api-40-to-50-mapping.html

**Comment by hornc** [comment]
I wonder how much this will affect #2857 and #2444 which I was planning to work on soon (in the proposed next sprint milestone).

**Comment by cdrini** [comment]
Our amazon python library has an issue for this, but it doesn't look like it's had a ton of progress https://github.com/yoavaviram/python-amazon-simple-product-api/issues/162

**Comment by cdrini** [comment]
Here's another migration-y guide: https://webservices.amazon.com/paapi5/documentation/migration-guide.html?ref_=pe_3519780_470445350

**Comment by mekarpeles** [comment]
@mekarpeles responsible for issuing new keys in Feb

**Comment by mekarpeles** [comment]
https://affiliate-program.amazon.com/assoc_credentials/home button necessary for migrating from AWS to Product API

**Comment by mekarpeles** [comment]
Breaking protocol and assigning 2 assignees to this issue (since some of the efforts require server-side changes and regen of keys). @hornc, I noticed you are assigned via @cdrini -- was this for migrating the actual python library / doing the 4.0 -> 5.0 migration part? If so, happy to tag team.

**Comment by mekarpeles** [comment]
NB: @hornc, @cdrini 
https://github.com/internetarchive/olsystem/pull/78#issuecomment-584905439

Keys are migrated and tested, next step is key merge + deploy

**Comment by mekarpeles** [comment]
Keys merged and deployed. Ready for code migration

**Comment by cdrini** [comment]
@mekarpeles : It might be worth trying to for the python library to use 5.0 on dev to see what breaks?
@hornc : Could fork, fix the bits, and PR back into core repo
- Where are we using this API, since we're getting prices from BWB
@mekarpeles : Amazon import API and still being used for prices for amazon prices
@hornc : Should we not bother with updating and just use BWB?
@mekarpeles : We still need Amazon API for importing ISBN; sponsorship program (title, page count price)

Decision: Keep amazon calls for now; too many changes to do to remove

**Comment by cdrini** [comment]
From https://github.com/yoavaviram/python-amazon-simple-product-api/issues/162#issuecomment-585125300, here's a possible alternate library that works with PAAPI 5: https://pypi.org/project/python-amazon-paapi5/

**Comment by tfmorris** [comment]
I'm guessing this got closed by accident since the work is incomplete, untested, and not yet deployed.

**Comment by mekarpeles** [comment]
@tfmorris this code had been tested and deployed (as of Friday). If there are followup tasks, let's make sure to create issues for them.

**Comment by tfmorris** [comment]
@mekarpeles I assume you will (or already have) create any necessary issues for the followup to finish this task (e.g. getting import working, fixing exception handling, etc). It would be good to reference them to this issue so that people can find them easily.
