### ISSUE TITLE
Enable searching for a classification on prod

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#2913]
Works on similar subjects normally are in similar-valued lc_classifications and/or dewey_decimal_class. It should be possible for clients to search on these fields to find such works.

### Describe the problem that you'd like solved

1. Ensure the above-mentioned classifications are put in the SOLR index, not just the edition json
2. Add "Classification" to the list of fields for Advanced search at https://openlibrary.org/advancedsearch 
3. Amend the search query to support such search.
4. Result should be a list of the matching works, not specific editions.

### Proposal & Constraints

Nearly every major online catalogue is searchable by classification: LC, BnF, BL, etc.

1. Although an easy-to-use "search nearby" link would be great to have, it is a next-stage feature. Let's walk before running.
2. If client searches for QA135 they will expect to see a superset of the results found for QA135.5

### Additional context

Doing this should help facilitate finding mergeable works, translations, etc. by the same author.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I think this probably should be closed, as I already created that claim here: #2673. It'll be nice to write it there (unless this is different).

**Comment by cdrini** [comment]
@LeadSongDog  I'm going to leave this open as it's still stuck in dev.openlibrary.org, but searching by classifications works on dev.openlibrary.org (e.g. `lcc:QA135*`, `lcc:[PT5001 TO PT5980]`, or `ddc:6*`)

Here are some demos:

- Library of Congress: https://dev.openlibrary.org/people/ScarTissue/lcc-list
- Dewey Decimal: https://dev.openlibrary.org/people/ScarTissue/ddc-list


@BrittanyBunk #2673 seems to depend on this issue, so I think they can co-exist.

**Comment by cdrini** [comment]
Blocked by #3435

**Comment by cdrini** [comment]
This was completed! You can now search for classifications on prod: https://openlibrary.org/search/howto#classifications

**Comment by BrittanyBunk** [comment]
thanks!
