### ISSUE TITLE
Import LC classification from MARC record if existing edition found

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2916]
Currently when we import a book from archive.org MARC records, if an existing match is found, the LC classifications (MARC `050`) are not added to the OL record.

**Comment by cclauss** [comment]
While you are looking at this can you please explain the source of the `marc` dict in these locations?
```
./openlibrary/catalog/works/by_author.py:81:24: F821 undefined name 'marc'
    if e['key'] not in marc:
                       ^
./openlibrary/catalog/works/by_author.py:85:12: F821 undefined name 'marc'
    data = marc[e['key']][1]
           ^
./openlibrary/catalog/people/build_object.py:49:29: F821 undefined name 'marc'
    p = build_person_object(marc, [])
                            ^
./openlibrary/catalog/people/build_object.py:53:29: F821 undefined name 'marc'
    p = build_person_object(marc, [])
                            ^
```

**Comment by hornc** [comment]
@cclauss I have just review the code re. you comment above, the `marc` dict appeared in old and unsued code (part of an early standalone script?), it will have never been run in the context of the Open Library application. That code has since been removed to https://github.com/internetarchive/openlibrary-bots/pull/37
