### ISSUE TITLE
Subject pages with slashes are not linked correctly from search results page

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2932]
Searching subjects search result page gives non functioning links to subjects with slashes in them:

e.g. JUVENILE FICTION / Comics & Graphic Novels / General   16 books, subject 

apparently has 16 books, but I can't access the subject URL to find out what they are.

### Relevant url?

https://openlibrary.org/search/subjects?q=general+fiction&mode=everything

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by LeadSongDog** [comment]
@cdrini Another dupe. Issue #333 covers the same thing in both subject and publisher.
Other dupes at #569, #2202 too.

**Comment by tfmorris** [comment]
And #727.

@hornc your 27 works (not 16 because subject indexing is still broken) are here: https://openlibrary.org/subjects/juvenile_fiction__comics__graphic_novels__general
