### ISSUE TITLE
Add account registration graphite stats

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2940]
We have xauth (linking OL/IA) stats but we're currently missing basic stats about account creation (at the highest level) e.g. in openlibrary/accounts/model.py

### Evidence / Screenshot (if possible)
N/A
### Relevant url?

https://openlibrary.org/account/create

### Related files

openlibrary/accounts/model.py see `stats` call for `xauth` linking

### Stakeholders

@cdrini

**Comment by imskr** [comment]
Is this open to work? @mekarpeles

**Comment by mekarpeles** [comment]
Given we do have xauthn graphite stats, tempted to close; 
@cdrini?

**Comment by MayankVir** [comment]
Is this issue open to work now?

**Comment by mekarpeles** [comment]
Closing as we do have # linked accounts + account creation info in stats
