### ISSUE TITLE
Sort lists dropdown in a useful way

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2943]
When adding an item to a list, the lists are displayed in order of creation. For users with a large number of lists, this becomes difficult to manage.

### Describe the problem that you'd like solved
Lists should be sorted either by most recently used at the top or in alpha order so that it is easy to locate on the dropdown.

**Comment by tfmorris** [comment]
The current order is effectively random (internal hash order) which is clearly not useful at all. I see a few different possibilities for improving this:

1. Most recently used, or
1. Alphabetical, or
1. Alphabetical with cursor on the most recently modified list
1.  Some hybrid that does first N (1? 3?) most recent, followed by alpha, or alpha if list is greater than a certain size, or ...

We've got a PR (#3310) for the pure mostly recently used implementation, but I'm concerned that it'll have usability issues when there is a large number of lists. Apologies for not hashing out the implementation details in advance of the coding!

**Comment by tfmorris** [comment]
Apparently @seabelis provided feedback on chat, not here, but I think she agreed the MRU was going to be almost as bad for large lists. My personal preference order is 3, 4, 2, 1. The solution in #3310 is only marginally better than random.
