### ISSUE TITLE
Replace discontinued LEPL module

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2945]
This parser has been discontinued since 2012 and from the deprecation warnings that Python 3.8 is spitting out, it's going to stop working with Python 3.9.

http://www.acooke.org/lepl/discontinued.html
https://pypi.org/project/LEPL/

It looks like it's only used to parse email addresses, so it should be easy to get rid of:

```
$ find . -name '*.py' -exec grep lepl {} \; -print
import lepl.apps.rfc3696
    return lepl.apps.rfc3696.Email()(email)
./openlibrary/accounts/model.py
```
The [validate_email](https://pypi.org/project/validate_email/) module looks like a good replacement candidate.

**Comment by nilshah98** [comment]
Hey, is this issue up for grabs?

**Comment by tfmorris** [comment]
@nilshah98 If you look just above, you'll see a linked PR that fixes this.

**Comment by nilshah98** [comment]
My bad, should have looked at it harder.
Thanks!
