### ISSUE TITLE
Not all lists displayed on add-to-list widget

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2954]
If a user has a lot of lists (not sure how many) not all lists are displayed. So one can make new lists, but cannot add anything to the lists from the widget.

### Steps to Reproduce

1. Go to any page that allows one to add item to list
2. Do ... keep making new lists. Eventually you will no longer see them on the dropdown even though they are created successfully.

* Actual: Only the initial seed can be added to the list because the list does not appear on dropdown.
* Expected: The list will be available on the dropdown.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 79.0.3945.88 (Official Build) (64-bit)
- **Operating system?** macOS Catalina 10.15.2
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by Evazisouli** [comment]
Hello! I have already made 21 lists myself but I cannot see the problem mentioned.

**Comment by seabelis** [comment]
I'll close this. I think it may have been solved with . #3310
