### ISSUE TITLE
Recent UserDict.DictMixin with Mapping change has broken editions page

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2957]
Recent PR #2935 is causing errors on the edition page.

`/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: TypeError: Can't instantiate abstract class MultiDict with abstract methods __iter__, __len__ (falling back to default template)`

@tfmorris This looks familiar from the change that was made to Infogami -- I thought we had a solution to this problem. Can you remember the details?

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/905545/73630014-bd79ed80-46b9-11ea-9ca2-0abd10e40d27.png)

### Relevant url?

http://localhost:8080/books/OL24197475M/The_complete_works_of_Mark_Twain.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@tfmorris @cclauss @hornc

**Comment by cdrini** [comment]
Bumping to P0 since it's blocking deploy
