### ISSUE TITLE
Homepage broken when setting ?lang url parameter

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2959]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/73680071-9e636780-4689-11ea-9208-0fb130292495.png)
![image](https://user-images.githubusercontent.com/6251786/73680199-da96c800-4689-11ea-8e89-3d826a5a46cc.png)

### Steps to Reproduce
1. Go to https://openlibrary.org/?lang=fr (or https://openlibrary.org/?lang=fr&debug=true for debug info)

```
<type 'exceptions.KeyError'> at /
'hit'
```

https://github.com/internetarchive/openlibrary/blob/673f7d0e00c4ea1782ca88bed03f73d47bf4d459/openlibrary/plugins/openlibrary/stats.py#L74

Variable | Value
-- | --
memcache_hits | 2
memcache_misses | 0
s | <Storage {'data': {'key': u'home.homepage.fr-'}, 'name': 'memcache.get', 't_start': 1580754796.506607, 'time': 0.0}>
stats_summary | <Storage {'total':  <Storage {'count': 0, 'unaccounted': 0.32955098152160645, 'time':  0.3402059078216553}>, 'memcache.get': <Storage {'count': 3,  'time': 0.00292205810546875}>, 'infobase': <Storage {'count': 1,  'time': 0.007732868194580078}>}>

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF72
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles @tfmorris

**Comment by cdrini** [comment]
My guess is this is something weird with memcache, since it works fine on dev. Restarting memcache might help.

**Comment by cdrini** [comment]
Restarted all three memcaches (3-5)

```sh
ssh -A ol-mem3
sudo service memcached restart
```

**Comment by cdrini** [comment]
No change

**Comment by cdrini** [comment]
Related to #2895

**Comment by cdrini** [comment]
Locally, here's what `s` should look like:

```json
{
    "t_end": 1580834758.574496,
    "data": {
        "hit": true,
        "key": "home.homepage.en-"},
        "name": "memcache.get",
        "t_start": 1580834758.573718,
        "time": 0.0007779598236083984
    }
}

**Comment by cdrini** [comment]
It looks like the source is missing the `head`???? view-source:https://openlibrary.org/?lang=fr

**Comment by cdrini** [comment]
And it looks like this _is_ in memcache: 

```py
>>> import memcache
>>> mc = memcache.Client(['ol-mem%d:11211' % i for i in range(3,6)])
>>> mc.get('home.homepage.fr-')
>>> mc.get('home.homepage.fr-')[:300]
'[{"__body__":"\\n\\n<div id=\\"contentBody\\">\\n  \\n<div class=\\"carousel-section\\">\\n  <div class=\\"carousel-section-header\\">\\n    <h2 class=\\"home-h2\\"><a href=\\"/subjects\\">Browse by Subject</a></h2>\\n  </div>\\n  <hr>\\n  <div class=\\"carousel-container\\">\\n    <div class=\\"carousel carousel--progres'
```

**Comment by cdrini** [comment]
Wait, https://openlibrary.org/?lang=en Also errors; is this some issue with the `?lang` parameter?!?

**Comment by cdrini** [comment]
Going to try setting my browser's `Accept-Language` to sim a real non-en user (via https://github.com/sorz/accept-language-per-site )

**Comment by cdrini** [comment]
Aaaaand it works -\_- Dropping this in priority

**Comment by tfmorris** [comment]
I can't tell if this is still a problem or not. It sounds like it's fixed, but the issue is still open.

**Comment by cdrini** [comment]
It's still a problem, but it's not as serious a problem as it was originally, since it only affects developers (who are using the ?lang= url param).

**Comment by tfmorris** [comment]
I haven't investigated fully, but I suspect the import changes from f2554143.

We have the following identically named stats modules:

```
./openlibrary/core/stats.py
./openlibrary/plugins/openlibrary/stats.py
./openlibrary/admin/stats.py
./vendor/infogami/infogami/utils/stats.py
```
Seems like importing the wrong one could have an effect like this.

Do we have stats disabled on `dev`, causing this to be untested?

**Comment by tfmorris** [comment]
This works locally, so someone who has access to both needs to debug the config differences between `dev` and `prod`.  It looks like perhaps `stats.end()` isn't getting called, since that sets both the `end_time` and the `hit` boolean. Possibly `memcache.get()` is throwing an exception that isn't caught.

Some things to check:
- [ ] stats enabled on dev? (`true` for Docker, but see below)
- [ ] "stats_server" running on dev? (configured as `localhost:9090` for Docker, but nothing running there)
- [ ] version of `python-memcached` on prod & dev (1.59 in Docker)
- [ ] version of `memcached` on prod & dev (1.5.21 in Docker)

 There's a `try/except` block further up which is designed to keep stats failures from preventing pages rendering. Perhaps it'd be a good idea to cover this case too (after we get root cause on the failure)

**Comment by Yashs911** [comment]
@cdrini, I think we can close this issue. Any idea why category title and book to sponsor are not translated?
![tempsnip](https://user-images.githubusercontent.com/64412143/104618651-fcc70180-56b2-11eb-878a-bbf856d83f8a.png)

**Comment by cdrini** [comment]
Oh wonderful! I wonder if it got fixed with the python 3 migration.

Books to Sponsor looks like it might just be missing? Although our i18n flow right now is a bit confusing; I'm not entirely sure how to generate up-to-date .po files without introducing issues :/

Can't recall why the subject names are not being translated, but I think there was a reason :P Investigating the code my reveal why.
