### ISSUE TITLE
Expose bookshelves as JSON API

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2963]
We need to be able to get how many bookshelves an item is on from the JS UI in order to be able to prevent merges for those items

### Summary of Requirements
- [ ] Publicly accessible endpoint `/works/OL1W/-/bookshelves.json` that returns count of books
- [ ] Response schema: `{ "counts": { [shelf_name]: number } }`

### Relationships
- Part of #805

**Comment by tfmorris** [comment]
Is a bookshelf the same as a List?

This feels like it might fit better as query/search on the List/bookshelf endpoint, not the works endpoint.

**Comment by cdrini** [comment]
Bookshelves are reading logs; the biggest difference is that they can be private, so we can't return a list of bookshelves, only aggregate info. Note there is a /works/OL1W/-/lists endpoint : https://openlibrary.org/works/OL19710804W/Less/lists
