### ISSUE TITLE
Docker Desktop 2.2.0.0 Prevents Running Tests and Starting Services

### ISSUE THREAD

**Issue by user404d** [internetarchive/openlibrary#2970]
When using Docker Desktop 2.2.0.0 on Windows 10 Build 1903 and WSL (Debian) the project failed to run properly locally when using `docker-compose` and its configuration in `docker-compose.yml`. There were many different problems which all seem to be related to regressions in Docker Desktop introduced in 2.2.0.0 (see docker/for-win#5530, docker/for-win#5540).

### Relevant url?

docker/for-win#5530
docker/for-win#5540

### Steps to Reproduce

1. Install Docker Desktop 2.2.0.0 on Windows 10
2. initialize the project by cloning from WSL (to get the correct line endings and correct symlinks)
3. follow `docker/README.md` to build images
4. `docker-compose up` or `docker-compose run --rm web make test` (both fail)
    - `docker-compose up` usually failed to import the infogami module through the infogami symlink
    - `docker-compose run --rm web make test` would fail because the `node_modules` directory would become empty as an empty `node_modules` directory would appear on the host then get mounted into the container (at least this is what appeared to be happening, see the docker/for-win issues above)

* Actual: Failed to start the `web` service or run tests in the `web` service
* Expected: Start the `web` service or run tests successfully in the `web` service

### Details

- **Operating system?** Windows 10 N Build 1903
- **Environment (prod/dev/local)?** local
- **Docker Version** Docker Desktop 2.2.0.0

### Proposal & Constraints

I took the advice in the linked docker/for-win issues given by other users who recommended to downgrade Docker Desktop to version 2.1.0.5

**Comment by user404d** [comment]
I'm making this mostly to document for others to see. I don't think there is much to be done as far as this project is concerned.

**Comment by guyjeangilles** [comment]
@user404d Since this isn't actionable as is, can you make a pull request updating the [Docker instructions](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md) with the information in the issue description so we can close out this issue

**Comment by cclauss** [comment]
@user404d Can this issue be closed?  The underlying issues were closed and Docker Desktop is now on [v3.2.1](https://docs.docker.com/docker-for-windows/release-notes).

**Comment by user404d** [comment]
Yes it can be closed.
