### ISSUE TITLE
Read & Return Ebook buttons colliding

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2972]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/978325/73778176-9bc34980-473f-11ea-9da6-796f250d3d2e.png)

### Relevant url?

1. Search results
2. Work's editions table
3. Editions page (esp. on mobile)

**Comment by aashimgarg** [comment]
Hey @mekarpeles i want to work on this issue!

**Comment by aashimgarg** [comment]
@mekarpeles any url?

**Comment by aashimgarg** [comment]
@mekarpeles ?

**Comment by mekarpeles** [comment]
I believe this occurs in `macros/LoanStatus.html` or `macros.ReadButton` and then `openlibrary/static/css/components` -- possibly `buttonCta.less`?

**Comment by mekarpeles** [comment]
The way I would solve this issue (since the local environments do not support "borrowing") is to go on dev.openlibrary.org, find a book/edition like https://openlibrary.org/books/OL23292543M/The_giver, borrow the book, and then look at the buttons on that page (desktop and mobile). The mobile especially should appear to overlap.

Also, if you go to the `work` for this page, https://openlibrary.org/books/OL23292543M/The_giver, you should see the editions table behave like the screenshot above.

**Comment by cdrini** [comment]
In general, you can usually find the right html file by searching the code base for a unique looking string; in this example "Return eBook" might be good. In VSCode or Pycharm, `ctrl-shift-f` will let you search the entire codebase.

Once you have the right file(s), just edit the file so that it always displays the return button. Then you can easily view it locally as you try to fix it 👍

**Comment by mekarpeles** [comment]
@aj-kamal can we assign you to this issue?

**Comment by Aj-KamaL** [comment]
Yes, sure. 
Do let me know if #3187  resolves the issue or not.

**Comment by Aj-KamaL** [comment]
> @Aj-KamaL can we assign you to this issue?
Yes, sure.
Do let me know if #3187 resolves the issue or not.
