### ISSUE TITLE
Lack of public folder directory.

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2977]
Don't know where all the files are - because they're located in multiple places

### Describe the problem that you'd like solved
Public files are in multiple locations and it would be beneficial to keep them in one place for the public to easily view and access.

### Proposal & Constraints
_Proposal:_ Collect the locations of all the files and put the links in one place, along with the 'loose' documents (like on Google) in folders and add to some 'get started' or 'about site' or 'for developers' webpage on the OL.
_Suggested location:_ https://openlibrary.org/developers/api where it says "Our API should not be used for bulk download of Open Library data. If you want a dump of complete data, please read about your Bulk Download options, or email us at info@."
_Folder examples:_ 1) main, 2) librarian, 3) coding
_Constraints:_ 1) people may still not find it, 2) it's not helpful, not enough people use/need it (that's a worry of any issue though - and a lot of people would be able to use it) or get confused when looking at

### Additional context
Links to mention:
http://archive.org/details/ol_data
https://github.com/internetarchive/openlibrary
https://openlibrary.org/developers/dumps
Personally collected files on Google that'll be beneficial to copy to the main folder of the OL: https://drive.google.com/drive/folders/1m3Kp9W9p5jNbGaGJjvIsHyHYfv9yA-53?usp=sharing

### Stakeholders
Newcomers - mainly developers to catch up on where the OL is at right now to continue to help it along.
Me - it helps me direct people to where they need to go. It also helps me personally in getting to where I need to go.

**Comment by imskr** [comment]
I would like to work on this issue @BrittanyBunk @mekarpeles

**Comment by BrittanyBunk** [comment]
@imskr if you need my help with that, let me know

**Comment by mekarpeles** [comment]
If there are documentation changes, we should try to start with small actionable changes per team lead. In the last year a lot of our FAQs and documentation have been improved both for engineering and also by the librarian teams. Closing until there's a specific reason to re-open.

**Comment by BrittanyBunk** [comment]
@mekarpeles if the documentation has been improved, where is it then?

**Comment by BrittanyBunk** [comment]
@mekarpeles I think this should be reopened. The issue is there's no location for all the documents of the Open Library - it's extremely hard to keep up with changes - you have documents in the github wiki, code section, google drive, data dump on the OL website, etc. - there's no centralized position. I'm not sure what 'small actionable changes' means - this is just that - you just make a page with links to everything available - and separate by category what is private and what's public. I mean, there was someone who wanted to work on it.

I think it'll be extremely helpful! At least to me! To both reopen this issue and to also make this fixed.

I think it'll help to have a centralized place, as then volunteers can add their work there too! Then everyone can look at everyone's stuff. Then the links to places like https://colab.research.google.com/drive/1j1PJ-e761JGH1d4CYCcnT0RkvVVhI57p#scrollTo=31j7E8tKeaDU would be there too! Please!
