### ISSUE TITLE
Random book button goes to homepage when clicked from work page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2983]
### Steps to Reproduce
1. Go to a works page; e.g. https://openlibrary.org/works/OL5848307W/Walt_Disney's_Mother_Goose
2. Click "More > Random Book"

* Actual: Goes to homepage
* Expected: Goes to a random book

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF72
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
I cannot duplicate this bug. I'm on Ubuntu 16.04 FF 72.0.2 (64-bit). I specifically was redirected to https://openlibrary.org/books/OL9817158M/The_Pullman_Strike_of_1894.

Can someone else try to duplicate this?

**Comment by cdrini** [comment]
Hmmm, I can't repro this anymore either :P Not sure what changed :/ Closing as not an issue for now.
