### ISSUE TITLE
Editions missing from sitemap

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2987]
The current sitemap appears to only index works and authors which may cause editions to get missed unless they're organically crawled from the works page (and they have a corresponding work).

### Relevant url?

https://openlibrary.org/static/sitemaps/siteindex.xml.gz

### Proposal & Constraints

Editions should be included in the sitemap to highlight their visibility and insure that they aren't skipped, particularly since we're moving to edition pages as the primary.

### Stakeholders
@mekarpeles @hornc

**Comment by hornc** [comment]
I agree. From specifying out what is required for import criteria the threshold data for a "book" is at the edition level, i.e. it must have a publisher and data. We do not import 'works'.

I'm in the process of writing up my import guidelines, but I'm taking Open Library's "One page for every book" to mean one page for every _edition_ in our model. The fact we do not index editions in Solr for search, nor list them in the sitemap, given that they are the main record we care about, is a big issue we should address. 


To define an OL edition: it is closest to the FRBR concept of _manifestation_, which is the class of physical things (in book form) with the same characteristics. Editions are physical, Works are not.

**Comment by LeadSongDog** [comment]
@hornc We should clearly explicate that multiple electronic images of the same block of words are _NOT_ distinct OL editions, though in FRBR-speak they are distinct manifestations.

**Comment by mekarpeles** [comment]
On `ol-home` sitemaps are being rsync'd to `/1/var/lib/openlibrary/sitemaps/` on `ol-www1` by our cron:

```0 20 1 * * openlibrary /olsystem/bin/verify-node.sh ol-www1 && mkdir -p /1/var/lib/openlibrary/sitemaps && rsync -av --delete rsync://ol-home/var_1/tmp/sitemaps/sitemaps /1/var/lib/openlibrary/sitemaps/```

We confirmed that on the 1st of February `sitemap_works_*` were being created in 
`ol-www1:/1/var/lib/openlibrary/sitemaps/sitemaps$`

**Comment by mekarpeles** [comment]
Google Search Console reports that `https://openlibrary.org/static/sitemaps/siteindex.xml.gz` was indexed on Feb 24, 2020 with 26,139,082 urls discovered on Feb 18, 2020 (Success)
