### ISSUE TITLE
Showing the dropdown menu when the cursor is not over the respective option when the screen is minimized

### ISSUE THREAD

**Issue by aashimgarg** [internetarchive/openlibrary#2995]
When the size of the window screen is minimized the books and browser options shows the dropdown menu even the cursor is not on these options!

the window screen should be less than 935px approx.

Relevant URL:-
https://openlibrary.org/

**Comment by guyjeangilles** [comment]
@aashimgarg Can you post a screenshot, your OS, and web browser you're using? I cannot duplicate this bug on Ubuntu 16.04, FF 72.

![2995_ol](https://user-images.githubusercontent.com/7256157/74281063-a8363c00-4d15-11ea-93ef-c31018c28c87.png)

**Comment by nynaalekhya** [comment]
@jdlrobson Hi, I could not replicate this bug.

**Comment by jdlrobson** [comment]
I also cannot replicate. This is working fine for me. Thanks for the ping @nynaalekhya.

Closing as invalid. Happy to reopen if futher information can be provided that includes replication steps and screenshots.
