### ISSUE TITLE
Clean up first pass internationalization

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2998]
Part of #791, followon to #2442

Now that we've done an initial pass of internationalization, we should review the results and clean up as much as possible before asking translators to invest in translations which will need to be revised.

Some specific issues to find/fix include

- [ ] Remove as much HTML markup as possible, especially things which are easy for a translator to mess up such as `href`s, Javascript, etc. We currently have over 100 instances as measured by `$ grep '<' openlibrary/i18n/messages.pot | wc -l`. Limited use of style markup e.g. `<b><i>` is ok if it's difficult to remove while retaining the entire phrase/sentence for translation context.
- [ ] Remove/revise any obviously bad copy/references, such as references to `/subjects/lending_library`
> "Browse all the available books through the <a "
> "href=\"/subjects/lending_library\">\"Lending Library\"</a> subject, or "
> "try a <a href=\"/search?subject_facet=Lending%20library\">search</a>."
- [ ] Revise informal/folksy phrasing which is difficult to translate (and not that great to start with) e.g. "A short bio?", "Huh?"
- [ ] Fix incomplete sentences/phrases which are an indication that text concatenation is being done in the code or implicitly via layout e.g. "who have written the most books on this subject", "Add another edition of", or "Sorting by". These should be complete sentences, with embedded replacement variables, if necessary, to be translatable.
- [ ] Collect feedback from early translators like @dcapillae for other things which are awkward or need fixing.
- [x] Add names to all substitution parameters to help provide context for translators. (41 instances from ` grep -E '%[sd]' openlibrary/i18n/messages.pot | wc -l`)
- [ ] Punctuation separate from text e.g. `<a href="link">$_("This")</a>?` (39 instances of ?! and 146 instances from `find openlibrary -name '*.html' -exec grep -E '>[\.?!]' {} \; -print | wc -l`)

### Related files
openlibrary/ii18n/messages.pot

### Stakeholders
@cdrini @dcapillae @elizaLU

**Comment by dcapillae** [comment]
Thank you, @tfmorris. I'll try to contribute in any way I can. My lack of knowledge and experience does not allow me to contribute as much as I'd like.

I found some strange strings while updating the Spanish translation. I got an error in the poedit editor at [this string](https://github.com/dcapillae/openlibrary/blob/master/openlibrary/i18n/messages.pot#L2519). 

[Line 2519]
> #: header.html:59
> #, python-format
> msgid "This subject is on <strong>1 list</strong>."
> msgid_plural "This subject is on <strong>%s lists</strong>."

Should it be `This subject is on <strong>%(count)s lists</strong>`?

I also found [a link](https://github.com/dcapillae/openlibrary/blob/master/openlibrary/i18n/messages.pot#L2546) without `</a>`. Is this right?

[Line 2546]
> #: home.html:20
> msgid ""
> "For the top 2000+ most requested eBooks in California for the print "
> "disabled <a href=\"../people/sionnac/lists/OL25152L\">click here"

**Comment by tfmorris** [comment]
@dcapillae Thanks for pointing out the two problems. For the first, yes, you need the parameter name, ie `%(count)s`. For the second, I think it worked the way it was, but it was confusing, so I fixed it. Thanks for pointing it out.
