### ISSUE TITLE
catalog/onix/onix.py doesn't handle books with multiple title tags

### ISSUE THREAD

**Issue by bowlofeggs** [internetarchive/openlibrary#3]
I've got a book in an ONIX record that has more than one <title> tag. When this happens, onix.py raises an Exception:

File "<snip>/openlibrary/catalog/onix/onix.py", line 62, in **getitem**
    raise Exception ("more than one value for %s (%s)" % (reference_name, name))
Exception: more than one value for Title (title)

It is valid according to the ONIX docs for there to exist more than one <title> tag. This often happens when a book is bilingual.

**Comment by salman-bhai** [comment]
@mekarpeles I think we should close this!
