### ISSUE TITLE
Add stricter Travis tests only on a PR's modified files

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3011]
I am always frustrated when I see pull requests that modify files that contain:
1. ~Python 3 syntax errors~  Fixed in #3030 
2. ~undefined names~
3. unused imports
4. unsorted imports

### Describe the problem that you'd like solved

If a pull request modifies files then we should try to fix as many issues as we can.

### Proposal & Constraints

Add a new Travis CI test run on Python 3.8 that does the following:
1. `git diff origin/master --name-only`  # provides the file paths of only the modified files
2. `flake8 ${modified_files} --select=E9,F63,F7,F82 --show-source --statistics`
3. `isort --check-only ${modified_files}`

These checks are stricter than `make lint` for the modified files to catch Python 3 syntax errors, Python 3 undefined names (long, unicode, xrange, etc.), unused imports, unsorted imports.

### Stakeholders

@hornc @tfmorris @cdrini @mekarpeles

**Comment by cdrini** [comment]
I think it would be a mistake to have Travis fail a PR because it edits a file which has possibly unrelated problems. When doing a code review, it's generally considered bad practice to ask some to "fix _ while you're here"; it's better to fix those issues separately. It would also cause PRs to become bloated, since people would be forced to not just make their primary change, but also to fix code issues unrelated to their changes.

I think this would be a more appropriate solution: https://github.com/internetarchive/openlibrary/issues/2300 ; it still has some of these issues, but it's a much smaller scope since it only targets modified code lines as opposed to files.

**Comment by cclauss** [comment]
I understand that but...
We have had _undefined names_ (#1684) open for more than a year without much improvements and we have 400+ unused imports that are not getting fixed and new PRs are being opened with syntax errors that Travis is not catching and our import ordering is in shambles across tons of files.  If we do not tighten the screws somewhere then issues linger because there is no forcing function.

**Comment by cdrini** [comment]
What do you think of #2300 ? I think that's tightening the screws, without forcing all the devs to take on a lot of work they weren't intending to take, or making PRs explode in scope. It'll help with the syntax errors. Not so much with import ordering, but baby steps :) .

**Comment by cclauss** [comment]
I like that approach too.

**Comment by guyjeangilles** [comment]
@cdrini @cclauss What is the actionable step for this issue considering #2300 is still open?

**Comment by cdrini** [comment]
#3024 was good; I think we can implement the proposal in #2300 first, and see how that goes, and then decide if we want to take the bigger step proposed in this issue.

**Comment by cclauss** [comment]
What is left to do on this one?

**Comment by cclauss** [comment]
Also see #3093

**Comment by cclauss** [comment]
@cdrini Most of the other stuff is done but should we still worry about:
* unused imports
* unsorted imports

**Comment by imskr** [comment]
Can I work on this issue @cclauss

**Comment by cclauss** [comment]
Sure.  `flake8 --sélect=F401.` should find all the undefined names.

**Comment by mekarpeles** [comment]
Done -- lint-diff is in both travis + github actions / make
