### ISSUE TITLE
Subject pages should say they are about a subject

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#3012]
### Relevant url?
https://openlibrary.org/subjects/libraries

### Steps to Reproduce

1. Go to https://openlibrary.org/subjects/libraries
2. Look for something that provides the context of the page being about works on the subject of libraries.

* Actual: Page shows "Libraries 10,048 works"
* Expected: Suggest "10,048 works on the subject: Libraries" 

### Details
- **Logged in (Y/N)?** either
- **Browser type/version?** Chrome or FF
- **Operating system?** any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add wording to orient the patron on seeing the page.

**Comment by aashimgarg** [comment]
Hey @LeadSongDog do we just have to change from this "Libraries 10,048 works" to "10,048 works on the subject: Libraries" .?

**Comment by LeadSongDog** [comment]
That would be enough to convey to the reader that they are on a subject page IMHO. There are larger improvements possible, such as face tying, but baby steps...

**Comment by Keepingshtum** [comment]
Is the issue still around? Looks like something I can fix!

**Comment by mekarpeles** [comment]
Closing this issue as we already have a PR open which will make it so that subject pages render as if they are standard search results pages:

See: https://github.com/internetarchive/openlibrary/pull/2984
cc: @LeadSongDog

**Comment by BrittanyBunk** [comment]
I actually like it the way it is and wouldn't like to see it the way it's suggested here.
