### ISSUE TITLE
Remove solr/inside dead code

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3021]
At some point in the past, the search engine for letting you search inside books lived inside openlibrary. Now it lives in Internet Archive's code. The residual code left in the solr/inside directory is dead code and should be removed.

### Summary of Requirements
- [ ] Remove `solr/inside` directory
- [ ] Remove any code that references the code inside `solr/inside`

### Stakeholders
cc @cclauss

**Comment by cclauss** [comment]
Closed by #3027
