### ISSUE TITLE
Reading log links are broken

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#3025]
If you click on any reading log link, it doesn't work.

### Evidence / Screenshot (if possible)
![screenshot](https://user-images.githubusercontent.com/7125952/74341393-ed0ab300-4da7-11ea-9c08-9ad34725b52c.png)

### Steps to Reproduce

1. Go to "My Proflle" option in the menu;
2. Click on "currently reading", "have already read", and "want to read" link. (none of them work)

* Actual:

If you click on  any of these links ("currently reading", "have already read", or "want to read"), you get a "404 Page Not Found" message with the following text: "User $(page.key) does not exist".

* Expected: 

You should be able to see the books in your reading log for each category.

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Mozilla Firefox 68.4.1 
- **Operating system?** Debian GNU/Linux 9 (stretch)
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles @tfmorris @tabshaikh

**Comment by cdrini** [comment]
> @tfmorris : Yes, that's definitely internationalization. Also, the French translation has no links in it at all.
