### ISSUE TITLE
Borrow button no longer single-click borrows book

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3028]
### Steps to Reproduce

1. Go to e.g. https://openlibrary.org/books/OL5419329M/Zen_and_the_art_of_motorcycle_maintenance
2. Click "Borrow"

* Expected: Borrows book and goes to https://archive.org/stream/zenartofmotorcyc00pirsrich?ref=ol
* Actual: Goes to https://archive.org/stream/zenartofmotorcyc00pirsrich?ref=ol

### Details
- **Logged in (Y/N)?** Y
- **Browser type/version?** FF73
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Likely related to last deploy: https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-02-11
![image](https://user-images.githubusercontent.com/6251786/74365245-a616c080-4d9b-11ea-8e36-8360b3cb87fa.png)

### Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
Tried reverting the deploy on dev, and the problem went away, so definitely related to https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-02-11

**Comment by mekarpeles** [comment]
The problem is `edition.in_borrowable_collection()` in `user_can_borrow_edition` in `plugins.upstream.borrow` which is occurring because: 

https://github.com/internetarchive/openlibrary/pull/2955/files#r382877173

**Comment by hornc** [comment]
Under reproduction steps 2., the expected and actual URLs appear identical?
