### ISSUE TITLE
Missing commands in Cheat sheets.

### ISSUE THREAD

**Issue by aashimgarg** [internetarchive/openlibrary#3035]
Some commands in GIT CHEAT SHEETS is missing.
For example instead of using git pull we can git fetch and git merge. This will help the user to understand more.

**Comment by aashimgarg** [comment]
@hornc @jdlrobson @cdrini Should i work on this?

**Comment by cdrini** [comment]
Hi @aashimgarg ! Thank you for the suggestion; we want to avoid having a lot of unintentional `merge` commits in pull requests, as well as on your fork's master; so using `git pull` is preferable. Read the comments here for more info: https://gist.github.com/Chaser324/ce0505fbed06b947d962
