### ISSUE TITLE
503s on prod

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3036]
### Summary

- **What is wrong?**

- **What caused it?**

- **What fixed it?**

- **Followup actions:**
 

### Steps to close

1. [ ] Assignment: Is someone assinged to this issue? (notetaker, responder)
2. [ ] Labels: Is there an `Affects:` label applied?
3. [ ] Diagnosis: Add a description and scope of the issue
4. [ ] Updates: As events unfold, is noteable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [ ] "What caused it?" - please answer in summary
6. [ ] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by cdrini** [comment]
ol-www1 warning in NAGIOS https://monitor.archive.org/cgi-bin/nagios3/status.cgi?hostgroup=24.openlibrary&style=detail&servicestatustypes=4&hoststatustypes=15

**Comment by cdrini** [comment]
`ol-www1` `OLSEARCH` now critical in nagios

**Comment by cdrini** [comment]
Drop in pageviews occurred at 17:30 UTC

**Comment by cdrini** [comment]
This lines up with when a search issue was observed on archive.org (PT; UTC - 8h)
![image](https://user-images.githubusercontent.com/6251786/74468522-f445c580-4e68-11ea-9bb6-1168aded0202.png)

**Comment by cdrini** [comment]
Ops restarted their indexer at ~13:50 ET ; `ol-www1` no longer in NAGIOS

**Comment by tfmorris** [comment]
Why did Archive problems take down Open Library? I could see that it would cause problems with downloads of digital editions, but it shouldn't cause problems with page rendering.

**Comment by guyjeangilles** [comment]
@cdrini Is there anything else needed to close out this issue?
