### ISSUE TITLE
Modernizing our Python compound sorting

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3038]
The `cmp()` builtin and the `cmp=` parameter to `sorted()` were both removed in Python 3.
https://docs.python.org/3/howto/sorting.html
https://portingguide.readthedocs.io/en/latest/comparisons.html#the-cmp-argument

#3037 modernizes the easy cases of sorting but there remain other more complex, __compound sorting__ that I have not figured out how to solve...
https://github.com/internetarchive/openlibrary/search?q=cmp points to:
### sorted(d.keys(), cmp=lambda i, j: cmp(d[j], d[i]) or cmp(len(j), len(i)))
1. ~https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/works/by_author.py#L65~
2. ~https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/works/live.py#L77~
3. ~https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/works/find_works.py#L62~
### sorted(works, cmp=lambda a,b:-cmp(a['number_of_editions'],b['number_of_editions']) or cmp(work_key_int(a['key']), work_key_int(b['key'])))
1. https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/merge_works.py#L143

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
This feels like more of a refactor than a bug to me and I've labeled it as such

**Comment by cclauss** [comment]
The current code does not run on Python 3.  The proposed code runs on both Python 2 and 3.

I usually call code that does not run a bug.

**Comment by eduardoltorres** [comment]
@cclauss when or where is https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/merge_works.py#L143 exactly used?

I don't think I would have an issue "modernizing" it, but I am not sure where this function runs so I can check what's working and what's not. For exaple, line 144 from `merge_works.py`, where can I see this print?

**Comment by mekarpeles** [comment]
@eduardoltorres sorry that you've been blocked on this one -- @cclauss do you have any suggestions for @eduardoltorres ?

thanks all!

**Comment by cclauss** [comment]
@eduardoltorres I also suspect that this function is dead code.  It would be cool if you could create a pytest or doctest that proves our suspicion that this code would raise an error on modern Python if it was ever run.

Once our Python 3 migration settles down a bit, it would be cool to take a systematic approach to finding dead code with https://pypi.org/project/vulture or similar but not until things settle down a bit.

**Comment by cclauss** [comment]
I did a bit more digging...

This code is in the [main block of `merge_works.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/merge_works.py#L92) and is not indented under `if __name__ == "__main__":` so that code will be executed anytime that `merge_works.py` is run or imported.  The only place that I can find this merge_works mentioned is in a [--ignore statement in `run_doctests.sh`](https://github.com/internetarchive/openlibrary/blob/master/scripts/run_doctests.sh#L29) which gets run on the very last line of `.travis.yml`.

@mekarpeles @cdrini @hornc When does `merge_works.py` get run?  Is it OK if we delete this file?!?

If we need this file then we shoud do two things.
1. Create `def sorted_works(works):` that contains the logic of [the sort](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/edition_merge/merge_works.py#L142)
2. Put a bunch of doctests on that function that test all the combinations and permutations on Python 2.
3. Port the function body to support both Python 2 and Python 3 and ensure those same tests still pass.
4. Indent the whole main block under `if __name__ == "__main__":`
5. Remove the [--ignore statement in `run_doctests.sh`](https://github.com/internetarchive/openlibrary/blob/master/scripts/run_doctests.sh#L29)

**Comment by cclauss** [comment]
Closed because all files have been fixed or deleted.
