### ISSUE TITLE
Undefined name: Which import_author() should we use in openlibrary/catalog/load.py?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3041]
### Question

 Which of the [three versions of import_author()](https://github.com/internetarchive/openlibrary/search?q=import_author) should we import into [openlibrary/catalog/load.py](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/load.py#L46)?

[ ] from openlibrary.catalog.importer.load import [import_author](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/load.py#L123-L148)
[ ] from openlibrary.catalog.add_book.load_book import [import_author](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/add_book/load_book.py#L147-L175)
[ ] from openlibrary.catalog.onix.onix-import import [import_author](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/onix/onix-import.py#L83-L97)

**Comment by hornc** [comment]
Of the candidates `openlibrary.catalog.add_book` is the only module that is in active use.

I believe #3054 fixes this issue by deleting the various problematic files. (and archiving the legacy imported code to another repo https://github.com/internetarchive/openlibrary-bots/pull/37 )
