### ISSUE TITLE
Publishing history chart broken

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#3042]
The chart can show counts for one year only and does so in the wrong place. 

### Evidence / Screenshot (if possible)
![353EBCB8-A229-4F73-A1B2-8154556E4553](https://user-images.githubusercontent.com/11435431/74540551-f746c180-4f0d-11ea-9678-6fc67298ccde.png)
![C0DB8AAA-A3D8-459D-84CB-6E4AEFD2D1CC](https://user-images.githubusercontent.com/11435431/74540592-0e85af00-4f0e-11ea-9cac-39daa23c6b59.png)

### Relevant url?

https://openlibrary.org/subjects/in_library

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** both Safari and Chrome
- **Operating system?** iOS on iPhone
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Use two-finger zoom to select a section of timeline or put dragable handles on corners of the chart
Place the "420 editions in 1930" at the uncrowded top, not the bottom, of the chart box, either left- or right-aligned to the centreline of the chart box (opposite to the side of the selected year)

**Comment by guyjeangilles** [comment]
#158 may be related

**Comment by tfmorris** [comment]
It would be helpful to have an explanation as to why this got closed.

The drag-to-select functionality was broken as part of the front end "refactoring". I believe it used to not only change the displayed count for the selected date range, but also use that as a facet/filter.

Related issues are #2483, #2519, #2520
