### ISSUE TITLE
Adding the line break for better UI on Recent Changes page

### ISSUE THREAD

**Issue by aashimgarg** [internetarchive/openlibrary#3046]
![Screenshot from 2020-02-16 03-07-11](https://user-images.githubusercontent.com/55639487/74595600-74d31480-5069-11ea-8388-750bafad0029.png)

Add the line break for better UI between Recent changes and author merges.

**Comment by guyjeangilles** [comment]
@aashimgarg Please use the issue templates in the future when creating issues

I've also edited the title to make it more precise

**Comment by manav014** [comment]
https://github.com/internetarchive/openlibrary/pull/3078
Please check this PR for the same.

**Comment by manav014** [comment]
![Screenshot from 2020-02-22 00-40-37](https://user-images.githubusercontent.com/51242628/75064137-56a76180-550c-11ea-9f08-a760acd0c2c6.png)

**Comment by yash-gupta2000** [comment]
hello @aashimgarg , I would like to contribute on this. I'm having problem in installing docker images
Sending build context to Docker daemon 14.85kB
Step 1/12 : FROM olbase
pull access denied for olbase, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Stuck on this for last 3 hours. Help?

**Comment by yash-gupta2000** [comment]
#3083  
Please check PR.

**Comment by cdrini** [comment]
@guyjeangilles @aashimgarg Where should there be a line break? Please provide more information, since I'm not sure where the problem is.

**Comment by guyjeangilles** [comment]
@cdrini, I believe the line break should be between "Recent Changes / add cover" and "Author Merges | ..."

@aashimgarg correct me if I'm wrong

**Comment by Keepingshtum** [comment]
Hello all, read through this thread and the closed [PR](https://github.com/internetarchive/openlibrary/pull/3083)

From what I gather, we should add some padding as indicated in my screenshot (pardon the poor handwriting!)

![Screenshot (334)_LI](https://user-images.githubusercontent.com/20059269/76696632-97316f80-66b3-11ea-869a-17faa7473ebc.jpg)

@guyjeangilles @cdrini Correct me if I've got it wrong. Would love to submit a PR and get some momentum contributing!

**Comment by manav014** [comment]
#feature
Added a line break for better ui
Made  a commit that can close this issue please check that out.
