### ISSUE TITLE
Move standalone legacy catalog scripts out of Open Library main tree

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#3049]
Quite a number of sub-directories under `openlibrary/catalog/` appear to contain standalone scripts and utilities that are were never intended to be part of the Open Library main codebase. Other parts _are_ used for importing, and MARC record processing and are very much part of Open Library.

Python 3 and absolute import work is revealing some of this legacy code, and it's unclear how to test, or whether the modernisation changes are even appropriate.

### Proposal & Constraints

Proposal: Move all catalog subdirs that are entirely legacy / standalone code to `/scripts/legacy/catalog`, similar to https://github.com/internetarchive/openlibrary/tree/master/scripts/legacy/marc

This will remove similarly named code from consideration when working on active features, and reduce the burden on modernisation of OL code by not including code we do not need to support. 

### Additional context

Some examples:

**Used and Important**
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/add_book ; Main location for importing logic
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/marc ; Main location for MARC parsing code. Unfortunately there are legacy and deprecated versions of the code within this sudir, and very likely other files which are not used. It appears this code was a stand alone set of scripts which became merged, and is now integral to OL.

**Unused**
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/dup ; stand alone stats gathering script?
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/crawl/catalogue.nla.gov.au -- historical task specific code that is not part of any current process
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/wikipedia ; not part of any current process
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/scratch ; one off historical tasks? 'scracth' implies temporary / experimental scripts?
-https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/talis/isbn_and_author_date.py ; part of an historical import effort?

- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/solr ; not sure, but looks like a one off data analysis script?
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/treasury ; another historical import / analysis one off script?
- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/oca ;  another historical import / analysis one off script?
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/title_page_img ; standalone historical cover fix up task script for ImportBot ?
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/onix ; Standalone project with its own readme?
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/lc_updates ; historical script to one-off fetch updates from Library of Congress. Could be useful if it still works (unlikely?), but still not a core part of OL

Other dirs are less clear;

- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/importer needs a review. It seems to use a lot of deprecated MARC code, but may be the main source of imports from archive.org. It is probably due for a major refactor and simplification.

- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/catalog/merge ; some of this code _may_ be used, the 'merge' terminology is used elsewhere confusingly for detecting existing records (?)

- utils and works sound relevant, but may not be.

- ia could be in use, but whatever it does should probably be handled by https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/ia.py

### Stakeholders

@hornc @cclauss 

Similar to past issues: #901

**Comment by cclauss** [comment]
> Proposal: Move all catalog subdirs that are entirely legacy / standalone code to /scripts/legacy/catalog

My preference would be that we move these files to a separate new repo: https://github.com/internetarchive/openlibrary_unused so that we can grip and lint and run tests on the entire openlibrary repo without any exceptions or false positives from legacy directories.

**Comment by hornc** [comment]
I need to investigate why some solr code appears to be using catalog/get_ia

**Comment by guyjeangilles** [comment]
@hornc Can an issue be both a feature and a refactor?

I've also added your `MARC records` label as MARC parsing uses some of this legacy code as stated in the original issue.
