### ISSUE TITLE
Incorrect ISBN search result

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3068]
This search: https://openlibrary.org/search?isbn=02268162060226816214
brings up this edition: https://openlibrary.org/books/OL25433364M/La_conoscenza_come_bene_comune._Dalla_teoria_alla_pratica
with an ISBN of: 9788861591424

I expect invalid ISBNs to be rejected outright and ISBNs which aren't in the database to return zero matches, not some random edition.

The link is found on this page: https://opensyllabus.org/result/title?id=292057895920
so it's not a made up example.

### Stakeholders
@hornc @cdrini

**Comment by LeadSongDog** [comment]
@tfmorris For me, that search now returns “no results found“. Can this issue be closed?

**Comment by SouthGoingZax** [comment]
I also can't repro.  Closing.
