### ISSUE TITLE
Be able to create lists from Lists page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3070]
I feel this would come in handy for making necessary lists quickly instead of having to go to the book's page for it to be created. I don't think people should be creating lists without books on it, but if they could add a minimum of one book when they create their list, it could come in handy. It's not the most important feature, but is here for when it could be worked on.

**Comment by guyjeangilles** [comment]
I suspect this would involve creating a form similar to creating a new work/author/edition, etc.

**Comment by BrittanyBunk** [comment]
@guyjeangilles yup!

**Comment by cdrini** [comment]
This has been completed!
