### ISSUE TITLE
Sharing Lists shows un-rendered i18n $_ in description (Nested quotes?)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3076]
https://openlibrary.org/people/booklists/lists/OL146382L/David_Bowie_Top_100 @tfmorris @cdrini @tabshaikh  I think we have another i18n bug in our meta:

**Open Library**
David Bowie Top 100 | Lists | Open Library
$_(‘View the list on Open Library.’)

### Evidence / Screenshot (if possible)

This may be because of nested quotes:
`<meta content="$_(&#39;View the list on Open Library.&#39;)" property="twitter:description" />`

### Steps to Reproduce

1. Go to ... https://openlibrary.org/people/booklists/lists/OL146382L/David_Bowie_Top_100
2. Do ... share this link on slack and see that the meta desc it shows is:
`$_(‘View the list on Open Library.’)`

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
This class of bug seems to appear in several places, tracking them on this thread:

When a patron removes an item from a list:
“Yes, I&#39;m sure”

**Comment by tfmorris** [comment]
None the strings for the type `list` were extracted, so this whole section needs translating.
