### ISSUE TITLE
Add/remove from waiting list- the form doesn't submit

### ISSUE THREAD

**Issue by SRGOM** [internetarchive/openlibrary#308]
In the file: [openlibrary/openlibrary/templates/borrow.html](https://github.com/internetarchive/openlibrary/blob/acb9d2dd031da8449ae9aaf9cfc82da1c7d7e91b/openlibrary/templates/borrow.html)
Search for `class="submit"`. This is a part of `<a href="javascript:;" class="submit">` and is used to submit the form. However, it looks like there is no attacked JS to submit the form. A quick (but ugly) solution would look like rewriting all the `a` tags as such:

`<a href=#  onclick="javascript:$( this ).parents( 'form' ).submit()>`

A better solution would be to have a js function that adds an event listener after the page has loaded: 

```
$( ".submit" ).on( 
    "click",
     function(){ $( this ).parents( "form" ).submit() }
 )
```

I am not a regular contributor and I feel like me learning your coding guidelines would be an unnecessary effort, just for this small change. So can someone make this change please? Thank you.

**Comment by bfalling** [comment]
@SRGOM: Thanks for your comment, but lower on the `borrow.html` page, a click handler is already added, which does the form submission:
```
\$(function() {
    \$("a.submit").click(function() {
        \$(this).closest("form").submit();
    });
});
```
Is this not working for you?

**Comment by SRGOM** [comment]
Not on the current version in production...

**Comment by SRGOM** [comment]
Adblocker (uBlock Origin) issue, sorry for the false alarm.
