### ISSUE TITLE
Twitter HighestRatedBot Pilot

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3088]
How do we reach more patrons/readers and help them discover opportunities on openlibrary.org?

### Proposal

"Trending” each month, we only consider books from that month and post the top 10 highest/most rated books on Twitter using a Twitter Bot. 

The books we consider would be the ones that would have had the most engagement in that month.
- most times added to the Reading Log. 
- The Books with the highest Star Ratings.
- Most number of searches.

### Constraints and Planning 

As an experiment, we would try doing this manually (query our stars table) and see how much engagement we get if we post this out on our official Open Library twitter. 
The next step would be to create a Twitter Bot which would automatically post the "HighestRated"/"Trending" books on OL to twitter. 

### Stakeholders

@mekarpeles @tabshaikh

**Comment by cYph3r1337** [comment]
hey, I want to work on this. Should I?

**Comment by tabshaikh** [comment]
Hi, this issue is at hold for now as we are replanning our Distribution Plan for OL :)

**Comment by tfmorris** [comment]
Wouldn't it make more sense to first create a page (or section of the home page) that has these trending books on it? Then you have someplace for the bot to point people to.

**Comment by tabshaikh** [comment]
That sounds great too, in my mind I had like we upload a list of these books to Twitter with link to each

**Comment by cYph3r1337** [comment]
@tabshaikh I think your Idea will work fine 
Highest engagement book --> Bot tweets them (with link to the book) --> Trending page also starts showing them.

**Comment by mekarpeles** [comment]
I think it makes sense to prioritize our existing `borrowbot` #3255 before moving on to other projects. This thread has good ideas, however going to close it for pending how #3255 peforms
