### ISSUE TITLE
Use of the `text` property

### ISSUE THREAD

**Issue by mjfneto** [internetarchive/openlibrary#3101]
### Question
How can I use the `text` property received after doing a search request? Why is it an array with multiple id values? Are those pages?

**Comment by guyjeangilles** [comment]
@mjfneto I assume you're referring to the [Search API?](https://openlibrary.org/dev/docs/api/search) Correct me if I'm wrong.

The `text` seems to be random information for a short glance at `https://openlibrary.org/search.json?q=the+great+gatsby` @hornc can you shed some insight

**Comment by tfmorris** [comment]
I've updated the Search API documentation with additional information on this field:
https://openlibrary.org/dev/docs/api/search?_compare=Comparer&b=3&a=2&m=diff

It is an array of a bunch of different strings which is used to power the "All" search mode. You can find specifics in the Solr schema which the documentation links to.
