### ISSUE TITLE
Community Features

### ISSUE THREAD

**Issue by grravity** [internetarchive/openlibrary#3103]
### Feature Suggestion
I am suggesting the implementation of a bit more community features, such as reviews, forums, and better lists/profiles. 

### Suggestions To Implement, Possible Drawbacks, etc.
Goodreads is currently the mainstay for lists, and community driven aspects as far as a book site goes, but their site requires [lots of scripts to run](https://imgur.com/a/uqvCIsp), they are extremely advertiser heavy, a few privacy concerns, aren't very friendly to the open source community, and openlibrary just feels like home. I think implementing a few basic features to Openlibrary would make it amazing, and maybe even a competitor to goodreads. I understand Openlibrary is meant to be more of a database, but I genuinely don't see the harm in implementing a few basic community features to make it more similar to Goodreads, while keeping the main idea of Openlibrary. I think adding in a forums section, for users to discuss books, adding in the ability to provide reviews, maybe some kind of little achievement system for contributing to the database, friending and more friendlike features like goodreads has, and better list handling would be absolutely great. Maybe even an IRC channel for realtime discussion. I guess you could say, an [AniDB ](https://anidb.net/)but for books.

**Comment by guyjeangilles** [comment]
@grravity as this issue stands it isn't very "actionable." The items I've parsed from the issue description were:
- a forum  (covered in #2456)
- reviews (#1830 removed the book review plugin, with comments that it was coming back. Not sure if that was for user reviews or external reviews)
- achievement system for contributing to the database
- friending (covered in #739)
- list handling ([there's a label for this](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+follow+user+is%3Aopen+label%3Alists))
- IRC channel

#1964 was about making OpenLibrary more like GoodReads which was met mostly with opposition by the community. I doubt much as changed, but other people chime in.

**Comment by grravity** [comment]
> #1964 was about making OpenLibrary more like GoodReads which was met mostly with opposition by the community. I doubt much as changed, but other people chime in.

Ok, this is very understandable. It is a shame though imo, I think it has potential. The API is open though isn't it? Meaning anybody could theoretically make a site using OpenLibrary as the db. Maybe someone with the skills and interest would consider that to keep things a bit more seperate idk.

 As for lists though, I genuinely think that's the one thing that needs some work. The reading log seems to be both connected and disconnected to lists. If you go to a books page, and add a book to a list, you can select "reading", but that's not actually a list, it's a list part of the reading log. But if you go to "My lists", you can't see your lists beside your reading log lists. It's very messy imo. Especially if you would like to just share a link to all your lists (including your reading log).

Ontop of this, if you add a book to a custom list. Say The Hobbit for example, it adds that specific edition (which is great, but there was no clear option to add all editions instead).. and also if you add it to your reading log, it adds all the editions just as "The Hobbit - xxx editions", so it's not as specific (with no clear way of only adding a specific edition).

I can open a new issue for this with the lists label if that's preferred?

**Comment by guyjeangilles** [comment]
@grravity A new issue for the list feature you recommended would be welcome. I'll close this issue for the time being.

Also, OpenLibrary is an AGPL project so anyone could build a GoodRead-like competitor. I think the project wlhas data integrity issues so I would encourage anyone with the skillset to make a GoodReads competitor to consider contributing to OpenLibrary's backend :grin:
