### ISSUE TITLE
Implement Feature to add Chat Box

### ISSUE THREAD

**Issue by sonali623** [internetarchive/openlibrary#3107]
Implement a ChatBox Feature for realtime solutions to user problems.

### Describe the problem that you'd like solved
Forms and Mails are the old way to solve user problems. Most of the user issues can be solved with the help of a realtime chatbox. This would also help overcome objections of users instantaneously that mails and forms.

**Comment by guyjeangilles** [comment]
I'd figure this would make the FAQ obsolete

**Comment by mekarpeles** [comment]
calling this out of scope for now and closing; we have support for the time being and don't have sufficient staff or prioritization to create an automatic chat bot or a staffed bot.
