### ISSUE TITLE
Allow '/people' in robots.txt

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3115]
We want to index /users and /people (lists + reading logs, as they become public)

### Related files

https://github.com/internetarchive/openlibrary/blob/75452cf6f0e3c23e1030395c93e232686ebaa417/static/robots.txt#L3-L4

**Comment by MayankVir** [comment]
@mekarpeles I would like to work on this issue.

**Comment by imnotaqtpie** [comment]
i would like to work on this issue if possible. thanks.

**Comment by guyjeangilles** [comment]
@mayankvir @imnotaqtpie PRs are welcome to solve this issue
