### ISSUE TITLE
Does Open Library have a real dependency on acs4?

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#3119]
### Question

#3055 exists to remove a symlink that is breaking the new Python code linting process from working in dev. 

While trying to fix the symlink I noticed that of the two places acs4 is imported,

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/lending.py#L17

Doesn't seem to use `asc4`

and 

https://github.com/internetarchive/openlibrary/blob/d1c8dea74d1ca5170dd310f8bc4d53a12aec9baa/openlibrary/plugins/upstream/borrow.py#L490-L491

uses only one method, but seems to do nothing with the result?

@mekarpeles Can we remove this dependency altogether?

The existence of the symlink blocks the `make lint` command from giving sensible results so I have to test by pushing to CI, which takes too much time.

**Comment by mekarpeles** [comment]
I don't think we can remove acs4 dependencies. We tried doing this in the past and it didn't go well.

**Comment by tfmorris** [comment]
Since all lending is done by IA, not OL, I don't see why OpenLibrary would have a dependency on Adobe Content Server, which is used specifically for lending.
