### ISSUE TITLE
HTTPError: HTTP Error 503: Service Unavailable (falling back to default template)

### ISSUE THREAD

**Issue by grravity** [internetarchive/openlibrary#3121]
20:30:50 EST, 3/3/2020

/opt/openlibrary/deploys/openlibrary/c5dfe5e/openlibrary/templates/type/edition/view.html: error in processing template: HTTPError: HTTP Error 503: Service Unavailable (falling back to default template)
Unable to render this page. 

### Evidence / Screenshot (if possible)
https://b.catgirlsare.sexy/OwJV.png

### Relevant url?
https://openlibrary.org/books/OL7760799M/Home_Improvement_1-2-3

### Steps to Reproduce

1.  Search for a ISBN number
2. OR search for a book, then click the book's page.

* Actual: error above.
* Expected: brings me to the page.

### Details

- **Logged in: Yes** 
- **Firefox ESR 64bit 65.8.0 (OpenLirary was working a few hours ago no issues)** 
- **Win 10** 
- **not sure - prod**

**Comment by cdrini** [comment]
Thanks for the report, @grravity ! Could you provide the url you were visiting?

**Comment by cdrini** [comment]
Ah, found the url; you had placed it in the HTML comment. I updated the description

**Comment by grravity** [comment]
Yeah the link is in the issue :)

**Comment by cdrini** [comment]
Getting the same error on https://openlibrary.org/books/OL27820548M/Less . @mekarpeles @hornc , is this perhaps related to the PAAPI update?

**Comment by mekarpeles** [comment]
Resolved on production; closing issue and will tag w/ the PR to the actual solution
