### ISSUE TITLE
Consolidate OpenLibrary issue trackers to single public place

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#313]
We have at least the following bug trackers:

2007-2013 https://launchpad.net/openlibrary
2011-2014? https://github.com/internetarchive/openlibrary/issues
2014?-present Private JIRA tracker accessible only to employees

We should focus issue tracking on a single publicly accessible system. If you know of other trackers out there that are relevant, please add them in comments.

**Comment by tfmorris** [comment]
@bfalling @mek @jgonzalez159 @gdamdam mentioned this on OL Slack, but @'ing you so you get a more contextual notification.

**Comment by bfalling** [comment]
I've been told that the launchpad list is old/deprecated. My preference would be to use GitHub as the baseline tracker, and move all tasks which are still relevant from launchpad and JIRA to GitHub.

In addition, coming up in October is the 20th anniversary of the Archive, so I've created a Project here to highlight certain priority items. I'm open to input as to which tasks should be placed there, but particularly aiming for bugs which are causing users the most grief or features which would be the most empowering.

**Comment by tfmorris** [comment]
👍  Github works for me as the canonical tracker.

**Comment by bfalling** [comment]
All priority tasks identified by @jessamynwest and others have been moved to GitHub. See: https://github.com/internetarchive/openlibrary/projects/1
