### ISSUE TITLE
Digital audio editions shouldn't have a "Read" button

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3137]
Editions which can't be read shouldn't have a "Read" button next to the "Listen" button. The Read button is shown both on the works page, next to the edition, and the edition page.

### Relevant url?
https://openlibrary.org/books/OL26500501M/Pygmalion

**Comment by mekarpeles** [comment]
Should this even be a book on Open Library?

**Comment by LeadSongDog** [comment]
@mekarpeles Whyever not? It’s a human volunteer reading a particular PD text. More details are in the FAQ at https://forum.librivox.org/viewtopic.php?f=18&t=219

For some reason the link from the IA page to the Librivox page did not propagate to OL. That might’ve been because OL doesn’t yet support that identifier. I have linked it from edition notes in lieu.

**Comment by tfmorris** [comment]
> Should this even be a book on Open Library?

Yes, it definitely should according to our cataloging guidelines. I'm a little surprised it's even a question given past discussions about how important audio books are in today's marketplace. LibriVox books are much closer to "real" audio books read by voice talent than machine TTS of error-laden machine OCR. The Internet Archive staff also seemed very proud that they were hosting all the LibriVox recordings.

**Comment by seabelis** [comment]
This is resolved.

**Comment by tfmorris** [comment]
Can you expand on what the resolution was? If anything, it looks worse to me. The "Read" button is still there and it's been joined by a "Search inside" box, plus the screen is inconsistent saying "Not in the library" in one place and "Read" in another. It's offering "Print Disabled" when there's no Daisy file and, lastly, if you click the "Read" button the spinner never goes away.

(Ignore the mix of English and French. That's just because all new UI features and changes are added as English only)

![Screen Shot 2021-02-23 at 1 58 32 PM](https://user-images.githubusercontent.com/82178/108899906-f9defb00-75e6-11eb-8ba9-48a0e952e0e9.png)

**Comment by LeadSongDog** [comment]
This overlaps #4379. I can’t really understand why there are two buttons at all. Let’s just have one that works correctly.

**Comment by seabelis** [comment]
@tfmorris Yes, you're right. The Read button is still beneath the cover, just not on the editions list. Reopening.

**Comment by jonbell-lot23** [comment]
Hello, I’m new and I’m looking at UI issues. Is this still an issue? When I visit https://openlibrary.org/books/OL26500501M/Pygmalion I see two buttons:

* Audiobook
* Want to read

**Comment by mekarpeles** [comment]
In the future we may add format to our providers field within the Open Library edition (e.g. internet archive could have a format for text versus audio). At this point, it's not something we're planning on fixing.
