### ISSUE TITLE
Add AGPL Licensing to JS for FSF (Due: 2020-03-13)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3154]
### Describe the problem that you'd like solved

Brewster is giving a talk @ FSF so we want to get our js licenses up to grade :)

### Stakeholders

@bfalling, @cdrini

**Comment by tfmorris** [comment]
I'm confused. Do we have different licenses by language? I thought the whole repo was AGPL.

**Comment by cdrini** [comment]
Useful links for context:
- https://www.gnu.org/software/librejs/free-your-javascript.html
- https://www.fsf.org/blogs/licensing/rel-jslicense

**Comment by tfmorris** [comment]
To clarify, this doesn't add or change any licensing. It adds special markup to declare the license in a machine readable form for an obscure browser plugin. "Obscure" in this case means that when it was last available from the Mozilla store in Nov 2018, it had a grand total of 249 users during its 4 year lifetime. 
https://web.archive.org/web/20190512112349/https://addons.mozilla.org/en-US/firefox/addon/librejs/

It's hard to understand why this was considered enough of a priority to pull developers off real work that benefits customers.
