### ISSUE TITLE
Clean up automated tests

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#316]
Even aside from adding a more complete set of tests, the existing tests should be evaluated.

During deployment, only these tests are run by CI (from the Makefile):
- openlibrary/core/tests
- openlibrary/plugins/upstream/tests/test_forms.py
- openlibrary/plugins/upstream/tests/test_utils.py

Here are the results of running `py.test DIRNAME` on the following directories (names like `*test*`) inside Vagrant:
- openlibrary/core/lists/tests: PASS
- openlibrary/core/processors/tests: PASS
- openlibrary/core/tests: PASS
- openlibrary/coverstore/tests: FAIL
- openlibrary/mocks/tests: PASS
- openlibrary/olbase/tests: PASS
- openlibrary/plugins/admin/tests: FAIL
- openlibrary/plugins/books/tests: FAIL
- openlibrary/plugins/importapi/tests: FAIL
- openlibrary/plugins/inside/test: FAIL
- openlibrary/plugins/openlibrary/tests: FAIL
- openlibrary/plugins/upstream/tests: FAIL
- openlibrary/plugins/worksearch/tests: FAIL
- openlibrary/records/tests: FAIL
- openlibrary/tests: Only contains integration tests to be run outside vagrant: PASS
- openlibrary/utils/tests: PASS
- vendor/infogami/infogami/infobase/tests: PASS
- vendor/infogami/infogami/utils/tests: FAIL
- vendor/infogami/test: FAIL
- vendor/infogami/tests: FAIL
- vendor/infogami/tests/test_infogami: FAIL

We should correct-and-include or else delete the above tests. Consider consolidating all tests under the top-level tests/ directory.

**Comment by hornc** [comment]
:+1: 
I'm happy to help make this happen. I'll continue with https://github.com/internetarchive/openlibrary/pull/285 which is an attempt to get a test file sitting in `openlibrary/solr` to pass.

**Comment by hornc** [comment]
Other test files to collect:
/openlibrary/catalog/marc/test_work_subject.py

**Comment by hornc** [comment]
@bfalling , I can see two key areas where I can group tests right now, the `core` tests and the `solr` tests (in PR #285). Other tests can follow when we untangle what they are. According to the Readme, everything under `plugins/` is legacy and will be moved to `core` and `www` "soon" :)

Two options for consolidated new locations:
**1)**
```
<repo_root>/openlibrary/tests/core
                             /solr
```
OR
**2)**
```
<repo_root>/tests/unit/core
                      /solr
```
Which would you prefer?

I'm not sure if we are to take 'openlibrary/openlibrary` (what I'm referring to above as `<repo_root>/openlibrary`) as the openlibrary code top-level, or use the repo's top-level for the unit tests too.

**Comment by bfalling** [comment]
@hornc: For now, I'm slightly leaning towards the first option for test organization. Generally, I tend to organize around the role of the objects being tested, rather than the kind of test. e.g. "tests/models/..." rather than "tests/unit/..." but frankly, here there are a lot of mixed roles being played, so I think keeping them directly under "tests" and letting the subdirectories mirror the subdirectory structure in the code base is fine.

The one special directory is `tests/integration/`, which are browser-based tests run separately from `make test` and not meant to be run in the CI, and many of which could be replaced by functional tests once it's clear how to do that in this code base.

Re: the `plugins/` directory... I suspect that that statement about it being "legacy" was aspirational, since as far as I can tell, those files are still very much in use and in fact, constitute much of the core functionality (although some core functionality also exists under `core/` and `www/`). In any case, there are bigger fish to fry, so I suggest just testing things where they exist now, rather than continuing any migration out of `plugins/`.

**Comment by hornc** [comment]
Currently passing test locations to add:

- [ ] openlibrary/utils
- [ ] openlibrary/plugins/worksearch
- [ ] openlibrary/olbase
- [ ] openlibrary/mocks

**Comment by tfmorris** [comment]
What's the status of this? Was it completed and then tests started failing or is there more work to do?

Currently 7 tests are failing from `make test`
````
$ make test | grep x
platform linux2 -- Python 2.7.6 -- pytest-2.2.0
openlibrary/tests/core/test_waitinglist.py .xx.
openlibrary/plugins/upstream/tests/test_account.py .xxxxx
==================== 262 passed, 7 xfailed in 12.01 seconds ====================
````

**Comment by tfmorris** [comment]
Actually, looks like those tests are expected to fail, so perhaps this is done and can be closed?

**Comment by hornc** [comment]
@tfmorris I believe this is done, any further test tidy up can be raised as separate, more specific issues. Do you agree @bfalling ?

**Comment by mekarpeles** [comment]
I think this is right, we can open up new tasks for specific test areas where we are in greatest need of additional coverage
