### ISSUE TITLE
Remove use legacy ASCII only functions

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3176]
The legacy `isalpha()` and `isalnum()` functions should not be used any place where we expect freeform text because they are restricted to the ASCII character set.

There are two places that need to be cleaned up:

1. In the file [`openlibrary/plugins/upstream/models.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/models.py#L622-L646), the functions `filter_problematic_subjects(subjects, filter_unicode=True)` and `get_related_books_subjects(self, filter_unicode=True)` have a `filter_unicode` parameter.  The former function uses it to remove subjects that contain Unicode characters like `François`.  The latter function ignore the `filter_unicode` and would always filter out `François` and the test case explicitly tests for this.

The entire method is suspect since it's also blacklisting any subjects which contain punctuation, but we need to at least fix the multinational character part. 

2. In the file `openlibrary/plugins/search/stopword.py` which is unused dead code that implements an English only stopwords list.
https://github.com/internetarchive/openlibrary/blob/b26b6c3990504dcea35a5356c0cbf79074a9ab2c/openlibrary/plugins/search/stopword.py#L19-L20

The entire module should just be deleted.

**Comment by tfmorris** [comment]
The behavior of `isalpha()` and friends is actually Python version dependent. In Python 2 it is locale dependent, effectively making it ASCII only on our servers, but in Python 3 it includes all Unicode letters.

The `filter_problematic_subjects` method may be designed to work around inadequate escaping in https://github.com/internetarchive/openlibrary/blob/5f225827eb056da5051b3dab630d5721db85c960/openlibrary/core/lending.py#L115
which is used to query archive.org, so this may need to be fixed to correctly escape/quote punctuation and encode multinational characters.

**Comment by cclauss** [comment]
> The entire module should just be deleted.

What files should be deleted?

**Comment by tfmorris** [comment]
> > The entire module should just be deleted.
> 
> What files should be deleted?

`openlibrary/plugins/search/stopword.py`
