### ISSUE TITLE
Loan Actions Button UI can be improved

### ISSUE THREAD

**Issue by ishank-dev** [internetarchive/openlibrary#3186]
Loan actions buttons are not aligned properly and can be styled to enhance UI
### Evidence / Screenshot (if possible)
![Screenshot_20200315_011353](https://user-images.githubusercontent.com/45262592/76689374-42620a80-665b-11ea-896c-686d7eb10057.png)
### Relevant url?

https://openlibrary.org/account/loans
### Steps to Reproduce

1. Go to https://openlibrary.org/account/loans
2. You should have borrowed at least 2 books in order to see the loan action buttons

* Actual: Poorly aligned buttons 
* Expected: Proper styled buttons that are easy to understand.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**  Chrome

- **Operating system?** Ubuntu 19.10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Just have to style the buttons by putting the appropriate class name if it already exists.
### Related files

Not sure about the right CSS file please add it here if possible.

**Comment by jamesachamp** [comment]
This can be closed.  Duplicate issue #3225 was opened about a week after this issue, and was closed by PR #3244. Subsequent improvements were made, and the buttons look like this today:

![updated_buttons](https://user-images.githubusercontent.com/28732543/96517995-e5a18080-1237-11eb-9c40-54dc8dfca233.png)
