### ISSUE TITLE
Display better error message when IA services time out during borrow

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#319]
When attempting to borrow a book, if the IA loan services time out, a unspecified error is thrown. Instead, show a message, "The lending service is experiencing some issues. Please try again later."

Suggestion: Find where `openlibrary/core/lending.py:_get_ia_loan()` is called.

**Comment by salman-bhai** [comment]
Hi can I fix this Issue?

**Comment by mekarpeles** [comment]
I think this has been mostly resolved by increasing the timeout. @salman-bhai, we'd love your on another open issue! #802 may be a great starting place!
