### ISSUE TITLE
How to modify sql query and save the changes

### ISSUE THREAD

**Issue by the-nine-tail** [internetarchive/openlibrary#3191]
I was trying to fix xss in openlibrary, so I wanted to modify the sql query which insert the record of books in database. Where can I find all the queries and also after modifying how to save the changes??

@openlibrary

**Comment by guyjeangilles** [comment]
@the-nine-tail I don't know for sure, but I don't think there's a documented way to modify the OpenLibrary database directly with SQL, at least for non-staff. I think volunteers can only use Infogami, but I may be wrong.

**Comment by cdrini** [comment]
Hi @the-nine-tail ; [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) is unrelated to SQL; I believe you're thinking of [sql injection](https://en.wikipedia.org/wiki/SQL_injection), which isn't the problem here.
