### ISSUE TITLE
Borrow Graphs data stopped recording / generating for homepage

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3194]
This is also now happening to our user borrow counts graph (which we temporarily disable on the homepage live on ol-web3, ol-web4)

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/2481#issuecomment-599739110_

**Comment by mekarpeles** [comment]
Initial hunch is the cron may be failing due to AmazonAPI exception, but we tested commenting this code and still did not have success at recording / rendering data.

**Comment by the-nine-tail** [comment]
@mekarpeles can you please show the steps to reproduce this bug and any more details.
