### ISSUE TITLE
Investigate inconsistent state on Borrow page

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#320]
When I went to a borrow page — https://openlibrary.org/books/OL24658625M/The_song_that_sings_itself/borrow — it gave me the triple option (Online/PDF/EPUB) to borrow the book. When I clicked on Read Online, it returned me to that same page but with notice “You’ve already borrowed this. Read online or Return.” I clicked “Read Online” and went successfully to the Book Reader. Seems like maybe some state got glitched, because the page thought it should display the Online/PDF/EPUB borrow choices and yet also some internal flag indicated that the book was already borrowed.

**Comment by mekarpeles** [comment]
This should be addressed, please re-open if not
