### ISSUE TITLE
Offer alternatives joining a waitlist

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3200]
The issue is that since more people are going to go to the OL in the future, preparing that would involve getting people to where they need. So if someone sees (or clicks on) the waitlist button, there are a list of similar books to choose from. This is just a 2nd option to joining the waitlist, as that option should still be available too, just not the only option.

That I believe would be what would keep people on the site and happy. I know personally that if I really can't get a book I want, the next best version is still going to help me out than nothing at all.

**Comment by tabshaikh** [comment]
@BrittanyBunk But if we are on the works page we can get a list of all the editions with their availability https://openlibrary.org/works/OL15203980W/Macbeth so the question could also be how can we do something similar if we are on a edition's page

**Comment by BrittanyBunk** [comment]
Not just the work's page, but other works if all those editions are taken. It's tough, but I would say if there's a way to go by a list (like I believe if I want say the 12th edition, the order would be 13th followed by 11th, then 14th, 10th, etc.). So there would be an order that a program would go by and it would suggest the next 3 books that one could take up.

**Comment by BrittanyBunk** [comment]
@tabshaikh I took the first example waitlist book I could find: https://openlibrary.org/books/OL3968892M/Marc_Chagall. Using the subject's page based on the words in the title: https://openlibrary.org/subjects/person:marc_chagall_(1887-), I generated a list of 'related' books that are just from the top 3 ones that say 'borrow' on them:
![image](https://user-images.githubusercontent.com/55302685/76833536-c0075100-67e8-11ea-8735-5f972a13aeea.png)
Note: just a draft, but it visualizes the idea

**Comment by tabshaikh** [comment]
How about a popup which shows related books and will reduce the clutter significantly

**Comment by BrittanyBunk** [comment]
@tabshaikh yes - that's what I was hoping to go for!

**Comment by BrittanyBunk** [comment]
while talking to Lisa, here's the list I created in order of priority (I bet it's incomplete, but a start). If one doesn't work (all the books are waitlisted or is unusable), go to the next:
1) duplicate book - just without a waitlist on it
2) collections - books with the book in it - same edition of course 
3) other editions
4) subject pages based on the title
5) fuzzy attributions - base on subject of book, similar works by author, similar books to it - kind of what the current carousels do now, just all in one with the book being available

Another option is just to not show books that are waitlisted in carousels (I guess it'd be good to make another Github issue from that), but that won't help those who go straight to the edition (or even work) page.

**Comment by BrittanyBunk** [comment]
slack continuation of the issue here: https://app.slack.com/client/T03ST9K7K/threads/thread/C0ETZV72L-1584261722.215000

**Comment by EbotFabien** [comment]
Hi @BrittanyBunk,concerning the altenatives for waiting list i think a button labelled  ‘’ While Waiting ‘’ below can help reduce the clutter and later on trigger a module that gives a whole bunch of related books to the user and the user can choose a book at the same time entering the waiting list or else he doesn’t click on the while waiting button at all and decide to take the waiting list option only.its like a 2 in 1 proposal.


<img width="387" alt="Capture final" src="https://user-images.githubusercontent.com/48429179/77045084-d7009b80-69c0-11ea-81e7-4262a81fb27a.PNG">
<img width="302" alt="Capture modal" src="https://user-images.githubusercontent.com/48429179/77045152-f0a1e300-69c0-11ea-9981-9c6df4881c9a.PNG">

**Comment by BrittanyBunk** [comment]
@EbotFabien yasss!!!! Such a great idea! I love it! 

I was wondering, what if we just combine the join waitlist with the while waiting button, and just say 'join waitlist and while waiting' <- ok, that'll need to be condensed. Maybe 'join and read', idk. 'Join and find'? I got it: 'join and browse' - with a confirmation of what spot someone is on the waitlist for.

The next step, now that we figured out what would be shown there, as what popped up worked for the Mark Chagall book, but fiction novels (@seabelis brought up 'Celery at Midnight') would likely need to use other subject tags instead of the author. I think basing it off of subject tags would be cool - but since the IA is likely going away from that - an alternative would need to be proposed.

**Comment by guyjeangilles** [comment]
@BrittanyBunk Would moving the "You might also like" section satisfy this issue?
![ol_3200](https://user-images.githubusercontent.com/7256157/77259365-caa66800-6c78-11ea-8d02-0246c3f34124.png)

**Comment by BrittanyBunk** [comment]
Maybe we don't have to move it. Maybe when someone clicks on the 'join waiting list' button, they're automatically added to the list and then redirected to that carousel (I mean, the webpage scrolls to that instead of moving that up - as it's in a nice place and sounds like easier work).

That way, people don't have to choose between joining a waitlist or finding another book, but can do both.

**Comment by mekarpeles** [comment]
Folks, please see the #684. We are in the middle of re-designing our books page so there is **only** 1 page (not works v. editions). As a result, patrons will **always** see every available copy of the book. And we **already** show a carousel of related book on both the editions and works page.

Closing this issue as a duplicate.

It is a requirement of `canonical books page` to make it obvious when another edition (other than then one you're on) is available. And @cdrini and I agree this same functionality will happen on search result pages, lists, etc (i.e. whether a work or edition is being shown, we'll let them know how many **available** copies there are.

**Comment by mekarpeles** [comment]
P.S. as per @guyjeangilles's comment, @bfalling also has voted for us to move up our book page carousels

**Comment by BrittanyBunk** [comment]
What if when people see the 'join waitlist' and 'preview' buttons, there can be a 'related' button there that can bring people to the carousel below? The issue is that when I go, I don't really see an alternative to waitlisted books, and that's the issue.

However, after the IA changed the borrow to be 1 hour or 14 day options, I don't see waitlists anymore, so I don't see this as an issue luckily.

**Comment by LeadSongDog** [comment]
Before joining the waitlist, other editions of the same work should be offered in preference to similar works. However we get there, situations like this should never arise:
![440931EC-E5E2-4543-B2F6-0F7C3401274B](https://user-images.githubusercontent.com/11435431/139681024-4a37072d-b095-4573-af4d-6a41e3c5068e.jpeg)

**Comment by BrittanyBunk** [comment]
@LeadSongDog that's exactly why I wrote this issue - because it's really sad to see a waitlist of 80 people for the same book while they're missing out on all reading and all the others.

yes, but more than that. The preference order should be:
1) different versions of the same one (editions, translations, different authors, etc.)
2) a review, sparknotes-like version, parody, etc. (so they get to know it without reading it)
3) books that come after it in the series
4) books that come before it in the series
5) books similar to it (in topic, like if it's about drawing - offer another drawing book)
6) books others that read this one liked
7) lesser visited books in the Open Library to read while they wait (as @mekarpeles explained how a lot of the Open Library is underutilized and this can solve that issue)
8) offer to read other books that they already got on loan or to search for other books in the meantime or just wait

Not sure if all these would be helpful, but I'm hoping these ideas will inspire something
