### ISSUE TITLE
Unexpected ERROR : ITEM_WAITING_FOR_CLAIM

### ISSUE THREAD

**Issue by ScarlettRed** [internetarchive/openlibrary#3201]
I was getting this error while accessing a particular book with URL: https:www.archive.org/stream/chroniclesofnar00Iewi?ref=ol#page/n5

![tempsnip](https://user-images.githubusercontent.com/45791528/76839865-49a43680-685c-11ea-9ebf-040848b805d6.png)

however, later on upon some further digging up, I found out that this book is already loaned by someone. I think this must be considered as an issue UI/UX wise.

**Comment by EbotFabien** [comment]
I think you had to be sent to the waiting list or less users need to be notified when books are borrowed

**Comment by mekarpeles** [comment]
This is definitely an issue, thought it needs to be passed to Archive.org staff leadership --> @bfalling

**Comment by ScarlettRed** [comment]
so, now that you have passed on this issue @mekarpeles  we don't have to work on it anymore.
