### ISSUE TITLE
Avoid showing waitlisted books in carousels

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3202]
If people are browsing, likely they want to see books that they want to read. Showing waitlisted books would take away from that. I mean, it's ok to have it there for general knowledge, but I don't think that's what people visit carousels for (then again, I'm really speaking for myself and have no knowledge of what other people use it for or if it does bother them).

I don't think it's a top priority, but is an inconvenience. It's a toss-up right now for whether to fix it or not - so it's up as a feature request.

**Comment by guyjeangilles** [comment]
I can't recall finding a waitlisted book in a carousel. @BrittanyBunk can you provide a screenshot?

**Comment by tfmorris** [comment]
I would be very surprised at this and it would indicate something fundamental broken since all of the queries include an explicit `AND loans__status__status:AVAILABLE`. Of course there's always a race window where you and another user both get shown the same volume and they decide to borrow it before you do.

**Comment by BrittanyBunk** [comment]
@guyjeangilles Yes - I do see them. They're in the subject carousels, not the front page - which is why you might've not seen them - they're hidden. I mean, it's ok to have them there - it just shouldn't be the first ones that are visible

**Comment by BrittanyBunk** [comment]
couldn't replicate

**Comment by BrittanyBunk** [comment]
New issue is shown https://github.com/internetarchive/openlibrary/issues/3248

**Comment by BrittanyBunk** [comment]
Due to the availability of books now, I don't see waitlisted books anymore. Yay!
