### ISSUE TITLE
More user-friendly 'unique visitors' stats page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3213]
Continuation of issue #2783, part 1 of split
https://openlibrary.org/ at the bottom of the page shows 'unique visitors'. When clicked on, it shows: https://archive.org/stats/
However, the information there is more for developers. What really is needed is a stats page that is for users. Something that shows up with a Google Analytics style (i.e. infographic style). My proposed metrics for 'unique visitors':
- **demographics**: location, age, etc.
- **means**: device, operating system, browser, where do they come from (is it typed directly into the browser or from a search engine, i.e. 'aquisition'), etc. (service provider, screen resolution, etc.)
- **behavior**: time of day, how long people stay on the site, which pages they go to, how often they come back (i.e. 'user retention'), timeline (how many people on which days), etc.

Bonus: info for a user: like how long it takes to load the front page or a book page (i.e. edition or work page)

**Comment by mekarpeles** [comment]
Related to #3214

**Comment by mekarpeles** [comment]
For now, these type of stats are either internal or, because we anonymize patron analytics, some of these questions we don't have great answers / presentations for.
