### ISSUE TITLE
Reading log stats appear too faint on editions page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3219]
The counts of "Want to Read"/ etc. appear too faint on the editions page. They should be black.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/77131439-07cce900-6a32-11ea-943c-cd908e4dcc20.png)

### Relevant url?
e.g. https://openlibrary.org/books/OL26673217M/A_Mind_for_Numbers

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@Aj-KamaL

**Comment by Aj-KamaL** [comment]
@cdrini Does #3220 seem good enough? 
Or we can also highlight the background of the text since the information seems important to the user? Let me know.

![image](https://user-images.githubusercontent.com/23471306/77139709-097fc680-6a9d-11ea-8208-57a29c06d223.png)
