### ISSUE TITLE
Preload key requests

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3221]
Google PageSpeed and Lighthouse Audit reveal that Open Library isn't prioritizing fetching resources that are currently requested later in page load causing to significantly increase the load time.

**Pages:**

- [ ] Homepage

#### Home Page delay:
![Screenshot from 2020-03-20 12-59-28](https://user-images.githubusercontent.com/31198893/77143951-aa28b300-6aaa-11ea-8ff1-4c67a192d441.png)

### Relevant url?

https://developers.google.com/speed/pagespeed/insights/?url=openlibrary.org

### Proposal & Constraints

Consider using `<link rel=preload>` to prioritize fetching resources that are currently requested later in page load.

### Stakeholders

@tabshaikh

**Comment by ishank-dev** [comment]
So are we supposed to just add  ``<link rel=preload>`` in all the relevant anchor tags?

**Comment by tabshaikh** [comment]
@ishank-dev Not all we need to find the links which are a bottleneck in performance and then preload those.

**Comment by ishank-dev** [comment]
How do we know whether they are a bottleneck in performance?
These are the following files which contains  ``<link>`` tag 
```
./openlibrary/templates/viewpage.html
./openlibrary/templates/site/head.html
./openlibrary/templates/books/custom_carousel.html
./openlibrary/templates/type/edition/view.html
./openlibrary/templates/widget.html
./openlibrary/templates/lists/feed_updates.html
./scripts/2009/01/olpc/src/embed.html
./scripts/2009/01/olpc/src/index.html
./vendor/js/jquery/jquery-1.11.0.min.js
./vendor/js/flot/examples/percentiles.html
./vendor/js/flot/examples/tracking.html
./vendor/js/flot/examples/turning-series.html
./vendor/js/flot/examples/index.html
./vendor/js/flot/examples/visitors.html
./vendor/js/flot/examples/image.html
./vendor/js/flot/examples/navigate.html
./vendor/js/flot/examples/resize.html
./vendor/js/flot/examples/annotating.html
./vendor/js/flot/examples/selection.html
./vendor/js/flot/examples/stacking.html
./vendor/js/flot/examples/thresholding.html
./vendor/js/flot/examples/interacting-axes.html
./vendor/js/flot/examples/zooming.html
./vendor/js/flot/examples/graph-types.html
./vendor/js/flot/examples/multiple-axes.html
./vendor/js/flot/examples/realtime.html
./vendor/js/flot/examples/ajax.html
./vendor/js/flot/examples/basic.html
./vendor/js/flot/examples/setting-options.html
./vendor/js/flot/examples/time.html
./vendor/js/flot/examples/interacting.html
./vendor/js/flot/examples/symbols.html

```

**Comment by tabshaikh** [comment]
slick.woff are now loading as they should with preload, therefore, closing this issue
![Screenshot from 2020-05-12 13-16-18](https://user-images.githubusercontent.com/31198893/81653789-ca457480-9452-11ea-98ed-aac45e14ab28.png)
