### ISSUE TITLE
Borrow Count homepage graph should redirect to /stats

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3229]
@scarlettred would you be willing to open a PR to fix this?

> I also checked only today. The e-books burrowed graph is working correctly now, but there is one more issue related to this. The link given with the burrowed graph is redirecting to some unexpected page redirecting page's URL is: https://openlibrary.org/subjects/in_library#ebooks=true This page doesn't show any information regarding e-books burrowed.

_Originally posted by @ScarlettRed in https://github.com/internetarchive/openlibrary/pull/3217#issuecomment-601560658_

**Comment by ScarlettRed** [comment]
@mekarpeles sure thing! I will open a PR to fix this issue.

**Comment by mekarpeles** [comment]
I looks like this has been implemented #3307
