### ISSUE TITLE
Schema.org tags for authors

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3231]
When we search for **books by \<name\>**  [https://www.google.com/search?q=books+by+mark+twain+openlibrary&oq=books+by+mark+twain+openlibrary](https://www.google.com/search?q=books+by+mark+twain+openlibrary&oq=books+by+mark+twain+openlibrary) we are shown a search result as shown below but the author does not have schema markup so my proposal is to add `person` schema.org tag to the author. 

***Opportunity:*** It could have search engine consequences for 8 million of our author pages.

@tfmorris:
As @seabelis pointed out on Slack, not all authors are people, but we can probably safely tag anyone with a birth or death date. In addition to Person.birthDate and Person.deathDate, other markup which could be added includes Thing.alternateName for each of the AKAs, Thing.sameAs to link to Wikidata.

The works on the page are already tagged as schema.org Books, but they could additionally be decorated with CreativeWork.author, CreativeWork.about (ie subjects), CreativeWork.publication, CreativeWork.inLanguage, etc.

![Screenshot from 2020-03-21 11-14-43](https://user-images.githubusercontent.com/31198893/77220430-eec55480-6b65-11ea-8426-df60ac0c570c.png)

### Stakeholders

@tabshaikh

**Comment by tfmorris** [comment]
As @seabelis pointed out on Slack, not all authors are people, but we can probably safely tag anyone with a birth or death date. In addition to Person.birthDate and Person.deathDate, other markup which could be added includes Thing.alternateName for each of the AKAs, Thing.sameAs to link to Wikidata.

The works on the page are already tagged as schema.org Books, but they could additionally be decorated with CreativeWork.author, CreativeWork.about (ie subjects), CreativeWork.publication, CreativeWork.inLanguage, etc.

**Comment by BrittanyBunk** [comment]
I do understand that people do like to add schema with SEO - but I feel sometimes it creates clutter. To me - it's just too much to read. It already has the novel in the description and people will click the link to see the rest. I don't see a need to add it to the search results (a place where it needs to be quick reading/action to get to where one needs to be).

**Comment by tfmorris** [comment]
Clutter? All schema.org markup is invisible.

**Comment by tabshaikh** [comment]
@BrittanyBunk are you referring to clutter in terms of UI changes it will bring to the search results>

**Comment by mekarpeles** [comment]
@BrittanyBunk please make sure you really understand the issue before weighing in and providing feedback. In this case, the schema tags only appear in the underlying markup and are not visible ot users (other than how google decides to augment their experience).

Feel free to ask a clarifying question.

**Comment by BrittanyBunk** [comment]
@tabshaikh yes! It just is showing too much of what's already there. I think one book's ok, but it shouldn't say 'books by _author". That line is also inessential, as we already know the author on the title of the link.

@mekarpeles I've seen schema used on a back-end before (I think?), and it's a lot and some of it doesn't get used, but is there just in case - so even if it's cluttering on the back-end, it's needed there for potential use - even if it's not in use at the moment.

**Comment by mekarpeles** [comment]
@BrittanyBunk schema.org tags are not displayed visibly on a web page to the end-user. They are specifically used to provide context and semantics to **search engines**.

Please take a look at this video: https://www.youtube.com/watch?v=9HvMv_1zG2s 

An important way that Google knows one of our pages is about a "book" or about an "author" is if we **tell** Google. And this is done by adding specific html tags to our markup.

Let's please move forward with this issue. It's a very easy metadata fix and it could have search engine consequences for 8 million of our author pages.

**Comment by tabshaikh** [comment]
Thanks @mekarpeles @tfmorris for the feedback, updated the issue accordingly :)

**Comment by devarshigoswami** [comment]
Hello There! can I be assigned this task?

**Comment by tabshaikh** [comment]
@devarshigoswami sure you can go ahead if you need any help you can ping me :)

**Comment by devarshigoswami** [comment]
@tabshaikh  I understand Openlibrary is using **microdata** schema. Do I need to add it specefically 
Also ,

**Comment by devarshigoswami** [comment]
@tabshaikh , please respond..

**Comment by jdlrobson** [comment]
> Do I need to add it specifically to Mark Twain's' author page or in templates in general?
Templates in general.

**Comment by tabshaikh** [comment]
templates in general I would say

**Comment by nk4456542** [comment]
@tabshaik, I would like to work on this, can you please tell me, Is `openlibrary/macros/SearchResultsWork.html` this the file where we need to add the Person schema 

https://github.com/internetarchive/openlibrary/blob/1e31269adcc7118642e591e9dcfc04f400bdf658/openlibrary/macros/SearchResultsWork.html#L40

Can you please confirm If am moving in the right direction, is this the line where we need to add Person.birthDate, Person.deathDate, and other schema mentioned in the issue description? I was a bit confused, so thought to ask. Thank you

**Comment by tabshaikh** [comment]
Hi @nk4456542 Schema should be added in this file https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/author/view.html
The schema tags mentioned in this message would suffice https://github.com/internetarchive/openlibrary/issues/3231#issuecomment-602078002 You could also propose additional schemas which are relevant to our content and you could use this site as your reference https://schema.org/author

**Comment by nk4456542** [comment]
Thank you @tabshaikh. Will start working on this
