### ISSUE TITLE
Ability for Librarians to remove subjects

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3233]

**Comment by tfmorris** [comment]
Subjects are not first class objects, so there's no record to remove. They are managed implicitly as part of the search indexing of works. When no edition/work references a subject, it should automatically disappear (when subject indexing is not broken as described in #1896). When we have implemented #2819, we'll likely have the full range of merge, edit, delete, etc operations as we do for other object types.

**Comment by BrittanyBunk** [comment]
@mekarpeles Idk why this is an issue - as librarians can remove subject tags so that if all the books are removed, the subject no longer exists. Maybe this should say 'subject pages', as it's possible for them to already do this in a way through tags.

**Comment by BrittanyBunk** [comment]
I think what's better is for a way for librarians to organize subject pages better where on a subject page, librarians can list books that fit under the category and then those books would then get a subject tag automatically added to them once a librarian adds the book in a subject.

**Comment by mekarpeles** [comment]
This issue is better phrased as, enable librarians to merge subject tags + bulk remove & add subjects (across works). Tagging in #7486 and closing.
