### ISSUE TITLE
/home missing meta `description` for keywords

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3234]
Along with Brittany, I carried out a keyword search audit for various search engines and one key finding was that /home is missing meta description for keywords

https://docs.google.com/spreadsheets/d/1THNPyFpJ2uxwBOAmRNrQQrzfQxMpk37HwA3ohM6u0oM/edit#gid=367130090

### Proposal & Constraints

Adding relevant meta descriptions tags according to priority keywords in the spreadsheet

### Stakeholders

@tabshaikh

**Comment by tabshaikh** [comment]
@cdrini @hornc @tfmorris If you would like to add something to this issue would be helpful :)

**Comment by ishank-dev** [comment]
I can help add the required keywords, it would be great if someone could direct me to the right header file in templates.

**Comment by tabshaikh** [comment]
Thanks for helping out in this :) if you open a pr I would be happy to get it reviewed and merged
