### ISSUE TITLE
Changing http to https

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#324]
The code still contains hundreds of mentions of http long after the switch to https should have been done. In many cases the target will correctly resolve and redirect, but this should not be accepted as the default behaviour. A short list of examples (please extend as found):

192 hits on https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=http%3A%2F%2Fopenlibrary.org
7 hits on https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=http%3A%2F%2Fworldcat.org&type=Code
116 hits on https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=http%3A%2F%2Farchive.org&type=Code
67 hits on https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=http%3A%2F%2Fwww.archive.org&type=Code
43 hits on https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=http%3A%2F%2Floc.gov&type=Code

**Comment by mekarpeles** [comment]
I can tackle this, thanks!

**Comment by LeadSongDog** [comment]
Perhaps https://github.com/internetarchive/openlibrary/blob/2bcb7d9866f00c4f7cfaf4fd23b87f72850b94bf/openlibrary/plugins/openlibrary/home.py#L86 would be a good starting place?

**Comment by mekarpeles** [comment]
Updated in all the obvious places I could find

**Comment by LeadSongDog** [comment]
There's still a problem at master / openlibrary / openlibrary / macros / databarWork.html (see line 10 et seq.)
It should be e.g. 
 https://www.worldcat.org/search?q=XXX&qt=owc_search 
vice 
 http://www.worldcat.org/search?q=XXX 
to avoid exposing the user's interest (and possibly zipcode) to a MITM

**Comment by jack17529** [comment]
If it's merged then please close.

**Comment by LeadSongDog** [comment]
There are still many http uses elsewhere. Sure the three issues #422 #440 #441 might close, but not #324. Check the queries above.

**Comment by jack17529** [comment]
@LeadSongDog sounds too easy should I work on it ?

**Comment by mekarpeles** [comment]
@jack17529 -- sure, give it a go

**Comment by LeadSongDog** [comment]
Many of these http: links are still seen in the code. The closure was, I think, premature.
