### ISSUE TITLE
Add project_gutenberg id as bibkey for Books API

### ISSUE THREAD

**Issue by jspizziri** [internetarchive/openlibrary#3240]
### Question

Hello, I'd like to query the Open Library API for book data based on the `project_gutenberg` id (I'm seeing in the [documentation](https://openlibrary.org/dev/docs/api/books) that you store that as an identifier). Is there a way to query your API by the PG id, or more generically by the `identifiers`? I tried a couple of things with no success.

If it's not possible, is this something that would be considered as a potential feature addition? Thanks!

**Comment by guyjeangilles** [comment]
@jspizziri From the documentation, the acceptable identifiers to query with are
>bibkeys
>
>List of IDs to request the information. The API supports ISBNs, LCCNs, OCLC numbers and OLIDs (Open Library IDs).
>
>ISBN
>Ex. &bibkeys=ISBN:0451526538 (The API supports both ISBN 10 and 13.)
>
>OCLC
>&bibkeys=OCLC:#########
>
>LCCN
>&bibkeys=LCCN:#########
>
>OLID
>&bibkeys=OLID:OL123M
`project_gutenberg` ids can be returned but not queried with, unfortunately.

@hornc @cdrini @mekarpeles can answer how feasible it is to add this as a query-able bibkey. I'm changing the title of this issue to reflect the change in context.

**Comment by cdrini** [comment]
Oh hi @jspizziri sorry for the delay, this slipped past us! Here is how you fetch an edition given a project gutenberg id: http://openlibrary.org/query.json?type=/type/edition&identifiers.project_gutenberg=07787&*

**Comment by jspizziri** [comment]
Thanks for the response!

**Comment by cdrini** [comment]
Thank you for your patience! 😊
