### ISSUE TITLE
Better subject results/page consistency

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3246]
subjects results page says 'books' and the subject pages show 'works'. This should be more consistent.
![image](https://user-images.githubusercontent.com/55302685/77276002-d8f38480-6c76-11ea-85aa-89111975e2ca.png)

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/3248#issuecomment-602397102
