### ISSUE TITLE
Delete ~400 spammy subjects from production Solr

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3247]
Because subjects are not being indexed (#1896), spammy subjects continue to exist even if the works that caused them to be created have been deleted.

I've curated a list of 398 candidates that we can manually delete using the Solr console, after review. They include ones which were specifically the subject of customer complaints to @seabelis 

### Relevant url?
https://openlibrary.org/search/subjects?q=buy+abercrombie

### Proposal 
1. Review the proposed list of subjects to make sure I didn't accidently include any valid ones by mistake.
2. Convert the list of document IDs to a Solr XML update document that we can feed to the production Solr
3. Have someone with access to the production Solr console submit the update to delete the subjects.

### Related files
[OL-Subjects-to-delete.txt](https://github.com/internetarchive/openlibrary/files/4366932/OL-Subjects-to-delete.txt)

### Stakeholders
@seabelis @cdrini

**Comment by BrittanyBunk** [comment]
@seabelis maybe this can be moved to the librarians repository?

**Comment by seabelis** [comment]
> @seabelis maybe this can be moved to the librarians repository?

I think only admins have access to the Solr console, so no it should not be moved.

**Comment by seabelis** [comment]
Please include these as subjects to remove/block. 
https://openlibrary.org/subjects/sale_books
https://openlibrary.org/subjects/non-classifiable
https://openlibrary.org/subjects/bargain_books

**Comment by cdrini** [comment]
Subjects are/have been re-indexed during full re-indexes; there are some subjects in the data that need to be removed eg https://openlibrary.org/works/OL15323828W/buy_abercrombie_clothingCoat_The_two_Pertaining_to_Guys_in_addition_to_Younger_Boys

**Comment by cdrini** [comment]
Closing ; a random sampling of those subjects yields no results. I imagine the full reindex removed the spam from solr.

**Comment by tfmorris** [comment]
I've reverted the edition and work mentioned by @cdrini in https://github.com/internetarchive/openlibrary/issues/3247#issuecomment-1063436509
