### ISSUE TITLE
Prioritize availability of books on subject carousels.

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3248]
Right now, there's a mix of the availability of a book:
![image](https://user-images.githubusercontent.com/55302685/77277009-3be61b00-6c79-11ea-863c-8a4e8efb1cd5.png)
I propose to have a better order, so that people don't scroll through as much to get to what they need (from most needed to least):
1) read
2) borrow
3) join waitlist (if that does appear)
4) no ebook available
Example of the image rearranged:
![image](https://user-images.githubusercontent.com/55302685/77277215-b1ea8200-6c79-11ea-8d8f-ae85bcad8114.png)

**Comment by mekarpeles** [comment]
Closing because this will be resolved by #2375 and #2984 (which are in-flight).
