### ISSUE TITLE
waitlist - users getting email when item is not available for them

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#325]
Users report getting email saying item is available and then clicking through and item is shown as not available and they are shown as still being on the waitlist (on their Loans page). Checking with users to make sure
- they are clicking within the time window
- they are logged in to OL when they see this message

Could maybe use a debugging tool to help determine what is happening (user error or OL/IA error)

**Comment by mekarpeles** [comment]
I think this is no longer an issue? @JeffKaplan? Going to assume this is safe to close as the emails and infrastructure for waitlist email sending is handled by archive.org now
