### ISSUE TITLE
Improved book category carousel

### ISSUE THREAD

**Issue by the-nine-tail** [internetarchive/openlibrary#3250]
Current book category carousel is very simple, the carousel UI should be improved for better user interaction and design.

Before:
![before](https://user-images.githubusercontent.com/62152426/77290269-d5f1a600-6d01-11ea-9084-70bb672baf12.png)

After:
![after](https://user-images.githubusercontent.com/62152426/77290279-dab65a00-6d01-11ea-9f4b-b20898439526.png)

OnClick:
![click](https://user-images.githubusercontent.com/62152426/77290663-a000f180-6d02-11ea-9eec-fee39b3ac6e2.png)

**Comment by guyjeangilles** [comment]
@the-nine-tail mind being assign of this issue, since you proposed a PR?

**Comment by tfmorris** [comment]
I'm not sure I consider making everything a button an improvement. If they are going to be wrapped in visible buttons, they need more room/margin at the bottom.

**Comment by the-nine-tail** [comment]
Not a problem

**Comment by jdlrobson** [comment]
I don't think we should do this. While I'm also not sure I consider this an approvement, this code should be considered frozen. 

We will likely need to move away from the slick code in future given #2809

In general our frontend is extremely unstable right now and what would be helpful is fixing bugs and removing code not adding things.
