### ISSUE TITLE
Error using /addbook to add a new edition

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3252]
It looks like general `Add Book` and `add another edition` is failing for works like
https://openlibrary.org/works/OL4104767W/The_Moon_Pool. I tried to add another edition with `ocaid` `moonpool00merrgoog`
and it failed w/ the attached error.

### Evidence / Screenshot (if possible)

![2020-03-23-121836_1600x900_scrot](https://user-images.githubusercontent.com/978325/77355467-b9556e00-6d01-11ea-804f-5790ce2c3846.png)

### Relevant url?

both /addbook or https://openlibrary.org/works/OL4104767W/The_Moon_Pool add edition from works page.

### Steps to Reproduce

1. go to /addbook or to the work page and click add another edition
2. publisher "G.P. Putnam's sons", published 1919
3. before submitting, consider inspecting element and in the `action=""` param of the form, add `action="?debug=true"`

* Actual: 
* Expected: 

### Stakeholders

@hornc

**Comment by tfmorris** [comment]
When I try it, I get a 503 from Solr:

http://ol-solr2:8983/solr/select?q=publisher%3A%22G.P.+Putnam%27s+sons%22+AND+publish_date%3A%221919%22+AND+key%3A%22OL4104767W%22&start=0&wt=json&q.op=AND

If it's not a configuration error, perhaps rebooting it would help.

**Comment by tfmorris** [comment]
I was able to add this edition: https://openlibrary.org/books/OL27932769M/The_Moon_Pool
so it seems that this was an intermittent problem, but the error reporting could definitely be improved.

**Comment by tfmorris** [comment]
Here's the stack trace from when it did fail a few days ago:

![Screen Shot 2020-03-27 at 5 13 36 PM](https://user-images.githubusercontent.com/82178/77801032-6b689f00-704e-11ea-9f98-9b733de5ce42.png)

**Comment by cdrini** [comment]
See related PR: https://github.com/internetarchive/openlibrary/pull/2924
And related user-reported issue: #3340

**Comment by cclauss** [comment]
I was able to add and delete and edition with no issues.
