### ISSUE TITLE
Improving Signup Process 

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3256]
Improving the Signup Process should be done in 2 parts to improve the conversion of people who visit OL first time -> use it regularly. The first part which is on Openlibrary is too remove the bugs in the signup process ie. we have seen a shocking 1/5 of users (i.e. 500 a day) are hitting issues when creating an account (either email or username taken, or captcha broken). The issues related to that are:

https://github.com/internetarchive/openlibrary/issues/1433 epic which contains 2 tasks
1. #2053 - update backend API endpoints
2. #2055 - Add real-time field validation for email, username, password to Account Registration Form front-end

The second part involves making signup a single click process ie. adding various o-auth signup like using Google GitHub … to ease up our signup. Research shows that 86% of users report being bothered by having to create new accounts on websites, 77% of users believe social login is a good registration solution and 92% of users will leave a site instead of resetting or recovering login info. [https://cxl.com/blog/social-login/#9-the-next-generation-of-social-engagement](https://cxl.com/blog/social-login/#9-the-next-generation-of-social-engagement)
Also, stats on OL show that OL has 10M unique IP's but only 88K new members so improving the signup process would greatly help us in converting new users to member's
![Screenshot from 2020-03-24 16-16-53](https://user-images.githubusercontent.com/31198893/77417220-19740f00-6deb-11ea-9b03-fac0d35223d5.png)
Moreover, there would be  1M or 1.5M uniques for the month as pointed out by @tfmorris that we currently show sum(counts), not count(union(ip addresses))) in /stats.

### Proposed Initial design:

![new-signup](https://user-images.githubusercontent.com/31198893/77419334-3a8a2f00-6dee-11ea-949a-092b40f8e51d.png)

### Stakeholders

@mekarpeles @tabshaikh

**Comment by tfmorris** [comment]
I'm all for improving the signup process, but we should set some realistic goals for metrics. Not all unique visitors are conversion candidates. Also you're quoting 28 day numbers, not daily numbers, and I bet the 28 day "unique" visitor counts is wildly overstated since the recent daily counts are ~600K (I suspect it's sum(counts), not count(union(ip addresses))).

Using recent daily counts (Mar 24), we see 597,434 unique IPs, many probably representing visits from our 3.2M users, and 8112 new users.

**Comment by tabshaikh** [comment]
Okay, I did not suspect that it sum(counts) maybe we can ask @mekarpeles about it?

**Comment by BrittanyBunk** [comment]
Just posting the before, as I don't sign up for my account anymore, so idk what the site looks like: 
![image](https://user-images.githubusercontent.com/55302685/77672940-c0b98900-6f46-11ea-978c-442b3489333a.png)

**Comment by BrittanyBunk** [comment]
There are obvious pros/cons to this: 
pros
- more users
- better integration with one's other accounts for easy signing in and remembering which websites they're on (so they don't need to bookmark as much)
cons
- privacy (but if people worry about privacy, then they have options to avoid that)
- takes effort to add it in
- is a lot of stuff on one page, that people might get confused (by which one should say choose an option maybe)
- how the account is able to integrate with the entire site and the IA could get tricky - especially with the IA (as the IA might have to add that too)

Overall, I feel the pros outweigh the cons - if it means more users

**Comment by tfmorris** [comment]
> Okay, I did not suspect that it sum(counts) maybe we can ask @mekarpeles about it?

Sure, if you want, but I don't see any way that 450K average daily visitors is going to add up to 12M visitors for the month. Perhaps 1M or 1.5M uniques for the month, but it's implausible to think that an entirely different cohort visits each day.

**Comment by mekarpeles** [comment]
related tasks are complete
