### ISSUE TITLE
Ability to add reviews and other additional features

### ISSUE THREAD

**Issue by vidhi-mody** [internetarchive/openlibrary#3259]
### Problem description

- Requesting a short review/ thoughts on a book from existing users. While selecting which book to read next, readers might face difficulties in deciding if a particular book is the right fit for them. Reviews can help in the decision making process.
- To improve user experience an option to change modes (light/dark) should be considered. 
- To gain funds to add books that have not been obtained yet, a more eye-catching option to donate can be added

### Proposed Solution

- Display detailed ratings given by the users below the book cover. Addition of a new field where along with submitting rating users can also submit a short review (word count can be limited) of the book. A carousel at the end of the book description displaying all reviews can be added to all existing pages
- A toggle button can help user switch modes. Dark Reader can be used for implementation
- A carousel displaying relatable/general quotes along with a Donate button can be added to the existing homepage. On clicking the donate button the users will be redirected to a new payment page where they can enter the amount they wish to donate along with their card details.

### Alternatives

- The reviews can be displayed using carousel cards (A group of 3 reviews at a time)
- Additional methods of switching modes can be explored
- Other interactive means to gain user's attention instead of the carousel

### Additional context

- Reviews can help determine popularity of each book. 
- Addition of dark mode can significantly improve user experience
- Improving visibility is the best way to raise funds

### Proposed additions to existing UI

![proposed](https://user-images.githubusercontent.com/49282105/77469218-beffa080-6e34-11ea-9eec-901dd2f9e691.png)
![reviewss](https://user-images.githubusercontent.com/49282105/77469234-c626ae80-6e34-11ea-83c5-78e5106da51c.PNG)
![rating](https://user-images.githubusercontent.com/49282105/77469247-c9ba3580-6e34-11ea-8dbb-4d224d38cb67.PNG)
![proposed2](https://user-images.githubusercontent.com/49282105/77469280-d50d6100-6e34-11ea-9583-01f136963953.png)
![dark mode](https://user-images.githubusercontent.com/49282105/77469295-d8a0e800-6e34-11ea-8800-04e6f9d2773c.PNG)
![light mode](https://user-images.githubusercontent.com/49282105/77469304-dc346f00-6e34-11ea-8387-8f4c7df171c6.PNG)
![proposal](https://user-images.githubusercontent.com/49282105/77469319-e0f92300-6e34-11ea-8b8d-9c1525e5c7a9.png)
![donation banner](https://user-images.githubusercontent.com/49282105/77469331-e6566d80-6e34-11ea-99f7-ccccc4418cdf.PNG)
![donation](https://user-images.githubusercontent.com/49282105/77469337-e8b8c780-6e34-11ea-91b7-314fa2042ccc.PNG)

**Comment by guyjeangilles** [comment]
ec4c81a37e57fe98a97e28c60b63ebff72ef410c introduced book reviews (based on the code it looked like external and internal review). #1830 removed the code because apparently, the feature was never put into place. Based on the PR comment thread, the review feature could back.

**Comment by vidhi-mody** [comment]
So has the code already been implemented and is just left to be integrated? Sorry got a little confused here!

**Comment by vidhi-mody** [comment]
Also, an addition to this feature can be a chat bot which recommends books of a particular genre/category based on user ratings

**Comment by BrittanyBunk** [comment]
I would not like a carousel, but would prefer it to be like most other review pages, where someone sees the average rating of a book and when clicked on, it shows all the reviews there. A carousel would be too much to look at.

**Comment by BrittanyBunk** [comment]
I would say that the donation banner should be with the sponsor book banner - as it's already becoming too much at the top - asking for money when it's a 'free' site - so if I see too many banners and not enough material, it would make me hesitant to proceed with it.

**Comment by BrittanyBunk** [comment]
Light/dark mode is cool and a necessity, but I worry about what happens when they visit a book to read and the glare from that hurts one's eyes. If there's a 'dark' mode, then the books should be placed in dark mode too. If it's not, then it'd be good to warn those in dark mode that the books they're going to may have a lot of glare because it's not able to be converted. I think epub does well on conversions, so it's preferable to lead them to an epub version of a book, rather than a PDF of it.

**Comment by BrittanyBunk** [comment]
Other than that, the stars for ratings looks good, as well as the donation page formatting.

**Comment by vidhi-mody** [comment]
So you suggest that when clicked on the rating reviews of all the people who gave that particular rating are displayed?
If that's the case then where the reviews will be displayed need to be figured out. A list below the book description may not look that great

**Comment by BrittanyBunk** [comment]
![image](https://user-images.githubusercontent.com/55302685/77720821-3f91de80-6fa6-11ea-8857-3b86a266fdef.png)
is what I'm talking about. When a person clicks on the number of reviews, then they're taken to a page, to the carousel pops out. I personally don't like viewing everyone's rating of a book, as it conflicts with my thoughts of what the book's like - which really takes away from me viewing the site. This is me - I'm not speaking for anyone else.

**Comment by laoshaw** [comment]
some books are so dark and my eyes just can't read them, can we have different theme(light mode, night mode ,etc)

**Comment by BrittanyBunk** [comment]
> some books are so dark and my eyes just can't read them, can we have different theme(light mode, night mode ,etc)

@laoshaw have you tried to turn up the brightness on your computer?

**Comment by mekarpeles** [comment]
This issue has a lot of valuable pieces, thank you for investing the time and energy and sorry it's taken so look to give it a careful review!

The feature requests, as I can tell, are:
1. Book Reviews -- we're piloting this on thebestbookon.com: https://github.com/Open-Book-Genome-Project/TheBestBookOn.com/pull/67 (a place where patrons can use their Open Library accounts to safely make reviews without affecting the Library/Catalog feel). These may some day get merged depending how the pilot goes.
2. Dark Mode -- this is a reasonable request (I imagine a lot of people would appreciate it existing. It's not a top priority for our 2021 roadmap but if a member of the community wanted to implement it, we'd be happy to review and help it become a reality).
3. Star ratings popup -- I think @BrittanyBunk's proposal seems like a good one (use hover/click capabilities to learn more about star ratings). Happy for an issue to be opened for this (it's a lower priority).
4. Donations banner -- we're deferring to Archive.org for their donation banner so I think it makes sense to say "no" to this one.

I welcome new, specific issues being created for 2 & 3.

This specific issue is too broad (proposal) and I am going to close it as "proposal having been reviewed"
