### ISSUE TITLE
Have an Open Library specific donate page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3260]
Right now the donate page redirects to https://archive.org/donate/?platform=ol. However, various organizations outside of the Open Library (MIT is an example) tend to allow for donating to a specific cause within them. So it would be beneficial for the donate page to donate to an Open Library specific fund pool of the Internet Archive, because the Open Library is a project of the IA and is growing enough to have its own page (plus, it seems more professional). This is especially true now that there's a Book Sponsorship Program. The donate page would show books to sponsor, but also funding specifically for the Open Library, so funds could go to Open Library activities, like maintenance and book sponsoring for books that aren't getting the sponsorship they need. It can also include a link to the volunteer page for those who can't donate their money, but can donate their time. @tabshaikh

**Comment by guyjeangilles** [comment]
I'm not sure if one can donate to the Open Library directly. @mekarpeles can you provide insight.

**Comment by tfmorris** [comment]
Yes, that would be a better way of doing things, which we've discussed in the past, but it's never gone anywhere. You are donating to Open Library. You're donating to Internet Archive and they spend the money however they want -- mostly not on Open Library.

**Comment by mekarpeles** [comment]
I don't think we want process funds on openlibrary.org.
