### ISSUE TITLE
Have recordings of community meetings

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3261]
A lot of people don't or can't attend community meetings, yet a lot of critical notes are said during then that are good to reference later that would provide context for the notes. So having a record of meetings in an archive would help to document what is said there for people who need to work with it or for reference years later (maybe to catch someone up in the organization's happenings). It should be acceptable to do, as the meetings are public ones.

**Comment by guyjeangilles** [comment]
Archive is on [the Wiki](https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes), specifically in a [Google Doc](https://docs.google.com/document/d/16eAABOSLrmCbOkRbwVXzis2x4dz2gEQWJsXK-crDCqg/edit#)

**Comment by tfmorris** [comment]
Real-time synchronous meetings aren't scalable for a global volunteer organization anyway. We should strive to do as little as possible that way and instead focus on using the asynchronous collaboration tools that are available through Github, Google Docs, etc.
