### ISSUE TITLE
Update Pillow in production environment to 6.2.2

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3262]
Currently our version on prod is 5.3.0. I was planning to do this as part of https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-03-24 , but didn't realize it was a major version bump, so creating a separate issue to do this. I believe this is only used in ol-covers1, but is likely installed everywhere.

**Comment by cclauss** [comment]
What is the next step?

**Comment by cclauss** [comment]
@cdrini Is this closed at https://github.com/internetarchive/openlibrary/blob/master/requirements_common.txt#L10-L11

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/blob/master/requirements_common.txt#L15-L16
