### ISSUE TITLE
Bad UI of /home/lists page

### ISSUE THREAD

**Issue by ScarlettRed** [internetarchive/openlibrary#3264]
In addition to #3070 
As shown in the screenshot the /home/lists page has many spacing alignment errors. The page should be able to project a clean list of various *LISTS* created by users.

### Evidence / Screenshot (if possible)
![lists page](https://user-images.githubusercontent.com/45791528/77547690-882c9780-6ed3-11ea-90bf-cd3123abde80.png)

![lists page 2](https://user-images.githubusercontent.com/45791528/77547986-ece7f200-6ed3-11ea-917f-bf90afce87b6.png)

### Relevant url?

https://openlibrary.org/lists
### Steps to Reproduce

1. Go to open library home page
2. scroll down to *About the Library*
3. Click on the graph showing *Lists created*

* Actual: a page showing some recommendations of lists pops up with a lot of bad UI.
* Expected: expecting to see some sort of aligned way to show some already existing lists.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
1. A new page with some good spacing alignment should be made with a recommendation list of *Lists*. 
2. Some customization in the design to well define the lists n the recent activity related to the lists at the bottom of the page, as highlighted in the second screenshot above.

### Stakeholders
@mekarpeles

**Comment by jdlrobson** [comment]
@nynaalekhya do you have any interest in looking at fixing the alignment of those list items (the space marked by the blue box under Favourites) ?

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue.
My sol:
![ol sol lists](https://user-images.githubusercontent.com/64412143/103903945-98d89200-5122-11eb-9295-fbe8f6aa152f.png)
