### ISSUE TITLE
better spacing on /stats page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3270]
![image](https://user-images.githubusercontent.com/55302685/77671841-63710800-6f45-11ea-90cc-88c49fbf805e.png)
where the red line is

**Comment by ritwikchakraborty123** [comment]
can you please help me to find the particular page or the path of file where we have to make change.

**Comment by BrittanyBunk** [comment]
@ritwikchakraborty123 https://openlibrary.org/stats the spacing doesn't look like an issue today, but that's because the numbers are smaller than in this picture. The numbers could be better spaced out.

**Comment by RayBB** [comment]
Not sure what was going on back in 2020 but I can't reproduce this issue anymore even with numbers of the same size.
Closing for now.
