### ISSUE TITLE
ol-www1 issues, website unavailable, load balancing suspected

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3271]
### Summary

- **What is wrong?**

Website unusable. Open Library 503'ing, pages not loading, haproxy looked fine.

- **What caused it?**

Unknown. Increased usage and congestion in haproxy.

- **What fixed it?**

Restarted ol-web3 and ol-web4 to make sure there were no hanging processes. ol-web4 was not happy at all (possibly part of the problem). Restarted the machine and it took **far** longer than usual to reboot. Once I eliminated web heads as problematic, I moved back to `ol-www1` and restarted nginx + haproxy (not the bare metal) and service restored shortly after.

- **Followup actions:**
 

The problem seems to have started at 11:30a (according to ol-alert emails).
It was luck we were able to respond in <20 minutes. I hit openlibrary.org and noticed the problem, as opposed to checking my email. Maybe `ol-alerts` should go to slack and ping @cdrini + @mekarpeles.

### Steps to close

1. [x] Assignment: Is someone assinged to this issue? (notetaker, responder)
2. [x] Labels: Is there an `Affects:` label applied?
3. [x] Diagnosis: Add a description and scope of the issue
4. [x] Updates: As events unfold, is noteable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [x] "What caused it?" - please answer in summary
6. [x] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by mekarpeles** [comment]
Tweeted here:
https://twitter.com/openlibrary/status/1243249557728661504

**Comment by tfmorris** [comment]
I noticed two different failure modes when this was happening: 1) raw 503s all the way back to my browser and 2) the "Open Library is offline for maintenance" page. More of 1 than 2.

BTW, HA Proxy needs to be added to https://github.com/internetarchive/openlibrary/wiki/Production-Service-Architecture
