### ISSUE TITLE
Incorrect recommendations on Sponsorship page

### ISSUE THREAD

**Issue by ScarlettRed** [internetarchive/openlibrary#3275]
I tried to sponsor the books recommended on the sponsorship page, out of the first 6 books- 4 are not available for sponsorship. I know as a sponsor I would like to sponsor that book which I would like to read or sponsor, but this is a bug w.r.t. UI.

### Evidence / Screenshot (if possible)
![sponsorship](https://user-images.githubusercontent.com/45791528/77739268-37ce4a80-7037-11ea-9908-1d5286a90630.png)
![image](https://user-images.githubusercontent.com/45791528/77739313-4ddc0b00-7037-11ea-8d19-1050aa0e5920.png)
![image](https://user-images.githubusercontent.com/45791528/77739364-664c2580-7037-11ea-94a7-1aa781049f04.png)

### Relevant url?
https://openlibrary.org/sponsorship
https://archive.org/donate/?isbn=9780123694966&type=sponsorship&context=ol&campaign=pilot
https://archive.org/donate/?isbn=9781880599167&type=sponsorship&context=ol&campaign=pilot
https://archive.org/donate/?isbn=9781892213013&type=sponsorship&context=ol&campaign=pilot
https://archive.org/donate/?isbn=9780345016027&type=sponsorship&context=ol&campaign=pilot

### Steps to Reproduce

1. Go Home of OpenLibrary
2. click on 'Sponsor a book' blue button.
3. go to the recommendation list of books to sponsor.

* Actual: Links of already sponsored or books that are not yet ready to be sponsored exists.
* Expected: ALL the links of books(which are already sponsored or are not yet ready to be sponsored) shouldn't even exist on that page.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** CHROME
- **Operating system?** WINDOWS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Links of such books should be removed and the list of books ready to be sponsored should be updated regularly.

### Stakeholders
@mekarpeles

**Comment by guyjeangilles** [comment]
@mekarpeles could this be the fix to #2789 regressing?

**Comment by cdrini** [comment]
This should be fixed now; we believe it was the result of a temporary outage with our connection to Better World Books. Thanks for the report, @ScarlettRed !
