### ISSUE TITLE
Better coordination of roles and help

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3277]
There's a bottleneck in the workflow where the "[OL Team](https://openlibrary.org/about/people)" has too many issues to work on and everyone else not enough. This causes an imbalance that has a solution.

### Describe the problem that you'd like solved
Solving the imbalance in work levels due to a lack of communication and connection. Also, help more people be on the same page to work together better through synchronizing priorities

### Solution:
On the OL Team page: method to contact to work with them, list of past accomplishments, defining of current role and focus (maybe through subject tags), and ideas that: 1) one wants to see happen, 2) they are currently working on of main people there
Publicize help more: 
1) mention the GitHub page (to suggest issues) on the '[reporting a problem](https://openlibrary.org/contact?path=/help/faq/editing)' link on the home page, 
2) crowdsourcing work that needs crowdsourcing (like, but not limited to, finding duplicates) or 
3) making it possible for people to reach out better (not everyone's on Slack and some help pages, like https://openlibrary.org/help would benefit from placing the links to the [GitHub Wiki](https://github.com/internetarchive/openlibrary/wiki), [blog](http://blog.openlibrary.org/), more step-by-step and listing of specific activities on the [volunteer page](https://openlibrary.org/volunteer) (like more description on the "Designer & User Researcher" section, list how people could edit pages in the "librarian" section, etc.) (shouldn't the 2020 roadmap be here), etc. to know what's going on), 
4) make it easier to become a lead on projects, 
5) show what capabilities volunteers can do (in list form, even though it's kind of on https://openlibrary.org/volunteer - beyond roles a list of general capabilities - like being able to create new github issues or write a blog post, etc.)

- A workflow design, like Lucidchart (available on Google Drive) to show the tasks and roles of each person: it helps to know what's missing or too much so the roles can be adjusted more easily
- willingness and ability to divvy up roles more and making sure no one's too overloaded with work
- put the 2020 roadmap in a really important place for everyone to know the vision (idk - the 'vision' page, the GitHub Wiki, etc.?)
- understanding of the capabilities and limitations of each person and ability to work with it to get tasks done
- add in all the recommended changes proposed and agreed upon
- need more channels to get more people to see the content they need to get to to get to the information they need

### Additional context
This is going to help more people go on the site, be able to participate more, and more tasks will get done as a result

### Stakeholders
those who think this is a good idea, will fix it, and everyone involved in being able to make the changes necessary for this implementation.

**Comment by BrittanyBunk** [comment]
Being able to provide greater permissions to volunteers to fit their role (based on their skills and what they want to do) is something that's still being discussed. To facilitate the discussion more, I created a Google doc **that anyone could edit** to help with understanding which permissions which roles need: https://docs.google.com/spreadsheets/d/17A_sk5o6WRmS37RcxgTEhotUxSA71H4W5Gec-o-cU3M/edit?usp=sharing

**Comment by guyjeangilles** [comment]
>There's a bottleneck in the workflow where the "OL Team" has too many issues to work on and everyone else not enough. This causes an imbalance that has a solution.

I agree, but I don't think the steps outlined in this issue description are the best way to solve this. I honestly think the meat of the problem comes from:
1. A large user base and a significant amount of technical debt
2. A small dev team

>     1. mention the GitHub page (to suggest issues) on the '[reporting a problem](https://openlibrary.org/contact?path=/help/faq/editing)' link on the home page,

I actually disagree. Sending an email is a much lower barrier of entry for patron than making a Github account and reporting an issue. 

>     2. crowdsourcing work that needs crowdsourcing (like, but not limited to, finding duplicates) or

Aren't we doing this already?

>     3. making it possible for people to reach out better (not everyone's on Slack and some help pages, like https://openlibrary.org/help would benefit from placing the links to the [GitHub Wiki](https://github.com/internetarchive/openlibrary/wiki), [blog](http://blog.openlibrary.org/), more step-by-step and listing of specific activities on the [volunteer page](https://openlibrary.org/volunteer) (like more description on the "Designer & User Researcher" section, list how people could edit pages in the "librarian" section, etc.) (shouldn't the 2020 roadmap be here), etc. to know what's going on),

While delineation isn't perfect, I don't think the problem is worth a GitHub issue.

>     4. make it easier to become a lead on projects,

Again, I think that we're doing a decent job of this

>     5. show what capabilities volunteers can do (in list form, even though it's kind of on https://openlibrary.org/volunteer - beyond roles a list of general capabilities - like being able to create new github issues or write a blog post, etc.)

Like mentioned, openlibrary.org/volunteer does this. Perhaps we could add writing a blog post to the Communications Specialist portion, but otherwise I think the volunteer page is fine.

> 
>     * A workflow design, like Lucidchart (available on Google Drive) to show the tasks and roles of each person: it helps to know what's missing or too much so the roles can be adjusted more easily

What benefit would this provide which isn't provided by the [Wiki](https://github.com/internetarchive/openlibrary/wiki#meet-the-team)

>     * willingness and ability to divvy up roles more and making sure no one's too overloaded with work

If you mean by the OL team, from what I can see this is largely/entirely controlled by the Internet Archive

>     * put the 2020 roadmap in a really important place for everyone to know the vision (idk - the 'vision' page, the GitHub Wiki, etc.?)

👍 

>     * understanding of the capabilities and limitations of each person and ability to work with it to get tasks done

This is dynamic. We should mitigate risk for volunteers and full time staff but this is almost impossible to control especially in a volunteer project.

>     * add in all the recommended changes proposed and agreed upon

Not sure what you mean by this. Do you mean this issue specifically?
 
>     * need more channels to get more people to see the content they need to get to to get to the information they need

**Strong disagree**. Fragmenting the community is a bad idea. Lowering the barriers of entry to communicate I can get behind.

**Comment by BrittanyBunk** [comment]
@guyjeangilles Thank you for this breakdown - it helps to see things clearly and I think we're in agreement on some parts and others you do have more experience than me about it.

What benefit would this provide which isn't provided by the Wiki? 
- There isn't a volunteer table there.

I think I might've miscommunicated the last one. What you say is true - I think I was referring to people coming from outside of the internet trying to get to the OL being able to be met on the internet with info to get there and do so. Also, I don't think it'll be fragmenting if people get to where they need. Like if I find the book I was looking for on the OL by starting on a Wikipedia page, then I'm more connected to the OL than before. I mean, if I find it on Wikipedia before that, I was already there, so it's fragmenting - but in a way that I wouldn't be connected with the OL to begin with to fragment from it (or maybe we're talking about two different things?).

**Comment by guyjeangilles** [comment]
> What benefit would this provide which isn't provided by the Wiki?
'- There isn't a volunteer table there.

https://github.com/internetarchive/openlibrary/wiki#meet-the-team is a list of team leads, many of which are volunteer. I dont think we should get more granular than that.

The last point sounds like distribution/marketinf? Am I understanding you right?

**Comment by BrittanyBunk** [comment]
I believe so. I found https://docs.google.com/document/d/1RUsUnIJM78gTr5ycewUJNwYHERBQdg_Tv-X-OZpwtRY/edit#heading=h.h7rzk0v4rwic, which does show distribution ideas. It shows the users, but it misses the info about what type of person they are (like user, volunteer, admin/dev, etc.) based on their permissions, time, and what they do. I mean, it's editable by anyone, but I just don't want to add anything to avoid messing up the document - but it kind of does look like it's supposed to be added on to.

**Comment by BrittanyBunk** [comment]
I'm going to try to resolve some of this through creating an "Enthusiast and Beta Tester" (EBT) page to help these volunteers find their starting point, because everything for them will be like looking at new tasks like a newcomer to them, and there needs to be a place to plug into where they need to be to get started quickly when called for help on tasks. Right now, documentation is specific to individual roles (like the librarian repository or the engineering coding wiki), so it'll be helpful for EBTs to know where to go, what they're looking at, and how to be setup (like know the method of how to read for each role and software to have/get) to plug in to anything - as EBTs do a little bit of everything without going too deep into any of them (unless they specialize for a task). This would allow for better coordination of volunteers and experts to get tasks done. If not, I'll reopen it.

**Comment by BrittanyBunk** [comment]
I don't think this could be resolved by documentation. The issue is that there's a pathway to form issues (like on github) and discuss solutions until they come about (on github), but there's no real ability for people to form teams and/or implement solutions on the website. Either there's an excuse, like 'not enough developers' or it requires special permissions - and this is where ideas get stuck in limbo - where the issues go nowhere until they're either abandoned or closed. This is what I was trying to get at. I just wasn't able to word it properly earlier. This is what I'd like resolved - as right now I can't implement my own issues and solutions to issues, as I don't have permission. Others don't - and I feel they get lost too as to where to go - because they're not picked up by groups and teams resolving issues.

**Comment by mekarpeles** [comment]
Hi, I think this conversation needs to happen on a community call and not on the tracker; this is turning into a large discussion over something which is a pretty scoped communication.

**Comment by BrittanyBunk** [comment]
@mekarpeles I understand that community discussion issues are going to be long, but there needs to be a place for them to appear. A community call hour won't be enough time and most definitely wouldn't be beneficial - as it'll take away from more important matters. This is what I was referring to in terms of a more decentralized place to work on matters with the community in detail. If I made something like that - no one will go to it - because it needs to be approved. My idea would be for it to be to add the https://github.com/internetarchive/openlibrary/issues/3374, so that long discussions can continue. Or, it's a new group, or it's going to be a forum or brainstorm location (like Google Docs) for this - as shutting ideas down just because it doesn't fit the formatting doesn't make these (or future issues by other people) go away - they just don't get addressed or worked on.
