### ISSUE TITLE
Suggested UI layout for /borrow#stats

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3282]
@ScarlettRed and I put this together as a collaborative effort this UI layout for the borrow stats page: https://xd.adobe.com/view/c44286cb-6190-461e-7aee-8357af397550-b273/. This is a work in progress and open for adjustments. Related to #3232 and #3229.

**Comment by tfmorris** [comment]
I think perhaps you misunderstand what a Pull Request is. It's used to submit a set of code changes for review and approval. The code could be HTML, CSS, Javascript, or Python, but a mockup/wireframe isn't the same thing.

You can read more about the Github model here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests

**Comment by BrittanyBunk** [comment]
@tfmorris that's what I was kind of thinking, but you're right. Thanks for laying it out. So it's good how it looks then?

**Comment by ScarlettRed** [comment]
@tfmorris this issue was created for you all to review the suggested page that was required to be made in accordance with #3232 
@BrittanyBunk I think we should post this link on the slack channel as well.

**Comment by BrittanyBunk** [comment]
@ScarlettRed it sounds cool, but it's not big enough of an issue to do that. Instead it'll be better to post the link of your design on there, so people could look at it :)

**Comment by BrittanyBunk** [comment]
@tfmorris @guyjeangilles should I start creating a mockup/wireframe code to make a pull request for putting together the page, now that the UI in put together?

**Comment by tfmorris** [comment]
You should coordinate with @mekarpeles

**Comment by guyjeangilles** [comment]
@cdrini Is into design as well

**Comment by BrittanyBunk** [comment]
@guyjeangilles didn't know that!

I really would like to have a game plan and some setup of what the code looks like before bringing anyone else in, as that part's my responsibility.

I looked at the elements of https://openlibrary.org/stats and figured a lot of the stats come from graphite. So I'll check out where the borrow stats are there and proceed from there - as the uppermost graphs on that page are the right format for the /borrow#stats page.

**Comment by mekarpeles** [comment]
original link blocked behind password
