### ISSUE TITLE
Display /subjects page in columns

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3287]
The subjects page was meant to be displayed in columns, but 

### Steps to Reproduce

1. Go to https://openlibrary.org/subjects

| Expected | Actual | 
| --- | --- |
| Something like this: ![image](https://user-images.githubusercontent.com/6251786/78060210-26e44880-7359-11ea-879e-3fe086a16516.png) | ![image](https://user-images.githubusercontent.com/6251786/78060246-319edd80-7359-11ea-8b56-b21c1db908c7.png) |

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF74
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Find a way to add some CSS to this page. Since this is an infogami wiki page, we're not really sure how to add css to it :/ Any attempt to add e.g. `<style>`, or `style="..."` to the wiki page's markup failed (looks like it's not allowed), so we need to a way to add CSS to this while leaving the actual HTML file here (or somewhere?) as a wiki page for easy editing.

### Related files
None 😬

**Comment by BrittanyBunk** [comment]
Is there a way to make it an array or table?

I'm no expert, but this is what my thoughts are:
I did look at the homepage - and it really is a confusion of sorts - has a mix of javascript, css, and of course some stuff (like the bots) are written in python. 
From building websites, usually the CSS is built separately from the HTML, but kind of 'inserted in' so the html code reads it.
The OL homepage looks like it uses a separate CSS file for its CSS coding, so maybe that could be done too - like create a separate CSS file that an HTML code could call upon?
![image](https://user-images.githubusercontent.com/55302685/78099724-adb81600-7397-11ea-817f-69d7d275db52.png)
