### ISSUE TITLE
Permanently disable auto full text search fallback

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3288]
This has been "temporarily" fixed in #3273, but we should make the fix permanent. The previous behavior was a UX nightmare. When an "All" search returned no results, the system would, without warning or asking the user, automatically kick off a very expensive and slow full text search operation which couldn't be cancelled and would take a minimum of 5-10 seconds to return.

The two most common cases where this would happen were:
1. An intermittent Open Library search engine error, where the user wants to retry the search
2. A typo or bad search term where the user wants to adjust the search

In each of these cases, the system blocks the user from taking action until it has returned the (useless) full text search results.

### Proposal & Constraints

The current temporary fix should be cleaned up, if necessary, and made permanent.

### Stakeholders
@cdrini @mekarpeles @gdamdam

**Comment by mekarpeles** [comment]
Closing this issue; at some point w _do_ want to incorporate fulltext results into the search experience and remove dead-ends (the results are fairly slow and so we'll need a better strategy)

**Comment by tfmorris** [comment]
@mekarpeles Perhaps your rationale for closing could address some of the comments in the original issue -- which were supported by Internet Archive staff member @cdrini. Since it's principally a  UX issue, maybe someone with user experience like @jdlrobson or @seabelis should be polled for their opinions.

Others, like @LeadSongDog, may raise the issue of OpenLibrary sending patrons' search queries off to a third party site like Internet Archive, but that's not my principal concern.

**Comment by LeadSongDog** [comment]
@tfmorris To be clear, I see no real problem with sending the query on to IA, just to redirecting the user’s browser there, while a very slow search runs. If OL provides an IA proxy for the response, it should work just fine.
