### ISSUE TITLE
Firefox v49 with uBlock Origin ad-blocker disables many JS components

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#331]
![pasted_image_10_7_16__11_14_am](https://cloud.githubusercontent.com/assets/1231433/19200692/36d35ca0-8c7f-11e6-99c6-1b9495ad5e4d.png)

**Comment by jessamynwest** [comment]
Fascinating! I use ad-blocker but not uBlock and everything's fine on my end.

**Comment by bfalling** [comment]
This may be related to an issue where certain users' configuration of AdBlock Plus (seemingly on some Windows 10) caused links on the Borrow page to not be clickable. White-listing OL solves it. We added this to the OL Help page:

> Some users have been reporting inability to click links on the "Borrow" page of Open Library including their usernames. If this is happening to you, please email us with your operating system and browser combination and we'll work to diagnose the issue. Some users have reported that disabling their ad-blockers will fix this. If you are affected, could you please try this?

There might not be any action to take, but it does seem like in OL, we use Javascript to fire a number of events, such as page redirects or form submissions on particular pages, that really don't require Javascript. Replacing them with standard HTML might help them function better when JS blockers are present. Some pages might also be reporting JS errors outright.

**Comment by mekarpeles** [comment]
Not sure if this is still relevant, but flagging as will not fix (unless we start receiving further complaints)
