### ISSUE TITLE
API to add a Book

### ISSUE THREAD

**Issue by rcastellotti** [internetarchive/openlibrary#3312]
### Question
Is it possible to add books via API? I see you are using RECAPTCHA which makes me doubt, but adding via api would be very interesting( I could add a section to add books to openlibrary.org in my mobile application which allows you to scan a Book's barcode and save it somewhere)

Thanks in advance 
RC

**Comment by cclauss** [comment]
A different but related repo:
* https://github.com/internetarchive/openlibrary-client
* https://github.com/internetarchive/openlibrary-client#usage

**Comment by rcastellotti** [comment]
That might be the answer

**Comment by tfmorris** [comment]
> Is it possible to add books via API?

Yes, but write access to the API requires a whitelisted account. We don't have a good way to enable this for general usage.

As for openlibrary-client, that has an aggressively viral license, so can't be used by any non open source apps. I tried unsuccessfully to get that changed. It's really just a convenience library though and doesn't grant any special powers that aren't available through the raw REST API.

**Comment by guyjeangilles** [comment]
Gonna close this since the question is basically answered.
