### ISSUE TITLE
Print-disabled DAISY file links fail from listings but not edition pages

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#332]
A user reports: "Often times, when you click on the protected Daisy titles on the main page that lists the titles, you get a 404 error. However, if you click or enter on the title you want, go to the protected Daisy, and then download the title, the errors disappear. I was happy to discover this because many of the books do not work if you simply click on the protected daisy without first clicking on the actual book. In other words, if you search for an author, some of the books show that the book is in protected Daisy. If you enter on the protected Daisy for that title, you will most likely get a 404 error. However, if you enter on the title of that book, and then go to the protected Daisy, you will most likely succeed in downloading the title."

Also note that there may be other DAISY-generation issues at the Archive, but the above report suggests a discrepancy between listing and detail page DAISY links.

**Comment by mekarpeles** [comment]
I think this has been resolved.
