### ISSUE TITLE
Import BWB ids for pre-isbn books

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3320]
I added a `better_world_books` field for ID numbers: E.g. https://openlibrary.org/books/OL27291054M/Dwellers_in_the_Mirage . We should import BWB IDs for pre-isbn books so that the price shows up and so that these can be sponsorable.

### Stakeholders
@hornc @mekarpeles

**Comment by guyjeangilles** [comment]
@cdrini I'd like to tackle this.

I presume the first step would be filtering the most recent data dump for editions with no ISBN using `grep`.

After that I'm not sure what's the best way to know if an edition has a BWB id

**Comment by cdrini** [comment]
Sounds good to me! We might be able to get a dump from BWB with that data; @hornc do you by any chance have that or know how we can get it?

**Comment by LeadSongDog** [comment]
Quick screen: pre 1966 can’t have an SBN. 1966-1970 ISBN-10 starts with 0 if any
1970 onward most will have one.

**Comment by mekarpeles** [comment]
I don't want to be too contentious, but I might even suggest us closing this one. There may be ~1M books they've seen with either No-ID or pre-isbn. The metadata will likely be sparse. Often times there is no just ID evident on the book (e.g. no barcode, etc); it's not that it's pre-isbn. @LeadSongDog's comment is well informed. I don't know that this direction has the ROI to merit this specific vector for imports, versus e.g. Jude has 5M+ MARC records from institutional partners sitting on a VM somewhere which would be much higher ROI and include pre-isbn books. Leaving it to @cdrini

**Comment by tfmorris** [comment]
I support @mekarpeles recommendation to close this.
