### ISSUE TITLE
Display sub-subjects at top of search in desktop

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3321]
Once #2984 is merged, the subjects page will look identical to search results. It's likely that people using this page will want to "dive deeper" by looking into sub-subjects, so we should bring this to the top (at least on desktop where it doesn't take up too much space; maybe also on mobile?). Thoughts?

### Proposal & Constraints
![image](https://user-images.githubusercontent.com/6251786/78615293-15121200-783f-11ea-84ec-ba08f909c10b.png)

### Additional context
It would be nice if some light refactoring of the worksearch template was done in preparation of this.

**Comment by BrittanyBunk** [comment]
This doesn't say where the subjects part is right now, but it's too much at the top. When I search, the first thing I want to see is the book results (as I'm trying to get a book) and seeing anything else would be confusing. I'm not sure how much space there is, but maybe a 2nd filtering column would be easier to work with. If not, expand/collapse filter categories would work to make the subjects visible. The websites I like expand/collapse.

**Comment by mekarpeles** [comment]
I like the idea of us improving search to show e.g. subjects, fulltext, authors, etc. I think this PR should be closed and the solution reassessed w/ the scope of the 2021 goal
