### ISSUE TITLE
Update German / Deutsch translation

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3324]
Now that we've finished the bulk of the internationalization of strings used in OpenLibrary (#2442 #2998), the original German translation (#2818), contributed by @justcomplaining, should be completed/updated.

The message file is `openlibrary/i18n/de/messages.po`
The translation guidelines are here: https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#internationalization-i18n---for-translators

**Comment by justcomplaining** [comment]
I am trying to follow the translation guidelines but running scripts/i18n-messages gives me the following error and sadly I have no understanding of code whatsoever, so help would be appreciated :laughing:
 
`Traceback (most recent call last):
  File "./i18n-messages", line 9, in <module>
    from openlibrary import i18n
  File "/home/steven/openlibrary/openlibrary/i18n/__init__.py", line 2, in <module>
    import web
ImportError: No module named web
`

**Comment by justcomplaining** [comment]
I just tried it again, and the error persists. Am I doing something wrong or is it a bug?

**Comment by cdrini** [comment]
These were updated by @bitnapper a while ago. Thank you @bitnapper!
