### ISSUE TITLE
Update Czech translation

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3325]
Now that we've finished the bulk of the internationalization of strings used in OpenLibrary (#2442 #2998), the original Czech contributed by @Clonewayx , should be completed/updated.

The message file is `openlibrary/i18n/cs/messages.po`
The translation guidelines are here: https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#internationalization-i18n---for-translators

**Comment by mekarpeles** [comment]
I believe this is done

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/cs/messages.po
