### ISSUE TITLE
Search results contain broken e-book links

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#334]
https://openlibrary.org/search?q=davinci+code&has_fulltext=true

There are 3+ results, most of which are Daisy.

The links are like: https://openlibrary.org/works//works/OL8733727W
(Note the extra /works/)

In another search https://openlibrary.org/search?q=english&has_fulltext=true

I see: https://openlibrary.org/works//works/OL6925296W
(note the extra /works//)

Possibly related to #332

**Comment by jessamynwest** [comment]
We saw this /works/works formation on author merge pages too if that's helpful (i.e. if you're on an author merge page and want to click through to see an author's works, I think, you get that /works/works thing which then fails)

**Comment by bfalling** [comment]
@mekarpeles: Note @jessamynwest's last comment, which I still see in evidence on the Author Merge page, e.g. (picking 2 authors from the Vagrant seed items in the Quickstart "Copying documents" section) http://localhost:8080/authors/merge?key=OL1518080A&key=OL18283A

The "Remix" link URL on that page is http://localhost:8080/works//works/OL6037022W

(However, I do confirm that the Daisy icon links on the metadata search results page, e.g. http://localhost:8080/search?q=twain, are fixed, and that PR has been merged.)

**Comment by mekarpeles** [comment]
Thanks! I see this too, I'll update for that case as well.

**Comment by mekarpeles** [comment]
I did a search through the top level html pages in templates/ and found these possible candidates as well having `/works/$doc`

improve_search.html -- confirmed (including in followup PR)

Should be resolved in the latest PR

**Comment by hornc** [comment]
@mekarpeles I'm pretty sure this is resolved now?
