### ISSUE TITLE
Unable to add book when similar work exists

### ISSUE THREAD

**Issue by drupol** [internetarchive/openlibrary#3340]
Hi,

I discover your service today and I wanted to add a couple of books from my bookshelf.
It has worked without any trouble for some, but I'm unable to add the following one:

Title: The First Six Books of the Elements of Euclid
Author: Oliver Byrne (_there are duplicates, it should be merged, but I select the first one_)
Publisher: Taschen
When: 2013
ISBN 10: 3836544717

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/252042/78989361-b3e68900-7b33-11ea-9af6-3a3aa8089863.png)

### Relevant url?

https://openlibrary.org/books/add

### Details

- **Logged in (Y/N)?**: Yes 
- **Browser type/version?**: Firefox or Chrome, same result on both 
- **Operating system?**: Linux
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Ah, it looks like the bug happens when a similar book exists. Are you able to create the record using this url? https://openlibrary.org/books/add?work=/works/OL15677131W

**Comment by drupol** [comment]
Thanks! I succeeded to add the new edition: https://openlibrary.org/books/OL27936588M/The_First_Six_Books_of_the_Elements_of_Euclid

**Comment by cdrini** [comment]
Sweet! I'm going to leave this issue open since the code still needs to get fixed 👍

**Comment by guyjeangilles** [comment]
I've changed the title to better reflect the reason the issue has remained open
