### ISSUE TITLE
Canonical URLs should not include version url param

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3341]
The first result on google when searching for [how to borrow openlibrary](https://www.google.com/search?client=firefox-b-d&q=how+to+borrow+openlibrary) links to https://openlibrary.org/help/faq?v=102 ; which is ~7 years older than the current page!

### Steps to Reproduce

1. Go to https://openlibrary.org/help/faq?v=102 and inspect the source

* Actual: `<link rel="canonical" href="https://openlibrary.org/help/faq?v=102" />`
* Expected: `<link rel="canonical" href="https://openlibrary.org/help/faq" />`

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF74
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles @tabshaikh

**Comment by tfmorris** [comment]
This is addressed by the pending canonical URL PR.

**Comment by guyjeangilles** [comment]
The specific PR is #3306

**Comment by SouthGoingZax** [comment]
That PR is closed now.  This looks like a subset (and thus dupe) of #2864 (see the last comment for a larger set of parameters to exclude).

**Comment by SouthGoingZax** [comment]
Closing this as a dupe of #2864
