### ISSUE TITLE
Removing an Edition still shows a "ghost" item on the Work page

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#335]
Reported: I removed some duplicates of an item here:
https://openlibrary.org/works/OL12216637W/Calorie_restricted_diets_for_weight_reduction

They are showing up as odd "Publisher-unknown Title-missing" records instead of just disappearing. Re-indexing didn't fix the issue.

Another example of this:
https://openlibrary.org/works/OL98927W/The_trauma_of_birth

**Comment by anandology** [comment]
They look alright to me. Is it just a matter of time before it gets
corrected? If that is the case, then it might be a caching issue.

There is a way to examine the cache entries from the admin panel.

**Comment by jessamynwest** [comment]
Would be great from a feature request to have some sort of cache-clearing/resetting thign happening when we do this sort of thing.

**Comment by LeadSongDog** [comment]
This is still a problem. See https://openlibrary.org/search/authors?q=John+Gloag&mode=everything

**Comment by LeadSongDog** [comment]
Possibly related, after editing a work to link to a different author record, the former author record still shows the edition. This seems to relate somehow to the book covers linked, though I may be imagining that.
The recent author merge to https://openlibrary.org/authors/OL120185A/John_Edwards_Gloag still showed many works as being by "Gloag, John" but clicking through on (for example) https://openlibrary.org/works/OL1189728W/Guide_to_Western_architecture the shown author name is correct on the seven edition records. 

Experimenting, edits touching _all_ the edition records seemed to cause a cache update with the revised author name shown against the work. There's got to be an easier/more obvious way.

**Comment by LeadSongDog** [comment]
Ok, I think I've got this now. Simply touching the by_statement in the edition record causes the indexing to be created after a few minutes time lag:
https://openlibrary.org/books/OL6467527M/99?b=4&a=3&_compare=Compare&m=diff
did it. It caused a null edit to the associated work record:
https://openlibrary.org/works/OL1189672W/99?b=2&a=1&_compare=Compare&m=diff

**Comment by hornc** [comment]
all down to our know solr indexing issues which are being addressed in upcoming upgrades etc
