### ISSUE TITLE
Split the Open Mic and Meeting notes from each other

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3355]
### Problem
On the [2020 Open Library Community Call document](https://docs.google.com/document/d/1FEG-bdOTsi8Q3IHgFboL_LZImN18Q4wsWWWtlV8RgKk/edit?usp=sharing), the meeting notes are combined into the Open Mic topics. That makes it really difficult to read and separate who brought up a topic and what was discussed.

### Solution
Have a 'notes' section that's above the 'Open Mic' section to separate the two for easy reading

### Stakeholders
Anyone who uses the document for reference

**Comment by mekarpeles** [comment]
This is a ticket for slack, not for the openlibrary code base

**Comment by BrittanyBunk** [comment]
@mekarpeles If that is true, as I assumed internetarchive/openlibrary meant all Open Library issues, not just developer ones, then why is this not explained in https://github.com/internetarchive/openlibrary/wiki/Interacting-with-GitHub-Issues? Also, if that is true, then there should be a place on Github that separates the non-developer issues from the actual ones - I mean a simple label is fine or a new github group - but adding them to Slack won't work - as they'll get lost. It'll be beneficial to know a usable alternative to work with - so that anyone who needs any Open Library issue addressed, not just developer ones, have a place to go for that. Why not make an Openlibrary-developers group so that developers aren't caught up in the other issues? I just don't get it.
