### ISSUE TITLE
Importing high-signal Archive.org subject tags onto Open Library Works

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3356]
### Describe the problem that you'd like solved

There are hundreds of useful subject tags for the `inlibrary` collection on Archive.org for books which are also in Open Library but missing these subjects. We may want to consider strategically importing some of these timely subject tags into/onto Open Library to improve discovery.

## Example

Here's an example which (given we've chosen a subject tag we want to import from Archive.org):
1. Finds all books on Archive.org which are in the lending program which also have the specific `subject`
2. Fetches the corresponding Open Library work
3. Adds the Archive.org subject to this work (and saves)

```
from olclient import OpenLibrary
import internetarchive as ia

if __name__ == "__main__":
    config = {'general': {'secure': False}}
    params = {'page': 1, 'rows': 10000, 'scope': 'all'}
    fields = ['openlibrary_work']

    # get a list of all IDs we want to add this subject to on Open Library:
    subject = 'XXX'  # <-- insert subject here
    q = 'openlibrary_work:(*) AND subject:%s'
    ol = OpenLibrary()
    for i in ia.search_items(q, fields=fields, params=params, config=config).iter_as_results():
        ol_work = r.get('openlibrary_work')
        # Add `subject` to OL work
        ol.get(w).add_subject(subject)
```

## Vetted High-Signal Tags

Here are some hand-picked groups of examples of "subject" tags on Archive.org which we may want to import onto Open Library works.

Each section header beginning with a `##` is a logical grouping (it doesn't exist as a tag on Archive.org) I've made up to group the tags below it.

```
## Arts, Crafts & Hobbies
Crafts / Hobbies
Hobbies/Crafts
Crafts & Hobbies
Textile crafts
Handicrafts
Crafts & Hobbies - General

## Cooking, Recipes, & Nutrition
Cooking
Cookery
Cooking, American
Cooking / Wine
Quick and easy cooking
Cookery, American
International cooking
Cooking, Italian
Vegetarian cooking
Cookies
Christmas cooking
Cookery, International
Cooks
Cooking, Chinese
Cooking (Vegetables)
Quick and easy cookery
Cooking (Natural foods)
Christmas cookery
Cooking (Pasta)
Cooking, French
Vegetarian cookery
Microwave cookery
Microwave cooking
Cookbooks
Cooking (Herbs)
Cooking (Fish)
Holiday cooking
Cooking (Chocolate)
Cooking / General
Cookery, Italian
Women cooks
Casserole cooking
Cooking, Mexican
Cooking (Chicken)
Barbecue cookery
General cookery
Cookery (Pasta)
Jewish cooking
Cooking (Fruit)

## Health, Exercise, & Fitness
Health/Fitness
Health & Fitness
Bodybuilding
Weight training
Exercise
Free weights
Yoga
Hatha yoga
!! pilates


## Medicine
Medicine
Medical
Medical / Nursing
Medical care
Medicine, Popular
Medical ethics
Alternative medicine
Ethics, Medical
Medical policy
Popular medicine
Holistic medicine
Social medicine
Medicine, Chinese
Medical economics
Medical examiners (Law)
Medical genetics
Medicine, Preventive
Genetics, Medical
Traditional medicine
Medical care -- United States
Medical policy -- United States
History of Medicine
Medicine and psychology
Internal medicine
Medical emergencies
Medical fiction
Religion and Medicine
Materia medica, Vegetable
Medicine, Psychosomatic
Emergency medicine
```

### Proposal & Constraints

For this issue, I propose we start small and focused and only process one section at a time.

For each section, (e.g. `## Arts, Crafts & Hobbies`) above, we want to find all `inlibrary` books with **any** (i.e. the [set union](https://en.wikipedia.org/wiki/Union_(set_theory))) of the associated tags. This can be done by chaining each sub-tag with the `OR` operator when querying Archive.org.

e.g. `collection:inlibrary AND subject("crafts" OR "hobbies" OR ...)`

#### Constraints

Some Archive.org subject tags have special characters, here are a few heuristics we may want to use:

- `--` split subject
- `//` split sbject
- `[0-9]+` (regex) i.e. ignore numbers; likely a date
- `index` ignore tags containing this string; avoid false positives

**Open Questions:**
- What do we do about `/` or `-`? Splitting may not always right answer
  

### Next Steps:

- [ ] Talk to @mekarpeles about choosing 1 subject to test for import

**Comment by ishank-dev** [comment]
@mekarpeles  Does one need to be very familiar with the OL python library to work on this? 
And how will we ensure that the right subject tag is assigned to the right book?

**Comment by BrittanyBunk** [comment]
You don't mean putting these subject tags on the subjects page when you say 'creating' right?

**Comment by BrittanyBunk** [comment]
I found: https://github.com/internetarchive/openlibrary/blob/refactor/everything/openlibrary/templates/subjects/index.html. Are we talking about this?

**Comment by MayankVir** [comment]
I would like to work on this feature update

**Comment by mekarpeles** [comment]
I think most of the subject tags in question are likely imported through MARC records. Going to close for now.
