### ISSUE TITLE
When using the API, some covers are not available

### ISSUE THREAD

**Issue by drupol** [internetarchive/openlibrary#3362]
Hello,

I'm trying to get the cover of a book using its isbn-13 and no cover is found despite the fact that there is a cover for that book.

Book link: https://openlibrary.org/books/OL23175425M/Why_does_e_mc2

API images links:
* https://covers.openlibrary.org/b/isbn/OL23175425M-M.jpg
* https://covers.openlibrary.org/b/isbn/9780306817588-M.jpg

Using curl:

```shell
$ curl -I https://covers.openlibrary.org/b/isbn/OL23175425M-M.jpg
HTTP/1.1 200 OK
Server: nginx/1.4.6 (Ubuntu)
Date: Thu, 16 Apr 2020 07:24:39 GMT
Connection: keep-alive

$ curl https://covers.openlibrary.org/b/isbn/OL23175425M-M.jpg --output cover.jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   807    0   807    0     0    735      0 --:--:--  0:00:01 --:--:--   735

$ file cover.jpg
cover.jpg: GIF image data, version 89a, 1 x 1
```

**Comment by drupol** [comment]
Any news on this so far ?

**Comment by tfmorris** [comment]
The Cover service doesn't include all the covers. Rather than fixing it, OpenLibrary added a workaround to the web client to fetch covers directly from IA. That's why you see different results in the web app. You're probably stuck using the same workaround.

**Comment by drupol** [comment]
I understand, but then there is a discrepancy between the OL frontend and OL API !

**Comment by mekarpeles** [comment]
@tfmorris @drupol -- we have Guy's cover bot that retroactively fills in IA Ids. We also have several cover improvements which have happened in the past few years.

The API calls above work, though careful that /isbn only works with isbn and /olid must be used if the ID type is Open Library ID.
https://covers.openlibrary.org/b/isbn/9780306817588-M.jpg
https://covers.openlibrary.org/b/olid/OL23175425M-M.jpg
