### ISSUE TITLE
Add Open Library (OL) Team to Footer

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3366]
Cleanup of footer - part 1

Reference pages:
https://openlibrary.org/about/people
Footer of https://openlibrary.org/

### Problem
It's difficult to find the OL team without searching for it. It would be better if it's in the footer.

Before:
![image](https://user-images.githubusercontent.com/55302685/79640275-8d34dd80-8145-11ea-976d-189f8a88d27b.png)

### Solution
![image](https://user-images.githubusercontent.com/55302685/79640393-44315900-8146-11ea-87c4-2e8d11452a2c.png)

**Comment by tabshaikh** [comment]
@BrittanyBunk where would the team link lead
