### ISSUE TITLE
Move Terms of Service to bottom

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3369]
Footer cleanup - part 4

### Problems
- The Terms of Service normally goes at the bottom of pages, so that it's clear where to find them. Right now, it's too difficult to find and moving it to the bottom will help out with that.
- The space in the OL column should be able to make room for better links

Before:
![image](https://user-images.githubusercontent.com/55302685/79640804-6d52e900-8148-11ea-98af-dfd1842b5953.png)

### Solution
After:
![image](https://user-images.githubusercontent.com/55302685/79640817-8fe50200-8148-11ea-9886-c9b5d28c5665.png)

**Comment by mekarpeles** [comment]
We recently redesigned the footer and decided to put the Terms of Service where it is.
