### ISSUE TITLE
Add K12 link in footer

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3371]
Footer change - pt 6

### Problem
- it's going to be difficult to find the K12 button after it gets removed from the banner

Before:
![image](https://user-images.githubusercontent.com/55302685/79640983-aa6bab00-8149-11ea-9100-e1b6ca36d540.png)

### Solution
After (disregard font):
![image](https://user-images.githubusercontent.com/55302685/79641239-169ade80-814b-11ea-8eb3-836377be45fd.png)

**Comment by mekarpeles** [comment]
We're going to be adding this to the Nav bar (there's a PR which will be going on this weekend or Monday). I don't want to overload the footer with links. We should add links carefully and thoughtfully based on data we've collected from google analytics.
