### ISSUE TITLE
Add 'community discussion' option for new github issue

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3374]
### Referring to:
https://github.com/internetarchive/openlibrary/issues/new/choose
![image](https://user-images.githubusercontent.com/55302685/79641952-93c85280-814f-11ea-9f33-c0a885fc2852.png)

### Problem
There are only options for extremes. Either: 1) put in a request for something to get done or 2) ask a question to get an answer. There's no middle. If there's a middle, where people can put a request for a feature, but not for getting it done - just to brainstorm and it's not a question, it'll help to have an option for that. So I'm proposing a 'community discussion' button.

PS - opening a 'blank issue' is not going to allow the community to see that it requires discussion

### Solution - Proposal:
![image](https://user-images.githubusercontent.com/55302685/79641937-6c718580-814f-11ea-840d-a494b60c4e1f.png)

**Comment by mekarpeles** [comment]
Question is currently playing the role of Community Discussion. I believe we had a community call where we discussed this point, and instead of making 2 new types, we went with Question.

**Comment by mekarpeles** [comment]
Let's bring this up as a discussion point on Tuesday

**Comment by SouthGoingZax** [comment]
Looking through the community call notes from April, there is just one line about this with (I assume) @guyjeangilles's name mentioned next to it.  Does anyone who attended recall how the discussion concluded?

**Comment by BrittanyBunk** [comment]
It got unresolved, because I had to leave, already being late to something. They said that the questions section is already the community discussion. If I were to finish the discussion, I would've mentioned to just change 'ask a question' to 'questions/community discussion'. Problem solved.

**Comment by mekarpeles** [comment]
I think we should stick with the existing "Question"; we have a label for community discussion.

"Questions & Community Discussion" also sounds find to me -- happy to review a PR which proposes this change.
Marking this issue as resolved

**Comment by BrittanyBunk** [comment]
@mekarpeles Questions & Community Discussion is good for me
