### ISSUE TITLE
Expand the OL Team top description

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3375]
### Reference
https://openlibrary.org/about/people
![image](https://user-images.githubusercontent.com/55302685/79642289-8f049e00-8151-11ea-9676-920b7fb2fa3e.png)

### Problems
- It's great in showing who's on the team, but not if people want to be a part of it. So I'm thinking if people want to get involved, point them to where they need to go.
- This doesn't explain that the OL team is part of the greater Internet Archive (IA) team. I hear that there's confusion on where the OL lies with the IA, so making it clear would dispel confusion that typically tends to take place
- doesn't give credit to the countless volunteers outside of the core Open Library team

### Proposed solution
Something more collaborative!
Notes:
- Changed 'small' to 'core' to allow for growth.
- Provided opportunities for the public to join in
  (an alternative might be a section at the bottom of the webpage for this instead)

Mockup (ignore font):
![image](https://user-images.githubusercontent.com/55302685/79642994-8c0bac80-8155-11ea-94c4-0ef86722ce9f.png)

**Comment by mekarpeles** [comment]
Updated https://openlibrary.org/about/people.en
+ added https://openlibrary.org/volunteer

**Comment by BrittanyBunk** [comment]
@mekarpeles thanks. There's just one part missing - and that's in the librarian part. It doesn't say how anyone from anywhere can just edit any information on the Open Library, as that's what it's all about. Where's the average editor that isn't a part of a team on the OL, but just gets edits done independently? How about "Independent Librarian"? I mean, there are those at libraries - the ones that put books back on the shelf and stuff. It's like that on here.
