### ISSUE TITLE
Proposed updates to footer

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3376]
The following were proposed by @BrittanyBunk, to be discussed during our next community call.

#3366
#3367 
#3368 
#3369 
#3370 
#3371 
#3372 
#3373 

### Proposal & Constraints

@tabshaikh which of these changes (if any) do you feel strongly for / against? Let's help scope these changes and then you and Brit can bring this to a community call for feedback as a next step

### Stakeholders

@tabshaikh who led the last redesign of our footer, to clear designs w/ @mekarpeles

**Comment by BrittanyBunk** [comment]
Thanks for putting them in one place! I will definitely not mind discussing it during the next community call for sure.

**Comment by SouthGoingZax** [comment]
It looks like all those issues are closed.  Can this be closed?

**Comment by tabshaikh** [comment]
Closing it Thank you as I do not feel strongly about any of the above-proposed changes
