### ISSUE TITLE
Some books shown in admin as checked out to "Unknown"

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#338]
Some books on their Borrow Admin page show themselves as checked out to "Unknown". (See screenshot)

Steps used to reproduce (on 10/3/2016) for this book:
https://openlibrary.org/books/OL5798434M/101_science_experiments./borrow_admin

According to @jessamynwest...

> This is what I did.... borrowed book using Richard's v2 BookReader beta and then returned it. There was an error message:
> 
> ```
> Unknown err: Invalid argument supplied for foreach() /home/richard/petabox/www/common/LoanServer.inc:31
> Unknown err: Invalid argument supplied for foreach() /home/richard/petabox/www/common/LoanServer.inc:43)
> ```
> 
> Then the book was checked-in according to both IA and OL. So I went to OL to get it again (in BookReader) and got a template error. I went to IA on my non-admin account and borrowed it in BookReader and now when you go to OL you can see the book checked out to "unknown" and I don't see it on my loans in IA.
> 
> On the OL page the current loans section shows the loan at the bottom but it's checked out to user null
> 
> ```
> { "_key": "loan-101scienceexperi00pode", "_rev": 1, "book": "/books/OL5798434M", "expiry": "2016-10-17 19:19:42", "fulfilled": "1", "loan_link": "", "loaned_at": 1475522382.0, "ocaid": "101scienceexperi00pode", "resource_id": "bookreader:101scienceexperi00pode", "resource_type": "bookreader", "stored_at": "ia", "type": "/type/loan", "user": null, "uuid": "loan-391814833" }
> ```
> 
> Another data point: Richard's v2 correctly states that I have 1 of 5 books on loan but IA's loans page doesn't show this book. So they seem to be drawing info from two places.
> 
> Repeated test with another book: same thing happens. OL error is:
> 
> ```
> Sorry. There seems to be a problem with what you were just looking at.
> We've noted the error 2016-10-03/193450603687 and will look into it as soon as possible. Head for home?
> ```
> 
> Successfully checked out of IA. On OL admin page, same error reproduced:
> https://openlibrary.org/books/OL24201662M/The_big_book_of_tricks_and_magic/borrow_admin
> 
> Neither book shows on my loans page:
> https://archive.org/details/@jessamyn&tab=loans

(At this point in testing, ACS4 started throwing errors and was down.)

**Comment by bfalling** [comment]
Here's that screenshot:
![pasted_image_10_9_16__10_53_pm](https://cloud.githubusercontent.com/assets/1231433/19228193/a493b4b6-8e77-11e6-88a8-b02b92e4ff9c.png)

**Comment by jessamynwest** [comment]
Here's another example book, from another user.

https://openlibrary.org/books/OL5854499M/Nicomachean_ethics./borrow_admin

**Comment by mekarpeles** [comment]
@bfalling is this still an issue I wonder?

**Comment by mekarpeles** [comment]
Unless @JeffKaplan brings this up as an issue (I think he's been using @rchrd2's lending dashboard) then I am going to close this as **will not fix**
