### ISSUE TITLE
Covers DB not backed up since 2012

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3386]
### Evidence / Screenshot (if possible)
On ol-covers1, we can see that a backup to archive.org/details/ol_data has not been done since 2016 by (I believe) @anandology. We'd be in some trouble if the cover store disks failed. Maybe @abezella can help us take a snapshot of this disk as a failsafe.

Running covers backup should have a script in /scripts and I believe there's a manual process for doing this

cc: @gdamdam? @anandology? @bfalling? @abezella?

**Comment by anandology** [comment]
I guess we archive every 10000 covers and move it to the archive storage.
There should be a script for doing that automatically.

**Comment by anandology** [comment]
I guess you need to run this:

https://github.com/internetarchive/olsystem/blob/master/bin/archive-covers.sh

**Comment by anandology** [comment]
On Tue, Apr 21, 2020 at 2:49 AM Michael E. Karpeles <
notifications@github.com> wrote:

> Evidence / Screenshot (if possible)
>
> On ol-covers1, we can see that a backup to archive.org/details/ol_data
> has not been done since 2016 by (I believe) @anandology
> <https://github.com/anandology>. We'd be in some trouble if the cover
> store disks failed. Maybe @abezella <https://github.com/abezella> can
> help us take a snapshot of this disk as a failsafe.
>
The last backup was in 2012, not 2016.

https://archive.org/details/l_covers_0006


> Running covers backup should have a script in /scripts and I believe
> there's a manual process for doing this
>
> cc: @gdamdam <https://github.com/gdamdam>? @anandology
> <https://github.com/anandology>? @bfalling <https://github.com/bfalling>?
> @abezella <https://github.com/abezella>?
>

I guess so. Happy to check if I still have access to the server.  @abezella?

**Comment by BrittanyBunk** [comment]
@mekarpeles can archive.org/details/ol_data be linked to the data dump page on OL?

**Comment by mekarpeles** [comment]
It looks like back in the day ~2009 we had an [`--archive`](https://github.com/internetarchive/openlibrary/blob/425e1df1e20a7b5d3210f1f9aa8abd6c20fb72cd/openlibrary/coverstore/server.py#L18-L19) cli option for covers which lived in this file separate file: 
https://github.com/internetarchive/openlibrary/blob/425e1df1e20a7b5d3210f1f9aa8abd6c20fb72cd/openlibrary/coverstore/archive.py

It would find/take covers which had not yet been archived (`where='archived=false'` in the db) from local disk and convert them to warc disk which results in items like

This was run by the olsystem script which @anandology mentions above (which will currently break because no `--archive` option has existed in the code for some time and we should probably learn why it was removed):
https://github.com/internetarchive/olsystem/blob/master/bin/archive-covers.sh

1. [ ] Why was --archive removed?
2. [ ] Does this `archived` field still exist in the db (I'm assuming yes because this used to work and we haven't reprovisioned db to my memory)
3. [ ] Does the code work (for some very small example subset)
4. [ ] With this knowledge of 1-3, do wet setup monthly crons to shift unarchived covers from disk to warc items (and are there are consequences of doing so / what chanced would we wish to make)?
5. [ ] (later) somehow assimilate these offerings into data dumps page (e.g. latest covers, all covers)

**Comment by BrittanyBunk** [comment]
@mekarpeles it would be nice if covers are in the data dump location on the open library's website, to prevent such confusion.

Also the website you listed  https://archive.org/details/warc_covers_0000 only has a few covers - 100. Is that supposed to be like that?

**Comment by mekarpeles** [comment]
I need to coordinate with @abezella but I think the OL db is **typically** backed up (at least monthly?)

Since landing https://github.com/internetarchive/openlibrary/pull/7230, we now have documentation and a tested/understood process for archiving cover files themselves. Marking this issue as resolved.

We still likely want covers to be archived on a monthly basis and a new issue will be created for this.

**Comment by anandology** [comment]
The challenge with time based backups was that cover archive expects fixed
number of images per archive.

It may be good idea to seperate the backup and the archive.

A nightly job backups all the covers uploaded in the previous day as a tar
ball with date in the filename to ol-covers-backup item.

A separate monthly job would archive the covers on the machine, only when
enough covers are avilable for an item.

What do you think @mekarpeles?
