### ISSUE TITLE
Correct Read links in Search Inside results when multiple files or filename-vs.-id disparity

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#339]
In the Search Inside search results, the Read links need to be changed to handle cases where the image stack filename is different from the Archive.org ID (as often happens due to characters like spaces in the filename), and where the search result is for one file in an Archive.org item containing multiple files.

In both cases, the solution is to construct links that incorporate the filename, as opposed to only the Archive.org ID, when necessary. The filename can be parsed via the Metadata API.

e.g. 
Metadata API call:
https://archive.org/metadata/savefanfiction-10399417-It_was_worth_it-kettleowl/files

Link to BookReader with Search Inside:
https://archive.org/stream/savefanfiction-10399417-It_was_worth_it-kettleowl/It%20was%20worth%20it-ffnet_10399417#search/Friendship

FYI: Incorrect link that redirects to Details page:
http://archive.org/stream/savefanfiction-10399417-It_was_worth_it-kettleowl#search/Friendship

**Comment by guyjeangilles** [comment]
@hornc This looks like an issue you'd tackle. Are you willing to be assignee? Note: being assignee doesn't necessarily mean you are the one doing the work for the issue but responsible for collecting information needed to devise a solution. From the wiki:

>At submission and prior to triage, the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per the issue's context. Let me know if you agree or disagree.

**Comment by cdrini** [comment]
This needs to be verified if it's still an issue. It's only been 8 years :)

**Comment by RayBB** [comment]
Moved to https://github.com/internetarchive/bookreader/issues/1254
