### ISSUE TITLE
Regression - Cover change of work requires refresh to view

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3395]
Possible regression of PR #3353  . New cover is not displayed after update until page is refreshed.

### Steps to Reproduce

1. Go to https://openlibrary.org/works/...
2. Do change cover of work (cover does change, but old cover still displayed)
3. Refresh. New cover can now be seen.

* Actual: Old cover is displayed.
* Expected: New cover should be displayed without refreshing.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 80.0.3987.163 (Official Build) (64-bit)
- **Operating system?** Mac OS Catalina 10.15.4
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cdrini @devarshigoswami

**Comment by mekarpeles** [comment]
@devarshigoswami any chance you can look into this one?

**Comment by devarshigoswami** [comment]
@mekarpeles Absolutely ,sir! let me look into it.. @seabelis, sorry I couldn't reply in time, joined my first job outta college and things have been a tad hectic

**Comment by seabelis** [comment]
@devarshigoswami No worries. It's not a blocker; new covers can still be added. It just may be a little confusing for some users of the site.

**Comment by devarshigoswami** [comment]
@seabelis @mekarpeles Hi, could anyone walk me through how to change the cover of work in https://openlibrary.org/works/ ? If I try the 'edit' option, it says permission denied.

**Comment by seabelis** [comment]
@devarshigoswami If you hover over a cover you should see "manage covers". Click on this and it will bring up the covers for all the editions associated with the work. Click one to select it and submit.

**Comment by ForgottenProgramme** [comment]
Hey, @seabelis ! 
Is this issue still open? Can I please try resolving it?

**Comment by seabelis** [comment]
@ForgottenProgramme , it is still an issue. I'm not sure if @devarshigoswami is working on it though.

**Comment by codetochangeMinds** [comment]
Hey @ForgottenProgramme are you working on this issue.

**Comment by codetochangeMinds** [comment]
Hey @seabelis, can I work on this issue?

**Comment by seabelis** [comment]
@codetochangeMinds You don't actually need my permission, but I'm happy to answer any questions about the issue if you need more info. Thanks!

**Comment by Sabreen-Parveen** [comment]
@seabelis Is someone working on this issue? If not I would like to work on it..

**Comment by codetochangeMinds** [comment]
@Sabreen-Parveen I think its already resolved. You can see the linked pull request just above your comment.

**Comment by Sabreen-Parveen** [comment]
Actually, the pull request has not been merged so, I thought so.
