### ISSUE TITLE
Address CORS issues with Covers API

### ISSUE THREAD

**Issue by kaaniboy** [internetarchive/openlibrary#3399]
A continuation of #329. It seems like the Open Library Covers API endpoint still has CORS issues, meaning that we cannot make requests to the endpoint from within the browser.

### Describe the problem that you'd like solved

The Covers API endpoint should be adjusted to allow requests directly from browsers. 

### Proposal & Constraints
This can be done by adjusting the `Access-Control-Allow-Origin` header. Reviewing the solution applied in #329 may also be valuable.

**Comment by matiaslabra** [comment]
I just faced this situation working with a canvas (`The canvas has been tainted by cross-origin data`). If someone else needs a quick workaround, I am appending the Open Library cover url into a public Google server (proxy).

```
`https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=2592000&url=http://covers.openlibrary.org/b/id/${
            book.olCoverId
          }-M.jpg`
```

**Comment by klcarlton** [comment]
I'm running into this issue as well. Fantastic project otherwise!
I'm a bit surprised this issue hasn't gotten more attention as it prevents what is fairly common api usage.

**Comment by cclauss** [comment]
@jamesachamp Could you please take a look?

**Comment by jamesachamp** [comment]
@cclauss Sure, I'll work on this over the weekend.

**Comment by jamesachamp** [comment]
Open Library redirects API calls with key `isbn` and calls for large images to Internet Archive.  While it is fairly trivial to add the `Access-Control-Allow-Origin` header to Open Library responses, I'm not sure how difficult it would be to do so on Internet Archive's side.  
Discussion and coordination will be necessary in order for this change to be applied for requests to the covers API.  In the meantime, should I go ahead and make the changes on OL's side?

**Comment by jamesachamp** [comment]
Following up on this.  It looks like fixing this completely will require changes in both Internet Archive and Open Library.  @mekarpeles  what are your thoughts on this?

**Comment by alexpareto** [comment]
Does OpenLibrary proxy the requests for the covers API? It seems that a proxy with the correct headers seems to resolve the issues... perhaps adding the header only on the OpenLibrary side would work?

**Comment by cdrini** [comment]
@jamesachamp Could you try adding it to the OL resources? I think that would cover a majority of requests. I'm pinging some of the folks at IA to see if there are any options for the IA ones.

**Comment by cdrini** [comment]
This should no work for most `-S.jpg` or `-M.jpg` images! Larger quality images might get routed to IA, which won't the CORS headers, so best bet is to stick to `-S.jpg` or `-M.jpg` images.

**Comment by cdrini** [comment]
From Hank at IA: 

> ah, zipview.php is a defunct predecessor of view_archive.php, which redirects in an attempt to support legacy requests.
can covers.openlibrary.org be updated to use view_archive.php directly rather than zipview.php—or even better, as it would probably let you drop from covers.openlibrary.org whatever code is being used to determine the actual location of the olcovers259 item, a /download/ URL instead: https://archive.org/download/olcovers259/olcovers259.zip/2598178.jpg? the /download/ redirect will now include the CORS header.

I created a separate issue for managing that last piece: #4672

**Comment by klcarlton** [comment]
I can confirm that the issue is fixed for -S.jpg and -M.jpg images. Thanks a bunch everyone!

**Comment by cdrini** [comment]
All images should now be CORS-able 🎉
