### ISSUE TITLE
Can't undo some author merges (i.e. semi-broken admin feature)

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#340]
Examples:
- https://openlibrary.org/authors/OL40965A/Nancy_Holder
- https://openlibrary.org/authors/OL7130718A/Adele_Ashworth
- https://openlibrary.org/recentchanges/2013/11/25/merge-authors/47774633
- https://openlibrary.org/recentchanges/2011/07/21/merge-authors/43801768
- https://openlibrary.org/recentchanges/2016/08/04/merge-authors/50515125
- https://openlibrary.org/recentchanges/2013/07/12/merge-authors/47605678 (might have worked but timed out)

**Comment by bfalling** [comment]
Another one:
https://openlibrary.org/authors/OL6856645A/Aristotle?merge=true&duplicates=OL3203154A,OL6027876A,OL6059585A,OL5987701A,OL5994902A,OL7120281A,OL7116355A,OL7116423A

**Comment by LeadSongDog** [comment]
It's likely unrelated, but: https://github.com/internetarchive/openlibrary/blame/c4d877ee6410df6f70ab45718baebe52fdf366ba/scripts/solr_author_merge.py#L42 shows a mismatched single-quote mark.

**Comment by hornc** [comment]
I believe the root cause may be https://github.com/internetarchive/openlibrary/issues/475
Authors that are currently redirects confuse the logic.

**Comment by hornc** [comment]
all of the above merges appear to have since been undone
