### ISSUE TITLE
Remove calls to sync update_waitinglist 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3403]
This is a cleanup for #3402, it is tentatively determined that loan_sync from openlibrary.php within petabox is not required on borrow and the right logic should get called anyway when the join/leave waitlist logic is invoked within petabox lending internals.

**Comment by dherbst** [comment]
I removed the `update_waitinglist` calls and did some other pyflakes cleanup here https://github.com/internetarchive/openlibrary/pull/4280 If you want to wait until py3 is finished I can close the PR and re-do it after the python3 milestone.
