### ISSUE TITLE
Sitemap returning 404

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3404]
The sitemap looks like it's no longer available 

### Evidence / Screenshot (if possible)
Google Search Console:
![image](https://user-images.githubusercontent.com/6251786/80266730-77ef1000-866b-11ea-825b-fe8c1d492ec6.png)

### Relevant url?
- https://openlibrary.org/static/sitemaps/siteindex.xml.gz

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF75
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by the-nine-tail** [comment]
Hello @cdrini by checking the sitemap I came to know that there might be an issue with "http header content-type" it should be application/xml instead of text/html

**Comment by cdrini** [comment]
@the-nine-tail Would you mind creating a new issue for that?

**Comment by cdrini** [comment]
Ah, it looks like the rsync from ol-home (where the sitemaps are generated) to ol-www1 failed: `rsync -av --delete rsync://ol-home/var_1/tmp/sitemaps/sitemaps /1/var/lib/openlibrary/sitemaps/`.

Re-running it fixed it :+1: We're not entirely sure what caused it to fail in the first place, but it might've been a fluke network error perhaps? I re-added it to google search console as well:

![image](https://user-images.githubusercontent.com/6251786/81585518-47ed7f80-9382-11ea-820a-260c4cb1f676.png)

I've created a calendar event to check that this generates correctly at the start of next month to ensure it _was_ a fluke failure.
