### ISSUE TITLE
Book Formats shown as "Absent" on item Admin page

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#341]
Customer support says...

I received email from user:
"This book is checked out and 2 people are on the waiting list.
But, you'll need to log in or open a free account to borrow eBooks from Open library."

Item was on her waiting list, so I updated the loan, which bumped her off (had been waiting for 19 days). When I reviewed the info on the admin borrowing page, all formats were listed as "Absent"
Item:
https://openlibrary.org/books/ia:moveablefeast00hemi_mxe/A_moveable_feast/borrow_admin

It is a DAISY book but also in lendinglibrary and browserlending. I'm able to view the item on the archive following the archive.org ID:
https://archive.org/details/moveablefeast00hemi_mxe

**Comment by guyjeangilles** [comment]
@bfalling Is this still a problem? If so, @mekarpeles I'm defaulting to asking you to be assignee. Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on context: let me know your thoughts

**Comment by mekarpeles** [comment]
I'm going to assume this is resolved, cc: @bfalling. Closing.
