### ISSUE TITLE
ISBN search should return matching edition first, not the general work

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#342]
Searching for ISBN:
Dan Brown Deception Point ISBN 1416524800

The result:
https://openlibrary.org/search?q=1416524800

...which is the overall work when the search is specifically looking for an edition. In a work that might have dozens of editions this isn't a great way to show results.

**Comment by LeadSongDog** [comment]
@bfalling @mekarpeles  This might be complicated by the presence of that ISBN under two editions: it was listed for https://openlibrary.org/books/OL19561918M/Deception_point (2006, Pocket), as well as https://openlibrary.org/books/OL23277453M/Deception_point (2001, Pocket). 

Such ISBN duplications on multiple editions should, by now, be automagically detected and channeled in to some sort of cleanup.

**Comment by mekarpeles** [comment]
To be addressed with our #684 canonical / enhanced works pages. When we render works, we can specify an edition olid in the url (i.e. even if we're rendering works as the unit, there may be an easy way to render the work w/ the desired edition selected)

**Comment by mekarpeles** [comment]
Relates to #684

**Comment by mekarpeles** [comment]
In general, our search results should be more sensitive to matching the correct edition. For this specific issue, the query provided now does resolve to an edition via the openlibrary.org/isbn/xxx api

**Comment by seabelis** [comment]
@mekarpeles Only when there is only one edition with the ISBN. When there are more, you get the work in results. ISBN should not be considered a unique identifier; they are frequently reused by publishers for later editions of the same work, sometimes recycled for entirely different works, sometimes printed by mistake (but once in a book, people will use that to search - mistake or not), and the lending library frequently has multiple copies of the same book.

**Comment by mekarpeles** [comment]
@seabelis I agree; I think it will benefit us to have a new `epic` issue which outlines a strategy of having edition matches in our search results
