### ISSUE TITLE
Uneditable bad date field in author record

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3421]
The author record at the URL below has a `date` key containing the string "(Dmitriĭ Nikolaevich)" which is rendered for display under the author's name, but not editable anywhere.

### Relevant url?
https://openlibrary.org/authors/OL1285518A
https://openlibrary.org/authors/OL1285518A.json

### Steps to Reproduce
1. Click the URL
2. Click the "Modifier" button

* Actual: The field isn't available anywhere for editing
* Expected: The field should either: a) not be rendered or b) be editable.

### Proposal
* Remove the `date` field from the display
* Move contents of any existing `date` fields to birth date and death date

**Comment by hornc** [comment]
@tfmorris , thanks for noticing this. I was able to edit the .yml and correct the invalid date field and linked to Wikidata etc while I was there.

The `date` field is documented as existing for authors in the JSON schema https://github.com/internetarchive/openlibrary-client/blob/1ee0fdf9a229d10f6a7605ea7774b2db834336da/olclient/schemata/author.schema.json#L36  I'm not sure exactly what it's for -- my guess would be a floruit date when exact birth and death aren't know, but it may not be used consistently in the records that have it.

I've fixed the data on this particular record, but there should still be some action taken to resolve the issue as reported. The field should be clarified,  and made editable or removed as suggested above.

**Comment by cdrini** [comment]
As of the Mar31 dump, there are 15,981 author records with that field. Here's a sample:


Key | `date`
-- | --
https://openlibrary.org/authors/OL1004101A | 4th cent
https://openlibrary.org/authors/OL1095882A | ca.
https://openlibrary.org/authors/OL1254270A | 1922
https://openlibrary.org/authors/OL1564104A | fl. 1619
https://openlibrary.org/authors/OL1801919A | fl. 1911-1913
https://openlibrary.org/authors/OL1993469A | ed.
https://openlibrary.org/authors/OL2135268A | fl. 1560
https://openlibrary.org/authors/OL2157040A | fl. 1845
https://openlibrary.org/authors/OL2356113A | fl. 1544
https://openlibrary.org/authors/OL2420377A | 1893
https://openlibrary.org/authors/OL2504017A | fl. 1751-1785
https://openlibrary.org/authors/OL3878100A | 2005-2010
https://openlibrary.org/authors/OL39937A | September 2009
https://openlibrary.org/authors/OL4267611A | fl. 1737
https://openlibrary.org/authors/OL4283381A | jin shi 1778
https://openlibrary.org/authors/OL4357365A | b.1908
https://openlibrary.org/authors/OL4443048A | d.1675

**Comment by tfmorris** [comment]
This appears to have been editable until at least 2010 and was a target for spammers, e.g. https://openlibrary.org/authors/OL583169A/Jacques_Fossey?v=13. The field appears to only get rendered if both the birth and death date are missing.

But the vast majority seem to be dates that were imported from MARC records which weren't considered parseable into a birth date and/or death date, including both florit dates as well forms like "né 1844" and "b.1921", or, less frequently, even more exotic forms like "¹⁸³²⁻¹⁸⁹⁰" 

For cases where the birth and death date aren't populated, moving the raw string to one of them, assuming it can't be parsed, would at least allow users to clean it up.

A more general solution for florit dates and other non-regular forms will needed eventually.

**Comment by SouthGoingZax** [comment]
Would people be happy displaying non-empty date fields in the edit form if the other two date fields are empty, like:

```
$ git diff type/author/edit.html 
diff --git a/openlibrary/templates/type/author/edit.html b/openlibrary/templates/type/author/edit.html
index 054c8da8a..a4dadc3f5 100644
--- a/openlibrary/templates/type/author/edit.html
+++ b/openlibrary/templates/type/author/edit.html
@@ -73,6 +73,16 @@ $putctx("robots", "noindex,nofollow")
                             </div>
                         </div>
 
+                       $if not page.birth_date and not page.death_date and page.date:
+                               <div class="formElement contentQuarter" id="date">
+                                   <div class="label dateLabelAcc">
+                                       <label for="date">$_("Date")</label>
+                                   </div>
+                                   <div class="input deathInputAcc">
+                                       <input type="text" name="author--date" id="date" value="$page.date"/>
+                                   </div>
+                               </div>
+
                         <div class="formElement contentQuarter">
                             <div class="label tipAcc">
                                 <span class="tip">$_('We\'re not storing structured dates (yet) so a date like "21 May 2000" is recommended.')</span>
```

With just a date field:
![image](https://user-images.githubusercontent.com/72705998/100048168-1477bd00-2dc9-11eb-9e8b-793a2c47bf44.png)

And not displaying the date field if one of the other fields is there:
![image](https://user-images.githubusercontent.com/72705998/100048529-e47ce980-2dc9-11eb-858c-4ac1437730db.png)

After deleting the death date and using the form to remove the date field:
![image](https://user-images.githubusercontent.com/72705998/100048014-aaf7ae80-2dc8-11eb-8b99-0703ac4f790a.png)

**Comment by SouthGoingZax** [comment]
@mekarpeles thinks we can just make it editable if it isn't empty, regardless of the state of the other two date-related fields, and not show it if it is empty.  We can also add some text next to it to tell people we're trying to migrate away from it and how they can help.
