### ISSUE TITLE
Applying for a bot account

### ISSUE THREAD

**Issue by manumazu** [internetarchive/openlibrary#3424]
### Question
Hello, could you add my account as bot in order to use the https://openlibrary.org/api/books ressource ?
My user on openlibrary.org is "bibliobot".
Here are IPs of server allowed to request your api :
78.40.125.148 
82.245.203.17

### Additional context
I am working on an application for people who want indexing and share there bookshelf.
This question is for @mekarpeles or @hornc 

Thank you for your nice and open project.

**Comment by mekarpeles** [comment]
Hi @manumazu, the books API shouldn't require a bot account -- only if you're writing values back to OpenLibrary. How many requests do you imagine you'll be making per day?

Open Library also has bookshelves + lists and an API (and the ability to share) is there a reason these aren't sufficient for you?

 are you on our slack? Have

**Comment by manumazu** [comment]
Hi @mekarpeles, using openlibrary for storing bookshelves could be a solution. I don't have any idea about volumetry. I'm working on a prototype. I keep you in touch if we need to register a bot on your API.
Regards
