### ISSUE TITLE
Shorten work/edition URLs

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3425]
### problem
URLs are too long and the tail end of them are not necessary, as they change whenever the book title gets changed. So removing it might let the site run faster and be easier to copy/paste/type in. Shortened versions do work in the same way as the current lengthier ones, so no need to have what's unnecessary around.

### solution - examples
- Work:
now: https://openlibrary.org/works/OL262505W/The_Valley_of_Fear
better: https://openlibrary.org/works/OL262505W/

- Edition
now: https://openlibrary.org/books/OL25000752M/Sherlock_Holmes_the_Valley_of_Fear
better: https://openlibrary.org/books/OL25000752M/

**Comment by seabelis** [comment]
The urls with ID only already work. Having the titles in the url is better for SEO.

**Comment by BrittanyBunk** [comment]
@seabelis that's what I said - it just redirects to a lengthier one, which is time-consuming and also longer to read. However, having the URL lengthier does have the purpose of validating that a person is in the correct spot.

I didn't know that and don't see how, but if there's a purpose, then that's good. However, is there a way to improve the SEO to move away from this if the direction to shorten URLs is chosen?

**Comment by mekarpeles** [comment]
No, the url being verbose and human readable is very important.
