### ISSUE TITLE
Create instructions for handling GitHub issues better

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3426]
### problem
not every issue on GitHub is a priority for the OL to handle. However, it looks like they all are currently. This causes people to work on all issues assuming that they're a part of the OL when they're not, leading to both a waste of time and confusion of what the OL is about.

### solution
Make the GitHub page more professional by adding in instructions at the top of the issues page to let people know to not work on issues unless they're assigned to a team lead and to ask and follow what the team lead says to get it done. Then people won't be working individually, but cohesively.

**Comment by mekarpeles** [comment]
The `Needs: Help` is being used to denote which issues we would like community help with.

**Comment by BrittanyBunk** [comment]
@mekarpeles mind writing that somewhere? I didn't know about that.
