### ISSUE TITLE
When item added to List, list book cover appears first as broken image

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#343]
When you add an item to a list, you pull down a menu and select a list (or create a new one). However once the item is added to a list you should see the list book cover on the page, and instead you see a broken image. Reloading fixes the issue but should probably be fixed on the page.

What it should look like:
![pasted_image_10_9_16__11_37_pm](https://cloud.githubusercontent.com/assets/1231433/19228363/508db586-8e79-11e6-8588-5ec5d7b89810.png)

What it looks like first (before reloading):
![pasted_image_10_9_16__11_37_pm](https://cloud.githubusercontent.com/assets/1231433/19228373/676a904e-8e79-11e6-88ce-4c839ad075f5.png)

**Comment by salman-bhai** [comment]
Is this Issue done @mekarpeles ?

**Comment by mekarpeles** [comment]
I believe so... Will re-open if there's been a regressions
