### ISSUE TITLE
VIAF & Wikidata IDs being added to redirect records

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3431]
Months after a [bad merge](https://openlibrary.org/authors/OL42906A?_compare=Comparer&b=5&a=4&m=diff) by Jeff Kaplan, `Cleanup Bot` added VIAF and Wikidata IDs to the remaining stub redirect record.

Not sure how widespread this problem is.

### Relevant url?
https://openlibrary.org/authors/OL42906A?_compare=Comparer&b=6&a=5&m=diff

### Expected Behavior

1. If bots use offline data from a batch process, they should confirm that it's still accurate when they do the live edits.
2. Redirect records (`/type/redirect`) should **never** be the target of updates, except to revert the redirect.

### Stakeholders
@hornc @mekarpeles

**Comment by hornc** [comment]
I am no longer using automation to add identifiers to OL records. The specific example in this issue now has the correct ids.

Future automation should check for redirects before making edits as suggested above.
