### ISSUE TITLE
Add more separation in the UI for editing books

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3433]
### problem
When editing an edition, some edits appear at the work level. People can't tell while editing the edition that this will happen. 

### solution
Separate work and editions changes from each other very clearly and distinctly so people understand what changes will impact works and which will impact editions.
https://openlibrary.org/books/OL7209142M/Comedies_with_an_introd._by_G.S._Street/edit

Visual:
![image](https://user-images.githubusercontent.com/55302685/80868260-41f2f280-8c4e-11ea-8c16-cf0b1cced1a0.png)

**Comment by guyjeangilles** [comment]
"Links" for specifics can still be useful. I.e special audiobooks links.

**Comment by BrittanyBunk** [comment]
@guyjeangilles I never said it wasn't. These columns shouldn't be available when editing an edition, because they show up on the works page

**Comment by LeadSongDog** [comment]
@BrittanyBunk Can this be closed now? I looks to me to have been completed. The three tabs you crossed out are now replaced by a single link to the work edit page.

**Comment by BrittanyBunk** [comment]
@LeadSongDog yes. It...looks...awesome! Thank you everyone!
