### ISSUE TITLE
search-inside result-links should add the original query-term to the Archive-URL-hash for readable items

### ISSUE THREAD

**Issue by waldenn** [internetarchive/openlibrary#3439]
Currently when following the inside-results for readable books on Archive.org, the original query is not appended to the Archive.org URL hash. This causes the inside results to now show up. I think this is a bug, as this is the point of inside search. This feature can save a lot of time.

### Evidence / Screenshot (if possible)

https://openlibrary.org/search/inside?q=%22Gobiidae%22&language=eng

### Relevant url?

The readable results items should get a "#mode/2up/search/"Gobiidae" appended to their links, so the Archive.org reader can show the match positions inside the book.

* Actual: no "#mode/2up/search/"query" is appended: https://archive.org/stream/reviewofgobioidf00wint#mode/2up
* Expected: the hash should be appended: https://archive.org/stream/reviewofgobioidf00wint#mode/2up/search/%22gobioid%22

Thanks for an awesome project!!

**Comment by mekarpeles** [comment]
"See All" results looks like it is accurately appending the search and the hash. Can you please double check and possibly include a very short video / screen share of what's happening in your browser? Or is there a different link you're talking about? e.g. the "Read" button? Thank you!

**Comment by waldenn** [comment]
Ah yes, I did not even notice the "See All Results" link. Sorry. Good to see the feature is already there.

However IMHO, there should just be the read button in this "inside search". It would clean up the list of book rows (without those repetitive links), and not surprise others as it did for me. I expected to see the results when clicking on that  button AFTER using the "searching inside" interface. Make it easy for the user. Ideally: then also provide an option to clear the markers by clearing the "search inside" input-field and pressing ENTER / clicking submit.

Thanks!!

**Comment by guyjeangilles** [comment]
Gonna close for now, we can open a new UX issue if need be
