### ISSUE TITLE
OL Admin merge page produces malformed URLs

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#344]
If you go to a merge page from Open Library like this one:
https://openlibrary.org/authors/merge?key=OL946631A&key=OL6896893A

All of the links to items have malformed URLs like this:
https://openlibrary.org/works/works/OL4616559W (note duplicated 'works')

Actual URL format should be this:
https://openlibrary.org/works/OL4616559W

**Comment by hornc** [comment]
@bfalling This looks to be fixed now? I was looking for something quick to attempt to from the projects page and saw this, but the first link no longer has duplicate 'works'. I couldn't find the exact fix commit because there has been so much activity recently :)

**Comment by mekarpeles** [comment]
Yup! I believe this bug has been resolved. Thanks for catching this. I can send a message to #openlibrary-g on slack with a list of low hanging fruit if that would be helpful, would love to team up on some of our open bugs :)
