### ISSUE TITLE
Switch Continuous Integration to use Docker

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3443]
~Fixed in #4242~

Using docker in ~Travis~ GitHub Actions would save time by catching errors that will break the build environment, as well as by being a stepping stone to allowing us to use ~Travis~ GitHub Actions + testcafe for UI testing (#3412).

~See https://docs.travis-ci.com/user/docker/~

### Stakeholder
@cclauss

**Comment by cclauss** [comment]
I have always found mixing Docker and Travis to be limiting but I am OK with it as long as:
1. There is one DockerThat supports both Python 2 and Python 3, and
2. Travis continues to run both Py2 and Py3 tests on all PRs.

**Comment by cdrini** [comment]
Ooops, meant to put #4382 on sprint

**Comment by cclauss** [comment]
https://docs.docker.com/build/ci/github-actions/

**Comment by mekarpeles** [comment]
After talking to @cclauss we decided to close
