### ISSUE TITLE
Add To Staff Picks button not working for librarians

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3445]
The toolbar at the top of the edit view for editions displays Add to Staff Picks, but throws Permission Denied error if one is logged in as a librarian.

### Steps to Reproduce

1. As a librarian, go to any edition with IA ID
2. Do click Add to Staff Picks

* Actual: Permission Denied
* Expected: Added successfully

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 81.0.4044.129 (Official Build) (64-bit)
- **Operating system?** MAC OS Catalina
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @dcapillae

**Comment by dcapillae** [comment]
Is the "Add to Staff Picks" button for us librarians? I tried to use it once and got the same result (Permission denied).

**Comment by seabelis** [comment]
> Is the "Add to Staff Picks" button for us librarians? I tried to use it once and got the same result (Permission denied).

At first I thought not, but as it turns out, it is supposed to work for us.

**Comment by dcapillae** [comment]
What happens if a book is added to the staff picks? Should I follow any specific criteria? I guess the selection depends on the experience and criteria of the librarians, doesn't it?

**Comment by seabelis** [comment]
@dcapillae It will add it to the hope page carousel called books we love. As far as criteria goes, @mekarpeles needs to answer that.
