### ISSUE TITLE
Add a search bar to individual author pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3446]
### Describe the problem that you'd like solved

Some authors have hundreds of books. Let's add a search bar (similar to how https://openlibrary.org/collections/Marley-Dias-1000BlackGirlBooks-Library has a pre-populated search box) to enable patrons to better filter author work results.

### Related Files
- Authors page template: https://github.com/internetarchive/openlibrary/blob/a547d62016578a263b6814e725ade08478718f21/openlibrary/templates/type/author/view.html
- The way the search field exists on /collections/Marley-Dias-1000BlackGirlBooks-Library : https://github.com/internetarchive/openlibrary/blob/c485124f02cf89c02efb9b231d3906a79df3505a/openlibrary/macros/QueryCarousel.html#L13-L18

**Comment by jsparmani** [comment]
@mekarpeles I would like to work on the issue!

**Comment by guyjeangilles** [comment]
@jsparmani Awesome! Feel free to make a pull request with your solution

**Comment by shaswa123** [comment]
Hey,
I would love to know if this issue is still being worked on or not
