### ISSUE TITLE
Lists not working

### ISSUE THREAD

**Issue by LongJohn-Silver** [internetarchive/openlibrary#3448]
I can only add something to a list when I create one, after that I click on "add to list" but nothing happens. I tried this on my daily browser, Firefox v.76 (which quite a few extensions and is hardened for privacy on the regular settings plus some extra tweaks on the about:config), since my setup may be interfering with it, I tried some other browsers (Waterfox v.2020.04 and Chromium V.80.0.3987.162) but it's still not working.

### Relevant url?
Not applicable.

### Steps to Reproduce
1. Go to some author's page
2. Click on "Add to list"
3. Select a list

* Actual: Author does not add to the list
* Expected: Author adds to the list

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Hardened Firefox v.76, Waterfox v.2020.04 and Chromium V.80.0.3987.162
- **Operating system?** Debian 10 Buster
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
The proposal would be that you could add authors to lists, although as mentioned on my other issue, I think this should be changed altogether, but that's another topic.

**Comment by mekarpeles** [comment]
We tried with https://openlibrary.org/authors/OL34184A/Roald_Dahl on an existing list and by creating a new list and both seemed to work form the authors page. However, there was some funky javascript i18n errors with the display / count which fixed after refresh.

Can you record a short video clip / screen share of what you're trying and what the outcome looks like? Thank you!

**Comment by guyjeangilles** [comment]
I was able to add https://openlibrary.org/authors/OL7350596A/Nnedi_Okorafor to an existing list as well. I'm gonna close this for now. Will reopen if @LongJohn-Silver provides some more evidence

**Comment by LongJohn-Silver** [comment]
I created a gif, sorry if it's not the best thing in the world but I'm doing what I can. After I choose the list I want the book to be added, it just closes the new window and it doesn't do anything.

https://upload.vaa.red/4ef6N#c67aaab2a19faf1f30d7e3f65fa5bc8f

**Comment by LongJohn-Silver** [comment]
Any updates?
