### ISSUE TITLE
Being able to follow other users

### ISSUE THREAD

**Issue by LongJohn-Silver** [internetarchive/openlibrary#3449]
I would like to be able to follow other users.

### Describe the problem that you'd like solved
Being able to follow users.

### Proposal & Constraints
Adding a button to follow X or Y user.

### Stakeholders

**Comment by mekarpeles** [comment]
We do have a feature in progress for following patrons: #1966. We'd love help on this (though we'll want to scope out the next steps together, if possible). There is a sql model already (on production even) to support this feature. See the PR associated w/ 1966.

**Comment by mekarpeles** [comment]
@LongJohn-Silver, can we please continue this discussion on #739? Closing this issue as a duplicate.

**Comment by LongJohn-Silver** [comment]
> @LongJohn-Silver, can we please continue this discussion on #739? Closing this issue as a duplicate.

Sure, thanks, and sorry that I created a duplicate, and search for a similar issue but nothing popped up or I didn't noticed it.
