### ISSUE TITLE
Q: How to perform database migrations?

### ISSUE THREAD

**Issue by rafaelalvessa** [internetarchive/openlibrary#3451]
### Question
How to do a database migration?

### Additional context
I've made a change to the DB that requires a DB migration.  I followed the [Wiki page](https://github.com/internetarchive/openlibrary/wiki/Getting-Started#database-migrations) and took these steps:

```sh
$ docker-compose exec web bash
```

Once inside the Docker container (I suppose `ol-db1` is the correct DB):

```sh
$ scripts/migrate_db.py ol-db1
```

I then get this error:

```py
Traceback (most recent call last):
  File "scripts/migrate_db.py", line 129, in <module>
    main()
  ...
  File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  role "root" does not exist
```

I also tried to use `psql` with a different user/role – using `openlibrary` – but I don't know the password.  Not that it would make any different because the script `migrate_db.py` still uses `root`.

**Comment by jimchamp** [comment]
I don't think that `migrate_db.py` is in use these days.  If one were to use it to migrate to another version, they would have to do the following:
1. Add a `upgrade_015` function that takes a reference to the `db` and updates all of the necessary tables.
2. Increment `LATEST_VERSION` to 15
3. Run the script.

Recommend that any such changes are made after creating a new DB container.  After the changes are made, the `pg_dump` file that is used to populate local instances will need to be updated.  This can be done be running [this script](https://github.com/internetarchive/openlibrary/blob/master/scripts/dev-instance/create-dev-db-pgdump.sh).
