### ISSUE TITLE
Support private lists

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3456]
### Describe the problem that you'd like solved

Currently OpenLibrary supports two different kinds of lists (cf #851):
1.  three standard "Reading Log" lists which contain only books, and 
2. an unlimited number of user created lists which can include works, editions, authors, & subjects

The first class of lists is private by default and can be made public if the user desires. For the second class of lists, the user has no access control at all and all lists are forced to be public.

### Proposal & Constraints

The same access control model should apply to both types of lists with the user having control over whether or not they are publically available. While a single global private/public switch could be used (e.g. the existing one), it might be desirable to allow users to make individual lists public if they so desire, so that they have finer-grained access control.

**Comment by mekarpeles** [comment]
This month we plan on switching reading logs to public by default (which is how goodreads an many other platform operate), with the exception that we will emphatically continue to support a private setting for anyone who so chooses.

Lists, themselves, have public since their inception circa 2010: http://blog.openlibrary.org/2010/12/15/lists-are-here/ and http://blog.openlibrary.org/2010/09/07/lists-are-coming/

I think the spirit of lists are to be public and if one wants a private mechanism for tracking personal books without implicating themselves, like what they're reading, the reading log serves this purpose

**Comment by mekarpeles** [comment]
Unless the community in large feels very strongly about private lists (feel free to still post on this thread), I am closing as 'will not fox'

**Comment by dyeray** [comment]
I also think private lists would be a nice feature. I currently use several private lists in Goodreads (I don't use public lists actually), but I was considering switching to Open Library for privacy reasons.

**Comment by Gunther0042** [comment]
This is a feature I would very much appreciate. I like dividing my "Want to Read" books into subject categories and the only way to do this currently is with lists. I am fine with lists being public by default but it would be great to have the ability to make a list private. I suppose adding a way to tag and filter books within the reading log lists would also effectively provide the functionality I am looking for, but I imagine that would be a harder change.

**Comment by mekarpeles** [comment]
@Gunther0042 -- We have #2819 planned for this year which may solve some of the problem. For now the plan is still to keep lists public.

**Comment by tfmorris** [comment]
> Unless the community in large feels very strongly about private lists (feel free to still post on this thread)

Instead of depending on people finding a closed issue to voice their support, perhaps this could be included as a survey question for users the next time one of the super intrusive top-of-every-page surveys is run? That would generate the data needed to understand how much priority to give this request.

**Comment by dyeray** [comment]
I don't want to contribute spam, but if you ask me even a survey would be a bit of a selection bias. The people that need private lists are not on openlibrary, they are on other platforms that do offer this feature.

**Comment by rturquier** [comment]
I use lists to keep track of books that I’ve borrowed or lent. This is not intended to be public, and I would strongly prefer a private setting if it were available. I hope this feature will get implemented at some point!

**Comment by beancaper** [comment]
Just chiming in to say that I'd also really like to have private lists!

**Comment by tfmorris** [comment]
Note that although Goodreads doesn't allow making individual lists private, if you make your profile private, then ALL your lists are private and only visible to friends.

https://help.goodreads.com/s/question/0D58V00008DnYW6SAN/how-do-i-make-my-reading-list-private

Private profiles would be another way to address this feature request.
