### ISSUE TITLE
Author merge UI selects first listed author by default

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3469]
By automatically selecting  the first listed author by default, the chances of accidental incorrect merges are high. To avoid merging the first listed author, one must double opt out by changing the merge target AND removing the selected check box.

### Evidence / Screenshot (if possible)
I searched Sandra Brown for merging. Janet Daily is selected by default.
<img width="776" alt="Screenshot 2020-05-16 at 19 01 32" src="https://user-images.githubusercontent.com/17739465/82125664-b4fc7d00-97a7-11ea-9c36-a0c3f21edab3.png">

### Steps to Reproduce

1. Search an author.
2. Click merge authors.

* Actual: First listed author is selected by default.
* Expected: Nothing should be selected by default. Only the user should choose which profiles to merge.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@tfmorris @dcapillae @cdrini @mekarpeles @leadsongdog

**Comment by LeadSongDog** [comment]
#668 discussed this problem

**Comment by tfmorris** [comment]
Yes, this is a duplicate of #668. See my comment from Feb. 2018 https://github.com/internetarchive/openlibrary/issues/668#issuecomment-369307926 for some proposed fixes.

**Comment by seabelis** [comment]
Closing as this is a duplicate of #668.
