### ISSUE TITLE
Home page "Books to Borrow" list includes checked-out books

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#347]
On the home page, no checked-out books should appear under "Books to Borrow", to avoid frustrating users.

**Comment by jessamynwest** [comment]
This usually only happens when something on the main page has gotten out of sync. Let's see if we can reproduce.

**Comment by mekarpeles** [comment]
This has been resolved for now -- our popular books is static (comes from json ~2000 books).
We also now use the archive.org API availability API to dynamically check and filter works/editions based on their availability. See https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/availability.js

What should happen is we should create a custom Subject (type) with all of these books in them and then dynamically load them as we do any other subject.

For now, marking this as closed
