### ISSUE TITLE
Merged work IDs do not appear in edition histories

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3474]
When a work is merged and the edition is migrated, viewing previous versions of that edition does not show the previous work ID. Sometimes, in cases of incorrect merges it would be useful to see or restore the previous work. This is only possible if one knows the ID.

### Describe the problem that you'd like solved
When an edition is moved, it's history should display the work ID it was moved from, even if that work has been merged.

### Additional context
Example of an edition that's been migrated and the original work merged.
https://openlibrary.org/books/OL27769174M/Through_the_Magic_Door
Looking at the version prior to the move indicates this was associated only with itself. I know this is not the case. The work ID it was merged from should be somewhere in the history. https://openlibrary.org/books/OL27769174M/Through_the_Magic_Door?v=2

**Comment by LeadSongDog** [comment]
@seabelis When you say merged, was this a manual edit of the edition record to refer to a different work record, or was it something else?  I would think it should be possible to auto comment the edition history with old one new work ids, but they do show at https://openlibrary.org/books/OL27769174M/Through_the_Magic_Door?_compare=Compare&b=3&a=2&m=diff

**Comment by tfmorris** [comment]
@seabelis Both the new and old work IDs are show here: https://openlibrary.org/books/OL27769174M/Through_the_Magic_Door?_compare=Comparer&b=3&a=2&m=diff

You have to build the URL by hand, but if you go to the work history, 
https://openlibrary.org/works/OL20344623W?m=history
you could navigate to an earlier version like https://openlibrary.org/works/OL20344623W?v=2 and restore it, then revert the edition record to undo a merge.

**Comment by seabelis** [comment]
@tfmorris @LeadSongDog Yes, that's actually what I need. I was looking at the actual record rather than the change, so https://openlibrary.org/books/OL27769174M/Through_the_Magic_Door?v=2 does not actually show the work ID if you hover over the "1 edition" link.
