### ISSUE TITLE
Cleanup bot adding edition contributors as work authors

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#3478]
### Relevant url?

https://openlibrary.org/works/OL15346397W/El_ingenioso_hidalgo_Don_Quijote_de_la_Mancha?_compare=Compare&b=75&a=74&m=diff

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: edition contributors showed as work authors
* Expected: only the work author should show on the work record

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by tabshaikh** [comment]
Cleanup Bot is @hornc personal bot so that problem might have been fixed since.
