### ISSUE TITLE
Incorrect READ buttons on carousels

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3479]
User-generated carousels using Work IDs display READ buttons if print-disabled items are available.

### Evidence / Screenshot (if possible)
<img width="412" alt="Screenshot 2020-05-26 at 18 30 06" src="https://user-images.githubusercontent.com/17739465/82926065-ef6fd200-9f7e-11ea-9e22-571f0245c000.png">

### Relevant url?
https://openlibrary.org/collections/read-the-movie
The two works listed at the top should display BORROW buttons, for example.

### Steps to Reproduce

1. Create a collection page.
2. Add some work IDs that have a mix of borrowable and print-disabled editions.

* Actual: READ button displays for works with print-disabled items.
* Expected: BORROW buttons should display unless public domain copies are available.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by shucon** [comment]
I'm starting to work on this.

**Comment by shaswa123** [comment]
Hey,
I just want to know if someone is still working on it or not.

**Comment by shucon** [comment]
Yes I'm working.

**Comment by mekarpeles** [comment]
I think this is now resolved with the refactors to `LoanStatus`.
