### ISSUE TITLE
Author search results page shows outdated information

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#349]
Example search: **https://openlibrary.org/search/authors?q=Xavier+Bichat**

In the database, these authors who are all the same have been merged. Merge author page offers no options for merging.

https://openlibrary.org/authors/merge?key=OL1171828A&key=OL6000744A&key=OL6088346A&key=OL4327928A&key=OL4327922A&key=OL6059391A

Clicking through to any of the individual pages goes to the main author page here.

https://openlibrary.org/authors/OL1171828A/Xavier_Bichat

Unclear why this page is showing up with six entries.

**Comment by LeadSongDog** [comment]
If an external text links to https://openlibrary.org/authors/OL6000744A they should be redirected to https://openlibrary.org/authors/OL1171828A/Xavier_Bichat right? The real question is: "Why do individual results from the search still show one associated work by  e.g. https://openlibrary.org/authors/OL6000744A/Xavier_Bichat  after the author merge?" 
I've cleaned up some, but that was a perfect storm of diacritics, variant work spellings, translations, multiple volumes, variant author spellings, subsequent critical analysis, etc. so there were many work records for each work. These will still have to be merged, but their titles are mostly standardized now.

**Comment by skylerbunny** [comment]
+1. This isn't necessarily related to an author merge, either. Example: author OL7366872A has two works associated with them, OL17626020W and OL17626019W. However (possibly related to issue #351 ?, if you look for the title 'Bait and Switch' explicitly, you will find OL17626019W in the list but as 'By unknown author' If you then click INTO the book, you'll find that it is in fact associated with the author entry above, but search never reflects this change, and will never allow the book to be searched by author.

**Comment by skylerbunny** [comment]
I'm going to create a new issue for what I've identified. Looking through the code I realize that 'merging an author' doesn't appear to use the same code path as creating a new book, so I'll address what I've found in a new issue.

**Comment by LeadSongDog** [comment]
@Skylerbunny did you create a new issue? Which?

**Comment by mekarpeles** [comment]
Related to #699 essentially: broken or stale author search

**Comment by hornc** [comment]
I _think_ this is another example of what https://github.com/internetarchive/openlibrary/pull/861 fixes, so this should no longer occur :crossed_fingers: 

Some of the old data that has persisted may need to be manually added to solr to force a reindex. At least now manually adding the keys via the admin/solr interface will do the correct thing, previously they would still not be removed.

@LeadSongDog,  I would love confirmation that this has improved, and I'd be happy to trigger a manual reindex of any author OLIDs if you can provide a list. I'll be keeping an eye out too, and am trying to think of a good way to collect all deleted or redirected authors that have so far missed removal from solr. 

@skylerbunny Did you raise an issue outlining what you find out about merges? It sounds like you may have noticed something else that I haven't.

**Comment by LeadSongDog** [comment]
@hornc Not sure if it's better or not. Should it already be running on production?  

1) For instance, this morning I did some changes at OL35246A, including disinverting his name.  As you can see, it still shows the inverted author name for each work listed at https://openlibrary.org/authors/OL35246A/William_Henry_Brown 

2) Further, the works shown on the author page do not reflect changes that do show when you click through, e.g. the 1963 "Organic chemisty" [sic] which was by a different author entirely, as is now seen at https://openlibrary.org/works/OL16120915W/Organic_chemistry

3) The edition counts shown on the Author page do not agree with (they lag) the edition counts shown on the listed Work pages. The "What work is this an edition of" dropdown has the same lagging edition count.

4) Searching either "Title" or "All" for "Organic chemisty" still shows the author as William Henry Brown vice the now-corrected Frederick G. Bordwell which shows once you click on the found work.

**Comment by hornc** [comment]
@LeadSongDog 1,2, and 4 are about Work searches, and still open issues.  I don't think there is currently any attempt to re-index Works when an author is edited. I have created a new issue #891 for those. This issue is about Author search results not updating when authors are edited. Merged, deleted authors were not being removed from search results, #861 fixed that specific issue.

The example Author search in the description above still shows one "Please see Xavier Bichat"  author that hasn't been removed, but that is part of the already existing  #628 issue.

I think the Author search results showing outdated author results is fixed.

**Comment by LeadSongDog** [comment]
@hornc Thank you, that makes sense.
