### ISSUE TITLE
Error when searching for a book title with french accent.

### ISSUE THREAD

**Issue by drupol** [internetarchive/openlibrary#3491]
Link: https://openlibrary.org/search?q=M%C3%A9thodes+de+la+th%C3%A9orie+des+fonctions+d%27une+variable+complexe&mode=ebooks&has_fulltext=true

Error:

`/opt/openlibrary/deploys/openlibrary/1e724d8/openlibrary/templates/work_search.html: error in processing template: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128) (falling back to default template)`

**Comment by LeadSongDog** [comment]
Related: #135 #667 #1808

**Comment by tfmorris** [comment]
@LeadSongDog I don't think any of those are actually related.

This is just a garden variety internationalization bug. It's trying to interpret UTF-8 as ASCII.
