### ISSUE TITLE
Archiving url with Russian characters doesn't display PDF (Wayback Machine)

### ISSUE THREAD

**Issue by Melonadev** [internetarchive/openlibrary#3492]
### Relevant urls

**Archived**:
https://web.archive.org/web/20200605023059/http://xn--b1aanbebkbbpfqcbebcaoyded7a1etm.xn--p1ai/tribuna/kachesov.pdf

**Current (original url)**:
http://xn--b1aanbebkbbpfqcbebcaoyded7a1etm.xn--p1ai/tribuna/kachesov.pdf
or
союзмосковскихкомпозиторов.рф/tribuna/kachesov.pdf

### Steps to Reproduce

1. Search the **original url** above in [Wayback Machine](https://archive.org/search.php?query=).
2. Go to any snapshot.

* Actual: The Wayback Machine displays its homepage as its captured page.
* Expected: The Wayback Machine displays the actual PDF.  [Here](https://web.archive.org/web/20160927001627/http://cits.tamiu.edu/kock/pubs/journals/2016JournalIJeC_WikipediaEcollaboration/Kock_etal_2016_IJeC_WikipediaEcollaboration.pdf)'s a successful example.

### Details

- **Issue persists both logged in and logged out, even with uBlock Origin disabled**
- **Microsoft Edge Version 83.0.478.44 (Official build) (64-bit)**
- **Windows 10 Home Single Language, 64-bit operating system, x64-based processor**
- **RAM 4.00 GB (3.88GB usable)**
- **Processor Inter(R) Core(TM) i5-8250U CPU @ 1.60GHz  1.80 GHz**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Unrelated to Open Library; @mekarpeles can you notify the Way Back Machine folks?
