### ISSUE TITLE
Mobile Sidebar 

### ISSUE THREAD

**Issue by tabshaikh** [internetarchive/openlibrary#3493]
Whenever we access OL on a mobile device a menu bar with a small number of options is currently presented and all the cool features we add is hidden and does not surface to the top. 

### Proposal & Constraints

We would want to redesign the menu bar to open in form of a sliding side bar so that we can have a complete menu for our users

https://www.figma.com/proto/ExZAre2gj07FukhtWeqSyR/ol-sidebar?node-id=1%3A22&scaling=scale-down

### Additional context

https://www.figma.com/file/ExZAre2gj07FukhtWeqSyR/ol-sidebar?node-id=0%3A1

### Stakeholders

@jdlrobson

**Comment by jdlrobson** [comment]
If you go this route I'd recommend looking at what we do on Wikipedia mobile which uses a CSS only solution via the checkbox hack.

Also please make a decision with #1514 prior to this change.

**Comment by jdlrobson** [comment]
What items are missing from the menu on mobile? I have had a quick glance and I don't see anything missing..

**Comment by guyjeangilles** [comment]
@tabshaikh Can you answer Jon's question?

**Comment by Yashs911** [comment]
@tabshaikh @jdlrobson Any update on this.

**Comment by mekarpeles** [comment]
The figmas are no longer accessible -- @tabshaikh I'm closing this issue, feel free to re-open if you have access to the figmas to share
