### ISSUE TITLE
Stored XSS at https://openlibrary.org/authors/some-author-page in "Alternative names" section

### ISSUE THREAD

**Issue by MaorDayanOfficial** [internetarchive/openlibrary#3499]
### Evidence / Screenshot (if possible)
https://i.imgur.com/6WgJglf.png
https://i.imgur.com/zUB8AtH.mp4

### Steps to Reproduce

1. Click edit in the author page
2. Write the payload in "Does this author go by any other names?" like: 
`<svg onload=alert(document.domain)>`
and click "Save"

* Actual: Stored XSS has been executed
* Expected: Stored XSS has been executed

### Details

- **Logged in (Y/N)?** - Yes
- **Browser type/version?** - Chrome | Firefox Mozilla | Safari
- **Operating system?** - Windows | macOS | Linux
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
 Encode the section

**Comment by Yashs911** [comment]
@MaorDayanOfficial @xayhewalo  I guess we can close this issue.
![image](https://user-images.githubusercontent.com/64412143/104615314-23833900-56af-11eb-9449-41c8e822f1ad.png)
