### ISSUE TITLE
Add standalone endpoint for creating Authors 

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#352]
Should create a separate dialog https://openlibrary.org/authors/add and get it out of the dialog https://openlibrary.org/books/add where it causes nothing but trouble.

**Comment by jessamynwest** [comment]
This is a very good idea.

**Comment by mekarpeles** [comment]
Is the suggestion to implement Authors in a similar way to how we do bookcover images?

**Comment by LeadSongDog** [comment]
I would think that author records should not be dependent on work records nor edition records. Ideally, a user would enter a name or an external identifier such as LC Auth, VIAF or ISNI and these would be queried. The responses would be compared to existing OL A records for near matches. If none is convincingly close, a new OL A record would be created from these, while disinverting word order as needed.

**Comment by mekarpeles** [comment]
updated title: the endpoint could be similar to bookcovers: e.g. https://openlibrary.org/authors/add

**Comment by jessamynwest** [comment]
Just need to make sure there's some sort of check to not add authors where there is one extant. Some sort of fuzzy search that will get all the variants of an author's name? I still think this is a good idea but as a use case needs to make sure it preserves authority control.

**Comment by LeadSongDog** [comment]
Should have at least (forename or init ) + surname + ( one date or VIAF or Isni or similar) to create, and no matching extant author record

**Comment by tfmorris** [comment]
Disallowing creation of new author records altogether would be the "perfect" solution and it sounds like the direction we're headed with the last couple of comments.

I disagree that making the flow more convoluted and difficult would be an improvement. I'd much rather see the effort put into fixing search and giving the users other tools to effectively tell whether "their" author is already in the system.

**Comment by LeadSongDog** [comment]
Not convoluted. User wants to add a book. Who is it by?  Search for authors like their entry. One of these (with details shown) or new? (Should be well under 10% new). We know these works by that author, one of these, or new?  Ok, now Tell us about your edition: title if different from work, got an identifier, or publisher and date? 
Simple flow, but follow the hierarchy you are trying to build.

**Comment by LeadSongDog** [comment]
@mekarpeles I’ve never understood the point of a Needs:Help tag that doesn’t identify the help needed.  That said, what’s the sticking point?

**Comment by mekarpeles** [comment]
Adding to staff call for discussion today, ty

**Comment by mekarpeles** [comment]
After staff call we decided the action was to discuss authors in next week's community call which is May 10th

**Comment by mekarpeles** [comment]
Since this issue was created, I believe there's now autocomplete on /book/add which allows the patron to both choose an existing author or create a new one. During the community call there was feedback from @cdrini + @seabelis that for now this issue should be closed (and re-opened as new arguments come up which make this endpoint necessary)

**Comment by cdrini** [comment]
To expand on that, we don't believe this is really blocking #2500 .  #2500 is mainly blocked because our author model currently has some issues. The bigger one being a _lot_ of disambiguation/conflation problems. Adding contributors as `OL...A` ids without better tools would add to this problem _drastically_. Also, we have a problem of authors being stored on both works/editions in a poorly defined manner. I think #2500 needs some data/implementation proposals that address these issues.

**Comment by LeadSongDog** [comment]
@mekarpeles No, the /book/add is not a solution. Try for instance to add the Google eboock 0LogkAEACAAJ and you quickly realize the type ahead cannot show even a fraction of the 450-ish records for authors named  "William Alexander".  We need to pry /author/add away from /book/add and address it directly in one place. DRY

**Comment by jessamynwest** [comment]
Yeah we need a simpler way to get at authors generally. I can not comment on whether this is or is not blocking 2500 but controlled vocabulary is tricky and the book/add flow is highlighting one of the concerns.

**Comment by LeadSongDog** [comment]
@mekarpeles Please explain why you closed this, or reopen. We still have no clean way to create an author record. DRY says this functionality should not reside in both works/add and books/add code.
