### ISSUE TITLE
is there a JSON API for inside search results?

### ISSUE THREAD

**Issue by waldenn** [internetarchive/openlibrary#3532]
### Question

Is there a JSON API URL for inside-search requests? I could not find it in the API documentation. Adding ".json" to the end of "inside" does not work here.

The HTML search URL is: [https://openlibrary.org/search/inside?q=%22stocked+with+wine-related+goods%22&mode=ebooks&has_fulltext=true](https://openlibrary.org/search/inside?q=%22stocked+with+wine-related+goods%22&mode=ebooks&has_fulltext=true)

I would have exepected this to work for JSON output: [https://openlibrary.org/search/inside.json?q=%22stocked+with+wine-related+goods%22&mode=ebooks&has_fulltext=true](https://openlibrary.org/search/inside.json?q=%22stocked+with+wine-related+goods%22&mode=ebooks&has_fulltext=true)

Thanks!

**Comment by tfmorris** [comment]
It's just a wrapper for the Internet Archive search API, so you could use that.

**Comment by waldenn** [comment]
Are you sure about that?

Can you give me a link that returns the JSON results (including the text snippets) for the query "stocked+with+wine-related+goods"?

This [query](https://openlibrary.org/search.json?q=%22stocked+with+wine-related+goods%22) returns nothing.

**Comment by mekarpeles** [comment]
@waldenn yes -- OL uses a special version of Archive.org's API which only it can access within the network. We have a PR (#4044) which should allow json access

**Comment by waldenn** [comment]
Excellent, thanks Michael and others for your great work!

**Comment by tfmorris** [comment]
@waldenn The API I was talking about was this: https://archive.org/advancedsearch.php?q=stocked+with+wine+related+goods&fl%5B%5D=identifier&sort%5B%5D=&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&output=json&callback=callback
but it doesn't return the same results as: https://archive.org/search.php?query=stocked+with+wine+related+goods&sin=TXT
which doesn't appear to offer a JSON output option.

It's weird, but I guess not surprising, that the Internet Archive has proprietary APIs that they don't offer to the public.
