### ISSUE TITLE
Books Page Issues (following Canonical Books Launch)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3561]
- [ ] (TODO) Issues relating to list (post Canonical Books Page launch) #3607 

- [x] (TODO - remove the initial perspective ) trapezoid-shaped cover looks distorted
<img width="255" alt="Screenshot 2020-07-08 at 17 00 01" src="https://user-images.githubusercontent.com/17739465/86934965-9e85f880-c13c-11ea-9cfa-f3f798d8196c.png">

- [x] (TODO - place on new line) Edition subtitles and edition information should not be on the same line.
<img width="672" alt="Screenshot 2020-07-08 at 17 04 35" src="https://user-images.githubusercontent.com/17739465/86935459-253ad580-c13d-11ea-9523-90666ca63dad.png">

- [ ] (TODO) Work subtitles do not appear on work record or in work record's history.  **!Important**

- [x] (TODO) From search results page, clicking "X editions" should go to the top of the editions list, above the drop-down. It currently goes to the middle of the list.

- [ ] (TODO) Font-size too small for several patrons (there's been a regression on the author's page)

- [x] Work covers still exist, but are not editable.

- [ ] Sync button appears on works URL but only editions should be sync-able.

- [x] Searching by IA ID, example celerystalksatmi0000howe, goes to incorrect edition. **!Important**

- [ ] (Forms submits on save ... ) After saving an edit, user should be returned to the same url they started from. For example if an edit is made from the work url, they should not be redirected to an edition url after saving an edit.

- [x] (TODO) An edit button should be next to the edition details at the bottom of the page. It is usually there that one notices an edit needs to be made. User currently has to scroll back up to the top to reach the edit button.

- [x] (TODO) All edition details should be in one place, even if this means repeating on the page. This block should indicate which edition the details belong to without user having to scroll back up to the top to locate that info.
<img width="699" alt="Screenshot 2020-07-15 at 10 29 11" src="https://user-images.githubusercontent.com/17739465/87524909-15fddf80-c689-11ea-9db2-e0b72fb85cd9.png">
    - Add edition title/publisher/etc to the edition details box

- [ ] (TODO New issue) Bullet points do not render in descriptions

- [x] #3760 Orphaned editions throw errors. 
/opt/openlibrary/deploys/openlibrary/9cdb75d/openlibrary/templates/type/edition/view.html: error in processing template: TypeError: %d format: a number is required, not instance (falling back to default template)
https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?edition=

- [x] Some works throw `error /opt/openlibrary/deploys/openlibrary/9cdb75d/openlibrary/templates/type/work/view.html: error in processing template: AttributeError: 'url' (falling back to default template)`
https://openlibrary.org/works/OL16060245W/Crispin?edition=crispinatedgeofw00avi1 #3564 

### Stakeholders
@mekarpeles @tabshaikh @cdrini

**Comment by dcapillae** [comment]
I found another bug:

- Lists are displayed in disorder when a book is included in several lists. Example: [OL8563887M](https://openlibrary.org/books/OL8563887M).

![screenshot](https://user-images.githubusercontent.com/7125952/86964095-d6edfc80-c165-11ea-950f-c67fc376c62c.jpg)

**Comment by guyjeangilles** [comment]
I've added @dcapillae 's comment to the list of problems in the original issues description so it won't get lost.

**Comment by mekarpeles** [comment]
Some of these still may be relevant, but I think the issue in general can be closed and we can open up any remaining issues separately
