### ISSUE TITLE
Docker build crashes on CentOS

### ISSUE THREAD

**Issue by aasifkhan7** [internetarchive/openlibrary#3562]
I tried building openlibrary by following the docker instructions on a MacOS Mojave 10.14.6. the build was success and I could access the application on localhost:8080. However when I replicate the process on a CentOS system, the build fails with user permissions errors, I suppose.

### Steps to Reproduce

1. git cloned https://github.com/internetarchive/openlibrary
2. ran `docker build -t olbase:latest -f docker/Dockerfile.olbase .`

* Actual: 
```Step 17/22 : RUN npm ci
 ---> Running in d624fdbfe928
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /openlibrary/package.json
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, open '/openlibrary/package.json'
npm ERR!  [OperationalError: EACCES: permission denied, open '/openlibrary/package.json'] {
npm ERR!   cause: [Error: EACCES: permission denied, open '/openlibrary/package.json'] {
npm ERR!     errno: -13,
npm ERR!     code: 'EACCES',
npm ERR!     syscall: 'open',
npm ERR!     path: '/openlibrary/package.json'
npm ERR!   },
npm ERR!   isOperational: true,
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/openlibrary/package.json'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/openlibrary/.npm/_logs/2020-07-08T15_43_33_704Z-debug.log
```

* Expected: Image created without error

### Details
- **Operating system:** 
NAME="CentOS Linux"
VERSION="7 (Core)"
- **Environment (prod/dev/local)?** dev

**Comment by cclauss** [comment]
@aasifkhan7 Is this still a problem?  Did you try running this command with `sudo`?
* `sudo docker build -t olbase:latest -f docker/Dockerfile.olbase .`

**Comment by aasifkhan7** [comment]
@cclauss let me check and get back to you.

**Comment by cclauss** [comment]
If it is still a problem, then inside the Docker container, can you run `ls -la /openlibrary/package.json` ?
