### ISSUE TITLE
exposed ASCII code on dialog

### ISSUE THREAD

**Issue by spamspambaconspam** [internetarchive/openlibrary#3565]
This appeared when I removed an item from a list.

![sp20200710_083143_703](https://user-images.githubusercontent.com/9367321/87174887-d8264300-c2a5-11ea-9dcf-0dc889cf94cd.png)

**Comment by guyjeangilles** [comment]
I can duplicate this bug on mobile as well.

@spamspambaconspam Please use the issue templates in the future.

**Comment by spamspambaconspam** [comment]
> @spamspambaconspam Please use the issue templates in the future.

Sure!  I must've sneezed at the exact moment I was creating an issue, because I don't recall seeing them (lol), but gotcha and will do!

**Comment by jamesachamp** [comment]
I just submitted a PR that corrects this, but there is an opportunity to refactor to use the `confirmDialog` function for these dialogs.  Issue #3813 should probably be resolved first, though.
