### ISSUE TITLE
create simple web tool for author merges when we only have Author ID

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#357]
Given a list of Author IDs, would like a simple command line or web tool to do author merges. Merge Wizard is great if we can get authors via search, otherwise I have to construct URLs in the form

https://openlibrary.org/authors/merge?key=OL2686331A&key=OL6382850A&key=OL522921A&key=OL6425233A&key=OL2902619A

would love a simple form that can do this.

**Comment by mekarpeles** [comment]
We can add this to github.com/internetarchive/openlibrary-client

**Comment by guyjeangilles** [comment]
@mekarpeles Defaulting to asking you to be assignee. Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by mekarpeles** [comment]
Can this be closed? Added to next proposed milestone as a reminder for us to evaluate. Should be solved by Librarian Merge tools? cc: @seabelis

**Comment by seabelis** [comment]
Yes, this can be closed for re-evaluation.
