### ISSUE TITLE
Clean up bot merged work leaves unfixable work redirect on author page?

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#3570]
### Relevant url?

https://openlibrary.org/books/OL2410921M/The_splendid_outcast?_compare=Compare&a=8&b=7&m=diff
merged
https://openlibrary.org/works/OL15845272W
with
https://openlibrary.org/works/OL3471098W
but 
both records still show under 
https://openlibrary.org/authors/OL578569A/Beryl_Markham

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by hornc** [comment]
@LeadSongDog I think this is just a solr indexing problem, where a work now a redirect OL3471098W is left on the author's page. I added it to a manual reindex.

In my old merge OL15845272W was the master record and OL3471098W was the duplicate.

**Comment by cdrini** [comment]
I think @hornc is correct, this is likely a solr issue. I force re-indexed all the works on the author's page, and it's gone now :+1:

Since the merge happened in 2017, I'm closing this; I believe there used to be a bug where redirects wouldn't be handled by solr that was a fixed a few years ago.
