### ISSUE TITLE
Searching should support sorting by classifications

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3574]
Although searches like https://dev.openlibrary.org/search?q=lcc%3AQA*&mode=everything are possible (on dev), it is currently not possible to view the results in "Shelf order".  This data lives in solr, but has just not been exposed to any of the OL search apis.

This would be essential for a "Sort by shelf order" feature.

### Summary of Requirements
- [ ] Add `&sort=lcc` parameter to /search and /search.json
- [ ] Add `&sort=ddc` parameter to /search and /search.json
- [ ] Bonus: When sorting by a classification, display the classification in the search results.
- [ ] Bonus: Include in UI as an option; (Shelf Order (DDC) | Shelf Order (LCC))
- [ ] Bonus: Add GA tracking to all sort options

Note: `lcc` and `ddc` are multiValued fields in solr; this makes them ineligible for use as a sorting field. The fields `lcc_sort` and `ddc_sort` were created for this purpose, but they had to be single valued (1 per work), and the longed such value was used. This could create a kind of confusing situation where one could back unexpected results. We might want to expose `lcc_sort` and `ddc_sort` directly, maybe? Or automatically switch `lcc:` to `lcc_sort` if we're sorting? But that will change the number of results :/ Exposing `lcc_sort` might be better for now.

### Stakeholders
@seabelis @LeadSongDog

**Comment by LeadSongDog** [comment]
It strikes me that these sorts are not necessarily for browse-time. The classifications intrinsically need only to be considered when saving work records, a much less costly thing. A work could link to prev- and next-LCClass, prev- and next-DDC.
