### ISSUE TITLE
Mockups/Design explorations for Shelf Explorer

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3575]
Subtask of: #3576

Explore/try some different ways of representing classifications data to create a library- or bookstore-like experience.

## Stakeholders

@seabelis @LeadSongDog @mekarpeles

**Comment by cdrini** [comment]
Here are some simple list based explorers (note: very slow):

- Dewey decimal: https://dev.openlibrary.org/people/ScarTissue/ddc-list
- Library of Congress: https://dev.openlibrary.org/people/ScarTissue/lcc-list

**Comment by cdrini** [comment]
Here's the current exploration page: https://f1efv.csb.app/

**Comment by mekarpeles** [comment]
Considering this done for now -- we could still use help on signage for Oct 27, but the aesthetic is good to move to production / beta on openlibrary.org/explore
