### ISSUE TITLE
How do we modernize pytest_funcarg__xyz() tests?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3586]
https://github.com/internetarchive/openlibrary/blob/0c6084ac100a926afc1bd3a16702a00fd4cf478e/openlibrary/records/tests/conftest.py#L1

will raise an error on Python 3.  The pytest docs do not clearly describe how to modernize these tests. 

https://docs.pytest.org/en/latest/funcarg_compare.html#no-pytest-funcarg-prefix-when-using-fixture-decorator

**Comment by tfmorris** [comment]
My reading of the docs is that it would become:

```python
@pytest.fixture(scope="session")
def compare_results(request)
```

but `compare_results()` isn't used, is it?
