### ISSUE TITLE
Javascript error when removing cover

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3587]
Trying to delete the cover on an edition or empty work is unsuccessful. It is possible to upload a cover but the Finished button does not work.
### Relevant url?
All edition and work urls.

### Steps to Reproduce

1. Go to any edition or work url.
2. Try to drag cover to trash. After uploading image try to click Finished.

* Actual: nothing
* Expected: Removal of cover in the case of deletion attempt or, in the case of clicking the Finished button, the window should close.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 83.0.4103.116 (Official Build) (64-bit)

- **Operating system?** MacOS
- **Environment (prod/dev/local)?** prod

### Stakeholders
 
@tabshaikh @cdrini @mekarpeles

**Comment by LeadSongDog** [comment]
#905 relates

**Comment by guyjeangilles** [comment]
Is there a current work around to delete cover?

**Comment by seabelis** [comment]
@guyjeangilles  I tried using a script in client to replace the cover IDs array with an empty array on a work, but this did not have any effect. I did not try on an edition. It could be that an empty array is not correct either; maybe there's a different value that can be used?

**Comment by mekarpeles** [comment]
I believe this is closed by @jamesachamp #3825
