### ISSUE TITLE
No reaction from dialog box when creating a new list

### ISSUE THREAD

**Issue by spamspambaconspam** [internetarchive/openlibrary#3599]
When creating a new list:
After clicking the "OK" button (titled "Create new list" in this specific d-box), the d-box does not disappear.
However, the new list **_is_** created and works fine.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/9367321/87886725-59d84800-c9ed-11ea-8c50-1c97b7c099a3.png)

### Relevant url?
Any work or book screen.

### Steps to Reproduce

1. While viewing a book/work, click on the drop down for "Want to Read"
2. Click on "Create a new list" at bottom of drop down     ![image](https://user-images.githubusercontent.com/9367321/87886867-4f6a7e00-c9ee-11ea-9607-dc8d003c2085.png)
3. Type in name of new list
4. Click button "Create new list" to create
5. Wait.
6. Wait some more
7. Click "x" in top right corner
8. Use new list

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Edge 
- **Operating system?** Win 10
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
Seems like some simple JS to close the box on click could fix this.

**Comment by seabelis** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/3561.
