### ISSUE TITLE
Does run_solr_query() have a mutable default parameters problem?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3613]
### Evidence / Screenshot (if possible)
[__run_solr_query(param = {}, ...)__](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py#L312) has a [___mutable default parameter___](https://docs.python-guide.org/writing/gotchas/) called `param`.  Is this a problem or is it done intentionally?

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
I would bet money that's not intentional 😅

**Comment by guyjeangilles** [comment]
Doing the following should be simple fix without changing functionality.
```python
def run_solr_query(param=None...):
    ...
    if param is None:
        param = {}
   ...
```

**Comment by cclauss** [comment]
Yes.  [what-you-should-do-instead](https://docs.python-guide.org/writing/gotchas/#what-you-should-do-instead)
