### ISSUE TITLE
Formatting some text as a quote causes odd line breaks in that quote.

### ISSUE THREAD

**Issue by spamspambaconspam** [internetarchive/openlibrary#3614]
I entered a block of text, and formatted a small chunk of that text as a quote.
The preview of the formatting looked perfect.
However, after "publishing" my edit, the quote-formatted text had unexpected line breaks.

Narrowing or widening the window had no affect on the line breaks.

Screenshots pretty much explain it all (better than me) :)
 
NOTE:
I experienced this while editing an **author** record ~ in the "about" field.  
This issue may or may not exist in other fields that provide the same functionality.

### Evidence / Screenshot (if possible)
Image #1 shows the raw formatting as entered.
Image #2 shows the preview ~ the preview is the desired result.
Image #3 shows the actual output ~ the formatting has been fubar'd.

![image](https://user-images.githubusercontent.com/9367321/88179197-86f94600-cbf9-11ea-8a3c-9d685b16f383.png)
![image](https://user-images.githubusercontent.com/9367321/88179469-fa9b5300-cbf9-11ea-9c35-44d68485b0c5.png)
![image](https://user-images.githubusercontent.com/9367321/88179481-01c26100-cbfa-11ea-906d-3c00495cd6c7.png)

### Relevant url?
https://openlibrary.org/authors/OL1761977A/Martha_Foley

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Edge
- **Operating system?** Win 10
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
@spamspambaconspam Please post a screenshot of your entire screen. This may be an artifact of text wrapping.

**Comment by spamspambaconspam** [comment]
Hah!  Figured it out!!  STILL a possible issue, depending on what angle you look at it from :D 

First, to address your request, the line breaks don't budge regardless of level of zoom, display width, etc.
I was going to take a screenshot for you when I stumbled across what's going on.

Apparently, there are TWO DIFFERENT blockquote styles you can create, and I happened to use control characters from BOTH styles in my one blockquote, and ended up confusing my browser.  :D 

If you highlight a bunch of text and then click the icon to format that string as a blockquote, the selection is re-formatted so:
A line break is added between words at about the 45th* column mark.
A ">\s" is placed at the beginning of each line of the string.  
_*don't quote me - I only did one test run :)_

The image here shows the how the selected string is modified.  (Prior to it getting modified, it  was as wide as the paragraphs before and after it.) 
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
![image](https://user-images.githubusercontent.com/9367321/88616567-782fea80-d062-11ea-8b29-38d9c7378a7b.png)
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

This results in the text  getting formatted like this next image.
I didn't like that, as I feel it wastes real estate, and it also kinda looks like it's formatted as a two columns, but the other column is missing :D 

**_NOTE:  this method does NOT SCALE - it's not responsive to increases or decreases in window/display width._**   
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
![image](https://user-images.githubusercontent.com/9367321/88616711-dd83db80-d062-11ea-92c9-2737c7e49079.png)
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
I wanted it to look like this:
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
![image](https://user-images.githubusercontent.com/9367321/88616999-95b18400-d063-11ea-9d79-48ba356d9439.png)
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
But we know that doesn't work... after the changes are written, we get that funky line break.

Here's the twist:
If you place a single ">\s" at the beginning of the string and leave the rest alone, then the entire string (up to the \n), gets formatted as a blockquote, and IS responsive to screen width changes.
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
![image](https://user-images.githubusercontent.com/9367321/88617258-24be9c00-d064-11ea-8bd2-fdc10d0c7051.png)
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
![image](https://user-images.githubusercontent.com/9367321/88617251-1ff9e800-d064-11ea-9752-56cb919b81f5.png)
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Now if I could only figure out how to stop github from scaling my images at "whatever we feel like" :D

**Comment by guyjeangilles** [comment]
Less of a bug and more markdown being markdown. Gonna close this for now.
