### ISSUE TITLE
Make lists searchable

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#364]
Open Library lists are only surfaced on user pages, item pages, and the overarching Lists page. The lists should be searchable at a basic level

- find lists with this item on them
- find lists with this keyword in them

**Comment by mekarpeles** [comment]
There's a prototype on `feature/list-search`. It hasn't been designed and is not very accurate (it searches against psql directly instead of solr)

**Comment by guyjeangilles** [comment]
@mekarpeles `feature/list-search` (#1149) was deleted but this issue wasn't update. Can you explain why? I'm assigning you per slack discussions

**Comment by cdrini** [comment]
https://openlibrary.org/search/lists?q=biography Does exact string matching of the title :/

**Comment by jessamynwest** [comment]
This is excellent. Is there a way to do this for words in the title to get a wider set of results?

**Comment by cdrini** [comment]
With the current implementation, unfortunately no. The current implementation is hitting postgres directly instead of solr, so we can't do any "smart" searching like we do with books. Long term, we need to index lists inside solr as well.

**Comment by mekarpeles** [comment]
I'm going to mark this as closed, even though the list search sucks.

**Comment by tfmorris** [comment]
> I'm going to mark this as closed, even though the list search sucks.

@mekarpeles Can you expand on the rationale for this? Normally we close feature requests when they've met the needs of the requester.

Can you clarify what is currently implemented? Exact full match only? Prefix match? Embedded keyword? (Sounds like definitely not the latter)
