### ISSUE TITLE
Empty Solr field search queries break search rendering

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#365]
e.g. A search for "title:" -- https://openlibrary.org/search?q=title%3A

Results in error:
/opt/openlibrary/deploys/openlibrary/93ddc9e/openlibrary/templates/work_search.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'startswith' (falling back to default template)

**Comment by guyjeangilles** [comment]
Still an error. Seems like wrapping the query in a try catch block would patch the issue

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/blob/7195f181742af7389843f275eefb2e675055b727/openlibrary/plugins/worksearch/code.py#L265 needs to check if `reply` is `None` and then not try to do the search.

**Comment by mekarpeles** [comment]
Seems to be fixed!
https://openlibrary.org/search?q=title%3A
