### ISSUE TITLE
Simultaneous side-by-side testing of Python 2 and 3 on Docker

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3653]
I am frustrated when I want to compare Python 2 to Python 3 because I need to use Docker Compose to shut down the system and then reboot with `PYENV_VERSION=2.7.6` or `3.8.5`.  Would it be possible to launch two instances of `web`?
1. Web on Python 2 on http://localhost:8082
2. Web on Python 3 on http://localhost:8083

This would enable me to change the final digit of the port number on URLs to ensure that execution and presentation matched on both versions of Python.

**Comment by cdrini** [comment]
You might be able to do it by git cloning a fresh copy of the OL repo, modifying the `docker-compose` file to export only port `8080` but at a different location, and then in that dir doing `PYENV_VERSION=2.7.6 docker-compose up -d`. That might work?

**Comment by cclauss** [comment]
I gave that a try but it did not work because `PYENV_VERSION=2.7.6 docker-compose up -d` restarts solr and memcached.  I tried to put web Python 2 on 8082 and start it both before and after docker-composing up the main repo on Python 3.  No luck.

**Comment by cdrini** [comment]
I was able to get it work with this:

```
cd openlibrary
cd vendor/infogami
git pull master
cd ../..
vim docker-compose.yml  # Make it expose to 8083
INFOGAMI=local PYENV_VERSION=3.8.5 docker-compose up -d

cd ..
mkdir ol-py2
cd ol-py2
git clone --depth 1 https://github.com/internetarchive/openlibrary.git .
vim docker-compose.yml  # Make it expose to 8082, and COMMENT OUT the other ports on the web service
docker-compose up -d web  # Only start web :)
```

Let me know if that works!

**Comment by cdrini** [comment]
There might be some strange behaviour (they should both be using the same solr and memcache, I think)

**Comment by cdrini** [comment]
Hey! I'm going to close this if that's ok :) If the above doesn't work and you still want this, feel free to re-open!
