### ISSUE TITLE
Search inside with `title:` results in escaped HTML in empty results page.

### ISSUE THREAD

**Issue by bnewbold** [internetarchive/openlibrary#3656]
### Evidence / Screenshot (if possible)

Text comes through as:

```
No hits for: <strong>title: &quot;People’s History of Computing in the United States&quot;</strong>
```
![image](https://user-images.githubusercontent.com/130077/89213214-9b362f00-d579-11ea-9cf1-e02c757b86b3.png)

### Relevant url?

https://openlibrary.org/search/inside?q=title%3A+%22People%E2%80%99s+History+of+Computing+in+the+United+States%22

### Steps to Reproduce

1. Searched in box: https://openlibrary.org/search?q=title%3A+%22People%E2%80%99s+History+of+Computing+in+the+United+States%22&mode=everything
2. Clicked the link labeled "No results found. Search for books containing the phrase "title: "People’s History of Computing in the United States""?", which led to https://openlibrary.org/search/inside?q=title%3A+%22People%E2%80%99s+History+of+Computing+in+the+United+States%22

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chromium
- **Operating system?** Linux
- **Environment (prod/dev/local)?** prod

**Comment by guyjeangilles** [comment]
Using `title:` with search inside seems counter intuitive to me, but this is a bug nonetheless.

**Comment by cdrini** [comment]
I can no longer repro, the url now displays correct HTML 
![image](https://user-images.githubusercontent.com/6251786/210887869-83a1e1fe-54d1-43b1-980c-640ea014cd13.png)
