### ISSUE TITLE
Add UI to allow admins to delete author records

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#366]
There are junk author records and we need a way to delete them. This is possible with some records and not others, should be possible for all.

From: https://openlibrary.org/authors/OL3059820A/Finl/edit

![screen shot 2016-11-01 at 12 19 29](https://cloud.githubusercontent.com/assets/698448/19897209/8bcb799c-a02d-11e6-9e9a-3d5c2a647928.jpg)

**Comment by LeadSongDog** [comment]
Apparently that used to be "Tom of Finland". NSFW

**Comment by jessamynwest** [comment]
Another SFW one https://openlibrary.org/authors/OL570512A/Mohd._Ismail_Sarbini/edit

**Comment by hornc** [comment]
I think Authors can be deleted, if the system is confident that there are no works or edition back links to that author.  [**Bug:** that message "Deleting author pages is not allowed." is incorrect]

* In the case of the "Finl" author above, the author page shows one _edition_ attributed to that author, /books/OL8676103M  -- the [edition view](https://openlibrary.org/books/OL8676103M) only displays the author from the Work level, but the edition json shows two authors against it: https://openlibrary.org/books/OL8676103M.json   , one of which is 'Finl'.  **Bug** there isn't a proper way to even see, let alone edit+remove this author attached to an edition. I have seen bot edits that delete all author info from editions, presumably with the assumption that authors belong only at the work level.

* Second case, Mohd., the author page shows no works listed, but the author's works.json https://openlibrary.org/authors/OL570512A/works.json lists one work, which is what the code is picking up on. https://openlibrary.org/works/OL3441072W/Mencari_pulau_impian Maybe this is another indexing problem?  I'm going to add both the work and author to the solr index to see if that brings the two inline. Why does this author need deleting?

**Comment by LeadSongDog** [comment]
@hornc re "I have seen bot edits that delete all author info from editions, presumably with the assumption that authors belong only at the work level." 
There obviously are additional authors for later editions of some works, particularly serials, but OL has no way of distinguishing these. It should. The straightforward answer would be to add "additional author" to the list of contributor roles to cover these cases.

**Comment by hornc** [comment]
TASK: 

- [ ] Fix error message "Deleting author pages is not allowed." to be more informative and explain why the page can't be deleted: "This Author page cannot be deleted as there are works/editions still assigned  to this id."   Extra credit: provide a count + link to the items 

I use '/authors/OL...A/works.json' as this is often more accurate than Solr search results (although that may be improving soon) .json is not very UI friendly though.
