### ISSUE TITLE
Inconsistent fields between works and editions schemas

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#367]
Comparing the two schemas there are many discrepencies in which of the fields are included. Several appear to be in the wrong place entirely, though as usual, I'm unsure. Could someone please review and comment. Just for ease of comparison, I alpha-ordered them:

[fieldlist.xlsx](https://github.com/internetarchive/openlibrary/files/567038/fieldlist.xlsx)

**Comment by LeadSongDog** [comment]
#142 relates.

**Comment by mekarpeles** [comment]
@LeadSongDog can I please move this to https://github.com/internetarchive/openlibrary-client? We're trying to address schema solidification there :)

cc: @hornc

**Comment by LeadSongDog** [comment]
No objection if it means it will get addressed.  I'm still trying to understand what openlibrary-client is supposed to be. A hosted service that users access as a website? An app they install? Or is it just for the privileged few? There should be an intelligible explanation somewhere...

**Comment by mekarpeles** [comment]
great point -- I'll see if I can add copy to make it more clear what the client is.

It's a command line tool and python library anyone can download, similar to the Internet Archive command line tool, which allows users to script bots capable of making bulk changes on openlibrary. Anyone can use the tool with their Open Library account credentials to fetch / **read** data from OpenLibrary via the APIs. **Writing** to Open Library using the client requires a `bot` or an `admin` account.

We're using the https://github.com/internetarchive/openlibrary-client/issues section as a place to discuss data cleanup efforts and schema conventions. See also: #718

**Comment by LeadSongDog** [comment]
I hope there will be an implementation that does not have to be installed by the user. Public library machines are often locked down, as are many corporate networks. Perhaps some sort of hosted VM to run the client?

**Comment by mekarpeles** [comment]
@LeadSongDog This tool wraps our existing public APIs which essentially accomplishes what you're talking about, I think. Unclear who or what the use case would be for a hosted openlibrary-client. Also, if possible, lets try to address points like this as separate issues so we aren't conflating this topic of this thread

**Comment by LeadSongDog** [comment]
I hope I am misunderstanding. It seems to me that the intention is now to give up on using the wiki for such edits by ordinary users, instead only allowing it to be done with a new tool which most users will not be able to use. That is not an _Open_ library. It will need a new name.

**Comment by cdrini** [comment]
@LeadSongDog Don't worry, openlibrary-client is *absolutely* not intended to replace Open Library; it's just a *supplementary* tool for users (specifically users that can program) to create bots and make lots of (usually) menial edits at a faster rate than a human would be able to.

**Comment by guyjeangilles** [comment]
@LeadSongDog Was this issue ever migrated? If so, I propose closing this issue.

**Comment by LeadSongDog** [comment]
@mekarpeles @guyjeangilles 
I don't see any sign of it on openlibrary-client, but perhaps I'm not searching correctly. Mek?

**Comment by tfmorris** [comment]
> Was this issue ever migrated? If so, I propose closing this issue.

I think pushing issues off to another repo was just a passing phase and is something that we no longer do.

**Comment by guyjeangilles** [comment]
I've changed labels accordingly. @hornc do you potentially have any idea why work and edition schemas differ this way?

**Comment by tfmorris** [comment]
Actually, I'm going to close this. I didn't really look at it closely last time around. The spreadsheet has an extract of the Solr schema from 2016, but we don't actually index editions currently, so that piece is moot. Plus "review and comment" doesn't really buy us anything.

When we add (or switch to) indexing editions, we'll want to design the edition schema carefully, but that can be done as part of that project.
