### ISSUE TITLE
BookReader doesn't work on original iPad

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#369]
Trying to track down an iPad to reproduce this

**Comment by jessamynwest** [comment]
Loan goes through like normal but then it hits the "stream" URL and just stays on the "loading" page and never gets to the actual book.

**Comment by LeadSongDog** [comment]
Seems to work on iPad 3.

**Comment by jessamynwest** [comment]
Yep and I've got an iPad 2 that it is fine one. But I can recreate on iPad 1, book just never loads.

**Comment by LeadSongDog** [comment]
The specific failing rev of iOS and Safari might be indicative.

**Comment by jessamynwest** [comment]
God point. I'll update til I can't anymore and see if it's still broken and note the revs.

**Comment by jessamynwest** [comment]
IOS 5.1.1 (latest that will run) and the Safari version that comes with it. I checked and can't run FF on it. Downloaded Chrome and the same thing happens (can not get item and loan is not fulfilled)
![screen shot 2016-11-11 at 10 08 46](https://cloud.githubusercontent.com/assets/698448/20219322/e344a84e-a7f6-11e6-8422-7a0d23de9a2d.jpg)

**Comment by guyjeangilles** [comment]
Considering this only affects the 1st gen iPad and that the 1st gen iPad is technically not supported by Apple anymore, I propose we close this issue and leave this device unsupported.

**Comment by jessamynwest** [comment]
I concur.
