### ISSUE TITLE
Books Page, Editions Table: "Remember" # Results to Display 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3712]
@jessamynwest writes:

> There are 120-ish versions of this book and I am shown three. I expand that list to go to “All” with the dropdown (this is fine) but then when I click away and click back that preference is not respected and I have to use the drop down again. Time consuming and bad ux.

<img width="470" alt="screen_shot_2020-08-15_at_15 52 50" src="https://user-images.githubusercontent.com/978325/90320756-a46bb800-def8-11ea-83f9-6e8a55aa307c.png">

### Describe the problem that you'd like solved

Books page editions table doesn't remember / honor how many books you'd like displayed by default by the table.

### Proposal & Constraints

Expand the LocalStorage settings in(similar to in plugins/openlibrary/js/ol.js (which is how we're storing the top-bar search facet -- e.g. author v. title, etc) to remember the patron's settings.

Because of page caching, we may want to check LocalStorage and change the number of displayed results from 3 to whatever the patron has selected **after** pageload using js.

### Stakeholders

@tabshaikh @seabelis @jessamynwest @cdrini

**Comment by aasifkhan7** [comment]
@mek Can you please assign me to this issue? (My apologies - I opened a PR without even getting assigned the issue.)
