### ISSUE TITLE
Use definition table for contributors on Books Page

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#3713]
Just a small design request. In the editions #edition-details section, the details like id's, physical details... are styled with definition tables which produces a nicely structured view while the contributors section consists of list elements with lots of breaks which looks very cramped.

Just compare the sections in this example: [OL28775995M](https://openlibrary.org/books/OL28775995M/Der_Todeskanal#edition-details)

Style the contributors section with the same `<dt><dl><dd>` elements as the other sections.

Sorry that I can't make the change myself but I couldn't find the corresponding file and even than I'm not sure if I know how to change that.

**Comment by anushri20** [comment]
@bitnapper Can I work on this?

**Comment by bitnapper** [comment]
> @bitnapper Can I work on this?

Also not in charge... but I think everyone would be very greatful, if you can do something about that.

**Comment by bitnapper** [comment]
When somebody is looking into that, maybe the dt element could get a bit more space to avoid overlapping:

![image](https://user-images.githubusercontent.com/2772669/95496248-d2bdbf00-09a0-11eb-8c43-05f5e191790a.png)

**Comment by nynaalekhya** [comment]
@jdlrobson Hi,
Can I work on this issue?

**Comment by jdlrobson** [comment]
@nynaalekhya fine with me, provided @mekarpeles has no objections.

**Comment by Yashs911** [comment]
> @jdlrobson Hi,
> Can I work on this issue?

Hi, @nynaalekhya. I have solved this issue locally, but as you claimed it first, if you have no problem, can I create a PR for this issue. If you want to solve this issue, I don't have any problem 😄

**Comment by nynaalekhya** [comment]
@Yashs911  Fine for now, but claim the issue before you work on it.

**Comment by bitnapper** [comment]
Thans, looks good.
