### ISSUE TITLE
My profile page slow to load, sometimes 504s

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3724]
### Relevant url?
https://openlibrary.org/people/ScarTissue

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF79
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Hmm; I think it's just taking a very long time to load; it took ~10s uncached, but didn't 504 anymore. Updating title.

**Comment by miphilomath** [comment]
Sometimes it is taking longer, sometimes not. It took 18s on an average to load the profile page for me, with fastest being 11s and longest 42s, compared to usual 1-2s to few other random profiles.

**Comment by mekarpeles** [comment]
@miphilomath may I ask you to look into this?

If you have any questions about what files are related, I'd be happy to get you up to speed.

Some useful tips and tricks for this issue:
1. if you add `?_profile=true` to the url, you should get a breakdown of loadtime by component / call.
2. if you add `?debug=true` you can get stack traces and on some pages (like the books page) this causes a table to be rendered with more granular load times by component.

**Comment by mekarpeles** [comment]
@miphilomath if you look at the openlibrary/templates/type/editions/view.html template, you should find code which gets run when ?debug=true is present:

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L3
...
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L482-L499

We can implement this same approach on people's profiles pages to determine which component is causing problems:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/view.html

**Comment by mekarpeles** [comment]
Our guess is it's the list components
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/view.html#L8-L11
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/view.html#L58-L75

**Comment by SouthGoingZax** [comment]
The performance here seems much better.  Fixed by solr -> SSD?

**Comment by cdrini** [comment]
Agreed; I do think we have a perf issue related to how lists are loaded on the profile page, but this issues seems closed :+1:
