### ISSUE TITLE
Search results display bug. "checked out/borrow" icon overlaps righthand column with long titles..

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#373]
iMac. El Capitan. Firefox 49.

![screen shot 2016-11-10 at 16 20 07](https://cloud.githubusercontent.com/assets/698448/20194753/b6edc6bc-a761-11e6-9526-e2c8910ac910.jpg)

(has been happening for a while but just captured it in the wild.)

**Comment by LeadSongDog** [comment]
https://github.com/internetarchive/openlibrary/commit/d8e0a6cdae24d16c8dd7ffe453fd4f771d0d4c80#diff-2978a555cb02eb655603308c71f57559R169 is suggestive

**Comment by mekarpeles** [comment]
cc: @bernatfortet

**Comment by cdrini** [comment]
No longer an issue
