### ISSUE TITLE
Selecting "currently reading" on Reading Log accidentally also clicks Star Ratings

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3755]
Clicking on the Reading Log dropdown and selecting "currently reading" bleeds through the UI component and frequently clicks on the StarRating component (resulting in an unintentional rating)

### Evidence / Screenshot (if possible)

![download](https://user-images.githubusercontent.com/978325/91647418-736aa780-ea0f-11ea-8b67-9ccbef53c692.gif)

### Relevant url?

any books page e.g. https://openlibrary.org/books/OL1627167M/Neuromancer

### Steps to Reproduce

1. Go to ... https://openlibrary.org/books/OL1627167M/Neuromancer
2. Do ... click on Reading Log drop down
3. Select "currently reading"

Consider also editing the backgrounds of all the divs within `dropper` to be transparent so you can see this happening and debug

### Proposal & Constraints

Likely something float or z-index related?

### Related files

Component:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lists/widget.html#L185
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lists/widget.html#L282

CSS:
https://github.com/internetarchive/openlibrary/blob/master/static/css/components/dropper.less

`openlibrary/templates/lists/widget.html`

**Comment by jamesachamp** [comment]
It looks like this can be solved by adding a `pointer-events: none` rule to the star component when the reading list dropdown menu is open, and removing the rule when the menu is closed.

If this approach is acceptable, I can submit a PR for this within a day.

**Comment by rohitgeddam** [comment]
I would like to work on this.

**Comment by cdrini** [comment]
@jamesachamp That sounds perfect! Go for it :)

Thanks for offering, @rohitgeddam ! @jamesachamp got to this one first :) Maybe you might want to take a look at #3296 if you're looking for something to contribute to.

**Comment by jamesachamp** [comment]
@cdrini Just submitted a PR for this.  I may be a bit slow to resolve any review comments, as I'm currently having some issues with my local setup...
