### ISSUE TITLE
Run full solr reindex with Aug dump

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3758]
There have been a large swathe of imports which are currently missing from our solr; run a full re-index to get them included. Also a good time to test (1) how the solr builder works with the py2/py3 changes, (2) the new to-production flow now that ol-solr0 is in use.

### Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
Reindex complete; here are the numbers (using 2020-08-31 dump; and querying 09-14 solr for "before" values)

Type        | # in postgres | # in prod solr | # in new solr | psql diff   | solr diff
----------| --------------- | ------------- | -------------- | ----------- | --------
Works     | | 22217079 | 22848656 |  | 631577
Orphans |  | 3069021 | 3035808|  | -33213
Authors  |  | 7452483| 7713532|   | 261049
Subjects | 0 | 1514064 | 1514064 | - | 0

**Comment by guyjeangilles** [comment]
Should this issue still be open?

**Comment by cdrini** [comment]
Nope! :)
