### ISSUE TITLE
Issue linking accounts

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3759]
@JeffKaplan Reporing that he's having some issues linking certain accounts; see https://internetarchive.slack.com/archives/C075DJ6G1/p1598905321019400

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
Assuming stale, no longer an issue
