### ISSUE TITLE
Orphaned editions error

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3760]
```
/opt/openlibrary/deploys/openlibrary/9afb5a2/openlibrary/templates/type/edition/view.html: error in processing template: IndexError: list index out of range (falling back to default template)
```

### Relevant url?
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1
- https://openlibrary.org/books/OL9773440M/Muertos_Incomodos?v=1&debug=true

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF79
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
Dupe of #4052
