### ISSUE TITLE
fix lists display issue

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#377]
Something in a recent update made the list fint size smaller and the list display intended when they appear on an item page. Example page.

https://openlibrary.org/books/OL7203499M/What_to_draw_and_how_to_draw_it

example image showing how lists looked before and how they look now.

![screen shot 2016-11-14 at 21 06 27](https://cloud.githubusercontent.com/assets/698448/20290863/b82c21d4-aab0-11e6-8a27-ec2f50c6ae6e.jpg)

**Comment by mekarpeles** [comment]
resolved
