### ISSUE TITLE
Graphite statsd volume too large for memcached

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3782]
`stats.ol.memcache.{hits,misses}` looks like it might be trigger too frequently. Maybe related to lazy loading related carousels (hitting memcache more freq)?

```
samuel-archive  [11:55 AM]
Hi, I have noticed that ol is  sending about 400/sec these statsd events: ol.memcache.hits:1|c to graphite.
Could you guys turn on sampling at 1/40 or so for this event?  thanks!
samuel-archive  [12:10 PM]
(my target is 10 / second for most of these stats...)
```

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@samuel-archive

**Comment by mekarpeles** [comment]
notes:
https://statsd.readthedocs.io/en/v3.2.1/reference.html#incr
`StatsClient().incr(stat, count=1, rate=1)`

**Comment by mekarpeles** [comment]
@tabshaikh this is likely from our RelatedWorkCarousels -- any updates / testing on this one?

**Comment by mekarpeles** [comment]
I believe this should now be solved as we no longer are caching RelatedWorksCarousel.

**Comment by mekarpeles** [comment]
Re-opening, looks like the presumed fix didn't wokr

**Comment by mekarpeles** [comment]
I see `stats_hook` in `openlibrary/plugins/openlibrary/stats.py` which increments stats to memcache for hits and misses and `create_stats_client` which sets up the graphite connection using `pystatsd.Client`

**Comment by mekarpeles** [comment]
It looks like we can sample per event which is what we seem to want to do:
https://statsd.readthedocs.io/en/v3.2.1/types.html

From the docs:
`rate` is a float between 0 and 1:

```
# Increment this counter 10% of the time.
statsd.incr('some.third.event', rate=0.1)
```
