### ISSUE TITLE
Create ol-web1

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3783]
Fossa + docker (cc @samuel-archive )

**Comment by mekarpeles** [comment]
ol-web1 is provisioned (it may need to be re-provisioned with focal, but I say let's continue forward trying to get a production python3 version of `ol-dev1` (i.e. staging.openlibrary.org) as part of our haproxy pool.

This will require a change to `olsystem` in `/etc/postgres/hb_pga.conf` to add the IPs of ol-web1 (for our dbs) if the IP is not there already. And likely the `olsystem/etc/openlibrary.yml` (and similar configs) as well.
