### ISSUE TITLE
Fix EOY donation banners on dev + production

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3785]
1. Coordinate w/ product team to **not** load /include/donate.php assets if we're not in an active donation period
2. On prod: if not `dev-enabled`, we **should** load the banner from archive.org. This needs to be added/fixed. We should split this into a different/new option for toggling whether to show donation banner via olsystem openlibrary.cnf which should default to False on local.
3. We believe localhost shouldn't be showing any donation banner stuff, so (especially assuming we solve part 2) we want to re-enable visual banner includes on dev.

The end-of-year `donate banner` injection code used to load way more than we needed (e.g. jquery, etc). This has been fixed

https://dev.openlibrary.org/?ymd=2019-12-06 hides the css for EOY donations banner (because it's annoying / distracting on dev). 

As a result, we disabled it on production. 

https://dev.openlibrary.org/?ymd=2019-12-06

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Notes

It would be great to know this is resolved prior to October (in advance of EOY). Also, it would be great for includes/donate.php to not return anything if we are not in an active donation period. (edited) 

Otherwise, this has very noticeable impacts on OpenLibrary.org performance

Right now, on every page load, we're pulling:
```
        <script src="https://archive.org/includes/jquery-1.10.2.min.js"></script>
      <script src="https://archive.org/components/npm/@babel/polyfill/dist/polyfill.min.js"></script>
      <script src="https://archive.org/includes/build/js/ie-dom-node-remove-polyfill.min.js"></script>
      <script src="https://archive.org/includes/analytics.js"></script>
                                  <meta property="braintree_token" content="production_xxx">
                      <meta property="environment" content="production">
                      <meta property="venmo_id" content="xxx">
```

### Stakeholders

cc: @bfalling, @cdrini. @jbuckner

**Comment by cdrini** [comment]
This was fixed (and is no longer really necessary since we're switching to the iframe).
