### ISSUE TITLE
Site performance is abysmal 

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#3793]
The site has been getting steadily slower over the last few months, but now has become completely unusable.

- autocomplete for author names takes several seconds which defeats the entire purpose of having autocomplete
- this URL 504'd after 60 seconds **twice** before finally loading in 40 seconds (ie response time of 160 seconds or 160000 msec to use a more common unit of measurement for latency).
  https://openlibrary.org/authors/merge?key=OL336361A&key=OL2039613A&key=OL5069405A&key=OL6800800A&key=OL1473920A&key=OL5452718A&key=OL4642295A&key=OL4247412A&key=OL4906452A&key=OL7288258A&key=OL5909189A&key=OL6463981A&key=OL3814683A&key=OL5858741A&key=OL5869152A&key=OL6452175A&key=OL5221953A&key=OL2079923A&key=OL2027549A&key=OL6524204A&key=OL6201685A&key=OL6679523A&key=OL6039535A&key=OL6063863A&key=OL3752513A&key=OL2530296A&key=OL6162987A&key=OL7366486A&key=OL6689897A&key=OL6088798A

Although the entire site is sluggish author merge is particularly bad with any merge candidate review containing more than a handful of authors (or is it the listed editions slowing it down) being super slow.

The UI changes already hinder editing, but the performance issues make it completely impossible

**Comment by seabelis** [comment]
I'm not sure if this is related, but works and editions pages take 30+ seconds to load.

**Comment by SouthGoingZax** [comment]
Is this still a problem after the Solr -> SSD change in late October?

**Comment by tfmorris** [comment]
I never got any confirmation that anyone else considered it a problem, so perhaps my standards were just too high.

I'll see if the issue still exists the next time I have reason to visit the site.

**Comment by seabelis** [comment]
@SouthGoingZax Performance was exceptionally poor in Sept/Oct and has since improved. However, book and author pages are still slow to load. About 15 seconds for me. I'm no longer getting the 504s.

**Comment by mekarpeles** [comment]
Performance has actionable steps on our roadmap for this year, close this in favor of a new issue # turning this into a performance Epic
