### ISSUE TITLE
Search result preview overlapping with other page elements

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#3796]
Typing a search request with plenty of hits into the top search-field, waiting for the preview results. The result bar (could not figure out the id) is overlapped by `<ul class="work-menu sticky">`.

### Evidence / Screenshot (if possible)

![Screenshot_2020-09-13 The Girl, the Gold Watch and Everything (1962 edition) Open Library](https://user-images.githubusercontent.com/2772669/93017086-37feda00-f5c6-11ea-87be-44f8c9aab73e.png)

### Steps to Reproduce
1. Go to any page and type 'Girl, the Gold Watch' into the upper search bar and just wait
2. when the preview results appear, you should see the problem

- **Logged in:** not relevant
- **Browser type/version?**  firefox
- **Operating system?** osx
- **Environment?** prod

**Comment by jamesachamp** [comment]
The search results are in `<div class="search-bar-component">`.  Both the search bar component and the work menu have the same z-index (`999`).  It looks like increasing the search bar component's z-index will correct this.

I'll raise a PR for this tomorrow, as it's a bit late here now.

**Comment by guyjeangilles** [comment]
I recall seeing this bug before, but can't find the issue. If anyone has better memory than me mention the issue in this thread

**Comment by guyjeangilles** [comment]
@cdrini I'm still seeing this bug why was this closed?

**Comment by cdrini** [comment]
Fixed on dev :) Deploying today

**Comment by cclauss** [comment]
[This seems to be occurring again.](https://internetarchive.slack.com/archives/C0ETZV72L/p1612791843104800)

**Comment by Yashs911** [comment]
I would like to work on this
