### ISSUE TITLE
base64.decodestring was deprecated and removed in Python 3.9 in favor of decodebytes

### ISSUE THREAD

**Issue by tirkarthi** [internetarchive/openlibrary#3798]
### Steps to Reproduce

It should be decodestring in python 2 and decodebytes in python 3.

```
openlibrary/plugins/importapi/code.py
462:        username, password = base64.decodestring(authstring).split(':')
606:        username, password = base64.decodestring(authstring).split(':')
```

**Comment by Abhirup-99** [comment]
Hello!
Can I start working on this issue, as it has a good first tag, and I am also new to open-source contributing and would like to fix this issue?

**Comment by Abhirup-99** [comment]
I have pushed a commit, please do review. @tirkarthi

**Comment by Abhirup-99** [comment]
@tirkarthi I messed up the last pr due to some git issue. I have pushed a fresh pr, do take a look.
