### ISSUE TITLE
Running i18n scripts fails due to permissions error

### ISSUE THREAD

**Issue by jamesachamp** [internetarchive/openlibrary#3812]
Running `docker-compose exec web make i18n` results in a permissions error, and `.mo` files are not generated.

### Evidence / Screenshot (if possible)
Stack trace is as follows:
```
$ docker-compose exec web make i18n
python ./scripts/i18n-messages compile
failed to compile /openlibrary/openlibrary/i18n/de/messages.po
Traceback (most recent call last):
  File "./scripts/i18n-messages", line 93, in <module>
    main(sys.argv[1])
  File "./scripts/i18n-messages", line 82, in main
    i18n.compile_translations()
  File "/openlibrary/openlibrary/i18n/__init__.py", line 76, in compile_translations
    _compile_translation(po_path, mo_path)
  File "/openlibrary/openlibrary/i18n/__init__.py", line 25, in _compile_translation
    raise e
IOError: [Errno 13] Permission denied: '/openlibrary/openlibrary/i18n/de/messages.mo'
Makefile:40: recipe for target 'i18n' failed
make: *** [i18n] Error 1
```

### Steps to Reproduce

1. Run `docker-compose up` and wait until your local instance has started.
2. Run `docker-compose exec web make i18n`

* Actual: Permissions error is thrown, and `.mo` files are not generated.
* Expected: `.mo` files are generated.

### Details

- **Logged in (Y/N)?** N/A
- **Browser type/version?** N/A
- **Operating system?** Ubuntu 18.04.5 LTS
- **Environment (prod/dev/local)?** local

### Proposal & Constraints

This doesn't seem to be happening for Windows machines, as per @cdrini 
I was able to find a work-around by running the script as root in the container using these commands:
`docker exec -u 0 -it openlibrary_web_1 bash`
`make i18n`

**Comment by cdrini** [comment]
I was able to fix this by deleting the .mo files from outside the container; then docker was able to create/modify them as it wished. Does this work for you, @jamesachamp ?

```
echo **/**.mo
rm **/**.mo
docker-compose exec web make i18n
```

**Comment by jamesachamp** [comment]
@cdrini no, it didn't.  I'm getting the same error message as before.  Whenever I try to execute anything on `web`, user `openlibrary` is used by default.  Does the same thing happen for you?

**Comment by mekarpeles** [comment]
@cclauss can you investigate this one at your leisure next time you're on your local env?
