### ISSUE TITLE
List removal dialog buttons not translated

### ISSUE THREAD

**Issue by jamesachamp** [internetarchive/openlibrary#3813]
When deleting a list with language preference set as `fr` or `es`, the buttons in the confirmation dialog box are displayed in English.  The body of the dialog is, however, displayed in the correct language.

### Evidence / Screenshot (if possible)
Dialog with Spanish language preference set:
![es_i18n_issue](https://user-images.githubusercontent.com/28732543/93631270-4596d400-f9b9-11ea-89c3-f8bd794e6a10.png)

### Relevant url?

openlibrary.org/people/${YOUR_USERNAME}/lists?lang=es
or
openlibrary.org/people/${YOUR_USERNAME}/lists?lang=fr

### Steps to Reproduce

1. Log into Open Library
2. Ensure that you have created at least one list
3. Navigate to one of the above listed URLs
4. Click on the garbage can icon to open the dialog

* Actual: Body of dialog box is translated, while the buttons are not.
* Expected: Body and buttons of the dialog are translated.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Strings for this dialog box are defined in the `confirmDialog` function in `dialog.js` (full path listed below).  As far as I can tell, we are not currently extracting i18n strings from `.js` files.  Babel has a built in Javascript extractor that can be utilized for this.

Alternatively, the confirmDialog button options can be overridden with i18n strings in `lists.html`.

I can work on this once an approach is chosen.

### Related files

openlibrary/plugins/openlibrary/js/dialog.js
openlibrary/plugins/openlibrary/js/index.js (`confirmDialog` is exposed as `ol_confirm_dialog` here)
openlibrary/templates/lists/lists.html

**Comment by cdrini** [comment]
Heads up this is a part of a larger problem associated with the fact that we don't have i18n for our JS files (I believe an issue exists somewhere).

**Comment by jamesachamp** [comment]
I'll start working on the second approach, then (overriding the dialog's button options).
