### ISSUE TITLE
Determine which Works are on the most Lists

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#382]
Anyone have a suggestion for the best way to determine which Works belong to the most Lists?

@diamondman, @bfalling 

By a count, it looks like we have ~80,000 lists (via the thing table). It seems like the actual data for lists is stored within the `data` table (which unfortunately has ~120M+ records)

The following (see https://github.com/internetarchive/openlibrary/blob/feature/lists-carousel/openlibrary/plugins/openlibrary/home.py) works but the EXPLAIN score of the query is ~120M... As are the number of rows in the `data` table.

```
@public
def popular_available_from_lists_carousel(limit=60):
    db = get_db()
    list_items = db.query("""
    SELECT thing_id, data::json FROM (
      SELECT thing_id, revision, data, rank() OVER (
        partition by thing_id order by revision desc
      ) FROM data where thing_id in (
        select id from thing where thing.type=(
          select id from thing where key='/type/list')
        )
      ) subquery where rank=1;
    """)

    work_keys = {}
    for item in list_items:
        for seed in item.data['seeds']:
            key = seed['key']
            if key.startswith('/works/'):
                work_keys[key] = work_keys.get(key, 0) + 1
    sorted_keys = sorted(work_keys, key=lambda k: work_keys[k], reverse=True)
    books = [format_book_data(web.ctx.site.get(key))
             for key in (sorted_keys if sorted_keys <= limit else sorted_keys[:limit]]
    return render_template("books/carousel", storify(books),
                           id='popular-carousel')
```

It seems like we may want to keep a table of the top 1000 most popular works (i.e. works which are on the most lists) and update this (i.e. recompute a work) if a Work is added to a list.

Use case: "Trending" books carousel on home page.

**Comment by tfmorris** [comment]
I'd lead with the use case, if that's the important thing. "Trending" implies recent activity, not the total historical record. That means looking at List Adds for the last N days, not the current list population (although that might provide a useful background signal to measure against).

Another important aspect of the use case is how "fresh" you need the data to be. Is "trending" last night at midnight OK? Last Sunday at noon? The 1st of the month?

Lastly, EXPLAIN queries come in two flavors: 1) plan base on statistics and other things that the query planner knows about and 2) actual. The two can be wildly different. If you were going to do this live, you'd shoot for a query and an index structure which made the query satisfiable completely from the index (and you'd put the LIMIT on the initial list_items query so you didn't sort them all and then throw 99% of them away)

**Comment by guyjeangilles** [comment]
@mekarpeles I'm not sure who would be best assignee for this issue so I'm defaulting to ask you. Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts.

**Comment by cdrini** [comment]
Will be solved by https://github.com/internetarchive/openlibrary/issues/2609
