### ISSUE TITLE
https://openlibrary.org/type/author raises a TypeError

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3824]
https://openlibrary.org/type/author raises /opt/openlibrary/deploys/openlibrary/4ed1ca3/openlibrary/templates/lib/history.html: error in processing template: TypeError: %d format: a number is required, not instance (falling back to default template)

### Relevant url?

https://openlibrary.org/type/author
https://openlibrary.org/type/author?debug=True  # For more details

### Steps to Reproduce

1. https://openlibrary.org/type/author
2. Look at the yellow box at the top of the page

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Hmm, I'm not observing an error here.

![image](https://user-images.githubusercontent.com/6251786/93933808-346b0180-fcf0-11ea-825d-ab89e65c7caf.png)

**Comment by cclauss** [comment]
![Screenshot 2020-09-22 at 23 59 21](https://user-images.githubusercontent.com/3709715/93942054-f097ec80-fd2f-11ea-92e6-d24d0e3e7ed9.png)

![Screenshot 2020-09-22 at 23 59 47](https://user-images.githubusercontent.com/3709715/93942063-f7befa80-fd2f-11ea-8b69-6475e2081f6c.png)

**Comment by Abhirup-99** [comment]
can I work on this issue?

**Comment by cclauss** [comment]
@Abhirup-99 Can you replicate this issue?  In general, we follow the “many eyes make all bugs trivial” approach so if you see an issue that you want to try to fix then do not wait for permission — just go for it.  If two people submit a pull request to fix the same issue, it is usually a learning opportunity.

**Comment by cdrini** [comment]
Hmm, this looks like it might be an i18n issue. What language is your browser? Can you expand the first "Local vars" in the debug view?

**Comment by cclauss** [comment]
![Screenshot 2020-09-23 at 18 52 41](https://user-images.githubusercontent.com/3709715/94044232-29869e80-fdce-11ea-8ac2-12fa4c8d5af3.png)

**Comment by cclauss** [comment]
`kw    {'count': }` looks suspect to me.

**Comment by cdrini** [comment]
How odd! It's showing up for me now :/ 
![image](https://user-images.githubusercontent.com/6251786/94046756-1d371d00-fd9f-11ea-94c5-23b6e90ba6b6.png)

**Comment by cdrini** [comment]
But in incognito it's fine:

![image](https://user-images.githubusercontent.com/6251786/94046944-58d1e700-fd9f-11ea-8725-e0434d645bcc.png)

**Comment by nk4456542** [comment]
#3883 issue and this issue are related, also this is occurring for 'type/collection', 'type/scan_location','type/place' etc.

**Comment by SouthGoingZax** [comment]
I think this was resolved by #3922 and can be closed.
