### ISSUE TITLE
Unique visitors graph dropped to 0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3827]
This graph dropped to 0 ~Aug 25, and hasn't quite recovered. There's a noticeable stop in a few things around this time.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/94047038-84ed6800-fd9f-11ea-8e92-ec2b6a7c251e.png)

### Relevant url?
https://openlibrary.org/

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF80
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Note it looks like this release happened on that day: https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-08-25

**Comment by mekarpeles** [comment]
See: August 25th deploy. Merging this issue w/ #3838

**Comment by cdrini** [comment]
@cclauss Could you investigate this one?

**Comment by cclauss** [comment]
Related to #2481 ?

**Comment by cclauss** [comment]
@mekarpeles and I pair programmed on this one until we discovered and `import sentry` exception being raised on `ol-www1`.  We did a `python2 -m pip install sentry-sdk==0.18.0` on `ol-www1` and re-ran the command `sudo -uwww-data sh -c '/olsystem/bin/verify-node.sh ol-www1 && /olsystem/bin/olenv /opt/openlibrary/openlibrary/scripts/ipstats.py  /opt/openlibrary/olsystem/etc/openlibrary.yml'` to get things working again.
