### ISSUE TITLE
Vladislav Polunin

### ISSUE THREAD

**Issue by VLADPOLUNIN** [internetarchive/openlibrary#3832]
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by VLADPOLUNIN** [comment]
http://williamwhitejr.com/. How are you doing today?

**Comment by guyjeangilles** [comment]
Bot be gone
