### ISSUE TITLE
ebook not appearing in search results

### ISSUE THREAD

**Issue by JeffKaplan** [internetarchive/openlibrary#3854]
search issue:
https://openlibrary.org/books/OL27928540M/Returning_To_The_Age_Of_Reason does not appear in results for ebooks.
https://openlibrary.org/search?q=title%3A+%22Returning+To+The+Age+Of+Reason%22&mode=ebooks&has_fulltext=true

**Comment by guyjeangilles** [comment]
Looks fine to me. If someone can duplicate we can reopen.
![ol3854](https://user-images.githubusercontent.com/7256157/95035201-d9ec8080-06b3-11eb-803d-f6919a58131a.png)
