### ISSUE TITLE
Do we need sudo for all steps in Docker-based deploys?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3859]
### Question

https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#docker-based-deploys-alpha
Do we need `sudo` to proceed ___all___ commands in the Docker-based deploys?

It would be helpful if the last thing that `./scripts/make-integration-branch.sh` did was `git rev-parse --short HEAD` to print out the "software version" that we should expect to see on http://staging.openlibrary.org/status   This would serve as a verification that staging is running the correct integration branch.

**Comment by cdrini** [comment]
We'd need to run `sudo usermod -aG docker YOUR_USER` (followed by a logout/login) to be able to run docker as non-sudo. Printing the SHA seems good to me!
