### ISSUE TITLE
Fix HTML validator errors for landing page

### ISSUE THREAD

**Issue by navneetsaluja** [internetarchive/openlibrary#3877]
Putting HTML code of homepage in [W3C HTML validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2F) leads to errors. (Part of a bigger move to HTML 5)
### Evidence / Screenshot (if possible)
![Selection_001](https://user-images.githubusercontent.com/54721958/94973865-77b44400-052a-11eb-8487-ed0419b357b1.png)

[ignoring warnings for now]
### Relevant url?
https://openlibrary.org

- **Environment (prod/dev/local)?** prod

@cdrini

**Comment by guyjeangilles** [comment]
We should merge this issue with #2798 which focuses on all templates

**Comment by navneetsaluja** [comment]
I was going to initially create PRs on that #2798, but I consulted Drini and he told me to create separate issues for every page since its easier to review them and some of them can be used as good-first-issue's. I might have misunderstood him though, I'll start making PRs to #2798. Thank you for letting me know.

**Comment by guyjeangilles** [comment]
@navneetsaluja Making smaller issues isn't a problem. We call them "Sub-Epics" in this repo. #2798 would be the "Epic" that all the other sub-epics are under.
