### ISSUE TITLE
Fix HTML Validator issues on /subjects page

### ISSUE THREAD

**Issue by navneetsaluja** [internetarchive/openlibrary#3881]
Putting HTML code of /subjects endpoint in [W3C HTML validator](https://openlibrary.org/subjects) leads to errors. (Part of a bigger move to HTML 5)
### Evidence / Screenshot (if possible)
![Selection_004](https://user-images.githubusercontent.com/54721958/95003188-486d0800-05fa-11eb-95b9-84b3312b65be.png)

### Relevant url?
https://openlibrary.org/subjects

- **Environment (prod/dev/local)?** prod

### Related files

If #3878 gets accepted, it fixes the first two errors. Proof: 
![Selection_006](https://user-images.githubusercontent.com/54721958/95003240-e82a9600-05fa-11eb-88c9-4f0c9988ee06.png)

Since the code for the contentBody in /subjects is handled in the production database and we cannot modify it on our local instance using git, we have to take out the HTML from http://openlibrary.org/subjects.json, create a page on the local instance, correct it, and then send the whole HTML to whoever is leading this issue (I guess?) with a screenshot as a proof to show its working locally.

### Stakeholders

@cdrini

**Comment by guyjeangilles** [comment]
Again, should be merged with #2798

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue.

**Comment by Yashs911** [comment]
> Since the code for the contentBody in /subjects is handled in the production database and we cannot modify it on our local instance using git, we have to take out the HTML from http://openlibrary.org/subjects.json, create a page on the local instance, correct it, and then send the whole HTML to whoever is leading this issue (I guess?) with a screenshot as a proof to show its working locally.

@jdlrobson so according to this we can't change this using git.

**Comment by jdlrobson** [comment]
Sorry @Yashs911 i'm not following you.

The HTML of http://localhost:8080/subjects can be generated just fine but you need to import it.

$ python scripts/copydocs.py "/subjects"

The HTML for that page can be piped into https://validator.w3.org/#validate_by_input

The reviewer (likely me) can verify the HTML is valid by the same approach and verify there are not UI regressions on the page locally.

**Comment by Yashs911** [comment]
@jdlrobson https://github.com/internetarchive/openlibrary/pull/3878#issue-497163886 according to the 4th point in the description

> The only error remaining is the Stray start tag script which the validator does not like is because the scripts in openlibrary/templates/site/footer.html are outside the <body> tag. Since all the scripts are related to analytics and therefore belong before the HTML page ends, we can ignore this error.

Should I ignore this error?
And how should I send the HTML file?

**Comment by Yashs911** [comment]
@jdlrobson I have uploaded the HTML code here https://codepen.io/yashs911/pen/dypQBVM

**Comment by jdlrobson** [comment]
Can you share the wikitext code so I can paste it into http://localhost:8080/subjects?m=edit ?

**Comment by jdlrobson** [comment]
Update: applied this change to the subject page.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fsubjects

2 errors remain - those will need changes in the codebase. THanks @Yashs911 for sorting this out!

**Comment by jdlrobson** [comment]
One more error has snuck in relating to the new hamburger menu:

```
Error: Attribute role not allowed on element label at this point.

From line 107, column 5; to line 107, column 73

nt">↩↩    <label role="button" for="toggle-hamburger" class="hamburger-button">↩     

Attributes for element label:
    Global attributes
    for — Associate the label with form control
```

**Comment by jdlrobson** [comment]
Closing as  #4447 tracks remaining issue
