### ISSUE TITLE
Creating a new work from existing and orphaned edition fails

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#3882]
I tried to create a new work from the existing [OL17874460M](https://openlibrary.org/books/OL17874460M/) by editing and selecting _move to a new work_.

### Evidence / Screenshot

![Screenshot_2020-10-04 Der Harz Open Library](https://user-images.githubusercontent.com/2772669/95013132-7aa05900-063e-11eb-9666-f8cf3fbac1a7.png)

### Relevant url?
Mayby any orphaned edition /edit

### Steps to Reproduce
1. Go to [OL17874460M](https://openlibrary.org/books/OL17874460M/) 
2. Do EDIT
3. work field
4. typ in anything and scroll to last entry _move to a new work_
5. save

* Actual: error shown in screenshot
* Expected: creating new work and assigning edition to it

### Details

- **Logged in Y**
- **Browser type/version?** firefox 81
- **Operating system?**  osx current
- **Environment?** prod

**Comment by guyjeangilles** [comment]
@seabelis Have you ever had this problem?

**Comment by seabelis** [comment]
@guyjeangilles I don't believe I've seen this specific error.

**Comment by seabelis** [comment]
This appears to be resolved. @bitnapper , can I close?

**Comment by bitnapper** [comment]
Haven't seen that bug lately. So yes, thanks.
