### ISSUE TITLE
504 Timeouts occurring for Patrons w/ several large Lists

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3896]
e.g. https://openlibrary.org/people/Hermgirl/lists.json

See: https://twitter.com/TheKateFreeman/status/1313314985129377793

**Comment by SouthGoingZax** [comment]
A gist with the output of _profile=true: https://gist.github.com/SouthGoingZax/fba883cb94f499dc28cfdc4d0bf2e79c
