### ISSUE TITLE
Archive.org/service/availability API required updates for new 1h schema

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3898]
`www/common/AvailabilityService.inc` i.e. https://archive.org/services/availability needs to be updated to support the new flags:

```
lending___is_printdisabled
lending___is_readable
lending___available_to_waitlist
lending___available_to_borrow
lending___available_to_browse
```

### Related files

`www/common/AvailabilityService.inc` in petabox

### Stakeholders

@bfalling, @judec

**Comment by Yashs911** [comment]
Hi, @mekarpeles. I would like to work on this issue. Please guide me on what all changes do I need to make and in which file.

**Comment by mekarpeles** [comment]
Hi @Yashs911 -- apologies, this code lives within the Archive.org's codebase (not Open Library) and so this has to be an issue which staff takes on.

It's currently my top priority and there's a merge request in progress internally:
https://git.archive.org/ia/petabox/-/merge_requests/2381

**Comment by mekarpeles** [comment]
This code is finished on Archive.org side (live at https://archive.org/services/availability?identifier=massachusettsbea00wall) and the Open Library side is in CR @ #4214
