### ISSUE TITLE
Create OL pages for IA lendable books without OL pages

### ISSUE THREAD

**Issue by mikemccabe** [internetarchive/openlibrary#39]
About 10% of the IA lendinglibrary / inlibrary books can't be borrowed, as there's no corresponding OL page that can be looked up via the iaid.

Possible fixes -
- Re-run imports for these books?
- 'Try harder' to find a match - look for title/author/other match, etc, and add the iaid to any discovered OL records.

**Comment by bfalling** [comment]
We should probably write a script that sweeps through all IA "books" (however defined) -- not just lendable ones -- and make sure editions(/works/authors) exist for the in OL.

**Comment by LeadSongDog** [comment]
If such a script is to be run, it should likely start with fixing the missing authors, then the missing works, and only then look for the missing editions. At each stage, minor variations in spelling, punctuation, diacritics, word-order, whitespace, capitalization, absent subtitle, etc should not defeat matching against similar extant records. This will not be trivial, but it is necessary.

**Comment by mekarpeles** [comment]
We've since fixed importbot, re-run importer on all inlibrary books, and have written back olids to archive.org to bridge the gap on this issue. Considering it closed for now (though a real-time sync / pubsub between IA and OL would be preferable)
