### ISSUE TITLE
dev.openlibrary.org security certs expired

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3903]
### Summary

- **What is wrong?**  dev.openlibrary.org security certs expired

- **What caused it?**

- **What fixed it?**

- **Followup actions:**
 

### Steps to close

1. [ ] Assignment: Is someone assinged to this issue? (notetaker, responder)
2. [ ] Labels: Is there an `Affects:` label applied?
3. [ ] Diagnosis: Add a description and scope of the issue
4. [ ] Updates: As events unfold, is noteable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [ ] "What caused it?" - please answer in summary
6. [ ] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by cdrini** [comment]
@mekarpeles Would you be able to fix this one and document how to fix it? This is well outside of what I'm good at dealing with :P

**Comment by mekarpeles** [comment]
Certs in place thanks to Andy. Server needed a restart.

abezella  3 days ago
the services on ol-dev0 need  a restart to pick up the updated cert

abezella  3 days ago
for some reason the update wasn't pulled down, so i just put it in place now

abezella  3 days ago
we should really start getting ol off trusty/14.04 asap.  cfengine2 is showing its age
