### ISSUE TITLE
Secret Key Expose in a Github Repo

### ISSUE THREAD

**Issue by pawanrawat07** [internetarchive/openlibrary#3915]
Hii
There I found something in a github repo and I want to share with you plz take a look.

Github Repo-
https://github.com/Dparmar006/OpenLib/blob/f09b2073124eaceee7316a4db4eb084901feb5a4/openLib/openLib/settings.py#L23

Secret key that I found-

SECRET_KEY = 'm(a#k1we_1$xlw395+l1auw6=grj3f@76ct3=ue7*qh#fgm1=@'

**Comment by ArunTeltia** [comment]
@pawanrawat07  This is not the bug for InternetArchive/openlibrary try adding the issue to the affected [repository](https://github.com/Dparmar006/OpenLib/issues/new)

**Comment by mekarpeles** [comment]
Thank you @ArunTeltia!

I'm going to close this issue as it applies to a different project.
