### ISSUE TITLE
Button Text "Check Availability" overflows 

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#3916]
### Relevant URL?
https://openlibrary.org
### Steps to Reproduce

1. Go to https://openlibrary.org
2. Try the website at the width of 1519px 

here is the image
![check](https://user-images.githubusercontent.com/43555219/95966211-7cc99b00-0e28-11eb-96f0-d0044145af4b.JPG)

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Microsoft Edge
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

It is a frontend related issue, following are the two ways to resolve this 
1) By making the text smaller or removing padding
2) Set a min-width of the button(cta-btn--available) to be 150px and one can increase the width of the container "test-body-mobile" by giving a media query

### Stakeholders

First time writing an issue in this repo so don't know who to tag as a stakeholder

**Comment by Yashs911** [comment]
@ArunTeltia before 1199px only 5 books are there in a row and after 1200px its 6 books per row so I guess changing the font-size might help in saving this issue.

**Comment by ArunTeltia** [comment]
I think the same I want to work on the issue If it's not the problem with you after this get accepted :D 
What I think is we have to set the min-width of the button and we can change the media query from 1200 to 1400px for 6 books 
Or 
we can increase the container width from 80% to 90% it will resolve the issue

**Comment by Yashs911** [comment]
@ArunTeltia If you want you can work on this issue.

**Comment by mekarpeles** [comment]
Thank you @ArunTeltia and @Yashs911 -- there are plenty of issue!

Since @ArunTeltia opened this one, I'd love to give them a chance to submit a PR for the solution. I'm noticing you commenting on other issues, @Yashs911 and am happy to help you find a good one and work with you to get a PR approved!

**Comment by mekarpeles** [comment]
@jamesachamp, @cdrini, @jdlrobson, & @koderjoker should all be able to offer feedback on the approach or PR :)

I'm tagging @jamesachamp as I believe they will be a great point-person / mentor for this issue.

Jim, if you decide you'd rather not be lead, please let me know and I'll be super happy to jump in :)

**Comment by jamesachamp** [comment]
I'm happy to help!

I think that changing the font size of the cta buttons will cause the visual style of some components to be inconsistent.  For example, if we lower the font size of all cta buttons, it makes the text in the dropper on a book page look a bit too large:
![all_font_change](https://user-images.githubusercontent.com/28732543/96301298-f72f2200-0fc4-11eb-8669-a6369e55a48e.png)

Changing only the font size of only `cta-btn--available` buttons can also lead to buttons of varying sized in a single carousel:
![available_font_change](https://user-images.githubusercontent.com/28732543/96301542-58ef8c00-0fc5-11eb-858c-5db1b10bbab5.png)

By default, our carousels display 6 books on screens larger than 1200px.  Would anyone be opposed to lowering the default number to 5?  This would increase the width of the book components and allow the button to grow to accommodate longer strings.

**Comment by ArunTeltia** [comment]
Yes that will be better we can make a media query for 1500px such that it will show 6 books in a row and for 1200px to 1500px 5 books will be suffice 
I also gave an idea of making the container(test-body-mobile) bigger, I think that can also be considered

As shown in picture we can create a container this big 
![container](https://user-images.githubusercontent.com/43555219/96303010-574eb400-1017-11eb-88aa-a8818e240bf8.JPG)

Please let me know your thoughts @jamesachamp

**Comment by cdrini** [comment]
I agree with @jdlrobson that reducing the markup seems like a viable option; Changing it to "Check" sounds good to me :+1:

Make sure to do a search throughout the codebase for "Check Availability"; we'll have to make updates to the i18n files as well.

**Comment by jdlrobson** [comment]
I can't replicate this bug using the description steps. Did we fix this by other means?

<img width="498" alt="Screen Shot 2021-01-09 at 9 53 50 AM" src="https://user-images.githubusercontent.com/148752/104105068-9419f800-5260-11eb-9bca-8973e47d55b8.png">

**Comment by Yashs911** [comment]
@jdlrobson I guess the **Check Availability** option was removed

**Comment by ArunTeltia** [comment]
Yes I think of the same @Yashs911 I i will close this issue with this comment
