### ISSUE TITLE
wrong video link in installation section inREADME.md

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#3920]
In the installation section of README.md, it opens the link https://archive.org/embed/openlibrary-developer-docs/zoom_0.mp4?autoplay=1&start=2 which is a dead link. What it should open is the link 
https://archive.org/embed/openlibrary-developer-docs/

Suggestion: this video is old now, I can create a new video related to setting the development environment, as I recently set up the development environment using docker 

With this Issue, I will add a PR to resolve this 

Stakeholder:
@mekarpeles

**Comment by Yashs911** [comment]
@ArunTeltia I am unable to set up the environment can you please help me. I have installed docker

**Comment by ArunTeltia** [comment]
@Yashs911 yes will be happy to help but there are some errors right now in setting up with docker 
The database is showing error check this #3919
I have reported It for now 

BTW tell me where are you stuck you can mail me at teltia.arun18@gmail.com
I will try my best to help :D
