### ISSUE TITLE
Category count number not fully visible

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#3923]
Without padding some part of the count is cut and hence does not look nice.
### Evidence / Screenshot (if possible)
![openlibrary](https://user-images.githubusercontent.com/64412143/96131271-9812d400-0f16-11eb-974b-ab737a3d7fea.JPG)

### Relevant url?
https://openlibrary.org/

### Steps to Reproduce
1. Go to https://openlibrary.org/

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Google Chrome
- **Operating system?** Windows System
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add some padding-bottom in category-count

### Stakeholders
2nd Issue

**Comment by mekarpeles** [comment]
@Yashs911 are you willing to take this one on? :)

**Comment by Yashs911** [comment]
@mekarpeles Yes, I guess adding padding-bottom: 1px; will fix the issue

**Comment by Yashs911** [comment]
@mekarpeles How can I change the docker image drive from C to D as I have less space on C drive? I am currently using Windows 10 Home.

**Comment by Yashs911** [comment]
@mekarpeles after building docker images when I run docker-compose up its shows this error and localhost:8080 says site can't be reached.
![erroropenlibrary](https://user-images.githubusercontent.com/64412143/96359038-a5ed7280-112b-11eb-9dda-da9f9739ff34.JPG)

**Comment by ArunTeltia** [comment]
@Yashs911 I will suggest you to join the Internet archive Gitter channel, here you can ask your queries
[Link to the gitter channel](https://gitter.im/theopenlibrary/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
