### ISSUE TITLE
'maximum recursion depth exceeded' on /people/304vn

### ISSUE THREAD

**Issue by SouthGoingZax** [internetarchive/openlibrary#3926]
Fixed in internetarchive/infogami#189

https://openlibrary.org/people/304vn returns:

``/opt/openlibrary/deploys/openlibrary/68474f6/openlibrary/templates/type/user/view.html: error in processing template: RuntimeError: maximum recursion depth exceeded (falling back to default template)``

https://openlibrary.org/people/304vn?&debug=true returns:

``<type 'exceptions.RuntimeError'> at /people/304vn
maximum recursion depth exceeded
Python	/opt/openlibrary/deploys/openlibrary/68474f6/infogami/utils/markdown/markdown.py in _linesUntil, line 1426
Web	GET https://openlibrary.org/people/304vn``

### Evidence / Screenshot (if possible)
![max recursion depth exceeded 1](https://user-images.githubusercontent.com/72705998/96291458-e4a0f280-0f9c-11eb-864a-5d4d94fdc19a.png)
[... a lot more of that last message ... ]
![max recursion depth exceeded 2](https://user-images.githubusercontent.com/72705998/96291465-e8cd1000-0f9c-11eb-8a5b-310182ecf539.png)
![max recursion depth exceeded 3](https://user-images.githubusercontent.com/72705998/96291471-eb2f6a00-0f9c-11eb-8f9e-bbe88380503e.png)

I haven't seen this with any other page, and I don't see any related past or present issues when searching for that error.

### Relevant url?
https://openlibrary.org/people/304vn

### Steps to Reproduce

1. Go to one of the two URLs above and wait

* Actual: (see above)
* Expected: Page renders, even if in some sort of degraded mode once a timeout is reached

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?**  Chrome
- **Operating system?** Linux
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
This specific user profile was filled with spam (we blocked the account + reverted)
https://openlibrary.org/people/304vn.json?v=2

We should keep this open, though and figure out why the recursion problem was happening
may be related to markdown

**Comment by anirbansaha782** [comment]
I want to take up this issue.
As I am new to this  contribution can to you guide me through where to look up for this issue. I am unable to locate the file markdown.py.
Thanks in advance

**Comment by SouthGoingZax** [comment]
Take a look at the "Prerequisites & Troubleshooting" section of https://github.com/internetarchive/openlibrary/blob/master/docker/README.md.  It looks like markdown.py is in the Git submodule called infogami, which I guess you might not get if you git clone the repository via https.

**Comment by cclauss** [comment]
# This page has been deleted
