### ISSUE TITLE
Sponsorship Barcode Creator: Convert ISBN10 -> 13

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3927]
I don't believe our sponsorship barcode UI converts ISBN10 requests to ISBN13 
https://8882k.codesandbox.io/#isbns=

Eliza frequently looks up books by barcode (and often times the barcode is the ISBN10.

The solution may be fairly easy -- presumably we just need to append `978` ~ Line 48 (`iaRecord` in `asyncComputed`) in https://codesandbox.io/s/8882k?file=/src/components/SponsorBookSlip.vue

**Comment by jamesachamp** [comment]
The last digit is a checksum, and will likely be different between ISBN10 and ISBN13 numbers.

**Comment by cdrini** [comment]
I'm using a JS library called `isbn3`; also using it in the Merge UI. Handles all those details :+1:

This should be good to go, @mekarpeles !
