### ISSUE TITLE
#3908 committed an update of vendor/infogami to master

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3928]
### Evidence / Screenshot (if possible)

This is important to revert.

https://github.com/internetarchive/openlibrary/pull/3908/files and scroll to the bottom.

I discovered this while investigating #3902 but I do not believe that the two are related.

#3642 and #3885 were my attempts to put a block in place to prevent this but they do seem to be a solution.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by cdrini** [comment]
It looks like this was already done by another PR! :)
