### ISSUE TITLE
Edit to a work record is recorded on edition's history

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#3930]
When a work is edited the change is saved to an edition's history. This can be confusing when viewing a record's history. Note, it seems to affect only one edition if there are multiple associated with the work.

### Relevant url?
I changed the title of the work, not the edition, however it is displayed in the edition's history. https://openlibrary.org/books/OL8645261M/Sandman?m=history

### Steps to Reproduce

I noticed when viewing an edition's history that a change I'd made earlier to the associated work was listed as a change on the edition.

* Actual: Change to work is reflected in edition's history.
* Expected: Change to work should be reflected only in the work's history.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 86.0.4240.80 (Official Build) (x86_64)
- **Operating system?** MacOS
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
I don't know about the general issue, but that specific example looks fine to me. 

The edit comment is "Moved edition to primary work." and, indeed, the parent work on the edition record changed from `/works/OL679303W` to `/works/OL679304W`

**Comment by seabelis** [comment]
Sorry, I made an additional edit after creating this issue and should have updated for clarity. Edit #12 "Restored original title on this record" was a change to the work that this edition was previously associated with. https://openlibrary.org/books/OL8645261M/Sandman?_compare=Compare&b=12&a=11&m=diff
