### ISSUE TITLE
Fix YAML Load Warnings in three files

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#3958]
Current versions of [PyYAML](https://github.com/yaml/pyyaml) want to see a Loader parameter on calls to `yaml.load()`.  Please modify these files to ensure that pytest does not raise warnings.  Hint: Investigate `safe_load()`.  On the instances in `test_update_work.py`, it would be helpful if the file was closed when we were done reading it.

### Evidence / Screenshot (if possible)

pytest generates these warnings:
```
openlibrary/plugins/admin/tests/test_services.py::test_loader
  /openlibrary/openlibrary/plugins/admin/tests/conftest.py:8: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    d = yaml.load(f)

openlibrary/tests/solr/test_update_work.py::Test_update_items::test_update_author
  /openlibrary/openlibrary/config.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    runtime_config = yaml.load(open(config_file))

openlibrary/tests/solr/test_update_work.py::Test_update_items::test_update_author
  /openlibrary/infogami/__init__.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    runtime_config = yaml.load(open(config_file))
```

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by Purhan** [comment]
Hey, can I take up this issue? This would be my first time contributing to OpenLibrary.

**Comment by cclauss** [comment]
Go ahead and submit a PR.
