### ISSUE TITLE
put one item on waitlist, got four emails

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#397]
This may have been me beta testing but I just got for emails that tell me that different editions of the same item are available for me. Screenshot follows. This was sent to jessamyn@archive.org

![screen shot 2016-12-05 at 15 27 53](https://cloud.githubusercontent.com/assets/698448/20901225/897342f0-baff-11e6-89ba-52ea8882e334.jpg)

**Comment by mekarpeles** [comment]
cc @rchrd2 -- I believe this will be addressed w/ our new lending system (and mail scheme -- everything coming from IA)

**Comment by rchrd2** [comment]
Actually, this *might* have been fixed by another change. Let's keep an eye out for this, but as far as I have experienced, this is no longer an issue.

**Comment by mekarpeles** [comment]
Will close for now under suspicion of it being fixed :) :tada:
