### ISSUE TITLE
Restarting BWB Imports through October

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3980]

**Comment by mekarpeles** [comment]
2020-11-17

Please be advised, ImportBot is actively processing BWB data for:
* 2020-08
* 2020-09
* 2020-10
* 2020-11

Monitoring as there could be performance implications of have 4 concurrent imports happening at once (especially if Archive.org daily ImportBot cron decides to run)

Now on books-lists we can run sudo bash /bwb-monthly/monthly.sh and it will automatically determine the month (e.g. 2020-11) and then conditionally run each step (from any initial directory):
See: https://github.com/internetarchive/openlibrary-bots/pull/61/files
