### ISSUE TITLE
Index all StandardEbooks imports w/ link to read books

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3982]
Standardebooks folks want to import their collection into OL as editions with links that go to standardebooks. @mekarpeles is providing support.

Needs:
- [ ] Data set of all standard ebooks books.
- [ ] Import each as a new edition
- [ ] Way to detect which work to attach new edition to

**Comment by cdrini** [comment]
@mekarpeles : Main challenge is determine it adds the identifiers correctly during import.

**Comment by mekarpeles** [comment]
What we know is StandardEbooks has a XML/opds syndication feed of books, any of which may be updated at any time.

1. First, we want to perform a `HEAD` check to see if the results have changed (compare to some state-file/historical data on disk)
2. If the results have changed, do a `GET` for the catalog and save the data
3. Loop over book catalog entries and find book records whose `update` time > the state-file last `update` time 
4. Add all these new/updates books to the `manage-imports.py` Import queue
5. Update the statefile

**Comment by mekarpeles** [comment]
Right now, importbot (the general json case) does not import covers, this should be a separate issue (to add cover url to schema)
