### ISSUE TITLE
Refresh volunteer menu

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3984]
Want: A document that lists different roles and different projects. Communicate with leads to find which tasks are "important" / which projects are currently in flight.

https://docs.google.com/document/u/1/d/1CgWXIsyn_kTZ_6n3n_zfSDuglj1yLUjVtg1EjL0Bf6E/edit#heading=h.gzsl3sqg0r51 used to be this, but is now out-of-date.

**Comment by mekarpeles** [comment]
Closing:
1. Deprecate google doc Menu for Volunteers
2. Add links to each section in /volunteer page to each lead's good-first-issues/help-wanted
3. Leads will be responsible for setting good-first-issues and help-wanted (they can provide a link in response to emails they receive from volunteers)
