### ISSUE TITLE
MVP for thebestbookon

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3985]
_(note this is issue is mainly for keeping our milestone complete; not entirely related to OL folks)._

https://github.com/Open-Book-Genome-Project/TheBestBookOn.com is getting close to getting an MVP ready!

MVP means:
- [x] Can submit recommendations
- [x] Can view recommendations

**Comment by mekarpeles** [comment]
UI work still requires for community, but basic flow for MVP is in place :)
