### ISSUE TITLE
Book Genome Project: Run on "Staff Picks" collection

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3986]
_(note this is issue is mainly for keeping our milestone complete; not entirely related to OL folks)._

https://github.com/Open-Book-Genome-Project/sequencer 

CC @finnless

**Comment by mekarpeles** [comment]
cc: @finnless

**Comment by cdrini** [comment]
This set was meant to be used as a dummy test ; OBGP was tested on an other set, so this is no longer necessary.

See related #5725
