### ISSUE TITLE
Data dump for reading log stats

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3989]
Currently there's no dump of reading log stats. Let's make a public dump of it.

- [x] https://github.com/internetarchive/olsystem/pull/131 Should run regularly
- [x] Reading log bookshelves SQL command with anonymization
    - [x] #5426
    - [x] #5529
- [x] Anonymization test.
- [x] Run manual dump with the new code https://archive.org/download/ol_dump_2021-08-11
- [x] #5546 Add download API for ratings/readinglog
- [x] Deploy
- [x] Add link/docs to https://openlibrary.org/developers/dumps

### Stakeholders
@cdrini

**Comment by cdrini** [comment]
Plan is to dump the reading log table, and extract data with the following columns:


| WorkId | EditionId? | Date | Shelf
| --- | --- | --- | --- |
| OL151997W | NULL | 2020-08-10 | Want To Read

Similarly for ratings

| WorkId | EditionId? | Date | Rating |
| --- | --- | --- | --- |


This format will allow temporal analysis, which is nice, and is also easier to export.

**Comment by cdrini** [comment]
@BharatKalluri Would you be interested in taking this one? The general idea is to add a dump script to OL that dumps the reading log postgres table.

**Comment by BharatKalluri** [comment]
Sure, I would need some help in setting up because I only setup and worked on OL client up until now. I would love to work on this! 👍🏽

**Comment by BharatKalluri** [comment]
Hi @cdrini , As far as I understand, master dump is generated from bash (https://github.com/internetarchive/openlibrary/wiki/Generating-Data-Dumps)

Here are the commands for generating dumps , let me know if they work as expected

### Queries

**Reading log query**

```
select bookshelves_books.work_id,bookshelves_books.edition_id, bookshelves.name, bookshelves_books.updated from bookshelves_books join bookshelves on bookshelves_books.bookshelf_id = bookshelves.id;
```

**Ratings query**

```
select ratings.work_id, ratings.edition_id, ratings.created, ratings.rating from ratings;
```

### `psql` reading log dump command

```
psql -U openlibrary -d openlibrary -c "copy (select bookshelves_books.work_id,bookshelves_books.edition_id, bookshelves.name, bookshelves_books.updated from bookshelves_books join bookshelves on bookshelves_books.bookshelf_id = bookshelves.id) to stdout" | gzip -c > reading-log.txt.gz
```

### `psql` ratings dump command

```
psql -U openlibrary -d openlibrary -c "copy (select ratings.work_id, ratings.edition_id, ratings.created, ratings.rating from ratings) to stdout" | gzip -c > ratings.txt.gz
```

Let me know how this should be integrated into the [dump python script](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/data/dump.py)

**Comment by cdrini** [comment]
Wonderful! I think running this from postgres directly seems good :+1: I'll give it a go on prod to see how it works!

**Comment by cdrini** [comment]
Could you open a PR adding these as .sh files? I think theres scripts/dumps dir? If not, maybe create scripts/dump-ratings.sh .

**Comment by cdrini** [comment]
I tested as follows on prod:

```sql
EXPLAIN SELECT bookshelves_books.work_id, bookshelves_books.edition_id, bookshelves.name, bookshelves_books.updated
FROM bookshelves_books join bookshelves on bookshelves_books.bookshelf_id = bookshelves.id
```

```
                                    QUERY PLAN
----------------------------------------------------------------------------------
 Hash Join  (cost=25.98..115688.86 rows=3055195 width=48)
   Hash Cond: (bookshelves_books.bookshelf_id = bookshelves.id)
   ->  Seq Scan on bookshelves_books  (cost=0.00..73653.95 rows=3055195 width=20)
   ->  Hash  (cost=17.10..17.10 rows=710 width=36)
         ->  Seq Scan on bookshelves  (cost=0.00..17.10 rows=710 width=36)
```

That looks reasonable; a seq scan on `bookshelves_books` would usually be a problem for a query, but since we're dumping the table, that's necessary :)

As a sanity check, ran:

```sql
SELECT bookshelves_books.work_id, bookshelves_books.edition_id, bookshelves.name, bookshelves_books.updated
FROM bookshelves_books join bookshelves on bookshelves_books.bookshelf_id = bookshelves.id
LIMIT 10
```

```
 work_id  | edition_id |     name     |          updated
----------+------------+--------------+----------------------------
  4439701 |            | Already Read | 2017-12-11 20:02:54.757479
    63060 |    5816906 | Already Read | 2017-12-26 02:32:29.626215
 10417330 |            | Want to Read | 2017-11-08 02:44:44.168561
  4466500 |    2712504 | Want to Read | 2017-11-08 18:29:21.959072
 14850224 |    7729290 | Already Read | 2017-11-08 18:29:27.401058
  5920528 |            | Want to Read | 2018-01-05 12:36:56.17951
 15852999 |            | Want to Read | 2018-03-15 21:59:01.671517
  3743769 |    4114449 | Already Read | 2017-11-10 01:23:27.765112
  4619760 |   16479114 | Want to Read | 2018-02-06 21:51:39.863213
  3603559 |    3548301 | Want to Read | 2017-12-29 20:42:01.942018
```

Looks good! Two things:

- can we use postgres to modify `work_id` and `edition_id` and convert them to `/works/OL...W` style strings? That would make it more consistent with our other dumps. Something like `SELECT concat('/works/OL', bookshelves_books.work_id, 'W') as work_id, ...` might do the trick.
- Is it a problem to include the datetime... Is there a way that might be used to de-anonymoize the data... Can we do something similar to the above and only make it the updated column go to the hour? So `2017-12-11 20:00:00.00000`. That might be good enough? Or is that unnecessary? CC @mekarpeles @bfalling 

Finally ran the whole thing:

```sh
time psql -U openlibrary -d openlibrary -c "copy (select bookshelves_books.work_id, bookshelves_books.edition_id, bookshelves.name, bookshelves_books.updated from bookshelves_books join bookshelves on bookshelves_books.bookshelf_id = bookshelves.id) to stdout" | gzip -c > /tmp/reading-log.txt.gz
```

Took 9s, generated a 43MB gzip! Generated a file:

```
$ zcat reading-log.txt.gz | head
4439701 \N      Already Read    2017-12-11 20:02:54.757479
63060   5816906 Already Read    2017-12-26 02:32:29.626215
10417330        \N      Want to Read    2017-11-08 02:44:44.168561
4466500 2712504 Want to Read    2017-11-08 18:29:21.959072
14850224        7729290 Already Read    2017-11-08 18:29:27.401058
5920528 \N      Want to Read    2018-01-05 12:36:56.17951
15852999        \N      Want to Read    2018-03-15 21:59:01.671517
3743769 4114449 Already Read    2017-11-10 01:23:27.765112
4619760 16479114        Want to Read    2018-02-06 21:51:39.863213
3603559 3548301 Want to Read    2017-12-29 20:42:01.942018
```

Which lgtm :+1:


Ran the ratings one (note I removed the table name from the fields, since we only have one table here):

```sh
time psql -U openlibrary -d openlibrary -c "copy (select work_id, edition_id, created, rating from ratings) to stdout" | gzip -c > /tmp/ratings.txt.gz
```

And got back:

```
$ zcat ratings.txt.gz | head
17882343        \N      2018-06-20 09:02:48.767794      3
1629179 22981670        2018-06-20 11:01:26.166709      5
4226036 10690412        2018-06-20 11:08:13.551397      5
5264255 2719185 2018-06-20 11:24:29.492492      5
1681415 2582724 2018-06-20 11:56:14.533028      5
1837390 \N      2018-06-20 13:07:45.798319      5
1853596 2331075 2018-06-20 13:58:02.384528      2
15197048        \N      2018-06-19 04:18:26.65533       5
472910  \N      2018-06-20 13:58:55.308396      5
18342   26445972        2018-06-20 20:35:31.65127       4
```

Which looks good! Same concern about datetime though. Also it seems like we're missing headings? I wonder if there's a way to auto add that in...

**Comment by cdrini** [comment]
Re-opening until I add this to the monthly dump cron job

**Comment by cdrini** [comment]
Ran manual dump with:

```sh
tmux
# ---
COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml" \
HOSTNAME="$HOSTNAME" \
docker-compose run \
    -u openlibrary \
    -e "SCRIPTS=/openlibrary/scripts" \
    cron-jobs \
    bash
# ---
curl 'https://patch-diff.githubusercontent.com/raw/internetarchive/openlibrary/pull/5529.diff' | git apply
cd /1/var/tmp
/olsystem/bin/cron/oldump.sh ol-db1 openlibrary `date -d yesterday '+%Y-%m-%d'` --archive
```

Waiting...

**Comment by cdrini** [comment]
Grr it errored with `error waiting for container` :/

**Comment by cdrini** [comment]
Darn, ol-home0 docker daemon restarted for some reason ~13 hours ago. Restarting from scratch :(

**Comment by cdrini** [comment]
Stopped to try to get the automatic cron job working with @mekarpeles ; we think we got it!

**Comment by cdrini** [comment]
It randomly failed again :( Kicking it off one more time outside of cron
