### ISSUE TITLE
Solr should including stale ratings numbers

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3990]
Although this data might be out-dated, if we do a full reindex every month, it should be approximately correct.

Main goal: Solrbuilder full reindex should be able to fetch this data, and store it, and make it available for query.

- [x] Get loading of ratings working in solr-updater
- [x] Get loading of ratings working in solr-builder
- [x] Kick off solr reindex to test ratings
- [x] Fix any issues
- [x] Start solr next updater with correct code

### Stakeholders
@mekarpeles @cclauss

**Comment by cdrini** [comment]
What could we want to use this for:

- Ratings
    - Display aggregate graphs like this:
    ![image](https://user-images.githubusercontent.com/6251786/129408410-54a4d802-68e3-4eaf-aa15-63cc331111bd.png)
    - Sort books by highest rated
    - Filter books by rating (only show my sci fi books with a rating > 3)
- Reading log
    - Find me the most want-to-read sci fi book
    - Find me the most read sci fi book

- (PUNT) Trends:
    - What books have received a lot of ratings this month? this week? this year?
    - What's the highest rated book this year? Last year
    - What's the most want-to-read book this year
    - PUNTing because these don't really map to a something people want, since once a book is moved from WTR -> Read, the row is deleted. So I'm not actually seeing "What's the most wtr book this month", but "what's the book that was most added to wtr in this month and then never moved". Not really what I want.
    - Same with ratings; when a book was rated doesn't matter. If we had End-date tracking, that might work.
    - Also, not sure what the best way to store that in solr. Having something for just the current month might be reasonable?

- Data we need on each work:

```
ratings_avg: 3.5
ratings_median: 4.2
ratings_count: 15
ratings_buckets: [4, 3, 0, 1, 7]
# Might need to be like so:
ratings_buckets_1: 4
ratings_buckets_2: 3
ratings_buckets_3: 0
ratings_buckets_4: 1
ratings_buckets_5: 7

rl_to_read: 16
rl_currently_reading: 3
rl_already_read: 32
```

**Comment by mekarpeles** [comment]
Trending
`reading_log_total`
`reading_log_monthly`
`reading_log_weekly`

These will get overwritten each re-index

e.g. Show me all results filtered by things that are trending w/ activity this month

**Comment by cdrini** [comment]
Going to try add a hook before new data is written to the DB to write to solr, so that the numbers keep updating.

**Comment by cdrini** [comment]
Note converting this issue to be just for ratings; will create a separate issue for reading log, since it introduced some unique challenges, and don't want to hold this up.

**Comment by cdrini** [comment]
Going to release first stab which is just stale numbers which get copied over during reindex.
