### ISSUE TITLE
Sentry should include deployment SHA

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3991]
Sentry has options for specifying the SHA of the current code, so you can see when an error was introduced. We currently don't take advantage of this.

### Stakeholders
@cdrini

**Comment by cclauss** [comment]
This might already be happening...
![Screenshot 2020-11-01 at 19 14 56](https://user-images.githubusercontent.com/3709715/97810838-01b11300-1c77-11eb-9e29-d1d416785ee0.png)

Those 12-digit hex server names seem to link to the [12-digit hex host number on the `status` page](http://ol-web1.us.archive.org:8080/status?debug=true).

`ol-web3` events do not seem to be going into Sentry but `ol-web4` events do.

**Comment by cdrini** [comment]
This is the docker container SHA; it'll changer every time the docker container is rebuilt. Not sure why sentry is using that.

**Comment by cdrini** [comment]
ol-web3 is currently not hooked up to sentry to reduce load (in theory now that we know how to set sentry quotas, we might want to try to connect it as well with a quota; but something to do when we're bored :P )
