### ISSUE TITLE
Retire ol-web3 & ol-web4

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#3992]
With ol-web1 running python3, we want to connect ol-web1 permanently and remove our old python2 ol-web3/4.

Blocked by: ~#890~, ~#3333~, and ~#3993~.

- [x] Retire ol-web3
- [x] Retire ol-web4
- [ ] Remove refs to ol-web{3,4} from olsystem

**Comment by cclauss** [comment]
It would be of interest to use one of these servers (`ol-web3`) as a testing ground for `staging.vNext` which will be based on [`k3d`](https://k3d.io/) and [`k3s`](https://k3s.io).  This would provide a fast self-contained single-node Kubernetes cluster for implementing declarative configuration of our staging environment.

This cluster would manage one `memcached` container and two `openlibrary_web_1` containers.  As changes are made to our test branch the cluster would restart one webnode after the other.  Doing so would achieve two objectives:
1. Establish the automation to keep staging running reliably while making it easier for new contributors to test on.
2. Teach us how to configure openlibrary in a self-healing environment for prod.vNext.

Todos:
* [ ] Agree on the utility of this activity
* [ ] Upgrade os from Ubuntu 14.04 to 20.04
* [ ] Install docker
* [ ] Install k3d
* [ ] Git pull openlibrary and infogami
* [ ] Create k3s cluster config

**Comment by cclauss** [comment]
ol-web3 is now gone.

**Comment by cdrini** [comment]
@abezella and @mekarpeles Decomissioned ol-web4 as well 🎉

**Comment by cdrini** [comment]
This will be closed by  internetarchive/olsystem#111
