### ISSUE TITLE
Error in processing template on /lists on local instance

### ISSUE THREAD

**Issue by navneetsaluja** [internetarchive/openlibrary#4005]
If we create a list locally with more than one book, it shows the error: 
```
/openlibrary/openlibrary/templates/recentchanges/lists/comment.html: error in processing template: AttributeError: 'module' object has no attribute 'Seed' (falling back to default template)
```
(with ?debug=true)
```
<type 'exceptions.AttributeError'> at /lists
'module' object has no attribute 'Seed'

Python | /openlibrary/openlibrary/plugins/upstream/models.py in get_seed, line 953
-- | --
GET http://localhost:8080/lists
```
Stack trace is sent below.

### Evidence / Screenshot (if possible)

I added 3 books to the list, so it shows the error twice. (does not show on only one book in the list)
![Selection_017](https://user-images.githubusercontent.com/54721958/97899750-ac046580-1d5f-11eb-8027-0faa40566a35.png)

![Selection_016](https://user-images.githubusercontent.com/54721958/97899675-9e4ee000-1d5f-11eb-8980-d67d4dda9cbe.png)

### Relevant url?
http://localhost:8080/lists

### Steps to Reproduce

1. Make a new list with a book using the steps [here.](https://openlibrary.org/help/faq/reading-log)
2. Add another book to the same list.
3. Go to /lists (http://localhost:8080/lists).

* Actual: Error in processing template (Nothing is displayed under Active Lists either, maybe a result of this)
* Expected: Layout similar to https://openlibrary.org/lists 

### Details

- **Logged in (Y/N)?** Y (with the admin openlibrary account for the local instance)
- **Browser type/version?** Mozilla Firefox for Ubuntu 81.0.2 (64-bit)
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** local

### Proposal & Constraints

Not sure.

### Stakeholders

Related to docker, so @cdrini.

Note: @nk4456542 tested this as well, same bug.

**Comment by jamesachamp** [comment]
I am not able to reproduce these errors.

Lists are not displayed beneath the "Active Lists" header unless they contain more than four books.
