### ISSUE TITLE
K-12 Page erroring on Python 3

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4006]
`/openlibrary/openlibrary/templates/type/page/view.html: error in processing template: AttributeError: 'str' object has no attribute 'decode' (falling back to default template)`

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/97905490-142b5b00-1d10-11eb-886e-82ad991b5bdb.png)

### Relevant url?
openlibrary.org/collections/k-12 on Py3

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
Closed in https://github.com/internetarchive/infogami/pull/124

**Comment by cdrini** [comment]
@cclauss I'm still seeing this on ol-web1; could you switch to the latest code there?

**Comment by cclauss** [comment]
Will do
