### ISSUE TITLE
Category and bookcover outlines are hidden (Accessibility issue)

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4012]
When one tab through the openlibrary homepage, some component only show the top or bottom outline
### Evidence / Screenshot (if possible)
![tab1](https://user-images.githubusercontent.com/64412143/98074261-10264700-1e90-11eb-864e-ba528bc2c417.JPG)

### Relevant url?

https://openlibrary.org/
### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Use Tab 

* Actual: 
![tab1](https://user-images.githubusercontent.com/64412143/98074317-30560600-1e90-11eb-809b-e42e35536e1e.JPG)

* Expected: 
![tab](https://user-images.githubusercontent.com/64412143/98074322-33e98d00-1e90-11eb-95c9-c1e75375efe4.JPG)

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
![a](https://user-images.githubusercontent.com/64412143/98074955-6b0c6e00-1e91-11eb-944c-f49e5b21bb53.JPG)

**Comment by aavishkarmishra** [comment]
I would like to work on this but can anyone help with from where can I start any how to check updated css in docker?

**Comment by Yashs911** [comment]
@aavishkarmishra I want to work on the issue. But don't worry you will find plenty of good first issues. 
Regarding your query, I would suggest first install docker and set up the openlibrary locally. If you face any problem you can ask here https://gitter.im/theopenlibrary/Lobby

**Comment by aavishkarmishra** [comment]
@Yashs911 Please look into mentioned issue also.

**Comment by Yashs911** [comment]
Hi @jamesachamp Should I go ahead with the proposed changes

**Comment by jamesachamp** [comment]
Yes, go ahead.  To clarify, you'll be working on the buttons, covers, and category items?

**Comment by Yashs911** [comment]
> Yes, go ahead. To clarify, you'll be working on the buttons, covers, and category items?

@jamesachamp Yes
