### ISSUE TITLE
Python 3: could not display: <AttributeError: 'type'>

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4015]
http://ol-web1.us.archive.org:8080/subjects/biology?debug=true
```
<class 'AttributeError'> at /subjects/biology
can't set attribute
Python	/openlibrary/openlibrary/core/lists/model.py in __init__, line 323
Web	GET http://ol-web1.us.archive.org:8080/subjects/biology
```

### Evidence / Screenshot (if possible)

![Screenshot 2020-11-04 at 20 57 44](https://user-images.githubusercontent.com/3709715/98161763-923e5c00-1ee0-11eb-8fee-85576e75a004.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
https://stackoverflow.com/questions/4183432/cant-set-attribute-with-new-style-properties-in-python
