### ISSUE TITLE
Docker Deployment Strategy for ol-web[1,2]

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4017]
- [x] connect ol-web[1,2] to sentry
- [x] restart always
- [x] set docker-compose hostname on docker-compose to match parent machine (for sentry)
- [x] for production, we don't want to mount /openlibrary inside the container (because pulling will mess things up)?
- [x] We need to edit
https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#ol-web1
such that the instructions have a path for concurrently building a new latest image for Open Library after a deploy, without taking down the running service on that web-node.

For 2020-11-05 Thu, we should try building the `oldev` image on `ol-home` and then rsyncing it over to ol-web1 and ol-web2.
We'd then do a docker down and a git pull and a docker up (as per the provisioning docs) to restart the container.

**Comment by cclauss** [comment]
I am a bit lost on this issue...

Why do we want to deploy on ol-web{1,2}?  I thought our goal was to take them ___out___ of circulation.

**Comment by cclauss** [comment]
Please review https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide-on-Python-3 which is an updated version of https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide.  Once we are satisfied with this we can switch it over to replace the existing guide.

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide is now the Python 3 instructions and the Python 2 instructions are still available at https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide-for-Python2.
