### ISSUE TITLE
More dropdown is overlapping with search

### ISSUE THREAD

**Issue by aavishkarmishra** [internetarchive/openlibrary#4026]
More dropdown is overlapping with search in navbar.
### Evidence / Screenshot (if possible)
![Screenshot_2020-11-05 Welcome to Open Library Open Library](https://user-images.githubusercontent.com/58372823/98273498-58408900-1fb8-11eb-83a1-b8e8b6427a9a.png)

###Expected:  Can be shifted little down to remove over lapping.

#4012  @Yashs911 Please look into this also.

**Comment by Yashs911** [comment]
@aavishkarmishra wait for members and collaborators to review this issue.
