### ISSUE TITLE
Add a 'genre' form field (separate from subjects)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4027]
Problems:
- The OL staff needs to make their own judgments on which carousels to pick
- Labels are currently used to group books, but subject keywords are details about a book, not a genre
- a large part of what comprises a book is not on the OL

Solution:
- adding a genre box allows for user/bot input instead of staff - offloads work
- separates genre from other labels

The benefit of this is that once these genres appear, then carousels could be formed by these. Yes, I know that already exists this way, but it'll be more exact - and match other libraries and where books are supposed to go.

**Comment by bwright8** [comment]
I am new, but could I try to work on this? I have a passion for books and would love to see this issue solved.

**Comment by bwright8** [comment]
I was working on this today but ran into a couple issues. I can add a genre form field to an "edit work" page. But as I try to "save" an edit, the local Open Library instance (via docker) gives me an error page. Is there a way to test editing test data locally?

**Comment by bwright8** [comment]
I wonder if logging in as an admin would help, but I am also having the same issue as #4090

**Comment by tuminzee** [comment]
> #4090

I am sure you solved this issue, but I am still want to know. Did it solve your issue?

**Comment by tuminzee** [comment]
Sorry @BrittanyBunk it took me some time to reply to this, but I really like the early references which you have tagged here

**Comment by BrittanyBunk** [comment]
@bwright8 thank you so much for working on this!

**Comment by bicolino34** [comment]
I support this idea. At the current state, subjects can't be internationalized #791

**Comment by mekarpeles** [comment]
@jimchamp and I have plans around subjects (moving many subjects out of the subjects field and into a relational database similar to what we're doing for Community Tags). I'd rather not start a 3rd effort. Ideally everything uses the ~Community Tags structure which has `genre` as a field already.
