### ISSUE TITLE
all.js contains an invalid selector SyntaxError on line 26

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4035]
### Evidence / Screenshot (if possible)
Paused on exception SyntaxError: Element.querySelectorAll: '*,:x' is not a valid selector

![Screenshot 2020-11-06 at 09 51 30](https://user-images.githubusercontent.com/3709715/98347878-4f7f9f80-2018-11eb-8772-f7438bd22d63.png)

https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#alljs-and-custom-javascripts
Often when I am trying to use the Firefox Inspector, it is hung up on the SyntaxError.
### Relevant url?
https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jdlrobson @cdrini @jamesachamp

**Comment by jamesachamp** [comment]
It looks like this issue is fairly widespread (occurring on the home page, book pages, search, etc.).  I'll devote some time to this today.

**Comment by cdrini** [comment]
This looks like a false alarm; the error is inside jquery code, and correctly handled by jquery code. Unchecking "Pause on caught exceptions" should avoid the debugger breaking here :+1:
