### ISSUE TITLE
Send-to-Kindle

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#404]
Any reason the send functionality only works on one brand of cloud, and at that, one which is tied to a proprietary reader? How about supporting non-DRM files on Gdrive, Box, Dropbox, OneDrive, etc? Even better, support an open transport protocol to an arbitrary address, such as by ftp.

@Tpt It would be very cool to have further support for moves to Wikimedia Commons, as discussed at https://en.wikisource.org/wiki/Help:Internet_Archive#Adding_files perhaps by invoking https://tools.wmflabs.org/ia-upload which uses the code at https://github.com/Tpt/ia-upload

**Comment by Tpt** [comment]
@LeadSongDog It's a great idea! https://tools.wmflabs.org/ia-upload  has still some known bugs that makes the workflow sometime complicated (especially now because IA has removed DjVu generation and our PDF to DjVu converter has some issues) but it's definitely something we should work on.

**Comment by LeadSongDog** [comment]
Format conversion is rather a secondary issue.  While it's great to have OCR'd searchable content, ensuring independent copies exist (irrespective of which format) should come first. https://en.wikipedia.org/wiki/LOCKSS

**Comment by LeadSongDog** [comment]
https://en.wikipedia.org/wiki/LOCKSS
While having well-catalogued copies with OCR'd searchable formats is wonderful, the first priority ought to be simply to have independently maintained copies.  Let's focus on easing the transport first and worry later about format conversions.

**Comment by guyjeangilles** [comment]
@mekarpeles I'm not sure who should be assignee for this issue, so I'm defaulting to you/your suggestion. Note: being assignee doesn't necessarily mean you are the one doing the work for the issue but responsible for collecting information needed to devise a solution. From the wiki:

>At submission and prior to triage, the assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per the issue's context. Let me know your thoughts.

**Comment by RayBB** [comment]
This feature was removed way back in #446 
However, feel free to reopen or make a new feature request if you think this is something that should be added again.
