### ISSUE TITLE
i18n files not built automatically on Python 3 web nodes

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4040]
### Steps to Reproduce

1. Go to https://openlibrary.org/books/OL25428864M/Americanah?lang=fr

* Actual: Page is in English
* Expected: Page has buttons in French (like https://dev.openlibrary.org/books/OL25428864M/Americanah?lang=fr)

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss

**Comment by jamesachamp** [comment]
Dates are being translated, so the issue may lie in our i18n compilation process:
![i18n_issue_fr](https://user-images.githubusercontent.com/28732543/98397258-130a6e80-202d-11eb-9422-80393a8df6fe.png)


Is there an `.mo` file in `openlibrary/i18n/fr`?  If not, try running `make i18n` and check again.

**Comment by cdrini** [comment]
:+1: That looks like it; `make i18n` looks like it wasn't run at all :/ Dropping in priority

**Comment by cdrini** [comment]
I ran it manually, but we have to figure out why this wasn't run automatically during the build process

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/pull/3906#pullrequestreview-518213407
https://github.com/internetarchive/openlibrary/pull/2253

**Comment by cdrini** [comment]
False alarm; I'm going to assign this one to myself. It was a docker issue, not a code issue.
