### ISSUE TITLE
Fix patron block and revert functionality where /type/delete encountered

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4045]
In #711 there is a case where a user has been blocked. There is an issue with reverting all of their changes because one of them has already been deleted and is registering as /type/delete instead of /type/author.

```
<class 'infogami.infobase.client.ClientException'> at /admin/people/AliceKirk/edits
expected /type/author, found /type/delete

Python | /opt/openlibrary/deploys/openlibrary/824a904/infogami/infobase/client.py in handle_error, line 84
POST https://openlibrary.org/admin/people/AliceKirk/edits
```

Success criteria:
- [ ] an admin should revert all of AliceKirk

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/711#issuecomment-723378773_

**Comment by benbdeitch** [comment]
Hello! Could you assign me to this issue?
