### ISSUE TITLE
Book cover missing

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4047]
Book cover is missing src generated src="http://covers.openlibrary.org/b/id/-1-M.jpg"
### Evidence / Screenshot (if possible)
![cover](https://user-images.githubusercontent.com/64412143/98435315-592d0400-20f9-11eb-8796-7d5f9b0e47c4.JPG)

### Relevant url?
https://openlibrary.org/collections/k-12

### Steps to Reproduce

1. Go to https://openlibrary.org/collections/k-12

* Actual: above image
* Expected: 
![cover1](https://user-images.githubusercontent.com/64412143/98435520-85e11b80-20f9-11eb-9818-eab19000292d.JPG)

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome 
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
@cdrini Can you guide me on how to fix this issue?

**Comment by Romi-776** [comment]
** Hey, @Yashs911 and @cdrini. **

Maybe I found the solution to this issue but I don't know how to implement this?

What's going on in this issue?
    The book cover (of book "I am going to read") is not visible on this page: https://openlibrary.org/collections/k-12
    But it should be visible.

* The information I found: *
    Image link of this book on that page is:- https://covers.openlibrary.org/b/id/-1-M.jpg

**What is the solution?**
  **  Image link should be:- https://covers.openlibrary.org/b/id/10507160-M.jpg  **

**Comment by dwaipayan05** [comment]
It's part of the sprint, we need to get this done. Can anyone guide in how to go through this, all I know is that its about a missing Cover ID of size M.

**Comment by mekarpeles** [comment]
We believed this is resolved by #4667
