### ISSUE TITLE
Add a new Nagios alert for severe outages

### ISSUE THREAD

**Issue by SouthGoingZax** [internetarchive/openlibrary#4062]
There have been two large, long outages recently that appear to not have been noticed (or their severity was perhaps unknown) for quite some time until they were escalated to staff members on Slack, at which point they were quickly resolved.

Homepage (and more?) outage on 2020-11-07:
![image](https://user-images.githubusercontent.com/72705998/98481352-796aca80-21ae-11eb-911c-44c63368107a.png)

Search outage on 2020-10-25 (#3960):
![image](https://user-images.githubusercontent.com/72705998/98485007-4c2b1600-21c8-11eb-8c9c-2fd526222d25.png)

It sounds like a contributing factor could be that alerts for severe incidents can get lost in alerts for low severity incidents and/or that people get desensitized when incidents that trigger alerts often resolve themselves.

### Describe the problem that you'd like solved

It would be nice to have clearer, actionable signals that don't get lost in the noise when there are significant outages.

### Proposal & Constraints

There might be an opportunity to tweak the existing alerts to be less noisy, but absent that, a new alert whose name stands out (e.g., SevereSiteErrors) and that will trigger when the site is clearly having a bad time (5K errors/second for X minutes?) could help alert staff to more severe problems in a clearer way.

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
All three of core staff are now on nagios alerts + our nagios alerts have been updated so we're hoping this somewhat alleviates the issue (and will result in faster detection time)
