### ISSUE TITLE
Remove grayscale filter from browse by subject images

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4063]
- [ ] 1)Everything from book covers to graphs is colorful so what's the reason behind applying a grayscale filter on Browse by subject images

### Evidence / Screenshot (if possible)
![bw](https://user-images.githubusercontent.com/64412143/98636261-845b6180-234c-11eb-8ebf-dfb2a8049405.JPG)

![img](https://user-images.githubusercontent.com/64412143/98636272-89201580-234c-11eb-9c2a-3d31398a060e.JPG)

- [ ] 2) Remove margin from h3 tag in order to align it properly
![1](https://user-images.githubusercontent.com/64412143/98636468-ee740680-234c-11eb-809c-bce343f50dd3.JPG)

Expected:
![2](https://user-images.githubusercontent.com/64412143/98636477-f338ba80-234c-11eb-8972-591df482f34a.JPG)

### Relevant url?

https://openlibrary.org/
### Steps to Reproduce

1. Go to https://openlibrary.org/

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jamesachamp

**Comment by Yashs911** [comment]
@mekarpeles Should I go ahead and create a PR for both these minor issues

**Comment by SouthGoingZax** [comment]
@Yashs911 feel free to send a PR and ask @jamesachamp for a review
