### ISSUE TITLE
Intellectual freedom. Terms of service. Privacy policy

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#4070]
We can't keep overlooking or downplaying this topic.

The OL homepage footer link "Terms of Service" goes to https://archive.org/about/terms.php

While I believe that Easter egg to be an error, even if it is still the agreed-upon behaviour, that target needs some serious work on the way it addresses librarianship, law, user communication, and technology. 

Its privacy discussion section, written 10 March 2001, is nearly two decades out of date, pertaining to a world gone by. 

It refers to Apache, Internet Explorer, and Netscape Navigator but makes no mention of GOOG, AMZ, or FB, all of which OL has been bending over backwards to enable rather than limit.  If the truth is that OL and IA are going to be doing very little to protect the user's privacy, then that should at least be admitted clearly and visibly, such as a simple statement: **"Expect no privacy, we will spill all your beans. Live with it or leave."** At least that would be honest, though of course I think we should simply do better and try *hard* to protect intellectual freedom.

The ALA holds that the principle of user privacy protection is a key aspect of librarianship, as seen in many discussions, such as at https://journals.ala.org/index.php/ltr/issue/view/190 or in their Intellectual Freedom Manual.

Consider the comparable LoC page at https://loc.gov/legal/privacy-policy/ which makes clear what is and is not done with users' personal information there. Similarly, the BL page at https://www.bl.uk/about-us/privacy-policy makes clear their intent.

The best behaviour for librarians and library systems *should* be to keep only the bare minimum of user personal information needed for the library to function, *and* to do so in a way that ensures even that information is unavailable for other purposes. 

My municipal public library card number does not link me to my past reading, only my current loans and holds. It simply identifies me as being a unique authorized patron (a.k.a. a ratepayer or dependent). An encrypted and firewalled system links that card number to my email address for overdue notices etc. That's it. If I log in, it is via an https page that allows me to choose (if I wish) to track and share the current, hold, and completed lists under a user name of my choice, and allows me to control such sharing down to the individual titles. The server is in my country and subject to the privacy laws of that one country alone. That limited personal information is disclosed only by my choice or in response to a specific court-ordered search warrant. I can freely read about and think about books on topics which are unpopular, contrary to any ruling elite's interests, considered immoral by my family, or even which advocate ideas held by some people in some places to be illegal or dangerous. I don't need to worry that a book read at home (on e.g. abortion, sex, politics, crypto, human rights) will get me arrested if I go abroad (to Poland, Nigeria, Venezuela, Cuba, or China respectively). My reading is MY reading, as it should be. 

Why should the OpenLibrary *not* choose to demonstrate best behaviour?

**Comment by mekarpeles** [comment]
@LeadSongDog I wanted to give you an update that I've forwarded this feedback to our policy team for review.

There are a few points which resonate:

> refers to Apache, Internet Explorer, and Netscape Navigator but makes no mention of

I'm not sure what this list of services should be, I'm not a lawyer, but the sentiment of refreshing these seems like it may be useful to patrons and the Archive alike.

> principle of user privacy protection is a key aspect of librarianship

Another area where an opportunity exists to spell our what options patrons have, where user-generated data may be public (which on Open Library is many places: Lists, profile page, etc), where user data may not be public (e.g. things like loan history), and perhaps what options patrons have with respect to setting privacy (e.g. Reading Log https://openlibrary.org/account/privacy)

I'll see if I can update this issue with some response to understand what actions or timelines may be available.

**Comment by LeadSongDog** [comment]
@mekarpeles Thanks for the feedback, I was beginning to think it had gone unread.

**Comment by mekarpeles** [comment]
I have a call with policy team to offer feedback today. I will do my best to convey these thoughts. Thank you

**Comment by mekarpeles** [comment]
The right teams are investigating if and how they may be better surfaced to patrons in a way which addresses the spirit of this issue. I will continue to give them all the information I can to support their process and will advocate for transparency and the library standards which are in all of our best interests. I am not in a position to make these policy decisions.

For this reason, I am closing this issue and invite members of the community to address followup questions or concerns to info@archive.org.
