### ISSUE TITLE
Add cover is raising TypeError for posting a str, not bytes

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4083]
Related to  #2852, #4080

Fixed in  #4102

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/add_book/__init__.py#L261 is posting str, not bytes.

### Evidence / Screenshot (if possible)
From https://sentry.archive.org/sentry/ol-web/issues/9042
![Screenshot 2020-11-12 at 16 23 16](https://user-images.githubusercontent.com/3709715/98959662-cb3f8780-2503-11eb-985d-b18a2f2875b5.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
The same error is thrown here: https://openlibrary.org/search?q=9781948434065&debug=true

**Comment by cdrini** [comment]
The fix to this should be near-identical to https://github.com/internetarchive/openlibrary/issues/4058
