### ISSUE TITLE
Find a place for `ia configure` keys in docker-based ol-web1/2

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4094]
These keys are used as part of the sponsorship flow. They currently require running `ia configure` manually, and currently living in the ephemeral docker container. Let's add these to olsystem.

This is P1 since it will require a good deal of manual steps next time we do a deploy.

**Comment by mekarpeles** [comment]
Closed by olsystem https://github.com/internetarchive/olsystem/pull/99. Moved to ia.ini

Still need to figure out the mounting from olsystem to /openlibrary/.config/ia.ini

**Comment by mekarpeles** [comment]
Perhaps `/olsystem/etc/ia.ini:/openlibrary/.configs/ia.ini`

**Comment by cclauss** [comment]
Do we need access to these for both prod and staging?
