### ISSUE TITLE
Cannot read memcached from /admin/inspect/memcache

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4096]
```
<class 'TypeError'> at /admin/inspect/memcache
a bytes-like object is required, not 'str'
```

### Relevant url?
- e.g. https://openlibrary.org/admin/inspect/memcache?keys=home.homepage.en-&action=read&debug=true

### Steps to Reproduce
1. Log in to openlibrary prod or local as admin
2. Go to the home page (so that it gets added to cache)
3. Go to /admin/inspect/memcache?keys=home.homepage.en-&action=read&debug=true

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss

**Comment by cdrini** [comment]
Note: Turns out this is a separate issue from: #4085

**Comment by cclauss** [comment]
Clicking on that URL does not generate that TypeError.  How can we make this exception more discoverable?

**Comment by cdrini** [comment]
Clicking on this URL generates a type error for me:

![image](https://user-images.githubusercontent.com/6251786/99275866-01c61c80-27fa-11eb-9919-2e915d97a981.png)

It should generate the same error on local dev environment.

**Comment by cdrini** [comment]
Added reproduction steps

**Comment by cdrini** [comment]
Dropping in priority since only affects admins
