### ISSUE TITLE
Duplicate and dangerously placed DELETE button on author edit form

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4101]
A duplicate DELETE button is on the author edit form. Additionally it is placed in a dangerous location just below the SAVE button and highlighted in orange. 

### Evidence / Screenshot (if possible)
<img width="338" alt="Screenshot 2020-11-16 at 16 13 28" src="https://user-images.githubusercontent.com/17739465/99282408-ee37a780-2833-11eb-8190-130f9b8ba628.png">

### Relevant url?
https://openlibrary.org/authors/OL...A/[author]/edit

### Steps to Reproduce

1. Go to any author profile
2. Click edit button.
3. Scroll to bottom where SAVE is and see also the two DELETE buttons.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by LeadSongDog** [comment]
Seemingly the upper Delete button is nonfunctional, at least on mobile.
