### ISSUE TITLE
ImportBot/Clean Up Bot sometimes edit usergroup/people pages

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4107]
It seems like ImportBot/Clean Up Bot sometimes match on a non-book page.

### Relevant url?

- https://openlibrary.org/usergroup/librarians?m=history
- https://openlibrary.org/people/horncBot?m=history
- https://openlibrary.org/books/OL26870818M/Wraith?_compare=Compare&b=5&a=4&m=diff
- https://openlibrary.org/type/edition?m=history

### Stakeholders
@hornc @mekarpeles

**Comment by cdrini** [comment]
From @hornc :

> I can seen in my import logs at least one of the cases where the usergroup was modified:
> `marc_loc_2016/BooksAll.2016.part40.utf8:26558120:880: 200 -- {'next_record_length': 2467, 'success': True, 'edition': {'status': 'modified', 'key': '/books/OL25332923M'}, 'work': {'status': 'modified', 'key': '/usergroup/librarians'}, 'next_record_offset': 26559000}`
>
> It found the right edition, and that edition has a proper work. The matching, modification, and response is provided by OL, so for some reason it decided to pick the usergroup :shrug:

...

> this one is weirder, I wondered why I could only find 1 instance of usergroup in the log, the other record import matched an (AFICT unrelated) edition as the work
> `marc_loc_2016/BooksAll.2016.part14.utf8:44969185:748: 200 -- {'edition': {'key': '/books/OL3507307M', 'status': 'modified'}, 'success': True, 'next_record_offset': 44969933, 'next_record_length': 956, 'work': {'key': '/books/OL26870818M', 'status': 'modified'}}`
> ... and gave it the librarians' description https://openlibrary.org/books/OL26870818M/Wraith?_compare=Compare&b=5&a=4&m=diff

...

> My gut feel is that queries are sporadically returning completely different objects in these cases, of the wrong type. I can't explain how that might be happening though... I don't think it's a code problem (At least I can't see how it is -- the mismatching result do not seem reproducible at all)

**Comment by hornc** [comment]
TODO: when Solr catches up, reimport these MARC records (removed from the librarians usergroup)
- [ ] marc:marc_loc_2016/BooksAll.2016.part40.utf8:26540428:1227
- [ ] marc:marc_loc_2016/BooksAll.2016.part14.utf8:44969185:748


https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part40.utf8:26540428:1227
https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part14.utf8:44969185:748

**Comment by cdrini** [comment]
Looks like it's also editing /type pages? https://openlibrary.org/type/edition?m=history (added to list)

**Comment by hornc** [comment]
the bad data that was causing these mis-matches has been removed, and solr has caught up. Closing as resolved.
