### ISSUE TITLE
Search: Boost Verified Results (e.g. Harry Potter)

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4111]
When I search "Harry Potter" according to me the first page should provide Harry Potter books. But instead, It shows other results that are not that relevant.
### Evidence / Screenshot (if possible)
![everything](https://user-images.githubusercontent.com/64412143/99363077-4e812480-28da-11eb-8374-088548b118ba.JPG)

![search](https://user-images.githubusercontent.com/64412143/99363210-7a040f00-28da-11eb-880a-7f51670f8162.JPG)

When one selects the ebooks filter:
![ebooks](https://user-images.githubusercontent.com/64412143/99363127-6062c780-28da-11eb-9c6d-678afab492c1.JPG)

* Expected: It should show relevant results first.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome 
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by Kartik1397** [comment]
Can I work on this issue?

**Comment by mekarpeles** [comment]
It's unclear what needs to be done to close this issue as a proposal has not been put forth by @cdrini so I am considering this a P3 (i.e. not on this milestone / month)

**Comment by cdrini** [comment]
This can be closed; with solr8, we tweaked some of the weights here and now solr8 shows up at the top! The search now better prefers books with high priority. See https://docs.google.com/spreadsheets/d/1BN5I7-OkTPaoTr2Es6jQ4O9ICWFmH0q9CP6kEgolCgg/edit#gid=0.
