### ISSUE TITLE
Lists widget erroring and not rendering on non-author pages

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4121]
Seems possible related to https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-11-17

`/opt/openlibrary/deploys/openlibrary/bc485c1/openlibrary/templates/lists/widget.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'key' (falling back to default template)`

Sentry: 
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/99467179-dc293800-290b-11eb-9cd5-2b75ce3fe19c.png)

### Relevant url?
e.g. https://openlibrary.org/authors/OL550077A/Robert_E._Staub

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by cclauss** [comment]
Can not replicate this on my Mac.
![Screen Shot 2020-11-18 at 11 58 10](https://user-images.githubusercontent.com/3709715/99522250-b0eb2b00-2995-11eb-97e8-4d77ce4dae2e.png)

**Comment by SouthGoingZax** [comment]
I also cannot replicate it.
