### ISSUE TITLE
Python 3: Coverstore does not have proper file access to write images

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4160]
### Evidence / Screenshot (if possible)
https://sentry.archive.org/sentry/ol-covers/issues/11167

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
resolved
