### ISSUE TITLE
High registrations resulting in verification email backlog

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4163]
Get report from @abezella that verification emails are backlogged as a result of high registration numbers from openlibrary. We think this is related to spam. We're hoping #4075 will help, but will need a bit of time for it to have an impact (it was deployed 2020-11-17), since the spam is specifically for increasing SEO of various misc websites.

### Stakeholders
@abezella @SouthGoingZax @mekarpeles

**Comment by mekarpeles** [comment]
This seems to be resolved by IP banning
