### ISSUE TITLE
Possible delete openlibrary/macros/RecentPageList.html

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4167]
This file looks unused.

- [ ] Confirm no occurrences of `RecentPageList` in the repo
- [ ] Delete the file
- [ ] Delete any CSS/JS related to this file

## Stakeholders
@ArunTeltia

**Comment by Yashs911** [comment]
@cdrini I would like to work on this. How can I no occurrences of `RecentPageList` in the repo?

**Comment by Yashs911** [comment]
I guess we can delete this file
![recent](https://user-images.githubusercontent.com/64412143/100313173-06e55180-2fda-11eb-848b-9533b68619ef.JPG)

![re](https://user-images.githubusercontent.com/64412143/100313137-f8973580-2fd9-11eb-90ed-56b44c06b3df.JPG)
