### ISSUE TITLE
Delete openlibrary/templates/admin/inspect/{thing,tasks}.html

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4169]
These are dead code and no longer used. They were introduced in https://github.com/internetarchive/openlibrary/commit/1996f2733b0d0ea21ddba37b0ea2438e63ae9b21 , but their python code was removed at some point, but these templates were left behind.

- [x] Confirm they're not used anywhere
- [ ] Remove the two files in question

### Stakeholders
@ArunTeltia

**Comment by Yashs911** [comment]
@cdrini @ArunTeltia I would like to work on this issue.
