### ISSUE TITLE
Can we eliminate `page.v2`?  Aren't all pages v2 now?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4174]
### Question

Can we eliminate [`page.v2`](https://github.com/internetarchive/openlibrary/search?q=%22page.v2%22)?  [_Aren't all pages v2 now?_](https://github.com/internetarchive/openlibrary/pull/4142#pullrequestreview-536112290)

If so, it would be helpful to remove this complexity distributed throughout our code.

**Comment by jdlrobson** [comment]
Yes we can.
