### ISSUE TITLE
Clicking on hamburger icon on mobile unintuitively doesn't close menu when its open

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4200]
1. Open https://openlibrary.org/
2. Open Developer console and toggle to Mobile View.
3. Click on the "3-lines button" to open the menu.
4. Click it again to close it.

* Actual: Step 4 doesn't do anything.
* Expected: Step 4 should close the menu.
Comments: Clicking outside the box closes the menu.
### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by Kartik1397** [comment]
This bug is not only with hamburger but with all dopdown-menu which uses hover event.

**Comment by shrey27tri01** [comment]
I am working on this issue. Will raise a PR soon :)

**Comment by jdlrobson** [comment]
At first, I thought this was serious, but now looking into it, the hamburger button works fine for me on my mobile device so this is probably not an issue for real mobile devices.

Note:  In developer console,whether you enable or disable this icon will give you different results:
<img width="75" alt="Screen Shot 2021-01-07 at 5 54 48 PM" src="https://user-images.githubusercontent.com/148752/103964934-71c59480-5111-11eb-832a-887a72e8b664.png">

Is this actually a real problem in the real world? Should probably be fixed but also probably not a high priority like I first thought.

**Comment by Yashs911** [comment]
> Is this actually a real problem in the real world? Should probably be fixed but also probably not a high priority like I first thought.

@jdlrobson Yes, I tried to use the hamburger button on my mobile to close it but it doesn't work.

**Comment by shrey27tri01** [comment]
@jdlrobson That's strange, because the hamburger doesn't work on my mobile device, I tried it on both Chrome as well as Firefox. 
Maybe it works on only some devices?

**Comment by jdlrobson** [comment]
Maybe. Does seem a bit of a delay
![Screenshot_20210107-194325_Chrome](https://user-images.githubusercontent.com/148752/103971946-b7d62480-5120-11eb-90cf-513ce2af09ad.jpg)

**Comment by jdlrobson** [comment]
Ok I think I see what's happening here. Clicking the button will retain the focus. 

We should use the checkbox hack for this menu and all the other menus. It will be better than a javascript hack to fix this.
https://css-tricks.com/the-checkbox-hack/

**Comment by shrey27tri01** [comment]
@jdlrobson Really sorry for the late response! Could you please help me regarding which file do I start with? I tried having a look and started with the HTML template files at [`/openlibrary/templates`](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates), but couldn't figure out which static files are being used in which template, and which files do I actually have to change. Could you please help me out here?
Sorry for the novice question! :sweat_smile:

**Comment by Yashs911** [comment]
@shrey27tri01
HTML file [nav_head.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_head.html)
CSS file [header-bar.less](https://github.com/internetarchive/openlibrary/blob/master/static/css/components/header-bar.less)

**Comment by shrey27tri01** [comment]
Hey @jdlrobson, I tried using the checkbox hack, but that doesn't seem to be able to solve the problem at the moment (I think using javascript to achieve this would a viable solution). I have described the problems I am facing in more detail in the pull request I have created over [here](https://github.com/internetarchive/openlibrary/pull/4405). 

Do check it out and suggest what next to do.
