### ISSUE TITLE
Roman numbers are not valid for number_of_pages

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4204]
### Question

Can we parse this data into valid `number_of_pages` (int) for the following books?

The data for `number_of_pages` for the first book is coming through as `XXII, 516`.  Python does not like that...
[ValueError infogami.infobase.common in parse_data](https://sentry.archive.org/sentry/ol-infobase/issues/11358)
errorinvalid literal for int() with base 10: ''
```
python3 -c "int('XXII, 516')"
[ ... ]
ValueError: invalid literal for int() with base 10: 'XXII, 516'
```
Does this book have 516 pages?  Is the same true for the other three books below?  Should we add a bit of code to get rid of the roman numerals and set the `number_of_pages` to 516?  Or perhaps the book has 22 pages (XXII)!!  Should we have a bot that seeks out this kinda data and cleans it up?

For extra credit...  Sometimes `number_of_pages` is the empty string.  Should this code just return `number_of_pages=0`?

### Stakeholders

![Screen Shot 2020-12-01 at 21 11 41](https://user-images.githubusercontent.com/3709715/100797784-f6423a80-3422-11eb-8e79-3bef8c7a1b45.png)
![Screen Shot 2020-12-01 at 21 12 48](https://user-images.githubusercontent.com/3709715/100797786-f7736780-3422-11eb-8205-dbc5ccf56ae2.png)
![Screen Shot 2020-12-01 at 21 14 06](https://user-images.githubusercontent.com/3709715/100797788-f80bfe00-3422-11eb-951b-0401885607ef.png)
![Screen Shot 2020-12-01 at 21 13 25](https://user-images.githubusercontent.com/3709715/100797790-f8a49480-3422-11eb-9e49-e25c5dcd8b71.png)

**Comment by hornc** [comment]
@cclauss `number_of_pages` should be a number / integer: https://github.com/internetarchive/openlibrary-client/blob/master/olclient/schemata/edition.schema.json#L91

Those strings with roman numerals look like they would be valid in the `pagination` field, which is a string https://www.w3.org/2001/sw/wiki/Library_terminology_informally_explained#pagination

**Comment by cclauss** [comment]
Thanks for the pointers Charles.  We think that we know which bot is creating these records so we will try to implement a fix.

**Comment by seabelis** [comment]
@cclauss There are two fields on the form, one is for page count ('How many pages?') and that is strictly integers. The other is that pagination and this field is unrestricted to allow for roman numerals, volume count, maps, etc.

**Comment by LeadSongDog** [comment]
@seabelis To be fair, we've never been entirely consistent about this (please pay no attention to the small minds' bugaboos). Should a pagination of "xxii, 550" be accompanied by an integer page count of 550, or more correctly 572?

**Comment by seabelis** [comment]
@LeadSongDog Probably, yes. But in all honesty I pay more attention to the string field as I find it more helpful. I don't always complete the integer field.

**Comment by tfmorris** [comment]
The pagination field makes no sense to a computer, so you'll never be able to sort by length, etc without the `number_of_pages` field. I would expect "XXII, 516" to result in a number of pages value of either 538 or perhaps a slightly higher number equivalent to 2 x # of leaves.

As an integer field, it should never be equal to "". I would expect that an unknown value would be encoded by the field not being present (or perhaps have a value of `None`).

Note that anything that has been scanned has an  exact page count that can be picked up in from the scanning data, so no need for human entry.

**Comment by cclauss** [comment]
@guyjeangilles Can you please try to discover which of our import bots is bringing in roman numbers into an integer field.

**Comment by hornc** [comment]
The problem looks like it could be coming from this code, if this script is active for ImportBot: https://github.com/internetarchive/openlibrary-bots/blob/master/BWBImportBot/import-ol.py#L42

**Comment by hornc** [comment]
@mekarpeles I see there has been a change to the bots repo code from what I wrote originally in the `parse-biblio.py` script:

![image](https://user-images.githubusercontent.com/905545/106533406-fcee4a80-6556-11eb-8530-ed69681ab578.png)

`pagination` is the correct OL desitination field to use when copying that data. The committed version in openlibrary-bots looks like a WIP straddling python 2 and 3, so I'm not sure if that code is running anywhere, but if the same source has been copied and is running elsewhere, it is populating the wrong field. 

https://github.com/internetarchive/openlibrary-bots/blob/master/BWBImportBot/import-ol.py#L41-L42 also looks like a work around attempt to use `pagination` for `number_of_pages`, which is also incorrect.

Source data description of that field confirming roman numerals are allowed: "Total Number of pages in format: Roman page
count (if present), Arabic page count (i.e., xxiii, 531)"  

The original script is Python3 and committed (non-public) on my Archive gitlab. The first commit in openlibrary-bots includes modifications I didn't make.

**Comment by cclauss** [comment]
@hornc Given your understanding of this code, can you please create a pull request that fixes this issue?
