### ISSUE TITLE
Travis no longer running

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4207]
Travis switched their pricing plan on Nov. 2, and we ran out of their trial 10k credits on Nov. 24th :( ~Everyone needs to be _VERY CAREFUL_ when merging PRs, since the Travis checks are no longer running.~

IA paid for a month of Travis so we're good for now, and in talks to determine if we qualify for their OSS credits, as well as looking into GitHub Actions as an alternative.

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

## Stakeholders

@mekarpeles @cclauss

**Comment by cdrini** [comment]
I sent them a support email asking for OSS credits just now; looking online, it seems like it takes ~1w for them to respond?

**Comment by cdrini** [comment]
They responded yesterday (Dec 7):

> Thanks for contacting Travis-CI Support! We would love to help.
>
> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
>
> - You are a project lead or regular committer (latest commit in the last month)
> - Project must be at least 3 months old and is in active development (with regular commits and activity)
> - Project meets the OSD specification
> **- Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)**
> - Project can not provide commercial services or distribute paid versions of the software
>
> Does this sound like you and your project? We'd be very happy to support you!
>
> However, if your project does not match these requirements or you have further questions [1], please feel free to ask!
>
> We look forward to your response if you meet these requirements to proceed with the next steps.

Emphasis mine. My guess is since we do have paid staff, albeit from a non-profit organization (Internet Archive), we don't apply for this. @bfalling got internetarchive a month of Travis to use for some breathing room.

Although the wording is ambiguous... (is it: "(commercial company) or (organization)", or is it "commercial * (company or organization)" ?).

**Comment by cclauss** [comment]
Given that this is a Priority 1, could we please have clarity on what is required to close this issue?

If we have an alternative CI like GitHub Actions (#4188) doing everything that Travis CI did, will that close this issue?

**Comment by cdrini** [comment]
Dropping to p2 since travis is running now since IA got a month.

**Comment by cclauss** [comment]
:greenlight: 4207 - git submodules? @cclauss -- let's try adding make git fpr js + py actions

That worked like a champ!  GitHub Action for JavaScript landed and Python (#4188) is in review.
