### ISSUE TITLE
Unable to import csv generated by Goodreads

### ISSUE THREAD

**Issue by ofefo** [internetarchive/openlibrary#4216]
When trying to import my library with the generated .csv file from Goodreads, I receive an internal error.

```
Hmm...

Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2020-12-04/191144042614 and will look into it as soon as possible. Head for home?
```

https://openlibrary.org/account/import/goodreads

- **Logged in (Y/N)?** yes
- **Browser type/version?** Mozilla Firefox 83.0
- **Operating system?** GNU/Linux
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
@tabshaikh one for you to investigate when you have time :)

**Comment by captain-panda** [comment]
@tabshaikh I'd like to help with this.

**Comment by cdrini** [comment]
Note: The timeframe suggests this might be a python 3 issue, so we should also check that.

**Comment by SouthGoingZax** [comment]
It does look like a regression from the migration to Py3.  If you use the Chrome developer tools and add "?debug=true" to the form submit action, you get:

![image](https://user-images.githubusercontent.com/72705998/102017157-06f38a00-3d1a-11eb-93ab-71355df9ad9c.png)

**Comment by cdrini** [comment]
Bumping to P0; this is apparently affecting all imports.
