### ISSUE TITLE
Works don't combine in search

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4217]
after combining multiple works together, they still appear together in the search results:
![image](https://user-images.githubusercontent.com/55302685/101217707-ab007580-3636-11eb-852d-64cb87809a3e.png)

**Comment by mekarpeles** [comment]
I think this may be a solr latency issue that @cdrini is aware of -- after 15 or so minutes, the works **should** appear merged on Production.

Dev uses a different version of memcache which doesn't get updated in the same way through infobase (known issue which should be resolved once the Librarian Bar goes live on production early this upcoming year).
