### ISSUE TITLE
'Find a physical copy near you' should prioritize OCLC when available

### ISSUE THREAD

**Issue by skylerbunny** [internetarchive/openlibrary#422]
Real world case:

https://openlibrary.org/books/OL26228110M

This is a hardcover edition of a book, one of six editions. It has an ISBN-10 of 1449483488. The link 'Find a physical copy near you' creates a URL based on the ISBN-10, which is http://worldcat.org/isbn/1449483488 . The problem is - if you browse to this, this ISBN on WorldCat  is a compilation entry for the entire series (which happens to include that ISBN in a list of about 10).

While one can argue that this is a problem with Worldcat (that it should return most specific ISBN results when available), OL can solve it for themselves simply like this:

If an OCLC number is explicitly provided for a given book edition, the 'Find a physical copy near you' link should use (in this example) http://www.worldcat.org/oclc/952649184 , NOT http://worldcat.org/isbn/1449483488. In other words, we should assume that when a contributor puts in an OCLC number, they know what they're doing and that specific OCLC is there for a reason.

**Comment by LeadSongDog** [comment]
Just commented at #324 
This should be using https as described there.

**Comment by skylerbunny** [comment]
Addressed @LeadSongDog's https change (where possible) in the files.

**Comment by guyjeangilles** [comment]
@skylerbunny @mekarpeles The WorldCat link for the edition in the issue properly redirects to this OCLC url: https://www.worldcat.org/title/phoebe-and-her-unicorn/oclc/952649184. I'm proposing we close this issue. Let me know your thoughts.

**Comment by cdrini** [comment]
Yep; looks like it's fixed
