### ISSUE TITLE
Open Library Amazon API usage exceeding limit

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4220]
Dup of #3967

Received email from Amazon API:

> Hello,
> 
> Your Associates account is at risk of closure.
> 
> Why?
> You are trying to submit requests that exceed your account’s usage limit. You must not exceed, or if you build and release an application that calls PA API, each copy of that application that is installed by an end user will not exceed, any limit on calls per second set forth in any Specifications.
> 
> What’s next?
> Within five business days please correct the violations and notify us when you are in compliance through our customer service contact page: https://affiliate-program.amazon.com/home/contact. Please choose the subject 'Warning/Information Request Response' from the dropdown menu, and be sure to reference Issue Code 83441-US in the comments field.
> 
> If not done within five business days, we will close your account.

## Stakeholders
@mekarpeles @bfalling

**Comment by mekarpeles** [comment]
I temporarily disabled Amazon calls on ol-web[1,2] & ol-dev1 to reduce traffic. It's still running on ol-dev0.

I also emailed Amazon w/ the info above and will await their reply.

Next steps: (can now wait until this week)
* I think we should consider making prices lazy load (like Related Books Carousels) cc: @tabshaikh, @jamesachamp 
* We might consider moving amazon fetch code into a single service/API running on ol-www1 and setting an nginx rule to reverse proxy to that service (or make it an internal service -- may be a better idea) @mekarpeles 
* Presumably we can batch 10 ASIN/ISBN requests to Amazon. Not sure the best way to queue those. Maybe some global list which gets flushed every 1 seconds @mekarpeles, @cclauss
