### ISSUE TITLE
Search for title:©♭ broken - returns all 23.4M works

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#4223]
This search https://openlibrary.org/search?mode=everything&q=title%3A+%22%C2%A9%E2%99%AD%22
returns 23 426 379 results, which is clearly too many.

### Relevant url?

see above

### Steps to Reproduce

1. Go to ... the url above or
2. Do ... the typing of the characters in the search box

* Actual: all works are returned
* Expected: only results with the given letters in their title are returned

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod openlibrary.org

**Comment by LeadSongDog** [comment]
title, author, or subject searches for that string all do the same thing

**Comment by cdrini** [comment]
It seems like solr is doing processing on the title field that strips out some of those characters. This query with `title_suggest` returns the correct results: https://openlibrary.org/search?q=title_suggest%3A+%22%C2%A9%E2%99%AD%22&mode=everything

It seems like it's stripped out by solr's WordDelimeterGraphFilter? Seems unlikely to cause user's issues, and it's possible to find the works of interest with the `title_suggest`, so closing.

![image](https://user-images.githubusercontent.com/6251786/152877261-76f4f8df-03a7-49c6-af97-8659d663667e.png)
