### ISSUE TITLE
(PYL-W0102) Dangerous default argument

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4227]
## Description
Mutable Default Arguments: https://docs.python-guide.org/writing/gotchas/

Do not use a mutable like `list` or `dictionary` as a default value to an argument. Python’s default arguments are evaluated once when the function is defined. Using a mutable default argument and mutating it will mutate that object for all future calls to the function as well.

## Occurrences
There are 23 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/HarshCasper/openlibrary-1/issue/PYL-W0102/occurrences/](https://deepsource.io/gh/HarshCasper/openlibrary-1/issue/PYL-W0102/occurrences/)

**Comment by Yashs911** [comment]
@cclauss I would like to work on this issue.

**Comment by Yashs911** [comment]
If I am not wrong I need to do the changes as shown below 
**Incorrect:**
`def request(self, path, method='GET', query={}):`
**Correct:**
```
def request(self, path, method='GET', query=None):
    if query is None:
        query = []
```

**Comment by cclauss** [comment]
`query = query or {}`

**Comment by Yashs911** [comment]
> `query = query or {}` # i.e.: if it is any _falsey_ value like `None`, `False`, `0`, `0.0`, `[]`, `set()`, then we want to set it to `{}`.

@cclauss Is this correct?

```
def request(self, path, method='GET', query = query or {}):
    if query:
        query = {}
```

**Comment by cclauss** [comment]
Please fix the easy ones and leave the complex ones for future pull requests.

**Comment by captain-panda** [comment]
@cclauss I'd like to have a go at it.

**Comment by cclauss** [comment]
My sense is that #4228 fix almost all of these issues with the exception of one file.

**Comment by captain-panda** [comment]
Oh... okay then

**Comment by cclauss** [comment]
openlibrary/plugins/upstream/adapter.py lines 108 and 124 would close this issue.

**Comment by captain-panda** [comment]
> openlibrary/plugins/upstream/adapter.py lines 108 and 124 would close this issue.

On it

**Comment by cclauss** [comment]
@Yashs911 or @captain-panda Could one of you create a PR on the remaining file?

**Comment by Yashs911** [comment]
> @Yashs911 or @captain-panda Could one of you please create a PR on the remaining file?

@cclauss I would like to, but I don't know what all changes do I need to make
