### ISSUE TITLE
Recomission dev.openlibrary.org like staging.openlibrary.org

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4229]
`dev` and `prod` should be on the same version of Python on Ubuntu 20.04.1 LTS (Focal Fossa)

Should https://dev.openlibrary.org point to ol-dev1 or should we upgrade ol-dev0 to run Python 3?

### Relevant url?

https://dev.openlibrary.org/status says Python 2.7.6 on Ubuntu 14.04.5 LTS (Trusty Tahr)
http://staging.openlibrary.org/status says Python 3.8.6 on 6.04.7 LTS (Xenial Xerus)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: Legacy Python
* Expected: Python

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
Given that it is easier to do edit-on-the-fly debugging without Docker, should two dev servers be configured as:
1. Open Library running on Python 3 on bare metal
2. Open Library running on Python 3 in Docker containers

**Comment by cdrini** [comment]
Final action was to remove the old dev server, and switch to staging.
