### ISSUE TITLE
Update eslint-plugin-vue and disable the new "vue/no-mutating-props" rule

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4231]
@dependabot tried to update "eslint-plugin-vue" to 7.2.0, but a new rule is incompatible with how a large chunk of our code is written. Let's update and disabled the rule.

### Summary of Requirements

- [ ] Update eslint-plugin-vue to 7.2.0 (See https://github.com/internetarchive/openlibrary/pull/4230)
- [ ] Disable "vue/no-mutating-props" rule

### Context

See https://github.com/vuejs/eslint-plugin-vue/issues/1371 for details on why we're disabling the rule as opposed to changing our code.

**Comment by Sabreen-Parveen** [comment]
@cdrini I would like to work on this issue.

**Comment by cdrini** [comment]
Go for it, @Sabreen-Parveen !
