### ISSUE TITLE
npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4243]
When I do Docker builds, I see the following warning:
> npm WARN ajv-keywords@3.4.0 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

Is this something to worry about?  Is it worth fixing?

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
@cclauss this is an npm issue [npm/npm#19877](https://github.com/npm/npm/issues/19877#issue-298965480)

> I also hope that the issue with missing peer dependency that a lot of people report to ajv (ajv-validator/ajv#708, ajv-validator/ajv-keywords#56) could go away after this upgrade. Even though it still looks like npm problem to me (or some other tool problem), I don't know what else apart from eslint still uses ajv 5.x to cause this version conflict...

> > 
> > It's an npm 3+ problem at the end of the day, but npm folks have said that they basically would have to rewrite their dependency tree builder to solve this (i.e., they're aware it's a bug but the effort to fix is massive). I'd have to dig up the issue again, though.
> 
https://github.com/eslint/eslint/pull/9856#issuecomment-377694098

**Comment by cclauss** [comment]
That repo is archived (cannot be updated) in favor of https://github.com/npm/cli.

**Comment by jamesachamp** [comment]
I think that we can overlook this for the time being.  Running `npm list ajv` shows that this warning is related to Webpack's dependencies:
```
├─┬ @vue/cli@4.2.3
│ └─┬ @vue/cli-shared-utils@4.5.3
│   └─┬ request@2.88.2
│     └─┬ har-validator@5.1.5
│       └── ajv@6.12.3 
├─┬ @vue/cli-plugin-babel@4.5.0
│ └─┬ cache-loader@4.1.0
│   └─┬ schema-utils@2.7.1
│     └── ajv@6.12.5 
```
... Several dependencies omitted for brevity ...
```
└─┬ webpack@4.44.2
  ├── ajv@6.12.5 
  └─┬ schema-utils@1.0.0
    └── UNMET PEER DEPENDENCY ajv@6.5.4 
```
`schema-utils` is used by webpack to validate options in plugins and loaders, and has nothing to do with Open Library functionality.  Since our builds are working properly and we rarely update our webpack configs, we can probably disregard this.

@cdrini does this reasoning seem sound to you?
