### ISSUE TITLE
Switch infogami submodule to infogami master

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4249]
Most of our production servers are now on Python 3 + infogami master. Can we switch the repo's submodule to infogami master? 

~Potentially blocked by #4060~ ; the services on ol-home which are not yet py3 + infogami master (e.g. ol-home solrupdater, ol-home cron jobs)

## Stakeholders

@cclauss  @mekarpeles

**Comment by cclauss** [comment]
ol-home is the KEY.

**Comment by cdrini** [comment]
Confirm:

- [ ] Remove ol-home from fabfile -- specifically from rsync (i.e. freeze code on ol-home)
- [ ] Confirm that python scripts on ol-home run from the deploys directory, not from the "build" (/1/...) directory
- [ ] Literally update git update submodule to point master SHA

**Comment by cclauss** [comment]
Another approach would be to add a step to fabfile which checkout a specific infogami commit on ol-home after the rsync in a deploy.

Should ol-home restart its services as a step in each deploy.
