### ISSUE TITLE
Cannot update css-loader from 3.6.0 to 5.0.1

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4253]
Dependabot tried to updated this in #4196, but it failed with a bunch of errors it didn't used to have; See them here: https://travis-ci.com/github/internetarchive/openlibrary/jobs/457654449#L287

### Related files
https://travis-ci.com/github/internetarchive/openlibrary/jobs/457654449#L287

### Stakeholders
@Sabreen-Parveen @jamesachamp

**Comment by cigar-galaxy82** [comment]
@cdrini I would like to work on this issue

**Comment by Yashs911** [comment]
@jdlrobson current version `"css-loader": "5.2.4",`. So I guess we can close this issue.
