### ISSUE TITLE
Remove music from the intro video

### ISSUE THREAD

**Issue by mhucka** [internetarchive/openlibrary#4254]
The intro video at https://archive.org/embed/openlibrary-tour-2020/openlibrary.ogv has piano music playing over the sound of the narrator's voice, and it's insanely distracting and annoying.

### Describe the problem that you'd like solved

Only have the speaker's voice, without music playing at the same time.

**Comment by mekarpeles** [comment]
@mhucka sincere apologies for the poor choice of background music. Feedback noted and will be considered for future videos (mea culpa). In this specific case, that video was done on my own hours and I don't have easy access to simply disable an audio layer without recording the entire video again (which I don't plan to do, but welcome the community to do -- and will happily replace my video with theirs, should they wish to contribute a better resource).

As a result, and with no disrespect intended (I think the complaint is valid) I am going to close this issue as "feedback duly noted" and (my apologies) "not planning to fix".

If there's some other resolution you imagine we could entertain, I'm open to further discussion! And thank you for giving us this feedback as it will impact my future decisions re: making our videos accessible and useful.
