### ISSUE TITLE
/developers doesn't contain clickable links

### ISSUE THREAD

**Issue by bbkane** [internetarchive/openlibrary#4261]
https://openlibrary.org/developers has good information, but the link format is broken

### Evidence / Screenshot (if possible)
<img width="957" alt="image" src="https://user-images.githubusercontent.com/6081085/102020820-6eb4cf80-3d30-11eb-9014-6c8defada4b6.png">

### Relevant url?

https://openlibrary.org/developers

### Steps to Reproduce

1. https://openlibrary.org/developers
2. Try to click a link

* Actual: nothing
* Expected: I expected the link to open

### Details

I tried to edit the page, but I don't have permission

<img width="330" alt="image" src="https://user-images.githubusercontent.com/6081085/102020870-e2ef7300-3d30-11eb-8f79-b2e1c79ebd89.png">

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Firefox
- **Operating system?** MacOS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Have someone with permissions edit this page.

**Comment by cdrini** [comment]
Fixed :+1:
