### ISSUE TITLE
A GET to /account/import/goodreads should redirect to /account/import

### ISSUE THREAD

**Issue by SouthGoingZax** [internetarchive/openlibrary#4264]
https://news.ycombinator.com/item?id=25409173 points out that a GET to https://openlibrary.org/account/import/goodreads returns "method not allowed"

### Describe the problem that you'd like solved

It would be a better user experience to redirect such requests to /account/import

### Stakeholders

@mekarpeles @cdrini

**Comment by dherbst** [comment]
Please consider https://github.com/internetarchive/openlibrary/pull/4270 as a fix for this issue.
