### ISSUE TITLE
Add ability for a user to filter lists by date added

### ISSUE THREAD

**Issue by arawden** [internetarchive/openlibrary#4267]
While I'm tracking the list of books that I want to read in the future, I'd like to be able to sort my "Want to Read" list by date added. This way, I'm able to determine which books have been in my backlog the longest, so I can finally get around to reading them.

### Describe the problem that you'd like solved

When viewing my "want to read" list, I should be able to sort the list by date in ascending or descending order, so I can view my most recently added books or the books I added years ago and haven't gotten around to reading.

### Proposal & Constraints

When viewing the `/people/<user>/books/want-to-read` list, add a UI control for sorting the list by date added. It's likely that this could be the start of a broader feature request for the ability to filter the list by book title, author, etc, as right now the only controls are pagination. 

### Additional context

I've attached a screenshot of this feature's implementation in Goodreads
![image](https://user-images.githubusercontent.com/1264044/102033280-e0603e00-3d6f-11eb-8a87-c7ee2a541e62.png)

**Comment by Sabreen-Parveen** [comment]
@arawden I would like to work on this issue.

**Comment by Evazisouli** [comment]
Hello! I'm a new contributor, should I try to contribute in this issue?

**Comment by Evazisouli** [comment]
@jamesachamp could you give me some guidelines please?

**Comment by mekarpeles** [comment]
Howdy @Evazisouli, this could be a good one! 

# Working with Reading Log

A mini-tutorial.

## Overview

The html template for the reading log code is here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/books.html

This is what the rendered page looks like:
https://openlibrary.org/people/mekBot/books/want-to-read

The template is rendered by a view method here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L733-L760

## Data Flow

A user visits https://openlibrary.org/people/mekBot/books/want-to-read. This url pattern is matched by https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L734 within the code and thus is handled by the `public_my_books` function in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L733.

The `public_my_books` in function in `plugins/upstream/account.py` calls the `Bookshelves` API model in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/bookshelves.py#L6 which asks/queries for Reading Log data from the database.

The `Bookshelves` model returns data back to `public_my_books` where it is used to render (i.e. passed from https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L755-L759 into) the html template (https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/books.html).

## An example

In #5080, you can read through a complicated example of adding a feature to the Reading Log here: https://github.com/internetarchive/openlibrary/issues/5080#issue-864008133

**Comment by Evazisouli** [comment]
Thanks @mekarpeles! I would really like to work it!
