### ISSUE TITLE
Increase max-width of the containers

### ISSUE THREAD

**Issue by awebdeveloper** [internetarchive/openlibrary#4269]
This lies some where in between a bug/feature request. The max width(in css) on the desktop for header(header-bar) and body (test-body-mobile) is 960. These days most folks have screen sizes bigger than this. can we bump it to 1280. Thus giving things a much needed breading room.

**Comment by jamesachamp** [comment]
I think that a larger main container size will help with some of the carousel button overflow issues that we've been seeing.  Whoever works on this should ensure that there are still reasonably sized left and right margins on smaller screens.

**Comment by awebdeveloper** [comment]
@jamesachamp  I can raise a PR to change the width

**Comment by jamesachamp** [comment]
@awebdeveloper Go for it!

**Comment by Yashs911** [comment]
@jamesachamp, as we have removed `Check Availability` and `1 hour Borrow` buttons. Should we still increase, the main container width? or We can close this issue.

**Comment by jamesachamp** [comment]
@Yashs911 This should probably be a group decision.  I've added the "Needs: Community Discussion" label, and will bring it up during our next community meeting on Tuesday.

**Comment by awebdeveloper** [comment]
On larger monitors it looks small. From large I mean a 15' MacBook. which these days is the standard size

**Comment by jamesachamp** [comment]
We can go ahead and try a max-width of 1200px for larger screen sizes.

**Comment by dwaipayan05** [comment]
So, its basically increasing max-width test-body-mobile in v2.less and header-bar in header-bar.less to 1200px ?
Should I send a PR for this ?

**Comment by jamesachamp** [comment]
@dwaipayan05 Yes, I think that should do it.  Before opening a PR, ensure that the site still looks good on smaller screens.

**Comment by mitchell-frost** [comment]
If it is still open, can I work on it? The last update seems to be a quite some time ago

**Comment by jamesachamp** [comment]
@mitchell-frost Yes, go for it.
