### ISSUE TITLE
Unicode Error rendering edition template

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#427]
https://openlibrary.org/books/OL25155458M/

redirects to:
https://openlibrary.org/books/OL25155458M/%E6%BC%A2%E5%AD%97%E5%8F%A4%E4%BB%8A%E9%9F%B3%E8%AB%96

**Error:**
/opt/openlibrary/deploys/openlibrary/7bf33ca/openlibrary/templates/type/edition/view.html: error in processing template: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-11: ordinal not in range(128) (falling back to default template)

**Comment by mekarpeles** [comment]
Similarly https://dev.openlibrary.org/search/subjects?q=%C3%B3

**Comment by hornc** [comment]
PR to fix the subject search issue: #491  The original reported issue seems to be caused by unicode in the date field: `publish_date: "二〇一〇年十一月三十日，November 30, 2010"`

**Comment by hornc** [comment]
unfortunately I merely stopped the error, not made the search work :(
https://dev.openlibrary.org/search/inside?q=%D0%90%D0%BD%D1%82%D0%BE%D0%BD+%D0%A7%D0%B5%D1%85%D0%BE%D0%B2

returns a ridiculous number of results. I think the unicode characters are being dropped now. Needs further investigation.
