### ISSUE TITLE
Add unit tests for GoodReads import

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4271]
GoodReads imports broke without any automatic indication (#4216 ). Let's add some unit tests that test this code (code in question: https://github.com/internetarchive/openlibrary/pull/3597 )

## Summary of requirements

- [ ] The tests should have caught #4216 had they been in place.

## Stakeholders

@SouthGoingZax @tabshaikh

**Comment by cdrini** [comment]
@SouthGoingZax Would you be able to work on this one? That CSV file you used for testing would be mighty helpful :)

**Comment by SouthGoingZax** [comment]
I didn't find a existing unit test that mocks the output of web.input() to pass in test csv data.  Looking more into how this could work, https://github.com/webpy/webpy/blob/master/docs/input.rst says ```web.input()``` returns a ```web.storage``` object.  Intentionally creating an error in the ```fetch_goodreads``` function and using debug=true reveals that ```web.storage``` object has the structure: ```{'csv': FieldStorage(...)}```, with the value there being an instance of ```cgi.FieldStorage```:
![image](https://user-images.githubusercontent.com/72705998/102695740-15401b00-41de-11eb-9ca8-a05a60f31f61.png)

The bottom of [this recipe](https://webpy.org/cookbook/fileupload) says that if we don't pass in ```csv={}`` as a parameter to ```web.input()``` in ```fetch_goodreads.POST()```, we'll get a string back instead of a cgi.FieldStorage object.

So it looks like there are at least two paths for generating the value in a mock ```web.storage``` object: 1) create a mock cgi.FieldStorage object, or 2) adjust the ```web.input()``` call to get a string back and just use a string in our mock object.  The second option seems easier, so I'll go that route.
