### ISSUE TITLE
Make dev environment py3 by default

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4276]
Most of our production servers are Python 3 now; we want developers to be developing on py3 by default as well. Note we still want the option to run as Python 2, so we shouldn't remove the install entirely (yet :) )

- [x] ~Blocked by #4249~: Update git submodule to master

**Comment by cclauss** [comment]
Dropped `docker-compose.infogami-local.yml` from:
https://github.com/internetarchive/openlibrary/wiki/Production-Service-Architecture
https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide
