### ISSUE TITLE
Incorrect list count displayed when patron deletes list

### ISSUE THREAD

**Issue by jamesachamp** [internetarchive/openlibrary#4288]
Whenever a patron deletes a list from their lists, the total list count (outlined in red below) is not updated unless the page is refreshed.

### Evidence / Screenshot (if possible)
![incorrect_list_count](https://user-images.githubusercontent.com/28732543/102402472-cb272180-3fb2-11eb-987c-14f84144ae4d.png)

### Steps to Reproduce

1. Log into Open Library.
2. Ensure that you have created at least one list.
3. Click on your profile picture and select "My Lists" from the profile menu.
4. Note your total number of lists.
5. Delete a list and note the total again.

* Actual: Total list count displayed will not change.
* Expected: Total list count displayed should match the actual number of lists.

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Firefox 83.0
- **Operating system?** Ubuntu 18.04.5 LTS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

On list delete, update the text of the element that displays the total list count.

**Comment by Sabreen-Parveen** [comment]
@jamesachamp I would like to work on this issue.

**Comment by jamesachamp** [comment]
@Sabreen-Parveen go for it!  Let me know if you have any questions about anything.

**Comment by Sabreen-Parveen** [comment]
@nynaalekhya, thanks for the PR.

**Comment by jamesachamp** [comment]
@nynaalekhya In the future, please ensure that nobody is working on an issue before taking it up.

**Comment by nynaalekhya** [comment]
@jamesachamp Yeah I'll make sure.

**Comment by nynaalekhya** [comment]
@Sabreen-Parveen If you want to work on this issue, you can continue to resolve it.

**Comment by Sabreen-Parveen** [comment]
@nynaalekhya Yes, I would like to work on it. Thanks :)

**Comment by jamesachamp** [comment]
Thanks @nynaalekhya!  Let me know if you'd like some help finding some other good first issues.

**Comment by nynaalekhya** [comment]
@jamesachamp Can I take up this issue, #3523?

**Comment by jamesachamp** [comment]
@nynaalekhya Yes, I think that's probably fine.  Just say that you would like to work on it in that thread.  Since there was somebody working on it before, it's good etiquette to mention them and ask if they are still working on it.

**Comment by nynaalekhya** [comment]
Yeah, the assignee field says no one is assigned. I have asked on the thread. Thank you :)

**Comment by shrey27tri01** [comment]
@Sabreen-Parveen are you working on this issue? If not, can I take this up @jamesachamp?

**Comment by Sabreen-Parveen** [comment]
@shrey27tri01 this issue has already been resolved and I have attached a PR, you can look for some other issues :)
