### ISSUE TITLE
UI Improvements for Book Covers dialog

### ISSUE THREAD

**Issue by Kartik1397** [internetarchive/openlibrary#4306]
## Current Behavior
![2020-12-18_02-27](https://user-images.githubusercontent.com/24036721/102543110-c9577e00-40d8-11eb-967a-f2045ab178c4.png)
## Expected Behavior
![2020-12-18_02-28](https://user-images.githubusercontent.com/24036721/102543130-d7a59a00-40d8-11eb-98c4-91668ac36b18.png)

Maybe, we can also increase size of close button.

**Comment by mahi0601** [comment]
Can i work on this issue @Kartik1397

**Comment by Kartik1397** [comment]
Sure @mahi0601.

**Comment by mekarpeles** [comment]
@mahi0601 did you still want to try this issue?

**Comment by bobmatyas** [comment]
@scottbarnes I confirmed this issue still exists and would be happy to fix it if you want to assign it to me.

**Comment by KshitijThareja** [comment]
@mekarpeles @scottbarnes I believe there's still no progress with this issue. If possible, please assign me this issue. I have completed working on it and will link a PR in some time.
Thanks :)

**Comment by bobmatyas** [comment]
@KshitijThareja I am still intending to submit a PR for this. I had some stuff come up and was unable to submit yet.

**Comment by KshitijThareja** [comment]
@bobmatyas I'm sorry I didn't see your reply. You should go ahead with this issue then.
