### ISSUE TITLE
Create a rational method to have a recaptcha-less dev environment

### ISSUE THREAD

**Issue by skylerbunny** [internetarchive/openlibrary#431]
*To develop with reCAPTCHA locally, for testing new user signups and edits that require a user to prove they are human, you will need to sign up for a reCAPTCHA API key pair from Google Developers* [(1)](https://github.com/internetarchive/openlibrary/blob/master/Quickstart.md#recaptcha)

If a developer wants to test *anything* with non-admin or anonymous user permissions, they have to create a reCAPTCHA pair to ultimately get to that point, requiring going to Google. This is a bit much to simply test out basics like non-admin record insertion when reCAPTCHA is irrelevant to the testing.

Can a simple flag be added to openlibrary.yml like 'use_recaptcha', enabled by default, that can be disabled? This at least makes it easy to turn off for simple testing, and would also open the door in future to (for example) do automated performance testing related to record adding.

**Comment by mekarpeles** [comment]
I'm for this, cc: @bfalling

**Comment by dvanduzer** [comment]
via @skylerbunny in Slack, an adaptable version of recaptcha v2: https://github.com/adium/python-recaptcha/blob/master/recaptcha/client/captcha.py

**Comment by hornc** [comment]
The place to add this check to disable recaptcha if in a dev environment would be:
https://github.com/internetarchive/openlibrary/blob/18c30c785efcc51aa24cfa80796c8470b48ae00c/openlibrary/plugins/upstream/addbook.py#L54

in `recaptcha_exempt()`

Is this entry in the config file,

https://github.com/internetarchive/openlibrary/blob/master/conf/openlibrary.yml#L62
`#dev_instance: True`
the appropriate config to check?

**Comment by salman-bhai** [comment]
@mekarpeles @hornc would #809 be sufficient to close this!

**Comment by salman-bhai** [comment]
@mekarpeles ?

**Comment by mekarpeles** [comment]
Recaptcha v2 works fine if either you use the public development keys which google issues, or if you register your own keys and add them to openlibrary.yml
