### ISSUE TITLE
We want a public roadmap!

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#432]
Hi all, thanks for voicing your opinions on our first community call in a while.

Several people requested we make an Open Library roadmap more publicly accessible.

A former roadmap was published here:
https://github.com/internetarchive/openlibrary/projects/1

Would this (projects) format work for an updated roadmap?

@bfalling and I will have a public roadmap we can share by our next community call, next Wednesday at 9:30am

Another frustration which was brought up is, people want to have better access and transparency into the Open Library team (for questions/answers) and code reviews. Our slack channel is the best way to get involved. I'll update our main documentation to describe how you get added. It's currently a manual process, so if you'd like to get added, send an email to mek@archive.org

Thanks everyone for a successful call #1!

**Comment by skylerbunny** [comment]
(Just a ping! Sent an email to that address about being added. Thanks!)

**Comment by mekarpeles** [comment]
@skylerbunny, made sure you're added on slack -- thanks for following up! Also, we're finalizing a public roadmap which will be discussed tomorrow @ 9:30am PST during our community call.

Will create the calendar invite shortly.

Looking forward to hearing everyone's input on our direction and priorities!

**Comment by mekarpeles** [comment]
We now have a public roadmap on our wiki for 2017 Q2 (and Q3) 
https://github.com/internetarchive/openlibrary/wiki/Roadmap
