### ISSUE TITLE
Library Explorer: Autocomplete + jump directly to a Classification / shelf

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4320]

**Comment by tallforasmurf** [comment]
Key here is doing it while staying in the virtual UI. Need a drop-down of Dewey/LoC categories perhaps?

**Comment by BrittanyBunk** [comment]
what does this even look like? I don't get it - however, it's not a priority for me to understand, as I"m not going to be working on it.

**Comment by cdrini** [comment]
Duplicate of #4356
