### ISSUE TITLE
Incorrectly placed books on some shelves in the new Explorer

### ISSUE THREAD

**Issue by ksze** [internetarchive/openlibrary#4322]
I see some incorrectly placed books on some shelves in the new Explorer.

Please see this screenshot:
![image](https://user-images.githubusercontent.com/381556/102857583-a8d64d80-4463-11eb-8a65-e7e836aa6511.png)

e.g.
- 00X sub-shelf:
  - [823.914](https://openlibrary.org/works/OL82537W)
  - [621.3916](https://openlibrary.org/works/OL65487W)
- 01X sub-shelf:
  - [364](https://openlibrary.org/works/OL20262W)
  - [002](https://openlibrary.org/works/OL4119177W)
etc.

**Comment by ksze** [comment]
Actually, I think I just realized what happened. Some books have multiple codes for some reason, even though some of those codes don't seem to make sense:
![image](https://user-images.githubusercontent.com/381556/102858009-7d079780-4464-11eb-9a34-df9dce69d4f9.png)

**Comment by ksze** [comment]
Assuming the codes are indeed correct, I would suggest displaying the code that got the book on a the shelf instead of the first code in the list, to reduce confusion.

**Comment by ksze** [comment]
Looks like this is related to #4314.

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/4322#issuecomment-749380583

Thank you @ksze! Good insights, agreed

**Comment by ksze** [comment]
Also seems related: #4323
