### ISSUE TITLE
API: fetch list of main subjects

### ISSUE THREAD

**Issue by smoqadam** [internetarchive/openlibrary#4328]
### How can get the list of all main subjects? 

is there any API to fetch this list:
![image](https://user-images.githubusercontent.com/1223848/103098618-61f47d80-4646-11eb-93ff-1ccc4bb409a1.png)

Thank you

**Comment by tfmorris** [comment]
No. It's a hardcoded-English only list embedded in the source code: https://github.com/internetarchive/openlibrary/blob/9718ae2731b7bcaedb3e48884fcf5251298c6a92/openlibrary/plugins/openlibrary/home.py#L99-L102
as are the carousel categories:
https://github.com/internetarchive/openlibrary/blob/9718ae2731b7bcaedb3e48884fcf5251298c6a92/openlibrary/plugins/openlibrary/home.py#L25-L30

**Comment by dherbst** [comment]
This PR could add an api to get the subjects https://github.com/internetarchive/openlibrary/pull/4336.  I'm not sure if this is the best url to use for the api - looking for feedback on that.

**Comment by smoqadam** [comment]
@dherbst Thanks. 

what about `/subjects/featured.json` or `/subjects.json?featured=true`?

**Comment by mekarpeles** [comment]
@smoqadam we don't currently have an API for this, unfortunately there is no current plan to create one (though it hasn't changed in ~4 years). Closing

**Comment by tfmorris** [comment]
I interpret this as a request for such an API, which seems like a perfectly reasonable request. 

@dherbst even contributed a PR which provided such an API, but abandoned the PR when it was ignored by reviewers for a month.

**Comment by dherbst** [comment]
FWIW if someone else wants to run with it - the PR went like this:

```python
from openlibrary.plugins.openlibrary.home import get_featured_subjects

class featured_subjects_api(delegate.page):
    path = r'/api/featured_subjects'

    @jsonapi
    def GET(self):
        featured_subjects = get_featured_subjects()

        return simplejson.dumps(featured_subjects)
```
