### ISSUE TITLE
Failing to solve recaptcha on 'add/edit a book' results in data entry loss

### ISSUE THREAD

**Issue by skylerbunny** [internetarchive/openlibrary#433]
If a contributor is adding information about a book and do not get the recaptcha correct, information that may have been entered will be lost upon either clicking the browser back button or using the 'Go Back' link provided:

* Contributors that have been added in that session will disappear, except for the author
* Identifiers (ISBN10, etc.) that have been added in that session will disappear

This means that there is a 'cost' to getting the recaptcha wrong beyond simply having to solve the recaptcha again; a contributor will be forced to re-enter information.

**Comment by mekarpeles** [comment]
This sucks, we should fix this. Thanks for reporting

**Comment by hornc** [comment]
It seems the only values that are retained on using browser back are retained by the browser cache. Authors and Identifiers are added to the page by other actions (Author autocomplete, and the Identifier 'Add' button) and therefore aren't retained in the same way the normal form field values are, so they are lost.

There a probably multiple ways to do this better
* AJAX verification of recaptcha before leaving the page?
* ability to re-load the form using the values that were previously POSTed

I think though that updating the recaptcha to the currently supported version is the sensible first step. Not sure of the priorities here.

**Comment by salman-bhai** [comment]
@mekarpeles @hornc will #809 have any conflicts with this one? I'm not so sure!

**Comment by salman-bhai** [comment]
@mekarpeles ?

**Comment by mekarpeles** [comment]
I believe I tested this and its working
