### ISSUE TITLE
Hover over 1 Hour Borrow Audio button flickers and width of the button gets way too big

### ISSUE THREAD

**Issue by serv** [internetarchive/openlibrary#4342]
### Evidence / Screenshot (if possible)

![1-hour-borrow](https://user-images.githubusercontent.com/103456/103433038-fad34d80-4b9e-11eb-9952-99b0aa41ef65.png)

### Relevant url?
https://openlibrary.org/books/OL362125M/Rainbow_Six

### Steps to Reproduce
1. Using Firefox or Brave to go https://openlibrary.org/books/OL362125M/Rainbow_Six
2. Under different editions of the book section, hover over the Audio 1 Hour Borrow button
3. Try moving the cursor from different size (left, top, right, bottom) to reproduce the bug.

* Actual: The 1 Hour Borrow button gets wider. Listen option doesn't appear. On Brave, the button flickers oscillating from width shrinking and growing.
* Expected: The Listen option should appear from the left to right.

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Firefox 84.0.1 (64-bit)
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I think the Listen button should appear like this.
![want](https://user-images.githubusercontent.com/103456/103433093-df1c7700-4b9f-11eb-99eb-904ced9a25ac.png)

**Comment by Yashs911** [comment]
@serv I would like to work on this issue.

**Comment by Yashs911** [comment]
![ol](https://user-images.githubusercontent.com/64412143/103435572-70d6c380-4c36-11eb-8d7a-1227bb0a99ed.JPG)
this issue is caused due to this. @jamesachamp if possible can you please help why we need this particular media query.

**Comment by Yashs911** [comment]
@cclauss #4374 fixed this issue. Should I close my PR?? and we can close this issue.

**Comment by cclauss** [comment]
Yes and yes.  Thanks!
