### ISSUE TITLE
BWB Import Errors

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4359]
- BWB Import error; perhaps around dates?
- BWB gets stuck after hitting some sort of rate limit?

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Duplicate of #4359

**Comment by LeadSongDog** [comment]
@mekarpeles 
Wait, what? How is #4359 a dupe of #4359?
Anyhow, many (most?) BWB import histories are showing ISBN links that can’t be found for confirmation at BWB.
Example: https://openlibrary.org/books/OL29622724M/Moritz_Pasch?m=history 
Either they never existed or bwb is deleting them. We need to archive them somewhere for traceability, perhaps on the wayback?
