### ISSUE TITLE
Borrowbot has error with multiple replies

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4361]
When someone replies to borrowbot, it repeats its message. It shouldn't say anything after its responded once?

(Note: this is a bots issue, but placed here to make our project management saner)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
@robertIanClarkson what's the latest on this one?

**Comment by robertIanClarkson** [comment]
@cdrini Still plan on finishing the bot. Right now it is working pretty well though. I just need to clean it up a bit. 
Sorry, I've been MIA because I had a contract job and had to move apartments.
Should have time this week to finish it up.

**Comment by robertIanClarkson** [comment]
@cdrini I have finished my v1 refactor of the code. It should behave as we expect.

You can tweet the bot directly with an isbn or amazon link
You can comment an `@borrowbot` on a thread that has an isbn or link (Note: this will only look 1 level up at the parent tweet, no deeper)
The bot will ignore replies that do not have an isbn or link

Here is the code: https://github.com/robertIanClarkson/openlibrary-bots/pull/1

Mek gave me credentials to the borrowbot server but I want to run the code and functionality by someone more senior beforehand.

**Comment by cdrini** [comment]
@mekarpeles Says this one looks closed! 🎉
