### ISSUE TITLE
Bookshelves appear empty on Chrome

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4362]
Bookshelves appear empty until scrolling happens.

### Relevant url?
https://openlibrary.org/explore

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by nynaalekhya** [comment]
@cdrini 
Hi,
Could I work on this issue?

**Comment by nynaalekhya** [comment]
I think this may be caused due to IntersectionObserver.
