### ISSUE TITLE
2021 community call

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4367]
When is it?

**Comment by jamesachamp** [comment]
Tuesdays at 10:00 AM PST.

**Comment by BrittanyBunk** [comment]
@jamesachamp thanks, because I was going off the wiki, so it gave me the wrong time.

**Comment by BrittanyBunk** [comment]
I'm really glad it's at 10. I just can't do 11:30 - it's way too late in the day and is around lunch time.

**Comment by BrittanyBunk** [comment]
@jamesachamp why does it look like 11:30am here? https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes

**Comment by cdrini** [comment]
Fixed
