### ISSUE TITLE
Rating Stats round off stars to lowest integer

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4371]
Ratings like 3.99, 3.84 print only 3★.
### Evidence / Screenshot (if possible)
![ol](https://user-images.githubusercontent.com/64412143/103731457-350f7580-500b-11eb-9546-b6ba811c424d.PNG)

### Relevant url?

https://openlibrary.org/books/OL362125M/Rainbow_Six

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jamesachamp

**Comment by jdlrobson** [comment]
Why? I don't consider this a bug. It's important context that its 3.94 (almost 4) and not 3. Even Amazon does this.

I would like to decline this without strong reasoning.

**Comment by Yashs911** [comment]
@jdlrobson we can use half star rating instead just like goodreads
![image](https://user-images.githubusercontent.com/64412143/104104053-a8dfa580-52cb-11eb-8399-a22bafdf849b.png)

**Comment by Yashs911** [comment]
> Why? I don't consider this a bug. It's important context that its 3.94 (almost 4) and not 3. Even Amazon does this.
> 
> I would like to decline this without strong reasoning.

@jdlrobson, I am not asking to round off the 3.94 value. I am saying we should either use fraction star or round off the number of stars.

**Comment by tfmorris** [comment]
The two alternatives are:
1. *** 3.94
2. **** 3.94

@jdlrobson Why do you think the first (ie the current behavior) is better than the second?

**Comment by jdlrobson** [comment]
Ideally this would be a half star and a fraction.
Saying something is 3/5 stars when actually it is 3.95 is a bit controversial IMO.

> @jdlrobson Why do you think the first (ie the current behavior) is better than the second?
What I'm asking here is what exactly is the problem statement here? This seems like a non-problem to me. The onus should be on the proposer to

**Comment by Yashs911** [comment]
> The onus should be on the proposer to tell me why the new behaviour is better than the old. What I'm asking here is what exactly is the problem statement here? This seems like a non-problem to me.

@jdlrobson The problem is showing a 3.5+ rating as 3 on a scale of 5. A more solid solution will be using half stars, but in the mean time, we could use my solution where rating < 3.5 print (`***`) and rating > 3.5 print (`****`)

**Comment by jdlrobson** [comment]
The correct solution to this is to change the star graphic, but I also do not see this as a high priority, so please let us focus on other things. The list of pull requests is already extremely large, so we should be making efforts to clear that first .
