### ISSUE TITLE
Remove Python 2 support

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4384]
Blocked by ~#4324 and~ #4383 (The last of our production code that still uses Python 2)

Purpose: Faster and smaller builds/CI!
- [x] #4385 Remove testing on 2.7 from CI
- [x] #4386 Remove 2.7.6 install from olbase

**Comment by mekarpeles** [comment]
This can be closed, the remaining tasks have been moved to #4776. We have a bit more work to do re: ol-dumps cron, but we've already made our docker instances Py2-only, and so we accept the risk that breaking py2 changes could occur on remaining ol-home crons.
