### ISSUE TITLE
Recent activity not showing on list page

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4389]
Problem:
https://openlibrary.org/lists shows
![image](https://user-images.githubusercontent.com/55302685/104034250-7c217600-5185-11eb-84bb-4cddefc34b54.png)

when it should be filled with 
![image](https://user-images.githubusercontent.com/55302685/104034301-8e9baf80-5185-11eb-9219-2b62e46b081f.png)

Solution:
- remove 2nd column of active lists
- add in from recent changes page: https://openlibrary.org/recentchanges/lists
- level the recent changes title with the active changes title on https://openlibrary.org/lists

other ideas: 
- put recent changes underneath active lists
- put 'recent changes' in parentheses in the same title as 'active lists'

**Comment by Yashs911** [comment]
@BrittanyBunk  its due to alignment error (#3264)
![image](https://user-images.githubusercontent.com/64412143/104034921-83816780-51f7-11eb-9bf3-cb9a122d12bb.png)

**Comment by BrittanyBunk** [comment]
duplicate
