### ISSUE TITLE
Book Donations Flow

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4398]
By piloting book sponsorship, we've learned a lot about what patrons are looking for in a book donation flow (compared to our vanilla process of emailing the Archive, checking if a title is available, and mailing the book to our physical archive -- as described in https://openlibrary.org/bookdrive.

A benefit of the sponsorship flow is it helps patrons identify which titles may not yet be in the controlled digital lending library. One cost, however, which has become especially evident due to additional challenges posed by the pandemic, is that sponsorship poses logistic challenges and constraints which do not exist within our vanilla book donation flow.

After stakeholder discussions, we've decided to try temporarily simplifying the book contribution process with a v2 of this program that tries to find a happy medium between vanilla donation and an integration which both (a) helps patrons discover which books may be useful for the library and (b) simplifies / streamlines / guides patrons through the process of donating a copy of a book.

This opens up possibilities because such a revised flow also enabled patrons who may already own the book to donate it to the library without being required to purchase an additional copy (a concern we hear raised regularly). This proposal also comes after learning our physical collections team has their own process for handing book donations and there may be an opportunity for us to leverage and re-purpose our existing processes and technology to converge on a single flow which accommodates both teams and ultimately results in a better outcome.

The initial goals of the sponsorship program were to give patrons a voice, increase representation and diversity of our materials, and simplify/streamline the process of making certain qualifying titles available through the library. In the spirit of continuing to make the process as simple as possible (both for patrons and also for us, in terms of managing multiple programs) we think it makes most sense to try only this simpler flow for some time (rather than maintain multiple systems which may work differently and require different support).

## Proposal

The general idea of the new donation flow is to show a "Donate" button where the Sponsorship button used to be on any qualifying titles. Instead of eating all of the logistic challenges of the sponsorship program (even though this may be most convenient for patrons), we'd like to test instead showing a popup with instructions to help patrons either donate an existing copy of the book they own, or to purchase a copy to donate to the library's address.

### Stakeholders

@bfalling @cdrini

**Comment by BrittanyBunk** [comment]
I think that makes more sense, as the money shouldn't go towards books when it can go towards other things. Also, people want to get rid of their books all the time - especially in the pandemic. Logistically, buying may not be as guaranteed for getting the desired book compared to donations. I mean, maybe there are rare books even that aren't even available to buy! It also allows books to get into the OL faster, as we don't have to wait until there's enough money. It might even be cheaper, as I bet some people may just buy a book on their own for really cheap and send it out.

Plus, from an environmental perspective - too much paper!

One day I really hope it'll come to a point where no one has to physically send over a book but rather be able to be the controlled lender where they are - so people can treat borrowing books like they would in person - and that's safer/healthier too. I mean, that would even go better with the idea of an open library. I guess there'd have to be a way to verify the person still has the physical book - but I bet there's a way.

Just glad that better efficiency's been figured out.
