### ISSUE TITLE
scripts/copydocs.py /books/OL26617202M does not update book count

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4400]
### Evidence / Screenshot (if possible)
https://openlibrary.org/search/authors?q=Fabienne+Clauss author has 1 book...
1. Launch Open Library in a Docker container on localhost.
2. `open http://localhost:8080/status`  # to ensure OL is running properly
3. `http://localhost:8080/search/authors?q=clauss`  # there should be no hits
4. `docker exec -it openlibrary_web_1 /bin/bash`
5. `./scripts/copydocs.py /books/OL26617202M`  # to import https://openlibrary.org/books/OL26617202M
```
./scripts/copydocs.py /books/OL26617202M
fetching ['/books/OL26617202M']
found references ['/works/OL18072639W']
fetching ['/works/OL18072639W']
found references ['/authors/OL7440583A']
fetching ['/authors/OL7440583A']
saving ['/authors/OL7440583A']
[{'key': '/authors/OL7440583A', 'revision': 1}]
saving ['/works/OL18072639W']
[{'key': '/works/OL18072639W', 'revision': 1}]
saving ['/books/OL26617202M']
[{'key': '/books/OL26617202M', 'revision': 1}]
```
* http://localhost:8080/authors/OL7440583A  # Shows the author ✅ Author has 1 work.
* http://localhost:8080/works/OL18072639W  # Shows the work ✅
* http://localhost:8080/books/OL26617202M  # Shows the book ✅
* http://localhost:8080/search/authors?q=Fabienne+Clauss  # Shows the author but the ___author has no books___ ❌ 

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
This is solr being laggy :) It should update after a bit. You can try running `docker-compose exec make reindex-solr`. Let me know if that works!
