### ISSUE TITLE
Add small icon link to Worldcat from editions list

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4408]
Prior to the new books page design launch in summer 2020, the editions list had a Worldcat icon linking to the record for that edition. This is handy when sorting out long edition lists that contain study guides, comic books, adaptations, etc. incorrectly associated with a work (usually classics or anything that's ever been made into a children's movie).

### Describe the problem that you'd like solved
Add the icon to the editions list as it was before the new books page.

### Proposal & Constraints

This icon is generally only useful for librarians, so something small that doesn't get in the way is sufficient.

### Stakeholders
@seabelis

**Comment by BrittanyBunk** [comment]
where's it located now?

**Comment by Yashs911** [comment]
@seabelis I would like to work on this issue.

**Comment by seabelis** [comment]
@Yashs911 Thank you.

**Comment by Yashs911** [comment]
@seabelis I have added the link below Download for print disabled.
![worldcat](https://user-images.githubusercontent.com/64412143/104409308-fe49da00-558b-11eb-803e-0bedb503a390.JPG)

**Comment by seabelis** [comment]
LGTM. Thank you.

**Comment by Yashs911** [comment]
@seabelis Added "Libraries near you:" text
![Capture](https://user-images.githubusercontent.com/64412143/104459949-7be50880-55d3-11eb-93e4-89eb11baabc5.JPG)

**Comment by seabelis** [comment]
Yes, that indicates it's not part of the print-disabled link.
