### ISSUE TITLE
troubleshoot Vagrant login configuration to make Quickstart quicker

### ISSUE THREAD

**Issue by dvanduzer** [internetarchive/openlibrary#442]
As originally reported by @skylerbunny, after running `vagrant up`, there is still an issue logging into the admin interface of the dev instance. The new xauth service and the captcha configuration are the two biggest barriers to a "quick" quickstart for new devs.

**Comment by bfalling** [comment]
Do the reCAPTCHA config instructions in the Quickstart.md file help?

**Comment by dvanduzer** [comment]
Yes, I'll retitle this issue...

**Comment by mekarpeles** [comment]
It would be nice if no recaptcha was required in order to get up and running (i.e. if no config key present, don't require captcha). @skylerbunny may have also mentioned this point

**Comment by hornc** [comment]
I _think_ currently you don't need a valid key in the config for admin to login (as admins don't get recaptchas), but the keys need to be there in the config file for it to be parsed correctly.

**Comment by mekarpeles** [comment]
See also: https://github.com/internetarchive/openlibrary/issues/444 which is a related problem (s3 key for a privileged role user which OL needs to validate creds against archive.org's xauth API)

**Comment by skylerbunny** [comment]
The point I was trying to make is that ideally we might not want it to be necessary to do anything with Google to create a basic OL environment to develop on, at least in theory. No key generation, no nothing. [I do believe I can do this by simply eliminating the code block that checks for recaptcha whatsoever in both places, but it probably wants to be more user friendly than that].

**Comment by mekarpeles** [comment]
On slack, @hornc suggests one may possible by able to do:

> I just found this in my notes, which I think gets around the recaptcha error without needing an actual google key:

```plugin_recaptcha:
    public_key: "test"
    private_key: "test"
```

If so, this may also address the problem (though we should update the quickstart.md accordingly).

Also, again (sorry to disappoint), though this may solve the recaptcha problem and while I totally agree the best experience is to "just work" out of the box, an s3 key will be a blocker for logging in (i.e. https://github.com/internetarchive/openlibrary/issues/442#issuecomment-285846556)

**Comment by dvanduzer** [comment]
When I use those test credentials, I still get the recaptcha error. The instructions in quickstart.md are still accurate for working around this. The other issue is best described in #444
