### ISSUE TITLE
Allow page rotation while reading books that may have horizontal content  

### ISSUE THREAD

**Issue by shrey27tri01** [internetarchive/openlibrary#4428]
For books that may have horizontal content (an example screenshot is attached), users should be able rotate the page to better view it. This may not be necessary for mobile/tablet or even laptop users, but it may be necessary for desktop users.

### Describe the problem that you'd like solved

A rotation option should be present in the bottom navbar to rotate the book by 90 degrees, either clockwise or counterclockwise.

### Proposal & Constraints

A *rotation button* as an option on the bottom navbar, where the *Flip left*, *Flip right*, *Zoom in*, *Zoom out*, etc. buttons are present, like this one:
![Screenshot from 2021-01-16 18-05-19](https://user-images.githubusercontent.com/52366674/104812059-a4fcd780-5825-11eb-9680-03378dbe0c15.png)

### Additional context

Here is an example where the page may need to be rotated by the user 90 degrees to the right (Taken at *page 12* from the book [*Angels & Demons* by *Dan Brown*](https://openlibrary.org/books/OL31443610M/Angels_Demons)). 

![Screenshot from 2021-01-16 17-59-58](https://user-images.githubusercontent.com/52366674/104811930-e3de5d80-5824-11eb-8907-0a32714533b4.png)

**Comment by Yashs911** [comment]
@shrey27tri01 I guess you should open this issue on bookreader repo

**Comment by mekarpeles** [comment]
Closing and crossposting to bookreader
