### ISSUE TITLE
Subjects page (page-subject.less) loads unnecessary CSS - should be simplified.

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4429]
### Evidence / Screenshot (if possible)

According to static/build/page-subject.css the subjects page loads 8KB of CSS. This is 2kb more than the home page, despite being a very simple page.

It looks like we never simplified the CSS when redesigning the subject page.

A casual glance at static/css/page-subject.less shows we still import components/dropper.less for example, despite not ever showing the component.

Let's check what CSS is unused using an unused CSS audit and simplify this stylesheet and reduce the bundle size.

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this. Should we use the following PurifyCSS, PurgeCSS, UnCSS to remove unused CSS?

**Comment by arnab15** [comment]
@Yashs911  are you working on it? @jdlrobson  if it's not assigned to anyone I can work on it if you guide me a little bit on how I can perform optimization to solve the issue?

**Comment by jdlrobson** [comment]
The file is meant to act as an inventory of features on the page, so it should be easily done manually without tools by checking the styles added (in particular their parent selector) and whether they relate to the html on the page. 

There is a lot of unused css in the site, but that's not the priority here.

**Comment by Yashs911** [comment]
@jdlrobson I went thrrough all the imports and here what I found:
```
@import (less) "components/carousel.less";
@import (less) "components/chart.less";
@import (less) "components/link-box.less";
@import (less) "components/widget-box.less";
@import (less) "components/dropper.less";
@import (less) "components/listLists.less";

```
All these imports are not used in https://openlibrary.org/subjects **but are used in** https://openlibrary.org/subjects/sciencemathematics .

![tempsnip](https://user-images.githubusercontent.com/64412143/105012580-4e311100-5a64-11eb-8097-58ba72e225fd.png)

Following are the links to the design wiki:
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#carousel
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#chart
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#widgetbox
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#dropper
https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library#listslists

**Comment by jdlrobson** [comment]
Good point! I overlooked the subjects pages themselves. While we could create a new entry point for this page, I don't think there's much value in doing that.

Thanks for investigating so thoroughly!
