### ISSUE TITLE
Fix validation issues on the view subject pages

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4438]
Incorrect HTML can lead to rendering issues and bugs.

### Evidence / Screenshot (if possible)
The validator tool flags errors on https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fsubjects%2Fmagic

### Steps to Reproduce

1. Run `docker-compose exec web bash`
2. Run `python ./scripts/copydocs.py "/subjects/magic"
3. Use the validator tools direct input feature to flag errors
4. fix errors in the associated templates
5. submit a pull request addressing the issues.

### Stakeholders
@jdlrobson

**Comment by nynaalekhya** [comment]
Hi @jdlrobson ,
Can I work on this issue?

**Comment by Yashs911** [comment]
@jdlrobson #4481 will fix this issue.
![image](https://user-images.githubusercontent.com/64412143/105943303-02472300-6087-11eb-908f-098d28a04479.png)

**Comment by Yashs911** [comment]
@jdlrobson I think we can close this issue.

**Comment by jdlrobson** [comment]
yep all good! thanks!
