### ISSUE TITLE
Fix validation issues on the author page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4439]
Incorrect HTML can lead to rendering issues and bugs.

### Evidence / Screenshot (if possible)
The validator tool flags errors on author pages

e.g. https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fauthors%2FOL18319A%2FMark_Twain

### Steps to Reproduce
1. Run `docker-compose exec web bash`
2. Run `python ./scripts/copydocs.py "/authors/OL18319A/Mark_Twain"
3. Use the validator tools direct input feature to flag errors
4. fix errors in the associated templates
5. submit a pull request addressing the issues.

### Stakeholders
@jdlrobson

**Comment by nynaalekhya** [comment]
Hi @jdlrobson,
Can I work on this issue?

**Comment by nynaalekhya** [comment]
Thank you, @jdlrobson.
