### ISSUE TITLE
Fix HTML validator issues on books page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4440]
Incorrect HTML can lead to rendering issues and bugs.

### Evidence / Screenshot (if possible)
The validator tool flags errors on https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fbooks%2FOL28775995M%2FDer_Todeskanal/Der_Todeskanal

### Steps to Reproduce

1. Run `docker-compose exec web bash`
2. Run `python ./scripts/copydocs.py "/books/OL28775995M"
3. Use the validator tools direct input feature to flag errors
4. fix errors in the associated templates
5. submit a pull request addressing the issues.

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue.
![image](https://user-images.githubusercontent.com/64412143/105120438-3c994900-5af8-11eb-8aaf-58a5bbf6d4e3.png)
I think in the URL, you have added Der_Todeskanal two times

**Comment by Yashs911** [comment]
@jdlrobson 
![image](https://user-images.githubusercontent.com/64412143/105121293-da414800-5af9-11eb-9cda-d2fe1428122b.png)
1st error: replacing space with %20 (encoding the URL) will solve this error
2nd error: I don't think we can do anything about it? Or can we?
3rd error: Already Fixed

**Comment by jdlrobson** [comment]
> @jdlrobson I would like to work on this issue.

Sure. All I ask is just to pick one task at a time so that others don't get alienated from contributing.

>  2nd error: I don't think we can do anything about it? Or can we?

This should be an attribute `data-workid`, which will require potentially other changes in JS/CSS

**Comment by Yashs911** [comment]
@jdlrobson, I have fixed all the errors. Can you please guide me on how to fix `Duplicate ID read_ebook. (4)` the same error is also there on the homepage.
