### ISSUE TITLE
Fix validation issues on the home page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4441]
Incorrect HTML can lead to rendering issues and bugs.

### Evidence / Screenshot (if possible)
The validator tool flags errors on the home page

e.g. https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2F

### Steps to Reproduce
1. Run `docker-compose exec web bash`
2. Use the validator tools direct input feature to flag errors on the home page
3. fix errors in the associated templates
4. submit a pull request addressing the issues.

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue.

**Comment by Yashs911** [comment]
@jdlrobson 
![image](https://user-images.githubusercontent.com/64412143/105119629-baf4eb80-5af6-11eb-9938-1184c35f33d4.png)
How should I fix the src error should I write src="" or something else?
How should I fix the duplicate id error?

**Comment by jdlrobson** [comment]
> How should I fix the src error should I write src="blank.gif" or something else?

I'd recommend using a base64 1x1 png for this
You can get the base64 via https://png-pixel.com/
and make it a data uri in the src attribute per https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

Make sure to use a constant so that URL doesn't make the template unreadable!
