### ISSUE TITLE
Mobile Nav Menus fail to close

### ISSUE THREAD

**Issue by shrey27tri01** [internetarchive/openlibrary#4444]
Clicking the account component and other menus in the header after opening them in mobile view doesn't close them.

This issue is an extension to #4200. Re-clicking the account component and the _My Books_ and _Browse_ menus in the header, after opening them, doesn't close them. Ideally they should be closed after re-clicking them.   

### Relevant url?

https://openlibrary.org/

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Open Developer Console, toggle to Mobile View and click on the _Browse_ or the _My Books_ menu to open either of them
3. Click on the opened menu again to close it.

To reproduce the bug for the account component:
1. Go to https://openlibrary.org/ and login
2. Open Developer Console, toggle to Mobile View and click on the account component:
![](https://user-images.githubusercontent.com/148752/104268991-131e5480-544a-11eb-9d0b-91f1273bc065.png)
3. Click on the it again to close it.

* Actual: Step 3 doesn't do anything.
* Expected: Step 3 should close the menu.

### Details

- **Logged in (Y/N)?** Yes for the account component, No for the others
- **Browser type/version?** Firefox Version 84.0.2 (64-bit)
- **Operating system?** Ubuntu 20.04
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

A similar solution as has been used for #4200 should fix the isssue

**Comment by jdlrobson** [comment]
@shrey27tri01 any updates on this one?

**Comment by shrey27tri01** [comment]
Sorry, couldn't get time due to college work :sweat_smile: 
Though I have started working on it now. Will raise a PR soon :)

**Comment by shrey27tri01** [comment]
@jdlrobson I've created a PR [here](https://github.com/internetarchive/openlibrary/pull/4501). Do check it out :)
