### ISSUE TITLE
Lists page has duplicate lists id

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4472]
When using the validator tool on https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Flists you'll notice that one of the complaints is that #list is used twice.

* Ideally remove the id on the body tag, or at least rename it to "page-lists"
* Confirm the validator passes for this page.

### Evidence / Screenshot (if possible)

<img width="1349" alt="Screen Shot 2021-01-23 at 9 32 08 AM" src="https://user-images.githubusercontent.com/148752/105609399-e0376300-5d5d-11eb-91bd-cb631379be6b.png">

### Relevant url?
https://openlibrary.org/lists

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
@jdlrobson I would like to work on this issue

**Comment by Yashs911** [comment]
@jdlrobson, the body id is actually generated and is interconnected in some way. Changing the id breaks the page.
```
class lists_home(delegate.page):
    path = "/lists"

    def GET(self):
        delegate.context.setdefault('bodyid', 'lists')
        return render_template("lists/home")

class lists(delegate.page):
    """Controller for displaying lists of a seed or lists of a person.
    """
    path = "(/(?:people|books|works|authors|subjects)/[^/]+)/lists"
```
Can we instead change the `<div is="lists" >` to  "list" or something else because testing body id change might be difficult.
