### ISSUE TITLE
Fix validation issues on user list page

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4473]
Incorrect HTML can lead to rendering issues and bugs.

### Evidence / Screenshot (if possible)
The validator tool flags errors on user lists page

e.g. https://validator.w3.org/nu/?doc=https%3A%2F%2Fopenlibrary.org%2Fpeople%2Frobothugs%2Flists%2FOL192872L%2FCycle_2_Books

### Steps to Reproduce
1. Run `docker-compose exec web bash`
2. Import lists into site using `python ./scripts/copydocs.py`
3. Use the validator tools direct input feature to flag errors on https://openlibrary.org/people/robothugs/lists/OL192872L/Cycle_2_Books
4. fix errors in the associated templates
5. submit a pull request addressing the issues.

### Stakeholders
@jdlrobson

**Comment by nynaalekhya** [comment]
@jdlrobson ,
Can I work on this issue?
