### ISSUE TITLE
UI for adding a page to a list is unintuitive, could be improved

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4480]
The list UI is not great. It's not clear that clicking list names will add the current book to the list, and it becomes even more confusing when those same links link to the lists themselves.

### Relevant url?
Any book page. e.g. https://openlibrary.org/works/OL194006W/Diary

### Steps to Reproduce

I was playing around with the list feature today, and opened the list widget:

<img width="263" alt="Screen Shot 2021-01-23 at 9 15 25 PM" src="https://user-images.githubusercontent.com/148752/105621774-1f969b80-5dc0-11eb-8297-6fffde4a221e.png">

Click the list "Jon's Recommended".

Expected: I will go to the list.
Actual: My book was added to the list without any confirmation and no obvious way to remove it.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

At minimum. I think the "My Reading Lists:" heading should be changed to "Add to existing list:",
when I click the link I should get a confirmation saying "Are you sure you want to add to the list?"

A better solution might be to  display all my lists with checkboxes next to them, or at least empty checkboxes next to the title. This also allows me to undo if necessary.

### Stakeholders
@mekarpeles

**Comment by Yashs911** [comment]
@jdlrobson UI on local host:
![image](https://user-images.githubusercontent.com/64412143/105626907-3b9a4b80-5e59-11eb-8842-db0a900d7e24.png)

**Comment by jdlrobson** [comment]
This is how it will look when #4369 lands, yes. However, I think this amplifies the problem, as it  the "my reading lists" section is no longer related to the dropper component. It looks like a shortcut to reading lists links.

At least the link "Personal List" should read "Add to **Personal List**" and "My Reading Lists" should be changed to "Add the book to a list:"

"Create a new list" should also possibly be renamed "Add to a new list" and autopopulate the list with the book.

**Comment by BrittanyBunk** [comment]
it would be nice to have checkboxes next to the lists, so people can check and uncheck them. I have this issue a lot, but I just haven't brought it up, because so many other issues have popped up for me.

**Comment by seabelis** [comment]
Related to #3561

**Comment by Yashs911** [comment]
@jdlrobson Currently the UI looks like this:
![image](https://user-images.githubusercontent.com/64412143/107016059-7f7b4200-67c3-11eb-8b7e-cb7a69f99a1a.png)
But when I click **Use this Work** checkbox
I see the **Personal List** option as well but this book is already added to the Personal List.
![image](https://user-images.githubusercontent.com/64412143/107019364-9459d480-67c7-11eb-96d4-1d7752ffbc83.png)

**Comment by mekarpeles** [comment]
Related also to #7390, marking as dupe since a good portion of the concerns are addressed by current work or are captured in the aforementioned tracking issue
