### ISSUE TITLE
Random Hamburger checkbox visible in narrow / mobile viewpoint

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4486]
### Evidence / Screenshot (if possible)

![openlibrary org_ (9)](https://user-images.githubusercontent.com/978325/105746609-84531280-5ef4-11eb-9ff7-47754fff3314.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by nynaalekhya** [comment]
@jdlrobson ,
The visibilty of checkbox could be set to hidden.

**Comment by jdlrobson** [comment]
@mekarpeles this is a caching issue I noted in the review. Please clear the caching on that page to fix.

**Comment by jdlrobson** [comment]
Where are you seeing it?

**Comment by Yashs911** [comment]
@jdlrobson opacity: 0; is applied to the input but I it will be better if we use display: none;
![image](https://user-images.githubusercontent.com/64412143/105794853-dc9c1a00-5fb1-11eb-89e7-f906d512e6d3.png)
![image](https://user-images.githubusercontent.com/64412143/105794919-fa697f00-5fb1-11eb-9fd0-0ceff1ed115d.png)

**Comment by jdlrobson** [comment]
Opacity 0 is necessary. Checkbox hack doesnt work with display none.

This shouldn't be a problem I just need to understand from @mekarpeles where we are seeing this (production? Dev? ) before suggesting an issue.

**Comment by Yashs911** [comment]
@jdlrobson I am able to use display: none; and I also didn't notice the checkbox in mobile viewpoints.

https://user-images.githubusercontent.com/64412143/105796169-474e5500-5fb4-11eb-95c6-2003a6073270.mp4

**Comment by Arnab11917676** [comment]
hello @jdlrobson, can I work on this issue...

**Comment by jdlrobson** [comment]
I checked in with @mekarpeles and he cannot reproduce. This is a caching problem like I suspected.
