### ISSUE TITLE
List's Works show 0 Editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#449]
This impacts discovery and access of Works through our user Lists. Currently any Work on a List is show as having 0 editions (and thus no borrow icon). Perhaps the problem is how the List is put into solr?

**Comment by hornc** [comment]
Seed class is here: https://github.com/internetarchive/openlibrary/blob/c4d877ee6410df6f70ab45718baebe52fdf366ba/openlibrary/core/lists/model.py#L294

`get_solrdata` on a work seed always seems to return 0 edition counts: `{'ebook_count': 0, 'last_update': datetime.datetime(2013, 3, 28, 7, 50, 48, 835814), 'work_count': 0, 'edition_count': 0}` So maybe there is a problem with solr?

The [Work view template](https://github.com/internetarchive/openlibrary/blob/329b122997a532d8dbcaa9979a97b2d9d3024720/openlibrary/templates/type/work/view.html) shows the correct edition count by getting the seed's document edition count...

**Comment by mekarpeles** [comment]
@hornc this is consistent with my suspicions.

**Comment by hornc** [comment]
After testing my PR, I notice that some works have `get_ebook_info` results, which shows **Read** and **Borrow** icons, and others don't when they clearly have ebooks available. Seems like that the root cause is with how solr has indexed works

**Comment by mekarpeles** [comment]
@hornc demolished this bug
