### ISSUE TITLE
Can collection carousel display be sorted by # of editions or availability?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4493]
### Question
Can collection carousel display be sorted by # of editions or availability?

### Additional context
For example, if the results of a query include public domain, lending library, and print-disabled, the ability to sort or filter on the type best suited for the collection would be helpful. See https://openlibrary.org/collections/happy-new-year-2021 where many 'not in library' results appear when there are also borrowable works available.

### Issue resolution criteria
This can be closed if a solution is provided or if it is not going to be implemented.

### Stakeholders
@seabelis @mekarpeles

**Comment by BrittanyBunk** [comment]
@seabelis I brought this issue up in #4379, but you put them into words, so kudos

**Comment by BrittanyBunk** [comment]
duplicate of #3248

**Comment by seabelis** [comment]
Documented here. https://github.com/internetarchive/openlibrary/blob/85bc3e69150f4e19edd8e3e6c8720169dd4dcb7b/openlibrary/macros/QueryCarousel.html#L1
