### ISSUE TITLE
Show most available on carousel thumbnails

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4503]
Problem
Many books in a carousel will show an edition's not available, which is true. However, the other editions can very well be. 

Solution
I propose for the thumbnail of a work to show the most available edition. So instead of saying 'not in library', when there's 'borrow' and 'read' editions, put up the 'read' edition in the thumbnail instead. If that's not available, do 'borrow', etc.

**Comment by mekarpeles** [comment]
This is a technical limitation, not by design. Our solr roadmap for 2021 should resolve this issue because in the future we should reliably know which editions are e.g. inlibrary, language, etc.
