### ISSUE TITLE
Home Page Color Contrast

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4523]
EPIC: #4522
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/106560463-112d4a00-654d-11eb-9f76-98589e36bb3e.png)

### Relevant url?

[Home](https://openlibrary.org/)
### Steps to Reproduce

1. Go to https://wave.webaim.org/report#/https://openlibrary.org/

### Proposal & Constraints

Currently the contrast ratio is **2.84:1** for background color `#999999` and foreground color `#FFFFFF`. Changing the background color to `#757575` will make the contrast ratio **4.6:1**

**Comment by BrittanyBunk** [comment]
not quite sure I follow - it looks fine.

**Comment by bpmcneilly** [comment]
Thank you for reporting @Yashs911! - Out of curiosity, have you tested other potential color contrast issues on the homepage, or are you interested in helping more with our accessibility efforts? If so, please feel free to reach out to me!

**Comment by Yashs911** [comment]
@bpmcneilly I only found 2 color contrast issues on the homepage (both due to the 2 `Not in Library` buttons).
![image](https://user-images.githubusercontent.com/64412143/106696733-5744e500-6603-11eb-97bc-28a6d2faafbc.png)

And Yes, I would like to solve other issues as well, one page at a time.
Should I create a PR with the above solution?

**Comment by bpmcneilly** [comment]
@Yashs911 - if you feel comfortable making the edits, please do. The color change, from an accessibility perspective, looks perfect to me!
