### ISSUE TITLE
TypeError on openlibrary/templates/type/work/view.html

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4524]
Some works throw the following error: 
`/openlibrary/openlibrary/templates/type/work/view.html: error in processing template: TypeError: expected string or bytes-like object (falling back to default template)
`
### Relevant url?
https://openlibrary.org/works/OL17364096W/Hikayat_Iskandar_Zulkarnain?debug=true&edition=

### Steps to Reproduce

1. Go to ... https://openlibrary.org/works/OL17364096W/Hikayat_Iskandar_Zulkarnain?edition=

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cclauss

**Comment by cclauss** [comment]
The code is trying to do a `re.match()` on the `author.name` but in this case the `author.name` is `None` so the `re.match()` raises a TypeError.  The empty string would be a safer value for a str than `None`.

https://openlibrary.org/authors/OL7292325A

**Comment by Yashs911** [comment]
@seabelis I guess this issue was fixed but....
![image](https://user-images.githubusercontent.com/64412143/107198697-771d4400-6a1b-11eb-9981-ac9b28a61ab0.png)

**Comment by cclauss** [comment]
Yes.  The `author is None` issue was fixed via another repo.

My sense was that `LoanStatus` would always raise an error on an Edition that is `Not in Library`
* https://openlibrary.org/works/OL19545135W/The_Moon_Is_a_Harsh_Mistress?debug=true?edition=

**Comment by Yashs911** [comment]
> My sense was that `LoanStatus` would always raise an error on an Edition that is `Not in Library`
> 
> * https://openlibrary.org/works/OL18072639W/La_Grande_Neige?debug=true?edition=
> * https://openlibrary.org/works/OL19545135W/The_Moon_Is_a_Harsh_Mistress?debug=true?edition=

I didn't notice the `?debug=true` 😄 
We can close this issue.

**Comment by seabelis** [comment]
Thank you.
