### ISSUE TITLE
How come the community calls wait on a host to join in?

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4528]
Problem:
it's too difficult to join the community meetings, because of the need for host approval. It causes me to miss the meetings. Last year, the meetings were completely open.

Solution:
open the meetings to where people don't need a host approval, just like how it was before.

**Comment by mekarpeles** [comment]
We'd need to create a new zoom link, we usually set multiple hosts so this shouldn't be too big of a problem. There isn't an option to set this on our existing room (we've tried).
