### ISSUE TITLE
same as #2641 but with lists

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4529]
Reference #2641.

https://openlibrary.org/people/EshrektOgre/lists/OL104809L/Textbooks click on https://openlibrary.org/works/OL1027511W/Understanding_international_conflicts and you'll see the difference between what it looks like in the list to what it actually is for the cover image.

**Comment by mekarpeles** [comment]
Not planning on fixing this one; we don't have a good consensus on what would what would be better than what we're doing.
