### ISSUE TITLE
Linters are not running

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4537]
It looks like during the introduction of Vue (or some other event) we stopped applying the Open Library stylelint configuration file. This leads to inconsistent, hard to read code and adds unnecessary friction during the code review process.

Running 
```
npx stylelint ./**/*.less --config .stylelintrc.json
```
triggers various errors.

### Proposal & Constraints
- [x] Make sure the  .stylelintrc.json is applied in the existing lint rules.
- [x] Run npx stylelint ./**/*.less --config .stylelintrc.json --fix
- [x] Any errors that require manual intervention should be fixed
- [x] Spaces between properties and values and !important are fixed and enforced e.g. `background-color:@light-yellow!important; ` errors, and `background-color: @light-yellow !important; ` does not.
 - [x] Instances of #eee are replaced with @lightest-grey variable
- [x] We do not use      // stylelint-disable-next-line function-url-quotes 
- [x] donateModal is replaced with a BEM class

### Stakeholders
@cdrini @mekarpeles

**Comment by cdrini** [comment]
Is it the missing config? https://github.com/internetarchive/openlibrary/blob/master/package.json#L13

**Comment by jdlrobson** [comment]
No `npm run lint` does not work. I've not checked to see why it's not loading .stylelintrc.json

I agree it's odd per https://stylelint.io/user-guide/configure but perhaps for now we should explicitly pass it while we work that out.

**Comment by jdlrobson** [comment]
I think the issue here might be `static/css/components/.stylelintrc.json` which doesn't /extend/ the parent configuration.

**Comment by jdlrobson** [comment]
Yep, that looks like the culprit here!

**Comment by navneetsaluja** [comment]
@jdlrobson May I work on this? Since you've already figured out the problem in the first sub-issue, the solution would just be to [extend the parent configuration](https://stylelint.io/user-guide/configure#extends). Will also look at the other 2 sub-issues.

**Comment by jdlrobson** [comment]
Go ahead! Quicker we get this addressed the better. For now this should be our top priority.

**Comment by mekarpeles** [comment]
Thank you @navneetsaluja  + @jdlrobson

**Comment by jdlrobson** [comment]
🎉🎉🎉
