### ISSUE TITLE
New feature: exclude POD and ebook spam

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#454]
Certain "publishers" such as Kessinger and Literary Licensing have been polluting the commons, taking PD content, often from IA, slapping on a boilerplate intro, and selling it as copyrighted. OL should be able to exclude these "editions" from search results, either by default or at least as an easy option.

**Comment by tfmorris** [comment]
I hate Kessinger's with a passion, but if you're going to start censoring books, where do you draw the line?

The solution to this, in my opinion, is to have a robust Work fusion system and edition recommendatino system where the Kessinger "editions" will just naturally drift to the bottom of the rankings.

**Comment by LeadSongDog** [comment]
Censoring is what they attempt to do, in removing them from the public domain. What I'm suggesting is something closer to the "ebook only" button which is already present. Are there any examples where Kessinger publishes something that is not already available? I haven't been able to turn them up. They occasionaly mutate the title or  author spelling to make it more difficult to find the real work, but that's hardly creativity that needs to be protected from the "censor".

**Comment by mekarpeles** [comment]
I encourage us to find ways to increase the scale of our coverage and the accuracy of our metadata, but I think there are too many features which are critical to the use cases of our readers to focus on battling specific publishers.

If we're to accomplish our mission of one page for every book, it will benefit us to focus on thinking at scale and identifying systemic problems rather than philosophical ones.

I won't close the issue but I also cannot dedicate time to working on it (and I think there's low hanging fruit which will have greater impact to our end users -- those looking for books to read and cite).

**Comment by tfmorris** [comment]
Nothing is removed from the public domain. That is an impossibility.

**Comment by LeadSongDog** [comment]
Legal impossibility is not practical impossibility. See for instance: www.theregister.co.uk/2009/06/26/copy fraud/

**Comment by tapaswenipathak** [comment]
Hi folks: Is the ticket still open?

**Comment by guyjeangilles** [comment]
@tfmorris @mekarpeles can filtering out publishers be done via advanced search?

**Comment by seabelis** [comment]
I don't care for these types of publishers either, but I think of them as offering a 'service' similar to the copy shop when I was an undergraduate (pre-internet, pre-ebook). If a PD text was assigned, we could order the copy, printed and bound from the copy shop. Might be convenient for non-ebook users wanting an out-of-print text. I think I have occasionally seen them included in library collections on oclc.

**Comment by seabelis** [comment]
I would be in favour of checking amazon imports against oclc and importing only those items that exist in oclc.

**Comment by mekarpeles** [comment]
This doesn't seem like something we're planning on doing, in the interest of cleaning up our tracker, I'm closing.
