### ISSUE TITLE
Possible outdated Docker command to update JS and CSS

### ISSUE THREAD

**Issue by drakene** [internetarchive/openlibrary#4540]
The command below doesn't work on my Windows build for remaking CSS/JS assets. The "Home" container, in fact, shuts down after a short while of executing "docker-compose up."  

![possible_old_docker_command](https://user-images.githubusercontent.com/46735016/106904988-d00e7480-66c9-11eb-8b0b-ae53d44ec0df.png)  

However, on [Gitter](https://gitter.im/theopenlibrary/Lobby) Yash Saravgi @Yashs911 said that the home container shutting down is normal behavior and that the command to remake CSS assets was the following:  

    docker-compose exec web make css  
    docker-compose exec web make js  

I wanted to open an issue for this just in case there is either an problem on the wiki (which I would be willing to fix and make a pull request for if necessary) or if there is something going wrong on the Windows build. I'm still new, so it could be a mistake on my end. With that being said, Yash's solution works for me. Please let me know if I can make this issue more descriptive or neater for future reference!

### Relevant url?
https://github.com/internetarchive/openlibrary/blob/master/docker/README.md

### Steps to Reproduce

1. Get the local build up and running
2. Make some changes to CSS/JS
3. In terminal using working directory of local repo, type: docker-compose exec home npm run build-assets

### Outcome
* Actual: Output in terminal of "No container found for home_1"  
* Expected: Changes to CSS/JS that are reflected on local build following refresh of webpage.

### Details
 
- Firefox 
- Windows 10 Home 
- Local build

### Proposal & Constraints
Appropriate changes to the Docker README.md file using Yash Saravgi's suggestions.

**Comment by cdrini** [comment]
Ah, thanks @drakene ! Yeah, that's outdated. It should be `run --rm` instead of `exec`. I opened a PR #4541. Can you test the instructions and confirm they now work?

**Comment by drakene** [comment]
Using the branch you created, the instructions appear to work!
