### ISSUE TITLE
Getting a 403 Forbidden response

### ISSUE THREAD

**Issue by hgcl** [internetarchive/openlibrary#4543]
Hi! 

I have been using the Books API (in read mode only) to fetch the book info for [my personal bookshelf](clarale.com/books) — [code here if needed](https://github.com/hgcl/clara-website/blob/main/lib/getAllBooks.js). Everything was working fine until a few days ago, when I began to receive `403 Forbidden` responses.

### Evidence / Screenshot (if possible)

As a test, this is the URL I am trying to fetch:
https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data

The fetch is working fine in Postman and in the browser, but not from a [`fetch()`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) call from NextJS website.

This is the 403 response I get:

```js
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: Gunzip {
      _writeState: [Uint32Array],
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      bytesWritten: 0,
      _handle: [Zlib],
      _outBuffer: <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 33 20 46 6f 72 62 69 64 64 65 6e 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d ... 16334 more bytes>,
      _outOffset: 0,
      _chunkSize: 16384,
      _defaultFlushFlag: 2,
      _finishFlushFlag: 2,
      _defaultFullFlushFlag: 3,
      _info: undefined,
      _maxOutputLength: 4294967295,
      _level: -1,
      _strategy: 0,
      [Symbol(kCapture)]: false,
      [Symbol(kTransformState)]: [Object],
      [Symbol(kError)]: null
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data',
    status: 403,
    statusText: 'Forbidden',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
```

I am aware that 403s can happen for PUT/POST calls to edit books, but so far using the API without auth has worked, and I can't find any documentation pointing to 403s for GET calls.

Could this be related to any kind of rate limiting? Or did anything change in the API recently that could have caused this?

Thank you so much for your help!

### Details

- **Logged in (Y/N)?** N 
- **Browser type/version?** NodeJS
- **Operating system?** Mac OS 10.14.16
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Hi @hgcl ! Thanks for the bug report.

Hmmmm :/ We deployed a change to some of our CORS headers yesterday, but I tested this URL and it's got the right headers when hit from the browsers. I tried hitting it from node and got the error:


```js
> fetch('https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data').then(r => r.text()).then(j => console.log(j))
Promise { <pending> }
> <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

Confusingly enough, our staging server seems not to give the error :/

```js
> fetch('http://staging.openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data').then(r => r.text()).then(j => console.log(j))
Promise { <pending> }
> {"ISBN:2070464237": {"url": "http://staging.openlibrary.org/books/OL26210208M/La_Horde_du_Contrevent", "key": "/books/OL26210208M", "title": "La Horde du Contrevent", "authors": [{"url": "http://staging.openlibrary.org/authors/OL3980331A/Alain_Damasio", "name": "Alain Damasio"}], "number_of_pages": 736, "pagination": "700", "identifiers": {"goodreads": ["25135826"], "isbn_10": ["2070464237"], "isbn_13": ["9782070464234"], "openlibrary": ["OL26210208M"]}, "publishers": [{"name": "Gallimard"}], "publish_date": "2015", "cover": {"small": "https://covers.openlibrary.org/b/id/7891413-S.jpg", "medium": "https://covers.openlibrary.org/b/id/7891413-M.jpg", "large": "https://covers.openlibrary.org/b/id/7891413-L.jpg"}}}
```


Ok, let me see if the CORS headers are correct. Another possibility is HTTPS issues?

Yeah, CORS headers are missing, but not sure who's throwing the 403... :/ And the same code is on staging for this stuff.

```js
> fetch('https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data').then(r => console.log(r.headers))
Promise { <pending> }
> Headers {
  [Symbol(map)]: [Object: null prototype] {
    server: [ 'nginx/1.4.6 (Ubuntu)' ],
    date: [ 'Fri, 05 Feb 2021 18:22:31 GMT' ],
    'content-type': [ 'text/html' ],
    'transfer-encoding': [ 'chunked' ],
    connection: [ 'close' ],
    'content-encoding': [ 'gzip' ]
  }
}
> fetch('http://staging.openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data').then(r => console.log(r.headers))
Promise { <pending> }
> Headers {
  [Symbol(map)]: [Object: null prototype] {
    server: [ 'nginx/1.10.3 (Ubuntu)' ],
    date: [ 'Fri, 05 Feb 2021 18:22:59 GMT' ],
    'content-type': [ 'application/json' ],
    'transfer-encoding': [ 'chunked' ],
    connection: [ 'close' ],
    'access-control-allow-origin': [ '*' ],
    'access-control-allow-method': [ 'GET, OPTIONS' ],
    'access-control-max-age': [ '86400' ],
    'x-ol-stats': [ '"IB 1 0.035 MC 3 0.001 TT 0 0.040"' ]
  }
}
```

**Comment by cdrini** [comment]
@mekarpeles Also did some fiddling with our nginx version recently (timeline unknown); could that have affected it?

**Comment by cdrini** [comment]
Note it seems like all our APIs are affected :(

```js
> fetch('https://openlibrary.org/works/OL19710804W.json').then(r => console.log(r.status))
Promise { <pending> }
> 403
```

**Comment by cdrini** [comment]
Although note this is working for `curl` and for `python`, so seems like something related to node

```bash
$ curl 'https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data'
{"ISBN:2070464237": {"url": "https://openlibrary.org/books/OL26210208M/La_Horde_du_Contrevent", "key": "/books/OL26210208M", "title": "La Horde du Contrevent", "authors": [{"url": "https://openlibrary.org/authors/OL3980331A/Alain_Damasio", "name": "Alain Damasio"}], "number_of_pages": 736, "pagination": "700", "identifiers": {"goodreads": ["25135826"], "isbn_10": ["2070464237"], "isbn_13": ["9782070464234"], "openlibrary": ["OL26210208M"]}, "publishers": [{"name": "Gallimard"}], "publish_date": "2015", "cover": {"small": "https://covers.openlibrary.org/b/id/7891413-S.jpg", "medium": "https://covers.openlibrary.org/b/id/7891413-M.jpg", "large": "https://covers.openlibrary.org/b/id/7891413-L.jpg"}}}

$ python
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data').json()
{'ISBN:2070464237': {'url': 'https://openlibrary.org/books/OL26210208M/La_Horde_du_Contrevent', 'key': '/books/OL26210208M', 'title': 'La Horde du Contrevent', 'authors': [{'url': 'https://openlibrary.org/authors/OL3980331A/Alain_Damasio', 'name': 'Alain Damasio'}], 'number_of_pages': 736, 'pagination': '700', 'identifiers': {'goodreads': ['25135826'], 'isbn_10': ['2070464237'], 'isbn_13': ['9782070464234'], 'openlibrary': ['OL26210208M']}, 'publishers': [{'name': 'Gallimard'}], 'publish_date': '2015', 'cover': {'small': 'https://covers.openlibrary.org/b/id/7891413-S.jpg', 'medium': 'https://covers.openlibrary.org/b/id/7891413-M.jpg', 'large': 'https://covers.openlibrary.org/b/id/7891413-L.jpg'}}}
```

**Comment by cdrini** [comment]
@hgcl To clarify, the code [here](https://github.com/hgcl/clara-website/blob/main/lib/getAllBooks.js), is it running in the browser, or in node?

**Comment by cdrini** [comment]
Also: As a temporary fix while we figure this out, you can switch to making a request to `http://staging.openlibrary.org`.

**Comment by cdrini** [comment]
Also, if you have an idea of exactly when you first noticed this issue, that would help us a lot in pinning down what might have caused it :)

**Comment by cdrini** [comment]
Also tried using node's `http`; that seems to work (although doesn't support https):

```js
const http = require('http');
http.get('http://openlibrary.org/api/books?bibkeys=ISBN:2070464237&format=json&jscmd=data', res => { res.setEncoding('utf8'); let rawData = '';   res.on('data', (chunk) => { rawData += chunk; }); res.on('end', () => console.log(rawData)); })
```

**Comment by mekarpeles** [comment]
Hi all, this is intentional and my doing. We're getting hit by aws DDOS'ers and doing our best to ensure quality of service for patrons visiting the website, as well as re-enabling access to endpoints as we're able to responsibly able to. @hgcl your use case should now be unblocked, thank you for helping us tune this and apologies that you experienced this (APIs are core to what we do so it's with a heavy heart that we make any changes which may affect our developers, unless our staff is pressed for options).

I'll make a note on twitter as well so others are aware.

**Comment by grantsaylor** [comment]
Hi, when trying to access something like: https://openlibrary.org/isbn/9781250178602.json, you get a 404. Will this service be restored? This is essential to my application functionality. Thanks.

**Comment by atsmith14** [comment]
I'm having the same issue as @grantsaylor and this route is essential to my applications functionality as well.

**Comment by mekarpeles** [comment]
@grantsaylor + @atsmith14 can you help us understand what your apps may be doing and what IPs may be making this call so we can help white-label your services?

**Comment by grantsaylor** [comment]
My app uses google vision to scan ISBN numbers and then calls the API to return the JSON file so we can get data like book cover, author, title, pub date (it's a little library style app)

**Comment by hgcl** [comment]
> Hi all, this is intentional and my doing. We're getting hit by aws DDOS'ers and doing our best to ensure quality of service for patrons visiting the website, as well as re-enabling access to endpoints as we're able to responsibly able to. @hgcl your use case should now be unblocked, thank you for helping us tune this and apologies that you experienced this (APIs are core to what we do so it's with a heavy heart that we make any changes which may affect our developers, unless our staff is pressed for options).
> 
> I'll make a note on twitter as well so others are aware.

Thank you so much for the explanation @mekarpeles! I haven't had time to try it out again, but really appreciate you looking into it so quickly 🙏

**Comment by mekarpeles** [comment]
@grantsaylor very happy to make sure you're on the access list, is there any chance you can share the IP with me and we can make sure you get setup? mek@archive.org

**Comment by mekarpeles** [comment]
Closing as resolved; some sources are still being blocked due to high volume or abuse. Please write to us if you feel like this is being done in error and we will do our best to accommodate!
