### ISSUE TITLE
Rename "bodyid" to "cssfile"

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4546]
The `bodyid` was removed from its primary purpose in yesterday's deploy: https://github.com/internetarchive/openlibrary/compare/deploy-2021-01-25...deploy-2021-02-04#diff-5c48cb9056d50894674eef9b1074b2fd410dd462d90122050aa7cf26dafebcf5L8 , but there are still lots of places that _set_ the `bodyid`. Since this is no longer being used as the `bodyid`, let's rename it to something more appropriate. Namely `cssfile` seems reasonable.

Here is the main place it's used now: https://github.com/internetarchive/openlibrary/blob/1a2f38ad41d5662e880edcdbb759242dadd28375/openlibrary/templates/site/head.html#L25

References: https://github.com/internetarchive/openlibrary/search?q=%22bodyid%22

### Stakeholders

@Yashs911 @jdlrobson

**Comment by jdlrobson** [comment]
Not sure I'm understanding the problem here and what's unused. From what I can see these are used to define the stylesheet that is added to a page?

**Comment by cdrini** [comment]
Ahh, forgot about that. Then we need to rename it. This variable `bodyid` was called that because it would set the `id` of the `body`. It's no longer doing that. Let's rename it to... `cssfile`.

**Comment by Yashs911** [comment]
@cdrini I would like to work on this issue.

**Comment by mekarpeles** [comment]
Is this possibly related?
https://github.com/internetarchive/openlibrary/issues/4549

**Comment by Yashs911** [comment]
> Is this possibly related?
> #4549

No, #4549 is related to https://github.com/internetarchive/openlibrary/pull/4369
