### ISSUE TITLE
List widget appears always expanded on Books page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4549]
A regression (perhaps caused by a recent style, js, or markup change) is resulting in the List widget being always rendered as expended.

### Evidence / Screenshot (if possible)
![openlibrary org_books_OL26741076M_Dark_Matter](https://user-images.githubusercontent.com/978325/107117714-15998180-6831-11eb-9824-d33fe36d3fd3.png)

### Steps to Reproduce

1. Go to ... https://openlibrary.org/books/OL26741076M
2. Do ... look at where the list widget is (it will be expanded)

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Chrome 
- **Operating system?**  Linux
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jdlrobson @cdrini

**Comment by Yashs911** [comment]
@mek related to #4480

**Comment by Yashs911** [comment]
We can make a separate dropdown for Add to Existing List just like Want to Read.
or
something like this:
![image](https://user-images.githubusercontent.com/64412143/107120199-3524be80-68b2-11eb-9583-20494a25640a.png)

**Comment by jdlrobson** [comment]
@mek this is because of the recently resolved #3630.

Was that not wanted?

There was a pull request for several weeks.

**Comment by mekarpeles** [comment]
Should get resolved by #4552 which reverts #3630 as recommended in https://github.com/internetarchive/openlibrary/issues/3630#issuecomment-774583282

The reasoning (mostly miscommunication on my part) is described here:
https://github.com/internetarchive/openlibrary/issues/3630#issuecomment-774670797
