### ISSUE TITLE
"Random Book" option isn't

### ISSUE THREAD

**Issue by ayust** [internetarchive/openlibrary#4553]
The "random book" feature on the openlibrary.org site appears to not function as originally intended, and instead is only returning one of a small number of results for books with "available" or "lending" in their textual metadata (title, description, etc).

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/344766/107159376-68b02900-6944-11eb-9821-de30501f6b68.png)

### Relevant url

https://openlibrary.org/random

### Steps to Reproduce

1. Go to https://openlibrary.org/random repeatedly

* Actual: The resulting book pages seem to repeat quite frequently, and all have "lending" or "available" in the book title / subject / description.
* Expected: An actual random assortment of books from across the corpus.

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome / curl
- **Operating system?**  Windows / Linux
- **Environment (prod/dev/local)?** prod

### Related files

This functionality appears to be implemented here:
https://github.com/internetarchive/openlibrary/blob/8575acb2543143d9b7e2bd0f387dccaa4541835e/openlibrary/core/lending.py#L207

It looks like it is relying on the advanced search page to be able to provide a random selection from the corpus when invoked in a certain way, and it seems like the search implementation likely changed since this functionality was originally implemented, such that search is no longer honoring the flags this function is trying to send, and instead interpreting them as free text search terms (hence the bias towards "available" and "lending" topics in the non-random book result).

**Comment by pixeljava** [comment]
Hi... Just browsing around looking for a first good issue.
I'm not a python dev, but after taking a peek under the hood it looks like line 211 might hold some answers:
`               "+AND+(lending___available_to_borrow OR lending___available_to_browse)"`
Is it possible that these are being interpreted as the actual query string, causing the key words "lending", "available" "borrow" and "browse" to be interpreted as the search query?

**Comment by mekarpeles** [comment]
@ayust thank you for submitting this issue, you're right, there appears to be an issue!

@pixeljava thanks for looking into this! I'm not sure that's the problem in this case, but we can modify the actual archive.org query to see if changes result in the correct behavior -- please do try! <3

Removing Open Library from the equation, there does indeed appear to be something strange / problematic with the query itself (upstream):

http://archive.org/advancedsearch.php?q=_exists_:openlibrary_work+AND+(lending___available_to_borrow%20OR%20lending___available_to_browse)&fl=identifier,openlibrary_edition&output=json&rows=1&sort[]=random

cc: @ximm can you see based on this url / query why the same set of books may be returned across requests? Is it a problem with cache and perhaps all we need to do is e.g. add `&reCache=1` to the url?

**Comment by mekarpeles** [comment]
@pixeljava you're totally right, I believe in the query, we need to update the call to:

https://archive.org/advancedsearch.php?q=_exists_:openlibrary_work+AND+(lending___available_to_borrow:true%20OR%20lending___available_to_browse:true)&fl=identifier,openlibrary_edition&output=json&rows=1&sort[]=random

namely adding `:true` after `lending___available_to_browse` and `lending___available_to_borrow`.

Do you mind opening up a PR? :tada:

**Comment by dwaipayan05** [comment]
Can I follow the above given instructions and open up a PR ?

**Comment by pixeljava** [comment]
Yes, please do. I'm not a Python developer and I'd feel bad changing something without being able to thoroughly test it first.
