### ISSUE TITLE
/openlibrary/openlibrary/templates/lists/widget.html: error in processing template: TypeError: Object of type Nothing is not JSON serializable (falling back to default template)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4555]
Patron is reporting the following error:
`/openlibrary/openlibrary/templates/lists/widget.html: error in processing template: TypeError: Object of type Nothing is not JSON serializable (falling back to default template)`

### Relevant url?
https://openlibrary.org/works/OL24171550W/Kelebihan_Amalan_Bulan_Rejab_Sya%E2%80%99ban_Ramadhan

### Steps to Reproduce

1. Go to ... https://openlibrary.org/works/OL24171550W/Kelebihan_Amalan_Bulan_Rejab_Sya%E2%80%99ban_Ramadhan
2. Do ... view error.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
Unable to reproduce this issue on dev: https://dev.openlibrary.org/works/OL24171550W/Kelebihan_Amalan_Bulan_Rejab_Sya%E2%80%99ban_Ramadhan

**Comment by cclauss** [comment]
https://dev.openlibrary.org/status shows that it is running legacy Python 2.7.6
https://openlibrary.org/status shows that it is running Python 3.8.6

**Comment by cclauss** [comment]
Start up a local instance
```
docker exec -it openlibrary_web_1 /bin/bash
python3 scripts/copydocs.py /works/OL24171550W
```

**Comment by cdrini** [comment]
Note sure how many records this is affecting? Seems not super prevalent, setting to p3.

**Comment by LeadSongDog** [comment]
Looking at the edition json, it seems possible that the title:"Kelebihan Amalan Bulan Rejab, Sya\u2019ban & Ramadhan" is somehow problematic. The author name containing "Alias" is also suggestive, but not all the works by that author show the error.

**Comment by cclauss** [comment]
https://openlibrary.org/works/OL24171550W/Kelebihan_Amalan_Bulan_Rejab_Sya%E2%80%99ban_Ramadhan?debug=true  Looking down into the URL with `?debug=true` this looks to be `covers` related...

**Comment by LeadSongDog** [comment]
I notice that see the covers error only when logged in, but see the widgets error twice, whether logged in or out.

**Comment by hornc** [comment]
Hmm, this looks like it is the same Infogami `Nothing` I struggled with here https://github.com/internetarchive/infogami/issues/148
It doesn't quite behave like `None` , and a list of results containing it _looks_ empty like `[]` , but is not equal to `[]`
