### ISSUE TITLE
Issue with displaying https link in the wiki

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#457]
I've tried to change the http links in the [OL Dumps documentation][1] page to https and the links disappeared.

I've added a note in the [sandbox page][2] to demonstrate that issue.

[1]: https://openlibrary.org/developers/dumps
[2]: https://openlibrary.org/sandbox

**Comment by anandology** [comment]
Script reproduce the this issue.

```
from openlibrary.core.olmarkdown import OLMarkdown

text = """
http://openlibrary.org/
<http://openlibrary.org/>

https://openlibrary.org/
<https://openlibrary.org/>
"""

md = OLMarkdown(text)
print(md.convert())
```

Output:

```
<p><a href="http://openlibrary.org/" rel="nofollow">http://openlibrary.org/</a><br/>
   <a href="http://openlibrary.org/" rel="nofollow">http://openlibrary.org/</a>
</p>
<p><br/>
</p>
```

**Comment by LeadSongDog** [comment]
@anandology, at https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/importapi/import_opds.py#L20 
and at
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/importapi/import_rdf.py#L37
the "http" should be "https"
