### ISSUE TITLE
Book page: Editions Table "Listen" roll-over glitch

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4575]
increased width of "special access" text causes noticeable glitches in "Listen" roll-over in editions table

### Evidence / Screenshot (if possible)
![editions-glitch-20210211T130916](https://user-images.githubusercontent.com/978325/107699820-77138300-6c6b-11eb-8cf2-7c449d237e29.gif)

### Relevant url?

https://dev.openlibrary.org/books/OL1722731M/Influence

### Steps to Reproduce

1. Go to ... https://dev.openlibrary.org/books/OL1722731M/Influence
2. Do ... hover over the "Listen" section of the editions table buttons

* Actual: glitches
* Expected: don't glitch :sweat_smile: 

### Related files

macros.LoanStatus + macros.ReadButton + less

### Stakeholders

@jamesachamp, @cdrini, @Yashs911, @Sabreen-Parveen, @shivambhatia5432, @jdlrobson

**Comment by Yashs911** [comment]
@mekarpeles I would like to work on this issue.
