### ISSUE TITLE
Add Instagram/Whatsapp for Sharing

### ISSUE THREAD

**Issue by dwaipayan05** [internetarchive/openlibrary#4578]
Among the other Social Media links for sharing, can WhatsApp/Instagram be added as the crowd over there consists of a good number of book lovers.

### Describe the problem that you'd like solved

A Social Media Icon of Instagram/WhatsApp to be added in SocialShare.html which would allow the user to share the book through these. The image below is what the current social share window looks like.

![image](https://user-images.githubusercontent.com/53687927/107732324-15602100-6d1e-11eb-9c6c-0c5a17369eee.png)

**Comment by mekarpeles** [comment]
@dwaipayan05 we'd be open to Facebook, Twitter, and then a More icon which uses the `details` tag (see the Vendors "more") to list additional share options

**Comment by jdlrobson** [comment]
Please consider using  https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share and supporting whatever the user has installed on their phone and replacing these icons with a single unbiased-towards-a-single-platform share button.

**Comment by dbouris** [comment]
hi  @cdrini me and my colleague  @Philippos01 are interested in taking over this issue, both for Whatsapp and Instagram. Do you mind assigning it to us?  We have also considered using the Web Share API as @jdlrobson mentioned above

**Comment by cdrini** [comment]
Notes from discussion:
- Replace 4 share icons with single “[ICON] Share” button + modal
- Investigate where to integrate web share api; should just be one option in the modal?
- Need to keep “Embed” as an option – that’s our currently most clicked share button
- TODO: jimchamp get share icon to use

Seems like a good one @dbouris ! @jimchamp will help answer any questions :)
