### ISSUE TITLE
Address pep8 problems

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#458]
Catch-all issue for #193, #166, #354
cc: @tfmorris

**Comment by mekarpeles** [comment]
See branch refactor/pep8

**Comment by mekarpeles** [comment]
@tfmorris I got us started (above) -- would you like to take over some of this cleanup?

**Comment by tfmorris** [comment]
This is not something that I have the bandwidth to tackle, but I'd be happy to help figure out a good strategy (incremental by module, by subdirectory, all at once, by cleanup type, etc).

I'll also note that some of this was likely improved as part of our Python 3 port cleanup (which is higher priority since we only have 7 months left before the deadline).

**Comment by guyjeangilles** [comment]
@mekarpeles All the related PRs are merged, but the pep8 branch is stale. What's the status of this issue?

Also, @tfmorris @cclauss @salman-bhai has this/will this be addressed with the Python 3 updates?

**Comment by cclauss** [comment]
Just whack the whole codebase with __isort__ followed by __psf/black__.  Should just take a minute.

**Comment by guyjeangilles** [comment]
Defaulting to assigning @mekarpeles per slack discussions

**Comment by cclauss** [comment]
Trial run -- will change no files.
* isort --check-only -l 88 -sg "scripts/*" -sg "vendor/*" -rc .
* black --check --exclude "/(scripts|vendor)/" .

Actual run -- ___will modify files__
* isort -l 88 -sg "scripts/*" -sg "vendor/*" -rc .
* black --exclude "/(scripts|vendor)/" .

**Comment by mekarpeles** [comment]
@cclauss can I assign this one to you (you don't have to do it, just make it's tracked as something we may still need to do in our checklist)

**Comment by mekarpeles** [comment]
This appears to be resolved. Going to close and tagging @cclauss just in case I'm wrong
