### ISSUE TITLE
Admin Only feature visible on Edit Profile Page

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4581]
An Admin-only feature is visible to users  on the Edit profile page
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/107755215-874d6000-6d48-11eb-85a8-3d584b15aa69.png)

### Relevant url?

https://openlibrary.org/people/{username}?m=edit
### Steps to Reproduce

1. Go to My profile
2. Click Edit

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

**Comment by infern018** [comment]
@Yashs911  I would like to work on this issue, can you assign it to me?

**Comment by Yashs911** [comment]
> @Yashs911 I would like to work on this issue, can you assign it to me?

@infern018  Only Collaborators can assign issues, but you can go ahead and submit a PR. 
Ping me if you need any help.

**Comment by infern018** [comment]
@Yashs911  i am encountering some problem in setting up the project, does openlib has any slack or other channel for basic discussiosns

**Comment by jimchamp** [comment]
@homewardgamer is this an issue that you would be interested in?  I think that it's a pretty good first issue, and I'm happy to answer any questions that you may have.

**Comment by homewardgamer** [comment]
> @homewardgamer is this an issue that you would be interested in?  I think that it's a pretty good first issue, and I'm happy to answer any questions that you may have.

Yeah I will surely work on this Isssue! Thanks for assigning it to me @jimchamp .

**Comment by homewardgamer** [comment]
I have made the PR, Kindly review @jimchamp
