### ISSUE TITLE
Adding to lists broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4586]
Adding an item to a list no longer works as of 12-02-2021.

### Steps to Reproduce

1. Go to ...an edition, etc.
2. Do ...add item to list.

* Actual: List link loads list page.
* Expected: Item should be added to list.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 88.0.4324.150 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cclauss

**Comment by cdrini** [comment]
Seeing this error in the console:

![image](https://user-images.githubusercontent.com/6251786/107823265-7e12c200-6d4d-11eb-904a-1f516f7e6227.png)

**Comment by cdrini** [comment]
The issue was we were using `json_encode` inside lists/widget.html on an empty list `[]`. The code change caused `json_encode([])` to return `{}`, breaking the JS code.
