### ISSUE TITLE
Author and language not saved after edit

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4587]
Edits to edition language or work authors fail to save.

### Steps to Reproduce

1. Go to ...any edition, for example https://openlibrary.org/books/OL31954710M/The_Treaty_with_China
2. Do ...add a language from the dropdown, add an author to work.

* Actual: After save, the changes to author and edition should be retained.
* Expected: Language, author fields are blank.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 88.0.4324.150 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cclauss

**Comment by cdrini** [comment]
Likely caused by #2734

**Comment by cdrini** [comment]
Repro'd the autocomplete bug on staging; I'm going to open a revert PR and put it on staging to see if that fixes it

**Comment by cdrini** [comment]
It did! Will deploy shortly.
