### ISSUE TITLE
/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: MemcachedKeyCharacterError: Control/space characters not allowed (key=b'gt-availability-"Les Aventures de Tom Sawyer"') (falling back to default template)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4588]
Error message after saving new edition:
/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: MemcachedKeyCharacterError: Control/space characters not allowed (key=b'gt-availability-"Les Aventures de Tom Sawyer"') (falling back to default template)

### Relevant url?
https://openlibrary.org/books/OL31954808M/Les_Aventures_de_Tom_Sawyer

### Steps to Reproduce

Added this new edition, but this error was not occurring for previous adds.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 88.0.4324.150 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Noticed there were spaces in the ocaid, removed ocaid and re-testing.

https://openlibrary.org/books/OL31954808M

Fixed!
