### ISSUE TITLE
Related books carousels never stop loading

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4592]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/107835119-6bf14d80-6d66-11eb-81fd-0f46892841a1.png)

### Relevant url?
e.g. https://openlibrary.org/works/OL9489809W/The_Mysterious_Uni-verse?edition=

### Steps to Reproduce

* Actual: Loading indicator always there
* Expected: Carousels should appear at some point

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF85
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@tabshaikh @jamesachamp @Yashs911 @jdlrobson

**Comment by dwaipayan05** [comment]
I wanted to get an idea about something in this issue, Over here in openlibrary/openlibrary/plugins/openlibrary/js/carousels_partials.js /

`data: {
                workid: $('.RelatedWorksCarousel').data('workId'),
                _component: 'RelatedWorkCarousel'
            },`
 What does the _component refer to actually ?

**Comment by Yashs911** [comment]
@jamesachamp Is this issue related to https://github.com/internetarchive/openlibrary/pull/4007 ?

**Comment by jamesachamp** [comment]
@Yashs911 Not really.  Please refer to my comments in #4623 for the root cause.
