### ISSUE TITLE
[My Library] List items under creator does not properly capitalize Unicode characters

### ISSUE THREAD

**Issue by dotMavriQ** [internetarchive/openlibrary#4602]
![https://i.imgur.com/TiC5CCh.png](https://i.imgur.com/TiC5CCh.png)
### Steps to Reproduce

1. Create a list item that uses Unicode characters such as ÅÄÖ
2. View it from "My Uploads" when logged in as a user.

* Actual: The letters that are not in the ASCII character set are capitalized where they should not be.
* Expected: I expected capitalization to be correct. 

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** LibreWolf 5.0 (64-bit)
- **Operating system?** 
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2
Kernel Version: 5.10.15-1-MANJARO
OS Type: 64-bit
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NV137
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Hopefully, the fix is minor and pertains to perks when parsing non-ASCII Unicode characters.

**Comment by infern018** [comment]
I would like to work on this issue, can you tell me where can I find this search by creator section , or the relevant URL where this issue is showing up?

**Comment by dotMavriQ** [comment]
> I would like to work on this issue, can you tell me where can I find this search by creator section , or the relevant URL where this issue is showing up?

https://archive.org/details/@dotmavriq 

I can find it here in an entry I have myself made containing the letter `å` under Creator. 

`<h5><button data-toggle="collapse" data-target=".facet_creator" aria-expanded="false" role="button" aria-controls="facet_creator" class="collapsed">Creator</button><span class="hidden-xs">Creator</span><a href="/details/@dotmavriq&amp;morf=-creator" class="js-more-facets-click" data-switchtoalpha="-creator"><img class="filter-" data-toggle="tooltip" src="/images/filter-count.png" title="" alt="Show sorted alphabetically" data-original-title="Show sorted alphabetically"></a></h5>`

**Comment by infern018** [comment]
where can I find the code for archive.org profile section, I know about "openlibrary.org" site code, but was not able to figure out for the first one

**Comment by cclauss** [comment]
% python3
```
>>> s = "Â Üñîçø∂é String"

>>> s.lower()
'â üñîçø∂é string'

>>> s.upper()
'Â ÜÑÎÇØ∂É STRING'

>>> s.title()
'Â Üñîçø∂É String'
```

**Comment by mekarpeles** [comment]
We've passed this on to @bfalling who runs the Archive.org team -- since this isn't a bug on OpenLibrary.org, we're going to close the issue here. Thank you for reporting!
