### ISSUE TITLE
siteSearch is id but being continuously used in the same page 

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#4619]
Problem : Making code refined, 
There are many files where i found id siteSearch, I want to report a file which have more that one instance of it

/openlibrary/templates/stats/readinglog.html

so I want to know if its better to change the id to class or better to create a new class for the readinglog.html file

There are many files with id siteSearch and many files with class siteSearch 

I think it will be better to change the id to class with some other name 

 
### Stakeholders

@jdlrobson

**Comment by jdlrobson** [comment]
I would suggest removing the ID `#siteSearch` and replacing any instances  styling the #siteSearch selector with .list-books. Best to leave `.siteSearch` as is for now.

**Comment by ArunTeltia** [comment]
Working on the pr
