### ISSUE TITLE
2021-01 datadumps smaller than expected (missing data?)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4621]
Related to #4671, #4723

Looks like archives for January 31 2021 are much smaller than usually comparing to months past. Is it possible to re-upload them with missing data?

https://archive.org/download/ol_dump_2021-01-31

Past months which is what the sizes are typically:

https://archive.org/download/ol_dump_2020-12-31
https://archive.org/download/ol_dump_2020-11-30

- [ ] Compare 2020 dumps vs. 2021 dumps
    - [ ] Similar filenames
    - [ ] Similar file sizes
    - [ ] Similar file contents
- [ ] Ensure that rsync runs properly on the end-of-March 2021 transfer

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by hornc** [comment]
@mekarpeles @cclauss 

I just got burned by this issue when downloading the Feb dumps from https://archive.org/download/ol_dump_2021-02-28

I was looking to update the orphaned edition counts, that data shows 4M, which is double the last proper count. That gave me a scare :)

The data looks like it is simply out of date, the most recent last modified date in the editions dump is `2019-03`, which matches the orphan count from then. I'm not sure where this 2019 data is being pulled from, but hopefully that'll make it easier for you to track down.

**Comment by cclauss** [comment]
This issue was fixed in https://archive.org/download/ol_dump_2021-03-19 but let's leave it until the April 1st dump.

**Comment by hornc** [comment]
@cclauss , did you see my comments in slack that this latest dump has some old versions of some items?
Checking for orphaned editions shows that there are 300K more orphans than the last dump, but I think this is due to bad data in the dump.

An example is this edition, currently at a `v=2` since 2009, but is in the dump with latest version `v=1`
e.g. https://openlibrary.org/books/OL10003370M/Discussion_Paper_On_Registration_Of_Rights_In_Security_By_Companies

Here's another one that is one version behind in the data dump: /books/OL10024097M  `v=3` in the dump vs. `v=4` on the site

Many / (most?) of the entries in the data dump have the current version data. e.g. /books/OL10002616M  , `v=4` in the data, `v=4` on the live site

**Comment by tfmorris** [comment]
Is the Dec 2020 dump known to be complete? When is the last known good dump?

**Comment by cdrini** [comment]
Yes, that's the last known correct dump.

**Comment by cclauss** [comment]
I will have time to work on this again in my morning based on what we discovered in our last discussion.

**Comment by cdrini** [comment]
Awesome! Thank you, @cclauss !

**Comment by cdrini** [comment]
Status update: With the PR above merged, the split records @cclauss ran on the 03-19 dump do look to be the correct size! Or very similar anyways:

```
9.2G    ol_dump_2021-03-19.txt.gz
4.0K    ol_dump_2021-03-19_files.xml
4.0K    ol_dump_2021-03-19_meta.xml
355M    ol_dump_authors_2021-03-19.txt.gz
6.6G    ol_dump_editions_2021-03-19.txt.gz
26M     ol_dump_redirects_2021-03-19.txt.gz
2.0G    ol_dump_works_2021-03-19.txt.gz
```

Going to try running the full flow to see if it works!

```sh
export COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml"
docker-compose run cron-jobs bash
# ---
su openlibrary
export SCRIPTS=/openlibrary/scripts
cd /1/var/tmp
time /olsystem/bin/cron/oldump.sh ol-db1 openlibrary `date -d 'yesterday' + '\%Y-\%m-\%d'` --archive
```

And now we wait...

**Comment by cdrini** [comment]
Failed because the fix hadn't been deployed -\_- . Also it tried to save to `ol_dump_--archive` for some ridiculous reason? Let's try again.

I think `%` is a special character in a cron file, which doesn't work in native bash; tweaked the date command to work. Trying this now:
```sh
COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml" docker-compose run \
    -u openlibrary \
    -e "SCRIPTS=/openlibrary/scripts" \
    cron-jobs \
   bash
# ---
curl 'https://github.com/internetarchive/openlibrary/commit/71dc678ec1e1b6d9a1b4bd53595c4d2f00c45031.diff' | git apply
cd /1/var/tmp cron-jobs
/olsystem/bin/cron/oldump.sh ol-db1 openlibrary `date -d yesterday '+%Y-%m-%d'` --archive
```

Wait once more...

**Comment by cdrini** [comment]
Ok! Done; they look about the right size again; uploading failed because I forgot to set the hostname :/

```
openlibrary@a4aa495d634e:/1/var/tmp/dumps/ol_dump_2021-04-12$ du -sh *.txt.gz
9.2G    ol_dump_2021-04-12.txt.gz
357M    ol_dump_authors_2021-04-12.txt.gz
6.6G    ol_dump_editions_2021-04-12.txt.gz
27M     ol_dump_redirects_2021-04-12.txt.gz
2.0G    ol_dump_works_2021-04-12.txt.gz
```

Here's the commands I used to re-upload. Note Hank had to delete the failed runs in order for the IDs to be available

```sh
COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml" \
HOSTNAME="$HOSTNAME" \
docker-compose run \
    -u openlibrary \
    -e "SCRIPTS=/openlibrary/scripts" \
    cron-jobs \
    bash
# ---
cd /1/var/tmp/dumps
python /olsystem/bin/uploaditem.py ol_dump_2021-04-12 --nowait --uploader=xxx@xxx.org
python /olsystem/bin/uploaditem.py ol_cdump_2021-04-12 --nowait --uploader=xxx@xxx.org
```

They should show up at https://archive.org/details/ol_dump_2021-04-12 and https://archive.org/details/ol_cdump_2021-04-12 once it's done.

**Comment by cclauss** [comment]
Thanks MASSIVELY!!!

**Comment by cdrini** [comment]
Aaand upload complete! If folks want to take a look to verify: https://archive.org/details/ol_dump_2021-04-12 and https://archive.org/details/ol_cdump_2021-04-12 .

I'll close this issue after my solr run is complete—that'll spit out some errors if references are missing.

**Comment by cdrini** [comment]
Stats from latest dump:


Type | count
-- | --
/type/about | 1
/type/author | 8426018
/type/backreference | 7
/type/collection | 3
/type/delete | 1235931
/type/doc | 9
/type/edition | 30100361
/type/home | 11
/type/i18n | 966
/type/i18n_page | 15
/type/language | 467
/type/library | 325
/type/local_id | 7
/type/macro | 126
/type/object | 3
/type/page | 274
/type/permission | 10
/type/place | 1
/type/rawtext | 47
/type/redirect | 718712
/type/scan_location | 1
/type/scan_record | 2
/type/series | 3
/type/subject | 91400
/type/template | 300
/type/type | 47
/type/uri | 1
/type/user | 2
/type/usergroup | 14
/type/volume | 107
/type/work | 22127655

Orphans: 2310485


Solr reindexing completed without a hitch! So dump looks good :+1: Closing this issue.
