### ISSUE TITLE
"Less" facet not visible on Search Result page

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4625]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/108300236-fd791900-71c5-11eb-8ac0-7266136e67a4.png)
### Relevant url?

https://openlibrary.org/search?q=Mark&mode=ebooks&has_fulltext=true
### Steps to Reproduce

1. Go to https://openlibrary.org/search?q=Mark&mode=ebooks&has_fulltext=true
2. Click "more"

* Actual: less not visible
* Expected: both more and less should be visible

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by dwaipayan05** [comment]
It's visible on my Windows Machine, can someone confirm the reproducibility of this issue ?

**Comment by Yashs911** [comment]
> It's visible on my Windows Machine, can someone confirm the reproducibility of this issue ?

@dwaipayan05 Currently, it's visible, but when we merge https://github.com/internetarchive/openlibrary/pull/4623, it won't be.
