### ISSUE TITLE
2020 IA Performance Reviews

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4657]
We should have received self-review forms from BZ; and then we need to sync and peer-review one another.

**Comment by cclauss** [comment]
### Employee input completed:
* [x] @cclauss 
* [ ] @cdrini 
* [ ] @mekarpeles 
### Performance Review completed:
* [ ] @cclauss 
* [ ] @cdrini 
* [ ] @mekarpeles
