### ISSUE TITLE
DRY Sort options on search/authors page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4662]
The sort options on the search and authors page are duplicated (and out of sync!)

- https://openlibrary.org/search?q=hello&mode=everything
- https://openlibrary.org/authors/OL123779A/Ernest_Hello

## Summary of Requirements
- [ ] Create a new template (in an appropriate location): Maybe `sort_options.html`. **Use the code in `work_search.html`**
- [ ] Replace the sorting code in `work_search.html` with `$:render_template("sort_options.html")`
- [ ] Replace the sorting code in `type/author/view.html` with `$:render_template("sort_options.html", exclude=('relevance'), default='editions')`

Note: This will make the new "Random" sort options available on author pages!

## Stakeholders
@Yashs911

**Comment by lephemere** [comment]
How do we deal with the `Relevance` sorting options for the author's list of works? What makes a work more relevant than an other one?

**Comment by cdrini** [comment]
Good question! Let's add some options to the template; so for example we could do `$:render_template("sort_options.html", exclude=('relevance'), selected='editions')` on the authors pages.

**Comment by Yashs911** [comment]
@cdrini I will create a PR as soon as I am done with my exams (by the end of next week) :)
