### ISSUE TITLE
IA Toolbar gone missing!

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4665]
### Evidence / Screenshot (if possible)
Where did it go?
![image](https://user-images.githubusercontent.com/6251786/108897981-a9669e00-75e4-11eb-9715-ca3a9a73246e.png)

### Relevant url?
https://openlibrary.org

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF85
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Related files
Seems like caused by this commit: https://github.com/internetarchive/openlibrary/commit/55a6a3974b6f5ee6efa2e498dee69ef33bb46303

### Stakeholders
@jdlrobson @drakene

**Comment by jdlrobson** [comment]
Which toolbar are you referring to? Are you referring to the "view book on archive.org" in the screenshot or something else?

Is the HTML for this toolbar in the DOM and hidden via CSS or missing entirely?

> Seems like caused by this commit: 55a6a39

Did you do a git blame to confirm this, or is this a guess based on recent changes?
I'm not sure how a change to the covers HTML could impact anything on the given Relevant url (homepage)


I should have some bandwidth to look at this today with some further informaiton.

**Comment by jdlrobson** [comment]
I'm guessing this is what you mean?:

<img width="914" alt="Screen Shot 2021-02-23 at 12 08 12 PM" src="https://user-images.githubusercontent.com/148752/108901510-ce9ce180-75cf-11eb-8678-fe3dfc67f02e.png">

Running a git bisect now to see when this happened...

**Comment by tfmorris** [comment]
I like the new look. Much cleaner than having two different "top" bars.

**Comment by cdrini** [comment]
Yep that's the one. I added a temporary shim to production until we get a proper fix.

```html
<style>#topNotice { display: block !important; }</style>
```

**Comment by jdlrobson** [comment]
Yep can confirm that 55a6a3974b6f5ee6efa2e498dee69ef33bb46303 is the problem here (with git bisect)

The line here is the problem:
https://github.com/internetarchive/openlibrary/commit/55a6a3974b6f5ee6efa2e498dee69ef33bb46303

**Comment by jdlrobson** [comment]
Pushed fix. The line is no longer needed so yay to identifying and getting rid of more unnecessary cruft.
