### ISSUE TITLE
covers.openlibrary.org should hit archive.org/download

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4672]
Subtask of #3399
Closes #3399 

We can pretty decently simplify our covers.openlibrary.org code, as well remove 1 network request to IA for each cover image, by using the archive.org/download endpoint instead of the server-specific url.

This code: 

https://github.com/internetarchive/openlibrary/blob/ba0b052a64dc3e20d4014743778741bb6ecea874/openlibrary/coverstore/code.py#L191-L196

Makes a request to IA to determine the `server`; we can essentially replace this with just `%(protocol)s://archive.org/download/%(item)s/%(item)s.zip/%(filename)s` (e.g. https://archive.org/download/olcovers259/olcovers259.zip/2598178.jpg ).

This will let us delete the `locate_item` code, which will remove a network request and speed things up (\o/). This will also close #3399 , since the /download endpoint is CORS-enabled.

### Summary of Requirements
- [ ] `zipview_url` is updated to the new url format (above)
- [ ] `zipview_url` no longer calls `locate_item`
- [ ] `locate_item` (and friends) deleted if not used anywhere else

### Stakeholder
@jamesachamp

**Comment by cdrini** [comment]
Would you be interested in trying this one, @jamesachamp ? Should have a decent impact on performance!

**Comment by jamesachamp** [comment]
I'll take it up.
