### ISSUE TITLE
Work search - Sort by first published displays work with no publication date first

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#4673]
When searching for a work and sorting by `First Published`, if some works match the search and have no first publication date, they appear first.
I expected to see works with known first published year first and not pages later.

### Evidence / Screenshot (if possible)
n/a

### Relevant url?

For example: https://openlibrary.org/search?q=calamity&mode=everything&sort=old

### Steps to Reproduce

1. Search for `calamity` in the search bar (https://openlibrary.org/search?q=calamity&mode=everything)
2. Sort by `First Published` (https://openlibrary.org/search?q=calamity&mode=everything&sort=old)

* Actual: First result is `The Mount Rushmore Calamity by Jeff Brown` with no publication date
* Expected:  `A theatre wherein be represented as wel the miseries & calamities that follow the voluptuous worldlings by Noot, Jan van der`, first published in 1569 and only displayed on page 2 of the search

### Details

- **Logged in (Y/N)?** No
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

When sorting by publication date (`First Published` or `Most Recent`), works with no publication date should be the last results displayed.

**Comment by Evazisouli** [comment]
Hi @cdrini! Is this a good issue to contribute in as a new contributor?

**Comment by lephemere** [comment]
@evazisouli, as a new contributor you should probably check issues tagged [Good First Issue](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) for a starter.

**Comment by lephemere** [comment]
If you are interested in this issue, here below are some information I gathered, as I already had some thoughts on this matter:
- Current version of Apache Solr is 3.6.2.
- As per [Solr 4.0.0 Release Note](https://solr.apache.org/docs/4_0_0/changes/Changes.html), it seems that query sort options were quite limited before version 4.
- Currently, issue #3317 is in progress to upgrade Solr to version 8.
- As per [Solr 8.1 Ref Guide](https://solr.apache.org/guide/8_1/query-syntax-and-parsing.html), we should have more features to play around with. I was thinking of using function queries to tackle this issue.

**Comment by Evazisouli** [comment]
@lephemere thanks for your advice! I'll start with another issue first, in order to get familiar with the whole process.
