### ISSUE TITLE
Translate /subjects to Spanish

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4675]
Subtask of: #4677

We can translate these pages to other language thanks to `/type/i18n_page`! Just go to https://openlibrary.org/subjects.es?m=edit . If you don't have permissions, please comment with your OL username, and I'll see what I can do :)

NOTE: This is kind of annoying in that ideally we'd want to #2819 , which would give us the ability to store translated titles on the subject itself. But that's far away unfortunately, and in this seems good enough in the interm, and will provide a lot of value to non-English users. We will also be able to copy over the translations from this page once #2819 is complete, so no one's work is wasted.

### Stakeholders
@dcapillae

**Comment by dcapillae** [comment]
Great! Thanks, @cdrini.

Spanish translation in progress...

**Comment by dcapillae** [comment]
A first [Spanish translation](https://openlibrary.org/subjects.es?v=3) is now available.

**Comment by cdrini** [comment]
Wonderful, thank you @dcapillae !
