### ISSUE TITLE
Translate /subjects to French

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4676]
Subtask of: #4677

We can translate these pages to other language thanks to `/type/i18n_page`! Just go to https://openlibrary.org/subjects.fr?m=edit . If you don't have permissions, please comment with your OL username, and I'll see what I can do :)

NOTE: This is kind of annoying in that ideally we'd want to #2819 , which would give us the ability to store translated titles on the subject itself. But that's far away unfortunately, and in this seems good enough in the interm, and will provide a lot of value to non-English users. We will also be able to copy over the translations from this page once #2819 is complete, so no one's work is wasted.

### Stakeholders
@lephemere

**Comment by lephemere** [comment]
I got a permission denied. My OL username is `lephemere`.

**Comment by cdrini** [comment]
@lephemere Ok! You should have perms now :+1:

**Comment by lephemere** [comment]
@cdrini It works! I'll start with the translation.

**Comment by lephemere** [comment]
I have published the french translation.

**Comment by cdrini** [comment]
Awesome, thank you @lephemere !
