### ISSUE TITLE
Translate /subjects to Croatian

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4679]
Subtask of: #4677

We can translate these pages to other language thanks to `/type/i18n_page`! Just go to https://openlibrary.org/subjects.hr?m=edit . If you don't have permissions, please comment with your OL username, and I'll see what I can do :)

NOTE: This is kind of annoying in that ideally we'd want to #2819 , which would give us the ability to store translated titles on the subject itself. But that's far away unfortunately, and in this seems good enough in the interm, and will provide a lot of value to non-English users. We will also be able to copy over the translations from this page once #2819 is complete, so no one's work is wasted.

### Stakeholders
@milotype

**Comment by cdrini** [comment]
@milotype Ok! You know have permissions to edit :+1: https://openlibrary.org/subjects.hr?m=edit You have to translate the bits in between the tags; eg:

`<h3>Arts</h3>` -> `<h3>ARTS_IN_HR</h3>`, or

`<li> <a href="/subjects/history_of_art__art__design_styles">Art History</a> </li>` -> `<li> <a href="/subjects/history_of_art__art__design_styles">ART_HISTORY_IN_HR</a> </li>`.

Let me know if you have any questions!

**Comment by milotype** [comment]
@cdrini Hmmm ... nope, it doesn't work. I get a "Permission denied to edit /subjects.hr." :-(

**Comment by cdrini** [comment]
Ooops! My bad; I missed a piece. Can you try again?

**Comment by milotype** [comment]
Yes, it works now! Thank you.

**Comment by cdrini** [comment]
Woohoo! That looks great :) Closing this issue :+1: Thanks @milotype !

**Comment by milotype** [comment]
@cdrini Now the next step would be to use the translated strings on the homepage as well ;-) 
See screenshot

![Subject](https://user-images.githubusercontent.com/43657314/124259736-2378d780-db2f-11eb-9157-2abb85fedac3.png)
