### ISSUE TITLE
Coverserver internal server error

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4680]
> Hello, My name is [REDACTED], Library System Administrator, from Statistics Canada Library. I am writing to you because I recently discovered that the book cover images from Open Library on our OPAC didn't display properly. I contacted our vendor but they told us that the error was from your side and I have to contact you directly. Can anyone look into this issue and let me know what happened and how to fix it, please?

### Evidence / Screenshot (if possible)
https://covers.openlibrary.org/b/isbn/9780660209135-M.jpg

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
That isbn doesn't exist in our catalog: https://openlibrary.org/isbn/9780660209135

**Comment by jamesachamp** [comment]
It should return `empty.gif` if no image is found:
https://github.com/internetarchive/openlibrary/blob/fd5dbb02937f7db80a1f90ef898c2f7edc35c83a/conf/coverstore.yml#L9

If the above configuration is missing, the API call will return a `404` error.  If there is no `empty.gif`, a `500` error is returned and there will be `FileNotFoundError`s in the covers server logs.

**Comment by cdrini** [comment]
Ahhh, I think we had the wrong path here after our py3/docker migration. Opened a PR in olsystem to fix.

**Comment by cdrini** [comment]
Fixed, and patch deployed for testing. Working now! Here's the diff

```diff
-default_image: "/opt/openlibrary/openlibrary/static/images/empty.gif"
+default_image: "/openlibrary/static/images/empty.gif"
```
