### ISSUE TITLE
Multiple menus can be open in the header at the same time

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4686]
@mekarpeles apologies for missing this in code review. Should probably be fixed prior to next deploy. With the recent changes to improve our menus for non-JavaScript users we introduced a new usability feature for JS users.

Luckily this can  be rectified with a few lines of JS.

### Evidence / Screenshot (if possible)
<img width="946" alt="Screen Shot 2021-02-27 at 3 49 01 PM" src="https://user-images.githubusercontent.com/148752/109403643-5148d800-7913-11eb-940e-21300afa9bb3.png">

### Relevant url?
http://localhost

### Steps to Reproduce

1. go to home page
2. click hamburger
3. click browser
4. etc... 

* Actual: 
* Expected: Opening one menu should close the others.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
:+1: Thanks @jdlrobson I'll try out the PR, and if it's not working I'll do a revert so we can deploy tomorrow :+1: (double heads up, cc @cclauss :) )
