### ISSUE TITLE
cron-jobs service stuck in restart loop

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4707]
Running `docker container ls` on `ol-home0` reveals that the cron-jobs service is stuck in a restart loop. Note docker containers need their `command` to be long-running, so maybe the cron docker service is only _starting_ the cron service, but not "hanging" on it?

**Comment by cclauss** [comment]
In #4387 we used [`command: cron -f`](https://github.com/internetarchive/openlibrary/blob/master/docker-compose.production.yml#L64) to run `cron` in the foreground to make it a long-running process but perhaps we need to do more.
* https://stackoverflow.com/search?q=cron+jobs+in+docker+container
* https://medium.com/@jonbaldie/how-to-run-cron-jobs-inside-docker-containers-26964315b582
* https://ypereirareis.github.io/blog/2020/04/09/running-cron-jobs-docker-container-definitive-guide

**Comment by cdrini** [comment]
Hmm :/ Do the logs reveal anything useful?

**Comment by cclauss** [comment]
```
docker logs --tail=10 openlibrary_cron-jobs_1
cron: can't open or create /var/run/crond.pid: Permission denied
cron: can't open or create /var/run/crond.pid: Permission denied
...
```

**Comment by cclauss** [comment]
1. Try `user: root` in `docker-compose.production.yml`
```
COMPOSE_FILE="docker-compose.yml:docker-compose.production.yml" docker-compose up -d --no-deps cron-jobs
docker logs --tail=10 openlibrary_cron-jobs_1  # no output...
```
