### ISSUE TITLE
Barcodescanner should default to single scan

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4708]
Barcodescanner should have a checkbox to toggle scan many vs scan and jump to book page. Maybe something like "[ ] Scan Multiple Books" at the bottom. It should default to being unchecked.

For the single-scan option, how it should work is:
* if 2 consecutive scans result in the same ISBN...
* check the isbn on Open Library and see if it exists
* If so, use js to redirect patron to this book page

### Stakeholders
@mekarpeles

**Comment by finnless** [comment]
If in bulk scan mode there should be an option to append all scanned books to a book list. This would significantly speed up the scanning process for batches.

**Comment by cdrini** [comment]
Created an issue for that here: #4728

**Comment by nynaalekhya** [comment]
@mekarpeles Could I work on this issue

**Comment by mekarpeles** [comment]
I believe @Sabreen-Parveen was interested in trying this issue (Sabreen, can you confirm here on this thread so the UI will let me assign the issue to you?) -- @nynaalekhya there's another improvement to the barcode scanner #4728 which we'd love your help with, if you're willing!

**Comment by Sabreen-Parveen** [comment]
> I believe @Sabreen-Parveen was interested in trying this issue (Sabreen, can you confirm here on this thread so the UI will let me assign the issue to you?) -- @nynaalekhya there's another improvement to the barcode scanner #4728 which we'd love your help with, if you're willing!

Yes @mekarpeles, I am interested in working on this issue, it would be great if you would assign this to me :)

**Comment by nynaalekhya** [comment]
Hi @mekarpeles 😄 
I have completed working on this issue since the issue has not been claimed on this thread.

**Comment by LeadSongDog** [comment]
@nynaalekhya 
Q: when there are multiple scans of a single EAN-13 barcode, do you screen out those with invalid checksums before looking for consistency of result?

**Comment by jamesachamp** [comment]
We're using [quaggaJS](https://serratus.github.io/quaggaJS/#tipsandtricks) to scan and decode barcodes.  All checksum validation is handled by this library.

**Comment by tuminzee** [comment]
@LeadSongDog are you interested in working on this issue?

**Comment by LeadSongDog** [comment]
@tuminzee 
Happy to participate in discussions of goals, but my coding days are far behind me. I never really made the switch to OOP, let alone py. I’m a dinosaur.

**Comment by tuminzee** [comment]
Haha, coding could be overwhelming sometimes 😃 
Still I would like to thank you for your interaction, it added clarity to the issue :)
