### ISSUE TITLE
Book title ("link") and Cover name missing

### ISSUE THREAD

**Issue by Romi-776** [internetarchive/openlibrary#4711]
The name of the book which is also a link to that book is missing and the cover is also not giving information about the name of the book.

### Evidence / Screenshot (if possible)
![Screenshot from 2021-03-02 08-14-47](https://user-images.githubusercontent.com/53464933/109588902-7f0a6880-7b2f-11eb-9547-02ff326dcc52.png)

### Relevant url?

https://openlibrary.org/works/OL5735360W/Catching_Fire_%28The_Hunger_Games_2%29?edition=catchingfire00coll

### Steps to Reproduce

1. Go to https://openlibrary.org/works/OL5735360W/Catching_Fire_%28The_Hunger_Games_2%29?edition=catchingfire00coll
2. Scroll downwards to view 18 editions section.
3. Select "Show All entries".
4. On book no. 10 you'll notice this bug.

* Actual: **Above Image.**
* Expected: 
![Screenshot from 2021-03-02 08-34-41](https://user-images.githubusercontent.com/53464933/109590564-3607e380-7b32-11eb-8f46-a9ad2c74447e.png)

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

**Comment by Romi-776** [comment]
@mekarpeles , @cdrini Can anyone point me in the right direction in order to fix this?

**Comment by cdrini** [comment]
Strange! It looks like someone had edited the record and removed its title :P I just edited it now and added it back. https://openlibrary.org/books/OL23614051M/Catching_Fire?_compare=Comparer&b=19&a=18&m=diff
