### ISSUE TITLE
Unexpected token b in JSON at position 0

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4720]
Error message: Unexpected token b in JSON at position 0

### Relevant url?
http://staging.openlibrary.org/works/merge?records=OL15235105W,OL15524485W,OL88547W

### Steps to Reproduce

1. Go to ...http://staging.openlibrary.org/works/merge?records=OL15235105W,OL15524485W,OL88547W
2. Do ...merge

* Actual: Error message: Unexpected token b in JSON at position 0
* Expected: Works should merge.

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Chrome Version 88.0.4324.192 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** staging

### Stakeholders

@cdrini

**Comment by cdrini** [comment]
Can you try again, @seabelis ? We had some temporary outages yesterday, and it looks like this might have been during then.

**Comment by seabelis** [comment]
Yes. Worked.
