### ISSUE TITLE
Delete editions_merge directory (dead code)

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4722]
### Summary of Requirements

- [ ] Delete said directory
- [ ] Look for any references to `editions_merge` and delete those references (or bring them up for discussion)

### Stakeholders

@ArunTeltia @jdlrobson

**Comment by cdrini** [comment]
Would you be interested in taking this one, @ArunTeltia ?

**Comment by ArunTeltia** [comment]
Yes sir I am working on it
