### ISSUE TITLE
ol-home0 provisioning needs rsync ferm/input

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4723]
The issue was that we were updating `/etc/ferm/ferm.conf` rules even though these were auto-generated daily. We should have been putting them in `/etc/ferm/input/` as is described in @abezella's guide:
https://docs.google.com/document/d/1W4DtLPlzCUszovOj1yA6uy5Ws8GY_cpjlxu5VOo2aQo/edit#heading=h.3dy6vkm

The second issue is, restarting `ferm` via `sudo service ferm reload` causes Docker iptables to go haywire.
The solution is to restart docker with `sudo systemctl restart docker`

HOW DO WE DETECT FERM RULES CHANGES FROM ANSIBLE.

* [x] If we reprovision `ol-home0` this `ferm/input` rule needs to be a step, e.g. adding:
`saddr $CLUSTER proto tcp dport rsync ACCEPT;`
to `/ol-home0:/etc/ferm/input/rsync.conf`

Related to #680

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/4706#issuecomment-790771364_

**Comment by cclauss** [comment]
Rsync works between ol-home0 and ol-www0.  We will reopen this if we run into rsync issues.
