### ISSUE TITLE
Add video tutorial for contributing

### ISSUE THREAD

**Issue by khabdrick** [internetarchive/openlibrary#4747]
### Summary
I thought about this issue because, I am aware there are some people who have a hard time going through the documentation and all, and coming from a self-thought background I can understand that, we always looked to video tutorials to learn new things. The screencast/video tutorial will be just to help newcomers have an easy time contributing instead of overwhelming themselves with the bulkiness of the docs.

**Comment by cclauss** [comment]
Five videos:
* Four videos: https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md
* One video: https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide

**Comment by khabdrick** [comment]
Ohhh, yeah
wasn't aware
