### ISSUE TITLE
Same Readers Stats for all editions of a Book

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4752]
Same Readers Stats for all editions of a book. When we give a rating the value is passed to all other editions of that book. Same with Want to Read, Currently Reading, Have Read
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/110228693-210fc380-7f29-11eb-9966-357f87680c63.png)
![image](https://user-images.githubusercontent.com/64412143/110228701-2a009500-7f29-11eb-99e7-4688e5bf41a7.png)

### Relevant url?

https://openlibrary.org/books/OL5415472M/Sula.
https://openlibrary.org/books/OL3382093M/Sula
https://openlibrary.org/books/OL31938360M/Sula
### Steps to Reproduce

1. Go to any book page https://openlibrary.org/books/OL5415472M/Sula.
2. Open different editions

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Closing this is a non-issue -- these Reading Log stats are computed at a work level (not an edition level) so aggregate totals are reflected e.g. across editions. Otherwise, the data becomes too fragmented in many cases to be useful.
