### ISSUE TITLE
Upload Open Library book covers for bulk access to archive.org

### ISSUE THREAD

**Issue by post-l** [internetarchive/openlibrary#476]
The dumps for the latest covers are not available for the original covers it stopped at ids starting with a 5 and for large covers, it stopped at 6. The latest cover added has the id 7912615. 

I can't find any discussion or document around this issue so that's why I'm posting it here.

documentation:
https://openlibrary.org/dev/docs/api/covers

missing original bulk:
http://www.archive.org/details/covers_0006/
http://www.archive.org/details/covers_0007/

missing large bulk:
https://archive.org/details/l_covers_0007/

**Comment by mekarpeles** [comment]
Hi @post-l -- I'm ccing @hackerfactor who was recently doing work related to Open Library covers who may be able to offer input.

It may be the case that the naming convention changed. e.g. I see many "cdump" which I assume is cover dump, in the Open Library Data collection on archive.org:

https://archive.org/details/ol_exports?sort=-publicdate

**Comment by post-l** [comment]
OL Complete Dump "cdump"
> This contains dump of all revisions of all the records in Open Library. Format is same as the OL dump.
From https://openlibrary.org/developers/dumps

**Comment by anandology** [comment]
Ol covers are now stored in items like this:

https://archive.org/details/olcovers660

IIRC, each item stores about 10,000 covers.

**Comment by post-l** [comment]
The last Ol covers dump is olcovers713 so dumps from 714 to 791 are still missing.
Currently missing covers from 7140000 to 7912615.

**Comment by anandology** [comment]
They usually sit on the covers node and periodically drained. The process
was manual, when I used to manage it about 4 years ago. Not sure if that is
still the case.

**Comment by LeadSongDog** [comment]
Any reason not to provide a file size preview on the dump download page?

**Comment by post-l** [comment]
@anandology  I think that no one did your manual process after because the 713 batch was uploaded by you on 2012-06-27 20:52:00 😜  

@LeadSongDog Not really related to this issue but anyway, you can find the file size on this page if you click on the ZIP button or show all (download page). For each dump, there is an olcoversXXX_files.xml with dump files information inside but you have no details of the files/images inside of each zip. You need to download them.

**Comment by hbromley** [comment]
@post-l, are you familiar with the "zipview" feature on archive.org? The current version of the website doesn't offer obvious links, but you can easily formulate a suitable URL by adding a trailing slash.

For example, the [download](https://archive.org/download/olcovers660) page for item olcovers660 includes a link to file olcovers660.zip that looks like `https://archive.org/download/olcovers660/olcovers660.zip`; adding a trailing slash, to make it `https://archive.org/download/olcovers660/olcovers660.zip/`, [brings](https://archive.org/download/olcovers660/olcovers660.zip/) you to a page that lists the contents of the zip, and offers links to view/download any of the individual files within it. The same approach works for tar's  rar's, and several other archive formats.

**Comment by LeadSongDog** [comment]
@post-l  the point is that https://openlibrary.org/developers/dumps leaves the reader in the dark as to what the size is. Multi-GB files should not come as a surprise, especially to mobile users.

**Comment by post-l** [comment]
@hbromley I didn't know about this cool feature! Thanks! :)

**Comment by mekarpeles** [comment]
cc: @hornc

**Comment by brad2014** [comment]
Is this still an issue?  Let's use this issue to track missing or broken dumps, and #1439 for the issue of adding size to the download page.

**Comment by mekarpeles** [comment]
It looks like there may not be an automatic process for Cover-store, to archive Open Library's covers on Archive.org. We're appear to be several years behind.

@hornc are our covers backed up **anywhere** on archive.org that you know of (even if not in easily accessible way)? :sweat_smile: 
cc: @cdrini

**Comment by hornc** [comment]
This process was never automated AFAICT.

https://archive.org/details/ol_exports?and%5B%5D=covers&sin=  shows some, there are others that Anand uploaded in community texts;

https://archive.org/details/covers_0001

you should be able to guess the rest of the ids ;)

**Comment by mekarpeles** [comment]
Work was done this year to dust off the process for archiving Open Library covers to Archive.org: https://github.com/internetarchive/openlibrary/issues/7197

We have some covers named `olcoversXXX`:
https://archive.org/search.php?query=identifier%3Aolcovers%2A

We have some covers named `covers_XXXX`
And some covers named `covers_XXXX_YY`
https://archive.org/search.php?query=identifier%3Acovers_*

We now have a `README` https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/README.md which documents our process moving forward.

There **remains** a range of covers (~5M < w/ ID < 8M) which are non-uniform and may be hard to archive.

The next step is setting up a monthly cron job #7257 to move files off local disk to items.
