### ISSUE TITLE
Data cleanup

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#477]
There's a lot of low-hanging fruit for easy data cleanup (by bot?). Examples:

Edition names often have "ed edition" or "ed. edition": https://openlibrary.org/books/OL11703886M/Become_strategic--or_die?b=6&a=5&_compare=Compare&m=diff

Pagination often includes a height such as "... 22 cm" that belongs elsewhere.

**Comment by mekarpeles** [comment]
Is there any way we can consolidate all of our Data cleanup into a single document, maybe on the wiki? Or tag/label so we have a better holistic idea of what similar issues exist?

I would love it if issues on our list were things which had a clear and objective start and end.

Otherwise, it will get punted by the core team and, if we're lucky, will at most generate discussion and perhaps bug-fix in the form of a small, scoped subset of the problem. (And if there *is* a small subset of the problem which can/should be solved, let's please report an issue which is specific to that and then see who from the community may be willing to jump in and solve it) :)

@LeadSongDog thank you for reporting! Extremely valuable -- trying to find protocols which will help us be more actionable in addressing your suggestions

**Comment by tfmorris** [comment]
There's a ton of this stuff on the ol-tech mailing list and various other abandoned communication channels. We could use a tag here or a wiki page or any number of other mechanisms to collect it all.

There are, however, two different types of cleanups:

1.  Those which are independent of anything else and can be done on an ad hoc basis (although perhaps a general cleaning infrastructure would be useful to support this activity).
2. Those which have an impact on other activities like author merges, works merges, edition merges, etc.

The latter tend to be iteratively reinforcing. ie the better view of the duplicate authors you can get, the better you can identify duplicate works and vice versa.

**Comment by LeadSongDog** [comment]
Some reflect incorrect or incomplete imports such as https://openlibrary.org/books/OL16156872M/Lettres_a_la_fianc%C3%A9e?b=9&a=4&_compare=Compare&m=diff
corrections based on https://openlibrary.org/show-records/talis_openlibrary_contribution/talis-openlibrary-contribution.mrc:1032526208:458 (I deleted stray trailing punctuation, inserted the series title and the height per the MARC, but I also corrected some missing accents that the MARC omitted. Much of this is a repetitive pattern.

**Comment by LeadSongDog** [comment]
Similarly OL13786150M was incorrectly imported Aug 31, 2008 by ImportBot from a correctly-accented MARC record. Then on Dec 11, 2009 the mangled title was propagated by WorkBot at OL10565972W which four days later it then linked to that edition. There are a LOT of similar instances. In many  cases there also exists a correctly accented work I.e. OL607986W that was similarly created from OL15214201M that was correctly imported by ImportBot on Sept 18, 2008. It seems something was fixed in that 18 days but the residue was never addressed.

**Comment by LeadSongDog** [comment]
Many of the 2008 imports from Amazon incorrectly show a series title parenthetically appended to the edition title. Often these also spawned autogenerated work records with the same extended title. From the current carousel, we see:
https://openlibrary.org/books/OL10749737M/Primal_Instincts_(Harlequin_Blaze)?v=1
that spawned 
https://openlibrary.org/works/OL5884955W/Primal_Instincts?v=1 
which work record was later cleaned up a bit:
https://openlibrary.org/works/OL5884955W/Primal_Instincts?b=4&a=3&_compare=Compare&m=diff
but the defective edition record still persists:
https://openlibrary.org/books/OL10749737M/Primal_Instincts_(Harlequin_Blaze)
and it still leaves the "series" field blank, even though the LoC MARC data linked in 2009 by
https://openlibrary.org/books/OL10749737M/Primal_Instincts_(Harlequin_Blaze)?b=2&a=1&_compare=Compare&m=diff 
lists the field: 440  0 $aHarlequin blaze ;$v378.

This class of repetitive error created many defective (and often redundant) works. It should be possible somehow to collect up the edition records, move the series titles from the edition title to the correct field, check for redundant work records, and merge them without the parenthetically suffixed series in the work title. Just as a SWAG, I would think this error affects about 1-3% of edition records.

**Comment by hornc** [comment]
The [openlibray-client](https://github.com/internetarchive/openlibrary-client) now has a `data-cleanup` tag for data clean up tasks, and it is the tool that will enable volunteers to make the edits in bulk:

https://github.com/internetarchive/openlibrary-client/issues?q=is%3Aissue+is%3Aopen+label%3A%22data+cleanup%22

Feel free to add more or provide code snippets to make the corrections!

**Comment by tfmorris** [comment]
I'm just seeing this comment now, but it seems strange to me that OpenLibrary data cleanup tasks would go in the issue tracker of a client library/tool. What's the thinking behind that?

**Comment by tfmorris** [comment]
Seems like this is the prototypical data cleanup task, but I don't appear to have rights to add that label. @hornc or @mekarpeles could you label it please?

**Comment by LeadSongDog** [comment]
@hornc @mekarpeles : bump?

**Comment by guyjeangilles** [comment]
This really should be an epic. As @mekarpeles said, we should create a list of _small_, _clearly defined_,  tasks that related to data cleanup.  The`Data Cleanup` label is a good place to start.

**Comment by mekarpeles** [comment]
It should be an epic **and** a tag. I'm closing this issue. Folks in this thread, if there's an epic to be made from it, please organize it according to the issue standards (following the `epic` guidelines as per @guyjeangilles's suggestion)
https://github.com/internetarchive/openlibrary/wiki/Interacting-with-GitHub-Issues and https://github.com/internetarchive/openlibrary/wiki/Using-Managed-Labels-to-Track-Issues

**Comment by mekarpeles** [comment]
@hornc can you please take a look at these as data lead and see if anything needs to be integrated it into our other issues or docs?
