### ISSUE TITLE
Move ol-home / ol-www ipstats cron job + ol-home solr to ol-home0

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4775]
> MOVE ALL CRON JOBS TO OL-HOME0 ipstats.py. Unclear what ideal course of action is for these, but if we could get them running on ol-home0 with other cron jobs: that would be nice!

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/4383#issuecomment-792948485_

Related:
* https://github.com/internetarchive/openlibrary/issues/5144

* [ ] sitemap rsync should run on ol-home0 [Slack thread](https://internetarchive.slack.com/archives/C075DJ6G1/p1614111981011600) <details>The sitemaps are generated on ol-home0 and copied over to ol-www1 where they are served. We can actually make the `rsync` command run on ol-home0 and target ol-www1 (and/or ol-www0). This is **not** blocked by ol-www0 migration.  `saddr $CLUSTER proto tcp dport rsync ACCEPT;` in `/etc/ferm/ferm.conf` is vital.</details>

**Comment by cdrini** [comment]
Closed in favour of #7622  and #4426
