### ISSUE TITLE
Add book subtitles to lists

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4783]
Problem: 
right now, putting subtitles into the subtitle box doesn't work out for titles that have the same name, as they all look the same in lists - due to the subtitles not showing up in lists. This forces people to write what should be in the subtitles in the titles and is just a mess and overall hard to read and disorganized.

Solution:
Add subtitles to lists, so that subtitles can be written where they should and everything's more readable.

Example:
![image](https://user-images.githubusercontent.com/55302685/110538382-d765db00-80d8-11eb-9961-f1c92b9422f2.png)

Would look like all of them had California Treasures as the title if the part after it - the grades and books were in the subtitles instead. Adding subtitles would differentiate them in the lists and there's enough space to do so too.

**Comment by Yashs911** [comment]
@BrittanyBunk I would like to work on this issue.

**Comment by BrittanyBunk** [comment]
@Yashs911 thanks, but I can't assign anything to anyone.
