### ISSUE TITLE
Subject are barely readable by users when someone came to check the book

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#4786]
### Describe the problem that you'd like solved

The subject section when a reader opens a book is not user friendly or i mean to say readable (See Image)
![afdewew](https://user-images.githubusercontent.com/43555219/110615322-503c6400-81b9-11eb-8b09-c89712cc4d9a.PNG)

Url in this image: 

> https://openlibrary.org/works/OL9770557W/Alice%27s_Adventures_in_Wonderland_Through_the_Looking_Glass

### Proposal & Constraints

We can add some padding between each subjects to make it more readable

### Stakeholders

@mekarpeles @cdrini

**Comment by Yashs911** [comment]
We can design them like Github labels or tags on different websites.
![subjects tags](https://user-images.githubusercontent.com/64412143/111946307-409a1500-8b01-11eb-809a-e137156c5745.JPG)
![subjects page](https://user-images.githubusercontent.com/64412143/111946314-4263d880-8b01-11eb-8d5e-40d3c5020c14.JPG)
I would like to create a PR for this.

**Comment by mekarpeles** [comment]
Subjects are now truncated as described
