### ISSUE TITLE
In the /subjects there are some input inbox box at every navbar and also the hamburger icon on expand overlap with browse

### ISSUE THREAD

**Issue by ArunTeltia** [internetarchive/openlibrary#4789]
### Evidence / Screenshot (if possible)
![subjects](https://user-images.githubusercontent.com/43555219/110655327-f782c080-81e4-11eb-8b4d-181f4e66cf39.PNG)
![subject2](https://user-images.githubusercontent.com/43555219/110655536-25680500-81e5-11eb-8102-1a5bf0b6462c.PNG)

### Relevant url?

https://openlibrary.org/subjects

### Steps to Reproduce

1. Go to https://openlibrary.org/subjects

* Actual: In the /subjects there are some input inbox box at every navbar and also the hamburger icon on expand overlap with browse also I am not sure why there are checkbox present It was not present before.

Really Bizzare behavior on continuous refreshing checkbox is getting removed and this bug is disappearing

### Details
I am not really sure why this behavior is happening but this is visible most of the time. I think this is browser specific, as I am trying to reproduce it on chrome and this is not reproducible there

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Microsoft Edge
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jdlrobson @mekarpeles

**Comment by Yashs911** [comment]
@ArunTeltia can't reproduce this error on Microsoft edge

**Comment by ArunTeltia** [comment]
Here Check it out 
https://user-images.githubusercontent.com/43555219/110665444-644e8880-81ee-11eb-9c9d-ac5fec72a935.mp4

In google Chrome 
![Screenshot (59)](https://user-images.githubusercontent.com/43555219/110666060-fa82ae80-81ee-11eb-9045-c279386f2444.png)

**Comment by jdlrobson** [comment]
this is a caching issue. Please run `make css`.
