### ISSUE TITLE
Windows setup shows 502 Bad Gateway in browser

### ISSUE THREAD

**Issue by higagan** [internetarchive/openlibrary#479]
Hi,
I am trying to get development environment up in windows. Here is my nginx error log:
![image](https://cloud.githubusercontent.com/assets/615578/25454918/a1a07d78-2aeb-11e7-91d6-3074fc59f803.png)

 I have installed virtual box and vagrant. 
after 'vagrant provision' command runs successfully 
![image](https://cloud.githubusercontent.com/assets/615578/25454742/21f2e9f8-2aeb-11e7-9a94-9ecf6e29561f.png)

But when I open the browser with localhost:8080, i am getting 502 error:
![image](https://cloud.githubusercontent.com/assets/615578/25454779/3f958786-2aeb-11e7-87c9-41e4fef13129.png)

I tried giving a server restart command , /etc/init.d/ol-start through putty . it restarts successfully.
![image](https://cloud.githubusercontent.com/assets/615578/25454847/6ce9a3d4-2aeb-11e7-87bd-2607fa02e2a0.png)
 But still same 502 error i am getting.

**Comment by mekarpeles** [comment]
@higagan It looks like the gunicorn service is not getting started -- I'd debug why the app isn't starting by `source`-ing the virtualenv and then manually running `python app.py` and see how it responds. There should likely be an error log for openlibrary itself (the app) which provides some traceback of what's going wrong.

**Comment by higagan** [comment]
Hi mek,

Any update on this?

Thanks
Gagan

**Comment by mekarpeles** [comment]
@higagan did we try manually running app.py from within vagrant to see where/how it is breaking? (see my previous msg above).

It should be as straight forward as sourcing /openlibrary/venv/bin/activate (or wherever the virtualenv is setup on vagrant) and then running python app.py from within vagrant openlibrary directory.

**Comment by higagan** [comment]
Hi @mekarpeles 
I ran app.py . 
![image](https://cloud.githubusercontent.com/assets/615578/25539126/3f3a5e50-2c63-11e7-976a-e621d35bd7fb.png)

can you tell where can i get infogami.utils.

Thanks
Gagan

**Comment by mekarpeles** [comment]
Looking through the configs, it does not seem the paths are configure for the VM to easily work for Windows. Others, feel free to weight in. Anyone else have success w/ running Open Library on windows?

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/211

**Comment by cdrini** [comment]
This should no longer be an issue with the new docker flow.
