### ISSUE TITLE
Bad UI of User Lists + Minor design improvement of Lists Page 

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4794]
The content of My lists is not aligned properly. + Minor design improvement on the Lists page.
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/110740194-a57b8280-8258-11eb-8d17-6e5a56ff0208.png)
### Relevant url?

https://openlibrary.org/people/yashs911
https://openlibrary.org/lists
### Steps to Reproduce

For lists page
* Actual: 
![image](https://user-images.githubusercontent.com/64412143/110740260-c8a63200-8258-11eb-9219-0bdf5eef2288.png)
* Expected: 
![image](https://user-images.githubusercontent.com/64412143/110740286-d360c700-8258-11eb-8466-d68bf747856c.JPG)

### Stakeholders

@jdlrobson

**Comment by Yashs911** [comment]
I was also wondering can we remove the **No description** text because the majority of lists don't have description.

**Comment by ps364279** [comment]
Should I do it

**Comment by Yashs911** [comment]
@ps364279 Yeah you can go ahead and create a PR. If you need any help just ping me.
