### ISSUE TITLE
Add "Import and Export Options" to My Profile

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4795]
### Describe the problem that you'd like solved

Being an OL member for the past 5 months I was not aware exactly where this option was until today I found it in Settings.
I believe this feature should be added to the More menu / My profile so that more users will come to know about this.

### Stakeholders

@mekarpeles

**Comment by sharur7** [comment]
Can I work on this isssue?
@Yashs911

**Comment by Yashs911** [comment]
@sharur7 I would suggest you to wait. Once it's finalized where we want to add the option then you can create a PR.

**Comment by sharur7** [comment]
> @sharur7 I would suggest you to wait. Once it's finalized where we want to add the option then you can create a PR.

Cools!

**Comment by mekarpeles** [comment]
Adding a link to the Profile menu, similar to as @Yashs911 describes, seems alright with me:

![openlibrary org_ (11)](https://user-images.githubusercontent.com/978325/112757745-ef29d400-8f9f-11eb-8c34-5ad60302df96.png)

**Comment by Yashs911** [comment]
@sharur7 Are you still interested in solving this issue?
