### ISSUE TITLE
Add more data to Reading Log Export Option

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4796]
I exported my reading log and the data I got:
![image](https://user-images.githubusercontent.com/64412143/110741929-7adef900-825b-11eb-8e7c-7df19ccc793b.png)

While I did a similar export from Goodreads and the data I got:
![image](https://user-images.githubusercontent.com/64412143/110742033-a82ba700-825b-11eb-9a52-3b65adce5199.png)

### Describe the problem that you'd like solved

So I believe we can add **Title**, **Author**, **Year of Publication**, **Ratings**, **ISBN** e.t.c

### Stakeholders

@mekarpeles

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L884 would be a good starting point.

**Comment by shrey27tri01** [comment]
Can I work on this issue?

**Comment by cclauss** [comment]
@shrey27tri01  Thanks for your interest.  You do not need to wait for permission.  If you feel like you can fix this issue then please submit a pull request.  Let us know if you need any help.

**Comment by cclauss** [comment]
How is this effort going?  Any blockers?

**Comment by Yashs911** [comment]
@cclauss I also tried to solve this issue but the function `get_users_logged_books` doesn't return any information apart from `work_id (int) - the Open Library work ID as an int (e.g. OL123W becomes 123)` so I was wondering how can we use the work_id to extract info regarding title, author, YOP e.t.c

Am I on the right track?

I also thought of using this function but was getting some kind of error:
https://github.com/internetarchive/openlibrary/blob/fd9693a87cf79064e828e925e7cb9f2411044529/openlibrary/plugins/upstream/account.py#L777

**Comment by cclauss** [comment]
At the [url provided above](https://github.com/internetarchive/openlibrary/issues/4796#issuecomment-797580393) you should see `for book in books:` where I believe that each book will be a Python dict so you should be able to `print(list(book.keys))` to see what fields are available.  You can then add `book["supercool_key"]` to `row` and see if that value shows up.

**Comment by shrey27tri01** [comment]
@cclauss Sorry for the dumb question, but I'm unable to print anything on the console using `print(list(book))` inside the loop `for book in books:` after clicking on the "Download" button. I also tried printing just `books` after the `books` variable is initialized, but I still don't get any output. On the other hand, using the print statement inside another function, say the [`import_books():`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L854) function gives me an output on the console correctly.

**Comment by cclauss** [comment]
Try `print(list(book), file=web.debug)`

**Comment by cclauss** [comment]
Did that work?

**Comment by shrey27tri01** [comment]
@cclaus Yes, that worked, thank you very much!
Printing `list(book)` gives me the following keys: `['username', 'work_id', 'bookshelf_id', 'edition_id', 'updated', 'created']`
Now can I use this information to look up book name, author, title, isbn etc. using `readlog.get_works(key, page=i.page)` like the way it is used in [this](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L733) function?

**Comment by mekarpeles** [comment]
Just a reminder that the data for these books is not in the DB so some sort of join may be necessary (or using solr). One thing we could do is provide a script which allows one to take their reading log dump and then pull all of the corresponding data. This would be a great good first issue if someone wanted to work on it.

The central issue here is performance -- we're exporting the entire Reading Log which can have tens of thousands of items (and I know at least 5 reading logs which do, having done this query, lol). Joining this w/ solr data or infobase behind the scenes is problematic for the same reasons as Lists.

having a separate e.g. ol-client thing or script to take the dump (offline) and then fetch the underlying items seems useful but hard to do on the website unless we kick off some offline dump like e.g. facebook does for "downloading your data".

Having a javascript thing which does something like this could be a good approach (@cdrini's idea, I like it)

**Comment by tuminzee** [comment]
@shrey27tri01 would you be still interested in taking this one?

**Comment by shrey27tri01** [comment]
@tuminzee I am not currently working on this issue. You can go ahead, please. Also, really sorry for the late response :)

**Comment by jimchamp** [comment]
Closed by #6621
