### ISSUE TITLE
Adding the Klingon Language

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#4797]
I know it may sound stupid for some but there are books written in Klingon like The little Prince (Ta' puq mach) and klingon dictionaries. But there is no entry for the Klingon language. Would be nice to be able to set the language to klingon for thos works.

**Comment by seabelis** [comment]
I've run into this as well. I had to use 'Multiple Languages' because Klingon is not available.

**Comment by cclauss** [comment]
https://openlibrary.org/books/OL6805303M/The_Klingon_Hamlet

**Comment by tfmorris** [comment]
I can certainly see why people would think it's stupid, but the Library of Congress assigned a [language code](https://www.loc.gov/marc/languages/language_code.html) `tlh`, so it's easy enough to include. It's got the same code in ISO 639-2. https://www.loc.gov/standards/iso639-2/php/code_list.php

**Comment by mekarpeles** [comment]
Language is language -- let's make works as easy as possible for people to discover and as useful as possible. Especially if there are contributors interested in adding translations. The standard steps should apply re: setting up a `tlh` directory within i18n.

@bitnapper would you like to own this one? And do you have any questions?

https://openlibrary.org/i18n

**Comment by cdrini** [comment]
@seabelis You should have perms to create this here: https://openlibrary.org/languages/tlh.yml?m=edit ; you might want to copy https://openlibrary.org/languages/eng.yml?m=edit as a template.

**Comment by cclauss** [comment]
We already have a label for **Internationalization (i18n)** but now do we need to add a new label for **Intergalactization (i16n)**? ;-)

**Comment by bitnapper** [comment]
@mekarpeles I'm not sure what you're asking. I don't think translating the interface into Klingon is a good idea (I don't think its a bad idea in general but I don't know any Klingon ... ). For now I'd be happy if an editions language can be set to Klingon.

**Comment by cdrini** [comment]
Ok, I created the language! Hello Klingon :)

![image](https://user-images.githubusercontent.com/6251786/111415504-703bbe00-86b8-11eb-902d-278d88f580dc.png)

**Comment by cclauss** [comment]
majQa'.
