### ISSUE TITLE
Author names with composed diacritics don't autocomplete

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#4799]
This author name cut & paste directly from WorldCat doesn't autocomplete, even though the record exists: Hildegard Höhr
Manually changing the spelling to use a letter with precomposed diacritic allows the autocomplete to find the correct record. This will cause duplicate author records to be created.

### Evidence / Screenshot (if possible)
![Screen Shot 2021-03-12 at 2 37 31 PM](https://user-images.githubusercontent.com/82178/110990130-e64ec680-8340-11eb-8cc8-fb301f4e3596.png)
![Screen Shot 2021-03-12 at 2 37 47 PM](https://user-images.githubusercontent.com/82178/110990159-f2d31f00-8340-11eb-8eae-0754150093b6.png)

### Steps to Reproduce

1. Follow instructions above
2. Profit

* Actual: Screenshot #1 - autocomplete fails
* Expected: autocomplete works

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
This was likely fixed by #5600 . I can no longer reproduce the issue.
