### ISSUE TITLE
Possible to create 5 identical lists?

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#48]
http://openlibrary.org/people/Tuli/lists

**Comment by hornc** [comment]
looks like a duplicate of #227 ?

**Comment by hornc** [comment]
Fixed with tested and merged PR https://github.com/internetarchive/openlibrary/pull/252
@gdamdam can you please close this issue, thanks!

**Comment by salman-bhai** [comment]
@mekarpeles @hornc would it be okay if we can close this Issue!
