### ISSUE TITLE
 Bump css-loader from 3.6.0 to 5.x.x #4765 

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#4815]
IN #4765 Dependabot tried to upgrade our version of css-loader to 5.1.1

Unfortunately, this upgrade breaks the loading of static image and font assets which now resolved differently.

* Expected: 

- [ ] css-loader is upgraded to the latest version (5.x.x)
- [ ] make css works without error
- [ ] make js works without error
- [ ] static asset URLs are not resolved - we do not want to embed fonts and images inside the stylesheets. The `url` option of  https://www.npmjs.com/package/css-loader is likely needed.

### Stakeholders
@jdlrobson

**Comment by Ayushsunny** [comment]
I would like to work on this issue

**Comment by Ayushsunny** [comment]
Hello @jdlrobson actually I'm new to this open-source, so can you explain bit more like what exactly I have to do and where is the code base of this issue so I can easily find out and work.

**Comment by Yashs911** [comment]
@Ayushsunny First you need to set up the local env. After that install the latest version of css-loader (https://www.npmjs.com/package/css-loader) using `@latest`. Run `make css` and `make js` and send a PR.
Although I don't know what needs to be done for the 4th checkpoint (`static asset URLs are not resolved`)
