### ISSUE TITLE
History of edits missing revision/version

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#483]
Compare https://openlibrary.org/books/OL19350064M/The_mariners'_handbook to the respective https://openlibrary.org/books/OL19350064M/The_mariners'_handbook?m=history and it is clear that revision 2 of December 15, 2009 is missing from the former. It seems obvious that both lists should show the same list of entries.

**Comment by hornc** [comment]
I believe this is deliberate, but not very clear... I'm not sure it is documented anywhere, but it looks like the item page's 'History' footer only ever shows 5 edits. The first, then the last 4. 

If you look at the page source the first edit row has `class=first` and is displayed shaded to distinguish it from the others.

Are you suggesting adding the actual revision number somewhere in the row? Maybe an ellipsis to indicate a break in the sequence if there are more that 5 edits?

See https://openlibrary.org/authors/OL11149A/Sophocles for an item with 16 edits in history, but still only 5 on its main view.

**Comment by guyjeangilles** [comment]
Assigning jdlrobson (not tagging ask requested ) per slack discussions since a template change should resolve this issue.

**Comment by jdlrobson** [comment]
needs some changes in the backend or guidance on what the frontend is doing wrong before I am willing to be assignee

**Comment by RayBB** [comment]
Cannot reproduce the issue.
If it comes up again please share steps to reproduce.
