### ISSUE TITLE
Enable deployment roll back to a previous Docker image

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4830]
Relates to #4806

As a deployment operator, how can I smoothly roll back to a previous Docker image when a deployment has issues?

### Describe the problem that you'd like solved

I do a deployment and I see there are issues that require me to roll back to a previous Docker image.

% `cat rollback_oldev.sh`
```bash
#!/bin/bash

if [[ -z "${1}" ]]; then
    echo "$0 oldev_tag  # A Docker tag command line parameter is required."
    exit 1
fi

SHOW_OLDEV_LATEST="docker image ls | grep oldev | grep latest"
SERVERS="ol-home0 ol-covers0 ol-web1 ol-web2"
for SERVER in $SERVERS; do
    ssh $SERVER "hostname && $SHOW_OLDEV_LATEST && docker tag oldev:$1 oldev:latest && $SHOW_OLDEV_LATEST"
done
```
Issues:
1. `docker tag` needs an image `TAG`, not an `IMAGE ID`.
2. Docker image TAGs are machine-specific while Docker IMAGE IDs are the same on all servers.
3. Retagging an image as `latest`, makes it lose its Docker TAG which makes re-reverting difficult.

The script above needs to be modified to:
1. Take an IMAGE ID as its command line parameter and must convert that to a TAG on each server
2. Preserve the original TAG when retagging an image as `latest` to facilitate re-reverting.

### Stakeholders

@mekarpeles @cdrini

**Comment by cdrini** [comment]
Fixed by `OLBASE_IMAGE` environment variable.
