### ISSUE TITLE
ebook terminology confusing to patrons

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4838]
Patrons sometimes write in saying they use the ebook filter with unexpected results. Most people unfamiliar with how the term 'ebook' is used on Open Library expect to see a list of editions available in an ebook format, unrelated to the lending library.

### Proposal & Constraints

Update terminology so that there is some clear distinction between an ebook format and editions available inlibrary to borrow.

### Related files
Related to #2346

**Comment by mekarpeles** [comment]
I know this is a problem and is slightly confusing however am going to flag as "will not fix" for the time being. Eventually we'll rethink the entire radio button experience on the search for ebooks v. catalog etc

**Comment by bilch** [comment]
Why not use "borrowable" or "borrowable/readable" for the time being? I'm a librarian and a fairly intensive user of Open Library, and it took me a year to understand that "ebook" doesn't mean what I expected it to mean. (The number of "+1" when I mentioned this in the librarian group suggests I wasn't the only one.)
