### ISSUE TITLE
npm run lint error

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#4839]
npm version 7.5.4
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/111468074-2d76f600-874b-11eb-99e5-fbcf3983ec16.png)

**Comment by cclauss** [comment]
https://www.npmjs.com/package/mkdirp seems to be missing.

Our GitHub Actions successfully [run that test](https://github.com/internetarchive/openlibrary/runs/2132970269#step:5:10) on every pull request.

Did you try with [npm v7.6.3](https://www.npmjs.com/package/npm)?

**Comment by cclauss** [comment]
Perhaps see 4852 https://github.com/internetarchive/openlibrary/pulls

**Comment by cclauss** [comment]
@cdrini on #3408 say:
> Eslinting causes the build to fail every other time (???????????)

**Comment by Yashs911** [comment]
> https://www.npmjs.com/package/mkdirp seems to be missing.
> 
> [Our GitHub Actions](https://github.com/internetarchive/openlibrary/actions) successfully [runs that test](https://github.com/internetarchive/openlibrary/runs/2132970269#step:5:10) on every pull request.
> 
> Did you try with [npm v7.6.3](https://www.npmjs.com/package/npm)?

@cclauss Installing `mkdirp` doesn't solve the problem.
Same error with npm version 7.6.3

**Comment by Yashs911** [comment]
Closing this issue. I was not running npm run lint inside the docker bash 😅 .
Sorry for the inconvenience caused
