### ISSUE TITLE
Create aggregate observation statistics component for book pages

### ISSUE THREAD

**Issue by jamesachamp** [internetarchive/openlibrary#4867]
### Describe the problem that you'd like solved

The observations survey in the book notes modal form was designed to gather information that would be useful for readers who are searching for a book that meets certain criteria.  Currently, observations that are submitted are not being shared with other patrons at all.  This is a missed opportunity.

### Proposal & Constraints

Create a new "Reader Observations" section in book pages.  This section can be quickly navigated to by clicking a new "Reader Observations" tab, which will be located above the editions table.  The new section will contain a count of the total number of people that submitted observations for the work, each observation type that was submitted, and the percentage of respondents who submitted each observation value.

### Additional context

Mock-up for new component:

![component_mock_up](https://user-images.githubusercontent.com/28732543/111874875-71e1dc00-896d-11eb-848c-bf17d8cde4b3.png)

**Comment by jamesachamp** [comment]
A PR for this is ready, and will be opened once #4803 is merged.

**Comment by tfmorris** [comment]
> Describe the problem that you'd like solved
> Observations that readers submit for a book can be used to provide information to other patrons. Anonymized observation statistics can be displayed in a new component on a book page.

This describes a solution, not a problem. What is the problem that is being solved? Have readers been asking "How fast-paced is this book?" I'm having a hard time envisioning the use case for this additional clutter in the UI, which is already in dramatic need of simplification and streamlining.

**Comment by jamesachamp** [comment]
I've updated the problem description.

The point of the component is give patrons an idea of what other readers thought of a work, based on thirteen different aspects (DB entries for each are found [here](https://github.com/internetarchive/openlibrary/blob/410489b27523cd10b2e743961e932974a8b2e8fa/openlibrary/core/schema.sql#L100-#L296)).
