### ISSUE TITLE
Reply from Solr/do_search is None for some queries, breaks search results

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#487]
Some searches can receive an empty (None) reply from `do_search`, which breaks the search results display.

Example search:
https://openlibrary.org/search?q=language%3Aeng&debug=true&sort=new

/openlibrary/plugins/worksearch/code.py in do_search, line 282
```
    if reply.startswith('<html'): ...
        is_bad = True
    if not is_bad:
        try:
....
```

if `reply` above is None, an exception is raised. I'm haven't dug in deep enough to find out why `do_search` is returning none. I'm not sure if setting `is_bad = True` if reply is `None` is sufficient to fix the problem.

The message `m`at https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py#L291  will need to be set to something informative if `reply == None` like "Empty reply from Solr"

I don't know why Solr should return an empty reply though, I think the root cause needs to be investigated.

**Comment by mekarpeles** [comment]
https://openlibrary.org/search?q=language:eng

**Comment by guyjeangilles** [comment]
@hornc Have you explored this bug any further? Also are you willing to be assignee for this issue. Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by mekarpeles** [comment]
Appears to be resolved!
