### ISSUE TITLE
Librarian tools for fixing Orphaned editions

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#4874]
Re-enable the 'Orphaned Editions'  orange indicator that was on this page:

![image](https://user-images.githubusercontent.com/905545/112094271-dddb7300-8bff-11eb-8857-a245f81f29be.png)

+ New feature:

Display in librarian only orange any extra hidden or deleted authors, 
e.g. https://openlibrary.org/books/OL12885070M/Fire_in_Boomtown  has 2 authors in its metadata,
https://openlibrary.org/books/OL12885070M.yml
but only one is displayed. The other is a `/type/delete` .  It would be great for Librarians to have visibility on these kinds of 'hidden' authors. I believe this has been brought up on other issues.

Also, while I'm at it:
![image](https://user-images.githubusercontent.com/905545/112094550-5cd0ab80-8c00-11eb-8828-8b1097be700f.png)
Make this additional metadata input smaller or collapsible. I have never used it to add extra metadata through the UI, I either use a bot script for a large task, or use the .yml edit form. This textarea takes up too much space.

  

### Additional context

Recently discovered than many orphaned editions that would have otherwise been repaired by re-importing have been failing because the linked authors are deletes. It is blocking any imports that match on these existing records.

**Comment by LeadSongDog** [comment]
#5265 relates
