### ISSUE TITLE
Images require refresh when added

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4876]
Images do not display once added. Browser refresh is needed.

### Evidence / Screenshot (if possible)
<img width="866" alt="Screenshot 2021-03-24 at 09 54 12" src="https://user-images.githubusercontent.com/17739465/112282026-fe024500-8c86-11eb-9bca-72043633d6c5.png">

### Steps to Reproduce

1. Go to ...any record that needs an image. For example, https://openlibrary.org/books/OL27616833M/Family_Storms
2. Add a cover image.

* Actual: Image area goes/stays blank.
* Expected: Cover should be displayed once added.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 89.0.4389.90 (Official Build) (x86_64)
- **Operating system?** Mac Big Sur
- **Environment (prod/dev/local)?** prod

**Comment by LeadSongDog** [comment]
@seabelis Did you refresh your browser? I see the image you added.

**Comment by RayBB** [comment]
@LeadSongDog the original post says a refresh is need for the image to appear. This is about an issue with the uploading experience. Not a problem of the file actually getting saved.


I'll also note that if you switch to the "manage" tab on book cover the covers won't show up until the refresh.
This would probably be good to fix at the same time.

**Comment by LeadSongDog** [comment]
Arrgh! <auto-trout>
