### ISSUE TITLE
Structured data for book name improvement

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#4883]
Structured data validation on authors page shows Book `name` is a URL

![image](https://user-images.githubusercontent.com/905545/112417102-c16c4180-8d8b-11eb-855c-af4eae8d5e5e.png)

test URL: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fopenlibrary.org%2Fauthors%2FOL7235073A%2FGurney_Seed_Nursery_Co

Suggestion to fix: 
```
      <div class="resultTitle">
         <h3 itemprop="name" class="booktitle">
           <a itemprop="url" href="/works/OL17636653W?edition=CAT31309973"
              class="results">From the house of Gurney</a>
         </h3>
        </div>
```

I can't figure out how to make the Author show as `@type` `Organization` or `Person` rather than `Thing`

**Comment by Yashs911** [comment]
Hi, @hornc I would like to work on this issue.
For Author @type we can use:
```
<span class="bookauthor">by
        <a itemprop="author" itemscope itemtype="https://schema.org/Organization" href="/authors/OL7235073A" class="results">Gurney Seed &amp; Nursery Co</a>
</span>
```

**Comment by hornc** [comment]
@Yashs911 go for it, thanks!

I tried that `itemscope` and it kinda worked, but lost the url:
![image](https://user-images.githubusercontent.com/905545/112421970-ffba2e80-8d94-11eb-9037-e496b9216959.png)
 
It's on the right track though, you might be able to figure it out :)

**Comment by Yashs911** [comment]
@hornc the URL for both author and book have domain search.google.com instead of openlibrary.org
![image](https://user-images.githubusercontent.com/64412143/112424592-b6e58400-8d5a-11eb-99d4-29d685011541.png)
