### ISSUE TITLE
Cover upload modal: Finished button partially blocks links

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#4889]
When you upload a book cover with a long url the url wraps behind the button, which doesn't look great.

Additionally, the div around that button makes more than half of the "Add Another Image?" link unclickable. (see second screenshot)

### Evidence / Screenshot (if possible)

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/921217/112555520-768f0180-8d6c-11eb-9d41-afeb56ea3ed2.png)
![image](https://user-images.githubusercontent.com/921217/112555679-ba820680-8d6c-11eb-81db-4326e1502e96.png)
  
</details>

### Steps to Reproduce

1. Upload a cover with via a long url.

* Actual: Uploaded image url is partially blocked. Add another image link is partially blocked.
* Expected: Neither would be blocked.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Seen in Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Probably just need to rework the css and or html of where things are placed.

Edit:
Poking around at the source of the page it seems like this is a bit more complicated.
Basically the whole modal has a fixed height, within it there is an iframe with fixed height, and within that is where the buttons are.
If you change it so the button goes below the link, it will make the html within the iframe taller than the iframe height, and as such, out of view. That makes it seem like it would be rather messy to fix.

The simple fix would be:
1. hide the overflow of the url so it truncates
2. move the button from floating to be in the div right below the url
3. add a 5px margin to top and bottom of button

The result would be:

<details>
  <summary>This</summary>
  
![image](https://user-images.githubusercontent.com/921217/112557112-c15e4880-8d6f-11eb-87d4-c3b464810e5b.png)

</details>

Would be great if any designers had thoughts.

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/covers/saved.html

**Comment by ArunTeltia** [comment]
What if instead of showing the url we can just put the name ``` $_("Book Cover URL") ``` and wrap the text with the url, that will look much more cleaner according to me

**Comment by RayBB** [comment]
Currently, as soon as you hit "submit" your image is uploaded and saved.
The "finish" button, as far as I can tell, doesn't do anything other than close the window.

Given that the image is already uploaded and being used for the book, I agree that maybe we don't need to show the image in the modal. However, it would be nice to have #4502 fixed first so the user can see the image without having to refresh the page.

**Comment by RayBB** [comment]
I meant it would be nice to have #4876 fixed first.

**Comment by RayBB** [comment]
It seems this can also be an issue when uploading an image without a URL as well.

![image](https://user-images.githubusercontent.com/921217/113532821-051f3200-9568-11eb-97ef-a1e72f475cc1.png)

One possible solution is to use `display: flex` and have the image and the text next to each other like so:
![image](https://user-images.githubusercontent.com/921217/113532993-75c64e80-9568-11eb-95e7-a6f39d3c795d.png)
