### ISSUE TITLE
CSS zindex issue on mobile with top menu due to CSS transform

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#4924]
Cover image overlaps menues. Same as issue #4718

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/2772669/112758395-7dc54200-8fee-11eb-82ee-3d7c75a058df.jpeg)

![image](https://user-images.githubusercontent.com/2772669/112758532-41461600-8fef-11eb-8ebe-3d20108f94d5.jpeg)

### Relevant url?

https://openlibrary.org/books/OL32134402M/

### Steps to Reproduce

Go on mobile page of a work or edition with book cover and open left or right menu.

* Actual: menu under cover image
* Expected: menu above cover image

### Details

- **Logged in (Y/N)?** both
- **Browser type/version?** firefox mobile
- **Operating system?** iOS 
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
@bitnapper I am unable to reproduce the error on my (Android + Chrome)

**Comment by navneetsaluja** [comment]
Same, I'm unable to reproduce it as well. Try clearing the cache and trying again.

**Comment by RayBB** [comment]
Unable to reproduce iPad with firefox 33.0 (4119). Are you still seeing this issue? Is it on all works?

**Comment by bitnapper** [comment]
In all cases the latest Version. Can't reproduce on iPas Pro either but similar effects in latest Safari and Chrome on iPhone:

**Firefox after clearing**
![image](https://user-images.githubusercontent.com/2772669/112787162-40959a00-9058-11eb-9810-10308991fa9c.jpeg)

**Safari**
![image](https://user-images.githubusercontent.com/2772669/112787214-586d1e00-9058-11eb-818d-452c6b1ecc7b.jpeg)

**Chrome (iOS)**
![image](https://user-images.githubusercontent.com/2772669/112787231-615def80-9058-11eb-85bc-c10c28a557df.jpeg)

**Comment by bitnapper** [comment]
Also not limited to only one book. Heres another example from latest Safari, iOS, logged in:![image](https://user-images.githubusercontent.com/2772669/112787460-da5d4700-9058-11eb-8acb-c4846a1f1a07.jpeg)

**Comment by bitnapper** [comment]
iOS: 14.4.2 (18D70), iPhone 11 Pro

Firefox Daylight 33.0 (4119)
Chrome 87.0.4280.77

**Comment by ArunTeltia** [comment]
@bitnapper I checked this on my iphone this is definately an issue 
The behaviour of the bug 
when we click on one of the dropdown it hide behind the image but after we click on different dropdown we dont see that behaviour again

**Comment by jdlrobson** [comment]
can somebody summarize which browsers this a problem on? Is it just Safari?

I can replicate this on safari when I hover over the cover, so i'm pretty sure this relates to the CSS transforms on `.editionCover .cover-animation`.

Let's make sure when fixing this we don't descend into more z-index madness.

**Comment by ArunTeltia** [comment]
I checked it on I phone 11 safari @jdlrobson and I got the issue the thing about this issue 
Once you go to that page and press for drop down it was showing as the image is stating but after we click on somewhere else or scroll and after the scroll of we reclick on it the behaviour is no longer been seen and the behaviour of the drop down is as same as expected

**Comment by kmcgonigle** [comment]
I think a small CSS update will fix this issue. I plan to open a PR momentarily for review.

I am able to replicate (and fix) on my Mac OS desktop Safari browser (v.14.1.2), but I can't replicate on any other browsers or on the iOS Simulator in Xcode.

It would be very helpful if anyone who was able to replicate this issue could test the fix and see if it solves it on your browser version/device. Thanks all!
