### ISSUE TITLE
Extra information about graph gets overlapped by div

### ISSUE THREAD

**Issue by navneetsaluja** [internetarchive/openlibrary#4925]
When we hover over the graphs, it shows us the exact number of the said quantity. However, we aren't able to see this since its overlapped by the main div. Refer to the screenshots to understand more clearly.
### Evidence / Screenshot (if possible)
![grapph](https://user-images.githubusercontent.com/54721958/112769402-6b72f480-903e-11eb-94e0-414149b8b984.png)
![graph2](https://user-images.githubusercontent.com/54721958/112769403-6d3cb800-903e-11eb-93ed-49fd7f4f9a32.png)

### Relevant url?
 First ss: https://openlibrary.org/
Second ss:  https://openlibrary.org/subjects/in_library#ebooks=true

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Scroll down, hover over the rightmost graph, even though the other graphs should have the same problems.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** 87.0 (64-bit)
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

**Comment by ArunTeltia** [comment]
There are 2 things that we can do, we can delete the hover effect that is behind the chart div or we can make it appear above the chart 
but we have title that is appearing on the hover so i dont think there is a need of the inside hover we can simply delete the hover effect 
I like to work on this

**Comment by shrey27tri01** [comment]
I think this issue can be solved by adding `z-index: 100;` to the labels on hover so that they are visible over the chart if we hover over them. I have created a PR [here](https://github.com/internetarchive/openlibrary/pull/4976) for this. @jamesachamp could you please review it?

**Comment by schu96** [comment]
@mekarpeles @jimchamp 

Plot labels for the front page of OpenLibrary are all still hidden behind the ```contentBody``` div. 

![image](https://github.com/user-attachments/assets/bf737afb-435a-4207-9a2f-0a714827ae44)

It looks like it's just missing ```z-index : 100``` in ```plot.js -> plot_tooltip_graph -> showTooltip```. It'd be a straightforward PR for this but the charts are not populated for localhost:8080 so I'm not sure how to go about testing locally.
