### ISSUE TITLE
Error on isbn page: `TypeError("'NoneType' object is not iterable")`

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#4928]
This google https://www.google.com/search?q=%22https%3A%2F%2Fopenlibrary.org%2Fisbn%2F%22

Leads to https://openlibrary.org/isbn/9833782239
Which has an error message: `TypeError("'NoneType' object is not iterable")`

### Evidence / Screenshot (if possible)
<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/921217/112787064-62a90100-8ff3-11eb-94fe-7d9ccf438da7.png)

  
</details>

### Relevant url?
https://openlibrary.org/isbn/9833782239
https://openlibrary.org/isbn/141858028X

### Steps to Reproduce

1. Go to the url above

* Actual: Sees a not so helpful error
* Expected: Show a more user friendly error

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF and Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
https://openlibrary.org/search?q=9833782239&mode=everything&debug=true
Might help debug this issue.

**Comment by ahmedbilal** [comment]
The problem is with the following code

```python
def isbn_10_to_isbn_13(isbn_10):
    isbn_10 = canonical(isbn_10)
    if len(isbn_10) != 10 or not isbn_10[:-1].isdigit()\
        or check_digit_10(isbn_10[:-1]) != isbn_10[-1]:
            return
    isbn_13 = '978' + isbn_10[:-1]
    return isbn_13 + check_digit_13(isbn_13)
```

In my opinion, it should raise something like `raise ValueError("%s is not a valid ISBN 10" % isbn)` instead of return `None`

**Comment by RayBB** [comment]
Ah an interesting thing.

It turns out that first ISBN just has the 978 cutoff and would be 9789833782239
But the isbn 10 is 983378223X. At least according to [worldcat](https://www.worldcat.org/title/memoir-abdullah-cd-bahagian-ii-penaja-dan-pemimpin-rejimen-ke-10/oclc/848099445).

**Comment by RayBB** [comment]
On a related note today I was searching for this "isbn" listed on an ebay listing: 0133923612

It gets what appears to be the same error because the isbn isn't valid.

However, it is because the ebay poster posted part if the isbn 13 "978-0133923612" and the real isbn 10 is "0133923614".

Checking if the isbn prepended with 978 is valid would be nice. Some sites like gettextbooks.com do this.

**Comment by muster-mark** [comment]
There seems to be a wider issue here in that the HTTP status code is 200 even though there is an error.

**Comment by RayBB** [comment]
Seems like this is fixed now!
