### ISSUE TITLE
Tab order on Individual List Page is incorrect

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#4939]
I am testing accessibility of the individual list page per #4902.

Per the [WebAIM Keyboard Accessibility guidelines](https://webaim.org/techniques/keyboard/#navigation):
> As a keyboard user navigates through the page, the order in which interactive items receive keyboard focus is important. The default keyboard navigation order must be logical and intuitive. This generally means that it follows the visual flow of the page—**left to right, top to bottom**. 

After the header is tabbed through and we reach the content of the page this guideline is immediately broken. 
The tab order goes from right to left and bottom to top for the first five tabs. It goes: Edit > User > History > User > Lists. 

It is my understanding that this should be changed to: User > Lists > User > History> Edit.

### Evidence / Screenshot (if possible)

https://user-images.githubusercontent.com/921217/112925839-3bfbd080-90ae-11eb-9d92-9a4d7507f4e5.mp4

### Relevant url?
https://openlibrary.org/people/mekBot/lists/OL103955L/Childhood_Favorites

### Steps to Reproduce

1. Go to page, use the tab key to see what elements are selected.

* Actual: Order went from right to left. (Edit > User > History > User > Lists)
* Expected: Order goes from left to right and top to bottom.  (User > Lists > User > History> Edit)

### Stakeholders
@bpmcneilly

**Comment by Yashs911** [comment]
@RayBB I would like to work on this issue.

**Comment by Yashs911** [comment]
@RayBB for tablet view EDIT button is shifted to the left and after fixing the alignment issues(I will create a PR).
The order looks correct:
![image](https://user-images.githubusercontent.com/64412143/114383092-c5c99480-9baa-11eb-9947-4c84e7c50859.png)
So I was a little confused but according to me we should give priority to destop

**Comment by RayBB** [comment]
@Yashs911 please do work on this if you're interested :)

I agree that the desktop view should take preference for tab order.

In my opinion we should keep the edit button consistent to have it in once place across different views as much as possible. But perhaps that's a different issue.
