### ISSUE TITLE
Make a systematic analysis of Python bytes/str conversions

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4941]
I am frustrated by [Python bytes vs. string](https://github.com/internetarchive/openlibrary/issues?q=label%3A%22Python+3%3A+bytes+vs.+str%22+) bugs and sometimes related [Unicode](https://github.com/internetarchive/openlibrary/issues?q=label%3A%22Theme%3A+Unicode) bugs.

### Describe the problem that you'd like solved

We should make a systematic analysis of where we do these conversions to find existing bugs and avoid new ones.  `bytes.decode()` and `str.encode()` should be called less often now that we are using `requests`. 

### Proposal & Constraints

*  [ ] Would it be useful to monkey patch `bytes.decode()` and `str.encode()` to find out where, how often, and with what parameters they are being called.
* [ ] Can Sentry help us find bytes/str issues and track improvements?
* [ ] Where are we encoding/decoding to 'ascii' which is losing important information? `normalize()`, `strip_accents()`
* [ ] Where should we add more Üñîçø∂é examples to our tests?
* [ ] Could we use the ___Language Server___ to find where we use these functions?

**Comment by dhruvmanila** [comment]
Another idea I got today was:
1. Analyze and list out all the functions and methods which uses either of the conversion (encoding/decoding)
2. Start putting type hints for those functions/methods one at a time.

The process itself will tell us more information regarding what the function is doing and why are we encoding/decoding and at the end we could conclude if we even need to do the conversion.
