### ISSUE TITLE
Import and export options page design is not responsive

### ISSUE THREAD

**Issue by shrey27tri01** [internetarchive/openlibrary#4971]
On visiting the [Import and Export Options](https://openlibrary.org/account/import) page after logging in on a mobile device, the "Import from Goodreads" option and "Export your Reading Log" option occur side-by-side (like how they would look on a desktop) instead of a responsive layout.

### Evidence / Screenshot (if possible)
![2021-04-03](https://user-images.githubusercontent.com/52366674/113444219-16a1f600-9411-11eb-8c5e-4d8c3bd92bac.png)

![2021-04-03 (1)](https://user-images.githubusercontent.com/52366674/113444227-199ce680-9411-11eb-8160-9fc28a8f16f6.png)

### Relevant url?

https://openlibrary.org/account/import

### Steps to Reproduce

1. Visit https://openlibrary.org/account/import on a mobile device or open developer tools -> toggle mobile view on a desktop
2. Login

* Actual: The options occur side-by-side, in a desktop fashion
* Expected: Responsive view for the "Import from Goodreads" option and "Export your Reading Log" options

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Brave v 1.22.71
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

This is most likely a flexbox issue

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/import.html
https://github.com/internetarchive/openlibrary/blob/master/static/css/page-user.less

**Comment by Yashs911** [comment]
@shrey27tri01 I would like to work on this.
