### ISSUE TITLE
Add to list button is too big on page of orphaned book

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#4987]
The add to list button is very big on this page with an orphaned book. Probably related to #3561

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/921217/113540899-c9429780-957c-11eb-86fd-37a55124c165.png)

### Relevant url?
https://openlibrary.org/books/OL9475434M/Pokemon_The_First_Movie_Animation_Comics?edition=

### Steps to Reproduce

1. Go to the page

* Actual: Button expands beyond parent div
* Expected: Button stays in parent div

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Brave
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
@RayBB I would like to work on this issue.

**Comment by RayBB** [comment]
@Yashs911 sounds good
