### ISSUE TITLE
Work subtitles do not appear at top of page

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4991]
Subtitles for works do not appear at the top of the page. 

### Evidence / Screenshot (if possible)

<img width="412" alt="Screenshot 2021-04-06 at 18 16 54" src="https://user-images.githubusercontent.com/17739465/113743747-4d735700-9704-11eb-8df0-a9a90ce31605.png">
### Relevant url?
For example, https://openlibrary.org/works/OL38479W/King_of_the_Vagabonds?edition=

### Steps to Reproduce

1. Go to a work with a subtitle.
2. Do notice that the subtitle is not displayed at the top of the page.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Frequently subtitles are not important and can be omitted from the work title altogether. However, in some cases the subtitle is very important or the most important part of the title (frequently for series volumes). This information should be visible at the top of the page with the title.

### Related files
Related to #3561.

**Comment by Yashs911** [comment]
@seabelis PR https://github.com/internetarchive/openlibrary/pull/4960 Fixed this issue.
