### ISSUE TITLE
No direct way to view/edit work covers

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4992]
Since the new book page launch, work covers have only been editable by appending the work url.

### Relevant url?
https://openlibrary.org/books/OL24211805M/King_of_the_Vagabonds/edit
https://openlibrary.org/works/OL38479W/King_of_the_Vagabonds/manage-covers
https://openlibrary.org/works/OL38479W/King_of_the_Vagabonds/add-cover

### Steps to Reproduce

1. Go to https://openlibrary.org/books/OL24211805M/King_of_the_Vagabonds/edit
2. Click the Work Details tab.
2. Do notice there is no work cover displayed and no way to edit it.

* Actual: No way to view/edit the work cover from the edit page.
* Expected: When going to the edit work form, the cover should be visible as well as a way to edit it.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
At the very least, links to manage and add a cover to the work should be present and the current cover should be visible.

### Related files
Related to #3561

**Comment by cclauss** [comment]
Is there another URL that exhibits this problem?  For me, this page has a cover and works as expected.

**Comment by seabelis** [comment]
@cclauss I've added one more step to reproduce. You must go to the Work Details tab.

**Comment by RayBB** [comment]
@mekarpeles I'm interested in working on this. Can you assign to me?
Any context on why this wasn't added before or complexities that may come up?

**Comment by mekarpeles** [comment]
@RayBB I know you've been busy w/ your new job! Would you like me to free the `assignee` for this one? :)

**Comment by RayBB** [comment]
@seabelis based on a recent discussion with @mekarpeles we've really shifted away from the the works focus and are now surfacing editions more prominently. I don't think that (at least according to @mekarpeles) we want to be able to select/edit covers for works because we'll be surfacing the edition cover instead.

I'll close this for now but if either of you feel differently please let me know and reopen this issue.
