### ISSUE TITLE
Can we merge requirement*.txt files from three down to two?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#4994]
I am always frustrated when I am looking to update a Python dependency that I need to look at three requirements files instead of just two.

### Describe the problem that you'd like solved

This repo currently has:
1. requirements.txt
2. requirements_common.txt
3. requirements_test.txt

Would it be a good idea to simplify and merge requirements so that we just have:
1. requirements.txt
2. requirements_test.txt  # imports requirements.txt to avoid errors.

Or is there some logic to having three files?

### Stakeholders

@dhruvmanila

**Comment by RayBB** [comment]
@cclauss 
Have you considered the `extras_require` field in setup.py?
I'm not familiar with our build/setup process but I've seen this used for dev dependencies on other projects and it seems to work fine. Not sure if there is any downside to it.

```
setup({
    install_requires=requirements,
    extras_require={
        'dev': [
            'pytest',
            'pytest-pep8',
            'pytest-cov'
        ]
    }
})
```

Here's a SO link giving an example: https://stackoverflow.com/a/28842733/620699

**Comment by cclauss** [comment]
Thanks, @RayBB but I like the explicit nature of requirements files instead of hiding those details in `setup.py`.  With requirements files, we can install our dependencies separate from performing other setup tasks.

**Comment by dhruvmanila** [comment]
Here's what I found out:
```console
❯ rg 'requirements\.txt' ./

❯ rg 'requirements_common\.txt' ./
./requirements.txt
1:-r requirements_common.txt

./requirements_test.txt
5:-r requirements_common.txt

./docker/Dockerfile.olbase
74:RUN python3.8 -m pip install --default-timeout=100 -r requirements_common.txt \
75: && python3.9 -m pip install --default-timeout=100 -r requirements_common.txt

❯ rg 'requirements_test\.txt' ./
./scripts/solr_builder/Dockerfile.olpython
7:RUN pip install -r requirements_test.txt

./scripts/2018/10/bootstrap.sh
48:PYTHON_PACKAGES=$OL_ROOT/requirements_test.txt

./docker/Dockerfile.oldev
16:RUN python3.8 -m pip install -r requirements_test.txt
17:RUN python3.9 -m pip install -r requirements_test.txt
```
- `setup.py` has its dependencies listed out in the file itself, so its not relying on any of the said requirements file.
- `requirements_common.txt` as the name suggests, is a list of common dependencies for testing and development purposes.
- `requirements.txt` is never used, atleast internally. It might be used for the developer to install the necessary dependencies. 

As seen above, `Dockerfile.olbase` is using `requirements_common.txt` and `Dockerfile.oldev` is using `requirements_test.txt`, so are we not using `requirements.txt` ever? If so, then how is the `requests` library which is in `requirements.txt` being installed as that is being used throughout openlibrary?

Also, running a quick `rg` for the listed dependencies gives me that some of them aren't being imported or used anywhere in the openlibrary project namely: `clint`, `decorator`, `ecdsa`, `schema`. I haven't looked at others.

**Comment by cclauss** [comment]
Nice.  I believe that `setup.py` Is also never used.  Open Library is not a package on PyPI and we never do or recommend doing `pip install openlibrary`.  Based on your findings above, a sane, phased approach would be:
1. Remove `requirements.txt`, test and the do a weekly deployment to ensure nothing breaks.
2. Rename `requirements_common.txt` to `requirements.txt`, test and do a weekly deployment.
3. Remove `setup.py`, test and the do a weekly deployment to ensure nothing breaks.

@cdrini, @mekarpeles Your thoughts?

**Comment by dhruvmanila** [comment]
Taking further look at the dependencies and as mentioned in my previous comment, the `requirements.txt` file is never used to install any dependencies.

So, I looked into the Docker environment about which `pip` packages were being installed (using `requirements_test.txt`) and found out this:

<details>
<summary><code>pip</code> packages inside Docker web service:</summary>

```console
$ pip list
Package                       Version
----------------------------- -----------
amightygirl.paapi5-python-sdk 1.0.0
attrs                         20.3.0
Babel                         2.9.0
backports.csv                 1.0.7
beautifulsoup4                4.9.3
certifi                       2020.12.5
chardet                       4.0.0
cheroot                       8.5.2
click                         7.1.2
contextlib2                   0.6.0.post1
DBUtils                       1.3
debugpy                       1.2.1
Deprecated                    1.2.12
docopt                        0.6.2
dparse                        0.5.1
eventer                       0.1.1
flake8                        3.9.0
flup-py3                      1.0.3
Genshi                        0.7.5
gunicorn                      20.1.0
idna                          2.10
iniconfig                     1.1.1
internetarchive               1.9.9
isbnlib                       3.10.6
jaraco.functools              3.3.0
jsonpatch                     1.32
jsonpointer                   2.1
lxml                          4.6.3
mccabe                        0.6.1
more-itertools                8.7.0
mypy                          0.812
mypy-extensions               0.4.3
packaging                     20.9
Pillow                        8.1.2
pip                           21.0.1
pluggy                        0.13.1
psycopg2                      2.8.6
py                            1.10.0
pycodestyle                   2.7.0
pyflakes                      2.3.1
Pygments                      2.8.1
pymarc                        4.0.0
pymemcache                    3.4.1
pyparsing                     2.4.7
pytest                        6.2.3
python-dateutil               2.8.1
python-memcached              1.59
pytz                          2021.1
PyYAML                        5.4.1
requests                      2.25.1
safety                        1.10.3
schema                        0.7.4
sentry-sdk                    1.0.0
setuptools                    49.2.1
simplejson                    3.17.2
six                           1.15.0
Sixpack-client                1.2.0
soupsieve                     2.2.1
statsd                        3.3.0
toml                          0.10.2
tqdm                          4.60.0
typed-ast                     1.4.2
typing-extensions             3.7.4.3
urllib3                       1.26.4
validate-email                1.3
web.py                        0.62
wheel                         0.36.2
wrapt                         1.12.1
```
</details>

Taking the diff will give you the result that only the following packages from `requirements.txt` are present in the `pip` list ***which aren't being installed using `requirements.txt`, they are installed as the dependencies of packages in `requirements_common.txt`*** 
- `requests`
- `python-dateutil`
- `schema`

**BUG:** The big problem here is that `requests` package is never installed as a direct dependency, it is only installed as an indirect dependency of some other package. We rely heavily on the `requests` package.

Continuing with what @cclauss mentioned, our first step should be to transfer the three listed dependencies from `requirements.txt` to `requriements_common.txt` and then rename `requirements_common.txt` to `requirements.txt` ***along with changing the references of `requirements_common.txt` as well.***

After that, we can then start pruning the unused dependencies after concluding whether they are ever used in the entire codebase directly or indirectly.

**Comment by cdrini** [comment]
> Our first step should be to transfer the three listed dependencies from `requirements.txt` to `requriements_common.txt` and then rename `requirements_common.txt` to `requirements.txt` along with changing the references of requirements_common.txt as well.

That sounds perfect; great find! I confirmed I can find no references whatsoever to `requirements.txt` in our codebase.

**Comment by cdrini** [comment]
Note setup.py is used only for `cython`izing certain files during the solrbuilder flow ; it's not used for installing dependencies (those should be removed from that file).

**Comment by cclauss** [comment]
Please make sure there is ___a comment___ near the top of `setup.py` to explain when and how that file is used.
