### ISSUE TITLE
Search API language-filtering does not work currently

### ISSUE THREAD

**Issue by waldenn** [internetarchive/openlibrary#4996]
The web interface is able to do language filtering, but the search API is currently not. 

As the search API documentation implies you can just add ".json" to the search end-point, combined with the fact that language-filtering is important for many readers, I marked this a bug (instead of a feature request / enhancement).

**Evidence / Screenshot (if possible)**

Example 1:

https://openlibrary.org/search?mode=ebooks&q=romeinen&has_fulltext=true&language=dut (5 results)
https://openlibrary.org/search.json?mode=ebooks&q=romeinen&has_fulltext=true&language=dut (0 results)

Example 2:

https://openlibrary.org/search?mode=ebooks&q=%22Remy%22&has_fulltext=true&language=fre (424 results)
https://openlibrary.org/search.json?mode=ebooks&q=%22Remy%22&has_fulltext=true&language=fre (0 results)

**Proposal & Constraints**

Add the same language-filtering logic as seen in the web-interface to the search API.

There may be other missing Search API filters (I will check them later), but the language filter is quite important IMHO.

**Comment by lephemere** [comment]
I tested other filters available in the search web interface and the following didn't work with the search API as well:
- author_key
- subject_facet
- person_facet
- place_facet
- time_facet
- first_publish_year
- publisher_facet
