### ISSUE TITLE
Is there a way to limit the page-size of search API requests?

### ISSUE THREAD

**Issue by waldenn** [internetarchive/openlibrary#4999]
### Question
Is there a way to limit the page-size of search API requests?

The default Search-API page-size is 100 items: http://openlibrary.org/search.json?q=the+lord+of+the+rings

I would like to reduce the page-size (limit) for Search API calls, since the user can just 'page' through the results if he/she wants. Fetching more results also requires more processing on the client-side.

Side notes:
- The number is 20 for the search-inside API: http://openlibrary.org/search/inside.json?q=thanks%20for%20all%20the%20fish
- I think both default page-sizes should probably be the same (20 seems like a reasonable number to me).
- The Archive.org API has the "limit" parameter to do this.

Thanks!

**Comment by cdrini** [comment]
`limit=1` will set the page size for both of them. It looks like there is a bug with /search/inside ; it's erroring when limit is set!

**Comment by waldenn** [comment]
Ah sorry, I overlooked applying "limit" to the Search-api, as I did not see it documented.

Thanks for looking into the inside-search issue too!
