### ISSUE TITLE
Check if MARC records imported are still current

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#500]
Example: OL15162854M was created from a UofT Marc by importbot on 18 Sep 2008. That imported record is stale. A search at that library finds that same record 670101s1941 now shows an oclcno 221428809. Perhaps a periodic scan-for-change on existing Marcs is in order. Once a year would go a long way.

**Comment by tfmorris** [comment]
I think this is overly ambitious given our current resources. Typically MARC records are acquired in batches, so we don't even have a link back to an online searchable source. At scale we'd also run into the problem of resolving edit conflicts and trying to figure out which edits were "best" by some metric.

**Comment by guyjeangilles** [comment]
@hornc Do you have a plan to address Tom's concerns?

**Comment by mekarpeles** [comment]
I agree with @tfmorris -- in the future, we can just re-import new MARCs and e.g. ignore conflicting fields
