### ISSUE TITLE
Covers API Goodreads ID Not Functional

### ISSUE THREAD

**Issue by teusday** [internetarchive/openlibrary#503]
It appears the "/goodreads/[$value]" pattern is broken for the covers API.
For example, the covers API demo page features Zen Speaks. The [ISBN URL](http://covers.openlibrary.org/b/isbn/9780385472579-S.jpg?default=false) still works, but the [goodreads URL](http://covers.openlibrary.org/b/goodreads/979250-S.jpg?default=false) does not.

**Comment by mekarpeles** [comment]
Hi @teusday, thanks for submitting this issue. Can confirm this is an issue with the link you reference (i.e. the one from the docs @ https://openlibrary.org/dev/docs/api/covers) and for librarything as well. It's unclear to me that a goodreads ID does exist for this cover.

@hornc et al -- was this something which was working in the past? Do we know of a goodreads cover id which works? 

Timeline: @teusday, I don't think core team has the bandwidth to prioritize this at the moment, but we're open to reviewing a fix if anyone has an idea of the cause.

From a cursory crawl, cover retrieval is defined in
https://github.com/internetarchive/openlibrary/blob/d0ad3cc991616c7e5d7acb69527a100d423ac5c8/openlibrary/plugins/upstream/models.py#L507

**Comment by guyjeangilles** [comment]
The goodread's link still isn't working properly. @hornc Are you willing to be assignee for this issue? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts.

**Comment by gnncl** [comment]
Hi,
I tried it but it doesn't come with cover data with goodreads id

**Comment by mekarpeles** [comment]
this is the OL page which does have an goodreads id in the OL metadata:
https://openlibrary.org/books/OL7440033M/Zen_Speaks

This goodreads id I don't believe is in cover store's the database

**Comment by mekarpeles** [comment]
Is there anyone who would be absolutely devastated if we deprecate coverstore lookup by goodreads?

**Comment by RayBB** [comment]
Considering that it hasn't been working for so many years I think it's safe to remove this functionality formally.
@mekarpeles where does this code even live? I can't find any mention of goodreads in coverstore.

**Comment by RayBB** [comment]
@hornc if there is no plan to fix this then maybe we should remove the code or update the docs to say this is broken with no plan to fix? https://openlibrary.org/dev/docs/api/covers

**Comment by hornc** [comment]
@RayBB thanks for the reminder, I have never seen this functionality work, and wasn't sure where it was referenced -- I've edited that page to remove the references
