### ISSUE TITLE
Issue with local developer environment (pyenv + web_1)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5039]
### Evidence / Screenshot (if possible)

Patrons reporting issues with pyenv and docker-compose encountering an issue with `web_1`.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Perhaps try #5040

**Comment by dhruvmanila** [comment]
As mentioned by @cdrini, doing a `docker-compose build --pull web` will upgrade the local image to the latest. Another thing to keep in mind is to not be in a virtual environment created by you when you are doing `docker-compose up` as that will alter the `PYENV_VERSION` environment variable which is used to set the correct Python version to run in the docker container.

**Comment by Evazisouli** [comment]
Hello, I've followed the instructions but I' m getting an error for solr-updater_1. I' m attaching a screenshot, if it helps.
![Screenshot_3](https://user-images.githubusercontent.com/56540005/114538958-a0955e80-9c5c-11eb-88b8-fbbd82ca9c04.jpg)

**Comment by dhruvmanila** [comment]
That would probably be the case if you don't have the `infogami` submodule. Try running the following command:
```
$ git submodule update --init
```

**Comment by Evazisouli** [comment]
Should I run this command in directory openlibrary or inside docker directory?

**Comment by dhruvmanila** [comment]
In the root of the project.

**Comment by Evazisouli** [comment]
Okay, thank you! However I get the same errors as earlier... It's like it can't have access to infogami regarding its location.

**Comment by dhruvmanila** [comment]
Can you provide me with some more details? Like what steps did you take until this error occurred? I won't be able to help without some context.

**Comment by Evazisouli** [comment]
Yes, of course. I have built the images in docker following the tutorial video and I have upstreamed my repo with the latest master and run the docker-compose build --pull web command. Then, I ran the command you provided for infogami and after that I ran the docker-compose up command and I still got the same errors as the screenshot I have provided earlier, so I don't have access to the localhost.

**Comment by cdrini** [comment]
Hi @Evazisouli ! Here are some things that might help:

(1) Did you follow the symlink instructions for Windows folks in the Troubleshooting section here: https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#for-windows-users-only . That might cause some issues like this.

(2) Try resetting your docker environment following the instructions here: https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#fully-resetting-your-environment

(3) If that doesn't work, you can try checking out infogami locally? It should already be in the docker container, but just in case:

```sh
git submodule init
git submodule sync
git submodule update
```

And if none of that works, just as a sanity check, let's check the versions of things. Here's what's on my machine (I'm also one of the Windows people :) ): 

```sh
$ docker --version
Docker version 20.10.5, build 55c4c88
$ docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f
$ git --version
git version 2.22.0.windows.1
```

**Comment by Evazisouli** [comment]
Hi @cdrini! Thank you so much for your help! It finally worked and I managed to get access to the localhost!

**Comment by cdrini** [comment]
Wonderful! I'm glad it worked :) Would you mind sharing what did the trick? Us windows users tend to have a number of issues with docker, so it might help someone else :)

**Comment by mekarpeles** [comment]
@Evazisouli when you get a chance, can you please update this issue with which step fixed your problem?

And then we will close this issue :)

**Comment by Evazisouli** [comment]
Hello! Yes of course! The issue I had was linked with the `infogami` submodule, as I understood. 

So, I run the command `git submodule update --init` at first.
 
Then, I followed the steps @cdrini suggested and I think that the ones that fixed my problem and therefore gave me access in the localhost were the following commands:

`git submodule init`
`git submodule sync`
`git submodule update`

**Comment by cdrini** [comment]
Awesome, thank you @Evazisouli !
