### ISSUE TITLE
Library Explorer: Other languages list filter

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5042]
In the Library Explorer, the other languages filter list is partially hidden.
Moreover, when navigating with keyboard arrows, going up select the item below the selected one and going down select the item above, which is counterintuitive.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/73437497/114535585-7f2e7580-9c50-11eb-87e2-44381e477a66.png)

### Relevant url?

https://openlibrary.org/explore

### Steps to Reproduce

1. Click on `Filter` on the floating bottom panel
2. Click on `Other...` in the `Language` section to open the list

* Actual: Hidden list items and inversed keyboard navigation
* Expected: No always hidden items in the list and intuitive keyboard navigation 

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF87
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Related files

Floating controls panel is defined here:
[openlibrary\components\LibraryExplorer\components\LibraryToolbar.vue](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue)

**Comment by Yashs911** [comment]
@lephemere I would like to work on this issue.
I think the keyboard arrows behavior is due to the `flex-direction: column-reverse;` to solve this, we can use `flex-direction: column` and arrange the list in the order we want.
