### ISSUE TITLE
Book Widget fails for Redirects after books merged

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5046]
When a book is merged, iframes which reference the pre-merged work show the entire open library books page rather than the widget view.

https://openlibrary.org/works/OL1063339W/How_to_win_friends_and_influence_people/widget

Should look like this:
![openlibrary org_books_OL21094918M_How_to_win_friends_and_influence_people_widget](https://user-images.githubusercontent.com/978325/114756688-dcd5c700-9d0f-11eb-8d05-349db154e385.png)

But instead redirects to the new page (not in widget view)

### Evidence / Screenshot (if possible)

https://openlibrary.org/works/OL1063339W/How_to_win_friends_and_influence_people/widget
should look like...
https://openlibrary.org/books/OL21094918M/-/widget

**Comment by STAMATIOSL** [comment]
Can I take this issue?

**Comment by STAMATIOSL** [comment]
The code linked with the issue is in the https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lists/widget.html ? @mekarpeles

**Comment by arimanyus** [comment]
Hey @STAMATIOSL, are you looking into this?

**Comment by STAMATIOSL** [comment]
@arimanyus No, you can go for it!

**Comment by pranjii** [comment]
Can I do this??

**Comment by sagnik2001** [comment]
Can I work on this ?

**Comment by tuminzee** [comment]
> @arimanyus No, you can go for it!

Hello @arimanyus are you still working on the issue?

**Comment by ejgonzalez17** [comment]
Hi , I would like to work in this Issue .

**Comment by mekarpeles** [comment]
The code for the widget is here
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L242-L262

The html is here
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/widget.html

The step to fix this:
In https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L246 after we have the olid -- i.e. `web.ctx.site.get(olid)`, we need to check its infogami type to see if it's a `redirect`. If it is, we need to do a while loop to keep doing `web.ctx.site.get(olid)` until we no longer have a redirect. 

@arimanyus, if you're available, why don't you take a shot at it? :)

**Comment by Shofiya2003** [comment]
Can I work on this issue?

**Comment by tuminzee** [comment]
@arimanyus how you are doing so far. Do you need any help?
If you are occupied let me know, than I can assign this issue to @Shofiya2003

**Comment by mekarpeles** [comment]
@Shofiya2003 I'd say give it a shot! I'll assign you :)

**Comment by Shofiya2003** [comment]
Thanks a ton. I am starting to work on it and will get back to you if I need any help.

**Comment by Shofiya2003** [comment]
Hello
I have made changes but I am having a tough opening the webpage using gitpod to check the changes. Do I need to set up the project on my local machine. I need help.

**Comment by mekarpeles** [comment]
@Shofiya2003 did you have any other questions?

**Comment by mekarpeles** [comment]
should be solved by #7059
