### ISSUE TITLE
add discussion tab on github

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#5078]
Problem:
The issue with putting discussions in the issue section is that the 'issue' gets closed by others. This halts discussions before it gets to where it needs to go.

Solution:
Add a discussion tab, so that people can freely talk about what they need to. People shouldn't have to wait until the community meeting to get out what they have to say and brainstorm.

**Comment by RayBB** [comment]
None of the repos I've seen lately have discussions turned on so I don't have experience with it but it looks handy.

There are docs about it here for those who are curious:
https://docs.github.com/en/discussions

There communities that use it though are: https://github.com/gatsbyjs/gatsby/discussions and https://github.com/nodejs/node/discussions

Some of the features of it that are nice at first glance include:
* Converting issues to discussions
* Upvoting (much easier to see issues many people care about than looking at reacts)
* Q/A format 
* Some level of threading

Some questions/concerns:
* How will we decide what is an issue vs what is a discussion? We should have this documented and clear for contributors.
* Training people to use discussions tab
* How will discussions tab be monitored/triaged?
* Can we get on the "Communities using discussions" section of the github docs 🤔
* What examples do we have of issues that were closed before they got where they needed to go?


Generally I think it is worth looking into more. I may play around with it myself on some repos.

**Comment by BrittanyBunk** [comment]
@RayBB thanks for looking into it. 

- The ones that should be a discussion are issues that the OL staff don't want to work on that get closed because they are half-baked ideas that need to be thought out through more and shouldn't be closed.
- I'm not worried about categories. As it grows, it's not hard to group everything, but I prefer not to categorize it. Just treat it like the issues for now - a long flow.
- I wouldn't say it's hard to train people if the documentation's there - you just point people to your article
- it gets monitored by the people there. Obviously someone can be assigned to moderate it, but like all forums, it's up to those in the forum to monitor it
- idk - I haven't used github docs
- if you look at my issues and the places I wrote that it shouldn't've been deleted, you can see proof there
- if there aren't that many discussions (I don't see too many), we don't have to worry about categories and tags. That's much later.

**Comment by mekarpeles** [comment]
Not intended to use discussions tab yet / for now. Closing as will not fix :)
