### ISSUE TITLE
Add OpenSearch so that open library can easily be searched from FireFox

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5097]
### Describe the problem that you'd like solved
Right now, chrome automatically adds open library as a search engine using it's [tab search](https://www.chromium.org/tab-to-search) feature.

I like to use Firefox and right now it does not detect search on openlibrary and as such doesn't offer to add OL as a search engine.

### Proposal & Constraints
I propose that we follow [these docs](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) to make it easy to add OL as a search engine.
It seems like the implementation would be just adding one xml file and one line to the head element of OL pages.

### Additional context
At the end we can have something like this
![image](https://user-images.githubusercontent.com/921217/116029743-ac3a3b00-a5f5-11eb-9d8a-957e78967b87.png)

Here are some examples of how this is used:
https://groups.google.com/g/opensearch/c/bSM_Z-Ds7L4

**Comment by mekarpeles** [comment]
Go for it, if you'd like to try!!
