### ISSUE TITLE
need simple way to get/create OL edition from iaid

### ISSUE THREAD

**Issue by mikemccabe** [internetarchive/openlibrary#51]
This comes up from lending - I frequently get a list of books to load into lending from a library partner, but find that there's no corresponding edition/work to add lending subjects to.

This is a job for the import API, I think...

Please reassign to me when there's an import API pathway for this.  (Or if there already is one!)

From the latest batch:

williamhenrymoor00defo
meadorsmeadows00mead
updatedmorgangen00morg
ancestryofrevwal1985morg
alongwaywithbenj00morr
morrowsrelatedfa00morr
genealogiaeordat00mors
forebearsdescend00mars
descendantsofhug00cham
searchforwestmos00mosl
georgemoseleyrev00cawt
jamesmosmanearly01mosm
jamesmosmanearly02mosm
mottstreet00mott
muhlenbergsofpen00wall
descendantsofjon00murr

and from an earlier set:

21_Success_Secrets_9781576759189
301_Ways_to_Have_Fun_at_Work_9781605092690
A_Game_As_Old_As_Empire_9781576757987
A_Peacock_in_the_Land_of_Penguins_3rd_9781605092522
A_Simpler_Way_9781605092546
A-Complaint-Is-A-Gift-9781576759462
Abolishing_Performance_Appraisals_9781605093956
Accidental_Genius_2nd_9781605096513_ePDF
Affluenza_9781605096476
Agenda_for_a_New_Economy_2nd_9781605093765
Aligned_Thinking_9781605091457
Alternatives_to_Economic_Globalization_9781605094090
Analysis_for_Improving_Performance_9781576755303
Appreciative_Inquiry_9781605092812
Attracting_Perfect_Customers_9781605098494
Be_a_Sales_Superstar_9781605098364
Be_the_Hero_9781576759998
Be_Your_Own_Brand_2nd_9781605098111
Branded_Customer_Service_9781576758861
Catch_9781605093802
Change_Is_Everybodys_Business_9781605093680
Change_Your_Questions_Change_Your_Life_2nd_9781605094304
Community_9781576757734
Confessions_of_an_Economic_Hitman_9781576755129
Cracking_the_Code_9781576755334
Cultural_Intelligence_2nd_9781576757994
Downshifting_9781576759905
Driving_Growth_Through_Innovation_9781576755549
Eat_That_Frog_9781576755044
Emotional_Discipline_9781576759622
Emotional_Value_9781605097244
Empowerment_Takes_More_than_a_Minute_9781605093390
Evaluating_Training_Programs_9781576757963
Finding_Our_Way_9781605091464
Flight_Plan_9781576755563
Full_Steam_Ahead_2nd_9781605098760
Fun_Works_9781576755181
Future_Search_9781605094298
Gangs_of_America_9781605097121
Get_Paid_More_And_Promoted_Faster_9781576758021
Get-There-Early-9781576755310
Getting_Things_Done_When_You_Are_Not_In_Charge_9781605092843
Go_Team_9781605093413
Goals_2nd_9781605094120_ePDF
Helping_9781576758724
Hot_Spots_9781605092973
How_to_Get_Ideas_9781605093017
How_to_Make_Collaboration_Work_9781605092850
Ideas_Are_Free_9781605090177
Ideaship_9781605093369
Intrinsic_Motivation_at_Work_2nd_9781576755921
Know_Can_Do_9781605093376
Leadership_and_Self-Deception_2nd_9781576759783
Leadership_and_the_New_Science_3rd_9781605091471
Leadership_From_the_Inside_Out_9781576759806
Love_It_Dont_Leave_It_9781576758755
Macroshift_9781576751787
Magnetic_Service_9781605096421
Managers_Not_MBAs_9781576755112
Managing_9781576758953
Networking_for_People_Who_Hate_Networking_9781605096070_ePDF
No_More_Regrets_9781605098876_WEB
One_From_Many_9781605090184
Open_Space_Technology_3rd_9781576757758
Out_of_Poverty_9781576755488
PeopleSmart_9781605098500
Performance_Consulting_2nd_Edition_9781576757772
Power_and_Love_9781605093055
Prisoners_of_Our_Thoughts_2nd_9781605099217
Repacking-Your-Bags-9781576758762
Running_Training_Like_a_Business_9781605096407
Salsa_Soul_and_Spirit_9781576755228
Screwed_9781576755297
Seeing_Systems_9781576755358
Shifting_Sands_9781576759769
Solving_Tough_Problems_9781576755372
Sprout_9781605092836
Synchronicity_2nd_9781609940188
Terms_of_Engagement_2nd_9781605094489
The_3_Keys_to_Empowerment_9781605093406
The_100_Absolutely_Unbreakable_Laws_of_Business_Success_9781576757949
The_Anatomy_of_Peace_9781576759554
The_Answer_to_How_Is_Yes_9781605093949
The_Blind_Men_and_the_Elephant_9781605096124
The_Change_Handbook_9781576755099
The_Courageous_Follower_9781605092744
The_Great_Turning_9781576755396
The_Hamster_Revolution_9781576755754
The_Introverted_Leader_9781576755877
The_Laws_of_Lifetime_Growth_9781576755051
The_Leadership_Wisdom_of_Jesus_3rd9781609940058
The_Nonverbal_Advantage_9781576757741
The_One_Minute_Negotiator_9781605096209
The_Post-Corporate_World_9781605093963
The_Power_of_Appreciative_Inquiry_2nd_9781605093291
The_Power_of_Failure_9781605093895
The_Power_of_Purpose_2nd_9781605095271
The_Referral_of_a_Lifetime_9781576758670
The_Resiliency_Advantage_9781605091501
The_Secret_9781605094700
The_World_Cafe_9781605092515
Theory_U_9781576758663
Trust_and_Betrayal_in_the_Workplace_9781576759493
Turning_to_One_Another_2nd_9781576759844
Unequal_Protection_2nd_9781605095608
We_Are_All_Self-Employed_9781605093840
Whistle_While_You_Work_9781576759523
Your_Leadership_Legacy_9781605096308
Zenobia_9781576755495

**Comment by mekarpeles** [comment]
Hopefully importbot is now handling this gracefully.
