### ISSUE TITLE
"Thank you very much for improving that record" message causes content on page to shift

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5103]
"Thank you very much for improving that record" message causes content on page to shift on page. This is like Lucy pulling the football away just as Charlie Brown is going to kick it; just as one goes to click on something, the target moves.

### Steps to Reproduce

1. Go to ...any work or edition record.
2. Do ...save an edit.

* Actual: "Thank you very much for improving that record"  appears briefly and then disappears, causing the rest of the content on page to shift up.
* Expected: The message should either remain until the patron clears it or behave in a way that does not cause content to shift.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 90.0.4430.85 (Official Build) (x86_64)
- **Operating system?** Mac OS Big Sur
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The message should either remain until the patron clears it or behave in a way that does not cause content to shift.

### Stakeholders

@seabelis

**Comment by RayBB** [comment]
I would take a look. However, I can't reproduce or try to fix it since I can't edit a work on my local environment due to a recaptcha issue (related to https://github.com/internetarchive/openlibrary/issues/2021#issuecomment-817213073).

If anyone can help me get around the recaptcha issue I'll work on this issue.

**Comment by Yashs911** [comment]
@seabelis Will this work:

https://user-images.githubusercontent.com/64412143/116504017-0fb5b880-a8d5-11eb-90ff-32e4bba5ea56.mp4

I think using `position: absolute;` will solve the problem

**Comment by seabelis** [comment]
@RayBB Are you signed in as an admin? I _think_ that should remove the recaptcha. 
Username: openlibrary@example.com
Password: admin123

@Yashs911 I think so. There's a flicker in the video that makes it a little difficult to see what's happening right at that moment.

Thank you both!

**Comment by RayBB** [comment]
seabelis I am logged in with that account but it still had the recaptcha.

But if @Yashs911 is taking this on then I won't worry about it for now.
