### ISSUE TITLE
Lists flash on book page when page loads

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5108]
Following the deployment on 28 April 2021, I noticed my lists flash up onto the page and then disappear when page loads. If that edition is on my list, the relevant list name remains. 

Page load also seems slower than usual.

### Evidence / Screenshot (if possible)

https://user-images.githubusercontent.com/17739465/116588577-03a11980-a91c-11eb-838c-47585d3f6d6c.mov

### Relevant url?
 
Any edition or work url.

### Steps to Reproduce

1. Go to ...an edition or work url.
2. Do ...note the left side of page on load.

* Actual: Patron's lists all load and then disappear.
* Expected: If I have a relevant list it should appear alone. If I have no relevant list, nothing should appear at all.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 90.0.4430.85 (Official Build) (x86_64)
- **Operating system?** MacOS Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@seabelis

**Comment by cdrini** [comment]
This is likely also causing a dip in the performance of this page. This is the PR that introduced it: #4597
