### ISSUE TITLE
No way to add an author, independently of Work creation

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#512]
@JeffKaplan has been asking, why don't we have a way to "Create an Author" without creating a book.

We do have a way to do this through APIs, but not for administrators or users.

**Comment by LeadSongDog** [comment]
Dupe of #352 isn't it?

**Comment by guyjeangilles** [comment]
I agree with @LeadSongDog. This appears to be a duplicate of the older issue #352. I propose closing this issue.

**Comment by tfmorris** [comment]
Agreed. Let's be bold and just make it so...
