### ISSUE TITLE
Remove Python 3.8

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5128]
Now that we're on 3.9, we can remove 3.8 entirely 🎉 

### Summary of Requirements
- [x] No refs to Python 3.8 #5146
- [ ] Anywhere Python 3.9 is explicitly referenced can be removed (since it's the default)
    - [ ] Can/should we remove the `.python-version` file?
- [ ] Remove [`from typing import List, Set`](https://github.com/internetarchive/openlibrary/search?q=typing), etc. because [PEP 585](https://www.python.org/dev/peps/pep-0585) is implemented in Python >= 3.9.

### Stakeholders
@dhruvmanila @cclauss

**Comment by dhruvmanila** [comment]
Awesome! I'll get on it right away!

**Comment by cclauss** [comment]
Released yesterday https://www.python.org/downloads/release/python-395/

**Comment by cdrini** [comment]
Moving 3.9.5 upgrade out; that would better be done separately: #5141

**Comment by cdrini** [comment]
If we can remove the python-version file, I'm down to do so!

**Comment by dhruvmanila** [comment]
These are where we would remove the 3.8 reference:
```console
❯ rg 'python3\.8'
docker/Dockerfile.oldev
5:RUN python3.8 -m pip install -r requirements_test.txt

docker/Dockerfile.olbase
59: && python3.8 -m pip install --upgrade pip wheel \
76:RUN python3.8 -m pip install --default-timeout=100 -r requirements.txt \

❯ rg 'python3\.9'                                                                                                                                                         
docker/Dockerfile.oldev
6:RUN python3.9 -m pip install -r requirements_test.txt

docker/Dockerfile.olbase
60: && python3.9 -m pip install --upgrade pip wheel
77: && python3.9 -m pip install --default-timeout=100 -r requirements.txt
87: && python3.9 -m pip list --outdated
```

Actually, I do think we don't need the `.python-version` file as we're already generating it with the global command. Also, as we're moving to one Python version, we should not need it.
https://github.com/internetarchive/openlibrary/blob/707606e1c9c3ddf706f0df450c6f3946843c1fff/docker/Dockerfile.olbase#L55-L60

**Comment by cdrini** [comment]
Sg! You might want to do a search for `3.8` alone as well; can't imagine that should appear anywhere outside of a python context :P

Yep! Removing all those 3.8 installs will speed up olbase building a ton :)

**Comment by dhruvmanila** [comment]
> Sg! You might want to do a search for 3.8 alone as well; can't imagine that should appear anywhere outside of a python context :P

I did do that and these were the only ones relevant to our issue :)
Same for 3.9

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/python_tests.yml#L12

**Comment by mekarpeles** [comment]
I think we're now on 3.9.4? Closing for now
