### ISSUE TITLE
Delete junk "Notebook" records

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5132]
There are a lot of junk records for Notebooks created that need to be deleted. It might be a good idea to work off one of the old monthly data dumps (or OL search) to come up with a short list of candidates which we can then try to manually review. Note: fixing the source would be part of #4151 , this is fixing the damage that's already done.

### Stakeholders
@seabelis

**Comment by pranjii** [comment]
Can I get this job?

**Comment by jimman2003** [comment]
this should be at https://github.com/internetarchive/openlibrary-librarians ..

**Comment by seabelis** [comment]
There is a script to handle individual cases https://colab.research.google.com/drive/1bLbWs6YlvxXuP0Q--N6Os83ZmNLn0i8m#scrollTo=d1CSHaTZWVMu&line=1&uniqifier=1. This requires a bot account. I've been processing them as I find them.
