### ISSUE TITLE
Limit OCAID editing to librarians

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5135]
This is largely currently the case, but there are some loophole where people can OCAIDs.

### Stakeholders
@seabelis @mekarpeles

**Comment by cdrini** [comment]
Proposed solution: Exclude "Internet Archive" from drop downs on https://openlibrary.org/books/add and edit book page for non-admin, non-librarian users. Not bullet proof, but sufficient.

Longer term we might want the OCAIDs to be added in some way, but the interface should only show the availability button if it meets a certain set of criteria.

Blocks mass IA imports, because the books we want to import, we don't want to appear as available, but want them in the catalog.

**Comment by ashdwilson** [comment]
Changes were made in templates to remove OCAID for users who are not administrators or librarians.

We should consider follow-up work for sanitizing input based on user role, in the endpoint itself. Either silently sanitize or respond with a 401 for unauthorized updates.
