### ISSUE TITLE
how to install new instance of openlibrary on a server?

### ISSUE THREAD

**Issue by miracinonyx** [internetarchive/openlibrary#514]
I am interested in using the openlibrary software on my website, but I can only find instructions for setting up a dev instance. Are there instructions somewhere that I'm missing? Thanks!

**Comment by mekarpeles** [comment]
@miracinonyx is there a way the Open Library APIs are insufficient?
Other than internally (and I don't think our internal instructions will be that helpful outside of our infrastructure), I'm not sure there are great instructions for installing Open Library from scratch in a production-style setting. The provisioning instructions used in the dev instance should provide some direction.

**Comment by vg** [comment]
This might help http://code.openlibrary.org/en/latest/

**Comment by mekarpeles** [comment]
Thanks @vg! Marking this issue as closed
