### ISSUE TITLE
New `ol-home0` Crons need to run/trigger ol-www1 ipstats

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5144]
We need our new Crons on `ol-home0` to run or trigger the following via ssh on `ol-www1`:
 
```source /opt/openlibrary/venv/bin/activate;sudo /opt/openlibrary/venv/bin/python /opt/openlibrary/openlibrary/scripts/ipstats.py  /opt/openlibrary/olsystem/etc/openlibrary.yml from ol-www1```

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/2481#issuecomment-833100823_

Related:
* #4775

**Comment by mekarpeles** [comment]
I re-ran `crontab /etc/cron.d/openlibrary` on `ol-www1` and it looks like the latest up-to-date ol-www1 cron may now be running.

**Comment by cdrini** [comment]
Closed in favour of #7622
