### ISSUE TITLE
Vulnerability CWE-79 found in patron-metadata/index.js

### ISSUE THREAD

**Issue by dwaipayan05** [internetarchive/openlibrary#5169]
**Source of Vulnerability**
https://github.com/internetarchive/openlibrary/blob/133ee89ae2bbb290d4a805b2be4763906aa06765/openlibrary/plugins/openlibrary/js/patron-metadata/index.js#L104

https://github.com/internetarchive/openlibrary/blob/133ee89ae2bbb290d4a805b2be4763906aa06765/openlibrary/plugins/openlibrary/js/patron-metadata/index.js#L43

**Vulnerability Description :** Unsanitized input from data from a remote resource flows into append, where it is used to dynamically construct the HTML page on client side. This may result in a DOM Based Cross-Site Scripting attack (DOMXSS). A extended description of the vulnerability can be found [here](https://cwe.mitre.org/data/definitions/79.html)

**Possible Fixes** : Sanitize data input in an HTTP request before reflecting it back, ensuring all data is validated, filtered or escaped before echoing anything back to the user, such as the values of query parameters during searches.

**Comment by jamesachamp** [comment]
Data used to generate the HTML is coming from Open Library servers.  Is there any reason to treat this as an untrusted source?

Regardless of the answer, I don't think that there is a compelling reason to generate the form on the client side now that observations live in OL servers.  This code can be moved to [UserMetadata.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/UserMetadata.html) instead (preferably after #5089 has been merged).
