### ISSUE TITLE
Delete dumpbins

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5180]
Dumpbins are retail displays, not books. These are too many to delete manually. https://openlibrary.org/search?mode=everything&q=title%3A+%22dumpbin%22&sort=editions

### Relevant url?
https://openlibrary.org/search?mode=everything&q=title%3A+%22dumpbin%22&sort=editions

### Steps to Reproduce

1. Go to ... https://openlibrary.org/search?mode=everything&q=title%3A+%22dumpbin%22&sort=editions
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by LeadSongDog** [comment]
Prior discussion at #2691.

**Comment by seabelis** [comment]
This could be achieved more easily if 1) all 682 works could be merged in one go AND 2) more than 50 editions could be deleted at a time using a script.

**Comment by seabelis** [comment]
Resolved with https://colab.research.google.com/drive/1bLbWs6YlvxXuP0Q--N6Os83ZmNLn0i8m?usp=sharing
