### ISSUE TITLE
Search editions by keyword without knowing work id?

### ISSUE THREAD

**Issue by Miksier** [internetarchive/openlibrary#5184]
Hello,

I... need Your help again.
### Question

How to get a list of (if I understand correctly)  editions with a cover, author etc. by a key word?

### Additional context

I try to query every book/edition that contains a word. So lets use book 'Fantastic Mr. Fox' as an example. 
For now Im a French guy, I speak no english at all. I try to search for my book 'Fantastique Maitre'.
I go to or query with a .json `"https://openlibrary.org/search?mode=everything&q=Fantastique+Maitre"`
I get a list with "Fantastic Mr. Fox"( and some "999" that we will ignore).

I dont speak English at all and I have no idea what the original title of the book is so the 'Fantastic Mr. Fox' is not my book, also the cover is different so I found no book.
There are 9 editions of "Fantastic Mr. Fox" containing words ''Fantastique Maitre'.  I'd think that those editions would be shown because... those are the 'real' physical books and the the 'work' is but a group for those books. 

From what I understand(didnt look at the source code) the query is looking in the 'text' and gives the result if its there.

I CAN query editions for the book if I know its id but its not exactly what I want. 
 `https://openlibrary.org/query.json?type=/type/edition&works=/works/OL2163720W&*=`

Maybe I could get the results I want from the deprecated JSON api but since its deprecated I dont want to wake up to it not working anymore.

So the expected result would be to get all 9 editions of  'Fantastique Maitre' this '999' and maybe ''Fantastic Mr. Fox' work.

### Issue resolution criteria
a query to get list of editions/books that contain a specified word.

**Comment by mekarpeles** [comment]
There isn't a way to go directly from a keyword to a specific edition. At best, you can use the search.json API to find works and edition info about those works:

https://openlibrary.org/search.json?q=Fantastique+Maitre

There isn't edition level granularity (e.g. about language, availability, etc). Two API calls need to be made. We'd love to fix this but it's currently a limitation of our system / architecture / APIs
