### ISSUE TITLE
Unable to connect to infobase server

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5185]
Editing [this](https://openlibrary.org/books/OL22829413M/Wuthering_Heights./edit) orphan throws error, "Unable to connect to infobase server"
### Relevant url?
https://openlibrary.org/books/OL22829413M/Wuthering_Heights./edit

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL22829413M/Wuthering_Heights./edit
2. Do ...try to save an edit

* Actual: Error "Unable to connect to infobase server"
* Expected: edits should be saved

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Chrome
- **Operating system?** MacOS Big Sur
- **Environment (prod/dev/local)?** prod

**Comment by LeadSongDog** [comment]
Also seen at 
https://openlibrary.org/books/OL20417038M/Lone_eagle/edit
https://openlibrary.org/books/OL21881506M/Lone_eagle./edit
https://openlibrary.org/books/OL19462841M/Lone_eagle./edit
Seen moving from OL10614095W to OL19726W or simply revising content.

**Comment by LeadSongDog** [comment]
The message is an exception handled here: 
https://github.com/infogami/infogami/blob/3e9357c0184cd51921e198762c9f7d03b4589cf1/infogami/infobase/client.py#L156

Would it be more helpful if the message included some information, perhaps the path parameter?

**Comment by jimchamp** [comment]
> More IDs with this error. OL13200728M,OL12992823M,OL9487522M,OL10157476M,OL9406979M,OL9647822M,OL12951967M

These all look like orphaned editions.  Are you able to edit any orphaned editions at all?

**Comment by seabelis** [comment]
https://testing.openlibrary.org/works/merge?records=OL151074W,OL8984228W,OL8984251W,OL19907154W,OL20943143W,OL151075W,OL19003767W,OL3543886W,OL11360583W,OL3543900W,OL11360554W,OL11360575W

**Comment by seabelis** [comment]
https://testing.openlibrary.org/works/merge?records=OL151056W,OL8984230W

**Comment by dcapillae** [comment]
The following records are also blocked for editing by this error:
- [ ] _Here's to You, America!:_ https://openlibrary.org/books/OL9329974M
- [ ] _Be My Valentine, Charlie Brown_: https://openlibrary.org/works/OL25755W
- [ ] _Chariots for Hire_:  https://openlibrary.org/works/OL25895W

**Comment by dcapillae** [comment]
It is working well for me now. It is possible to edit the records without problems. It will take me a while to go through them all, but I would say that the initial issue has definitely been resolved.
