### ISSUE TITLE
Do not use jQuery shorthand event methods in jQuery

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#5198]
Throughout our JavaScript codebase, a lot of code makes use of jQuery methods that according to TypeScript hinting aredeprecated in 3.3.

We should replace all these with `on` or `trigger` as appropriate.

For example

```
$('.selector').click(clickFn);
$('.btn').click();
```
becomes

```
$('.selector').on('click', clickFn);
$('.btn').trigger('click');
```

Methods to fix:
- []  click
- [] mouseover
- [] mouseout
- [] mouseup
- [] submit

### Evidence / Screenshot (if possible)

<img width="796" alt="Screen Shot 2021-05-23 at 9 43 32 AM" src="https://user-images.githubusercontent.com/148752/119269205-57b1bd80-bbab-11eb-8748-eecf379ed1f9.png">

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
I would like to work on this. If someone else also wants to work we can divide the work. :)
