### ISSUE TITLE
Two books not showing: TypeError: '>' not supported between instances of 'Nothing' and 'int' (falling back to default template)

### ISSUE THREAD

**Issue by ma8642** [internetarchive/openlibrary#5205]
I get this error:
`TypeError: '>' not supported between instances of 'Nothing' and 'int' (falling back to default template)`
when trying to view the following two books:
- https://openlibrary.org/books/OL2216788M/Out_of_Africa_and_Shadows_on_the_grass
- https://openlibrary.org/books/OL7275436M/Tao_Te_Ching

### Evidence / Screenshot (if possible)
<img width="1018" alt="Screen Shot 2021-05-24 at 11 45 22 PM" src="https://user-images.githubusercontent.com/13713037/119436411-1d9b0580-bcea-11eb-9bcb-9d8e627fa8d2.png">

### Relevant url?

- https://openlibrary.org/books/OL2216788M/Out_of_Africa_and_Shadows_on_the_grass
- https://openlibrary.org/books/OL7275436M/Tao_Te_Ching

### Steps to Reproduce

1. Visit the urls above.

* Actual:  I see the error `TypeError: '>' not supported between instances of 'Nothing' and 'int' (falling back to default template)`.
* Expected: I should see the profile page for the book.

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Firefox 88.0.1
- **Operating system?** MacOS 10.15.7
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/4603, @cdrini might be able to fix this.

**Comment by cdrini** [comment]
This is a by-product of #5206 again :( I was able to fix the first book, but the second is giving me `Unable to connect to infobase server` errors.

**Comment by cdrini** [comment]
Closing in favour of #5206 . The books in the description are now fixed.
