### ISSUE TITLE
Textarea resize beyond page border

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5210]
Resizing `textarea` can lead to part of the page go beyond the page "border".

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/73437497/119720577-6d083f80-be6a-11eb-8d88-771eb22ab46a.png)

### Relevant url?

Screenshot from [books/edit](https://openlibrary.org/books/OL6906429M/The_description_of_Greece/edit)

Issue also on pages:
 - [admin/block](https://openlibrary.org/admin/block)
 - [admin/imports/add](https://openlibrary.org/admin/imports/add)
 - [authors/edit](https://openlibrary.org/authors/OL28743A/Cicero/edit)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Related files

- openlibrary/templates/admin/block.html
- openlibrary/templates/admin/imports-add.html
- openlibrary/templates/books/edit/about.html
- openlibrary/templates/books/edit/edition.html
- openlibrary/templates/books/edit/excerpts.html
- openlibrary/templates/type/author/edit.html

**Comment by Yashs911** [comment]
@lephemere I would like to work on this issue. I think using `resize: vertical;` should fix the problem.

**Comment by lephemere** [comment]
Other templates with `textarea`:
openlibrary/templates/account/notes.html
openlibrary/templates/admin/inspect/memcache.html
openlibrary/templates/admin/solr.html
openlibrary/templates/admin/spamwords.html
openlibrary/templates/support.html
openlibrary/templates/type/list/edit.html
openlibrary/templates/type/page/edit.html

**Comment by lephemere** [comment]
| templates | olform | comment |
| --------- | ------ | ------- |
| account/notes.html | no | OK, not resizable |
| admin/block.html | no | |
| admin/case.html | no | testing? |
| admin/imports-add.html | no | |
| admin/inspect/memcache.html | yes | |
| admin/solr.html | yes | |
| admin/spamwords.html | yes | |
| books/edit/about.html | yes | |
| books/edit/addfield.html | no | dead code? |
| books/edit/edition.html | yes | |
| books/edit/excerpts.html | yes | |
| edit_yaml.html | no | testing? |
| lib/history.html | no | |
| support.html | yes | |
| type/about/edit.html | yes | testing? |
| type/author/edit.html | yes | |
| type/doc/edit.html | yes | testing? |
| type/home/edit.html | no | tag issues, testing? |
| type/list/edit.html | yes | |
| type/macro/edit.html | no | testing? |
| type/page/edit.html | yes | |
| type/permission/edit.html | yes | testing? |
| type/rawtext/edit.html | no | testing? |
| type/template/edit.html | no | testing? |
| type/user/edit.html | yes | |
| type/usergroup/edit.html | yes | |

**Comment by lephemere** [comment]
Issue is also present in `colorbox`. Box is not resizable. Hence, `resize: none` should do the trick.

![image](https://user-images.githubusercontent.com/73437497/162583606-fe761b38-43c1-417e-a8e0-161c6f9ddc7d.png)

**Comment by jimchamp** [comment]
`account/notes.html` is also a colorbox `textarea`.  I agree that we should completely restrict resizing colorbox `textarea`s for now.  

In the past, we have adjusted a colorbox's height with this function:
https://github.com/jimchamp/openlibrary/blob/7f260943c8377f0c2a078d67e7a216609fec8877/openlibrary/plugins/openlibrary/js/patron-metadata/index.js#L118-L126

This code was removed some time ago, but we could use something similar with a resize listener and allow colorbox `textarea`s to be vertically resized.

**Comment by jimchamp** [comment]
Adding a `resize: vertical` rule to these textareas should mostly take care of this.  The textareas that are found in modals may be a bit more complicated, but these can be done in a separate PR (if it's easier for the contributor).

**Comment by sop-kim** [comment]
Hi, could I work on this? I am new to the project and am looking for a good first issue.

**Comment by mekarpeles** [comment]
@sop-kim yes please! Do you have an invitation to slack? We're happy to help you from there as well. You may email me at mek@archive.org
