### ISSUE TITLE
Library Explorer Access

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5212]
### Describe the problem that you'd like solved

I don't see any links from the OL home page to reach the [Library Explorer](https://openlibrary.org/explore) page.
Would be great to have a link somewhere to reach this page (and not type `explore` in my browser search bar each time as I do right now...).
Will also improve visibility of this feature to OL users.

### Proposal & Constraints

Add a link in the top `Browse` dropdown menu and/or in the `Discover` section in the footer.

**Comment by cdrini** [comment]
Sounds perfect! The last thing I think that needs doing is making the default sort order "Random" ; that'll make the shelves have different books on a regular basis, which would be nice.

**Comment by Yashs911** [comment]
https://github.com/internetarchive/openlibrary/pull/5430 will add Library Explorer to the Browse Menu
