### ISSUE TITLE
Export list in json format does not work

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#5215]
The option to export list in json format does not work.

### Evidence / Screenshot
![screenshot](https://user-images.githubusercontent.com/7125952/119910099-ab7b2880-bf56-11eb-8bbc-2d34ed37c602.png)

### Steps to Reproduce
1. Go to any list (e.g. [Rif War](https://openlibrary.org/people/dcapillae/lists/OL197248L))
2. Select option to export as json 

* Actual: You receive an error message like this: "Hmm... Sorry. There seems to be a problem with what you were just looking at. We've noted the error 2021-05-27/234105967423 and will look into it as soon as possible. Head for home?".

* Expected: Get a data file with the list books in json format.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Mozilla Firefox 78.9.0esr (32-bit)
- **Operating system?** Debian 9
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
We can see the error by going directly to this url (w/ `debug=true`)
https://openlibrary.org/people/dcapillae/lists/OL197248L/Rif_War/export?format=json&debug=true

**Comment by mekarpeles** [comment]
@dherbst this was possibly an accidental regression based on changes to `plugins/openlibrary/list.py` -- do you mind taking a look?

**Comment by cdrini** [comment]
Specifically I think it was this one: f9de97d . Actually this looks super quick to fix :P I'll open an issue.

**Comment by dherbst** [comment]
Thanks @cdrini.  Sorry I missed that one.
