### ISSUE TITLE
Add cover thumbnails have gone from small to miniscule.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5217]
Adding a cover to a work opens a preview of available covers. Since deployment on 27-05-2021, these thumbnails are too small to be of much use. Prior to this they were larger, but only the left half could be seen. Prior to the new books page the covers were fully displayed.
### Evidence / Screenshot (if possible)
<img width="812" alt="Screenshot 2021-05-28 at 08 29 28" src="https://user-images.githubusercontent.com/17739465/119940283-40017d00-bf8f-11eb-91fb-d6b1da0fe127.png">

### Relevant url?
https://openlibrary.org/works/OL1841317W/Star_Wars_-_New_Jedi_Order_-_The_Final_Prophecy/add-cover

### Steps to Reproduce

1. Go to ...any work url
2. Do ...append with "/add-cover" to open cover editor

* Actual: see screenshot
* Expected: covers should be large enough to see detail and displayed in full

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Version 90.0.4430.212 (Official Build) (x86_64)
- **Operating system?** MacOS Big Sur
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
@seabelis -- @cdrini + @jamesachamp and I went through triage and thought this was a P3 because it's "work-aroundable" (non-blocking). If this is wrong and should be P2 or higher, please let @jamesachamp know.

**Comment by jdlrobson** [comment]
Looks fine for me right now. Did this get fixed? Or maybe this was a problem relating to cached assets?
https://openlibrary.org/works/OL1841317W/Star_Wars_-_New_Jedi_Order_-_The_Final_Prophecy/add-cover

**Comment by Yashs911** [comment]
For me:

https://user-images.githubusercontent.com/64412143/120416206-66059380-c37a-11eb-8015-37216b6e58d1.mp4

**Comment by jamesachamp** [comment]
I think that this can be solved by capping the number of books shown be the carousel to 3 or 4.  Right now it seems that the carousel is allocating enough space to display 6 images at once, which is the default.  

I see that we are able to set these values on Carousel initialization, but I'm unclear on how to change the values that are being passed for the add covers modal (or even *what* is being passed...).
