### ISSUE TITLE
Edition table should order works by greatest to least availability

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5218]
The edition table frequently uses a print-disabled-only or "not in library" edition as the default even when readable and borrowable editions exist. 

### Evidence / Screenshot (if possible)
<img width="1097" alt="Screenshot 2021-05-28 at 17 26 42" src="https://user-images.githubusercontent.com/17739465/120007211-f1c59b80-bfd9-11eb-8c78-e5eaee2f4712.png">

### Relevant url?
https://openlibrary.org/works/OL11915W/The_Celery_Stalks_at_Midnight?edition=

### Steps to Reproduce

1. Go to ...https://openlibrary.org/works/OL11915W/The_Celery_Stalks_at_Midnight?edition=
2. Do ... Observe that a print-disabled only edition is listed as the default even though there is a borrowable edition available.

* Actual: 
* Expected: Table should sort by greatest to least availability.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by LeadSongDog** [comment]
It seems the subtitled edition record was sorted differently. This edit fixed the issue:
https://openlibrary.org/books/OL17226960M/The_Celery_Stalks_at_Midnight?_compare=Compare&b=13&a=12&m=diff

**Comment by seabelis** [comment]
This is also related to which edition is "best" and the one that patrons land on by default without any known preferred sort choice, language, etc. This may also determine which availability is displayed on carousels, but I'm not certain.

**Comment by seabelis** [comment]
I appreciate the fix, but I'm not sure moving the subtitle to the series field is a perfect solution. The subtitle probably shouldn't take precedence over availability in determining the default edition.

**Comment by LeadSongDog** [comment]
You’re right. The series should be Bunnicula. "A Vegetable Adventure" was ahead of title on just that edition, so I stated that in the edition notes.

**Comment by mekarpeles** [comment]
@cdrini mentioned (I think, correctly) that `printdisabled-only` books might throw these off (and we don't exactly have this information cleanly within solr...

**Comment by libjenner** [comment]
+1 

For now, we curators of collections are adding language to the collections pages to the effect of _If a book says it is "not in library" or "checked out," a copy might still be available! Click on the book's cover to see if you can borrow one of the other editions._ But, of course, some library visitors & potential patrons skip right down to the carousels and might not realize a book is actually available. This would be a much-appreciated fix! Thank you :)

**Comment by mekarpeles** [comment]
This should be fixed. And if now, it will be when https://github.com/internetarchive/openlibrary/pull/6125 lands.
