### ISSUE TITLE
Adding an edition fails

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5219]
Since the deploy on 27-05-2021 adding an edition fails with error "Hmm...
Sorry. There seems to be a problem with what you were just looking at.
We’ve noted the error 2021-05-28/054532635131 and will look into it as soon as possible. Head for home?"
### Evidence / Screenshot (if possible)
<img width="1134" alt="Screenshot 2021-05-28 at 18 01 40" src="https://user-images.githubusercontent.com/17739465/120011613-cabd9880-bfde-11eb-9102-67afa6a19941.png">

### Steps to Reproduce

1. Go to ...any book page
2. Do ...click add another edition

* Actual: After populating the fields and saving, the error above displays. 
* Expected: Edition added and edit form loads.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**  Version 90.0.4430.212 (Official Build) (x86_64)
- **Operating system?** Mac OS Big Sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by cdrini** [comment]
Here's the exact error:

![image](https://user-images.githubusercontent.com/6251786/120031676-1cf2bf80-bfc7-11eb-859b-b96ea8e5a648.png)
