### ISSUE TITLE
RFC: Establishing a reference metadata standard format for OL Editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#523]
Some points to consider:
1) OL started with editions only, no works. So we have a lot of editions with data we'd expect to be on Works (e.g. Subject tags). There are ~5M orphaned editions for which this may apply.
2) Many communities like Wikidata have standards around Dates. OL is fairly free-flow. We should consider what standards we want to use on fields like this
3) Right now anyone can edit OL edition metadata and add any keys they want. Let's try to create a more structured schema so our tools (like `openlibrary-client` can predictably marshal types (read from and write to the APIs).
4) The OL metadata sometimes includes `types` (e.g. {"type": "work", "key": "..."}. and sometimes does not. Our proposal should canonicalize these cases one way or the other
5) Field names should similarly be canonicalized.
6) Let's make sure OL data standards are in line with the rest of Archive.org
7) Let's consider rolling out such changes incrementally and prioritizing the fields which will help us merge editions and authors. As we do this, we might include incorporating xisbn data from OCLC and IA's APIs.

@hornc has done a great job of drafting notes in the wiki: https://github.com/internetarchive/openlibrary/wiki/OL-Standards

cc: @tfmorris, @leadsongdog, @bfalling

**Comment by mekarpeles** [comment]
Feel free to iterate on OpenLibrary Metadata Standard™ (OLMS -- just what we need, another standard) for Edition metadata proposal here:
https://gist.github.com/mekarpeles/3d6c24122521a29e7e0f9c1ac2e459ad

**Comment by hornc** [comment]
@mekarpeles I've been playing with describing the edition format as a JSON schema here: 
https://github.com/hornc/ol-schemata/blob/master/edition.schema

I am planning to create a current version, and a series of stricter versions to help identify data issues that can be cleaned up..

**Comment by hornc** [comment]
The existing definition of an Edition appears to be this: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/types/edition.type

**Comment by hornc** [comment]
**UPDATE** The current JSON schema of an edition is being maintained here (moved from my repo to the official client): https://github.com/internetarchive/openlibrary-client/blob/master/olclient/schemata/edition.schema.json

Now part of the Open Library Client. It can be used to automatically validate items from within the client.

@mekarpeles Can we close this issue now? Further discussion and proposals to the schema can be made on the `edition.schema.json` file itself?

**Comment by guyjeangilles** [comment]
Several things:

#524 is referenced as a subtasked of this issue, so I'm tagging this issue as Epic and #524 as Sub-Epic.

@hornc I think it makes more sense to discuss proposals to this standard format in github issues to better solicit input from the community. 

Also, if this is actually done and #524 as well, I propose closing this issue. If both this issue and #524 are not done, are you willing to be assignee for this issue? It seems you're already doing the work for it.

**Comment by mekarpeles** [comment]
No clear next steps; closing as having served its purpose
