### ISSUE TITLE
Eslint: Add eslint eqeqeq rule

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#5238]
We have various type-unsafe equality if statements in our codebase now.

There are about 80 instances of this in our codebase.

### Evidence / Screenshot (if possible)

[] Introduce the eqeqeq rule https://eslint.org/docs/rules/eqeqeq
[] Confirm running `npm run lint:js` shows errors.
[] Fix errors

### Stakeholders
@jdlrobson

**Comment by lukan23** [comment]
Hi @jdlrobson , I am a beginner to open source and would love to work on this. Can I try?

**Comment by jdlrobson** [comment]
@lukan23 that would be great! Go for it!

**Comment by sadn1ck** [comment]
Hey @jdlrobson, came across this issue while searching for good first issues, saw this wasn't being worked on, so I did the changes in a branch [here](https://github.com/sadn1ck/openlibrary/commits/5238/bug/eslint-eqeqeq-rule). 

I ran the tests mentioned in the CONTRIBUTING doc as well (they passed). Let me know if any changes are required and if I should make a PR.

Thanks!
