### ISSUE TITLE
RFC: OLMS for Edition external identifiers?

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#524]
This is a subtask of #523 -- what specifically should be the OpenLibrary Metadata Standard be for an Edition's external identifiers (e.g isbn10, isbn13, librarything)?

Right now we represent these in a variety of ways.
cc: @hornc, @tfmorris, @leadsongdog

**Comment by guyjeangilles** [comment]
More details at the parent epic issue: https://github.com/internetarchive/openlibrary/issues/523#issuecomment-545191150

I've added labels per the context

**Comment by guyjeangilles** [comment]
#523 was closed, @mekarpeles should this be closed too?
