### ISSUE TITLE
Reporting a problem leads to blank page when not logged in

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5247]
Reporting a problem leads to blank page when not logged in.

### Evidence / Screenshot (if possible)
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/921217/120227042-2442e480-c1e4-11eb-9a68-f23ba2ae8748.png">

### Relevant url?

https://openlibrary.org/contact

### Steps to Reproduce

1. Go to https://openlibrary.org/contact (while not logged in)
2. Report a problem
3. See how you'll be taken to a blank page

* Actual: Goes to blank page
* Expected: Goes to thank you page or another screen

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF
- **Operating system?** Mac OS
- **Environment (prod/dev/local)?** prod

### Related files

#3826

**Comment by jamesachamp** [comment]
This happens whenever the form is submitted with an empty email field.  In these cases, the `/contact` POST controller returns an empty string, and the support email is not generated and sent.

Making the email input field required and explicitly setting its type to `email` will largely prevent this from happening.  The text next to the input should also be updated, as it implies that the email is optional.

**Comment by tonytamsf** [comment]
I've submitted a simple fix for this to validate the email address field as a valid email as well as not blank.

https://github.com/internetarchive/openlibrary/pull/5384
