### ISSUE TITLE
Login, log out, and account creation broken on development instance

### ISSUE THREAD

**Issue by jamesachamp** [internetarchive/openlibrary#5256]
I am unable to log out on my local instance.  Account creation and login pages also throw errors when loaded.

### Relevant url?

The following pages display error messages:
http://localhost:8080/account/login
http://localhost:8080/account/create

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** Both
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** dev

### Proposal & Constraints

A few lines of code should be rolled back in #5201.  Relevant code is pointed out in the PR.

**Comment by jdlrobson** [comment]
Yuck! his is why I hate inline Javascript :) thanks for catching!

The changes you've proposed fix this for me locally so I dont think we need to roll back. Is there anyway to apply them post-merge or does somebody need to create a pull request with those changes?
