### ISSUE TITLE
many timeouts today

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5266]
Today I've gotten several timeouts with the following error:
```
/openlibrary/openlibrary/templates/type/author/view.html: error in processing template: ReadTimeout: HTTPConnectionPool(host='ol-solr1.us.archive.org', port=8984): Read timed out. (read timeout=10) (falling back to default template)
```

### Relevant url?
It happened on urls like https://openlibrary.org/authors/OL2670930A/Rick_Kazman but it doesn't happen consistently.

### Steps to Reproduce
Not clear

* Actual: error message
* Expected: no error message

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by cdrini** [comment]
Yep! This looks as a result of the #3317 testing. Last time it stabilized after an hour or so, but it seems like it's still kicking around. My current hypotheses:

(1) Our solr-updater triggers a solr `<commit/>` every minute; this seems to cause a noticeable dip in performance. With solr8, we should be making use of automatic soft commits, and not explicitly calling commit. That will require some testing.

(2) Confirm this server is using and SSD; can't recall if it is.


Testing (1) now by temporarily turning off solr-updater for solr8. If the load times drop back down to normal, that means that is the culprit, and then I will investigate how to switch to soft commits.

**Comment by cdrini** [comment]
Here is the current average load time for search pages. I switched both web heads to hit solr8 ~19:00 (UTC)

![image](https://user-images.githubusercontent.com/6251786/120714190-e4ecf000-c490-11eb-89e9-02e1f8b9c52a.png)

**Comment by cdrini** [comment]
It went down a little, but not enough. Another hypothesis is that I need to run an optimize step. I had to run this on the old Solr, but wasn't sure if this need it. Going to give that a go, and switch production back to the old solr in the mean time :+1:

**Comment by mekarpeles** [comment]
@cdrini has taken actions to monitor and we think this is resolved, closing for now, if this is noticed again, let's please re-open
