### ISSUE TITLE
harry potter is the first book in the computer science section of library explorer

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5267]
I see that harry potter is the first book in the computer science section of library explorer. Not sure how it works but it seems like that is the wrong place. 

I reported it as an issue to the librarians and they said:
> It could be related to this issue here, https://github.com/internetarchive/openlibrary/issues/1946. There are a lot of books in that classification that don't belong there and since the classification is 00, this may be the reason. Drini should be able to answer that. Else it could just be that one edition has the wrong classification. The classification displayed is 823, so I'm not sure what else is taken into account.

### Evidence / Screenshot (if possible)
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/921217/120716943-73964880-c462-11eb-9d13-5d098ecb2cf2.png">

### Relevant url?
https://openlibrary.org/explore

### Steps to Reproduce

1. Go to https://openlibrary.org/explore

* Actual: Shows books not related to CS
* Expected: Show CS books

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by cdrini** [comment]
This specific case was mostly just bad data, so fixed the record here: https://openlibrary.org/books/OL22596889M/Harry_Potter_and_the_Chamber_of_Secrets?m=diff&b=17 .

Also made the normalizer more robust to ignore situations like these: https://github.com/internetarchive/openlibrary/pull/5270/files#diff-ceef924335890bf09d5545b6745a4a68242405eb40a0a77480d6560b9ba3d920R68

**Comment by jimman2003** [comment]
Another occurance:
![image](https://user-images.githubusercontent.com/58356745/122958818-9e056280-d38b-11eb-96af-cff965b973a3.png)
Maybe the normalizer needs checking once more?

**Comment by cdrini** [comment]
:+1: The changes to the normalizer will unfortunately not be visible until we do a full solr reindex; that'll be in ~ a week or so.
