### ISSUE TITLE
Replace Wikipedia references with Wikidata references

### ISSUE THREAD

**Issue by GerardMeijssen** [internetarchive/openlibrary#527]
Hoi, at this time there are many references in Internet Archive that link to the English Wikipedia. However for many people there is an international audience. 

In stead of linking to en.wp, you could link to Wikidata. This includes many more people including Americans, Brits who have a Wikipedia article but not in English. This exercise is easy to do as do as every Wikipedia article has only one link to Wikidata.

NB The OCLC in its VIAF data did exactly this to good effect, the result has also been a much better cooperation and coordination between wiki people and the library world.

 @hornc

**Comment by LeadSongDog** [comment]
Will advise DarTar about this and invite his input.

**Comment by hornc** [comment]
@GerardMeijssen / @LeadSongDog  What is the preferred format for links back to wikidata from other sites?

I would default to using this format, for example:
https://www.wikidata.org/wiki/Q868

**Comment by GerardMeijssen** [comment]
Hoi,
The main thing to know is the identifier.. With it you can also provide
Reasonator [1], it includes the same identifier and is much more
informative. It also has the benefit of being available in any language.
Thanks,
      GerardM

[1] https://tools.wmflabs.org/reasonator/?q=Q868

**Comment by dartar** [comment]
Thanks for the heads up @LeadSongDog. 

@GerardMeijssen: which references are you referring to? I agree that in general Wikidata items should be the preferred resources for entity mapping, but I'd like to see a couple of examples where you suggest WP links should be replaced: there are many cases where pointing to an encyclopedic entry in English actually makes a lot of more sense.

**Comment by LeadSongDog** [comment]
I expect that over time there will be much more complete span of authors and works on Wikidata than on Wikipedia simply because notability is not required for a Wikidata entry. Many Wikidata entries will have no corresponding Wikipedia entry, perhaps just a citation. Where there is, it can be found via the Wikidata entry anyhow, in whatever WP languages it exists.

**Comment by GerardMeijssen** [comment]
There is certainly a place where a link to an article is more advantageous.
However, Wikidata supports substantially more authors in any language than
even the Wikipedias combined. When the idea is to have an article when
there is one, it is just a little code that will present the article based
on the Wikidata item. This has the added benefit that for one author IA
only is  one link to the WMF and the article can be shown in the language
of the reader.

Given that IA is there for all languages, it makes sense to include the
support WMF provides for any language.

**Comment by hornc** [comment]
@GerardMeijssen , there are now links from Author pages to Wikidata via the Reasonator tool, e.g. https://openlibrary.org/authors/OL32772A/%C3%89mile_Zola

Many authors, including the above, also have links back to Wikipedia, but those are user added and could be links to any site.

**Comment by hornc** [comment]
Closing as DONE: Wikidata (via the Reasonator) is now the OL system's builtin way of handling these links. Users are still free to add Wikipedia links in the free-form links fields, but that is not built into the system.
