### ISSUE TITLE
Docker takes up 34gb on my computer due to OpenLibrary

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#5274]
The top left square of my hard drive is Docker relating to OpenLibrary  (34.1GB)
<img width="647" alt="Screen Shot 2021-06-06 at 7 42 11 AM" src="https://user-images.githubusercontent.com/148752/120928722-b5a9cf00-c69a-11eb-97fe-ca330b60a28b.png">

My concern is that this  requirement of disk space excludes a lot of would-be-contributors, particularly ones who cannot afford powerful machines.

Is there optimizations we can make to reduce the size of Docker? For example, could Solr be optionally enabled for those that work on search, and could frontend engineers like myself rely on the production API and dummy search results?

### Steps to Reproduce
To visualize disk space I made use of Grand Perspective: http://grandperspectiv.sourceforge.net/

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini @mekarpeles

**Comment by Yashs911** [comment]
+inf, and on windows, the default storage location of docker images is C drive, so when I started contributing, it was a huge problem,  but after days of research, I was finally able to shift it to D drive :)

**Comment by RayBB** [comment]
Not sure if it's the same exact issue, but I've faced similar issues with Docker generally in relation to Docker reserving too much space with docker.raw https://github.com/docker/for-mac/issues/2297

If anyone is currently facing this issue I'd recommend trying out codespaces. It has worked quite well for me in developing open library https://github.com/features/codespaces

**Comment by cdrini** [comment]
Hmm, could folks having this issue list the specific directories which are taking up space? As specific as possible would be nice, but don't go to too much trouble.

Also, can I get the results of:

`docker container ls -a`

`docker image ls`

`docker volume ls`

**Comment by jdlrobson** [comment]
`docker image ls` seems to give a clue. I had multiple openlibrary/olbase images.
A prune got rid of a bunch of them, but not sure how I ended up in this state!

```
olsolr                         latest              0e7dca5052e9        4 weeks ago         369MB
oldev                          latest              00086a7d1997        4 weeks ago         2.72GB
openlibrary/olbase             latest              9fc1b393fe7b        4 weeks ago         2.42GB
ubuntu                         xenial              aefd7f02ae24        6 weeks ago         134MB
openlibrary/olbase             <none>              48dc47b80c82        2 months ago        2.4GB
ubuntu                         <none>              f6f49faac5cf        2 months ago        132MB
openlibrary/olbase             <none>              e08f91f6e661        3 months ago        2.76GB
openlibrary/olbase             <none>              19d046731f37        4 months ago        2.74GB
openlibrary/olbase             <none>              3c2a6fc6e0aa        5 months ago        2.46GB
ubuntu                         <none>              9499db781771        6 months ago        131MB
openlibrary/olbase             <none>              102d2e6640e3        7 months ago        2.45GB
composer                       latest              06a1b04fa4e4        12 months ago       179MB
mariadb                        10.3                5eccdce15d61        12 months ago       345MB
wikibase/elasticsearch         6.5.4-extra         966fe296fe39        12 months ago       777MB
wikibase/wikibase              1.34-bundle         d2f25d99a9d8        12 months ago       1.3GB
wikibase/wdqs                  0.3.10              2ec16b38f53e        12 months ago       216MB
olbase                         latest              2bd5f505cbdb        15 months ago       1.17GB
memcached                      latest              291823545098        18 months ago       82.2MB
ubuntu                         <none>              56bab49eef2e        18 months ago       123MB
docker/desktop-reclaim-space   latest              acaa0a8bbb14        20 months ago       101kB
postgres                       9.3                 c230b2f564da        2 years ago         223MB
```

After some pruning still 2 gb olbase's... are both needed?:

```
olsolr                         latest              0e7dca5052e9        4 weeks ago         369MB
oldev                          latest              00086a7d1997        4 weeks ago         2.72GB
openlibrary/olbase             latest              9fc1b393fe7b        4 weeks ago         2.42GB
ubuntu                         xenial              aefd7f02ae24        6 weeks ago         134MB
composer                       latest              06a1b04fa4e4        12 months ago       179MB
mariadb                        10.3                5eccdce15d61        12 months ago       345MB
olbase                         latest              2bd5f505cbdb        15 months ago       1.17GB
memcached                      latest              291823545098        18 months ago       82.2MB
ubuntu                         <none>              56bab49eef2e        18 months ago       123MB
docker/desktop-reclaim-space   latest              acaa0a8bbb14        20 months ago       101kB
postgres                       9.3                 c230b2f564da        2 years ago         223MB
```

**Comment by mekarpeles** [comment]
6GB better than 34GB!

**Comment by cdrini** [comment]
Sweet! You can also remove any `openlibrary/olbase` that has `<none>` in its label field. Not sure why those don't get auto-deleted :P Only the `openlibrary/olbase` is needed; you can remove the `olbase` (that's a residue of an older flow). Closing this issue as I think that helps resolve it. What was the final size after the pruning?
