### ISSUE TITLE
Improve choosing of default edition for works

### ISSUE THREAD

**Issue by omentic** [internetarchive/openlibrary#5294]
### Describe the problem that you'd like solved

Currently, the default book version (what shows up when navigating to a book from the search) is seemingly random - and can vary across languages, even when those languages weren't the originally published language. Here's The Fellowship of the Ring, for example: https://openlibrary.org/books/OL28255957M/

(this also can vary within a series - like Harry Potter)

### Proposal & Constraints

It would be great if the default book version was determined by the publishing date. For people browsing in a language different than the originally published language, they could just be served the oldest known copy in their language. 

Although, if there's data on what book version is _most_ used, that might work better, especially for older works without covers.

Another solution would for every book to manually have a "default", but that would probably be time-consuming and not very effective.

**Comment by cdrini** [comment]
Note: We might want to choose the best edition considering: (1) the user's language; (2) is it borrowable/readable, (3) the record with the most information (largest JSON).

**Comment by davidscotson** [comment]
I think the order is currently based on "Availability" of the edition, I'm not sure how that is calculated, but if you click the Availability heading on the list, the one that by default is at the top goes to the bottom, and then comes back again when you sort again. Assuming that "available" is either yes/no, a secondary sort by the language(s) set for the user's browser would probably be a good improvement.

A more general issue is that a work should probably have it's own cover image associated with it seperate from  (but usually sourced from) the editions. The recognizability of the cover and the "availability" of an edition seem to be inversely associated so usages like having a list of books you want to read, a list of Author's books or a topic shelf can seem a bit visually random. Using the work's image in the top left, and the edition images for the list might work, though currently there's some edition specific call to actions under the large image.

Wikipedia/Wikidata often have a hand selected image associated with a work, for use in the top right corner infobox, often a first edition of some kind, and things like a handwritten manuscript or decorative frontispiece for older works, which would be a good place to start I think, though I think they technically can have any "related" image there so it's mostly convention that it's the book cover.

**Comment by mekarpeles** [comment]
This is related to #8820 and #7452. Already this can likely be closed by some of the work @cdrini has done on edition search results taking language and availability into account.
