### ISSUE TITLE
eslint: prefer-const

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#5307]
A lot of our legacy code uses "var". Using const and let will make it clearer where it is expected for our variables to be modified.

https://eslint.org/docs/rules/prefer-const

### Steps to Reproduce
- [] Add  the new rule to .eslintrc.json, making it error
- [] Fix offenders

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jdlrobson

**Comment by Yashs911** [comment]
> This rule is aimed at flagging variables that are declared using `let` keyword, but never reassigned after the initial assignment.

It will only change the let to const if its never reassigned. Is this the goal for this issue?
or
we should also include https://eslint.org/docs/rules/no-var?

**Comment by jdlrobson** [comment]
> It will only change the let to const if its never reassigned. Is this the goal for this issue?
Yes. If a variable is never reassigned it's helpful to point that out at declaration.

>  we should also include https://eslint.org/docs/rules/no-var : This rule is aimed at discouraging the use of var and encouraging the use of const or let instead.?

Yeh that also sounds like a useful addition going forward, but perhaps a bit more work?
