### ISSUE TITLE
Met "Internal Server Error" when trying to add a new book in Chinese characters

### ISSUE THREAD

**Issue by xuyuji9000** [internetarchive/openlibrary#5308]
I was trying to to add a Chinese book on [Open Library](https://openlibrary.org)
Met "Internal Server Error" error.

### Evidence / Screenshot (if possible)
<img width="816" alt="Screen Shot 2021-06-13 at 9 23 26 AM" src="https://user-images.githubusercontent.com/4877346/121792550-0a17f600-cc29-11eb-9559-1565852ab113.png">
<img width="818" alt="Screen Shot 2021-06-13 at 9 21 56 AM" src="https://user-images.githubusercontent.com/4877346/121792553-0be1b980-cc29-11eb-92f0-82146f17c1c7.png">

### Relevant url?

- [add link](https://openlibrary.org/books/add)
- [error link](https://openlibrary.org/books/add)

### Steps to Reproduce

1. Go to [Open Library](https://openlibrary.org/), Click **Add a Book**
![image](https://user-images.githubusercontent.com/4877346/121792582-83174d80-cc29-11eb-9ad3-352dcf75613d.png)

2. Type in Chinese characters for the book information.

<img width="1027" alt="Screen Shot 2021-06-13 at 9 28 14 AM" src="https://user-images.githubusercontent.com/4877346/121792592-b78b0980-cc29-11eb-876c-6e67fcb62398.png">

3. Click **Add**
<img width="1131" alt="Screen Shot 2021-06-13 at 9 28 52 AM" src="https://user-images.githubusercontent.com/4877346/121792602-d5f10500-cc29-11eb-8ba7-4fedbbb50061.png">

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 89.0
- **Operating system?** macOS 11.4
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Sorry for the trouble, this is a really annoying one :( Can you paste the book information here, and we'll add it manually for you (somehow). The actual underlying issue is #4311.

**Comment by cdrini** [comment]
@xuyuji9000 Actually, it looks like the book actually _was_ created! The page just errored. You can go to your profile page to see it in your "Recent edits" section. Let me know if that's not the case!

**Comment by cdrini** [comment]
(Also @dhruvmanila and I just worked on getting a fix to the root cause, so this should be permanently fixed soon :) )

**Comment by xuyuji9000** [comment]
> @xuyuji9000 Actually, it looks like the book actually _was_ created! The page just errored. You can go to your profile page to see it in your "Recent edits" section. Let me know if that's not the case!

Sorry for the late response.

Thanks for notification of this information.

**Comment by cdrini** [comment]
This should now be fixed on openlibrary.org! Please let us know if you're still having issues.

**Comment by xuyuji9000** [comment]
@cdrini 
Thanks for the reminding.

Just had a try of the updated feature.

<img width="1230" alt="Screen Shot 2021-06-29 at 10 07 56 AM" src="https://user-images.githubusercontent.com/4877346/123726149-08edf680-d8c2-11eb-9980-42ead7d2313f.png">


I put in the title "品质国家战略" in Chinese, but the end result is in English. 
Is it suppose to be like this?
