### ISSUE TITLE
Search fails to find authors w/ accents in name

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#5310]
Historically search has required exact spelling for any "foreign" words, but now it's gotten worse and even exact matches don't work. The three searches below fail to find the author records with exact word matches.

### Relevant url?
https://openlibrary.org/search/authors?q=Pe%CC%81tur
https://openlibrary.org/authors/OL263940A/Pe%CC%81tur_Gunnarsson.

https://openlibrary.org/search/authors?q=O%CC%81lafur+Jo%CC%81hann
https://openlibrary.org/search/authors?q=O%CC%81lafur&mode=everything
https://openlibrary.org/authors/OL254628A/O%CC%81lafur_Jo%CC%81hann_Sigur%C3%B0sson

### Steps to Reproduce

1. Go to the URLs above
2. Do ...

* Actual: Nothing found
* Expected: Correct author records foudn

### Details

- **Logged in (Y/N)?** both
- **Browser type/version?**  chrome
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by Yashs911** [comment]
Advanced Search works fine:
https://openlibrary.org/search?author=P%C3%A9tur

https://openlibrary.org/search?author=%C3%93lafur+J%C3%B3hann

**Comment by tfmorris** [comment]
@Yashs911 I'm slightly confused. Are you saying that I used the wrong search and that I shouldn't have used the Author search to search for author's names? Was this an error on my part as opposed to a bug in the OpenLibrary search software?

**Comment by Yashs911** [comment]
@tfmorris  No not at all, I mean the author search can be configured in the same as advanced search.

**Comment by cdrini** [comment]
Fixed by the latest solr reindex thanks to #5600
