### ISSUE TITLE
Occasional 503s/slowdowns; likely solr 8 related

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5343]
Getting reports of 503s/slow down on site; seems solr related. Have noticed that a solr restart seems to fix the issue. Might want to set up a docker-compose healthcheck/auto restart?

![image](https://user-images.githubusercontent.com/6251786/122936725-5fe25180-d33f-11eb-8be5-5428e50dd8be.png)

- [x] Create an automatic solr-restarter
- [x] Commit solr-restarter code to openlibrary repo?

### Stakeholders
@seabelis @RayBB

**Comment by cdrini** [comment]
Happened once more today:

Unlike usual, the cpu usage DROPPED during the slow down:

![image](https://user-images.githubusercontent.com/6251786/123177602-96a98c00-d453-11eb-85d3-3b1cd1c2bd33.png)

I tried hitting the solr ping endpoint (to see if I could use it as a docker-compose healthcheck), but it worked fine. Snappy. Same with the solr dashboard.

We checked haproxy:

![image](https://user-images.githubusercontent.com/6251786/123177682-bc369580-d453-11eb-9dde-833d4bc0bee5.png)

Only thing curious here is the "Max: 1" in the queue column; that value is usually zero. I'm wondering if haproxy somehow set up a queue and blocked itself into oblivion? Restarting haproxy `docker restart solr_builder_haproxy_1` resolved the down time.

**Comment by cdrini** [comment]
Other curious thing: the "Last" column is at 6m, which is about the length of the service interruption. Comparing to OL, this looks a little out of the ordinary:

![image](https://user-images.githubusercontent.com/6251786/123178304-eb013b80-d454-11eb-8e48-213036f37a35.png)

**Comment by LeadSongDog** [comment]
@cdrini 
Now getting 503s several times per hour, noticably when revising works’ authors: type-ahead ceases to happen. Seen with both Safari/iPadOS and Chrome/iPadOS.

**Comment by cdrini** [comment]
Today's been especially bad :/ There have also been some unrelated sporadic Internet Archive networking issues causing the same problem.

**Comment by cdrini** [comment]
Created an alert for this in our grafana instance; we should now get a slack notification if avg search page time is slow for >3min.

Mostly need this to help diagnose the issue. Next time it happens, I'll see if I can:
- find a pattern for CPU usage which I can use to auto-restart when a CPU threshold is passed
- find a request that returns a failing message that I can use to auto-restart things
- find some solr setting that I can use to detect that something's up.

As a baseline:

```
$ docker stats
CONTAINER ID        NAME                     CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
801781b239d4        solr_builder_solr_1      287.16%             10.9GiB / 15.64GiB    69.69%              15.2GB / 91.5GB     6.54TB / 5.14GB     72
40f1405b3065        solr_builder_haproxy_1   14.20%              12.46MiB / 15.64GiB   0.08%               106GB / 108GB       6.71MB / 0B         9
dc6232f440da        jenkins                  0.16%               1.931GiB / 15.64GiB   12.35%              89.9MB / 11MB       41.4GB / 83.9MB     52
```

Seems like solr CPU <~400% is normal

**Comment by cdrini** [comment]
Also as a baseline:

/solr/admin/cores?action=STATUS&core=openlibrary 

```json
{
  "responseHeader":{
    "status":0,
    "QTime":7},
  "initFailures":{},
  "status":{
    "openlibrary":{
      "name":"openlibrary",
      "instanceDir":"/var/solr/data/openlibrary",
      "dataDir":"/var/solr/data/openlibrary/data/",
      "config":"solrconfig.xml",
      "schema":"managed-schema",
      "startTime":"2021-08-02T15:05:32.841Z",
      "uptime":64700,
      "index":{
        "numDocs":35997685,
        "maxDoc":36073863,
        "deletedDocs":76178,
        "indexHeapUsageBytes":410380,
        "version":345905,
        "segmentCount":11,
        "current":false,
        "hasDeletions":true,
        "directory":"org.apache.lucene.store.NRTCachingDirectory:NRTCachingDirectory(MMapDirectory@/var/solr/data/openlibrary/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@3254c68; maxCacheMB=48.0 maxMergeSizeMB=4.0)",
        "segmentsFile":"segments_1did",
        "segmentsFileSizeInBytes":-1,
        "userData":{
          "commitCommandVer":"0",
          "commitTimeMSec":"1627916669744"},
        "lastModified":"2021-08-02T15:04:29.744Z",
        "sizeInBytes":25725006970,
        "size":"23.96 GB"}}}}
```

**Comment by cdrini** [comment]
Also as a baseline:

/solr/admin/metrics?group=core&prefix=QUERY./select

```json
{
  "responseHeader":{
    "status":0,
    "QTime":141},
  "metrics":{
    "solr.core.openlibrary":{
      "QUERY./select.clientErrors":{
        "count":439,
        "meanRate":0.002465493065768435,
        "1minRate":5.257884874358488E-8,
        "5minRate":4.918988170064348E-4,
        "15minRate":0.0017770554113570403},
      "QUERY./select.distrib.requestTimes":{
        "count":0,
        "meanRate":0.0,
        "1minRate":0.0,
        "5minRate":0.0,
        "15minRate":0.0,
        "min_ms":0.0,
        "max_ms":0.0,
        "mean_ms":0.0,
        "median_ms":0.0,
        "stddev_ms":0.0,
        "p75_ms":0.0,
        "p95_ms":0.0,
        "p99_ms":0.0,
        "p999_ms":0.0},
      "QUERY./select.distrib.totalTime":0,
      "QUERY./select.errors":{
        "count":439,
        "meanRate":0.0024654930547102515,
        "1minRate":5.257884874358488E-8,
        "5minRate":4.918988170064348E-4,
        "15minRate":0.0017770554113570403},
      "QUERY./select.handlerStart":1627916732974,
      "QUERY./select.local.requestTimes":{
        "count":18053692,
        "meanRate":101.39237438180135,
        "1minRate":126.05107299763685,
        "5minRate":128.07409482786738,
        "15minRate":131.2787871858724,
        "min_ms":0.035289,
        "max_ms":737.878637,
        "mean_ms":7.014883004589785,
        "median_ms":0.120911,
        "stddev_ms":39.61192985866026,
        "p75_ms":2.26974,
        "p95_ms":30.293151,
        "p99_ms":101.134912,
        "p999_ms":737.878637},
      "QUERY./select.local.totalTime":556332689901445,
      "QUERY./select.requestTimes":{
        "count":18053692,
        "meanRate":101.39237274608074,
        "1minRate":126.05204401082182,
        "5minRate":128.0741919705631,
        "15minRate":131.27881331974777,
        "min_ms":0.042041,
        "max_ms":3437.316774,
        "mean_ms":5.7312996754134735,
        "median_ms":0.137449,
        "stddev_ms":41.228852624645995,
        "p75_ms":2.231775,
        "p95_ms":29.797629,
        "p99_ms":79.610776,
        "p999_ms":448.734494},
      "QUERY./select.requests":18053697,
      "QUERY./select.serverErrors":{
        "count":0,
        "meanRate":0.0,
        "1minRate":0.0,
        "5minRate":0.0,
        "15minRate":0.0},
      "QUERY./select.timeouts":{
        "count":0,
        "meanRate":0.0,
        "1minRate":0.0,
        "5minRate":0.0,
        "15minRate":0.0},
      "QUERY./select.totalTime":556332790688096}}}
```

**Comment by cdrini** [comment]
Forgot to look at the other things in my panic :(

**Comment by cdrini** [comment]
Set up an auto-restarter which has largely removed this as a big problem. Sluggishness now lasts <3min, and happens rather infrequently.

**Comment by cdrini** [comment]
This is looking stable; need to move the auto-restarter somewhere better 😬

**Comment by cdrini** [comment]
Ideally we'd be using `docker swarm` or something, that can handle auto-restarts things, instead of programming our own.
