### ISSUE TITLE
Ability to link/anchor to a specific Book Carousel

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5346]
custom_carousel file within templates/books/custom_carousel.html + macros/QueryCarousel have a mechanism which may be updated which can let us add an `anchor` name so that we'll be able to link to the header of Book Carousels.

### Stakeholders

@mekarpeles @libjenner

**Comment by libjenner** [comment]
I'll take a swing at this. Linking the two links @mekarpeles suggested above, so I can find them easily:

- [templates/books/custom_carousel.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/custom_carousel.html)
- [macros/QueryCarousel](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/QueryCarousel.html)

**Comment by mekarpeles** [comment]
This may have relevant examples: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html
