### ISSUE TITLE
Book page does not display correctly at standard zoom level

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#5365]
The book page does not display correctly at standard zoom level (100%) after the [last deploy](https://github.com/internetarchive/openlibrary/releases/tag/deploy-2021-06-28). It is displayed in a single left-aligned column (this happens between ~960px to ~1050px width). Displayed correctly if zoomed in or out, but at the standard level it behaves strangely.

### Evidence / Screenshot 
![screenshot](https://user-images.githubusercontent.com/7125952/123793119-a99fde80-d8e1-11eb-9db5-684aa39b735e.png)

### Relevant url?
It looks like #5235 could fix this. 

### Steps to Reproduce
1. Go to any book page and switch between different zoom level 

* Actual: The book page is displayed in a single left-aligned column at standard zoom levels (100%)
* Expected:  The book page is displayed in two column at standard zoom levels (100%)

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?** Mozilla Firefox 78.9
- **Operating system?** Debian Stretch 9.13
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
Fix deployed; thanks to @Yashs911 for the fix! Please re-open if you're still seeing the issue, @dcapillae :+1:

**Comment by dcapillae** [comment]
@cdrini I have checked that the same (or similar) issue occurs on author pages. The right column with the author's photo, subjects, places and so on, is displayed below and aligned to the left instead of above and to the right at the standard zoom level. Should I open a new issue?

The works pages are now displayed correctly :+1:.

**Comment by cdrini** [comment]
@dcapillae is that a new issue? Since this week's deploy?

**Comment by dcapillae** [comment]
@cdrini It happens after the last deploy. It did not happen before.

I guess it must be a related issue because it is very similar in behavior to the one just fixed. The content of the author pages is aligned in a single column to the left at the standard zoom level (the author's photo, for example, should appear at the top right, but it appears at the bottom left). A similar behavior to what happened in the book pages.

**Comment by Yashs911** [comment]
Between 960px to 1020px `contentOnethird` shifts down.
![image](https://user-images.githubusercontent.com/64412143/124342427-83c85180-dbe1-11eb-98c1-428a64235e63.png)
Before the deploy max-width of the test-body was 960px and css media queries also changes at 960px.
