### ISSUE TITLE
All links at the top of the author profile page opens author image

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5366]
After merging an author, a "refresh the page" link appears. If one clicks on this, it opens the author photo.
### Evidence / Screenshot (if possible)
<img width="768" alt="Screenshot 2021-06-29 at 14 20 43" src="https://user-images.githubusercontent.com/17739465/123796351-57f95300-d8e5-11eb-84ff-72d34f24bf06.png">

### Steps to Reproduce

1. Go to ...a search that produces duplicate authors
2. Do ...merge the authors
3. click the refresh page link

* Actual: Author photo opens
* Expected: page should refresh

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** 
- **Operating system?** mac os big sur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by seabelis** [comment]
This is also affecting the author search/filter box. If the box is populated, it cannot be re-selected as doing so opens the author image.

**Comment by seabelis** [comment]
From a patron:
I keep trying to add a new book to the page of the author Vera Strange

https://openlibrary.org/authors/OL8328767A/Vera_Strange

because a of a new one that's come out with all the necessary info. But everytime I try to add a new book, for some reason my pointer thinks I'm referring to changing the author's image.

**Comment by jamesachamp** [comment]
Closed by #5370 

Details about the root cause can be found here: https://github.com/internetarchive/openlibrary/pull/5269#issuecomment-871752956
