### ISSUE TITLE
Remove tap-highlight-color for better Mobile UI

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#5369]
### Describe the problem that you'd like solved

The default behavior is that any element (or containing element) that has `cursor: pointer` explicitly set and is clicked will flash blue momentarily. (Only for mobile devices)
### Proposal & Constraints

But in order to improve the UI keeping in mind, the PWA should we remove the default and set it to `-webkit-tap-highlight-color: transparent;`

According to my research, there are no accessibility requirements in [WCAG](https://www.w3.org/TR/WCAG21/) that require the use of `-webkit-tap-highlight-color`.
### Additional context

Current behaviour (When we click the navigation dropdown menu):
![image](https://user-images.githubusercontent.com/64412143/123908996-06f56780-d996-11eb-8de2-1b7e83c64e42.png)

### Stakeholders

@cdrini @bpmcneilly

**Comment by cdrini** [comment]
Ah, it looks like we've set `cursor: pointer` on the whole thing; can we set it just on the `<summary>` tag?
