### ISSUE TITLE
Home page carousels lack clear display of book titles

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#540]
Feedback from user: Book titles should be more clearly displayed near/on their covers, since for many books, it is not obvious from the cover what the book title is.

**Comment by mekarpeles** [comment]
Yup, we should gut and redo carousels... our implementation of jcarousel also seems to render strangely in IE (aside from displaying without title, author, etc).

Will try to address some of these things w/ carousel v2 integration

**Comment by LeadSongDog** [comment]
Can I put in a plea for serving covers from OL not IA? When firewalls block the embedded cross-site links those carousels are super-ugly. Either a thumbnail cache or a proxy would do

**Comment by mekarpeles** [comment]
@LeadSongDog I hear you. I think we can do that.

**Comment by mekarpeles** [comment]
Working on a new carousel design on refactor/carousels

**Comment by LeadSongDog** [comment]
Further to my above, a text-only form (without covers) should look much cleaner than the attached. There should also be a style distinction between the title, the author, and the other info: "by", "(171 editions)" etc. 
![carousel](https://user-images.githubusercontent.com/11435431/30336672-e7063fc6-97b3-11e7-91bf-cb729b836c8a.png)

**Comment by LeadSongDog** [comment]
#496 relates

**Comment by mekarpeles** [comment]
Nominating for #603

**Comment by jdlrobson** [comment]
This seems a little old and was reported about the old jCarousel so I'm bolding resolving this. Please open a new bug if there is something wrong with the current implementation.
