### ISSUE TITLE
staging/testing appearing in Google search!

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5403]
These developer-only endpoints should not be appearing in Google! They likely cause SEO issues or just send our users to the wrong place.

### Relevant url?
- Staging: https://www.google.com/search?q=site%3Astaging.openlibrary.org (1760 results)
- Testing: https://www.google.com/search?q=site%3Atesting.openlibrary.org (2100 results)

### Proposal & Constraints
@RayBB recommends: 

> FYI if you want to have this pages removed from Google you need to serve a noindex for a while before serving the robots.txt
>
> Counter intuitively, if you just add robots.txt it'll keep those pages indexed longer.
> 
> https://developers.google.com/search/docs/advanced/crawling/block-indexing
> https://www.reddit.com/r/TechSEO/comments/mcc98l/googles_unusual_handling_of_robots_noindex/
> 
> Considering it looks like google has 1,650 staging and 2,340 testing urls it may be a good idea to do the noindex first. Especially since those urls are slower and that could cause further SEO issues.

So: 
- [x] #5406 Add `<meta name="robots" content="noindex">` to head when `web.ctx.host != 'openlibrary.org'`
- [x] Wait until the number of search results goes down
- [ ]  #5397 Update robots.txt

### Stakeholders
@RayBB

**Comment by cdrini** [comment]
Dropping to P2 now that the main piece has been done.

**Comment by RayBB** [comment]
As of Aug 12, 2021:
Staging went from 1760 to 1160
Testing went from 2100 to 1090

**Comment by cdrini** [comment]
Now at:
- staging: 770
- testing: 835

**Comment by cdrini** [comment]
Now at:
- staging: 909
- testing: 608

**Comment by cdrini** [comment]
Apparently I can submit bulk removal requests from Google Search Console! Sent those out for staging/testing. Waiting...

**Comment by cdrini** [comment]
It worked! Now the norobots PR should be good to go :+1:
