### ISSUE TITLE
Excerpts has an extra ) parenthesis

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5410]
I added an excerpt to the book as seen below and noticed that there is an extra parenthesis after the contributors name. There is no related opening parenthesis.

### Evidence / Screenshot (if possible)
<img width="759" alt="image" src="https://user-images.githubusercontent.com/921217/125177737-015c0680-e17a-11eb-88ba-f4f1eb556485.png">

### Relevant url?

https://openlibrary.org/works/OL24695783W/Medicine_at_Your_Feet?edition=

### Steps to Reproduce

1. Go to https://openlibrary.org/works/OL24695783W/Medicine_at_Your_Feet

* Actual: Extra )
* Expected: No )

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I looked briefly at the related code for works/editions but didn't see any obvious reason this parenthesis is showing up.

### Related files

https://github.com/internetarchive/openlibrary/blob/040d316aadbd548b2a39768bf6b0faec11b6c834/openlibrary/templates/type/edition/view.html#L286

**Comment by cdrini** [comment]
Ah; I believe there's an extra `)` at the end of the line you referenced 😛 This takes me back to writing racket :)
