### ISSUE TITLE
Redesign Mobile Header Bar

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5423]
With @Yashs911 working towards creating a PWA, we want to make the header bar feel more like a native app's header.

### Designs
Here's the SVG: https://www.dropbox.com/s/6ewocoycrbkykd8/ol%20header.svg?dl=0

#### Logged out users
![image](https://user-images.githubusercontent.com/6251786/125507458-7679a2ea-7930-41d0-a162-ab49de707d6e.png)

#### Logged in users
![image](https://user-images.githubusercontent.com/6251786/125509468-8de945c2-1258-493a-9a43-9bca58f17351.png)

Interaction/UX notes:
- The buttons in the toolbar should have padding; the toolbar itself should not have much (any?) padding. (This makes the click regions larger)
- The click region of each list item needs to be taller. Make sure this is easy to change. The list item `<a` tags should have most of the padding.
- Clicking anywhere outside the drawer will close the drawer
- Clicking on the hamburger icon while the drawer is open will close the drawer
- Optional: swiping from the right edge from anywhere will open the drawer
- The header bar should be sticky
- You should not be able to scroll the document body while the header bar is open (see `overscroll-behavior`)
- You should be able to scroll the hamburger drawer
- The drawer should animate in.
- The "shadow" should animate in.
- Font on Windows should be `Bahnschrift` (pre-installed on windows devices)
- The Browse/More menus should still be there, but won't be sticky. (Longer term, might want to remove these)

Misc notes:
- Longer term, we likely want to add a bottom nav bar; similar to Library Explorer/GoodReads. But not part of this.

### Stakeholders
@mekarpeles @Yashs911 @jdlrobson

**Comment by cdrini** [comment]
@Yashs911 Can you comment on this one? That'll let me assign it to you :P

**Comment by Yashs911** [comment]
@cdrini I would like to work on this issue.

**Comment by Yashs911** [comment]
Now as the hamburger will contain both the "Browse" and "More/Other" Menu options. I think it will be better to remove the Browse and More Dropdown from Mobile View.
Related issue: https://github.com/internetarchive/openlibrary/issues/4788
