### ISSUE TITLE
Unify "My Books" Experience (Reading Log, Lists, Loans)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5434]
### Describe the problem that you'd like solved

Too many different UI's to maintain for "My Books" (Reading Log, Lists, Loans) and no great way to navigate between these views and see summaries of each one at a bird's eye view. Use the http://openlibrary.org/account/books UI as the default, uniform experience for these three views, where the lists and loans may be rendered as inner pages.

### Proposal & Constraints

https://openlibrary.org/account/books would be the default experience that patron sees (e.g. the left side-bar) and the /account/loans and /account/lists view would render as a partial within this wrapper.

### Stakeholders

@cdrini @seabelis @jamesachamp @mekarpeles 

### Relevant Conversations

@mekarpeles: Wanted to chat about a patron's Reading Log + Lists experience. Currently, a patron clicks on their avatar and there's a concept of their Loans their Reading Log and their Lists. https://openlibrary.org/account/books seems like the best representation of what one might expect as a unified experience of these three things

@jamesachamp: That makes sense to me.

@mekarpeles: There was a PR once upon a time (it's on ol-dev0) of a refactor which combines loans, lists, and reading log.

@jamesachamp: How long ago, do you think?

@mekarpeles: 2 years? I can find it. It was like... https://github.com/internetarchive/openlibrary/tree/refactor/everything too old to even run on docker. Making sure all existing links work (e.g. /account/lists) would remains a priority, though I'm thinking of deprecating the /loans experience in favor of something nested within the "my books" UI. Similar to @cdrini's nav bar changes for mobile, I don't know exactly what the verbiage change would be, but the flavor would be to blur the lines between lists and reading log, something like "My Books" or "My Library".

@jamesachamp: Ok.  And that would link to /account/books?

@mekarpeles: At very least, I think it makes sense that https://openlibrary.org/account/lists and http://openlibrary.org/account/loans might load within the same sort of UI showing the left sidebar of menu options. And that there may be some simplification of the My Books main nav menu to link to these new experiences. I'm seeing this as a P3 (P2 at highest) type of refactor, so we're more talking about direction of the front-end which I'd eventually like to discuss with you and @cdrini and put under your leadership once we have a direction. Seems like something community members could also help with. So think of this as (a) strategy / idea stage, (b) RFC, (c) intent for you to eventually be driving that direction. I'm happy to create an issue for it. As we come up with more of these, I'm very interested in your and Drini's thoughts on how we'd prioritize these aesthetic and user-experience-improving changes against each other.

@jamesachamp:
This makes sense to me.  I know that the template with the sidebar could use refactoring (maybe moving reading log components to their own template file).

@mekarpeles:
That reflects my experience as well, from a code perspective. I don't presume the returns will be massive, but I do think it could simplify the experience. The loans page and list pages look pretty unpolished. Making "My Books" more of a dashboard seems like a great way to give patrons a single zeitgeist-style bird's-eye view of books which matter to them.

**Comment by cdrini** [comment]
I think that's a great idea to explore! But we 100% need a mockup before diving into code changes. There is a risk of over simplification here which could result in reduced discoverability. Mockups would help reveal that. Specifically, we'd need: (1) mockups of what options would be in menus; (2) mockups of what the new joint page would look like. Specifically the "Loans" section might need some extra thought

**Comment by jamesachamp** [comment]
I think that the menu options can stay the same.  They would just link to the "My Books" page with the correct view displayed (Reading log, loans, book notes, etc.).

I will include a link to some mock-ups here, once they are completed.

**Comment by cdrini** [comment]
So idea is to make this page more like a master-details interface.

- [ ] Add "My Loans (2)" just above "My Reading Log" in left side bar
- [ ] Clicking my loans displays loans in the right "details" section
- [ ] Clicking a list in the left displays right "details" section
     - [ ] Open Question: List export options? List metadata
- [ ] Clicking "My Lists" brings up https://openlibrary.org/people/ScarTissue/lists in the details section
- [ ] No URLs should be deprecated; they should just go to the my books page with the correct item in the "details" section
- [ ] Make sure any .json endpoints work
