### ISSUE TITLE
Add Open Library author IDs to author pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5435]
### Describe the problem that you'd like solved

Open Library author IDs are needed when creating a Wikidata entry for an author.  An author ID can be copied from the URL of the author's page, but this can be cumbersome (especially for mobile users).  

### Proposal & Constraints

Add the author OLID to the body of the author's page.  The sidebar may be a good location for this.

### Additional context

Additional information about how author IDs are used in this context can be found [here](https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose).
### Stakeholders

@RayBB

**Comment by ashishgits** [comment]
is OL included in the id?

**Comment by ashishgits** [comment]
or just the numbers?

**Comment by ashishgits** [comment]
i want to solve this issue

**Comment by RayBB** [comment]
@ashishgits it will include OL plus the number plus A

**Comment by shanamatthews** [comment]
Whoops - sorry @ashishgits I was already working on this and just put out a PR. I should have commented to say so, my bad!
