### ISSUE TITLE
Link to author identifier docs from author edit page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5436]
### Describe the problem that you'd like solved
Would like to link to the author identifier docs here from the author edit page.
This will make it easy for folks to learn more about identifiers.

Page to link to: https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose

### Proposal & Constraints
<img width="552" alt="image" src="https://user-images.githubusercontent.com/921217/126008757-b6cd50e1-60d9-4e1f-aac6-e79342aab506.png">

Perhaps we should add a question mark directly next to the author identifiers heading that links to this page.

Similar to what we have for the markdown editor (but with a higher quality icon)
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/921217/126008890-81201cb4-0edb-455a-8b65-acca50ac2341.png">

### Additional context

Loosely related to #5435 - which is to make it easy to copy Author ID.

**Comment by Atharva-Shinde** [comment]
I would like to work on this issue, I read the document link above, would you guide me a bit??

**Comment by jtboing** [comment]
Hello. I'd like to help with this issue, if I may.

**Comment by RayBB** [comment]
@jtboing go for it :)

**Comment by jtboing** [comment]
Thanks! I'll get started. Is it okay if I am put as assignee? So that this is shown on my issues tab.

**Comment by RayBB** [comment]
@jimchamp can you assign the issue?

**Comment by goyaldhara** [comment]
Hi, I would like to work on this issue.

**Comment by pranjii** [comment]
I would like to work on this issue

**Comment by RayBB** [comment]
@pranjii this issue already has an open PR by @goyaldhara so I'd recommend working on something else.
If you know some CSS this may be a good issue to try https://github.com/internetarchive/openlibrary/issues/5153

**Comment by yuvy6376** [comment]
Hello, Yuvraj this side I would like to contribute with this issue or any other under your guidance !!!

**Comment by RayBB** [comment]
@yuvy6376 go for it

**Comment by tuba-mouqeem** [comment]
@yuvy6376 are you working on it?

**Comment by yuvy6376** [comment]
> @yuvy6376 are you working on it?
> 

No

**Comment by yuvy6376** [comment]
> @yuvy6376 are you working on it?
> 

Due to medical reasons I can't do it!!!

**Comment by sahilsaini110** [comment]
@RayBB is this issue still active??

**Comment by getuliobr** [comment]
Hi, is this still available @jimchamp ? I'd like to work on this.

**Comment by jimchamp** [comment]
Thanks @getuliobr, I've just assigned you to this.  Please let me know if you have any questions about anything.
