### ISSUE TITLE
Link to author identifier docs from reading stats page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5437]
### Describe the problem that you'd like solved
We should link to docs about author identifiers on the reading stats page.
This is because reading stats are powered by author identifiers (particularly wikidata)

### Proposal & Constraints
Add the info here:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/921217/126009239-6821a6c7-0cd9-43e8-b284-9b4bfa8fa3be.png">

I propose changing
> Demographic statistics powered by Wikidata. Here's a sample of the query used.

To
> Demographic statistics powered by Wikidata. Here's a sample of the query used.
> Improve these stats by adding the Wikidata author identifier following [these instructions](https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose). 

### Additional context

Related to #5436

**Comment by RayBB** [comment]
@Atharva-Shinde I'd recommend staring with this ticket instead since it's a little bit less ambiguous.

The file you need to change is here: https://github.com/internetarchive/openlibrary/blob/6e18fcd514ac872157d6986f55e97e499b2a5bb7/openlibrary/templates/account/readinglog_stats.html#L121

The local setup with docker is pretty well documented. As soon as you change this file it should be live in you local env. No need to restart or anything!

**Comment by Atharva-Shinde** [comment]
ok I am onto it :)

**Comment by Atharva-Shinde** [comment]
can you please verify the changes

**Comment by tfmorris** [comment]
Those [instructions](https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose) are redundant. There's no reason for a user to add things twice when computers are much better at keeping things in sync. Entering the OL ID in Wikidata should be sufficient (after merging all the duplicate OL author records). I never enter IDs anywhere but in Wikidata.

The instructions should also describe how to update the "ranks" for Wikidata to match the current prefered OL ID (for cases where an author record with birth/death dates, but which only had one or two works got reconciled to Wikidata and  then merged out of existence when when there was another author record with many more works (but no dates).

**Comment by RayBB** [comment]
@tfmorris I agree that we should not have to add it twice. The instructions describe the current process. This ticket is only to add a link to the instructions. The link will be relevant even if instructions change.

1. I think it would be great to open a ticket so that IDs only have to be added in once place if there isn't already one.
2. Please also open an issue with copy that you'd like to have added regarding ranks. I think it would be great to add as I'm not even familiar with how that works.

**Comment by Atharva-Shinde** [comment]
I haven't got any email @RayBB,  when should I expect the email or could you please share the link to join the slack ..
