### ISSUE TITLE
Edit button is running away due to long username

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5439]
Edit button seems to be going far to the side when there are long usernames.

### Evidence / Screenshot (if possible)
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/921217/126013449-558be23a-7cb2-4f11-a4d1-e8faeeff2abc.png">
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/921217/126013474-cc8637b2-6e6e-4a5e-8436-fba978b6ae67.png">

### Relevant url?
https://openlibrary.org/works/OL20600W/Gulliver%27s_Travels
https://openlibrary.org/people/glbw

### Steps to Reproduce

1. Go to the pages

* Actual: Edit button are to the side of page
* Expected: Edit button within the bounds of center div

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

IMO it's probably find to clip the usernames with a `...`. Otherwise maybe try to do a text wrapping.

**Comment by the-halfbloodprince** [comment]
Hi, I would be willing to try to fix this, please assign me this issue?

**Comment by RayBB** [comment]
@the-halfbloodprince awesome feel free to start👍

@jamesachamp can you assign?

**Comment by RayBB** [comment]
@mek @jimchamp maybe a small bump in priority with this since NYT bot may touch 10,000s of popular books soon
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/921217/128258059-1ce8a834-3c42-4b7a-bc2f-517a217be37f.png">
