### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [internetarchive/openlibrary#5456]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/commit/b8ae04bcf4fe8c24435de64c39acfe5d8ae2c5cc

Looking forward to your email, thank you for helping us stay on top of security concerns.

**Comment by zidingz** [comment]
Thank you for your swift action!

**Comment by JamieSlome** [comment]
@mekarpeles - just getting in touch to see if you received those reports? To make your life easier, you can view them here:

[Report #1](https://huntr.dev/bounties/6487a64d-c803-4775-a664-1604f3b56076/)
[Report #2](https://huntr.dev/bounties/0c6e4d53-50b4-4039-8a02-641ffa04a198/)
[Report #3](https://huntr.dev/bounties/c2939957-90dd-4f3b-863d-96a890263fec/)
[Report #4](https://huntr.dev/bounties/53d22546-9243-4e73-ae8c-fbbb345a3f3f/)
[Report #5](https://huntr.dev/bounties/e32c85cb-e95b-482d-8ac7-e845d2443670/)
[Report #6](https://huntr.dev/bounties/88c5465e-6c2d-4fdf-b3cd-e6787d8649b6/)
[Report #7](https://huntr.dev/bounties/d9a449f0-932e-4e15-8cc8-c7202013016a/)
[Report #8](https://huntr.dev/bounties/08593d40-2711-46f8-9e7a-e455346e7b8f/)
[Report #9](https://huntr.dev/bounties/35171839-6a38-4084-9b35-6bf64a386f8e/)
[Report #10](https://huntr.dev/bounties/fa4cba6b-1c5e-4101-828a-3b1f7fe863ca/)

To get a better view, you can just visit [your repositories](https://huntr.dev/users/mekarpeles/repositories) page as well 👍
