### ISSUE TITLE
Q: Open Library API to fetch all data (books, authors, subjects) through single api?

### ISSUE THREAD

**Issue by rubinim95** [internetarchive/openlibrary#5458]
is there any api in open library to fetch all data through single api includes books ,authors ,subjects,edition,prices etc..?

**Comment by jimman2003** [comment]
no.. maybe a monthly dump will serve you better?

**Comment by mekarpeles** [comment]
The `search` API is likely the closest if you are only making a single API call. Otherwise, the monthly data dumps are a good choice.

**Comment by cdrini** [comment]
@rubinim95 Can you give an example of what request you're trying to make? That would help a lot :)

If you're looking for getting info about a specific book, the search APIs include things like author name, etc. Eg https://openlibrary.org/search.json?q=harry+potter
