### ISSUE TITLE
Sample Dumps

### ISSUE THREAD

**Issue by MridulaKamath** [internetarchive/openlibrary#5472]
Is it possible to get small dump of works, e.g. 10k records? I am working on a demo application for my project, and while I need this type of data, I don't need 2.2G of it.

**Comment by cdrini** [comment]
If you're comfortable with the terminal, this command will download the first 10k rows of the works dump, and save them in the file `sample_ol_works.txt`

```sh
curl -L 'https://openlibrary.org/data/ol_dump_works_latest.txt.gz' | zcat | head -n 10000 > sample_ol_works.txt
```

Does that help?

**Comment by MridulaKamath** [comment]
Yes! Thank you so much!
