### ISSUE TITLE
Fix /isbn to retry Affiliate API up to 3 times (w/ 1 sec timeout)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5474]
Should be fixed in #6332

Right now if one goes to a page like https://openlibrary.org/isbn/9781797210285 and the book isn't in OL, we enqueue a request for it in the Affiliate Server.

However, after enqueued, Open Library will return a Not Found page (and import the book behind the scenes).

What we should do is if one hits the /isbn endpoint directly, that we should assume they're willing for the import to complete and we should retry up to e.g. 3 times.

### Relevant url?

https://openlibrary.org/isbn/9781797210285

### Proposal & Constraints

Alternatively, we could have GET parameter which lets people skip the retry (if they're trying to just submit books for import)

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L374

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L340

### Stakeholders

@jimchamp @cclauss

**Comment by RayBB** [comment]
Not sure about what level of overhead this may require but it could be nice to perhaps return a status like "pending" or "failed" when you call that endpoint. Something that could just be stored in memory and only kept around for an hour or something. That's perhaps a nicer approach for many tools than just having much longer response times.

**Comment by RayBB** [comment]
Possibly related to #2205

**Comment by mekarpeles** [comment]
The current implementation needs to be fixed because it's spamming the service without exponentially backing-off.

We should update the code so that `/submit` affiliate-server endpoint so that by default it retries=0 times. The /isbn/{isbn} endpoint sould override to use retries=3 with exponential back-off starting at 1 sec (e.g. 1 sec, 2 sec, 4 sec).

https://github.com/internetarchive/openlibrary/blob/master/scripts/affiliate-server#L188-L202
