### ISSUE TITLE
Create endpoint for admins to write-back IDs to Archive.org

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#549]
Open Library now gets most of its availability information from an official Archive.org API maintained by @bfalling. This API works because we took millions of Open Library editions (those for which we had Archive.org items) and we wrote the `openlibrary_work` and `openlibrary_edition` data into their respective archive.org items.

A problem we are currently facing on Open Library is we have many Open Library editions (~5M of them) which don't have (aren't linked to) any works. Around 200,000 of these editions are linked to borrowable or readable Archive.org items.

@hornc is currently working on taking this 200,000 subset of the 5M orphaned OL editions which have Archive.org IDs  (i.e. editions which are not linked to any work) and trying to unorphan them (i.e. attaching them to existing works, or creating new works for them).

To start off, he's identified a simple case where ~10,000 editions can be cleanly merged into existing works. However, in order for this information to be reflected in the new v2 Availability API, these Open Library editions need their Archive.org items updated with `openlibrary_work` and `openlibrary_editions` data.

This can be done by an Archive.org administrator such as @mekarpeles, @bfalling, or @JeffKaplan but we'd like to setup an endpoint (With privileged Archive.org S3 keys on the backend) which allows Open Library adminstrators to update the `openlibrary_work` and `openlibrary_edition` fields of an edition's archive.org item.

**Comment by hornc** [comment]
@mekarpeles  can we close this now as it it complete as far as I understand (unless you have more to add!)

For reference, the admin sync endpoint it:
`/admin/sync?edition_id=OL...M`

**Comment by mekarpeles** [comment]
This task's parent is #732

**Comment by mekarpeles** [comment]
Closing as per https://github.com/internetarchive/openlibrary/issues/549#issuecomment-340947558, but noting that #731 is still requirement
