### ISSUE TITLE
Temporary Planned Email outage: OL Activiations Will Be Down (~6h)

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5497]
We'll want an announcement bar which shows "email info@archive.org to activate email".

Preferably the ops team e.g. @jimbonator may be able to help us activate a batch of emails in bulk given a list of emails?

**Comment by jimbonator** [comment]
Do you mean take a list of user's email addresses and activate their account as though they had clicked the confirmation link in the email we send them on sign-up?  (Since they won't receive the confirmation email during the outage.)

**Comment by mekarpeles** [comment]
Tentatively planning to have a banner up on Friday Aug 20 @ 1pm
