### ISSUE TITLE
/openlibrary/openlibrary/templates/recentchanges/merge-authors/view.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'key' (falling back to default template)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5506]
When trying to view some merge-authors error is thrown. 
`/openlibrary/openlibrary/templates/recentchanges/merge-authors/view.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'key' (falling back to default template)
`
### Relevant url?
https://openlibrary.org/recentchanges/2010/06/03/merge-authors/39673431

### Steps to Reproduce

1. Go to ... https://openlibrary.org/recentchanges/2010/06/03/merge-authors/39673431
2. Do ...

* Actual: above error
* Expected: should be able to see merge history with undo option

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Chrome Version 92.0.4515.107 (Official Build) (x86_64)
- **Operating system?** MacOS BigSur
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by jimman2003** [comment]
Located the issue:
https://github.com/internetarchive/openlibrary/blob/839271fdb367c05bfd9f9b8fa0ca9b1e06f79466/openlibrary/templates/recentchanges/merge-authors/view.html#L21

**Comment by tuminzee** [comment]
@jimman2003 would you like to work on this issue?

**Comment by jimman2003** [comment]
Yes.. As I said , probably a easy fix

**Comment by tuminzee** [comment]
@jimman2003 I have assigned you the issue.
Happy contributing 😄
