### ISSUE TITLE
Is your Email up?

### ISSUE THREAD

**Issue by amammad** [internetarchive/openlibrary#5525]
Hello sir.
can you just tell me that the following email still working or not?
openlibrary@archive.org
and if it is working now, do you receive any email from huntr.dev team?

**Comment by amammad** [comment]
can you just give me any feedback?

**Comment by amammad** [comment]
Hello dears,
can I ask you to Respect me a little and give me just a feedback ?
Best regards.

**Comment by bicolino34** [comment]
@mekarpeles @seabelis give an answer to the person, and finally close the issue.
