### ISSUE TITLE
No module named infogami

### ISSUE THREAD

**Issue by grubeli** [internetarchive/openlibrary#5526]
### Evidence / Screenshot (if possible)
openlibrary solr updater - container keeps restarting due to error: "No module named `infogami`"
![image](https://user-images.githubusercontent.com/74614193/128860758-c129e894-1761-4fe0-afaa-7ae6444add90.png)

### Steps to Reproduce
* docker-compose up

* Actual: restarting
* Expected: access web page

**Comment by jimman2003** [comment]
Try git submodule init in openlibrary folder and rebuild the container

**Comment by grubeli** [comment]
Doesn't help

**Comment by jimman2003** [comment]
Also try pulling the new commits , there was a bug iirc

**Comment by mekarpeles** [comment]
I'm assuming this is no longer an issue?
