### ISSUE TITLE
Merged authors appearing as separate entries in search/subjects

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary#5535]
### Evidence / Screenshot (if possible)
<img alt="Screenshot_2021-08-11-11-55-50-744_com.kiwibrowser.browser.jpg" src="https://user-images.githubusercontent.com/58356745/129035488-dd437beb-b824-4c47-a90b-426b8b4dffbf.jpg" width="300" >
^ Note the 2 "UNICEF"s; these have been merged.

### Relevant url?

Old id: https://openlibrary.org/search?q=author_key%3AOL214662A&mode=everything
Category: https://openlibrary.org/subjects/children#sort=date_published&ebooks=true
### Steps to Reproduce

1. Go to category
2. Observe duplicate result

* Actual: two entries
* Expected: one entry

### Details

- **Logged in (Y/N)?**  
N
- **Browser type/version?** 
Kiwi Browser latest /chromium 93 mobile
- **Operating system?**
Android 11 
- **Environment (prod/dev/local)?** 
prod

### Stakeholders

@cdrini

**Comment by RayBB** [comment]
Same thing happening here with `Danielle Steel`
https://openlibrary.org/subjects/new_york_times_bestseller

**Comment by LeadSongDog** [comment]
I suspect that work records still exist showing the redirect-from author ID and the searched-for subject. Is there a way to find what-links-here for the devalued author ID?

**Comment by cdrini** [comment]
These examples have all been fixed as a result of the latest re-index, but I believe the underlying issue is still present.

**Comment by jimman2003** [comment]
This seems to be solved now, the old author was deleted
