### ISSUE TITLE
Author pages are broken on dev site

### ISSUE THREAD

**Issue by shanamatthews** [internetarchive/openlibrary#5539]
As of some new commit today (may be PR #5534), author pages don't load on the dev site. 

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/3520671/129252409-44c129f4-30d9-49a1-8a71-a753eb5ed87a.png)

![image](https://user-images.githubusercontent.com/3520671/129252421-1d1166cb-d37d-4dfb-97ba-ee34611375e0.png)

### Relevant url?
e.g. http://0.0.0.0:8080/authors/OL18283A/Daniel_Defoe

### Steps to Reproduce
I was taking a look at author page while taking a look at feature request #5435 yesterday and had no issues getting my local setup running.

Today, I pulled from master and ran my local setup again, but author pages were broken 😢 

I've reprod this with a totally fresh git clone & docker setup. 

### Details

- **Logged in (Y/N)?** Y as admin 
- **Browser type/version?** Chrome (latest)
- **Operating system?** macOS (latest)
- **Environment (prod/dev/local)?** local, but it's totally fresh

**Comment by cdrini** [comment]
That looks to be the error! Opening a PR now to unblock folks
