### ISSUE TITLE
Make all IA IDs available to librarians or admins

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5554]
It is difficult to check for duplicate IA IDs when some IA IDs are not visible. 

### Describe the problem that you'd like solved

Make IA IDs visible for librarians (or admins).

### Additional context

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L440-L445
`$ no_index = edition.get_ia_meta_fields().get('noindex', False)
                $for name, values in edition.get_identifiers().multi_items():
                    $ identifier_label = values[0].label
                    $if not (edition.is_in_private_collection() and identifier_label == 'Internet Archive'):
                        $if not (no_index and identifier_label == 'Internet Archive'):
                            $:display_identifiers(identifier_label, values, itemprop=cond(name in ["isbn_10", "isbn_13"], "isbn", `None))``
Add a user.is_librarian().

**Comment by jimman2003** [comment]
There is already a user.is_librarian https://github.com/internetarchive/openlibrary/blob/12d5741f88baa6902f74972cad47608bf5c515ea/openlibrary/plugins/upstream/code.py

**Comment by seabelis** [comment]
This was solved at some point.
