### ISSUE TITLE
Show message for Author + Search pages w/ no ebooks (if ebooks radio selected)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#556]
Show a message when `ebooks` selected and no ebooks available. Or we can have it select `everything` in this case
cc: @JeffKaplan

**Comment by mekarpeles** [comment]
@conditionsofexistence (ps great username)

**Comment by mekarpeles** [comment]
@JeffKaplan also brings us: "search results, to me are odd e.g. https://openlibrary.org/authors/OL125391A/Georges_Simenon?page=6
even though ebooks is selected it tries to display everything so there are many pages but all go blank after page 4 because they are not ebooks"

The easiest imperfect fix is to say, "No ebooks in this page of results"

**Comment by guyjeangilles** [comment]
@jdlrobson Even though #2541 is meant to resolve #2177 , you may be able to kill two birds with one stone and address this issue too.

If you agree, are you willing to be assignee for this issue?

**Comment by cdrini** [comment]
Closed by #2570 ; now it does display a sentence there.
