### ISSUE TITLE
Daisy-only books rendering incorrectly in "ebooks" mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#557]
e.g. https://openlibrary.org/search?q=surely+you%27re+joking+mr.+feynman&mode=ebooks&has_fulltext=true

**Comment by shreyansh23** [comment]
@mekarpeles
Can you throw some light on how to should I proceed and what all changes will be required?

**Comment by mekarpeles** [comment]
Sorry I should have assigned myself to this, I have a fix in progress. Work_search.html has a loop which filters ebooks only but it needs to know which books are print disabled. This was added in #1978

**Comment by guyjeangilles** [comment]
@mekarpeles Labeling this as backlogged. It also seems counter productive to leave a high priority issue to hacktoberfiest. Let me know your thoughts.

**Comment by cdrini** [comment]
This looks like it's working; w print-disabled ticked, print disabled renders: https://openlibrary.org/search?q=surely+you%27re+joking+mr.+feynman&subject_facet=Protected+DAISY&mode=printdisabled . Let's create another issue for improving the UX for print-disabled users.
