### ISSUE TITLE
Does anyone know where I can find field definitions for the openlibrary book database tables?

### ISSUE THREAD

**Issue by TimFromPhx** [internetarchive/openlibrary#5571]
### Question

Does anyone know where I can find field definitions for the openlibrary book database tables?

### Additional context

I'm using the  RESTful APIs to look up books but I am having a hard time finding field definitions for the book tables. I am getting the data just fine but I don't know exactly what the fields mean.
Thanks for any help you can give.

**Comment by jimman2003** [comment]
One source I know of is https://github.com/RayBB/openlibrary-to-sqlite(the column names in the script)

**Comment by TimFromPhx** [comment]
Thanks for your help but when I went to that page you recommended I got a 404 Page not found error. Might you have any other suggestions?

 

Thanks again for your help.

**Comment by hornc** [comment]
I'm not sure if this helps as it doesn't describe database tables, but it does document the JSON API for authors, editions, and works: 

https://github.com/internetarchive/openlibrary-client/tree/master/olclient/schemata

It has formats, and some descriptions and examples.

**Comment by TimFromPhx** [comment]
Charles,

 

It doesn't show field definitions but does have enough data of different types that I can easily tell what the field definition should be.

 

Thank you very much for your help,

 

Tim Anderson

**Comment by jimman2003** [comment]
Try clicking my link on github, I correctted the link ;)

**Comment by TimFromPhx** [comment]
Thanks for the help. I am not sure how to close the question. Can you tell where to go to close my question or you can close it if that is easier. I am new to github. I have coded for a long time but have always used other types of source control.

 

Thanks again for your help,

 

Tim Anderson

**Comment by cdrini** [comment]
It's the button at the bottom here :) 
![image](https://user-images.githubusercontent.com/6251786/130503665-4aacee1c-a0f0-4b10-9dce-d1d545ac6518.png)

But I can close for you :+1:
