### ISSUE TITLE
Add book form does not have disclaimer.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5585]
The add book form does not present the following disclaimer: "By saving a change to this wiki, you agree that your contribution is given freely to the world under CC0. Yippee!"

By the time the patron sees this they have reached the end of the edit form AFTER the initial record has been created.

### Relevant url?
https://openlibrary.org/books/add

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/add
2. Do ...notice there is no disclaimer.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by sarathsajan** [comment]
Hey I want to contribute. So is the edit location inside this file [https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/login.html]. Where should I add the sentence in the webpage.

I coming to this issue from Good First Issue, so pardon for any beginner mistakes from me.
Thanks.

**Comment by sarathsajan** [comment]
Hey I want to contribute. So is the edit location inside this file [Link to the file](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/login.html) Where should I add the sentence in the webpage.

I coming to this issue from Good First Issue, so pardon for any beginner mistakes from me.
Thanks.

**Comment by seabelis** [comment]
@sarathsajan Placement should probably go at the bottom near the submit button.

**Comment by sarathsajan** [comment]
Thanks for assigning this issue to me

* I have made the necessary change to _replicate the disclaimer from "edit book" form to "add book" form_.
* I also did a pull request after making the changes --> #5593 
* Please help me if I am _missing_ any standard procedure for contribution.

Thanks.

**Comment by sarathsajan** [comment]
Hey, much thanks for your time and helping me out to navigate through the codebase and provide a useful contribution to the project.
