### ISSUE TITLE
Organize/spec October presentation

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5597]
Lil' OL jam to present what we've done this year

- [x] Coordinate speakers
- [x] Create slide deck
- [x] Blog posts about OL review/etc

**Comment by mekarpeles** [comment]
https://blog.openlibrary.org/2021/10/20/2021-end-of-year-community-updates/ is our end of year blog post, and we're uploading 2021-10-26-OpenLibrary-Community-Celebration.mp4 to openlibrary-tour-2020
