### ISSUE TITLE
Matrix to Slack bridge

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary#5603]
Currently the community is split between two chat platforms
### Describe the problem that you'd like solved

Connect those two sub-communities
### Proposal & Constraints

Join Slack and Matrix though a bridge

### Additional context

Step to enable the bridge:
![info from the matrix side](https://user-images.githubusercontent.com/58356745/131553935-71d0e836-2d99-4428-aed9-b08153a0c581.png)
![scroll until bridges](https://user-images.githubusercontent.com/58356745/131554214-23570f06-c2fe-45ee-965d-c7149337515b.png)

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
Other context https://matrix.org/docs/projects/bridge/matrix-appservice-slack

**Comment by mekarpeles** [comment]
Not enough bandwidth -- happy to enable what options are necessary on IA slack if someone says what should be done. Otherwise, closing as unplanned
