### ISSUE TITLE
Search Inside results do not display when result is only one item

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5618]
Search inside finds one result and displays that count, but not the result itself.

### Evidence / Screenshot (if possible)
<img width="913" alt="Screenshot 2021-09-02 at 10 10 20" src="https://user-images.githubusercontent.com/17739465/131807575-d69d9960-974a-42b9-89f2-f2083971aea5.png">

### Relevant url?
https://openlibrary.org/search/inside?q=The+Unparalleled+Adventure+of+One+Hans+Pfaall+The+Balloon-Hoax+Mesmeric+Revelation+Ms.+Found+in+a+Bottle+A+Descent+into+the+Maelstrom

### Steps to Reproduce

1. Go to ...https://openlibrary.org/search/inside?q=The+Unparalleled+Adventure+of+One+Hans+Pfaall+The+Balloon-Hoax+Mesmeric+Revelation+Ms.+Found+in+a+Bottle+A+Descent+into+the+Maelstrom
2. Do ...see "About 1 result found in 0.13" but nothing listed.

* Actual: no result listed
* Expected: the one result should be listed.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by RayBB** [comment]
@seabelis is this an intermittent issue? Or perhaps it is fixed? Now I see results

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/921217/134443921-94857013-9d78-4a4c-a51e-ad41b2182d12.png">

**Comment by seabelis** [comment]
Yes, appears to be working as it should now.
