### ISSUE TITLE
Consolidate /account/loans into /account/books to show my checked out books

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#562]
Instead of having a separate page for loans + waitlists (/account/loans) and a different page for lists + reading log (e.g. /account/books), combine them in the /account/books page as e.g. /account/books/loans.

Show the actual books the user has checked out, maybe with a tab/radio to switch between checked out and wishlist

[ Checked out | Wishlist ]
-------------------------------
[ cover ] Title 1 
[ cover ] Title 2
etc

**Comment by guyjeangilles** [comment]
https://openlibrary.org/accounts/loans shows the books I've checked out. I propose closing this issue.

**Comment by jdlrobson** [comment]
This page appears to be 404ing now. Did we remove it by mistake?

**Comment by mekarpeles** [comment]
@guyjeangilles is right -- though the url should be:
https://openlibrary.org/account/loans 

We were considering deprecating this page and showing them in https://openlibrary.org/account/books (all in one place)

**Comment by mekarpeles** [comment]
I'm assigning myself and drastically decreasing priority
