### ISSUE TITLE
Can't add book by Stan Tekiela

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5625]
When I try to add this book is fails
First I tried openlibrary.org/isbn/9781647550912 but that didn't work

So then I tried adding the book manually and that fails too with 
```
/openlibrary/openlibrary/templates/books/check.html: error in processing template: AttributeError: 'author_key' (falling back to default template)
```
OR (if debug true)
```
<h1>&lt;class 'AttributeError'&gt; at /books/add</h1>
  <h2>'author_key'</h2>
  

Python | /home/openlibrary/.pyenv/versions/3.9.4/lib/python3.9/site-packages/web/utils.py in __getattr__, line 105
-- | --
POST https://openlibrary.org/books/add


```
### Evidence / Screenshot (if possible)

<details>
  <summary>Inputs</summary>
  
  
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/921217/132097308-099b6fd9-239c-44b2-966a-b95699a9df53.png">

  
</details>

<details>
  <summary>Stack Trace when debug true</summary>
  
  
![image](https://user-images.githubusercontent.com/921217/132097270-4bb80404-e62b-41db-ad30-975c190a8753.png)

  
</details>

### Steps to Reproduce

1. Go to add book page
2. Try to add book with above author and ISBN
3. See error

* Actual: Couldn't add new book
* Expected: Can add new book

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by RayBB** [comment]
Seems to have been added by import bot a few weeks later

**Comment by Iizuki** [comment]
I'm getting the same _AttributeError: 'author_key'_ error while trying to add a book (Night Flights) for Philip Reeve.

**Comment by cdrini** [comment]
It looks like a separate issue was opened for this here: #5879 . Opting to keep #5879 , since it's more general, whereas this issue is about a specific book.
