### ISSUE TITLE
Public API is down

### ISSUE THREAD

**Issue by jlariza** [internetarchive/openlibrary#5626]
When using the public API, a 500 error status code is being raised.

### Evidence / Screenshot (if possible)
<img width="1224" alt="Screen Shot 2021-09-05 at 11 19 26 AM" src="https://user-images.githubusercontent.com/16421045/132133951-f8532794-bea9-4599-a969-9312178f3c55.png">

### Relevant url?
https://openlibrary.org/search.json?q=the+lord+of+the+rings

### Steps to Reproduce

1. Go to https://openlibrary.org/search.json?q=the+lord+of+the+rings

* Actual: a 500 error status code is returned
* Expected: a 200 success status code is returned with the results of the search query

### Details

- prod
- I tried it with brave and with postman; both are returning same 500 status code

**Comment by jimman2003** [comment]
it is working for me now on brave,try again ?

**Comment by jimman2003** [comment]
can you close the issue?, if this is solved

**Comment by jlariza** [comment]
It is working now. Thank you
