### ISSUE TITLE
API returns different works from solr

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary#5629]
In the Web UI/Solr Edgar Allan Poe solr return all of his normal works
in the API a single work is returned , unrelated to him
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/58356745/132247264-0fc3c6c5-c03f-4f79-9471-92d846023e1b.png)
vs
```{"covers": [8091919], "birth_date": "19 January 1809", "remote_ids": {"viaf": "60351476", "isni": "0000000121354025", "project_gutenberg": "481", "wikidata": "Q16867", "librivox": "21"}, "personal_name": "Poe, Edgar Allan", "type": {"key": "/type/author"}, "alternate_names": ["Edgar Alan Poe", "Poe, Edgar Allan", "Edgar A. Poe", "Poe,Edgar Allan \u30dd\u30fc,\u30a8\u30c9\u30ac\u30fc\u30fb\u30a2\u30e9\u30f3 (1809-1849)", "Edgar Poe", "/Edgar Allan Poe/Alihassanifard", "Poe Edgar Allan", "Poe E.A.", "Edgar Allan 1809-1849 Poe", "Edgar Allan Poe,Edgar Allan Poe", "Edgar ALLAN POE", "Poe, Edgar Allan, 1809-1849", "EDGAR ALLAN POE", "POE EDGAR ALLAN", "Edgar allan Poe", "Edgar Allan POE", "Edgar Allan, Poe,", "Poe Edgar Ala", "POE Edgar Allan", "E. Poe", "POE-E", "E. A Poe", "E. A. Poe", "E.A.: Poe", "(mei) Po"], "links": [{"title": "Wikipedia", "url": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe", "type": {"key": "/type/link"}}, {"title": "BookBrainz", "url": "https://bookbrainz.org/author/6eef1b1c-a4a2-4c8d-a37c-75df656b5178", "type": {"key": "/type/link"}}, {"url": "https://inventaire.io/entity/wd:Q16867", "title": "inventaire.io", "type": {"key": "/type/link"}}], "ocaid": "b29820364", "bio": {"type": "/type/text", "value": "Edgar Allan Poe was an American writer, poet, editor and literary critic, considered part of the American Romantic Movement. Best known for his tales of mystery and the macabre, Poe was one of the earliest American practitioners of the short story and is considered the inventor of the detective-fiction genre. He is further credited with contributing to the emerging genre of science fiction.[1] He was the first well-known American writer to try to earn a living through writing alone, resulting in a financially difficult life and career.[2]\r\n\r\nSource and more information: https://en.wikipedia.org/wiki/Edgar_Allan_Poe"}, "key": "/authors/OL28127A", "death_date": "7 October 1849", "source_records": ["ia:b29820364", "amazon:0353090670", "amazon:9603221163", "amazon:1517348064", "amazon:1435166884", "amazon:1731578679", "amazon:2850184691", "amazon:149616640X", "amazon:8479051256", "amazon:201134235X", "amazon:3379004510"], "name": "Edgar Allan Poe", "title": "(mei)", "photos": [6015207, 3367197, -1], "works": [{"key": "/works/OL17806159W"}], "latest_revision": 24, "revision": 24, "created": {"type": "/type/datetime", "value": "2008-04-01T03:28:50.625462"}, "last_modified": {"type": "/type/datetime", "value": "2021-08-31T16:08:28.552600"}}``` (API respone)

### Relevant url?

https://openlibrary.org/authors/OL28127A/Edgar_Allan_Poe (web UI)
https://openlibrary.org/authors/OL28127A.json (API)

### Steps to Reproduce

1. Go to https://openlibrary.org/authors/OL28127A.json
2. Observe the works of the author

Note that no other author I have seen have works in his json response

* Actual: different works for web ui/solr and api
* Expected:  same works for web ui/solr and api

Note that https://openlibrary.org/authors/OL28127A/works.json returns correct results 
### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?**  Chromium 93
- **Operating system?**  Linux
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles , @cdrini

**Comment by cdrini** [comment]
Ah this looks like a bug; the https://openlibrary.org/authors/OL28127A.json endpoint should not return any works! It should only return metadata about the author themselves.

This seems like a bug related to #6145 ; here is the edit where this data was added: https://openlibrary.org/authors/OL28127A.json?v=10 . I cleaned up this specific record, so closing this issue.
