### ISSUE TITLE
Works page is deformed (overflowing div and rating stars doubled)

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5638]
It'll be clear from the screenshot but text is going over the side of the page, also the rating stars are doubled.

### Evidence / Screenshot (if possible)
<details>
  <summary>Spoiler</summary>
  
  
![openlibrary org_works_OL17805397W_Cracking_the_Coding_Interview_edition=](https://user-images.githubusercontent.com/921217/132550381-1ddb489c-22af-493e-9d38-211fede429fe.png)

  
</details>

### Relevant url?

https://openlibrary.org/works/OL17805397W/Cracking_the_Coding_Interview?edition=

### Steps to Reproduce

1. Go to https://openlibrary.org/works/OL17805397W/Cracking_the_Coding_Interview?edition=

* Actual: Works page text overflowing and rating doubled
* Expected: Text inside center dive and rating not doubled

### Details

- **Logged in (Y/N)?** Both
- **Browser type/version?** FF/Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by rgrupesh** [comment]
Hello @RayBB 

I would like to work on this issue. I look around and I didn't find other pages with the above issue. So, I'm guessing I need to work on that specific page only. And, by rating doubled, you meant the size of the stars, right?  

Is there anything I should know of?

**Comment by RayBB** [comment]
@rgrupesh unfortunately, I am not in a position to guide you as I don't fully understand the issue myself.

However, since it is labeled as a P0 I believe that some of the staff members will fix this since it is urgent.

However, if you know CSS this may be a good first issue to try https://github.com/internetarchive/openlibrary/issues/5153

**Comment by mekarpeles** [comment]
The issue is that the Work + Edition descriptions contain formatting such as `<code>` which are causing their content divs to overflow.

Either the work description and edition description sections need to somehow be restricted or an overflow-auto needs to be added to that component (e.g. `work-description code { overflow: auto }` -- NB: this is pseudo-code)

**Comment by rgrupesh** [comment]
@jimchamp 

Any pointers to get started?

**Comment by jimchamp** [comment]
Sure.  Like @mekarpeles explained, there is a `<code>` block that is causing the main content area to overflow.  This `<code>` element is located in the work description of the [page](https://openlibrary.org/works/OL17805397W/Cracking_the_Coding_Interview?edition=).  We can tell that this is causing an issue by observing the main content's width change when the `<code>` element is deleted:
![Peek 2021-09-13 10-52](https://user-images.githubusercontent.com/28732543/133108745-84f59afd-b43a-4b62-b0e4-97e7c263ef20.gif)

You'll want to add some style rules that will keep that element from overflowing.  When I'm working on something like this, I tend to experiment with new styles using the browser devtools to start.  Once I find something that works, I add the new CSS to the appropriate `.less` file(s), compile the CSS, and check that the changes worked as expected.

To test this locally, you may want to update the description of a book on your local instance to include a sizeable `<code>` block.  Using the description from the linked page would probably be best.  You can get this by copying the work description from the [edit work page](https://openlibrary.org/books/OL26395119M/Cracking_the_Coding_Interview_189_Programming_Questions_and_Solutions/edit) (ensure that the "Work Details" tab is selected):
![Screenshot from 2021-09-13 11-17-54](https://user-images.githubusercontent.com/28732543/133110918-f7005afa-2328-462b-85b9-956bd2459407.png)

**Comment by rgrupesh** [comment]
@jimchamp I'm working on applying some rules to those specific `.less` files. BTW, how do I get full functional instance of site on my local machine? I cannot find some pages and books on my local instance. Any back-end specific tools that I need to install?

**Comment by jimchamp** [comment]
Here are some ways that you can import data onto your local environment: https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

I executed the following to import the book used as an example earlier:
```bash
docker-compose exec -uroot web bash
./scripts/copydocs.py /books/OL26395119M --recursive
```
After the script successfully imports the book, you can view the page locally here: http://localhost:8080/works/OL17805397W/Cracking_the_Coding_Interview?edition=

The overflow is still present when I view this page locally.

**Comment by RayBB** [comment]
The issue is likely related to https://github.com/internetarchive/openlibrary/issues/5473#issue-956042886

**Comment by jimchamp** [comment]
> The issue is likely related to [#5473 (comment)](https://github.com/internetarchive/openlibrary/issues/5473#issue-956042886)

@RayBB are you referring to the lack of data on @rgrupesh's local instance?

@rgrupesh when you visit your local instance's homepage, is the classic works carousel populated? Your homepage should look something like this:
![Screenshot from 2021-09-18 07-08-12](https://user-images.githubusercontent.com/28732543/133887072-06ddec76-5817-4e34-a307-303de85c2003.png)

If you don't see any books in the carousel, you may have to briefly wait before visiting the site after you run `docker-compose up`.  When you see `openlibrary_home_1 exited with code 0` in the logs, all of the data has been loaded in the local instance and can be viewed on the local site.

**Comment by rgrupesh** [comment]
@jimchamp This is what I have on my local instance. I see some books.

![Screenshot from 2021-09-19 09-59-04](https://user-images.githubusercontent.com/54068868/133915258-0c4741dd-0f8a-48ab-9336-94e14d57ed8b.png) 

And regarding the issue, adding `overflow: auto` to the `<code>` solves the issue but it deforms other part of the webpage.

![Screenshot from 2021-09-19 10-11-46](https://user-images.githubusercontent.com/54068868/133915489-f8277ad3-c52a-4613-ac8f-a9b6273a4c9b.png)

deformed nav-bar due to addition of  `overflow: auto`:

![Screenshot from 2021-09-19 10-12-06](https://user-images.githubusercontent.com/54068868/133915492-06e7d444-d32b-4dcb-ae9b-d26492422edc.png)

The issue seems to be coming from work-description class. `work.less` file doesn't have css code related to that class. Where should I look for? Besides, setting `white-space:normal` to `<code>` will do the trick but it violates the very purpose of `<code>` tag.

**Comment by jimchamp** [comment]
Your homepage look good!

It looks like you will have to add `.work-description` to `work.less`.  Something like this would probably work:
```less
.work-description {
  code {
    /* Your styling rules */
  }
}
```
