### ISSUE TITLE
Set up a GitHub page for Open Library's Storybook

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5643]
### Describe the problem that you'd like solved

Now that we have Storybook set up, it would be nice to publish our Storybook on a GitHub page.  This could replace our [design pattern library](https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library) once we have stories for all of our components.

### Proposal & Constraints

Create a GitHub page for this repository.  Set up an action to deploy Storybook to the page when updates have been made.

Will likely need to use [Storybook Deployer](https://github.com/storybookjs/storybook-deployer) for this.

### Stakeholders

@jdlrobson

**Comment by jimchamp** [comment]
I've got everything up and running on my fork: https://jimchamp.github.io/openlibrary/

I'd like to include this as a part of our CI flow.  Once I've sorted that out, I'll open a PR.

**Comment by jdlrobson** [comment]
Nice!
