### ISSUE TITLE
Submission feedback missing from Book Tags modal

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5646]
When a book tag is selected or removed, a message is sent to the server and the change is persisted.  Although this is happening, it is not clear to patrons that their selections are being saved.

Previous iterations of the Book Tags modal displayed toast messages on submission success or failure.  This should still be happening today, but is not.

### Steps to Reproduce

1. While logged in, go to a book page.
2. Open the book tags modal and select some tags.

* Actual: No indication of submission is given.
* Expected: Some visual feedback telling me that selections have been saved.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Display toast messages on submission success or failure.  Remove tag from selected collection if its submission somehow fails.

**Comment by mekarpeles** [comment]
Let's please adjust this so it says, "Your changes are automatically saved" in green, **unless** there is some error, but this can be a separate issue.
