### ISSUE TITLE
Not Able to Upload Cover Image

### ISSUE THREAD

**Issue by ma8642** [internetarchive/openlibrary#5649]
Not able to upload cover images.  I tried this twice with 2 different books.

### Evidence / Screenshot (if possible)
https://www.loom.com/share/183e628d6ae848e4a96775c283ae607d

### Relevant url?
1. https://openlibrary.org/books/OL25346052M/Around_Windham
![20210911_131855](https://user-images.githubusercontent.com/13713037/132963173-d1665279-e06b-4633-b0ea-649431247c79.jpg)

2. https://openlibrary.org/works/OL23175393W/Skiing_in_the_Catskill_Region
![51xVer0iHhL](https://user-images.githubusercontent.com/13713037/132963453-06f97d71-34f1-42ef-9db6-c93f17184ae6.jpg)

### Steps to Reproduce

1. Go to either of the relevant urls
2. Try to upload the photos above as cover image

* Actual: User prompted to add missing url.
* Expected: Photo should upload successfully.

### Details
Error: `Uncaught TypeError: s(...).val() is undefined`

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 91.0.2
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by ma8642** [comment]
I have found that this is a duplicate of this closed issue:  https://github.com/internetarchive/openlibrary/issues/5637

Perhaps it has been fixed and the fix just isn't deployed to prod yet?  Happy to close if so.

**Comment by jimchamp** [comment]
> Perhaps it has been fixed and the fix just isn't deployed to prod yet?

This is correct.  The fix should be deployed to prod later this week.  In the meantime, you can upload images using our testing site: https://testing.openlibrary.org
