### ISSUE TITLE
ImportBot adding multiple instances of same author when author has multiple roles on amazon

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5650]
The problem is related to  #756 but different because we aren't talking about creating new authors. Just adding the same author twice.

I believe this happens with author is also the illustrator or similar
<img width="260" alt="image" src="https://user-images.githubusercontent.com/921217/133016372-6e14f2ad-b2df-4731-96da-95f0d831e5f7.png">

There are ~25,000 works with the same authorID is added twice.
I discovered this from analyzing the data dumps using my [sqlite importer](https://github.com/RayBB/openlibrary-to-sqlite).

### Evidence / Screenshot (if possible)
A few examples: OL24626887W, OL24591068W, OL24539272W

* Actual: When author is also illustrator, author is added twice
* Expected: When author is also illustrator, author is added once (and maybe also noted as illustrator elsewhere)

### Proposal & Constraints

I propose three courses of action
1. Stop the author ids from being added to a work multiple times
2. Fix import bot to add other roles as such
3. Run a batch script to fix the remaining cases where this is still happening

**Comment by RayBB** [comment]
Script to find duplicate authors ids:
```
import sqlite3
import json
from tqdm import tqdm

connection = sqlite3.connect('openlibrary_works.sqlite3')

c = connection.cursor()    
c.execute('SELECT * FROM works') 
works_with_duplicate_authors = []

for row in tqdm(c):
    work_id = row[-11]
    authors_str = row[10]
    if authors_str is None:
        continue
    authorArray = json.loads(authors_str)
    authorSet = set(authorArray)
    if len(authorArray) != len(authorSet):
        works_with_duplicate_authors.append(work_id)


f = open("works_with_duplicate_authors.txt", "a")
f.write(",".join(works_with_duplicate_authors))
f.close()
```

List of works with duplicate authorids
[works_with_duplicate_authors.txt](https://github.com/internetarchive/openlibrary/files/7508210/works_with_duplicate_authors.txt)

**Comment by RayBB** [comment]
https://openlibrary.org/people/whitespacebot is working on it! Thanks @jimman2003

**Comment by RayBB** [comment]
Just got the latest dump and checked for works with duplicate authors. These were the only ones I found:

> OL19302720W,OL26145390W,OL26293105W,OL26297374W,OL26294507W,OL26132434W,OL26173229W,OL26291641W,OL20180449W,OL15063571W,OL26181665W,OL26285366W,OL26190753W,OL26291959W,OL26323390W,OL6595019W,OL26196231W,OL26292457W,OL15132668W,OL26178394W,OL26333429W,OL26298248W,OL26421841W,OL26305252W,OL19626052W,OL18490992W,OL16481077W,OL26292656W

@jimman2003 if you wouldn't mind running your bot over these last few that would be great!

**Comment by jimman2003** [comment]
I fixed almost all of them , except OL26292656W , weird error https://gist.github.com/jimman2003/3117fb8913c4858dc09e4dd01e9d6e23
