### ISSUE TITLE
Strange visual effect when hovering over cover image

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5658]
This was previously as a Firefox issue and now in Chrome as well. When hovering over the cover image on a work or edition page the image stretches across the screen. I noticed this in Chrome after upgrading to Version 93.0.4577.63 (Official Build) (x86_64).

### Evidence / Screenshot (if possible)
https://internetarchive.slack.com/files/U0235436KAR/F02DF09E24A/the_big_game__november_1__1993_edition____open_library_-_google_chrome_2021-09-04_17-14-05.mp4

### Steps to Reproduce

1. Go to ...any work or edition page
2. Do ...hover over the cover img

* Actual: image stretches across display
* Expected: either nothing or the usual wiggle (or whatever you want to call it)

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Version 93.0.4577.63 (Official Build) (x86_64)
- **Operating system?** MAC OS
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by cdrini** [comment]
@seabelis Can you download / re-upload the mp4 here? The slack link won't work for everyone.

**Comment by jimchamp** [comment]
Here's an example of the problem:

![image_glitch](https://user-images.githubusercontent.com/28732543/134102444-a23e58e8-d0e5-4172-879d-cad4d923e198.gif)
