### ISSUE TITLE
Excessive speed throttling when downloading data dump

### ISSUE THREAD

**Issue by jimman2003** [internetarchive/openlibrary#5662]
### Relevant url?

https://openlibrary.org/developers/dumps/
### Steps to Reproduce

1. Go to https://openlibrary.org/developers/dumps/
2. Download any dump from there

* Actual:  download speeds start 1mb/s and then get throttled to 100 kb/s
* Expected:  download speeds 1mb/s all the way

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Chromium 93
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by RayBB** [comment]
It is a pain that I too would like to see fixed. 
However, in the meantime I recommend downloading via the torrent. You can even use aria2c if you're inclined to use CLI.
It is still throttled from OL server but when I downloaded there were other peers seeding that sped it up quite a bit.

Also as a hack I started downloading it from several machines and then it went much faster.

**Comment by jimman2003** [comment]
Yeah, but the torrsnt creation is not automated , so everytime I have to bug the staff

**Comment by cdrini** [comment]
I think we need to confirm that this is just a redirect to IA. If it is, then this is IA's problem ?

**Comment by jimman2003** [comment]
IIRC from the archive of ia it has the same symptoms

**Comment by brierjon** [comment]
Along the Cloudflare CDN route, maybe looking at IPFS pinning of the dumps? - [https://developers.cloudflare.com/distributed-web/ipfs-gateway](https://developers.cloudflare.com/distributed-web/ipfs-gateway)

There may be possible funding to pursue if further work is needed - [https://github.com/ipfs/devgrants](https://github.com/ipfs/devgrants)

**Comment by mekarpeles** [comment]
I think this was related to bandwidth limitations that IA was facing that should no longer be affecting us.
