### ISSUE TITLE
Why won't book work 9789400404588 import using the isbn endpoint?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5665]
Wondering why this book won't import when using the isbn endpoint.
It has an Amazon product page on the US website.

Is there something missing?

### Relevant url?
https://openlibrary.org/isbn/9789400404588
https://www.amazon.com/gp/product/9400404581/

### Steps to Reproduce

1. Go to https://openlibrary.org/isbn/9789400404588
2. See that it isn't imported

### Proposal & Constraints
Not sure how to debug or investigate this but since it's related to the goal of improving import pipeline I figured I'd start a thread.

### Stakeholders
@mekarpeles

**Comment by RayBB** [comment]
Going to drop some additional links here that aren't importing:
https://openlibrary.org/isbn/9798451851142
https://openlibrary.org/isbn/9798477298242
https://openlibrary.org/isbn/9798478416973
https://openlibrary.org/isbn/9798473603255
https://openlibrary.org/isbn/9798542548203
https://openlibrary.org/isbn/9798458396417
https://openlibrary.org/isbn/9798475879832
https://openlibrary.org/isbn/9798704878636
https://openlibrary.org/isbn/9798735188681
https://openlibrary.org/isbn/9798521158522

Pretty much all from amazon recent books lists.

**Comment by cdrini** [comment]
@mekarpeles suggests looking at openlibrary/core/vendors.py, and triggered that code manually from the production affiliate container

**Comment by mekarpeles** [comment]
Closing as 1-off
