### ISSUE TITLE
Borrow buttons should indicate loan duration

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5684]
The borrow button displays the same for items that can be borrowed for 1 hour and items that can be borrowed for 14 days. Patrons have to click each available copy to find the loan type they want.

### Proposal & Constraints
Buttons should read "1 Hour Loan" and "14 Day Loan" or something similar to indicate the loan duration at a glance.

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
This is now deprecated as behavior is session/browse by default with the option to extend
