### ISSUE TITLE
Increase in internal errors since ~Sep 9

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5685]
Cause of increase unknown. Potentially related to some of the import work? This is causing our alerts to become very noisy.

![image](https://user-images.githubusercontent.com/6251786/134227797-1708f980-1284-40ae-ae32-5608cbfce7fb.png)

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
stale; likely relevant, but lots changed in how we're running the pipeline in the past year
