### ISSUE TITLE
Stale/deleted subjects returned by /subject search

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#569]
e.g. https://openlibrary.org/search/subjects?q=juvenile+fiction -- most pages 404, we may want the solr re-indexer to prune outdated subjects

**Comment by tfmorris** [comment]
The 404s are actually due to the forward slash (/) handling bug described in #333, rather than a stale index.

I'm going to close this as a duplicate, but feel free to reopen if you disagree.

**Comment by tfmorris** [comment]
As an example, "JUVENILE FICTION / Historical / Medieval" is actually
at https://dev.openlibrary.org/subjects/juvenile_fiction__historical__medieval
not https://dev.openlibrary.org/subjects/juvenile_fiction_/_historical_/_medieval
