### ISSUE TITLE
I18n of welcome carousel

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5698]
### Question

Nice work on the welcome carousel, looks neat. One question though, is there any plans to i18nalize this part?
Same as the subjects page?

### Stakeholders

#791, @cdrini

**Comment by mekarpeles** [comment]
The strings should be primed already for i18n, we just need to rerun our translations and get volunteers to fill in the missing translations :)

@lephemere -- @jimchamp will let you know when we've recompiled the translations and we'd love your help if you're willing :)

**Comment by jimchamp** [comment]
![image](https://user-images.githubusercontent.com/28732543/210845473-74692e21-0e01-4c49-8234-d31b9c555367.png)

Closing as completed.
