### ISSUE TITLE
Dark Theme for the Website

### ISSUE THREAD

**Issue by ShaileshKumar007** [internetarchive/openlibrary#5715]
### Describe the problem that you'd like solved

I think It's good to have a dark mode option on the website.

### Proposal & Constraints

As we all know that most of the websites and apps in today's world are using the dark theme, even big companies like google also using this so why can't we.

One way to do this is to run a script that will toggle the theme when someone clicked on the Switch button

### Additional context

![imgonline-com-ua-twotoone-HCXFICVoMra](https://user-images.githubusercontent.com/71178959/135739291-b89cf981-f94d-4317-8e1e-5f20afeb8cab.jpg)

**Comment by Yashs911** [comment]
Duplicate https://github.com/internetarchive/openlibrary/issues/4448

**Comment by mekarpeles** [comment]
Thank you all, glad these issues are now linked, closing as duplicate. Thank you for giving us this suggestion 
@ShaileshKumar007!
