### ISSUE TITLE
Manually copy sitemaps from ol-home0 to ol-www1

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5720]
Fixed in internetarchive/olsystem#143

Temporary shim while #5674 is not working.

No instructions for this! Investigate the cron file.

**Comment by cclauss** [comment]
Related to #5674

**Comment by cclauss** [comment]
Currently, the sitemaps file on ol-www1 are 264 days old.
```
>>> now = datetime.now()
>>> sitemap_path = Path("/1/var/lib/openlibrary/sitemaps/sitemaps")
>>> print(max((now - datetime.utcfromtimestamp(filepath.stat().st_mtime)).days for filepath in sitemap_path.iterdir()))
264
```

**Comment by cclauss** [comment]
Tried from __ol-home0:__ `rsync -r -v --progress /1/var/tmp/sitemaps ol-www1:/1/var/lib/openlibrary` both with `sudo` and without and got permissions errors both ways.
