### ISSUE TITLE
Is there a way to force a refresh or reindex of a work's cover image?

### ISSUE THREAD

**Issue by libjenner** [internetarchive/openlibrary#5730]
### Question

I can often force a refresh of a work, edition, author, or subject by using the solr admin page. That works great. Is there a way to force a refresh of the cover image to reflect a recently changed cover?

### Additional context

You can see the problem [on this page](https://openlibrary.org/collections/test-follow-merged-works).

There are two works that are showing the same cover, A Land Apart From Time and Journey to Chandara. 

ALAFT in the carousel is showing the cover from JTC, even though no editions attached to the ALAFT work have that cover. I think the cover got associated with ALAFT because there _was_ an edition of JTC attached to ALAFT incorrectly. I moved that JTC edition to the correct work, but the ALAFT work's cover never updated after that.

### Issue resolution criteria

Maybe this is a bug? Maybe this is just as easy as me submitting the work to be reindexed somewhere? 

### Stakeholders
@libjenner

**Comment by seabelis** [comment]
https://openlibrary.org/works/OL19650750W/Dinotopia/manage-covers
https://openlibrary.org/works/OL19650750W/Dinotopia/add-cover

**Comment by libjenner** [comment]
It never even occurred to me that you could get to the work directly --- thank you @seabelis! If this isn't in docs, I'll add it. I think that's all I needed.

**Comment by libjenner** [comment]
This is related to #4992
