### ISSUE TITLE
Two books in a carousel are showing "Not in Library" when borrowable editions exist

### ISSUE THREAD

**Issue by ghost** [internetarchive/openlibrary#5732]
In the [Newbery Medal Winners](https://openlibrary.org/collections/newbery-medal) collection, two books in the 1970s carousel show "Not in Library" but both works have multiple borrowable editions.

### Evidence / Screenshot (if possible)

![1970s-newbery](https://user-images.githubusercontent.com/85025703/136055278-a7fa0e5f-68c6-4f37-b433-d8bee4e75e45.png)

### Relevant url?

https://openlibrary.org/collections/newbery-medal

### Steps to Reproduce

1. Go to the [Newbery Medal Winners Collection](https://openlibrary.org/collections/newbery-medal) page.
2. Scroll down to the 1970s carousel.
3. Click on Bridge to Terabithia or Julie of the Wolves. 

* Actual: Bridge to Terabithia and Julie of the Wolves appear to be Not in Library. Clicking on each work opens a work page with an un-borrowable edition in focus.  
* Expected: Bridge to Terabithia and Julie of the Wolves should be showing blue Borrow buttons just like all the other books in the carousel. Clicking on each work page should open the work page with a borrowable book in focus.

### Details

- **Logged in (Y/N)?** both
- **Browser type/version?** Firefox 91.0.2 for Mint
- **Operating system?** Linux Mint 20
- **Environment (prod/dev/local)?** prod, testing

### Proposal & Constraints

I'm 100% sure this is already covered by another issue (probably related to IA availability) but I never get a clear answer when I mention it so I'm creating this issue to document what's going on. 

I bet we're losing patrons who see a "not in library" and don't bother to click to find out otherwise. For now, curators have been adding disclaimers to the top of collections pages, suggesting patrons click on the work to be sure that a borrowable edition doesn't exist, but I would love for this to Just Work. 

### Stakeholders
@libjenner

**Comment by libjenner** [comment]
@mekarpeles said in chat, _carousels are powered by solr. Solr indexes works. It has a list of archive.org ids associated with that work. It checks the first in the list._ 

Is there a way we can check the first borrowable in the list?

**Comment by mekarpeles** [comment]
Solr now also indexes editions, we may have more control over the solution here; added @cdrini as lead

**Comment by cdrini** [comment]
This appears to be fixed, but I had to update the work IDs because some were redirects 😬

https://openlibrary.org/collections/newbery-medal?_compare=Compare&b=24&a=23&m=diff
