### ISSUE TITLE
Books and covers API different results

### ISSUE THREAD

**Issue by Richb987** [internetarchive/openlibrary#5745]
I am using the Books API - searching by ISBN. I have noticed that sometimes the response has no cover image urls, but then if I use the covers URL directly - I do get an image.

e.g. ISBN: 9780006547136

the books url: https://openlibrary.org/api/books - does not return cover image urls, but when I call, e.g. https://covers.openlibrary.org/b/isbn/9780006547136-L.jpg - I do get an image

**Comment by linzinha** [comment]
It looks like there's not a cover for this edition: 
https://openlibrary.org/books/OL22643573M/Fuzzy_thinking

What calls are you running to get the different results?

**Comment by mekarpeles** [comment]
This may be an issue with resolving redirects. I'm going to close as stale for now
