### ISSUE TITLE
Cannot reverse deleted or merged works

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5753]
When trying to reverse some merged works, an error is thrown. 
```
/openlibrary/openlibrary/templates/books/RelatedWorksCarousel.html: error in processing template: TypeError: Object of type Nothing is not JSON serializable (falling back to default template)
Hmm...
Sorry. There seems to be a problem with what you were just looking at.

We've noted the error 2021-10-12/170342688830 and will look into it as soon as possible. Head for home?
```
### Relevant url?
https://openlibrary.org/works/OL14918267W?v=2&m=revert
https://openlibrary.org/works/OL23224294W?v=2

### Steps to Reproduce

1. Go to ...a deleted work
2. Do ...roll back to an earlier version

* Actual: see error above
* Expected:  previous version should be restored

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by b2pacific** [comment]
Hey @jimchamp , I would like to work on this issue. Can you assign it to me?

**Comment by jimchamp** [comment]
#6047 allows merged and deleted works to be reversed, but not without displaying another error message.  If/when another error is displayed in testing, I can find details about the error on the server and troubleshoot the issue given the error message.
