### ISSUE TITLE
Lending button text is cut off in other languages

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#5754]
The text of the lending buttons appears cut off in the translated versions of the site. The error is repeated systematically in several places (edition pages, author pages, searches, lists, etc.).

### Evidence / Screenshot 
Only some examples:

1. Home page carousels: Should read "No en la biblioteca", but only reads "No en la bibliote".
![1_boton-no-en-la-biblioteca-aparece-cortado-en-carruseles_es](https://user-images.githubusercontent.com/7125952/137000158-97463e5f-e2f4-45e8-8ac0-7997cd0bd941.jpg)
2. Search page: Should read "Unirse a la lista de espera", but only reads "Unirse a la lista de es".
![2_boton-unirse-a-la-lista-de-espera-aparece-cortado-en-pagina-de-busqueda_es](https://user-images.githubusercontent.com/7125952/137002421-f20aba85-e2af-4a2c-826c-49eb4a5e2bbf.jpg)
3. Author page: Should read "Unirse a la lista de espera", but only reads "Unirse a la lista de espe".
![3_boton-unirse-a-la-lista-de-espera-aparece-cortado_es](https://user-images.githubusercontent.com/7125952/137000589-ea01f39e-c5a7-4091-920e-9f46b128ff57.jpg)
4. Edition page: Should read "Devolver libro electrónico", but only reads "Devolver libro electrón".
 ![4_boton-devolver-libro-electronico-aparece-cortado_es](https://user-images.githubusercontent.com/7125952/137000693-91152266-657f-4308-b95f-a771666008bb.jpg)
5. Edition page: An example with two buttons in which the text is correctly displayed in one of them and in the other one it is cut off.
![5_boton-unirse-a-la-lista-de-espera](https://user-images.githubusercontent.com/7125952/137001063-147d684b-9c92-4e46-8ca6-0d5cad935e98.jpg)

### Steps to Reproduce
1. Go to pages on the site where the buttons appear in different lending situations (Not in library, Join waitlist, etc.).
2. Change the interface language from the bottom right menu and check the result in different languages.

* Actual: Button text is cut off
* Expected: Button text should appear in full.

### Details

- **Logged in (Y/N)?**  Y
- **Browser type/version?**  Firefox 93.0
- **Operating system?** Ubuntu 20.04.3 LTS
- **Environment (prod/dev/local)?** prod

**Comment by shaneriley** [comment]
Buttons have a default CSS property value to prevent text wrapping to multiple lines, which is causing this issue. It can be removed in favor of wrapping the text to multiple lines, but I'd like to get a core team member to make the final decision on this as it will undoubtedly lead to rows of buttons being varying heights.

Code in question: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/buttonCta.less#L22

**Comment by dcapillae** [comment]
Yes, I think we could use shorter strings. For example:

1. "No en la biblioteca" (Not in Library) could be "No en biblioteca".
2. "Devolver libro electrónico" (Return eBook) could be "Devolver libro". 
3. "Unirse a la lista de espera" (Join Waitlist) could be "Unirse a la lista".

(1) is OK, it means the same thing; (2) and (3) mean something similar, "Return Book" and "Join List". They are not exact translations but I think they would also work.

**Comment by dcapillae** [comment]
I have checked out [eBiblio](https://madrid.ebiblio.es/resources/5fcfb8b76af9f80289310deb), a book lending website that operates in Spain operated by public libraries. They use "Reservar" (Reserve) to mean "Join Waitlist". Sounds like a good solution, and a very short one!

![ebiblio-screenshot](https://user-images.githubusercontent.com/7125952/137815335-e3ca96ee-7248-40a9-bf52-a99a32d4db27.png)

**Comment by cdrini** [comment]
That seems good to me! What do you think @mekarpeles ?

Any chance "Reservar" could conflate with something else on OL?

**Comment by dcapillae** [comment]
If you give me the OK, in a next update of the site translations I could change the text of the buttons to reduce the length of the string.

**Comment by cdrini** [comment]
Ok! @mekarpeles and I chatted over it, and those seem good! To clarify:

1. "No en la biblioteca" (Not in Library) → "No en biblioteca".
2. "Devolver libro electrónico" (Return eBook) → "Devolver libro". 
3. "Unirse a la lista de espera" (Join Waitlist) → "Reservar".

**Comment by lephemere** [comment]
Same issue on the french part:

| EN | FR (current) | FR (proposed) |
|--|--|--|
| Not in Library | Pas dans la bibliothèque | Indisponible |
| Return eBook | Rendre le livre électronique | Rendre le livre |
| Join Waitlist | Rejoindre la liste d'attente | Réserver |
| Search Inside | Rechercher à l'intérieur | Recherche plein texte |

As I'm currently working on the french translation, I'll update it directly.
