### ISSUE TITLE
scripts/copydocs.py fails when the received content is too large

### ISSUE THREAD

**Issue by shaneriley** [internetarchive/openlibrary#5761]
When the copydocs script is used to copy a work that contains data that exceeds a character count of 4094, an error is thrown and the work is not copied.

### Steps to Reproduce

1. Run the copydocs script in your web container (`docker-compose run web bash`, `./scripts/copydocs.py`) using [this work](https://openlibrary.org/works/OL16060982W/Prentice_Hall_Literature_-_Timeless_Voices_Timeless_Themes_-_The_American_Experience)
2. The error indicating the request is too large will be thrown (5495 chars. Limit says it's 4094)

* Actual: work is copied to local database
* Expected: error thrown due to data size

### Details

- **Logged in (Y/N)?**  N/A
- **Browser type/version?** N/A 
- **Operating system?** N/A
- **Environment (prod/dev/local)?** dev

### Related files

https://github.com/internetarchive/openlibrary/blob/master/scripts/copydocs.py

**Comment by b2pacific** [comment]
@jimchamp can you assign this to me?

**Comment by jimchamp** [comment]
@b2pacific what is your plan for fixing this issue?  I suspect that we will have to make a configuration change (either nginx or gunicorn) to address this issue, but I may be wrong.

**Comment by jimchamp** [comment]
It's a gunicorn configuration.  @b2pacific, you can update our web GUNICORN_OPTS in `docker-compose.yml` to fix this, here: https://github.com/internetarchive/openlibrary/blob/c713c09e4e09f7521f8e7cd89678a5a2a4ad150c/docker-compose.yml#L8

Here is the setting to use: https://docs.gunicorn.org/en/stable/settings.html#limit-request-line

**Comment by b2pacific** [comment]
Yeah, it is because of gunicorn error :)
https://serverfault.com/questions/564464/nginx-request-line-too-large
