### ISSUE TITLE
"Browse" and "More" header bar items have a tiny font size on reading log stats pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5766]
"Browse" and "More" headers have a smaller font size on reading log stats pages than other pages.

### Evidence / Screenshot (if possible)
![Screenshot from 2021-10-18 18-56-29](https://user-images.githubusercontent.com/28732543/137817674-17d89de6-9f7c-4d98-b3bb-eeee476c5753.png)

### Steps to Reproduce

1. Go to a reading log stats page.
2. Observe the size of the header items.

* Actual: Header items have a small font size.
* Expected: Header items are the same size as other pages.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Sure!  Let me know if you have any questions, @b2pacific.

**Comment by b2pacific** [comment]
Hey @jimchamp I have fixed the issue and have created a PR. Do review it!
