### ISSUE TITLE
404 - Page Not Found /works/OL...W/daisy does not exist

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5768]
Links to Daisy from Work pages are broken.
### Relevant url?
1. Go to ...https://openlibrary.org/works/OL4648179W/Recursive_Methods_in_Economic_Dynamics/daisy

### Steps to Reproduce

1. Go to ...https://openlibrary.org/works/OL4648179W/Recursive_Methods_in_Economic_Dynamics/daisy
2. Do ...

* Actual: 404 - Page Not Found /works/OL4648179W/daisy does not exist
* Expected: Daisy information page i.e. https://openlibrary.org/works/OL4648179W/Recursive_Methods_in_Economic_Dynamics/daisy

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Did this work at some point in the past?  I would expect Daisy links to be edition-level.

All of the daisy links on the work page (https://openlibrary.org/works/OL4648179W/Recursive_Methods_in_Economic_Dynamics) link to the best-fit edition's daisy page (https://openlibrary.org/books/OL2058563M/-/daisy).  Were these links broken when this issue was opened?

**Comment by jimchamp** [comment]
I'm seeing that the daisy links found in search results lead to 404 pages.  Work page daisy links seem fine.

**Comment by jimchamp** [comment]
> I'm seeing that the daisy links found in search results lead to 404 pages.

URLs for Daisy links in search results always reference the work.  All `/work` Daisy links seem to be failing.

**Comment by mekarpeles** [comment]
@bfalling are Daisy files no longer available on Archive.org?

I can't find them within downloads or on the derive formats chart

I see daisy in some download options on the details page (https://archive.org/details/recursivemethods00stok) but this seems to be on the fly. And the on-the-fly mechanism seems to maybe not be working?
https://ia800906.us.archive.org/epub/index.php?id=recursivemethods00stok&dir=/13/items/recursivemethods00stok&doc=recursivemethods00stok&type=daisy

**Comment by mekarpeles** [comment]
Going to merge #6183 in tandem with this one.
