### ISSUE TITLE
Error when reverting merge

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5776]
In trying to revert a succession of bad author and work merges, I've enountered this which needs to be reverted to v.1 but throwns an error. https://openlibrary.org/works/OL36791W?v=1

Works by EL James is not a duplicate of The Three Musketeers by Dumas, so this must be reverted.

### Relevant url?
https://openlibrary.org/works/OL36791W?v=1

### Steps to Reproduce

1. Go to ...https://openlibrary.org/works/OL36791W?v=1
2. Do ...Try to revert

* Actual: `/openlibrary/openlibrary/templates/lists/widget.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'key' (falling back to default template)`
* Expected: The record should revert to previous state.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by cdrini** [comment]
Hmm, when I run the repro steps, I actually get a "Hmm..." error, which hides an "Unable to connect to infobase server". Can you confirm this is what you see, @seabelis ?

**Comment by seabelis** [comment]
The EL James/Dumas conflation has been resolved.
