### ISSUE TITLE
Inaccurate availability presented in search results

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5782]
From a patron:
There is a bug in the search results.

They don't show books that can be borrowed correctly.

Example.

Search for this "hugh cook warlords". 

You will get 4 results. But none are ebooks right? "Not In Library"

Open the top result. It's an ebook and you can borrow it.

### Relevant url?
https://openlibrary.org/search?q=hugh+cook+warlords&mode=everything

### Steps to Reproduce

1. Go to ...https://openlibrary.org/search?q=hugh+cook+warlords&mode=everything
2. Do ...click first result

* Actual: book available
* Expected: not available according to search results

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by cdrini** [comment]
This was a case of solr being outdated, like as the result of a `Bot` import. I force reindexed that results on that page and it became borrowable again. Closing this in favour of #5700 . Note this will also be fixed by the next full reindex #5502 .
