### ISSUE TITLE
Reversion: author searches with wildcards fail

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#5784]
Wildcard asterisk fails in author name search, but works in "All" search. This used to work. 
### Evidence / Screenshot (if possible)
![A097E003-93BE-454E-8696-6BD66A64068D](https://user-images.githubusercontent.com/11435431/138561672-765afb2c-3f70-4db6-840e-d4e6f4c97ffb.png)
![22BF5133-458D-463E-B26B-DB2B43E9519C](https://user-images.githubusercontent.com/11435431/138561674-16449abc-5473-4c9c-aed4-67c4ad4db603.png)

### Relevant url?

https://openlibrary.org/search?q=Jon+kabat*&mode=everything

### Steps to Reproduce

1. Go to search bar
2. Enter a partial name ending with *
3. Select "Author" as search type
4. Run query

* Actual: nothing found
* Expected: list of matching authors

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** Safari or Chrome
- **Operating system?** iPadOS
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Ahhh, I think this broke in this commit: 694355826d9528629aa29f9eb403abb952afc888 when I enabled `dismax` for queries ; should be an easy fix!
