### ISSUE TITLE
Problematic reading list on work page causes page to error

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#579]
`<type 'exceptions.AttributeError'> at /works/OL84924W`

### Relevant url?
https://openlibrary.org/works/OL84924W/Deep_Six?debug=true

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF69
- **Operating system?** Win10

### Stakeholders

**Comment by salman-bhai** [comment]
What is the problem regarding this Issue? If it is fixed can we close this Issue?

**Comment by salman-bhai** [comment]
I did click the link and I wasn't sure what to do post that. I did remove `debug=true` as well but I think maybe because I didn't login I couldn't find an error to it! Thank you for helping out with that!

**Comment by salman-bhai** [comment]
I think I do see the error now after logging in. Thanks again for your help.

**Comment by hornc** [comment]
Interesting, I looked at this issue, and as @salman-bhai implies, clicking on https://openlibrary.org/works/OL84924W/Deep_Six?debug=true without being logged in gives no error, but once logged in, there is an error.

```
<type 'exceptions.AttributeError'> at /works/OL84924W
items
Python	/opt/openlibrary/venv/local/lib/python2.7/site-packages/simplejson/encoder.py in iterencode, line 377
Web	GET https://openlibrary.org/works/OL84924W
```

**Comment by tfmorris** [comment]
Which makes sense since reading lists don't get shown to users who aren't logged in and, as I mentioned in April 2018, the problem is with JSON encoding the reading lists for the work.

```
{'active': True, 'owner': {'displayname': 'James F. Rosendahl', 'key': '/people/jimr01'}, 'cover_url': '//covers.openlibrary.org/b/id/3699606-S.jpg', 'name': 'Espionage', 'key': '/people/jimr01/lists/OL52320L'}, 
{'active': True, 'owner': {'displayname': 'Linda A. Rodriguez', 'key': '/people/lindaisling'}, 'cover_url': '//covers.openlibrary.org/b/id/7026016-S.jpg', 'name': 'My Action & Adventure Thrills', 'key': '/people/lindaisling/lists/OL56447L'}>, 
{'active': True, 'owner': {'displayname': 'Edward Ronald Greeley', 'key': '/people/rgreeley'}>, 'cover_url': '//covers.openlibrary.org/b/id/6903541-S.jpg', 'name': "Ron's Favourites- Already Read", 'key': '/people/rgreeley/lists/OL10009L'}, 
{'active': True, 'owner': {'displayname': 'Edward Ronald Greeley', 'key': '/people/rgreeley'}>, 'cover_url': '//covers.openlibrary.org/b/id/6903541-S.jpg', 'name': "Ron's Favourites- Already Read", 'key': '/people/rgreeley/lists/OL10009L'}, 
{'active': , 'owner': {'displayname': '', 'key': }>, 'cover_url': '/images/icons/avatar_book-sm.png', 'name': '', 'key': '/people/JPhippz/lists/OL60745L'}
```
Eyeballing the list of reading lists, one of the things that catches my eye is that the last item has no value for the key `active` (and is malformed in other ways). I bet that's enough of a clue for someone to fix it.

**Comment by guyjeangilles** [comment]
#333 , #640, and #2202 may be related as they involve url encoding, but aren't json related.

Assinging @cdrini per our slack conversation since he's talking the url encoding in #333

**Comment by lucasdondo** [comment]
I'm also having that issue in Linux and Android (Pretty much the same haha).
`/opt/openlibrary/deploys/openlibrary/933f53b/openlibrary/templates/books/check.html: error in processing template: AttributeError: 'author_key' (falling back to default template)`
It happens when trying to add a book

**Comment by tfmorris** [comment]
@lucasdondo That sounds like a different issue. If it's reproducible, please create a separate issue. If you just need help setting up a development environment, please ask for help on Slack.

Going back to the original issue, the last List on the list of Lists (https://openlibrary.org/people/JPhippz/lists/OL60745L) has been deleted, but there's still a partial dangling reference to it associated with the work. The Lists widget (openlibrary/templates/lists/widget.html) is choking attempting to render.

Actually, the underlying calls to get the lists seem to fail as well:
https://openlibrary.org/works/OL84924W/lists.json?debug=true
https://openlibrary.org/works/OL84924W/lists.yml?debug=true
both fail, but they work if you add `limit=4` to them, e.g.
https://openlibrary.org/works/OL84924W/lists.json?limit=4&debug=true

The last entry seems to be either null or malformed in a way that breaks both the JSON and YAML encoders.

There's a secondary issue that the same entry appears twice on the list, but I don't think that's what's causing the problem.

I suspect it's going to require direct manipulation of the database using SQL to fix the underlying corruption.

**Comment by mekarpeles** [comment]
Seems to be resolved.
https://openlibrary.org/works/OL84924W/Deep_Six
