### ISSUE TITLE
Wrong link for “Depósito Legal. Biblioteca Nacional de España” ID

### ISSUE THREAD

**Issue by miguelmaiquez** [internetarchive/openlibrary#5790]
The link generated for the "Depósito Legal. Biblioteca Nacional de España" ID doesn't work.

### Evidence / Screenshot
![ol nbe issue](https://user-images.githubusercontent.com/5161774/138714359-91897bd2-22da-4a6e-ba2a-976676e59fad.png)

### Steps to Reproduce

1. Edit » Do you know any identifiers for this edition?
2. Select Identifier » Depósito Legal. Biblioteca Nacional de España
3. Write ID. Example: B 28007-1973 (That would be the right way to write it, according to Search instructions » Legal deposit number, at Biblioteca Nacional de España: “Do not use punctuation marks between the province prefix and the corresponding number. E.g.: CA 482-2003”. But I also tried with and without hyphen, with and without periods, with and without spaces, all combinations, with the same result)

* Actual: No results when clicking the link:  "B28007-1973{CKEY}" found no matches in the library you searched.
* Expected: The right right permalink for a "B 28007-1973" search: http://catalogo.bne.es/uhtbin/cgisirsi/x/0/0/57/5/3?searchdata1=2139546{CKEY}&user_id=WEBSERVER

(You can also check the results when making an “all fields” search at http://catalogo.bne.es/uhtbin/webcat entering B 28007-1973)

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 93.0
- **Operating system?** Linux, Ubuntu 21-10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Either figure out how to redirect to the right url, or temporary remove the link (like we have other identifiers without a link now), showing just the identifier as a reference, so the users can do the search themselves at the Biblioteca Nacional de España Catalog.

**Comment by cdrini** [comment]
Removed the link :( If someone finds a way to get a proper link, let me know. I hunted around the site for a while and couldn't find anything.

**Comment by miguelmaiquez** [comment]
Hi, @cdrini  

I found out that Biblioteca Nacional de España (BNE) has a [new data catalog site](https://datos.bne.es/inicio.html) where is actually possible to direct the Depósito Legal (DL) link.

It works through the search option, by writing the DL just the way it is written on the info of the book (letter – space – number – dash - year)

In the following examples, please note that the only change in both of the url is the DL part, almost at the end.

**Example 1:**

DL: **B 11971-2015**

url for the link:

datos.bne.es/find/resultados/?advanced=1&resourceType=&language=&seltab=0&type=C1003&P3002%2CP3014%2CP3028=&orden3=&OP3003%2COP3006%2CP1011=&OP3008=&P3003=&cleanPublicationDatea=&cleanPublicationDateb=&P3006%2CcleanPublicationDate=&P3016%2CP3022=&P3041%2CP3009%2CP3013%2CP3039=**B 11971-2015**&P3001=&P3024=

Which renders like this:

https://datos.bne.es/find/resultados/?advanced=1&resourceType=&language=&seltab=0&type=C1003&P3002%2CP3014%2CP3028=&orden3=&OP3003%2COP3006%2CP1011=&OP3008=&P3003=&cleanPublicationDatea=&cleanPublicationDateb=&P3006%2CcleanPublicationDate=&P3016%2CP3022=&P3041%2CP3009%2CP3013%2CP3039=B%2011971-2015&P3001=&P3024=

**Example 2:**

DL: **B 28007-1973**

url:

datos.bne.es/find/resultados/?advanced=1&resourceType=&language=&seltab=0&type=C1003&P3002%2CP3014%2CP3028=&orden3=&OP3003%2COP3006%2CP1011=&OP3008=&P3003=&cleanPublicationDatea=&cleanPublicationDateb=&P3006%2CcleanPublicationDate=&P3016%2CP3022=&P3041%2CP3009%2CP3013%2CP3039=**B 28007-1973**&P3001=&P3024=

Which renders like this:

https://datos.bne.es/find/resultados/?advanced=1&resourceType=&language=&seltab=0&type=C1003&P3002%2CP3014%2CP3028=&orden3=&OP3003%2COP3006%2CP1011=&OP3008=&P3003=&cleanPublicationDatea=&cleanPublicationDateb=&P3006%2CcleanPublicationDate=&P3016%2CP3022=&P3041%2CP3009%2CP3013%2CP3039=B%2028007-1973&P3001=&P3024=

------------

Another option, also in that site, is the url ID of the edition, which leads directly to the book, instead of the search results:

https://datos.bne.es/edicion/a5722426.html

https://datos.bne.es/edicion/bimo0001584187.html

But that ID is not listed on the info of the book, so it would require for the user to copy it from the url, and that would have to be explained somehow in the Open Library ID dialog, which might be more complicated.
