### ISSUE TITLE
Decouple OpenLibrary from Civi CRM

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5801]
### Describe the problem that you'd like solved

Open Library should not be calling Civi directly.  The application team reports an unexpectedly high volume of traffic to Civi, which is likely due to recent changes to the "My Books" page.  Civi calls are used to find patron's sponsorships, of which a count is displayed in the sidebar.

### Proposal & Constraints

Either remove code related to the sponsorship program, or find another way to get the sponsorship data.

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
we can a query of this flavor
https://archive.org/search.php?query=donor%3A%22%40mekarpeles%22%20collection%3Aopenlibraryscanningteam
