### ISSUE TITLE
Japanese characters not displayed correctly

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5809]
While looking for books in japanese language, came accross some books with unicode characters not displayed correctly.

### Evidence / Screenshot (if possible)
![ol-issue-02](https://user-images.githubusercontent.com/73437497/139498752-201492b8-5f46-42b8-9e51-ee215325effd.jpg)

### Relevant url?
Works:
 - https://openlibrary.org/works/OL22249633W/12431_12383_12375_12399_12362_12363_12354_12373_12435_12364_12377_12365
 - https://openlibrary.org/works/OL22246581W/12402_12392_12388_12398_20154_29983_12289_22810_12367_12398_19990_30028

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: Title as unicode characters
* Expected: Title with japanese characters

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** Firefox 93.0
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
This is just bad data from BetterWorldBooks. Booksellers are notorious for crappy data. Amazon is much worse than library data. BetterWorldBooks is at least as bad as Amazon.

Many people have suggested that OpenLibrary stop importing bad data from booksellers, but it doesn't seem to make any impression on the decision makers.

**Comment by cdrini** [comment]
As far as I can tell, none of this is bad data ; the books look to be valid books, just in Japanese. It seems like perhaps the importer should be doing html entity -> unicode ?

**Comment by cdrini** [comment]
@lephemere I wrote a quick script to fix some of these , but it relies on having a search query with a high match. I fixed about ~40 (See https://openlibrary.org/people/drinibot ). Let me know if you can find a search query with more, and I'll run it against those!

**Comment by lephemere** [comment]
Nice.

For high match we should go for characters with the highest appearance frequency in Japanese:

| Char | HTML | Hits |
|---|---|---|
| の | \&#12398; | ~220 |
| た | \&#12383; | ~90 |

Source: [Chikamatsu, N., Yokoyama, S., Nozaki, H. et al. A Japanese logographic character frequency list for cognitive science research. Behavior Research Methods, Instruments, & Computers 32, 482–500 (2000).](https://link.springer.com/content/pdf/10.3758/BF03200819.pdf)

I've also checked the already updated works/editions. For [OL25601017W](https://openlibrary.org/works/OL25601017W), the title was ending with `&#3`, probably cutoff at import. I have already corrected the title with the missing characters. The rest looks fine.

**Comment by tfmorris** [comment]
The reason I claimed bad data is because on the BWB site itself, the title renders as all ?s.
https://www.betterworldbooks.com/product/detail/9781912704354

![Screen Shot 2021-11-29 at 6 25 25 PM](https://user-images.githubusercontent.com/82178/143958638-0a22473e-1dbf-4ce6-9666-ff9bf4271c12.png)

**Comment by cdrini** [comment]
@lephemere Ran it over your queries, and they were all fixed! Also I love the research-based approach on that 😊 

@tfmorris Ah, gotcha; I thought you meant they looked like notebooks or something.

**Comment by tfmorris** [comment]
So if all the existing ones were fixed and the importer now discards BWB data, can this be closed?

**Comment by hornc** [comment]
I think proper Unicode importing has been implemented since this report. Further instances of bad import data (if it's not being rejected already) can be raised separately.

**Comment by tfmorris** [comment]
@hornc Can you confirm that the example above (https://www.betterworldbooks.com/product/detail/9781912704354) will get filtered by the current BWB import quality screens?
