### ISSUE TITLE
copydocs.py script throws authentication error

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#581]
Running the copydocs scripts with `python copydocs.py /authors/OL33442A` yields an authentication error (below). This script was working in the not-too-distant past, so maybe related to #576 ? This could also be a far-reaching problem; if logging into the api with username/password is no longer functioning, it might be the case that anything using `api.py` won't work anymore.

The error observed:
```
Traceback (most recent call last):
  File "copydocs.py", line 247, in <module>
    main()
  File "copydocs.py", line 234, in main
    dest.login("admin", "admin123")
  File "/openlibrary/openlibrary/api.py", line 97, in login
    response = self._request('/account/login', method='POST', data=data, headers=headers)
  File "/openlibrary/openlibrary/api.py", line 55, in _request
    raise OLError(e)
openlibrary.api.OLError: Internal Server Error:
```
After which the HTML page for an "Internal Error" is outputted to the console.

**Comment by mekarpeles** [comment]
I added a fallback for OL infogami login -- want to see if it works now?

**Comment by mekarpeles** [comment]
#631

**Comment by hornc** [comment]
@mekarpeles @cdrini `copydocs.py` is now working for me (without having to modify any S3 config settings) as a result of #631 , closing
