### ISSUE TITLE
Release Public PWA/TWA

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5828]
The TWA on Google Play is ready to go into the next phase of release; anyone should be able to install it; not just the people we explicitly include.

https://docs.google.com/document/d/1grAAE5hUyoXe1AV6Bb3Xv4mn0L6SKewI8gBNaeUvFPE/edit

**Comment by mekarpeles** [comment]
for next 1:1!

**Comment by mekarpeles** [comment]
1. [ ] bubblewrap?
2. [ ] service worker.json on archive.org
3. [ ] setting pwa live on google

**Comment by mekarpeles** [comment]
@cdrini and I just cut an Open Testing release 

Folks from the community should be able to register + download/install using these links **after** google reviews + approves:

- Mobile: https://play.google.com/store/apps/details?id=org.openlibrary.testing.twa
- Web: https://play.google.com/apps/testing/org.openlibrary.testing.twa

For developers, just as a reminder, here is where we went to manage this flow:
https://play.google.com/console

@Yashs911 once this this is public for testing, would you be open to taking the lead to help us write a blog post to promote the amazing work you did w/ @cdrini? Thank you!

**Comment by Yashs911** [comment]
> @Yashs911 once this is public for testing, would you be open to taking the lead to help us write a blog post to promote the amazing work you did w/ @cdrini? Thank you!

@mekarpeles Yes, will start working on the initial draft.

**Comment by mekarpeles** [comment]
@Yashs911 @cdrini and I are happy to help! Your original doc is here with lots of great work which may be included in the blog:

https://docs.google.com/document/d/1FkxVPi7pVX5dFkgaENTFifZdsdq3JFDWhxPhPldIWAk/edit#heading=h.so0h9gcffmol
