### ISSUE TITLE
Blog post for TWA/PWA

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5829]
Work with @Yashs911 to create a blog post about his fellowship and the TWA!

**Comment by mekarpeles** [comment]
@Yashs911 do you mind if we assignee you to this one?

**Comment by Yashs911** [comment]
@mekarpeles Yes, you can add me as the assignee, I have already started with the blog will share with you on slack

**Comment by tuminzee** [comment]
Hi @Yashs911 I hope you are doing well.
How is the issue going? Do you need any help, or resources?

**Comment by Yashs911** [comment]
@tuminzee I am very well, thank you.
My mid-semester exams are going on. I will pick this up after 16th March

**Comment by tuminzee** [comment]
@Yashs911 thank you for the update; best of luck with the exams?
