### ISSUE TITLE
Get more detailed book page performance metrics

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5832]
We currently have perf metrics on grafana, but that only gives us average load times. We want to avoid implementing anything too intricate, and would rather use an off-the-shelf solution.

Possible options:

- Work with @mmcnl to hook up Open Library to IA's elastic cluster, which provides core web vital tracking amongst other things
- Add hooks for Sentry perf monitoring: https://docs.sentry.io/product/performance/
- Slightly different, snakevix: https://jiffyclub.github.io/snakeviz/ ; this let's us see the flame chart for a specific page load.

**Comment by jimchamp** [comment]
We would like to have better metrics for the following book page components:
- [ ] Vendor/affiliate bar
- [ ] Lists (carousel + dropdown) --- dropdown is being initialized multiple times (some details can be found [here])(https://github.com/internetarchive/openlibrary/pull/5264#issuecomment-855004899)
- [ ] Editions table
- [ ] Read status CTA button
- [ ] Fetching work from Infogami
- [ ] Community Reviews
- [ ] Recommendations carousel
- [ ] Page history

**Comment by cdrini** [comment]
Ideal world is have pages load <1s .

Anecdotally, we believe the big bottlenecks are:
- LoanStatus button takes 1-1.5s per page, uncached!
- Editions table seems like it has the most outsized impact for more popular / older books.

**Comment by cdrini** [comment]
Closing this now that we have downstream issues.
