### ISSUE TITLE
Autocompletion doesn't match partial strings

### ISSUE THREAD

**Issue by eloquence** [internetarchive/openlibrary#584]
The search endpoint appears to operate on stemmed keywords only, which is fine for keyword search but can yield very confusing results in autocompletion ("search as you type"). For example, I have a book next to me called "The Storytelling Animal". I have to type all the way up to "the storytelling anim" to get this result, saving two characters. In between, I get _zero_ results several times, even as I get closer to completing the title. This is because partial words like "storyt" don't produce matches.

See https://gist.github.com/eloquence/586dbbfc26fc4bc21c48867f125677fc for a detailed example.

Often users will adopt a "type a bit, wait what happens" approach when using autocomplete boxes. When this leads to zero results, it can be very frustrating and even appear broken. 

In my experience, usually these types of searches use a special autocomplete index. While there are important differences in how stopwords like "the" and stemming are handled and how relevancy is scored, it's rare to encounter an autocomplete box that doesn't match on partial strings. Compare the search above with similar searches in Google, Amazon, Goodreads, Wikipedia, Wikidata, etc.

If none exists, I suggest adding an experimental autocomplete index, and optimizing it until such a point that it can be made the default for autocomplete operations such as the title search on the openlibrary.org frontpage.

**Comment by eloquence** [comment]
Without a new index, it may still be possible to improve result quality. After a bit of trial and error, I found that submitting the search as set of "title:" searches joined with AND, with the last search transformed into a wildcard search, seems to produce consistently more relevant results. Quickly hacked together:

https://cdn.rawgit.com/eloquence/69ed78042b6feb250834810d54ff1d37/raw/f788506606eb94d687949a8715a1ff61ad2feb0b/olsearch.html

Code:
https://gist.github.com/eloquence/69ed78042b6feb250834810d54ff1d37

For example, typing "The Wealt" will give you "The Wealth of Nations", whereas the official search will return no results. Caveat: It seems to be fairly easy to get the search API to throw 500s, and this may throw 500s in cases where the old one wouldn't. This example includes a default delay of 300 milliseconds before queries are fired to avoid hitting the API too hard.

Of course, since this isn't a phrase search, it will match mid-title, which may be a bit confusing in some cases. However, it's not that unusual -- Goodreads, for example, does the same.

It still doesn't match in cases where I think an autocomplete search ideally should: "The Storytelling" doesn't match "The Storytelling Animal" in either the old search or this one. It's not quite clear to me why not since both "the" and "storytelling" are part of the title. However, at least this one completes from "The Storytelling An" onwards. 

I'd appreciate thoughts on whether this approach might be an improvement to the current autocomplete search already, at least for titles -- if so, it should be trivial to implement, possibly as an experimental feature at first.

**Comment by eloquence** [comment]
I've cleaned up this alternative implementation a bit (catching a few more cases that would cause 500s) and integrated it with lib.reviews. A blog post about that is [here](https://lib.reviews/team/developers/post/39e78424-bf57-404d-92ed-ff84e96d922e) and most of the relevant code is in the _requestHandler function [here](https://github.com/eloquence/lib.reviews/blob/master/frontend/adapters/openlibrary-autocomplete-adapter.js). Just respond to this thread if there's interest in porting this approach in some form to OL itself, and I'd be happy to take a crack at it. :)

**Comment by guyjeangilles** [comment]
@cdrini @tfmorris I don't think there is a autocomplete function in OL currently. I believe we wanted to implement something like [Freebase](https://developers.google.com/freebase/v1/search-widget).

@eloquence I believe the OL team has deprioritized search for the time being, but if you are willing develop a solution, are you willing to be assignee for this issue? if not @cdrini @tfmorris, are one of you willing to be assignee?

I've also added labels per the issue's context: let me know your thoughts.

**Comment by tfmorris** [comment]
First, congrats to @eloquence for figuring out how to hack the API in an undocumented way to get (kinda) what he wants, but clearly doubling the search load (ie two calls for every autocomplete) isn't sustainable for a production system.

Engineering autocomplete APIs is a well known science. We should just follow one of the existing patterns (and that my break this hacky homebrew solution).

**Comment by mekarpeles** [comment]
Current website has realtime autocomplete (which we may wish to tune). Thank you for this work + investigation!
