### ISSUE TITLE
Support sorting for list carousels

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5857]
Sorting [list carousels ](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/ListCarousel.html) is not currently possible. 

### Describe the problem that you'd like solved
Add support similar to what is possible with [query-based carousels.](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/QueryCarousel.html). Sorting by editions, scans is highest priority (personally).

### Stakeholders

@mekarpeles

**Comment by cdrini** [comment]
@Sabreen-Parveen Would you be able to take a look at this one? I believe all we need to do is forward a `sort` parameter between two templates, or something along those lines :)

**Comment by cdrini** [comment]
Hi @dennxa !

Yep! So this is the template for the lists carousel:

https://github.com/internetarchive/openlibrary/blob/02881e405be7ffcd67cbd2a0a0865ba0dd4f8ef4/openlibrary/macros/ListCarousel.html#L1-L11

At the bottom, you can see it calls the `QueryCarousel`. `QueryCarousel` supports the `sort` parameter, so you will just need to add a new sort parameter to `ListCarousel`, and forward it along to `QueryCarousel` :+1:
