### ISSUE TITLE
Carousel search query pulling incorrect data.

### ISSUE THREAD

**Issue by tmanarl** [internetarchive/openlibrary#5862]
I'm building collection carousels using search queries.  I have one carousel that is pulling in two different subject tags.  
`QueryCarousel('subject:"collectionID:DS9#"', search=False, has_fulltext_only=False, sort='old', title="Numbered novels (1993–2000)", limit=150) `is also pulling in works with subject tag `collectionID:DS9nov`. 

### Evidence / Screenshot (if possible)
[Screenshot](https://drive.google.com/file/d/1aoIGeI6N4HzQHuRADN3uTW_ZzXtBkOfP/view?usp=sharing)

### Relevant url?
[Star Trek Collection](https://openlibrary.org/collections/star-trek#ds9)

### Steps to Reproduce

1. Go to [Star Trek Collection](https://openlibrary.org/collections/star-trek#ds9)
2. Notice that all the works in "Episode Novelization" carousel also appear in the "Numbered Novels" carousel for the Deep Space Nine section only.
3. Also observe that the same code behaves correctly for the other uses of "Numbered Novels" in the collection.

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

### Stakeholders

@tmanarl

**Comment by jimchamp** [comment]
As I mentioned in Slack, I highly recommend avoiding the use of special characters in subject names.  In this particular case, I've found that `9#` is being treated like a wildcard in this query, and all books with a subject starting with `collectionID:DS` are being returned.  This only seems to happen when a digit proceeds the `#` character; queries for `'subject:"collectionID:ST#"'` return subjects that are exact matches and nothing more.
