### ISSUE TITLE
The export list option does not include the works, only the editions

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#5868]
The export list option doesn't work when the list include works only. If the list include works and editions, it exports editions only. If the list only includes works, it does not export anything.

### Evidence
This [list](https://openlibrary.org/people/dcapillae/lists/OL202672L) includes works only.  Try to export it in any format. The results are null.

### Steps to Reproduce
1. Go to any list containing only works (OL...W) or works and editions (OL...W and OL...M)
2. Try to export the list and check the results: if the list contains only works (OL...W), it exports nothing; if it contains works and editions, it exports the editions (OL...M), but does not include the works (OL...W). 

* Actual: It is not possible to export lists that include works in a satisfactory way. The results are partial (only editions) or null.
* Expected: When exporting a list in any format (json, html, or bib), the results should include all seeds, including both works (OL...W) and editions (OL...M).

### Details

- **Logged in (Y/N)?** Y 
- **Browser type/version?** Mozilla Firefox  94.0
- **Operating system?** Ubuntu 20.04.3 LTS
- **Environment (prod/dev/local)?** prod

**Comment by Al-0** [comment]
Hi, I will take a shot at solving this!

**Comment by dcapillae** [comment]
Related to this issue, maybe it could also consider solving the export of lists that include authors. Open library offers the possibility to add authors to lists, but the export option does not work correctly with this type of items. ([example](https://openlibrary.org/people/dcapillae/lists/OL202608L): this list only includes authors, but the export options offer a strange mix of results.)
