### ISSUE TITLE
Error when adding book: `/openlibrary/openlibrary/templates/books/check.html: error in processing template: AttributeError: ‘author_key’ (falling back to default template)`

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5879]
Getting an error when adding this book:

Title: Beyond Habitat
Author: Moshe Safdie
ISBN: 9780262368049

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/921217/141889214-26d0bbf5-3eef-4356-b0ea-d038ce1982a7.png)

![image](https://user-images.githubusercontent.com/921217/141889236-04c1d650-1467-4bb6-a840-7c6033edbacb.png)

Debug error page (download and rename to .html to see page):
[error.txt](https://github.com/internetarchive/openlibrary/files/7543090/error.txt)

### Relevant url?

https://openlibrary.org/books/add

### Steps to Reproduce

1. Go to https://openlibrary.org/books/add
2. Try adding this book

* Actual: Error
* Expected: Success

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by cclauss** [comment]
With https://openlibrary.org/books/add?debug=true the output will be something like:
![Screenshot 2021-11-16 at 10 12 52](https://user-images.githubusercontent.com/3709715/141957277-e633a1eb-bee4-4870-82d0-7a35d7dffbd9.png)

**Comment by mekarpeles** [comment]
I feel like this should be a P2, though I notice @cdrini has made it a P1 so I'm assuming we're hitting this often and there may be a few different examples we can use to reproduce + identify the root cause? @jimchamp to take lead for now.

**Comment by jimchamp** [comment]
@RayBB I've deployed a solution to our testing environment.  You should be able to add this book there.
