### ISSUE TITLE
Make reindex-solr not working

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5888]
reindex-solr is failing which causes no books to show up in search for local dev

### Evidence / Screenshot (if possible)
```
home_1          | db:5432 - accepting connections
home_1          | psql --host db openlibrary -t -c 'select key from thing' | sed 's/ *//' | grep '^/books/' | PYTHONPATH=/openlibrary xargs python openlibrary/solr/update_work.py --ol-url http://web:8080/ --ol-config conf/openlibrary.yml --data-provider=legacy
home_1          | Traceback (most recent call last):
home_1          |   File "/openlibrary/openlibrary/solr/update_work.py", line 1744, in <module>
home_1          |     FnToCLI(main).run()
home_1          |   File "/openlibrary/scripts/solr_builder/solr_builder/fn_to_cli.py", line 52, in __init__
home_1          |     arg_opts = self.type_to_argparse(annotations[arg])
home_1          |   File "/openlibrary/scripts/solr_builder/solr_builder/fn_to_cli.py", line 102, in type_to_argparse
home_1          |     raise ValueError(f'Cannot determine type of {typ}')
home_1          | ValueError: Cannot determine type of list[str]
home_1          | Makefile:62: recipe for target 'reindex-solr' failed
home_1          | make: *** [reindex-solr] Error 123
```

### Steps to Reproduce

1. Go to https://gitpod.io/#https://github.com/internetarchive/openlibrary/
2. See the reindex-solr step fail

* Actual: Failed
* Expected: Success

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Related files

Related to #5852

**Comment by cdrini** [comment]
This will break solr-updater if it goes into production ; taking a look

**Comment by jimchamp** [comment]
Some notes about this:
When `annotations` contains a list of strings, `self.type_to_argparse(annotations[arg])` is called with `'list[str]'` as the argument (note that this is a string, not a type).  This is causing type_to_argparse incorrectly evaluate the types of lists.
