### ISSUE TITLE
Solr enhancements

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#59]
Edward, can you please add the following fields to solr? Most of these we've discussed over skype.
- original_language
- cover_id
- publisher_key (like subject_key, required for publisher pages)
- a new field to store multiple lending editions (required to show the first available book to borrow)

Also, it will be handy to store the edition info as JSON. There is no need to index this field.

```
"editions": [{
        "key": "/books/OL1M", 
        "title": "Foo",
        "publisher": "Foo",
        "publish_date": "...",
        "ia": "foo00bar", 
        "isbn": [..], 
        "cover_id": 1234, 
        "overdrive": "..", 
        "inlibrary": True, 
        "lendinglibrary": False
    },
    ...
]
```

**Comment by mekarpeles** [comment]
Of the keys above, I think `inlibrary` is the big one which is missing... We're currently handling this via subject tags (which we're trying to deprecate because anyone can easily edit these fields through the UI)

Closing and opening a new issue re: `inlibrary`
