### ISSUE TITLE
First card in the list of publications is shorter than the rest

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#5903]
### Evidence / Screenshot (if possible)
<img width="1438" alt="Screenshot 2021-11-23 at 8 28 54 PM" src="https://user-images.githubusercontent.com/73935799/143048195-4b993ab3-9fdf-4d67-b146-cdc6a4c58bc9.png">

### Relevant url?

https://openlibrary.org/people/dcapillae/lists/OL202672L/Origami_Collection

### Steps to Reproduce

1. Go to the above URL
2. If you are using chrome open the dev tools and select the following resolution `1440x900`
3. The first card will come out to be shorter than the rest

* Actual:
* 
* Expected:

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** 95.0.4638.69  Google Chrome
- **Operating system?**MacOS X Monterery
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

This can be fixed very easily in the chrome dev tools only by adding the following CSS
`width: 100%` this way the full width of the parent div will be occupied by the card.

**Comment by homewardgamer** [comment]
I would like to work on this Issue.

**Comment by jimchamp** [comment]
@homewardgamer you can work on this.  I'm not sure what element's width you are intending to modify, but I would advise against it. Many components on this page are used in different views, and changing the width may adversely affect those views.

The main issue for this particular list page is the image's `align` attribute, which has been set to `align="right"`.  This is effectively the same as `float: right`.  The image's height overlaps the first card in the list, interrupting the flow of the card.  A simple fix for this would be to add the `clearfix` class to list element, here: https://github.com/internetarchive/openlibrary/blob/1ac15a484695469791de546773021e7c7400c6a6/openlibrary/templates/type/list/view_body.html#L193

**Comment by homewardgamer** [comment]
Thanks for the insights! @jimchamp, I will surely modify the files and do the changes needed.
