### ISSUE TITLE
Improve rendering time of editions table for big works

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5918]
Works with many editions can take north of ~5s to load and render, because of the hundreds of editions they have to process.

## Proposal
- Maybe toss it in an iframe? That'll reduce browser rendering time, but a good chunk of time is also spent server-side on this. More analysis needed.
- Use datatables pagination options ; they support some sort of async fetching of pages of data.

**Comment by mekarpeles** [comment]
Closing for now, eventually we'll switch to solr editions, we already have limit to ebooks
