### ISSUE TITLE
Prevent ListWidget from triple-firing 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5919]
See #5832

1. [ ] investigate whether this is a performance issue when cached
2. [ ] if it is, propose solution

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Closing this, as I realized today that this is not an issue.  There are actually 3 ListWidgets on book pages: One beneath the CTA button in the sidebar, and two at the bottom of the page.

Instead of a single widget triple-firing, all three widgets are firing once.
