### ISSUE TITLE
Create Roadmap for 2022

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5920]

**Comment by BrittanyBunk** [comment]
is there a location for all these to access - from the past to present? It's just a little difficult trying to figure all this out.

**Comment by mekarpeles** [comment]
@BrittanyBunk yes there is:
https://docs.google.com/document/d/1KJr3A81Gew7nfuyo9PnCLCjNBDs5c7iR4loOGm1Pafs/edit#

**Comment by mekarpeles** [comment]
[2022 Community Roadmap Plan](https://docs.google.com/document/d/1szK5X2RPJl1hZ2cYiv9zw7QOn1I_QSJkCHckHi6Ue2c/edit#heading=h.pp7afpf26wws)
