### ISSUE TITLE
Transfer monthly dumps using IA client

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#5930]
I am always frustrated when ol-dumps succeed but the transfer to https://archive.org/details/ol_exports?sort=-publicdate fails.

### TODO: Switch to ia client tool. This will only work in production 'til then
From `scripts/oldump.sh` in #5909
```bash
function archive_dumps() {
    # Copy data dumps to https://archive.org/details/ol_exports?sort=-publicdate
    # For progress on transfers, see:
    # https://catalogd.archive.org/catalog.php?checked=1&all=1&banner=rsync%20timeout
    # TODO: Switch to ia client tool. This will only work in production 'til then
    python /olsystem/bin/uploaditem.py $dump --nowait --uploader=openlibrary@archive.org
    python /olsystem/bin/uploaditem.py $cdump --nowait --uploader=openlibrary@archive.org
}

# Only archive if that caller has requested it and we are not testing.
if [ "$archive" == "--archive" ]; then
    if [[ -z $OLDUMP_TESTING ]]; then
        archive_dumps
    fi
fi
```

### Describe the problem that you'd like solved

Replace the calls to [`/olsystem/bin/uploaditem.py`](https://github.com/internetarchive/olsystem/blob/master/bin/uploaditem.py) above with https://github.com/jjjake/internetarchive

### Additional context

Need to generate `_file.xml` and `_meta.xml` as in:
* https://archive.org/download/ol_cdump_2021-10-13
* https://archive.org/download/ol_dump_2021-10-13

**Comment by jimman2003** [comment]
working on this ... pr incoming
