### ISSUE TITLE
Homepage books carousel shows english text after loading

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#5932]
When not on the English version of the homepage, when displaying the next books via the right arrow on a carousel, the text switch back to English at some point.

### Evidence / Screenshot (if possible)
First three book set looks fine:

![image](https://user-images.githubusercontent.com/73437497/144721765-a0954a9b-a5ed-4955-9b0e-5f8103f97959.png)

On the fourth however:

![image](https://user-images.githubusercontent.com/73437497/144721850-0c46ec6a-a117-46a3-8abb-cdce3e8d1bea.png)

Same till the ends.

A `Loading...` message (not translated) appears shortly between the third and the fourth book set in the carousel.

![image](https://user-images.githubusercontent.com/73437497/144722006-9a7de613-22bc-4a66-972a-6da5eac7c101.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF94
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Data point: By default, we load 18 books when carousel is created.  In the above example, it seems like the first eighteen books' buttons have the correct text, but newly loaded books default to English.  This may be worth looking into.

The English "Loading..." text is generated in Javascript ([here](https://github.com/internetarchive/openlibrary/blob/4ba715b31eedc12444757f245c922a380f2c3159/openlibrary/plugins/openlibrary/js/carousel/Carousel.js#L152)).  We don't yet have a good way of localizing strings in our JS files, so it may be best to consider other solutions for this (maybe a graphical loading indicator?).

**Comment by benbdeitch** [comment]
Hello! I'd be delighted to work on this issue.  I don't have much experience with handling localization issues, but it feels like it'll be an interesting task to approach.
