### ISSUE TITLE
Add a suggestion box to collections

### ISSUE THREAD

**Issue by tmanarl** [internetarchive/openlibrary#5937]
I would like a suggestion box added to each collection page that would allow patrons to submit potential books to add to said collection.

### Describe the problem that you'd like solved
Currently there is no easy way for an Open Library patron to communicate with curators.  I am proposing a simple suggestion box feature that would allow users to submit a works ID of a book they think should be added to a collection.  This would be especially useful on large collections and ones that still have books being currently published.  This way users would be able to assist in keeping the contents of collections current.

### Proposal & Constraints
A suggestion box feature could be added to each collection.  This could be added as a curator's note at the end of the introduction that alerts users of it's functionality, or it could automatically be created at the bottom.  A user would be able to post a works/edition ID to the box and submit it.  This would then alert the curator of the collection and/or the collections lead of the suggestion.  The curator could then decide whether or not to act on the suggestion.

A few things to consider with this suggestion:
- The suggestion box feature could either be automatically added with new collections or it could be a feature (like a widget) that is added by the curator if desired.  Perhaps a markdown shortcut could be created to make adding it simple for the curator.
- Lead curators would need to be established for each collection as to who would be responsible for receiving suggestions.  This would not be as simple as who creates the page as sometimes collections are created by librarians for other curators to utilize.
- Notifications would need to be created for each suggestion.  This could be set up as an email notification, or somehow a notification system could be established within the OL website.
- The notification would be sent to the lead curator and would include the collection, the book suggested and the user submitting.  

### Additional context
Here's a potential visualization:
[<img src="https://docs.google.com/drawings/d/e/2PACX-1vToq4AYCpb1CMgPztKwFIUoWaCvyairUzYPPgQG0XP6rx1TPKCb1Nt3G39Ilsa6Zt0prrCzllYdUirA/pub?w=928&amp;h=556">](url)

### Stakeholders
@tmanarl @libjenner

**Comment by mekarpeles** [comment]
@jimchamp +1's this idea. This could allow us to do something like community lists.

sql table
`suggestions`
`key` (which could be a list page), `edition`, `note/reason`, `submitter`, `date`, `moderator`

could be a good table for this, and then on a certain page (i.e. `key`) one can see the suggested book additions

**Comment by BrittanyBunk** [comment]
I was going to suggest that people can suggest lists.

This idea made me think of something else:
- what if people can make suggestions to lists - like if someone created a list and someone else thought of something that could be added to it, then they can make suggestions that the public could see. It could help those who made the list find books they didn't think about, but might've been looking for.

**Comment by BrittanyBunk** [comment]
I actually think a better solution is going to go the series pages route. Then, people can just write in the series that a book is in, which'll lead to the formation of collections. Anyone who thinks that a book goes there will add the series name and it'll automatically show up in the collection. That way, no one has to wait on suggestions for it to go through collections - it's automatically there. I'll try to attend the next community meeting to help out with this.

**Comment by Hitansh-Shah** [comment]
@jimchamp I would like to work on this feature. This feature has quite a few subtasks so it will be a good mini project for getting familiar with both backend and frontend along with their connection. I may get stuck in some areas of backend or even frontend but I'll ask the doubts for the same. I think I will be able to finish this in a couple of weeks. Can you assign it to me please?

**Comment by tmanarl** [comment]
> I actually think a better solution is going to go the series pages route. Then, people can just write in the series that a book is in, which'll lead to the formation of collections. Anyone who thinks that a book goes there will add the series name and it'll automatically show up in the collection. That way, no one has to wait on suggestions for it to go through collections - it's automatically there. I'll try to attend the next community meeting to help out with this.

I do think it is still important for the collection curator to play a role in accepting/denying suggestions and then placing said suggestion in the appropriate carousel.  The Star Trek collection for example has 72 separate carousels, and a suggestion added automatically is unlikely to populate in the correct place.

**Comment by mekarpeles** [comment]
What if instead of a suggestions box, we asked the question but then linked to https://openlibrary.org/contact?path=/help and added a Topic for "Suggestion" :)

**Comment by BrittanyBunk** [comment]
@mekarpeles I think we're thinking up ideas and getting somewhere - I like this brainstorming!

I personally think that's overly complicating the matter and putting way too much work on admins. If @seabelis did 10,000 merges - adding suggestions on top sounds overwhelming - even for me. I can't even think about this anymore without inducing anxiety - I'm stopping now lol.

Also, a suggestion box will exist either way - it'll just be located in a different place is all.

However, don't let me stop you from living your dream if that's what you want to pursue! If you do it that way, here's what you'll need:
1) the 'suggestion' topic is automatically selected.
2) provide instructions for people as to how exactly to write it in properly - what details they need - like the work ID and collection it'll be added to.
3) have a link there.

**Comment by tmanarl** [comment]
If it links to that page and a patron submits a suggestion to add to a collection, how would the curator receive said suggestion?

**Comment by tuminzee** [comment]
Hello @Hitansh-Shah this issue does not have `label:"Needs: Help"` that is why you cannot be directly assigned to this issue.
Still I will ask @mekarpeles and @jimchamp for details for this issue. 

If you are looking for some good issues you can find it [here](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs%3A+Help%22) 

I would also recommend discussing the specificity of this issue with the lead (@mekarpeles)
Thank you for your interest and responses. Happy Contributing! 🕺🏼

**Comment by BrittanyBunk** [comment]
@tmanarl you bring up a really great point - if admin have difficulties being overloaded with notifications to where they stop looking at them, how will they receive any notifications if this gets overwhelming too?

**Comment by mekarpeles** [comment]
I agree with @BrittanyBunk that for v1, collection maintainers could be allowed to change the permission of their collection to be public. Any time a community member makes a change, our wiki already has version control which shows the specific changes and lets the admin roll the changes back. If anyone wants their collection to be editable, I can help.

This avoids having to build a notification system which is quite complicated:
* How do we know when a change/suggestion has been made -- looking at all recent changes to the page?
* Do we only show a notification for the maintainer when on that page? e.g. "5 suggestions pending"
* etc

For now, I think @BrittanyBunk's is a valuable interpretation which allows the problem to be solved and doesn't require creating anything new. Closing this issue for now though keeping around the thread and context so we can revisit and continue discussing at any time.

**Comment by mekarpeles** [comment]
@tmanarl + @BrittanyBunk + @Hitansh-Shah please see #6111 regarding why this issue may be harder than it seems & why we're uncertain about whether it should be worked on.

**Comment by tmanarl** [comment]
Really and truly, this blew up way more than I was expecting and turned into something I DO NOT want to happen.  I do not want collections to be publicly editable; that was not my intention when I proposed this suggestion, nor would I want to see it implemented.  Please do not consider that as a possibility.
