### ISSUE TITLE
Books that are  `Not in library` have bigger height than the rest of the books card.

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#5942]
### Evidence / Screenshot (if possible)

<img width="1438" alt="Screenshot 2021-12-07 at 7 59 30 AM" src="https://user-images.githubusercontent.com/73935799/144955174-fdc1455e-266b-4676-b023-9804086bb1dc.png">
### Steps to Reproduce
Open https://openlibrary.org/ and check for books that are `Not in the library`.You will find that they have a bigger height in terms of card size than the rest of the books.

1. Go to ...
2. Do ...

* Actual: `Not in library` book cards being longer than others
* Expected:All book card having the same height irrespective of their library status

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?**Chrome  96.0.4664.55
- **Operating system?** MacOSX
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by jimchamp** [comment]
I've noticed that "Not in Library" buttons are direct children of `div`s with class `book-cta`, while other buttons are nested within a `div` with class `cta-button-group`.  Nesting "Not in Library" books within a `cta-button-group` `div` solves the layout issue.

**Comment by homewardgamer** [comment]
Could you also mention the concerned files that have to be changed? @jimchamp

**Comment by homewardgamer** [comment]
I have made the PR kindly review it @jimchamp
