### ISSUE TITLE
Editing pages on Open Library w/o Javascript

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#595]
John Gilmore mentioned that Open Library edits fail when javascript is disabled. This doesn't seem like an action which needs to require javascript.

Will update this thread if we get more info about browser, a traceback, etc.

**Comment by mekarpeles** [comment]
I think we determined the issue here is that recaptcha is required for many edit use cases (which uses google APIs)

**Comment by tfmorris** [comment]
Anything that uses autocomplete (e.g. picking author's names) is going to fail if Javascript is not enabled.

**Comment by salman-bhai** [comment]
@mekarpeles should we close this Issue. Because in the new reCAPTCHAv2 we do need JS to render the reCAPTCHA images from Google!

**Comment by mekarpeles** [comment]
I think this should be fine to close in either case -- folks whose accounts are > 2yr old shouldn't see captcha anyway
