### ISSUE TITLE
List delete icon disappears on hover

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5959]
While hovering over the delete icon for lists, the icon disappears.  This icon is present in list items on the following views:
1. Individual lists --- used to delete books from a list.
2. List of all lists --- used to delete a list.

### Evidence / Screenshot (if possible)
![vanishing_bin](https://user-images.githubusercontent.com/28732543/145447964-14ff1cb6-74eb-4176-b509-67be71bf2666.gif)

### Relevant url?

All lists: `/account/lists`
List pages: `/people/{username}/lists/{list_olid}`

### Steps to Reproduce

1. Go to either of the above listed pages.
2. Locate a green trash bin icon and hover over it.

* Actual: The green trash bin icon disappears.
* Expected: The red open trash bin icon is displayed.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The image file used for the green trash bin contains two icons, the second one being a red bin with an open lid. A CSS rule can be added to display the red bin on hover.

### Related files

Image: https://github.com/internetarchive/openlibrary/blob/master/static/images/back_list-trash.png
CSS: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/search-result-item.less

**Comment by sulogna2001** [comment]
can i work on this issue?

**Comment by tuminzee** [comment]
Hello @jimchamp sorry I did see that the issue was already assigned.
I made a PR which resolves this issue.
my sincere apologies @sulogna2001
