### ISSUE TITLE
Some ISBN searches error

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#5963]
### Evidence / Screenshot (if possible)

Example:
**Errors:**
https://openlibrary.org/search?debug=true&isbn=1234567890

```
<class 'TypeError'> at /search
'NoneType' object is not iterable
```

**Expected example, gives no results:**
https://openlibrary.org/search?debug=true&isbn=12345

Looks like if an ISBN is sufficiently "ISBN like" (10 or 13 digits), but isn't a real ISBN, there is the possibility of an unhandled exceptions.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by agmckee** [comment]
The error is actually being raised by the dependency, [isbnlib](https://github.com/xlcnd/isbnlib). Looks like updating openlibrary/core/models.py to validate the ISBN, using e.g. isbnlib is_isbn10 before calling to_isbn_13 would pick up the issue with the invalid ISBN and prevent this.
