### ISSUE TITLE
Load Open Syllabus Project (OSP) IDs & curriculum counts into Open Library Solr

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5969]
This would allow us to:

1. showcase Open Syllabus Carousels
2. boost ranks for books
3. Give OSP an API to query/resolve against
4. Include links back to OSP
5. Show curriculum data (courtesy of OSP) on TBBO (thebestbookon.com)

### Describe the problem that you'd like solved

At minimum, a new field in solr called `osp_assignments` with the total number of times (int) a work has been cited in managed-schema.xml

There are 1,369,891 OL works with 1+ citation in this dataset:
Data looks like: https://gist.github.com/davidmcclure/1f3f701e48c1a8f9018d2bf85878e094
https://drive.google.com/drive/folders/1F-BZkHfbyYtHqb64SB1bz-AWhiESYTyoXXX

### Proposal & Constraints

Curriculum counts & IDs added to solr for OL works 

### Stakeholders

@cdrini @jimchamp

**Comment by BrittanyBunk** [comment]
This sounds cool. I have many syllabi on my computer from numerous courses and know where these syllabi are located on the internet:
- university pages
- There's also OCW (open courseware) and MOOCs (massively open online courses) where showing the syllabi and where people can get course content for free would help them find the textbook they need too when the course comes around.

I really know nothing about this project outside of this post, so I'll look forward to learning more to see what I can do - if there's anything I need to do.

**Comment by mekarpeles** [comment]
Here's the roadmap entry for OSP
https://docs.google.com/document/d/1zqrrmOd3_gagMZu-rDzQPWl0WeDln-ieaIlx3QHyRkw/edit#heading=h.clalixeo5bac

**Comment by mekarpeles** [comment]
This PR is similar to this draft PR:

https://github.com/internetarchive/openlibrary/pull/6191/files

Here is the solr schema which will need to be updated:
https://github.com/internetarchive/openlibrary/blob/master/conf/solr/conf/managed-schema

For a specific openlibrary_work, we'll want (at minimum) a count of the number of times the work has been assigned on a syllabi. Maybe we also want to include a `ranks` field which e.g. contains a list of (subject, rank) tuples?
