### ISSUE TITLE
Book cover title out of bounds

### ISSUE THREAD

**Issue by tuminzee** [internetarchive/openlibrary#5976]
Book cover title is too big, that it goes out of its boundary. 

### Evidence / Screenshot (if possible)

![06](https://user-images.githubusercontent.com/58180803/145956423-43f2ccb4-5fa2-48b9-84eb-fdce29b8d254.png)

### Relevant url?

https://openlibrary.org/books/OL34650330M/%C2%98Die%C2%9C_Hauptaufgaben_des_Volkswirtschaftsplanes_%C2%981974_%C2%9C_neunzehnhundertvierundsiebzig_und_der_Weg_zu_

### Steps to Reproduce

1. Go to [this book](https://openlibrary.org/books/OL34650330M/%C2%98Die%C2%9C_Hauptaufgaben_des_Volkswirtschaftsplanes_%C2%981974_%C2%9C_neunzehnhundertvierundsiebzig_und_der_Weg_zu_)
2. Observe the book cover title on the left

* Actual: Book cover title goes out of the boundary
* Expected: Book cover title should be justified and in-bounds.

### Details

- **Logged in (Y/N)?** Both
- **Browser type/version?** Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)
- **Operating system?** Ubuntu 20.04 LTS
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by Hitansh-Shah** [comment]
@tuminzee thanks for mentioning this issue. I will give this issue a go.

**Comment by Hitansh-Shah** [comment]
@tuminzee In the development version when I am searching for this book (`Die Hauptaufgaben des Volkswirtschaftsplanes 1974 [neunzehnhundertvierundsiebzig] und der Weg zu seiner Verwirklichung (1974)`
), I am not able find any results. However in the production version the book shows up.

**Comment by tuminzee** [comment]
You'll have to import test data locally.

Here's some info about copydocs this will help:  https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

**Comment by Hitansh-Shah** [comment]
> You'll have to import test data locally.
> 
> Here's some info about copydocs this will help: https://github.com/internetarchive/openlibrary/wiki/Getting-Started#importing-test-data

Got it👍️. Thanks a lot

**Comment by Hitansh-Shah** [comment]
I went through the codebase and managed to find the html template and css file involved in the issue. I added a property in css file and I got the following results. Please check the result and let me know if I should open a PR. Thanks
![image](https://user-images.githubusercontent.com/76250591/146921342-77541ae6-973d-4bd3-b0d8-4beff68b8fbd.png)

**Comment by tuminzee** [comment]
If you are happy with it. Go for it.
I'll tag @jimchamp here. He is the lead, he will review the PR.
If you need my help with anything. I will be here.
Have a good day!

**Comment by Hitansh-Shah** [comment]
@tuminzee Thanks for guiding throughout this issue. I will open a PR.

**Comment by tuminzee** [comment]
I am learning myself. I'm happy that it helped ☺️
