### ISSUE TITLE
My Loans Page: Show useful content if no loans

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5979]
### Describe the problem that you'd like solved

When a patron has no loans and visits their `/account/loans` page, they are presented with a mostly blank page:

![Screenshot from 2021-12-15 16-44-40](https://user-images.githubusercontent.com/28732543/146270215-94f38c4f-a7fd-4fe4-9c3a-da80587fa3ba.png)

This blank page is an opportunity to help patrons find their next book to borrow.

### Proposal & Constraints

If a patron has currently has no loans, let's display the following on the loans page:
- [ ] A "Books We Love" carousel
- [ ] A "Browse by Subject" carousel
- [ ] A link to our collections page (https://openlibrary.org/collections)

There may be some issues with the carousels overflowing on the loans page.  The carousels can be configured to display a smaller number of cards, which may prevent the carousels from overflowing.

The collections page link should have a nice call to action, something like "Check out these special collections".

### Additional context

Loans page template: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/loans.html

Example "Books We Love" carousel call: https://github.com/internetarchive/openlibrary/blob/9dbb9c13cda88c0c79b2fab0f47b64f72d75f681/openlibrary/templates/home/index.html#L27
Example "Browse by Subject" carousel call: https://github.com/internetarchive/openlibrary/blob/9dbb9c13cda88c0c79b2fab0f47b64f72d75f681/openlibrary/templates/home/index.html#L41

**Comment by jimchamp** [comment]
@tuminzee I'm going to assign this to you.  Feel free to unassign yourself if this is something that you're not interested in.

**Comment by homewardgamer** [comment]
If the Issue is open for assigning then I can work on this issue. @jimchamp

**Comment by tuminzee** [comment]
> @tuminzee I'm going to assign this to you.  Feel free to unassign yourself if this is something that you're not interested in.
> 
> **Edit:** The interface isn't allowing me to assign this to you, but consider yourself assigned.

I will start working on it. 
I will update asap

**Comment by tuminzee** [comment]
> If the Issue is open for assigning then I can work on this issue. @jimchamp 

Hi @homewardgamer I am working on this issue. But when I'm stuck, i will ask for your help. 
Have a good day 😄

**Comment by homewardgamer** [comment]
> > If the Issue is open for assigning then I can work on this issue. @jimchamp
> 
> Hi @homewardgamer I am working on this issue. But when I'm stuck, i will ask for your help. Have a good day 😄

Great! I would love to help in any way possible!😁

**Comment by mekarpeles** [comment]
A good first step may look something like:

```
diff --git a/openlibrary/templates/account/loans.html b/openlibrary/templates/account/loans.html
index be875f3c6..362cc2663 100644
--- a/openlibrary/templates/account/loans.html
+++ b/openlibrary/templates/account/loans.html
@@ -55,6 +55,12 @@ window.q.push(function(){
 <div>
   $if len(loans) == 0:
     <div><em>$_("You've not checked out any books at this moment.")</em></div>
+
+    <div><p>Perhaps you'll enjoy these hand-crafted <a href="/collections">special collections</a> or...</p></div>
+    <div>
+      $:render_template("home/custom_ia_carousel", title=_('Books We Love'), key="staff_picks", query='languageSorter:("English")', subject="openlibrary_staff_picks", sorts=["lending___last_browse desc"], limit=18)            
+      $:render_template("home/categories")
+    <div>
 $else:
   $# Have current loans
   <div class="borrow borrow-table collapse">
```

But **note** that the css styles of these components overflow the page and need to be fixed **without** breaking the homepage :) !

**Comment by tuminzee** [comment]
Thank you @mekarpeles for saying that 🕺🏼 
Also thank you @homewardgamer, I managed to solve the issue. But I am looking forward to collaborating with you

**Comment by mekarpeles** [comment]
related #5450
