### ISSUE TITLE
More padding to the Log In Button

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#5981]
The login button looks a little weird when compared to the sign in button.There is no left or right padding in the `Log in` Button.

### Evidence / Screenshot (if possible)
<img width="1426" alt="Screenshot 2021-12-16 at 9 03 39 AM" src="https://user-images.githubusercontent.com/73935799/146303463-2c4473cc-2881-4482-9e47-827e846428aa.png">

### Steps to Reproduce

1. Open https://openlibrary.org/account/login
2. Check the Log In button

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?**Chrome
- **Operating system?**MacOSX
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add some more left and right padding to the `Log In` button to make it look more even and easily accessible.

### Stakeholders

@jimchamp

**Comment by tuminzee** [comment]
@homewardgamer you have a good eye. I didn't even notice it!

**Comment by Hitansh-Shah** [comment]
Hey! I would like to contribute to this. I have set up my docker environment and I am able to reproduce the issue. Can I work on this?

**Comment by tuminzee** [comment]
@Hitansh-Shah I am pretty sure @homewardgamer has resolved this issue in his local env

**Comment by Hitansh-Shah** [comment]
@tuminzee Fine no problem🙌

**Comment by jimchamp** [comment]
@Hitansh-Shah if you are interested, #5982 should be a good first issue related to CSS.

**Comment by homewardgamer** [comment]
Should I work on this Issue @jimchamp ?

**Comment by Hitansh-Shah** [comment]
> @Hitansh-Shah if you are interested, #5982 should be a good first issue related to CSS.

Thanks for suggesting this. But I think someone has already linked a pull request for that issue. 
Also I am proficient in MERN stack so I think I would also be able to solve intermediate frontend issues. So you can suggest me if you have some in mind which are unattended.

**Comment by jimchamp** [comment]
> Should I work on this Issue @jimchamp ?

Yes, if you'd like.  Let me know if you have any questions.
