### ISSUE TITLE
Logout link in header drop-down behaves differently than other drop-down links

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5982]
### Evidence / Screenshot (if possible)
The logout link in the account drop-down header component behaves differently than other links in the drop-down:
1. The cursor does not change when hovering over the logout link.
2. The clickable area of the logout link is less wide than other drop-down links.

![logout](https://user-images.githubusercontent.com/28732543/146430004-7eb965f3-b110-48af-af61-50b13ff1a6e1.gif)

### Relevant url?

Any page.

### Steps to Reproduce

1. Log into Open Library.
2. Expand the account drop-down in the header.
3. Hover over the logout link, note the cursor as you hover.
4. Click to the right of the words "Log out".

* Actual: Cursor doesn't change on hover, and clicking doesn't trigger a logout.
* Expected: Cursor changes on hover, and clicking triggers a logout.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The underlying issue is that the logout link is actually a button, while other drop-down links are anchor tags.  The logout link _should_ be a button, as it submits a form for logging out.  The solution should only require CSS changes to the button.

### Related files

CSS rules for the button can be found here: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/header-bar.less
For reference, HTML for the button is here: https://github.com/internetarchive/openlibrary/blob/95a5a8d76d558f58ba94343c9e3b648cd6a3be56/openlibrary/templates/lib/header_dropdown.html#L48-L50

**Comment by Azazel5** [comment]
@jimchamp Hey I added a pull request for this issue a couple days ago and just wanted to make sure that the steps I did were acceptable. This is my first time contributing to open source, so please let me know if I need to change something or follow other steps to get this merged :)

**Comment by omduragkar** [comment]
Hey @jimchamp can I start working on it.  Seriously I would love to work on this issue
