### ISSUE TITLE
Match color of page-banner and footer-icons

### ISSUE THREAD

**Issue by tuminzee** [internetarchive/openlibrary#5986]
The color of top page banner and footer icons should match

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/58180803/146613358-b84c2cf0-1c6b-4c52-aee0-f4d4a557b62b.png)
![image](https://user-images.githubusercontent.com/58180803/146613399-cd89b310-5335-4b03-bd7e-9be332a49c9b.png)

### Relevant url?

https://openlibrary.org/*

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Observe top-page-banner and footer-icon

* Actual: different color
* Expected: same color

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Google Chrome Version 96.0.4664.110 (Official Build) (64-bit) 
- **Operating system?** PopOs 20.04 LTS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Make color consistent changes

### Stakeholders

@jimchamp

**Comment by ejgonzalez17** [comment]
Hi, I would like to work in this Issue .

**Comment by tuminzee** [comment]
hi @ejgonzalez17 I have solved this issue. How about you try #5987

**Comment by ejgonzalez17** [comment]
I would like to collaborate and solve this issue.

**Comment by tuminzee** [comment]
@ejgonzalez17 but this issue do you mean #5987 ?

**Comment by ejgonzalez17** [comment]
Yes, that's right, sorry, the tabs in Chrome got confused
