### ISSUE TITLE
Add option to prefer a provider in a search carousel

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5992]
Subtask of #5792

Currently, carousels on collection pages (e.g. https://openlibrary.org/collections/hugo-awards  ) cannot specify a preferred book provider (e.g. prefer librivox audiobooks). This will let us do that! Note we can already use the `providerPref` url parameter in a search; e.g. https://openlibrary.org/search?q=publisher%3Alibrivox&mode=everything&providerPref=librivox ; we just need this to be exposed to `QueryCarousel`.

Expected usage:

```{{QueryCarousel('publisher:librivox', provider_pref='librivox', has_fulltext_only=False)}}```

### Related files

- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/QueryCarousel.html

**Comment by tuminzee** [comment]
I would like to work on this issue

**Comment by cdrini** [comment]
Awesome! Let me know if have any questions :)

**Comment by cdrini** [comment]
I think all the changes that need to be made should be in the `QueryCarousel.html` file :+1:

**Comment by tuminzee** [comment]
I will try to finish this before holidays.
Thank you for your help, and prompt reply 🕺

**Comment by cdrini** [comment]
Ooooh, heads up I _think_ this might actually be quite a bit more complicated 😅 it might need changes to a few different spots. Be warned ; if it looks like it's getting complicated, bring it up :+1:

**Comment by tuminzee** [comment]
Perfect, I'll try my best 🕺👨‍💻

**Comment by cdrini** [comment]
We determined that this is probably better to day after #2064 , so removing good first issue. Thanks for your patience, @tuminzee !

**Comment by tuminzee** [comment]
Thank you @cdrini for your patience 👯

**Comment by cdrini** [comment]
Replaced by #7252
