### ISSUE TITLE
Add support for specifying cover urls to import API

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5993]
A lot of the auto-importers we want to set up for Trusted Book Providers also have covers. We don't want to have to create custom scripts to just add the covers after importing has run ; let's just make it possible to import!

### Describe the problem that you'd like solved
- Modify the import schema to support eg `cover_url: "https://....jpg"` field

### Stakeholders
@jimchamp @hornc @mekarpeles

**Comment by hornc** [comment]
@cdrini doesn't this feature already exist?

https://github.com/internetarchive/openlibrary/blob/bea487ca1576bdfda8a67d4ab89040f4f65bb390/openlibrary/catalog/add_book/__init__.py#L600-L603

The import format accepts `cover: <url>` and uploads it to coverstore and converts it to an id.

**Comment by cdrini** [comment]
Beat me to it! Yeah, just discovered it as well. Woohoo! Nothing to implement!

I tested this on my local instance:

```js
await fetch('/api/import', {
    method: "POST",
    body: JSON.stringify({
        title: "Beowulf",
        source_records: ["key:value"],
        authors: [{"name": "Tom Robbins"}],
        publishers: ["Harper Collins", "OpenStax"],
        publish_date: "December 2018",
        cover: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Harlingen._Sint-Micha%C3%ABlkerk._Hoofdaltaar._HDR._12-07-2021._%28d.j.b%29_02.jpg/750px-Harlingen._Sint-Micha%C3%ABlkerk._Hoofdaltaar._HDR._12-07-2021._%28d.j.b%29_02.jpg"
    })
})
```

**Comment by cdrini** [comment]
CC @jimchamp
