### ISSUE TITLE
Add ISO 639-1 language codes to OL language records

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5997]
Any work we want to do in the future to help display books to users in their language would require us to have a mapping between the language codes stored on our books, ISO 639-2/B (e.g. `fre`) to ISO 639-1 (e.g. `fr`), which is what's used by browsers/etc.

### Proposal

- [ ] Add a new field to our language records: `iso_639_1` (e.g. https://openlibrary.org/languages/fre.json )
- [ ] Create a script to copy data from https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes into open library

### Additional context
- Note the language code on our books isn't exactly 639-2/B, it's [MARC21](https://www.loc.gov/marc/languages/language_code.html) (See https://github.com/internetarchive/openlibrary/issues/2435#issuecomment-536763259 ), but since 639-2/B is based on MARC21, I imagine there are few collisions. It would be worthwhile to verify. Although note one of the benefits of including this data in OL is that we can fix any outliers.

### Stakeholders
@hornc

**Comment by ejgonzalez17** [comment]
Hi ! , I will try to solve this issue

**Comment by ejgonzalez17** [comment]
I just uploaded the Pull Request , I await for your comments.

**Comment by cdrini** [comment]
Sorry again for my delay on your PR, @ejgonzalez17 ! I'm going to need to take this one on; it's blocked some progress for #6377 .

**Comment by cdrini** [comment]
Ok, added these in with a wikidata-based approach; here's the code: https://colab.research.google.com/drive/1HWG92jo6wM43_iA2dINjnkj4hX5Y6kt5

**Comment by tfmorris** [comment]
@cdrini  This premise:

> ISO 639-1 (e.g. fr), which is what's used by browsers/etc.

is incorrect. The language tags used in HTTP headers (ie by browsers) are specified by [BCP 47](https://www.rfc-editor.org/info/rfc5646), **not** ISO 639-1.

In Wikidata, these can be found using the property [P305](https://www.wikidata.org/wiki/Property:P305) "IETF Language Tag". For languages which have ISO 639-1 codes, these will overlap, but the VAST majority of languages do not have an ISO 639-1 code.
