### ISSUE TITLE
OpenLibrary multi-row subject carousels glitchy

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#600]
The initial load of multi-row subject carousels on Open Library tend to be glitchy (chrome). If you click on one of the facet filters/sorters like "ebooks only", the glitches seem to go away. The glitch manifests as the two rows seeming to load independently and out of sync.

**Comment by jdlrobson** [comment]
This doesn't seem applicable now we have removed all jCarousel code.
