### ISSUE TITLE
More padding to the some buttons

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#6007]
There are many buttons that have no left and right padding, through this Issue I intent that we solve all of them, instead of taking them one by one.
For example we can solve #6003 also in this Issue.
### Evidence / Screenshot (if possible)
<img width="1439" alt="Screenshot 2021-12-23 at 12 01 41 PM" src="https://user-images.githubusercontent.com/73935799/147198450-019622d8-c6e0-45bb-85e8-b893b4753fe1.png">

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by homewardgamer** [comment]
@jimchamp  should i start working on this Issue?

**Comment by omduragkar** [comment]
@homewardgamer can I work on this. I really want to work on this issue.
Thanks,
Om
