### ISSUE TITLE
Archive/Updates of Open Library progress

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6008]
**Right now:**

- The Open Library's great in their blog at sharing their milestones.

**Issue:**

- The records of the Open Library's progress is really hard to find - on github, there's a lot of issues opened, and a project list - it's hard to know the relation to these to the OL's overall progress (like the roadmap). This causes volunteers to go in one direction when the OL is going in another potentially.
- It's really hard to contribute and keep up with (by knowing) the progress of the Open Library (personally as a volunteer, but this can apply to other positions), due to all the places where documentation's located instead of it being in one place: from the github to the google doc's being randomly located. Plus, there's no archive, so I can't compare the past to now. One example's all the roadmaps.

**Solution:**

- have a place where all the documentation of the progress of the Open Library's in lists - the projects, documents, goals, etc.
- show the status of it - finished, currently in progress, help wanted, stalled, cancelled, etc.
- shows who's working or able to work on it

**Brainstorm:**
I have no idea where this is going to go. It needs to reach out to those who actively work on the OL:
- volunteers
- developers
- staff
- etc.

**possible locations:**
- [blog](https://blog.openlibrary.org/) as a new tab called 'volunteers/developers'
  * problem - I don't like this, as the information will continually flow vs having lists that're in one place, but added to
- github
- public google drive folder for viewing or commenting only
- tab on the Open Library website for documentation of progress
   * doesn't make sense entirely, as it doesn't fit into the tab categories easily and might be info overload there. One caveat is to merge the volunteers into the developers tab, but that would be quite unpleasant to developers - as it's mixing matters - not all developers are volunteers. However, volunteers and developers are similar, and maybe there's a way to do it. Also development involves a lot of documentation and recording of progress.
   

**Questions I have:**

- is this making things overly complicated?
- is this needed?
- how can we make this work if this is going to become a reality?

**Comment by mekarpeles** [comment]
This document is a great entry point and index into Open Library:
https://docs.google.com/document/d/1KJr3A81Gew7nfuyo9PnCLCjNBDs5c7iR4loOGm1Pafs/edit

1. Details: It links to a document describing how we do project management
2. Archive: It has a breakdown of every year (for the past 5 or so years)
3. Roadmap: It links to our current roadmap + priorities documents
4. Projects: It lists project documents

Progress of efforts is typically depicted on Github (in Epic issues) or on the 
* Projects: https://github.com/internetarchive/openlibrary/projects
* Active Sprint: https://github.com/internetarchive/openlibrary/milestones
* Epic Issues: https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Epic%22

I think the index document above addresses many of these concerns. There's a link to it on the navigation menu of our main Wiki:
![github com_internetarchive_openlibrary_wiki (1)](https://user-images.githubusercontent.com/978325/148141989-cc59dbcf-1a6b-4148-bfcd-39427e3d32a4.png)

There's likely much more we can do, specific suggestions are welcome!

**Comment by BrittanyBunk** [comment]
@mekarpeles I didn't think about the github closed issues as being milestones - you're totally right.

**I do have suggestions:**
- can you label the executive index as 2018-2022?
- I don't actually see the roadmaps in the executive index. It would be desirable to place them in - unless I missed it - in which you can tell me where it is. That'll be awesome, because then the link in the github wiki for 2021's roadmap can be removed.

I think that there's been a lot of accomplishments - I'm really proud of what the Open Library's done. You'll see in my explanation below the real issue:

**Very long rest of it:**
I guess that's why I got tripped up - it's not that these accomplishments aren't there. The issue is the lack of visibility/intuitiveness. I didn't know that the roadmap is called 'executive index' - that's probably why I missed it. Another thing is when issues are closed, they're not visible unless you know to actually look for that - and type it in to the search saying 'issue:closed'.

Maybe I'm making a big deal, but wouldn't it be nice to put a footer in the github wiki a list of places you can find these accomplishments/updates - the issues, blog, roadmaps, coding, developer center, etc. I mean the pull requests is the main place you can see the progress of Open Library more than anything else, but it took me a while to figure out - just writing it out on the wiki page is nice - that's where I assume is one of the first places people go. 

Maybe there's a place to beta test there too - because you show a lot of stuff in beta in the community page and wouldn't it be nice for people to beta-test? Didn't we have that? Didn't we already have this talk about getting people to the right place? Maybe we did and the volunteer and github 'get started' section in the coding readme were created - so I guess we missed the github wiki - that's probably my fault for not communicating that. I really appreciate and thank everyone for doing the volunteer and github contribution place - those are dreams come true!

I feel this relates to a 'getting started' section on the github wiki - because everything's been written out so well https://openlibrary.org/volunteer and https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md . The next step is to make it easy to access on github on a main page people go first to, like wiki.

Do you think it'll clog up the wiki page to have a 'getting started' section with the links and have an accomplishments/updates footer (or links in the right hand column) in the wiki explaining that the Open Library showcases what they do by closing issues on the github? Maybe I don't have good intuition, but I know it would help me out.

**Comment by BrittanyBunk** [comment]
I feel like this should be opened back up, because there are so many improvements that can be made.

I found another idea: there's a lot of repositories that're by the Open Library, like the bots, clients, and librarian ones. These are super hard to find. Can't we have a section on the wiki in the right hand column listing all the repositories associated with the OL online, so that we can find them easily? It's taking me forever to look around for it.

Sorry I'm having difficulties expressing it all, but it's so many navigation links that when branched together are going to make navigation to all the good stuff so great!
