### ISSUE TITLE
add warning to merging IA-attached works

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6009]
**Background:**
In the Internet Archive, books are scanned and then attached a work in the Open Library. Some books are the same work, but different editions, yet are made into different works. 

**Problem:**
If someone goes in to merge the two works, there's nothing explaining about how the Internet Archive book that it's attached to is assigned a work. The work ID doesn't change on the IA's side. The biggest issue is that no one will know this happens when it happens, and then the bots and work ID's go out of sync and causes problems in of themselves that're avoidable.

**Solution:**

- Change the IA work ID on the IA's page for the book when the work ID changes in the OL.
- Because the first solution's unlikely to happen, add a notation (i.e. instructions) and give a warning that it's attached, so that people know or are cautious and take the right precautions either to or not to merge the two.

**Comment by mekarpeles** [comment]
This issue will be broadly solved by #732 (and is broadly similar to #5912 & #2552). This issue offers useful context for #732 but should be closed as an underlying issue is Archive.org's data becoming out of sync with Open Library IDs after Open Library records are merged.
