### ISSUE TITLE
Move editions to new works

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6010]
### Problem
Right now, the only option to modify works pages for editions is either by:

- creating a new book
- merging existing works together

None of these solutions apply to an edition in an already-existing work that needs to move to a work that doesn't exist.

### Solution
Allow to be able to create a new work from the edit page
![image](https://user-images.githubusercontent.com/55302685/147289835-4212f84d-5e87-420b-a54f-e17e5b73c214.png)

### Example:
https://openlibrary.org/works/OL19403260W/Addison-Wesley_mathematics is one that would require 2 works to be created and one to be deleted

**Comment by jimman2003** [comment]
I think this is already available, not sure why not visible in that screenshot

**Comment by BrittanyBunk** [comment]
> I think this is already available, not sure why not visible in that screenshot?

It's not in the screenshot, because it doesn't pop up. try it out to see if it does or doesn't.

**Comment by mekarpeles** [comment]
I believe @BharatKalluri and @cdrini may have been working on code related to this, adding @BharatKalluri as the `Lead` and cc'ing @seabelis as a stakeholder

**Comment by seabelis** [comment]
This exists. It may be a librarian feature.

**Comment by BrittanyBunk** [comment]
@seabelis where? If it does, then no one has to work on the cody.

**Comment by cdrini** [comment]
Yep! That's exactly the case; this is limited to librarians only since it requires a solid understanding of the difference between works and editions (which is kind of hairy :P).
