### ISSUE TITLE
Remove "browse" and "more" menu from sidebar in mobile view

### ISSUE THREAD

**Issue by Hitansh-Shah** [internetarchive/openlibrary#6012]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/76250591/147334595-68612f62-ddc7-4e29-8bbb-9506d665ffc6.png)
![image](https://user-images.githubusercontent.com/76250591/147334609-a7c8f5ef-59be-4c2d-a5d8-92abbee34f44.png)

### Relevant url?

https://openlibrary.org/.

### Steps to Reproduce

1. Go to https://openlibrary.org/.
2. open mobile view

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Ubuntu 20.04
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I propose to remove "browse" and "more" menu from sidebar in mobile view. And then we can also change the icon of sidebar to "profile" icon. This will also solve #5985

**Comment by BrittanyBunk** [comment]
I also notice that the person icon should be moved out more to see the 3 bars better too.

**Comment by omduragkar** [comment]
Hey @mekarpeles  @Hitansh-Shah  @cdrini I think i can solve this thing out. Also would love too can you please assign me this ?
Thanks,
Om

**Comment by mekarpeles** [comment]
Thank you to Dana's work on #7053 & #7021 we should be able to close this issue.

Now the options are "My Books" and "Browse" and the options have been updated based on user research we conducted.
