### ISSUE TITLE
Synchronization with other platforms

### ISSUE THREAD

**Issue by xplosionmind** [internetarchive/openlibrary#6015]
### Describe the problem that you'd like solved

Adding a book to Open Library (or editing its status) should automatically synchronize with other platforms. Ideally, this could be implemented vice-versa: any change occurred on other platforms, could be pinged and changed in Open Library, too.

<br>

### Proposal & Constraints

As of right now, there are many issues that request the option of importing and/or exporting to other book-focused platforms, among them GoodReads, Bookwyrm, Inventaire, and, of course, Open Library.

Suppose a user has one account on more than one of those platforms (most of us), and they wants to add a book they just bought. Every single time this happens, they would have to go to every platform and manually import the book or change its status.

I opened the same issue [for Inventaire](https://github.com/inventaire/inventaire/issues/593), and [for Bookwyrm](https://github.com/bookwyrm-social/bookwyrm/issues/1698).

<br>

### Additional context

Synchronization would include:

- [ ] book metadata
- [ ] reading statuses
   -  started reading
   - currently reading
   - finished reading
   - paused (or stopped reading)
- [ ] collections (a.k.a. shelves)
- [ ] <b class='wtf'>???</b>

**Comment by mekarpeles** [comment]
I'd love it if all these systems used the same decentralized catalog and provided various front-ends, but (a) Open Library can't make this decision for other platforms like Goodreads and (b) maintaining `n` integrations is a stretch, especially for bookwyrm, inventaire, and open library which have very limited resources.

Open Library **is** committed to offering APIs and making its (non-identifiable-patron) data public:
https://openlibrary.org/developers/dumps

I'm also quite happy for the community to create such integrations and of course I'm excited for any chance to coordinate w/ @mouse-reeve on how Open Library and Bookwyrm can more fundamentally team up. Decentralization is also in Open Library's interest.

**Comment by mekarpeles** [comment]
Replied here: https://github.com/bookwyrm-social/bookwyrm/issues/1698#issuecomment-1411509780

Open to more specific proposals! We currently publish monthly dumps to help other platforms get all of our updates. We have tools to import book record corrections from other services as well and we're happy to put in the time to help.

**Comment by tfmorris** [comment]
@mekarpeles Can you expand on this:

> We have tools to import book record corrections from other services as well 

I'm not aware of with any tool or process which improves OpenLibrary records when upstream providers MARC records improve, so this is very welcome news.
