### ISSUE TITLE
Autocomplete failure for ʻAbduʼl-Bahá

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#6016]
When attempting to fix a [bad work record](https://openlibrary.org/books/OL27504584M/Some_Answered_Questions) that referenced a [conflated author record](https://openlibrary.org/authors/OL7694471A), the primary author's name, as cut & paste from WorldCat ("ʻAbduʼl-Bahá"), returns zero autocomplete results.

After several attempts, the string that finally returned non-zero results was "Abdul Baha", but then attempting to use the exact name from the selected author record "ʻAbduʼl-Bahá " also fails autocomplete, encouraging the user to create a new author record with the exact same name as the selected record.
<img width="697" alt="Screen Shot 2021-12-27 at 6 50 11 PM" src="https://user-images.githubusercontent.com/82178/147514863-4e2caf6c-baca-4391-afe9-beeee7274f22.png">

Using the same string, as it appears on the author record, in an [author search](https://openlibrary.org/search/authors?q=%CA%BBAbdu%CA%BCl-Baha%CC%81&mode=everything) places the exact match *fourth* in the search results after matches which aren't even close.
<img width="475" alt="Screen Shot 2021-12-27 at 6 51 37 PM" src="https://user-images.githubusercontent.com/82178/147514851-5c1ba9ce-a196-46d8-bbda-a659c885892e.png">

### Evidence / Screenshot (if possible)

see above

### Relevant url?
see above

### Steps to Reproduce
see above

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Exact search matches should appear first. Autocomplete return matching results.

**Comment by tfmorris** [comment]
Autocomplete for the top right search box now works, but autocomplete in the author field of the work edit page is still broken. This may have the same root cause as #4800. It may also be related to #790 which got mistakenly closed.

@mekarpeles should I stop reporting search bugs? This didn't even get triaged in over a year which makes it feel like a waste of time to report them in the first place.

**Comment by mekarpeles** [comment]
@cdrini when I ignore the `-` in `Abduʼl-Bahá` (as @tfmorris mentions re: #4800) the author is able to resolve correctly from the edit UI.

**Comment by cdrini** [comment]
This appears to no longer be an issue.
![image](https://github.com/internetarchive/openlibrary/assets/6251786/1dab2ee3-ea4c-46de-b66f-7f49d5d35cf5)


Also it looks like #790 was correctly closed, the primary issue there was with the /search/authors endpoint, which had a different root cause as well
