### ISSUE TITLE
Date format isn't correctly read off edition.

### ISSUE THREAD

**Issue by HamsterDeveloper** [internetarchive/openlibrary#6021]
### Evidence / Screenshot (if possible)
![Screenshot_2021-12-29 Kerstin Gier Open Library](https://user-images.githubusercontent.com/33803304/147663665-59810ef6-d97a-4fb4-bedd-5847039916c2.png)

### Relevant url?

[Affected work](https://openlibrary.org/works/OL26745647W)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

when adding the publication date to editions in the recommended format (YYYY-MM-DD), the website isn't able to display the line "First published in YYYY" on an author's page. "Sep 29th, 2021" would work on the other hand. This doesn't allow to correctly sort by most recent/first published.

### Proposal & Constraints
as both formats "YYYY" and "Sep 29th, 2021" work and are correctly sorted on a work's page, I can imagine those two are converted to the same format in order to be able to be compared to each other. If that's not the case for "YYYY-MM-DD", it would be worth investigating if that effects the sort order in the edition list as well.

### Stakeholders
@cdrini

**Comment by mekarpeles** [comment]
@HamsterDeveloper one consideration worth clarifying is that on the Author page, we're actually seeing a list of Works and not Editions.

This happens to be the result of technical limitations, not a our decision about the experience. This list is populated by our search engine with indexes works (not editions). This is something we have scheduled to work on in the 1st half of this year.

@cdrini as I understand it, because we're seeing works on the author's page, we're not easily able to show the edition level facet information (like date) that @HamsterDeveloper might prefer.

**Comment by HamsterDeveloper** [comment]
it's really only about the format of the source data though, because the relevant information is already being taken from the edition and displayed correctly if another date format is used.

**Comment by agmckee** [comment]
When the date is entered into an edition in ISO 8601 format the SOLR document attribute "first_publish_year" doesn't get created for the indexed edition. This is the data that ultimately gets used by the SearchResultsWork macro and also the worksearch module. The reason it doesn't get indexed are lines 597-600 in update_work.py:

```python
pub_years = {
    m.group(1) for m in (re_year.search(date) for date in pub_dates) if m
}
if pub_years:
    add_list('publish_year', pub_years)
    add('first_publish_year', min(int(y) for y in pub_years))
```
re_year is a regular expression that matches 4-digit years but doesn't match ISO 8601 dates. See https://regex101.com/r/QUlBC0/1

I tested this in my local environment by creating some editions with ISO 8601 dates and examining the documents in SOLR for those editions and noticed the missing "first_publish_year" attribute.
