### ISSUE TITLE
Labels when pointing on rating

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6024]
Open Library uses 5-star rating, and I think it might be a good idea to add labels to each star. For example, something like on Goodreads: when you point at 1-star it will show — did not like it, 5-star — it was amazing, or something like that.

**Comment by tuminzee** [comment]
I like the idea @bicolino34; I'd like to give my idea after some testing.

**Comment by tuminzee** [comment]
Stars | Interpretation 
-- | --
⭐️ | I didn’t like it.
⭐️⭐️ | It was a one-time read.
⭐️⭐️⭐️ | I enjoyed reading it.
⭐️⭐️⭐️⭐️ | I enjoyed reading it and I recommend it to others.
⭐️⭐️⭐️⭐️⭐️ | I enjoyed reading it, I recommend it to others, and I would also like to re-read it.

**Comment by bicolino34** [comment]
@jimchamp delete label "Needs: Community Discussion"

**Comment by mekarpeles** [comment]
I think we may do a disservice trying to impose strict criteria around the star ratings. I'm not exactly sure what problem that we're trying to solve here. I wouldn't presume people are going to change how they rate books based on a description that we offer, nor am I sure we should try to achieve that. For instance why does a four star book mean that I would recommend it? If they wish to communicate something beyond a star rating we have community tags that allow them to communicate much of what's being shown in the table above. Feel free to bring up during a community call if others feel differently; my feeling is to close.

**Comment by tuminzee** [comment]
@mekarpeles, I will bring this in the community call, also I really like how Daniel Capilla expressed his views on this one

**Comment by mekarpeles** [comment]
Open to other ideas! Especially since on mobile there aren't hover states anyway, I think the existing star ratings as is are sufficiently intuitive. Closing for now. Thank you for putting the time into this proposal, I'm glad it is here for us to discuss
