### ISSUE TITLE
IA Bar visible on mobile view breaks the App drawer experience

### ISSUE THREAD

**Issue by Yashs911** [internetarchive/openlibrary#6025]
I noticed that the IA bar is also visible on mobile view. So is this intentional?
Because it seems to break the app drawer experience, maybe I can fix that if it's intentional, or else I will remove the IA bar from mobile view.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/64412143/147811794-93024e56-8dea-443b-a774-67cbb2ed1e93.png)

### Relevant url?

https://openlibrary.org/
### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Mobile view

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by mekarpeles** [comment]
I think the current design is okay for now -- for now we are showing the IA top bar (even on mobile)
