### ISSUE TITLE
Internationalization of original book titles

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6032]
**Problems:**
- original books might be in a different language than the native language of someone coming onto the Open Library to view it. This leads to problems, where they can't find the book title, because it won't come up in the search. Even if it does, it won't be possible to read, because it's in a different language.
- google translate can't be used for multiple languages, so it won't be able to translate titles if the language is different than the language being viewed for the rest of the open library page.
- a lot of people are having this issue. One person even created a bookmarklet to 'anglify' book covers to English (https://gist.github.com/MignonBelongie/02019888af8a44811850458d891350e2), so that they can read it. However, this isn't enough, because it won't be accessible to everyone and these anglified titles won't be searchable. The 'anglification' needs to be on the website itself, along with every other language there.
- books aren't translated to every single language, so we can't rely on translations to find a book in languages it's not translated in.

**Solution:**
- create an international conversion form in the works edit page, so that the original title can have a translated/transliterated (or an extra option - what it's commonly referred to in a language - not sure what that's called) version underneath that people can read in their own language (especially when google isn't able to).
- people can use bookmarklets (or google translate) to import titles that they see from those translations to this form field
- how the form field looks like is in the area inside the red box
![image](https://user-images.githubusercontent.com/55302685/148114929-589b30b2-a890-4ac7-b801-040a8cc392d4.png)

**Relates to:**
github issues #2775, #2919, #865, #2190, #412, #2601 (especially), and #2752

**Complications:**
- it would be preferable to see the translated titles on the works page. However, if people don't want to see it, it can be just invisible on the works page and only in its edit section for use only for search results.

**Stakeholders**:
@cdrini @mekarpeles @MignonBelongie and anyone else that's interested in participating

**Comment by LeadSongDog** [comment]
@BrittanyBunk 
To be clear, are you suggesting that we find teams of humans to manually translate e.g. all the Serbian titles to Balinese? That seems a rather intractable approach in several regards. You’d also eventually need to index hundreds of translations for each work title, all for the sake of those few Balinese users who are interested in knowing about a Serbian work that has never been translated. 

Better to start with improvements to the way and the frequency that existing translations are captured: most authors write in one language and translations appear in much the same sequence as the first editions. We could do much better at recognizing these as translations and merging them into the correct work.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I think there's a lot of assumptions, misunderstandings, and a lack of depth of ideas. So I'll address them.

No - I never mentioned finding 'teams of humans' anywhere. It's just an extra field form when editing a work page. It'll be no more people than those that already exist to work on editing pages of books right now. People (unless bots take up this job) will manually add in a translation - this is mainly for themselves, but in a public space to help out others.

Because of this, it's not 'indexing hundreds of translations' - it's going to be most likely few to none for each book, because they're going to be manually entered in (unless one person decides to take up the role of adding in all of them or bots do this). Adding a few extra titles into the search engine is well worth the cost for the benefit of people who are limited in what they can read, because they can't use the site to find books they're looking for - to me, that's unfair.

I don't think it matters if a book has a translated version or not - so worrying about it shouldn't need to happen. Why:
- this feature is a beginning step for a feature that allows books in the Internet Archive to be listened and translated to any version they want to read in. 
- maybe people just want to find the book they're looking for without reading it. The Open Library gives descriptions of books - so they can find it. You don't need a book to be translated for that - maybe someone who can translate it to them will, but at least they will know where the book is for that.

I'll take your example: say there are a few Balinese users who look at a Serbian work. Maybe there's no Balinese translation, but that book is heavily talked about in that language, maybe because of the cultural impact it has. Maybe one person writes in the Balinese translation and there's only 100 Balinese speakers that'll look at it - those people might talk to others and it might reach 1000s to 10,000s of people or more. If we rely only on translations, it's not going to work, because it's going to miss out on these situations. Maybe if it's on the Open Library with the title translation, it would become widespread in knowing about the book enough for it to become its own translation - and the Open Library would have a role in that - so that the people who need that book will be able to see it finally in their language. One begets the other. 

I really hope that the Open Library can be that starting point for helping the world to read more and better, so that there is equal access in reading opportunities. It's not supposed to be a bigger deal than what it is: just a form field for people to add in a title in their language, so that they can read the title and understand it, to know they're looking at the right book, and have it be the same language as the rest of the page they're reading - so everything is translated to the same language, and search for it in the search bar, so they can find it. That's all.

**Comment by BrittanyBunk** [comment]
As seen in #6041 , there's definitely an issue where titles are getting transcribed by bots.

In addition to translation and transliteration, there should be a field for transcription. I'm going to call this TTT from now on

There actually not only should be an ability to TTT to other languages, but it might need to be done for the language the title's in - so that each could be looked up. For instance, if there's an edition in Bengali that might pop up differently in different places, such as without accents or transliterated in a way that doesn't make sense (like question marks in the title), each iteration of its own language should be posted underneath the title.

**The issue:** is that this can cause too much clutter. I don't know where this can be located, maybe only on the back end or as a hide/show feature, but all of it should be there and it's going to be really long. Maybe it would work better in a table, idk. It's something to talk about further, but is good to acknolwedge, so we're not surprised when the time comes.

**Comment by onnotasler** [comment]
I think all fields necessary are already included in the front end: You have "Language", "Title" and "The Book is also known as" field. If you combine those, you should have all data to show a works title according to the browser's preferred language.

I think, the problem could technically be solved if the work's title was not entered manually, but created automatically according to language settings and edition information.

**Comment by cdrini** [comment]
This was addressed by edition-aware search. Now, on authors pages and in search results, the book title will be displayed in the users language. Eg https://openlibrary.org/authors/OL2162284A/Stephen_King?lang=fr

There are other places we need to apply this logic though (carousels)
