### ISSUE TITLE
Add autocomplete to subject + people + places

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6050]
I would like to have list of prompts when typing info for books. Preferably, with number of usage of this certain subject.

Example from Russian fan fiction site ficbook.net (search for users).
![image](https://user-images.githubusercontent.com/58372007/149519467-511df2d7-25b2-4343-86e7-7ffac01eca9f.png)

**Comment by tuminzee** [comment]
I would like to work on this issue

**Comment by BrittanyBunk** [comment]
This actually, as I discussed in #6074 was also discussed at the same meeting - we all talked about which keywords should be pulled out of books.

We thought about how the most common words can be pulled out, but we realize that those would not be representative of the book itself, as you'd get issues like having the word 'the' or 'a', prepositions, etc. popping up. Then we thought about having the unique words come up, but those might just be for one sentence and doesn't represent the book at all.

Then maybe the most common unique word can be used, but that might just be referenced without it being about the book at all.

I actually suggested having the keywords from google books be brought into the Open Library. I actually feel like I already wrote this out somewhere, but I can't find it

**Comment by BrittanyBunk** [comment]
this is related to #4027 , because the issue is keywords aren't the same as what the book's about itself.

**Comment by BrittanyBunk** [comment]
I think I found the reason for this problem here: #584

**Comment by tuminzee** [comment]
Sorry @BrittanyBunk it took me some time to reply to this, but I really like the early references which you have tagged here

**Comment by mekarpeles** [comment]
@tuminzee if you still would like to work on this issue, would you like to propose a small technical plan + design and bring to an upcoming community call for discussion?

**Comment by tuminzee** [comment]
@mekarpeles yes I will do that :)

**Comment by tuminzee** [comment]
sorry @mekarpeles I wouldn't be able to finish it right now. 
I will un-assign myself from the task
