### ISSUE TITLE
Replace psycopg2 with asyncpg to accelerate database performance 3x

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#6052]
I'm always frustrated when Open Library takes too long to respond

### Describe the problem that you'd like solved

Replace [psycopg2](https://pypi.org/project/psycopg2) with [asyncpg](https://pypi.org/project/asyncpg) to leverage Python asyncio to accelerate database performance 3x.
* http://magic.io/blog/asyncpg-1m-rows-from-postgres-to-python
* https://github.com/magicstack/asyncpg
* https://levelup.gitconnected.com/fastapi-vs-express-js-vs-flask-vs-nest-js-benchmark-5e14d518cc00

### Proposal & Constraints

Adopt `asyncpg` or wait to see if https://www.psycopg.org/psycopg3 is even better.

**Comment by tuminzee** [comment]
I would like to work on this issue

**Comment by mekarpeles** [comment]
@cclauss proposed closing, we can always re-open in the future, great idea may be lots of work
