### ISSUE TITLE
Better Share Preview for Lists & Reading Log (e.g. Twitter Social Card)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6054]
This is a create "social card" view of a book list (from fivebooks). Would be great if Open Library lists generated this type of preview :slightly_smiling_face:

see: https://twitter.com/jabuppartyon/status/1482812981591347206

![twitter com_tommycollison_status_1482812483337277442](https://user-images.githubusercontent.com/978325/149683625-487f1e78-ab3b-4574-8bfa-cfaeec3eed08.png)

Here's the metadata fivebooks attaches:
```
 <meta name="twitter:card" content="summary_large_image" />
 <meta name="twitter:title" content="Five Books: The Best Sci Fi Books for Beginners, recommended by Nicholas Whyte" />
 <meta name="twitter:image" content="https://fivebooks.com/best-books/sci-fi-books-for-beginners-nicholas-whyte/shareimage.jpg" />
 <meta name="twitter:site" content="@five_books" />
 <meta name="twitter:label1" content="Interview by" />
 <meta name="twitter:data1" content="Cal Flyn, Deputy Editor" />
 <meta name="twitter:label2" content="Est. reading time" />
 <meta name="twitter:data2" content="16 minutes" />
```

Here's what Open Library's looks like today (for Lists):
![twitter com_tommycollison_status_1482812483337277442 (1)](https://user-images.githubusercontent.com/978325/149684431-fb5a7ed6-b5cf-4ec5-b5e7-ab445890306a.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

In order to load the List page, we'd have already pulled the list + bookcovers from the db, so the right `/templates/type/list/view` (?) file like just needs to be updated somehow to use the e.g. 5 first book covers.

One question is how the book covers are converted into a single image. We may wish to create a simple endpoint on our coverstore service (https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/code.py) to combine these images into a preview image which then gets used to the card.

This could be done with `Pillow`
https://www.tutorialspoint.com/python_pillow/Python_pillow_merging_images.htm

This isn't a super easy issue, however it is well scoped if someone wanted to give it a shot!

**Comment by Udai1931** [comment]
Hi @mekarpeles, I like to work on this.

**Comment by BrittanyBunk** [comment]
I see what you mean. I think it's a genius idea to treat lists like a tumble page where you see the book cover and browse through that than look at them one at a time. I wonder if that'll improve loading times too? At the very least it lets people view more to have to click around less.

**Comment by mekarpeles** [comment]
Thank you @Udai1931! If you have any questions, please let me know!

**Comment by saieswar13** [comment]
Is this still open issue? Can I work on it?

**Comment by tuminzee** [comment]
Hi @saieswar13, @Udai1931 is working on the issue, 
How about you take a look [here ](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Help%22). I am sure you will find something interesting
Happy Contributing 😄 
Thank you for your interests in Open Library 🕺🏼 

Let me know if you are stuck, I would love to help.

**Comment by mekarpeles** [comment]
@Udai1931 are you still planning on working on this one? And if so, did you have any questions about getting started?

**Comment by mekarpeles** [comment]
@saieswar13 it seems it's all you if you'd like to take this one on! :)

**Comment by tuminzee** [comment]
@saieswar13 best of luck with the issue :)
Thank you for contributing to Open Library

**Comment by saieswar13** [comment]
> @saieswar13 it seems it's all you if you'd like to take this one on! :)

Thank you @mekarpeles, Sir I'm new to open source contribution. Could you please say me how to get start with this issue?

**Comment by tuminzee** [comment]
> > @saieswar13 it seems it's all you if you'd like to take this one on! :)
> 
> Thank you @mekarpeles, Sir I'm new to open source contribution. Could you please say me how to get start with this issue?

I think the best way to interact would be to ping @mekarpeles on slack

**Comment by tuminzee** [comment]
@saieswar13 how are you doing?
Did you manage to get yourself started with the issue?
Please let me know if you have any difficulties, I would love to help. 

Adding few links which will help you to get started with Open Library
- https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md
- https://github.com/internetarchive/openlibrary/wiki

**Comment by mekarpeles** [comment]
Hi @saieswar13, I'm going to open up the assignee field for now and give others an opportunity. Please let us know if you've already started working on this as I want your existing work to be respected / considered! Thank you!

**Comment by constantinazouni** [comment]
Me and @Vassilis-Boubis would like to work on that

**Comment by mekarpeles** [comment]
It looks like we won't be able to use svg
https://stackoverflow.com/questions/21636503/use-svg-as-ogimage

We'll probably want to...
* [ ] create a background image which gets added to `/static/imgs`
* [ ] Write a function (lets call it `create_list_preview` which takes a list ID (e.g .`/people/mekBot/lists/OL104041L`) fetches the first 5 **book items** from the List, uses python Pillow / PIL library to overlay these book covers over the background, and then returns the image preview (in memory).
* [ ] creates a public API endpoint which calls create_list_preview and returns the image

**Comment by mekarpeles** [comment]
@Vassilis-Boubis + @constantinazouni, is it alright if @furugoorin helps with the 1st checkbox of creating a background design? I think that would be a cool collaboration!

**Comment by furugoorin** [comment]
Great, I'll keep you all posted with some mockups here! Do let me know if there are any updated specifications with regards to dimensions, palette, etc., when the mockups are ready.

**Comment by furugoorin** [comment]
Please refer to this [social card designs link](https://xd.adobe.com/view/b7274a73-6173-4683-b275-7f776ca7ef9d-e274/) 

I can make more changes on my end, and sync them here.

The first two prototypes are just color gradients; I tried to find the closest color match by converting hsl to hex given the `css/less color.less` file, and from a general overview of the OpenLibrary website. The rest is a matter of preference for different parchment/paper textures (I tried to adhere to the theme of books). We can toss more ideas around, as well!

**Comment by mekarpeles** [comment]
nice work! this looks cool :)
![xd adobe com_view_b7274a73-6173-4683-b275-7f776ca7ef9d-e274_ (1)](https://user-images.githubusercontent.com/978325/165189521-42243c67-e94b-48ea-911f-3bfe14e776f9.png)

**Comment by jimchamp** [comment]
How should the card look if there are less than five items on a list that have covers?

**Comment by furugoorin** [comment]
@jimchamp How about justifying the content so that the books are centered, to begin with? [See mockup](https://xd.adobe.com/view/b585fe5e-cf8c-43eb-8cdb-24caa7613ca0-e0d6/)

**Comment by jimchamp** [comment]
Thanks @furugoorin!  That makes sense to me.

@constantinazouni, I noticed that Twitter has a 5MB maximum size limit for card images.  More details can be found here: https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#crawling (in the "URL Crawling & Caching" section).
