### ISSUE TITLE
Possibility to add more photos to author page

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6055]
I would like to have possibility to add more than one photo to author page.

**Comment by jimchamp** [comment]
Both books and authors can be linked to multiple images, but today the interface only shows one. Are you asking for the UI to show more than one image?

**Comment by bicolino34** [comment]
> Both books and authors can be linked to multiple images, but today the interface only shows one. Are you asking for the UI to show more than one image?

@jimchamp Yes, I would like to have UI. I didn't know that multiple images can be linked

**Comment by tuminzee** [comment]
![image](https://user-images.githubusercontent.com/58180803/151032660-4f93fd04-332e-4f87-90f4-29d27fd02b81.png)
may be something like a carousel on the author images?

**Comment by bicolino34** [comment]
> ![image](https://user-images.githubusercontent.com/58180803/151032660-4f93fd04-332e-4f87-90f4-29d27fd02b81.png) may be something like a carousel on the author images?

@tuminzee cool idea!

**Comment by BrittanyBunk** [comment]
if you do this idea, it would be wise to label dates on them, at least by year. I personally feel it might be a little confusing, both from a logistical and use standpoint, but don't let me get in the way of your ideas. I like having only one photo, as I can associate only that, but I know it's easier to recognize authors by different pictures they may have of themselves.

**Comment by tuminzee** [comment]
@BrittanyBunk I agree to that; how we ask the community if they want this. if yes, I'd be happy to prepare a demo for it.
