### ISSUE TITLE
Faroese available twice in language selection

### ISSUE THREAD

**Issue by HamsterDeveloper** [internetarchive/openlibrary#6062]
When choosing the language of an edition, Faroese apppears twice.

### Evidence / Screenshot (if possible)

![Slack Image (2022-01-21_06-43-35-640)](https://user-images.githubusercontent.com/33803304/150575806-29964053-2b5b-4786-997d-8c6b4a4bf67f.jpg)

**Comment by cdrini** [comment]
Faroese appears twice here: https://openlibrary.org/languages , under https://openlibrary.org/languages/far and https://openlibrary.org/languages/fao . We likely want to merge these two, and then update all records? This isn't something we've hit with languages before.

**Comment by lephemere** [comment]
far language code for Faroese was deprecated in MARC 21 (https://www.loc.gov/marc/languages/language_code.html). [far](https://iso639-3.sil.org/code/far) is however a valid ISO 639-3 language code for the Fataleka language.

**Comment by lephemere** [comment]
There are actually more duplicate language names with different MARC codes:

| Language Name | MARC Code | Discontinued MARC Code |
|---|---|---|
| Croatian | [hrv](https://openlibrary.org/languages/hrv) | [scr](https://openlibrary.org/languages/scr) |
| Esperanto | [epo](https://openlibrary.org/languages/epo) | [esp](https://openlibrary.org/languages/esp) |
| Ethiopic | [gez](https://openlibrary.org/languages/gez) | [eth](https://openlibrary.org/languages/eth) |
| Faroese | [fao](https://openlibrary.org/languages/fao) | [far](https://openlibrary.org/languages/far) |
| Frisian | [fry](https://openlibrary.org/languages/fry) | [fri](https://openlibrary.org/languages/fri) |
| Galician | [glg](https://openlibrary.org/languages/glg) | [gag](https://openlibrary.org/languages/gag) |
| Guarani | [grn](https://openlibrary.org/languages/grn) | [gua](https://openlibrary.org/languages/gua) |
| Interlingua (International Auxiliary Language Association) | [ina](https://openlibrary.org/languages/ina) | [int](https://openlibrary.org/languages/int) |
| Irish | [gle](https://openlibrary.org/languages/gle) | [iri](https://openlibrary.org/languages/iri) |
| Khmer | [khm](https://openlibrary.org/languages/khm) | [cam](https://openlibrary.org/languages/cam) |
| Malagasy | [mlg](https://openlibrary.org/languages/mlg) | [mla](https://openlibrary.org/languages/mla) |
| Oromo | [orm](https://openlibrary.org/languages/orm) | [gal](https://openlibrary.org/languages/gal) |
| Sami | [smi](https://openlibrary.org/languages/smi) | [lap](https://openlibrary.org/languages/lap) |
| Samoan | [smo](https://openlibrary.org/languages/smo) | [sao](https://openlibrary.org/languages/sao) |
| Serbian | [srp](https://openlibrary.org/languages/srp) | [scc](https://openlibrary.org/languages/scc) |
| Shona | [sna](https://openlibrary.org/languages/sna) | [sho](https://openlibrary.org/languages/sho) |
| Sinhalese | [sin](https://openlibrary.org/languages/sin) | [snh](https://openlibrary.org/languages/snh) |
| Sotho | [sot](https://openlibrary.org/languages/sot) | [sso](https://openlibrary.org/languages/sso) |
| Swazi | [ssw](https://openlibrary.org/languages/ssw) | [swz](https://openlibrary.org/languages/swz) |
| Tagalog | [tgl](https://openlibrary.org/languages/tgl) | [tag](https://openlibrary.org/languages/tag) |
| Tajik | [tgk](https://openlibrary.org/languages/tgk) | [taj](https://openlibrary.org/languages/taj) |
| Tatar | [tat](https://openlibrary.org/languages/tat) | [tar](https://openlibrary.org/languages/tar) |
| Tswana | [tsn](https://openlibrary.org/languages/tsn) | [tsw](https://openlibrary.org/languages/tsw) |

**Comment by tfmorris** [comment]
> This isn't something we've hit with languages before.

#863 contains my original 2018 report of this problem along with a recommended course of action.
