### ISSUE TITLE
add API endpoint and/or olclient method for adding a new author

### ISSUE THREAD

**Issue by MignonBelongie** [internetarchive/openlibrary#6063]
I would like to be able to edit a work, using olclient or the API, in order to assign an author to it, even if the author doesn't already exist. Since I can already do this for authors that do exist, being able to create a new author would solve my problem.

Of course, it's already possible to add a new author when editing a work through the website. That apparently works by setting the author key to `__new__`, in which case the author name is used to create a new author. (I think the author name is ignored if an actual author key is used.) This would also be a good solution for me.

### Stakeholders
@mekarpeles

**Comment by tfmorris** [comment]
OpenLibrary already has hundreds of thousands of duplicate author records. Anything that makes it easier to create additional duplicates should be strongly discouraged.

**Comment by MignonBelongie** [comment]
This might be crazy, but what if the API required a parameter that demonstrated that you checked for an existing record for the author? E.g. `/addauthor?name=Jane+Doe&numMatchesFound=<n>`, where `n` is the number of results when doing an author search with that name.

**Comment by jimman2003** [comment]
> This might be crazy, but what if the API required a parameter that demonstrated that you checked for an existing record for the author? E.g. `/addauthor?name=Jane+Doe&numMatchesFound=<n>`, where `n` is the number of results when doing an author search with that name.

I think , this won't work because:
1. A script can also fetch that number , making the throttling meaningless
2. You can create similiar named author, no problem, perpetuating the duplicate author problem

**Comment by MignonBelongie** [comment]
My intention was to prevent accidental duplicates, not deliberate ones.

**Comment by cdrini** [comment]
Hunting around, it looks like this _is_ possible! Not sure what perms it needs. Search for `class new` to find the code.

```js
await fetch('/api/new', {
    method: 'POST',
    body: JSON.stringify({ type: {key: '/type/author'}, name: 'Hello world' })
})
```
