### ISSUE TITLE
Improve merge workflow for duplicate works

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6064]
### Describe the problem that you'd like solved

Today, and most likely always, Open Library will have duplicate records for works. Often, duplicates contain very little information about the book in question.  This can lead to a poor experience for patrons who have navigated to a duplicate work page in hopes of finding information about the book.

There is a manual process to merge duplicate records, but it is cumbersome and not open to many folks.  If this process was easier and accessible to a larger group of people, it may result in more duplicates being merged.

### Proposal & Constraints

The merge workflow could be improved by doing the following:

- [x] Create a UI for merging duplicate work records (#3408)
- [x] Create a merge request queue and UI (#4071)

**Comment by Hitansh-Shah** [comment]
Hey @jimchamp . I could give this a try. Can I work on this?

**Comment by mekarpeles** [comment]
Squashed!!!
