### ISSUE TITLE
Improve Book Page Mobile Header Section

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6066]
### Describe the problem that you'd like solved

Improve the header to show author, title, subtitle, ratings above fold for mobile view (mediaqueries).

Today, visiting a book page on a mobile device is not a good experience.  If one comes to a book page searching for a book's title or description, they have to scroll well below the fold to find what they are looking for.  These problems are exacerbated when landing on a page with an ambiguous cover image:

Is:
![mobile_book_page](https://user-images.githubusercontent.com/28732543/150614570-18164acd-f1ea-4f2f-bdc1-9eb9fce37a37.png)

Should be closer to:
<img src="https://user-images.githubusercontent.com/978325/163467647-6ed1c513-a020-43e7-8fcb-7543ffb41480.png" alt="openlibrary org_books_OL32784120M_Harry_Potter_and_the_Chamber_of_Secrets(Pixel 5) (1)" width=300>

### Proposal & Constraints

Let's ensure that the following information is above the fold on mobile devices:

- The Header Section:
	- Cover image
	- Preview and search buttons
	- Book title and subtitle
	- Byline
	- Aggregate ratings and shelf counts
	- Borrow button
	- Want to read button
- Navbar

### Additional context

Code changes in support of this issue should not affect the design of the desktop book page.

**Comment by tuminzee** [comment]
I would like to work on this

**Comment by constantinazouni** [comment]
Can @Vassilis-Boubis and I work on that issue?

**Comment by cdrini** [comment]
This has been merged into master now :+1:
