### ISSUE TITLE
Account registration success page + email use different usernames

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#607]
On the success page, you are shown your displayname. In the email verification you are shown your archive.org username. We probably want to be consistent with which one we show.

Great catch by our friends at Rutgers!

**Comment by guyjeangilles** [comment]
@mekarpeles If I remember correctly, authentication was all moved over to archive.org and thus this problem doesn't exist anymore. Thus I propose to close this issue. Let me know your thoughts.
