### ISSUE TITLE
Access denied on public OL documents

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6077]
Problem:
2020: Priorities - Open Library
and other documents deny access to seeing them on the executive index: https://docs.google.com/document/d/1KJr3A81Gew7nfuyo9PnCLCjNBDs5c7iR4loOGm1Pafs/edit#

There's actually the same issue with many documents in the roadmap page of the wiki: https://github.com/internetarchive/openlibrary/wiki/Roadmap

Solution:
make all of the ones that should be publicly visible given access or copied into a document for access.
some roadmaps might be missing on the executive index - they should be added and give everyone access to see them.

The issue is I feel there're some documents I contributed to and now I can't access them, and neither can anyone else.

**Comment by tuminzee** [comment]
List of the documents which deny access along with the links:

- [2018 Roadmap](https://docs.google.com/document/d/1wpa4f-r8jBimam-36CAZGQ_QjApegm10XfH85eG7KAE/edit)
- [2018 Q2](https://docs.google.com/document/d/1yLWc335qsLyMPbWULMj25VGBX-ruJrcBH0JpfLzxy0Y/edit)
- [2022: Open Library - Planning](https://docs.google.com/document/d/1szK5X2RPJl1hZ2cYiv9zw7QOn1I_QSJkCHckHi6Ue2c/edit)
- [Project Kickoffs](https://docs.google.com/document/d/1UESWsk2QX1_NBOiOSVb1VU6vMjNujyh7sB0T7H_jKH4/edit#heading=h.55s0nzir6nvy)
- [ABC Weekly Standup 2022](https://docs.google.com/document/d/1UESWsk2QX1_NBOiOSVb1VU6vMjNujyh7sB0T7H_jKH4/edit#)

[...to be continued]
(P.S. I am not sure, if the whole community should have access to all docs mentioned)

**Comment by mekarpeles** [comment]
I've updated the documents which should be open -- 2018 docs are good to link (i.e. know they exist) on the index, but were intended for staff and thus will remain with their current permissions. ABC is a staff planning doc.

**Comment by BrittanyBunk** [comment]
@mekarpeles if there're staff documents, it would be helpful to label them as such, as this is appears as a public document and it's mixed messages without signifying.
