### ISSUE TITLE
Book isn't shown correctly in reading log

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6079]
I was scrolling through my want to read list and found a book without cover, title and instead of author there was Unknown author. When I click on it, it sends me to Eldest by Christopher Paolini (OL3396812M). It was imported from Goodreads. 

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/58372007/151355492-a915c829-0c74-482f-84f5-e0777530172b.png)
leads to
![image](https://user-images.githubusercontent.com/58372007/151355551-7cd9bd72-d38f-4369-9d90-c74892562e03.png)
same goes for Eragon
![image](https://user-images.githubusercontent.com/58372007/151355747-73a244a8-5c35-40af-b254-1a5a29b0a54f.png)

### Steps to Reproduce
Probably, export books from Goodreads and check reading log

### Stakeholders
@mekarpeles

**Comment by BrittanyBunk** [comment]
I feel like this is a known issue that has to do with solr indexing, as it's actually a site-wide issue that goes beyond a reading list. It's also an issue when you create a list or when you click on a book to read. @cdrini discussed this at the community meetings to me and explained that he's reindexing to prevent these issues from happening.

I don't believe this has much to do with goodreads, but it could - I am not 100% sure on anything really. I actually think this might be some issue to do with the lack of writing in the title in the gray boxes. This was a request that I made, so it was granted, but only partially - some gray boxes still don't have titles. 

There's also the issue of book covers in regards to how they're linked and which book cover is posted - this is actually a bot issue. This might be the issue happening here.

**Comment by mekarpeles** [comment]
Sorry, I don't believe this has to do with solr.

I think it's more likely that this was a work which was **merged** and the stale book is on the reading log.

We have an effort on our roadmap for this quarter to fix the underlying problem: #2553 

Marking this issue as resolved because the source of the problem is known and an effort has been prioritized to address it.

Thank you for documenting and raising!
