### ISSUE TITLE
Should be a way to "resend" welcome/activation email

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#608]

**Comment by aalmazan** [comment]
Is this still something that can be worked on? Mind if I take a crack at it?

**Comment by guyjeangilles** [comment]
@mekarpeles to clarify, this would be a button/clickable link on a users account page to resend the validation email?

**Comment by mekarpeles** [comment]
Thank you for the offer @aalmazan! I think since activation is now handled by Archive.org as of #526, this can be closed
