### ISSUE TITLE
post-informational community meetings

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6080]
Question:
I notice that the problems being worked on with the Open Library are getting more and more. This is a good thing. However, the community meetings are just too small to go over each one in depth. This leads to people like me not understanding fully the details of each issue and makes me not able to help out as much as I'd like to. This also has an issue on the opposite end, where issues might not be worked on, because they're not discussed to where a solution's reached.

However, I'm not a person in charge of creating meetings nor one who solves issues officially. There's also the big issue of 'time'.

So my question is - should we have more community meetings, ones past the regular general meetings to talk about specific issues?

If we can't have official community meetings, because it would take up too much time from those who actually solve the issues of the OL, is there a way for volunteers to come together to help each other understand details more and get on the same page? I feel this would be super helpful, because I notice a lot of people post the same issue on github or ask the same questions - and this might alleviate people's concerns, as well as keep the issues on github low.

Thoughts? Just brainstorming here. Do people want this, like I do, or is it just me?

**Comment by BrittanyBunk** [comment]
I have an idea - if a volunteer repository's created, then volunteers can have their own weekly meetings on top of the ones by the staff, so that volunteers can offload the work and explain info to each other.

This is especially great for those who speak in foreign languages, as then people can explain to each other in other languages, so everyone's on board. The issue with regular community meetings is that they're in English. Solves multiple issues at once.

**Comment by mekarpeles** [comment]
If there's a special topic which requires discussion, we're happy to help facilitate a meeting, but given the amount of work on staff's plate already, we feel that having a mtg w/o a specific agenda may subtract further from our time.

I appreciate there are many who would like to be more involved, however a separate volunteers repo doesn't seem like the way to go about it. Staff needs to be responsible for running the system and thus we need to have say in what PRs get merged. Anyone is welcome to submit a proposal and a PR!

**Comment by BrittanyBunk** [comment]
@mekarpeles I think there's some misunderstandings on my volunteer repository idea. The staff (along with volunteer help) would do the PRs - but the volunteers would work out the github issue to a solution with providing insights to others through communication. I guess it's hard, because I tried it on discord with limited success, but I'm not an organization - so it might be different, idk. Idk what OL's needs are either. It's really important to have every volunteer's files in one place to say the least, so they can be utilized and issues organized to be tagged. That's my understanding. Maybe I'm missing something?
 
Also, I have absolutely 0 clue how to facilitate a meeting on special discussions. I don't see that written anywhere. Maybe I'm missing something, but if it's nowhere to be found, we can start there?
