### ISSUE TITLE
Deploy & Investigate whether olsystem deploys are correctly working

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6083]
@mekarpeles noticed the ol-web1 had an outdated etc/openlibrary.yml . This should have included the Dec 7th changes that update the ol-mem servers but didn't. What went wrong?

**Comment by mekarpeles** [comment]
Deploy went out yesterday and it looks like the import pipeline is still working. We'll see whether the partner bot runs on the ~15th and will re-open if it breaks.
