### ISSUE TITLE
volunteer github repository

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6084]
### Problem:
- there's a major issue of the openlibrary github on both sides - the staff and volunteers. Staff get either too many notifications or don't get notified
- Issues aren't being worked on, because there's an overload on staff
- volunteers are in waiting on their ideas and proposals
- volunteers can't communicate with each other in a way to get what they need done, so they either get lost or propose the same issue as someone else, out of not being informed
- the issues that staff need to work on get lost in the stream of volunteer information

**Bottom line:** the volunteer and staff github issues are mixed together in a way that's causing many problems: overwhelming, confusion, lack of delivery, duplication, etc.

Solution:
- a volunteer repository would allow for github issues that can be done by volunteers only without approval

How it would work is any issue that staff approve volunteers to work on themselves would be placed into the volunteer repository with a note in the staff repository that it's moved over there. Volunteers then would work on it themselves. When they're finished, they can close the issue - and then the OL staff can look at the closed issues to take it upon themselves when they feel like it to integrate it back to the OL to finish the job and implement it on the website, etc.

Limit:
- can cause confusion and duplication of work if there's two locations for github issues. However, this isn't going to be so much of an issue, because github issues can be closed and explained where they continued

Freedoms:
- volunteers are being given more tools and roles than ever, so it's really important and best that it's all in one place for everyone to use.
- this is where beta ideas can be launched and tested - we'd have a location where volunteers can go to for updates and the tools they need
- volunteers can place their files in a place that everyone can see and access

**Comment by BrittanyBunk** [comment]
expansion of #4366

**Comment by mekarpeles** [comment]
1. This is a volunteer repository
2. We do want there to be an approval process for contributing
3. gitter and slack are appropriate ways for members of the community to ask questions

There **is** definitely a problem with being updated when people ask questions + want to contribute on github +1

Right now, @tuminzee has volunteered to help us solve this problem by tagging us when volunteers express interest in taking on an issue.

Maybe the ideal solution would be a bot that adds a label automatically to the issue (like github marketplace / testcafe) -- see: https://github.com/apps/need-response-app.

For now, @tuminzee here's a task we'd love help with:
https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+created%3A%3E2022-01-17

Once a week, check this query (updating the date range) to check the most recently **updated/commented** issues and add a tag called `Needs: Response` and then the ABC team can add `Needs: Response` to our triage.

**Comment by mekarpeles** [comment]
we created:
1. a way to check for issues which needs responses: https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+comments%3A%3E1
2. A new tag called `Needs: Responses`
3. Added this process to our weekly ABC call

**Comment by BrittanyBunk** [comment]
@mekarpeles Thanks for the extra label. It means a lot that you're addressing a problem here.

Please don't let get in the way of this, so you can disregard the rest of what I say if we leave the situation there. 

However, sooner or later you'll need to create a volunteer repository. The problem is going to keep arising, as dedicating a person for notifying is a band-aid. Because I see a future with a volunteer 'only' repository, I'll address what's written.
1) This is not a dedicated volunteer repository. This is the open library's repository. If this was a volunteer repository, then OL staff wouldn't add in issues - and you add them all the time. What I refer to is a dedicated volunteer only repository.
2) I already mentioned the approval process for putting issues in there - unless you mean an approval process for the volunteer github - in which that's fine to wait on and to go ahead with that.
3) Slack is private and gitter doesn't organize issues like github, so if they worked, why do we have the problems we have now? BE I don't see how slack and gitter are the same as a repository, because they're insufficient in replacing github.

I don't see bots being able to solve this issue when a repository's needed.

The question isn't if, but when. This isn't my problem, so if it doesn't happen, it doesn't - I don't worry or care. I put the idea out there because the OL desperately needs it and a bot, person, label, or external forum won't replace that.
