### ISSUE TITLE
ImportBot importing non-covers

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6089]
Sometimes ImportBot imports placeholder covers. Can we check the url before importing the cover? These likely are all the same url.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/151876429-c108301b-7f9e-4851-b4c0-ddc5aa0e5bfa.png)

### Relevant url?
https://openlibrary.org/works/OL27276169W/The_Modern_Presidency

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
The relevant code should be here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L244

It seems like the image came from:
https://www.amazon.com/Modern-Presidency-Debates-Define-Institution/dp/0231206666

The url seems like it may change?
We're seeing: https://images-na.ssl-images-amazon.com/images/I/01RmK+J4pJL._BO1,204,203,200_.gif

We can remove the size info if we need to:
https://images-na.ssl-images-amazon.com/images/I/01RmK+J4pJL.gif

We may have to

**Comment by tuminzee** [comment]
I would like to work on this one

**Comment by tuminzee** [comment]
I was able to find one more product with no images 
https://www.amazon.com/Family-Drama-Stories-Delhi-Season/dp/B09QV94P8H/ref=sr_1_52?crid=31A13RN06YRDK&keywords=shashi&qid=1643898630&s=books&sprefix=shashi%2Cstripbooks-intl-ship%2C276&sr=1-52

If we compare url's of both the images.
https://images-na.ssl-images-amazon.com/images/I/01RmK+J4pJL.gif
https://m.media-amazon.com/images/I/01RmK+J4pJL.gif

Both are names '01RmK+J4pJL.gif'
although this data is not enough to put a static check.

**Comment by mekarpeles** [comment]
Go ahead! Unless @jimchamp had someone in mind.

**Comment by mekarpeles** [comment]
@b2pacific would you like to take this one?

**Comment by jimchamp** [comment]
I was planning on giving this to @b2pacific (if they are interested).  They are looking for issues focused on the back-end.  My projects are mostly front-end, so I thought this would be a good one.

**Comment by b2pacific** [comment]
@jimchamp I'll take this one. Thanks!

**Comment by jimchamp** [comment]
Thanks @b2pacific!  I'm fairly certain that we need to add a check to the cover URL in `load_data`, here: https://github.com/internetarchive/openlibrary/blob/177417cd6136abfef885a998255ee7c5df30f688/openlibrary/catalog/add_book/__init__.py#L578

Before `cover_id` is set in that function, we should ensure that the cover URL does not contain this string: `RmK+J4pJL`.
