### ISSUE TITLE
Solr should normalize ISBNs

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#609]
Currently, searches like `isbn:"978-84-00-04725-2"` yield no results because of the '-'. `isbn` is defined in the schema.xml file to be of type `string`, which means they are indexed and queried verbatim. They should probably have their own field type which handles these.

**Comment by LeadSongDog** [comment]
Duplicates #49 and related to #27 #142

**Comment by tfmorris** [comment]
There are ISBN and LCCN normalization filters for SOLR here:
https://github.com/mlibrary/umich_solr_library_filters

**Comment by tfmorris** [comment]
@LeadSongDog You said both dupe and not dupe at different times. I agree that #49 is a separate issue (data updates vs search).

This issue is very specific - indexing and searching for ISBNs. Let's not extend it to include all things ISBN related. Fixing the original issue, as framed by @cdrini, would provide useful benefit for the users.

**Comment by brad2014** [comment]
Is the fix going to be to (a) create a proper isbn normalization function (that accommodates isbn's with text in them, etc, as noted in #1194), (b) on setting an isbn, first normalizes it before storing it, and (c) on search, first normalizes it before searching?

If so, then we can close #49 as a duplicate.  If we don't solve the normalization issue, neither issue is resolved, and if we do, both of them are.

**Comment by cdrini** [comment]
The root cause of #49 might be this, but I have no clue what LC Bot is/does, so not certain.

The fix would basically be to update our solr config and do a full reindex, but we don't have a flow for a full reindex at the moment (that's what #1843 is working on). I'll rename it to "Solr should normalize ISBNs".

**Comment by hornc** [comment]
@cdrini Is still an issue? I didn't explicitly try to fix this issue, but I think some of recent work and refactoring around ISBN lookups, and search improvements to apply isbn conversions consistently may have fixed this.

Now when I do a category ALL search for `isbn:978-84-00-04725-2`

https://openlibrary.org/search?q=isbn:978-84-00-04725-2

I am redirected straight to https://openlibrary.org/books/OL3849512M/Hombres_y_documentos_de_la_filosofi%CC%81a_espan%CC%83ola  which shows that both hyphen stripping and isbn13<->isbn10 conversion is happening.

**Comment by cdrini** [comment]
Oh sweet! That's awesome! Hmmm; so when is the normalization process happening when you query for `isbn:978-84-00-04725-2`? in `work_search`?

**Comment by hornc** [comment]
@cdrini do you agree we can close this issue? I think the "fix" for this is what broke #2623 :)

**Comment by cdrini** [comment]
https://openlibrary.org/search?q=isbn%3A%22978-84-00-04725-2%22&mode=everything works! Looks done to me.

**Comment by cdrini** [comment]
(Note _technically_ this should be done on solr directly (not in the python); Solr actually has processors for ISBNs that handle all this stuff. But we can deal with it later; I'm content closing this)
