### ISSUE TITLE
Add "Lists" link to books page navbar

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6096]
### Describe the problem that you'd like solved

When visiting a books page, I have to scroll to nearly the bottom of the page to see the lists that contain the book.  It would be great if I could jump to that section by clicking a link on the navbar.

### Proposal & Constraints

Add a new link to the book page navbar that will jump to the "Lists containing this Book" section of the page.  A unique `id` will need to be added to that section.  Ensure that the new `id` is written in [kebab-case](https://en.wikipedia.org/wiki/Letter_case#Kebab_case), if necessary.

The text for the link should be "Lists", and it should be internationalized.  The new link should appear rightmost on the navbar.

**Comment by jimchamp** [comment]
@homewardgamer would you be interested in working on this?

**Comment by homewardgamer** [comment]
Yes @jimchamp  I would love to work on this Issue! Thanks for considering me.
