### ISSUE TITLE
Capture book page subject clicks with Google Analytics

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6106]
### Describe the problem that you'd like solved

In order to help guide our book page redesign, we would like to understand how patrons are interacting with our book page subject links.  More specifically, we'd like to know how often the subject links in the overview are clicked vs. the subject links in the work component, which is located below the fold.

### Proposal & Constraints

Five new analytics events will be created to measure subject link clicks.  In order to transmit these events to Google Analytics, we need to add a special data attribute with the correct event category and action to each subject tag.

The data attribute that we use for events is `data-ol-link-track`.  The values for this attribute are dependent on the subject link's location on the page:

- Subject links that appear above the editions table should have value `BookOverview|SubjectClick`
- Links in the work component (found below the editions table) with label "SUBJECTS" should have the value `WorkSection|SubjectClick`
- Links in the work component with label "PEOPLE" should have the value `WorkSection|SubjectPeopleClick`
- Links in the work component with label "PLACES" should have the value `WorkSection|SubjectPlacesClick`
- Links in the work component with label "TIMES" should have the value `WorkSection|SubjectTimesClick`

### Additional context

The `data-ol-link-track` attribute will need to be added to the anchor tag in this file: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/SubjectTags.html
A new parameter for the above template will likely be needed in order to identify if the link appears in the overview or the work component.

**Comment by tuminzee** [comment]
I would like to work on this issue

**Comment by jimchamp** [comment]
I want to see if @homewardgamer wants this one.  If not, I'll assign it to you, @tuminzee.

**Comment by tuminzee** [comment]
sure thing 🕺🏼

**Comment by homewardgamer** [comment]
> I want to see if @homewardgamer wants this one.  If not, I'll assign it to you, @tuminzee.

I would love to work on this Issue @jimchamp . In case I am struck I will surely ask for @tuminzee  help.

**Comment by tuminzee** [comment]
Yes @homewardgamer go ahead😊

**Comment by homewardgamer** [comment]
Hey @tuminzee, @jimchamp. I am getting an error while solving the PR.
The error is as follows
<img width="1099" alt="Screenshot 2022-02-10 at 9 37 00 AM" src="https://user-images.githubusercontent.com/73935799/153335225-e10b5494-e5b1-4a86-a193-3de6947c57e4.png">
These are the changes that I have done to the code.
https://github.com/homewardgamer/openlibrary/commit/f8093e9ff312bf09d693274f0b6ac9224c19eb2f
Kindly have a look and let me know what the Issue is.
