### ISSUE TITLE
Remove repeated edition description from book pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6107]
### Describe the problem that you'd like solved

If an edition has a description, we see this description twice on a book page: once above the fold, and again in the `#edition-details` component.  Displaying the same description twice on a single page offers little value to patrons.

### Proposal & Constraints

Remove the edition description from the `#edition-details` component.

### Additional context

Relevant code can be found in the book page template: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html

**Comment by tuminzee** [comment]
Thank you assigning the issue. I will finish it soon.
