### ISSUE TITLE
Duplicate identifiers on edit form

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6108]
Duplicate identifiers exist for the French National Library (Bibliotheque Nationale du France, BNF) and "Cornell University ecommons".

### Evidence / Screenshot (if possible)
<img width="577" alt="Screenshot 2022-02-04 at 13 44 29" src="https://user-images.githubusercontent.com/17739465/152531368-b1bc1d27-43cf-4e31-ba3b-535bd84f3957.png">
<img width="525" alt="Screenshot 2022-02-04 at 13 44 23" src="https://user-images.githubusercontent.com/17739465/152531372-2e23875b-0804-4f46-afbd-02ca98f5aab9.png">

### Relevant url?
[
](https://openlibrary.org/books/OL...M//edit)

### Steps to Reproduce

1. Go to ...any edition edit page
2. Do ...view identifiers

* Actual: The stated identifiers are listed twice.
* Expected: Each identifier should be listed only once.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by HamsterDeveloper** [comment]
on a similiar note: the identifier Deutsche National Bibliothek should actually be spelled Deutsche Nationalbibliothek

**Comment by onnotasler** [comment]
As a slight addition: Only one of the two entries for the BNF actually works.

At Bibliothèque Nationale de France, you can enter any number and it will be shown.
At Bibliothèque national de France (BnF), you cannot enter anything. Whatever you enter will simply vanish after clicking "add".

(The same problem occurs with the Amazon links too, by the way: I can only add amazon.com links, the other amazon-countries show no result.)

Also, it is not clear which identifier from the BNF is actually needed, they have two:
Identifiant de la notice : cb339844780 (I assume it is this one, but that is not clear - if it is, an (ark) behind the libraries name owuld clear this issue)
Notice n° :  FRBNF33984478 (If it is this one, I would suggest an (FRBNF) behind the libraries name.)

**Comment by tuminzee** [comment]
Thank you @onnotasler for your interaction :) 
it brings more clarity to this issue

**Comment by Freso** [comment]
I’m currently only seeing one of each. Has this been fixed? Are you still seeing this @seabelis (or anyone else)?
![Cornell University ecommons](https://github.com/user-attachments/assets/a52527a3-8a85-425f-b134-e46be3db5f4c)
![Bibliotheque Nationale du France](https://github.com/user-attachments/assets/57dd6d7a-fb49-462c-ac12-28f7f02b445d)

**Comment by onnotasler** [comment]
> I’m currently only seeing one of each. Has this been fixed?

This has been fixed in duplicate issues (7030 and 7825), and this one can be closed.
