### ISSUE TITLE
Add Homepage Onboarding Card: Fulltext Search

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6123]
Find a consistent graphic (e.g. thenounproject + create card in onboarding carousel which links to fulltext search endpoint https://openlibrary.org/search/inside (or to a page which has docs on fulltext search e.g. https://blog.openlibrary.org/2018/07/14/search-full-text-within-4m-books/)

Please post a screenshot or notes of your idea if you'd like to take this issue on on @tuminzee can help make sure you get assigned!

**Comment by MdSahil-oss** [comment]
@[mekarpeles](https://github.com/mekarpeles), would you like each searching result be:->

[Book Name](https://) by Author
["Toggle switch to show the few fulltext searching results of the Book on the same page"](http://)
-------if Toggle switch is clicked then:
------------few fulltext searching results
------------["another Link to see all fulltext results of the Book on another page"](http://)

Each searching result will be in separate card.

if you like it, so assign this issue to me or you can give some tips to me.

**Comment by tuminzee** [comment]
@MdSahil-oss how about you also post some graphics related to this one?

**Comment by mekarpeles** [comment]
I think the issue may need to be clarified. On the homepage, there is an Onboarding Carousel which looks like this:
![openlibrary org_ (18)](https://user-images.githubusercontent.com/978325/153305334-ab2940df-09ed-4032-a607-900332265142.png)

The solution is to add a new entry to the carousel, perhaps it could look like this:
![openlibrary org_ (19)](https://user-images.githubusercontent.com/978325/153305592-dc3e8f75-6121-4ccc-b93d-432bfc6cddc1.png)

The carousel item should advertise "Fulltext Search".

The example above uses this graphic from thenounproject: https://static.thenounproject.com/png/4582399-200.png

**Comment by tuminzee** [comment]
@MdSahil-oss would you like to work on it?

**Comment by MdSahil-oss** [comment]
@tuminzee I would like to work on it.

**Comment by MdSahil-oss** [comment]
@tuminzee assign this issue to me

**Comment by tuminzee** [comment]
I have assigned you the issue. Happy Contributing!
