### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get' in Want to Read list

### ISSUE THREAD

**Issue by roversch** [internetarchive/openlibrary#6126]
### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/1436556/152973912-818d4fea-b71f-40f5-a5bf-a9f88a327d9c.png)

### Relevant url?

https://openlibrary.org/people/josbos2817/books/want-to-read

### Steps to Reproduce

1. Go to [my 'Want to Read' list](https://openlibrary.org/people/josbos2817/books/want-to-read)

* Actual:  Page doesn't render correctly
* Expected: I can see my books. Note that I can see my 'Already Read' list without problems.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 96.0
- **Operating system?** Ubuntu 20.04.3
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Very sorry this is happening to your Reading Log! @cdrini mentions it looks like the records (which is a redirect) is getting editions attached to it by ImportBot which may be messing things up. 
https://openlibrary.org/works/OL1068165W.json

@cdrini reverted the work and it looks like your Reading Log is now fixed. We're making sure we have an issue to prevent this breakage in the future. Thank you!

#6145

**Comment by roversch** [comment]
Thank you!

**Comment by roversch** [comment]
Page 3 still seems to have a problem, however: https://openlibrary.org/people/josbos2817/books/want-to-read?page=3
