### ISSUE TITLE
List carousel does not work with Work IDs

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6130]
Creating a collection using the list carousel method does not work if the list contains Works.
### Relevant url?
https://openlibrary.org/collections/banned-challenged-in-schools?v=7

### Steps to Reproduce

1. Create a list carousel using a list containing Works, for example, https://openlibrary.org/people/agent-lisa/lists/OL205302L
2. Do ...notice error

* Actual: 
```
ListCarousel failed with error:
the JSON object must be str, bytes or bytearray, not NoneType
```
* Expected: Same behaviour as one get using a list containing only editions.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
Right now we're using editions instead of filtering seeds:
https://github.com/internetarchive/openlibrary/blob/a8e46e3af041ba824c32833165815c9af7cc35c4/openlibrary/plugins/openlibrary/lists.py#L330
