### ISSUE TITLE
"/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'get' (falling back to default template) Unable to render this page."

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6134]
Error when viewing some editions. May be solr related. It seems to happen with newer records. Maybe those that have not been indexed yet.
### Relevant url?

https://openlibrary.org/books/OL35552510M/Community-Based_Monitoring_in_the_Arctic?debug=true

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL35552510M
2. Do ...see error

* Actual: 
```
"/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'get' (falling back to default template)
Unable to render this page."
```
* Expected: no error.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by roversch** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/6126?
