### ISSUE TITLE
Error when rendering work page

### ISSUE THREAD

**Issue by KucharczykL** [internetarchive/openlibrary#6150]
When opening a work URL, an error is displayed and nothing renders except for the outer layout.
The error is:
```
/openlibrary/openlibrary/templates/type/work/view.html: error in processing template: AttributeError: 'description' (falling back to default template)
```

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/31072879/154090413-01526865-0208-4be5-8e39-96fabbafc503.png)

### Relevant url?
* https://openlibrary.org/works/OL18184289W/La_formule_pr%C3%A9f%C3%A9r%C3%A9e_du_professeur
* https://openlibrary.org/works/OL8140110W/Midnight_Tides

### Steps to Reproduce

1. Go to one of the URLs above
2. See error

* Actual: The page did not render.
* Expected: The page renders correctly.

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Chrome 98.0.4758.80 (Official Build) (64-bit)
- **Operating system?** Linux
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

N/A

**Comment by KucharczykL** [comment]
Hi @tuminzee, thank you for working on this! The first link is fixed but the second still gives me an error, though.

**Comment by jimchamp** [comment]
@KucharczykL the changes have not yet been deployed to production.  They are on our testing branch, though: https://testing.openlibrary.org/works/OL8140110W/Midnight_Tides

**Comment by KucharczykL** [comment]
@jimchamp Ah, I wasn't aware it's in the testing branch since the first link already started working. Sorry for the noise :)
