### ISSUE TITLE
Remove `by OpenStax` from all work & edition titles (`title_suggest:"by OpenStax"`)

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6152]
Subtask of #5792 

A lot of OpenStax works include "by OpenStax" in the title, creating for some silly looking records:

![image](https://user-images.githubusercontent.com/6251786/154116476-37c05250-2734-462e-b3d9-7751432a76c2.png)

Remove " by OpenStax" in a bulk script. This query will find all the results: https://openlibrary.org/search?q=title_suggest%3A"by+openstax"&mode=everything . Let's remove them from these works and from any of their editions that match.

## Stakeholders
@jimman2003

**Comment by cdrini** [comment]
Would you be interested in this one, @jimman2003 ?

**Comment by jimman2003** [comment]
Yeah. Seems well defined..

**Comment by jimman2003** [comment]
Done! Relavant code is here , last cell : https://colab.research.google.com/drive/1LBu0zPkDIrqZ-czW09Y6yzN9VbInEg0K?usp=sharing

**Comment by cdrini** [comment]
Confirmed no results now match the query, thanks @jimman2003 !
