### ISSUE TITLE
Include full url in "Report a problem" emails

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6153]
### Describe the problem that you'd like solved
Currently the "Report a problem" form sends the user's URL, but doesn't include any parameters. So staff only sees e.g. `/search` instead of `/search?q=harry+potter`. This makes it harder to debug issues.

### Additional context
Currently, the `Report a Problem` link in the footer includes the path, but not the parameters!

Related code:
- The link in the footer: https://github.com/internetarchive/openlibrary/blob/8a1e17358c107e665bc653b689c3f50fb329f2c2/openlibrary/templates/lib/nav_foot.html#L44
- The spot this parameter is passed to the support form: https://github.com/internetarchive/openlibrary/blob/8a1e17358c107e665bc653b689c3f50fb329f2c2/openlibrary/templates/support.html#L54-L56
- The form's post endpoint: https://github.com/internetarchive/openlibrary/blob/39962157c12465d050e43458444aba9a59661c8d/openlibrary/plugins/openlibrary/support.py#L65

### Stakeholders
@seabelis

**Comment by Hitansh-Shah** [comment]
@cdrini I could give this a try. Can I work on it?
