### ISSUE TITLE
Editions table doesn't always include entry for the page's book

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6154]
A recent change to the book page editions table has caused the table to render without the current page's edition in some instances (mainly, if we do not have an ebook for the edition).  We want to ensure that the current page's edition is the first item in the list, and that it has the class `highlight`.

### Evidence / Screenshot (if possible)
![Screenshot from 2022-02-15 19-26-44](https://user-images.githubusercontent.com/28732543/154172972-c4eb7a0d-d538-4f6e-a19f-2a6478df12e6.png)

_Default editions table entries on page of book with no OCAID_

![Screenshot from 2022-02-15 19-28-23](https://user-images.githubusercontent.com/28732543/154173121-6c0e0317-c308-43b9-894a-d81053a8d8b1.png)

_Table for the same page when all editions are displayed.  Note that the first entry is highlighted._

### Relevant url?

https://openlibrary.org/books/OL13561340M/Ovid's_Epistles

### Steps to Reproduce

1. Go to the above-listed page.
2. Observe the editions table.

* Actual: Book with OLID `OL13561340M` is not in the editions table.
* Expected: Book with OLID `OL13561340M` is the first entry in the table, and the entry is highlighted.

### Details

- **Logged in (Y/N)?** N/A
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The editions table is ultimately populated with the results of the `Work.get_sorted_editions` method, here:
https://github.com/internetarchive/openlibrary/blob/942a5b1b27dd888f8d33e99247414fffc655c6c7/openlibrary/plugins/upstream/models.py#L721 

When `ebooks_only` is true, we should ensure that the current edition is in the list of editions.  If this proves to be too difficult, the current edition can be prepended to the list in the book page template.  The editions list is set here:
https://github.com/internetarchive/openlibrary/blob/942a5b1b27dd888f8d33e99247414fffc655c6c7/openlibrary/templates/type/edition/view.html#L27

**Comment by b2pacific** [comment]
This looks like a good issue for me. Can I you assign this to me @jimchamp ??

**Comment by jimchamp** [comment]
Thanks @b2pacific!  I should mention an edge case that you may not be aware of.  Sometimes there are works that have no associated editions.  These are called orphaned works.  In the case of an orphaned work, the editions table is displayed with a message saying that there are no editions.  I'm not sure if this information will be useful to you as you work on this, but it's good to know regardless.

**Comment by tuminzee** [comment]
Hello @b2pacific I hope you are doing good.
I want to know if you were able to solve the edge case which @jimchamp mentioned [here](https://github.com/internetarchive/openlibrary/issues/6154#issuecomment-1043759830) 

Also I would like to appreciate your time and efforts
Happy Contributing 🕺🏼

**Comment by jimchamp** [comment]
It looks like this was solved recently, likely in one of the PRs related to the `get_sorted_editions` function.
