### ISSUE TITLE
Reading Log json endpoint "already-ready" broken

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6165]
### Evidence / Screenshot (if possible)

https://openlibrary.org/people/mekBot/books/already-read.json?debug=true

Line 62 should probably be something like

```
'author_keys': [a.author.get("key") for a in w.get('authors', []) if a.author], 
```

instead of 

```
'author_keys': [a.author.key for a in w.get('authors', [])], 
```

in openlibrary/openlibrary/plugins/upstream/mybooks.py

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by MdSahil-oss** [comment]
@mekarpeles  I would like to work on it.

**Comment by cdrini** [comment]
This appears to no longer be an issue
