### ISSUE TITLE
Comprehensive Apple IPSW collection

### ISSUE THREAD

**Issue by rickmark** [internetarchive/openlibrary#6167]
To facilitate good quality security research a collection of all published Apple IPSWs must be maintained.  Apple from time to time leaks valuable data, but once these IPSWs are furnished, they loose the ability to claim "trade secret" on the contents.  The collection is a massive amount of data, and there are silos of this information:

- https://www.theiphonewiki.org
- https://docs.hackdiffe.rent
- https://data.nicolas17.xyz/ipsw-torrents/

Currently archive.org has 44 IPSWs but we'd like to extend this to a comprehensive index.

### Describe the problem that you'd like solved
A full listing of any Apple IPSW ever released publicly - withstanding when Apple "yanks" older IPSWs

### Proposal & Constraints
Ingest IPSW feeds and Assets listed in : https://docs.hackdiffe.rent/.data/mobile_assets.json

### Additional context
It should be reviewed that there is no legal prohibition against archiving publicly released IPSWs

### Stakeholders
Generally the interested parties discuss such things at: https://discord.gg/hackdifferent - part of the https://hackdiffe.rent community.

**Comment by tfmorris** [comment]
Are they books? That's what OpenLibrary catalogs. If you're looking for the Internet Archive or Wayback Machine, that's a different thing.

**Comment by rickmark** [comment]
Sorry for some reason ‘archive.org’ expressly links to this repo, historical reasons?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mekarpeles** [comment]
I think emailing info@archive.org is the right thing to do! Apologies for the inconvenience @rickmark.
