### ISSUE TITLE
Collapsible table of contents on book pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6171]
### Describe the problem that you'd like solved

When present, the table of contents can take up a lot of vertical space in our book pages:

![Screenshot from 2022-02-22 14-49-23](https://user-images.githubusercontent.com/28732543/155208114-59e64549-0dbc-4426-a6f8-c59b9896df3f.png)

### Proposal & Constraints

Make the table of contents section collapsible.  The table of contents should be collapsed on page load. Ensure that the change does not negatively affect the book page's accessibility score.

**Comment by MdSahil-oss** [comment]
@jimchamp I'd like to work on this issue.

**Comment by jimchamp** [comment]
Go for it!  We have code for collapsing `div`s that can probably be reused here.  You can see how we've set it up for our book page subject tags, here:
https://github.com/internetarchive/openlibrary/blob/5d94aa93edf7f5d8f438751bb2b9d64b5a4cdaea/openlibrary/templates/type/edition/view.html#L222-L227

`S:macros.ReadMore` refers to https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/ReadMore.html

There is also a JS file for the collapse/expand functionality: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/readmore.js

**Comment by MdSahil-oss** [comment]
@jimchamp would you like to share the path from where you got above shown image. that will help me a lot to target the file where i need to perform changes

**Comment by jimchamp** [comment]
Here's a link to the page with the pictured table: https://openlibrary.org/books/OL8811476M/Generation_Hex#edition-details

Here is a recent pull request that makes work descriptions collapsible: https://github.com/internetarchive/openlibrary/pull/6243

**Comment by mekarpeles** [comment]
@MdSahil-oss I believe just by adding a class of `restricted-view` to the table of contents, it will automatically because hidable/showable.

Here's the code which generates the table of contents
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/TableOfContents.html

**Comment by jimchamp** [comment]
> @MdSahil-oss I believe just by adding a class of `restricted-view` to the table of contents, it will automatically because hidable/showable.

This restricts the height, but does not give patrons the option to expand.  Assigning myself, as there has been no contact from @MdSahil-oss, and this is on my milestone.
