### ISSUE TITLE
Collapsible work descriptions

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6172]
### Describe the problem that you'd like solved

Work descriptions found in the `.work-info` section of our book pages can take up a lot of vertical space.

### Proposal & Constraints

Make these work descriptions collapsible.  These descriptions should be collapsed on page load.  Ensure that the changes do not negatively affect our book page accessibility score.

**Comment by BrittanyBunk** [comment]
good idea - we have that for editions, why not works?
