### ISSUE TITLE
Error when trying to add edition to wait list

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6184]
Patron sees error message when adding item to wait list. The item is successfully added, but the error makes it appear as if it has not been.
### Relevant url?

https://openlibrary.org/books/OL25086706M/Shadow_and_Bone
### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL25086706M/Shadow_and_Bone
2. Do ...Add to wait list.

* Actual: /openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: TypeError: %d format: a number is required, not NoneType (falling back to default template)
* Expected: Wait list confirmation.

### Details

- **Logged in (Y/N)?**y
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by jimchamp** [comment]
Opened a PR which corrects the rendering issue, but does not address the underlying problem (outlined in PR).
