### ISSUE TITLE
Trending Books Carousel

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6186]
## Background

For #6014 we created a new Trending page https://openlibrary.org/trending ([code](https://github.com/internetarchive/openlibrary/blob/a67cedf3dcdb417b7980c034984d8f85ad2a9cc3/openlibrary/views/loanstats.py)] and several APIs changes to enable us to query for the most recently logged books (i.e. those added to e.g. one's Want to Read list).

## Goal

The objective of this github issue is to adapt and enhance these APIs (with pagination support) so we can show a Trending or Activity carousel on the homepage.

## Steps

1. Update the `get_most_logged_books` API to allow for an `offset` parameter (to compliment the existing `limit` parameter) https://github.com/internetarchive/openlibrary/blob/a67cedf3dcdb417b7980c034984d8f85ad2a9cc3/openlibrary/views/loanstats.py#L40-L54. This will allow us to load additional pages of results for the carousel.
2. We need to add a new API endpoint to plugins/openlibrary/api.py for getting the `most_logged_books` which takes a `limit` (default 20, max 100), `offset` (default 0), and `since_days` (default 1) which returns json of books.
3. Using the `QueryCarousel` as a template https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/QueryCarousel.html create a new macro called a macros/ModelCarousel.html which uses a database model (such as ratings or reading logs). This will call `get_most_logged_books(since_days=7, limit=20, offset=0)` and a `load_more` which in
4. Update the homepage template https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html#L22 to include a call to `ModelCarousel` which will show a carousel of the most recently logged books.

## Notes

Closes #6147

**Comment by MdSahil-oss** [comment]
@mekarpeles I'm beginner at openlibrary but i have enough development skills to work on enhancement/issue like this so if possible so assign this issue to me, i would like to work on it.

**Comment by mekarpeles** [comment]
## Background

Currently, the homepage carousels are powered by
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html#L39

```
$:render_template("home/custom_ia_carousel", title=_('Books We Love'), key="staff_picks", query='languageSorter:("English")', subject="openlibrary_staff_picks", sorts=["lending___last_browse desc"], limit=18, test=test)
```

Which under the hood calls:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/custom_carousel.html

## Step 1

The solution will be to add a new carousel to the templates/home/index.html which looks like:

```
$:render_template("books/custom_carousel", books, title=title, url=url, key=key, min_books=min_books, load_more={"url": load_more_url, "mode": "page", "limit": limit}, test=test, compact_mode=compact_mode)
```

The `books` variable will need to be replaced with a `public` function which is capable of fetching trending books.

Such a function exists here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/views/loanstats.py#L40-L54
We'll need to import `from infogami.utils.view import public` add a `@public` decorator above line 40 so this function can be called from within our html templating language

This will accomplish the first half of what we need -- it will produce a carousel on the homepage with 20 trending books.

## Step 2

Eventually, in order to configure the carousel to dynamically load more pages, we'll need to create a new API to fetch more trending books and pass this url in as `load_more_url`.

An example of such a `load_more` API is openlibrary.org/browse.json which is defined in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/api.py#L64-L89.

We may wish to extend this `browse.json` endpoint to include a `trending` flag like:

```
        i = web.input(
            q='', page=1, limit=100, subject='', work_id='', _type='', sorts='', trending=False
        )
        if i.trending:
            get_most_logged_books(...)
```

But this will require one final step because `get_most_logged_books` currently only returns the first limit (e.g. 20) books. We want to update this function so it can take a limit and a page number, e.g. `get_most_logged_books(limit=20, page=2). This requires us to update the function beneath get_most_logged_books which is called most_logged_books in order to not only have a limit and since but to also have an offset (where the offset will basically be the `limit * page`
https://github.com/internetarchive/openlibrary/blob/07f80c5a8d1c402d4d20d278662a65cf09b5dd8d/openlibrary/core/bookshelves.py#L79-L98

**Comment by dbouris** [comment]
hi @mekarpeles, me and @Philippos01 would like to work on that if possible!
