### ISSUE TITLE
speed up page loading of editions

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6195]
problems:

- editions page gets overloaded with content
- it's too hard to load

Solution (my idea):

- move the edition list to the works page
- then if people want to see more editions, the link will take them there

stakeholders
@seabelis @mekarpeles @cdrini - what do you all think?

**Comment by BrittanyBunk** [comment]
please if you move the editions to works - these're the tabs I'd like to see - 'show':
- first 5
- only ebooks
- all

**Comment by BrittanyBunk** [comment]
avoid loading covers, just words
![image](https://user-images.githubusercontent.com/55302685/156247435-8477163d-6948-4456-9f17-150109fe8938.png)

**Comment by BrittanyBunk** [comment]
see rest of documentation https://docs.google.com/document/d/1LEbzsLZ1F9_YIQOoZzO7GoZnG1z-rudhZ9HNtsameTc/edit# under 3-1-22

**Comment by BrittanyBunk** [comment]
*My idea was to bring the editions to the work page (related to github #2823)
  - Lisa said it looked like that before
     * Mek said that the issue with that is that
       - when people had to click on an edition, they’d need to go back to the works page to find the next edition - and that was too many steps
         * I agree - I was one of the people who complained about this
           - My proposal: have in both places
             * Issues
               - Overcomplicating
                 * Solve by overview tab as default on editions pages
               - Not needed - works page getting removed
       - There’s too many editions to look through, which is confusing to know the right one
         * Proposal: organize by text, not cover - see image in github #6195
* Issue: variations are mixed in with the layers of editions
  - Examples 
     * [Printings](https://www.travelinlibrarian.info/writing/editions/) - shown by 1 2 3 4 5 on the copyright page inside book
       - States - variations in printings
     * designations - same isbn, but different cover - like this [9th edition](https://pictures.abebooks.com/isbn/9780130669971-us.jpg), can also have a [badge](https://images-na.ssl-images-amazon.com/images/I/516aANUjYtL._SX218_BO1,204,203,200_QL40_ML2_.jpg) or going on the NYT bestseller list
       - needs a sub-subtitle field under subtitle when editing
     * media formats - paperback, hardcover
     * Translation, transcription, transliteration - github #6041
  - Lisa wants everything at the edition level - github #2751
     * My proposal: levels - universe -> series (replaces works) -> editions -> variations (which might have multiple levels)
       - Reason - too many editions at the editions level
         * Causing - confusion - in terms of finding the right edition (especially if they’re all the same edition)
         * Making editions pages hard to load
       - Issues - Drini 
         * talked about overcomplicating the system
           - where it can become unusable if there’s too many details
             * Problem: it’s already overcomplicated, but frustrating too - we need better
             * Another benefit is having everything there - which is the point of the OL in the first place! - this keeps people like me from going crazy thinking a book doesn’t exist when it does
         * Brought up [FRBR](https://www.loc.gov/catdir/cpso/frbreng.pdf) (page 6 is something I heard Mek bring up many times)
           - I personally think FRBR has complicated matters and we need better- due to
             * terminology not understood by the average person
             * unnecessary, unhelpful organizational structure

**Comment by mekarpeles** [comment]
Our recent deployment made it so a max of 10 editions is show by default, prioritizing ebooks and the performance of e.g. Pride & Prejudice went down from ~40s to 3s. There are other performance issues we want/need to solve, I believe we have issues for these (e.g. Edition-level search should help the get_sorted_editions call to choose the best book and also async editions table will help. Finally, this month on our ABC call, we talked about cleaning up some of our old/deprecated/expensive Lending checks which are no longer needed @jimchamp)
