### ISSUE TITLE
Bot/Action: Automatically Propose Whitespace Removal if CI Fails

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6197]
Almost every PR I review has failing issues with whitespace.

![github com_internetarchive_openlibrary_runs_5272715227_check_suite_focus=true](https://user-images.githubusercontent.com/978325/155902270-5c920e58-d9b1-48b5-8901-7c0156dbfb11.png)

![github com_internetarchive_openlibrary_runs_5272715227_check_suite_focus=true (1)](https://user-images.githubusercontent.com/978325/155902268-66710026-ab55-4f80-b845-e32e702aee94.png)

### Describe the problem that you'd like solved

Install or create some bot/action which automatically fixes or proposes/suggests whitespace removal to a PR.

**Comment by cclauss** [comment]
Just `git commit` again and it should pass because the trailing-whitespace job has already corrected the code.
