### ISSUE TITLE
User Reviews vulnerable to upload of abusive content.

### ISSUE THREAD

**Issue by dmullis** [internetarchive/openlibrary#6203]
Abusive rant found posted as a "review", to earlier legitimate book upload.

### Evidence / Screenshot (if possible)
_Reviewer: [ICnothing](https://archive.org/details/%40icnothing) - - February 17, 2022
Subject: What about the J question?
Kicked out of 109 different nations,_ ... remainder of rant elided

### Relevant url?
https://archive.org/details/WhyNationsFailTheOriginsODaronAcemoglu#reviews

### Steps to Reproduce
Search book titles for "Why Nations Fail", click on first matching thumbnail.

### Proposal & Constraints
1. Disable further review uploads, pending implementation of better controls.
2. Consider strategies for culling existing abusive "Reviews".  Existing content search UI seems to lack visibility into Review content or metadata: https://archive.org/advancedsearch.php
3. Consider strategies for review vetting e.g. add a "flag review" checkbox; extend trust to a pool or tree of moderators.  Hate speech is typically encoded with abbreviations or "dog whistles", so content-based filtering likely to remain impractical.
4. Consider strategies for managing known abusive users e.g. shadow ban.

### Related files
https://github.com/internetarchive/openlibrary/blob/39962157c12465d050e43458444aba9a59661c8d/openlibrary/core/observations.py

**Comment by mekarpeles** [comment]
This is on Archive.org, cc; @JeffKaplan @bfalling @seabelis 

Closing as not relevant to openlibrary.org -- however, agreed! This is presently why we implemented the https://blog.openlibrary.org/2021/08/20/introducing-community-reviews/ the way we did
