### ISSUE TITLE
Users asking for their borrow history

### ISSUE THREAD

**Issue by JeffKaplan** [internetarchive/openlibrary#621]
Users are asking to see their borrow history on Open Library, you can currently do this on archive.org and so this is where I have been sending users.

Maybe there's a way to get this info from archive.org APIs?

**Comment by salman-bhai** [comment]
Is this Issue fixed with Open Library Public Reading Log?

**Comment by mekarpeles** [comment]
@salman-bhai no -- if available, we should be pulling their reading history from archive.org and displaying on openlibrary (or at very least including a link to archive.org where the user can view their history, which probably makes more sense)

cc stakeholders: @jimbonator, @bfalling

**Comment by mekarpeles** [comment]
For now as a stop-gap, I think we should be linking to their archive.org account borrow history page, e.g.:

https://archive.org/details/@mekarpeles&tab=loans#loans-history

**Comment by guyjeangilles** [comment]
Assigning jdlrobson (not tagging as request) per slack discussions since this is front end related.

**Comment by LeadSongDog** [comment]
@JeffKaplan @mekarpeles  @guyjeangilles 
This issue should raise potential privacy questions on both platforms. Before exposing the log, we need to be extra sure that the request is from the user themselves, and not (for instance) an abusive partner, prospective employer, etc. with access to their password. At minimum a confirmation email would be in order, if not full 2-factor.

**Comment by mekarpeles** [comment]
Can we add a link to their https://openlibrary.org/account/loans page which goes to:
https://archive.org/account/?tab=loans#loans-history ?
