### ISSUE TITLE
post-meeting notes

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#6219]
### Problem:
- the community notes are for the notes during the meeting
- notes that're after the meeting take up too much space (see my post-meeting notes on 3-2-22) - clogs it

### Solution:
- post-meeting notes document - write as much as needed to fill people in

### Benefit:
- people get informed as to what happened in the meeting
- records everything - reference

### Bad:
- too many documents - hard to find
- can put everything on the community notes

### Discussion:
- should we put all the post meeting notes on the community meeting page or start a new document for them?

**Comment by mekarpeles** [comment]
As you asking for a summary of each meeting? I don't think staff has the bandwidth for this and it's not clear where we'd put it.

If folks want to add a new section after Open Mic to our meeting notes (such as "Post-Meeting") that sounds fine to me!
