### ISSUE TITLE
Make editions searchable and filterable by different parameters

### ISSUE THREAD

**Issue by jollygreenegiant** [internetarchive/openlibrary#6226]
I'm the developer of a reading tracking app on Android called [Luna Reading Tracker](https://play.google.com/store/apps/details?id=com.jggdevelopment.bookbuddy).  And I'm looking into switching over to OpenLibrary as the app's data source.

Open Library by far has the most comprehensive information of any book API I've found (with the possible exception of Google Books, but they prohibit monetization), and I'd like to switch to OL, but I'm struggling with the text search feature for my app.  Users can use my app search for books, usually by title (although I'd like to add filters for author and other things), and expect a list of books that match the given search.

The problem I'm running into is that the Open Library returns Works rather than editions, which works for my use case sometimes, but not always.  For example, a search for "harry potter" returns all seven books as Works, but if my user were to click on a work, there's not a way that I can find to figure out which edition to send them to without picking one arbitrarily.  This also presents  a problem when the user searches in a language other than the original published language of the book, because the Work that is returned is always in the original language.  As far as I can tell, there isn't a way to retrieve only the editions of a Work that are in a specific language.

### Describe the problem that you'd like solved
I would like a way to search with the API in such a way that it returns the most relevant editions for a particular search.  So a search for "harry potter" with the language specified as English would return a single English edition of each of the seven books as the top seven results, maybe the most relevant, popular, or recent edition for each?

Same goes for searching in languages that differ from the Work's native language.  For example, if a user searches for "Harry Potter y la piedra filosofal" (the spanish translation of HP book 1), the correct Work comes up, but the title is in English, and the editions field of the API response shows every edition in every language, even if you specify the language.  I assume it brings up any work with an edition in that language, rather than only the editions that are in that language.  I'd like to have a way for me to filter the editions that are returned by language.

### Proposal & Constraints

Some sort of editions search endpoint that works similarly to the book search endpoint, where you can specify a query and parameters (title, author, language, etc), but where the response is specific editions of the Work that are relevant to the search.

Examples:

**Endpoint (approximately):** "/edition_search.json?title=harry+potter&language=eng"
**Expected Results: ** I would expect the first seven results to be the seven Harry Potter Works, with each result being a relevant English-language edition of the work, so in this case, probably the most popular edition of each book, so that the cover image is recognizable and the title is what the user would expect.

**Endpoint (approximately):** "/edition_search.json?title=harry+potter&language=spa"
**Expected Results: ** Same as above, but with Spanish-language only results.  This should only return an edition of a Work if that edition is in Spanish.  So if only books 1-6 had been translated to Spanish, I would expect this to return six results, and not book 7.  As with the last example, these would be Spanish-language editions of the works, so the cover images and titles would be in Spanish.

**Endpoint (approximately):** "/edition_search.json?title=harry+potter+and+the+goblet+of+fire&language=spa"
**Expected Results: ** This should return no results because there are no Spanish-language editions with that title (I assume), since it is in English.

### Additional context
Here is an example of my app's search screen to give some context into the kind of information I'm displaying.  This info is pulled from the IsbnDb API, not OpenLibrary.

![device-2022-03-03-093423](https://user-images.githubusercontent.com/25214257/156585825-f38ab656-cd7b-4cdb-8db9-c3fa816b5025.png)

Happy to provide additional context if needed, I will be actively tracking this issue.  Thank you!

**Comment by jollygreenegiant** [comment]
@cdrini just wanted to bump this and see if you need anything else from me to be able to triage this.  Happy to provide more info if needed.

**Comment by cdrini** [comment]
Hi @jollygreenegiant ! Sorry for the delay; this is _exactly_ (to the T :P) What I've been working on this past quarter :) We're calling it "editions in solr" (solr is our search engine). It's still in development/we're still working out kinks, but we're going to be putting it up on testing.openlibrary.org this week to see how it performs!

This PR has the work in progress code: #6119 . My apologies I don't have my notes super well organized publicly somewhere.

It would work on the existing search endpoint, but would include an `editions` field that would have information about the edition(s) that best match the user's query. For example if a user searches for `language:fre`, then we would show the French editions only in the `editions` field.

**Comment by jollygreenegiant** [comment]
No worries, thanks for the quick response!  I'm glad this is getting such strong attention, it would be a game-changer for my use case.  If you have the time, I'd love a ping when the new endpoint is available so I can start working with it and seeing how it would integrate into my app.  Thanks again for all the effort on this!

**Comment by cdrini** [comment]
I created #6377 to keep a log of progress on editions in solr :+1:

**Comment by jollygreenegiant** [comment]
@cdrini this looks awesome, it's exactly what I was looking for!  

The only thing that I notice is missing is a description of the edition.  The work itself has one in the original published language (English in the case of the Harry Potter books), but the Spanish editions don't have a Spanish description, for example.  If that's a piece of data that's available, I'd love to have access to it, since that's the only other major piece of text I show in the app outside of the title.

It looks like the OpenLibrary web page for the Spanish-language editions have English descriptions, so maybe that just isn't data that's available for most books, but I wanted to mention it.

I tried this briefly with a couple basic searches, different languages, and pagination, and it seems to be exactly what I was looking for.  I really appreciate your work on this - when it's ready, it will be a huge improvement to my app both for me as a dev and for my users' search experience.

**Comment by cdrini** [comment]
Sweet! Description isn't in our search engine I'm afraid so you'll need to do a separate fetch for it. You could fetch the matching edition's description with this url: http://openlibrary.org/books/OL22723514M.json :/

The UI page for the book shows the edition's description if the edition has one, otherwise it falls back to the work's description (which is usually in English).

(Oh, also in case it's useful, we do have this endpoint if you want to search editions; but it doesn't support any text processing like our search engine. It's lower-level, and will just let you search the direct fields of the records. Eg http://openlibrary.org/query.json?type=/type/edition&works=/works/OL82537W&languages=/languages/fre&*= )

**Comment by cdrini** [comment]
This is now fixed! You can do a search like this: https://openlibrary.org/search.json?q=harry%20potter&mode=everything&fields=key,title,editions&lang=fr to get back results, _preferring_ French results, but not _requiring_ French results. This is now powering the main search on Open Library :) Please let me know if this meets your requirements, @jollygreenegiant !

Note: https://openlibrary.org/search?q=harry%20potter%20and%20the%20goblet%20of%20fire&mode=everything&fields=key,title,editions&lang=fr Will _prefer_ but not require French. if you want to _require_ French, add `language:fre` in the query.

**Comment by jollygreenegiant** [comment]
This is exactly what I need - thank you so much for all the work on this!!

**Comment by 404-html** [comment]
@cdrini Mery Christmas and thank you very much for this change! 🙌 
I played with the `editions` field a bit and I noticed that `docs` collection under `editions` always have only one element, example:
https://openlibrary.org/search.json?q=black%20swan&fields=key,title,editions

Response:
```json
{
  "numFound": 1794,
  "start": 0,
  "numFoundExact": true,
  "docs": [
    {
      "key": "/works/OL8070930W",
      "title": "The black swan",
      "editions": {
        "numFound": 7,
        "start": 0,
        "numFoundExact": true,
        "docs": [
          {
            "key": "/books/OL6274386M",
            "title": "The black swan"
          }
        ]
      }
    },
    ...
  ]
}
```

`numFound` indicates there's 7 editions, we can see them listed on https://openlibrary.org/works/OL8070930W/The_black_swan but the JSON response contains only one of them.

Is there any way to get all editions listed?
Let me know please if I should raise separated issie.
