### ISSUE TITLE
Docs: Update "Quick Start for OpenLibrary's developers"

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#6227]
I'm always frustrated when I hear that new contributors are unsure how to set up to make their first commit.

### https://github.com/internetarchive/openlibrary/wiki/Getting-Started needs an update!
* [ ] Setup of development tools including Docker
* [ ] Setup of testing tools 
* [ ] Setup of pre-commit hooks
* [ ] Making your first commit

**Comment by agmckee** [comment]
I think possibly of greater concern at present is the time for pull requests to be reviewed, and to be deployed. As a relatively recent new contributor to Open Library (although I've been a user and previously tried to get involved as a developer a decade ago) I was surprised for how long it took to see the approved and merged changes to actually end up in a deployment. Another PR of mine is currently awaiting review and has been for months (not a complaint, I understand how much time it takes and that other work takes priority). Fast feedback is quite important in keeping new contributors around and actively contributing. People start developing for various reasons but it is likely, I think, that many will be trying to fix issues that affect them personally. As such they generally welcome knowing whether or not their PR is likely to be welcome and wanted, when it is likely to get deployed to production should it be accepted, how to avoid their PR being declined (i.e. how to avoid wasting their time - should changes be minimal, should they refrain from modifying certain types of code e.g. models, should they modify tests in the same PR or commit as modifying the tested code).

FWIW I didn't find the documentation _that_ out of date, although obviously some things definitely are. I do a lot of experience getting up to speed with undocumented codebases, however, so my view might not be typical. However all documentation decays, and the livelier the development the more likely the documentation will be somewhat out of date. This isn't necessarily a blocker to new developers onboarding provided there's a reasonable starting point for common issues and some people in the community available to help other devs get up to speed. I've tried to help a few people in various issues and discussions.

**Comment by mekarpeles** [comment]
Thank you @agmckee. We can definitely do better about communicating when releases will happen and getting back to contributors with reviews. We're aiming for weekly or biweekly deploys on Tuesdays.

@cclauss I've added a link from the old documentation https://github.com/internetarchive/openlibrary/wiki/Getting-Started to our new documentation (at the top).
