### ISSUE TITLE
Author Pages: Fix ebooks-only pagination

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#623]
If mode=ebooks is active in localStorage, on the *backend* we should filter OL solr results using the availability v2 API before returning them to the user and adjust pagination accordingly.

**Comment by mekarpeles** [comment]
1) Get a list of *all* work_keys by this author from Open Library solr
2) Pass the list of openlibrary_work IDs to archive.org availability v2 API to get a list of which of these books is readable/borrowable (disregard the actual availability status --  Availability API will automatically be triggered on each *page* of results in either case)
3) Cache this result as a function call, e.g. get_author_readable_works for 1 day
4) Use this as the basis to query for Author's books when mode=ebooks selected, otherwise, use existing logic.

cc: @rajbot; you had mentioned looking into this (just fyi)

**Comment by mekarpeles** [comment]
This only works because I imagine there aren't many authors with > 1,000 works. But keep in mind the Archive.org availability v2 API has a hard limit of 1000 work_id csvs
e.g. https://archive.org/services/availability/?openlibrary_work=OL362705W,...

**Comment by mekarpeles** [comment]
Also, note this won't work for search results or subjects as there are very likely to be far more than 1,000 results.

**Comment by guyjeangilles** [comment]
I think this relates to #2177 and #556 

Also, @mekarpeles It looks like you've thought about how to implement a solution to this issue, are you willing to be assignee? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on context: let me know your thoughts

**Comment by tfmorris** [comment]
The proposed solution seems computationally expensive. 

Isn't the existence of an IA ID (aka ocaid) a good proxy for whether a digital edition exists?
