### ISSUE TITLE
Bug report 

### ISSUE THREAD

**Issue by MdSahil-oss** [internetarchive/openlibrary#6252]
web layout is not well rendered.
### Evidence / Screenshot (if possible)
Here is the screenshot :- https://drive.google.com/file/d/1cPxVEzd8G4vwR4sjvNRIGQDwh5VGGTkc/view?usp=sharing

### Steps to Reproduce

1. Open the openLibrary web locally on your machine or on Gitpod.
2. You will see above mentioned bug on top of the page.

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
This is a problem with the css/js not getting rebuilt correctly which will be fixed once we do our next deploy tomorrow.

css/js is outdated until deploys
