### ISSUE TITLE
Remove DELETE button from bottom of edition edit form, activate DELETE button at the top of the form

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6272]
There are two DELETE buttons on the book edit form. One at the bottom, which is sometimes mistaken as the SAVE button, and one at the top of the form, which currently does nothing.
### Relevant url?

https://openlibrary.org/books/OL...M/edit
### Steps to Reproduce

1. Go to ...any edition edit form
2. Do ...notice the two DELETE buttons

* Actual:multiple delete buttons, one of which does not work
* Expected:a single delete button, at the top of the page, that deletes the record when clicked

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by LeadSongDog** [comment]
Related #4101
