### ISSUE TITLE
Warning field for works

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6285]
I think it would be cool to have a warning field for works because some people may not want to read books with topics that they consider inappropriate. In my view, it should be something like subjects field but without possibility to create new values for casual users.
Some possible warning: cursing words, violence, rape, sexual scenes etc
There also should be possibility to exclude books from search results if it has certain warning (not sure whether it's possible to exclude subjects)

**Comment by mekarpeles** [comment]
We currently do have Community Reviews https://blog.openlibrary.org/2021/08/20/introducing-community-reviews/ which allows patrons to identify books which have content warnings. We could make this more visible on other parts of the page as well

**Comment by bicolino34** [comment]
@mekarpeles I don't think it's possible to exclude books with certain content warning from search results, is it?
