### ISSUE TITLE
Books page navbar hidden behind header in mobile

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6288]
In mobile views, the stickied navbar is obstructed by the mobile header.

### Evidence / Screenshot (if possible)

![Screenshot from 2022-03-14 16-34-35](https://user-images.githubusercontent.com/28732543/158257064-51ad1326-58ab-4e11-912e-b33f8949243d.png)

### Steps to Reproduce

1. Go to a book page in mobile view.
2. Scroll until the navbar is at the top of the page.  Keep scrolling in the same direction.

* Actual: The navbar disappears behind the header.
* Expected: The navbar is stickied below the header.

### Details

- **Logged in (Y/N)?** N/A
- **Browser type/version?** FF 97.0.2 (64 bit)
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Change the navbar CSS rules for smaller viewports. Specifically, the `top` value needs to be offset by the height of the mobile header.

**Comment by mekarpeles** [comment]
jim to put on :8600 for testing
