### ISSUE TITLE
Add Password Requirements Messaging Near Account Creation Page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#629]
User is currently only shown password constraints when registration fails because of invalid password.

Rutgers University proposes adding messaging near the password field.

Candidate for #603 @aaronsw hackathon

**Comment by salman-bhai** [comment]
Hi can I take this up? I'm a first time contributor.

**Comment by mekarpeles** [comment]
Sure thing! I think there was an attempted out request in this in the past; I can try to link it here

**Comment by salman-bhai** [comment]
Alright I'll look into that before putting up my PR

**Comment by salman-bhai** [comment]
@mekarpeles this was the required string file! https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/i18n/account/register/strings.en

**Comment by salman-bhai** [comment]
I think I just had to add two lines since there was already a guideline for username

**Comment by seabelis** [comment]
The password requirements have disappeared.

**Comment by mekarpeles** [comment]
I think we do / will show them only when there is a problem with the password as opposed to every time.
