### ISSUE TITLE
Disable "auto focus/scroll" on edit page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6293]
The jumping around after loading is reaaaally annoying, and it's never in the field I want anyways.

### Steps to Reproduce
1. Go to eg https://openlibrary.org/books/OL35615701M/The_Game/edit
2. Wait

* Actual: After 1s, the page jumps around and places your focus on the title field
* Expected: Nothing to happen

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
- Only jump in _if_ a field name is specified; e.g https://openlibrary.org/books/OL35615701M/The_Game/edit#edition-subtitle
- If no field name is specified, do not jump, and do not scroll

### Related files
https://github.com/internetarchive/openlibrary/blob/3aab30cd5feb25dfa930731dd6f21db1d0f04dd0/openlibrary/plugins/openlibrary/js/edit.js#L279-L299

### Stakeholders
@mheiman

**Comment by cdrini** [comment]
@mheiman would you be interested in helping with this one? I think this has been annoying you as much as it's been annoying me :P

**Comment by mheiman** [comment]
Sure, I'd be happy to fix this one. Thanks!
