### ISSUE TITLE
Add a book errors with "notfound" trying to match existing work

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6294]
`{'at': {'key': '/books/OL28M', 'property': 'works'},  'error': 'notfound',  'key': '/works//works/OL2896727W'}`

^ Note the wrong work key.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/158281106-bdae1a35-e155-48ef-a58d-7d7a9e278dc3.png)

### Steps to Reproduce
1. Click "Add a book"
2. Fill the fields, trying to create an edition that will match an existing work, but not an existing edition
3. Set the `action="?debug=true"` on the main form element
4. Hit "Add"

* Actual: Error is thrown: "notfound"
* Expected: Edition to be added to existing work

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?**FF
- **Operating system?**win10
- **Environment (prod/dev/local)?** prod, local

### Stakeholders
@jimchamp

**Comment by cdrini** [comment]
P2 since you _can_ get around this by click on the "Add an edition" link on a work.

**Comment by scottbarnes** [comment]
@cdrini, I'd like to work on this!
