### ISSUE TITLE
loans: make it possible to re-download books that use ACS

### ISSUE THREAD

**Issue by mangtronix** [internetarchive/openlibrary#63]
Make it possible to re-download books that use ACS.  Sometimes the ACS client (e.g. ADE or Bluefire) will have a problem downloading the book and the state will be fulfilled in ACS/OL but the user won't have the book to read or return.  Also if the user deletes the book instead of returning it they have no way to return it.

Here's a typical support email:

Hi, I borrowed the book "Taking Larger Trout". I tried to open it on my iPad and it didn't work. I accidentally deleted it before returning it, now I can't return it at all because I no longer have the original file. Can this be returned so I can redownload it and read on my computer? thanks

**Comment by bfalling** [comment]
ACS lending will be handled by the Internet Archive BookReader and will allow re-downloading ACS4 links there. Open Library will no longer handle loans directly, but simply redirect to IA. Closing this issue.
