### ISSUE TITLE
Prototype OpenLibrary Lite for Mobile

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#630]
@rchrd2 is going to be running an experimental @archivelabs interface group at the #603 @aaronsw hackathon *this* Sunday (Nov 5, 2017).

Respond on this issue if you're interested in coordinating with Richard in person or remotely.

OpenLibrary Lite is an attempt to make Open Library's core features more accessible on mobile devices.

**Comment by LeadSongDog** [comment]
Consider iiab.org for offline use?

**Comment by rchrd2** [comment]
Hello. I drew up some rough wireframes of an MVP. It's inspired by SimpleE (https://itunes.apple.com/us/app/simplye/id1046583900?mt=8)

![scan nov 2 2017 5 57 pm page 1](https://user-images.githubusercontent.com/182479/32357195-c50be86e-bff7-11e7-9735-9a2124d66d9f.jpg)
![scan nov 2 2017 5 57 pm page 2](https://user-images.githubusercontent.com/182479/32357200-c79f618c-bff7-11e7-89b2-09ce9ce9bc87.jpg)
![scan nov 2 2017 5 57 pm page 3](https://user-images.githubusercontent.com/182479/32357202-c9ba03be-bff7-11e7-876d-b9c5258043ec.jpg)

The idea is that you can browse, save, and view books, in a mobile-friendly app-like interface.
Login is optional for accessing loan-restricted books.  So I guess, "favoriting" should work in both localstorage and through the open library lists api (want to read).

I suspect that there is a nice mobile webapp framework which can handle a lot of the UI chrome. For bookreader I used http://mmenu.frebsite.nl, but I don't know if it solves all the UI issues here.

**Comment by mekarpeles** [comment]
@aeschylus expressed interest in working on this on Sunday for #603

**Comment by mekarpeles** [comment]
This was a resounding success! Closing the issue as it now has its own home (listed above)
