### ISSUE TITLE
Cannot build olbase image on ARM machines (eg M1 Macs)

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6316]
Errors on the openresty install step, because openresty should be built with different source file for arm devices.

```
 > [ 8/20] RUN apt-get update && apt-get -y install --no-install-recommends openresty:                                              
#12 0.278 Hit:1 http://security.debian.org/debian-security buster/updates InRelease                                                 
#12 0.289 Hit:2 https://deb.nodesource.com/node_16.x buster InRelease                                                               
#12 0.441 Hit:3 http://deb.debian.org/debian buster InRelease
#12 0.451 Hit:4 http://deb.debian.org/debian buster-updates InRelease
#12 0.874 Get:5 http://openresty.org/package/debian buster InRelease [2967 B]
#12 0.967 Fetched 2967 B in 1s (3843 B/s)
#12 0.967 Reading package lists...
#12 1.371 Reading package lists...
#12 1.757 Building dependency tree...
#12 1.839 Reading state information...
#12 1.892 E: Unable to locate package openresty
```

### Steps to Reproduce

1. Run `docker build -t openlibrary/olbase:my-test-label -f docker/Dockerfile.olbase .` on an M1 Mac

* Actual: Errors with the above error
* Expected: It works

### Details

- **Logged in (Y/N)?** na
- **Browser type/version?** na
- **Operating system?** Mac Os 12
- **Environment (prod/dev/local)?** local

### Proposal & Constraints
- openresty is used only for nginx, which isn't used for local dev ; maybe put in own Dockerfile?
- Find a way to switch based on a flag (or automatically) between building ARM and non-ARM? Also unclear if the resulting nginx will be able to run on an arm system if built with a non-ARM machine, and vice versa.

### Stakeholders
@RayBB @cclauss

**Comment by cdrini** [comment]
Labelling as P3 because rebuilding the base image is _pretty_ rare ; and if someone does need to test something, since we don't actually use openresty anywhere on the local dev env, we can just comment out the failing `install` line.

**Comment by cclauss** [comment]
# A proposed solution for the ARM v.s. Intel issue...
https://github.com/internetarchive/openlibrary/pull/6306#issuecomment-1078412267

**Comment by mekarpeles** [comment]
Is this still an issue?

**Comment by RayBB** [comment]
I can try today and let you know

**Comment by cclauss** [comment]
What about a `scripts/install_openresty_if_not_arm.sh` that used one of the answers in https://stackoverflow.com/questions/65259300 to conditionally install `openresty`?

`RUN apt-get update && scripts/install_openresty_if_not_arm.sh`

**Comment by cdrini** [comment]
> Which probably isn't worth supporting.

yeah, I think that might be the current status on this. We definitely don't want to support two separate complicated build systems! This is built fresh every deploy, and M1 users can download/use the prebuilt olbase image, so it's pretty low priority.
