### ISSUE TITLE
Covers loading slower than usual

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6324]
Edition covers load slower than usual for the past 1-2 weeks.
### Relevant url?

Example, https://openlibrary.org/books/OL33334015M/Sports_good_news_Bible 
### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL33334015M/Sports_good_news_Bible
2. Do ...Most of the page loads normally, but the image takes about a minute to load.

* Actual: Image taking longer than ususal to load.
* Expected: Image should not take a minute to load.

### Details

- **Logged in (Y/N)?**y
- **Browser type/version?** Chrome Version 99.0.4844.51 (Official Build) (x86_64)
- **Operating system?** MacOS
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @jimchamp @cdrini

**Comment by mekarpeles** [comment]
@seabelis is this resolved? Can it be closed?

**Comment by seabelis** [comment]
Yes.
