### ISSUE TITLE
Make work id and author id fields on book edit page smarter about what they accept

### ISSUE THREAD

**Issue by mheiman** [internetarchive/openlibrary#6356]
On the book editing page, the fields for setting the work for an edition and for setting the author of a work have autosuggest functionality — you can start typing a value to get a list of matching records. You can also type a work or author ID to get a specific record, but if you enter anything besides the bare ID, it doesn't work.

When doing librarian work, I often find myself wanting to enter a specific ID in these fields, especially if I've been making a lot of changes and autosuggest doesn't have the right values because SOLR hasn't caught up yet. This involves finding the item I want, clicking on it, carefully extracting the appropriate ID from the browser location bar, and pasting that into the editing field.

What I'd really love to be able to do is just right-click an author or work link somewhere, copy the URL, paste it into the editing field, and have the autosuggest be smart enough to figure out what I'm trying to do and suggest the right ID.

### Proposal & Constraints
I propose upgrading the work and author fields so that they can extract the appropriate ID from a complex string (like a URL), saving librarians a lot of fussy clicking and selecting IDs.

I don't see any downsides here. OLIDs are well designed so that they're easily distinguishable from other text. The likelihood of a false match is extremely small, and if it were to happen, the user still gets feedback about the value they're about to save, so they can make any necessary corrections.

### Stakeholders
@mheiman

**Comment by tfmorris** [comment]
This is something that Freebase used to do and would be a great addition.

It can also be extended to external identifiers using (inverting) the HTML templates that are used to format internal identifiers into clickable links.
