### ISSUE TITLE
Add usefull tips to the Docker Installation Guide about Code Updates.

### ISSUE THREAD

**Issue by Philippos01** [internetarchive/openlibrary#6359]
As a new comer, using the Docker installation guide there was a misunderstaning concerning the auto code updates in the web templates. Although, the docker installation process is well described and easily implemented, me and my collegue @dbouris found out that it is not clearly stated which pages auto update and which need extra docker commands to do so, because they are cached.

@mekarpeles 
@cdrini

**Comment by mekarpeles** [comment]
Happy to also assign @dbouris though they will need to reply on this thread before GitHub allows us to do this.

**Comment by dbouris** [comment]
hi, happy to be also assigned if possible!
