### ISSUE TITLE
Make subjects + arrow clickable (expand/collapse) but not the subject tags itself

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6361]
The subject tags simultaneously collapse/expand the subject area AND navigate away from the page. This is potentially unclear for patrons.
### Evidence / Screenshot (if possible)
![expanded_subjects](https://user-images.githubusercontent.com/28732543/162535821-aab546bb-bf0c-4c4a-962d-96ef9da1d7e4.gif)

_This behavior is incorrect.  Subjects should not expand or collapse when link is clicked._
### Steps to Reproduce

1. Go to ...Any work page.
2. Do ...Click a subject tag

* Actual: As described above.
* Expected: Subject tags should not trigger expand/collapse behaviour. This should be limited to the arrow expanders.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by jimchamp** [comment]
It looks like we may need to update the code that clamps our subjects.  Placing the triangle and label inside of a container element and attaching the click event listener to the container should fix this.

__Files related to this issue__:

Template for subject tags:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/SubjectTags.html

Code for subject clamping:
https://github.com/internetarchive/openlibrary/blob/46bcf7c30178f53ef427a5840c4b24717ed79fb0/openlibrary/plugins/openlibrary/js/readmore.js#L23-L46

`initClampers()` is called here:
https://github.com/internetarchive/openlibrary/blob/46bcf7c30178f53ef427a5840c4b24717ed79fb0/openlibrary/plugins/openlibrary/js/index.js#L198-L211

**Comment by cdrini** [comment]
A simpler approach might to just not expand/collapse if the click was on an `a` element. Because the css clamp also handles the `...`, which we do want to be clickable. Something like `if (event.target.nodeName == 'a') return`

**Comment by dbouris** [comment]
hi @jimchamp, me an @Philippos01 would like to work on that!

**Comment by mekarpeles** [comment]
Related to #6428. Re: test coverage, see https://github.com/internetarchive/openlibrary/pull/6428#issuecomment-1100238302
