### ISSUE TITLE
Work pages are not rendering edition details (physical object)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6362]
Work pages are not rendering all edition details (physical object). It is necessary to navigate to the edition url in order to view these details.

### Relevant url?

https://openlibrary.org/books/OL24937226M/The_Catholic_Youth_Bible
https://openlibrary.org/works/OL17732W/Bible?mode=all 

### Steps to Reproduce

1. Go to ...https://openlibrary.org/works/OL17732W/Bible?mode=all 
2. Do ...Look for the physical object details (hint: they are not there)

* Actual: No physical object details
* Expected: Physical object details should appear regardless of url type (work vs. edition)

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by jimchamp** [comment]
I'm seeing the physical object details on the work page that you've linked to:
![Screenshot from 2022-04-01 12-46-45](https://user-images.githubusercontent.com/28732543/161307197-4fcc29a7-57a0-4a52-b4d8-b6e5f84ab2dd.png)

Am I misunderstanding something?

**Comment by jimchamp** [comment]
Confirmed that this is now present in the details section.
