### ISSUE TITLE
Book cover isn't shown correctly on the publisher/subject pages

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6369]
Works with short titles without covers aren't shown correctly on publisher/subject pages.

### Evidence / Screenshot (if possible)
Works with titles "Моё имя" and "Тьма" have too small boxes
![image](https://user-images.githubusercontent.com/58372007/161436844-8b508635-dd94-4aca-8490-63d12727d774.png)

### Relevant url?
Publisher: https://openlibrary.org/publishers/%D0%9A%D0%BD%D0%B8%D0%B3%D0%B0_%D0%A4%D0%B0%D0%BD%D1%84%D0%B8%D0%BA%D0%BE%D0%B2
Subject: https://openlibrary.org/subjects/%D0%B0%D0%BD%D0%B3%D1%81%D1%82
Works: «[Моё имя](https://openlibrary.org/works/OL27052607W/%D0%9C%D0%BE%D1%91_%D0%B8%D0%BC%D1%8F)», «[Тьма](https://openlibrary.org/works/OL27052610W/%D0%A2%D1%8C%D0%BC%D0%B0)»
### Steps to Reproduce
1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by kazikhanmargulan** [comment]
Hello guys! Will this commit solve this? https://github.com/kazikhanmargulan/openlibrary/commit/74ff76d96e7777cdd334cf6f63014a5eed36eeaa
I just added the fixed width to the book cover.
