### ISSUE TITLE
Switch PWA/TWA from pointing to testing.openlibrary.org to openlibrary.org

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6375]
Note this is causing edits from the app to behave strangely / not show up (as is the case on testing.openlibrary.org)

### Stakeholders
@bicolino34 @seabelis

**Comment by bicolino34** [comment]
TWA now points to openlibrary.org

**Comment by Yashs911** [comment]
@cdrini @bicolino34 It would be great if we can generate a new APK and update it on Google Play Store because currently its using the testing.openlibrary.org APK

**Comment by bicolino34** [comment]
Indeed. It is still pointing to testing.openlibrary.org. my mistake. Sorry for that

**Comment by Yashs911** [comment]
Generating a new APK and updating the SHA-256 (from Play Store) [here](https://openlibrary.org/static/.well-known/assetlinks.json) should fix the issue

**Comment by RayBB** [comment]
@mekarpeles not theoretical anymore. Update just rolled out to me :)
![image](https://github.com/internetarchive/openlibrary/assets/921217/dad7ab0e-87af-4890-8650-16ed7b2e2840)
