### ISSUE TITLE
Coordinate with students for good first issues

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6395]
We've been chatting with three (3!) student teams this month who are interested in contributing to Open Library!

- First team (3): Chloe, Crystal, and Michelle
    - Working on book page; eg #6411
- Second team (2): @dbouris , @Philippos01 
    - #4578 
- Third team (2): Vassilis, Constantina
    - Maybe: accessibility; #6054 ; other books page issues

**Comment by mekarpeles** [comment]
I feel like this project board as resolved our core issues and we've made contact w/ each student to ensure at least 1 task each is in flight:

https://github.com/internetarchive/openlibrary/projects/36?add_cards_query=is%3Aopen
