### ISSUE TITLE
Create IA Summer of Code Docs

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6396]
Funding has been acquired

Next steps are to
* [x] create the [Google Doc describing the program + showing a menu of proposed opportunities](https://docs.google.com/document/d/1sI4FjXtzP-5iCym8CDd_WWD5BARr1gI7I3ObgAvhBtk/edit) 
* [ ] create a [google form for applicants](https://docs.google.com/forms/d/1mozWhfhQ8v5GfPT68LXfBSGNHJ3nAIPYH_nG9yvB1H8/edit)

CodePath + Wendy H & Partner org + CMU + NYU + IA DEI channel all good candidates for outreach

**Comment by mekarpeles** [comment]
Applications need to be open by end of week i.e. Friday, May 6 and selected before June.
