### ISSUE TITLE
Multiple Amazon records imported 5 times apiece creating duplicate editions

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#6405]
This Amazon record: https://www.amazon.com/gp/product/2757891332

was imported 5 times in a row as:

- https://openlibrary.org/books/OL32623293M
- https://openlibrary.org/books/OL32623294M
- https://openlibrary.org/books/OL32623295M
- https://openlibrary.org/books/OL32623296M
- https://openlibrary.org/books/OL32623297M

Here is another set of 5 copies of https://www.amazon.com/gp/product/2744091022
- https://openlibrary.org/books/OL32598981M
- https://openlibrary.org/books/OL32598982M
- https://openlibrary.org/books/OL32598983M
- https://openlibrary.org/books/OL32598984M
- https://openlibrary.org/books/OL32598985M

### Relevant url?
See above

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: See above
* Expected: Amazon records get imported zero or, at most, one time

### Details

- **Logged in (Y/N)?** N/A
- **Browser type/version?** N/A
- **Operating system?** N/A
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
This is out of control! ImportBot is creating 3 copies of each book imported from Amazon. At this rate, it won't be long before bad data outstrips good data in OpenLibrary :(

![Screen Shot 2023-04-20 at 8 01 57 PM](https://user-images.githubusercontent.com/82178/233510898-d87752bd-cd3c-4427-92fb-e344eda4002e.png)

**Comment by cdrini** [comment]
Stopped. Something must have changed recently to have this become significantly more prevalent.

**Comment by cdrini** [comment]
Darnit still happening! Jumping back in

**Comment by cdrini** [comment]
Finally stopped the thing 😤 That was such a tangle

**Comment by mekarpeles** [comment]
Either (a) we may have an issue with our catalog/import code which is failing to resolve / differentiate same works or (b) the `/isbn` endpoint in `plugins/openlibrary/code.py` is somehow ignoring the catalog code or (c) the `scripts/affiliate-server` batch imports are somehow failing their `get_pending` checks.

**Comment by LeadSongDog** [comment]
@cdrini 

Thank you very much for addressing that urgent problem of ImportBot doing 2, 3, 4, and 5 fold imports of one isbn. 

Please though, before rue-enabling it, can we get the limitations put in place to prevent new author- and work-records being created solely on the basis of AMZ/BWB crap metadata? We humans can’t do data cleanup as fast as ImportBot can pollute the pool.

**Comment by scottbarnes** [comment]
I suspect the underlying problem here is fixed by #8511: there has long been a race condition when concurrently trying to import the same item, and #8511 includes a [fix](https://github.com/internetarchive/openlibrary/pull/8511/commits/f479cae9cf41a374a3a6f30a6cff354fb5cc712d) for that race condition via the `/isbn/` endpoint.

However, that PR did not address what's necessary to bring the affiliate-server, which handled Amazon imports, back online, nor does it address import quality (:disappointed:).

**Comment by mekarpeles** [comment]
Linked to #8690

**Comment by mekarpeles** [comment]
I think this should now be resolved, especially since we're staging amazon rather than making them pending.
