### ISSUE TITLE
Non-ASCII character rendering broken on author page

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#6406]
This author https://openlibrary.org/authors/OL8115327A/Robert_Wi_347_niewski
has a name that renders as `Robert Wi&#347;niewski` on the author page
but, correctly, as `Robert Wiśniewski` on the pages of his works e.g. https://openlibrary.org/works/OL21191421W

### Evidence / Screenshot (if possible)
![Screen Shot 2022-04-10 at 10 40 15 PM](https://user-images.githubusercontent.com/82178/162656086-3a7ef02f-7816-4aed-9805-611dd144feb3.png)

### Relevant url?
See above

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected: Correct rendering is used on all pages where the name appears

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 100.0.4896.75 (Official Build) (x86_64)
- **Operating system?** Mac OS
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
This was a XSS vulnerability on the _work_ page. Html entities shouldn't be follow, but should be replaced on the data record with their proper unicode counterpart.
