### ISSUE TITLE
Work count shown as 1 when actually 0

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#6407]
When an author has zero works or all works are filtered by search on the author page, the count is incorrectly shown as 1 instead of 0.

### Evidence / Screenshot (if possible)
![Screen Shot 2022-04-09 at 2 37 48 PM](https://user-images.githubusercontent.com/82178/162656566-4827aa06-714a-49d5-975d-18a2a62b11fa.png)

### Relevant url?
https://openlibrary.org/authors/OL2804931A

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected: The correct count to be shown ie 0.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
Fixed by #7614

**Comment by tfmorris** [comment]
#7579 is a broader version of this. It turns out that the problem was specific to the French translation, not the search functionality.
