### ISSUE TITLE
Cannot remove an Edition's language from the edit UI

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6409]
There is a section for adding an edition's language in the edit UI.  However, there does not seem to be a way to delete an existing language using the UI.

### Evidence / Screenshot (if possible)
![Screenshot from 2022-04-11 12-39-23](https://user-images.githubusercontent.com/28732543/162790332-c7907fe7-f605-47b3-a39d-9358facf5257.png)
_Languages can be added here, but not removed..._

### Steps to Reproduce

1. Go to an edition page and click the edit button.
2. Select the edition tab, if it is not already selected.
3. Scroll down until you reach the language section.
4. Delete one of the languages and submit the edit form.

* Actual: A success flash message is displayed, but nothing has changed.
* Expected: The language is deleted.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF 97.0.2
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Provide some means to delete a language using the edition edit UI.  It would also be nice if the "Thank you very much for improving that record!" message isn't displayed when no edit has happened (this can be a separate issue if it's more than trivial to implement).

**Comment by tfmorris** [comment]
Can you explain the use case for removing an edition language? If the language is wrong, just correct it. There are also codes like `zxx`, `mul`, `unk` for special cases.

**Comment by jimchamp** [comment]
Multiple languages can be added to an edition.  If two or more languages are assigned to an edition that is written in a single language, then at least one of the assigned languages are incorrect.  This functionality would be handy in these cases.

**Comment by tfmorris** [comment]
Thanks for the clarification. Presumably this will be restricted so that they can't remove the last language.

**Comment by jimchamp** [comment]
This seems reasonable.  I can't really think of a use case for removing the last language, nor do I want our catalog's quality to drop.

**Comment by scottbarnes** [comment]
I'd like to work on this.
