### ISSUE TITLE
When no star ratings on book, UI looks weird

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6411]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/162824327-1d800dab-41dc-4f11-9037-f5338ef4ea6d.png)

### Relevant url?
eg https://openlibrary.org/books/OL664495M/An_octave_above_thunder

### Steps to Reproduce

1. Go to book with no ratings

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by Vassilis-Boubis** [comment]
Hello! Can @constantinazouni and I work on that issue?
