### ISSUE TITLE
Make site footer mobile responsive

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#642]
Right now, the Open Library website header is mobile responsive. The body and footer are not.

For new pages we add (i.e. the body), an effort will be made to make them mobile responsive.

In order for this to happen, the footer must first be made mobile responsive.

See:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_foot.html
https://github.com/internetarchive/openlibrary/blob/master/static/css/master.css

**Comment by LeadSongDog** [comment]
Only peripherally related, but that line in the existing footer reads:
Top | Home • Add a Book • Subjects | Authors | Lists • About Us | Help • Developers

For some reason https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_foot.html shows a bizarre mix of `<span>|</span>` and `<span>&bull;</span>` and even `<span></span>`

It doesn't appear these add anything to the comprehensibility of the line over, say, just a white space.

**Comment by mekarpeles** [comment]
@LeadSongDog good catch -- these changes have been added and are live!
