### ISSUE TITLE
strip spaces from ISNI author ids

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#6423]
**Feature:** Input validation on ISNI identifiers by stripping out any spaces entered on saving (similar to how hyphens are stripped from ISBNs before storing)  I think this is done in js on the edit forms?

I noticed some authors currently have ISNI with spaces, e.g. https://openlibrary.org/authors/OL2520118A/Amian_L._Champneys

Which forms an incorrect URL which does not resolve correctly: https://isni.org/0000%200000%204804%202905/

It is correct to store the ISNI without spaces. If a display format is desired, this could be new feature to insert spaces at the correct points. Currently the author ID config doesn't have a clear location for adding id specific display logic though.

For input, it makes sense to me to:

* Allow a user to enter an ISNI with display format spaces
* Strip those spaces before saving the id to the database

**Not in scope / separate feature:**

* Adding display format spaces back when presenting ISNIs back on the UI.
e.g.
```
     <a href="https://isni.org/0000000048042905/">0000 0000 4804 2905</a>
```
* ISNIs appearing in RDF, JSON, or other raw data formats should also not have spaces (no action required if we ensure spaces are never saved)

**Comment by bencomp** [comment]
This appears to be strongly related to #5696.
