### ISSUE TITLE
Fix Book Page Navigation Bar Overflow on Mobile (Horizontal Scroll)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6431]
When in mobile view, the Book Page navigation bar overflows on to 2 lines.

We'd like instead for the nav bar to star on 1 line and to overflow horizontally (be scrollable).

This will require adding css to the [`.work-menu.sticky`](https://github.com/internetarchive/openlibrary/blob/971383b5d6caf6a0f9f2397563661b6997b58539/static/css/components/work.less#L149-L193) component in [work.less](https://github.com/internetarchive/openlibrary/blob/971383b5d6caf6a0f9f2397563661b6997b58539/static/css/components/work.less#L149-L193)

```
    white-space: nowrap;
    overflow-x: auto;
```

We want the nav bar to be scrollable (by mouse or finger) but we don't want the default bulky scroll bar to appear.

This stackoverflow page may have some tips
https://stackoverflow.com/questions/16670931/hide-scroll-bar-but-while-still-being-able-to-scroll

```
.work-menu.sticky {
    -ms-overflow-style: none;  /* Internet Explorer 10+ */
    scrollbar-width: none;  /* Firefox */
}
.work-menu.sticky::-webkit-scrollbar { 
    display: none;  /* Safari and Chrome */
}
```

This is a subtask of #6066.

### Evidence / Screenshot (if possible)
![openlibrary org_books_OL25840917M_The_Three-Body_Problem (1)](https://user-images.githubusercontent.com/978325/163434850-347990d3-42d5-4c8d-82dc-2c4d25dde1fc.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
** We should use `overflow-x: auto`; Otherwise the scrollbar will always be visible.

**Comment by furugoorin** [comment]
@mekarpeles I would like to claim this issue! I would also like to open this up to Michelle and Chloe, so that the three of us could tackle this together.
