### ISSUE TITLE
Add Google Analytics Tracking to Book Page Nav Tab Items

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6437]
On the homepage, we have an onboarding carousel where each "card" has a special field which allows it to be tracked by google analytics which looks like:

`data-ol-link-track="OnboardingCarouselClick|Read"`

The should be read as:
The "Read" button of the an `OnboardingCarouselClick` event

In our case, we probably want an event of `BookPageNavbar` and then actions of e.g. `Overview`, `Lists`, etc.

Each `<a>` tab will have something which looks like `data-ol-link-track="BookPageNavbar|Overview"` where the term `Overview` will change depending on which tab we're referencing.

### Describe the problem that you'd like solved

![openlibrary org_works_OL8076534W_Designs_for_Coloring](https://user-images.githubusercontent.com/978325/165362511-cf69b965-137d-465d-90de-5b14d44f68f4.png)

@ChloeQian12 would you be open to helping with this one?

**Comment by ChloeQian12** [comment]
Hi Mek @mekarpeles! Thank you so much for consideration. However, my hands are already full with the current issue. I will let you know once I finish translating the file.

**Comment by jimchamp** [comment]
Just completed this while working on the generic navbar component.  Sorry, @ChloeQian12 --- I thought that you were working on adding analytics to the header items...

**Comment by jimchamp** [comment]
I stand corrected --- that PR was not merged.  We want to set the `data-ol-link-track` values to the following for each link:
| Link Text | `data-ol-link-track` value |
|---:|---:|
| Overview | BookPageNavBar&#124;Overview |
| View `n` editions | BookPageNavBar&#124;EditionTable |
| Details | BookPageNavBar&#124;Details |
| Lists | BookPageNavBar&#124;Lists |
| Related Books | BookPageNavBar&#124;RelatedBooks |
| Reviews | BookPageNavBar&#124;Reviews |

I see that you are still assigned to this issue, @ChloeQian12.  Are you still interested in working on this?  If not, I'll go ahead and unassign you.
