### ISSUE TITLE
Combine Loans and Waitlist pages

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6438]
We currently have loans and waitlists as separate items in the My Books sidebar:

![image](https://user-images.githubusercontent.com/6251786/163466932-cb7430b2-2489-4283-a931-771fafd7cf45.png)

As we add more items to this sidebar (Eg #6427 ), this it's getting a little messy. "Waitlist" isn't as useful anymore for most patrons, so lets combine Loans and Waitlist:

![image](https://user-images.githubusercontent.com/6251786/163469613-8871d6cc-232d-4f1a-8a11-4eafa29011fe.png)

### Proposal & Constraints
- [ ] /account/loans should render the waitlist items
- [ ] /account/waitlist should redirect to /account/loans
- [ ] Remove the "Waitlist" link from the sidebar
- [ ] Rename "Checked out" to "Loans"

### Stakeholders
@jimchamp

**Comment by cdrini** [comment]
Hi @tangym27 ! Would you be interested in this one after working on Read more? Also before #6427 :)

**Comment by tangym27** [comment]
Hi @cdrini! Yes, this sounds great. Thank you!
