### ISSUE TITLE
you cant publish commercial material worldwide, just in US. also you cant read it yourself cuz free reading is capitalism cost saving hence commercial use.

### ISSUE THREAD

**Issue by lootnath** [internetarchive/openlibrary#6443]
us judges irratiinal and poorly trained.

**Comment by mekarpeles** [comment]
Thank you for your feedback. If you have questions or comments about the policies of the Open Library service, please feel free to direct them to info@archive.org.

The github is primarily for engineering efforts and team coordination so there aren't many things we can do to engage with such perspectives here. Thank you!
