### ISSUE TITLE
Merge UI should be available to users with `trusted-users` tag

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#645]

**Comment by hornc** [comment]
Currently merge authors and merge editions are implemented as Infogami feature flags:
https://github.com/internetarchive/openlibrary/blob/master/docs/design/feature-flags.rst

(docs need to be updated to show usergroups of form: `/usergroup/beta-testers`)

Currently OL has the following usergroups:

- /usergroup/admin
- /usergroup/allusers
- /usergroup/api
- /usergroup/beta-testers
- /usergroup/demo
- /usergroup/dev
- /usergroup/everyone
- /usergroup/librarians
- /usergroup/scan
- /usergroup/translators
- /usergroup/virtualshelf

`/usergroup/librarians` seems like the best candidate.

As far as I can tell, tags and usergroups are completely independent. Only tags are displayed against users in the admin interface. It would be nice to see what usergroups a user, and self-profile, belong to.

**Comment by hornc** [comment]
**Problem with feature flags:**  If `usergroup` is selected as the filter, only one usergroup can be chosen, so for example, choosing `/usergroup/librarians` for `merge-authors` means that `/usergroup/admins` won't be able to merge, which is not ideal.

The easiest way to let admins do everything is to change the feature enabled check to something like: `(is_feature_enabled() || user.is_admin())`

**Comment by mekarpeles** [comment]
Is this resolved by https://github.com/internetarchive/openlibrary/pull/664?
@hornc 

Note, this feature should probably work for trusted_user and admins -- currently @JeffKaplan isn't seeing it as an admin (I've set him as a trusted-user)

**Comment by hornc** [comment]
@mekarpeles  I'm not sure why the feature is not showing up for admins -- I can  no longer see it either.  I re-checked in my dev environment and I see the feature if I am admin non-librarian, OR I am in the librarian user group, I even tried disabling the merge authors feature in config to confirm being an admin still gives access to the feature (being admin overrides the specific config), and it worked locally as expected.

Has the config been updated without the code being deployed to prod?  ... just typed this and checked, yup.. prod SHA shows 938e859, which is just before my PR was merged! :)

**Comment by mekarpeles** [comment]
I think its not currently @ 532587d and the config looks like this on olsystem:

`features:
    upstream: enabled
    cache_most_recent: enabled
    recentchanges_v2: enabled
    history_v2: admin
    merge-authors:
        filter: usergroup
        usergroup: /usergroup/librarians
    merge-editions: admin`

**Comment by hornc** [comment]
@mekarpeles Can this be closed now as https://github.com/internetarchive/openlibrary/pull/664 is in an the config is correct.

 As a slight aside based on the title of this issue, I don't see that user tags are used for anything other than as a keyword tag associated with users. The built in way of handling permissions (inherited from Infogami) is via usergroups. The tags seem to confuse things (at least me, as I don't see why they have been added, so maybe I'm missing something ;) ) Perhaps we can have a discussion about the role of tags and the correct process of allocating permissions at some point?

**Comment by mekarpeles** [comment]
Yes, closing and happy to revisit as per your comment :)
