### ISSUE TITLE
Book Edit Page: By default, ENTER triggers Delete not Save

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6471]
Believed to be related to #6273. When a patron uses the ENTER key to submit the book edit form, the delete button is being triggered instead of save.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by bitnapper** [comment]
### Evidence / Screenshot (if possible)

<img width="1060" alt="Screenshot 2022-04-22 at 17 58 07" src="https://user-images.githubusercontent.com/2772669/164751359-edc42290-2e85-47fb-abfa-557d2ae899d2.png">

## Steps to Reproduce

1. Got to any edition
2. Click edit
3. select the  _How many pages?_ text field
4. press enter

- actual

> This page has been deleted

- expected

changes should have been changed.

## Details

-     Logged in: yes
-     Browser type/version: Firefox on iOS, Firefox 99.0.1 macOS, Safari 15.4 macOS, Chrome macOS
-     Operating system: iOS and macOS
-     Environment (prod/dev/local)? prod

**Comment by jimchamp** [comment]
Thanks for the details!  I'm on it.

**Comment by LeadSongDog** [comment]
Oh crap! Thanks to this bug I inadvertently deleted several editions today. Is there a way to undo?
