### ISSUE TITLE
Replace sidebar for mobile "My Account" pages

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6485]
### Describe the problem that you'd like solved

In mobile views, the sidebar in "My Account" pages is placed above the content.  Since the sidebar contains many items, patrons must scroll fairly far to find the content that they are looking for.  It would be great if the sidebar didn't take up so much vertical space in mobile views. 

### Proposal & Constraints

Let's convert the sidebar into a navbar in mobile views.  The navbar would be similar to those found on book pages.

### Additional context

This will remain blocked until a generalized navbar template is created.  I am actively working on this now.

**Comment by mekarpeles** [comment]
I think we have a dupe issue #6857
