### ISSUE TITLE
Translate /subjects into Chinese

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6486]
We can translate these pages to other language thanks to `/type/i18n_page`! Just go to https://openlibrary.org/subjects.zh?m=edit . If you don't have permissions, please comment with your OL username, and I'll see what I can do :)

Here are some others: https://openlibrary.org/subjects.es , https://openlibrary.org/subjects.fr

### Additional context
NOTE: This is kind of annoying in that ideally we'd want to #2819 , which would give us the ability to store translated titles on the subject itself. But that's far away unfortunately, and in this seems good enough in the interm, and will provide a lot of value to non-English users. We will also be able to copy over the translations from this page once #2819 is complete, so no one's work is wasted.

### Stakeholders
@eguo3 @ChloeQian12

**Comment by eguo3** [comment]
Hi @cdrini , thank you for informing us! I tried to open the page but I don't have permission. My OL username is also eguo3 :)

**Comment by cdrini** [comment]
Awesome, thank you @eguo3 ! Try now :) https://openlibrary.org/subjects.zh?m=edit

**Comment by eguo3** [comment]
> Awesome, thank you @eguo3 ! Try now :) https://openlibrary.org/subjects.zh?m=edit I added you to /usergroup/translators on Open Library.

It works! Thank you @cdrini !

**Comment by eguo3** [comment]
Just added the translation!

**Comment by tuminzee** [comment]
@cdrini should we close this issue?

**Comment by cdrini** [comment]
Oh, I missed the notification; thanks for the ping, @tuminzee !

Wow that looks awesome, @eguo3 ! 😊 

https://openlibrary.org/subjects.zh

![image](https://user-images.githubusercontent.com/6251786/167484041-5104e2c8-a1bd-4713-98d6-43b08bcff07b.png)
