### ISSUE TITLE
Translate CONTRIBUTING.md to Chinese

### ISSUE THREAD

**Issue by ChloeQian12** [internetarchive/openlibrary#6497]
### Describe the problem that you'd like solved

I noticed that there is no Chinese translation of [CONTRIBUTING.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md). I would love to help translate the file.
### Proposal & Constraints

N/A

N/A
### Additional context

N/A
### Stakeholders

@mekarpeles

**Comment by tuminzee** [comment]
@mekarpeles as @ChloeQian12 is interested in working on this issue, I would like to assign this issue to @ChloeQian12 

Thank you @ChloeQian12 for your help. I have assigned this issue to you. Happy contributing 👯

**Comment by tuminzee** [comment]
@ChloeQian12 how is it going? do you have any issues, or doubts?

**Comment by ChloeQian12** [comment]
@tuminzee will get it done in a couple of more days!
