### ISSUE TITLE
Spelling error, subjects page, German translation

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6505]
From a patron:
Auf der deutschen Themenliste: "Matematik" tut weh: Typo bitte korrigieren.

### Evidence / Screenshot (if possible)
<img width="265" alt="Screenshot 2022-05-02 at 10 08 53" src="https://user-images.githubusercontent.com/17739465/166204043-af0d6b86-a825-4302-8f15-df83bb0fc6c5.png">

### Relevant url?

https://openlibrary.org/subjects
### Steps to Reproduce

1. Go to ...https://openlibrary.org/subjects
2. Do ...View in German. See typo where Matematik is listed.

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Related files

Issue #4678 
### Stakeholders

@bitnapper @cdrini

**Comment by dcapillae** [comment]
Fixed: "Mathematik".

**Comment by tuminzee** [comment]
It is already fixed @seabelis @mekarpeles can we close this issue?

**Comment by cdrini** [comment]
Thank you so much @dcapillae ! Confirmed fixed :)
