### ISSUE TITLE
Enriching Reading Log data exports (more fields)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6519]
* Currently Reading Log dumps (https://openlibrary.org/account/import) are limited to IDs because large Reading Logs (500+ items) can cause performance issues aggregating results in memory and and serving as large files. Currently, Lists impose an export limit if there are more than ~1k items
* The manual work around is to look over each Reading Log entry (e.g. OL16801714W) and to fetch the json for the corresponding item from Open Library API or the data dumps: https://openlibrary.org/works/OL16801714W.json
* 2 possible solutions to this problem are:
  * Give an option to download all work data but limit to e.g. 500 results (and show a notice, similar to lists page)
  * Offer a js option which allows one (from the OL website) to download pages of ~500 results from Reading Log (calculated based on total number of patron's books on Reading Log)
  
Questions for community:
* What format of data would you prefer/expect? CSV? JSON?

cc: @jimchamp @mheiman @seabelis @jimman2003

**Comment by mheiman** [comment]
My sense is that anyone able to manipulate a JSON file to do anything useful is capable of using the existing API.

If a non-programmer wants their reading log data for something, they're probably hoping to manage it in a spreadsheet or import it to another service, which suggests CSV. But without having some clear use cases, it's hard to know what fields would be helpful to include beyond the obvious title, author, year.

**Comment by Fl0rent** [comment]
csv could be useful to make statistics.
The number of books read in a year, languages, authors, theme ...

so I would suggest for the columns: 

1. title
2. author
3. isbn ?
4. my rating
5. number of pages
6. year published
7. date read
8. read count
9. series ?


Personally, I like to export my data in csv format, for future proofing purposes.

**Comment by tuminzee** [comment]
@Fl0rent would like to give it a try?
@mekarpeles what do you think about the points mentioned by @mheiman and @Fl0rent

**Comment by Fl0rent** [comment]
@tuminzee a try for ?

**Comment by cclauss** [comment]
Resolution is complicated by a bug noted in the comments of `get_users_logged_books()` that can be seen by doing:
`assert get_users_logged_books(username, page=1)  != get_users_logged_books(username, page=2)`
for a user that has just three logged books.  Normally the first page should return a list of three books and the second page should return an empty list but instead, it returns the same three books as the first page.
@cdrini Database query help needed.
