### ISSUE TITLE
Replace "Not In Library" button with "Check local libraries"

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6525]
Related to #5831 

### Problem

Patrons get confused when they see a button that says "Not in library". It's a dead end. Instead, we should give them a default action of searching for an Open Library book within their local libraries using Worldcat or LibraryLink.

### Describe the problem that you'd like solved

Replace `Not in library` button:
![openlibrary org_search_q=the+best+thing mode=everything](https://user-images.githubusercontent.com/978325/167480811-204ddf44-4961-49a7-94ea-e5dd9eb2e1ba.png)

With `Check local libraries`:
![openlibrary org_search_q=the+best+thing mode=everything (3)](https://user-images.githubusercontent.com/978325/167480743-a8b56e12-e1c8-480a-b619-db18d179bd27.png)

### Proposal & Constraints

* The style should use the `cta-btn--shell` class.

* The button should link to the Worldcat link in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/WorldcatLink.html#L9

* Button must have analytics / click-tracking (to compare before/after)

### Additional context

Code:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/LoanStatus.html#L137-L140

### Stakeholders

@jimchamp @cdrini @seabelis @JeffKaplan @bfalling

**Comment by mekarpeles** [comment]
For now, clicking btn will go to Worldcat, eventually we may wish to explore integrations which show library availability from within the context of Open Library and the other valuable info we're able to show on the book page.

**Comment by jmoldyvan** [comment]
I can attempt to do this!

**Comment by tuminzee** [comment]
@mekarpeles I see that you have self-assigned this issue. Would like me to work on this one?

**Comment by mekarpeles** [comment]
This one is a bit tricky and I'm almost done :)

**Comment by mekarpeles** [comment]
Prototype: Create a modal similar to the `share` modal which has tabs for checking Library.Link & Worldcat availability.

**Comment by tuminzee** [comment]
hello @ThisIsRahmat I will list down few resources which can help you understand the codebase and flow better
[Readme.md](https://github.com/internetarchive/openlibrary#readme)
https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md

I hope this helps.

**Comment by ayushdhiman-py** [comment]
hey i want to work on this issue please assign me this issue

**Comment by JaydenTeoh** [comment]
Hi, I'll be taking on this issue. I'll make a PR within this week.

**Comment by JaydenTeoh** [comment]
@mekarpeles Here is my current implementation for the modal, I would probably need the designer's input on it. But the functionality is there already, will make the PR once the design is settled.
<img width="857" alt="image" src="https://user-images.githubusercontent.com/90945854/224507642-f7e3e7ea-f0f3-4a67-9051-c2531397bb78.png">

**Comment by weshatheleopard** [comment]
This button is confusing both the old and the new ways. Should be clearer. Like, **"This book is currently checked out by enother reader. Would you like to be notified once it is returned? Also, you can [ CHECK LOCAL LIBRARIES ]"**

**Comment by prasoon2510** [comment]
Yeah I am very happy to work with thus good first issue.  Will you assign to me please

**Comment by cdrini** [comment]
Howdy folks, there's an open PR for this one, and this needs a bit more planning for direction :) Removing the good first issue label for now.

**Comment by mekarpeles** [comment]
The current state of this issue is that, instead of "Not In Library" the button should say: `Locate` using the primary color button and pop up a modal with worldcat results

**Comment by tuminzee** [comment]
@mekarpeles can I work on this issue?

**Comment by mekarpeles** [comment]
@tuminzee this one may be complicated as some books don't have ISBNs and there's still discussion about what type of experience should occur when the button is clicked and so I've assigned it to myself, sorry! ❤️

**Comment by tuminzee** [comment]
@mekarpeles that's cool I'll find some
other issue 🕺🕺🕺

**Comment by mekarpeles** [comment]
@SivanC let's achieve this in our PR for #5831
