### ISSUE TITLE
My Books Dropper: Standardize & make behavior consistent across all views

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6531]
The "Reading Log" button on the Search Results page should have the same options (e.g. add to lists) as the Books Page

* [ ] #8298 
* [ ] #6897
* [ ] #6992
* [ ] #8009
* [ ] #8298

**Comment by jimchamp** [comment]
Before this happens, we may want to reconsider how items are removed from lists.  Ideally, this functionality can be tucked away inside of the reading log dropper.  If we remove items in a way similar to that of the book page, our search result items have a good chance to become more cluttered.

**Comment by mekarpeles** [comment]
Agreed, #7173 -> #6992 would enable books to be managed completed from within the dropper (as opposed to the Books Page where "remove from list" functionality done outside.

We should make it at minimum so, even if we keep the Book Page design (of showing what lists are active) then we can **also** manage via checkboxes within the WTR/List Dropper Widget

**Comment by mekarpeles** [comment]
May I make you the assignee on this one @DebbieSan?

**Comment by DebbieSan** [comment]
Certainly! Thank you!

**Comment by DebbieSan** [comment]
Just an FYI, I am working on a dropper menu / new buttons to address this issue. I should have something to present at the design meeting :)
