### ISSUE TITLE
ol_dump_works contains authors that have been deleted

### ISSUE THREAD

**Issue by rahulsabbineni** [internetarchive/openlibrary#6532]
Thank you for creating Open Library! I've downloaded some of the OL data dumps into Postgres and had a quick question after interacting with the data.

I think `ol_dump_works_2022-03-29.txt` contains 30 distinct authors that do not exist in `ol_dump_authors_2022-03-29.txt` or `ol_dump_redirects_2022-03-29.txt`.

As one example, [`/authors/OL7103602A`](https://openlibrary.org/authors/OL7103602A) appears in the works dump 14 times. Per the site, this author has been deleted, but the 14 works they've created remain. In this case, I believe all of the data is spam - as an example, check out [`/works/OL16721549W`](https://openlibrary.org/works/OL16721549W/Porkchops_and_More%21).

As another example, [`/authors/OL8410068A`](https://openlibrary.org/authors/OL8410068A) appears in the works dump twice. Again, the author has been deleted, but their two works remain. In this case, the works (`OL21981903W`, `OL22278850W`) may be valid, given both have ISBN 13 numbers that seem to match Amazon product pages.

My question is - if the author has been deleted (and not present in authors / redirects dump), shouldn't their author record be deleted from the `authors` key in the works dump? 

I'm not sure if this is a bug, so I've marked this as "Question & Discussion". Thanks again!

**Comment by cdrini** [comment]
Thank you @rahulsabbineni ! Would you be able to post a list of all the works that have deleted authors? There must've just been a historical bug at some point that resulted in them not being cleaned up. We can go through them and delete what we can!
