### ISSUE TITLE
Clamp Read More sections by default, like subjects

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6534]

**Comment by lakshya-dhariwal** [comment]
May I be assigned to this? 
I can start working on it once more detail is added.

**Comment by jpdh9881** [comment]
@jimchamp Hi Jim, could I be assigned this issue? @mekarpeles got me set up and suggested I start with [6484](https://github.com/internetarchive/openlibrary/issues/6484) and [6857](https://github.com/internetarchive/openlibrary/issues/6857)

**Comment by jpdh9881** [comment]
@jimchamp Is this the sort of thing you were looking for?

Default:
![image](https://user-images.githubusercontent.com/54423825/201789187-2d4472ac-d355-4075-b063-0d9a0f1aca30.png)

Expanded:
![image](https://user-images.githubusercontent.com/54423825/201789254-b3c4548d-77da-4fcb-92df-9dafce4df3de.png)

**Comment by jimchamp** [comment]
I'm pretty sure we still want the "Read more" link here.  I'm also noticing that our subjects are not expanding in Firefox.
Let's pause work on this issue until I get more details about what exactly is needed for this issue to be considered complete.

In the meantime, would you like to work on issue #7007?

**Comment by jpdh9881** [comment]
Sounds good, I'll move to #7007. In my changes I refactored the clamp styles so it works in Firefox now.

**Comment by jimchamp** [comment]
Thanks @jpdh9881!
You can probably discard the code that fixes the subject clamps.  I opened a PR that addresses this yesterday.

**Comment by jimchamp** [comment]
Closing this, as it's already completed.
