### ISSUE TITLE
Mobile Book Page has horizontal scroll (too wide)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6535]

**Comment by Sumit-Sahni** [comment]
What  should be change could you please elaborate

**Comment by tuminzee** [comment]
@Sumit-Sahni sure, @mekarpeles @jimchamp will add more description for this issue.
Thank you for your interest in Open Library, happy to see you here 😄 
Have a good day 🕺🏼

**Comment by jimchamp** [comment]
Sorry for the delay!  It looks like the search input in the editions table is overflowing in mobile:

![Screenshot from 2022-05-20 19-07-53](https://user-images.githubusercontent.com/28732543/169623317-1b5242fd-10f1-4a73-93c4-6f78c2ba3bce.png)

It would probably be better if the search input was left-aligned and either above or below the edition count selector in mobile.

**Comment by tuminzee** [comment]
@Sumit-Sahni I hope this information is sufficient for you, would you like to work on this issue?

**Comment by scottbarnes** [comment]
I submitted a PR here: https://github.com/internetarchive/openlibrary/pull/6623.
