### ISSUE TITLE
Increase padding on clickable Book Page Nav Regions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6538]
The tabs of the navbar are currently only clickable on the text. The purple region below is _not_ clickable -- but should be. Change the padding to be on the `<a>` element so these are easier to press on touch screens.

![2022-04-21-13-14-42](https://user-images.githubusercontent.com/6251786/168120313-2bfee696-ee95-48fd-a4f2-ec87fe6c1477.png)

### Related files
- CSS: https://github.com/internetarchive/openlibrary/blob/bd1e9d8ce0a2d50b72d5451f1f7b175f3ab5c559/static/css/components/work.less#L200-L210
- HTML: https://github.com/internetarchive/openlibrary/blob/5b8d4fc0c80748b2fea54b468294e2dfb00afbb2/openlibrary/macros/EditionNavBar.html

**Comment by jeremyng353** [comment]
Hi, I'm interested in working on this issue. By clickable book page, I'm assuming you mean the pages of a book that you can click to flip, but which part is the nav region? Is it the part at the bottom with the page slider and other buttons?

![image](https://user-images.githubusercontent.com/69836033/168053354-a964ada9-22ca-47aa-9be2-0b55c2a7450a.png)

**Comment by jeremyng353** [comment]
Thanks for the clarification, I'd like to work on this issue.

**Comment by cdrini** [comment]
Awesome, thank you @jeremyng353 ! Let us know if you have any questions :)
