### ISSUE TITLE
Subject can't be added to list

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6540]
Subject can't be added to list. Also, a list can't be created from subject page.

### Steps to Reproduce

1. Go to ... any subject
2. Do ... add to list

* Actual: subject isn't added to list
* Expected: subject is added to list

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by tuminzee** [comment]
@cdrini @seabelis did you encounter this issue?

**Comment by bicolino34** [comment]
This should be solved by #6391. I thought that it had already been merged into master branch, but apparently it hadn't

**Comment by tuminzee** [comment]
thank you for your response @bicolino34
