### ISSUE TITLE
Improve localization files handling counting

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6541]
Currently, localization files handle only singular/plural forms:
> msgid "1 book"
msgid_plural "%(count)d books"

It's not quite appliable for Ukrainian language because we use three different forms of words with different numbers. E.G. in Ukrainian it will look like:
> 1, 21, 31, 41... книга
2, 3, 4, 22, 23... книги
0, 5, 6, 7, 8... книг

This also will be useful for russian and Belarusian languages and perhaps most other Slavic languages

**Comment by milotype** [comment]
@bicolino34 @cdrini @tfmorris 
I'm not a porgrammer, but Croatian needs 3 forms:
- one
- few
- other

The `Plural-Forms` code for Croatian is correct.

I'm not sure what Ukrainian needs …

I use [Poedit](https://poedit.net/) for translating. The app sets the necessary code for plural forms automatically according to the selected language/localization.

Hope this info is helpfull …

**Comment by tuminzee** [comment]
@milotype this is helpful, thank you for your participation

**Comment by bicolino34** [comment]
> @bicolino34 @cdrini @tfmorris I'm not a porgrammer, but Croatian needs 3 forms:
> 
>     * one
> 
>     * few
> 
>     * other

I updated my initial comment about Ukrainian counting to make it more understandable (I hope). Ukrainian also needs three forms, I think they are same as in Croatian

**Comment by milotype** [comment]
Some more nformations …
I found a website which explains (somewhat) the differences between **Internationalization (i18n)** and **Localization (l10n)**
[i18n vs l10n — what’s the diff?](https://blog.mozilla.org/l10n/2011/12/14/i18n-vs-l10n-whats-the-diff/)

**Comment by cdrini** [comment]
Ok, I did some hunting around for some examples and found this file: https://translationproject.org/PO-files/uk/anubis-4.2.uk.po from this site: https://translationproject.org/domain/anubis.html .

@bicolino34 I think you will need to add this line: `"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"` in a similar location, and then change the plural translations to be like so:

```
msgid "Child [%lu] finished. %s. %d client left."
msgid_plural "Child [%lu] finished. %s. %d clients left."
msgstr[0] "Процес-нащадок [%lu] закінчився. %s. Залишився %d клієнт."
msgstr[1] "Процес-нащадок [%lu] закінчився. %s. Залишилося %d клієнти."
msgstr[2] "Процес-нащадок [%lu] закінчився. %s. Залишилося %d клієнтів."
```

Is it clear what `[0]`, `[1]`, and `[2]` refer to?

**Comment by bicolino34** [comment]
@cdrini I think this issue can be closed. But it may be a good idea to add this info to [i18n Contributor's Guide](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md) and recommend translators to use [Poedit](https://poedit.net/) for automatic adding of these forms

**Comment by tfmorris** [comment]
Sorry to have missed the earlier ping, but I can confirm that @milotype has the correct info. More than two plural forms is definitely supported.

**Comment by bicolino34** [comment]
This functionality is already available in .po file type
