### ISSUE TITLE
Add Search Page Navigation

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6542]
Make it easier to switch between the different types of searches open library offers by including a tab bar, like that used on book pages, on search pages.

### Proposal & Constraints
- Create a macro, `SearchNavBar.html` that renders this component

![2022-04-21-16-00-52](https://user-images.githubusercontent.com/6251786/168118532-81606093-9a7a-42ac-8a0f-30ccbd904a05.png)

- The tabs should be:
    - Books (handles all/title searches)
    - Authors
    - Full text
    - Subjects
    - Lists
    - Advanced

- Render that component on each of the search html templates in the position depicted above

- re-use the css classes of the tab bar on book pages

**Comment by tuminzee** [comment]
@cdrini you mentioned this issue in one of the pr's which is merged, is this issue still open?

**Comment by mekarpeles** [comment]
@tuminzee this is still open and help wanted.

Also, if possible, let's please move "Hits" underneath the search results, e.g. 
![search-nav](https://user-images.githubusercontent.com/978325/175785963-d443625c-961d-4d9f-af3a-7b6c76b62e3c.png)
