### ISSUE TITLE
How can I query the author's most recent works using the dev API?

### ISSUE THREAD

**Issue by jwoudenberg** [internetarchive/openlibrary#6547]
### Question
How can I query the author's most recent works using the dev API?

### Additional context
I'd like to create an RSS feed of an author's work, so I can get an update when a new work by an author is released. To help with this I'd like to query the author's most recent works, basically obtain in JSON format the data presented in the 'works' section on an author's web page, when those works are sorted according to the 'Most Recent' filter. For example: [Martha Well's page](https://openlibrary.org/authors/OL221294A/Martha_Wells?sort=new&page=1).

I've tried using the [author api](https://openlibrary.org/dev/docs/api/authors), and can get a list of author's works that way ([example](https://openlibrary.org/authors/OL221294A/works.json)), but don't know how to sort the works similar to the 'Most Recent' ordering in the UI (I imagine this is by first publish date?). I can imagine I might be missing the right query parameter, or maybe I'm using the wrong API entirely.

**Update:** I think I found the name of the parameter used internally to render the author works page [here](https://github.com/internetarchive/openlibrary/blob/78c8418b8e88e30153350d1a0ecdbfda2fda7ebb/openlibrary/plugins/worksearch/code.py#L832): It's `sort: 'first_publish_year desc'`. I have tried a couple of query param invocations on the `/authors/OL221294A/works.json` endpoint using this knowledge, but haven't been able to manage ordering of the returned works. Probably I'm overlooking something!

### Issue resolution criteria
As mentioned above, I'd be super grateful if anyone could help me get a listing of author works in the order shown on the author html page.

### Stakeholders
I don't know who to tag here, sorry!

**Comment by tuminzee** [comment]
@jwoudenberg I hope Open Library's documentation helped you. But I see that you are facing issues 
I would like to tag @cdrini & @jimchamp they will be able to help you to solve this one.

I wish you a good day ahead 😄

**Comment by cdrini** [comment]
Hi @jwoudenberg ! Thanks for the ping, @tuminzee  :) 

You should be able to use the main search endpoint like so to get an author's works: https://openlibrary.org/search?q=author_key%3A%22OL221294A%22&mode=everything

You can use the UI to select the desired sorting, then change `/search` -> `/search.json` to get it as json.

E.g. this: https://openlibrary.org/search.json?mode=everything&q=author_key%3A%22OL221294A%22&sort=new

Let me know if you have any questions!

**Comment by jwoudenberg** [comment]
That's super clear, many thanks!
