### ISSUE TITLE
Don't allow merging a work with more than 50 editions into another work

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6558]
Sub-task of #6556

The Merge UI currently allows this, but only moves over the first 50 editions! Leaving the rest in a sort of limbo.

Prevent this from being allowed, or investigate if we can increase it to a larger limit, but we'll probably still need to block at whatever limit that is.

### Stakeholders
@mheiman @dcapillae

**Comment by mheiman** [comment]
I'll dig into what's creating the limitation and report back.

**Comment by jimman2003** [comment]
My guess is infogami, I think I had found a reference to 50 there
