### ISSUE TITLE
https://openlibrary.org/random seems to have only two works available 

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6592]
If someone goes to https://openlibrary.org/random repeatedly, the results will be one of two works. The two works seem to change over time.
### Relevant url?

https://openlibrary.org/random
### Steps to Reproduce

1. Go to ...https://openlibrary.org/random several times.
2. Do ...Note that you will only ever get one of the two same titles.

* Actual: See description above.
* Expected: Given all the works on Open Library, it seems a random selection will rarely repeat.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by cclauss** [comment]
On macOS, the command: `open https://openlibrary.org/random https://openlibrary.org/random https://openlibrary.org/random https://openlibrary.org/random https://openlibrary.org/random` will open multiple tabs in the browser which prove that this is a problem.
