### ISSUE TITLE
Delete button on author pages has vanished

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6599]
There used to be a delete button on the top right corner when editing author pages for librarians, but it's no longer there.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/170792553-9e7546dd-fa71-47b9-94ca-8658f59c5f7d.png)

### Steps to Reproduce
1. Go to eg. http://localhost:8080/authors/OL18319A/Mark_Twain/edit

* Actual: No delete button
* Expected: Delete button

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF 100
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@jimchamp

**Comment by mekarpeles** [comment]
This is a duplicate of #6583, @cdrini requested we close this one
