### ISSUE TITLE
Page position incorrect when clicking book page navbar link

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6627]
Whenever a patron clicks on a book page navbar link, the navbar partially obscures the section that they have navigated to.  A patron must scroll up a small amount to see the section's header.

### Evidence / Screenshot (if possible)
![desktop](https://user-images.githubusercontent.com/28732543/171907481-fc5c7eda-9c83-4fbd-9f5d-31f3f2ab6f7d.gif)
_Desktop view_

![mobile_jump_link](https://user-images.githubusercontent.com/28732543/171907498-9d7a54a0-5157-4520-b9c9-95d472bf52af.gif)
_Mobile view_

### Relevant url?

Any edition or work page.

### Steps to Reproduce

1. Go to any edition or work page.
2. Click on a navbar link.
3. Observe the page after the scrolling has stopped.

* Actual: The top of the target section is obscured by the navbar.
* Expected: The navbar rests neatly above the target section.

### Details

- **Logged in (Y/N)?**N/A
- **Browser type/version?** N/A 
- **Operating system?**N/A
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Apply enough `scroll-padding` to the top of the `html` element to offset the incorrect positioning.  You will likely need to use different amounts for mobile and desktop.

**Comment by Jyotiraditya24** [comment]
hey, i would like to resolve this problem

**Comment by Jyotiraditya24** [comment]
I am new to open source so how I can get the code of the above website

**Comment by jimchamp** [comment]
@Jyotiraditya24 I don't want to overwhelm you by assigning too many tasks.  Will gladly assign this to you once your other assigned issue is complete.
