### ISSUE TITLE
The My Lists page should link to instructions to create a list

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#6633]
I'm always frustrated when I go to the [__My Lists__ page](https://openlibrary.org/people/username/lists) but there are no [instructions on how to create a list](https://openlibrary.org/help/faq/reading-log#lists).

### Describe the problem that you'd like solved

https://openlibrary.org/people/username/lists should have link to https://openlibrary.org/help/faq/reading-log#lists
Perhaps the text `No lists yet!` could be a hyperlink to https://openlibrary.org/help/faq/reading-log#lists

**Comment by Jyotiraditya24** [comment]
hey , I am new to open source could I work on this issue

**Comment by jimchamp** [comment]
@Jyotiraditya24 yes you can!

You will have to make a change in [this template](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lists/lists.html), specifically in the else block towards the end of the file.

Some of the syntax in our templates may seem a bit strange at first glance.  [This documentation](https://webpy.org/docs/0.3/templetor) should help explain things.  I'm also happy to answer any questions that you may have.

**Comment by tuminzee** [comment]
@Jyotiraditya24 how is it going, if you need any help or if you have any issue you can reach out to lead @jimchamp

**Comment by Jyotiraditya24** [comment]
@tuminzee I think I have solved the issue will be opening a pr soon
