### ISSUE TITLE
Make it possible to add ISBN10 with hyphens in edition editing screen

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6634]
Related: #4548

Currently, it is not possible to add ISBN10 ID in edition editing screen if it contains hyphens. For example, 966-7007-30-2 can't be added, but if hyphens are deleted it will work fine. In contrast, ISBN13 can be added both with hyphens and without. I think that hyphens can be automatically deleted when adding ISBN to database without need to do it manually.

In my personal opinion, for end user no-hyphen format doesn't look good. Compare 966-7007-30-2 and 9667007302, first one is better distinguishable and it may be preferable for people with bad eyesight. @seabelis suggested having a setting that can be toggled on/off by user to show ISBNs either with hyphens or without

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
@hornc

**Comment by hornc** [comment]
Thanks for taking this on @scottbarnes 

You're looking at the correct page.

I didn't realise that the ISBN13 are currently saved with hyphens -- I consider that to be incorrect. The hyphens should be stripped out before saving to the database. The possible duplicates you noticed are going to be a problem for both ISBN10 and ISBN13.

I tested locally and confirmed that the hyphens are currently saved :(

```
isbn_10:
- '3442002109'
isbn_13:
- '9783442002108'
- 978-0-321-53496-5
- 978-0321534965
```

I think stripping any hyphens on save is required. I'm not sure whether that should be done in Python or here in js.

If Python is the best place for it, I can take a look if you like, but I'm happy to leave the js to you :)

**Comment by hornc** [comment]
Related: #4548

**Comment by scottbarnes** [comment]
Thanks for this, @hornc. I will try to come up with some behavior to strip hyphens (and other invalid characters) and check for duplicates in JS at the very least.

**Comment by scottbarnes** [comment]
I have created a WIP PR here: #6670. I still need to figure out where to add tests, and ensure what I have done is responsive to the needs of this issue.
