### ISSUE TITLE
ol_dump_latest has not worked since 21 March 2022

### ISSUE THREAD

**Issue by neilt** [internetarchive/openlibrary#6640]
Is anyone aware that the data dumps are not working.  I could not find an active ticket covering this issue.

 ol_dump_latest.txt.gz is currently 20 bytes.  The last good file I could find is dated 21 March 2022.

Even the May files that I could find in the archive for example the one dated 5/27 still only contain data from 21 March 2022.

Thanks

**Comment by cdrini** [comment]
Hi sorry about that ; the last one didn't work correctly. The 05/31 will be deleted soon, so the links should then be fixed. We've had some issues with it not running automatically, tracked in #5402 ).

The 05/27 dump should be correct; can you describe what problems you're seeing that makes you think the data is outdated?

**Comment by cdrini** [comment]
Can confirm the dumps are identical -_- . @mekarpeles and @cclauss just pushed up the new dump for 06-06 ; that appears to have correct up-to-date information.

**Comment by neilt** [comment]
Yes, that worked. The new file now has data through 2022-06-06.

Thanks
