### ISSUE TITLE
Show count of Reviews on Books Page nav bar 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6647]
### Describe the problem that you'd like solved

Currently, the books page Nav Bar shows a number next to editions (e.g. `View 3 Editions`) but no number is included next to `Reviews`. Let's add the number of reviews (i.e. the number of patrons who have submitted review tags for a book) to the nav bar.

![openlibrary org_works_OL1994300W_Echo_Of_Betrayal (1)](https://user-images.githubusercontent.com/978325/172921942-31d0b39b-6a35-4eab-a4de-34e8f52a99f1.png)

**Comment by vchapandrews** [comment]
Hi @mekarpeles,

(Apologies if this is all useless *garbáge*, this is my first attempt at contributing to an open-source project! :D)

I *believe* the change needs to be made in this file: [EditionNavBar.html](https://github.com/internetarchive/openlibrary/blob/877cc453df06bc59b393b9db7d200789afb7cb6b/openlibrary/macros/EditionNavBar.html) (Shown below)

```HTML
$def with (edition_count=1, show_observations=False)

<ul class="work-menu sticky">
  <li class="selected">
    <a href="#edition-overview">$_("Overview")</a>
  </li>
  <li>
    <a href="#editions-list">
      $ungettext('View %(count)s Edition', 'View %(count)s Editions', edition_count, count=edition_count)
    </a>
  </li>
  <li>
    <a href="#details">$_("Details")</a>
  </li>
  <li>
    <a href="#reader-observations">$_("Reviews")</a>
  </li>
  <li>
    <a href="#lists-section">$_("Lists")</a>
  </li>
  <li>
    <a href="#related-work-carousel">$_("Related Books")</a>
  </li>
</ul>
```

# Proposed changes

Change first line to include value for review count (which I believe is given by `num_rating` in your codebase?):

```diff
- $def with (edition_count=1, show_observations=False)
+ $def with (edition_count=1, num_ratings=0, show_observations=False)
```

Following this syntax (`$ungettext('View %(count)s Edition', 'View %(count)s Editions', edition_count, count=edition_count)`) from earlier in the file:

```diff
- <a href="#reader-observations">$_("Reviews")</a>
+ <a href="#reader-observations">
+   $ungettext('%(count)s Review', '%(count)s Reviews', num_ratings, count=num_ratings)
+ </a>
```

Any thoughts/feedback you have would be really helpful to me (if you have the time!)

**Comment by architsinghal-mriirs** [comment]
Hi @vchapandrews You should link the PR here.

**Comment by vchapandrews** [comment]
Hey @architsinghal-mriirs I've created a PR here: #6720
