### ISSUE TITLE
Trending Carousel missing default bookcovers

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6648]
This is a fairly prominently displayed feature on the homepage so it would be good to get this out quickly if the fix is easy

### Evidence / Screenshot (if possible)

![openlibrary org_ (2)](https://user-images.githubusercontent.com/978325/172922531-d2872dfd-d170-4a37-ac7d-11155ebaf1ad.png)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
@cdrini suggests this may be because we're using solr to fetch book records and they may not have covers, in which case we may be able to fall back to the cover service using edition id

**Comment by elotrocattivo** [comment]
To narrow down the source of the problem, I scrolled through the carousel a bit and made a list of the ids/titles that didn't show a cover:

OL27704443W – WHY MEN MARRY BITCHES
OL25515697W – Twisted Games
OL27295832W – Reminders of Him
OL13217802W – Quran
OL21155191W – How to Talk to Absolutely Anyone
OL27816616W – 2023 CFA Program Curriculum Level I Box Set
OL27492373W – Life Skills for Teens
OL27894406W – They the Pretty Stars
OL4777827W – Solutions manual [for] Microwave devices and circuits
OL709534W – Parlons schwytzertütsch
OL3729346W – Metode dan aneka teknik analisis bahasa
OL20756908W – Slaying Dragons
OL27953223W – Last on the list
OL21694149W – How to Survive a Pandemic
OL21723504W – General Principles of Astrology
OL20043290W – Small acts of leadership
OL9286598W – HARMONY’S WAY (THE BREEDS, VOLUME 2)
OL21197567W – Self-Acceptance
OL13292143W – Dirty movies
OL7120536W – Arquitectura religiose de la Habana en el siglo veinte
OL21370266W – Three Men in a Boat
OL21723504W – General Principles of Astrology
OL5543357W – Rizal and the development of national consciousness
