### ISSUE TITLE
Fundraiser banner malfunction

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#665]
@bfalling This only logs the problem, it doesn't handle it:
https://github.com/internetarchive/openlibrary/blob/baaf5c6a34356b64c17fefc8cbd3f8ef3e42afb4/openlibrary/plugins/upstream/utils.py#L691

If the url doesn't load (i.e. with archive.org blocked by firewall), there's no way to set the cookie and the user can't dismiss the banner. It's very annoying.

**Comment by LeadSongDog** [comment]
@mekarpeles This is back with a vengance. Not only can I not dismiss the banner, but it stops me from editing too. Lack of access to archive.org should not block the use of openlibrary.org

**Comment by LeadSongDog** [comment]
#1709 seems to relate. Sending all this unwanted analytics code to the browser is highly problematic for users on locked-down platforms, as are common on public-access, school labs, or corporate environments.

**Comment by LeadSongDog** [comment]
Evidently #1709 was a distinct issue. Editing is re-enabled, but it remains impossible to set the cookie from archive.org

**Comment by guyjeangilles** [comment]
@LeadSongDog is this still an issue? I don't remember having problems with the fundraiser banner recently. I assume the fundraiser banner will come back and December it'd be best to be proactive than reactive if this is still a bug.

**Comment by LeadSongDog** [comment]
I can't tell if the issue is gone or just latent, waiting for return of the banner. Perhaps someone can try activating it on a dev instance to see what happens?

**Comment by guyjeangilles** [comment]
I'm gonna assign jdlrobson (not tagging as requested) per slack discussions since this seems front-end related

**Comment by jdlrobson** [comment]
@mekarpeles can we enable this banner code on dev?

From what i remember the banner is maintained in a repo outside ours and the js file varies based on date so there is little we can do here except track down and report the problem.

**Comment by LeadSongDog** [comment]
Could it not somehow be proxied through OL? As a general principle, it's a bad idea to require that a client has access to an off-host redirect target. It begs for MITM attacks.

**Comment by mekarpeles** [comment]
This should be resolved and there's an iframe approach that I believe IA Product team is working on. Tagging @bfalling and closing this one.
