### ISSUE TITLE
Local docker `make test` no longer works

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#6650]
The Docker instructions at https://github.com/internetarchive/openlibrary/blob/master/docker/README.md give the command

    docker-compose run --rm home make test

to run the standard tests. This now fails with:

```
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
Creating openlibrary_home_run ... done
make test-py && npm run test && make test-i18n
make[1]: Entering directory '/openlibrary'
pytest . --ignore=tests/integration --ignore=infogami --ignore=vendor --ignore=node_modules
make[1]: pytest: Command not found
make[1]: *** [Makefile:77: test-py] Error 127
make[1]: Leaving directory '/openlibrary'
make: *** [Makefile:84: test] Error 2
```

`pytest` is not available as a command in the Docker image.

A workaround to run at least the python tests locally is:

    docker-compose run --rm home python -m pytest openlibrary/

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cclauss** [comment]
Strange...  Works for me.

% `docker-compose run --rm home make test`
```
WARN[0000] The "HOSTNAME" variable is not set. Defaulting to a blank string.
make[1]: Entering directory '/openlibrary'
pytest . --ignore=tests/integration --ignore=infogami --ignore=vendor --ignore=node_modules
===================== test session starts =====================
platform linux -- Python 3.9.4, pytest-7.1.2, pluggy-1.0.0
rootdir: /openlibrary
plugins: anyio-3.6.1, asyncio-0.18.3
asyncio: mode=legacy
collecting ... Couldn't find statsd_server section in config
pytest_configure None
collected 1248 items

openlibrary/catalog/add_book/tests/test_add_book.py .....................................    [  2%]
openlibrary/catalog/add_book/tests/test_load_book.py ..........                              [  3%]
openlibrary/catalog/add_book/tests/test_match.py .x                                          [  3%]

    [ ... ]

scripts/tests/test_partner_batch_imports.py .......                                          [ 99%]
scripts/tests/test_solr_updater.py ...                                                       [ 99%]
tests/test_docker_compose.py ..                                                              [100%]

===================== warnings summary =====================

    [ ... ]

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============== 1152 passed, 25 skipped, 17 xfailed, 54 xpassed, 35 warnings in 62.44s (0:01:02) ==============
make[1]: Leaving directory '/openlibrary'
```

**Comment by jimchamp** [comment]
I'm also not able to reproduce this.
@cclauss. do you know if there were any recent changes to our Docker set-up that would require a rebuild in order for `pytest` to work?  I know that we have a dedicated Python image now, but I thought that we added that some time ago...

**Comment by hornc** [comment]
Thanks @jimchamp and @cclauss ;  I thought I had updated the Docker images recently, and I couldn't see any recent changes to python modules or pytest. I did a 
```
# Remove volumes that might have outdated dependencies/code
docker volume rm openlibrary_ol-build openlibrary_ol-nodemodules openlibrary_ol-vendor
```

then a simple

      docker-compose build

seemed to fix it, with matching pytest versions to what is posted above. I should have tried that first :D
