### ISSUE TITLE
Move msg txt beneath Waitlist Button

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6652]
Currently, the text appears first, causing the buttons to misalign in carousels.

Also, we should consider using the same primary action blue for waiting list. The text is descriptive enough, I don't think the red color is necessary.

![openlibrary org_ (3)](https://user-images.githubusercontent.com/978325/173215229-7dd3b675-d96c-453b-b970-15a1f5c423a1.png)

### Describe the problem that you'd like solved

![testing openlibrary org_1337_](https://user-images.githubusercontent.com/978325/173215119-3797d9c7-1be7-4e55-b920-773aa42fef4c.png)

Also, consider shortening text to "[2] reader(s) in line" to avoid overflow

![testing openlibrary org_1337_ (1)](https://user-images.githubusercontent.com/978325/173215117-9f2dd1ad-5427-42e6-9fb6-ef9b70163c68.png)

Another option is showing the waiting list length in the button itself:

![testing openlibrary org_1337_ (2)](https://user-images.githubusercontent.com/978325/173215273-a91bc7c4-5452-424d-8a05-b59318808201.png)

### Diff

```
diff --git a/openlibrary/macros/LoanStatus.html b/openlibrary/macros/LoanStatus.html
index 16686e15a..319f36b1e 100644
--- a/openlibrary/macros/LoanStatus.html
+++ b/openlibrary/macros/LoanStatus.html
@@ -96,16 +96,16 @@ $elif availability.get('is_lendable'):
     $else:
       $# "JOIN-WAITLIST" button
       $ wlsize = availability.get('users_on_waitlist') or availability.get('num_waitlist')
+      <form method="POST" action="$borrow_link" class="join-waitlist waitinglist-form">
+        <input type="hidden" name="action" value="join-waitinglist"/>
+        <input type="submit" class="cta-btn cta-btn--unavailable" id="waitlist_ebook" value="$_('Join Waitlist')"/>
+      </form>
       <p class="waitinglist-message">
         $if wlsize:
           $_("Readers waiting for this title: %(count)s", count=wlsize)
         $else:
           $_("You'll be next in line.")
       </p>
-      <form method="POST" action="$borrow_link" class="join-waitlist waitinglist-form">
-        <input type="hidden" name="action" value="join-waitinglist"/>
-        <input type="submit" class="cta-btn cta-btn--unavailable" id="waitlist_ebook" value="$_('Join Waitlist')"/>
-      </form>
   $else:
     $# Checked out: Show checkout out + preview if secondary, else just preview
     <div class="cta-button-group">
diff --git a/static/css/components/buttonCta.less b/static/css/components/buttonCta.less
index 2fa653019..fe47d6ff5 100644
--- a/static/css/components/buttonCta.less
+++ b/static/css/components/buttonCta.less
@@ -59,9 +59,9 @@ a.cta-btn {
   }
 
   &--unavailable {
-    background-color: @burnt-sienna;
+    background-color: @primary-blue;
     color: @white;
-    &:hover { background-color: darken(@burnt-sienna, 20%); }
+    &:hover { background-color: darken(@primary-blue, 20%); }
   }
   &--shell, &--shell:link, &--shell:visited {
     background-color: @white;
```

**Comment by constantinazouni** [comment]
I think that users are used to connect the blue button with specific actions (borrow, sign up etc). In my opinion the "join waitlist" button should have a different color like orange which is an opposite for blue button and is used for actions like "join". Also, I think that is better not to add info that changes dynamically at a button so I think that the "2 readers in line" should be below the button.

**Comment by cdrini** [comment]
Decision on community call:

- Remove "You are next in line!" in carousels
- Remove orange, replace with same blue

Undecided - For the IASoc:
- Switch waitlist to "Place a hold" -- check with IA folks to check consistency?
- Replace preview button with preview link below cover
- "Check libraries" button should be different from the primary blue CTA

**Comment by tuminzee** [comment]
@constantinazouni would you like to work on this issue?
