### ISSUE TITLE
Duplicate the pagination widget on lists

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6660]
The pagination widget is very low on a lists page, and it can be difficult to recognize there are multiple pages. On other pages, eg https://openlibrary.org/authors/OL218025A/Brad_Meltzer , we have the pagination widget duplicated at the top and bottom of the list of books. Let's do the same!

### Stakeholders
@seabelis

**Comment by architsinghal-mriirs** [comment]
Hi @cdrini , I'd like to work on this issue. You can assign this issue to me !
Thanks and Regards
Archit Singhal

**Comment by jimchamp** [comment]
Hi @architsinghal-mriirs!  Sorry that I didn't see your comment sooner.  Is this something that you'd still like to work on?

**Comment by ciannellaleo** [comment]
Hi @jimchamp, can you assign me to this issue, please?

**Comment by muditjuneja** [comment]
Are we taking about a page like this - https://openlibrary.org/search?subject=Magic.
This has the pagination widget only at the bottom. And we want it to be there at the top as well right?

**Comment by mekarpeles** [comment]
@ciannellaleo go for it!

**Comment by ciannellaleo** [comment]
@mekarpeles, should I change the page that @muditjuneja commented too?

**Comment by jimchamp** [comment]
@ciannellaleo sorry for the delay!  We're talking about list pages only (you can see an example [here](https://openlibrary.org/people/seabelis/lists/OL143333L/unknown)).
The template for this view is here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/list/view_body.html
The new `Pager` should probably be between the list description and the list results.

**Comment by ciannellaleo** [comment]
Well, I am getting trouble running the application. I have read all the documentation and have done everything right but still got infogami error. Yes, I have cloned the repository via SSH. Can anybody help me, please?

**Comment by jimchamp** [comment]
What commands were executed, and what were the errors?

**Comment by ciannellaleo** [comment]
I have forked the repository and cloned it to my local environment via SSH. I tried to clone directly from openlibrary too, but got the same error. I have executed the basic commands to build the docker image, following this https://github.com/internetarchive/openlibrary/blob/master/docker/README.md

![image](https://user-images.githubusercontent.com/96359865/187274358-366ce2c2-38a3-4fdd-a032-23c19e820b7b.png)

**Comment by cdrini** [comment]
Hi @ciannellaleo ; hmmm that's a messy error... It seems like all the containers exited with `No module named 'infogami'`.... What operating system are you using?

**Comment by ciannellaleo** [comment]
Hello @cdrini. I am using Windows. Docker version 20.10.17, build 100c701 and docker-compose version 1.29.2, build 5becea4c

**Comment by justkeeppushing** [comment]
Hello, I was able to get this to work with `docker compose -f docker-compose.yml -f docker-compose.override.yml up` (distinct from 'docker-compose' binary from apt). I am on the same Docker build. Try using this `docker compose` which is exposed from Docker Desktop's WSL2 integration. 

if you don't have WSL2 docker integration enabled, I would suggest to  do so and uninstall any existing binary's of Docker from your distro (you can check with dpkg-query -l | grep docker) then look into enabling this integration from Docker Desktop settings > Resources > WSL integration and look for your repo. 

I was not able to get this to work with the existing 1.29.2 docker-compose binary either, so I think that is your problem.
