### ISSUE TITLE
Reading Log Check-Ins

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6662]
This feature is required for Yearly Reading goals:

When someone clicks currently reading or already read, present options underneath the button to:
- add/update started date (today by default)
- add a check-in
- add a completed date (today by default)
- if "currently reading" end date shouldn't appear
- if a started date is set, we could show "you started reading on [date]" with e.g. a dotted underline which lets patron update date. (this is meant to be illustrative design-wise, not prescriptive).

Constraints: Add multiple, manually editable "Started-Reading" & "Finished-Reading" Dates

**Comment by bicolino34** [comment]
Related document: https://docs.google.com/document/d/1Zf43Ti6x3LVpPrpDMvoDgtSzxhYBYHSQXcOwHyHB1wU/edit

**Comment by bicolino34** [comment]
@mekarpeles I think this should be reopened as there is still no UI. So, it's still a work in progress
