### ISSUE TITLE
Translate / the Help Page into Chinese

### ISSUE THREAD

**Issue by eguo3** [internetarchive/openlibrary#6664]
### Question
Hi! I found that the Help Page (https://openlibrary.org/help) hasn't had a Chinese translation. I tried to add the translation but I don't have permission to edit the page. Could you help me with the permission? Thank you! :)

### Stakeholders
@cdrini

**Comment by mekarpeles** [comment]
@eguo3 what is your Open Library username? I can add you to the librarians group so you can contribute these edits

**Comment by eguo3** [comment]
> @eguo3 what is your Open Library username? I can add you to the librarians group so you can contribute these edits

Hi @mekarpeles ! My OL name is eguo3. Thanks! :)

**Comment by mekarpeles** [comment]
@eguo3 you should now have librarian permissions!
