### ISSUE TITLE
Change homepage trending carousel from 1-day to either 1 or 6 hours (whichever is better)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6674]
In our homepage, we currently render a carousel which shows the books most "trending today":
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html#L23

We want to update the plugins/openlibrary/api.py API to allow `/custom?days=&hours=`

https://github.com/internetarchive/openlibrary/blob/628ca04c4f345dfacc44a205f40028af5c60f9f3/openlibrary/views/loanstats.py#L55

get_trending_books will also need to be updated to include hours=0
https://github.com/internetarchive/openlibrary/blob/628ca04c4f345dfacc44a205f40028af5c60f9f3/openlibrary/views/loanstats.py#L50

Proposal, update `dateutil.date_n_days_ago` to be a function that takes (day=0 and hours=0)

If the `period` is `custom` then directly pass in the `days` to  `since_days` and `hours` to `since_hours` (new field).

https://github.com/internetarchive/openlibrary/blob/628ca04c4f345dfacc44a205f40028af5c60f9f3/openlibrary/plugins/openlibrary/api.py#L74-L78

Let's go for **2 hours** as the limit and try this on testing.

**Comment by cdrini** [comment]
Might want to change what the header links to
