### ISSUE TITLE
Ability to read entire embedded books from an external website. 

### ISSUE THREAD

**Issue by digitals82** [internetarchive/openlibrary#6694]
Hello,

I'm creating a website to house a specific genre of young adult books that are hosted on OpenLibrary. My goal is to make reading as fun and accessible for kids to navigate as they would Netflix and to also promote new books and authors. The website has been created using a Netflix-style plugin on WordPress. However, there is one major issue that is defeating the purpose of this whole website. 

The books that I embed only allow a preview and the user needs to sign in to access the whole book. Even if I'm logged into OpenLibrary outside of the website, it still won't allow me to read the entire text. I'd like to know if there is a way that I can either-

- Have the user sign in to OpenLibrary through my website?

- Have my website constantly logged in to OpenLibrary/remove the preview restriction? 

I've attached a video to demonstrate my issue.

Thanks for your time! 

Scott

https://user-images.githubusercontent.com/108327598/176129382-52cb7edb-394c-45c6-a430-9ed61c5872c9.mp4

**Comment by mekarpeles** [comment]
Since this can't be solved on openlibrary.org, closing the issue and will have @bfalling followup here once there's more info

**Comment by digitals82** [comment]
Great, thank you @mekarpeles ! I'm glad you like the project. If it takes off, I plan on branching out with different genres of children's literature!

I am currently paying a web developer to see if they can solve this issue, do you think it is something they can achieve, or would it only be possible to do it internally by @bfalling ? Perhaps I can shoot you a quick email?

Thanks again, I really appreciate the support!
