### ISSUE TITLE
Borrow buttons no longer reflect ACS status

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#670]

**Comment by guyjeangilles** [comment]
@mekarpeles Can you describe what ACS status is? That will make it easier for a volunteer to potentially contribute to this issue

I've added labels per issue context: let me know your thoughts

**Comment by cdrini** [comment]
This is pretty old and doesn't have enough info; let's close. Mek can reopen if it's still an issue.

**Comment by tfmorris** [comment]
ACS = Adobe Content Server. It's a DRM thing.
