### ISSUE TITLE
Profile hamburger doesn't override "More" navigation button on Desktop

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6705]
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/58372007/176993179-3b502a97-27a9-4744-a457-3d7660ef95f5.png)

### Steps to Reproduce
1. Go to any page
2. Do open browser for half a screen and open profile hamburger

* Actual: hamburger dropdown doesn't override "More" button
* Expected: hamburger dropdown overrides "More" button

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Mozilla Firefox 102.0 (64-bit)
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by scottbarnes** [comment]
I'd like to try addressing this, either by adjusting the z-index or some sort of relative/absolute positioning. I'll submit a PR and we'll see if it's any use.

**Comment by scottbarnes** [comment]
I created a PR at #6708.
