### ISSUE TITLE
Add Sambahsa to language selection

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6709]
Sambahsa is missing from language selection when adding a book.

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL38582732M/Ocolo_id_specule_ed_quo_alice_trohv_ter/edit
2. Do ...try to add Sambahsa as a language

* Actual: language not available
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
This is a tough one! This language doesn't have a MARC language code 😬 https://www.loc.gov/marc/languages/language_code.html The marc language code on ia/the marc record is `art`, which stands for "Artificial Language (other)" :/ I set it to this for now on Open Library, but not sure what we can do long term. CC @hornc

**Comment by mekarpeles** [comment]
I'd love to increase language support, though I'd like to mark this as not planned for now.
