### ISSUE TITLE
Integration tests fail looking for auth.yaml

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#672]
The need for this file or its intended contents doesn't appear to be documented anywhere. Following the instructions from the [README](https://github.com/internetarchive/openlibrary/blob/master/tests/integration/README.md) (as amended), results in the following:

```
$ pytest
============================= test session starts ==============================
platform darwin -- Python 3.6.1, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/tfmorris/git/openlibrary, inifile:
collected 17 items / 2 errors 

==================================== ERRORS ====================================
_______________ ERROR collecting tests/integration/test_auth.py ________________
test_auth.py:12: in <module>
    olsession = OLSession()
__init__.py:15: in __init__
    with open('auth.yaml', 'r') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'auth.yaml'
_______________ ERROR collecting tests/integration/test_loans.py _______________
test_loans.py:12: in <module>
    olsession = OLSession()
__init__.py:15: in __init__
    with open('auth.yaml', 'r') as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'auth.yaml'
!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 2 error in 0.28 seconds ============================

```

**Comment by guyjeangilles** [comment]
@tfmorris @mekarpeles Is this still a problem?

**Comment by tfmorris** [comment]
Still a bug, but could be obsolete code. It appears that @bfalling authored the README, so perhaps he or @hornc knows more.

**Comment by mekarpeles** [comment]
I think many of our integration tests are stale at this point. We might want a small epic detailing how we might prune our integration tests to a subset of things which works (rather than calling out what doesn't work -- which is a lot).

I support us creating such an issue -- for this issue, I am going to close.
