### ISSUE TITLE
Fix Styling of Unified Search

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6728]
Currently, if you go to https://testing.openlibrary.org/search and then click through the search navigation tabs, the search inputs, buttons, `hits` styling are all different.

Can we consolidate / fix our styles so that the input boxed, the submit buttons, and the treatments of things like `hits` look consistent across the pages?

See:
https://github.com/internetarchive/openlibrary/pull/6688#pullrequestreview-1033210746

### Evidence / Screenshot (if possible)

![template_candidate](https://user-images.githubusercontent.com/978325/178352576-dd052972-591f-4e58-8b31-1a1438acce6c.gif)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by Calerid** [comment]
I will take a look at this.

**Comment by chintanpuggalok** [comment]
Is this open?

**Comment by mekarpeles** [comment]
@Calerid sure, give this a go if you'd like to help standardize the size and colors of the `hits` results on those pages
