### ISSUE TITLE
Confirmation following work merge is broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6746]
The confirmation message following a work merge previously indicated which IDs had been merged. Now the message just says, 
`[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object] Merge request closed
`
The work merge itself appears to be successful.
### Evidence / Screenshot (if possible)
<img width="1298" alt="Screenshot 2022-07-15 at 08 04 09" src="https://user-images.githubusercontent.com/17739465/179161122-7c5fb017-ab09-46f0-ac26-56353487ad91.png">

### Steps to Reproduce

1. Go to ...a work merge url
2. Do ...merge works. 

* Actual: Message as noted above.
* Expected: A list of IDs successfully merged.

### Details

- **Logged in (Y/N)?** y
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp @mekarpeles @cdrini @mheiman @dcapillae

**Comment by jimchamp** [comment]
A fix for this is on testing now.  Will push for a quick review and deployment of the solution early next week.
