### ISSUE TITLE
Pls  help, i have got Installation Issue

### ISSUE THREAD

**Issue by saphemmy** [internetarchive/openlibrary#675]
Been trying to install the Solution...But been Futile.
My mail is saphemmy@gmail.com

**Comment by mekarpeles** [comment]
@saphemmy what installation issue are you hitting?

**Comment by saphemmy** [comment]
Several times tried installing openlibrary on my ubuntu machine. Its not
just installing

**Comment by mekarpeles** [comment]
@saphemmy can you please provide an error log, a line which shows where things may be breaking, or any additional information? Otherwise, we cannot help.

**Comment by saphemmy** [comment]
Will start the installation again now

**Comment by mekarpeles** [comment]
Please re-open this issue with a title that reflects the specific installation problem encountered, as well as an error log. Thanks for your help!

**Comment by saphemmy** [comment]
I will do that as soon as possible...was held up by office dev. Thanks for
your patience

On Dec 19, 2017 12:04 AM, "Michael E. Karpeles" <notifications@github.com>
wrote:

Please re-open this issue with a title that reflects the specific
installation problem encountered, as well as an error log. Thanks for your
help!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/internetarchive/openlibrary/issues/675#issuecomment-352586073>,
or mute the thread
