### ISSUE TITLE
LearnAwesome.org ID isn't clearly visible

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6759]
### Evidence / Screenshot (if possible)
![зображення](https://user-images.githubusercontent.com/58372007/179740005-fc5f40fd-39d3-447c-bc58-c9a4171a6fb1.png)

### Relevant url?
https://openlibrary.org/books/OL32336498M/Atomic_Habits
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?** Firefox 103 (64-bit)
- **Operating system?** Windows 8.1
- **Environment (prod/dev/local)?** prod

**Comment by DaaSH23** [comment]
I want to try, can I work on this issue?

**Comment by jimchamp** [comment]
@DaaSH23 you can work on this issue, but let's get some more details about the problem first.

@bicolino34 I'm not able to reproduce this on my machine:
![Screenshot from 2022-07-30 06-39-44](https://user-images.githubusercontent.com/28732543/181906680-abca8368-93fa-461f-a626-8299c7720fea.png)

I checked with Firefox and Chrome in both mobile and desktop view.  What browser are you using, @bicolino34?

**Comment by bicolino34** [comment]
I use Firefox 103 (64-bit). OS is Windows 8.1. May it be because of screen size, possibly? I also checked on mobile and it seems alright

**Comment by jimchamp** [comment]
Thanks @bicolino34!  It looks like the width of the first column is less than the length of the  "LearnAwesome.org":
![dl_dt_width](https://user-images.githubusercontent.com/28732543/182265445-220af699-8cad-4a22-913e-17ccd0912413.png)

@DaaSH23 the left column are `dt` elements, which have a width of `120px`.  Can you increase that to `130px` and see how that looks?  You'll have to change this file: https://github.com/internetarchive/openlibrary/blob/master/static/css/base/dl.less

**Comment by BoseSj** [comment]
Hi, I am quite a beginner at Open Source. I would like to try. Can I work on this issue?

**Comment by BoseSj** [comment]
I am not able to reproduce the issue, have tried in firefox (along with edge and chrome)  in the minimum width window.
It seems to be fine.
![image](https://user-images.githubusercontent.com/58129377/188266352-f5e384b1-0090-481e-8ed9-7c33365b65a6.png)
