### ISSUE TITLE
All book pages associated with authors with many works/editions perform poorly

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6767]
Poor performance and slow page loads have been blamed on long edition tables, however this problem appears to be related to the number of book records associated with an author. Work/edition pages for works with even one, unlinked edition take ~30 seconds to load. I have noticed this with Agatha Christie and Anton Chekhov, for example.

### Relevant url?

For example, https://openlibrary.org/books/OL15570797M/Hallowe'en_Party .

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL15570797M/Hallowe'en_Party
2. Do ...Note how long it takes for the page to load and that there is only one, unliked edition; no long edition table causing the performance issue.

* Actual:
* Expected: 

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**Chrome
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by seabelis** [comment]
The culprit is lists.

**Comment by jimchamp** [comment]
#6775 addresses this issue.
