### ISSUE TITLE
Lists section in nav sidebar in Reading log is rendered incorrectly in Ukrainian and German translations

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6768]
Lists section in nav sidebar in Reading log is rendered incorrectly in Ukrainian and German translations

### Evidence / Screenshot (if possible)
English:
![зображення](https://user-images.githubusercontent.com/58372007/179929055-fb737d59-61a2-4019-943b-77a4f85cabfb.png)
Ukrainian:
![зображення](https://user-images.githubusercontent.com/58372007/179929239-8dda1f3a-c311-4f13-932b-8cea41960b45.png)
German:
![зображення](https://user-images.githubusercontent.com/58372007/179929403-30f42d58-0f21-4e7a-a2f8-36f073534111.png)

### Steps to Reproduce

1. Go to My reading log
2. Do ... choose Ukrainian/German translation. Look at Lists section in nav sidebar

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 102.0.1 (64-bit)
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
Ah this is because we are using `float:right`.

This CSS should fix the issue:

```
.section-header.section-header-split::after {
  clear: both;
  display: block;
  content: "";
}
```

Search the codebase for `section-header-split` to see which LESS file this should go in :+1:

**Comment by bicolino34** [comment]
Update: I face issue only on my Windows 8.1 desktop but not on Linux Mint 21 Cinnamon

**Comment by scottbarnes** [comment]
I can have a go at this in a few minutes.
