### ISSUE TITLE
Edition form allows each edition to have only one language

### ISSUE THREAD

**Issue by sandbergja** [internetarchive/openlibrary#677]
This is troublesome for entering bilingual books (including dictionaries) and other multilingual materials.  Thanks for looking into this!

**Comment by LeadSongDog** [comment]
@sandbergja It works fine for me, in Librarian mode, using Chrome on Windows 7. It is a bit simplistic, but the basic function is there. https://openlibrary.org/books/OL13503633M/Andria?b=5&a=4&_compare=Compare&m=diff

**Comment by sandbergja** [comment]
Ahhh, thanks!  I didn't think of checking Librarian mode.

**Comment by tfmorris** [comment]
@sandbergja If you're satisfied that this is not a bug, could you please close the issue? Thanks!
