### ISSUE TITLE
List Widget: Asynchronously fetch patron lists

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6775]
### Describe the problem that you'd like solved

If a list widget is present on an Open Library page, the page will not load until the list widget has been rendered.  If a patron has lists with a large amount of entries, the list widget can take upwards of 30 seconds to render.  This makes the site painfully slow for such patrons, as list widgets are present on every book page.

### Proposal & Constraints

Let's asynchronously fetch the lists that are displayed in our list widget (highlighted below).
![list_of_lists](https://user-images.githubusercontent.com/28732543/180500694-cecb2a24-4073-40b3-b64c-c71b23a2925a.png)

The highlighted portion can initially be some type of loading animation, which can be replaced with the list names when they are available.

### Stakeholders

@seabelis

**Comment by mekarpeles** [comment]
Once we have a solution to this issue, if we can get me, @seabelis and yourself (@jimchamp) to test on testing v. prod (load times with debug=true) this would be great
