### ISSUE TITLE
`/merges` entries should be displayed in descending order

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6780]
Today, entries in all `/merges` views are displayed in order of `created` timestamp, ascending.  They should instead by ordered by `created` timestamp, __descending__.

### Relevant url?

https://openlibrary.org/merges

### Steps to Reproduce

1. Go to any `/merges` view.
2. Note the order of the merge requests in the table.

* Actual: Entries are listed from oldest to newest.
* Expected: Entries are listed from newest to oldest.

### Details

- **Logged in (Y/N)?**N
- **Browser type/version?**Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

When we fetch the requests for the `/merges` table, we should pass `order='created desc'` to the `CommunityEditsQueue.get_requests()` call.

### Related files

`/merges` controller is in [/openlibrary/plugins/upstream/edits.py](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/edits.py)

**Comment by vintagemind** [comment]
Hi! So the issue we're facing here is that the requests at https://openlibrary.org/merges is listed from oldest to newest but we want it to be from newest to oldest right?

**Comment by jimchamp** [comment]
Yes, that's exactly the problem!

**Comment by vintagemind** [comment]
I see, I am seeing the code now.

**Comment by vintagemind** [comment]
Have you tried order='created desc'?

**Comment by vintagemind** [comment]
And I am very sorry, but it seems like I can't set up OpenLibrary locally as I have some restrictions on my computer.

**Comment by vintagemind** [comment]
Which database are you using for this program? MySQL?

**Comment by jimchamp** [comment]
> Have you tried order='created desc'?

I'm sure that will work.  Would you like to open a pull request with that change?

We use Postgres for our production and local dev environment.  If we do use MySQL, it's for our Python unit tests only.
