### ISSUE TITLE
Search inside solr sometimes gives a timeout

### ISSUE THREAD

**Issue by EdwardBetts** [internetarchive/openlibrary#68]
Search inside solr sometimes gives a timeout, for example:

http://openlibrary.org/search/inside?q=oakdale+%22san+francisco%22

Open Library doesn't catch the timeout, it just returns a blank page.

**Comment by tfmorris** [comment]
This doesn't timeout currently and is over six years old, so closing.

**Comment by mekarpeles** [comment]
Seems to still occasionally happen (documenting here)
```
  File "/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/plugins/worksearch/code.py", line 178, in execute_solr_query
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out
```

**Comment by tfmorris** [comment]
> Seems to still occasionally happen (documenting here)

Reopened.
@mekarpeles Do you have information on which URL(s) triggered this? Any idea of the frequency?

**Comment by tfmorris** [comment]
"Search Inside" is actually using an archive.org API, so I suspect we have no way to fix or influence it.

**Comment by guyjeangilles** [comment]
Can we search inside without using the IA API/are we willing to implement our own search inside feature? If the answer to both is no, I propose closing this.
