### ISSUE TITLE
Switch Provisioning to use Ansible w/ a Production & Developer playbook

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#680]
In 2018 we intend to migrate from trusy to xenial -- our internal provisioning isn't as automatic as our vagrant setup and we'd like to get to a position where we only have one canonical build process which adjusts based on tags like `production`, `staging` and `developer`

**Comment by mekarpeles** [comment]
We currently use Vagrant to run a script called bootstrap.sh: https://github.com/internetarchive/openlibrary/blob/master/scripts/bootstrap.sh

There's a start to an ansible playbook in the `provisioning/` directory:
https://github.com/internetarchive/openlibrary/blob/master/provisioning/playbook.yml

The goal of this issue is to change our existing vagrant setup to use ansible exclusively (instead of scripts/bootstrap.sh), to do all provisioning, and to have a different playbook for `development` and `production` (we have a playbook started).

**Comment by rohitjain00** [comment]
@salman-bhai any followup on this?

**Comment by mekarpeles** [comment]
This is a subtask of #2036

**Comment by mekarpeles** [comment]
@abezella — [this old ansible playbook](https://github.com/internetarchive/olsystem/commit/982aeb76e9aa8d7ad20b57c856aa2c9c9b002829) that @anandology had in `olsystem` back in 2014 (which has since been overwritten of some unknown reason?) seems to have useful ansible logic for setting more appropriate memory limits than the 64mb default. It also replaced `127.0.0.1` with a `0.0.0.0` broadcast which is still probably what we want to do.

Is this logic something we can/should add (back) to [your new ansible playbook](https://github.com/internetarchive/olsystem/blob/master/playbooks/site.yml) in `olsystem`?

We ideally want this number to be *variable* based on the vm’s capacity https://github.com/internetarchive/olsystem/commit/982aeb76e9aa8d7ad20b57c856aa2c9c9b002829

**Comment by mekarpeles** [comment]
@hornc and I finally got our 1st VM provisioned as xenial with @abezella's help -- `ol-mem4` -- and added to our memcached pool

1. Andy provisioned the machine w/ a new ansible playbook in `olsystem`
2. We manually (for now) updated `/etc/memcached.conf` to change the local address to `0.0.0.0` instead of `127.0.0.1` so that it broadcasts to all machines in our cluster and also the memory from 64mb to 9500mb. @abezella, this should be incorporated into the ansible playbook, along with step 4 (which is the ferm rules)
3. @hornc and I made modifications to `olsystem` in order to include `ol-mem4` in the pool -- see: https://github.com/internetarchive/olsystem/pull/62
4. We added a xenial firewall rule to `/etc/ferm/input` -- we added a file to this directory called `ol` with the values `proto tcp dport 11211 ACCEPT;` and then ran `sudo service ferm reload` -- documented in https://wiki.archive.org/twiki/bin/view/PetaBox/XenialChangelog?twiki_redirect_cache=c076e607304d8b906c9211bb24eda746

**Comment by abezella** [comment]
@mekarpeles  - i've redeployed `ol-mem4` using the geerlingguy.memcached role from ansible galaxy (https://galaxy.ansible.com/geerlingguy/memcached).  this allows easy changes to the memory based on host (although currently set for one-size-fits-all in the memcached group) and also the listening addr change.  so that addresses 1) and 2).  for 4) i added a `ferm` template.

`/opt/openlibrary` has not been copied over but otherwise should be ready.  please take a look at the result.

**Comment by mekarpeles** [comment]
@abezella I think I see this here? https://github.com/internetarchive/olsystem/blob/master/playbooks/site.yml

**Comment by abezella** [comment]
yep!  also some other supplemental files dropped in:
https://github.com/internetarchive/olsystem/commit/dde66442de0064ca85cf3826daf4689167f34449#diff-7a2684d343bed66d1c59ec37a49e55c6
`ol-mem4` should be ready to go, then...

**Comment by guyjeangilles** [comment]
@abezella @mekarpeles This seems almost done. What else needs to be accomplished?
