### ISSUE TITLE
Remove Books Page "admin bar" for librarians (superlibrarians only)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6808]
The admin bar on the books page has options which are really only relevant to staff and super librarians. Let's please restrict this feature to the super-librarians group

### Describe the problem that you'd like solved

![openlibrary org_books_OL5800271M_Are_You_My_Mother](https://user-images.githubusercontent.com/978325/181933358-313a345e-6e25-45ad-81eb-b1531c04bd71.png)

### Additional context

The two relevant files are:

* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html#L3
* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/models.py#L788-L812

**Comment by jimchamp** [comment]
Closed by #6815
