### ISSUE TITLE
Broken edition pages in different languages

### ISSUE THREAD

**Issue by dcapillae** [internetarchive/openlibrary#6814]
The edition pages are broken in languages other than English displaying the following message:

"/openlibrary/openlibrary/templates/type/edition/view.html: error in processing template: TypeError: Plural value must be an integer, got str (falling back to default template)
Unable to render this page. "

### Evidence / Screenshot (if possible)
![screenshot](https://user-images.githubusercontent.com/7125952/182105114-b0562a53-d331-4213-acb8-f81594585727.png)

### Relevant url?

-- > https://openlibrary.org/books/OL27902091M/Carrie?lang=en (OK!)
-- > https://openlibrary.org/books/OL27902091M/Carrie?lang=es (You get an error)

### Steps to Reproduce

1. Go to any edition page
2. Try a language other than English. For example, by adding "?lang=es" to any edition page URL or by selecting a different language from the menu. You will get an error.

* Actual: The edition pages are not displayed in languages other than English.
* Expected: The editions pages should be displayed in any default or user-selected language.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 103.0
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Marking as Priority 0 --

I think this is related to EditionsNavBar `reviews` counts: #6777 
https://openlibrary.org/works/OL1622748W/El_filibusterismo?debug=true

**Comment by mekarpeles** [comment]
Thank you @dcapillae! Fixed

**Comment by seabelis** [comment]
Patron has confirmed continued errors using the German-language setting. https://openlibrary.org/works/OL28596922W
@mekarpeles

**Comment by tfmorris** [comment]
That work renders without error for me in both German and French.

**Comment by mekarpeles** [comment]
We ran another set of tests and we have determined this can be closed
