### ISSUE TITLE
Missing "Read by" contributory role

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#682]
Audiobooks are "Read by", "Performed by" or "Voiced by" someone, yet there is no such parameter value under "Select role".  Hence https://openlibrary.org/books/OL26085939M/Barnaby_Rudge?b=3&a=2&_compare=Compare&m=diff which was a less than satisfactory adjustment.

I presume many records for audiobooks similarly show the reader incorrectly as the author.

**Comment by guyjeangilles** [comment]
There still seems to be now "Read by" role. @hornc, this seems like something you'd handle. Are you willing to be assignee for this issue? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
@LeadSongDog do you agree that Narrator is appropriate/adequate? If so, please close this issue.

**Comment by seabelis** [comment]
Should narrator be changed to 'Read by'? I always felt it was clear but, I have seen at least one example where a well-meaning editor interpreted 'narrator' as a literary term and entered a character's name.

**Comment by LeadSongDog** [comment]
I have been using “narrator” too, but “read by” seems to be the normal term seen in catalogues. If we agree they are largely equivalent perhaps just replace one by the other?

**Comment by seabelis** [comment]
Works for me.

**Comment by guyjeangilles** [comment]
@leadsongdog @seabelis to clarify, the proposal is to change `Narrator` to `Read by`?

I can see how a good-intentioned user could add a fictional character as a narrator.

**Comment by LeadSongDog** [comment]
@guyjeangilles
Yes

**Comment by seabelis** [comment]
Yes. I'm okay with this.

**Comment by bicolino34** [comment]
Should this issue be closed? Now this contributor role has form "**Narrator/Reader**".
![зображення](https://user-images.githubusercontent.com/58372007/177378076-4b959adc-0aac-44af-bad0-f1891c1f9fd8.png)
