### ISSUE TITLE
Specific authors are not reindexing

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6824]
These two authors are conflated. Myself with the help of a volunteer are trying to sort the works out and assign to the appropriate author ID. However, many edits are not being displayed correctly and seem to be ignored by solr updater despite reindexing the authors and the specific works. Additionally, I have tried re-editing the author field in hopes of triggering a reindex, but this has been unsuccessful.
### Relevant url?

https://openlibrary.org/authors/OL928135A/Jennifer_Taylor
https://openlibrary.org/authors/OL2626814A/Jennifer_Taylor
### Steps to Reproduce

1. Go to ...ttps://openlibrary.org/authors/OL928135A/Jennifer_Taylor
2. Do ...Open first work listed, https://openlibrary.org/works/OL17502129W and note that the author displays correctly on the work page, but still appears on the profiles of both authors.

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp

**Comment by tfmorris** [comment]
I noticed the same thing with edits about a week ago, but didn't bother trying to track down what exactly was going on. Just chalked it up to ongoing search weirdness. I had a suspicion that perhaps removing authors from a work was one operation which didn't get reindexed, but didn't try to confirm the pattern.

**Comment by cdrini** [comment]
This was fixed by #6840 ; sorry for the bug there folks it was a bad one :/ All edits to books with IA IDs were not going through to solr for ~1-2w.
