### ISSUE TITLE
Data Dumps not auto-generating (AGAIN)

### ISSUE THREAD

**Issue by neilt** [internetarchive/openlibrary#6825]
Despite, at least, the following being marked as complete, the Data dumps are sill not working. 
#6640 
#5402 

The last data dump is dated 6/6/2022, it is now 8/2/22.  I thought the data dumps were supposed to happen automatically at either the end or the beginning of the month.

### Evidence / Screenshot (if possible)
https://archive.org/details/ol_exports?sort=-publicdate

### Relevant url?

https://archive.org/details/ol_exports?sort=-publicdate

**Comment by mekarpeles** [comment]
I believe dumps are generating again (and an issue regarding pollution of logs during generation has been fixed) https://archive.org/download/ol_dump_2022-08-31/ol_dump_editions_2022-08-31.txt.gz
