### ISSUE TITLE
If ISBN is detected as invalid, Worldcat link is not enabled

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6830]
https://openlibrary.org/books/OL39212557M/Shou_xiang_bang_jia_an_Meng_mian_nu_ren has an ISBN that is detected as invalid when entered. However, it is the ISBN as printed in the book and should still be present and searchable on the record. Searching Worldcat by ISBN does produce a record, however the ISBN is surpassed. Nonetheless, the record appears to be the correct one and therefore, the link to Worldcat should be active. https://www.worldcat.org/title/shou-xiang-bang-jia-an-meng-mian-nu-ren/oclc/60835859&referer=brief_results
### Relevant url?

https://openlibrary.org/books/OL39212557M/Shou_xiang_bang_jia_an_Meng_mian_nu_ren
https://www.worldcat.org/title/shou-xiang-bang-jia-an-meng-mian-nu-ren/oclc/60835859&referer=brief_results

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL39212557M/Shou_xiang_bang_jia_an_Meng_mian_nu_ren
2. Do ...Look for linke to Worldcat

* Actual: no link present
* Expected: link to https://www.worldcat.org/title/shou-xiang-bang-jia-an-meng-mian-nu-ren/oclc/60835859&referer=brief_results should be present.

### Details

- **Logged in (Y/N)?**y
- **Browser type/version?**chrome
- **Operating system?**macos
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini @jimchamp @scottbarnes

**Comment by scottbarnes** [comment]
Sorry for missing this. The short of it is that there is a one line change that may address the issue in the linked PR (#6862). I put probably far too much narrative about my exploration of the issues there. Hopefully it's not too incorrect.
