### ISSUE TITLE
Translation Permissions

### ISSUE THREAD

**Issue by milotype** [internetarchive/openlibrary#6831]
Please give me permissions to translate the strings of the sections of the web pages at https://openlibrary.org

I allready have the permission to change https://openlibrary.org/subjects

I don't have permissions for translating strings at:
https://openlibrary.org/trending/now
https://openlibrary.org/explore
https://openlibrary.org/collections
https://openlibrary.org/collections/k-12
https://openlibrary.org/books/...

I must addmit, that I still don't understand the concept of translating "Open Library" ... some things are translated at https://github.com/milotype/openlibrary/tree/master/openlibrary/i18n/..., while ohers have to be translated directly in the specific  sections of the website https://openlibrary.org/.

**Comment by cdrini** [comment]
- https://openlibrary.org/trending/now this needs help from someone to update the html. I created an issue: https://github.com/internetarchive/openlibrary/issues/7373
- Library explorer has an issue here: #6847
- You can now edit https://openlibrary.org/collections.hr?m=edit
- You can now edit https://openlibrary.org/collections/k-12.hr?m=edit
- Hmmm not sure what you mean by this last one!

Yeah translation on open library is a little difficult; anything that appears in the _code_ of open library (i.e. in this repo) is translated via the .po files. Anything that appears on the _database_ doesn't have a great translation strategy, except for the eg `.hr` pages.

Sorry for the delay on this one! I mean to get to it much earlier. Let me know if you have any other questions!
