### ISSUE TITLE
Adding visual selected to `#mrid-` and/or a way to specify a specific `mrid=`

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6833]
### Describe the problem that you'd like solved

Each row in our merge request table has a unique `id` and can be directly navigated to when adding an URI fragment to the URL (e.g. openlibrary.org/merges#mrid-123).  When we do navigate to a specific row, there is no styling to differentiate it from the other rows.

### Proposal & Constraints

Let's add some styling to rows targeted by URI fragments.

### Additional context

`Less` file for merge request table: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/merge-request-table.less

New style rules should be applied to `tbody tr:target`.  More information about the `:target` psuedo-class can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/:target).

**Comment by muditjuneja** [comment]
I can try and add some highlighting css to the focussed container in this case. What kind of highlighting do you have in mind? Plain border based or some kind of faded animation for few ms? Let me know how can I help.

**Comment by muditjuneja** [comment]
@jimchamp Is there a way to get the entries for this table when trying this locally?

**Comment by muditjuneja** [comment]
I tried pulling the data from prod by following this doc: https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data

But I am getting this error-

<img width="894" alt="Screenshot 2022-08-22 at 11 56 38 PM" src="https://user-images.githubusercontent.com/15162221/185992788-752ba9f0-a444-4379-8d07-c6cb06e0ff11.png">

**Comment by jimchamp** [comment]
Did you pass the `PYTHONPATH` when opening the shell?

I was able to import this author by running the following:
```
docker-compose exec -e PYTHONPATH=. web bash 
./scripts/copydocs.py /authors/OL2993152A
```

**Comment by jimchamp** [comment]
It may just be easier to add some dummy merge requests to the DB.  You can follow the instructions here to insert a few requests: https://gist.github.com/jimchamp/dd83ae3fe1ea86ae9621707fa96b4edf

**Comment by muditjuneja** [comment]
> @jimchamp I tried pulling the data from prod by following this doc: https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data
> 
> But I am getting this error-
> 
> <img alt="Screenshot 2022-08-22 at 11 56 38 PM" width="894" src="https://user-images.githubusercontent.com/15162221/185992788-752ba9f0-a444-4379-8d07-c6cb06e0ff11.png">

Yes, I used this exact command.
`docker-compose exec -e PYTHONPATH=. web bash`

**Comment by muditjuneja** [comment]
> It may just be easier to add some mock merge requests to the DB. You can follow the instructions here to insert a few requests: https://gist.github.com/jimchamp/dd83ae3fe1ea86ae9621707fa96b4edf

After inserting as per the queries, it gives me the following rendering error - 
<img width="1726" alt="Screenshot 2022-08-23 at 12 42 31 PM" src="https://user-images.githubusercontent.com/15162221/186095221-c6e9007a-e879-4022-a117-c5428ccf96db.png">

After deleting the entries it started working again. Checking more to figure out.

**Comment by jimchamp** [comment]
We have recently added a new `mr_type` column to the `community_edits_queue`.  It looks like your local instance may be missing that column.  With the application running, you can add the new column by executing the following:

```
docker-compose exec db bash
psql -Uopenlibrary
ALTER TABLE community_edits_queue ADD COLUMN mr_type INTEGER NOT NULL DEFAULT 1;
```

**Comment by muditjuneja** [comment]
Hi @jimchamp, I have added the highlighted styling here - https://github.com/internetarchive/openlibrary/pull/6913. Let me know if anything should be changed.
