### ISSUE TITLE
Use HTTPS links for ISNI display

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#6838]
On author pages with ISNI, the URL for the ISNI record starts with `http://www.isni.org/`, whereas ISNI shows the URL as `https://isni.org/isni/`. I would like every URL that is available through HTTPS to be HTTPS, to improve user privacy.

### Describe the problem that you'd like solved

Please update the ISNI link to use the official ISNI-provided format.

### Proposal & Constraints

It looks like updating <https://openlibrary.org/config/author> is required for this.

Note that the issue that any spaces within the ISNI are not removed when creating the URL. That is described in #5696 and #6423 and needs to be fixed first. Updating the URL template without fixing the spaces issue will not help, as links would still not resolve.

### Additional context

n/a

### Stakeholders

I wouldn't know who to tag.

**Comment by jimchamp** [comment]
I've just updated the ISNI URL configurations.  Please re-open this if you notice that anything is amiss.

**Comment by jimchamp** [comment]
Space issue is addressed by #6841

**Comment by bencomp** [comment]
Thanks! You didn't use the template that ISNI themselves use (`https://isni.org/isni/@@@`), but it works.

**Comment by jimchamp** [comment]
Thanks @bencomp --- I was being too hasty when I closed this.
Everything should be good now.  Any newly added ISNI numbers that contain spaces will be stored without spaces.
