### ISSUE TITLE
Mobile-first design for Books Page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#685]
See https://github.com/internetarchive/openlibrary/issues/679

This task will be apart of designing the Canonical Book Page, starting with a mobile-first design.

**Comment by mekarpeles** [comment]
Requirement for #684 canonical books page

**Comment by jdlrobson** [comment]
Would you be okay with closing this in favor of #1313 and expanding the latter with anything specific not captured there?

**Comment by guyjeangilles** [comment]
Assigning @mekarpeles per slack discussion since you're the assignee of the parent epic.
