### ISSUE TITLE
Orange background color makes diff unreadable

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6855]
When viewing a work or edition diff, the orange-coloured background makes the grey text difficult to read.
### Evidence / Screenshot (if possible)
<img width="436" alt="Screenshot 2022-08-09 at 16 20 28" src="https://user-images.githubusercontent.com/17739465/183673737-d523c597-b008-4ab8-988d-1ac62f296444.png">

### Steps to Reproduce

1. Go to ...a work or edition diff, for example, https://openlibrary.org/books/OL28342174M/Otherwise_Known_as_Sheila_the_Great?b=3&a=1&_compare=Compare&m=diff
2. Do ...notice orange background colour

* Actual:
* Expected: There should be enough contrast between the background and text to allow the text to be clearly visible.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by muditjuneja** [comment]
Hi @seabelis, I have changed the color of the text to darker grey and it has increased the contrast ratio as expected. Check the screenshot attached. 
<img width="1728" alt="Screenshot 2022-08-13 at 1 25 49 AM" src="https://user-images.githubusercontent.com/15162221/184434810-9c4dd854-a0b7-4d3a-9060-c6a7045e82c2.png">

If this is what we want then I can try raising the PR. Let me know how can I help.

**Comment by muditjuneja** [comment]
Here, I created a PR for the review here - https://github.com/internetarchive/openlibrary/pull/6872

**Comment by seabelis** [comment]
Yes, @muditjuneja . Thank you!
