### ISSUE TITLE
Covers for IA-linked items not importing correctly

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6866]
Recently, IA-linked items are being imported with title pages or text pages as covers, even when the IA item has a true cover available. 
### Relevant url?

Examples: 
https://openlibrary.org/books/OL29698626M/Target?_compare=Compare&b=3&a=2&m=diff
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected: 

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@bfalling @judec @mekarpeles

**Comment by seabelis** [comment]
I'll add more examples as I come across them.

**Comment by seabelis** [comment]
https://openlibrary.org/books/OL28824376M/Keeper?_compare=Compare&b=4&a=3&m=diff

**Comment by mekarpeles** [comment]
Needs discussion: talk to @hornc , @seabelis , and @cdrini about what to use for cover imports on IA

**Comment by mekarpeles** [comment]
I thought this may be a duplicate, I recall there was some discussion among @cdrini + @scottbarnes + @hornc about what API to use re: clothe, cover, etc, and I think @cdrini had a url that I was fine endorsing for now.

**Comment by cdrini** [comment]
Yep; #7616 . This one is older, but the other one has garnered more discussion, so will close this in favour of the other. I'll copy over the examples.

@scottbarnes you are unblocked to implement the solution proposed in #7616 :+1: I added it to the January milestone.
