### ISSUE TITLE
Rebooting Open Library Email Mailing List

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#687]
We'd like to launch an official Open Library mailing list with low-frequency Monthly Newsletters, similar to how Goodreads and other services engage with their audiences.

## Sub-Tasks
- [ ] #691 we need a design for the newsletter

## Open Questions
- contents of these Monthly Newsletter emails (e.g. metrics, new scans, possibly binder-breaking used book deals from our non-profit partner Better World Books)
- what platform will be used internally to manage emails securely
- how email subscriptions opt-out/in will be handled during registration and
- managed from account settings.

**Comment by salman-bhai** [comment]
@mekarpeles 
1. How often would we be releasing these Monthly Email Newsletters?
2. Would it be a better idea to release them quarterly rather than monthly?

**Comment by guyjeangilles** [comment]
More open questions: Who would write this? Sure we want to engage, but what's the target demographic and want value will the newsletter bring to them.

Also assigning @mekarpeles per slack discussions.

**Comment by mekarpeles** [comment]
We're doing increasingly more newsletters via Internet Archive, punting for now and sending to backlog
