### ISSUE TITLE
Suggest users to add books if there are no results in search

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6875]
Maybe, add some text on search results page like "Can't find what you look for? Then _add book_ yourself". Or something like that.

https://openlibrary.org/search?q=%D0%9E%D0%BD%D0%BE%D0%BC%D0%B0%D1%82%D0%BE%D0%BF%D0%B5%D1%97%D1%87%D0%BD%D0%B0+%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0+%D1%81%D1%83%D1%87%D0%B0%D1%81%D0%BD%D0%BE%D1%97+%D1%8F%D0%BF%D0%BE%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%97+%D0%BC%D0%BE%D0%B2%D0%B8&mode=everything

**Comment by cdrini** [comment]
The code is here: https://github.com/internetarchive/openlibrary/blob/7e877d32995e3716c11fd478b91dd2469441059c/openlibrary/templates/work_search.html#L149-L152
