### ISSUE TITLE
Create Book Ingestion Pipeline (keep catalog current)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#688]
See Openlibrary-client https://github.com/internetarchive/openlibrary-client/issues/65

Open Library doesn't currently subscribe to book feeds to keep its catalog up to date. It generally relies on (MARC) records in bulk from our library partners.

If you can recommend sources/feeds of high quality book metadata, we'd love to build a more modern ingestion process on top of our openlibrary-client tool.

This is the top-level issue for adding book metadata sources to Open Library.

**Comment by hornc** [comment]
Specific task for ISBN sources using the existing import API: #2034
