### ISSUE TITLE
Give super librarians permission to undo author merges

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6885]
This doesn't need to be an admin-only feature. They should be able to see the "Undo All" button on e.g. https://openlibrary.org/recentchanges/2022/07/22/merge-authors/95371217

### Stakeholders
@mheiman

**Comment by mheiman** [comment]
I'll take a look -- should be quick one.

**Comment by cdrini** [comment]
Discussed offline, it seems like this change needs to be on the config in olsystem. I'll take it over :)
