### ISSUE TITLE
Errors when patron tries to borrow books

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6889]
Errors reported by a patron when trying to borrow books. 
https://openlibrary.org/books/OL2711887M/borrow?ref=ol
" We've noted the error 2022-08-16/224056981978 "

https://openlibrary.org/borrow/ia/garageband0000plum?ref=ol
We've noted the error 2022-08-16/223813274487

https://openlibrary.org/works/OL19992650W?edition=ia%3Agarageband0000plum_i2d0
We've noted the error 2022-08-16/224414641644

https://openlibrary.org/works/OL518890W?edition=ia%3Agaragebandmissin00pogu
We've noted the error 2022-08-16/224533995074

I cannot reproduce.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @jimchamp @cdrini

**Comment by mekarpeles** [comment]
@seabelis I wonder if these may have been transient issues. Has the patron since been able to achieve success in borrowing titles from the library?

**Comment by cdrini** [comment]
@seabelis We can't seem to reproduce; could you message me on slack with details about the user? It might be something specific to their account. Do you know if they're still having issues?

**Comment by mekarpeles** [comment]
this issue has been a P1 for 2 consecutive weeks and we haven't bee able to reproduce the problem so we're going to close for now. If you can get us any additional information about whether the patron is still facing issues, we will re-open and give it the high priority it deserves:
