### ISSUE TITLE
Sorting buttons in Reading log don't work as intended

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6891]
When you press sort by "Date Added (oldest)" page refreshes and sorting is applied but "Date Added (oldest)" button doesn't turn green and doesn't become unclickable, and "Date Added (newest)" button doesn't become clickable

### Evidence / Screenshot (if possible)
On this scrrencshot books are sorted by oldest
![image](https://user-images.githubusercontent.com/58372007/185414834-58610de2-e5f4-43a3-8b91-238b5195f81d.png)

### Steps to Reproduce

1. Go to ... Reading log
2. Do ... press sort by "Date Added (oldest)"

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 103 (64-bit)
- **Operating system?** Linux Mint and Windows 8.1
- **Environment (prod/dev/local)?** prod

**Comment by muditjuneja** [comment]
I see the issue. If you change the sort param in the URL then it filters the results as per the filter applied but there is no effect on the buttons. They remain as is. Checking it locally, Hopefull will figure out the issue.

**Comment by muditjuneja** [comment]
Hi @bicolino34, Seems like we were missing the param while rendering the reading_log. Created a PR for your reference.
Check here - https://github.com/internetarchive/openlibrary/pull/6898
