### ISSUE TITLE
Librarian, Admin, & Moderator Features

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#690]
This is a top-level container for feature requests concerning Librarian Features, e.g. #903 and:
- [ ] merging works
- [ ] splitting editions off from works -- @cdrini recently provided an interface for this here: https://github.com/internetarchive/openlibrary/pull/661

**Comment by brad2014** [comment]
@mek, does this need further breakdown or assessment?

**Comment by guyjeangilles** [comment]
This seems redundant to the [Librarian issues](https://github.com/internetarchive/openlibrary/projects/14) project board. Should we close?

**Comment by tfmorris** [comment]
> This seems redundant to the [Librarian issues](https://github.com/internetarchive/openlibrary/projects/14) project board. Should we close?

Sounds good to me. We also have the "Affects: Librarians" tag

**Comment by guyjeangilles** [comment]
@mekarpeles What value does keeping this issue in the [ 2019 Epics](https://github.com/internetarchive/openlibrary/projects/11#card-21180935) project?

**Comment by seabelis** [comment]
I have never seen this.

**Comment by cdrini** [comment]
Confirmed with @mekarpeles ; closing this in favor of the project board.
