### ISSUE TITLE
Problem receiving books

### ISSUE THREAD

**Issue by damiankomonski** [internetarchive/openlibrary#6900]
Hello!

I create project with Open Library API. 

I use this to get books on some topic:
https://openlibrary.org/dev/docs/api/subjects

I get "works" and "key". So I want to download books/editions. I use this:
https://openlibrary.org/works/OL45883W.json

How can I get books/editions using WORKS? 

it seems impossible....

**Comment by mekarpeles** [comment]
https://openlibrary.org/works/OL45883W/editions.json
