### ISSUE TITLE
Design Open Library Monthly Email Newsletter

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#691]
@jeansaung -- any interest in working on the design for a Open Library Email Monthly Newsletter with us?

See: https://github.com/internetarchive/openlibrary/issues/687

**Comment by jeansaung** [comment]
@mekarpeles Sure! Maybe we can discuss further next week?

**Comment by salman-bhai** [comment]
Hi @mekarpeles what is it that we are planning to put up on these newletters?

**Comment by guyjeangilles** [comment]
Blocked until #687 reaches consensus. Assigning @mekarpeles per slack discussions since he is responsible for the epic issue
