### ISSUE TITLE
Cannot commit in gitpod: "No module named pre_commit"

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6918]
Add pre_commit to the gitpod environment

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cclauss @bicolino34

**Comment by mekarpeles** [comment]
Would it be useful to do a short "developing in gitpod" video?
