### ISSUE TITLE
Converting uploaded EPUB to other formats fails

### ISSUE THREAD

**Issue by philschatz** [internetarchive/openlibrary#6926]
Hello, When I upload an EPUB the jobs that run seem to fail to generate a PDF which causes the Book Viewer to not show up (it worked on June 30).

It seems the failure occurs on the machine that runs the `ebook-convert` command [from Calibre](https://github.com/kovidgoyal/calibre/blob/eb78a761a99ac20a6364f85e12059fec6517d890/src/calibre/linux.py#L22).

Another person encountered the _same error 2 days ago_ and the [author of Calibre noted](https://www.mobileread.com/forums//showthread.php?t=348820):

> conversion to pdf uses QtWebEngine, which needs a suitable graphics backend, which you are missing. Presumably this is some kind of headless VM/container?
> Use the env var to tell qt webengine to disable hardware acceleration, as described at https://doc.qt.io/qt-6/qtwebengine-debugging.html

Also, I am not sure if this is the correct place to report this. If this is incorrect, where should I?

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/253202/187737754-dd249aa5-f5b6-4625-b12b-b6cfa44204b0.png)

### Relevant urls

Here is the [uploaded book page](https://archive.org/details/intro-to-logic), the [failed job](https://catalogd.archive.org/log/3390233517), and the error from the failed job:

```
67% Running PDF Output plugin
68% Parsed all content for markup transformation
70% Completed markup transformation
No suitable graphics backend found

Load of clbr://internal.invalid/book/contents/intro-to-logic.toc.xhtml failed

FATAL ERROR: ulimit -v 10485760 && QTWEBENGINE_CHROMIUM_FLAGS="--no-sandbox" timeout 3600 ebook-convert '/var/tmp/autoclean/derive/intro-to-logic/intro-to-logic.epub' '/t/_intro-to-logic/tmp.pdf' --pdf-page-margin-bottom=72 --pdf-page-margin-top=72 --pdf-page-margin-left=72 --pdf-page-margin-right=72 --pretty-print failed with exit code: 1

  Derivation failed!
```

### Steps to Reproduce

I tried uploading several EPUB files, all of which failed with the same error in the logs: `No suitable graphics backend found`

- [Intro to Logic](https://archive.org/details/intro-to-logic)
- [Moby Dick](https://archive.org/details/pg2701-moby-dick-test) from Project Gutenberg [here](https://www.gutenberg.org/ebooks/2701)
- [Edible Toadstools](https://archive.org/details/test-pg46514-images).... and [source](https://archive.org/details/ouredibletoadsto46514gut)
 
### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Mozilla Firefox 104.0
- **Operating system?** Ubuntu
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

It seems the machine that runs the `ebook-convert` command [from Calibre](https://github.com/kovidgoyal/calibre/blob/eb78a761a99ac20a6364f85e12059fec6517d890/src/calibre/linux.py#L22) fails.

Another person encountered the _same error 2 days ago_ and the [author of Calibre noted](https://www.mobileread.com/forums//showthread.php?t=348820):

> conversion to pdf uses QtWebEngine, which needs a suitable graphics backend, which you are missing. Presumably this is some kind of headless VM/container?
> Use the env var to tell qt webengine to disable hardware acceleration, as described at https://doc.qt.io/qt-6/qtwebengine-debugging.html

**Comment by mekarpeles** [comment]
Hi @philschatz! Thank you for bringing this to our attention. I'm cc'ing @jimbonator and @bfalling as this derive operation relates to Archive.org (as opposed to OpenLibrary.org)

**Comment by philschatz** [comment]
Thanks! After waiting a little longer the books successfully built.

From the logs it seems that the `ebook-convert` program is gradually given more resources and the books seem to build by the 3rd attempt.

So the `No suitable graphics backend found` message was a red herring and we just had to wait a bit longer.
