### ISSUE TITLE
Add Google sign in button to hamburger menu

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6937]
One of the nice things about the google sign in button is that it requires only a single click. Let's add this button to the hamburger menu, so patrons can log in with a single click from anywhere.

### Proposal & Constraints

| Currently | After |
| ---- | --- |
| ![image](https://user-images.githubusercontent.com/6251786/188728208-996ca7a3-c8b5-4cf7-a10b-a0ceaacf8f51.png) | ![image](https://user-images.githubusercontent.com/6251786/188729291-4f5e2e80-3624-44bc-a079-83c1aa8026f6.png) |

Constraints:

- The iframe must not load until the hamburger icon is clicked
- The iframe should only load for logged out users

### Stakeholders
@mekarpeles

**Comment by cdrini** [comment]
- Mark: "Sign in w Google" Doesn't imply register; (Drini maybe "Continue with Google")
- Mek: Takes up more space; would this scale for other providers?

**Comment by anonymous-baaka** [comment]
I would like to work on this issue.  Please assign it to me. @cdrini

**Comment by JaydenTeoh** [comment]
@cdrini Hi, I have made a PR regarding this issue, do let me know if it's okay!
