### ISSUE TITLE
Add Google analytics tracking to search facets

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6938]
We want to know how much these are used; these are expensive to compute, so if any are not used we should remove them or make them lazy. And we should promote the most used ones to the top.

Eg update `<a href="/search?q=the+alchemist&amp;mode=everything&amp;author_key=OL112771A" title="Filter results for Ben Jonson">Ben Jonson</a>` to `<a href="/search?q=the+alchemist&amp;mode=everything&amp;author_key=OL112771A" title="Filter results for Ben Jonson" data-ol-link-track="SearchFacet|Author">Ben Jonson</a>`

So the following events:

- `SearchFacet|(Ebook|Author|Subjects|People|Places|Times|FirstPublished|Publisher|Language` for when someone clicks one of the facets

**Comment by Karthik-PM** [comment]
i would like to work on this issue , please assign it to me

**Comment by yoonmgyg** [comment]
Hello, I would like to begin working on this issue.

**Comment by cdrini** [comment]
Hi @yoonmgyg, please! Let us know if you have any questions :)

**Comment by prakhar1144** [comment]
Hi @yoonmgyg , please let me know if you are still working on this issue. Otherwise I would be happy to work on this issue.
