### ISSUE TITLE
Short tutorial video: "Developing Open Library using Gitpod"

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6939]

**Comment by ma8642** [comment]
Was a tutorial video made? If so where can I find it? Currently trying to use it to update some CSS. The general frontend dev instructions say that you have to run `make css` to update the instance with CSS changes. Running that causes this error:
```
mkdir -p static/build
parallel --verbose -q npx lessc {} static/build/{/.}.css --clean-css="--s1 --advanced" ::: static/css/page-plain.less static/css/page-form.less static/css/page-design.less static/css/page-edit.less static/css/page-book-widget.less static/css/page-subject.less static/css/page-admin.less static/css/page-barcodescanner.less static/css/page-user.less static/css/page-book.less static/css/page-home.less static/css/page-lists.less static/css/page-dev.less
/bin/sh: 1: parallel: not found
make: *** [Makefile:19: css] Error 127
```
I then tried running `npm run build-assets` instead. This prompts you to install webpack, but this errors out with `Error: EACCES: permission denied, mkdir '/workspace/openlibrary/node_modules/@akryum'`. @cdrini

**Comment by ma8642** [comment]
> Was a tutorial video made? If so where can I find it? Currently trying to use Gitpod to update some CSS. The general frontend dev instructions say that you have to run `make css` to update the instance with CSS changes. Running that causes this error:
> 
> ```
> mkdir -p static/build
> parallel --verbose -q npx lessc {} static/build/{/.}.css --clean-css="--s1 --advanced" ::: static/css/page-plain.less static/css/page-form.less static/css/page-design.less static/css/page-edit.less static/css/page-book-widget.less static/css/page-subject.less static/css/page-admin.less static/css/page-barcodescanner.less static/css/page-user.less static/css/page-book.less static/css/page-home.less static/css/page-lists.less static/css/page-dev.less
> /bin/sh: 1: parallel: not found
> make: *** [Makefile:19: css] Error 127
> ```
> 
> I then tried running `npm run build-assets` instead. This prompts you to install webpack, but this errors out with `Error: EACCES: permission denied, mkdir '/workspace/openlibrary/node_modules/@akryum'`. @cdrini

Documenting for anyone else who comes across this: as the [frontend docs](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md#updating-the-docker-image) mention, you need to run a docker-compose command. In my case I did:
`docker-compose run --rm home make css` rather than just `make css`.

**Comment by jimchamp** [comment]
We uploaded a Gitpod video about a year prior to this issue being opened, here: https://archive.org/embed/openlibrary-tour-2020/using-openlibrary-gitpod.mp4

Does that video suffice for this issue?
