### ISSUE TITLE
ILE blue bar obstructs hamburger drawer

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6942]
The "Help & Support" link in the hamburger drawer is partially obstructed by the ILE blue bar.

### Evidence / Screenshot (if possible)
![Screenshot from 2022-09-07 12-13-42](https://user-images.githubusercontent.com/28732543/188928424-9ee799f0-469e-4422-a4da-1b25b55e487f.png)

### Steps to Reproduce

When logged in as a `librarian`, `super-librarian`, or `admin`:
1. Go to a search results page.
2. Display the drawer by clicking on the hamburger icon located on the right side of the navigation menu.
3. Observe the "Help & Support" link (it's the last link)

* Actual: Link is partially obstructed by the blue bar, and illegible.
* Expected: The link is unobstructed.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Any
- **Operating system?**Ubuntu 20.04
- **Environment (prod/dev/local)?** prod

**Comment by ztjhz** [comment]
Hi, I would like to work on this issue. You can assign this issue to me!

**Comment by jimchamp** [comment]
Thanks @ztjhz!
The CSS for the ILE blue bar is in this file: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.less

The hamburger drawer CSS is here: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/header-bar.less
