### ISSUE TITLE
Move "Viking Kestrel Picture Books" from edition titles to series field

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6949]
There are ~80 books containing this publisher series in the title. This is causing these books to misleading match queries like `title:vikings`. Let's move it to the appropriate field, series.

Here's a query you can use (note it must use testing.openlibrary.org): https://testing.openlibrary.org/search.json?q=title%3A+%22Viking+Kestrel+Picture+Books%22&mode=everything&fields=key,title

And here's the human-readable UI: https://testing.openlibrary.org/search?q=title%3A+%22Viking+kestrel+picture%22&mode=everything

This one-off task can be done by someone's personal bot account.

Create a [colab](https://colab.research.google.com/), and have this snippet at the top to get access to open library client from colab:

```py
# Install open library client
!git clone https://github.com/internetarchive/openlibrary-client.git
!cd openlibrary-client; pip -q install .
!read -sp 'Email: ' EMAIL && ol --configure --email $EMAIL
from olclient.openlibrary import OpenLibrary
import olclient.common as common
ol = OpenLibrary()
```

**Comment by scottbarnes** [comment]
I'd like to work on this.

**Comment by cdrini** [comment]
Woohoo! Nice work @scottbarnes ! Search shows up clean :)
