### ISSUE TITLE
Is there an API to access ratings or reviews?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#6952]
### Question

Is there an API to access ratings or reviews?

I would like to be able to access:
1. Ratings (count of ratings and ratings themselves if possible, but at least an average)
2. How many lists it's in (75 Want to read, 3 Currently reading, 12 Have read, etc)
3. Community Reviews (at least count)
4. Any other data related to how users have interacted with a book if possible (number of checkouts? page views? etc)

### Additional context

I don't see any APIs listed here: https://openlibrary.org/developers/api
I also can't find any related issues in the GitHub (but please link of they do exist)

### Issue resolution criteria

1. Docs showing how to access this data
2. Tickets to create apis for this data
3. Docs saying why we don't want to expose this data

### Stakeholders

@jimchamp (just a guess)

**Comment by mekarpeles** [comment]
Swagger seems like a great step moving forward. As a step 0, having **some** documentation on https://openlibrary.org/developers/api may be useful (whether this is a page or a section).

Leaving this for @jimchamp to decide, but if someone created a page + section on https://openlibrary.org/developers/api that seems like a win (which can be cleaned up later)

**Comment by cdrini** [comment]
1. https://openlibrary.org/works/OL18020194W/ratings.json
2. https://openlibrary.org/works/OL18020194W/bookshelves.json
3. No API 
4. No API

**Comment by cdrini** [comment]
Closing this as answered; please create new issues for any APIs we should add!

**Comment by RayBB** [comment]
Added a note about these apis to the docs here. https://openlibrary.org/dev/docs/api/books
