### ISSUE TITLE
Javscript breaking in Safari

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6975]
Reported by a patron; I have been able to reproduce the issue.
Search for ebooks doesn't appear to work on MacOs Safari

### Evidence / Screenshot (if possible)
<img width="1680" alt="Screenshot 2022-09-19 at 09 32 40" src="https://user-images.githubusercontent.com/17739465/190969541-36443ffd-13b2-4446-a54f-4b46748fb104.png">

### Relevant url?

https://openlibrary.org/search?q=%22BETTY+NEELS%22&mode=ebooks

### Steps to Reproduce

Go to ...Main Page => click Books => enter "BETTY NEELS"
List of books appears (including "Not in Library")
Click on "ebooks"

Result: same same list as in Result 1 and "ebooks" has become UNHIGHLIGHTED.
Click on "ebook" (turns blue) and then "First Published" or "Most Recent" or "Most editions", etc.
Result: Expected list, except that the "Not in Library" books are included and "ebook" choice is Unhighlighted (turns white).

### Details

- **Logged in (Y/N)?**
- **Browser type/version?** Safari
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @jimchamp @cdrini

**Comment by mekarpeles** [comment]
This appears to be related to a query param `&has_fulltext=true` which somehow is dropped (unclear if safari specific or whether that patron somehow entered a unconventional flow).

One possible solution is just to add `has_fulltext=true` if `mode=ebooks` present?

**Comment by mekarpeles** [comment]
Upon further investigation (@cdrini ran in safari) it looks like jquery or something may be having trouble in safari `$` not found? Whatever the root cause is results in js breaking across the experience and the original issue opened is downstream of this root cause. Investigating.
