### ISSUE TITLE
A widget to embed Open Library Lists in external websites

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#698]
A widget for embedding an Open Library list in one's own website (grid of covers and titles, or text list, etc.).
https://twitter.com/samwilson/status/946652503277367298

**Comment by mekarpeles** [comment]
We could make a new endpoint in /plugins/openlibrary/code.py for `class Widget` which takes a url like... `openlibrary.org/works/OL....W/embed`

**Comment by jacobandresen** [comment]
Sounds interesting . I'd like to try implementing this widget. Anyone else working on it?

**Comment by mekarpeles** [comment]
@html5cat was taking a look at it though I don't think he started yet. It may be worth taking a stab at it -- in the worst case you two can pair the feature! I'm also around to help.

**Comment by html5cat** [comment]
Yeah, feel free to jump on it as I’m traveling till Monday!

**Comment by jacobandresen** [comment]
okidoki. I'll poke around here and report back about my findings before monday :)

**Comment by jacobandresen** [comment]
I just took a look at the Open Library code base .  been trying to grok  the infogami page / app / view structure. when you say "endpoint" are you refering to the api described here : https://github.com/internetarchive/openlibrary/wiki/Endpoints ? I don't fully understand what's going on ;)

 Looks like there is a endpoint related to lists endpoint  in openlibrary/plugins/openlibrary/lists.py ? This looks for me to be more directly related to the usecase of lists? (Note that I do not fully grok the openlibrary api yet) Maybe the "html" export can be used directly .. or extended ?

**Comment by mekarpeles** [comment]
Endpoint in this case meaning, the a url that a user submits which maps to a new class you'll write within the file `/plugins/openlibrary/code.py` which follows this general template:

```class widget(delegate.page):
    path = "(/works/OL\d+W)/.*/widget"  # this is the regex which matches the url the user enters 

    def GET(self, work_id):
        work = web.ctx.site.get(work_id) # get the work here
        return ???(work) # render template code (without header / footer which you get from render_template)
```

The fact that widget inherits from delegate.page is enough to register it with infogami; you don't have to do anything other than add a class like this one.

**Comment by mekarpeles** [comment]
@jacobandresen any other questions / progress on this? Happy to code review when its ready

**Comment by mekarpeles** [comment]
:) @jacobandresen, any progress or questions on this feature? @html5cat interested in continuing exploration on this?

**Comment by jacobandresen** [comment]
Sorry. I have been busy at work . No progress.  . @html5cat  feel free to grab this

**Comment by jacobandresen** [comment]
I'll continue poking around here . expect progress to be a bit slow. Still learning about infogami here.  @html5cat  any thoughts?

**Comment by mekarpeles** [comment]
@whatisgalen -- do you want to give this one a shot?

**Comment by mekarpeles** [comment]
We likely need some UI for customizing the widget as well, e.g. https://www.goodreads.com/user/edit?format=html. I imagine this will probably be some modal which is triggered on the /works page

**Comment by Zacharius** [comment]
Is there any way to supress the read button in the iframe. I love this feature but the button kinda clashes with my website design
