### ISSUE TITLE
Change Reading Log dropper from green to shell with blue border

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7005]
Change the style of our Reading Log dropper to something more like our "Preview" buttons.  This issue can be closed when our Reading Log droppers look similar to this mock-up:
![blue_shell_dropper](https://user-images.githubusercontent.com/28732543/192813199-3b638977-711b-4fab-adbb-851d982084d8.png)

### Related Files:
Reading Log dropper template: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/ReadingLogDropper.html
Reading Log dropper stylesheet: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/dropper.less

**Comment by Jyotiraditya24** [comment]
hey, could i work on this issue? I would love to contribute

**Comment by jimchamp** [comment]
Of course, @Jyotiraditya24! Please let me know if you have any questions.

**Comment by Jyotiraditya24** [comment]
@jimchamp I am having trouble setting up on my localhost if you could help me

**Comment by Jyotiraditya24** [comment]
1> changing the background here does not have effect on the button 
<img width="867" alt="Screenshot 2022-10-05 at 11 37 21 PM" src="https://user-images.githubusercontent.com/93746326/194130981-099951d2-b40a-404b-8020-406368b6f226.png">

**Comment by jimchamp** [comment]
You'll have to recompile the `.less` files each time you make a change.  You can do this by running `docker-compose exec web npm run build-assets:css`

**Comment by Jyotiraditya24** [comment]
Thankyou got it working ,I was sick so couldn't complete the issue working on it right now

**Comment by Jyotiraditya24** [comment]
@jimchamp I wanted the background-image of the dropper and the hex-color of the button

**Comment by Jyotiraditya24** [comment]
Made the necessary changes does it look good?
<img width="1410" alt="Screenshot 2022-10-11 at 10 43 04 PM" src="https://user-images.githubusercontent.com/93746326/195156764-2d7ba5ad-b37e-46ab-9577-7d46755d29ee.png">

**Comment by mekarpeles** [comment]
@Jyotiraditya24 this looks right to me, did you open a pull request yet with your changes?

**Comment by mekarpeles** [comment]
@Jyotiraditya24 just checking, it would be a help if you still wanted to submit that PR :)

**Comment by jpdh9881** [comment]
Hi @Jyotiraditya24, are you still working on this?

**Comment by jpdh9881** [comment]
Hey @jimchamp, could I be assigned this one please?

**Comment by JaydenTeoh** [comment]
@jimchamp Hi, I am looking to contribute to the WARI project for GSoC'2023. I have been making a few PRs to familiarise myself with the codebase. Please find my changes to the UI for the log dropper in this PR https://github.com/internetarchive/openlibrary/pull/7573

**Comment by mekarpeles** [comment]
We converged on a design for this one and I believe it can be closed.
