### ISSUE TITLE
Move book description above omnibar

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7007]
The description on book pages should be positioned directly above the omnibar in both mobile and desktop views.

Here is an example of how this should look on mobile devices:
![Screenshot from 2022-09-26 19-38-21](https://user-images.githubusercontent.com/28732543/192399196-124f9f4c-53e9-4b75-8858-5180aad4ccc6.png)

Note that restyling the omnibar is out of scope for this issue.

**Comment by BinniesLite** [comment]
Hi @jimchamp , I would love to work on this.

**Comment by jimchamp** [comment]
Thanks @BinniesLite!  Let me know if you need any guidance.

**Comment by BinniesLite** [comment]
Hi @jimchamp, absolutely, I'll try and get this done in the hacktoberfest.

**Comment by jpdh9881** [comment]
Hey @jimchamp, when I think I have things set should I submit a PR or would you like a few screenshots/notes to check over first?

**Comment by jimchamp** [comment]
You can go ahead and submit a PR.  There is a section for screenshots in the PR template.
