### ISSUE TITLE
Restyle the omnibar

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7008]
Our book page omnibar looks pretty bad in both mobile and desktop views:
![Screenshot from 2022-12-08 16-35-26](https://user-images.githubusercontent.com/28732543/206595903-3571eae7-e554-4ea3-86ad-2253beb648c2.png)
_Our current omnibar component_

Let's restyle the omnibar such that it looks like the following mock-up:
![Screenshot from 2022-09-28 11-06-23](https://user-images.githubusercontent.com/28732543/192816536-5453b6e0-48b2-43f0-b708-e6f8300f09a6.png)
_Mock-up for mobile omnibar_

The arrow need not appear in desktop views.

### Related Files:
Omnibar stylesheet: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/work.less
Omnibar HTML: https://github.com/internetarchive/openlibrary/blob/c4d2a52809638a49af1bedf3cdfc0bbf8fc5b14e/openlibrary/templates/type/edition/view.html#L210-L263

**Comment by Nishant891** [comment]
Hey! I would like to contribute in this issue.

**Comment by jimchamp** [comment]
Thanks @Nishant891!  Please let me know if you have any questions.

**Comment by Nishant891** [comment]
Okay I will.

**Comment by Paari1263** [comment]
Hey @jimchamp , I have completed the design of this omnibar as your mock design. Can you assign me,  so that I can create a PR.

**Comment by jimchamp** [comment]
@Nishant891 is currently assigned to this issue. 
@Paari1263 if there is something that you'd like to work on, please ask to be assigned first.

**Comment by Paari1263** [comment]
Can you assign me please

**Comment by Eds-Dbug** [comment]
This is what the Omnibar looks like so far for wider screens so far:
![image](https://user-images.githubusercontent.com/83380248/207192728-773a29ae-c895-464f-989e-38901b05fa34.png)

**Comment by Eds-Dbug** [comment]
For mobile so far its looks like this with a simple overflow scroll and no arrow:
![image](https://user-images.githubusercontent.com/83380248/207193108-c0e13d6f-4f5c-4a1e-a185-843ea650c6d8.png)

**Comment by Eds-Dbug** [comment]
:D
