### ISSUE TITLE
Display vendors beneath omnibar on mobile book page views

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7009]
On the mobile book page, the vendor section should appear directly beneath the omnibar.

![Screenshot from 2022-09-26 19-52-36](https://user-images.githubusercontent.com/28732543/192400589-ed0cc63d-11e6-4a4f-8bf0-07b05f7c4219.png)

In order to achieve this, the existing vendor section should be duplicated and added to the template after the omnibar section.  The newly created vendor section should not be displayed while the site has a two-column layout (desktop view).  Similarly, the original vendor section should not appear in mobile views.

The vendor section has its own template, here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/AffiliateLinks.html
It's probably best to pass an optional string to the template containing any additional classes that will be needed to display the correct vendor section.  You can add the new classes the the `ul` element in AffiliateLinks.html.

CSS for the vendor link section can be found here: https://github.com/internetarchive/openlibrary/blob/master/static/css/components/read-panel.less

**Comment by ztjhz** [comment]
I would like to work on this

**Comment by jimchamp** [comment]
Thanks @ztjhz!  Let me know if you have any questions.

**Comment by ztjhz** [comment]
@jimchamp 
May I know where the omnibar is at? I do not see it in the book page:

<img src="https://user-images.githubusercontent.com/59118459/193035733-f6500b96-7a70-463f-a365-98a3939c3dbc.png" height=500/>

**Comment by jimchamp** [comment]
This is the omnibar:
![Screenshot from 2022-09-29 10-23-25](https://user-images.githubusercontent.com/28732543/193057922-9850c49e-0adc-4241-8a50-6e7e35b1f1d2.png)
_Mobile view_

![Screenshot from 2022-09-29 10-22-24](https://user-images.githubusercontent.com/28732543/193057986-e184242b-88e8-418c-a4c3-325d4bfd0369.png)
_Desktop view_

You can find it by searching for an element with class `edition-omniline`
