### ISSUE TITLE
Convert My Books main nav item to dropdown

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7019]
### Describe the problem that you'd like solved

- My Borrows
- My Reading Log
- My Reading Stats
- My Lists

### Proposal & Constraints

- [ ]  unique analytics on each item (we want to know whether patrons click via hamburger v. the dropdown)

**Comment by Mustafa-Azad025** [comment]
hey @mekarpeles ,
Please Assign This Task To Me .

**Comment by Mustafa-Azad025** [comment]
Please Give The Path Where You Have Created Navbar Section.

**Comment by mekarpeles** [comment]
Hi @Mustafa-Azad025, I think this specific issue may be in current deliberation! @szgrune, Dana, and I will be meeting later this week to determine next steps. Thank you for your patience with us!

**Comment by mekarpeles** [comment]
After consideration, I think we're going to be moving in a slightly different direction #6857 + #7053
