### ISSUE TITLE
Remove trailing translation delimiter (= equals sign) from titles

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#702]
Translated titles of the form "lang 1 = lang 2" have been split, but the delimiter wasn't removed from the first language title. This affects both editions and the works derived from them.

An example is: https://openlibrary.org/books/OL20408332M/Cyllidebau_ysgolion

**Comment by hornc** [comment]
We should add a test case to the appropriate import path to ensure this case is handled on import.

Need an appropriate MARC record for the test, https://openlibrary.org/show-records/talis_openlibrary_contribution/talis-openlibrary-contribution.mrc:3105569389:534 (form the original report will do nicely)
