### ISSUE TITLE
Main Site Navigation Hamburger: More consistent sections

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7021]
Dana to add a screenshot + notes!

**Comment by BoseSj** [comment]
I would to work on it. Please let me know what to update in the Hamburger menu?

**Comment by mekarpeles** [comment]
Hi @BoseSj! Thanks for your offer to help. Dana is finalizing designs and we should be able to followup soon with next steps!

**Comment by BoseSj** [comment]
Oh! Cool enough! 😄

**Comment by mekarpeles** [comment]
Here's a draft PR which we can work from (it has some of the changes staged to show which files are related and what some of these changes may look like!)

https://github.com/internetarchive/openlibrary/pull/7140

We'd really love help bringing this over the finish line, cc: @BoseSj 

Dana should be replying shortly with the changes to make!

Thank you everyone and excited for these great changes to become a reality! :tada:

**Comment by danafein** [comment]
Hi @BoseSj! Thank you so much for your interest in updating the Hamburger menu!
 
The goal of the update is to make the menu clearer and more concise and consistent with the rest of the navigation on the site.

Specifically, we would like the hamburger menu to look like this:
<img width="193" alt="Screen Shot 2022-11-04 at 11 08 45 AM" src="https://user-images.githubusercontent.com/30005120/200941439-c974164f-918f-42be-b355-d81a2b42bbb3.png">

The main changes are:

- Include a “My Books” button at the top of the hamburger, before “My Profile”. This should link to the loans page for now. This section should also have an italic subheading that says, "Loans, Reading Log, Lists, and Stats".
- Remove “My Loans”, “My Reading Log”, “My Lists”, and “My Reading Stats” from the hamburger menu
- Split the “More” subheading into “Contribute” and “Resources”. Contribute should include “Add a Book”, “Recent Community Edits”, and “Developer Center”. Resources should include “Help & Support”

Thank you again for your help, and let me know if you have any questions!

**Comment by mekarpeles** [comment]
Passing to @jimchamp for now so we can shoot to get this out this week (by next Tuesday deploy)
