### ISSUE TITLE
Two entries for Bibliothèque Nationale de France in Identifier list, one does not work

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7030]
The French National Library has two entries in the Identifiers list in the book edit page.

1. Bibliothèque Nationale de France
2. Bibliothèque nationale de France (BnF)

Only the first one works, the second one has no effect.

Furthermore, it is not clear which identifier from the BnF should be included, they have two:
1. Identifiant de la notice  : ark:/12148/cb45200132d
2. Notice n° :  FRBNF45200132

### Relevant url?
https://openlibrary.org/books/OL32419698M/Hopeless

### Steps to Reproduce
Open any French book
Find the book in the catalogue of the Bibliothèque Nationale de France, in the case of my example:
https://catalogue.bnf.fr/ark:/12148/cb44219691j
Attempt to add one of the identifiers to each of the two entries from the identifier list:
- Bibliothèque Nationale de France
- Bibliothèque nationale de France (BnF)
The first entry should result in a new identifier in the list, the second will have no effect.

* Actual: I feel confused, which identifier to use and which identifier list entry to use. Then, one does not even work.

* Expected: There is either one clearly labelled identifier or two clearly separate identifiers, where it is clear which identifier from the source to enter.

### Details
- **Logged in (Y/N)?**
Yes

- **Browser type/version?**
Firefox 104.0.2 

- **Operating system?**
Suse Tumbleweed

- **Environment (prod/dev/local)?** 
prod

### Proposal & Constraints
There are two possible solutions:

1) Remove one identifier and clearly mark the expected identifier in the entry, 
i.e. Bibliothèque Nationale de France (ark)

2) Keep both identifiers, but make sure both work and tie them to the different identifiers the library uses.
Bibliothèque nationale de France ("ark" or "Identifiant")
Bibliothèque nationale de France ("FRBNF" or "Notice n°")

### Related files
Issues:
#6108
#5790
#6300

### Stakeholders
Everyone who enters identifiers or uses them to cross-check information.

**Comment by tfmorris** [comment]
The first entry doesn't have have a "url" key, so won't work as a link. It should just be deleted from https://openlibrary.org/config/edition (which I don't have the permission to do). The second entry will work when the bug described in #7032 is fixed.

The current URL value ("http://catalogue.bnf.fr/rechercher.do?motRecherche=@@@") will work with the ARK suffix that you used, cb45200132d, (as well as EAN/ISBNs). It could also switched to the slightly more direct "https://catalogue.bnf.fr/ark:/12148/@@@"

**Comment by cdrini** [comment]
Choosing the first one since it has 303 instances in OL, vs the second which has a strange key (`bibliothèque_nationale_de_france_(bnf)`) and only 92 refs.

These need to be transferred over: http://openlibrary.org/query.json?type=/type/edition&identifiers.biblioth%C3%A8que_nationale_de_france_(bnf)~=*&limit=500

**Comment by cdrini** [comment]
Actually I'll just leave open instead of creating another issue. @scottbarnes would you be able to create a small notebook to iterate over the ~90 results in the above link, and edit their identifiers section to change `bibliothèque_nationale_de_france_(bnf)` to `bibliothèque_nationale_de_france`? I'll assign to you if so :)

**Comment by scottbarnes** [comment]
@cdrini, I can most definitely do so and would like to so. :D

**Comment by scottbarnes** [comment]
@cdrini, thanks for your help. This is now done and the Google Collab workbook (readonly) is here: https://colab.research.google.com/drive/1LrPwzrVox0BIjYU_DFTU1J36cvZW_Y9i?usp=sharing

**Comment by cdrini** [comment]
Woohoo! Thanks @scottbarnes !
