### ISSUE TITLE
Edition page displays work title instead of edition title

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#704]
![image](https://user-images.githubusercontent.com/6251786/34456349-ea72829c-ed61-11e7-93ac-3abffc7fcc68.png)

https://openlibrary.org/books/OL18774656M/O_senhor_dos_Ane%CC%81is_II

This should display the Portuguese title (as seen in the URL).

**Comment by mekarpeles** [comment]
Especially as we move towards `canonical book` pages, how should titles show? Every page will effectively be a "work" page with a specific "edition" loaded.

Should we *always* show the edition title?

**Comment by seabelis** [comment]
Seems like this was fixed at some point.

**Comment by guyjeangilles** [comment]
Confirmed doesn't appear to be an issue anymore. @cdrini reopen if you disagree
