### ISSUE TITLE
Lack of DDC

### ISSUE THREAD

**Issue by damiankomonski** [internetarchive/openlibrary#7043]
Hello,

I am working with this API and create application. I decided to show categories according to DDC number. When I search something on this endpoint:
https://openlibrary.org/search.json?q=ddc:1*&sort=new&limit=40&offset=4&fields=*

and next I get data about some book in this endpoint:
https://openlibrary.org/api/books?bibkeys=OLID:OL37756350M&format=json&jscmd=details

I don't have "dewey_decimal_class" field. In some books this property is, and in some books not.

For example, in this work: OL27402076W we have two books OL37756350M and OL37310441M. In one open library return "deway_decimal_class" and in second not. 

This lack make it impossible to show categories... In my opinion every book should have this number.

**Comment by damiankomonski** [comment]
Also it will be nice if Open Library API returned DDC category name apart from DDC ID.

**Comment by damiankomonski** [comment]
Hello, any new informations?

**Comment by cdrini** [comment]
Hi @damiankomonski ! `ddc` is included in the results from the search.json endpoint. Can you use that in your application? The search.json endpoint combines information from _all_ editions of a work.

**Comment by cdrini** [comment]
Closing due to lack of response on this one. The search.json is the preferred over bibkeys for accessing book metadata and should provide the desired data!
