### ISSUE TITLE
How to get redirected to merged work when using JSON API without making two calls?

### ISSUE THREAD

**Issue by jollygreenegiant** [internetarchive/openlibrary#7044]
### Question
Is there a way to make a call to the JSON API redirect if the work being called has been merged, and redirects to a different work ID?

### Additional context
For example: work OL20867910W was merged, and the page now redirects to OL2707221W.  When going to openlibrary.org/works/OL20867910W, it redirects to the new merged work, as you'd expect.  But when calling openlibrary.org/works/OL20867910W.json to get the JSON data of the work, it doesn't redirect.  

I assume this is intended behavior, and I see that there is a `location` field on the JSON response that has the new work id on it, but is there a way to get the redirect on an API call without having to make two calls?  (one to get the old work, and then another if `location` != `key`)

**Comment by tfmorris** [comment]
Note that redirect processing is done client side, so you're going to have to make two requests either way. You won't save any latency or other overhead, just the one or two lines of extra code. On the flip side, you'd lose all the information that's in the current payload.
