### ISSUE TITLE
Recommendations on how to handle inconsistencies between Search API and Books API (cover_i)

### ISSUE THREAD

**Issue by wanecek** [internetarchive/openlibrary#7048]
### Question

What is the recommended way of handling inconsistencies between Search and Books/Works API, mainly arising from editions, specifically on covers?

### Additional context

I am working on a side-project that relies on the OpenLibrary API for finding books, retrieving the title, author(s), and cover for works. I use the Search API with the query search parameter. For security reasons, I send the key to the server-side, which again tries to find the same book to extract the same information, rather than allowing the client to submit these fields directly.

More concretely:

- For example, the user might search for "Less is More Hickel", yielding a query such as `https://openlibrary.org/search.json?q=less+is+more+hickel&fields=key,title,cover_i,authors`, from which the user may select the first item, which has a title, author and cover_i.
- We extract the `key` from this, which is `/works/OL21695547W`. 
- On the server-side, I use the Books API to attempt to fetch the same information: `https://openlibrary.org/works/OL21695547W.json`. **This does, however, not have a cover.** (Also, to get the author name, another request is required).

My questions are then:
- Is this intended behavior? As far as I understand it, this arises from the book having several editions, of which only one has the cover.
- Are there any suggested ways to work around this? Using the Search API again, i.e. querying `https://openlibrary.org/search.json?q=/works/OL21695547W&fields=key,title,cover_i,authors`? Or is there a way to specify fields for the /works/<id>.json urls that I cannot figure out?

### Issue resolution criteria

As soon as an answer is posted, even if it's that we don't know or that this is intended behavior (and my way of trying to manage this is the problem), I'm happy.

### Stakeholders

--- 

thank you all for your work on this!

**Comment by tfmorris** [comment]
Covers are attributes of editions, not works, but the search API only searches works (aggregated from the data for editions), not the editions themselves, which is part of the discontinuity that you're seeing.

Why not just request all the info you need from the Search API, so you don't have to make additional calls? It doesn't have a field called `authors` (as you have in your example), but you could do something like:

https://openlibrary.org/search.json?q=less+is+more+hickel&fields=key,title,cover_i,cover_edition_key,edition_key,author_name,author_key

If you need more detail on the edition associated with the cover, it's available using the `cover_edition_key` value https://openlibrary.org/books/OL29518280M.json

**Comment by wanecek** [comment]
Sounds like an excellent solution - thank you for taking the time to reply.
