### ISSUE TITLE
Provide way to merge two authors other than search list

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#705]
These two authors:

[Thompson, J. J. Lieutenant.](https://openlibrary.org/authors/OL5076381A/J._J._Thompson)
[J. J. of Brookville, Mississip Thompson](https://openlibrary.org/authors/OL3733204A/J._J._of_Brookville_Mississip_Thompson)

are basically impossible to merge with the current UI, short of resorting to manipulating URLs by hand (dangerous!) because the only search terms they share in common "J J Thompson" returns 342 hits while the merge listing is limited to some smaller number (100?).

An interface where you could navigate to one author and then select the other(s) via search might be one solution.

**Comment by mekarpeles** [comment]
Related: #357

**Comment by cdrini** [comment]
Note as a workaround, since author search allows lucene syntax you can search for i.e. `key:(/authors/OL1000A OR /authors/OL5000A)`  https://openlibrary.org/search/authors?q=key%3A%28%2Fauthors%2FOL1000A+OR+%2Fauthors%2FOL5000A%29

**Comment by LeadSongDog** [comment]
Common VIAF, ISNI, or wikidata ID ought to catch these once populated

**Comment by guyjeangilles** [comment]
@hornc Another issue that I think you should be assignee for this issue. Are you willing? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by RayBB** [comment]
This is resolved now as people with merge powers can select an author on one page then navigate to another and select it and both will be there.
