### ISSUE TITLE
The ISBN-10 and ISBN-13 markers in the add books page do not check for number length.

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7055]
If I add a new book and accidentally check ISBN-13 while inputting an ISBN-10 (or vice-versa), I do not get an error message.

### Evidence / Screenshot (if possible)
![Add-Book-ISBN-13](https://user-images.githubusercontent.com/36878944/194121565-0eaa366b-9828-4aa1-93e3-cf890eeb933c.png)
![Edit-Book-ISBN-13](https://user-images.githubusercontent.com/36878944/194121573-2c65d0ab-11ce-4077-9609-26375afe646d.png)

### Relevant url?
https:/openlibrary.org/books/add

### Steps to Reproduce
Add a new book
Enter an ISBN-10, but choose ISBN-13 from the drop down list
The ISBN will be placed as ISBN-13, even though it is to short

* Actual: The ISBN will be placed as ISBN-13, even though it is to short

* Expected: Either a) the programme automatically chooses the correct ISBN type, depending on length, or b) I get an error message that the number is to long / short.

### Details
- **Logged in (Y/N)?**
Yes

- **Browser type/version?**
Firefox 104

- **Operating system?**
Suse Tumbleweed

- **Environment (prod/dev/local)?** prod
prod and testing

### Proposal & Constraints
Use the same check for ISBN length in the add book page as in the edit book page.

### Related files
#4548
#6634
#4343

**Comment by feteezuk** [comment]
I'm working on this.
