### ISSUE TITLE
Automatic choice of identifier can cause an librarything ID to overwrite an ISNI ID

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7072]
If one edits an author, one can choose between several identifiers. ISNI and Wikidata are automatically selected, when the appropriate data is put into the form.

Sometimes, librarything identifiers are falsely detected as ISNI identifiers. In those cases, one has to select the identifier after putting the data in, otherwise an existing ISNI will be overwritten.

### Evidence / Screenshot (if possible)
![Screenshot_20221011_161601](https://user-images.githubusercontent.com/36878944/195115983-32578b90-9c65-43cc-9bd3-431a8d93e077.png)

### Relevant url?
https://openlibrary.org/authors/OL7504499A/

### Steps to Reproduce
1. I added identifiers to author Diandra Linnemann (it also happened with other author's).
2. After I selected the identifier librarything and put the data in, the selection switched to ISNI.

(This also happens with other author's, and it might also happen with certain VIAF IDs. - so far, I can only recall cases where it was caused by librarything.)

* Actual: The librarything identifier is saved as ISNI.
* Expected: The librarything identifier is saved as as librarything identifier.

### Details

- **Logged in (Y/N)?**
Y

- **Browser type/version?**
Firefox 104.0.2

- **Operating system?**
Suse Tumbleweed

- **Environment (prod/dev/local)?** prod
prod

### Proposal & Constraints
As far as I am aware, ISNI always starts with a number whereas librarything always starts with a letter. Perhaps this difference can be used to tell both apart. An other option would be to deactivate the automatic selection completely.

### Related files
#6423
#853
#856
#2744

**Comment by davidscotson** [comment]
Code seems to be here:

https://github.com/internetarchive/openlibrary/blob/fd89f0c9d64efbfc90e07a208572993e69dfee1f/openlibrary/components/AuthorIdentifiers.vue#L103

So tightening the regex for wikidata to match only if the Q is only preceded by whitespace characters and only followed by numbers then whitespace could help.

And the insi check could be changed to match 16 digits or 15 digits and an X, according to the wikidata regex matcher:

https://www.wikidata.org/wiki/Property:P213#P8966
