### ISSUE TITLE
Some publisher links are broken

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7074]
From a patron:
Searching for a publisher sometimes brings up no results, even if the search was from a direct link showing multiple books to that publisher. For example:

https://openlibrary.org/search/publishers?q=%22Media+Blasters%22

Clicking on the link for "Media Blasters 147 books" results in "We couldn't find any books published by Media Blasters." So where are the 147 books?

### Relevant url?

https://openlibrary.org/search/publishers?q=%22Media+Blasters%22
https://openlibrary.org/publishers/Media_Blasters
### Steps to Reproduce

1. Go to ... https://openlibrary.org/search/publishers?q=%22Media+Blasters%22
2. Do ...click the first entry, https://openlibrary.org/publishers/Media_Blasters

* Actual: no books
* Expected: should see 147 books

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Maybe solr related?

### Stakeholders

@cdrini @mekarpeles @jimchamp

**Comment by onnotasler** [comment]
I can confirm this problem. When I open the work OL27025404W and click on the publisher link, I get an error page saying this publisher would not have any books.

On book page
![Screenshot_20221023_235628](https://user-images.githubusercontent.com/36878944/197420101-9d0085b5-5810-4ec0-b024-7e2acff1942b.png)

On publisher page
![Screenshot_20221023_235646](https://user-images.githubusercontent.com/36878944/197420105-9446e030-ac9d-4711-8542-c81b10f6cca1.png)

**Comment by davidscotson** [comment]
The issue appears to be affecting publishers with a space in their name, which is being converted to a _ for the url, but then being searched as a literal _ (which sometimes finds a few matching entries).
