### ISSUE TITLE
Empty field for weight unit results in crash upon saving 

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7075]
In certain instances, items are imported with an entry in the weight field, but no weight unit (grams, kilos, ounces, pounds) selected.

This will lead to a crash when one attempts to edit and save that item without setting a weight unit.

### Evidence / Screenshot (if possibl
![Screenshot_20221012_190916](https://user-images.githubusercontent.com/36878944/195406212-ebac4f3d-bc5d-4136-aafe-b5aa978c8914.png)

Also, see error report 2022-10-12/170923872798.

### Relevant url?
https://openlibrary.org/works/OL27130932W/

### Steps to Reproduce
1. Edit the work OL27130932W as usual (it works with any work that has an entry in weight but no weight unit).
2. Save the work without selecting a weight unit.
3. Error message, work is not saved.

* Actual: Error message, work not saved
* Expected: Work saved or notice that one needs to select a measurement if the weight field is not empty.

### Details

- **Logged in (Y/N)?**
Y

- **Browser type/version?**
Firefox 104-2

- **Operating system?**
Suse Tumbleweed

- **Environment (prod/dev/local)?** prod
prod

### Proposal & Constraints
The work should either save or tell me how to solve the problem.

**Comment by scottbarnes** [comment]
I would like to work on this.
