### ISSUE TITLE
Add real-time validation for emails/screennames taken on IA to prevent random digit appending

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7080]
Patron reports that their chosen username was appended with numbers. The patron was not informed that this would happen during registration and understood the chosen username was available.

### Steps to Reproduce

According to @mekarpeles , this happens when the [archive.org](http://archive.org/) ID they request is available but the open Library ID is not.

* Actual: No warning that the chosen username is not available and will be appended
* Expected: If chosen username is not available warn the patron and give the opportunity to choose a different name.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by happycoding47** [comment]
Hi @seabelis, I'd like to help solve this issue if it's still open. Please guide. Thanks!

**Comment by seabelis** [comment]
Perhaps @mekarpeles can provide some guidance on this?

**Comment by mekarpeles** [comment]
@happycoding47 if you'd like to take a look at the code in openlibrary/account/model.py you should be able to see where this logic is being done within the `audit` function. See if you can propose a better way of doing this!
