### ISSUE TITLE
Delete all Alice Kirk / BookBoon spam

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#711]
https://openlibrary.org/people/AliceKirk
I came across this during the author merge cleanup because Alice created dozens of duplicate author records for the same person. 

Originally I thought this and the repetition in books e.g.
https://openlibrary.org/search?q=title%3A+%22Innovative+Design+Guidebook+for+Game+Changers%22&mode=everything

were just innocent mistakes, but after looking a little further I realized all the entries are just designed to turn OpenLibrary into a giant link farm for BookBoon.

In some cases, records were actively vandalized, like these two where works were retitled and reauthored: 

- https://openlibrary.org/works/OL2994057W/Long-Term_Assets?b=5&a=2&_compare=Compare&m=diff
- https://openlibrary.org/works/OL6830628W/Careering_Ahead?b=4&a=2&_compare=Compare&m=diff

**Comment by mekarpeles** [comment]
@tfmorris can I move this data cleanup task to https://github.com/internetarchive/openlibrary-client and tag @hornc?

**Comment by tfmorris** [comment]
Sure. I presume that you agree with the sentiment then.

**Comment by mekarpeles** [comment]
Yes, those 2 examples especially look egregious. 

https://openlibrary.org/works/OL2994057W/Capital_budgeting also has two editions both from 2013.

**Comment by mekarpeles** [comment]
Moved here: https://github.com/internetarchive/openlibrary-client/issues/68

**Comment by mekarpeles** [comment]
The user is blocked. There is an issue with reverting all of their changes because one of them has already been deleted and is registering as /type/delete instead of /type/author.

```
<class 'infogami.infobase.client.ClientException'> at /admin/people/AliceKirk/edits
expected /type/author, found /type/delete

Python | /opt/openlibrary/deploys/openlibrary/824a904/infogami/infobase/client.py in handle_error, line 84
POST https://openlibrary.org/admin/people/AliceKirk/edits
```

**Comment by mekarpeles** [comment]
Closing this issue and making reversion of AliceKirk success for #4045
