### ISSUE TITLE
GET with ampersand-chained values for same parameter returns only data related to the last one

### ISSUE THREAD

**Issue by CBazille** [internetarchive/openlibrary#7110]
When requesting data from an API using HTTP GET, both those two formats are commonly accepted:

- https://example.org/api/endpoint?param1=value1&param1=value2
- https://example.org/api/endpoint?param1=value1,value2

It is assumed by some REST frameworks, such as `RestSharp` for the `C#` programming language, that [both those formats are valid](https://en.wikipedia.org/wiki/Query_string#Web_forms) and that "it does not matter" which one is used. Hence the aforementioned framework settles on using the first format, chaining multiple values for the same parameter with an ampersand.

As far as I can tell, this format is currently not accepted by the OpenLibrary API. Furthermore, the API request does not fail but only returns data associated to the last parameter provided, which might return misleading results. For example:

- Works as expected: https://openlibrary.org/api/books?bibkeys=ISBN:9780553293357,9782017088578&format=json&jscmd=data
- Does not work as expected: https://openlibrary.org/api/books?bibkeys=ISBN:9780553293357&bibkeys=ISBN:9782017088578&format=json&jscmd=data

By "as expected", I mean here that both URIs should return the same data, since both are assumed to be acceptable.

### Describe the problem that you'd like solved
I would like to be able to send GET requests to the OpenLibrary API using both "&-chaining" and "comma-chaining" formats for same-name, multiple-valued parameters, i.e. calling the API with

- https://example.org/api/endpoint?param1=value1&param1=value2
- https://example.org/api/endpoint?param1=value1,value2

where both formats are accepted and return the exact same data.

**Comment by mekarpeles** [comment]
The formats of the examples are different, one uses bibkeys=ISBN: followed by a list of type ISBN. The second example is duplicating bibkeys (in particular) so these aren't comparing apples to apples.

In any event, while we have plans on improving our more recent API endpoints in the coming months (and using swagger, see some of our open PRs) this direction in particular is not one we plan to work on at this time. Thank you for bringing it to our attention!

**Comment by CBazille** [comment]
Sorry, reading your comment, it just now dawned on me that the format `ISBN:xxx,yyy,zzz` maps to a list of type `ISBN`. This might actually help me solve my problem in my own code... As I forgot to mention, I am still a beginner with Rest APIs and have a lot to learn.
Thank you for taking the time to answer !
