### ISSUE TITLE
Bad author merge for Kathleen Morgan from 2013

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#712]
The merges from 2013 need to be undone. They've conflated a novelist with a statistician and affected thousands of works.

https://openlibrary.org/authors/OL24370A/Kathleen_Morgan

**Comment by LeadSongDog** [comment]
The statistician is https://viaf.org/viaf/73431623
The pulp romance author is https://viaf.org/viaf/9176228
