### ISSUE TITLE
Add a standalone dump of Redirects?

### ISSUE THREAD

**Issue by ldorigo** [internetarchive/openlibrary#7121]
### Describe the problem that you'd like solved

Currently, it's possible to download Authors, Works, and Editions separately, however it's impossible to reconstruct a database from those three files because a lot of the OLIDs found in Works/Editions are not valid but rather redirects. This means it's necessary to download the full dump.

### Proposal & Constraints

Add a fourth "Redirects" dump with the missing redirects :-)

**Comment by tfmorris** [comment]
It would be nice to have a dump of the redirects, but I'd consider a bug to have redirects referenced in the production data. Those objects should be rewritten when the objects they reference are merged. If there are redirects in there, it's both a performance and a data integrity issue.

**Comment by mekarpeles** [comment]
We have bots which are going through and fixing redirects. We don't currently plan on releasing a separate dump of redirects though if anyone else wants to create one, please feel free!. Closing as not planned.
