### ISSUE TITLE
Pre-load BWB Promise Items into OpenLibrary

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7132]
To increase the robustness of Internet Archive digitization operations, load BWB `DailyPallets.json` data from archive.org promise / protodonation items into Open Library and enable querying of this data by `bwbsku` local_id.

**Comment by mekarpeles** [comment]
@jimchamp if you can please review the 2 PRs then this issue is losed

**Comment by jimchamp** [comment]
PRs have been reviewed and merged.  To date, all BWB promise items queued for import have been processed.
