### ISSUE TITLE
Searching for Mrs Manly returns Mrs Manning

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#715]
Thes search: https://openlibrary.org/search/authors?q=mrs+manly
returns these 3 results:

- **Manning** Mrs. 
2 books about To 1200, Sanskrit literature, India, History and criticism, Hindu civilization, Hindu Civilization, Civilization, Medieval, in literature, Civilization, Accessible book, including Ancient and mediaeval India

- Hockett, Ruth Marie **Manning** Mrs. 1895 - 
1 book about Training of, Teachers, including Visitors in an experimental school

- **Manning**, Tom Mrs. 
1 book including A summer holiday on Hudson Bay

There are apparently not [Mrs. Manley](https://openlibrary.org/authors/OL675161A/Manley_Mrs.) which is closer both phonetically and from an edit distance point of view. 

---------

Merged from #1567 

The search https://openlibrary.org/search/authors?q=berning returns completely unusable results.

I'm guessing that this is because it's being stemmed to "bern" and matched with other things with that stem, including Berne, Berns, etc.

The net results that the handful of Bernings are mixed in among over 500 other search hits.

**Comment by mekarpeles** [comment]
Of potential interest to @cdrini

**Comment by guyjeangilles** [comment]
This still is a problem. @tfmorris @cdrini Are either one of you willing to assignee for this project? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
This are two problems which need fixing here:
- Turn off English stemming on indexing for author names, since stemming is in appropriate for proper names (in addition to being English only)
- Use approximate search queries to find terms within a certain edit distance range - https://stackoverflow.com/a/20893636/167425

**Comment by LeadSongDog** [comment]
Unwanted stemming is also a problem in titles. A search for "Eve" is swamped with "Every", "Even", "Evening", etc. There should be a way to ask for exact matches only.

**Comment by LeadSongDog** [comment]
@tfmorris Going back to your original search, I notice that https://openlibrary.org/search?author=Mrs+Manley gives rather more precise results, while https://openlibrary.org/search?author=Mrs+Manly returned "No results found". This is a variation on the problem of needing a homophone matching option.

**Comment by cdrini** [comment]
This was fixed by #5600 .
