### ISSUE TITLE
Google Search results have begging plea instead of information

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#716]
It's bad enough that I have to dismiss this obnoxious begging multiple times a day, but now it's polluting the search results too.

https://www.google.com/search?q=George+Geith+of+Fen+Court

George Geith of Fen Court. A novel : Riddell, J. H., Mrs., 1832-1906 ...
https://archive.org/details/georgegeithoffen00riddrich
Donor challenge: A generous supporter will match your donation 3 to 1 right now. $5 becomes $20! Dear Internet Archive Supporter,. I ask only once a year: please help the Internet Archive today. We're an independent, non-profit website that the entire world depends on. Our work is powered by donations averaging about ...

**Comment by mekarpeles** [comment]
:( Yeah, we tagged @evanminto and @rchrd2 about this as well -- on our (OL) side, there are certain semantic changes we should be making to our markup to help google et la index correctly (including using `header` and `main` html tags correctly). As a safeguard, our banner should stop showing up in a few days though it would be ideal if we can update the markup to prevent this from happening.

**Comment by guyjeangilles** [comment]
I'm not seeing the donor begging in the links in the original issue. I propose closing this issue.

**Comment by hornc** [comment]
agree!
