### ISSUE TITLE
Merged authors removed from work and edition histories

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7163]
Sometimes there are errors with author merges and looking at histories helps to sort this out. Now it seems if an author has been merged, the ID is no longer present in a work/edition history making it appear as if the current author is as entered.
### Evidence / Screenshot (if possible)
Same edition history before and after restoring the merged author.
<img width="1243" alt="Screenshot 2022-11-17 at 17 58 44" src="https://user-images.githubusercontent.com/17739465/202509604-7e27c46a-6f3d-4212-9555-23152f85a135.png">
<img width="1173" alt="Screenshot 2022-11-17 at 17 58 16" src="https://user-images.githubusercontent.com/17739465/202509610-cab8424e-733b-4357-bb9d-7b89424ce1b3.png">

### Steps to Reproduce

1. Go to ...an edition or work with an author merge in it's history.
2. Do ...try to see what the original author was by looking at the diff.

* Actual: the diff appears as if there has been no change
* Expected: the change should appear in the diff

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini @mekarpeles @mheiman @jimchamp

**Comment by cdrini** [comment]
Fixed by #7368

![image](https://user-images.githubusercontent.com/6251786/235525008-63927c23-467f-4066-ae47-c39dd190dfd1.png)
