### ISSUE TITLE
Corrupted OCLC via Google books record

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#717]
https://openlibrary.org/books/OL20461153M/Thom%EF%BF%BD_Hobbes_Malmesburiensis_opera_philosophica_qu%EF%BF%BD_latine_scripsit_omnia_in_unum_corpus_nunc_...

- The OL metadata is about Thomæ Hobbes' 1839 Opera Philosophica and has error characters for the æ characters that it contains.
- The IA metadata is about a 1988 International Energy Agency publication.
- The page images are of the 1839 book.

This is one of the million or so books that was ripped off from Google, so it wouldn't have come through the normal scanning workflow.

If the root cause can be diagnosed, we should figure out how many other volumes are affected.

**Comment by mekarpeles** [comment]
@hornc -- we may want to look into what systemically is occurring on Open Library backend that makes these pages display as they do.

- is it a limited case? a data cleanup task?
- or is there something wrong in our OL logic

**Comment by LeadSongDog** [comment]
In this instance the problem is not local to OL. The IA file name agrees with the contained images but does not align with the IA metadata. OL errs in taking the IA data on its face value without checking,but this fragility is only an aggravating factor not the root cause.

**Comment by LeadSongDog** [comment]
It appears the IA metadata faithfully reflects the wrong OCLC number, for the IEA report. Oddly the google identifier xWEYAAAAIAAJ was not ported from the IA metadata to OL. It agrees with the Hobbes images contained.

**Comment by tfmorris** [comment]
@LeadSongDog I'm not sure I followed your two comments. What do you think is the most likely source of the error?

**Comment by LeadSongDog** [comment]
I would be asking where that erroneous OCLCno came from. At first blush it seems to have been on the IA record before the OL record. Once there the rest of the bad metadata would be bot populated without checks in the normal course of events.

**Comment by LeadSongDog** [comment]
As of now, the google record xWEYAAAAIAAJ links to the correct OCLCno 349834, but there's no obvious-to-me way to determine if that was the case back on 2008-10-27 when OL pulled in the IA record, or rather earlier when IA first pulled in the Google record. Is there a history available somewhere for the IA records?

**Comment by hbromley** [comment]
The Google page as it was when the ingest to archive.org occurred is preserved at:

https://archive.org/download/thomhobbesmalme01molegoog/thomhobbesmalme01molegoog_desc.html

In the "Find this book in a library" link on that page (top right), you can see that at the time, Google linked incorrectly to OCLC number 19295369, which corresponds to the "Emission Controls" book.

In archive.org task 42164116, logged at:

https://catalogd.archive.org/log/42164116

we can see that the (incorrect) OCLC was mapped to a LCCN, which in turn was used to obtain MARC.

This kind of problem was common during our initial ingest of ~1 million public domain Google books. Time was never allotted to incorporate sanity checks into the MARC fetch (which might have automatically flagged such drastic changes in metadata for human checking). At least several hundred archive.org items ended up with incorrect metadata as a result, many of which have since been fixed.

For Archive staff with access to the in-house wiki, there's a set of notes on how to correct this and related problems at https://wiki.archive.org/twiki/bin/view/CollectionsBox/CollectionsHowTo#FixGoogleBookOclc . It addresses three cases:

* Case A: Google had wrong OCLC number, and still does
* Case B: Google had wrong OCLC number, but has since been corrected
* Case C: OCLC number was right, but OCLC's xISBN service converted the OCLC number to the wrong LCCN

What we have here is Case B, for which the twiki page says:

> Diagnosis:
>
> While checking for Case A, you may find that the current Google page has a different OCLC number (in the "Find this book in a library" link) from the one in our saved copy of the original Google page. If so, follow the link and confirm that the resulting WorldCat page is for the correct book. Grab the correct OCLC number from the worldcat.org url.
>
> Correction:
>
> Do steps 2 through 6 given in the Case A correction. 

which are:

> 2. Run modify_xml to insert the correct OCLC number as oclc-id (if the wrong one is simply removed, we would pick it up again from our saved copy of the Google book page), and if lccn is present, remove it. [This step can be done in bulk for all similarly affected items.]
> 3. If the item contains a wrong MARC record, delete the dc.xml, marc.xml, and (if present) meta.mrc. [Must be done individually for each item.]
> 4. Run the CleanMeta bookop ("Multi-purpose cleanup of metadata for ImagePDF books"). [Can be done in bulk.]
> 5. Check the bookop log or refresh the details page (&reCache=1) to see if we found a new MARC record. If so, the item is fixed; if not, you'll need to resort to another method (consult with Hank).
> 6. Inform Open Library (Edward) that the item's metadata has changed.

**Comment by LeadSongDog** [comment]
@hbromley Thank you for that detailed explication.  I think though that the log entry you intend is actually https://catalogd.archive.org/log/29835457 from 2008-07-16.

On the premise that there are others like this, is there a systematic scrubdown to be run on the whole million? One might merely test to see if the OCLC number has changed at Google, or getting more ambitious test to see if the author name or the title is an approximate match between Google, IA, and OCLC. This should generate a somewhat smaller set needing action, though a few may still slip through.

@tfmorris The ligature "&aelig;" (however it was originally encoded) was in mangled form as "___" right in the original-name field of the pdf image container. I'm not sure why,

**Comment by hbromley** [comment]
@LeadSongDog , no, the task you refer to is from before the (incorrect) MARC record was added. At that time, the metadata was still correct. Task 42164116 (in the "BookOp SetupMetaXML" section) is indeed where the OCLC number was mapped to LCCN, MARC was fetched based on the LCCN, and the existing correct metadata (Thomas Hobbes book) was overwritten with the incorrect metadata (International Energy Agency publication).

**Comment by LeadSongDog** [comment]
@hbromley Hmmm, the earlier task https://catalogd.archive.org/log/29835457 shows the incorrect OCLCno (without saying what it is, just "19295369") under "NEW METADATA:" on the line beneath "the University of California". The later https://catalogd.archive.org/log/42164116 extrapolated from that error in the manner you state.

**Comment by hbromley** [comment]
@LeadSongDog, yes, in that later task, the (incorrect) OCLC number was mapped to LCCN, and that in turn led to the importation of the MARC for the IEA publication and extraction of the metadata from it.

It's true that the OCLC number is itself metadata, and was already wrong before the derive.php task I referred to. It would have been more precise if I had said all the bibliographic metadata _other than_ the OCLC number was correct until that later task. But that bad OCLC number was present in the item from the very first task, as part of the uploaded meta.xml file. The bup.php task you're looking at happens to have dumped the current metadata into the task log (and if you "view source," you can see the corresponding tags - at that point, the `<` and `>` characters weren't being escaped when written into the log, causing misrendering of the log file in html), but that task didn't change any metadata other than inserting the publicdate value. The "NEW METADATA:" caption, and the subsequent dump, is a little misleading, and just reflects the fact that the item now had a publicdate for the first time.

So the OCLC number was already wrong before that bup.php task ran, and the rest of the bibliographic metadata was still correct until the later derive.php task that fetched MARC and overwrote the Hobbes metadata with the IEA metadata.

**Comment by mekarpeles** [comment]
Super glad for the context in this thread, I'm not sure if there's an actionable here and it's be open since 2018 so opting to close unless there's something which needs to be done

**Comment by LeadSongDog** [comment]
@mekarpeles It appears that @hbromley has identified three cases or classes of problem records in the 3 Jan 2018 comment above. The next sensible action would be to create a way to identify the membership instances in each problem class. It strikes me that case B should be fairly straightforward to check. The others may need more subtlety, but let’s get the low hanging fruit first.
