### ISSUE TITLE
Covers low on storage: Archive + free 100GB

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7197]
We have 68gb of storage left on covers! This will likely last ~2months MAX. Need to compress the images on covers.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by onnotasler** [comment]
As far as I see, we are using JPEG as image file format at the moment. Would it be worthwhile to consider a switch to AVIF? As far as I am aware, most modern browsers support AVIF graphic file format nowadays and it offers similar image quality at lower image size.

Here is an example of a workflow to improve size to quality even more:
https://www.tempertemper.net/blog/avif-and-webp-are-not-always-better-than-png-and-jpg

**Comment by cdrini** [comment]
@onnotasler Webp/AVIF support would be a fantastic feature! It would help with page performance as well. Will create a separate issue.

**Comment by cdrini** [comment]
Mek ran his PR code and successfully archive enough covers to free 40gb! Nice work, Mek!
