### ISSUE TITLE
Block User & Revert Edits does not delete editions or works created by that user

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7204]
Sometimes spammers create spam in the form of works and editions. The admin action to block user and revert edits should revert ALL edits by that account, including deletion of any works, editions, or lists created by that account. Currently, this is not happening; I believe it used to. 

### Relevant url?

https://openlibrary.org/admin/people/quickbookshelp8269

### Steps to Reproduce

1. Go to ...a spammer account admin page
2. Do ...click Block and revert all edits

* Actual: account blocked, but edits are not reverted
* Expected: all edits should be reverted, anything created under the account should be deleted

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
This solution may be related / helpful as reference:
https://github.com/internetarchive/openlibrary/pull/6771

**Comment by mekarpeles** [comment]
@jimchamp -- this may be related to #563
