### ISSUE TITLE
ISBNs no longer are linked

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#722]
A recent change removed, from the edition page, the automatic link to worldcat pages for a specific ISBN OR ISBN13. Only if an OCLCno is provided does this link work. This is a giant leap backward.

**Comment by mekarpeles** [comment]
Not intentional change. Likely launched with reading log feature. There's a similar Daisy issue opened. I'll get around to both this week. Thanks!

**Comment by tfmorris** [comment]
What's the ticket # for the feature that broke all this stuff? All I was able to find in a casual search were tickets like this one complaining about the breakage.

#583 looks closest, but it's giant and has a some stuff that hints that it's not what I'm actually looking for.

**Comment by mekarpeles** [comment]
@tfmorris #583 which introduced #557 -- both which should be addressed by #723 (in review).

**Comment by mekarpeles** [comment]
I believe this has been fixed
