### ISSUE TITLE
Edition titles shouldn't be able to be removed

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7265]
It's currently possible to delete edition titles through the web interface. This shouldn't be allowed.

### Evidence / Screenshot (if possible)

This edit removed the edition title: https://openlibrary.org/books/OL2402875M/Medical_Terminology_For_Health_Professions?b=5&a=4&_compare=Comparer&m=diff

Hopefully it was a mistake, but it shouldn't be allowed. 

I confirmed that this behavior is still allowed today: https://openlibrary.org/books/OL2402875M/Medical_Terminology_For_Health_Professions?_compare=Comparer&b=8&a=7&m=diff

**Comment by mekarpeles** [comment]
Ask: HTML validation required to prevent deletion of edition titles.

**Comment by seabelis** [comment]
There  was an issue with a specific patron who felt there was no need for an edition title if there was already a work title. The problem was explained to the patron and they have stopped removing edition titles.

**Comment by Katzmann835** [comment]
Hi, I would like to be assigned to see if I can resolve this issue. Is that okay?

**Comment by Katzmann835** [comment]
If not, is there anything else I can do?

**Comment by scottbarnes** [comment]
I am sorry for being such a joy kill today, @Katzmann835. Alas, this is another one with a linked PR that looks as if it will sort the issue.

However, it might worth checking out the PR (#7342), seeing if you have anything to add, etc. 

I should have mentioned that to the 'right' of the issues, when you search for issues with the ["Good First Issue" and "Needs: Help"](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Good+First+Issue%22+label%3A%22Needs%3A+Help%22) labels, there is a place to see a linked PR, if anyone is assigned, etc.

**Comment by Katzmann835** [comment]
Way ahead of you, I was able to choose something else, thank you for
notifying me.
