### ISSUE TITLE
"All" Searching for an author name does not return books by that author

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7276]
Edition-aware search broke a feature; searching for e.g. "j k rowling" with "All" selected no longer shows books _by_ J. K. Rowling! Only books about her. This is because it requires there be a match of the user query at the edition-level, but the editions in solr do not store any author info. That all lives at the work.

**Comment by seabelis** [comment]
Patrons are reporting this issue.

**Comment by cdrini** [comment]
Proposal: Going to store a copy of the work authors in the solr edition. This is really the only way to make this feasible.
