### ISSUE TITLE
Advertised Work may be different language than its borrowable Edition

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#728]
Editions with titles that are different from the main work (i.e. translations) do not reflect this anywhere in the edition view except for the cover image. See https://openlibrary.org/books/OL26410183M/Orgullo_y_Prejuicio as an example.

**Comment by LeadSongDog** [comment]
Is this not a side effect of another recent issue? I can't find the issue number now but the edition page is showing the work title where the edition title should be.

**Comment by tabshaikh** [comment]
@mekarpeles https://openlibrary.org/books/OL26410183M/Orgullo_y_Prejuicio in this the work is in Spanish and the borrowable edition is in English right

**Comment by guyjeangilles** [comment]
Could not duplicate. Closing
![translation_different_title](https://user-images.githubusercontent.com/7256157/68096164-d4385a80-fea6-11e9-9c9e-69b9938bf26f.png)
