### ISSUE TITLE
Improve WYSIWYG: Replace wmd markdown preview with ProseMirror

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7305]
Open Library uses wmd.js which is no longer actively maintained. Replace it with ProseMirror, which is inline WYSIWIG and very extensible and well supported. https://prosemirror.net/

### Stakeholders
@onnotasler

**Comment by onnotasler** [comment]
For more information on this issue and an explanation why this is necessary, see #7309 and #7261

**Comment by cdrini** [comment]
Merging this with #7308
