### ISSUE TITLE
Turn over reading goal year on Dec 1st

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7322]
### Describe the problem that you'd like solved

If the current year is 2022 and we hit Dec 1st, the Yearly Reading Goal should prompt patrons to add a new goal for the following year (e.g. 2023).

This would mean as of Dec 1, 2022 that the patron would no longer be able to edit their 2022 yearly reading goals (it becomes frozen by the UI).

We should revisit after Jan 2023 (once we have some baseline data)

**Comment by jimchamp** [comment]
Closed by #7346
