### ISSUE TITLE
Add Italian SBN to edition identifiers dropdown

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7323]
From a patron:
_the "ID numbers" dropdown does not list the "Italian SBN", the identification systems used in Italy and managed by the ICCU (Istituto Centrale del Catalogo Unico) of MiC (Ministero della Cultura).
Just for example the identifier "IT\ICCU\CFI\0240439" can be used to identify this work:
https://opac.sbn.it/web/opacsbn/risultati-ricerca-avanzata#1671700893406
(one of the works that I recently edited).
See also: https://en.wikipedia.org/wiki/National_Library_Service_of_Italy_

### Describe the problem that you'd like solved

Add the option to add an Italian SBN to an edition by including it in the identifiers dropdown.

### Proposal & Constraints

As implemented with other edition-level identifiers.

Please see text above.

**Comment by cdrini** [comment]
Hmm this is on the list already, does this meet the bill?

![image](https://user-images.githubusercontent.com/6251786/210435588-3b317c22-b706-4302-9bbc-2067c49ffd7b.png)

**Comment by cdrini** [comment]
I see it here: https://openlibrary.org/config/edition . Oh we might need to make sure we download the changes on the db into the local version! We don't want those to get out of sync further. And then discontinue the online UI. 

ICCU was there for quite a while 😬

**Comment by Freso** [comment]
Ah, but that’s a classification, not an identifier, so not what is being asked for in this issue!

**Comment by cdrini** [comment]
Ahhhh my bad!
