### ISSUE TITLE
Fix Open Library Search Experience for `ebooks` mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#733]
There's a handful of problems with our current Open Library search experience

**Summary:**
Right now, when the `ebook` mode is selected for search, Open Library's Solr returns some `n` pages of results. But Open Library solr **(a)** doesn't have up-to-date availability information and **(b)** classifies books with DAISY only as also having ebooks (which is we've decided against as its not useful to the majority of our readers who can't use DAISY).

Currently, we have to use the archive.org availability v2 API to (after page load) filter out from these `n` pages of Open Library Solr, those entries which don't actually have ebooks . 

**Resulting Bad User Experience:
This might mean, after we filter out works with no ebooks from a results page, that we end up showing users a blank results page (with no `ebooks` results), even if there are **more** OL Solr pages from the catalog possibly containing `ebooks`! There could be hundreds of pages of results, so trying to filter and keep track of Solr pages in order to generate full pages of ebooks is not a viable solution.

In addition, the search results page flickers as we filter out books w/o ebooks. The solution here is to likely move this filtering logic to the backend. 

**How It Does Works, How It Should Work:**
I think with respect to `solr`, `ebook` mode is returning all results that have the `accessible` subject tag and these are **(a)** fairly hopelessly out of date, **(b)** include DAISY only books, which are not relevant to most users, and **(c)** expose us to data integrity risks given, all users currently have the ability to edit a book's subjects (so this is not the criteria/mechanism we should be using for filtering availability).

**Proposal for Recourse(s):**
1) Prevent screen "flicker" caused by `ebook` filtering
Do so by moving filtering logic to the backend for (a) authors, (b) works, (c) lists, and (d) reading log results pages.

2) **Request for comments** we could add a new flag to Open Library `editions` indexed in solr called `lendinglibrary` which is different from the subject/collection tag (controlled by admins) which we use for filtering in `ebooks` mode. cc: @cdrini, @hornc, @brenton  

We'd need to make sure that (similar to our #732 writeback of OL IDs to IA) that when changes are made to lending status on Archive.org, that these `lendinglibrary` flags are accurately written back to Open Library.

3) If there are zero results after filtering, show a message, i.e. #637

**Comment by tfmorris** [comment]
The fact that so-called "ebooks" mode is the default makes this super annoying as a new user experience. The full list of books (ie what they want) flashes briefly on the screen and then disappears without any indication as to why.

Even if this bug gets fixed, it'd be much more user friendly to not filter 90%+ of the editions by default.

**Comment by LeadSongDog** [comment]
Agree. Better to show all, with preference (first listing?) to ebooks, but more broadly defined: a reader likely doesn't care if the ebook is in OpenLibrary or HathiTrust or some other free source. Online at a cost will be better or worse (for some fraction of readers) than physical-for-free at the public library. Both are preferable to dead trees by FedEx. One ranking system should not be forced on all users. Of course, until users have a way to edit there preferences, this point is moot.
