### ISSUE TITLE
Better Author Resolution: Don't create duplicate author records for M. <surname> with exact date match

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7349]
For author records which are a title and surname with an exact match on surname, birth and death dates, such as  [M. Anicet-Bourgeois (1806 - 1871)](https://openlibrary.org/authors/OL11780500A?v=1) and [Auguste Anicet-Bourgeois (1806 - 1871)](https://openlibrary.org/authors/OL2329519A), that should be considered sufficient to not create a duplicate author record.

This duplicate was created just a couple of weeks ago, so it's not just a historical issue.

### Notes by Mek

- [ ] Author Resolution: Ignore case sensitivity for author
- [ ] Author Resolution: Ignore titles e.g. “Dr.” or "M."
- [ ] Author Resolution: Ignore punctuation “.”

### Stakeholders
@hornc

**Comment by tfmorris** [comment]
Actually, the problem is worse than described for this specific example because the MARC record actually includes the given name, but it got dropped during the import. The [edition](https://openlibrary.org/books/OL44269942M) which caused this author record to get created is linked to [MARC record](https://openlibrary.org/show-records/marc_columbia/Columbia-extract-20221130-027.mrc:76220368:1145) where we can see that the author's given name is included in a `100$q` subfield. 

There may be other cases where this isn't true, so I still think the problem as original stated should also be addressed.

**Comment by mekarpeles** [comment]
This should be a subtask of an issue specific to improving **Author Resolution** is already a goal for the year :+1:

**Comment by hornc** [comment]
The specific issue here is that the `M.` is a title and appears in a `100$c` subfield, which I don't think is used to form an alternate name to search against.

My first thought was that the author should be matched if `M. Anicet-Bourgeois` was an alternate name for the existing author, but I'm not sure the titles are being used for this matching.

It's possible the existing author only having the reversed form `Anicet-Bourgeois M.` as an alternate name is confusing the match. 

Is `Anicet-Bourgeois M.` a real alternate name for this author, or should it be `M. Anicet-Bourgeois`, and the combined `100$a` and `100$c` should have produced and matched this exact string?

**Comment by LeadSongDog** [comment]
Please note that the one record links Wikidata, ISNI and VIAF identifiers, and that all of those identify alternate name forms which include the “M.”  It would seem the answer is to just get on with importing those alternate name forms to the AKAs, as librarians have long wanted.
