### ISSUE TITLE
Add Yearly Reading Goals to /stats 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7352]
### Describe the problem that you'd like solved

Adding Yearly Reading Goals to /stats

`select count(*) from yearly_reading_goals`

See:
https://github.com/internetarchive/openlibrary/blob/3b1d509a8a9b4b5c22095664e169950a34cea8b6/openlibrary/plugins/admin/code.py#L564-L607
https://github.com/internetarchive/openlibrary/blob/3b1d509a8a9b4b5c22095664e169950a34cea8b6/openlibrary/plugins/admin/code.py#L465-L489
https://github.com/internetarchive/openlibrary/blob/3b1d509a8a9b4b5c22095664e169950a34cea8b6/openlibrary/views/loanstats.py#L129-L135

A function needs to be added to ~https://github.com/internetarchive/openlibrary/blob/3b1d509a8a9b4b5c22095664e169950a34cea8b6/openlibrary/core/bookshelves_events.py~ (**Correction:** https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/yearly_reading_goals.py) to allow for reading_log_counts similar to https://github.com/internetarchive/openlibrary/blob/3b1d509a8a9b4b5c22095664e169950a34cea8b6/openlibrary/core/bookshelves.py#L46-L74.

![openlibrary org_stats (3)](https://user-images.githubusercontent.com/978325/210180797-4c2048fd-3b1a-4479-afc2-103d7edabf0f.png)

**Comment by Blueclaus13** [comment]
Do you still need help with this? Could I collaborate on it?

**Comment by scottbarnes** [comment]
Hi, @Blueclaus13. I am just another volunteer, but I can see you have been looking hard for an issue. This one seems pretty self-contained, it hasn't been done yet, and it doesn't appear as if anyone else is working on it. If you haven't selected another issue, this might be a good one to work on.

If you decide to give it a go, just mention it here and even if it's not assigned to you immediately, it's unlikely anyone else will work on it. Please also ask any questions you have and we'll do our best to help.

**Comment by SamWilson22** [comment]
Hey @Blueclaus13 and @scottbarnes. I apologize for jumping in taking a look at this issue without discussing it with you first. Let me know if you'd like to collaborate on it going forward.

**Comment by Reykox123** [comment]
I'll keep it in mind, I really need some advice

Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Blueclaus13** [comment]
Don't worry, I hadn't started this issue because I had other assigned.

**Comment by rd713** [comment]
I want to to work on this issue and request to be assigned with this issue

**Comment by kevinc16** [comment]
Hey, I am new to the repo but I would like to work on this!

**Comment by jimchamp** [comment]
Thanks @kevinc16!  The links in the original post have been updated as they were out-of-date.  Let me know if you have any questions.
