### ISSUE TITLE
Add TheStorygraph Identifiers to the book and author identifier lists

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7353]
We already have LibraryThing and Goodreads among our identifiers, which can be very helpful to figure out foreign language translations of a book. Recently, The Storygraph has grown as competitor who targets a different demographic. 

It might therefore be useful to also include their ID in our catalogue, as they might serve to identify connections between works that the other services do not know. They have a function called _Browse editions_ that works very similar to Goodreads edition list.

### Describe the problem that you'd like solved

Add the Storygraph ID to the possible IDs for authors and editions.

### Proposal & Constraints

The StoryGraph ID looks very similar to the Overlook ID we already have.

**Comment by cdrini** [comment]
Hi Onno,

In order to add this, I need information in this format:

```yml
-   label: Goodreads
    name: goodreads
    url: https://www.goodreads.com/book/show/@@@
```

Could you provide the data for storygraph in this format? Note `@@@` is the storygraph ID we'll need.

**Comment by cdrini** [comment]
Done!
