### ISSUE TITLE
Compare versions for edition doesn't handle author redirects correctly

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7355]
Similar to the bug described and fixed in #7283 for works, the compare versions page for editions needs to be taught to correctly handle author redirects (although it isn't entirely clear to me that author merge should be updating authors in edition records rather than just removing them).

### Relevant url?

https://openlibrary.org/books/OL16991306M/Le_proc%C3%A8s_des_Industriels_de_Moscou?m=diff&b=3
https://openlibrary.org/books/OL14240117M.json?v=2
https://openlibrary.org/books/OL14240117M.json?v=3

* Expected behavior: Display looks the same as the work diff https://openlibrary.org/works/OL10928644W/Le_proc%C3%A8s_des_Industriels_de_Moscou?m=diff&b=4

### Stakeholders
@mheiman

**Comment by cdrini** [comment]
@mheiman Do you perchance have any idea what might be causing this?

**Comment by mheiman** [comment]
I believe that the change made in PR #7283 will also resolve this problem for editions. Let's verify after the next deploy and then close this issue.

**Comment by tfmorris** [comment]
I'm confused. Isn't the code from #7283 **already** deployed? I certainly saw a change in the behavior for works.

This code won't work for editions: https://github.com/internetarchive/openlibrary/blob/ec573489995dfd729b9dcdf35b528c6604f9cba4/openlibrary/templates/diff.html#L119-L120
because that's not how the data is structured: 
```json
"authors": [
  {
    "key": "/authors/OL4536950A"
  }
],
```

**Comment by mheiman** [comment]
I see the problem. I always make the mistake of assuming the authors of existing code knew what they were doing. :)

That's a very tiny fix — the PR is out now.

**Comment by tfmorris** [comment]
This is a partial duplicate of #7163
