### ISSUE TITLE
Covers server not returning default author images

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7363]
Previously it would return a dummy image. Now it return alt text because the endpoint errors?

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/6251786/210642102-bda36372-24d9-4f9a-9e88-e2245c403254.png)

### Relevant url?
eg https://openlibrary.org/search/authors?q=e+h+smith&mode=everything

### Steps to Reproduce

1. Go to https://covers.openlibrary.org/a/olid/OL291179A-M.jpg

* Actual: `not found` response
* Expected: Empty single pixel image, or default author image? Whatever it used to do in the past.

### Details

- **Logged in (Y/N)?**N
- **Browser type/version?**FF
- **Operating system?**Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@onnotasler

**Comment by johm** [comment]
This is also happening with cover images for book titles, i.e. this used to return a default blank image and now returns a 404 error: https://covers.openlibrary.org/b/isbn/9780063031616-L.jpg
