### ISSUE TITLE
Manually generate data dump for Jan 2023

### ISSUE THREAD

**Issue by RamshackleBumpkins** [internetarchive/openlibrary#7369]
### Question
Data Dumps not auto-generating looks like it failed again?  Most recent is currently "ol_cdump_2022-11-30" date 1 Dec. See https://archive.org/details/ol_exports?sort=-publicdate

### Issue resolution criteria
When data dumps are available for 1 Jan

Not sure if I should open a bug or reopen 5402, as it looks like that has been fixed (multiple ways).

### Stakeholders
@cclauss @mekarpeles

**Comment by cdrini** [comment]
Hi @RamshackleBumpkins , yes it looks like something went wrong! This is a bug. We'll investigate.

CC @mekarpeles @cclauss

**Comment by mekarpeles** [comment]
Kicked off another dump w/ @cclauss on 2023-01-10 

We updated the docs for kicking this off here:
https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs#monthly-data-dumps

**Comment by cclauss** [comment]
My terminal disconnected so I reran using tmux but then we had two dumps running simultaneously...  Killed both and then started a new 10 Jan 2023 dump.  Updated [Cron-Jobs#monthly-data-dumps](https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs#monthly-data-dumps) to add `tmux` and `ps -ef` and log tailing.

**Comment by cclauss** [comment]
archive_dumps(): ol_dump_2023-01-10 and ol_cdump_2023-01-10 have been archived to https://archive.org/details/ol_exports?sort=-publicdate
