### ISSUE TITLE
Editing adds additional quotes to subject/people marks

### ISSUE THREAD

**Issue by swthemathwiz** [internetarchive/openlibrary#7374]
Merges appear to add quotes to people marks with double-quotes.  Seen here:

https://openlibrary.org/works/OL2950903W/Contact

Presumably, the people mark started as just 'Eleanor "Ellie" Arroway' and it is now up to 'Eleanor """"""""""""""""Ellie"""""""""""""""" Arroway'.

I have seen it grow from recent merges. I have not seen a case with other forms of marks, but I would guess that they are the same. I have not seen the problem with quotes that are not internal nor with single quotes.

The format may be valid or invalid but it should not grow.

**Comment by cdrini** [comment]
Looking at the history for that record: https://openlibrary.org/works/OL2950903W/Contact?m=history It seems to be _editing_ that causes the duplicates quote marks. The merges seem to have no impact.

**Comment by swthemathwiz** [comment]
Oh, that could be. That was my editing, but I certainly didn't add extra quotes.
