### ISSUE TITLE
My Books: Mobile Re-design

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7376]
Designs: https://www.figma.com/proto/KE0BoBAlMPzPHbhvVblKS8/My-Books-Page-Prototype-Flows?node-id=332%3A80&scaling=scale-down&page-id=277%3A2&starting-point-node-id=332%3A80&show-proto-sidebar=1

Implement designs from #6875
 
![image](https://user-images.githubusercontent.com/6251786/210882500-8f77b6f9-ed1f-4aa0-b917-98e491218841.png)

**Comment by mekarpeles** [comment]
Duplicate of https://github.com/internetarchive/openlibrary/issues/6857
