### ISSUE TITLE
Designs for Read button on my books page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7377]
We want the buttons on the my books page to be easier to get to the book, while still providing options for other actions such as reading, viewing details about the book, or returning.

**Comment by danafein** [comment]
I can work on this!

**Comment by cdrini** [comment]
@danafein Could you post the latest designs on here? Once those are posted here we can close the issue and create a new one for implementation. Thank you @danafein !

**Comment by cdrini** [comment]
Awesome, thank you @danafein !

**Comment by cdrini** [comment]
Here's the implementation issue: https://github.com/internetarchive/openlibrary/issues/7443
