### ISSUE TITLE
Add system for database migrations to Open Library

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#738]
e.g. #719, it would be nice if we had some sane way of managing database migrations. @tfmorris mentioned [liquidbase](http://www.liquibase.org), we could also potentially use python `alembic`.

**Comment by tfmorris** [comment]
Obligatory HN discussion: https://news.ycombinator.com/item?id=10034546

Alembic looks like it'd do the job too.

**Comment by guyjeangilles** [comment]
@mekarpeles Was this ever made? If not, I'm defaulting to asking you to be assignee. Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by mekarpeles** [comment]
I think as @tfmorris mentions, alembic is a good tool for the job. I am not sure a clear scope for implementing db migrations given our current setup and given how infrequently we've been touching the db, I am going to close this issue in favor of more user-facing central issues.
