### ISSUE TITLE
Add carousel card for yearly reading cards to onboarding carousel

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7382]
Add new onboarding card carousel about reading goals
    - In an ideal universe, the card would have an action for "Set 2023 goal"
    - Maybe also have a little "New" badge

**Comment by Blueclaus13** [comment]
hello! could I collaborate on this issue?

**Comment by ankurkumarrr** [comment]
Hi, Can I work on this issue?

**Comment by mekarpeles** [comment]
We can use this as the placeholder image
https://thenounproject.com/icon/calendar-1012007/

**Comment by ankurkumarrr** [comment]
I added the carousel with it redirecting to mybooks. I'm finding it a little difficult to make an action to yearly reading goals.

**Comment by gobbledy-gook** [comment]
Hello
I have been able to make some progress in adding some action to the progress bar depending on the "Already-Read" Books section. Below is a sample screenshot. So I basically just took the count from "Already-Read" Carousel title and used it in the "reading_goal_progress.html" file. I would be glad to make some contributions in this issue.

![Screenshot 2023-03-07 at 4 05 21 PM](https://user-images.githubusercontent.com/96362727/223397793-7c47df6e-5251-407a-b5af-27b841504612.png)!
