### ISSUE TITLE
Explain "logged"

### ISSUE THREAD

**Issue by milotype** [internetarchive/openlibrary#7387]
### Question
Please explain the meaning of the word "logged"

### Additional context
Please explain the meaning of the word "logged" in the following strings:

```
#: stats/readinglog.html:11
msgid "# Books Logged"
msgstr ""
```

```
#: stats/readinglog.html:12
msgid "The total number of books logged using the Reading Log feature"
msgstr ""
```

```
#: trending.html:26
#, python-format
msgid "Logged %(count)i times %(time_unit)s"
msgstr ""
```

```
#: stats/readinglog.html:29
msgid ""
"The total number of unique users who have logged at least one book using "
"the Reading Log feature"
msgstr ""
```

```
#: stats/readinglog.html:83
msgid "Most Logged Books"
msgstr ""
```

**Comment by tfmorris** [comment]
A "Reading Log" is like a ship's log where observations are recorded on a regular basis, but instead it records the books a reader has read. "Logging" is the act of recording a book as having been read in the Reading Log. Perhaps in other languages/cultures reading diary or some other terminology is used.

**Comment by mekarpeles** [comment]
Possible interpretations for translation:
* Added to a shelf
* Mentions
* Tracked
