### ISSUE TITLE
Follow Patrons & activity feeds

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#739]
Related to: #857, and #1964

See: #8607

## Ideas
And possibly receive email updates when users create lists or mark books on their Reading Logs.

**Comment by mekarpeles** [comment]
Will develop on `739/feature/subscribe-to-users`

**Comment by mekarpeles** [comment]
cc: reidun76 -- conversation will be continued here (#839 closed as duplicate)

**Comment by guyjeangilles** [comment]
@mekarpeles this issue requires sub-tasks. Please add them.

**Comment by mekarpeles** [comment]
#3449 duplicates this issue; closing #3449.

**Comment by tfmorris** [comment]
If implemented, this should include the ability to block people from following as well.

**Comment by LongJohn-Silver** [comment]
Does Patrons mean any user or just people who donate in some way?
Is there any idea on when this will be live?

**Comment by LeadSongDog** [comment]
All library users are "patrons". Still, I would hate to see the pursuit of antisocial media detract from actually building a better library. Let’s just focus on that.

**Comment by LongJohn-Silver** [comment]
> All library users are "patrons". Still, I would hate to see the pursuit of antisocial media detract from actually building a better library. Let’s just focus on that.

I am not a fan of social media, I do not use any of them, but I think that referring to them as antisocial is a bit of an exaggeration and your personal opinion without any facts. I still think that adding some more features that support social interaction would help to build a better library, I know some people who would switch from GoodReads into OL for these features and I'm sure they would contribute as librarians at least, or as regular users who upload books every now and then.

**Comment by LeadSongDog** [comment]
I can’t claim to have invented the term, but I should make a point of ensuring OL has some of the books on the subject. As far as facts go, just look up Cambridge Analytica to see the harm they do.

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/739#issuecomment-626923019 you can mark your reading log as private -- that's the level of granularity we currently have.

**Comment by mekarpeles** [comment]
Weekly digest of activity over email could be a fun option :) as could weekly notifications of new follows.
