### ISSUE TITLE
How to translate "check-in"

### ISSUE THREAD

**Issue by milotype** [internetarchive/openlibrary#7391]
### Question
How to translate **check-in**? What is the context?

Strings:

- Add an optional check-in date.  Check-in dates are used to track yearly reading goals.
- Check-In
- Note: Submit "0" to delete your goal.  Your check-ins will be preserved.

**Comment by mekarpeles** [comment]
The context is a check-in is a progress update, so perhasp: "read date" or a "read event" or a "read update"
