### ISSUE TITLE
Fix ol-home0 space, clean up unrotated logs

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7395]
> This is surfacing another bug which is that log rotation didn't occur in or since November -- ~likely related to #7369 & power outage~

![image](https://user-images.githubusercontent.com/978325/211584362-c3e7db64-5577-4d21-84bd-dafbf8e3712c.png)

_Originally posted by @mekarpeles in https://github.com/internetarchive/openlibrary/issues/7393#issuecomment-1377400289_

**Comment by cdrini** [comment]
I'm solving this by manually log rotating for now:

```sh
ssh -A ol-home0
docker exec -it openlibrary_infobase_1 bash -c '
    cd /1/var/lib/openlibrary/infobase/log/2022
    tar czf 12.tar.gz 12  # take forever
    rm -rf 12
'
```

**Comment by cdrini** [comment]
52g free now
