### ISSUE TITLE
Account option to make your Reading Log public

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#740]
Currently, `Reading Logs` are implemented privately via https://openlibrary.org/account/my-books/<shelf>

**Proposal**
- This proposal will introduce a new public endpoint for users, e.g. https://dev.openlibrary.org/people/mekBot/my-books/<shelf>, which they can use to share books they've tracking. This endpoint will show a message if sharing is disabled.
- A checkbox option will be added to https://dev.openlibrary.org/people/<user>?m=edit of `readinglog`: true/false which modifies the user's `account` object
- Account creation will, in the future, set this option/flag to be public by default, but allow disabling.

**branch:** `/feature/public-reading-log-option`

**Comment by mekarpeles** [comment]
Steps remaining
- [ ] Add messaging to /people/{username}/books/reading-log
- [ ] Add link to user's /account/books/reading-log to enable public reading log

**Comment by LeadSongDog** [comment]
Each time a user's loans, logs, or lists are updated, they should be reminded if their privacy setting makes them public-visible.

**Comment by mekarpeles** [comment]
@LeadSongDog reading log is not public by default. Our *lists* for the past 10 years have been public-by-default and no change is anticipated to this. We do not automatically add things to people's reading log (e.g. when they borrow a book, we don't automatically add it for them). As a corollary:

1) We don't need to take an action when a user loans a book because this is not public
2) When lists are updated, this is always public, so no message is shown (and we plan to keep it public, our themed lists don't even have a private feature and we don't have plans to invest engineering effort to change this)
3) We could add reminders / or an "eye" icon (and if a volunteer adds a pull request for this feature, we'll support it) to the "log" button if the user is set to public (so they know). Right now, given Reading Log is explicitly private by default, I feel we're addressing the most critical case.
