### ISSUE TITLE
Yearly Reading Overview Page for given Year

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7414]
### Describe the problem that you'd like solved

* Creating a Yearly Reads page that shows what book a patron has read based on their check-ins for that year (roll-up).
    * Lives at `/account/books/already-read/{year}`
    *Should only work for others if reading log is set to public
    * If possible, use the @constantinazouni + @Vassilis-Boubis List social preview link
    * Show books based on check-ins in specified {year} 
    * If it’s my page, then show me a carousel of up to 5 books marked as “Already Read” without check-in dates
        * Title: “Books Missing Read Dates (12)” → Already Read
            * Not a requirement to filter out books already with check-ins
        * Show msg: “Some books you’ve read don’t have completion dates. Do you want to add them?"

**Comment by jimchamp** [comment]
Duplicate of  #7370.
