### ISSUE TITLE
Followup to #724: Additional Reading Log Stats

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#742]
- leader board for "want to read" and "read" should have lists for last trailing month (in addition to the all time)
- add breakdown of books *per* shelf (i.e. "want to read", "currently reading", "already read") -- all time + last trailing month

**Comment by cptchloroplast** [comment]
Hi, I'm interested on working on this, but I see it's been removed from the To Do list.  Is it still a feature to be added and if so, do you have anymore details about it?  Thanks

**Comment by mekarpeles** [comment]
Hi @cptchloroplast! Sorry for responding so slowly!

There's a page https://openlibrary.org/stats/readinglog which is rendered by `readinglog_stats.GET` in `openlibrary/views/loanstats.py` .

The interface shows:
- # books logged (want to read, already read, currently reading): month, all-time
- # users who have logged: month, all-time
- # star ratings: month, all-time
- # users who have star rated: all time
- A list of books most marked as "want to read": all-time
- A list of books most marked as "already read": all-time

What we don't have is:
- A list of books most marked as "want to read": month
- A list of books most marked as "already read": month 

The task is to update loanstatus.py to add `most_read_month` and `most_wanted_mont`, to add these to the values returns in the `leaderboard`, and then to update the `templates/stats/readinglog.html` page accordingly.

Still up for the challenge?
