### ISSUE TITLE
Is the data backing search API available via dumps?

### ISSUE THREAD

**Issue by dr-manhattan** [internetarchive/openlibrary#7424]
### Question

Is the data backing search API available via dumps?

### Additional context

It seems you can find works using ISBNs not present in the archive editions json dumps AFAIK, e.g. search for 145211868X. Is there another way to access this data, maybe a database dump? Also would be good to add these ISBNs to editions

**Comment by tfmorris** [comment]
That ISBN is present on this edition: https://openlibrary.org/books/OL28517747M
but in its ISBN-13 form 9781452118680, not the ISBN-10 form you presented.

You can do the same normalization in your  edition database dump search. To convert, strip off the trailing check digit, add 978 on the front, and recompute the check digit.

**Comment by dr-manhattan** [comment]
thanks, this is very helpful

**Comment by mekarpeles** [comment]
When we generate our data dumps, it may be of value to generating both ISBN10 + ISBN13 where possible. For this issue, I believe @tfmorris's response is enough to resolve the question asked. Thank you!
