### ISSUE TITLE
Missing editions in dump file

### ISSUE THREAD

**Issue by dr-manhattan** [internetarchive/openlibrary#7426]
### Evidence / Screenshot (if possible)

with gzip.open(r"ol_dump_editions_2022-11-30.txt.gz", 'rt') as csvinputfile:
    csvreader = csv.reader(csvinputfile, delimiter='\t')
    for row in csvreader:
        if 'OL44970932M' in row[1]:
            print("found")
            break

### Relevant url?

https://openlibrary.org/books/OL44970932M/

### Steps to Reproduce

script above, never finds the edition in question

* Actual:
No found message printed
* Expected:
Message printed

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
Since it was created 27 Dec 2022, I wouldn't expect to see it in a 30 Nov 2022 dump.

https://openlibrary.org/books/OL44970932M/Rossovermiglio?m=history

**Comment by mekarpeles** [comment]
I agree with @tfmorris -- 

Please try with the https://archive.org/download/ol_dump_2023-01-10/ol_dump_editions_2023-01-10.txt.gz dump and if it's still missing, please re-open the issue.

Thank you!
