### ISSUE TITLE
Cursor inconsistencies on book about page

### ISSUE THREAD

**Issue by ma8642** [internetarchive/openlibrary#7428]
When user mouses over certain links and buttons, the cursor is not in pointer mode.

### Evidence / Screenshot (if possible)
https://www.loom.com/share/d7936ac8557140c08e62949e2e35835f

### Steps to Reproduce

1. Lookup a book
2. On the page for that book, mouse over "Read More" underneath the book description.
3. Click "Read More" then "Read Less."
4. Mouse over the "Manage Covers" link (or "Add Cover Image" if there is none)
5. Click that and mouse over the various buttons within the modal

* Actual: sometimes the cursor was in pointer mode and other times it was not, even for buttons right next to each other.
* Expected: the cursor should always be in pointer mode for buttons.

### Details

- **Logged in (Y/N)?**: Y
- **Browser type/version?**: Firefox and Chrome
- **Operating system?**: Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Setting cursor to `pointer` in the necessary spots in the CSS code. This is in line with implementations for other buttons on the page. I am making a PR for this.

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
Thank you! All for pushing in the direction of greater consistency

**Comment by mekarpeles** [comment]
@ma8642 are you interested in taking this one?

**Comment by ma8642** [comment]
@mekarpeles Yes!

**Comment by JaydenTeoh** [comment]
@ma8642 @mekarpeles Hi, I am looking to contribute to the WARI project for GSoC'2023. I attempted this issue and have made changes to the cursor types for the relevant links/buttons in hopes of getting familiar with the codebase. Do let me know if there is anything I missed out on

**Comment by mekarpeles** [comment]
@ma8642 I apologize! I didn't reply to you fast enough and notice that @JaydenTeoh got to this issue already.

Can we help you find a different issue to work on?
https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22+label%3A%22Needs%3A+Help%22

Also, I appreciate it can be frustrating finding a good issue! Feel free to email me at mek@archive.org and I can make sure you're invited to slack (if not already) + help you find a project you're proud of. Thank you!!!
