### ISSUE TITLE
UX: Some patrons have difficulty removing books from reading log

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7433]
### Question

How can we make removing reading log items clearer?

### Additional context

Feedback received:
_"Boy that is the most un-intuitive way to implement removing a book. It makes no sense - I would think clicking on a button marked “Already Read” would have the same action as clicking on the arrow. That *really* needs to be handled a LOT better."_
_"It’s not obvious that clicking the Want To Read button does something different from clicking the dropdown. It would be more intuitive if there was a remove option in the dropdown menu as well."_

### Issue resolution criteria

This issue can be closed once there is a plan for improving the reading log removal functionality.

### Stakeholders

@mekarpeles

**Comment by seabelis** [comment]
"When I select books on my to read list, there are times when I decide I don't care for the book to read it. The only way to get it off of my list is to mark it already read. I haven't read it and would like to simply remove it. There used to be an option to remove a book from the to read list but that option doesn't exists anymore. Is it possible to put that option to remove a book back on again? I don't have goals to read a certain amount of books. I read for the enjoyment of reading, especially the older books which are so much better than the books written now a-days. Thank you so much for making that possible!
Thank you for your patience!"

**Comment by seabelis** [comment]
_"How can I delete books from my want-to-read list?"_

**Comment by seabelis** [comment]
_"how do i clear the "ALREADY READ" list"_

**Comment by seabelis** [comment]
"There needs to be a "delete this item" on the want to read and already reading lists. We try to read something and do not like it and have to either mark it already read or want to read. NO way to delete it. Please add that feature! Thank you."

**Comment by scottbarnes** [comment]
I know this may need some design help, but I'd like to work on this one. I will submit a PR tomorrow and maybe it can kick off a discussion of how to actually do it properly. :)

**Comment by mekarpeles** [comment]
This has also been discussed in the context of "Lists" in the dropdown.
https://github.com/internetarchive/openlibrary/issues/6992

Some options we may want to consider/discuss:

1. If a book is on Reading Log, (e.g. "Want to Read") then repeat this label within the drop down with a checked box next to it
2. Have some sort of text or graphic in the button itself to show it can be clicked

**Comment by DebbieSan** [comment]
Hi @mekarpeles , I talked to @scottbarnes about this issue and would love the opportunity to address both this issue and #6992 with a couple of Figma options. :)
