### ISSUE TITLE
Implement new read/return buttons on my books page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7443]
Implement @danafein 's mockups:

<img src="https://user-images.githubusercontent.com/30005120/214346286-e767a742-ca6c-4b1b-b629-9262bb1596df.png">

In scope:

- Add return button of style in mockups
- Change colour of expiry date
- Make expiry date relative using the `datestr(date)` function.

### Stakeholders
@danafein @jimchamp @mekarpeles

**Comment by protocolog** [comment]
I am an student of BITS Pilani india.If this is still open I would love to be assigned.
@cdrini

**Comment by JaydenTeoh** [comment]
@cdrini @mekarpeles Hi, has this issue been resolved? I am interested to contribute to the WARI project for GSoC2023 and I would like to contribute my solving some PRs and familiarising with the codebase first. Could I take this issue if it is not fixed yet?

**Comment by JaydenTeoh** [comment]
@cdrini @mekarpeles I have setup a dev environment but I noticed that the borrow function is not supported on dev environment. May I ask how can I mock a borrowed book so that I can implement @danafein designs?

**Comment by mekarpeles** [comment]
I think the button is implemented on the Books Page already (within the macro/LoanStatus.html) If we open a PR, we can put it on testing.openlibrary.org where there lending is available and we can test.

**Comment by JaydenTeoh** [comment]
@mekarpeles The button is implemented but clicking it and sending the API request results in internal server error. May I ask if there is any way I can visualise and style the buttons that I'm implementing if I am unable to borrow books into the loan page?

**Comment by JaydenTeoh** [comment]
@cdrini @mekarpeles made a PR for this implementation. I need a little help getting the `datestr` fn to work. I have the expiry time in UTC format but I am unable to convert it to relative time using `datestr`. Will also need to test this implementation on testing.openlibrary.org to see if my buttons are working properly
