### ISSUE TITLE
Change /partials endpoint to /partials.json to get gzip support

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7447]
Currently the /partials endpoint is not gzipped. This is a performance issue. Our nginx automatically gzips .json URLs, so since this is also a JSON endpoint, let's change it to `/partials.json` and update all references in the code. 

Revealed by Google Lighthouse/pagespeed insights:

![image](https://user-images.githubusercontent.com/6251786/214691547-20e14666-a0ca-43ca-9a7b-5527ae470cda.png)
https://pagespeed.web.dev/report?url=https%3A%2F%2Fopenlibrary.org%2Fbooks%2FOL23153983M%2FAlgebra

Steps:
- Find all references to /partials and change it to /partials.json

### Stakeholders
@cclauss @jimchamp

**Comment by Mayuresh0072** [comment]
@cdrini Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks

**Comment by cclauss** [comment]
@Mayuresh0072 please go ahead and create a pull request.  When multiple contributors create pull requests to fix the same issue then it is almost ways a learning and often the merging of ideas is more powerful than a single pull request,

**Comment by Mayuresh0072** [comment]
You are absolutely right. Actually, Solving issues is part of college assignment. So, It would be very helpful for me if you assign me, so that i can show my progress. Thanks

**Comment by Blueclaus13** [comment]
Could I participate in this issue? this is my first time in open source.

**Comment by mekarpeles** [comment]
Apologies @Blueclaus13 -- it seems @bkochendorfer has submitted a PR for this one, however we would love to work with you on one of these projects if you're interested in teaming up on an issue!

https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22+label%3A%22Needs%3A+Help%22

**Comment by jimchamp** [comment]
It looks like the `/partials` and `/lists/partials` endpoints are already `.json`.

`/merges/partials` and `/reading-goal/partials` endpoints are not returning `json`, and should be updated.  Any JS functions that hit these endpoints also need to be updated.

**Comment by jimchamp** [comment]
The `/merges/partials` endpoint was removed some time ago.  Only the `/reading-goal/partials` endpoint remains.  This is used to return a rendered yearly reading goal progress bar whenever somebody sets a reading goal from their My Books page.
