### ISSUE TITLE
Repair ~318 records with isbn stored in the wrong field

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7448]
http://openlibrary.org/query.json?type=/type/edition&isbn~=*&limit=500

Repairs:
- Move anything in the incorrect `.isbn` array to `.isbn_10` or `.isbn_13` arrays depending on length
- Move anything in the incorrect `.publisher` field to the `.publishers` array

This was the result of a bug in the import api code. It would save to these fields if no MARC was present.

### Stakeholders
@scottbarnes @hornc

**Comment by scottbarnes** [comment]
I'm like to work on this.

**Comment by scottbarnes** [comment]
This is done.

**Comment by cdrini** [comment]
Thanks @scottbarnes !
