### ISSUE TITLE
ReCaptcha: Only load where needed

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7453]
We may be loading ReCaptcha in more places across the site than we need/want which is also not great for reader privacy. We should limit this code inclusion to the areas they're used.

### Stakeholders

@cdrini

**Comment by jollypolly123** [comment]
What needs to be done for this? It sounds like the process is 
1. compiling the places it's loaded 
2. evaluating which are necessarily 
3. removing those that are unnecessary
I can start with 1. if this works

**Comment by jimchamp** [comment]
Closed by #8569
