### ISSUE TITLE
Update solrupdater/solrbuilder to specify new fields for IA search

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7467]
IA search now has ratelimiting, and we'll need to specify new parameters / fields when making requests to it. Make sure that this is only done for non-user triggered requests. Those _should_ be rate limited presumably.

**Comment by tfmorris** [comment]
Wait, does this imply that you can't rebuild the OpenLibrary search index without special internal access to IA? That would be pretty bad for external developers.
