### ISSUE TITLE
books on lists should not say `ebook available` if daisy only

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#749]

**Comment by hornc** [comment]
Scale of Print Disabled only books on OL:
IA has 6160 Print Disabled only items

`ia search '!collection:inlibrary AND collection:printdisabled AND scanningcenter:*' --itemlist | sort > printdisabled_ocaids.txt`

OL has 3611 of these (is missing 2549)

Of the 3611 Print Disabled editions on OL: 
 162 have duplicate records
 7 are orphaned editions (4 with no author populated)

We still need a good way to live query this, but I have all the lists of OCAIDs available if we want to set flags somewhere.

**Comment by mekarpeles** [comment]
closing this issue and creating a separate issue specifically for daisy coverage
