### ISSUE TITLE
`search.json` API results differ from the usual search

### ISSUE THREAD

**Issue by 0x29a** [internetarchive/openlibrary#7491]
Consider the search results on this page: https://openlibrary.org/search?q=Rang+%26+Dale%27s+Pharmacology&mode=everything

And documents that this URL returns: https://openlibrary.org/search.json?q=Rang%20&%20Dale%27s%20Pharmacology=&limit=10

Despite requesting the same book (`Rang & Dale's Pharmacology`), I get completely different results. Moreover, API doesn't return even a single correct match.

Is there anything I can do to make the search API work better in this particular case?

**Comment by tfmorris** [comment]
Why are you urlencoding one and not the other? You're second query is equivalent to

https://openlibrary.org/search.json?q=Rang%20

You need to correctly encode the ampersand (&) to get the same results as the other query.

**Comment by 0x29a** [comment]
Ah, I didn't notice the difference. Thank you very much, @tfmorris! I'm closing the issue.
