### ISSUE TITLE
Proposal: run watch commands when starting Gitpod

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#7497]
Goal: make it even easier for someone to update css/js in Gitpod

I would like to automatically run the watch commands in gitpod:
- `docker-compose run --rm home npm run-script watch`
- `docker-compose run --rm home npm run-script watch-css`

### Describe the problem that you'd like solved

The few times I pop over to Open Library to try to make a small css change or see if I can fix something I always have to dig around and see what command I need to run to get the CSS to update.
I think it would be nice for the dev environment in Gitpod to automatically run the watch commands so any changes made are picked up right away.

### Proposal & Constraints

These can be done by having separate tasks that start after we have docker running.

### Additional context

Happy to open a PR for this.

I consider this a blocker for https://github.com/internetarchive/openlibrary/issues/6939
Or at least a nice to have

### Stakeholders

@cclauss @mekarpeles

**Comment by cdrini** [comment]
sgtm! But use concurrently so they run in the same space :) See also https://github.com/internetarchive/openlibrary/pull/6442/files ; it might be a useful addition, but haven't had time to test!
