### ISSUE TITLE
Add author to page title instead of (or in addition to) date

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7499]
The author is more when displaying the title of a book page, the author is more important than the edition date. This should be displayed instead of the date, or with the date following it.

### Describe the problem that you'd like solved

Change the page titles to include the author after the edition title, for example, **Half American by Matthew Delmont | Open Library**
### Proposal & Constraints

Current display when posting to social media, for example. The edition date is not so important, but the author information is. This may also improve SEO.
<img width="537" alt="Screenshot 2023-02-03 at 18 44 32" src="https://user-images.githubusercontent.com/17739465/216672049-a03eb0b9-0969-4603-bcf4-2d342e3733c6.png">

**Comment by IrennaLumbuun** [comment]
Hi, I'm new to this project but would like to contribute to this task. QQ: How do we want to deal with books with multiple authors? For example: 
```
Upon a midnight clear
Authors: Mariah Stewart, Jude Deveraux, Margaret Allison, Stef Ann Holm, Linda Howard
```
Do we want to include all 5 authors? Or do we want to limit this information to N number of characters?

**Comment by seabelis** [comment]
Thank you, @IrennaLumbuun . The primary (first) author is enough. Sometimes multiple names are combined into one author, but that's an import error and a different issue, so don't let that throw you off.

**Comment by Blueclaus13** [comment]
Hello guys! Could I contribute to this issue?

**Comment by IrennaLumbuun** [comment]
Thanks, @seabelis! Can you (or @mekarpeles) help add me as a collaborator to this project? I'm getting `ERROR: Permission to internetarchive/openlibrary.git denied to IrennaLumbuun.` when trying to push the branch containing my change.
