### ISSUE TITLE
"The Open Library Team" page has broken links

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#7500]
### Evidence / Screenshot (if possible)
<img width="700" alt="image" src="https://user-images.githubusercontent.com/921217/216687052-67db61e1-a038-4c17-a668-29d00eae2fdc.png">

### Relevant url?
https://openlibrary.org/about/people

* Actual: Looks like `[[/user/mekBot|Mek]]`
* Expected: To have a link to profiles

Not sure what might have caused this but hope it's not a bug for some wider reason.

### Stakeholders

@mek since you have updated the page most frequently

**Comment by tfmorris** [comment]
That page is very out of date.  It's been years since I've been involved. Please remove my name from the active team list.

There's also something weird with the history for that page. The bottom of the page lists 62 revisions, but when you click through it only shows the first four edits from 2008/2009.

**Comment by cdrini** [comment]
Can you edit this page @RayBB ? If not we'll give you permissions :)

**Comment by RayBB** [comment]
@cdrini I can edit it but how should the links be fixed? Still pointing to OL profiles? and remove tfmorris

**Comment by cdrini** [comment]
I think the formatting has changed? Try putting the bold `*` character inside or outside the brackets? And switch to markdown style URLs `[VISIBLE Text](url)`.

**Comment by RayBB** [comment]
I think this is done @cdrini feel free to double check and see if there's anything else to be updated on the page.

**Comment by jimchamp** [comment]
Thanks @RayBB!
@tfmorris, we've removed your info from the "Active Team" section.  Would you like to be listed in the "Active Contributors" section, or not at all on this page?

**Comment by tfmorris** [comment]
I moved my entry to the emeritus section. I could tell exactly what the ordering was, but it looked like closest to most recent first, so I added myself to the top. Feel free to move it to wherever is appropriate.
