### ISSUE TITLE
Remove monthly carousels from home page

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7505]
The monthly carousels have gone stale and should be removed, or at least commented out, from the home page. 

### Evidence / Screenshot (if possible)
<img width="842" alt="Screenshot 2023-02-06 at 16 53 41" src="https://user-images.githubusercontent.com/17739465/217019398-d7008501-a03e-468f-9351-827d84711903.png">

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Maybe this can be resumed when there is a better selection method. The previous queries were not ideal and the carousels are populated with some irrelevant results. Many have since been updated on their respective collection pages, but the old selections still populate the home page.

### Stakeholders

@cdrini @Sabreen-Parveen @mekarpeles @jimchamp

**Comment by AmanSal1** [comment]
i am not able to understand your issue properly can you plz elaborate a little bit ?

**Comment by AmanSal1** [comment]
![1](https://user-images.githubusercontent.com/121633121/217521341-c8e46228-8f10-47e1-85b3-32fbd6627142.PNG)
![2](https://user-images.githubusercontent.com/121633121/217521380-1edb0bb6-ffe8-4dfc-9b2b-287b79905c08.PNG)




I guess the issue is being created due to the ambiguity of the book thus we would need a single display for each book

** i have attached the photos also please look into it **

**Comment by seabelis** [comment]
Thank you, @AmanSal1 .
I believe it's just lines 27 and 28 from https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/index.html.

**Comment by AmanSal1** [comment]
@seabelis so is the issue resolved ?

**Comment by seabelis** [comment]
Not yet. Those lines need to be removed before it's resolved.

**Comment by AmanSal1** [comment]
is this the right fix ?

**Comment by ayushdhiman-py** [comment]
Hi , i want to work on this issue please assign me this issue.

**Comment by cdrini** [comment]
Howdy folks I'm going to take this one myself because there are some intricacies of deleting some old code :) Thanks folks!

**Comment by RayBB** [comment]
@cdrini maybe you should remove the `good first issue` label if you're going to do this :)

**Comment by JaydenTeoh** [comment]
Hey @cdrini, do let me know if you need any help with this issue!
