### ISSUE TITLE
Fix past editions created with publish_date="????"

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7519]
A number of promise items were imported with a `publish_date` of `????`. There is a PR (#7518) that in theory stops this going forward. But there is still the issue of the many that were created.

### Relevant url?

I wasn't sure how to remove the 1000 item limit, but see https://openlibrary.org/query.json?type=/type/edition&publish_date~=%3F%3F%3F%3F&limit=5000 for 1000 items that have `????` as a `publish_date`. E.g. [OL46006260M](https://openlibrary.org/books/OL46006260M.json)

### Proposal & Constraints

Once the issue is fixed going forward, I'm not sure of the best way to fix what's already been done. I had hoped that these items would have been scanned and we'd have more metadata on them that we could parse, but I don't see it.

Perhaps the best solution is simply to remove `publish_date` values that are `????`, and then in the future if the editions are reimported, and if `publish_date` becomes a field that is updated on reimport (see the poorly named #7490), `publish_date` can be populated that way.

In any event, I would like to work on this. With the go ahead, I will write a small bot to simply delete all `publish_date` entries of `????`.

### Stakeholders

@cdrini

**Comment by scottbarnes** [comment]
Per a discussion with @cdrini, these should *not* be fixed now, as doing so would make any promise items added this way v2, and would hamper using MARC data to overwrite v1 promise items with extreme prejudice.

This should be fixed by reimporting after #7490 (or a similar PR) is merged.

**Comment by cdrini** [comment]
@hornc Can we close these now? You fixed all of these correct?

**Comment by hornc** [comment]
@cdrini I fixed a lot of them, but there may be stragglers. I was going to wait for the next data dump to confirm / clear up what is left.

**Comment by mekarpeles** [comment]
I believe @hornc fixed this?
