### ISSUE TITLE
Show work title on author page

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#7525]
Books on author page don't have work title shown near them. It only shows edition title

Search results page
![зображення](https://user-images.githubusercontent.com/58372007/218317450-264bee41-1da4-4824-b477-c9ee9694ef15.png)

Author page
![зображення](https://user-images.githubusercontent.com/58372007/218317519-9664294e-6cf8-46b9-9f09-656749332d5e.png)

**Comment by TheClerici** [comment]
Is this still available? i would love to work on this :D

**Comment by scottbarnes** [comment]
@TheClerici, I am also a volunteer so I can't speak authoritatively and I can't assign this issue, nor can I guarantee a PR for this issue would inevitably be merged, but with those caveats aside, nobody has done this yet. :)

If you want to start and aren't sure where to begin:
- once you start on it, mention here that you've started so others know know you are working on it;
- try to give an approximate time for when you hope to complete the issue; and
- taking a look at [line 146](https://github.com/internetarchive/openlibrary/blob/98432f1e5db85e0e906f7ef4e0231cce82910f25/openlibrary/templates/type/author/view.html#L146) of `openlibrary/templates/type/author/view`, along with [openlibrary/macros/SearchResultsWork](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/SearchResultsWork.html) generally, would be a good place to start.

If you have any questions, please don't hesitate to ask.

**Comment by TheClerici** [comment]
Sure! I plan to start working on it today and hopefully I can get it done by Thursday, any question I will ask here, thanks!!

**Comment by scottbarnes** [comment]
@TheClerici, I should note this is labeled as `Needs: Triage`, which I had missed. It may be best to wait for @cdrini to opine on the issue, as it's not certain this is a change that is desired. Sorry for missing that. :)

**Comment by TheClerici** [comment]
Okie dokie 👌

**Comment by cdrini** [comment]
Sorry for the delay folks, yep! Please feel free to work on this one @TheClerici !

**Comment by JohannSuarez** [comment]
Hello everyone! New guy here, @cdrini has invited me to tackle this one so I'm giving it a go
