### ISSUE TITLE
Sort books on My Books carousels (by most recent)

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#7526]
My books page carousels always show books that are the oldest added to Reading Log. I think it would be better to randomise books shown here. For example, in Want to Read carousel patron might see a book that he added a long time ago, but forgot about it, and might decide to read it. Same goes for Already Read carousel

![зображення](https://user-images.githubusercontent.com/58372007/218318034-6de93728-c0c9-4d02-87fe-18b4f073ac53.png)

**Comment by mekarpeles** [comment]
During a previous design call, the community tentatively decided to sort by most recently added -- I have a PR I'll be submitting soon.

**Comment by sid2002CN** [comment]
@mekarpeles Hi, I'm Sid, one of the students who listened to ur sharing. Your sharing today was truly valuable, and I am grateful for it. I'd love to get involved by working on this issue. Can u kindly points out which part of the code this is related to so I can get started?

**Comment by JaydenTeoh** [comment]
@mekarpeles I have made a PR for this issue. Please check on it and let me know if I missed out on anything https://github.com/internetarchive/openlibrary/pull/7572
