### ISSUE TITLE
Trending homepage carousels not randomizing sufficiently

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7533]
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
@jimchamp and @mekarpeles investigated and determined that there's no really convenient way out of this unless we add some randomization, but which would add its own complications. Good enough as is!
