### ISSUE TITLE
Hyphens are dropped from OCAIDs

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7542]
### Steps to Reproduce

1. Go to ...add edition form. For example, https://openlibrary.org/books/add?work=/works/OL20064953W
2. Do ...try to add an Internet Archive identifier with a hyphen. For example, `bwb_KR-436-798`. 

* Actual: On saving, the hyphens are dropped, changing the identifier to `bwb_KR436798`
* Expected: Identifier should be saved as entered.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I suspect this is caused by hyphen removal rules from ISBNs. It would be better if IA identifiers did not have hyphens.

### Stakeholders

@mekarpeles @jimchamp Maybe @scottbarnes . @cdrini

**Comment by mekarpeles** [comment]
Only remove hyphens for isbn and not for other identifiers

**Comment by sbwhitt** [comment]
Hey all, I'm looking to contribute and I think I've found a fix for this issue. I can have a pull request up shortly.
