### ISSUE TITLE
Search within an author's works can't find special characters

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7555]
### Evidence / Screenshot (if possible)

![Screen Shot 2023-02-19 at 4 48 35 PM](https://user-images.githubusercontent.com/82178/219977281-85a51940-0d59-4f96-a1b7-0035c1f7af51.png)

![Screen Shot 2023-02-19 at 4 49 40 PM](https://user-images.githubusercontent.com/82178/219977287-3eff3b2c-0c34-4199-9a3d-33b7445e6c4e.png)

### Relevant url?
https://openlibrary.org/authors/OL1149539A/Harriet_Anne_de_Salis?q=%C2%A9

### Steps to Reproduce

1. Go to https://openlibrary.org/authors/OL1149539A
2. Search for the copyright symbol

* Actual: search results say "1 work" and list zero works
* Expected: all works with a copyright symbol in their title should be listed

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@cdrini

**Comment by JaydenTeoh** [comment]
@cdrini Can I attempt this issue?

**Comment by karlitto01** [comment]
Hi @cdrini. I would like to work on this issue if it is not assigned to anyone yet. Thanks.

**Comment by davidscotson** [comment]
I note that this seems like a general search issue, not just on the search within author interface:

https://openlibrary.org/search?q=%C2%A9

A general search for the symbol finds no works, though it does seem to match against authors, suggesting the way that authors are stored in search is preserving this kind of characters.
