### ISSUE TITLE
# symbol is ignored by search

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7568]
It is not possible to search for the # character, for example "C#". 
### Steps to Reproduce

1. Go to ...openlibrary.org
2. Do ...type "c#" or "c/#" or "c//#" in the search box

* Actual: results ignore the # symbol
* Expected: titles, for example, should be returned if they contain the # character.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by JaydenTeoh** [comment]
I believe this issue is due to the same bug faced in #7555
