### ISSUE TITLE
Fix `/admin/imports` performance issues

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7577]
The `/admin/imports` view provides a detailed summary of data that was imported via our batch import pipeline.  Unfortunately, this page is very slow to load, and sometimes times out before rendering.  This is likely due to a slow-running DB query.

This issue can be closed when the root cause of the slow-loading page is investigated and corrected.

### Relevant url?

https://openlibrary.org/admin/imports

### Steps to Reproduce

1. Go to https://openlibrary.org/admin/imports

* Actual: Page takes a very long time to load (if it loads at all)
* Expected: Page loads in a few seconds or less

### Details

- **Logged in (Y/N)?** Yes (as admin)
- **Browser type/version?**Any
- **Operating system?**Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Find slow-running `import_item` DB select statements, and tune them such that they don't take such a long time to run.  Maybe some type of pagination is needed?

**Comment by albajarazeth** [comment]
Hello! I would like to work on this issue.

**Comment by jimchamp** [comment]
I'm not looking for help for this particular issue.

If you'd like to contribute, please search for issues that are unassigned and have the [Needs: Help](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Help%22) label.
