### ISSUE TITLE
Various French search results wrongly display 1 result when there are zero

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7579]
Various French search results wrongly display 1 result when there are zero. See, e.g., https://openlibrary.org/authors/OL1149539A/Harriet_Anne_de_Salis?q=flop when viewed in French.

This is because `1 hit` (or `1 result`, etc.) in sometimes hardcoded into some of the `ungettext` calls within the templates for grammatically singular numbers. But in French, 0 is singular, so setting correctly setting `plural(n > 1)` in the relevant `.po` file means 0 is singular, and we return the hardcoded `1 hit` translation, even though there are 0 results.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/26524678/221652303-59805f92-1a1a-4a58-9d12-bd82e9f65b96.png)
![image](https://user-images.githubusercontent.com/26524678/221652384-f39a0e0f-072d-43c6-b0f1-3a1c55b61edb.png)

I will submit a PR to fix this and to both fix this in the templates and to update the translation files to avoid breaking current translations for every instance of 1 hit, 1 result, 1 work, etc.

### Relevant url?

https://openlibrary.org/search/subjects?q=flopbop&mode=everything (when viewed in French)
https://openlibrary.org/search/subjects.json?q=flopbop&mode=everything

@cdrini

**Comment by cdrini** [comment]
Anything matching this regex will need updating: https://github.com/search?q=repo%3Ainternetarchive%2Fopenlibrary+%2Fungettext%5C%28%5B%27%22%5D1%2F&type=code&p=1

We should also update the ungettext example in the docs here: https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#internationalization-i18n---for-programmers

**Comment by scottbarnes** [comment]
Will do! :+1:

**Comment by tfmorris** [comment]
This is a duplicate / superset of #6407.
