### ISSUE TITLE
Confirm sitemaps are being copied to www0

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7580]
Related to
* #7581 (closed)

[Sitemaps](https://en.wikipedia.org/wiki/Site_map) are currently served as static files from our www server. E.g.  https://openlibrary.org/static/sitemaps/sitemap_authors_0000.xml.gz

https://github.com/internetarchive/openlibrary/blob/7401096d2b2c3281e21ea9084d309ea3235f3b4b/docker/web_nginx.conf#L68-L86

Note how it is expected that `/sitemaps` exists on the www server.

**Comment by cdrini** [comment]
The way sitemaps currently work:

They are generated every month by ol_dump.sh:
https://github.com/internetarchive/openlibrary/blob/31bc7e2789152f51ffee4b34e0399ccdd622b211/scripts/oldump.sh#L203-L213

Done monthly on the first of each month.

But this is done on ol-home0. So then they need to be moved to ol-wwwX to serve the files.

This is done by a cron task that runs on our ol-www that rsyncs from ol-home


Steps:

1) Run the sitemap generating script in the cron file directly on new ol-home inside the crons container. This should work (but might not; see #7581 ).
https://github.com/internetarchive/openlibrary/blob/31bc7e2789152f51ffee4b34e0399ccdd622b211/scripts/oldump.sh#L200-L213
2) Test running the rsync command from the new www inside the nginx container https://github.com/internetarchive/olsystem/blob/35dab0b979fd574d6304a0c40451044b9988c76e/etc/cron.d/openlibrary.allnodes#L24 . This should work as well.

If this all works, add a new cron file to the nginx service in docker-compose.production.yml with just this step (see `CRONTAB_FILES` env param; this should support space separate list of files).

**Comment by cclauss** [comment]
Source: `ol-home0%: /1/var/tmp/sitemaps`
Destination: `ol-www0: /1/var/lib/openlibrary/sitemaps`
