### ISSUE TITLE
Twitter cards missing cover when sharing book link

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7587]
### Evidence / Screenshot (if possible)
![Screenshot_20230301-031406](https://user-images.githubusercontent.com/6251786/222082034-19904141-6406-4223-9987-861b5a629e92.png)

Should display cover of https://openlibrary.org/works/OL2872957W/Our_stolen_future

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
That work previews on Twitter with a cover for me, but a) it shows info for an edition, not the work, and b) it shows two different sets of edition info (1997 edition vs. unknown edition)

![Screen Shot 2023-03-06 at 3 20 02 PM](https://user-images.githubusercontent.com/82178/223234437-72bea083-5ab2-4aec-873c-727828f38e76.png)

**Comment by cdrini** [comment]
I think this is an issue on twitter's side; I have data saver enabled for my twitter and I think that might be the cause!
