### ISSUE TITLE
Bulk List API: Add Books in Bulk

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7589]
The List API should be updated to accept a list of books (and should ensure editions are not already on the list)

**Comment by JaydenTeoh** [comment]
@mekarpeles Can I work on this one?

**Comment by JaydenTeoh** [comment]
@jimchamp The API is already capable of adding multiple books into the lists in one post request (e.g. payload: {add: [{key: "/books/OL25083437M"}], [{key: "/books/OL24375501M"}])). However, there is currently no user interface and flow to organize books into list in bulk currently. Perhaps we could have a separate page just for users to search for books and select certain matches to be added into a list. Or, we could implement it directly in the search page, where readers can click on a button to add the search results into a list? As I am working on a proposal for this fesature right now as part of GSoC, could we can have a discussion regarding how we would like to implement this?

**Comment by cdrini** [comment]
That's great ! Love not having to implement anything :) We need to update the docs on our lists page. Would you be able to help update the docs at https://openlibrary.org/dev/docs/api/lists to add information about this endpoint? (Or any other you found :P)

**Comment by cdrini** [comment]
I'll give you permission to edit that page :+1:

**Comment by cdrini** [comment]
Ok you should have edit access now!

**Comment by JaydenTeoh** [comment]
@cdrini @mekarpeles I have updated the docs with the API endpoint to add books in bulk to lists. Do let me know once there is a mockup for the Add books in bulk UI and I will start working on it!

**Comment by cdrini** [comment]
Sweet! That's still iterating a bit, but closing this issue as complete :) 

Did some rejiggering, and also added a link to the lists API from the main API index. Thanks @JaydenTeoh !
