### ISSUE TITLE
Work OLID is not being displayed

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#759]
The work OLID only appears to the user after clicking on it, and even then only as part of the URL shown in the browser's location bar. This is unlike what is done with the specific edition OLID. The canonical form should show both, I think.

See:
https://openlibrary.org/books/OL12M and circa:
https://github.com/internetarchive/openlibrary/blob/f1f7e01bb118e10787bd135a064ca7e4220dbece/openlibrary/templates/books/edition-show.html#L58

**Comment by LeadSongDog** [comment]
Compare, for this single-edition work:
https://openlibrary.org/books/OL24980075M/Small_scale_constant-area_test_of_an_aerothermopressor
https://openlibrary.org/works/OL16083500W/Small_scale_constant-area_test_of_an_aerothermopressor
https://openlibrary.org/authors/OL7407241A/James_Cobb_Matheson

In each, there are links to the other, but the user must go hunting Easter eggs to find them.
On the edition page, the work link shows when hovering over "1 edition".
On the work page, the edition link shows when hovering over "1 edition".
On the author page, the work link shows when hovering over "Small scale constant-area test of an aerothermopressor" while the "1 edition" is unlinked.
Small wonder this confuses users, it needs a UX rethink.

**Comment by guyjeangilles** [comment]
This still appears to be an issue. @jdlrobson Front-end seems to be your realm. Are you willing to be assignee for this issue? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
I'm fine with only having the identifiers in the URL. I don't think they add a lot of value.

Having said that, I think we should:
* be consistent in identifier treatment between work and edition pages
* make the link to the work more obvious on the edition page

**Comment by jdlrobson** [comment]
I think the bigger problem here is that user's don't understand the difference between an edition and a book. Is there a higher level issue for that particular problem that I can fold this issue into?

Marking as low as I'd like to work out a roadmap for how this works first.

**Comment by RayBB** [comment]
I'm going to agree with tfmorris. I think for most people who the work ID would be relevant can get it from the URL. If someone is really asking and wants it added to the page they can propose where they'd like it added and we can figure it out then.
