### ISSUE TITLE
Merge UI performance issues

### ISSUE THREAD

**Issue by mheiman** [internetarchive/openlibrary#7608]
Merge UI makes a lot of queries, and if any of them time out or fail, the whole merge gets held up. In the last few days, we've been seeing a high rate of these connection failures. 

The failures are mostly happening during retrieval of reading log, list, or ratings data. 

### Relevant url?
It's not particular to any merge request, so you can set up any arbitrary merge to test. The more works included, the higher the likelihood of failure.

### Proposal & Constraints
Since the performance issues seem to involve these secondary data tables rather than the primary work/edition data, it's probably worth verifying that all of the involved tables are correctly indexed and optimized for the queries that the Merge UI is making.

If we can't find any issues at the database level, another approach would be to modify the Merge UI so that these failures don't block the merge process. It's nice to have the reading log, list, and ratings information, but we could give librarians a choice of whether to reload the page or just proceed without that data, since it's not required to perform the merge.

### Stakeholders
@cdrini @mheiman @seabelis

**Comment by seabelis** [comment]
For context, the list data was relevant when the merge tool was initially created. At that time, librarians would not merge records with associated lists as that would break the lists for the patrons. That issue has since been resolved. Removing the list data from the merge table is acceptable at this point.

**Comment by cdrini** [comment]
Closing ; I believe the perf issues on this page are now less prevalent, and the non-blocking requests were implemented in #7631 .
