### ISSUE TITLE
"What work is this an edition of" is finding editions, not just works

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#761]
The dropdown search at the new "What work is this an edition of" is finding edition records, not just works:

![edition or work](https://user-images.githubusercontent.com/11435431/35120762-2cb3e970-fc67-11e7-8ff7-f97d944750a8.png)

**Comment by hornc** [comment]
code for this is at https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit/edition.html#L171

we should exclude editions from this drop down.
