### ISSUE TITLE
Add option to create a list directly from the "My Books" page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7613]
Subtask of #7390

Current design: 

<img src="https://user-images.githubusercontent.com/92345662/211180819-bba49834-ee0d-465e-bcec-b280486949f5.png" width=300>

This design needs more feedback though!

### Stakeholders

@DebbieSan @JaydenTeoh

**Comment by carlsonrob** [comment]
@cdrini Could you provide feedback if this issue was solved here?
https://github.com/internetarchive/openlibrary/pull/7553

As part of CodeDay Labs, myself and two others worked on this ticket.
Thanks.

**Comment by DebbieSan** [comment]
Hi @carlsonrob. Thank you for all your hard work on those issues on #7390.

This subtask of #7390 should just need some minor design changes and with the changes it should be good to go. 

The intention of this design is that when one clicks on ' Create a list' the modal to create a list appears.  Add to list is not necessary. This is only to create a list itself not to add a book to a list.

Feel free to reply if you have any questions :).

See the approved design below.

![image](https://user-images.githubusercontent.com/92345662/224426168-21d22252-37cf-45e0-89c6-e7e7a8b15e66.png)


@cdrini

**Comment by carlsonrob** [comment]
@DebbieSan 
Currently, I am utilizing the ReadingLogDropper macro to create the list. However, the generated anchor text is "Create a new list”, not "Create a list". Is this ok?
https://user-images.githubusercontent.com/29802482/219884882-3e308b21-fe9c-4a72-a73e-f2cfc5ba4302.png

**Comment by DebbieSan** [comment]
Hi @carlsonrob, I will reply to you on your PR #7553.

**Comment by mekarpeles** [comment]
This should be addressed **after** #3070

**Comment by mekarpeles** [comment]
I believe this can be closed 👍 
<img width="287" alt="Screenshot 2023-09-16 at 1 06 18 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/1ddd1108-6089-47ea-81c8-ac8269f0688a">
