### ISSUE TITLE
Cleanup/convert barcodescanner to use Vue

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7615]
This is becoming interactive enough where having it be in Vue would be helpful.

Steps (two separate PRs):

- [ ] Update LazyBookCard so that after it fetches `/isbn/...`, it fetches `https://openlibrary.org/search.json?q=edition_key:OL38222427M&fields=key,author_name` in stead of making multiple requests for the author names.
- [ ] Create a new BarcodeScanner Vue component. Most of the helper classes should remain the same and just be moved over (eg `OCRScanner`). `LazyBookCard` should be made into a Vue component. `OLBarcodeScanner` should be made into a vue component. Life the html from `barcode-scanner.html`, and replace it with a Vue app rendering (eg `$:render_component('MergeUI', attrs=attrs)`)

### Stakeholders
@Eds-Dbug

**Comment by Eds-Dbug** [comment]
I would like to work on this issue!

**Comment by Eds-Dbug** [comment]
I guess ill have to learn Vue then.

**Comment by leanderoudakkertue** [comment]
Hi, I noticed there hasn't been any activity for a few months. I would like to give it a try, could you assign me?
