### ISSUE TITLE
Store assets permanently 

### ISSUE THREAD

**Issue by maxcli** [internetarchive/openlibrary#7628]
Problem:  
Permanent and verifiable storage of digital assets 

Proposal :  
 Use Arweave : 

- permanent (200 years at least) 
- de-centralized blockchain(blockweave) 
- 'pay once on upload' 

   

Solution/Implementation:  
Allow bulk or individual upload via Web interface, or Web API , using open-source packages like "arweave" ,  and "arweave-wallet-connector"  etc.

Additional Context: 
I would like to contribute. Please see  additional details describing my working app : https://nanocorp.arweave.dev/

 Arweave Standards:   https://github.com/ArweaveTeam/arweave-standards 

Arweave  Background :  https://ardrive.io/can-data-really-be-stored-forever/#:~:text=The%20initial%20cost%20a%20user,data%20storage%20costs%20over%20time

**Comment by mekarpeles** [comment]
We make our data publicly available via data dumps, raid/store them redundantly on Archive.org and beyond. Please feel free to implement further data longevity strategies (out of scope of current roadmap)
