### ISSUE TITLE
When you add author to list, list is shown twice on author page

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#7643]
### Evidence / Screenshot (if possible)
![зображення](https://user-images.githubusercontent.com/58372007/224920453-ff01508a-8c45-4ec1-81dd-5168b7b111d8.png)

### Relevant url?
https://openlibrary.org/authors/OL4493304A/Mykha%C4%ADlo_Kot%EF%B8%A0s%EF%B8%A1i%EF%B8%A0u%EF%B8%A1byns%CA%B9ky%C4%AD

### Steps to Reproduce

1. Go to ... any author page
2. Do ... add author to list. It is shown once
3. Refresh the page. Now list is shown twice

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by Katzmann835** [comment]
Hi, I would like to be assigned to see if I can resolve this issue. Is that okay?

**Comment by scottbarnes** [comment]
Hi, @Katzmann835. It looks as if there's already a linked PR in the works to close this particular issue, but there is no shortage of unaddressed issues.

Perhaps a good place to start is issues with the ["Good First Issue" and "Needs: Help"](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Help%22+label%3A%22Good+First+Issue%22) labels. The [Getting Started](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md) page on the wiki can be helpful too.

**Comment by Katzmann835** [comment]
Thank you for notifying me, I can find a different issue to resolve instead
