### ISSUE TITLE
Open Library Team Page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7650]
### Describe the problem that you'd like solved

A basic team page design for https://openlibrary.org/about/people

Designs:
https://www.figma.com/proto/8MoiibMFcYHI3djoiiFmWP/Meet-the-Staff-2?node-id=206%3A244&scaling=min-zoom&page-id=206%3A213&starting-point-node-id=206%3A244

<img width="1065" alt="Screenshot 2023-03-14 at 7 43 39 PM" src="https://user-images.githubusercontent.com/978325/225191644-b40b07c3-60ae-4632-844e-58d508cc7106.png">

## Important files & next steps

Here is an example of how to register a new route with Open Library (i.e. how to define or override an endpoint like `/about/people`:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/authors.py

We'll also need to add a new file to our `templates/` directory -- `/about/people.html` in:
https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates

## Relevant resources
* https://archive.org/details/openlibrary-tour-2020/technical_overview.mp4

**Comment by Lasseignejk** [comment]
I'd like to work on this issue!

**Comment by mekarpeles** [comment]
@Lasseignejk please do! Do you have any questions or need any help with next steps?
