### ISSUE TITLE
Add site banner for March 20th Legal Oral Hearings

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7656]
Internal staff planning details available at https://docs.google.com/document/d/12X3MGLNV2k8w4eMXRd4MbP5QLb70PHuIKNeZ7B_YAQ8/edit#heading=h.wa34425eph6m

```
We're fighting for the future of our library today in court. [Show your support now!]
http://blog.archive.org/2023/03/20/today-fighting-for-the-future-of-our-library-in-court/
```

To be **patch deployed** day before/on March 20th

Relates to #7345 (if possible)

**Comment by JaydenTeoh** [comment]
@mekarpeles was wondering if you are working on the implementation to dismiss banners (mentioned in #7345) as part of this issue? If so, do you need help with it? I can make a PR for it within the next 2 days

**Comment by mekarpeles** [comment]
@JaydenTeoh if you'd like, it would be useful! This specific issue can be closed -- it has been deployed.

**Comment by JaydenTeoh** [comment]
@mekarpeles Thanks for the reply! I'm on it!
