### ISSUE TITLE
Self-Serve Process to Generate Work-level Edition Synonyms (DWWI) 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7657]
This is a possible duplicate. @hornc needs monthly solr dumps of Work-level Edition Synonyms (by isbn & lccn -- see #7545).

We did this as a 1-off in the past. This issue calls for **instructions** and a **script** / process that @hornc and/or others may run to create a fresh monthly Work-level Edition Synonyms dump.

Q: Should this be a monthly dump we create along with our other crons? Likely not necessary, but could be a pattern that ultimately saves work.

**Comment by tfmorris** [comment]
Is there a definition someplace for "Work-level Edition Synonym"? Is it some type of duplicate?
