### ISSUE TITLE
503 Service Unavailable when adding authors to list

### ISSUE THREAD

**Issue by JaydenTeoh** [internetarchive/openlibrary#7666]
I am getting `503 Service Unavailable` after trying to add an author to a list. The request URL is `https://openlibrary.org/people/jayden_t370/lists/OL223136L/seeds.json` and the payload is `{add: [{key: "/authors/OL2271984A"}]}`.

### Steps to Reproduce

1. Go to an authors page (e.g. https://openlibrary.org/authors/OL2271984A/Frank_H._Richardson)
2. Try to add the author into one of your list or create a new list for the author
3. Inspect the API response in the Network tab, it should show `Status Code: 500`
4. Refresh the page, the page should now should `503 Service Unavailable` and fail to render the author's page
<img width="794" alt="image" src="https://user-images.githubusercontent.com/90945854/225410198-be035ce8-93e2-4917-9a42-aabc06ba911a.png">

Issue will tie-in with #7643
### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Chrome
- **Operating system?** macOS Monterey
- **Environment (prod/dev/local)?** prod

### Stakeholders

@mekarpeles @cdrini, I know you guys mentioned about looking into 503 errors for book merging in yesterday's meeting, perhaps you guys would like to look into this issue as well

**Comment by mekarpeles** [comment]
@JaydenTeoh can you confirm this is still an issue? We recently hit some issues within this time frame documented in #7667 which have since been resolved.

If this issue is fixed, please close :)

**Comment by JaydenTeoh** [comment]
@mekarpeles Just tested and looks like the issue has been resolved. Will be closing this issue. Thanks Mek!
