### ISSUE TITLE
Accessibility issue on Privacy Settings

### ISSUE THREAD

**Issue by edent** [internetarchive/openlibrary#7679]
### Evidence / Screenshot (if possible)
<img width="530" alt="Screenshot 2023-03-17 at 11 24 00" src="https://user-images.githubusercontent.com/837136/225891902-4b1d60a8-1dfb-4c42-8d1f-2a0d51701569.png">

### Relevant url?
https://openlibrary.org/account/privacy

### Steps to Reproduce

1. Go to your privacy settings
2. Click on the **word** yes or no
3. Observe that the radio button doesn't change

* Actual: Radio doesn't toggle
* Expected: Radio should toggle

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 120
- **Operating system?** MacOs
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

`<label for="u0">Yes</label>`

Should be:

`<label for="r0">Yes</label>`

"no" needs to be changed to "r1"

**Comment by abelaba** [comment]
Hi @edent I would really like to contribute to this project, can I work on this issue?

**Comment by edent** [comment]
@abelaba go for it!

**Comment by scottbarnes** [comment]
Hi, @abelaba. It looks as if @cdrini has linked a PR, #7680, that will close this. It's on testing at https://testing.openlibrary.org/account/privacy and you can double check it and if you have any feedback it would be great to leave it over in #7680.

**Comment by abelaba** [comment]
Okay @edent and @scottbarnes thank you for the swift response. I will check it out.
