### ISSUE TITLE
Merge tool issue: failed to load ratings for /works/OL15156205W

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#7689]
### Evidence / Screenshot (if possible)
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/921217/226403832-00e7fa92-9c72-4462-be89-fefaed9ac926.png">

### Relevant url?

https://openlibrary.org/works/merge?records=OL1396634W,OL15156205W

### Steps to Reproduce

1. Go to above url (when a librarian)
2. See error

PS: I think this is worse for me because I'm loading from Europe.

* Actual: Error message and can't merge
* Expected: Error message saying rating can't load but still let me merge

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Make it so that if rating fail to load it just says there is an error but still lets you merge.

### Stakeholders

@seabelis @mekarpeles

**Comment by mheiman** [comment]
This is a duplicate of #7608, which has a pending PR to address it. Ray, you can close this and add any additional comments over there.

**Comment by RayBB** [comment]
@mheiman awesome! Thanks for fixing this :)
