### ISSUE TITLE
Redesign the Google Sign-Up Screen So No Email Sign-Up Field is Shown

### ISSUE THREAD

**Issue by beccat123** [internetarchive/openlibrary#7696]
Currently, the screen that users see after they chooses their Google account to sign into Open Library with displays fields for email sign-ups. This may cause user confusion, as patrons who have already chosen to sign up with their Google account likely do not need to see email-sign-up-related information.

Please make UI modifications to the current screen so that the design of the screen looks consistent with that documented in this Figma frame, a screenshot of which is also reproduced below:
https://www.figma.com/file/kiaTbWxdPsyqz6eeaT4M8l/Open-Library---Sign-In-Flow?node-id=131%3A107&t=FzSHcvPgYWggglxa-1
<img width="1440" alt="Google signup - second page" src="https://user-images.githubusercontent.com/99151794/226647699-21c309a7-54df-4b9b-a9d5-5edeb38f7fdf.png">

This issue belongs to the epic #7694

**Comment by Avyukth1C** [comment]
Hey, I am new to Open source projects. I would like to work on this Issue. I would like to understand the current codebase.

**Comment by mekarpeles** [comment]
Apologies @achiverram28 for not replying to you sooner! If you're still open to working on improving registration, we have several related issues we'd love to discuss with you.

@beccat123 + @jimchamp can we followup with @Avyukth1C to see if there's a way to move this effort forward?

**Comment by Avyukth1C** [comment]
I would love to work on it and make sure I put in my best efforts.

I would like some details on the functionality of the revamped page and would you be please direct me to required files.

Thanks in advance.

**Comment by jimchamp** [comment]
I don't believe that this change can be made, as the Google sign-in component is coming from archive.org.

Closing this for now.
