### ISSUE TITLE
Merge Authors on work with same name but different OLIDs

### ISSUE THREAD

**Issue by EdwardBetts** [internetarchive/openlibrary#77]
Example: http://openlibrary.org/works/OL61981W/Iliad

**Comment by LeadSongDog** [comment]
@bencomp I think that what @EdwardBetts  was addressing there was https://openlibrary.org/works/OL61981W/Iliad?b=47&a=45&_compare=Compare&m=diff and https://openlibrary.org/works/OL52947W/Bad_Luck_and_Trouble?m=history and https://openlibrary.org/works/OL52947W/Bad_Luck_and_Trouble?b=12&a=11&_compare=Compare&m=diff 
wherein a work record had multiple links to the same author record. This is distinct from the problem of multiple author records for a single author (e.g. variant spellings).

**Comment by LeadSongDog** [comment]
For the occasional parent and eponymous child coauthor cases where they do not use sr, jr, etc, either the birth and death dates or an external author id (e.g. VIAF, ISNI, Wikidata QID)  should be checked to avoid conflating the two. Usually a natural disambiguator already exists, as for George Herbert Walker Bush vs George W. Bush.

**Comment by mekarpeles** [comment]
This is solved by the fact that we have an Author merge method accessible to Librarians. If someone wants to do a task to bulk-identify Works which have presumed duplicate authors, feel free to document here. Going to close this issue as there's no systemic bug causing this.
