### ISSUE TITLE
Implement new design for the "my lists" section of the my books page

### ISSUE THREAD

**Issue by danafein** [internetarchive/openlibrary#7704]
We would like to add a new "my lists" section at the bottom of the my books page. The design for this section is pictured here: 

<img width="630" alt="Screen Shot 2023-03-22 at 2 11 41 PM" src="https://user-images.githubusercontent.com/30005120/226999025-d4d15574-d5c3-465b-a82f-38c08b275308.png">

The main components of this design are:

- The "My Lists" heading and the total number of lists in parentheses
- The list cards for the user's first three lists
- The design of the list card itself:
          - Beige background that previews the covers of the first three books on the list
          - White rectangle at the bottom with the name of the list and number of books

Here is an additional image, which shows the location of list section in relation to the rest of the my books carousels: 

<img width="385" alt="Screen Shot 2023-03-22 at 2 11 57 PM" src="https://user-images.githubusercontent.com/30005120/227000016-b861192c-a2a9-43b0-9236-a28c3e3e799f.png">

For any clarifying questions about the design, please reach out to @danafein

**Comment by MaAnCoSa** [comment]
Hi! I am new to contributing to open-source projects. Can I give this issue a try?

**Comment by danafein** [comment]
@MaAnCoSa yes, I just assigned the issue to you! Thank you for your interest in working on it!

**Comment by MaAnCoSa** [comment]
I am trying to work with the style of the different containers for a new carousel, but I have never worked with Less for the CSS files. I am trying to test if I can see changes creating a new class style in the carousel.less file (it just sets the div background to light blue), but the changes are never shown when refreshing the browser. I also tried restarting the docker container to see if that would recompile the CSS files with the changes in the Less files, but it's still the same.

What is the correct way of altering the styles in this project?

**Comment by scottbarnes** [comment]
@MaAnCoSa, the information is a bit spread out, but have you checked out [Building CSS and JS](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#building-css-and-js)?

**Comment by MaAnCoSa** [comment]
@scottbarnes I had not checked that! I used the watch script and everything shows now. Thank you.

**Comment by gobbledy-gook** [comment]
Is this issue still active or is it resolved ?

**Comment by scottbarnes** [comment]
Hi, @gobbledy-gook. There is a linked pull request (#7743), but I am not sure what's holding it up.

**Comment by 20481A05K0** [comment]
good morning everyone
Is this issue still exists or can you assign that to me i will try to handle

**Comment by jimchamp** [comment]
There is already a PR open for this issue.  If you're looking for a good first issue, check out this list: https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Help%22+label%3A%22Good+First+Issue%22
