### ISSUE TITLE
Update Docker Compose references (when used as a command) in Wiki articles

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7708]
Currently, the project wiki contains numerous references to `docker-compose`, but this is being [depreciated in June 2023](https://docs.docker.com/compose/compose-v2/) in favor of `docker compose`.

All wiki references to `docker-compose`, _when used as a command_, need to be updated to `docker compose`.

*Note*: references to file names, such as `docker-compose.yml`, should not _yet_ be changed to `compose.yaml` (per the [preferences stated in the Compose documentation](https://docs.docker.com/compose/compose-file/03-compose-file/)). File names should stay the same until #7594 is merged. For now, only update commands.

Here's a query to help find wiki references to `docker-compose`: https://github.com/internetarchive/openlibrary/search?p=1&q=docker-compose&type=wikis

Steps to complete:
1. Locate references to `docker-compose` on the wiki where `docker-compose` is being used as a command and not part of a file name.
2. Update the reference to `docker compose`
3. Keep track of the wiki articles you change and link them here so we can double check everything.

Related: #7594. 

### Stakeholders

@jamstack-elise, as you've raised this issue, would you be interested in taking it on?
@cclauss

**Comment by jamstack-elise** [comment]
@scottbarnes Yes, I'm happy to follow through. And thanks for the steps summary.

**Comment by scottbarnes** [comment]
Oh I just saw this. I am sorry, @jamstack-elise, for not making this more clear. This issue is specifically to address uses of `docker-compose` within the [wiki](https://github.com/internetarchive/openlibrary/wiki).

If you are still interested in doing this, this search will show all references that (potentially) need updating: https://github.com/internetarchive/openlibrary/search?p=1&q=docker-compose&type=wikis.

Note: the only references that need updating currently is when `docker-compose` is used as a command. We will need to update filename references once #7626 is merged, but I am not sure how soon that will be.

**Comment by jamstack-elise** [comment]
> Oh I just saw this. I am sorry, @jamstack-elise, for not making this more clear. This issue is specifically to address uses of `docker-compose` within the [wiki](https://github.com/internetarchive/openlibrary/wiki).
> 
> If you are still interested in doing this, this search will show all references that (potentially) need updating: https://github.com/internetarchive/openlibrary/search?p=1&q=docker-compose&type=wikis.
> 
> Note: the only references that need updating currently is when `docker-compose` is used as a command. We will need to update filename references once #7626 is merged, but I am not sure how soon that will be.

Oops @scottbarnes, I'm sorry for this small hiccup in this process.😅 

The wiki pages return 14 results with ```docker-compose.``` I've gone ahead and made the first pass of edits, and I've notated changes in the "optional" form field. 

Of the 14 wikis, 7 of these pages were edited so ```docker-compose``` is now ```docker compose```:
1. [Production Service Architecture](https://github.com/internetarchive/openlibrary/wiki/Production-Service-Architecture)
2. [Deployment-Scratchpad](https://github.com/internetarchive/openlibrary/wiki/Deployment-Scratchpad)
3. [Debugging](https://github.com/internetarchive/openlibrary/wiki/Debugging)
4. [Getting-Started](https://github.com/internetarchive/openlibrary/wiki/Getting-Started)
5. [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing)
6. [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet)
7. [Frontend Guide](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide)

Of the 14 wikis, 5 of these pages are in question:
1. [Testing & Staging environments](https://github.com/internetarchive/openlibrary/wiki/Testing-&-Staging-environments) | Question: This affects the script specifically. Do we want to place the docker compose edit when we have not yet had a deliberation for script file content?
2. [Deployment Guide](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide) | Question: Same question mentioned in this block's (1).
3. [Cron-Jobs](https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs) | Question: Do we want to edit the cron job to docker compose --profile ol-home0 up -d --no-deps cron-jobs?
4. [Loading-Production-Book-Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data) | Question: Same question mentioned in this block's (1).
5. [Solr](https://github.com/internetarchive/openlibrary/wiki/Solr) | Question: Same question mentioned in this block's (1).

Of the 14 wikis, 2 of these pages were not edited:
1. [Generating Data Dumps](https://github.com/internetarchive/openlibrary/wiki/Generating-Data-Dumps) | Reason: docker-compose is the filename.
2. [Open Library Community Call Minutes](https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes) | Reason: These are old minutes and likely stale.

As an aside, the work initially done before I realized I was wrong in following instructions is still useful in that we have visibility of what filenames have docker-compose commands embedded within the scripts. I've also updated the existing Readme markdown files found on openlibrary. Thanks!

**Comment by scottbarnes** [comment]
Thanks for this, @jamstack-elise!

Good call on adding that little 'header' section to [Deployment-Scratchpad](https://github.com/internetarchive/openlibrary/wiki/Deployment-Scratchpad). I think it makes sense to leave the rest of the references in there to `docker-compose` alone as they are historical. And yes, not point in updating the Community Call Minutes, I think.

With respect to the the 5 articles in question, because #7676 has been merged, we can safely update the references to `docker compose` where it is used as a command.

That said, let's not update any historical references for now. E.g. in the Deployment Guide, a lot of it is a log of the past. Let's only update references that are not a past log of things done / commands run / filenames used. Maybe we'll decide to do this later, but for now, let's only update more general 'here is how to do this thing'-type references, if that makes sense. 

@cclauss, any specific thoughts on updating historical references to `docker-compose` and `docker-compose.yml`?

Finally, the little `Edit message` box doesn't display formatting, so very short descriptions, such as "docker-compose -> docker compose" are probably sufficient going forward.

**Comment by jamstack-elise** [comment]
@scottbarnes This is a summary of the wiki edits made on the 5 articles:

(1)[Testing & Staging Environments](https://github.com/internetarchive/openlibrary/wiki/Testing-&-Staging-environments)

- Updated with a header about docker-compose and docker compose per the recent Docker instructions.
- Updated ```docker-compose``` commands to ```docker compose```  on [Manually deplying to testing.openlibrary.org](https://github.com/internetarchive/openlibrary/wiki/Testing-&-Staging-environments#manually-deploying-to-testingopenlibraryorg)

(2)[Deployment Guide](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide)

- Updated with a header about docker-compose and docker compose per the recent Docker instructions.
- Updated docker commands: ```docker-compose``` to ```docker compose``` on these headers with codeblock(s):
  - [Recovering from Restart Loops](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#recovering-from-restart-loops)
  - [Deploying to testing.openlibrary.org](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide#deploying-to-testingopenlibraryorg)

(3) [Cron Jobs](https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs)

- Updated with a header about docker-compose and docker compose per the recent Docker instructions.
- Updated docker commands: ```docker-compose``` to ```docker compose``` on these headers with codeblock(s):
  - [Updating Cron Jobs on ol-home0 - edited bash script](https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs#updating-cron-jobs-on-ol-home0)

(4) [Loading Production Book Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data)

- Adjusted the language under ## Loading Production Data into Local Developer Environment	so it segues into a new header: "### A note on `docker-compose` and `docker compose`"
- Updated docker commands: ```docker-compose``` to ```docker compose``` on the bash script.

(5) [Solr](https://github.com/internetarchive/openlibrary/wiki/Solr)

- Augmented the language under ### Making changes to solr config by introducing the Docker Compose update
- Updated docker commands: ```docker-compose``` to ```docker compose``` on the bash script contained in  [Making changes to solr config](https://github.com/internetarchive/openlibrary/wiki/Solr#making-changes-to-solr-config)

**Comment by scottbarnes** [comment]
Thank you for this, @jamstack-elise.

I reviewed it all and it looks good.

One minor change I made is that I removed the header about `docker-compose` and `docker compose` from a few articles only because of who the audience is for those articles and because on the servers where the commands in question will be run, updated versions of Docker Engine have already been installed. Without this background, you wouldn't have known that, though. :)

Looks like this part is all done! :tada:

**Comment by jamstack-elise** [comment]
> Thank you for this, @jamstack-elise.
> 
> I reviewed it all and it looks good.
> 
> One minor change I made is that I removed the header about `docker-compose` and `docker compose` from a few articles only because of who the audience is for those articles and because on the servers where the commands in question will be run, updated versions of Docker Engine have already been installed. Without this background, you wouldn't have known that, though. :)
> 
> Looks like this part is all done! 🎉

Fantastic! 🏹 It was intended to keep things broad for newcomers to see process. I bet it's easier for issue managers to subtract than add, especially in these async settings. Happy to have helped closed this. :)
