### ISSUE TITLE
Importbot changing/appending populated values

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7744]
Importbot changing/appending populated values.

### Relevant url?

https://openlibrary.org/books/OL28438803M/Bleak_House?_compare=Compare&b=10&a=8&m=diff

### Steps to Reproduce

1. Go to ...https://openlibrary.org/books/OL28438803M/Bleak_House?_compare=Compare&b=10&a=8&m=diff
2. Do ... note the change made by the importbot to the publisher field

* Actual: The importbot appended to the existing value. In this case, the corporate name was added to the imprint.
* Expected: If a field has a value, the bot should not change the existing value.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by mekarpeles** [comment]
@seabelis is this undesirable? Maybe we can discuss during community call (I'm tempted to close it but don't want to do so without understanding your opinions first).

**Comment by mekarpeles** [comment]
We are addressing these valid concerns in our development towards #7761

**Comment by seabelis** [comment]
https://openlibrary.org/books/OL9349663M/Big_Deal?_compare=Compare&b=9&a=5&m=diff
Existing publisher added a second time but with "Ltd." The Crowood Press has no obvious connection to this particular manifestation.

**Comment by tfmorris** [comment]
I think the goal should be to continuously improve the records, not necessarily freeze the first set of information available. Although "Crowood Press" is from [BWB import](https://openlibrary.org/books/OL9349663M/Big_Deal?b=7&a=6&_compare=Comparer&m=diff) and it is not complete fiction (surprisingly). Crowoods acquired Robert Hale's list when it closed in 2015 (and then [sold](https://joffebooks.com/blog-1/2019/3/5/joffe-books-acquires-robert-hale-crime-and-general-fiction-list-from-the-crowood-press) much of the list to Joffe Books in 2019).

Publishers with / without Inc, Ltd, etc should be dealt with by normalization. It looks especially silly on a single catalog record, but it's not much better to have the different name forms spread across editions. There are more than 7 different ways to spell "Robert Hale" in OpenLibrary:
![Screen Shot 2023-04-05 at 2 23 41 PM](https://user-images.githubusercontent.com/82178/230170391-e2065b55-0bea-4d4d-8161-b1384a112d70.png)

**Comment by seabelis** [comment]
"Crowoods acquired Robert Hale's list when it closed in 2015 (and then [sold](https://joffebooks.com/blog-1/2019/3/5/joffe-books-acquires-robert-hale-crime-and-general-fiction-list-from-the-crowood-press) much of the list to Joffe Books in 2019)."

Business acquisitions don't need to be part of the bibliographic record.

**Comment by seabelis** [comment]
As far as the name form goes, as it appears on the title page is appropriate (usually). The publisher names can change over time; multiple forms of the name do not need to appear on a given record.
