### ISSUE TITLE
Remove "(# ebooks)" from search results

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#775]
The ebooks count in ()'s is inaccurate because it includes all books we have digitized -- both those which are readable / borrowable and those which are restricted to a print-disabled-only audience. Since most users cannot access these books, the number is often misleading and thus should be removed from the UI. I believe 

I believe the change needs to be made in openlibrary/macros/SearchResultsWork.html within the css class `resultPublisher`

@salman-bhai -- want to try this one one?

In the following example, the `118 editions` should stay and the `(13 ebooks)` should be removed

![2018-01-30-014952_1600x900_scrot](https://user-images.githubusercontent.com/978325/35559775-6351f11e-0560-11e8-82b3-f0079ef3b678.png)

**Comment by salman-bhai** [comment]
I'll do it! Thanks again!

**Comment by salman-bhai** [comment]
I think we should close this Issue!
