### ISSUE TITLE
E-book filter

### ISSUE THREAD

**Issue by Ari1009** [internetarchive/openlibrary#7750]
Filtering book according to if it  is an e-book or not should be removed since there is already an option at the top.

![Screenshot (499)](https://user-images.githubusercontent.com/69034460/229307959-2d950803-dceb-4ad2-b33f-5783026990e3.png)
 this will help to have a cleaner UI

**Comment by mekarpeles** [comment]
We're open to proposals on how we can better set an "ebook mode" across searches and a new issue proposing such is welcome but this issue proposal we remove the radio buttons is not a viable option at this time.

**Comment by Ari1009** [comment]
Yes, changing the UI of the radio button is necessary. After that, we can decide whether or not to remove the e-book filter on the right side.
