### ISSUE TITLE
Sentry: High volume increase in Infobase errors

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7753]
### Summary

Key question is whether we need to increase threshold (number per hour) or whether there's an issue under the hood we need to resolve (related to 2023-03-31 deploy)

- **What is wrong?**

- **What caused it?**

- **What fixed it?**

- **Followup actions:**

### Steps to close

1. [ ] Assignment: Is someone assigned to this issue? (notetaker, responder)
2. [ ] Labels: Is there an `Affects:` label applied?
3. [ ] Diagnosis: Add a description and scope of the issue
4. [ ] Updates: As events unfold, is notable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [ ] "What caused it?" - please answer in summary
6. [ ] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by jimchamp** [comment]
Dropping to p2:  @mekarpeles and @cdrini changed some Sentry thresholds, which has helped.

**Comment by mekarpeles** [comment]
Closed as unactionable -- we didn't add enough info to track what's going on here
