### ISSUE TITLE
Missing unique IP data from IA in Graphite for the past three days

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#7762]
### Evidence / Screenshot (if possible)
We will now be getting our Unique Visitor counts from IA as discussed in
* #7745

However there is no new data for the past three days as can be seen at the end of https://graphite.us.archive.org/render?target=summarize(group(stats.uniqueips.openlibrary),"1day")&from=-60days&format=json
```
...
2023-03-28 22:22:00: 18999120
2023-03-29 22:22:00: 17806440
2023-03-30 22:22:00: 16001040
2023-03-31 22:22:00: 14670600
2023-04-01 22:22:00: 0
2023-04-02 22:22:00: 0
2023-04-03 22:22:00: 0
```
<img width="248" alt="Screenshot 2023-04-04 at 20 50 00" src="https://user-images.githubusercontent.com/3709715/229905383-ecfb0b68-5d96-4762-8f33-e4fdde46e4b5.png">

<img width="910" alt="Screenshot 2023-04-04 at 21 44 44" src="https://user-images.githubusercontent.com/3709715/229905409-8f3e65b3-c43c-49ad-913a-ef28e1565f84.png">

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
The stat numbers may be wrong on the chart but the numbers themselves are making it through the pipeline (archive.org www items)
