### ISSUE TITLE
Open Library's About Page and Vision Statement

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7777]
At the moment, Open Library has three entries to welcome users and give an overview about what Open Library is supposed to be. Some of the content is outdated or conflicting. For example, the Vision pages states one could publish directly through OpenLibrary, but that is nowhere followed on. With so many pages covering one topic, it is also rather difficult to keep them all up to date.

### Relevant url?

- [About us](https://openlibrary.org/about)
- [Open Library Vision](https://openlibrary.org/about/vision)
- [An Introduction to Open Library](https://openlibrary.org/tour#:~:text=OpenLibrary.org%20is%20an%20online,of%20charge%20and%20ad-free)

### Steps to Reproduce

I started to gather different aspects of the documentation, and found that some pages are conflicting.

* Actual: Different pages with similar topics, but different content.
* Expected: One page with up-to-date content.

### Proposal & Constraints

It would probably be a good idea to combine all three pages into one About page, to prevent users getting lost, and also to make it easier to keep the documentation up to date.

**Comment by WilsonGoins** [comment]
@mekarpeles can I be assigned to this? Also, would I need to send a draft for the one new "About" page before I actually update the website in a PR? First time contributing here...

**Comment by mekarpeles** [comment]
I merged the vision into https://openlibrary.org/about and made `vision` a redirect to `/about`. I think it's good enough for us to close.
