### ISSUE TITLE
Carousels bug with window resizing.

### ISSUE THREAD

**Issue by digitals82** [internetarchive/openlibrary#7778]
Hi everyone,

We've been creating collections with no arrows in order for them to form a grid. Here are two examples so far from myself and Lisa.

https://openlibrary.org/collections/nightmare-hall

https://openlibrary.org/people/agent-lisa/lists/OL202805L/goddard-1

It works fine when opening the page, but as soon as the window is resized, arrows appear on the carousels and it links to books that don't exist within the lists they are created from. 

Drini asked me to post the issue in here, and I've included a video to demonstrate what is happening. 

Hopefully someone can take a look and might have an idea why this is happening. Thank you!

Scott

https://user-images.githubusercontent.com/108327598/231401126-cb012d4c-fffd-4df8-8d0f-58b096c4a9c8.mp4

**Comment by mekarpeles** [comment]
What appears to be happening is when the list runs out of books, the carousel tech defaults or falls back to using the list key (e.g. `/people/smcvgped/lists/OL210986L`) as a `solr` query for `loadmore` whereas we should just return no results.

This seems `list` carousel related, e.g.

https://openlibrary.org/search.json?q=%2Fpeople%2Fsmcvgped%2Flists%2FOL210986L&fields=key%2Ctitle%2Csubtitle%2Cauthor_name%2Ccover_i%2Cia%2Cavailability%2Cid_project_gutenberg%2Cid_librivox%2Cid_standard_ebooks%2Cid_openstax&limit=20&offset=15

**Comment by digitals82** [comment]
Thank you for taking a look into this @mekarpeles !

**Comment by davidscotson** [comment]
I think this is the bug discussed the other day on the zoom call, regarding grids and YA horror titles so I've done a quick investigation.

Firstly, to explain the workaround attempted above via librarian configuration, the idea is to use multiple lists, each consisting of 6 books each. By stacking them on top of each other, you get a grid effect.

At full desktop size, the carousel is set by default to show 6 items, if it can show its entire list of items (i.e. 6 out of 6) then it doesn't add any arrows and the workaround works nicely.

If you resize the page downwards or visit on mobile, the current settings for carousels are to show less and less items per line so they fit nicely on the screen. At that point, the slider is only showing 4/6 or 3/6 items in each list, so it automatically adds the arrows back to let you scroll to view the rest.

Once you have arrows, you can scroll to the end of the 6 items, and the default behaviour of automatically continuing with a search kicks in, leading to books not specifically in the list showing up.

So, one potential quick partial fix is to add a load_more paramater to the ListCarousel and optionally disable the load more.

The arrows would still appear at smaller sizes, but you'd only be able to scroll the 6 items specified in the list.

One idea thats slightly more work but maybe worth it would be to provide a ListGrid template that simply used modern CSS Grid to lay out the books. So no scrolling, just a grid that matches the visual look in the video above.

**Comment by cdrini** [comment]
Hi @davidscotson ! We'll want the latter solution to meet Scott's need. We'll need to create a new issue for adding a grid view option for our carousels ; it seems like we don't have one!

Note code wise it might be easier to add a parameter to the existing carousel code display=grid (or something), since there are a few layers of carousel templates, but still leave that up to you!
