### ISSUE TITLE
Corrections for the identifiers of works in National Libraries

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7785]
When checking the identifiers for books, I found some errors - broken links, missing descriptions, spelling errors and the like.

### Relevant url?
https://openlibrary.org/config/edition

### Steps to Reproduce

Attempting to work with the identifiers on testing.

### Details
(Corrected entries for all entries with mistakes I found)

- [x] First of all, the Spanish National Library has three entries:
label: Depósito Legal. Biblioteca Nacional de España
label: Biblioteca Nacional de España Depósito Legal 
label: Depósito Legal N.A. 

- [x] Furthermore, the website link is broken for all of them and ended in a 404 (here the correct link).
website: https://www.bne.es/en/catalogues

- [x] There is a spelling error in the BnF name, the "nationale" should be written without a capital letter.

label: Bibliothèque nationale de France (BnF)
name: bibliothèque_nationale_de_france
website: https://www.bnf.fr/
url: https://catalogue.bnf.fr/ark:/12148/@@@

- [x] The Canadian National Library ID can now be linked with their new permanent redirect:

label: Canadian National Library Archive
name: canadian_national_library_archive
notes: Session-based IDs
website: https://library-archives.canada.ca/
url: https://central.bac-lac.gc.ca/.redirect?app=fonandcol&id=@@@&lang=eng
(Example for @@@: 4369908)

**Comment by cdrini** [comment]
All fixed! Note we should do a cleanup task to migrate `depósito_legal_n.a.` to the new ID.
