### ISSUE TITLE
Identifier whose domain no longer exist

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7787]
Some identifiers no longer exist, and the items are no longer resolved. Some were already marked as deprecated, but Choosebooks was not.

### Details

        label: Choosebooks
        name: choosebooks
        notes:
        url: http://www.choosebooks.com/displayBookDetails.do?itemId=@@@
        website: http://www.choosebooks.com/

        label: Freebase
        name: freebase
        notes: retired
        url: http://www.freebase.com/view/en/@@@
        website: http://freebase.com/

        label: Shelfari
        name: shelfari
        notes: merged with goodreads.com
        url: http://www.shelfari.com/books/@@@/
        website: http://www.shelfari.com/

### Proposal & Constraints

The identifier should be removed.

### Related files

https://openlibrary.org/config/edition

**Comment by cdrini** [comment]
I labelled it as no longer running, but we don't want to remove these. They're still valuable for historical reasons for folks who might've relied on those identifiers in the past.
