### ISSUE TITLE
The arrow icon not pointing downward.

### ISSUE THREAD

**Issue by gaurav-2-0-0-2** [internetarchive/openlibrary#7791]
So, the arrow icon before the filter button is pointing upward after clicking it on smaller widths.

![issue](https://user-images.githubusercontent.com/98230369/232634526-837334ec-a88d-4881-90ab-43619bf76183.png)

### Relevant url?
[check here](https://archive.org/details/tv?q=jello&and[]=program%3A%22The+Late+Show+With+Stephen+Colbert%22)

### Steps to Reproduce

1. Go to ... Search bar
2. Search anything 
3. select TV News Archive
4. decrease the width of the window
5. click on the filter button 
6. the arrow icon before this filter button is pointing upward even after clicking it. 

* Actual: Pointing Upward 
* Expected: It should point downward after the button has clicked and the dropdown has opened.

**Comment by gaurav-2-0-0-2** [comment]
Assign it to me, I'll be happy 😊 to work on this.

**Comment by seabelis** [comment]
This is actually an archive.org interface and not part of the Open Library site. @bfalling
