### ISSUE TITLE
Display author date(s) with name for librarians

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7799]
Author disambiguation is difficult and even more difficult when the author names all look the same for different identities. To see precisely which author is associated with a work, one must either click the author to view the profile or go into edit mode and use the author selection box.

### Describe the problem that you'd like solved

Authors should display their associated years to make this task less cumbersome. 

### Proposal & Constraints

Only the year is necessary, any other date information does not need to be displayed.
This should be a librarian-feature only.

### Additional context

For example, these are two different Stephen Kings:
<img width="454" alt="Screenshot 2023-04-19 at 09 02 16" src="https://user-images.githubusercontent.com/17739465/232992930-9b99cdaf-2e84-491f-bea3-ec4457b18a32.png">
<img width="484" alt="Screenshot 2023-04-19 at 09 02 38" src="https://user-images.githubusercontent.com/17739465/232993031-8c846762-0dee-4d60-9c83-b10100d4be65.png">

A display like this would make disambiguation much easier and less time-consuming:
<img width="314" alt="Screenshot 2023-04-19 at 09 04 35" src="https://user-images.githubusercontent.com/17739465/232993643-55f2d88f-ff8f-487b-8931-aaa447f54acf.png">
<img width="466" alt="Screenshot 2023-04-19 at 09 04 47" src="https://user-images.githubusercontent.com/17739465/232993680-717724ab-907f-473c-9c4a-048575328ed1.png">

**Comment by LeadSongDog** [comment]
@seabelis 
Why librarian-feature only? Many of us mortals have struggled with this problem.

**Comment by seabelis** [comment]
@LeadSongDog @mekarpeles indicated that this is preferred.

**Comment by tfmorris** [comment]
> @mekarpeles indicated that this is preferred.

Preferred by a representative sample of customers? I missed the fact that this was spec'd as librarian only and agree that it is generally useful. What is the down side to having more information available to everyone?

**Comment by cdrini** [comment]
The logic is that this area of the page is already featuring a lot of information. The downside to having more information _visible_ (note the information is/was always _available_) is that it can make it difficult to realize what information to focus on, and potentially look cluttered. My guess would be that a very large chunk of the users accessing this page would not have their experience improved by having that extra information in one of the most prominent pieces of realestate on this page, and in fact would defer their attention from information that might be more meaningful to them.

**Comment by LeadSongDog** [comment]
@cdrini 
"Available" only in the sense that the Lost Ark could be found by Indiana Jones with sufficient motivation, persistence, and willingness to risk bending rules.  Our task is to make the correct information readily accessible.  Perhaps a compromise then: don’t show it on small screens, where errors are unlikely to be corrected anyhow.

**Comment by Lux-Sales** [comment]
Working on it

**Comment by chrisbenson32** [comment]
Can I take this on as progress seems to have stopped on this item? cc @Lux-Sales

**Comment by AverseABFun** [comment]
I can.

**Comment by shahad1307** [comment]
@mekarpeles Hello I'm a student in CMU and I have a project. I'm interested in working on this issue. Looks doable could do assign me?

**Comment by jimchamp** [comment]
@shahad1307 you are assigned.  Please let me know if you have any questions.

**Comment by Aeltumn** [comment]
I noticed this issue has been without an assignee for a few months, so I don't think anyone is still working on it? I would be interested in giving it a try. Could you assign me?

**Comment by jimchamp** [comment]
There is a linked PR that addresses this issue.  @cdrini, what's going on with #8076?

**Comment by Aeltumn** [comment]
Could I make a copy of the PR, re-test it, and fix/address the comments? The PR has been inactive for quite a while and is waiting on author edits. I would be happy to look at it if that'd be okay?
