### ISSUE TITLE
resizing OL small and then wide w/ text in searchbox causes dropdown to trigger

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#780]
The primary searchbox in our topmost header bar on OpenLibrary.org (which also contains our logo) experiences problems when the the width of the website is changed.

**Steps to reproduce:**
1. Load OpenLibrary.org on Desktop (not a mobile device) with a browser opened to > 800px
2. Enter the text "Lord of the Rings" into the primary search box and **do not** press enter. You should see `realtime instant results` appear
3. Click outside of the primary searchbox and the `realtime instant results` should disappear / hide
4. Resize the browser window < 400px.
5. Resize the browser window back to > 800px
6. An error is occuring where The `realtime instant results` suddenly become shown again

**Hypothesis:**
There is code in `openlibrary/plugins/openlibrary/js/ol.js` which handles how the primary searchbox should behave when the window is resized. This may accidentally be showing `realtime instant results` when it shouldn't be.

**Comment by rohitjain00** [comment]
Is this still active? if it is please provide description for the issue

**Comment by mekarpeles** [comment]
Hi @rohitjain00! I've updated the original comment to be more descriptive

**Comment by rohitjain00** [comment]
@mekarpeles  Should after increasing the screen size the state of search result return to its original state or the results be closed always?

**Comment by rohitjain00** [comment]
I think the text written inside the text box should be cleared once the input bar for searching has stop showing
