### ISSUE TITLE
Misleading German translation on My Books page

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7813]
A German translation on the _My Books_ page and in the drop-down menu beneath the borrow button is misleading.

The entry _Currently Reading_ was translated as _Aktuell verliehen_ . "Aktuell verliehen" means "This book was lent to a patron and not yet returned". (The state _aktuell verliehen_ would be correct from a library's point of view: If I borrowed the book to read it, no one else can. But everything else on the My Books page is from an user's point of view, not from the library's point of view.)

### Evidence / Screenshot (if possible)
![Screenshot 2023-04-20 at 22-45-12 My Books Open Library](https://user-images.githubusercontent.com/36878944/233486828-534f6a48-003f-4588-8d08-6a0e32c33f24.png)
![Screenshot 2023-04-20 at 22-44-46 Meine Bücher Open Library](https://user-images.githubusercontent.com/36878944/233486860-650f37e7-6c1c-416c-b772-4de5470a7f9f.png)

![Screenshot 2023-04-20 at 23-07-34 Speak (2000 edition) Open Library](https://user-images.githubusercontent.com/36878944/233487974-bec8c95e-397a-4e0e-bac8-829ebdeac5af.png)
![Screenshot 2023-04-20 at 23-08-29 Speak (2000 edition) Open Library](https://user-images.githubusercontent.com/36878944/233488089-4d61e33b-58cd-49d9-9bd7-0c699a232347.png)

### Relevant url?

https://openlibrary.org/account/books/currently-reading

### Steps to Reproduce

1. Go to the "My Books" page
2. Switch language to German
3. Have DeepL or Google translate the text "Aktuell verliehen"

* Actual: I was very confused and wondered how I could enter books into OpenLibrary to lent to somebody else
* Expected: I can easily find the books I am reading at the moment

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?** Firefox 112.0 (64-Bit)
- **Operating system?** OpenSuse Tumbleweed
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Replace "Aktuell verliehen" with "Lese ich gerade" (informal) or "Derzeitige Lektüre" (formal). 

German does not have a gerund form of verbs, hence the term cannot be translated verbatim. Both translations transport the same meaning as "currently reading", just on different linguistic levels.

**Comment by onnotasler** [comment]
@cdrini Ok, that was a little confusing, but I think I got it done: https://github.com/internetarchive/openlibrary/commit/c40033dc0365dc9e2d5d8a7525499c6014d11b1e

**Comment by cdrini** [comment]
Nice @onnotasler ! That looks I think correct! You just have to click "Create pull request" on https://github.com/internetarchive/openlibrary/compare/master...onnotasler:openlibrary:patch-1 :)
