### ISSUE TITLE
Discovereads ID does no longer exist

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7823]
The Discovereads ID does no longer exist, it was merged into Goodreads in 2011 and discovereads.com does no longer resolve.

The name has been taken over by some libraries, but their programmes are not compatible with our discoverreads ID.

### Relevant url?

https://openlibrary.org/config/edition

### Details

label: Discovereads
name: discovereads
notes:
url: http://www.discovereads.com/books/@@@
website: http://www.discovereads.com

**Comment by cdrini** [comment]
labelled as discontinued :+1:
