### ISSUE TITLE
URL for Cornell University ID changed, also name confusion

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7825]
There are two problems with the ID for Cornell University.

1. Both Entries for Cornell University are labelled Cornell University ecommons, which makes it impossible to distinguish between them.
2. The URL for both identifiers are outdated.

#### Broken
label: Cornell University ecommons
name: cornell_university_online_library
notes:
website: http://ecommons.library.cornell.edu/handle/1813/11665

label: Cornell University ecommons
name: cornell_university_library
notes:
website: https://newcatalog.library.cornell.edu/catalog/@@@

#### Corrected
label: Cornell University ecommons
name: cornell_university_online_library
notes: Cornell's Digital Repository
website: https://ecommons.cornell.edu/
url: https://hdl.handle.net/1813/@@@

(Example: https://hdl.handle.net/1813/113105)

label: Cornell University Library Catalog
name: cornell_university_library
notes: Cornell University Library Catalog
website: https://www.library.cornell.edu/
url: https://catalog.library.cornell.edu/catalog/@@@

(Example: https://catalog.library.cornell.edu/catalog/15278099)

### Related files

If this bug is solved, #6108 can be closed, too.

**Comment by cdrini** [comment]
Fixed :+1:
