### ISSUE TITLE
ID for Harvard University Library changed

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#7826]
The URL for the ID for Harvard University Library changed.

### Broken
label: Harvard University Library
name: harvard
url: https://hollis.harvard.edu/primo_library/libweb/action/display.do?doc=HVD_ALEPH@@@
website: https://library.harvard.edu

### Corrected
label: Harvard University Library
name: harvard
url:  https://id.lib.harvard.edu/alma/@@@/catalog
website: https://library.harvard.edu

### Related files

https://openlibrary.org/config/edition

**Comment by cclauss** [comment]
Do we want `@@@` in the search bar when this operation is complete?
<img width="271" alt="Screenshot 2023-04-23 at 12 52 00" src="https://user-images.githubusercontent.com/3709715/233835706-ac23abe2-4ad6-4040-810c-d5c7639b14c0.png">

**Comment by onnotasler** [comment]
This is what the Havard library offers as permalink, with an easily found identifier.

Alternatively, we could use https://hollis.harvard.edu/primo-explore/fulldisplay?docid=01HVD_ALMA@@@, but I am not sure how stable that is and it is more difficult to find the correct identifier.

![grafik](https://user-images.githubusercontent.com/36878944/233837497-b63f18de-a834-415d-bc00-7c727b6378dc.png)

**Comment by hornc** [comment]
I typed this out from the image above because I wanted to see a live example, here it the permalink as a link:

https://id.lib.harvard.edu/alma/990012548240203941/catalog

**Comment by mekarpeles** [comment]
Fixed here:
https://openlibrary.org/config/edition?v=942
