### ISSUE TITLE
[X] no longer removes author from list

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7855]
The [x] next to the list name on an author profile no longer functions as a removal mechanism, instead, it links to the list as if it is part of the list name. The only way to remove an author from a list is to now go to the list page, find it on the list (which may be many pages long), and remove it from there.

### Evidence / Screenshot (if possible)
<img width="389" alt="Screenshot 2023-05-10 at 09 34 21" src="https://github.com/internetarchive/openlibrary/assets/17739465/77fcd12a-4bf7-4d50-a460-a402134a2ef0">

### Steps to Reproduce

1. Go to ...an author page
2. Do ...add to a list and then try to remove if from the list using the [x].

* Actual: Navigates to the list.
* Expected: Removal from the list.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by scottbarnes** [comment]
@seabelis, I'll submit a PR for this once since it appears I caused it. Woe is me.
