### ISSUE TITLE
Fetch subjects in JSON

### ISSUE THREAD

**Issue by SinaBYR** [internetarchive/openlibrary#7882]
### Describe the problem that you'd like solved
It'd be very useful if we could have a `/subjects.json` endpoint which would return all subjects in JSON format.

**Comment by tfmorris** [comment]
"all subjects" isn't a very good use case for the API. That sounds like something that would be better processed from the bulk data dumps.

If, on the other hand, you wanted the top N subjects, sorted in descending order by count of works, you could use the Search API, provided N isn't too large.  It's poorly documented, but you can use, for example, the following query to get the 2nd 10 most used subjects.

https://openlibrary.org/search/subjects.json?q=%2A&limit=10&offset=10

There are a number of limitations to the existing subject design - they're not internationalized, minor spelling variations are catalogued separately, they aren't related to similar subjects in any way, etc, etc.

https://openlibrary.org/search/subjects.json?q=%22history%20and%20criticism%22
https://openlibrary.org/search/subjects.json?q=%22histoire%20et%20critique%22
https://openlibrary.org/search/subjects.json?q=key:/subjects/history_and_criticism
https://openlibrary.org/search/subjects.json?q=key:/subjects/histoire_et_critique

Note that there's been talk (#2819) of implementing subjects as first class objects in the data model, which would likely change all of this.

**Comment by SinaBYR** [comment]
Thanks for the insights!
Having access to "top N subjects" will do it for me now, but I may need access to all subjects at some point in the future, so as you mentioned using bulk data dumps would be a better idea.
