### ISSUE TITLE
Code complexity: `load()` in `catalog/add_book/__init__.py` is too complex

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#7884]
A continuation of #7883

The `load()` function in `openlibrary/catalog/add_book/__init__.py` is too complex...
https://github.com/internetarchive/openlibrary/blob/112b89b2b5a37262664cd0f7647939a670e04833/openlibrary/catalog/add_book/__init__.py#L681-L864
```
openlibrary/catalog/add_book/__init__.py:681:5: C901 `load` is too complex (41 > 28)
openlibrary/catalog/add_book/__init__.py:681:5: PLR0912 Too many branches (42 > 22)
openlibrary/catalog/add_book/__init__.py:681:5: PLR0915 Too many statements (106 > 70)
```
Tasks:
* [x] In a separate pull request, add ___a lot___ of tests for this function ___without___ modifying the function.
* [ ] ___After___ the first pull request has been merged, in a separate pull request:
    * [ ] In `pyproject.toml` remove line `"openlibrary/catalog/add_book/__init__.py" = ["C901", "PLR0912", "PLR0915"]`
    * [ ] Modify the `load()` function so that it passes the tests created in step 1 as well as all `ruff` tests.

**Comment by scottbarnes** [comment]
This function and I are in a codependent relationship. I'd like to work on this.
