### ISSUE TITLE
Code complexity: `read_subjects()` in `catalog/marc/get_subjects.py` is too complex

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#7886]
A continuation of #7883

The `read_subjects()` function in `openlibrary/solr/update_work.py` is too complex...
https://github.com/internetarchive/openlibrary/blob/112b89b2b5a37262664cd0f7647939a670e04833/openlibrary/catalog/marc/get_subjects.py#L83-L171
```
openlibrary/catalog/marc/get_subjects.py:83:5: C901 `read_subjects` is too complex (41 > 28)
openlibrary/catalog/marc/get_subjects.py:83:5: PLR0912 Too many branches (40 > 22)
openlibrary/catalog/marc/get_subjects.py:83:5: PLR0915 Too many statements (74 > 70)
```
Tasks:
* [ ] In a separate pull request, add ___a lot___ of tests for this function ___without___ modifying the function.
* [ ] ___After___ the first pull request has been merged, in a separate pull request:
    * [ ] In `pyproject.toml` remove line `"openlibrary/catalog/marc/get_subjects.py" = ["C901", "PLR0912", "PLR0915"]`
    * [ ] Modify the `read_subjects()` function so that it passes the tests created in step 1 as well as all `ruff` tests.

**Comment by hornc** [comment]
I think the first step should be figuring out where this function is used, and is it part of any current import (or other) path.

There are a number of "get_subjects" functions in the code, at least one is deprecated. 

Here's what I've found, which confirms it _is_ used in the current import path:

openlibrary/catalog/marc/parse.py  imports  `subjects_for_work` 

https://github.com/internetarchive/openlibrary/blob/395c3a30c4902c3b72bfa6ea1cb6ab41a10aa857/openlibrary/catalog/marc/parse.py#L4

Which is used in 

https://github.com/internetarchive/openlibrary/blob/395c3a30c4902c3b72bfa6ea1cb6ab41a10aa857/openlibrary/catalog/marc/parse.py#L713

When the imported build an edition for importing.

`openlibrary.catalog.marc.get_subjects.subjects_for_work()` calls `get_subjects`:

https://github.com/internetarchive/openlibrary/blob/112b89b2b5a37262664cd0f7647939a670e04833/openlibrary/catalog/marc/get_subjects.py#L174-L184

**Comment by scottbarnes** [comment]
In case it's any help, here's a current a test coverage report showing the state of executed (green) vs. not executed (red) lines in `get_subjects()`:
![image](https://github.com/internetarchive/openlibrary/assets/26524678/826179c1-8979-4bec-9603-650d0bef5485)
