### ISSUE TITLE
Add validation to checks to book editing fields

### ISSUE THREAD

**Issue by wildemberg-sales** [internetarchive/openlibrary#7889]
### Describe the problem that you'd like solved

First I must inform you that they are for two features of the book editing system, which may end up generating a bigger problem in the future.
Both in the "edit description" part and in the "other titles" part, there is a message above that informs some restrictions so that the user does not create something wrong, but, the system does not contain a check so that these functionalities are not inserted contrary to the restrictions.

### Proposal & Constraints

The proposal to solve these problems would be to add a two functionalities, one for each input, making such a check so that the user does not leave the restrictions and ends up entering information that should not go to the database.
The system does not rely on checks of this type in the editing part of editing, but it could make this restriction clearer within the interface, and develop an error message every time the condition is broken

### Additional context

In the description section:
![image](https://github.com/internetarchive/openlibrary/assets/92035272/d6f63f19-f7e4-418b-a76c-64ee10b3675c)  

In the other titles section:
![image](https://github.com/internetarchive/openlibrary/assets/92035272/7f106767-34ce-4595-9bec-14190550b234)

### Stakeholders

@gojomo 
@anandology

**Comment by seabelis** [comment]
These are not major issues. The descriptions are subject to change. Just because the description of the work and edition are matching right now, doesn't mean someone won't change one or the other tomorrow. There is no harm if they are the same.

**Comment by jimchamp** [comment]
Closing this, as per https://github.com/internetarchive/openlibrary/issues/7889#issuecomment-1580077866
