### ISSUE TITLE
Make anonymous users complete a CAPTCHA for any/all edits

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#79]
Anand,

Over the last 2 days, we've been whacking moles (blocking random IPs, reverting edits) and have decided it's time to introduce CAPTCHAs for any/all anonymous edits.

Raj suggested you're the man for this feature. 

So, can you please add a CAPTCHA box above all SAVE buttons for not-logged-in users? 

---

The logical follow-on from this will be to add a CAPTCHA for new account generation, so, if you're in the mood, feel free to do that too.

If you can work on this feature and try to deploy it within the next week, that'd be perfect.

By the way, it looks like anonymous edits will be shut down when we transfer to the archive.org common backend system. This is a stop gap.

**Comment by hornc** [comment]
Currently "Only logged users are allowed to modify records on Open Library.", so resolved.
