### ISSUE TITLE
Punctuation in author name results in 0 matches for /edit author dropdown

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#790]
@mekarpeles @hornc Try this one on for size: 
https://openlibrary.org/books/OL25964714M/The_Wrinkle_In_Time_Quintet/edit
Note that the author name, "Madeleine L'Engle", contains an apostrophe. The dropdown shows no matches and so suggests creating a new author. Remove the apostrophe and suddenly it finds a match with 133 books, with the apostrophe shown for the match!  If this is common to all authors with an apostrophe, it will be *very* widespread, and many of them will have multiple single-book author records to merge: 
https://openlibrary.org/search/authors?q=Madeleine+L%27Engle&mode=everything
(I did a few before realizing the pattern here, then stopped.)

**Comment by LeadSongDog** [comment]
Similar examples:
https://openlibrary.org/search/authors?q=D%27Annunzio

**Comment by tfmorris** [comment]
A similar issue occurs with authors with hyphenated names, e.g. "James Crichton-Browne" which doesn't match anything while searching for "James Crichton Browne" does match the hyphenated name.

I think I've also seen "Smith, John F." (made up example) fail to match until the trailing middle initial was removed, but don't have an actual example of that.

**Comment by tfmorris** [comment]
It looks like the underlying issue is with the autocomplete endpoint which works differently than normal search https://openlibrary.org/authors/_autocomplete?q=james%20crichton-browne

The problem is that the query is being tokenized differently than the search index causing crichton-browne to be treated as a single token in the query, but two tokens in the index. We can fix the immediate problem, by putting the query string in quotes and not escaping special characters or substituting spaces for them, but I suspect that the autocomplete can be improved with a little more investigation (which I don't have time for at the moment).

The offending code is here: https://github.com/internetarchive/openlibrary/blob/85dd7cd522d34f7e06e6c777e437b64becfcc0da/openlibrary/plugins/upstream/addbook.py#L848

**Comment by LeadSongDog** [comment]
Most users will be unaware of the illegible distinction between the https://en.wikipedia.org/wiki/Hyphen and the https://en.wikipedia.org/wiki/Hyphen-minus (indeed, many will not even distinguish the various kinds of https://en.wikipedia.org/wiki/Dash and often may just use a white space in lieu). Robust implementation should handle all the likely typed variations while still finding the intended target. In this example, https://viaf.org/viaf/30318770 uses the hyphen-minus.  

Weirdly, Wikipedia's manual of style tells editors to use the hyphen for https://en.wikipedia.org/wiki/Surname#Compound_surnames but in practice biographies use the hyphen-minus instead. I've asked for clarification of the guidance there, but it has only peripheral import here.

**Comment by guyjeangilles** [comment]
This is still a bug.

@tfmorris @cdrini @hornc Are one of you willing to be assignee for this issue? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
I'll make sure this works correctly in the new Solr.

**Comment by tfmorris** [comment]
Another example: "Elaine N. Marieb" fails to autocomplete to "[Elaine Nicpon Marieb]( https://openlibrary.org/authors/OL24712A/Elaine_Nicpon_Marieb)" even though that exact name is listed in the AKAs.

**Comment by LeadSongDog** [comment]
Most of this seems to work on prod now (woohoo), but the 26 Mar 2018 @cdrini entry still has some echos. https://openlibrary.org/search/authors?q=name%3A%28Crichton-Browne%29 and https://openlibrary.org/search/authors?q=name%3A%28Crichton+Browne%29 give different, overlapping results.

**Comment by mekarpeles** [comment]
I believe this is now closed. Tested on edit UI w/ Madeleine L'Engle

**Comment by tfmorris** [comment]
This got fixed within the last 2-3 weeks.

**Comment by tfmorris** [comment]
@mekarpeles This should be re-opened (see above).

**Comment by tfmorris** [comment]
@mekarpeles Please reopen. I've consolidated the failure examples from #4800, #6016, and  #6088:
* Abduʼl-Bahá (from WorldCat #6016)
* Abduʼl-Bahá (name in OpenLibrary)
![Screen Shot 2023-02-01 at 9 48 54 AM](https://user-images.githubusercontent.com/82178/216076937-ab2dc3ed-515d-40cf-8b9c-6f264a49d3be.png)
* John Kabat-Zinn (#4800)
![Screen Shot 2023-02-01 at 9 43 45 AM](https://user-images.githubusercontent.com/82178/216077101-1b8ccc49-ed2d-4e18-9ba0-5a979bcdca5e.png)
* Agnieszka Lingas-Łoniewska (#6088)
![Screen Shot 2023-02-01 at 9 42 20 AM](https://user-images.githubusercontent.com/82178/216077142-a94325eb-29f7-40e6-8c0d-cbddd3f87b3b.png)


And a new one I've noted recently:
* Smith, Mrs. (the form without the trailing period works, ie Smith, M
![Screen Shot 2023-02-01 at 9 50 11 AM](https://user-images.githubusercontent.com/82178/216076831-3c4cc13e-d320-4e0e-8d98-666ff12c69ba.png)
rs)

![Screen Shot 2023-02-01 at 9 49 49 AM](https://user-images.githubusercontent.com/82178/216076885-b8978295-21cf-4530-af34-36179c28e2f3.png)
