### ISSUE TITLE
IA sync of orphaned editions fails with incorrect error msg.

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#792]
Syncing a orphaned edition via

/admin/sync?edition_id=OL7520207M

fails with the (incorrect) message:

```
{
error: "No qualifying edition"
}
```

Example:
https://openlibrary.org/books/OL7520207M/A_Mother's_Gift

https://openlibrary.org/admin/sync?edition_id=OL7520207M

1) Correct the error message in this case to alert what has happened
~2) Possibly sync only the `openlibrary_edition`? Would this cause more problems than it solves?~

Is the fix to deal with all the orphaned editions before syncing with IA?

Relates to #732 

**code at**  https://github.com/internetarchive/openlibrary/blob/8a303504065a65c45b930df3fcca430f948762b0/openlibrary/catalog/add_book/__init__.py#L287

**Comment by guyjeangilles** [comment]
Assigning @hornc per slack discussions because this issue has his tags
