### ISSUE TITLE
Goodreads imports fail horribly if no file is selected

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#7924]
If a patron attempts to import their Goodreads library without first selecting an input file, they are redirected to an error page with little useful information.

### Relevant url?

https://openlibrary.org/account/import

### Steps to Reproduce

1. Go to https://openlibrary.org/account/import
2. Click the "Load Books" button without first selecting an input file.

* Actual: Redirected to error page
* Expected: Prompted to choose a file

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add `required` attribute to the file `<input>`

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/import.html

**Comment by sbwhitt** [comment]
@jimchamp Picking this up. Seems like it is as simple as just adding required to the file input.
