### ISSUE TITLE
Some user-created books created with lccn=[null], causing rendering error

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7943]
Unclear how in the flow this is happening, but it's been happening for a while. Likely related to the add book form? Maybe it allows an empty LCCN? Not happening super often though, there were 106 total such errors in the db.

### Relevant url?
Eg https://openlibrary.org/books/OL47807201M/Mesopotamian_Coronation_and_Accession_Rites?v=1 (Note since fixed)

**Comment by mekarpeles** [comment]
In `catalog.add_book` import path, if a record has lccn of [] or [''] or [None] then discard the value?
