### ISSUE TITLE
Improve normalization of subjects during import

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#795]
https://github.com/internetarchive/openlibrary/blob/966eb0919e4c56c9d310d348fec5fc47edb6a23b/openlibrary/catalog/importer/add_source_records.py#L86

This list seems entirely arbitrary. It has Jr but not Sr, Capt not Maj nor Lieut nor Col nor Gen nor Adm, M nor Miss not to mention the non-English equivalents. 

It's also not entirely clear to me just how it is used.

**Comment by tfmorris** [comment]
Has this caused any observed problems? If not, I propose closing it.

It has nothing to do with author names. The list is an exception list for when trailing periods (.) should *not* be removed from subject entries, so "World History." becomes "World History" but "Smith, John, Dr." remains unchanged.

**Comment by LeadSongDog** [comment]
Sorry @tfmorris, I missed your Nov 22 question.  I think the introduction of elastic search has mooted the question: the trailing period no longer changes the hit count.
