### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#796]
re: John Gilmore

The top of the page now says "New to Open Library?  Learn More" and leads to the FAQ.  But it looks like the FAQ hasn't been reviewed recently; the last edit was a year ago.

The numbers of books available are probably old. (we should link to a stats page w/ the actual numbers)

Auth has changes -- "I wrote a book, and I have it in digital form.  Can I make it readable on Open Library?" answer says you need both an IA login and an OL login, but these have been unified...

**Comment by salman-bhai** [comment]
@mekarpeles should I work on this?

**Comment by salman-bhai** [comment]
@mekarpeles anything that can be done on this one?

**Comment by LeadSongDog** [comment]
Any number of books given would certainly be very wrong. The number of duplicate/overlapping records for editions can't really be quantified with any real degree of accuracy. We can't even say how many authors, for the same reason.  Stale cache messes up the reported results anyway. Lots of work records with no edition linked still show one or more as their edition count.  It's pretty discouraging that this doesn't get addressed.

**Comment by LeadSongDog** [comment]
The counts (of authors, works, and editions) simply can't be accurately reported until the data itself can be cleaned up. We could, however, state how many such _records_ are in OL. There are many other errors in the FAQ that could be quickly remedied, starting with the account info.

**Comment by guyjeangilles** [comment]
While the FAQ isn't on the homepage anymore, it still has all the above problems noted in this thread. @mekarpeles defaulting to asking you to be assignee for this issue. Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by BrittanyBunk** [comment]
I see issues with some FAQs sections that aren't detailed enough. Bit to add in is in []'s and if it has no words in it, the wording was removed.
1. I have an ebook that I'd like to donate to Open Library. How can I do that?
You can only donate books that you own the rights to yourself [or is in the public domain]
2. How can I contribute information to Open Library?
You can help build the Library. All you need to do is hit the EDIT button[, create an account or sign in,]...using Open Library data. [For those that aren't, look at the ID Numbers options in the drop down menu. Seek out the websites listed, find the IDs for books there, and then copy/paste it into corresponding location in the Open Library.]
3. Can you tell me more about a particular book?
No[, but that's where you come in]. Everything we know is already on our site[] and everyone [] is encouraged to enrich a record with additional information from which we can all benefit [whenever and wherever it's able to be added].
4. Can you send me a copy of a book?
No[, b]ut, you can download any ebook that we have available as full text in a variety of formats. Currently we offer over 1.7 million public domain books in PDF, ePub, DAISY, DjVu and ASCII text through our affiliation with the Internet Archive. [You can print out these public domain books using files. See https://youtu.be/pXoHC2D15hM?t=262]
5. Can I buy books from Open Library?
No[, but you can sponsor one.] <- add sponsor link
6. I have a book that I think might be worth something. Can you tell me what it's worth?
Unfortunately, we can not. We have no expertise in the valuation of books. You should try to find a website that specializes in used or rare books [or try to find the price somewhere on the book itself].
7. I found a very old book in my basement. Do you want it?
You're welcome to donate books to the Internet Archive through our Book Drive program. [You can also scan and add it in to the Internet Archive and link its ID to the edition's page on the Open Library.]
8. Where can I see what other people are up to?
Add in a 3rd bullet saying:[View the '[edit book](https://openlibrary.org/recentchanges/edit-book#humans)' section on recent changes]

**Comment by PriyavKaneria** [comment]
I would like to work on this issue. Please assign this to me.

**Comment by mekarpeles** [comment]
FAQs have been updated by the policy team
