### ISSUE TITLE
Search index has stopped updating (again)

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7977]
No updates to author records, including merges and name changes have been indexed in the last 20 hours.

### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/82178/22bc258f-da07-48ac-ba18-f010e5eece5f)

### Relevant url?
https://openlibrary.org/search/authors?q=E++Hontan%CC%83o%CC%81n
https://openlibrary.org/authors/OL4111823A

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini @mekarpeles

**Comment by cdrini** [comment]
We had an issue with the server running out of storage due to #7983 . I've gzipped all the logs and everything is now back to normal. Solr updater is catching up and should be done in a few hrs.

**Comment by tfmorris** [comment]
@cdrini How many hours is "a few"? it's been 20 hours since you closed this and the example search still doesn't return the given author record.

**Comment by cdrini** [comment]
Ah solr updater seems to have more errors when it's catching up over bulk edits; so there are probably some edits it didn't correctly catch up on. It is handling all incoming edits correctly now, so you should be able to edit the author to have the fix go through! I'll create an issue for the underlying problem.
