### ISSUE TITLE
Convert incorrect edition to its own book

### ISSUE THREAD

**Issue by Feline17** [internetarchive/openlibrary#7978]
### Question

How do I convert incorrect edition to its own book?

### Additional context

There are many books in this series. 
But they're called editions of the book instead.
https://openlibrary.org/works/OL6046917W/Felicity_Wishes?mode=all

**Comment by cdrini** [comment]
@seabelis would you be able to help on this one?

**Comment by bicolino34** [comment]
![Screenshot_20230627_230634_Firefox Nightly.jpg](https://github.com/internetarchive/openlibrary/assets/58372007/be16c0a7-3bf7-4f47-98a6-106a339b67ad)

There is such option on the edition page, but as far as I know, this is librarian-only feature

**Comment by LeadSongDog** [comment]
This example, like many others, needs several extra steps.
First, scan through the many title matches: 
https://openlibrary.org/search?q=title%3A+%22Felicity+wishes%22&mode=everything

0. Delete the non-books (abandoned, 10 copy counter pack, cover mount, calendar, diary)
1. The author records for "Emma Thompson" need to be deduped/merged.
2. *Felicity Wishes* is a series title: it needs first to be applied to each edition. 
3. Work titles and Edition titles need to be corrected. Try not to create anew work record unless there clearly is not an extant matching one.
4. Works need to be deduped/merged.

**Comment by seabelis** [comment]
I can work on it. Thanks.

**Comment by mekarpeles** [comment]
I'm assuming this is 1-off and can be closed?
