### ISSUE TITLE
New workflow possible by using whole-shelf spine images

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#798]
We are missing out on a great opportunity. Consider that a 4K photo of a 12" section of library shelf yields 300dpi. 

In a major institution one can capture the spines of a (roughly) ordered group of editions with adjacent shelfmarks or classifications (either Dewey or LC in most cases). For most libraries, the spines in an image will be marked with those classifications or corresponding shelfmarks. A photo of a shelf could (with suitable code) be automagically sundered into an ordered set of single-spine photos. These in turn could be paired to the imaged library's shelfmark and via that library's catalog thence to the OL edition record. 

Done properly this capture could be made as easy as strolling down the aisles with a GoPro. For really large libraries, one might want a pole with three or four cameras at different heights to capture entire shelf racks, but let's walk before running.

For partner libraries this could greatly facilitate the finding and prioritizing the relatively few volumes most worth scanning (i.e. the ones not already present in OL/IA).

In the longer term, librarians could be furnished with augmented-reality tools for quickly finding misplaced or missing volumes, a perennial thorn in the side.

**Comment by LeadSongDog** [comment]
It looks like part of this is addressed in https://github.com/leahbrumgard/ShelvedApplication

**Comment by mekarpeles** [comment]
Tagging @conditionsofexistence who leads development on our scanning software (who can represent these ideas to the digitization team). Thanks @LeadSongDog for these suggestions!

**Comment by guyjeangilles** [comment]
@conditionsofexistence @mekarpeles What's the current status of this scanning initiative?

**Comment by tfmorris** [comment]
While an interesting idea, this doesn't really sound related to the OpenLibrary web site or associated metadata.

**Comment by LeadSongDog** [comment]
The principal point is that it would help to fill in the metadata blanks. Shelving normally is in a sequence that reflects either classification or (for fiction) author name. A nonfiction book shelved between two others will normally have subject matter similar to both. Hence "shelved_with[OLID]" would be helpful information when no other subject metadata is at hand.

**Comment by mekarpeles** [comment]
Closing as out of scope for Open Library
