### ISSUE TITLE
Export star ratings only lists IDs and not titles

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7985]
Patrons do not find the IDs useful and request titles and authors are included in exported star ratings data.

### Describe the problem that you'd like solved

Include authors and titles in exported star ratings data.

**Comment by rebecca-shoptaw** [comment]
I know this is quite an old issue by now, but I think it's a good idea to fix and should hopefully be straightforward -- just making the `generate_star_ratings` function implementation more like the `generate_reading_log` one. Would be happy to work on it if we'd still like the change to be made!
