### ISSUE TITLE
Make web1/2, home0 infobase logs ephemeral

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7991]
Do we need these logs to persist long-term? They generally just record errors/access logs, which we likely don't need for longer than ~1-2w. Storing these inside the docker containers would have them be cleared out every deploy, and simplify some of our config.

Is there any reason we might need to keep these logs around, @mekarpeles ?

This would also solve:
- https://sentry.archive.org/organizations/ia-ux/issues/324142 (PR #7887)
- #7983 - https://sentry.archive.org/organizations/ia-ux/issues/362464/

### Related files

Changes:

```diff
diff --git a/etc/infobase.yml b/etc/infobase.yml
index 7393837..95bb519 100644
--- a/etc/infobase.yml
+++ b/etc/infobase.yml
@@ -27,8 +27,8 @@ cache:
         - "ol-mem1:11211"
         - "ol-mem2:11211"

-errorlog: /1/var/log/openlibrary/infobase-errors
-writelog: /1/var/lib/openlibrary/infobase/log
+errorlog: /var/log/openlibrary/infobase/errorlog
+writelog: /var/log/openlibrary/infobase/writelog

 logging_config_file: /olsystem/etc/logging.ini
 ```

```diff
diff --git a/compose.production.yaml b/compose.production.yaml
index fc7049baa..75e6cff08 100644
--- a/compose.production.yaml
+++ b/compose.production.yaml
@@ -147,8 +147,6 @@ services:
       - INFOBASE_CONFIG=/olsystem/etc/infobase.yml
     volumes:
       - ../olsystem:/olsystem
-      - infobase-writelog:/1/var/lib/openlibrary/infobase/log
-      - infobase-errorlog:/1/var/log/openlibrary/infobase-errors
   web_haproxy:
     profiles: ["ol-www0"]
     image: haproxy:2.3.5
@@ -310,6 +308,4 @@ secrets:
     ssl_certificate_key:
       file: /opt/.petabox/openlibrary.org.nopassword.key
 volumes:
-    infobase-writelog:
-    infobase-errorlog:
     archive-webserver-logs-data:
```

### Stakeholders
@cclauss @mekarpeles

**Comment by cclauss** [comment]
Infobase needs volume mount

**Comment by cdrini** [comment]
plan
On ol-home0:

Move all but last month to new location /1
Ensure perms are the same

Change infobase.yml
Change compose.production.yaml

stop infobase

Copy over last month

start infobase (will now have new settings)

**Comment by cdrini** [comment]
Nice! Those changes look good ; we should be good to go through the live migration, _then_ we'll be able to merge. Please don't merge yet!

**Comment by cdrini** [comment]
Closed by https://github.com/internetarchive/olsystem/pull/184
