### ISSUE TITLE
Some patrons reporting loan errors

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8001]
A number of patrons have reported errors when trying to borrow books. I can borrow the books under my account, but if I log in with their accounts, I see the error.
### Relevant url?

Sentry issue: https://sentry.archive.org/organizations/ia-ux/issues/46145
```
HTTPError (/books/.*)/borrow
400 Client Error: Bad Request for URL:
    https://archive.org/services/loans/loan/?action=borrow_book&identifier=courtofmistfury0000maas
Events: 16k
First Seen: a year ago
```
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cclauss

**Comment by mekarpeles** [comment]
We believe this may be because of intended changes made to the underlying system. If the error messages are unclear, we may wish to open a separate issue to clarify
