### ISSUE TITLE
"Log in as user" feature does not reset printdisabled cookie

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8005]
Logging in as a user via the admin UI for debugging does not reset the printdisabled cookies, causing some weird issues.

### Steps to Reproduce
1. Log in with admin, printdisabled account
2. "Log in as user" of another user account, not printdisabled accout

* Actual: pd=1 still set in cookies
* Expected: pd should be set to what makes sense for the user.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by Eds-Dbug** [comment]
I would like to take up this issue.
