### ISSUE TITLE
Want to read button looks weird when logged out 

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8009]
### Evidence / Screenshot (if possible)

When logged out:
<img width="666" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/10c6dcf8-9728-4ae5-b596-aabeced2bfe9">

When logged in:
<img width="805" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/9351b09a-e6f3-4dc0-b732-afdc217f8300">

### Relevant url?
https://openlibrary.org/search?q=fishing&mode=everything

### Steps to Reproduce

1. Go to the website when logged out and search for any book

* Actual: Looks like a ghost
* Expected: Looks like a button

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF/Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by jimchamp** [comment]
Working on refactoring this component now, so assigning myself.
