### ISSUE TITLE
OL Captcha (google v1) sunset end-of-month

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#802]
@neyer reported that our captchas are still using google's v1 API. This is getting sunset and we'll need to implement a different solution by the end of the month

**Comment by salman-bhai** [comment]
@mekarpeles I'll work on this one! 

But can you let me know whether I should register for a new key for the website or you'll do that from your end and I have to implement it in the code!

**Comment by mekarpeles** [comment]
We should be able to test it with a fake localhost key and then switch keys -- reCAPTCHA V2 seems like the right direction to go :)

**Comment by tfmorris** [comment]
I agree that the test keys should be usable for development. The key should be configurable so that developers can use their own or revert to the test key.

Here's a blog post about migration which might help:
https://blog.sendsafely.com/migrating-to-googles-nocaptcha-recaptcha

**Comment by salman-bhai** [comment]
@tfmorris thanks for the links!

**Comment by mekarpeles** [comment]
We're excited you're trying this one out @salman-bhai! Please let me know if you have any questions getting the Open Library developer instance up and running 🎉
