### ISSUE TITLE
Should we link to SwaggerUI in the API docs page?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8020]
### Question

Should we link to SwaggerUI in the API docs page?

Link to swagger API: 
https://openlibrary.org/swagger/docs

### Additional context

This was recently merged: https://github.com/internetarchive/openlibrary/pull/6018

### Issue resolution criteria

When we have an answer on if we should link to swaggerui.
If so we can create a new ticket (or just work form this one).

### Stakeholders

@cclauss

**Comment by mekarpeles** [comment]
Yes! Done

<img width="433" alt="Screenshot 2023-07-10 at 11 58 19 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/fc08b535-178d-4627-8eae-bcdcd8fcbdc0">
