### ISSUE TITLE
Add description to swagger api

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8021]
### Describe the problem that you'd like solved

We have this page: https://openlibrary.org/swagger/docs

We should say somethings like:
* These are still in development and may not be perfect
* If you'd like to contribute see https://github.com/internetarchive/openlibrary/blob/master/static/openapi.json
* Please do not use our APIs for bulk download

### Proposal & Constraints

We can edit these lines:
https://github.com/internetarchive/openlibrary/blob/3fcc46d7471a9561a3165e4db6c8de6aa7fc8778/static/openapi.json#L3-L6

Add files to the info object per the spec here https://swagger.io/specification/#info-object

### Additional context

Swagger was recently merged: https://github.com/internetarchive/openlibrary/pull/6018

### Stakeholders

@cclauss @jimchamp @scottbarnes @mekarpeles @cdrini

**Comment by cclauss** [comment]
This is a great suggestion!!  Let's also point them to https://openlibrary.org/developers/api or somehow merge both pages.  Please create a pull request so we can get feedback from others.  It is cool to see the `Try it!` functionality working...

**Comment by cclauss** [comment]
On https://openlibrary.org/swagger/docs#/default/read_api_books_api_books_get can we add some examples of or hints on how to create bibkeys?

**Comment by tfmorris** [comment]
It would be useful to warn that Swagger definition only includes a subset of the API and that they should see the API pages in the developer's docs for the full set.

**Comment by RayBB** [comment]
This is done.
New issue to update the docs #8474

**Comment by Realmbird** [comment]
So I change text in https://openlibrary.org/swagger/docs#/ with https://github.com/internetarchive/openlibrary/blob/master/static/openapi.json
Also which template is the API in

**Comment by RayBB** [comment]
@Realmbird yes

**Comment by Realmbird** [comment]
Ok
