### ISSUE TITLE
Misparsing publication year from dates

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#806]
I suspect this is not correct:
https://github.com/internetarchive/openlibrary/blob/846da3e48bb4a768dc51e8003ec09a66fe94dc9b/openlibrary/solr/update_work.py#L461

In any case, I am certain that this result is wrong:
![pub year](https://user-images.githubusercontent.com/11435431/36455598-d4f5887a-166e-11e8-8aa6-b11fff6771e4.png)

**Comment by guyjeangilles** [comment]
Nevermind #1440 (which is a duplicate of this issue) provided urls that display this problem. There is good discussion on how to fix this issue at #2039

**Comment by LeadSongDog** [comment]
The initial example was from https://openlibrary.org/works/OL1100007W/Le_tour_du_monde_en_quatre-vingts_jours

**Comment by tfmorris** [comment]
As I mentioned on #1440,

> The column is titles and publication information (year & publisher). From a quick glance at the code, I don't think it's even attempting to sort on publication date/year.

So just standardizing the date format is unlikely to be sufficient to fix this.

**Comment by LeadSongDog** [comment]
@tfmorris Agree that standardizing the format won't be sufficient, but it is necessary: sorting will be impossible until first there is a way to test A > B. That in turn requires a way to determine what A and B are.
