### ISSUE TITLE
'Ancient Greek' should be visible when typing 'Greek' when adding language to edition

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8077]
When adding a language, it is easy to miss the Ancient Greek option. If one starts typing 'Greek' it is not a visible option.
### Evidence / Screenshot (if possible)
<img width="328" alt="Screenshot 2023-07-10 at 21 18 27" src="https://github.com/internetarchive/openlibrary/assets/17739465/214f4a9b-d5fb-4d8a-adad-e66f5769ea29">
<img width="375" alt="Screenshot 2023-07-10 at 21 18 43" src="https://github.com/internetarchive/openlibrary/assets/17739465/1e5955ba-638b-4741-8beb-a39a45e2b57b">
<img width="293" alt="Screenshot 2023-07-10 at 21 18 34" src="https://github.com/internetarchive/openlibrary/assets/17739465/04b6cbae-602b-48db-b7b1-fdb889540b97">
(English added for comparison.)

### Steps to Reproduce

1. Go to ...any edition edit form
2. Do ... type 'Greek' and then type 'Ancient...'.

* Actual: Ancient Greed does not appear as an option when one types 'Greek.'
* Expected: Ancient Greek should be a visible option when one types 'Greek.'

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by pedrocampos0** [comment]
I'll work on this

**Comment by seabelis** [comment]
fixed
