### ISSUE TITLE
book list export as html not working

### ISSUE THREAD

**Issue by jacobandresen** [internetarchive/openlibrary#808]
Just tried pressing "export as HTML" on this list https://openlibrary.org/people/jacobandresen/lists/OL120215L/test

Nothing happened (blank screen).

**Comment by mekarpeles** [comment]
@jacobandresen, requesting you update this issue to remove the NOTE and add another issue if this is a feature you would like!

**Comment by jacobandresen** [comment]
done :)

**Comment by mekarpeles** [comment]
This list in question has a **work** not an edition; export only works for editions currently, I believe.

**Comment by tfmorris** [comment]
> This list in question has a **work** not an edition; export only works for editions currently, I believe.

I just tried exporting that list in all three formats and didn't get any error message (or export).

Surely if export is restricted to editions only, the users should be warned about that restriction.
