### ISSUE TITLE
Notify patron when entering an invalid LCCN

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8092]
Patrons should be notified when they enter enter an invalid LCCN into an edition's classifications.

The author of #7999 has (exceptionally skillfully and with great aplomb) stopped invalid LCCNs from breaking editions. However, the solution, though masterful in its execution, is wanting insofar as it silently drops invalid LCCNs to the floor, and patrons are not notified this has happened. We should avoid such undesirable behavior.

### Proposal & Constraints

We could notify patrons that an entered LCCN is invalid by:
1. bubbling up some error from the Python in `openlibrary/plugins/upstream/models.py` (see #7999); or
2. using JavaScript for validation and notify the patron that way.

It might make more sense to do it in JavaScript, _if_, for example, the validation could be copied from the ISBN validation. But perhaps there is some easy-to-use feature in `web.py` to do this.

Whatever it does, it should probably appear consistent with other validations on the page, such as that of ISBNs.

We should also prevent saving with an invalid LCCN, as opposed to ISBN, where we intentionally allow saving an invalid ISBN.

### Additional context

If this issue is addressed, the relevant comment in [`openlibrary/plugins/upstream/models.py`](https://github.com/internetarchive/openlibrary/blob/afe851000162a1ebe0602300a0172dafa49b825e/openlibrary/plugins/upstream/models.py#L335C3-L335C3) should be removed.

**Comment by sbwhitt** [comment]
Hey @scottbarnes, I'm interested in working on this. I previously worked on [this](https://github.com/internetarchive/openlibrary/pull/8148) solution for ISBN validation and figured that the validation in add-book.js [here](https://github.com/internetarchive/openlibrary/blob/83ba522d11e0074573c0850c5f9d8f0c661b5c79/openlibrary/plugins/openlibrary/js/add-book.js#L23) could be replaced with a generic `parseAndValidateIdentifier` function that branches into `parseAndValidateISBN` as well as a `parseAndValidateLCCN` function depending on the selected ID type (possibly including functions for any other ID types).

Similarly for [`edit.js/validateIdentifiers`](https://github.com/internetarchive/openlibrary/blob/83ba522d11e0074573c0850c5f9d8f0c661b5c79/openlibrary/plugins/openlibrary/js/edit.js#L186), could add in an LCCN validation portion.

Would these be the only two places requiring LCCN validation on the JavaScript side? Also, what kind of validation does LCCN need and is there any support for that already?

**Comment by scottbarnes** [comment]
Thanks for offering to take this on, @sbwhitt. :tada: I went ahead and assigned this to you. The approach you've proposed makes sense to me.

I *think* it's just the edition add and edit page where we'd need JavaScript LCCN validation.

I don't think there is currently any validation anywhere in JavaScript, but [`lccn.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/lccn.py) will normalize and validate an LCCN, so you could probably adapt that. There's also a comment with a link to a document that explains the LCCN namespace.

Please let me know if you have any questions!

**Comment by sbwhitt** [comment]
> Thanks for offering to take this on, @sbwhitt. 🎉 I went ahead and assigned this to you. The approach you've proposed makes sense to me.
> 
> I _think_ it's just the edition add and edit page where we'd need JavaScript LCCN validation.
> 
> I don't think there is currently any validation anywhere in JavaScript, but [`lccn.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/utils/lccn.py) will normalize and validate an LCCN, so you could probably adapt that. There's also a comment with a link to a document that explains the LCCN namespace.
> 
> Please let me know if you have any questions!

Ok sounds good. I might wait for that other PR (https://github.com/internetarchive/openlibrary/pull/8148) to be taken care of before I put up any changes (or combine them?), but will still be working on it.

**Comment by scottbarnes** [comment]
That makes sense to wait on the other PR. There's definitely no rush. :)
