### ISSUE TITLE
Author dropdown not working as expected

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8094]
Since the last deployment on July 13, the author dropdown on the edit form behaves differently. 
### Evidence / Screenshot (if possible)
<img width="1012" alt="Screenshot 2023-07-13 at 08 35 17" src="https://github.com/internetarchive/openlibrary/assets/17739465/389b1544-9d04-4de1-b218-0145867ec284">

### Steps to Reproduce

1. Go to ...add book or edit book form
2. Do ... try to add Plato as an author

* Actual: the most obvious choice is missing (Plato, the philosopher). Instead, there are authors that have plato as part of the spelling of their names or less prolific authors with the last name Plato.
* Expected: The most likely choice, probably determined by spelling and number of works, should appear on the list.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by tfmorris** [comment]
Note also that all of the authors have blank "including Subjects: ". This is another recent regression in autocomplete.

**Comment by cdrini** [comment]
Thanks @tfmorris added a fix for that to my PR
