### ISSUE TITLE
Changing coverstore URL configuration in local instances does nothing

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8097]
As per the instructions [here](https://github.com/internetarchive/openlibrary/wiki/Getting-Started#configuring), changing the `coverstore_url` configuration to https://covers.openlibrary.org should cause our local instances to source images from the production cover store.  This isn't working.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** All
- **Operating system?** All
- **Environment (prod/dev/local)?** local

### Proposal & Constraints

This was working fairly recently.  Recommend looking for recent code changes that would have caused this.

**Comment by jimchamp** [comment]
Have tested again, using `https://covers.openlibrary.org` as the `coverstore_url` and restarting `web` and `memcached` containers.  Afterwards, cover images are still missing from search results.

**Comment by cdrini** [comment]
Fixed the docs! Ah I think I see what the issue was ; there are now _two_ conf values, `coverstore_url` and `coverstore_public_url`. `coverstore_public_url` is the one that needs to be changed. That should fix it!
