### ISSUE TITLE
Quality improvement by searching for common OCR errors

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#810]
Sorry if this is out of place, but I just stumbled across an oddity. It appears that the Google-digitized non-English editions have some habitual problems in the OCR which shows up in the boilerplate they inserted. 

For instance, Googling: "carcfully scannod" site:archive.org
turns up 46,900 results, most of which are scanned from texts in languages that use diacritics. That can't be a coincidence. I'm wondering if it can be put to use for quality improvement. Might they just need a fresh run through OCR  with more modern software?

**Comment by mekarpeles** [comment]
I think your approach of searching for common misspellings is very smart and a could be a good way for us to test our overall OCR accuracy. Your conclusion also seems right, that re-running our OCR with newer software (we did just upgrade about 3 months ago and haven't re-run all of our books yet) is likely the correct solution.

**Comment by LeadSongDog** [comment]
Thanks, @mekarpeles. Any comment from @conditionsofexistence ?

**Comment by LeadSongDog** [comment]
@mekarpeles 
Sixteen months later, the same google search turns up "About 58,200" matches, an _increase_ of 11,200. Are the books being rerun at all? Or is the old OCR still in use?

**Comment by guyjeangilles** [comment]
59,600 now. Seems like something @hornc would take care of so I'm assigning him per slack discussions.

**Comment by LeadSongDog** [comment]
Now down to 32,600 so some progress is apparently being made. 
Weirdly though, further restricting the query to 
"carcfully scannod" site:archive.org "Full text of"
actually reports more hits, so perhaps the count reported by the Goog should be taken with a grain of salt.

**Comment by bicolino34** [comment]
Using full-text search on Open Library with phrase "carcfully scannod" I got [50556](https://openlibrary.org/search/inside?q=carcfully+scannod) hits
Searching in Google I get 29000 results. I was googling: "carcfully scannod" site:archive.org

**Comment by bicolino34** [comment]
@mekarpeles should this get moved to recently created [archive-ocr-tools](https://github.com/internetarchive/archive-ocr-tools) repo?

**Comment by mekarpeles** [comment]
Should be moved to open book genome project sequencer repo / issue tracker

**Comment by RayBB** [comment]
Moved https://github.com/Open-Book-Genome-Project/sequencer/issues/97
