### ISSUE TITLE
Fix invalid HTML in `header_dropdown.html`

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8109]
In `header_dropdown.html`, the pending merge request count badge is a `div` nested within a `summary` tag ([here](https://github.com/internetarchive/openlibrary/blob/ef9a338653207794985c884363553d28b16759bb/openlibrary/templates/lib/header_dropdown.html#L28)).  `div`s are not permitted to be child elements of `summary` elements, so this is causing our HTML to be invalid.

### Relevant url?

This component is present on every page.

### Steps to Reproduce

While logged in as a `librarian`, `super-librarian`, or `admin`:

1. Ensure that there is a pending merge request in the queue. 
2. Go to any page.
3. Inspect the badge with your browser's dev tools

* Actual: The count is inside of a `div`
* Expected: The count is inside of a `span`

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Change the `div` in question to a `span`, and update the related CSS.

**Comment by ThaungThanHan** [comment]
Hello, I am working on it.

**Comment by ThaungThanHan** [comment]
I could run the app but I cannot login. There is an internal error.

**Comment by jimchamp** [comment]
@ThaungThanHan update your previous comment with repro steps.  I can't help you if I don't know what you've tried.

**Comment by ThaungThanHan** [comment]
> @ThaungThanHan update your previous comment with repro steps. I can't help you if I don't know what you've tried.
> 
> Information from the `debug` page would also be useful. Adding `?debug=true` to the end of the URL should redirect you to the debug page. You may have to use your browser's dev tools to add the query string to the sign-in form's `action` before logging in.

Yes, I have edited the comment with error reproducing steps.

**Comment by jimchamp** [comment]
I'm pretty sure that I faced similar issues recently.  I fixed it by removing all of my Docker images, containers, and volumes:

`docker system prune -a`

**Important Note:** This will remove _all_ images, containers, and volumes on your machine, not just one's related to Open Library.

**Comment by ThaungThanHan** [comment]
> I'm pretty sure that I faced similar issues recently. I fixed it by removing all of my Docker images, containers, and volumes:
> 
> `docker system prune -a`
> 
> **Important Note:** This will remove _all_ images, containers, and volumes on your machine, not just one's related to Open Library.

Thank you. It works now. I am back on the task.
