### ISSUE TITLE
Rename `build_marc` and move it to a new home

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8111]
`build_marc` in [`catalog/merge/merge_marc.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge_marc.py) is poorly named. 

### Proposal & Constraints

@hornc has [suggested](https://github.com/internetarchive/openlibrary/pull/7940#discussion_r1228968439) renaming this to `expand_record()` and moving it to a new home. How about [`catalog/utils/__init__.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/utils/__init__.py)

There is perhaps a dangerous thread to pull at here, insofar as [`catalog/merge/merge_marc.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge_marc.py)
and [`catalog/merge/merge.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/merge/merge.py) have a number of overlapping functions. Some of those that overlap have been decorated as `@deprecated` in `merge.py`, but not all.

To avoid getting bogged down too far, let's limit this issue to dealing with `expand_record()`, nee `build_marc()`, and its direct dependencies (i.e. `build_titles()`).

Perhaps both can go from `merge_marc.py` to [`catalog/utils/__init__.py`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/utils/__init__.py), and then the `build_titles()` from `merge.py` can be decorated with `@deprecated` and it can point to the new location of `build_titles()`.

### Stakeholders

@hornc, @cclauss

**Comment by cclauss** [comment]
Nice!  Would it make sense to create a **separate pull request** to remove those @deprecated functions?

**Comment by scottbarnes** [comment]
> Nice! Would it make sense to create a **separate pull request** to remove those @deprecated functions?

I think it does make sense. I created #8112 to reflect this.
