### ISSUE TITLE
Missing API for username

### ISSUE THREAD

**Issue by SMillerDev** [internetarchive/openlibrary#8132]
### Question
Currently login can be done with email or username. How can a client detect the username of the login?

### Additional context
I'm currently making an iOS app for OpenLibrary and when the user logs in with email or UserName the APIs I call fail because it is not the exact user/profile name.

### Issue resolution criteria
When an API is pointed out or created to resolve this.

**Comment by mekarpeles** [comment]
Login must be done with email.

**Comment by SMillerDev** [comment]
@mekarpeles  okay, but that doesn't answer the initial inquiry though. In fact it makes it more difficult to determine the username.
