### ISSUE TITLE
Languages API endpoint only returns 15 languages

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8133]
The languages [page](https://openlibrary.org/languages) lists hundreds of languages, but the [JSON API](https://openlibrary.org/languages.json) only returns 15 and neither `limit` nor `offset parameters appear to have any affect.

### Relevant url?
https://openlibrary.org/languages
https://openlibrary.org/languages.json?limit=1000
https://openlibrary.org/languages.json?offset=100

It looks like the limit of 15 is intentional, which is *very* odd.
https://github.com/internetarchive/openlibrary/blob/7e197beeca9e4802fc96101d122766e5f52e8265/openlibrary/plugins/worksearch/languages.py#L71-L73

**Comment by cdrini** [comment]
Yep, that's a bad API! :P Here is a workaround in the interim, if needed: http://openlibrary.org/query.json?type=/type/language&name

**Comment by tfmorris** [comment]
> a workaround in the interim, if needed: http://openlibrary.org/query.json?type=/type/language&name

Thanks for the hint. I ended up parsing the HTML page, but if I need to do it again before this is fixed, the hint will be useful, although I'll probably use:

http://openlibrary.org/query.json?type=/type/language&name&name_translated

to get access to all the name forms.

**Comment by sbwhitt** [comment]
I can look into this and get a fix together

**Comment by cdrini** [comment]
@tfmorris You can also add `&*` to fetch all the data fields: http://openlibrary.org/query.json?type=/type/language&*

**Comment by sbwhitt** [comment]
@tfmorris @cdrini  I have a working solution on my local. Before I create a PR I wanted to ask if you would want the default limit remain at 15 for no limit/invalid value.
