### ISSUE TITLE
"Already Read" star rating component mangled on My Books page

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8137]
The star rating component found in "Already Read" My Books page items is mangled in both mobile and desktop views.

### Evidence / Screenshot (if possible)
![Screenshot from 2023-07-27 12-13-00](https://github.com/internetarchive/openlibrary/assets/28732543/dc5d4181-7f1c-41d4-9fa4-8e88c11a7c4f)
_Desktop star rating component is inside of the red box_

![image](https://github.com/internetarchive/openlibrary/assets/28732543/89a414ec-ffda-47ad-86cb-a135ed0a2739)
_Desktop star rating component, after rating_

### Relevant url?

https://openlibrary.org/account/books/already-read

### Steps to Reproduce

1. While logged into an account with books on the "Already Read" shelf, go to https://openlibrary.org/account/books/already-read
2. Look at the star rating components.

* Actual:  Component has odd layout.
* Expected: Component has correct layout. 

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**Firefox Desktop 115.0.2 (64-bit)
- **Operating system?** Ubuntu 22.04.2 LTS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Removing the "Rate" string may solve this.

### Stakeholders

@szgrune 
@mekarpeles

**Comment by cdrini** [comment]
@szgrune Do you have some time to investigate this one ?

**Comment by szgrune** [comment]
Just removed Rate, looks much better now. Another option might be to move Rate on line above stars, display as a block with width 100%, and text-align center so that it's like a title/instructions for the stars. However, I think it's pretty clear what the stars are for without the label
