### ISSUE TITLE
Update cgi.FieldStorage to unblock Python 3.13

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8147]
Python's `cgi` module has been [deprecated](https://docs.python.org/3/library/cgi.html) and will be removed in Python 3.13, `web.py` relies on `cgi.FieldStorage` for file upload, and Open Library uses `web.py` (and by proxy, `cgi.FieldStorage`, including, but not limited to, for cover upload). See [PEP-0594](https://peps.python.org/pep-0594/#cgi) for more.

@cclauss created an issue issue for this on the `web.py` GitHub: webpy/webpy#778.
### Proposal & Constraints

We need `web.py` updated to no longer use `cgi.FieldStorage`, we need to stick with Python <= 3.12, or we need to use something other than `web.py`, I think.

There's a PR to replace `cgi.FieldStorage` with [multipart](https://github.com/defnull/multipart/) and `urllib.parse.parse_qsl`: webpy/webpy#768.

### Stakeholders

@mekarpeles 
@cclauss

**Comment by cdrini** [comment]
Note Python 3.13 will be released october 2024 https://peps.python.org/pep-0719/

**Comment by scottbarnes** [comment]
@cclauss has released [webpy v70](https://github.com/webpy/webpy/releases/tag/webpy-0.70).

This PR will need to be updated so that `requirements.txt` includes `web.py==0.70`.

**Comment by cclauss** [comment]
Not yet on PyPI... https://pypi.org/project/web.py

**Comment by scottbarnes** [comment]
I found an issue in the code I submitted that contributed to webpy 0.70 and created an issue here: https://github.com/webpy/webpy/issues/776. I have a tentative fix and am working on tests for it.

**Comment by mekarpeles** [comment]
This is fixed here: #778
