### ISSUE TITLE
Mobile My Books item groups incorrect

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8156]
Because of the positions of the separating lines, it looks like the label "Want to Read" actually applies to the currently reading books

### Evidence / Screenshot (if possible)

![image](https://github.com/internetarchive/openlibrary/assets/6251786/b0f9bc59-4529-4a2e-adea-7d9b3bce0a3b)

### Relevant url?
https://openlibrary.org/account/books

### Proposal & Constraints
Move the line borders to correctly group the items.

### Stakeholders
@szgrune

**Comment by mekarpeles** [comment]
@szgrune what do you think about this css change? Up for making a tweak?

**Comment by szgrune** [comment]
Creating pull request with this solution now:

<img width="381" alt="Screenshot 2023-08-08 at 11 24 53 AM" src="https://github.com/internetarchive/openlibrary/assets/69476557/3cef810b-8464-4a53-a398-66e1952513a8">
