### ISSUE TITLE
Goodreads import fails if data contains a custom shelf

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8158]
Goodreads allows custom exclusive shelves in addition to the three standard read/want to read/currently reading shelves. If a patron has a custom exclusive shelf and tries to import their data, the import halts when it hits one of these rows.
### Evidence / Screenshot (if possible)
<img width="1218" alt="Screenshot 2023-08-04 at 11 08 24" src="https://github.com/internetarchive/openlibrary/assets/17739465/88ed35f8-2c62-470e-bef1-eccfc2dd43c0">

### Relevant url?

https://openlibrary.org/account/import/goodreads

Related to #7925 

### Steps to Reproduce

1. Go to ... import options.
2. Do ... try to import Goodreads data containing a custom exclusive shelf.

* Actual: import halts
* Expected: Those rows should skipped with a warning to the patron.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Custom shelves need to be handled in some way, or allow patron to skip them.

**Comment by mekarpeles** [comment]
I think at minimum, the desired behavior is to skip these records and to continue proceeding through the next compatible shelves. In the future, we could decide to turn these custom shelves into lists but maybe for simplicity (for now) it should just skip and be robust to these cases.

**Comment by akhil-rasheed** [comment]
Hi, I'd like to take up this issue. New to the community and this seems like a good first issue!
