### ISSUE TITLE
Update wikipedia citation output

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#817]
Example current citation for https://openlibrary.org/books/OL15327355M/The_Two_Towers

```
{{Citation
|publisher = Houghton Mifflin Co.
|isbn = 0395082544
|publication-place = Boston, USA
|title = The Two Towers
|url = http://openlibrary.org/books/OL15327355M/The_Two_Towers
|author = J. R. R. Tolkien
|publication-date = 1954
|id = 0395082544
}}
```

* `id` is already covered by ISBN, remove
* `url` should  be a link to the readable book, use archive.org url if it exists, not OL (use https!)
* add new `ol = 15327355M` field as this is recognised by Wikipedia and creates the correct link to OL
* unsure whether to use `publication-date` or `date` - confirm which is most current/accurate
* confirm we correctly populate all other ids we have available

See https://en.wikipedia.org/wiki/Template:Citation for guidelines.

**Comment by salman-bhai** [comment]
@hornc can I take this uo? If no one else is doing this!

**Comment by hornc** [comment]
@salman-bhai yes please, that would be great!
