### ISSUE TITLE
Original language / translated_from field value not localized on Edition edit page

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8174]
The language name is displayed in English for the `translated_from` / "Original Language" field on the edition edit page rather than being correctly localized. The drop down language selector correctly displays the localized name.

### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/82178/3832bd0f-7902-4d52-a532-e1b8dbb7e660)

### Relevant url?
https://openlibrary.org/books/OL43522513M/Les_noirs_et_les_rouges/edit

### Steps to Reproduce

1. Go to the above URL
2. Do a scroll down to the translation section of the page

* Actual: English name of the language is displayed
* Expected: Localized name of the language is displayed

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by karlitto01** [comment]
Hi. I am new to this community and would like to contribute to this issue, if possible. Thanks!

**Comment by parmishh** [comment]
Hi I would like to go next. If no one is working on this issue.
