### ISSUE TITLE
Merge works gives "Permission Denied" error

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8175]
### Evidence / Screenshot (if possible)
![Screen Shot 2023-08-08 at 3 47 38 PM](https://github.com/internetarchive/openlibrary/assets/82178/fa195601-ec1c-4b55-a3ea-207d8d7b31c4)

### Relevant url?
https://openlibrary.org/works/merge?records=OL31822851W,OL16656007W

### Steps to Reproduce

1. Go to author's page - https://openlibrary.org/authors/OL5735712A/Alberto_Garlini
2. Select two works to merge
3. Click "Merge works"
4. Fill in merge reason and click Save

* Actual: JSON parser error as above
* Expected: merge works

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 114.0.5735.198 (Official Build) (x86_64)
- **Operating system?** OS X
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
The merge worked for me... Are you getting this for every merge you try @tfmorris , or was it just this one specifically?

**Comment by cdrini** [comment]
Oh wait were those books meant to be merged? I just clicked merge thinking I'd get the error!

**Comment by tfmorris** [comment]
> Oh wait were those books meant to be merged? I just clicked merge thinking I'd get the error!

Those works were fine to merge. One was a translation of the other.

> Are you getting this for every merge you try @tfmorris , or was it just this one specifically?

Every merge, although I only tried a few times at a point in time in the past when I wasn't sure whether it was still under development or not (I never saw any announcement).

**Comment by cdrini** [comment]
That's odd... Are any other super librarians having trouble merging? CC @seabelis

**Comment by cdrini** [comment]
Oh I can't quite recall, I think one must also be a member of the APIs usergroup for this to work? Let me double check with Lisa.

**Comment by seabelis** [comment]
@tfmorris I've added you to the api usergroup. Can you check if it's working now?

**Comment by tfmorris** [comment]
@seabelis That did the trick. Thanks! The only slightly odd thing was that the response looked like this:
![Screen Shot 2023-08-10 at 1 46 22 PM](https://github.com/internetarchive/openlibrary/assets/82178/28a76f6a-defd-4ad7-8a83-6caecb4a71d0)
not sure if that's the way it's supposed to look, but it did the merge.

@cdrini (or some other programmer type) it seems like the code should using the same criteria/group to check whether to offer the feature and to actually execute it.

**Comment by cdrini** [comment]
Yeah that's the expected output for better or worse :P 

Yeah adding an automated check would be super helpful, since I know I always forget what perms are necessary!

Choosing this issue; please feel free to create a new one about auto checking perms!
