### ISSUE TITLE
last_login field broken since xauthn

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8179]
Since ~2017 when we moved from OL to IA login, we broke `last_login` field in `store` db under `account/{person}`.

### Related files

The logic in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L237-L238 needs to be added to https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L895

The solution is a new function which performs...

```
account_key = 'account/{person}'
account = web.ctx.site.get(account_key)
account['last_login'] = datetime.datetime.utcnow().isoformat()
web.ctx.site.store[account_key] = account
```

**Comment by tfmorris** [comment]
Those code references don't look valid. If you use Github's "copy permalink" you'll not only get a stable reference, but it'll also quote the code inline for you: https://github.com/internetarchive/openlibrary/blob/9b3a80f1d82c3c2455b207370d7d7de9c40e86ed/openlibrary/accounts/model.py#L229-L230
