### ISSUE TITLE
Various page styling + functionality is broken (infogami templates)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#818]
At one point it looks like i18n preferences were manageable from this page

cc: @leadsongdog

When @hornc's i18n changes get merged in we can talk about reviving this page

URL:
* https://dev.openlibrary.org/account/preferences

Appearance:
![screen shot 2018-12-24 at 4 29 00 pm](https://user-images.githubusercontent.com/148752/50408061-0eba6c80-0799-11e9-8368-18ac7d497505.png)

See also:

* https://openlibrary.org/account/forgot_password

**Comment by LeadSongDog** [comment]
Aside from language, are there any other prefs that should be supported? Perhaps low/no graphics? Ebook format default? Whether/where/how to email/tweet when wait listed books become available? Privacy of lists? Others?

**Comment by LeadSongDog** [comment]
Font. Contrast. Read aloud voice. Bookseller. Social Identities.

**Comment by mekarpeles** [comment]
near-term solution is removing the /preferences route which is unused/unreachable and has broken styles. This doesn't mean we won't have an /account/preferences page moving forward :)

I have a solution on dev which I'll push up

**Comment by jdlrobson** [comment]
I vote we drop this page since https://dev.openlibrary.org/account seems to be its replacement.

This seems to be code for infogami that has been replaced. This along with
