### ISSUE TITLE
Firefox constantly reloading

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8184]
Firefox mobile ios is constantly reloading Openlibrary pages, Login isnt possible as is any other page.

- **Logged in (Y/N)?** yes and no
- **Browser type/version?** Firefox mobile on ios or ipados, latest version
- **Operating system?** ios
- **Environment (prod/dev/local)?** prod

**Comment by 20481A05K0** [comment]
**hey** there!!

> can i take up this issue or still anyone working on it

**Comment by mekarpeles** [comment]
Is anyone else experiencing this problem? @bitnapper it may be good for us to try and jump on a call together so we can see what's going on?...

**Comment by bitnapper** [comment]
When I reported this issue, OL seemed to have some trouble delivering pages in general. No page loaded completely. It was ok-ish in most browsers but that time it was worse than ever before and lasted several days. Since I don't have this issue at the moment, I can't show you but would be available If you like to talk about it. I send you my preferred contacts in slack.

It seems Firefox mobile has different behaviour when timeouts are met than its desktop counterparts or other browsers I guess.

**Comment by bitnapper** [comment]
When I reported this issue, OL seemed to have some trouble delivering pages in general. No page loaded completely. It was ok-ish in most browsers but that time it was worse than ever before and lasted several days. Since I don't have this issue at the moment, I can't show you but would be available If you like to talk about it. I send you my preferred contacts in slack.

It seems Firefox mobile has different behaviour when timeouts are met than its desktop counterparts or other browsers I guess.

**Comment by cdrini** [comment]
(deleted accidental duplicate comment)

**Comment by mekarpeles** [comment]
I am marking as "cannot reproduce" for now. Please re-open if folks are still hitting this! It seems important.
