### ISSUE TITLE
Same MARC record imported twice creating duplicate OL edition records

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8189]
This MARC [record](https://openlibrary.org/show-records/marc_miami_univ_ohio/allbibs0078.out:4787453:852) was imported twice a couple of weeks apart creating duplicate OpenLibrary editions.

### Relevant url?
MARC record - https://openlibrary.org/show-records/marc_miami_univ_ohio/allbibs0078.out:4787453:852
Edition 1 - https://openlibrary.org/books/OL16784531M
Edition 2 - https://openlibrary.org/books/OL17946219M

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: Duplicate edition records created
* Expected: Each MARC record creates no more than one OpenLibrary edition

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@hornc

**Comment by hornc** [comment]
manually merged 2 editions imported from MARC in 2008 using pre-current process MARC import code into the record with a linked scan on archive.org: https://openlibrary.org/books/OL26325912M/Arthur_St._Clair_of_Old_Fort_Recovery
