### ISSUE TITLE
Tab for declined merges

### ISSUE THREAD

**Issue by JeneeW** [internetarchive/openlibrary#8195]
For librarians-in-training like me who commonly submit dozens to hundreds of merge suggestions at a time, it can be difficult to go back through checking to see which ones were rejected. If there was a tab added that specifically filtered the ones that are wrong, it would help me and other trainees correct mistakes more easily.

Is this a reasonable request?

**Comment by jimman2003** [comment]
I agree that rejected merges are useful feedback to be separated and thus emphasized
