### ISSUE TITLE
Four duplicate authors created sequentially (possible issue in import setup)

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8196]
### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/921217/b5ade4dc-dbed-46fc-aa00-0b5ac5dad942)

### Relevant url?

https://openlibrary.org/authors/merge?key=OL12764474A&key=OL12764477A&key=OL12764476A&key=OL12764475A

### Details
I noticed that these 4 authors with identical names and "Catalina Martinez Muñoz" and sequential IDs (OL12764474A, OL12764475A, OL12764476A, OL12764477A) were all imported right around the same time. Could possibly be a bug with the import algo and how it matches authors.

I wonder if it could be due to the author query used by the import bot being cached so all 4 requests said there was no matching author just because the first one did.

First mentioned on slack here: https://internetarchive.slack.com/archives/C02BX7F5P7H/p1691799181850039

**Comment by tfmorris** [comment]
Also 4 identical duplicate editions imported sequentially:

* https://openlibrary.org/books/OL47670760M
* https://openlibrary.org/books/OL47670761M
* https://openlibrary.org/books/OL47670762M
* https://openlibrary.org/books/OL47670763M

Creating 4 identical works: https://openlibrary.org/recentchanges/2023/08/12/merge-works/122940729

What a waste of time and resources!

**Comment by cdrini** [comment]
My guess would be this is the same as https://github.com/internetarchive/openlibrary/issues/6405 ; the offending code path has since been turned off. But the bug caused quite a bit of damage while there 😞 closing this in favour of that.

**Comment by tfmorris** [comment]
These were imported the same day that the pipeline was shutdown due to the previous bug report, so that seems possible.
