### ISSUE TITLE
Auto-detect ASINs & StoryGraph identifiers in the author page editor

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#8202]
### Describe the problem that you'd like solved
The author editing page is able to automatically "suggest" that Q57087507 is a Wikidata identifier or 0000 0004 8385 4684 is an ISNI, speeding up the process of adding identifiers to existing author pages. I think this could be done for ASINs & StoryGraph IDs as well, if I correctly understand what a regex is.

### Proposal & Constraints
ASINs are described here: https://inventlikeanowner.com/blog/the-story-behind-asins-amazon-standard-identification-numbers/

I think it would be best to only assume a 10-character code starting with B or B & a number, given the rate at which they're being created as detailed in the link above.

An example StoryGraph ID: 6c67a39f-eae2-4304-a8a3-7309da6560df

I don't know how best to describe this other than 'five alphanumberic chunks with dashes in between'. The middle ones seem to be shorter than the beginning and ending ones in my experience, but that's anecdotal.

### Additional context
This could possibly be extended to other identifiers, but I don't know enough about them to be sure it's worth proposing.

### Stakeholders
@RayBB

**Comment by davidscotson** [comment]
I have a code fix for this, though when trying to test locally with docker I noticed that the list of IDs is shorter, with only 5 options compared with the 10 on the live site.

I assume that can be configured somewhere, so I'll look into that to enable me to finish testing the change.

Looking at that longer list, I think I could also match the Youtube one (I assume it's the channel ID as described in detail here: https://www.wikidata.org/wiki/Property:P2397)

**Comment by RayBB** [comment]
I think the IDs might be configured in the DB dump that's imported when you start your instance and that's a bit outdated but I'm not sure. Would be a nice thing to document if you end up needing to update.

**Comment by davidscotson** [comment]
I managed to get the settings from the live site by following the instructions here:

https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data

but changing the example of :

```./scripts/copydocs.py /authors/OL1385865A	``` 

to

```./scripts/copydocs.py /config/*```

I tried with just /config/author rather than the * which seemed to do something but didn't seem to stick. Possibly some things get lost if you stop the docker container? Kind of feels like my JS changes keep needing to be rebuilt to be present on the dev docker.

Anyway, seems like I can test now.

**Comment by davidscotson** [comment]
PR created for review.

Seperate from this small improvement, I'm hopeful that many of these can be automatically imported from/via Wikdata e.g. here you can see their mappings between Open Library and Youtube IDs (this is actually only some of them, I limited it to the ones famous enough to have english wikipedia pages):

https://wikidata-todo.toolforge.org/beacon.php?prop=2397&source=648&site=enwiki

But in regards to that I note that storygraph isn't yet even proposed as a property there yet: https://www.wikidata.org/wiki/Wikidata:Property_proposal/Authority_control

**Comment by stopregionblocking** [comment]
Thanks!

> Seperate from this small improvement, I'm hopeful that many of these can be automatically imported from/via Wikdata

That's what I would hope too. However, this is still a useful step because a significant number of authors don't have any presence on Wikidata. There's also the possibility of Wikidata items having the wrong identifiers attached, making cross-checking more important, but I haven't thought about how to approach that for more than a few minutes.

**Comment by jimchamp** [comment]
My understanding is that ASINs uniquely identify products, not people.  I don't believe that an author can have an ASIN.  Am I missing something?

**Comment by davidscotson** [comment]
It's technically an Amazon Author ID but it's the same general deal:

https://www.wikidata.org/wiki/Property:P4862

I believe there's others for musicians and maybe more.
