### ISSUE TITLE
Add "Want to Read" buttons to book lists

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#8206]
Dear developers,

I suggest that a Want to Read" button be added to OpenLibrary book lists (example: https://openlibrary.org/people/floriana_de_nichilo/lists/OL224381L/tesi).
Currently, there is only a "Borrow" button, so I need to open each book from someone's list in a separate tab just to add that book  to my "Want to Read" list.

I appreciate you considering my suggestion.
Thank you for your time.

**Comment by sbwhitt** [comment]
Hey @jimchamp, I've been looking into this off and on so you can go ahead and assign me if you like.

**Comment by jimchamp** [comment]
Hi @sbwhitt.  This is blocked by #8019, which makes major changes to the "Want to Read" button.  Once that is merged, I'll remove the "Blocked" label and reach out to you.

**Comment by jimchamp** [comment]
@sbwhitt if you're still interested in being assigned, this is unblocked now.  Just let me know.

**Comment by bicolino34** [comment]
It would also be nice to add "Want to Read" button on author and subject pages

**Comment by sbwhitt** [comment]
@jimchamp Thanks for the heads up. I'll start looking into this again
