### ISSUE TITLE
openlibrary.org/account/login example 

### ISSUE THREAD

**Issue by bradyguyc** [internetarchive/openlibrary#8210]
### Question
A good example preferably in c# of a call to openlibrary.org/account/login passing in username and password and getting an api key back that allows subsequent calls to get and update my books read information.

### Additional context
The following code returns a login failed 200 but no token or api key to use.  Am I using this call correctly?  I don't see a session key returned in the headers either.  

Thanks

            try
            {
                var json = new JObject(
                      new JProperty("username", username),
                      new JProperty("password", password)
                  );

                var content = new StringContent(json.ToString(), Encoding.UTF8, "application/json");

                var response = await _client.PostAsync("https://openlibrary.org/account/login", content);

                if (response.IsSuccessStatusCode)
                {
                    var apiKey = response.Headers.GetValues("key").FirstOrDefault();
                }
                return response.IsSuccessStatusCode;
            
            }
            catch (Exception ex)
            {
                ErrorHandler.AddLog(ex.Message);
                //HttpResponseMessage responseMessage = new HttpResponseMessage();
                //responseMessage.StatusCode = System.Net.HttpStatusCode.NotFound;
                return false;
            }
`

**Comment by jimchamp** [comment]
To authenticate with JSON, you'll have to hit our JSON login endpoint: https://openlibrary.org/account/login.json

You won't be able to use your email and password to authenticate with this endpoint.  It requires keys that can be accessed here: https://archive.org/account/s3.php

POST your keys to the login endpoint, sending your keys in the body: {"access": "<your_access_key>", "secret": "<your_secret_key"}

If successful, you'll recieve a authentication cookie named `session`.  Include this cookie in subsequent requests.

**Comment by bradyguyc** [comment]
Thanks for the information.  Is there anyway that you can login using username and password?  Is that on the roadmap if not?

Thanks
Brady

**Comment by jimchamp** [comment]
If you want to use JSON, you;ll have to hit our JSON endpoint with your S3 keys.  Alternatively, you can POST a request to `/account/login` sending all of the required fields as form data.

**Comment by jimchamp** [comment]
@tfmorris could you clarify?  Do you want to know more about the login endpoints or the S3 keys?

**Comment by tfmorris** [comment]
I'm looking for documentation on authenticated access to the API. Basically whatever page https://github.com/internetarchive/openlibrary/issues/8210#issuecomment-1696241081 was abstracted from. I'm assuming it will have both more detail as well as usage examples. I was able to follow the link above to the S3(ish) keys (after an initial 500), so I know how to get them.

**Comment by jimchamp** [comment]
I see now, thanks!  These were ad hoc instructions that I put together by looking at the account login handlers ([here](https://github.com/internetarchive/openlibrary/blob/a8796b4952b13b6f12138c3de8e1af0efdea85d7/openlibrary/plugins/upstream/account.py#L308-L346) and [here](https://github.com/internetarchive/openlibrary/blob/a8796b4952b13b6f12138c3de8e1af0efdea85d7/openlibrary/plugins/upstream/account.py#L377-L414)).

I'll find an appropriate place to post this information, and post an update here afterwards.

**Comment by jimchamp** [comment]
@bradyguyc, please use the `/account/login.json` endpoint to authenticate with your keys.
If you have an Open Library account, you already have keys.

@tfmorris, I've updated the "Login" section [here](https://openlibrary.org/dev/docs/restful_api#login) with JSON authentication instructions. Have also added a jump link to that section at the top of the page.  The missing link was undoubtedly making this information harder to find.

**Comment by tfmorris** [comment]
Thanks @jimchamp ! I can see how this could work for a single user custom app, but what's the usage model for a multi-user app? If the username/password form does work, that allows the application to see the user's password, but if it doesn't, then app writers need to tell users to go fetch their keys (and then those keys are visible to the app).

**Comment by mekarpeles** [comment]
@tfmorris you're right that this isn't ideal. The saving grace is that authentication on Open Library returns s3 keys which I don't think can easily be used to change their email/password. This operation requires an additional step of entering password. If so, that would be a more significant oversight. There still is a vector if a 3rd party violated TOS by saving a patron's password. Doing SSO or something oauthy with a token would be a better approach but that's not how things are configured yet.

**Comment by tfmorris** [comment]
@mekarpeles Given people's propensity for reusing passwords across sites, it's not only their archive.org account which is at risk. If authenticated access can't be done securely, I think it's extremely unwise to allow applications which use it.
