### ISSUE TITLE
Allow shift-click in ILE

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8212]
Currently when selecting element in the ILE, you can only select one element at a time. Let's add support for `shift-click`. This will select all selectable items between the last selected item and the item that was `shift-clicked` upon.

**Comment by WaltersAvenger** [comment]
@cdrini can you assign this to me? If so, can you point me in the direction of the ILE bar?

**Comment by av1934413** [comment]
> Currently when selecting element in the ILE, you can only select one element at a time. Let's add support for `shift-click`. This will select all selectable items between the last selected item and the item that was `shift-clicked` upon.
> 
> ### Describe the problem that you'd like solved
> ### Proposal & Constraints
> ### Additional context
> ### Stakeholders

**Comment by cdrini** [comment]
Hi @WaltersAvenger ! The code for this is https://github.com/internetarchive/openlibrary/blob/b9a3c408d7fdfd550941194114d5d0ff477ebba0/openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js#L84 . Let us know if you have any questions!

**Comment by WaltersAvenger** [comment]
Sorry to be so late to get back. Do you know how I can access the ILE bar from inside the application?

**Comment by cdrini** [comment]
No worries yep! Once you have your local environment running, log in, do a search for anything (eg `the`), and then select one of the books. You'll see the bar appear at the bottom of the screen

**Comment by mheiman** [comment]
@WaltersAvenger, are you actively working on this one still? If not, I'd like to move ahead with a solution.

**Comment by WaltersAvenger** [comment]
@mheiman ahh no I have not looked at it and got very busy. I can pick up something else if you already have a solution

**Comment by cdrini** [comment]
Thanks @WaltersAvenger ! I'll assign this to Mark to unblock him. Please feel free to find another good first issue and we'll help you :)
