### ISSUE TITLE
Move "add a book" to the "help" section rather than "develop" of footer

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8213]
### Evidence / Screenshot (if possible)

<details>
  <summary>Screenshot</summary>
  
  ![image](https://github.com/internetarchive/openlibrary/assets/921217/cbd82cd7-8b20-4f06-9d51-272cdf4290a6)
  
</details>

### Relevant url?

https://openlibrary.org/

* Actual: "add a book" link is under the "develop" section
* Expected: "add a book" link is under the "help" section

### Proposal & Constraints

Move "add a book" to the help section of the footer.

It's clearly not related to software development like the other things under develop

### Related files

Would be a good first issue.

Slack thread: https://internetarchive.slack.com/archives/C0ETZV72L/p1691848296935779

**Comment by RayBB** [comment]
The result of the discussion was that it's probably not worth it to move it now.
But we should reconsider how the sidebar and footer map and what should be where.

**Comment by anujamerwade** [comment]
Hi @RayBB, I am new to the community. I came across this issue recently. I was wondering if I could take this up and try to solve it. However, from the comments I am not sure if this is finalized yet to be resolved or not. Kindly let me know. We could also discuss more in the community call on Tuesday. Thanks!

**Comment by RayBB** [comment]
The summary from the last community call is:
* Nobody was strongly opposed or in favor of moving it
* We should probably evaluate how the sidebar and footer are organized in general

In my opinion (as a volunteer) you could try making a PR to move it. At worst, you'll learn more about how Open Library works. At best the community will decide that it is a change that makes sense and merge it in. But if you have other issues that seem interesting maybe spend time on those instead.

**Comment by anujamerwade** [comment]
Thank you for your response @RayBB! I will take a look at other issues as well and submit a PR accordingly.

**Comment by piyush-poddar** [comment]
@RayBB @scottbarnes I have opened a [PR](https://github.com/internetarchive/openlibrary/pull/8394) for this issue, please review it.
