### ISSUE TITLE
Log out link doesn't work on `/account/create` and `/account/login` pages when already logged in

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8219]
When an authenticated patron navigates to `/account/create` or `/account/login` pages, we display a message telling them that they are already logged in.  This message also contains a "log out" link, which does nothing when clicked.

### Evidence / Screenshot (if possible)
![Screenshot from 2023-08-23 09-41-55](https://github.com/internetarchive/openlibrary/assets/28732543/748fdcb9-5a31-47e7-92f2-9618c6f00b88)
_Screenshot of login page.  Log out link is on the second line._

### Relevant url?

https://openlibrary.org/account/create
https://openlibrary.org/account/login

### Steps to Reproduce

While logged in
1. Go to either page listed in the "Revevant url" section, above
2. Click the "log out" link

* Actual: Nothing
* Expected: I am logged out of the site.

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?**Any
- **Operating system?**Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The "Log out" link in the hamburger menu works perfectly.  The broken log out links could be modeled on that.
Alternatively, a log out form can be added to the templates containing the broken links.

### Related files

Login page: https://github.com/internetarchive/openlibrary/blob/540853735859789920caf9ee78a762ebe14f6103/openlibrary/templates/login.html#L18
Create account page: https://github.com/internetarchive/openlibrary/blob/540853735859789920caf9ee78a762ebe14f6103/openlibrary/templates/account/create.html#L40

**Comment by Wreck-X** [comment]
can I take up this issue?

**Comment by jimchamp** [comment]
You are assigned.  Let me know if you have any questions.

**Comment by sudhanshu196r** [comment]
can I take up this issue ?

**Comment by jimchamp** [comment]
@sudhanshu196r You cannot have this issue, as I just assigned @Wreck-X to this issue 9 hours ago.  Please find an issue that has no assignee.

**Comment by WaltersAvenger** [comment]
@jimchamp went ahead and took a look at this one.

Here is a PR for it: https://github.com/internetarchive/openlibrary/pull/8239

**Comment by jimchamp** [comment]
@WaltersAvenger, why would you do that?  I j[ust told](https://github.com/internetarchive/openlibrary/issues/8219#issuecomment-1696175229) @sudhanshu196r that they should find another issue to work on, since @Wreck-X was _only _just__ assigned to this issue.

**Comment by jimchamp** [comment]
@WaltersAvenger and @sudhanshu196r:
If you're trying to find a good first issue, check out these search results: https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs%3A+Help%22+label%3A%22Good+First+Issue%22 
If the issue is already assigned to somebody, ask if they are still working on it before you start.

**Comment by sudhanshu196r** [comment]
thankyou @jimchamp

**Comment by Wreck-X** [comment]
> @Wreck-X, please continue to work on this issue, and feel free to reach out if you have any questions.

yep am on it

**Comment by Wreck-X** [comment]
I have made a PR #8241 could you review it? @jimchamp

**Comment by WaltersAvenger** [comment]
@jimchamp will find a new issue.
