### ISSUE TITLE
Investigate blocking ByteDance.com

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8226]
Noticing a spike in page access that seems like it's coming from here and leaving our covers service to very high CPU/load usage.

**Comment by cdrini** [comment]
Mek did this

**Comment by cdrini** [comment]
Ooops @jimchamp notes that this is the parent company of TikTok!?? So maybe don't want to block it. Our block is temporary anyways, it'll disappear after the next deploy.

**Comment by mekarpeles** [comment]
I think performance improvements since blocking speak for itself -- having a usable website > whatever potential value tiktok's engine provides.
