### ISSUE TITLE
How to get all the subjects names ?

### ISSUE THREAD

**Issue by rif103** [internetarchive/openlibrary#8230]
### Question

Hi, can I get all the "subjects" to allow my users to search books via category?

**Comment by cdrini** [comment]
The quickest option might be for me to give you a dump of the subjects, but what is your use case exactly ? You can also hit our API for searching subjects directly without a dump: e.g. http://openlibrary.org/search/subjects.json?q=horror

Or if you want to do an autocomplete, you can do https://openlibrary.org/subjects_autocomplete?q=horror .

Does this help, or would you like me to kick off the dump?

**Comment by mekarpeles** [comment]
All the subjects should be in our existing work data dumps:
https://openlibrary.org/developers/dumps
