### ISSUE TITLE
Single MARC record imported over 2300 times

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8231]
A single MARC record was imported thousands of times creating many thousand duplicate author record, edition records, and work records. These all need to be cleaned up.

### Relevant url?
MARC Record https://openlibrary.org/show-records/marc_university_of_toronto/uoft.marc:440170798:923
2329 works https://openlibrary.org/search?q=Legal+problems+concerning+unmarried+couples%3A+proceedings+of+the+eleventh+Colloquy+on+European+Law%2C+Messina%2C+8-10+July+1981.&mode=everything
2246 authors (after some merges) https://openlibrary.org/search/authors?q=Colloquy+on+European+Law.+1981+Messina%2C+Italy&mode=everything

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
We briefly looked and these appear to be older, so it might be an old bug that has since been fixed. Let us know if you notice newer cases of this problem! Otherwise we'll consider this to be about merging this up into a single record.

CC @jimman2003 who I think did some work on these before.

**Comment by tfmorris** [comment]
Yes, the cleanup is the focus of this issue. I noticed this when attempting to quantify the Spring 2023 Amazon import problem, but those are more like 5x, not thousands.

**Comment by hornc** [comment]
I have redirected all of these into the following records:

One Work:
OL11409552W

One Edition:
OL15121751M

One Author:
OL4791619A

Solr has caught up and the original searches (see the original issue description above) only show one record each.

I have no idea how this duplication happened in the first place, I can only assume it was using old import processes. I hope we don't have more of these, but if we do, I can script another redirect set. The provided search queries were super helpful in isolating the records to fix.
