### ISSUE TITLE
Unable to undo bad author merge

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8232]
This bad merge of two different authors with the surname [Weizsäcker](https://openlibrary.org/authors/OL686128A) can't be undone and gives an error.

### Relevant url?
https://openlibrary.org/recentchanges/2011/01/02/merge-authors/42481471

It says that the error was logged as 2023-08-09/231910284145

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected: Undo works

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
There are a few issues about this, @jimchamp is organizing them up.

**Comment by LeadSongDog** [comment]
Perhaps the real issue here is determining how a bad merge went uncaught for 150 months rather than 150 milliseconds.

**Comment by tfmorris** [comment]
This has the same root cause as #5664 (but I don't seem to be able to tag it as a duplicate).
