### ISSUE TITLE
Degraded website performance, 500s

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8242]
### Summary

- **What is wrong?**

- Many pages, including work page, subject page, and edit page seemingly 500'ing.

- **What caused it?**

- **What was tried?**

    - `sudo /etc/init.d/memcached restart` on memcache[0-2]
    - added to `ol-www0` `/opt/openlibrary/docker/web_nginx.conf`:
        ```
        if ($http_user_agent ~ (Bytespider) ) {
            return 429;
        }
        ```

- **What fixed it?**

- **Followup actions:**

### Steps to close

1. [x] Assignment: Is someone assigned to this issue? (notetaker, responder)
2. [x] Labels: Is there an `Affects:` label applied?
3. [ ] Diagnosis: Add a description and scope of the issue
4. [ ] Updates: As events unfold, is notable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [ ] "What caused it?" - please answer in summary
6. [ ] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by mekarpeles** [comment]
<img width="303" alt="Screenshot 2023-08-29 at 10 30 02 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/5edac4c0-e538-4652-8382-bae6abd4faef">

**Comment by mekarpeles** [comment]
Also increased load to cover server
![image](https://github.com/internetarchive/openlibrary/assets/978325/ac3788ad-2b1c-4fa6-b41c-da2c10147acc)

**Comment by tfmorris** [comment]
That chat conversation talks about archive.org, but openlibrary.org has been sluggish for days, including a much higher rate of 503s. During slowdowns the rate of 503s approach 100%, so I just stop using the site until it clears.

**Comment by mekarpeles** [comment]
I believe the new nginx rules (which need to be submitted across `openlibrary/docker/covers_nginx.conf` + `openlibrary/docker/web_nginx.conf`) helped alleviate some of the strain.

```
if ($http_user_agent ~ (Bytespider) ) {
    return 429;
}
```
