### ISSUE TITLE
Allow creation of lists via hand-crafted links of seed items

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#8245]
A link like the following (you may need to change the username in the url to your own) will pre-populate the add a list page with the specified items:

https://openlibrary.org/people/davidscotson/lists/add?name=The+Murderbot+Diaries&seeds=OL24747433W,OL17914663W,OL27481052W,OL19753589W,OL26794585W,OL24349461W,OL20735675W,OL20805971W,OL33402895W

This superficially looks the same as if you visited the "add a list" url and manually added the items. But on saving you get a 500 error if you use the url method.

On investigation, I believe this is due to the HTML form not specifying an "action" attribute, and so it tries to POST the form the to the full url, rather than just "https://openlibrary.org/people/davidscotson/lists/add".

Adding that shorter url to the <form> as an action attribute makes this work again.

### Details

- **Logged in (Y/N)?** Y

- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
What a headache! Took me so long to figure out what the root issue was, but I think I have a better fix here: https://github.com/internetarchive/openlibrary/pull/8463 .
