### ISSUE TITLE
Suggestion for a cleaner homepage by skipping books that aren't instantly readable

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#8247]
I was thinking that if it was possible to be sure that all the items in the homepage carousel were available to read or borrow, then we could link the book cover images directly to that and claim back some space currently given to "Borrow" (40 on current page), "Read" (5, and possibly not an interesting distiction from "Borrow" for the average home page vistor), "Not in Library" (5), "Preview Only", (1) "Join List" etc.

Attached is a quick mockup of what this might look like, with some other styles removed, the book size increased slightly to make use of the extra space restored and the names of some of the carousels changed a little to re-inforce the call to action of "these books are available for you to read right now".

The link to the work record could be restored but possibly only shown on book hover, "more info on Flatland by Author".

![bigger_books](https://github.com/internetarchive/openlibrary/assets/7288187/2978d402-ce26-4292-82d7-f7c4b8125fae)

**Comment by mekarpeles** [comment]
This is a great idea for us to keep in mind and we continue to evolve the homepage and other carousels. I think the general idea (if we want to create a new issue) is to add the **ability** for Archive.org-powered carousels to show only available books.

More generally, realtime availability info is not in our solr instance (e.g. "available now" -- only that it is a type of book that is "available" categorically) and we use solr to populate most carousels.

For the time being going to mark as closed (the idea has been discussed). We can also bring up during next design call but for issue hygiene, closing
