### ISSUE TITLE
Rename merge queue files for consistency

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8253]
### Short Summary:
Refactor merge request table such that there is more parity between the JS and HTML files.

### Background:
Names of files related to the librarian merge queue have become inconsistent over time:

#### Current file names
| Component | JS filename | HTML filename | LESS filename |
|--------|--------|--------|--------|
| Table header | merge-request-table/LibrarianQueue/TableHeader.js | `None` | components/merge-request-table.less |
| Table row | merge-request-table/LibrarianQueue/TableRow.js | `None`| components/merge-request-table.less |
| Base component (the whole table) | merge-request-table/LibrarianQueue.js | merge_queue/merge_queue.html | components/merge-request-table.less | 

I figure that the naming conventions for the JS and LESS files are in alignment, and no changes are required.  Our HTML template tile,,however, has an entirely different name, and would be difficult to find by a new developer (at least not without the help of somebody who is familiar with this code).  It's also kind of odd that there is a JS file for each component, but only one template file.

### Main Requirements:
1. Create two new template files: one for the table header, and one for a single table row.  Move existing header and table row HTML into their respective, newly created files.
2. Ensure that the following filepaths are used:

#### Updated file names
| Component | JS filename | HTML filename |
|--------|--------|--------|
| Table header | merge-request-table/MergeRequestTable/TableHeader.js | merge_request_table/table_header.html |
| Table row | merge-request-table/MergeRequestTable/TableRow.js | merge_request_table/table_row.html |
| Base component (the whole table) | merge-request-table/MergeRequestTable.js | merge_request_table/merge_request_table.html |

### Checklist:
- [ ] JS filepaths have been updated as per the above "Updated file names" table.
  - [ ] All references to these files have been updated.
- [ ] New templates have been created
  - [ ] table_header.html
  - [ ] table_row.html
- [ ] Existing merge_queue/merge_queue.html template has been updated:
  - [ ] Change filepath to merge_request_table/merge_request_table.html
  - [ ] Replace header and table row code with references to the new templates
- [ ] Update all references to the merge table template file

**Comment by Eds-Dbug** [comment]
I would like to take this issue!
