### ISSUE TITLE
Update node install method for olbase

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8255]
Right now when you build olbase you get this warning:
```
=> [ 4/20] RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -     && apt-get i  57.2s
 => => #                           SCRIPT DEPRECATION WARNING                                  
 => => # ================================================================================      
 => => # ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓      
 => => # ================================================================================      
 => => # TO AVOID THIS WAIT MIGRATE THE SCRIPT                                                  
 => => # Continuing in 60 seconds (press Ctrl-C to abort) ...                                   
```

It says:
```
  This script, located at ${bold}https://deb.nodesource.com/setup_X${normal}, used to
  install Node.js is deprecated now and will eventually be made inactive.

  Please visit the NodeSource ${bold}distributions${normal} Github and follow the
  instructions to migrate your repo.
  ${underline}${green}${bold}https://github.com/nodesource/distributions${normal}

  The ${bold}NodeSource${normal} Node.js Linux distributions GitHub repository contains
  information about which versions of Node.js and which Linux distributions
  are supported and how to install it.
  ${underline}${green}${bold}https://github.com/nodesource/distributions${normal}
```

### Steps to Reproduce

1. Run `docker build -t openlibrary/olbase:my-test-label -f docker/Dockerfile.olbas`

### Proposal & Constraints

We should probably install using their recommended method:
https://github.com/nodesource/distributions#debian-and-ubuntu-based-distributions

I'll take a look at fixing this, which will be easier after https://github.com/internetarchive/openlibrary/pull/8254 is merged :)

### Related files

https://github.com/internetarchive/openlibrary/blob/bb152d23c004f3d68986877143bb0f83531fe401/docker/Dockerfile.olbase#L37-L39

### Stakeholders

@cclauss

**Comment by sahlhhjdsj** [comment]
![51-05-8](https://github.com/internetarchive/openlibrary/assets/153050800/8b054fec-c61b-4907-919f-78c096614e3c)
![51-05-8](https://github.com/internetarchive/openlibrary/assets/153050800/dc5d87bb-3c28-47c0-8b25-8c3c997a6168)
