### ISSUE TITLE
infosoup identifier 

### ISSUE THREAD

**Issue by kb9mwr** [internetarchive/openlibrary#8269]
It would be desirable for a way to add identifer links to records on infosoup, ex:

https://infosoup.bibliocommons.com/v2/record/S181C82178

**Comment by mekarpeles** [comment]
Moved to #8271

**Comment by hornc** [comment]
Which is the identifier of the item in the example?

Infosoup looks like a local / regional library system and it's not clear the the URLs are persistent or contain an identifier.

The page has a different identifier listed: CARL0000082178

I'm not sure if the criteria for external identifiers are documented anywhere, but I'd say they are only appropriate for large national libraries that act as permanent archives with well established identifier formats which can be used as permalinks.

Links to local library catalog current holdings aren't likely to be permanent.

**Comment by mekarpeles** [comment]
Added

```
-   label: Infosoup
    name: infosoup
    notes: e.g. https://infosoup.bibliocommons.com/v2/record/
    url: https://infosoup.bibliocommons.com/v2/record/@@@
```

to https://openlibrary.org/config/edition.yml:
https://openlibrary.org/config/edition?v=941
