### ISSUE TITLE
Why are PDFs of some books are not available for download?

### ISSUE THREAD

**Issue by learner007** [internetarchive/openlibrary#827]
Some of the books on OpenLibrary can be read online but there is option to download only ePub (and not PDF). Epub often has many errors. (Example: https://archive.org/details/cardgamesforsmar00phdm_0)

If the book is available to read online, that means the PDF should be available, right?

**Comment by LeadSongDog** [comment]
So on OL that’s https://openlibrary.org/books/OL370151M

It does seem odd not to have the PDF.

**Comment by guyjeangilles** [comment]
It looks like a decision needs to be made about this. @mekarpeles defaulting to asking you whether or not this request should be implemented.

**Comment by cdrini** [comment]
@mekarpeles could this be an issue with the IA import process not generating the necessary file? I heard that sometimes happens.

**Comment by cdrini** [comment]
It's an easy-to-fix issue in the derive process; @JeffKaplan was able to fix the specified book. Feel free to create more issues if you find other such books!

**Comment by markbult** [comment]
No download option here either: https://archive.org/details/iscience0000unse_l5m5/page/n3/mode/2up

**Comment by LeadSongDog** [comment]
I’m confused. Are pdf downloads permitted while in copyright? I thought that was the whole point of controlled lending.
