### ISSUE TITLE
In Firefox - can't remove items from My Reading Log after refresh

### ISSUE THREAD

**Issue by Yonial** [internetarchive/openlibrary#829]
This issue is browser based, and happens in Firefox (does not reproduce in Chrome).

Reproduce:

1. Go to My Reading Log (make sure you have at least one item in the "Want to Read" list).
2. Items in the list will have "Want to Read + <check-mark>" in the drop down menu - expected behavior.
3. Refresh browser.
4. Items now show "Remove" (without the check-mark).
5. Reselecting "Remove" does not remove the item from the list.

![image](https://user-images.githubusercontent.com/10077523/37008426-c2a93aae-2096-11e8-920b-4aff7781ada2.png)

**Comment by guyjeangilles** [comment]
I can duplicate this bud as described on Windows 10 FF70.0 .  However, work arounds exist. If I don't refresh the page, the book is removed as expected. If I change the book to "Currently Reading", then click "Remove", the book is removed as expected.

**Comment by jdlrobson** [comment]
We were relying on element order (yuck!) I've submitted a pull request to fix this. I have recommended we do away with the count of books on a given shelf though at the trade off of not having to reload the page on every movement between shelves.
