### ISSUE TITLE
Deprecated author `website` property still in use on 3k records and UI

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#8293]
Remove deprecated author `website` field and UI elements.

Taken from: https://github.com/internetarchive/openlibrary-client/issues/56

Author view page still uses the `website` value for the UI:
https://github.com/internetarchive/openlibrary/blob/c561294109a60d45a9c6c32649b8ece54b286e24/openlibrary/templates/type/author/view.html#L102-L106

https://openlibrary.org/authors/OL2469657A/Gulshan_Sachdeva
but the edit UI shows it as deprecated.

![image](https://github.com/internetarchive/openlibrary/assets/905545/ba804582-0546-4475-a326-2898e2f58a42)

In the August 2023 dump there are only ~3k instances of this field.

```
zgrep -c '"website":' ol_dump_authors_2023-08-31.txt.gz
2982
```

- [x] The `website` URLs should be transferred to `links`, or possibly dropped if the URL is dead?
- [ ] Then references to `website` can be dropped from the code (UI / model)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by rkritika1508** [comment]
Hi, I am looking to get involved in OpenLibrary community and contribute here, can I start with this issue?

**Comment by hornc** [comment]
@rkritika1508 Sure, thank you! That would be great.

I imagine this as having a UI component to remove the deprecated UI elements, and a data component to move the old `website` to `links`. If you can do the UI part, I can focus on the data, which I think should be done as a one off bot type task.

**Comment by jimchamp** [comment]
@hornc, did you already take care of the data portion of this issue?  The UI/model changes seem like a good first issue.  Can this be done before the data is corrected?  I'm thinking that order doesn't matter in this case, but want to be sure before moving forward.

**Comment by jimchamp** [comment]
It's unclear to me if the data has been corrected or not, but I think that it is safe to proceed with the UI changes (@hornc, correct me if I'm wrong).

It would be helpful if a new contributor removed the references to `Author.website` from [author pages](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/author/view.html) and [edit author pages](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/author/edit.html).

**Comment by Dwayne-Lacey** [comment]
Hi, if this issue still needs worked on I'd love to take it on.

**Comment by jimchamp** [comment]
Thanks, @Dwayne-Lacey!  Will likely merge your work later today.

@hornc, I'm assuming that you're still going to clean up the data.  This issue can probably be closed once that is complete.

**Comment by hornc** [comment]
Thanks @Dwayne-Lacey for the UI work! I have just moved all the remaining `website`s into `links`.
