### ISSUE TITLE
Spring Cleaning: Get P2 issues <50 per Lead (Quarterly)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8295]
Our issue tracker has a high volume of issues and so it's important that our team has a way to easily filter out ones we've identified as of importance. We use the `Priority` labels to surface the most important ones. Every week, we go through every issue that is either `Priority: 0` (fix NOW) or `Priority: 1` (ideally is fixed by end of week).

We presently don't have hard-and-fast rules around expectations for `Priority: 2` issues and, perhaps as a result, we have more P2 issues than seem manageable†, given their importance -- [173](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22) of our 753 issues are P2 (~25%).

†Here manageable means distributing & reprioritizing P2 issues in such a way as to achieve the outcome that all of our P2 issues are being considered/factored in our yearly & monthly Milestone plans and that important issues are not falling through the cracks.

## Proposal

Towards this goal of getting a better grasp around our P2 issues, proposing:

* Each lead aims for <= 50, P2 issues (2 pages), though ideally <=25 (1 page), which may be done by...
  * Dropping the priority of issues from P2
  * Transferring the lead of an issue to an amenable lead 
  * Update and or close any issues as relevant
* Each quarter, as part of our team quarterly review, we have homework to enforce this suggestion and refresh our memory of what important issues are in our purview

## Execution

* [All P2 issues](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22) ~173
  * [x] [@mekarpeles](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40mekarpeles%22) ~25
  * [x] [@jimchamp](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40jimchamp%22+) ~16
  * [x]  [@cdrini](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40cdrini%22+) ~83
  * [x] [@scottbarnes](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40scottbarnes%22+) ~7 
  * [x] [@cclauss](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40cclauss%22+) ~12
  * [x] [@seabelis](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40seabelis%22+) ~3
  * [x] [@hornc](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+label%3A%22Lead%3A+%40hornc%22+) ~3
  * [x] [other leads](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+label%3A%22Priority%3A+2%22+-label%3A%22Lead%3A+%40mekarpeles%22+-label%3A%22Lead%3A+%40cdrini%22+-label%3A%22Lead%3A+%40jimchamp%22+-label%3A%22Lead%3A+%40scottbarnes%22+-label%3A%22Lead%3A+%40cclauss%22+-label%3A%22Lead%3A+%40seabelis%22+) ~15

**Comment by Eds-Dbug** [comment]
I would like to contribute to the cleaning.

**Comment by RayBB** [comment]
@Eds-Dbug would you like to help by investigating #395 ? If so, please try to reproduce the issue and comment on your findings. If it is still an issue then we should investigate fixing it. Feel free to message me on Slack with questions as well.

**Comment by Eds-Dbug** [comment]
Ill take a look.
