### ISSUE TITLE
Export public reading logs (public and private) as json,csv

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#830]
cc: @bnewbold who suggested this feature

**Comment by salman-bhai** [comment]
Export as in should they be downloadable as a CSV/JSON file or should it redirect to another page which will have CSV/JSON rendered ?

**Comment by bnewbold** [comment]
Export as in download.

**Comment by salman-bhai** [comment]
I'd like to work on this for this weekend @mekarpeles

**Comment by guyjeangilles** [comment]
@salman-bhai Any updates?

**Comment by mekarpeles** [comment]
We have an MVP for this at https://openlibrary.org/account/import
