### ISSUE TITLE
how to get available languages of a specific work

### ISSUE THREAD

**Issue by alicimen0614** [internetarchive/openlibrary#8301]
### Question
 I want to get a specific works available languages , trending and searching api provides languages but works and category api doesnt provide it how can I achieve it?

### Stakeholders

![githubissue](https://github.com/internetarchive/openlibrary/assets/93056138/3956966d-6e9b-49a5-ba5f-cfa44c6ae14d)

**Comment by mekarpeles** [comment]
I think you want to use the https://openlibrary.org/search.json?q= API as I believe this will return language

**Comment by alicimen0614** [comment]
I do know that search api returns language as ı pointed out on my question the question was can we  return languages from a specific work https://openlibrary.org/works/OL1968368W.json for example this doesn't have it

**Comment by tfmorris** [comment]
There are a lot of obscure corners of the API which aren't very well documented. There are a couple of ways to do this:

* https://openlibrary.org/search.json?q=key:/works/OL1968368W&fields=key,title,language (it won't work without the `/works/` prefix on the key)
* https://openlibrary.org/works/OL1968368W/editions.json - Note that this is paginated, so you'll either need to add `&limit=100` or do another call with the URL from the `links.next` field (ie add `?offset=50`).

If you want to browse subjects, you can use:

* https://openlibrary.org/search.json?subject=Contr%C3%B4le%20(Psychologie.)&fields=key,title,language,subject

Naturally, the different APIs return the language information in different formats, so be prepared to handle that.

**Comment by alicimen0614** [comment]
> There are a lot of obscure corners of the API which aren't very well documented. There are a couple of ways to do this:
> 
> * https://openlibrary.org/search.json?q=key:/works/OL1968368W&fields=key,title,language (it won't work without the `/works/` prefix on the key)
> * https://openlibrary.org/works/OL1968368W/editions.json - Note that this is paginated, so you'll either need to add `&limit=100` or do another call with the URL from the `links.next` field (ie add `?offset=50`).
> 
> If you want to browse subjects, you can use:
> 
> * https://openlibrary.org/search.json?subject=Contr%C3%B4le%20(Psychologie.)&fields=key,title,language,subject
> 
> Naturally, the different APIs return the language information in different formats, so be prepared to handle that.

Thank you that was helpful
