### ISSUE TITLE
Page selector empty on "My Books" import and export page

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8304]
It looks like there may be no option to the import/export page in the breadcrumb selector for My Books pages.

### Evidence / Screenshot (if possible)
![red_box](https://github.com/internetarchive/openlibrary/assets/28732543/09cac6dd-59cb-4a99-8ef4-577e444a7c67)
_Selector in question is inside the red box, above_

### Relevant url?
https://openlibrary.org/account/import

### Steps to Reproduce

While logged in:
1. Go to https://openlibrary.org/account/import
2. Look at the My Books page selector

* Actual: Selected page is an empty string.
* Expected:Selected page is something like "Imports & exports"

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?**Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Add option for import/export page to the My Books page selector.

**Comment by sbwhitt** [comment]
Hey @jimchamp, I have a working solution for this when it's ready to be assigned.

**Comment by jimchamp** [comment]
Thanks @sbwhitt! Feel free to reach out if you have any questions.
