### ISSUE TITLE
Big spikes in /books/* traffic causing performance issues

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8319]
There have been noticeable spikes in `/books/` traffic twice-a-day, every two days since ~September 16th. Causing performance issues throughout the site during the spike, and (speculating) possible causing our memcaches to be less effective after the spike.

### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/6251786/bcca933f-8723-47ec-b961-c1635521259d)

![image](https://github.com/internetarchive/openlibrary/assets/6251786/b0d1bcfc-2adc-4388-804d-37844a95b6fe)
https://wwwb-grafana.us.archive.org/d/000000176/open-library-dev?orgId=1&refresh=1m&viewPanel=7&from=now-7d&to=now
### Stakeholders
@mekarpeles @seabelis

**Comment by cdrini** [comment]
You can see the almost tripling of traffic here:

```
$ sudo cat access.log | grep -F 'GET /books/OL' | grep -oE '2023:..' | uniq -c
  34997 2023:06
 146560 2023:07
  75401 2023:08
  70993 2023:09
  79410 2023:10
  74192 2023:11
  75484 2023:12
  74462 2023:13
  70714 2023:14
  64086 2023:15
  73054 2023:16
 184519 2023:17
 179750 2023:18
  84003 2023:19
  59451 2023:20
  63961 2023:21
  67901 2023:22
  67744 2023:23
  31597 2023:00
```

**Comment by cdrini** [comment]
This is as much as I can try to hone it down to a specific pattern. It appears to not be bots, or JSON requests, or pages with a referrer set...

```
$ sudo cat access.log | grep -F 'GET /books/OL' | grep -v 'bot' | grep -vE 'GET /books/OL[0-9]+M.json' | grep -F '"-"' | grep -oE '2023:..' | uniq -c
  24287 2023:06
 111525 2023:07
   3580 2023:08
   2083 2023:09
   3201 2023:10
   2982 2023:11
   5322 2023:12
   2736 2023:13
   2878 2023:14
   2953 2023:15
   3350 2023:16
 129549 2023:17
 131763 2023:18
  23151 2023:19
   3044 2023:20
   2672 2023:21
   3169 2023:22
   4700 2023:23
   3430 2023:00
```

**Comment by cdrini** [comment]
This hones in on it further

```sh
$ sudo cat access.log | grep -F 'GET /books/OL' | grep -v 'bot' | grep -vE 'GET /books/OL[0-9]+M.json' | grep -F '"-"' | grep -F 'Safari/' | grep -vF '?' | grep -vE 'GET /books/OL[0-9]+M\.' | grep -oE '2023:..' | uniq -c
  24046 2023:06
 109673 2023:07
   1883 2023:08
    714 2023:09
    701 2023:10
    829 2023:11
   3128 2023:12
    964 2023:13
   1152 2023:14
   1501 2023:15
   1209 2023:16
 127129 2023:17
 129301 2023:18
  20705 2023:19
   1228 2023:20
    842 2023:21
   1732 2023:22
   2439 2023:23
   2412 2023:00
     63 2023:01
```

**Comment by cdrini** [comment]
No outlier in top IP during one of the hours of high traffic:

```
$ sudo cat access.log | grep -F 'GET /books/OL' | grep -v 'bot' | grep -vE 'GET /books/OL[0-9]+M.json' | grep -F '"-"' | grep -F 'Safari/' | grep -vF '?' | grep -vE 'GET /books/OL[0-9]+M\.' | grep -F '2023:17' | awk '{print $1}' | sort | uniq -c | sort -nr | head -n 30
    296 XXX.XXX.XXX.XXX
    289 XXX.XXX.XXX.XXX
    288 XXX.XXX.XXX.XXX
    288 XXX.XXX.XXX.XXX
    287 XXX.XXX.XXX.XXX
    286 XXX.XXX.XXX.XXX
    283 XXX.XXX.XXX.XXX
    282 XXX.XXX.XXX.XXX
    282 XXX.XXX.XXX.XXX
    281 XXX.XXX.XXX.XXX
    281 XXX.XXX.XXX.XXX
    280 XXX.XXX.XXX.XXX
    280 XXX.XXX.XXX.XXX
    280 XXX.XXX.XXX.XXX
    279 XXX.XXX.XXX.XXX
    279 XXX.XXX.XXX.XXX
    279 XXX.XXX.XXX.XXX
    279 XXX.XXX.XXX.XXX
    278 XXX.XXX.XXX.XXX
    278 XXX.XXX.XXX.XXX
    277 XXX.XXX.XXX.XXX
    277 XXX.XXX.XXX.XXX
    277 XXX.XXX.XXX.XXX
    276 XXX.XXX.XXX.XXX
    276 XXX.XXX.XXX.XXX
    276 XXX.XXX.XXX.XXX
    275 XXX.XXX.XXX.XXX
    275 XXX.XXX.XXX.XXX
    274 XXX.XXX.XXX.XXX
    274 XXX.XXX.XXX.XXX
```

Although they look eerily well distributed... And checking the top IP, it was only active during the spikes in traffic, but the traffic itself looks completely normal...

```
$ sudo cat access.log | grep -F 'XXX.XXX.XXX.XXX' | grep -oE '2023:..' | uniq -c                                               49 2023:06
    222 2023:07
      2 2023:08
    307 2023:17
    227 2023:18
     45 2023:19
```

**Comment by mekarpeles** [comment]
We may want to confirm the same IPs are hitting us across these spikes (i.e. re-using IPs)

1. either using Sam's tool
2. Disabling in nginx.conf the seed key deanonymization temporarily

**Comment by mekarpeles** [comment]
patch deployed https://github.com/internetarchive/openlibrary/blob/master/docker/web_nginx.conf with

`limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;`

```
location ~ ^/books/(?!.+\.json) {
    limit_req zone=one burst=5 nodelay;
}
```

To rate limit non json requests to Open Library book pages

**Comment by mekarpeles** [comment]
![image](https://github.com/internetarchive/openlibrary/assets/978325/23a5427b-6e27-4f85-8b49-07a68b48a02f)

We've been able to limit the impact by denying access to
```
deny 45.128.106.0/24;
deny 45.128.107.0/24;
```

**Comment by mekarpeles** [comment]
@samuel-archive suggests rather than installing a custom nginx as per https://github.com/internetarchive/openlibrary/blob/master/docker/Dockerfile.olbase#L50-L56, we instead use vanilla nginx and a log to pipe and obfuscate there.
