### ISSUE TITLE
#8203 may not have deployed fully

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#8320]
#8203 was deployed to the main site recently but I see differences between live and testing, with testing behaving more as I expect and live seeming as if it's not been deployed (or possibly partly deployed?)

### Steps to Reproduce

When editing an author, you should be able to paste in a storygraph id, and the id selector should detect it as Storygraph, so you don't need to select that. After you  click the "set" button, the selector should reset to "select one".

Currently I see the above behaviour on testing.openlibrary but not on live.

I tested a moment ago with eff57134-0d82-4193-9241-522ef5f2fa19 for https://openlibrary.org/authors/OL221294A/Martha_Wells/edit but I've seen it with other authors, so I don't think it's specific based on Author or id.

Similar with Amazon Author ID, detected on testing.openlibrary but not on live (B000APZA1O is the ID for Marth Wells)

And similar again with ISNI with spaces ("0000 0000 6309 5407" for Martha Wells), this should now be detected where before it would only recognize 16 character ISNI without spaces.

### Details

- **Logged in?** Y
- **Environment (prod/dev/local)?** prod vs testing

Note there's a JS error in the console on the edit page: "Uncaught TypeError: this is undefined" thought it shows up on both testing and live so may not be related.

### Stakeholders
@cdrini

**Comment by davidscotson** [comment]
The code seems present in openlibrary/components/AuthorIdentifiers.vue in git, but if I search in the browser debugger for the string 'storygraph', which should be in JS as a literal, it's not found on the live JS, but gets found on testing as part of the file:

static/build/components/production/ol-AuthorIdentifiers.min.js

**Comment by mekarpeles** [comment]
Our hypothesis is during last deploy, the vue assets did not rebuild. We'll do another deploy this week and monitor.

**Comment by mekarpeles** [comment]
See #8361. Deploy went out, the remaining steps will be tracked in the postmortem issue
