### ISSUE TITLE
Book/work page breaks when title is very long

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8323]
### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/921217/c2d40a8b-c086-40f9-9923-cef65203d042)

### Relevant url?

https://openlibrary.org/works/OL33860896W/

### Steps to Reproduce

1. Go to the page

* Actual: Page is deformed
* Expected: Page works with long title

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

**Comment by davidscotson** [comment]
Note that it's not the long title exactly, it's one of the "words" in the title being long, specifically "&#960;&#959;&#955;&#953;&#964;&#953;&#954;&#942;&#962;" which is an encoded form of "πολιτικής" apparently.

So a manual fix for this specific title, and possibly something worth doing at a larger scale would be to convert encoded characters. But the same problem shows up with sufficiently long real words in e.g. German.

The recommended fix these days for long words in CSS is to use `overflow-wrap: break-word` like is done on the title in the cover image fallback text. Though in this specific case there's an interaction with flexbox, so a `min-width: 1%` needs to be set on the parent flex container or else it gets ignored. I'll create a PR with that fix.

**Comment by RayBB** [comment]
I'm not the CSS expert but that fix sounds reasonable to me. I assigned you this for now 👍
