### ISSUE TITLE
Are i18n and i18n_page used anymore, if so how?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8329]
### Question

Are i18n and i18n_page used anymore, if so how?

- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates/type/i18n
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates/type/i18n_page
- https://github.com/internetarchive/openlibrary/blob/49b6ae6ae355f3d97017b33a936efbeb792fc06a/openlibrary/plugins/openlibrary/types/i18n.type
- https://github.com/internetarchive/openlibrary/blob/49b6ae6ae355f3d97017b33a936efbeb792fc06a/openlibrary/plugins/openlibrary/types/i18n_page.type

I'm struggling to see how either of these pages/types are used anymore.
If they are used, can someone show me how to use them so I can move the inline js out of the pages?
If not, is it okay for us to delete them?

### Additional context

Related to #4474

### Issue resolution criteria

When we know how to interact with these pages or if we can delete them.

**Comment by cdrini** [comment]
type/i18n_page are used, eg openlibrary.org/subjects.fr . i18n are I think unused.
