### ISSUE TITLE
Remove old i18n code

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8336]
Why:
Part of the epic to remove inline js #4474 
Can be removed per #8329

### Related files

Remove:
* https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates/type/i18n
* https://github.com/internetarchive/openlibrary/blob/49b6ae6ae355f3d97017b33a936efbeb792fc06a/openlibrary/plugins/openlibrary/types/i18n.type
* Any other references to these 
  * This is a little tricky because "i18n" is written often in the codebase but there shouldn't be many references to this actual type.

### Stakeholders

@RayBB

**Comment by piyush-poddar** [comment]
I would like to work on this issue #8336

**Comment by RayBB** [comment]
@piyush-poddar sounds good. Go ahead and tag me when you open your PR. Let me know if you have questions.

**Comment by piyush-poddar** [comment]
@RayBB I have opened [PR](https://github.com/internetarchive/openlibrary/pull/8373), please review it.

**Comment by piyush-poddar** [comment]
@RayBB Can you give some updates about my [PR](https://github.com/internetarchive/openlibrary/pull/8373)?

**Comment by RayBB** [comment]
We are currently waiting on a review/merge from someone with merge power (@cdrini @mekarpeles @cclauss etc).
I know they're pretty busy with the [annual celebration](https://blog.archive.org/2023/10/06/join-us-for-our-annual-celebration-thursday-october-12/) coming up so it might not be merged this week.

**Comment by piyush-poddar** [comment]
@RayBB Okay no problem. Can you please add an approving review, so that my [PR](https://github.com/internetarchive/openlibrary/pull/8373) is accepted in the Hacktoberfest.
