### ISSUE TITLE
Fix user activation flow so users can get back to Open Library

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#834]
Currently when new users signup on Open Library, they are emailed a link to activate on archive.org. They are then shown a login link for Archive.org instead of Open Library. I imagine this could be confusing users and we may want to watch new users go through this flow to confirm this hypothesis.
cc: @evanminto -- a test case for Friday lunch?

**Comment by evanminto** [comment]
Yeah we can definitely test this.

**Comment by mekarpeles** [comment]
https://git.archive.org/ia/petabox/tree/jim/xauthn-extensions/www/sf/services/xauthn
