### ISSUE TITLE
Subject tag autocomplete no longer sorts by frequency

### ISSUE THREAD

**Issue by mheiman** [internetarchive/openlibrary#8344]
When I developed autocomplete for subject tags, the results returned were automatically sorted by frequency — the most used subjects that matched were first on the list. This not only produced useful results, but helped concentrate the usage of particular subjects where multiple similar labels exist for a single topic, improving the quality of subject pages.

In subsequent refactoring of autocomplete support, this frequency sorting was lost.

### Steps to Reproduce
Edit a work and start typing in one of the subject fields to display the list of matching subjects.

* Actual: Subject suggestions are sorted in an apparently random order
* Expected: Subjects should be sorted with the "better" (more frequently used) choices at the top.

### Proposal & Constraints
I will be submitting a PR that restores the SOLR query that produces the frequency-sorted results.

### Stakeholders
@mheiman @cdrini

**Comment by davidscotson** [comment]
There was a recent bug about author autocomplete ordering too: #8299, which suggests non-subject items may be similarly affected.
