### ISSUE TITLE
Add ability to import reading log / bookshelves from Goodreads

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#835]
Goodreads provides a way to download/export a list of books from one's bookshelves.

This feature would allow a user to take an exported dump of their reading log from goodreads and then add each of these books to their Open Library account.

1) The user would go to a new url like /account/import/goodreads which shows a UI to upload a (e.g. csv) file
2) this UI would POST to a corresponding /account/import/goodreads backend API which would... likely hit the goodreads API and get the book's ISBN. It would then lookup the corresponding openlibrary edition by this ISBN and then invoke a readinglog action like "add to *Want to Read*"

For now, I think we can get away with *only* importing the user's "want to read", "currently reading" and "already read" reading log and skip all the user's other goodreads lists.

**Comment by caitlinpatricia** [comment]
Yes please!!

**Comment by mekarpeles** [comment]
See:
```
/openlibrary/scripts/2010/04$ ls`
build_goodreads_openlibrary_mapping.rb   import_goodreads_ids.py 
```

**Comment by rohitjain00** [comment]
I have not executed the script, but if the script seems to work this issue needs to be closed?

**Comment by fazlerabbi37** [comment]
@mekarpeles can this be added under the `Reading Log` section, so we may import the GoogReads export?

**Comment by cdrini** [comment]
@rohitjain00 The feature is not complete; that script was archived 9 years ago, so it probably doesn't work, and needs to be integrated into the UI. If someone wants to try taking this on, please feel free!

**Comment by guyjeangilles** [comment]
@mekarpeles This was slated for a *2018 Q2* milestone. I'm labeling it as backlogged. Are there any plans to proceed with the aforementioned script?

**Comment by mekarpeles** [comment]
@cdrini did you at some point have a branch to do something like this? Would you like to be assignee?

**Comment by tabshaikh** [comment]
Note-to-self: to remind to update the Nginx file size for increasing the time of uploads and also for logging in and downloading the files ...
