### ISSUE TITLE
Minor tweak to cover alt text

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#837]
At:
https://github.com/internetarchive/openlibrary/blob/78219a4e2d48584246617fd682088b58be06841a/openlibrary/templates/covers/book_cover_work.html#L13

it would help to insert a comma into the $title $_('by')  for better legibility, or to ease into i18n, lose the 'by' and just use a space wrapped foreslash, so $title $_(' / ')

**Comment by mekarpeles** [comment]
For these minor tweaks, it may be just as easy to submit a pull request with the fix so we can review and merge it :)

**Comment by LeadSongDog** [comment]
Pretty sure I can’t run the platform on my phone;-(

**Comment by mekarpeles** [comment]
fair point!

**Comment by salman-bhai** [comment]
Hi I saw this open, so sent a PR! Hope that's fine @LeadSongDog
