### ISSUE TITLE
Remove inline js: account/ia_thirdparty_logins.html

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8379]
Remove the inline JS from this file following the recommended steps in #4474

### Proposal & Constraints

This one should be relatively straightforward.

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/account/ia_thirdparty_logins.html

**Comment by yashwanthvarma18** [comment]
Hey @RayBB Please assign this to me

**Comment by RayBB** [comment]
@premtw you are assigned now.
@yashwanthvarma18 since you're assigned to the other one lets let premtw start his. If you finish the first one there are other open issues we can look at.

**Comment by premtw** [comment]
Thanks @RayBB

**Comment by RayBB** [comment]
@premtw are you still working on this?

**Comment by premtw** [comment]
@RayBB I yet to start. Stuck with some other PRs. Will start by today

**Comment by RayBB** [comment]
@premtw how's it going with this?

**Comment by AdwaitSalankar** [comment]
@RayBB Can you assign me? I can work on this.

**Comment by RayBB** [comment]
@AdwaitSalankar since we haven't heard from Prem in 2 weeks you're assigned.

**Comment by shahad1307** [comment]
@RayBB Hello I'm a student in CMU and I have a project. I'm interested in working on this issue. Looks doable could do assign me?

**Comment by RayBB** [comment]
@shahad1307 this issue already has a PR open that addresses it.
You might try the GitHub issue forms task (which I cant pull up on my phone now)
