### ISSUE TITLE
Remove inline js: books/breadcrumb_select.html

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8380]
Remove the inline JS from this file following the recommended steps in #4474

### Proposal & Constraints

This should be relatively easy to make and test.

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/breadcrumb_select.html

**Comment by yashwanthvarma18** [comment]
Hey @RayBB Please assign this to me

**Comment by RayBB** [comment]
@yashwanthvarma18 you are assigned now.

**Comment by RayBB** [comment]
@yashwanthvarma18 are you still working on this?

**Comment by imperial-chief** [comment]
Hello @RayBB sir,
I read through #4474 but i could not completely understand the steps.
I still want to work on this. Shall i work on this?

**Comment by RayBB** [comment]
@imperial-chief you can still work on it.
Which part of the steps are you getting stuck on?

**Comment by imperial-chief** [comment]
This are the steps:

Verify the page still works as before without any JS in the error console.
Make sure the JS is loaded. See note below.
Replace any references to window.q.push with $(fn)

**Comment by RayBB** [comment]
@imperial-chief Do you have a local instance of open library setup already? If not these are the [setup steps](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md).

**Comment by imperial-chief** [comment]
yes. i have set up.
i solved your last issue of adding searching tips.

**Comment by RayBB** [comment]
@imperial-chief have you tried moving the code and rebuilding the js by running `make js` in the docker container?

here is an example of a similar pr: https://github.com/internetarchive/openlibrary/pull/8374/files

**Comment by imperial-chief** [comment]
ok sir.
i will start working on it.
