### ISSUE TITLE
Remove inline js: lib/edit_head.html

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8383]
Remove the inline JS from this file following the recommended steps in #4474

### Proposal & Constraints

We should remove it! - Previous question [here](https://internetarchive.slack.com/archives/C0ETZV72L/p1696535611003499?thread_ts=1693606929.163359&cid=C0ETZV72L).
Note: this is slightly related to #5807 

### Related files

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/edit_head.html

**Comment by RayBB** [comment]
@AdwaitSalankar there is still a pending discussion on if we can delete it or not.
However, if you open a PR for this then we'll have extra motivation to get an answer.
I can't promise the PR will be merged though.

**Comment by AdwaitSalankar** [comment]
```
<script type="text/javascript">
window.q.push(function(){
    if(top.location != location){
        top.location.href = document.location.href;
    };
});
</script>
```
It seems like this code redirects the browser's URL to the document's location.
Do we want this functionality?
If yes, I can move this to a different file.

**Comment by RayBB** [comment]
@AdwaitSalankar I confirmed we can just remove the PR during the community call.
Please open a PR and tag me in it :)
