### ISSUE TITLE
add pre-commit setup instructions to docs

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8387]
We should document how to setup pre-commit locally. I realized it's not in our docs anywhere and would probably save people a good amount of time as they get started.

https://pre-commit.com/#install

**Comment by DanneelsSophie** [comment]
Hello, I can try to write this documentation, is it possible to add the hacktoberfest tag?
Should I write this documentation in the readme file? :) Can I mention a version to pre-validate to avoid any modifications that would lead to installation or other modifications?

**Comment by RayBB** [comment]
@DanneelsSophie feel free to take this on.
I'm not sure exactly where we should put it yet but maybe https://github.com/internetarchive/openlibrary/blob/master/docker/README.md is a good spot. Noting that pre-commit isn't run in docker but will still be needed.
Once you write the copy we can decide where the best spot is :)

**Comment by DanneelsSophie** [comment]
Thks you can assign me this task :D !

**Comment by RayBB** [comment]
@DanneelsSophie how's it going?

**Comment by DanneelsSophie** [comment]
@RayBB Sorry for the delay (: ! you can review my PR !
