### ISSUE TITLE
The ability to upvote/follow/subscribe to a user's reading log 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#839]

**Comment by reidun76** [comment]
I vote for this! Have wished for it for years!

**Comment by tfmorris** [comment]
Hopefully these aren't all conflated. Follow != upvote in a number of circumstances.

**Comment by mekarpeles** [comment]
Nope, not conflated; it's just unclear at this point which direction will be pursued and in terms of engineering efforts I can imagine them being mutually exclusive.

**Comment by mekarpeles** [comment]
See WIP - #1966

Related to #857 and #1964

**Comment by mekarpeles** [comment]
Supplanted by #739, #857, and #1964
