### ISSUE TITLE
Add author ids to author merge UI

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#8391]
### Describe the problem that you'd like solved

Easy access to hyperlinked author ids on the merge screen alerts people to potential seperate individuals with similar names, and provides an easy way to check.

### Proposal & Constraints

I'm open to changing the visual styling of this if desired.

### Additional context

<img width="1063" alt="Screenshot 2023-10-06 at 19 29 47" src="https://github.com/internetarchive/openlibrary/assets/7288187/d19b94ce-5013-406a-b826-54bda45a1baa">

**Comment by jimchamp** [comment]
@davidscotson be sure to discuss new features with staff before implementing.
