### ISSUE TITLE
Fix Weekly Community calls link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8396]
https://github.com/internetarchive/openlibrary/blob/085702675121b98907255ae204abca44cba7c51a/CONTRIBUTING.md?plain=1#L28

The Weekly Community calls [link](https://docs.google.com/document/d/1LEbzsLZ1F9_YIQOoZzO7GoZnG1z-rudhZ9HNtsameTc/edit) is currently "Access Denied" in `CONTRIBUTING.md`

I'm going to assume this is the 2022 link since it was added backed in 2022 (#7300)

# Acceptance Criteria
- [ ] Make the link publicly readable @mekarpeles 
- [ ] Update the link to point to the community calls page https://github.com/internetarchive/openlibrary/wiki/Community-Call

**Comment by clairecharles** [comment]
Hi @RayBB can I work on this?

**Comment by RayBB** [comment]
Yes please
