### ISSUE TITLE
Unique visitors graph dropped to 0 (again)

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8397]
Previously
- #2481 
- #3827 
- #5022 
- #5145 
- #5147

### Evidence / Screenshot (if possible)
<img width="448" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/70c1e4d1-66ee-4ec3-9f37-06373b44cab7">

### Relevant url?
https://openlibrary.org/

**Comment by mekarpeles** [comment]
cc: @samuel-archive

**Comment by mekarpeles** [comment]
Network lag, it's caught up
