### ISSUE TITLE
Redirect /advanced to /advancedsearch

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8399]
### Describe the problem that you'd like solved

While Googling for something on OL I came across https://openlibrary.org/advanced which seems to be just an old version of https://openlibrary.org/advancedsearch 

I was a bit confused at first because I knew the advanced search page should look different and realized it is a different page.

### Proposal & Constraints

Redirect that page to /advancedsearch

### Additional context

I can't seem to find this anywhere in the code base so maybe an admin needs to change the page.

@mekarpeles: Here's where /advancedsearch is defined in the code
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py#L515-L519
It's possible that https://openlibrary.org/advanced?m=edit is an infogami page which needs to be converted into a redirect

**Comment by piyush-poddar** [comment]
@RayBB `/advanced` is already redirecting to `/advancedsearch`. I think its fixed now.

**Comment by RayBB** [comment]
@piyush-poddar looks like you're right!

**Comment by piyush-poddar** [comment]
@RayBB Can you please tell how this redirection is working? I was just curious to know :)

**Comment by RayBB** [comment]
@piyush-poddar try visiting the localhost version of
https://openlibrary.org/advanced?m=edit when you're logged in!
There you'll see an option to redirect. I think that's how it works.
