### ISSUE TITLE
Add "Open Library Search Tips" link to advanced search page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8400]
### Describe the problem that you'd like solved

I was looking for this page but it was hard to find https://openlibrary.org/search/howto
I think it would be nice if we added a link to it on https://openlibrary.org/advancedsearch

PS: I already added a link to it on the help page https://openlibrary.org/help.en

### Additional context

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/search/advancedsearch.html

**Comment by piyush-poddar** [comment]
@RayBB Can you please specify exactly where should the link be added?
Should it be on the bottom of 'Advanced Search'?

**Comment by RayBB** [comment]
@piyush-poddar it is to be discussed. Feel free to make a proposal of what you think would look good and work well.
You may also try to find another example somewhere on the site and follow that.

**Comment by RayBB** [comment]
@RayBB something like that is sounds good to me. Be aware that I'm just a volunteer so don't have the final say on anything and getting community input (usually via slack or the community call) is how things are usually decided.

**Comment by piyush-poddar** [comment]
@RayBB Okay, then I'll open a PR after sometime.
Thanks for your input.

**Comment by imperial-chief** [comment]
Hello.
Is this issue still open?

**Comment by imperial-chief** [comment]
Yes sure.
But in case, if i open a PR first, will it be considered?

**Comment by piyush-poddar** [comment]
@RayBB I am quite engaged in some college stuff. You can go on with @imperial-chief PR if it resolves the issue successfully. If not, then I'll open a PR next week.
