### ISSUE TITLE
Modify /imports page to not show admin-only menu bar

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8415]
When a patron visits openlibrary.org/imports, the admin menu should only show up if they are administrators

![image](https://github.com/internetarchive/openlibrary/assets/978325/f78458d7-2386-4ba2-ba45-4b51bb468ba3)

`if ctx.user and ctx.user.is_admin()`

### Evidence / Screenshot (if possible)
Logged in as a patron
![image](https://github.com/internetarchive/openlibrary/assets/26524678/f6682d43-3f5a-476f-aa7b-f5097ad0dc5c)

Not logged in
![image](https://github.com/internetarchive/openlibrary/assets/26524678/70d1ce6f-f873-4e80-9797-69aa83dc1553)

### Relevant url?

https://openlibrary.org/admin/imports

* Actual: I can't view the imports dashboard
* Expected: I should be able to view the imports dashboard (maybe)

### Details

- **Logged in (Y/N)?** Yes and No.
- **Browser type/version?** Firefox 118.0.1
- **Operating system?** Linux
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I am not sure if this is even a bug as maybe it is intentional.

**Comment by hornc** [comment]
I don't think anything on the /admin/ path should be visible to non-admins.

Doesn't seem a bug to me.

**Comment by jimchamp** [comment]
I believe that #7944 makes our imports dashboard public to all patrons: https://openlibrary.org/imports

I'm still able to visit https://openlibrary.org/admin/imports as an `admin`, and its content is the same as the public imports page.  I'm wondering if there's any reason to keep the admin endpoint going forward.

**Comment by hornc** [comment]
@jimchamp I see that https://openlibrary.org/imports is public , that makes sense as an info dashboard, but the other admin navigation should be hidden, and the add to queue option should be restricted to be shown only to logged in Admin users:

![image](https://github.com/internetarchive/openlibrary/assets/905545/be836c1c-e3d6-4d2c-b4ba-4ae2d6de0cb5)

**Comment by mekarpeles** [comment]
/admin should be private (as is)
https://openlibrary.org/imports should be public (as is)
If not admin, the menu bar should not show up (nor should add new books to import queue link)
