### ISSUE TITLE
Fix Bulk Tagger (ILE): Searching & Saving

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8417]
* Fix bugs with #7648

Sporadically, looking up for tags will fail using the Bulk Tagger on the ILE (librarian blue bar).

It's unclear whether this is because the search is failing or the JS hits one error and then fails for every subsequent request, or...

Also, the UI seems to frequently fail to create and/or add tags to the works, even when search succeeds.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by RayBB** [comment]
One fully reproducible bug is if you only type one character into the search it won't show results and the console logs this error:
`Uncaught (in promise) TypeError: can't assign to property "innerText" on 1599: not an object`

It would also be great if the UI didn't redirect you to that page that just says success.
