### ISSUE TITLE
Page number option

### ISSUE THREAD

**Issue by JeneeW** [internetarchive/openlibrary#8420]
I am constantly needing to start at the very last page of an author's list of works, but though there is an option to go straight to the first page, there is never one to reach the last. Same goes for search results. I don't need the option as often there, but when I do, it's because it's difficult to work without it.

How hard would it be to add a link like "Last" in order to make the site more easy to navigate?

![Screenshot 2023-10-14 2 06 20 PM](https://github.com/internetarchive/openlibrary/assets/102813954/2833acb6-71a2-4104-8664-1642bec44113)
![Screenshot 2023-10-14 2 07 57 PM](https://github.com/internetarchive/openlibrary/assets/102813954/99d12099-82be-4742-baf5-809882d821a4)

**Comment by mekarpeles** [comment]
Why do you need to go to the last page? And, couldn't we just sort in the reverse order? e.g. Least editions instead of most editions?

**Comment by JeneeW** [comment]
Typically it works better when going through an author's list to start at the end and work forwards. Any changes made (whether they're adding info or cover pictures) automatically causes books to be sifted to the end, which means if I started at the beginning and worked back, I'd be re-encountering the same books I just worked through and most likely missing some that got pushed forward because of it. Most of the time I also find that after a set of merges, any books that remain to be sorted will likely be there at the end as well.

**Comment by davidscotson** [comment]
My use case for this is e.g. looking for things published by "Standard Ebooks" which have a low number of editions. (Since they're public domain works, this is often a sign they are not attached to the main Work and a merge is needed).

One UI pattern that might apply is:

Previous 1 ... 20 21 22 23 ... 59 Next

Which not only gives you a way to jump to the start and end, but also provide a max page count and a bit of context.

**Comment by sbwhitt** [comment]
@cdrini I would be interested in picking this issue up

**Comment by mekarpeles** [comment]
@sbwhitt yes please! After community discussion, it looks like maybe we can go with @davidscotson's approach above? And of course, use your discretion if just having "Last" as an additional option would for some reason be significantly easier to implement.

**Comment by sbwhitt** [comment]
> @sbwhitt yes please! After community discussion, it looks like maybe we can go with @davidscotson's approach above? And of course, use your discretion if just having "Last" as an additional option would for some reason be significantly easier to implement.

Sounds good to me. I think that would be a good solution
