### ISSUE TITLE
Prefill author name when adding work from author page

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#8422]
When adding a new work from an author's page, the author is not automically prefilled on the add page.

This use to work in the past.

### Evidence / Screenshot (if possible)

![image](https://github.com/internetarchive/openlibrary/assets/73437497/27c8bff8-3afb-4040-92d0-5ff49cb10533)

### Relevant url?

Example above from: https://openlibrary.org/books/add?author=/authors/OL1573400A

### Steps to Reproduce

1. Go to an author page
2. Click the "Add another?" link near the work counter

* Actual:
* Expected:

![image](https://github.com/internetarchive/openlibrary/assets/73437497/ce001918-4dbb-4e34-80de-6f0f5d44bce1)

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by sbwhitt** [comment]
Working on this, will have a PR shortly
