### ISSUE TITLE
Add front-end validation to Contributor for role (so name is not cleared on submit)

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#8423]
When inserting a new contributor without selecting a role, the message "Please select a role." is displayed but the contributor name previously entered is erased. This behaviour is quit annoying as you have to retype the contributor name and not only select the missing role.

### Evidence / Screenshot (if possible)

![image](https://github.com/internetarchive/openlibrary/assets/73437497/e5191b73-1347-4355-aba2-0c627eac3c69)

### Steps to Reproduce

1. On an edition edit page, go to the "Contributors" section
2. Add a contributor name without selecting a role
3. Click on "Add"

* Actual:
* Expected:

![image](https://github.com/internetarchive/openlibrary/assets/73437497/0ddb69d3-fcdd-4cb2-b2f0-ff5d442a0f41)

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by SCI-co-Newb** [comment]
I believe that in the function initRoleValidation, in the file edit.js, instead of returning an error, you can make it first $('#role-errors').text('Please select a role.').show(); then return false if the role is empty or ----, same for if the name is missing. This might not be the solution since I could not test it. Or you can add to the end of error('#role-errors', '#select-role', dataConfig['Please select a role.']) a '.replace()' and replace the empty field with data.name.

**Comment by sbwhitt** [comment]
This is not specific to the roles field as other inputs behave the same when trying to submit a value without selecting a type (ID Numbers, Classifications).

![image](https://github.com/internetarchive/openlibrary/assets/29631356/44cdad37-3c55-420e-b563-15677622121a)
![image](https://github.com/internetarchive/openlibrary/assets/29631356/5258a586-2123-4a78-8d3d-a7ffbc7ee2fb)

Not sure if this can really be considered a bug, but I get how it could be annoying for the user if they miss the type field initially. Maybe this should be a broader feature request for all of the input fields of this type on the edit page.

**Comment by dinesshkumar** [comment]
can i take this issue?
I am new to contributing

**Comment by jayashridangat** [comment]
Hello can I work on this issue?

**Comment by mahasultan** [comment]
@mekarpeles @lephemere Could you assign me to this issue? For a university project

**Comment by Reyali619** [comment]
@mekarpeles @lephemere I would like to work on this issue, please.

**Comment by shahad1307** [comment]
@mekarpeles @lephemere Hello I'm a student in CMU and I have a project. I'm interested in working on this issue. Looks doable could do assign me?

**Comment by Ultare1717** [comment]
Hello, I am a student from the University Of Toronto. Would it be possible for me and my group to work on this in case this issue is still open?

**Comment by jimchamp** [comment]
Sorry everybody --- I wasn't subscribed to this issue, and did not see the requests to be assigned.
@dinesshkumar, are you still interested in working on this issue?

**Comment by dinesshkumar** [comment]
@jimchamp Yes shall i work on this?

**Comment by jimchamp** [comment]
@dinesshkumar, yes, if you'd like.

**Comment by dinesshkumar** [comment]
@jimchamp working on it

**Comment by udaypatel1** [comment]
Hi @dinesshkumar , would it be possible to work on this together? Just recently set up my dev environment, would love to do a paired-programming session or learn from you. Thanks!

**Comment by rebecca-shoptaw** [comment]
If no one's on this, I'd love to work on it!

**Comment by jimchamp** [comment]
@rebecca-shoptaw, I've assigned you to the issue, but please don't start working on it for 24 hours.
@dinesshkumar, if you are still working on this, please comment on this issue within the next 24 hours, and I'll reassign you.

Sorry for any confusion --- The automatic unasisgnment action is new and we're still ironing out kinks in the process.
