### ISSUE TITLE
Auto-detect entered edition ID type

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#8424]
When adding a new book, it would be great if the ID type be automatically selected when entering the ID.

![image](https://github.com/internetarchive/openlibrary/assets/73437497/c9a396a8-9f8f-4572-9708-f76b3f870cee)

### Proposal & Constraints

I'm thinking like it is done in the author edit page when entering an identifier with a recognizable pattern.

There is only 3 ID types allowed here (ISBN-10, ISBN-13 and LCCN). Could be also be extended to the edition edit page also, however there is a lot more ID types allowed.

**Comment by DanneelsSophie** [comment]
Hello, I would like to complete this task but I don't understand everything. This will be the first time I contribute to this project :). 

> isbn-10 contains 10 (without -)
> isbn- contains 10 and 3 (country before) (without -)
> lccn: a two-character prefix (often containing blanks), a four-digit year, and a six-digit serial number (if the user does not write both prefixes, how can I differentiate ISBN-10 or LCCN?

Do you have any examples? :D thank you

**Comment by lephemere** [comment]
LCCN is a bit more complicated and different if the code was assigned before or after year 2000. See https://catalog.loc.gov/vwebv/ui/en_US/htdocs/help/numbers.html#lccn for more information.

ISBN-10 has a check digit at the end (https://en.wikipedia.org/wiki/ISBN#ISBN-10_check_digits). There are some edge cases where the check digit does not match but that impact's only a negligible number of codes.

ISBN-13 should only start with 978 or 979 for newer books.

**Comment by scottbarnes** [comment]
@DanneelsSophie, [openlibrary/plugins/openlibrary/js/idValidation.js](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/idValidation.js) has functions for validating ISBNs and LCCNs, which may or may not be helpful.

For example `isFormatValidIsbn10()` and `isFormatValidIsbn13()` will try to determine if a string is a valid ISBN format without trying to verify the checksum that @lephemere mentioned.

The comments to the functions also have some links to more about valid forms for the various IDs.

**Comment by DanneelsSophie** [comment]
I can try this task :D thanks you for this information @scottbarnes  and @lephemere , Could you add the tag hacktoberfest ? :D
