### ISSUE TITLE
Incomplete book list search results

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#8449]
Dear developers,
When I do a search for book lists on openlibrary.org, the search results are clearly incomplete.

### Relevant url:
https://openlibrary.org/search/lists?q=History&mode=everything

### Steps to Reproduce

1. Go to https://openlibrary.org/search/lists?q=&mode=everything
2. Search for _History_.
3. The search results will be incomplete: https://openlibrary.org/search/lists?q=History&mode=everything
For example, you won't find this book list among the results: https://openlibrary.org/people/clyde_barnes2/lists/OL236499L/History_of_Medicine

* Expected: Seeing all book lists matching my search query.

### Details

- **Logged in (Y/N)?**  Yes
- **Browser type/version?** Chrome Desktop for Windows, Version 118.0.5993.89
- **Operating system?** Windows 11
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Currently, the openlibrary.org search engine seems to only produce lists with an exact match of title to the search query, down to the capitalization of letters.

### Related files

Thank you for looking into this.

**Comment by mekarpeles** [comment]
Eventually we want Lists to be in solr which will fix this problem. Please see the following for tracking issues.

* #3385
* #7815

Making this issue as a duplicate
