### ISSUE TITLE
Remove deprecated backticks from Python code

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#846]
https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/solr/inside/index_all.py#L29

The single reversed comma quotation marks (&#8219;) or whatever that is here, and repeated lower in this module, seem anomalies. Is it a typo, or a real thing?

**Comment by tfmorris** [comment]
> The single reversed comma quotation marks (‛) or whatever that is here, and repeated lower in this module, seem anomalies. Is it a typo, or a real thing?

The represent deprecated Python syntax which is no longer supported in Python 3, so should be removed as a low priority task or as people are working on code that contains them.

https://stackoverflow.com/a/1673087/167425

**Comment by LeadSongDog** [comment]
@tmorris Thanks for clearing that up.

**Comment by salman-bhai** [comment]
I think we should probably look at changing the print statements for Python3 as well. @tfmorris do you think that should warrant for a separate Issue!

**Comment by tfmorris** [comment]
Yes, Python 3 should be a separate (low priority) ticket, in my opinion.
It's more than just print statements, but that would be a start.

All new code should be Python 3 ready <= coding standard addition

**Comment by salman-bhai** [comment]
I think this summarises it quite well!

[Differences between Python 2 and Python 3](http://sebastianraschka.com/Articles/2014_python_2_3_key_diff.html)
