### ISSUE TITLE
Weird syntax a typo?

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#847]
https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/solr/inside/index_all.py#L29

The single reversed comma quotation marks (&#8219;) or (\`) or whatever this (\`) is here, and repeated lower in this module, seem anomalies. Is it a typo, or a real thing?

**Comment by tfmorris** [comment]
Duplicate of #846
