### ISSUE TITLE
Add warning about OpenAPI definitions

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8474]
It would be useful to warn that Swagger definition only includes a subset of the API and that they should see the API pages in the developer's docs for the full set.

_Originally posted by @tfmorris in https://github.com/internetarchive/openlibrary/issues/8021#issuecomment-1616046580_
            

After #5910 and through checking of the docs we can remove it.

**Comment by Realmbird** [comment]
Can I do this one

**Comment by Realmbird** [comment]
@RayBB Please Assign this to me

**Comment by Realmbird** [comment]
I can do this today

**Comment by Realmbird** [comment]
@RayBB where is the docs so I can understand OpenAPI

**Comment by RayBB** [comment]
@Realmbird see https://github.com/internetarchive/openlibrary/issues/8021 and let me know if that answers it
