### ISSUE TITLE
Add OCLC & Goodreads identifiers to 'Add new book' screen

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#8475]
The OCLC Number & Goodreads identifier are already marked as frequent/important on the edition editing page. I think they deserve a promotion to the initial screen for adding new books, as a strong option for the many works which don't have ISBNs.

### Describe the problem that you'd like solved
Make it easier to add a well-known identifier to a new book.

### Proposal & Constraints
https://openlibrary.org/books/add

The drop-down menu under "And optionally, an ID number — like an ISBN — would be helpful..." should include OCLC & Goodreads as well as the other options already present.

### Additional context
Goodreads & Worldcat represent large bibliographic databases (larger than ISBN?) & are already privileged on other screens within OL, so I think they're reasonably options that will make the menu more useful without lengthening it too much.

**Comment by KshitijThareja** [comment]
Hi! I'd like to work on this issue. From what I understood, we need to add Goodreads and OCLC apart from the other options already present is the ID number menu. Is there something else that needs to be done apart from this?
Also can you please assign this issue to me so that I can start working on it.

**Comment by sbwhitt** [comment]
Validation for new IDs on the add book side would be more effort, but adding them would be pretty simple. Might be a good opportunity to overhaul ID validation so adding these new types is a bit more streamlined.

**Comment by seabelis** [comment]
@sbwhitt We discussed this recently and I believe the decision was to add only Project Gutenberg and Librivox (trusted partners) to the initial screen.

**Comment by sbwhitt** [comment]
> @sbwhitt We discussed this recently and I believe the decision was to add only Project Gutenberg and Librivox (trusted partners) to the initial screen.

Ok great, I can start working on that.
