### ISSUE TITLE
Author search doesn't search alternate_names

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#848]
This has been mentioned as a contributing factor in #714 and #756, but it's an issue in its own right.

As can be seen by these examples:

```
https://openlibrary.org/search/authors?q=AEschyle
https://openlibrary.org/search/authors?q=alternate_names%3AEschyle
https://openlibrary.org/search/authors.json?q=name%3A%22Aeschylus%22+AND+work_count%3A%5B5+TO+*%5D 
```
The first two examples return no results despite the fact that the alternate name form is listed in the author record and it doesn't contain any special characters. 

The last query not only works, but demonstrates that full SOLR query language support works.

Interestingly though, the returned results don't include `alternate_names` field and the `text` field doesn't include the alternate names, perhaps hinting at an indexing problem which could be the root cause.

**Comment by tfmorris** [comment]
I think this actually has a pretty simple cause. It doesn't look like [update_author()](https://github.com/internetarchive/openlibrary/blob/35968763aca2e9dac129fa3f76ba32da7bed8e6d/openlibrary/solr/update_work.py#L1187) (confusingly located in solr/update_work.py) does **anything** with the `alternate_names` field at all!

https://github.com/internetarchive/openlibrary/blob/35968763aca2e9dac129fa3f76ba32da7bed8e6d/openlibrary/solr/update_work.py#L1187

I don't have a Solr setup that I can test against easily, but I think inserting this snippet:

```python
    alternate_names =	a.get('alternate_names', [])
    if alternate_names:
        d['alternate_names'] = alternate_names
```
near this line https://github.com/internetarchive/openlibrary/blob/35968763aca2e9dac129fa3f76ba32da7bed8e6d/openlibrary/solr/update_work.py#L1244
would likely fix the problem.``

**Comment by LeadSongDog** [comment]
Sounds like a find... The odd placement mirrors that for creating new authors inside the dialog for new works.  That's one we've needed to extract for a long time.

**Comment by cdrini** [comment]
I think you are correct. Note that solr doesn't have an `alternate_names` field, so use `author_alternative_name` instead. This is used on works (so you *can* search works using alternate names) but I think you're correct in that they are not added to authors themselves.

**Comment by cdrini** [comment]
Ooops, I'm wrong, it does have `alternate_names`.

**Comment by hornc** [comment]
@tfmorris I've just noticed that https://github.com/tfmorris/openlibrary/blob/75626340ec473437a2b0cfb32ccec5f173ef5128/openlibrary/solr/update_work.py#L777 looks like it _is_ indexing alternate_names, but that is inside `build_data2()` ... which gets called by `build_data()`. The docstrings don't exactly make it clear what the difference is between those, or when they get called. That implies to me that _sometimes_ alternate_name will be indexed, perhaps triggered by changes to works?   Anything that needs to update authors should use the same code. Your PR is good, but I think the whole Solr process needs an overhaul to make all the paths visible so we can be sure all updates triggers use the same code.

**Comment by cdrini** [comment]
@hornc agree on need of overhaul :P That line is adding the author alt names to the *work*. I.e. you can search for *works* by its author alt names.

**Comment by tfmorris** [comment]
What @cdrini said. Everything under the sun gets added to works records, including author's alternate names which means that currently the best (and pretty much only) way to find an author by, say, the Greek spelling of their name is to select everything as the search facet and then click on the author link for one of the works which is found.

Refactoring the entire thing would be a fine project, but in the mean time, I'm hoping that this small change will fix this one specific problem.
