### ISSUE TITLE
Vue, ObservationForm JS loaded twice on books page; 130kb JS

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8493]
### Steps to Reproduce

1. Go to any book page, eg https://openlibrary.org/books/OL47072492M/Adventures_of_Sherlock_Holmes

* Actual: JS only to be loaded once
* Expected: JS is loaded twice!

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF119 (may be firefox related?)
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
- Find a way to avoid the JS being included twice even though the HTML for the observation form is included twice
- Don't include the html for the observation _modal_ twice ; decouple that from the button that opens the modal
- Ideally, only load Vue/other JS once the modal is clicked. Don't need it loaded by default. An iframe modal, like how mange-covers works, would be a better solution here!

**Comment by jimchamp** [comment]
WIP solution for #7547 removes the need for `render_component()` to append script elements to the rendered HTML, solving this issue.
