### ISSUE TITLE
Add Patron Onboarding Flow

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#850]
This is a candidate for 2021 Google Summer of Code!

- [x] #1433
- [x] #2058
- [x] #5500

Allow user to choose subjects, authors, and books to follow as part of optional sign-up flow.

**Comment by rohitjain00** [comment]
Agree!..We should ask users for their choice regarding genre, authors, publishers and provide them with more personalized experience.

**Comment by mekarpeles** [comment]
@rohitjain00 do you have any interest in being our Deputy of Registration and be our lead on features and issues facing https://github.com/internetarchive/openlibrary/labels/registration?

**Comment by guyjeangilles** [comment]
Assigning @mekarpeles per slack discussions since you created the string of associated issues.

**Comment by jamesachamp** [comment]
We may want to add a brief, optional tutorial on some of Open Library's features (book reader, library explorer, lists, etc.) as a part of the account creation flow.  This will likely require someone with good UX/UI design sensibilities.

**Comment by mekarpeles** [comment]
Onboarding entails 2 sets of flows:

## Pre-registration

Decorating the homepage with dismiss able-cards which alert partons of new features, onboarding tips, blog posts, etc.

On Robinhood mobile app, there are cards you can dismiss 
![Screenshot_20210324-033117](https://user-images.githubusercontent.com/978325/112209868-32b6c380-8bd7-11eb-9685-6cc51a73af14.png)

## Registration

When a patron signs up for Open Library, we have an opportunity to guide them through navigating the features of the site (e.g. author stats) or select actions (like adding a book to their Reading Log or Book Notes), to ask questions (about their level of understanding), and to collect strategic information to improve their experience (like subjects of interest).
 
Here we may learn from the onboarding flows of goodreads and storygraph:
![app thestorygraph com_reading_preferences_new](https://user-images.githubusercontent.com/978325/112210614-241cdc00-8bd8-11eb-858a-4d34fcce0e99.png)

1. Importing books from e.g. goodreads?
2. Adding 1st book to Reading Log
3. Adding BookNotes
5. Choose subjects/topics (v2)
5. Choose authors (v2)

**Comment by mekarpeles** [comment]
cc: @Sabreen-Parveen, @Yashs911, @ArunTeltia, @finnless, this isn't a claimable issue as it's a planning `Type: Epic`, though I thought you may wish to be aware of its existence and be interested in participating from the process or following its progress. :)

**Comment by mekarpeles** [comment]
Also, see: https://github.com/internetarchive/openlibrary/issues/2599

**Comment by cdrini** [comment]
There are a few issues around, but this work has been done, thanks to @Sabreen-Parveen @RayBB and @mekarpeles :)
