### ISSUE TITLE
On Edition Edit Page: Promote Trusted Book Providers & Social Catalogues in the Identifier list of Editions

### ISSUE THREAD

**Issue by onnotasler** [internetarchive/openlibrary#8500]
### Question

Should we replace the _always on top_ identifier entries for the two social book catalogues (Goodreads and Librarything) with our two trusted book providers (Librivox and Project Gutenberg)?

### Additional context

At the moment, the identifier section on edition pages offer six "fixed" identifiers that are always shown on top instead in alphabetical order:

- ISBN-10
- ISBN-13
- LCCN
- OCLC
- Goodreads
- Librarything

That probably made a lot of sense when OpenLibrary started, because Goodreads and Librarything were reliable (and sometimes the only) source for a lot of data. Recently, the impact of Goodreads and Librarything on OpenLibrary waned, as far as I am aware.

Open Library also recently added trusted book providers. These allow Open Library patrons to easily access books from those providers through Open Library. This feature requires the  books ID from the trusted book provider to be entered into the edition on Open Library. At the moment, this is a hassle, as the IDs for the trusted book identifiers are well hidden in a long, cumbersome list of identifiers that cannot be easily searched.

Fixing the two trusted book providers at the top would draw attention to them, and make it more likely for librarians to enter the respective ID. This would lead to a better service for patrons. By removing the two social catalogues, we make sure the entries fixed at the top does not get excessive.

### Issue resolution criteria

Once we decided how to increase the number of linked identifiers between Open Library and trusted book providers.

**Comment by seabelis** [comment]
I'm for this.

**Comment by davidscotson** [comment]
I believe this can be done by changing this line:

https://github.com/internetarchive/openlibrary/blob/5d42394737769d7bb8898a25da8caf59f166eeaa/openlibrary/templates/books/edit/edition.html#L419

Currently it is:

```
$ popular = ["ocaid", "isbn_10", "isbn_13", "lccn", "oclc_numbers", "goodreads", "librarything"]
```

Note that `ocaid` gets removed later for non-privileged users.

This list dictates the specific order of the items that appear before the  ---- menu break, and anything removed from this list will just appear in the alphabetical list below.

I believe the proposal is to promote 'project gutenberg' and 'librivox' to this priority area and demote `goodreads` and `librarything` to the alphabetical list below.

I think the proposal is to add the two new ones right at the top, so above even ocaid? I'll create a pull request to do that, but if any other specific order is desired then just comment here and I'll match that.

**Comment by bicolino34** [comment]
> I believe this can be done by changing this line:
> 
> https://github.com/internetarchive/openlibrary/blob/5d42394737769d7bb8898a25da8caf59f166eeaa/openlibrary/templates/books/edit/edition.html#L419
> 
> Currently it is:
> 
> ```
> $ popular = ["ocaid", "isbn_10", "isbn_13", "lccn", "oclc_numbers", "goodreads", "librarything"]
> ```
> 
> Note that `ocaid` gets removed later for non-privileged users.
> 
> This list dictates the specific order of the items that appear before the  ---- menu break, and anything removed from this list will just appear in the alphabetical list below.
> 
> I believe the proposal is to promote 'project gutenberg' and 'librivox' to this priority area and demote `goodreads` and `librarything` to the alphabetical list below.
> 
> I think the proposal is to add the two new ones right at the top, so above even ocaid? I'll create a pull request to do that, but if any other specific order is desired then just comment here and I'll match that.
> 
> 
> 
> 

I would also add Wikisource to this list, but ideally this list should be customizable, so that librarian can set preferred IDs for themself

**Comment by onnotasler** [comment]
> I believe the proposal is to promote 'project gutenberg' and 'librivox' to this priority area and demote `goodreads` and `librarything` to the alphabetical list below.

Exactly. 

> I think the proposal is to add the two new ones right at the top, so above even ocaid?

That is not  necessary. It is sufficient if those two placed somewhere in the priority list: 

$ popular = ["ocaid", "isbn_10", "isbn_13", "lccn", "oclc_numbers", "project gutenberg", "librivox"]

> Ideally this list should be customizable, so that librarian can set preferred IDs for themself

That would indeed be ideal, as I often need very specific IDs that others probably rarely use. Also, at the moment, it is extremely daunting to actually find identifiers you do not know the specific name. There already is an open issue for that problem, though (#7315 ) so lets solve problems one step at a time.
