### ISSUE TITLE
Amazon logos being used in place of book covers

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8509]
This book: https://openlibrary.org/books/OL32321627M/The_Politics_of_Memory_in_Poland_and_Ukraine
uses for its cover image an image which, ironically, says "No image available" and shows the Amazon logo: https://ia802607.us.archive.org/view_archive.php?archive=/31/items/l_covers_0010/l_covers_0010_94.zip&file=0010944986-L.jpg
That seems like a silly thing to import and display to the user.

### Evidence / Screenshot (if possible)
![Screen Shot 2023-11-09 at 12 33 36 PM](https://github.com/internetarchive/openlibrary/assets/82178/59ce1e3d-3c25-432d-8b6f-72d6aa75f4d9)

### Relevant url?
See above

### Steps to Reproduce
Click the link

* Actual: See above
* Expected: Don't import/display Amazon placeholders

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Thank you @tfmorris, +1 -- I think this is a duplicate issue which we addressed in Feb 7, 2022 on #6109

https://openlibrary.org/books/OL32321627M/The_Politics_of_Memory_in_Poland_and_Ukraine?a=1&b=1&v=1 was created + cover added in 2021 so we believe this issue can be closed, though understandably there may still be cleanup work for disassociating old placeholder covers and we've been unable to identify an engineering solution (without checking the hash of ~10M+ covers in archive.org items) and so we're going to close and leave this for librarians as they encounter them.

Let's **definitely** re-open if, as noted in #6109 the placeholder cover has changed and our code is not working correcrtly.
