### ISSUE TITLE
Auto-generated Inventaire.io author links from Wikidata ids

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#8518]
Note: not totally sure this is a good idea (though it's growing on me) but it seemed like it might be easy to implement so I tried it so now we have a prototype for people to try.

Inventaire.io builds mostly on wikidata data, and gives it a slightly more book-focused look:

https://www.wikidata.org/wiki/Q42
https://inventaire.io/entity/wd:Q42

### Describe the problem that you'd like solved
We are able to auto-generate links to Inventaire.io for any author where we have a wikidata ID.

### Proposal & Constraints
On output of ids on the Author page, immediately after the wikidata id, add a link to Inventaire generated from the wikidata id.

Inventaire can also have non-wikidata ids, so we should check if an Inventaire id has been added manually, and skip the second output.

### Additional context
<img width="349" alt="Screenshot 2023-11-11 at 10 25 43" src="https://github.com/internetarchive/openlibrary/assets/7288187/4c1d129a-17d8-49da-9f59-990e978c8570">

**Comment by cdrini** [comment]
Hi @davidscotson ! Interesting.... This does create _some_ issues, since it assumes that every wikidata record is in inventaire (which it might not be), and it also makes it look like we have the inventaire ID in our database (which we don't). I'm note entirely sure! Thoughts from folks?
