### ISSUE TITLE
Increase automated test coverage

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#852]

**Comment by salman-bhai** [comment]
Could you give more description for this?

**Comment by rohitjain00** [comment]
@mekarpeles Please provide more information on this issue?

**Comment by jdlrobson** [comment]
Being bold and closing this due to a lack of description and broadness. Coverage  can always be improved so I fear this ticket will always be open!

@rohitjain00 if you are interested in writing tests I can open some much more specific ones just let me know on slack!
