### ISSUE TITLE
Last read date not zero-padded by client-side code

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8521]
### Evidence / Screenshot (if possible)
When initially setting a last read date if the given day or month is a single digit, leading zeroes are not displayed. 

![lrd_no_padding_zero](https://github.com/internetarchive/openlibrary/assets/28732543/5f002c83-9f22-4784-af2b-183026da5ae3)
_The month should be zero-padded here._

### Relevant url?

Serach pages, book pages, and reading log pages.

### Steps to Reproduce

1. While logged in, go to any page containing a My Books dropper
2. Mark a book as "Already Read".  A prompt for a read date will appear below the dropper.  Click the "Other" option to manually enter a date.
3. Set a read date of 1 January 2023, and submit the form.

* Actual: "2023-1-1" is displayed
* Expected: "2023-01-01" is displayed.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Update the `showDateView` JS function to zero-pad and days and month values that are less than `10`.  The date string is formatted in this conditional:
https://github.com/internetarchive/openlibrary/blob/83fe5c7a7e4cbe738c065b764cffca9ef78a16e6/openlibrary/plugins/openlibrary/js/check-ins/index.js#L357-L362

The `padStart` [function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) should make solving this fairly simple.

### Related files

See above.

### Stakeholders

@seabelis

**Comment by KshitijThareja** [comment]
Hello 👋🏻
I'd like to work on this issue. Can you please assign it to me?

**Comment by jimchamp** [comment]
Hi @KshitijThareja 
You've been assigned.  Feel free to reach out if you have any questions.

**Comment by KshitijThareja** [comment]
@jimchamp Thanks for assigning it to me. I've linked a PR related to this issue. Can you please review it and suggest changes, if any?

**Comment by ikigai27** [comment]
i made some changes but I'm unable to push it can you help me to walk through it @jimchamp

**Comment by jimchamp** [comment]
@ikigai27 you may not have noticed, but @KshitijThareja was [assigned](https://github.com/internetarchive/openlibrary/issues/8521#issuecomment-1809558970) to work on this issue, and [has opened](https://github.com/internetarchive/openlibrary/issues/8521#issuecomment-1809640255) a [PR](https://github.com/internetarchive/openlibrary/pull/8523) which solves this.

Please find another issue and ask to be assigned before working on it.  This [guide](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) may help you with any Git issues you may encounter.
