### ISSUE TITLE
ILE selections not actually cleared when subjects added

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8530]
When submitting subjects with the Bulk Tagger, the selected works are meant to be deselected upon successful submission.  This isn't happening today, as the function used by the Bulk Tagger to reset the selections doesn't remove the selected items from session storage.

### Steps to Reproduce

1. Go to a search page.
2. Select several search result items.
3. Add a new or existing subject tag.
4. Visit a book page

* Actual: ILE blue bar is at the bottom of the page.  The "Clear selections" option is present in the blue bar.
* Expected: The blue bar does not appear at the bottom of the page.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Any
- **Operating system?** Any
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Will open a PR that fixes this shortly.

**Comment by mheiman** [comment]
We should think about this in the context of the other ILE functions — they intentionally leave the selection active in case the user wants to do something additional with the selected set. I could see the argument for tagging as well -- you might tag some items, close the popup, and then decide you want to make another change, but there's no way to recover the the set you were previously working on.

**Comment by jimchamp** [comment]
That's great feedback.  Will remove the call to reset the ILE from the bulk tagging form's submission handler.
