### ISSUE TITLE
Wikisource Trusted Book Provider

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8545]
- Titles in catalogue: [~500,000](https://en.wikisource.org/wiki/Main_Page) in English alone!
- No real presence in OL yet; [60](https://openlibrary.org/search?q=id_wikisource%3A*&mode=everything) works have wikisource IDs
- [x] Create identifier field for Wikisource
    - Big Question: wikisource IDs are language specific (eg note the `en` in https://en.wikisource.org/wiki/Goody_Two-Shoes_(1888) ) :grimacing: how should we deal with that?
    - Big Answer: Apparently URLs like this work! https://wikisource.org/wiki/en:The_Annotated_Strange_Case_of_Dr_Jekyll_and_Mr_Hyde
- [ ] Display read button when provider ID present
- [ ] Custom download options
- Create separate issue for:
     - Import missing records
     - Set up automatic import pipeline

### Proposal & Related Files

Follow the template in https://github.com/internetarchive/openlibrary/pull/8682/files ; except for wikisource!

**Comment by Freso** [comment]
FWIW, any item in Wikisource (and any other Wikimedia projects) will have a Wikidata item, so it might be enough to add the WD identifier and then get additional information (such as Wikimedia links) from that?

I don’t know enough about your code and data structures to know if that’s feasible for OL, but that’s generally how MusicBrainz and BookBrainz deals with e.g. getting Wikipedia excerpts.

**Comment by bicolino34** [comment]
Some of the editors in Ukrainian Wikisource showed interest to this project. Specifically, to the potential traffic from this.
I am slowly adding IDs to the Ukrainian editions. Hope this will soon be implemented

**Comment by pidgezero-one** [comment]
I'll take this one on after our discussion earlier, @cdrini ! Thank you!

**Comment by cdrini** [comment]
Awesome thank you @pidgezero-one !
