### ISSUE TITLE
Users confused by "Want to Read" action

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#855]
Perhaps rename to "Add to Wishlist"?

cc: @whatisgalen, @alexisrossi, @JeffKaplan

**Comment by mekarpeles** [comment]
maybe "Add to Wishlist" is more clear?

**Comment by cdrini** [comment]
I personally think wishlist is misleading; wishlist usually implies "A book I want to buy" or in the context of OL it could also be misconstrued as "A book I want OL to have". Maybe "Plan to read/Currently Reading/Read" is better? Can you provide more context by why users are confused? It might just be because this is a new feature.

**Comment by jkoby** [comment]
How about "Add To Reading List"?

**Comment by obsoletenerd** [comment]
I feel like "Want to Read" is still the clearest of all of the above (as a user who stumbled here out of boredom). Followed by "Add to Reading List".

**Comment by mekarpeles** [comment]
I think the bigger issue is people click "Want to Read" and expect to read the book. And we can address this by making sure there's always a button in the right side bar, e.g. "Read eBook" or "Borrow eBook" (in blue) or "No eBook Unavailable" (grey)
![book unavailable](https://user-images.githubusercontent.com/978325/46275322-59697700-c511-11e8-9e3c-4b7ecda47df7.png)

**Comment by obsoletenerd** [comment]
"Read Later"?

**Comment by frankely** [comment]
> "Read Later"?

Read It Later?

**Comment by mekarpeles** [comment]
I think these are all good suggestions -- I just checked with @JeffKaplan about how many emails we're getting from confused users, and the number has gone *way* down to ~1 per week.

I am going to close this issue as I think @cdrini was right -- https://github.com/internetarchive/openlibrary/issues/855#issuecomment-410531786 -- that such things happen when a new feature is introduced.

I'll open another issue for this task:
https://github.com/internetarchive/openlibrary/issues/855#issuecomment-425814181

**Comment by mekarpeles** [comment]
New issue moved to #1235
