### ISSUE TITLE
Make release notes or a change log more accessible to patrons

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8552]
It might be nice to make it more obvious to patrons when things have changed on openlibrary.org. To that end, making the release notes or a change log more accessible to patrons may make sense.

For example, when the loan history page changes, it may be more useful to some patrons, but they have no way to know about the changes, absent a blog post on the topic (and not all patrons may know to look at the blog to find out about new features, as it contains other posts as well).

We currently have https://github.com/internetarchive/openlibrary/releases, but it's a bit hidden as you have to go to GitHub, and as @seabelis points out, this may be too technical for many patrons.

### Proposal & Constraints

Perhaps we could add `/release-notes` to the "Welcome to Open Library" carousel.

**Comment by mekarpeles** [comment]
Let's please add an item to the footer call **Release Notes** that links to our github latest release notes.

**Comment by mekarpeles** [comment]
If we want a separate issue for creating an onboarding card, we can consider it, but for now, adding the footer item is enough to close this issue.

**Comment by lakshya-dhariwal** [comment]
Hey @mekarpeles i would like to try working on it
