### ISSUE TITLE
Add new "Volunteering" card to the "Welcome to Open Library" carousel

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8553]
We should consider adding `/volunteer` to the "Welcome to Open Library" carousel on the main page of openlibrary.org.

**Comment by jimchamp** [comment]
We would like to add a new onboarding carousel card that calls potential volunteers to action.
The new card can be added to [welcome.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/home/welcome.html), where we render our other onboarding carousel cards.

This image can be used for card: https://thenounproject.com/api/private/icons/4442336/edit/
It should be placed in this [directory](https://github.com/internetarchive/openlibrary/tree/master/static/images/onboarding), and named something like `volunteer.png`.

Image attribution should be "Volunteer by Candy Design from the Noun Project"

Title of the new card should be: "Volunteer at Open Library"
The card's body should read: "Discover opportunities to improve the library"

Clicking on the card should take the patron to the /volunteer page.

The new card should appear second to last in the carousel.

Finally, the `ol_link_track` value should be "OnboardingCarouselClick|Volunteer"

**Comment by xonx4l** [comment]
Assign it to me .

**Comment by xonx4l** [comment]
@jimchamp

**Comment by jimchamp** [comment]
Assigned. Thanks, @xonx4l!

**Comment by xonx4l** [comment]
@jimchamp made a Pr as per your suggestions which looks good and should not have any issue.

**Comment by xonx4l** [comment]
Thanks
