### ISSUE TITLE
Yearly Reading Goals: Ability to jump to specific year

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8557]
**Deadline** 2023! Because we want some way to go to previous years, which is currently not possible without manipulating the URL.

### Describe the problem that you'd like solved

Currently on https://openlibrary.org/account/books/already-read (the "My Already Read Books" page), we see all books the patron has read.

There's a way (see yellow highlight) to jump to the **current** year's books only, not previous years.

![image](https://github.com/internetarchive/openlibrary/assets/978325/0982f318-3e93-4289-a594-8a86e5858160)

What we want to do is update My Books “Already Read” reading log page to have some way to go to a specific year.

### Requirements

Add a second dropdown **only** on the "Already Read" page (and **if** the patron has every set a yearly reading goal) that says, “All Time” or “2023”, “2022” where the dates are populated from the entries in their yearly-reading-goals db table…
![image](https://github.com/internetarchive/openlibrary/assets/978325/4434d2c3-220d-49b9-b6f6-1be7943bb9ef)

Add title to the page “My {year} Reading Goals” if a date is selected. Selecting a date should bring you to e.g. `https://openlibrary.org/account/books/already-read/year/{year}`

### Technical Solution

Wrap the “crumb” dropper (for changing the page from e.g. "Currently Reading" to "Already Read") in a parent div container set to `display: flex` and if we’re on “Already Read” page then add a second “crumb” for the Year with default “All Time”.

**Comment by benbdeitch** [comment]
Hello! I'd love to work on this issue.

**Comment by Abhishektharu** [comment]
I haven't read any of the books how can I set any book to already read in db

**Comment by KshitijThareja** [comment]
@mekarpeles I'd like to work on this issue. Can you assign it to me if possible?

**Comment by Abhishektharu** [comment]
how do we return list of years. Given function def get_reading_goals_year(): only returns current year
