### ISSUE TITLE
Recommendations based on lists/readinglog, follows, user-item collaborative filtering

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#857]

**Comment by tphe** [comment]
Hi, I'd like to work on this issue as part of a class project on search engines. Are you imagining that the current recommendation system would be extended to include data from the users' list/readinglog and follows? Or would this be a separate area of recommendations (on the user's start page as "recommended for you" or something similar).

**Comment by guyjeangilles** [comment]
This can't be completed until we implement user following in #1966 . Assigning @mekarpeles since you're talking #1966 and #739 per our slack discussion

**Comment by mekarpeles** [comment]
Closing this and #2000 in favor of #8828
