### ISSUE TITLE
Create pagination for Merge Queue

### ISSUE THREAD

**Issue by Eds-Dbug** [internetarchive/openlibrary#8577]
Add pagination to the bottom of merge queue to improve UI for librarians

### Describe the problem that you'd like solved

Add pagination similar to image but at bottom of page.
![image](https://github.com/internetarchive/openlibrary/assets/83380248/9e128bea-5d41-46e0-9df8-8ee8d2c4a0d4)

### Proposal & Constraints

There is a pagination template "pagination.html", will attempt to implement this into the merge queue.  

### Stakeholders

@mekarpeles @openlibrary

**Comment by sheikhaffan21** [comment]
I am new open source contributor, I would like to get this job done.

**Comment by Eds-Dbug** [comment]
Go for it!

**Comment by Eds-Dbug** [comment]
Hey on second thought I am already half way done. Sorry about that I should
close the issue. There are still plenty of issues out there for you!

**Comment by Eds-Dbug** [comment]
On second thought I am half way done, this will probably make your work redundant sorry for the confusion.
