### ISSUE TITLE
Prevent Crawlers from hitting sort_options.html links that should be nofollow

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8579]
https://github.com/internetarchive/openlibrary/blob/308a35d6999427c02b1dbf5211c033ad3b352556/openlibrary/templates/search/sort_options.html#L8 should be updated to following https://www.lumar.io/blog/best-practice/noindex-disallow-nofollow/ so that these `<a>` tags do not get crawled by bots.

e.g. https://openlibrary.org/authors/OL7290222A/Taylor_Jenkins_Reid

The sort_options.html
<img width="892" alt="Screenshot 2023-12-01 at 12 42 55 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/8b601897-f5c5-4172-a3c4-7fb6a2567cd1">

### Evidence / Screenshot (if possible)

`openlibrary.org - [01/Dec/2023:20:14:45 +0000] "GET /authors/OLXXXA/XXX?sort=random_1701448397.338931&mode=everything HTTP/2.0" 403 185 "-" "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.6045.123 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" 0.000`

**Comment by tfmorris** [comment]
Shouldn't the `canonical` tag be taking care of this?

Also, the URL from your log doesn't match the links generated on that page. There's no seed on the `sort=random` for the links from that page. It seems like the reference may be coming from somewhere else.
