### ISSUE TITLE
Allowing OL users to subscribe to IA mailing lists

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#858]
Internet Archive has mailing lists it uses to message users. We want to ask Open Library users when they are registering if they want to join this mailing list. (:**tahW**)

- **Why**: The information in the email is likely useful to this audience, and is also one of the main ways IA asks for donations in December; this is important for OL keeping the lights on since IA funds/supports all of OL's infrastructure/staff.
- **Why-not**:
    - R1: There's a risk some of the emails won't be super pertinent to OL users and will bother them. We manage this risk by 1) getting a sample of previous emails to see what they're like, 2) ensuring unsubscribing is easy.
    - R2: There's some risk that people will be startled if the emails are coming from IA email addresses. To check: Does the registration success email come from an IA? If not, we might want to make it a requirement that the emails come from OL email addresses.
    - R3: We want to be able to track when donations come from OL users (as opposed to IA users). We can ~do this for donations via the OL banner, but it's not clear if we can do this from the emails.
- **When**: Targeting for 2019-Q4.
- **Who**: @cdrini (with help from @mekarpeles where necessary)

### Screenshot
IA's mailing lists:

![image](https://user-images.githubusercontent.com/6251786/69769173-c6968d80-1151-11ea-87df-30f00555fadb.png)

### Investigative work
- [x] Check previous archive.org email addresses for R1
- [x] Check if when a new account is created on OL, if the registration success email comes from an IA email account (for R2)
- [ ] Do some work to see how difficult to would be track if donations are coming from OL users vs IA users (R3)

### Summary of Requirements
- [ ] The registration page should include a check mark saying "Send me general announcements from the Internet Archive, the non-for-profit that runs Open Library (approx. two per month)"†
- [ ] Users who register for the emails should receive them
- [ ] Users who do not register for the emails should not receive them
- [ ] Emails should include an "unsubscribe" link that works
- [ ] The user's settings page on OL should include an "unsubscribe" link that works

<small>† IA has options for 2 mailing lists; it's not clear whether we should support both. When in doubt, only support 1</small>

**Comment by rohitjain00** [comment]
I don't understand this why to subscribe OL users to IA mailing list?

**Comment by mekarpeles** [comment]
When a patrons registers for an Open Library account, they are also registering for an Archive.org account and so we want to give the patron the ability to sign up for Internet Archive's mailing list at time of registration.

This involves a front-end and back-end component. First, we need to update our call to the `xauthn` API to specify/reflect whether the patron wishes to subscribe. Second, we need to update the UI form. The steps are similar to #2058

**Comment by tfmorris** [comment]
@mekarpeles Can you provide a link to the archives for some of these mailing lists? I can't find any examples.

To be clear, the reason that OpenLibrary subscribers end up with archive.org accounts is because we force them to, having disabled all the openlibrary.org accounts. They're not choosing to get archive.org accounts.

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary/issues/858#issuecomment-484287808
@tfmorris I understand this point well and have 0 authority on this point, it was a decision by Brewster himself and I expressed my opinion. 

@tfmorris I'm not sure that there is an archive of Archive.org's mailing list, I'll have to check.

> Send me general announcements from the Internet Archive (approx. two per month)
> Send me announcements about Internet Archive events in the San Francisco Bay Area

**Comment by LeadSongDog** [comment]
For the forum posts (vice mailing lists) at IA there's:
https://help.archive.org/hc/en-us/articles/360018126292-Forums-A-Basic-Guide

**Comment by guyjeangilles** [comment]
Defaulting to assigning @mekarpeles per slack discussions

**Comment by mekarpeles** [comment]
@cdrini docs @ https://git.archive.org/ia/petabox/tree/master/www/sf/services/xauthn

**Comment by cdrini** [comment]
Here's an example of a past newsletter email 
[Newsletter - New Treasures at the Internet Archive.pdf](https://github.com/internetarchive/openlibrary/files/4099704/Newsletter.-.New.Treasures.at.the.Internet.Archive.pdf)

**Comment by cdrini** [comment]
Email comes from archive.org: 
![image](https://user-images.githubusercontent.com/6251786/72930406-dd102e00-3d29-11ea-8450-8fafc7238b0a.png)

**Comment by cdrini** [comment]
After verifying email address, the welcome email also comes from IA :/
![image](https://user-images.githubusercontent.com/6251786/72930599-455f0f80-3d2a-11ea-93a1-e9d3534b9b83.png)
