### ISSUE TITLE
Work subtitles should be shown in matching works in My Stats

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#8585]
My Stats page matching works doesn't show work subtitles, which can sometimes be important for distinguishing works

### Evidence / Screenshot (if possible)
![зображення](https://github.com/internetarchive/openlibrary/assets/58372007/542c2747-425a-4d7f-b899-9104cbf47ec7)

### Relevant url?
Author with such works https://openlibrary.org/authors/OL10602562A/Michael_Sisa

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by siddoinghisjob** [comment]
Can I work on this issue? Could you please assign this to me?

**Comment by cdrini** [comment]
Go for it @siddoinghisjob !

**Comment by siddoinghisjob** [comment]
@cdrini Can you please tell me how to reproduce the bug? The mentioned link has no such issue. It shows the sub-titles along with the titles. 
![image](https://github.com/internetarchive/openlibrary/assets/96379749/df107abb-64d2-49ab-a312-bcc3d1fc0515)

**Comment by cdrini** [comment]
Hi @siddoinghisjob  ; you'll need to add some books (with sub titles) to your already read shelf, then go to your already read books and click the "reading stats" link. Then, click on one of the bar charts. You'll see a list of books at the bottom of the screen! URL should be something like https://openlibrary.org/account/books/already-read/stats

**Comment by siddoinghisjob** [comment]
Sorry for asking again. I have been stuck at mybooks.py for a while now. In mybooks.py, I want to add 'subtitles' to the works_json's items so I can print them (book information) on the HTML view. But I can not find the attribute of subtitles anywhere. Can anyone please point me in the right direction in order to find the attribute of 'subtitle' so that I can add it to the works_json object? @cdrini

**Comment by cdrini** [comment]
Hi @siddoinghisjob ; the works json will already have the subtitle if one exists. See if you can find the file that renders that line of text. It might be in the html or the js. A common pattern for this is to in your browser, right click the line of text, and click "inspect element". Then see if there's a unique looking class name on/near the element. Then search the codebase for that class name. That should take you to the right file.

**Comment by siddoinghisjob** [comment]
Sorry @cdrini for the delay; I have made a PR, which should fix this. This is my first contribution, and hence I was a little slow and clumsy, but I promise I will be quicker from now on.....

**Comment by cdrini** [comment]
Hi @siddoinghisjob nothing to apologize for! I will take a look once I get some time :+1:
