### ISSUE TITLE
Prioritize list of OSP ISBNs to stage vs. IDB

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8589]

**Comment by scottbarnes** [comment]
Around 3500 records were imported, where ISBNdb had adequate metadata and Open Library did not already have a record.

The output log including edition and work keys is here in case it's desirable to perform a mass operations on the items: [osp_output_log.jsonl.gz](https://github.com/internetarchive/openlibrary/files/14879953/osp_output_log.jsonl.gz)

Additionally, the following query can find all OSP-related imports: https://openlibrary.org/query.json?type=/type/edition&source_records~=osp:* (`limit` and `offset` work to page through the results).

Once #9034 is merged this issue can be closed.
