### ISSUE TITLE
Mobile Search Results Page (make mobile search v2)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#859]
part of #679

**Comment by mekarpeles** [comment]
@vigneshtdev
If you make a search on desktop today, you'll notice the search results interface looks like:

![current-search-desktop](https://user-images.githubusercontent.com/978325/40277428-c19e8a38-5bd3-11e8-8f1b-57eb6501fbd6.png)

I imagine we want something a bit closer to:
![search-mobile](https://user-images.githubusercontent.com/978325/40277676-edb19832-5bd7-11e8-9121-833a0986ed0c.png)

**Comment by LeadSongDog** [comment]
That looks cleaner but sacrifices function, losing the list of possible filter terms. Are they to hide under the filter icon? Perhaps show just the filter types (author, subject, ...) so two clicks gets to the filtered list.

It takes a lot of scrolling to get down to the page selection list at bottom, and this scrolling has to be repeated to move past each page. Best practice would move or clone the page selector list up to the top of the result page.

**Comment by mekarpeles** [comment]
@LeadSongDog if possible, can you provide a rough sketch / drawing of what you're envisioning?

The biggest take-home from the graphic above is that search results / books are full-width. Excited to entertain better ways of managing filters in mobile.

**Comment by LeadSongDog** [comment]
This is pretty rough. You’ll have to envision full width results vice my white-out, and a drop down twisty for each filter (authors, etc.). 

![img_1022](https://user-images.githubusercontent.com/11435431/40405346-383a72bc-5e2a-11e8-9d82-8d9cde65e3f9.PNG)

**Comment by mekarpeles** [comment]
Thanks @LeadSongDog -- this accomplished what I was hoping it would.

I see what you mean by providing a top level facet drop-down for each filter type. I like the idea, I'll talk to @whatisgalen and @vingestdev and see what we can come up with.

**Comment by mekarpeles** [comment]
@vigneshtdev it would be great if the design was mobile first (desktop second)

In general, it would also be nice if the page still *worked* without javascript (at least the core functionality worked). JS is allowed :)

**Comment by mekarpeles** [comment]
Hi @vigneshtdev, is this still something you're working on? Please let me know because otherwise @whatisgalen and I can make other plans. :)

**Comment by tabshaikh** [comment]
@mekarpeles would begin work on this, some guidelines if possible

**Comment by tabshaikh** [comment]
@mekarpeles got your point, let's finalize a design and then start working. The wireframe is an awesome place to start. Let me get back to you with some designs then we can begin working on them

**Comment by jdlrobson** [comment]
When #1577 (which I've approved) is merged can we call this done and open up a new more descriptive ticket for any further work?
