### ISSUE TITLE
Standardize the Edit button on books page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8590]
Currently on the Books Page, we have an Edit button that looks like this:

<img width="795" alt="Screenshot 2023-12-04 at 9 43 28 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/7e68b837-2730-48cf-9d04-16a883f7d596">

It uses the classes `linkButton larger`. We instead want to instead use the `.cta-btn` class `&--vanilla` in https://github.com/internetarchive/openlibrary/blob/6b1fdeb5372f8d6e5cd66ec8fc495a90ed954def/static/css/components/buttonCta.less#L4

The goal is to use fewer different buttons and to increase our consistency.

We also want to update the `vanilla` button so its visited states does not set color to #fff. e.g.

```
  &--vanilla, &--vanilla:visited, &--vanilla:link {
    padding: 5px;
    border: 2px solid @light-grey;
    background: @white;
    color: @grey;
    border-radius: 6px;
  }
  ```

**Comment by KshitijThareja** [comment]
Hi @mekarpeles . I'd like to work on this issue. Could you please assign it to me?
Thanks :)

**Comment by mekarpeles** [comment]
Yes! Very happy to.

While you're making this change, can you also please update the file `openlibrary/templates/type/edition/admin_bar.html` so the css classes look like `cta-btn cta-btn--small cta-btn--vanilla` and not just `cta-btn--vanilla`?

If you want to test that your code works, on your local environment you can log in and go to any book page it it should look something like this (I've highlighted the affected regions in yellow):

<img width="1076" alt="Screenshot 2023-12-04 at 10 13 15 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/86879139-46dc-4c66-b061-c27cf1f3ac4b">

**Comment by mekarpeles** [comment]
Here's instructions on how to login to your local environment:
https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md#logging-in-as-admin

**Comment by mekarpeles** [comment]
Just for fun, here are all the places where the old `linkButton` styling is used. Eventually we want all of these to use the `cta-btn--vanilla` (once we've standardized + fixed it).

```
macros/databarDiff.html:        <a class="linkButton" href="$changequery(m='history')" title="View the editing history of this page">$_("History")</a>
macros/databarDiff.html:        <a class="linkButton" href="$changequery(m='None')" title="View this page (exit Comparison view)">$_("View")</a>
macros/databarEdit.html:        <a class="linkButton larger" href="$page.key?m=history" title="View the editing history of this page">$_("History")</a>
macros/databarHistory.html:            <a class="linkButton larger" href="$edit_url" title="$_('Edit this template')"
macros/databarTemplate.html:      <a class="linkButton larger" href="$changequery(m='history')" title="View this template's edit history" accesskey="h">$_("History")</a>
macros/databarTemplate.html:        <a class="linkButton larger" href="$changequery(m='edit')" title="Edit this template"
macros/databarView.html:          <a class="linkButton larger" href="$edit_url" title="$_('Edit this template')"
templates/admin/profile.html:<button class="linkButton" url="/admin$page.key" title="Edit this template" accesskey="e">$_("Admin")</button>
templates/recentchanges/header.html:                <button class="linkButton" name="#" accesskey="u" id="undo-button" type="submit">Undo All</button>
templates/type/edition/compact_title.html:    <a class="linkButton linkButton--large" href="$edit_url" title="$_('Edit this template')"
```

**Comment by KshitijThareja** [comment]
Sure. After the initial changes are done and verified, we can go forward with changing all the occurrences of the old linkbutton. I'd be happy to work on it 😃

**Comment by seabelis** [comment]
I think this may have changed the tooltip to indicate that the button/link corresponds to the template rather than the edition or work. Maybe I just never noticed this before. Unfortunately, my screenshot does not capture the tooltip, but when I hover over the edit button, it says edit this template. When I hover over the history link, it says view this template's edit history. Neither of these show template information; they are specific to the edition or work.
