### ISSUE TITLE
Updating Twitter logo to X

### ISSUE THREAD

**Issue by parmishh** [internetarchive/openlibrary#8599]
Twitter logo has been changed to X.  But the website's logo hasn't updated.

### Proposal & Constraints

The current logo looks like: 
<img width="142" alt="Screenshot 2023-12-08 114548" src="https://github.com/internetarchive/openlibrary/assets/91942072/9491fbfb-a158-4e6e-80b6-0140e66baf55">

After changing the logo will look like:
<img width="136" alt="Screenshot 2023-12-08 114519" src="https://github.com/internetarchive/openlibrary/assets/91942072/8104c95c-7bc4-4668-bfda-05acac897e1b">

If the issue needs to be solved. 
**please assign me**, would like to work on it.

**Comment by rishabhkr-r111** [comment]
@parmishh Twitter logo has to be updated to X in the share button popup also.

<img width="358" alt="image" src="https://github.com/internetarchive/openlibrary/assets/117273351/982db1c3-23f1-443f-b886-6780e7fbc8ba">

**Comment by parmishh** [comment]
Hi @mekarpeles can this be assigned to me.

**Comment by parmishh** [comment]
> @parmishh Twitter logo has to be updated to X in the share button popup also.
> 
> <img alt="image" width="358" src="https://private-user-images.githubusercontent.com/117273351/289356756-982db1c3-23f1-443f-b886-6780e7fbc8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMjUwODcsIm5iZiI6MTcwMjIyNDc4NywicGF0aCI6Ii8xMTcyNzMzNTEvMjg5MzU2NzU2LTk4MmRiMWMzLTIzZjEtNDQzZi1iODg2LTY3ODBlN2ZiYzhiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQxNjEzMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZGJjN2Q0NWQ5NDNlM2ZhNzRlNjc2YjlkOGQ3NjVmOWZiZjIyNzlmYzk3YzY4ZWI3Zjg5MTkyOTBiYzRhNWJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Z1NFm0Z1QzzbRxswExOS6_A3orgCa1_xV3Ntx0o7BlQ">

Thanks for pointing out.

**Comment by mekarpeles** [comment]
@parmishh sure, let's please just remove the entire twitter/X icon + link from the footer and **not** update it. 

And let's update the twitter icon to X in the editions page modal.
![image](https://github.com/internetarchive/openlibrary/assets/978325/e6aa9ede-8208-440f-9163-e8bd9ac23f36)

**Comment by parmishh** [comment]
> @parmishh sure, let's please just remove the entire twitter/X icon + link from the footer and **not** update it.
> 
> And let's update the twitter icon to X in the editions page modal. ![image](https://private-user-images.githubusercontent.com/978325/289658996-e6aa9ede-8208-440f-9163-e8bd9ac23f36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjczNjUsIm5iZiI6MTcwMjYyNzA2NSwicGF0aCI6Ii85NzgzMjUvMjg5NjU4OTk2LWU2YWE5ZWRlLTgyMDgtNDQwZi05MTYzLWU4YmQ5YWMyM2YzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxNVQwNzU3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzJiN2E5ZGZjMzczNDYzMDA2OWI5YmMyZmQ3MThiOWFmOTBjOWU5NWM0MGIzNjljMTU3N2I1MGZlNDI2YzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JGTZnbzfrrGLhXJAgMoQzOUX398DKnHQCYREaSaKEHk)

So I need to completely remove the twitter/X logo from footer , I mean no logo for it in footer?

**Comment by WilsonGoins** [comment]
Hey, @parmishh can I be assigned to this issue? Just to confirm, we want to update the Twitter logo to the X logo in the share button, and then remove it entirely from the footer so that there is only the GitHub logo?

**Comment by mekarpeles** [comment]
Deciding to keep as is for now.
