### ISSUE TITLE
c# authentication example / help

### ISSUE THREAD

**Issue by bradyguyc** [internetarchive/openlibrary#8634]
### Question
I am having problems with my C# code to authenticate with openlibrary.org and was hoping someone here might be able to help.  

I am running this on a fairly mature mobile app that runs on iOS and Android using .net maui.  

Any thoughts/help would be greatly appreciated.

I have also tried using postman but can't get it to run successfully either curl works but so far that's all I can get to work.

Related to issue https://github.com/internetarchive/openlibrary/issues/8210

Thanks
Brady

```cs
using System;
using System.Diagnostics;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;


namespace MyNextBook.Helpers
{
    public class OpenLibraryLogin
    {

        
        private const string LoginUrl = "https://openlibrary.org/account/login";

        public async Task<string> Login(string accessKey, string secretKey)
        {
            var client = new HttpClient();
            var content = new StringContent($"{{\"access\": \"{accessKey}\", \"secret\": \"{secretKey}\"}}", Encoding.UTF8, "application/json");

            try
            {
                var response = await client.PostAsync(LoginUrl, content);

                if (response.IsSuccessStatusCode)
                {
                    foreach (var header in response.Headers)
                    {
                        Debug.WriteLine($"{header.Key}: {string.Join(", ", header.Value)}");
                    }

                    var sessionCookie = response.Headers.GetValues("Set-Cookie");
                    return string.Join(", ", sessionCookie);
                }
                else
                {
                    Debug.WriteLine($"Login failed with status code: {response.StatusCode}");
                    return null;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Exception occurred during login: {ex.Message}");
                return null;
            }
        }
    }
}
```

When I run the code this is what I get on the console:  Note no Set-Cookie or set-cookie 

Resolved pending breakpoint at 'C:\d3\MyNextBook\Helpers\OpenLibraryLogin.cs:34,1' to void MyNextBook.Helpers.OpenLibraryLogin.<Login>d__1.MoveNext () [0x001c0].
[0:] Date: Fri, 15 Dec 2023 17:04:30 GMT
[0:] Referrer-Policy: no-referrer-when-downgrade
[0:] Server: nginx/1.18.0, (Ubuntu)
[0:] Transfer-Encoding: chunked
[0:] X-Android-Received-Millis: 1702659868732
[0:] X-Android-Response-Source: NETWORK 200
[0:] X-Android-Selected-Protocol: http/1.1
[0:] X-Android-Sent-Millis: 1702659868219
[0:] x-ol-stats: "MC 1 0.000 TT 0 0.075"
Thread finished: <Thread Pool> #5

### Additional context

Here is the output from the curl command that works as expected.

**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.9.0-pre.2.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************

C:\Program Files\Microsoft Visual Studio\2022\Preview>curl
curl: try 'curl --help' for more information

C:\Program Files\Microsoft Visual Studio\2022\Preview>curl -i -H "Content-Type: application/json" -d "{\"access\": \"[REDACTED]\", \"secret\": \"\[REDACTED]"}" https://openlibrary.org/account/login
HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Thu, 14 Dec 2023 18:07:50 GMT
Transfer-Encoding: chunked
Connection: keep-alive
set-cookie: session=[REDACTED]
Referrer-Policy: no-referrer-when-downgrade

C:\Program Files\Microsoft Visual Studio\2022\Preview>

### Issue resolution criteria
Recommended changes to the c# code so that it returns the session cookie.

**Comment by jimchamp** [comment]
Try using the JSON endpoint for your login URL: `private const string LoginUrl = "https://openlibrary.org/account/login.json";`

Also, be sure not to publish your session cookie or S3 keys.

**Comment by bradyguyc** [comment]
Hot dog.... Thanks much @jimchamp  sometimes you just need another set of eyes...   And thanks for the publish note... I'll be making those user encrypted stored on device settings.
