### ISSUE TITLE
"-- Move to a new work" doesn't transfer authors from the previous work into a new one

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#8637]
There is a librarian-only feature which allows you to move edition into an entirely new work, but this new work doesn't have any authors added, and you have to add them manually each time. I suppose, most cases where we would use this feature is multiple volumes which are in one work and they need to be deconflated. So, it would be better to have for new works the same author as in the work edition previously belonged to.

### Evidence / Screenshot (if possible)
![зображення](https://github.com/internetarchive/openlibrary/assets/58372007/611f9804-f6ea-4b04-8f31-d77bac425245)

### Steps to Reproduce

1. Go to any edition
2. Do edit
3. in "What work is this an edition of?" field type "-- Move to a new work"
4. save the edit

* Actual: new work is created with no authors
* Expected: new work is created with the same authors as the work to which the edition previously belonged

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

- To `openlibrary/templates/books/edit/edition.html` after the `multi-input-autocomplete--works`, add two check boxes (unchecked by default):
    - One that says "Copy authors to new work"
    - One that says "Copy subjects to new work"
- Add JS to openlibrary/plugins/openlibrary/js/edit.js to only show these checkmarks if the input with name `edition--works--0--key` has value set to `__new__`
- https://github.com/internetarchive/openlibrary/blob/6e4c4f80db8b8ad1c5dce02acc061fdbb1dc019a/openlibrary/plugins/upstream/addbook.py#L610-L614
    - Handle the new check marks here, copying as necessary

**Comment by mekarpeles** [comment]
@cdrini mentions this may have originally been a conscious decision and that one solution may be a checkbox that is de-selected by default to move the author to the new work.

**Comment by cdrini** [comment]
Actually, to keep the implementation simple, let's keep the just always copy over the authors. It's much easier to delete the authors afterwards than to try to copy them.

Does that make sense from a librarian perspective? CC @seabelis

**Comment by seabelis** [comment]
This was intended because usually if you have to move to a new work, the author is incorrect.

Having the wrong authors in the history can complicate matters. I'd rather not add them.

**Comment by cdrini** [comment]
Sounds good to me! We talked about this over community call as well :) Examples brought up are like author books (eg "Picasso") which are all entirely different books! Having the option seems like the best deal.

We'll add a check box option as initially proposed, and it will default to being unchecked :+1:

**Comment by LeadSongDog** [comment]
@mekarpeles 
If we can’t get this fixed sometime soon, could we at least get a timely message to warn the librarian that the newly created work has no author linked? I’ve been trying to deconflate *The Waverley Novels*, but in the process I find I am inadvertently creating a bunch of unauthored work records. A warning would really help.
