### ISSUE TITLE
Add/update MARC language codes & captions

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#864]
There are a number of updates to language names and codes which should be incorporated at: https://www.loc.gov/marc/languages/languagechg.html

**Comment by guyjeangilles** [comment]
Related to #863. 

@tfmorris It looks like this is something you'd handle. Has there been progress and are you willing to be assignee. Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by tfmorris** [comment]
#1558 might help demonstrate where things need to be updated. It would make sense to address in conjunction with #863. I'm not adding it to my list of things to fix.

In addition to the main table update, it looks like there are some mapping tables embedded in various bits of code, e.g.

https://github.com/internetarchive/openlibrary/blob/22da07aef6f8aa83571d43a89e5ab22fda28a438/openlibrary/catalog/marc/parse.py#L223
https://github.com/internetarchive/openlibrary/blob/cf14f6a0cdf1623b9bf6bd7d07b43cf01191e8e1/openlibrary/catalog/importer/load.py#L195

@hornc probably knows more about which one(s) are active (and if there are others that I didn't stumble across).

**Comment by LeadSongDog** [comment]
LoC maintains both the MARC and the ISO language codes at https://www.loc.gov/standards/codelists/languages.xml

While it would be great to see this “just work”, a reasonable alternative would be to provide an agreed place to capture any known but unsupported language name, such as spelling it out in the edition details.

**Comment by hornc** [comment]
I should be able to resolve this when completing #9447
