### ISSUE TITLE
Book Description not available in Open Library when hovered

### ISSUE THREAD

**Issue by dhruvchandak30** [internetarchive/openlibrary#8649]
### Describe the problem that you'd like solved

When hovered on any book in archive.org we get a clear description about the book like the author, published in, topics, collection whereas in openlibrary.org when hovered on any book  we just get the title and author name.

### Proposal & Constraints

My proposal is to add the similar feature to open library section also

![image](https://github.com/internetarchive/openlibrary/assets/116879117/34af281e-2cd0-4be4-b011-24dccb39025e)

**Comment by dhruvchandak30** [comment]
@mekarpeles  Can I start working on this?

**Comment by mekarpeles** [comment]
I think this issue is currently out of scope for now. I'd rather we not rely on a popup for info, especially when a popup won't be easily accessible on mobile. One thing we've discussed is adding title but for now, I think the resolution to this proposal is "not planned". Thank you for the idea!
