### ISSUE TITLE
Internationalize language labels

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#865]
Currently all language labels are available in English only (unless English speakers use the language's native name).

Language labels should be fully internationalizable like the rest of the UI. As a short term stop gap, we could at least change the single label to include both the English name and the name in the native language (e.g. French / Français, German / Deutsch ).

**Comment by salman-bhai** [comment]
Hi, where can I find the files for this? Tried searching for labels but couldn't really find it!

**Comment by tfmorris** [comment]
The current labels come from e.g. https://openlibrary.org/languages/eng.json

**Comment by salman-bhai** [comment]
Okay that sounds about right! How do we proceed to add new files for other languages? @mekarpeles @tfmorris

**Comment by mekarpeles** [comment]
Where / how is this being used? Do you know @tfmorris

**Comment by guyjeangilles** [comment]
@tfmorris Bumping @mekarpeles' question. Where is that JSON generated?

**Comment by tfmorris** [comment]
This is the list of languages: https://openlibrary.org/languages
The template for that page is here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/languages/index.html
This is the page for French https://openlibrary.org/languages/fre
This is the JSON version of the French page: https://openlibrary.org/languages/fre.json
The list is served by this autocomplete endpoint https://openlibrary.org/languages/_autocomplete?q=fr&limit=6&timestamp=1574648477215
which is called from the edition edit page here: https://github.com/internetarchive/openlibrary/blob/3bbb234fb26bb95b049aa9c491669f54ae7d0dfa/openlibrary/templates/books/edit/edition.html#L19

**Comment by tfmorris** [comment]
I've updated French and German with the proposed stopgap here: https://openlibrary.org/languages

If this looks good to folks as an interim, any librarian/admin can complete the work using the list here: https://www.omniglot.com/language/names.htm

**Comment by tfmorris** [comment]
@mekarpeles Are you happy with the stop gap?

@seabelis Are you willing to take the interim updates on as a librarian task? I can create a separate issue for that so that we can use this issue to track the full solution.

**Comment by seabelis** [comment]
> I have a slight preference for the latter, just to make things more consistent with a single language being used first.

Agree with @tfmorris . 

Yes, I can work on this.
