### ISSUE TITLE
Add 'Want to Read' Dropper to the Search Inside page 

### ISSUE THREAD

**Issue by rishabhkr-r111** [internetarchive/openlibrary#8650]
Add 'Want to Read' Dropper to the Search Inside page as it appears on Books search result page and Authors search result page. Otherwise uses have to navigate to books pages to do so.

### Proposal
Dropper can be added below existing borrow button similar to other pages.

<img width="650" alt="image" src="https://github.com/internetarchive/openlibrary/assets/117273351/29df1782-1037-4afc-ad51-ad9dae0b7ae9">

@mekarpeles Can i work on this issue?

**Comment by sarthakkapila** [comment]
Hey @rishabhkr-r111 , I was wondering if you were working on this issue? As I'm really keen on resolving it.

**Comment by rishabhkr-r111** [comment]
@sarthakkapila I am currently working on this issue. I will soon submit a PR request.
