### ISSUE TITLE
Bulk Tagger: Disable "Submit" button after submission is made

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8651]
### Describe the problem that you'd like solved

After submitting a bulk tag update, the "Submit" button is still enabled and can be pressed again.

### Proposal & Constraints

After the "Submit" button is initially pressed, disable the button and replace the button's text with a loading spinner.  When the `POST` response is received, replace the loading indicator with "Submit".  If the response was an error, re-enable the submit button.

### Additional context

[This method](https://github.com/internetarchive/openlibrary/blob/ecfd0b137b08b76deac027a9e016ecd80e79b791/openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js#L509-L529) is responsible for submitting the bulk tag operation.

**Comment by xonx4l** [comment]
assign it to me @jimchamp .THANKS.

**Comment by jimchamp** [comment]
Assigned.  You'll probably want to use [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout) to simulate latency while developing.
Also, we added a spinner animation in #8555.  Try to reuse that animation in the button, if possible.
