### ISSUE TITLE
Bulk Tagger: Move "Create subject" affordance to bottom of menu options scroll container

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8652]
### Describe the problem that you'd like solved

Our bulk subject tagging tool allows librarians to search for existing tags and create new tags.  The affordance for creating new tags is initially hidden until some text is added to the search input.  When it is visible, it is pinned to the bottom of the bulk tagger, below the scroll container that holds the subject options.

Since all menu options may not be visible on the screen at once, and the "Create subject" affordance is essentially always  present at the bottom of the bulk tagger, it is very easy for librarians to create a subject that is already represented by a menu option.

### Proposal & Constraints

Move the "Create subject" affordance to the bottom of the scroll container which holds the menu options.  This will force people to look at each available menu option before being able to create a new subject, and will hopefully prevent folks from creating a subject that already exists.

Existing visibility rules for the "Create subject" affordance should remain unchanged:  If the subject search input is empty, the affordance should be hidden.

### Additional context

The root element of the "Create subject" affordance has class `create-new-subject-tag`.  This should be moved into the container that has class `selection-container`.

The bulk tagger is rendered client-side by the `renderBulkTagger` function, [here](https://github.com/internetarchive/openlibrary/blob/ecfd0b137b08b76deac027a9e016ecd80e79b791/openlibrary/plugins/openlibrary/js/bulk-tagger/index.js#L6C17-L6C33).

The affordance should look the same after it is moved the the new container.  If any CSS changes are needed, they should be made to [this file](https://github.com/internetarchive/openlibrary/blob/ecfd0b137b08b76deac027a9e016ecd80e79b791/static/css/components/tagging-menu.less).

For reference, the "Create subject" affordance is labeled as "Create Tag Buttons" in the below image:
![bt_labeled](https://github.com/internetarchive/openlibrary/assets/28732543/c576bb3c-4ab0-426e-9f50-2e88d872a157)

**Comment by QuantuM410** [comment]
Hey! I would like to work on this, do I have to create a draft PR to get it assigned?

**Comment by QuantuM410** [comment]
Hey @jimchamp! I have added a PR! Can you please look into it?
