### ISSUE TITLE
Bulk Tagger follow-up tasks

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8653]
This issue tracks follow-up tasks for the latest [bulk tagger work](https://github.com/internetarchive/openlibrary/pull/8575).

- [x] #8652
- [x] #8651 
- [ ] #8657
- [x] #8658
- [x] #8659

**Comment by mekarpeles** [comment]
Given all issues are closed here except #8657, I'm going to close this epic. Thanks for your great work @jimchamp!
