### ISSUE TITLE
Bulk Tagger: Highlight staged options

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8658]
### Describe the problem that you'd like solved

Today, the bulk tagger tool doesn't give any indication of what subjects are staged to be updated.  The only indication that something is staged is the submit button.  If nothing is staged, then the "Submit" button is disabled.  This make it very easy to accidentally add or remove subjects to works.

### Proposal & Constraints

Whenever a subject has been staged for addition or removal, add a highlight to the corresponding menu option.

![L9fXjjJRK97eyP6ADySysw2hQguT-rvLXsWYoFN18s9MOFp8m0bL47uUEG104uIsewXPGxef12twoqI3ksyNyKEH_nit396UIoyvCD5DYWWvRZmDaZFPdTQ_cd-mhmPgC2W_-gzHmz0-QpaV7cHqbUw](https://github.com/internetarchive/openlibrary/assets/28732543/5cc2d0f8-ee2a-40c8-ab78-22ecfe29524b)

### Additional context

Bulk tagger menu options are represented by the MenuOption class, in [this file](https://github.com/internetarchive/openlibrary/blob/7e32e7f1bdbb7e2c7ae8408bedd077ee5a2de68f/openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger/MenuOption.js).

The [`onMenuOptionClick` function](https://github.com/internetarchive/openlibrary/blob/7e32e7f1bdbb7e2c7ae8408bedd077ee5a2de68f/openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js#L323) is the called when a menu option is, you guessed it, clicked.

Any additional style rules should be added to [`tagging-menu.less`](https://github.com/internetarchive/openlibrary/blob/7e32e7f1bdbb7e2c7ae8408bedd077ee5a2de68f/static/css/components/tagging-menu.less).

Whenever the bulk tagging form is successfully submitted, the highlighting treatment should be removed from all menu options.

**Comment by QuantuM410** [comment]
Hey! I am interested in solving this issue. Could you please assign it to me?

**Comment by jimchamp** [comment]
Thanks, @QuantuM410.

**Comment by QuantuM410** [comment]
@jimchamp Just an additional query, whenever a subject is staged for addition or removal the submit button is active but if u click on the staged subjects again, there should be no staging to  be done and the submit button should deactivate again. Is this intentional behaviour or not? Also I have implemented highlighting to staged subjects but have a similar doubt regarding the same i.e. if I add a subject it highlights light green and if I remove it it highlights light red, now If I add a subject it turns green but if I click on it again it turns red - considering it a staged change just like the button.

**Comment by jimchamp** [comment]
There is no mechanism to unstage subjects at this time.  Depending on its initial state, once a menu option for a subject is first clicked, that subject is either staged for addition or removal.  If a subject is staged for addition and its menu option is clicked again, it is then staged for removal (and vice versa).

Just highlight staged options in yellow, as pictured above.

**Comment by QuantuM410** [comment]
> There is no mechanism to unstage subjects at this time. Depending on its initial state, once a menu option for a subject is first clicked, that subject is either staged for addition or removal. If a subject is staged for addition and its menu option is clicked again, it is then staged for removal (and vice versa).
> 
> Just highlight staged options in yellow, as pictured above.

I ve created a draft PR [here](https://github.com/internetarchive/openlibrary/pull/8676). Please check :)
