### ISSUE TITLE
ILE: Increase visibility of selected works

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8659]
### Describe the problem that you'd like solved

When works or authors are selected with the ILE tool, the selected items are displayed _below_ the ILE blue bar.  In order to see what was selected, one has to scroll to the bottom of the page.  If there is no cover or author image, it's even more difficult to see what was selected:

![image](https://github.com/internetarchive/openlibrary/assets/28732543/97d0c173-86ea-4f4c-9e09-9122e62799ba)
_What is the second selected item?  A book?  An author? Something else?_

### Proposal & Constraints

It might be nice if clicking on "`N` works selected" blue bar text somehow displayed what was selected.  Maybe the blue bar and the selections could slide up like a drawer?  Maybe the selected works appear above the bar on click?  Either way, the assignee should probably propose a solution for this before implementing it.

It would also be great if the selected items were links to the corresponding book or author page.

**Comment by QuantuM410** [comment]
Hey @jimchamp , I am interested in working on this issue. Could you please assign it to me? Or do I have to create a draft PR and we can continue from there as its mentioned ->[**here**](https://github.com/internetarchive/openlibrary/issues/8675#issue-2060342970)

**Comment by mekarpeles** [comment]
@QuantuM410 yes, please do create a draft as per the instructions and we can discuss your solution! :)

**Comment by xonx4l** [comment]
This allows users to quickly preview the selected items on demand by clicking the selection count text. The preview can then be dismissed to go back to the normal toolbar view.

**Comment by jimchamp** [comment]
@cdrini, you mentioned that the cover images below the blue bar are needed for some drag and drop functionality.  Can you provide some more information about this to @QuantuM410?  I don't really understand how that all works (or how its supposed to work).

**Comment by cdrini** [comment]
Hi! Yep! Basically, we use the `setDragImage` API to create an image that appears as you drag the selection (note: you can drag books from one tab to another):

![image](https://github.com/internetarchive/openlibrary/assets/6251786/74796c65-8199-4e07-90e2-a211e85857f7)

On FF, the element passed to `setDragImage` must be visible on the page. That is why the covers appear at the bottom. These covers should at the bottom should hence remain unaltered in order to allow the drag image preview to continue working (or they should be updated on purpose anyways). Any extra info should be added outside of this element:

https://github.com/internetarchive/openlibrary/blob/9e7f5bad39219511b5c6e1d9f62311592afde41f/openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js#L261

**Comment by jimchamp** [comment]
To be clear, we are not expecting any code changes with your proposals.

**Comment by QuantuM410** [comment]
> Hi! Yep! Basically, we use the `setDragImage` API to create an image that appears as you drag the selection (note: you can drag books from one tab to another):
> 
> ![image](https://private-user-images.githubusercontent.com/6251786/294035633-74796c65-8199-4e07-90e2-a211e85857f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTI1NzAsIm5iZiI6MTcwNDM5MjI3MCwicGF0aCI6Ii82MjUxNzg2LzI5NDAzNTYzMy03NDc5NmM2NS04MTk5LTRlMDctOTBlMi1hMjExZTg1ODU3ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTgxNzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUzNjY2YTQyOTgxNjU0ZDMwMDMyMzc5MTFmMzU1YjJmZGE4ZWEzMWRkYmE5NmRkMmZlNjkxMTVkZDM1OWZiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Nne_eXiEJYMlEXltMEUcHDvSZ133vzRhdkRAcTSlbM)
> 
> On FF, the element passed to `setDragImage` must be visible on the page. That is why the covers appear at the bottom. These covers should at the bottom should hence remain unaltered in order to allow the drag image preview to continue working (or they should be updated on purpose anyways). Any extra info should be added outside of this element:
> 
> https://github.com/internetarchive/openlibrary/blob/9e7f5bad39219511b5c6e1d9f62311592afde41f/openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js#L261

So can we create a drawer or a menu like bulktagger to deal with the selected elements or will it alter the drag and drop functionality. If its like that the only feasible option can be to make covers appear above the ILE blue bar on the page on click? Correct me if I am wrong.

**Comment by QuantuM410** [comment]
> > Hi! Yep! Basically, we use the `setDragImage` API to create an image that appears as you drag the selection (note: you can drag books from one tab to another):
> > ![image](https://private-user-images.githubusercontent.com/6251786/294035633-74796c65-8199-4e07-90e2-a211e85857f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTI1NzAsIm5iZiI6MTcwNDM5MjI3MCwicGF0aCI6Ii82MjUxNzg2LzI5NDAzNTYzMy03NDc5NmM2NS04MTk5LTRlMDctOTBlMi1hMjExZTg1ODU3ZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMTgxNzUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGUzNjY2YTQyOTgxNjU0ZDMwMDMyMzc5MTFmMzU1YjJmZGE4ZWEzMWRkYmE5NmRkMmZlNjkxMTVkZDM1OWZiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Nne_eXiEJYMlEXltMEUcHDvSZ133vzRhdkRAcTSlbM)
> > On FF, the element passed to `setDragImage` must be visible on the page. That is why the covers appear at the bottom. These covers should at the bottom should hence remain unaltered in order to allow the drag image preview to continue working (or they should be updated on purpose anyways). Any extra info should be added outside of this element:
> > https://github.com/internetarchive/openlibrary/blob/9e7f5bad39219511b5c6e1d9f62311592afde41f/openlibrary/plugins/openlibrary/js/ile/utils/SelectionManager/SelectionManager.js#L261
> 
> So can we create a drawer or a menu like bulktagger to deal with the selected elements or will it alter the drag and drop functionality. If its like that the only feasible option can be to make covers appear above the ILE blue bar on the page on click? Correct me if I am wrong.

@cdrini
