### ISSUE TITLE
Create Vectorized Open Library Logo

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#867]
Right now our logo is fuzzy and we don't really have an assortment of resolutions which can be used by the press. @jeansaung, do you know anyone who may be willing us breath some life into our logo?

**Comment by mekarpeles** [comment]
cc: @evanminto so you can track

**Comment by salman-bhai** [comment]
I'd like to do this if it's possible. Can I know the fonts that are used in the logo.

**Comment by salman-bhai** [comment]
None of the images were of good quality to recreate a vectorised version of the logo.

**Comment by salman-bhai** [comment]
Can something more be added to this, a more elaborate description as to what exactly is needed wrt "assortment of solutions"?

**Comment by seabelis** [comment]
I may be able to help with this. Do you just need the current logo recreated as a vector graphic?

**Comment by mekarpeles** [comment]
@seabelis yes! We'd love your help vectorizing the current logo: https://openlibrary.org/static/images/openlibrary-logo.png.

I believe the fonts are trajan pro and helvetica rounded bold (or google cinzel)

@salman-bhai helped get us started by vectorizing our previous logo: https://openlibrary.org/static/images/openlibrary-logo.png (which has some of the fonts/assets, in case it helps)

We're also open to your artistic liberties / touches if we happen to have violated any design principles in the process of making this logo  :)

**Comment by seabelis** [comment]
Do you happen to know the PMS# for the blue? If not, I can use the eyedropper tool.

**Comment by seabelis** [comment]
![openlibrary-logo-side-by-side-01](https://user-images.githubusercontent.com/17739465/37554782-c6a390f0-29dd-11e8-93e1-d0459ea6a91e.jpg)
Here's an initial re-creation. I don't think the font is helvetica rounded as the letters of "open" don't seem to be rounded at the ends (though the png is pretty blurry). The closest thing I have is Helvetica 65. Also, my Trajan font did not quite line up to the one in the logo (for example, the L is not as wide) so maybe it was a similar font or the original designer may have had a version of the font with alternate letters. The spacing was also manipulated it seems. I've tried to match it as best I could, however it looks to me like the gap between the R and the A is too wide. I'd be inclined to try some other options there. But first, I'll take any other feedback on the draft.

**Comment by mekarpeles** [comment]
Fantastic, this is much better than what we currently have! A few minor points of feedback, (a) the word OPEN may be aligned a bit too high on the sign, (b) we may want the sign to have slightly more rounded corners, and (c) I do think the OPEN sign is rounded (it is really pixelated)  -- here's a png + svg of our old designs which we may be able to re-incorporate: 

http://svgur.com/s/5t1 or https://fthmb.tqn.com/5xq2Tvw0itvRVm2OhNLYDbt5DTI=/300x0/open-library-logo-5980eddcc4124400106726d8.PNG

**Comment by seabelis** [comment]
Oh, yes. That's rounded. I don't suppose you have the font files?

**Comment by tfmorris** [comment]
More comments from the peanut gallery: 

- the old R had a straight foot. The extended curved foot of the new one exacerbates the RA spacing problem (which was bad to start with).
- I'd be tempted to play with negative kerning to even have the RA overlap to see if that's less visually annoying than the current gap (hard to tell w/o experimentation)
- the lines for the sign's "string" are too heavy. I think the same weight as the horizontal lines would be good (and that appears to be what the old design used)
- making the string "tighter" so it takes up less vertical space might help the logo fit places better
- I agree with @mekarpeles that Open should be centered in a rounded cornered sign

**Comment by tfmorris** [comment]
Actually, the default Trajan Pro kerning looks fine. It's kerned to overlap by default:

![image](https://user-images.githubusercontent.com/82178/37558208-da8d4576-29e6-11e8-952b-96b2e72941ce.png)

**Comment by mekarpeles** [comment]
@seabelis, here they are! https://drive.google.com/drive/folders/0B1AvV6Nqk7TkRHUwVWFuZHdKYms?usp=sharing :)

**Comment by seabelis** [comment]
@tfmorris Agreed. I also prefer the native spacing. I was trying to match the current logo as best I could, but I see on the .svg file of the older logo, the native spacing was used.

**Comment by seabelis** [comment]
The fonts are for Mac, so my system does not recognize them. I've used Arial Rounded as a substitute. Here I have the Arial font applied to OPEN and I've returned LIBRARY to its native spacing. I've included the overlay view to illustrate the differences.
![openlibrary-logo-side-by-side1](https://user-images.githubusercontent.com/17739465/37565215-284a4de0-2aa5-11e8-8e44-39694c14ec8f.jpg)

I've also noticed a slight difference in the blues used in the svg file and what my eyedropper detected in the png file. Was this an intentional change? Is there an official blue?

**Comment by LeadSongDog** [comment]
That's a huge improvement. It might be even better by adopting the same colour for the string as for the bars over and under the "Library".  Can the "OPEN" be vertically centred in the sign?

**Comment by bfalling** [comment]
This is looking really nice! It'd be great to see it at a few different sizes to see how well it scales up and down.

**Comment by seabelis** [comment]
I've created everything as a vector (Illustrator), so you can make it as big as you want.

**Comment by seabelis** [comment]
Oh, also, I've got Trajan in bold here, so maybe it's too heavy. Everything looks thicker on the pixelated graphic than in the old svg logo, so let me know which is preferred.

**Comment by seabelis** [comment]
![openlibrary-logo-side-by-side1-01](https://user-images.githubusercontent.com/17739465/37587170-d1e5df22-2b5e-11e8-962d-b2835653a060.jpg)
Here I have made some slight adjustments. The OPEN text is nudged down ever so slightly. I've reduced the stroke weight of the lines and string and matched the color. I've changed the Trajan font to regular weight.

**Comment by mekarpeles** [comment]
@seabelis this is looking fantastic

**Comment by mekarpeles** [comment]
@seabelis I'd love to call this issue closed -- is there a place we can access the svg and/or illustrator file (or whatever format was used to create the svg)?

**Comment by seabelis** [comment]
Sure thing. I'll finalize the file in the AM and pack it up.

**Comment by seabelis** [comment]
Download here: https://drive.google.com/file/d/19JHbTLpX9dX96HVfunwfM5xokevZZR2t/view?usp=sharing

I've included a handful of formats; the .ai file is in case you need to make further adjustments down the road (you will need the fonts installed if you want to change the test itself), the .ai outlines file will let you adjust the file, but the type is converted to shapes - so not fonts needed, but you cannot change the text. The .eps file is a generic vector file and then there are a few raster formats - the .png files are with transparency and the .jpg with a white background.

**Comment by mekarpeles** [comment]
Success! thank you @seabelis

**Comment by mekarpeles** [comment]
Added to our official OL google docs: https://drive.google.com/open?id=1GlUpiaobyL6dbxu8Ok_i_R87aalpzH_z

Added to our wiki as well: https://github.com/internetarchive/openlibrary/wiki/Design

**Comment by mekarpeles** [comment]
See #948 -- @nlevitt contributed some tweaks to the svg to enhance the size/presentation

> This tightens up the bounding box around the logo to remove some empty space, so that the logo looks roughly as big as the old one did.

The svg is live! Thanks @seabelis & @nlevitt!
