### ISSUE TITLE
Reading log carousels overflow on tablets

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8672]
The reading log carousels in "My Books" overflow on tablets, or at least they do in the Firefox dev tools for iPad and Kindle.

### Evidence / Screenshot (if possible)
![image](https://github.com/internetarchive/openlibrary/assets/26524678/cb050313-09ec-4b9c-a356-81a69cbe9f44)

### Relevant url?

https://openlibrary.org/account/books

### Steps to Reproduce

1. Use a tablet or the browser dev tools to replicate the tablet experience.
2. Go to https://openlibrary.org/people/<YOUR ACCOUNT HERE>/books
3. Scroll down to the reading log carousels, and look to the right to see that they overflow their bounding box.

* Actual: The carousels overflow.
* Expected: The carousels do not overflow on a tablet.

### Details

- **Logged in (Y/N)?** Yes
- **Browser type/version?** Firefox 120.1
- **Operating system?** Manjaro Linux.
- **Environment (prod/dev/local)?** prod

**Comment by sarthakkapila** [comment]
Hey! I am interested in solving this issue. Can you please assign it to me?

**Comment by sarthakkapila** [comment]
Hey! I have actually solved the bug and created a pull request.
I didn't read [this](https://github.com/internetarchive/openlibrary/issues/8675) earlier and was waiting to be assigned the issue. Do let me know if there are some more changes I can make as i am new to contributing to open source

Thank you.
