### ISSUE TITLE
Copydocs: Add error logging when records fail to import

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8680]
We believe we may be limited in how faithfully we can reproduce production errors in testing environments because copydocs seems to not let us specify revisions of documents and also records seem to fail silently.

https://github.com/internetarchive/openlibrary/blob/master/scripts/copydocs.py

**Comment by dhruvchandak30** [comment]
For this we can create a copydocs.log file, so whenever an error occurs it is logged into that file
When an error occurs during the fetching or saving processes, information about the error is logged into this file. This log file can be helpful for debugging and identifying issues that may occur during the execution of the script.

**Comment by scottbarnes** [comment]
Even if we need to create a new issue to add more comprehensive logging, what about, as a partial fix, something as simple as:

```diff
diff --git a/scripts/copydocs.py b/scripts/copydocs.py
index b59713e94..9a53ec4c0 100755
--- a/scripts/copydocs.py
+++ b/scripts/copydocs.py
@@ -275,8 +275,8 @@ def copy(
     for group in web.group(docs, 50):
         try:
             print(dest.save_many(group, comment=comment))
-        except BaseException:
-            print("Something went wrong saving this batch!")
+        except BaseException as e:
+            print(f"Something went wrong saving this batch! {e}")
     saved.update(keys)
```

Before:
```
openlibrary@9f99aad1aca5:/openlibrary$ PYTHONPATH=. ./scripts/copydocs.py /works/OL246364W?v=2
fetching versioned [KeyVersionPair(key='/works/OL246364W', version='2')]
saving ['/works/OL246364W']
Something went wrong saving this batch!
```

After:
```
openlibrary@9f99aad1aca5:/openlibrary$ PYTHONPATH=. ./scripts/copydocs.py /works/OL246364W?v=2  
fetching versioned [KeyVersionPair(key='/works/OL246364W', version='2')]
saving ['/works/OL246364W']
Something went wrong saving this batch! 400 Client Error: Bad Request for url: http://localhost:8080/api/save_many. Response: {"error": "notfound", "key": "/authors/OL2560490A", "at": {"key": "/works/OL246364W", "property": "authors.author"}}
```

I have a vested interest here as I manually make this change every time I run into import issues because of merges and need to go see what else (and what version) I need to import.
