### ISSUE TITLE
Covers API – many cover images are no longer appearing

### ISSUE THREAD

**Issue by aubreythreadgill** [internetarchive/openlibrary#8681]
The Covers API appears to not be returning images for many titles that were previously working fine.

Example:
https://openlibrary.org/works/OL17590212W/The_Subtle_Art_of_Not_Giving_a_F%2Ack
https://covers.openlibrary.org/b/id/8231990-M.jpg (nor S, nor L)
![image](https://github.com/internetarchive/openlibrary/assets/94575293/a99d54e0-6039-4a94-9cf4-99218484b90c)

This could all just be an issue with United Airlines WiFi?

**Comment by sarthakkapila** [comment]
hey @aubreythreadgill, most probably this is an issue with your wifi connection, as some companies tend block data at the DNS level.
Hope this helps.

**Comment by aubreythreadgill** [comment]
Just landed and that fixed it 😅 Sorry for the false alarm and thanks for the explanation!
