### ISSUE TITLE
Link to gitter chat should be removed as it is unattended

### ISSUE THREAD

**Issue by madmalkav** [internetarchive/openlibrary#8697]
As https://gitter.im/theopenlibrary/Lobby is completely unattended, it would be better to remove the links to that chat

**Comment by mekarpeles** [comment]
Hi @madmalkav! Very sorry! It appears we're not receiving any notifications from gitter even though we'd be very happy to respond :( :( we're checking our settings, I'm sorry for my lack of responses on gitter.

**Comment by madmalkav** [comment]
Well, if that was the problem I’m glad this ticket helped to address it . Closing ticket as removal of the links is no necesary after all
