### ISSUE TITLE
BAD API edit

### ISSUE THREAD

**Issue by rzroth** [internetarchive/openlibrary#8701]
https://openlibrary.org/developers/api

Has 'Partner API' changed to https://www.dreambooks.club/
By "Bernat Fortet | Added Dreambooks.club to "Friends using Open Library APIs" section"

</body>
</html>

https://openlibrary.org/developers/api?v=62 
Is correct:
https://openlibrary.org/dev/docs/api/read

### Steps to Reproduce

1. using API docs

### Details

- **Logged in (Y/N)?** - no
- **Browser type/version?** - any
- **Operating system?** - any 
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Fix edit 

### Stakeholders

[Bernat Fortet](https://openlibrary.org/people/bernat_fortet)
Added Dreambooks.club to "Friends using Open Library APIs" section

**Comment by mekarpeles** [comment]
Fixed
