### ISSUE TITLE
Tabs on Trending page should have same style as those on search page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8702]
### Describe the problem that you'd like solved

Trending page:
![image](https://github.com/internetarchive/openlibrary/assets/6251786/fc034d1c-39a7-40b6-8a82-1e0cba67a993)

Search page:
![image](https://github.com/internetarchive/openlibrary/assets/6251786/461e75ce-7574-45f4-b819-e6675c338fd7)

### Proposal & Constraints
Use the same css structure/classes as the `nav-bar` on the search page.

### Additional context
HTML for the trending page:

https://github.com/internetarchive/openlibrary/blob/5b23175235d15bf6f3e6aec6b7a1a4e72500d174/openlibrary/templates/trending.html

HTML for the search page:

https://github.com/internetarchive/openlibrary/blob/acb61b0a4c0af06596bafba01fce13ed1775c4cb/openlibrary/macros/SearchNavigation.html

**Comment by sarthakkapila** [comment]
Hey, @cdrini can you assign me this issue or should I create a draft PR first?

**Comment by Ayush1404** [comment]
Hey, can you please review if these are the changes that you expected?

**Comment by cdrini** [comment]
Sorry for the confusion @sarthakkapila ! That draft PR flow was something we were experimenting with but decided to stop the experiment. It seems like @Ayush1404 has already created a PR for this one, so I will assign this to them to avoid their work going to waste. Please feel free to tackle another Good first issue!

Thanks @Ayush1404 , I will provide feedback on your PR.

**Comment by sarthakkapila** [comment]
@cdrini No problem at all! and thanks for the update :)
