### ISSUE TITLE
Create Github Project Management Bot

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8704]
- [ ] Posts to slack and tags lead when new comments posted
  - For now, we are not going to auto-assign contributors (we'll continue to manually review comments)
- [ ] Unassigns contributors who are assigned but have not submitted a linked:pr in last 2 weeks

**Comment by rishabhkr-r111** [comment]
@mekarpeles i am interested to work on this.

**Comment by jimchamp** [comment]
@rishabhkr-r111 I'm already assigned.  Please find an issue that has no assignees.

**Comment by spurjhattam2207** [comment]
Can you assign this issue to me? I am interested
