### ISSUE TITLE
Why it take more than normal time to load all the library items when scrolling down ?? can we optimise it somehow??

### ISSUE THREAD

**Issue by xonx4l** [internetarchive/openlibrary#8705]
while working on some bugs I find that it take more than normal time to load all the library items when scrolling down . First I thought there's a problem with my network but now I have seen it happening every time I visit the site .Even the scrolling bar gets laggy sometimes .

It will be great if scroll bar and the  loading time of library items could  be fixed .
 
Thanks.

<img width="1440" alt="Screenshot 2024-01-11 at 8 00 16 PM" src="https://github.com/internetarchive/openlibrary/assets/119700621/5fba7375-2711-4622-969a-031f44cc4293">

**Comment by mekarpeles** [comment]
Hi, this is an issue for archive.org not openlibrary.org so I'm going to close it here.

Tagging @bfalling @iisa & @traceypooh so they're in the loop!

**Comment by xonx4l** [comment]
okay. Thanks.
