### ISSUE TITLE
Add TOOLTIP (that shows username and joined date) when hover over <img class = 'account-username'> 

### ISSUE THREAD

**Issue by Abhishektharu** [internetarchive/openlibrary#8708]
I am wondering whenever I need to see my username I have to go to list>profile to view my username and joined date 
### Describe the problem that you'd like solved

I was thinking of to add tooltip feature to view username and joined date whenever I hover hover my account-profile(picture)
### Stakeholders

@mekarpeles @cdrini

**Comment by Abhishektharu** [comment]
I found tooltip code but stuck to find and fetch the username and joined date. @cdrini please can you guide me how to add this feature?

**Comment by mekarpeles** [comment]
This is lower priority though happy to review if you'd like to give it a try!

**Comment by Ahmed-Armaan** [comment]
Hi, I would like to work on this.

**Comment by rebecca-shoptaw** [comment]
I'd like to work on this! Happy to submit a sample PR with proposed fix if needed.

**Comment by Abhishektharu** [comment]
@rebecca-shoptaw Sure You can work on this Feature. If your sample PR is ready you can submit .
