### ISSUE TITLE
Remove/migrate deprecated i18n method to current Babel/gettext method

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#871]
Open Library i18n is handled via the [python Babel library](http://babel.pocoo.org/en/latest/), `gettext`, and the message lists located https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n

More details [here](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/__init__.py)

The codebase has now deprecated code and strings located here: https://github.com/internetarchive/openlibrary/tree/master/openlibrary/plugins/openlibrary/i18n

There are a small number of messages in a few languages, including the following:

es Spanish
hi Hindi
it Italian
kn Kannada
mr Marathi
nl Dutch

Although the original sources are in git, they were maintained as wiki pages in infogami, so the latest versions are at, e.g., https://openlibrary.org/i18n/strings.nl.json, but there are only a couple of dozen strings per language.

This issue is to remove the deprecated i18n code and strings from the codebase, migrating anything that is useful to the current method's `messages.po` format.

1. Investigate how many already translated strings are still used and could be migrated to an new `<xx>/message.po` file.
2. Investigate current code and templates that rely on this mechanism  and remove.
3. Migrate the messages if appropriate
4. Remove `strings.<xx>`

**Comment by hornc** [comment]
To help with 1. above:
bash one liner to find line numbers in `messages.pot` for messages in a `strings.en`:

`while read msg;do egrep -n "$msg" messages.pot;done < <(sed "s/.*u'\(.*\)'$/\1/" strings.en)`

Partial output to show what it does:
```
1691:msgid "Log out"
2141:msgid "Create it?"
951:msgid "Upload"
1571:msgid "Log in"
```

**Comment by salman-bhai** [comment]
Link to the Wiki for additional info can be found [here](https://github.com/internetarchive/openlibrary/wiki/Contributing-to-Internationalization-(i18n))

**Comment by tabshaikh** [comment]
Link to the readme for additional info can be found here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md

**Comment by tfmorris** [comment]
The historical message files in git were used to seed the wiki, but they've been updated since then, so that, for example, Italian is on version 21 at https://openlibrary.org/i18n/strings.it.json.

These may be too small to bother saving, but wanted to make a note of it so it's not lost to history.

**Comment by tfmorris** [comment]
Here's a summary of what I plan to do with the existing translations:

- es Spanish - drop. The current translation is much more comprehensive
- hi Hindi - 15 strings from 2009 used to seed i18n/hi/strings.hi.yml
- it Italian - 250 strings from git in i18n/it/strings-starting.it and 30 from infogami in i18n/it/strings.it.yml
- kn Kannada - 4 strings saved in i18n/kn/strings.kn.yml
- mr Marathi - 7 strings saved in i18n/mr/strings.mr.yml
- nl Dutch - 29 strings saved in i18n/nl/strings.nl.yml

There are a total of 96 files to be deleted from the old internationalization system.
