### ISSUE TITLE
Clicking "Want to read" button adds different edition of a book

### ISSUE THREAD

**Issue by pekvasnovsky** [internetarchive/openlibrary#8712]
When I click on "Want to read" button on page https://openlibrary.org/books/OL27030061M/The_Demon-Haunted_World it adds the wrong edition to the "Want to read" list and when I click the book in the list it goes here https://openlibrary.org/works/OL2950942W/The_Demon-Haunted_World

---

### Evidence / Screenshot (if possible)
Right after clicking want to read:
![image](https://github.com/internetarchive/openlibrary/assets/145220123/06c83960-24b3-4c05-94d7-cf5161a338d3)

What is in the "Want to read" list web ui
![image](https://github.com/internetarchive/openlibrary/assets/145220123/61d40096-3763-48b9-b819-1275284db521)

After clicking "Preview only" in the want to read list 
![image](https://github.com/internetarchive/openlibrary/assets/145220123/f97ea5df-8305-4dd0-9fcb-a812f61a249e)

---

### Relevant url?

https://openlibrary.org/books/OL27030061M/The_Demon-Haunted_World

---

### Steps to Reproduce

1. Go to https://openlibrary.org/books/OL27030061M/The_Demon-Haunted_World
2. Click on "Want to Read" button
3. Go to https://openlibrary.org/account/books (it should redirect to "My books" page)
4. Look at "Want to Read" list whether you got the correct book or not there
5. Click on the book to verify you got the incorrect edition

* Actual: Added different edition of the book "OL2950942W"
* Expected: That edition "OL27030061M" would be added 

---

### Details

- **Logged in (Y/N)?** -> Y
- **Browser type/version?** -> Google Chrome	120.0.6099.217 (Official Build) (64-bit) (cohort: Stable)
- **Operating system?** -> Windows 10 Version 22H2 (Build 19045.3930)
- **Environment (prod/dev/local)?** prod

---

### Proposal & Constraints

--

### Related files

--

### Stakeholders

--

**Comment by mekarpeles** [comment]
I think this is a duplicate and should be closed. When you add an edition to the Reading Log, the edition is stored correctly. The problem is that going to the My Books page will show you the Work only (does not consider the edition) and so it may seem like the wrong edition is being presented. See:
* #2733
