### ISSUE TITLE
Duplicate account messages in code and templates

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#872]
There are duplicate account messages in

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py

and

https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates/account

Discovered while review i18n messages, both locations are included and there are near duplicates that double the number of strings to translate.

e.g.

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L348

`message = _("We've sent the verification email to %(email)s. You'll need to read that and click on the verification link to verify your email.", email=account.email)`
vs.
https://github.com/internetarchive/openlibrary/blob/413ee7e27039a705439f43648a89cbaa9db5083c/openlibrary/templates/account/verify.html

Which is the current method? Can remove the old one and make it clear which messaging should be used.

@mekarpeles you were making changes here recently, any guidance?

**Related:** but may be separate, there are many login error messages in that same .py file that are not i18nised,
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L43
I'm not sure if those are used, if not: remove, if so: i18n.

**Comment by tfmorris** [comment]
@mekarpeles @hornc Did you guys figure out what to do for this 2 year old issue? I'd like to close out the initial round of internationalization issues.

**Comment by hornc** [comment]
I'm not seeing a near duplicate msg about email in the strings file now. Closing as resolved.
