### ISSUE TITLE
Work title collation on author page should be diacritic insensitive

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8722]
When sort by work title is selected on an author page, the sorting is not done in a diacritic insensitive fashion, as it should be. I also suspect that Unicode normalization is not being done, but that would be much less of an issue if diacritics are ignored.

### Evidence / Screenshot 
![Screenshot 2024-01-15 at 1 29 06 PM](https://github.com/internetarchive/openlibrary/assets/82178/9ede2ed6-58ac-40e1-a2b4-ac4ed5fbcb44)

### Relevant url?
https://openlibrary.org/authors/OL291650A/Max_Ernst?q=&sort=title

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: Déchets collates after Dent
* Expected: Dechets and Déchets collate together

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by cdrini** [comment]
@mheiman would you be able to take a look at this one?

**Comment by mheiman** [comment]
I'll work on it. It fits in with some other things I'm looking at.

**Comment by cdrini** [comment]
Fantastic, thank you @mheiman !
