### ISSUE TITLE
Changing sort order of works on author page should reset page to 1

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#8723]
Currently if you're on an author page which has more than page's worth of works and choose a different sort order, the page number is left unchanged. It should return to page 1 when the sort order is changed.

For example, if you are at: https://openlibrary.org/authors/OL1498712A/F._Hal%C3%A9vy?sort=title&page=2
and click Trié par: [Le plus d'éditions](https://openlibrary.org/authors/OL1498712A/F._Hal%C3%A9vy?page=2)
you should end up at https://openlibrary.org/authors/OL1498712A/F._Hal%C3%A9vy
not https://openlibrary.org/authors/OL1498712A/F._Hal%C3%A9vy?page=2

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by rishabhkr-r111** [comment]
@cdrini can i work on this issue.

**Comment by cdrini** [comment]
Go for it @rishabhkr-r111 ! You'll want to modify openlibrary/templates/search/sort_options.html wherever it calls `changequery` to also set `page=None`.
