### ISSUE TITLE
Reading log throws error after first page

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8727]
When accessing any page other than 1 on the reding log, the following error appears. /openlibrary/openlibrary/templates/account/reading_log.html: error in processing template: TypeError: unsupported operand type(s) for -: 'str' and 'int' (falling back to default template)

### Evidence / Screenshot (if possible)
<img width="1159" alt="Screenshot 2024-01-17 at 20 06 15" src="https://github.com/internetarchive/openlibrary/assets/17739465/79a6192f-9790-488c-8c85-4d0debc40592">

### Relevant url?

https://openlibrary.org/people/agent-lisa/books/already-read?page=2
### Steps to Reproduce

1. Go to ...your reading log
2. Do ...go to page 2

* Actual: Error as noted above.
* Expected: Reading log should display.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by scottbarnes** [comment]
This may be fixed here but not yet deployed: https://github.com/internetarchive/openlibrary/pull/8698

**Comment by cdrini** [comment]
Patch deployed that PR since this is a rather bad bug! Thank you for the fix, @jimchamp !
