### ISSUE TITLE
Addition of Hindi as Change Website Language.

### ISSUE THREAD

**Issue by xonx4l** [internetarchive/openlibrary#8734]
Addition of Hindi as Change Website Language. As there's a very vast no of people who know only Hindi so this integration  can help them move through the website easily without any language barrier.

THANKS.

[
<img width="1440" alt="Screenshot 2024-01-20 at 12 00 34 AM" src="https://github.com/internetarchive/openlibrary/assets/119700621/9d0deb99-a5b7-4f52-96e3-17b761b9c5d3">
](url)

**Comment by rishabhkr-r111** [comment]
@xonx4l As a Hindi speaker myself i am definitely interested in this and can help out in translations.

**Comment by xonx4l** [comment]
@rishabhkr-r111  yeah sure . Thanks.

**Comment by scottbarnes** [comment]
@rishabhkr-r111, thanks for offering to help! Please check out the i18n guide here: https://github.com/internetarchive/openlibrary/wiki/Internationalization-Contributor's-Guide-(i18n). I'm assigning this to you @rishabhkr-r111 since you commented on it first.

**Comment by shivam200446** [comment]
@rishabhkr-r111 Hey, Are you working on it?

**Comment by rishabhkr-r111** [comment]
Hi @shivam200446 i am currently working on it.
