### ISSUE TITLE
Indicate start date for Trending Books data collection

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#8737]
It would help those interested in OL stats to indicate when the data for the "Trending Books" section began to be collected, especially the "All Time" section.

### Proposal & Constraints
Maybe simply putting a start date at the bottom of the page or something would be enough, but something more involved might be useful too, for example in facilitating [period]-by-[period] data analysis.

### Additional context
https://openlibrary.org/trending/forever

**Comment by shivam200446** [comment]
@jimchamp Hey, I would like to Work on it.

**Comment by jimchamp** [comment]
Sorry for the very late response, @shivam200446.  Are you still interested in working on this?

Trending results are derived from patrons' reading log shelves.  The earliest entry in the `bookshelves_books` table is from October 2017.  This information can be included in the view when "All Time" is selected.

**Comment by etgibbs** [comment]
@jimchamp I am a new contributor and would be interested in taking this as a first issue ... are you still interested in assigning someone to this? thanks

**Comment by jimchamp** [comment]
@etgibbs, you've been assigned.  [This file](https://github.com/internetarchive/openlibrary/blob/4043d671afe60105063fdcd12f59ffe36b087cbc/openlibrary/templates/trending.html) is the template for the trending page.
