### ISSUE TITLE
Update Portuguese "Tomar emprestado" -> "Empréstimo", and other suggestions

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8743]
From a patron:

Please allow me to suggest that the correct translation of "Borrow" to Portuguese is "Tomar emprestado", because "Emprestar" is "Lend" ;) If you wish to save space in the button, maybe "Empréstimo" (a noun, like "borrowing" or "loan").

Two more translation suggestions:
Instead of "Centro de ajuda" and "Centro de desenvolvedor", I would suggest "Central de ajuda" and "Central de desenvolvedor", which sounds more idiomatic.

**Comment by cdrini** [comment]
@ninalencastro Could you take a look at this one and choose the wording that makes the most sense?

**Comment by ninalencastro** [comment]
@cdrini  "Tomar emprestado" works, but I find it to be a bit clunky for this purpose. "Empréstimo" is a solution I prefer. The other two correction also check out as a better option: 

> Instead of "Centro de ajuda" and "Centro de desenvolvedor", I would suggest "Central de ajuda" and "Central de desenvolvedor"

 Thank you for the corrections @seabelis !

**Comment by cdrini** [comment]
Sweet, ok then "Empréstimo" is the decision, if someone is willing to update the translation file: https://github.com/internetarchive/openlibrary/blob/136fc1ff4c86bbb3f81aee49224aa44c01297950/openlibrary/i18n/pt/messages.po

**Comment by cdrini** [comment]
Fantastic! Go for it @rebecca-shoptaw

**Comment by rebecca-shoptaw** [comment]
Quick note: I realized in doing this that the capitalization in the original version was inconsistent between the two centers ("Centro de ajuda" vs. "Centro de Desenvolvedor") -- I standardized to lowercase based on the comments here, but can switch both to uppercase if that's preferred!
