### ISSUE TITLE
"Books" page in Search not rendering

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#8748]
The search page listed in the search menu as "Books" is not rendering, shows the error message below:

### Evidence / Screenshot (if possible)
<img width="923" alt="Screenshot 2024-01-23 at 1 05 39 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/07462930-c159-4261-9a6f-baf0e7a19166">

### Relevant url?

[https://openlibrary.org/search](https://openlibrary.org/search)

### Steps to Reproduce

1. Click on "Advanced" in the main search bar
2. Click on "Books" in the menu

Or navigate directly to [https://openlibrary.org/search](https://openlibrary.org/search)

* Actual: Error message, no page rendered.
* Expected: Search page like the others in the menu:
<img width="500" alt="Screenshot 2024-01-23 at 1 09 30 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/52a20d79-86d7-4eb3-8243-f3b39a1b45bf">

### Details

- **Logged in (Y/N)?** Y & N (happens in both cases)
- **Browser type/version?** Chrome/latest
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod (but happens in dev as well)

### Proposal & Constraints

On further investigation, I've discovered that the page does render if there is something entered into the top search bar, so it seems what is needed is to either a. make or b. find/relink a default book search page that matches the others in the menu (see image above) and renders without a search term.

This would be especially helpful to users who put in /search after the URL to try to start a search (or navigate over the way I did).

### Related files

[work_search.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/work_search.html)
[search templates](https://github.com/internetarchive/openlibrary/tree/master/openlibrary/templates/search)

**Comment by rishabhkr-r111** [comment]
Hi, @rebecca-shoptaw this issues is already open checkout #8730.

**Comment by rebecca-shoptaw** [comment]
@rishabhkr-r111 It sure is! I'm happy to close this issue and can try to transfer some of the details (proposal, related files) to the other one if helpful -- would be good to know re: the policy on merging duplicate issues.

**Comment by rebecca-shoptaw** [comment]
Duplicated #8730 !
