### ISSUE TITLE
Disable cover upload `submit` button after click 

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8749]
### Describe the problem that you'd like solved

It looks as if patrons are sometimes clicking `Submit` multiple times to upload covers, and that is causing duplicate uploads. Let's try to prevent that.

### Proposal & Constraints

When the `Submit` button is clicked to upload a cover, it should become unclickable and say `Uploading...`.

Additionally, if there are any upload errors, timeouts, etc., the button should be re-enabled so the patron can try again.

The `Submit` button in question can be found by going to an edition page, e.g. http://localhost:8080/books/OL9737752M/The_Odyssey, mousing over the cover image on the upper left, and clicking `Add Cover Image`. The `Submit` button will then be found in the lower left:
![image](https://github.com/internetarchive/openlibrary/assets/26524678/0d99d42b-8361-4aa9-a96b-11c5bc28f140)

### Additional context

I did a quick skim and here are some files worth that _may_ be looking at:
`openlibrary/templates/covers/add.html`
`openlibrary/plugins/openlibrary/js/covers.js`

### Stakeholders

@cdrini 
@rebecca-shoptaw

**Comment by rebecca-shoptaw** [comment]
I'd love to work on this!

**Comment by cdrini** [comment]
Awesome, thank you @rebecca-shoptaw ! Let us know if you have any questions :)
