### ISSUE TITLE
Replace covers url validation/placeholder with html attributes

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8755]
The covers form uses outdated methods for url verification and place holder text. Switch to using `type="url"` for the `<input>` tag, and use `placeholder="https://..."` with an empty value instead of the JS methods.

https://github.com/internetarchive/openlibrary/blob/912274d257600af7b0fb43006ae29d4d545e25b4/openlibrary/templates/covers/add.html#L66

https://github.com/internetarchive/openlibrary/blob/73dcb6851f04fa5262ce987057e5b21a184f3068/openlibrary/plugins/openlibrary/js/covers.js#L63-L76

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

## Stakeholders
@rebecca-shoptaw

**Comment by rebecca-shoptaw** [comment]
I'm on it!
