### ISSUE TITLE
Limit cover image file type using html attributes

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#8762]
Cover form allows you to select any file type to try to upload for the cover image, though only certain types are allowed. 

### Describe the problem that you'd like solved

Noticed this while working on #8755 (using html attributes for url validation). It would be great if we could do something similar for images, so that the form only allows users to try uploading one of the valid image types (png, jpg, gif), rather than allowing them to try anything and then validating on submit.

What happens now when you try to select a non-image to upload:
<img width="300" alt="Screenshot 2024-01-25 at 2 56 48 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/fe47a38c-feed-4ad9-9f6e-d21a33c5e655">

What could happen instead:
<img width="300" alt="Screenshot 2024-01-25 at 2 57 08 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/af7c1b08-33fb-45e5-8e98-9a39bfac62e2">

### Proposal & Constraints

This would be very easy to do using the HTML `accept` attribute (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept) to specify the preferred filetypes in the `add.html` file.

It could also involve removing redundant image file validation if necessary.

**Comment by rebecca-shoptaw** [comment]
Would love to take this on! Should be fairly simple.

**Comment by cdrini** [comment]
Awesome, sg! Thanks @rebecca-shoptaw !
