### ISSUE TITLE
suggested edit to documentation

### ISSUE THREAD

**Issue by bradyguyc** [internetarchive/openlibrary#8769]
### Question
how to use the My Books API documentation

### Additional context
[](https://openlibrary.org/dev/docs/api/mybooks)

### Issue resolution criteria
It would be beneficial to add some contest the links on this page.  Indicating that mekbot with user id.

**Comment by xonx4l** [comment]
can you elaborate this issue a bit @bradyguyc . Thanks

**Comment by bradyguyc** [comment]
something like this:

For API's that reference a specific users data such as those API's that start with people. Substitute {Profile Display Name} with the authenticated user or public data's profile display name.

[https://openlibrary.org/people/{Profile](https://openlibrary.org/people/%7BProfile) Display Name}/books/want-to-read.json [https://openlibrary.org/people/{Profile](https://openlibrary.org/people/%7BProfile) Display Name}/books/currently-reading.json [https://openlibrary.org/people/{Profile](https://openlibrary.org/people/%7BProfile) Display Name}/books/already-read.json

Also I started a wiki page for a C# example:  It will be several more weeks at least before I am finished with that.
https://github.com/internetarchive/openlibrary/wiki/Using-the-API's-with-C%23

**Comment by mekarpeles** [comment]
The documentation is here -- feel free to add more to it
https://openlibrary.org/dev/docs/api/mybooks
