### ISSUE TITLE
Fix My Notes

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8771]
Going to page 2 of notes breaks because the page is a string instead of an int.

### Evidence / Screenshot (if possible)

![openlibrary org_people_mekBot_books_notes_page=2 debug=true](https://github.com/internetarchive/openlibrary/assets/978325/71f02dc3-434f-45d7-8815-4e35f7c03a87)

### Relevant url?
https://openlibrary.org/people/mekBot/books/notes?page=2&debug=true

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by QuantuM410** [comment]
Hey @mekarpeles! I would like to work on this issue. Do I need to create a draft proposal first?

**Comment by Ayush1404** [comment]
Hey, i saw it was like a one liner fix so i just did it . See if ther is need of changes in it.

**Comment by jimchamp** [comment]
Possibly related: #8698 
Should probably check page two of every paginated My Books page in order to confirm that this isn't happening elsewhere.

**Comment by Ayush1404** [comment]
Okay I did check that and there was same error in my reviews, I did fix that too.
