### ISSUE TITLE
auto_unassigner.yml triggers workflows on github forks

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#8787]
### Evidence / Screenshot (if possible)

I received a bunch of failed job notifications on my personal github fork of this repo because the workflow had triggered.

I'm guessing this auto_unassigner.yml should only run on the internetarchive/openlibrary -- is there a way to set that?

https://github.com/hornc/openlibrary-1/actions/runs/7753132102/job/21143876385

I think it's failing because my fork is named `openlibrary-1` and the repo name is hard coded in the script. I don't think we want it running at all on contributor forks.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

**Comment by hornc** [comment]
I've also had notifications from a `cron_watcher` workflow which looks like it should also not be enabled on forks.

**Comment by jimchamp** [comment]
Have updated #8780 to prevent the workflow from running when triggered from a forked repo.
I found that all workflows run on my repo, so I disabled them from my repo's actions page.
