### ISSUE TITLE
Add "Copy URL" Option to Share Modal

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8802]
Especially on mobile, there is no way to copy the url of the page you're on in order to share it. Our current share modal has an "embed" option, which is similar, but we want to add an option for copy url:

<img width="225" alt="Screenshot 2024-02-07 at 10 23 36 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/651c3ae9-80c8-4787-9f30-dee4841e09c1">

<img width="428" alt="Screenshot 2024-02-07 at 10 23 22 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/df943b0c-7ea2-4b73-8adb-8527d1c35749">

We can use this icon:

https://www.flaticon.com/free-icon/link_341077

![image](https://github.com/internetarchive/openlibrary/assets/978325/a21b4859-e6cd-409a-8bd4-3fc8110160a8)

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by rishabhkr-r111** [comment]
i will like work on this issue.

**Comment by mekarpeles** [comment]
@Ayush1404 thank you for the contribution! We'll take a look :)
