### ISSUE TITLE
Request: Infogami Internationalization optimizations

### ISSUE THREAD

**Issue by justcomplaining** [internetarchive/openlibrary#8808]
Infogami pages internationalization basically works so this might not be high priority, but it's worse than the translation method for the rest of the platform because without checking all pages manually, as a translator:

- I cannot quickly see where translations are missing

- I cannot easily see whether the original language version (en) has been changed after last translation

Not sure how to best address this. As a translator, I could imagine both some script regularly exporting/importing all wiki page texts into the POT file somehow (no idea whether this is technically possible or sensible), or just some UI tools making it easy to monitor above issues:

- a page containing (automatically fetched) info on which language versions exist/are missing of all relevant pages

- an automatic note if the English version of a page has been last edited later than the translated version on each page; maybe a summary page showing which pages this applies to

**Comment by mekarpeles** [comment]
Closed in favor of #3328
