### ISSUE TITLE
Make edition description rich text as work description is 

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8825]
The work description is rich text and has a rich text editor. When an edition has a description it is displayed instead of the work description but it is not in rich text. I guess there is no reason for it not to be so I propose to have the same editor there as for the work description.

**Comment by noobCoderVP** [comment]
Can you elaborate more @bitnapper?

**Comment by bitnapper** [comment]
@noobCoderVP Yes, I can try. The field _edition-description_ is not a rich-text field. But it has the same function for editions as the _about-about_ is for works. So in my opinion it should have the same features. i.e. rich-text.

**Comment by noobCoderVP** [comment]
Thanks for that, I am working on this issue. Will fix it ASAP.

**Comment by noobCoderVP** [comment]
I have understood the issue

![image](https://github.com/internetarchive/openlibrary/assets/98279986/5cb14393-59b2-46ff-9474-988169cc691e)

I need to add buttons above similar to the field **Any notes about this specific edition?** in the field **Description of this edition**, am I right @bitnapper ?

**Comment by noobCoderVP** [comment]
![image](https://github.com/internetarchive/openlibrary/assets/98279986/be97a9d9-8c76-410d-adf0-8203be8a79d3)

I have fixed the issue, should I create a pull request for the same? Asking because it is my first contribution to internet archive, thanks..
