### ISSUE TITLE
Search Page: Redesign "Sort" options UI

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8829]
The objective of this issue is to take the long list of sort options in the screenshot (a) below and organize them in a `details` dropdown styled according to the designs in (b):  

(a) See the highlighted area:

<img width="700" alt="Screenshot 2024-02-20 at 12 16 38 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/f3fb471c-6f6e-450a-a32f-eded209361de">

(b) Proposed designs:
<img src="https://private-user-images.githubusercontent.com/978325/309010034-0fa521ff-64a0-46a4-9edd-ae481a27128a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NDQwNDYsIm5iZiI6MTcxMjk0Mzc0NiwicGF0aCI6Ii85NzgzMjUvMzA5MDEwMDM0LTBmYTUyMWZmLTY0YTAtNDZhNC05ZWRkLWFlNDgxYTI3MTI4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQxNzQyMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWZmNTkzNTA2NzNlODA1MDg2YTY4NTBhYTBjYTkyNTgxNzcyZjk5YTI5ZmE5ZjM2MjIzNzgyNzAzMGEwYjY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7sashaBsZGeGl8yiSFe9PLwUfCIvUPs1euUUizCr-YY" width="300" style="max-width: 100%;">

**Comment by Hitro147** [comment]
Hey there! I'm excited about contributing to open source and am pretty new here, I would love to help out with the search page changes. Could you kindly provide a little more detail on what changes you need? Thanks!

**Comment by mheiman** [comment]
@Hitro147 this needs some design proposals before any coding can be done. If you would like to review the current sorting interface and mock up a suggestion for how to make them clearer, more compact, and easily extendable in the future, please do!

**Comment by Hitro147** [comment]
When considering design improvements for the sort options UI on the "Search Books" page. Here are a few suggestions I came up for design improvements:

1. Dropdown Menu for Sort Options:
- Consolidate the sort options into a dropdown menu to save space and reduce visual clutter. A dropdown can also make it easier to add more sorting methods in the future without impacting the overall design.

2. Icons for Sort Types:
- Use intuitive icons next to each sort option to visually distinguish them. For example, a clock for "Most Recent" or a star for "Top Rated." This can make the interface more user-friendly, especially for quick visual scanning.
- Also, we could use this to have the most commonly used sorting options and the less commonly used ones can be in a separate dropdown.

Let me know if these design options align with Openlibrary's design aesthetic and which of these you prefer and I'll start on the mockup :)

**Comment by kylie-kiaying** [comment]
Hi @mheiman I came up with some possible design mockups for this sort option. Would appreciate any feedback on the design!

[Figma Mockups](https://www.figma.com/file/TvoCh1mKTelUNtvn2cENnH/OpenLibrary-%238829-Designs?type=design&node-id=2001-830&mode=design)

**Comment by mheiman** [comment]
Thanks, @kylie-kiaying ! Those are nice redesigns of the current interface elements, but we need to do a deeper restructuring.  

Some of the issues to consider:

- Most Recent and First Published are different direction sorts of the same data (which the naming obscures), but we don't provide a way to reverse the other sorts.
- We currently have a Work Title sort in beta, and we will probably want to add other sorts in the future, so any interface needs to grow elegantly.
- The Reading Log sort currently pops up a secondary menu (as you would have discovered if you tested the existing interface) which is more than a little weird. Any new solution needs to handle that better.

**Comment by mekarpeles** [comment]
@kylie-kiaying did you want to take the lead on implementing these designs? Or would you like us to find someone to do the engineering/implementation portion?

**Comment by aarasawa** [comment]
I would like to try implementing the design that @kylie-kiaying provided. If they would also like to work on it together that is cool too.

**Comment by aarasawa** [comment]
Hi @mekarpeles thank you for assigning this to me, I am excited to contribute what I can. 

Also, I seem to still be missing the slack invite in my inbox, do you think you could send another email?

**Comment by mekarpeles** [comment]
@aarasawa, resent to your gmail! :)
