### ISSUE TITLE
rm deprecated sections from README

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#883]
Remove sections from code.openlibrary.org and README and shift it to the Wiki.

**Comment by mekarpeles** [comment]
@salman-bhai made great progress on updating our github.com/internetarchive/openlibrary/wiki

I'll try to bring more content out of our README and into the wiki

**Comment by salman-bhai** [comment]
There are primarily 5 pages that we can move from code.openlibrary.org to the Wiki.
1. Setting up a Dev instance -> Already contains instructions in the org README
2. Getting Started with Development -> Will rename this to Front End Guide and convert the pre-existing `Frontend-Guide.rest` file to a `Frontend-Guide.md` file
3. Architecture of the dev instance. -> Will create a new page for this in the Wiki. We need to add more content here though.
4. Design Notes -> contains 3 subsections and three will be a single Wiki page for now. Later we can see if we need to separate the three- 
    * Dev Instance -> Will add as it is.
    * Lists -> Nothing much here. Is there any alternative resource which explain this?
    * Feature Flags - Will add this as it is
5. API Documentation -> This already exists or is already done. Will make no changes to this.
6. Appendices -> Will combine all the current files namely `Configuration Files`, `setup.py commands`, `Database Migrations` and `Dependencies` into one file. Later we can look at separating each one of them whereever necessary
