### ISSUE TITLE
bot privileges for BitBot

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8840]
Can you please give bot privileges to BitBot and the account to the "API" usergroup.

**Comment by mekarpeles** [comment]
I don't see such an account!

**Comment by bitnapper** [comment]
Yeah... thats strange. I have never noticed, that it has a number.

So its: <tt>bitbot8095</tt>

<img width="1025" alt="Screenshot 2024-03-07 at 17 12 37" src="https://github.com/internetarchive/openlibrary/assets/2772669/420f560c-ead8-46f3-a617-77e6fa703320">

**Comment by mekarpeles** [comment]
Done!
