### ISSUE TITLE
Fix untranslated error messages in `add.html` and `web.html`.

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#8848]
### Problem

While working on another issue, I noticed that a few strings in the cover and link adding forms are not getting translated because they are written in the JavaScript rather than the HTML files, so get ignored for internationalization: i.e. `$('#link-errors').html('Please provide a label.');` in `edit.js`

#### Evidence / Screenshot
<img width="843" alt="Screenshot 2024-02-27 at 2 59 08 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/a9de6d5e-8aa4-4a6b-be1f-fc1764a9305c">
<img width="592" alt="Screenshot 2024-02-27 at 2 54 39 PM" src="https://github.com/internetarchive/openlibrary/assets/140550988/887deb3e-42b1-4ad7-9137-9c022d96a3a0">

### Reproducing the bug

1. Change site language to any non-English language 
2. Go to a work page
3. Try to enter a link with no label (below the excerpts)

* Expected behavior: "Please provide a label" appears in the language you've selected for the site.
* Actual behavior: "Please provide a label" appears in English.

Note: You can follow the same process with trying to submit a new cover image without entering a link or an image file.

### Context

- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### Proposal & constraints

Very simple! The clearest way to fix the problem would be to replicate the approach @cdrini suggested for #8754 - transfer the relevant error messages into the HTML as a data attribute, and then access the data attribute in the JavaScript as needed.

This can also be bundled with a quick fix to make the "URL" and "Add Link" text correctly formatted for internationalization directly in the HTML.

### Related files

`openlibrary/plugins/openlibrary/js/edit.js`
`openlibrary/templates/books/edit/web.html`

`openlibrary/plugins/openlibrary/js/covers.js`
`openlibrary/templates/books/add.html`

**Comment by jimchamp** [comment]
Go for it!  Add the translated strings as an object in a `data-i18n` attribute (there are many examples of this in the codebase).  Let me know if you have any questions.
