### ISSUE TITLE
Reading log JSON view errors when too many work IDs passed to solr

### ISSUE THREAD

**Issue by mheiman** [internetarchive/openlibrary#8852]
### Problem

Since the last run of the new redirect resolution script, the JSON view of my already-read shelf is generating an error. The script fixed a number of redirects, and I haven't made any manual changes to the shelf since, suggesting that the script might have written some bad data.

My other shelves are sending JSON correctly, so it's not a general API issue.

#### Relevant URL
https://openlibrary.org/people/mheiman9541/books/already-read.json?debug=true

### Context

- Browser (Chrome, Safari, Firefox, etc): Firefox
- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### Stakeholders
@mekarpeles @mheiman @cdrini

**Comment by mheiman** [comment]
Update from @cdrini : Solr returned an http 414 URI too long. The script fixed so many issues that we're now sending too many work IDs to solr.

**Comment by benbdeitch** [comment]
Hello, I'd be thrilled to work on this issue, if you'd assign me. It looks like Solr has built in support for POST requests. 

The way it currently looks, the bodies of the requests will have to be formatted in the manner of 
```
{
   "params": {
         "q": "field:value",
         "rows": 10,
         "wt": "json"
     }
}
``` 
As such, I think this should be fairly doable.
