### ISSUE TITLE
Add Sardinian to list of languages

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8857]
@asereze translated the site to Sardinian, so we can now include Sardinian in our language options. This will let users select the language.

### Proposal & Constraints
See https://github.com/internetarchive/openlibrary/blob/8f8607e5c4fa4c3b5cf03cc2f5b591d89ea70d31/openlibrary/templates/languages/language_list.html

### Stakeholders
@asereze

**Comment by DarrellRoberts** [comment]
Hi there! I'd like to work on this issue if you'd like to assign me? If so, my only question is do the languages follow a particular order or would you just add the sc option at the end of the list?

**Comment by cdrini** [comment]
Awesome ty @DarrellRoberts ! I believe they're sorted by something; probably the language code 👍
