### ISSUE TITLE
Add drop shadow to cover modal

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8868]
### Describe the problem that you'd like solved

It would be nice if the cover shown in the cover modal had a dropshadow (border) like it does most places. You can see the difference it makes in this example where the modal book cover has no clear end but the cover seen in the background has a nice shadow.

![image](https://github.com/internetarchive/openlibrary/assets/921217/dfe6152a-bf4f-4fdb-b6ed-9c58a42f3fe8)

**Comment by QuantuM410** [comment]
Hey! I would like to work on this issue. Can I get assigned?

**Comment by RayBB** [comment]
@QuantuM410 you're assigned. Take it away :)

**Comment by QuantuM410** [comment]
@RayBB I have added the required changes in the PR. Please have a look into it :)
