### ISSUE TITLE
Add cancel button to top books edit page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8883]
### Describe the problem that you'd like solved

When I add a new book I am redirected to the book editing page. That makes sense.
However, I usually don't edit the book right away (if at all) because I want to add it to a list or write a review.

So I have to either:
1. Edit the url to remove the "edit" part and get to the book page
2. Scroll way down to click save or cancel (honestly I just now realized there even is a cancel button)
3. Click the author name then click the book

Here is what it looks like now
<img width="1109" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/9b61a973-d8ec-4180-854c-ed781c7b9f22">

Here is what the author edit page looks like with a nice cancel button at the top
<img width="1076" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/4780c953-27c0-4fb0-b839-5dfd2ee00d9f">

### Proposal & Constraints

Add a cancel button at the top to match the author edit page.

This has already been 👍 by Drini [here](https://internetarchive.slack.com/archives/C0ETZV72L/p1709831469614799?thread_ts=1709829675.659089&cid=C0ETZV72L) so is ready to be worked on.

### Additional context

A larger project that could be done if someone is interested is make a sticky footer that could look something like this. 
That should be a separate ticket though :) 

<details>
  <summary>Spoiler</summary>
  
  
![image](https://github.com/internetarchive/openlibrary/assets/921217/9e51480b-d5e5-4817-9def-8828204b8a09)

  
</details>

**Comment by seabelis** [comment]
Linked text is more difficult to copy paste, particularly when one only wants part of the title. I don't object the cancel button.

**Comment by RayBB** [comment]
@seabelis that's good feedback thanks! I've updated the issue just one option based on your and Drini's feedback.
(Previously it said we could make the title a linked text it).

A small tip: You can highlight the text of the link without it opening by holding ALT (OPTION on mac) when you select it. 👍 Mentioned [here](https://superuser.com/questions/1702591/how-to-easily-select-a-link-text-in-a-browser-without-activating-the-link).

**Comment by Realmbird** [comment]
@RayBB Can I help work on it, I just finished my first commit so I want to try something more difficult

**Comment by RayBB** [comment]
@Realmbird yes go for it!

**Comment by Realmbird** [comment]
Ok

**Comment by Realmbird** [comment]
@RayBB
1. I am trying to understand the problem you want to make a cancel button because after adding a book you usually don't want to to edit it.
2. For the thank you for adding book when adding cancel should I move that to be under the cancel and delete record button?

**Comment by Realmbird** [comment]
Also can I add cancel button to this page as well?
![Screenshot from 2024-03-19 23-07-36](https://github.com/internetarchive/openlibrary/assets/56459277/a24ddbaf-90e4-4b0b-84f2-1a3685794fa2)
![Screenshot from 2024-03-19 23-07-51](https://github.com/internetarchive/openlibrary/assets/56459277/2ae83c2d-3216-4cdd-a12a-02bd120a1968)

**Comment by RayBB** [comment]
@Realmbird 
1 - that is correct
2 - For the scope of this PR, I'd say that's a good solution.
3 - yes also put the cancel button on the page of the screenshot (I think it actually is the same page in the codebase)

Thanks!

**Comment by Realmbird** [comment]
Thank you I think I understand what I need to do will be working on solving the problem

**Comment by Realmbird** [comment]
@RayBB  I am currently working on adding a cancel button to the edit page. I am trying to see where the cancel button is implemented on the edit authors page. I looked at the edit html template for authors and found no cancel button. I see some syntax I do not recognize with the $ and macro. I would like to know what this is so I can further investigate a solution. An interesting thing I found was on the macros files there is on with a cancel file but, I would like at ask how the $ and code in html and what exactly macros

**Comment by Realmbird** [comment]
@RayBB 
![Screenshot from 2024-03-22 00-07-54](https://github.com/internetarchive/openlibrary/assets/56459277/342d787d-444f-415f-bab3-c5d568e7a323)
Got Cancel button on edit book

**Comment by Realmbird** [comment]
![Screenshot from 2024-03-22 00-14-44](https://github.com/internetarchive/openlibrary/assets/56459277/7d2a1cad-aafc-4960-ab68-4e0d8ad41c85)
Got order to change properly gonna try to get css to polish this site

**Comment by Realmbird** [comment]
@RayBB Not sure how to modify css but, through changing I got the page to look a lot better with cancel button
![Screenshot from 2024-03-22 00-26-39](https://github.com/internetarchive/openlibrary/assets/56459277/6bad6b27-26b5-4c13-a733-32f12696b335)

**Comment by Realmbird** [comment]
@RayBB I added cancel button and added styling is there anything else I need to do?

**Comment by RayBB** [comment]
Can you change it so it looks just like the author edit page with the order of the buttons? It would be helpful if you can post a screenshot of the two side by side. You shouldn't need to change css (I think) but if you do want to it would be here. https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#working-with-css

Anyway, I think you're about ready to open a PR! Good job :)

**Comment by Realmbird** [comment]
@RayBB Made Pull Request
