### ISSUE TITLE
Returns 502 when creating a snapshot

### ISSUE THREAD

**Issue by scoful** [internetarchive/openlibrary#8887]
### Problem

I apologize for bringing this up here.

https://archive.readme.io/reference/creating-a-snapshot

When I create a snapshot based on this URL action，Returns 502 when creating a snapshot

I don't know if this issue is under your purview or not, but I mentioned issue in this place and got no reply
https://github.com/ArchiveLabs/api.archivelab.org/issues/24

Sorry again for troubling you

#### Evidence / Screenshot
![image](https://github.com/internetarchive/openlibrary/assets/12808733/91ff44c9-7b80-4d74-9342-fc16325213c5)

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by mekarpeles** [comment]
Thanks. will followup in the other issue, this is the wrong place for it.
