### ISSUE TITLE
Unify the design of "no result" pages for different search types

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8891]
### Problem

A nice little project would be to make the "no results" / "no hits" pages across books, authors, etc uniform or at least a bit more consistent.

The page could contain some of these elements:
- Message there are no results
- a link to the docs about searching
- call to action (add a book, create a list)
- Possibly some suggested / related queries / autocorrect type stuff

Whoever works on this will have to coordinate with the community / design team to figure out what it would look like. Proposals are always welcome!

#### Evidence / Screenshot

![ezgif com-animated-gif-maker](https://github.com/internetarchive/openlibrary/assets/921217/c6cf30c7-8efd-4f05-b69f-384e1c3c4de4)

<details>
  <summary>Individual screnshots</summary>
  
   <img width="1076" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/e02e7cf4-4874-4b09-9a46-ddc128f1129a">
<img width="1071" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/0c9f3771-a9bf-4557-a3d1-7db26acbbc0d">
<img width="1076" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/10925a2f-46a9-4355-9e65-48df65245b86">
<img width="1079" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/f5c87e18-350e-4d8c-bb3d-34e8a9ce50dc">
<img width="1078" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/11ce83c3-7cb4-4afd-b5ab-06621d304cf7">
  
</details> 

#### Relevant URL
- https://openlibrary.org/search?q=%22institutional+thickness+999%22
- https://openlibrary.org/search/authors?q=%22institutional+thickness+999%22
- https://openlibrary.org/search/inside?q=%22institutional+thickness+999%22
- https://openlibrary.org/search/subjects?q=%22institutional+thickness+999%22
- https://openlibrary.org/search/lists?q=%22institutional+thickness+999%22

**Comment by mekarpeles** [comment]
See also, duplicate: #1001

**Comment by vanshitaverma** [comment]
Hello, I think the error message for 'Books' seems to be the most visually pleasing and informative so using that design as a template and making the rest uniform (match the design of 'Books') would be a good way to go. 

As such, I would like to work on this issue, can you assign it to me?

**Comment by RayBB** [comment]
@vanshitaverma since this is a somewhat bigger issue that will require input on the design I recommend you join the [weekly community call](https://github.com/internetarchive/openlibrary/wiki/Community-Call) if you can. It happens Tuesdays at 9AM Pacific time. Here you can share that you'd like to work on this and follow the design from the books page and a get a little guidance before you start working on it.
See you there!

**Comment by cdrini** [comment]
Here are the actions for each page:

* Books:
   * Search Inside
   * Create a new book
* Authors:
    * Search Inside
    * ~Create a new author~ We don't have an endpoint this! So can't  link to anything 
* Search Inside
    * No options
* Subject
    * Search Inside
* Lists
    * Search Inside

**Comment by andrewscheiner53** [comment]
Hi, I am an undergraduate working with a team looking to make contributions to Open Library. I came across this issue and was wondering what its status was. Is this ticket still open and do the "no result" pages still need standardizing? Thank you!

**Comment by RayBB** [comment]
@andrewscheiner53 yes they do. You can work on it. Please read the whole issue and comments closely before proposing your solution. If you can join the weekly call (seen in the github wiki) that's also a great place to share your designs and get feedback.

**Comment by RayBB** [comment]
@andrewscheiner53 you're completely right.
It looks like someone fixed this but forgot to close this PR.

However, I've created 3 new issues related to the search page.
You might be interested in picking up one of these. If so, please comment on the ticket directly.

* #10049
* #10050
* #10051

Closing this in favor of the above tickets.
