### ISSUE TITLE
Restrict read of patron preferences to logged in patron

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8893]
### Problem

There isn't a significant security implication given how we use settings today, but in the interest of patron privacy, we should make account preferences only accessible by the logged in patron.

#### Relevant URL
e.g. https://openlibrary.org/people/mekBot/preferences

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by jimchamp** [comment]
I'm thinking that this should also include the `.json` and `.yml` preference requests.
