### ISSUE TITLE
Author merge stripping Work-level metadata

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#89]
uh oh - we have a problem...

looks like author merge is stripping work metadata :( 

http://openlibrary.org/works/OL1087067W/Catalogue_of_the_collection_of_English_porcelain_in_the_Department_of_British_and_mediaeval_antiquities_and_ethnography_of_the_British_Museum?b=5&a=4&_compare=Compare&m=diff

all the author merges by marycee here: http://ol-bots.us.archive.org/cgi-bin/vandalismcenter.py

http://openlibrary.org/people/marycee

**Comment by LeadSongDog** [comment]
Odd, the history shows 6 revisions https://openlibrary.org/works/OL1087067W/Catalogue_of_the_collection_of_English_porcelain_in_the_Department_of_British_and_mediaeval_antiquit?a=4&_compare=Compare&b=5&m=history

 but the history shown at the foot of https://openlibrary.org/works/OL1087067W/Catalogue_of_the_collection_of_English_porcelain_in_the_Department_of_British_and_mediaeval_antiquit 
has only five; it omits rev 2 from 15 January 2010. 

To me, this suggests an off-by-one indexing error of some kind.

**Comment by hornc** [comment]
This is still happening :(
eg: https://openlibrary.org/works/OL1065650W/Der_menschliche_Gedanke?m=diff&b=3
from merge https://openlibrary.org/recentchanges/2017/05/18/merge-authors/51995688

The admin link above still works:  http://openlibrary.org/admin/inspect/store?type=merge-authors-debug&name=bad_merge&value=true

**Comment by hornc** [comment]
Here is the code that checks for bad merges as they are saved: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/merge_authors.py#L138

**Comment by guyjeangilles** [comment]
@hornc Is this still an issue? It looks like there are scripts to spot bad merges. Are there any other changes that can be implemented?

**Comment by mekarpeles** [comment]
@seabelis , @cdrini is this still a problem? If not, feel free to close.

**Comment by seabelis** [comment]
No. I've not observed this.
