### ISSUE TITLE
Bulk internationalization of HTML title/values where needed

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#8904]
### Problem

While I'm on an internationalization kick, I've noticed that there are a number of untranslated HTML `title` and `value` attributes (the value is often used to show button text) -- it would very simple to search the codebase for these, and to fix all that can be found in one go. 

#### Evidence / Screenshot
**Sample untranslated `title`:**
https://github.com/internetarchive/openlibrary/blob/d8569549d75da79d156323740fed79128fc92683/openlibrary/templates/history.html#L53-L60
**Sample untranslated on-screen `value`:**
https://github.com/internetarchive/openlibrary/blob/d8569549d75da79d156323740fed79128fc92683/openlibrary/macros/ManageWaitlistButton.html#L38
**Other untranslated on-screen text (fix can be bundled in):**
https://github.com/internetarchive/openlibrary/blob/d8569549d75da79d156323740fed79128fc92683/openlibrary/macros/ManageWaitlistButton.html#L42

### Reproducing the bug

1. Search the codebase for title=" and value=" 
2. A number of titles and on-screen values such as button text will show up improperly formatted for i18n

* Expected behavior: All on-screen text should be formatted like so: https://github.com/internetarchive/openlibrary/blob/d8569549d75da79d156323740fed79128fc92683/openlibrary/macros/EditButtonsMacros.html#L23
* Actual behavior:  A good amount of it is formatted like the examples shown above.

#### Proposal & constraints

Proposed solution is to go through and manually update each of the titles/values for i18n. Will be a somewhat repetitive task, but it's a very easy fix!

Helpful resources: 
* [i18n Guidelines](https://github.com/internetarchive/openlibrary/wiki/Internationalization-Contributor's-Guide-(i18n)#internationalization-i18n-developers-guide)
* [.pot File Generation Guidelines](https://github.com/internetarchive/openlibrary/wiki/Internationalization-Contributor's-Guide-(i18n)#extracting-strings-from-htmlpython-files-generating-the-pot-file) -- would be helpful to run this after the changes have been made to help keep the translations up to date

**Comment by rebecca-shoptaw** [comment]
Would be happy to take this on, or offer it to anyone in search of a good first issue who's interested!

**Comment by merwhite11** [comment]
@rebecca-shoptaw Hi Rebecca, I will get to work on this ! It will be a good way to familiarize myself with the code and process.

**Comment by rebecca-shoptaw** [comment]
@merwhite11 Amazing! Go for it, and let me know if you have any questions 😊✨

**Comment by merwhite11** [comment]
@rebecca-shoptaw I have a few questions. Posting as separate comments for easier responses:

Should the i18n syntax change based on the coding language of the file? 
I [read that this is the syntax for a vue file](https://vue-i18n.intlify.dev/guide/essentials/syntax):  :title="$t('prevSection.short')"
Or does the syntax from the guide work for vue, python and html files?
<a title="$('Add this book to your Want to Read shelf')">$('Want to Read')</a>

**Comment by merwhite11** [comment]
@rebecca-shoptaw 

There are some instances where the title/value is set to a static string and others where it is set to a dynamic variable. 
eg :[LibraryToolbar.vue](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue): 
<label title="I.e. Classification order. Note some books maybe missing when sorting by shelf order–we're working on it.">

eg:[ LibraryToolbar.vue](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/components/LibraryExplorer/components/LibraryToolbar.vue)
<label v-for="c of settingsState.classifications" :key="[c.name](http://c.name/)" :title="c.longName">

I see that this is the syntax for variables: ``$_("Hi, %(user)s", user=username)!` `, 
but how do I ensure the variable value is also i18n’ed? 

eg, here the book title must also be translated : [BooksCarousel.vue](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/components/LibraryExplorer/components/BooksCarousel.vue)
<a class="book" v-for="book in books" :key="book.key" :href="${OL_BASE_BOOKS}${book.key}" target="*blank" :title="%*(book.title)">

**Comment by merwhite11** [comment]
@rebecca-shoptaw 
I am assuming that any instances of title or value in the .po files do not need to be i18n syntaxed, as those are the english reference points for the translations. 

eg[ tr/messages.po](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/tr/messages.po)
```
#: lib/not_logged.html:7
msgid ""
"<strong>You are not <a href=\"/account/login\" title=\"Log in "
"now\">logged in</a>.</strong> Open Library will record your IP address "
"and include it in this page's publicly accessible edit history. If you <a"
" href=\"/account/create\" title=\"Create an Open Library account\">create"
" an account</a>, your IP address is concealed and you can more easily "
"keep track of all your edits and additions."
msgstr ""
```

last one, thank you !!

**Comment by rebecca-shoptaw** [comment]
Thanks for the great questions @merwhite11 ! 
1. Good catch! This format and `gettext()` method  only runs on HTML and Python files (and you're likely only to find the relevant `title`/`alt` attributes and `value` placeholders in the HTML in any case), so you can just focus on those for this issue. :)

2. On a related note, it looks like the sample cases you found are all Vue files, so there's no need to do anything with them as a part of this issue, but if you have any trouble with variable formatting in the HTML files, here's a quick example re: formatting more complicated variables:

For this untranslated `alt` and `title`:
https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/macros/databarAuthor.html#L78
Sample fix, modeled on this file's formatting:
https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/templates/type/work/editions.html#L21
Option 1:
 `alt="$_('Cover of: %(title)s', title=page.title + (': ' + page.subtitle if page.get('subtitle', None) else ''))"`
 Option 2 (a little tidier):
 `alt="$_('Cover of: %(title)s', title=f'{page.title}:{page.subtitle}' if page.get('subtitle', None) else page.title)"`
 
And there's no need to translate the content of the variable itself (book/page title), as it's helpful to keep it in its own language so people know what language the book/page is in.

3. Yep! Ignore all the `.po` files!

**Comment by merwhite11** [comment]
@rebecca-shoptaw 

Thank you for clarifying !

1. Got it. Will only edit HTML and Python files for this issue. 

2. I will use the python f-string example from Option 2 for variables - i like the tidy. And leave variable values in original language. 

3. no .po !

**Comment by merwhite11** [comment]
Ok, just to clarify again based on the examples your provided for variable syntax (Question 2) :

I need to repeat the syntax for both alt and title, correct? 

[databarAuthor.html](https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/macros/databarAuthor.html#L78)

            `<a href="$page.url">
            <img src="$cover" 
            width="32" 
            alt="$_('Cover of: %(title)s', title=f'{page.title}:{page.subtitle} if page.get('subtitle', None) else page.title)" 
            title="$_('Cover of: %(title)s', title=f'{page.title}:{page.subtitle} if page.get('subtitle', None) else page.title)"
            />
            </a>`

**Comment by rebecca-shoptaw** [comment]
@merwhite11 It seems so, alas, but if you want to make it cleaner, you could put the result of all that title logic into a variable at the top of the file, which could even just be called `title`, as here:

https://github.com/internetarchive/openlibrary/blob/0f19a3cd6c74804c43704a53c2107097d8351433/openlibrary/templates/covers/book_cover.html#L1-L4

and then call it later on when you need it:
https://github.com/internetarchive/openlibrary/blob/0f19a3cd6c74804c43704a53c2107097d8351433/openlibrary/templates/covers/book_cover.html#L33

**Comment by merwhite11** [comment]
@rebecca-shoptaw 
I'm unable to request a slack invite. When I click the link to request in the Wiki, it takes me to https://openlibrary.org/volunteer & I've already filled out the volunteer form here. Is there any way you could add me?

**Comment by rebecca-shoptaw** [comment]
@merwhite11 Ah, yes there's often a bit of a backlog in approving the slack join requests -- will ask around re: adding you now, and feel free to ask any more questions re: the issue here if you'd like!

**Comment by merwhite11** [comment]
@rebecca-shoptaw Alrighty, I edited the title, value and alt attributes in the HTML and Python files. I have it all pushed to my github fork's branch, but having trouble running the tests / getting my dev env to run. I had it running previously with Docker, but getting a 500 error now. Maybe I could get someone to help me at the meeting tomorrow?

**Comment by rebecca-shoptaw** [comment]
@merwhite11 Woohoo!! Thanks so much for taking on this big and repetitive task! Re: Docker, yes that will be a good thing to mention at the meeting and we can definitely do some troubleshooting to get everything up and running again. :)

**Comment by merwhite11** [comment]
@rebecca-shoptaw (leaving notes for future reference):
Was getting `No module name 'web'` error when initially trying to run extract command. 

Successfully ran the extract command using these steps: 
`docker compose run --rm -uroot home bash
pip install web.py
./scripts/i18n-messages extract`

Getting extract failures in /openlibrary/openlibrary/macros and /openlibrary/openlibrary/templates files. It is failing due to `$def with (VARIABLE NAMES)` syntax on the first line of each file. I'm going to disregard this failure.

**Comment by rebecca-shoptaw** [comment]
@merwhite11 Good call! The new automation process should prevent that in the future, so feel free to ignore!
