### ISSUE TITLE
Work cover selector lost ability to scroll

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8906]
### Problem

As of the last deployment, the ability to scroll through available work covers has gone missing.

#### Evidence / Screenshot
<img width="603" alt="Screenshot 2024-03-07 at 23 05 12" src="https://github.com/internetarchive/openlibrary/assets/17739465/f05813f3-b719-47d2-b073-b25c0ba37cec">

#### Relevant URL(s)
https://openlibrary.org/works/OL...W/-/add-cover

### Reproducing the bug

1. Go to ...https://openlibrary.org/works/OL...W/-/add-cover
2. Do ...look for a way to scroll through available covers.

* Expected behavior: You should be able to scroll.
* Actual behavior: You are unable to scroll.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by mekarpeles** [comment]
May be related to carousel js refactor.
