### ISSUE TITLE
Generate work-level isbn synonym dump

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8914]
Internal task to generate a dump of ~ isbns grouped by work.

## Completion criteria

We want to be at a place where e.g. @hornc can help run as-needed (e.g. monthly) work-level isbn synonym dumps and thus require:

- [ ] There's a README with documentation for generating work-level synonym ISBN dump
- [ ] A script for generating a work-level synonym ISBN dumps

**Comment by Ayush1404** [comment]
Hey, I would like to work on this issue but I don't understand it quite well, could you please elaborate on it a little?

**Comment by cdrini** [comment]
Re-ran the latest dump. Cleaned up the docs a bit in the PR.

@Ayush1404, ah missed your message; this was a staff issue :+1:
