### ISSUE TITLE
Allow markdown in "Why did you choose this excerpt?" field

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#8925]
### Describe the problem that you'd like solved
See title. This could be helpful to (for example) link to other pages within explanations.

### Additional context
Maybe there are good reasons to allow some markdown but not all of it.

**Comment by mekarpeles** [comment]
@jimchamp may know about another similar PR we can reference which may make doing this one a good first issue for a new contributor.

It may be this one!
* #8862

**Comment by jimchamp** [comment]
#8862 is the correct PR.  Adding the markdown editor to the excerpts field should be as simple as adding the `markdown` class to the `textarea`.

**Comment by raffchen** [comment]
Hi, may I work on this issue?

**Comment by etgibbs** [comment]
Hello! I am a university student looking to make an open-source contribution for my SWE class - would we be able to take this issue?

**Comment by jimchamp** [comment]
@raffchen, you've been assigned.  This [file](https://github.com/internetarchive/openlibrary/blob/4043d671afe60105063fdcd12f59ffe36b087cbc/openlibrary/templates/books/edit/excerpts.html) is the template for the excerpts section of the edit page.

**Comment by jimchamp** [comment]
This is a little more complicated than I thought.  The excerpt markdown is not being rendered correctly on book pages.

I'm also wondering if we want to let people add arbitrary links to book pages.  Blocking this until the team can discuss this.

**Comment by cdrini** [comment]
So we already allow arbitrary links in description, with a regex we use to ban certain spammy link. We should make sure that regex is applied in these new fields and not just description, but then arbitrary links should be ok.
