### ISSUE TITLE
No `Cache-Control` headers on IA CDN requests

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8927]
### Problem

These two JS load on every page: https://openlibrary.org/cdn/archive.org/donate.js and. https://openlibrary.org/cdn/archive.org/analytics.js

However, they are not cached like the rest of the JS.
This causes a lot (2 seconds) delay when on a very slow connection (only a few 100ms on a decent connection).

Their headers:
```
Content-Encoding: gzip
Content-Type: text/javascript
Date: Wed, 20 Mar 2024 11:48:52 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx/1.18.0 (Ubuntu)
Vary: Accept-Encoding
X-Ol-Stats: ""
```

Headers for all other requests:
```
Cache-Control: max-age=315360000
Content-Encoding: gzip
Content-Type: application/javascript
Date: Wed, 20 Mar 2024 11:03:17 GMT
Etag: W/"65e78c3f-69215"
Expires: Thu, 31 Dec 2037 23:55:55 GMT
Last-Modified: Tue, 05 Mar 2024 21:18:55 GMT
Referrer-Policy: no-referrer-when-downgrade
Server: nginx/1.18.0 (Ubuntu)
```

#### Evidence / Screenshot
<img width="1511" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/79644e7c-160c-44f4-ac3d-1c795665b1f0">

#### Proposal & constraints

Add cache control headers.

Probably should also add `defer` or `async` to their script tags so they don't block loading when they're not cached but this could be a different issue.
https://javascript.info/script-async-defer

#### Related files

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/plugins/openlibrary/code.py#L425-L430

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/templates/site/footer.html#L41-L42

https://github.com/internetarchive/openlibrary/blob/45ed08186221233c04f1859e3b8a703152b01539/openlibrary/plugins/upstream/utils.py#L1468-L1469

#### Stakeholders

PS: I don't have bandwidth to take this right now.

**Comment by QuantuM410** [comment]
Hey! I would like to work on this issue :)

**Comment by RayBB** [comment]
@QuantuM410 go for it!

**Comment by cdrini** [comment]
Since the deploy, the number of transactions to this endpoint are ~1/4 of what they were before! 
![image](https://github.com/internetarchive/openlibrary/assets/6251786/4790c15d-5157-4cf9-bac4-9e7323f12f76)

**Comment by RayBB** [comment]
@cdrini that's great thanks for the update! Is TPM thousands per minute?

Good job @QuantuM410 ! Very nice impact :)

**Comment by cdrini** [comment]
Transactions per minute!

**Comment by cdrini** [comment]
This was quite useful; would you mind creating a new issue to add the headings to `partials.json` ? That's another one which I think would work well with some browser-side caching! CC @jimchamp
