### ISSUE TITLE
No mechanism for Orphaned Editions to be removed from Solr once resolved

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#893]
Orphaned editions (ones without Works) are currently indexed in Solr as `/works/<edition_ID>`  e.g `/works/OL20454633M`

This is a workaround to allow them to appear in search results 
https://github.com/internetarchive/openlibrary/blob/d1fb792b9b33b93fd81a346cdc4f5934a5216e91/openlibrary/solr/update_work.py#L1127

When a work is added by a move or other edit, there is nothing that notices the change and removes the old  `/works/<edition_ID>` from the index, so the fake work will continue to appear in search results.

 `/works/<edition_ID>` needs a Delete update sent to Solr.

Currently the only way to remove them is to manually add the  `/works/<edition_ID>` keys to admin/solr interface.

**Suggestion:**
When the solr updater script sees an edition edit in the Infogami logs, in the `changeset` / `changes` fields, it should send a delete request to Solr for the `/works/<edition_ID>`  This will produce some delete requests for non-existent keys, but this does not cause a problem for solr. The alternative would be to query solr to find whether a '/works/` key exists for that edition, and delete if so. My thinking is that sending a delete anyway will put less load on solr but have the same end result.

**Comment by hornc** [comment]
Added the "blocker" tag because bulk or manual resolving orphaned editions is not much use if search results and author work lists are going to show them indefinitely.

**Comment by LeadSongDog** [comment]
These fake works are particularly egregious in that an edition without all three of an author,  a publisher, and a publication place seems to create a new fake work even in the attempt to link it to an existing known work.

**Comment by hornc** [comment]
Resolved in https://github.com/internetarchive/openlibrary/commit/cd67d7bfd666561124885c0cfe1e077cb82e5fe5
