### ISSUE TITLE
Side menu on mobile doesn't reach top/bottom of screen

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8943]
### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by QuantuM410** [comment]
Hey @RayBB! I can make a quick PR, just a question. Is the behaviour intended as it seems in the css. . 
![image](https://github.com/internetarchive/openlibrary/assets/85943021/9bc9b93d-99e0-4c29-b441-6b28575dd176)
https://github.com/internetarchive/openlibrary/blob/9222960a6007568c50acf97fcb612170e2817c2f/static/css/components/header-bar.less#L93-L100

**Comment by RayBB** [comment]
I'm not so sure about the CSS.
But you seem to have understood the issue before I could write the description.

I think ideally we will have it reach the bottom of the page and I'm not sure if we want it to reach the top of just under the donation bar. Personally I think it should go all the way to the top but maybe we should offer a mockup of both options so the staff and pick.

@QuantuM410

**Comment by QuantuM410** [comment]
![image](https://github.com/internetarchive/openlibrary/assets/85943021/ed5f03ba-c3dd-49c4-9aac-b828335c6949)
This is the sidebar covering the entire height

**Comment by RayBB** [comment]
@QuantuM410 Personally, I think that looks good, especially if we put a uniform shadow over the whole back area (like how GitHub does it) instead of a gradient shadow that's lighter at the top.

<details>
  <summary>Example</summary>
  

https://github.com/internetarchive/openlibrary/assets/921217/ccbfaa14-451c-4d01-af68-93a2bd132587
  
  
</details> 

I'll emphasize again that it's not up to me so we'll need to propose our best options to Drini/Mek and let them make the call. 👍

**Comment by QuantuM410** [comment]
@RayBB  I agree with the removal of gradient shadow as uniform shadow looks much better and consistent to me. Sure! will make a PR after its been decided :)

**Comment by RayBB** [comment]
While we're at it, maybe we could make the sidebar scroll in/out a little smoother? Kinda like what I did in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5389

**Comment by RayBB** [comment]
@QuantuM410 can you share a screenshot of what it would look like? We can post it in the design channel. They have a call today and could get us feedback pretty quick I hope :)

**Comment by QuantuM410** [comment]
![image](https://github.com/internetarchive/openlibrary/assets/85943021/902f7115-496c-4a98-aaa8-44cc8cf97c84)
@RayBB Sure! Here, I just removed the gradient and added ```rgba(0, 0, 0, 0.5);```

**Comment by RayBB** [comment]
@QuantuM410 drini said the bottom design looks good so let's go with that! If you feel like adding smooth transitions it's welcome but not required.
