### ISSUE TITLE
Remove unused name match code

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#8958]
### Problem

While working on #7349 I noticed that the name matching code in `openlibrary/catalog/add_book/match_names.py` and `openlibrary/catalog/add_book/tests/test_match_names.py` is either not used, or it's only used within the the pair of files.

We should delete these files.

### Context

Because I needed to verify if one of the functions was used so I could see if I was interrupting some existing business logic, I used `git grep` to check whether that function was called anywhere. It was called within a function in that file, so I had to check that. In turn I checked if each function was called by a function outside of either of these two files. Though there are a few functions by the same name in other files (e.g. `flip_name()` in `openlibrary/catalog/utils/__init__.py`), none of the functions in these two files are called outside of these two files.

**Comment by kw-8** [comment]
Hi, can you assign me this issue? I would like to get familiar with the internet archive repo in general :)

**Comment by scottbarnes** [comment]
@kw-8, thanks for your interest in this issue. I have assigned it to you.

If you've not yet done so, you'll want to check out [CONTRIBUTING.md](https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md), with particular emphasis on:

- the [Docker installation README.md](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md), though to be fair, this issue can likely be solved without actually running any code.
- [How we use git](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) (AKA the Git Cheat Sheet")

Then for this issue specifically, you'll want to make sure none of the functions deleted are called anywhere else (note: some of the function names exist in multiple files, sadly). If none of the functions are used, you can `git rm` the file.

Please ask any questions that you might have.

**Comment by DebbieSan** [comment]
Hi @scottbarnes, it seems this issue is idle. Could I kindly work on it? TIA

**Comment by scottbarnes** [comment]
@DebbieSan, I forgot to mention I assigned this to you, but I see you submitted a PR, so thank you very much for that.
