### ISSUE TITLE
Delete bad author names (cassette catalog ids)

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#896]
@hornc 
Similar to #152 many Compact Cassette catalog ids have been embedded in author record name fields.
Please run this oh-so-similar check to quantify the current size of the problem:
egrep -Ec " Cs[a-zA-Z0-9]{2,4} " ol_dump_authors_2018-02-28.txt

**Comment by mekarpeles** [comment]
I think we wanted to open this issue on openlibrary-client!
https://github.com/internetarchive/openlibrary-client/issues/74
