### ISSUE TITLE
Support different seeds for random.hourly sort

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8965]
These carousels are all sorted by random.hourly, but we want them to have a different random subset!

![image](https://github.com/internetarchive/openlibrary/assets/6251786/408dcd86-f96a-4534-bacf-46f437f9f444)

### Proposal & Constraints
Expand `random.hourly` sorting to support a custom seed like `random`

### Stakeholders
@RayBB

**Comment by tfmorris** [comment]
Are you sure there's no a data issue here? On the surface, it seems surprising that the best books for 12th graders are also the best books for 6th graders.

**Comment by RayBB** [comment]
@tfmorris we discussed this on the community call. Lisa and co said that reading levels aren't always what you might expect them to be. It's not about "best" it's about some other calculation based no vocabulary and such.

That's not to say there isn't a data issue but we don't think there is. If you find any examples where the data is bad let us know please!
