### ISSUE TITLE
Login errors not localized

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#8967]
### Problem

Login errors are only displayed in English, regardless of chosen language.

#### Evidence / Screenshot
![localized_login_errors](https://github.com/internetarchive/openlibrary/assets/28732543/3c71e35d-21cd-4b5c-96ba-b862820ee169)
_Highlighted area displays non-localized strings._

#### Relevant URL(s)
https://openlibrary.org/account/login

### Reproducing the bug

1. Go to the `/account/login` page
2. Select a language other than English from the language dropper, found on the page's banner
3. Log in with invalid credentials

* Expected behavior: Error message is written in the selected language
* Actual behavior: Error message is English

### Context

- Browser (Chrome, Safari, Firefox, etc): All
- OS (Windows, Mac, etc): All
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

#### Proposal & constraints

Replace hard-coded login errors with localized strings.

#### Related files

The error strings can be found in the `LOGIN_ERRORS` `dict`, here:
https://github.com/internetarchive/openlibrary/blob/a2f111c8cf6b52e2e30f7ae1fb009b76d3c92b5e/openlibrary/plugins/upstream/account.py#L60-L76

Keys of this `dict` should remain as they are --- only the values should change.

#### Stakeholders

@rebecca-shoptaw

**Comment by RBrar66** [comment]
Hi, I would like to work on this issue.

**Comment by rebecca-shoptaw** [comment]
@RBrar66 Great, it's all yours! You can read up more fully on the internationalization syntax as needed in the [wiki](https://github.com/internetarchive/openlibrary/wiki#internationalization-i18n-developers-guide), but for reference here is an example of a correctly internationalized Python string:
https://github.com/internetarchive/openlibrary/blob/6816776da0a228675bd818d3ac2a4b47a9b9f8ac/openlibrary/plugins/upstream/account.py#L536-L537

All the `i18n` process requires here is wrapping the to-be-translated string in `_(' ')` like the example above, i.e. `"invalid_email": "The email address you entered is invalid", ` would become `"invalid_email": _('The email address you entered is invalid'), `

Thanks so much and let me know if you have any questions!
