### ISSUE TITLE
Profile images broken from some users

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8974]
### Problem

We sent this to the IA team to investigate but:

> We might have to fix on our side. There were changes to the IA endpoint; it used to automatically return a default image. It's not clear yet whether they'll be able to restore that behaviour. If not, we'll need to create a wrapper endpoint around it on OL.

#### Evidence / Screenshot
![image](https://github.com/internetarchive/openlibrary/assets/921217/bfeb1382-26f6-4238-826b-bf88df5a1cf6)

#### Relevant URL(s)
https://internetarchive.slack.com/archives/C0ETZV72L/p1711540073200289

### Reproducing the bug

Definitely happens if you don't have a profile picture set. Might also happen if you do have a profile picture set.

Example
`<img class="account__icon" src="https://archive.org/services/img/@raybb" alt="My account" title="raybb
Joined September 21, 2020">`

**Comment by rebecca-shoptaw** [comment]
Weird!! I checked and got the same error behavior on both OL and IA, I tried setting a profile picture and confirmed it does still show if a picture is set. Hopefully they figure it out on their end!

**Comment by RayBB** [comment]
Suddenly it seems to be working again!

![Screenshot_20240327-230518.png](https://github.com/internetarchive/openlibrary/assets/921217/e47b2fe4-fbfd-428e-8b73-317610712dc6)

**Comment by cdrini** [comment]
This is now fixed, thank you @traceypooh !
