### ISSUE TITLE
 Test commands in the documentation need more context/consistency

### ISSUE THREAD

**Issue by juanig1** [internetarchive/openlibrary#8985]
### Problem
(Meta) The git cheat testing section sheet assumes the web container is running 
#### Evidence / Screenshot
Both `docker compose exec web make test` and `docker compose exec web npm run lint` need the `web` container to be running. It is not the case if you are just following the instructions up to that point.
#### Relevant URL(s)
https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#creating-a-pull-request > `Test your changes:5` 

### Reproducing the bug

1. Go to openlibrary repo
2. Do:
```
$ docker compose exec web make test
```

* Expected behavior:
Tests run

* Actual behavior:
Test do not run:
```
$ docker compose exec web make test
(some warnings)
service "web" is not running
```
(same case for linting)

### Context

- Browser (Chrome, Safari, Firefox, etc): -
- OS (Windows, Mac, etc): Linux + Docker
- Logged in (Y/N): -
- Environment (prod, dev, local): dev

#### Proposal & constraints

I may be missing something but my suggestion would be either:
1) Update the guide so users:
- first run openlibrary locally via `docker compose up`
- navigate to `localhost:8080` and test manually 
- (and then) run tests/lint with the original commands (in a new terminal) 
Or:
Use `docker compose run --rm` instead of `exec` i.e: `docker compose run --rm web make test`, this way a container is created and destroyed once the command finishes. (update: Seems this is already in use here: https://github.com/internetarchive/openlibrary/wiki/Testing, maybe drop the --rm to keep it consistent with that)
#### Related files

https://github.com/internetarchive/openlibrary/wiki/Testing

**Comment by juanig1** [comment]
@mekarpeles hey, just updated the wiki to use `run` instead of `exec` to tackle this (as used [here](https://github.com/internetarchive/openlibrary/wiki/Testing)).
First time using github's wiki, but just wanted to point out it did not ask for a pr/approve

**Comment by scottbarnes** [comment]
Thanks for both catching and being to update this, @juanig1.

I was just thinking about it a bit more, and if we use `docker compose run`, we should probably specify the `--rm` flag so people don't end up with a lot of containers, and probably also use the `home` container because it doesn't rely on other containers.

See, e.g. I start with 75 containers, but running a container with `run` and not specifying `--rm` leaves me with +1 containers:
```sh
❯ docker container ls -a | wc -l                                                                                                                                                                                                                                                            
75                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            
❯ docker compose run home w                                                                                                                                                                                                                                                                 
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.                                                                                                                                                                                                                    
 03:13:47 up 4 days, 10:46,  0 users,  load average: 5.42, 3.67, 2.25                                                                                                                                                                                                                       
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                            
❯ docker container ls -a | wc -l                                                                                                                                                                                                                                                            
76                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                            
❯ docker compose run --rm home w                                                                                                                                                                                                                                                            
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string.                                                                                                                                                                                                                    
 03:14:11 up 4 days, 10:46,  0 users,  load average: 3.78, 3.42, 2.20                                                                                                                                                                                                                       
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                            
❯ docker container ls -a | wc -l                                                                                                                                                                                                                                                            
76
```

@juanig1, would you mind updating the commands to use `docker compose run --rm home`?

**Comment by scottbarnes** [comment]
I just saw you already mentioned `--rm` in the issue description. You're on it, @juanig1. :) Let's use `docker compose run --rm home <whatever>` in both places. Would you be willing to update both the Git Cheat Sheet and the [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing) wiki article?

**Comment by juanig1** [comment]
Hey scott, thanks for

**Comment by juanig1** [comment]
Hey @scottbarnes, thank you for the input!

Updated both Git Cheat Sheet and Testing wiki articles to use `run --rm` and the `home` container:
[Testing diff](https://github.com/internetarchive/openlibrary/wiki/Testing/_compare/d02d070772b2f623106ac4d3866884d1cc83eb29...3d465f762ca4449dd89e734290e753403a1470b6), [Git Cheat Sheet diff](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet/_compare/3786efd2eff83826a1a6af787b186fd53adbeac8...b15738860ae9e66cd66ab48e24f254883e6cb427)

If we want to be more thorough, there's one more use of `docker compose exec` (excluding scripts) in the [Readme](https://github.com/internetarchive/openlibrary?tab=readme-ov-file#running-tests) but seems to be explained correctly. Can update that too if you want so everything is consistent.

Happy to help!

**Comment by scottbarnes** [comment]
Thanks for updating those, and good catch on the use of `docker compose exec` in the `README` files, @juanig1. Let's go with consistency, even if that one is more clear about having the containers running.

Please update that one as well, if you're willing, by making a PR to modify the English and Chinese `README` files. And I think remove the `cd docker` as that may only confuse people.
