### ISSUE TITLE
add cache control headers to partials.json

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8991]
> This was quite useful; would you mind creating a new issue to add the headings to `partials.json` ? That's another one which I think would work well with some browser-side caching! CC @jimchamp

_Originally posted by @cdrini in https://github.com/internetarchive/openlibrary/issues/8927#issuecomment-2027686950_

**Comment by cdrini** [comment]
After some more thinking I realized that unlike the `/cdn` endpoint which is hit on every pageload on openlibrary, this endpoint is _different_ on every page; so having a browser-side cache would likely not be a huge improvement. Closing as not worth the potential benefit right now.
