### ISSUE TITLE
Filters from the same category dissappear

### ISSUE THREAD

**Issue by raffchen** [internetarchive/openlibrary#8994]
#### Evidence / Screenshot
If we have more than one filter from the same category on a search like so:
![image](https://github.com/internetarchive/openlibrary/assets/19312856/501fde45-40df-4f2e-b91f-95ce4b8f6b5a)

And then we add a filter from a different category using the side menu, then only the one that was added last stays:
![image](https://github.com/internetarchive/openlibrary/assets/19312856/37c6bed4-993d-4ae8-afb8-20e72db0d5fb)

Adding the filters by manually editing the [URL](https://openlibrary.org/search?q=fantasy&mode=everything&subject_facet=Fiction%2C+fantasy%2C+general&subject_facet=Fiction&subject_facet=Fantasy&language=spa) still works:
![image](https://github.com/internetarchive/openlibrary/assets/19312856/f2135887-6e31-42f0-90a7-a85157eb50f8)

#### Relevant URL(s)
https://openlibrary.org/search?q=fantasy&mode=everything&subject_facet=Fiction&subject_facet=Fiction%2C+fantasy%2C+general&subject_facet=Fantasy

### Reproducing the bug

1. Search for a book and apply multiple filters from the same category, or go to https://openlibrary.org/search?q=fantasy&mode=everything&subject_facet=Fiction&subject_facet=Fiction%2C+fantasy%2C+general&subject_facet=Fantasy
2. Using the side menu, add a filter from a different category, such as Language or Author

* Expected behavior: All of the filters from the Subjects category remain, and the new filter is also applied (like in the 3rd screenshot)
* Actual behavior: The new filter is applied, but all but one of the filters from the Subjects category disappear

### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome, Firefox
- OS (Windows, Mac, etc): Windows
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

**Comment by raffchen** [comment]
After doing some digging, it looks like this is because of webpy's `storify` function. This is used in webpy's `input` function which we use in `changequery`. 

https://github.com/webpy/webpy/blob/d3649322b85777b291ac2b7b3699fb6fc839e382/web/utils.py#L130-L141
![image](https://github.com/internetarchive/openlibrary/assets/19312856/7a32675f-d32b-4417-a21e-ca992a49d707)

For my example URL from above, this is the result:
![image](https://github.com/internetarchive/openlibrary/assets/19312856/2539cd10-033e-4a58-b58b-fe3c15a4f943)

**Comment by raffchen** [comment]
I've linked a draft fix for this that seems to work.

**Comment by cdrini** [comment]
Hi @raffchen apologies for the delay! Your approach touches a method that is used _profusely_ throughout the codebase, so I need to fully understand the implications of the change (which involves understanding some web.py internals) and try to come up with some clever ways to test it. I haven't had the time to tackle that kind of task. Apologies for the delay!

**Comment by cdrini** [comment]
This appears to no longer be an issue; it was incidentally fixed by #9397 .
