### ISSUE TITLE
Fix Search to enable faceting by availability_type (public, print-disabled, lendable)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#900]
Following up on #59, related to #978 

We could completely fix our search results if we had a way to filter works with editions that are `lendable`, `restricted` (i.e. printdisabled) or `public`.

There are:
- 1M printdisabled books (not `inlibrary`) 
- .66M lendable books in `inlibrary`
- 2.18M public books in OL `accessible_book` subject

In total, this could touch 3.84M editions.

We'd also want to update solr to our works are re-indexed according to whether they have `lendable`, `restricted`, and `printdisabled` books available.

**Comment by mekarpeles** [comment]
This actually may not be needed given `solr` is already keeping track of many of the required fields.

A book has one of four `access_classes`: `public`, `lendable`, `print-disabled`, or `unavailable`.
Related to: #1929 

These fields are indexed as follows within: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py#L638-L649

- `q=ia_collection_s:*inlibrary*` -- item is **lendable**
- `q=public_scan_b:true` -- item is **public**
- `q=printdisabled_s:*  -- item is **print-disabled**

**Comment by tfmorris** [comment]
It looks like the number of works is on the order of 2.65M. Most of the data is in SOLR, but not in the easiest form to use. In particular, `ia_collection_s:*inlibrary*` to mean `lendable:true` is awkward because it Solr can't build a facet from it.

If we do want to change the schema, doing the same time as we're making other schema changes would allow the reindexing to be combined.

Here are some stats from the current experimental Solr instance loaded with recent data:


```
public_scan_b:
 term | frequency
 true | 1516516
false | 1187320

printdisabled_s: 1193930 records with fields looking like:
term | frequency
OL1000003M | 1
OL1000032M;OL6778912M | 1
printdisabled_s:*;* - 65240 works with multiple IDs (ie almost all have a single ID)

ia_collection_s:*inlibrary* 873622
ia_collection_s: 297682 distinct values with collections concatenated together
term | frequency
printdisabled;inlibrary;china;internetarchivebooks | 303092
printdisabled;librarygenesis | 245900
americana | 227557

2374508 ia_collection_s:*inlibrary* OR public_scan_b:true
 285679 printdisabled_s but not public_scan_b or ia_collection_s:*inlibrary*

```

**Comment by tfmorris** [comment]
p.s. we also have `has_fulltext`

```
 term | frequency
   -- | --
false | 19333485
 true | 2703836


```

**Comment by guyjeangilles** [comment]
I added the Search theme and the Feature type (I was split between Feature and Refactor for the latter). Let me know your thoughts.

**Comment by mekarpeles** [comment]
This is resolved with @cdrini's recent edition-level search
