### ISSUE TITLE
Cron to restart ol-mem[0-2] daily or weekly

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9000]
Memcache sometimes gets saturated and stuck (memory leak?) after running for a prolonged time.

We want to, for now, add a cron to the memcached servers to restart e.g. once a day or once a week.

**Comment by RayBB** [comment]
@mekarpeles @cdrini 
1. Are there any logs from when memcached stopped working that may shine light on this?
2. What version of memcached do we use? I don't see it mentioned anywhere in dockerfiles but [in python](https://github.com/internetarchive/openlibrary/blob/506551862ff2509a5215bad70050bd42f2bf3b01/requirements.txt#L25) it says `1.59` which was released more than half a decade ago (2018-7-7)! There have seen been dozens of releases including some that say they improve the stability of memcached.

**Comment by cdrini** [comment]
Unfortunately our memcached isn't managed via the docker compose like the rest of the cluster, so it's whatever version happens to be on the systems themselves.

Note the version in the requirements.txt isn't the version of `memcached` itself, but the version of the python client library. If you want to create an issue to update it, and test that things work locally, that would be great!

**Comment by cdrini** [comment]
Considering this blocked; our crons run in a container which doesn't (and shouldn't) have ssh access to other servers in the cluster. The proper approach would be to use containers for memcached and then hook these servers up via a swarm network. Don't have time to allocate to that right now.

**Comment by cdrini** [comment]
@RayBB the logs unfortunately reveal nothing; they just note when it was restarted.

**Comment by RayBB** [comment]
@cdrini thanks for looking into the logs.
Is it possible for you to check what version of mem cached is used on the machine?

**Comment by mekarpeles** [comment]
We're going to put a cron on the memcached servers themselves, because the whole thing we want to see is if this is even worth pursuing / does it fix the problem... And if we lose the code during an upgrade, so be it. If it's useful enough, we'll find a way to codify it as a process e.g. docker swarm

**Comment by RayBB** [comment]
@mekarpeles when you do that could you check the memcached version?

**Comment by mekarpeles** [comment]
`memcached 1.5.22`

**Comment by mekarpeles** [comment]
I've run `sudo crontab -e` on each `ol-mem[0-2]` and added
```
0 0 * * * /etc/init.d/memcached restart
```
And confirmed with `sudo crontab -l`

**Comment by RayBB** [comment]
@mekarpeles memcached [1.5.22 is from 2020-2-1](https://github.com/memcached/memcached/wiki/ReleaseNotes)

If this issue happens to come up again, it might be worth looking into an upgrade (lots of bugfixes mentioned in the new changelog).
