### ISSUE TITLE
Why does this search not find the main works for The Lord of the Rings?

### ISSUE THREAD

**Issue by thomasmichaelkane** [internetarchive/openlibrary#9021]
### search
https://openlibrary.org/search.json?title=The+Lord+of+the+Rings&author=J.R.R.+Tolkein --- {67 results}

### id of target works not found
https://openlibrary.org/works/OL27448W/

A search without the author finds the correct works, even though this author name spelling matches that in the json perfectly. I fear that this error may happen repeatedly if it is happening with such a big title as this.

**Comment by seabelis** [comment]
@thomasmichaelkane Try https://openlibrary.org/search.json?title=The+Lord+of+the+Rings&author=J.R.R.+tolkien

**Comment by thomasmichaelkane** [comment]
thanks!

**Comment by cdrini** [comment]
Going to close this since it was a spelling error. Note @benbdeitch has a PR that's currently undergoing code review/qa that will make our search resilient to small spelling errors like this. #6923
