### ISSUE TITLE
Delete some unused templates discovered by i18n process

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9057]
Delete these files and anything that they call that is only called by them. It is no longer possible to edit macros from the openlibrary.org website.

- openlibrary/macros/EditButtonsMacros.html
- openlibrary/templates/type/macro/*
- openlibrary/templates/type/rawtext/*
- openlibrary/macros/SRPCoverImage.html
- openlibrary/macros/databarAuthor.html
- openlibrary/templates/admin/profile.html
- openlibrary/templates/lib/markdown.html

For each:

- Note other macros/templates referenced in the html file. Are they only referenced by the files we are deleting? If so delete it as well
- Search the codebase for the name of the file. Remove any CSS or CSS comments
- Search the codebase for the name of the file. Remove any code (not necessarily entire file) that references the given file.

## Stakeholders

@merwhite11

**Comment by Spedi** [comment]
Hi there!
I suppose I can tackle this issue, is there any chance that I can work on it?

**Comment by cdrini** [comment]
Hi @Spedi ! Go for it :) Let me know if you have any questions!

**Comment by Spedi** [comment]
I was starting to tackle this issue, should I also delete the references of the templates on the .po files?

**Comment by cdrini** [comment]
At the end of the deletions, generate the pot file; that should be enough!

**Comment by cdrini** [comment]
Hi @Spedi I'm going to take this one; it's a little higher priority since I don't want translators to accidentally translate the strings here since they won't be used!

**Comment by Spedi** [comment]
Hi there @cdrini!
Don't worry, and I'm sorry I didn't make any PR, I probably shouldn't have taken too many issues on my back :)

**Comment by cdrini** [comment]
This is priority 2 because otherwise translators will translate strings we don't actually need :+1:
