### ISSUE TITLE
"Add book" gives misleading Permission Denied page if not logged in

### ISSUE THREAD

**Issue by whatisgalen** [internetarchive/openlibrary#906]
Rather than a heading saying "Permission Denied" we should have something more direct informing the user to log in order to do this action, for instance:
"Please **Log in** to your Open Library account in order to add a new book."

**Comment by guyjeangilles** [comment]
This still an issue. If a user tries to borrow a book without logging in they are appropriately directed into a log in page. 

@mekarpeles I assume this would be a good first issue, but if not, are you willing to be assignee? Note, being the assignee doesn't necessarily mean you are responsible for doing the work, just responsible for gathering/providing information to address the issue. From the Wiki.

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

**Comment by mekarpeles** [comment]
Here's where the code is:
https://github.com/internetarchive/openlibrary/blob/742b48a0aa88cec0820f5b57575b812e72ffc396/openlibrary/plugins/openlibrary/code.py#L193-L211

One line 198, we can add a check to see if the user is logged in...
```
if not web.ctx.site.get_user():
    raise web.seeother("/account/login?redirect=/addbook")
```
Which will redirect gracefully to login and then to addbook (once they login) without showing an error message first. Saves the user a step.

@whatisgalen do you have any interest in trying this one?

**Comment by user404d** [comment]
Was looking into this one a little bit and ran into the same issue being addressed by #2958, so this one will probably need to wait until that change is wrapped up and merged.

**Comment by guyjeangilles** [comment]
@user404d can you post a screenshot, traceback, and or the steps you took  to deduce that #2958 is related? This is valuable information to retain in the issue thread.

**Comment by user404d** [comment]
I may be wrong in thinking that the other issue will hold up progress on this issue. Here's what made me think that it may still cause a problem:

Running locally with a personal recaptcha...

1. Navigate to the form to add a book while anonymous
![anonymous book addition](https://user-images.githubusercontent.com/6620882/73717111-76eaba00-46de-11ea-93a8-3f3819b25dd4.png)

2. Logs and page after submission of the new book
![anonymous book addition, log after submission](https://user-images.githubusercontent.com/6620882/73717143-8cf87a80-46de-11ea-8585-22118ee46e83.png)
![anonymous book addition, page after submission](https://user-images.githubusercontent.com/6620882/73717146-8ff36b00-46de-11ea-8c74-cc1544c610e7.png)

3. Logs and page after final submission
![anonymous book addition, log after final submission](https://user-images.githubusercontent.com/6620882/73717253-dba61480-46de-11ea-8cae-23508e7368f3.png)
![anonymous book addition, page after final submission](https://user-images.githubusercontent.com/6620882/73717259-e1035f00-46de-11ea-92c5-6b65b1dd878b.png)

It doesn't appear that there is any permissions problems though which seems to be the major concern with this issue, but it may be difficult to work on if the other issue is interfering.

**Comment by user404d** [comment]
This was effectively a fresh instance and my browser was FF72

**Comment by user404d** [comment]
I think that I am missing a lot of context related to this issue. Sorry for the confusion. I only just now realized that this might be behavior only seen when deployed in production or with some settings that I just may not have enabled locally.

**Comment by guyjeangilles** [comment]
Hmm, that seems like separate issue, or at least manifests differently on dev than production.

@user404d Can you make an issue with the information you provided above?

With #2293 came a python3 compatible branch. So if this error doesn't show up on that branch, we maybe able to avoid creating a fix.

**Comment by tfmorris** [comment]
Yes, #2958 should fix this. If you don't want to wait for it to be merged into master, you can merge it into your working branch.

**Comment by cdrini** [comment]
@user404d #2958 merged :+1:

**Comment by tfmorris** [comment]
The full text of the error message is:

> Permission denied to add a book to Open Library.
> 
> Only logged users [sic] are allowed to add records on Open Library. Please [log in](https://openlibrary.org/account/login?redirect=/books/add) to add a book.

That seems pretty similar to the requested:

> "Please Log in to your Open Library account in order to add a new book."

Perhaps we just need to adjust the sentence order or wording?

**Comment by user404d** [comment]
I spent some more time investigating this issue and I am currently unable to change the permissions for editing `/books`, `/authors`, etc. via `admin/permissions` because the save of the permissions is failing. It appears that the lookup in `infogami` for `/books`, `/authors`, etc is failing. Or perhaps it is failing for the other set of things. 

Response from infogami:
```
404 POST /openlibrary.org/save_many {'comment': 'Updated edit policy.', 'data': '{}', 'query': '...'}
```

Contents of `query` pretty printed:
```
[ { u'body': { u'type': u'/type/text',
               u'value': u'One web page for every book. ([More...](/about))'},
    u'child_permission': { u'key': u'/permission/open'},
    u'column_1': u'<h3>Browse the Catalog</h3>\r\n\r\n<p>You can always search, but try jumping in to <b><a href="/subjects"><strong>subjects</strong></a></b>, like <a href="/subjects/astronauts">Astronauts</a>, <a href="/subjects/place:texas">Texas</a>, <a href="/subjects/diaries">Diaries</a>, <a href="/subjects/riots">Riots</a>, <a href="/subjects/place:assam">Assam</a>, <a href="/subjects/time:pleistocene">Pleistocene</a>, <a href="/subjects/person:colette_(1873-1954)">Colette</a>, <a href="/subjects/carpentry">Carpentry</a>, <a href="/subjects/accessible_book">accessible books</a>, or the <a href="/subjects/lending_library">lending library</a>.</p>',
    u'column_2': u'### Add a Book ###\r\n\r\nThere are millions of records in Open Library, but nowhere near every book ever published! Would you like to <b><a href="/books/add">try adding a book</a></b> to the library?',
    u'column_3': u'### Open an Account ###\r\n\r\nYou can keep track of your edits if you <b><a href="/account/create">open an account</a></b>. <br><br>It\'s a wiki too, which means anyone can edit or correct it anytime.',
    u'created': { u'type': u'/type/datetime',
                  u'value': u'2013-03-20T10:27:04.640800'},
    u'intro': u"**Ever wanted to play librarian?**\r\nIt's OK. We all do.",
    u'key': u'/',
    u'last_modified': { u'type': u'/type/datetime',
                        u'value': u'2013-03-20T10:27:04.640800'},
    u'latest_revision': 1,
    u'news': { u'type': u'/type/text',
               u'value': u'<b>Open Library Redesign!</b><br />\r\n\r\n<br />We\'re about to announce the upcoming redesign of Open Library. We\'ve been working for the past few months on a ton of improvements that we can\'t wait to show you. Please, <a href="http://blog.openlibrary.org/">keep an eye on the blog for our announcement</a>.'},
    u'permission': { u'key': u'/permission/restricted'},
    u'revision': 1,
    u'statement': u'If you love books, why not *help build a library*?',
    u'stats': { u'type': u'/type/text',
                u'value': u'{{BookCount("featuring %s books", "including %s with full-text")}}'},
    u'title': u'Open Library',
    u'title2': u'Welcome to Open Library!',
    u'type': { u'key': u'/type/home'}},
  { u'child_permission': { u'key': u'/permission/loggedinusers'},
    u'key': u'/works',
    u'permission': { u'key': u'/permission/restricted'},
    u'type': { u'key': u'/type/page'}},
  { u'child_permission': { u'key': u'/permission/loggedinusers'},
    u'key': u'/books',
    u'permission': { u'key': u'/permission/restricted'},
    u'type': { u'key': u'/type/page'}},
  { u'child_permission': { u'key': u'/permission/loggedinusers'},
    u'key': u'/authors',
    u'permission': { u'key': u'/permission/restricted'},
    u'type': { u'key': u'/type/page'}}]
```

**Comment by user404d** [comment]
mek helped me out and showed me how to fix the missing meta data for permissions

1. Change `/permission` page to `type/permission`
2. Add child `/permission/loggedinusers` with type `type/permission`
3. Add read allowed usergroup `usergroup/everyone`

Then editing permissions via `/admin/permissions` began working.
