### ISSUE TITLE
Give my bot user permissions

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9060]
https://openlibrary.org/people/raybbbot
Per the instructions here: https://github.com/internetarchive/openlibrary/wiki/Writing-Bots

I want to bulk upload ~60 works scraped (with the help of @Realmbird) from https://www.smashingmagazine.com/printed-books/ https://www.smashingmagazine.com/ebooks/
I've carefully looked over the data and it seems good to me.

PS: I have access to the NYT bot creds but figure I shouldn't use that because it is it's own thing.

### Stakeholders

@mekarpeles @hornc

**Comment by mekarpeles** [comment]
Done
