### ISSUE TITLE
Remove `/admin/waitinglists` page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9062]
### Problem

https://openlibrary.org/admin/waitinglists frequently times out because there's too many records and too many queries per record.

The page is presumably supposed to return a list of all books with waitinglists.

Check with @seabelis if this page is needed as I know we have a separate dashboard for Archive.org

![image](https://github.com/internetarchive/openlibrary/assets/978325/eebee98c-26e9-4768-a494-e06060f222cd)

One workaround is limiting the number of books returned, which has been tested by #9059 and works on testing

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by mekarpeles** [comment]
I think we may be able to remove this admin endpoint entirely as the source of truth for checking waitlists is now the archive.org/services/loans API

**Comment by pidgezero-one** [comment]
Could I take this issue on, please? 😊

**Comment by jimchamp** [comment]
@pidgezero-one, go for it!  Let me know if you have any questions about anything.

**Comment by pidgezero-one** [comment]
Thanks @jimchamp !

My only question so far: does this ticket strictly remove admin/waitinglists (and associated code used only for that page), or does it also need to remove all waiting list code entirely (such as the WaitingLoan class)?

**Comment by jimchamp** [comment]
@pidgezero-one, the scope of this issue is limited to removing the admin/waitinglist page and the code associated with it.

**Comment by pidgezero-one** [comment]
Thank you for the clarification @jimchamp ! My PR only covers that scope.
