### ISSUE TITLE
LCBot creating duplicate edition records

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#907]
These four editions: https://openlibrary.org/search?q=9789791442268&mode=everything
not only have the same ISBN, but the same LCCN and were created from four copies of the same LC MARC record - three of which are identical and the fourth of which has a minor version difference.

The LC identifier should be considered a *very* strong identifier in cases like this and should prevent duplicate editions from being created.

Also, in cases where a previously ingested MARC record is updated, we should probably just apply the updates rather than starting from scratch.

**Comment by LeadSongDog** [comment]
The same author has 2 other ISBNs with the same pattern. Each imported on two dates a day apart, same LCCN. 
https://openlibrary.org/authors/OL6758842A/Syaiful_Arif

**Comment by tfmorris** [comment]
Yes, I know -- and there are many other cases for other editions/authors. The example was meant to be illustrative, not exhaustive.

**Comment by LeadSongDog** [comment]
@tfmorris 
Could you please change the title of this issue to make it something more clearly actionable?

**Comment by seabelis** [comment]
LCCNs are not exclusive.

**Comment by hornc** [comment]
Three of the 4 items in this report were orphaned editions, and LCBot is no longer active, so there were probably multiple factors contributing to the data getting into this state in the first place. 

The editions are now associated with a single work, which is progress.

Recent import processes going via the API have matched and added new source records to a single https://openlibrary.org/books/OL24014674M/Gus_Dur_dan_ilmu_sosial_transformatif from the various duplicate LOC entries. Evidence: https://openlibrary.org/books/OL24014674M/Gus_Dur_dan_ilmu_sosial_transformatif?b=5&a=2&_compare=Compare&m=diff which I think shows imports now are doing the right thing.
