### ISSUE TITLE
Updating Open Library footer to be more comprehensive

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#908]
We have a lot of infogami pages which aren't discoverable on OL. A better footer (like airbnb) would be nice

Tagging this issue as WIP because it needs to be spec'd out before anyone works on it. It should likely have clear footer sections and hit topics like...

- about
- donating
- search types
- help
- apis

**Comment by mekarpeles** [comment]
The top level ones may be... 

*Browse*
- Books
- Authors
- Subjects
- [Advanced Search](https://openlibrary.org/advancedsearch)

*Learn More*
- About Us
- [Vision](https://openlibrary.org/about/vision)
- [Blog](http://blog.openlibrary.org)

*Help*
- [FAQs](https://openlibrary.org/help/faq)
- [Common Problems](https://openlibrary.org/help/faq/troubleshooting)

*Developers*
- [Bulk Data Dumps](https://openlibrary.org/developers/dumps)
- [APIs](https://openlibrary.org/developers/api)
- [Writing Bots](https://github.com/internetarchive/openlibrary/wiki/Writing-Bots)

*Contribute*
- Add a Book
- [Suggest Edits](https://openlibrary.org/help/faq/about#contribute)
- Donate

**Comment by tabshaikh** [comment]
![footer1](https://user-images.githubusercontent.com/31198893/40384317-cdc4bbbc-5e20-11e8-8852-e54807285a90.png)
![footer_with_logo_down](https://user-images.githubusercontent.com/31198893/40384320-ce3946d0-5e20-11e8-83cf-566cbf402011.png)
![footer_without_logo](https://user-images.githubusercontent.com/31198893/40384322-ce7d128e-5e20-11e8-8251-4bd624c9155d.png)

**Comment by tabshaikh** [comment]
Initial design ideas

**Comment by LeadSongDog** [comment]
Nice start. Some comments:

In either of those layouts the use of title case vice sentence case in the links is a source of confusion. When "Advanced Search" is linebroken it looks as if it were two links "Advanced" and "Search". Ditto for "Common Problems".  If the columns were narrower it could also become evident for "Bulk Data",  "Writing Bots", "Add a Book", "Suggest Edits". Better to switch the case.

The "About Open Library" title is redundant in all three layouts. 

It would be simpler to say "Open Library is building a wiki page for each book ever published." 

Rather than "Your use of the Open Library is subject to the Internet Archive's Terms of Use" perhaps just add "Terms of use" under "Learn more". (Tangential: OL needs to serve a copy of those terms for users without always-live access to IA.) 

To most of the world, "a 501(c)(3) non-profit" doesn't convey much meaning. Need to find better wording if this is needed at all.

**Comment by mekarpeles** [comment]
+1 on many of @LeadSongDog 's comments

Feedback from our community call:
1) Add back IA parthenon logo next to legal info? @hornc 
2) All items should fit on one line e.g. "Advanced Search" (using flexbox) @mekarpeles
3) No big OL logo (@bfalling  + @mekarpeles + @whatisgalen )
4) Improved header-to-item font-size ratio @cdrini -- use same font size w/ bold header evan @rchrd2 
5) Make the git rev hash less prominent @hornc 
6) Like: Link to twitter and github @mek
7) ~Add `gitter` link?~ Maybe we should hold off (because traffic may be too large)
8] Merge common problems + FAQs? rm "About Us"
9) Remove About Open Library *header* for bottom text

**Comment by mekarpeles** [comment]
@tabshaikh thanks so much for your work on this.

After interviewing a handful of people (@bfalling, @rchrd2, et al) it seems like we'll probably want to go with a hybrid of 2 and 3:

https://user-images.githubusercontent.com/31198893/40384320-ce3946d0-5e20-11e8-83cf-566cbf402011.png

https://user-images.githubusercontent.com/31198893/40384322-ce7d128e-5e20-11e8-8251-4bd624c9155d.png

i.e. the columns all on the same row by themselves, with no OL logo

**Comment by tabshaikh** [comment]
@mek @LeadSongDog Thanks for your inputs, will surely improve upon those aspects. Hoping to update the footer as soon as possible (this week only 🙂)

**Comment by tabshaikh** [comment]
@LeadSongDog then the legal data should not be included in the footer

**Comment by LeadSongDog** [comment]
I don't even see it in the footer on the archive.org mobile homepage. In fact, the only way I found the terms of use page was by getting the link from the OL desktop footer.  Something tells me that archive.org dropped the ball on this. Best to check with legal before completely removing it. A link in the footer (just as on GitHub) ought to be sufficient, but the target page really does belong on the same openlibrary.org server, even if it is cached from the one on archive.org.

**Comment by mekarpeles** [comment]
@tabshaikh any updates you'd like to share here?

**Comment by mekarpeles** [comment]
@tabshaikh a rough sketch might look something like:
http://archive.org/~mek/olfooter.html

(a) using flexbox + flex-wrap to make mobile responsive
(b) links in the same row
(c) bottom-most footer line w/ IA logo

**Comment by tabshaikh** [comment]
@mekarpeles Ya sure working on this
