### ISSUE TITLE
How can this book have been recently returned if it is deleted?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9082]
### Problem

This was seen April 13 at 8:55pm.

Is this a bug? or what might be causing this?

#### Evidence / Screenshot
| Image 1 | Image 2 | Image 3 |
|---------|---------|---------|
| ![image](https://github.com/internetarchive/openlibrary/assets/921217/03cce191-1ad8-4e82-bff6-6c74b059c7f5) | ![image](https://github.com/internetarchive/openlibrary/assets/921217/117d17a0-f5d6-4e78-80da-93073d427da8) | ![image](https://github.com/internetarchive/openlibrary/assets/921217/fdc8b107-c3db-4164-b925-92d286bf98be) |

#### Relevant URL(s)
https://openlibrary.org/books/OL15580410M/Cyber_China

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by mekarpeles** [comment]
There are cases where the lending statuses of items may change over time or IDs may become stale or out of sync between archive.org and openlibrary.org items. It's a matter of presentation and the fix would be to use the sync-ia button as an admin/librarian or to contact @seabelis
