### ISSUE TITLE
Cleanup use of `is_usergroup_member('/usergroup/librarians')`

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9087]
### Describe the problem that you'd like solved

We currently still use: `is_usergroup_member('/usergroup/librarians')` in a few places.
We should probably refactor them to use `is_librarian()` instead like we do in most places.

### Additional context

<img width="1171" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/94e93422-4737-4ce6-be5d-0d883ee413dc">

**Comment by QuantuM410** [comment]
Hey @RayBB! I can make a quick PR, can I get assigned

**Comment by QuantuM410** [comment]
@RayBB I am unable to test for the path /authors/merge (The librarian seems to have access to request to merge). I have tested for the path /admin/* and it seems to work the same. 
Also is there any way I can log somethin on execution of the python code in html files. I tried using print with flush=True and it seems to throw ```name Error```
Furthermore, I can also see the usage of a similar user-group of superlibrarians being used and maybe can be replaced with ```is_super_librarian()```

**Comment by RayBB** [comment]
@QuantuM410 something like http://localhost:8080/authors/merge?key=OL21093A&key=OL161167A&key=OL19677A&key=OL24638A&key=OL114411A&key=OL20585A&key=OL50694A&key=OL47908A&key=OL29586A&key=OL2688089A&key=OL29388A should work on localhost for you?

I think we can also replace the superlibrarians but lets start with just librarians to keep it easy to review.

**Comment by RayBB** [comment]
Reopening for https://github.com/internetarchive/openlibrary/pull/9334

(this is actually code I added around the same time the PR fixing this was made).
