### ISSUE TITLE
Author auto-complete can't find hyphenated names

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#909]
On a works page when editing the authors, I tried to use the string "James Crichton-Browne" which didn't match anything, even though "James Crichton Browne" matched the author entry with the hyphenated last name.

Autocomplete failures encourage editors to create duplicate records.

**Comment by LeadSongDog** [comment]
Is this the same root issue as #790

**Comment by tfmorris** [comment]
Seems likely. I'll update that one.
