### ISSUE TITLE
Remove version tags from docker compose files

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9092]
### Problem

[They haven't been needed](https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md) for a long time (since like 2019) and as of the latest docker I'm getting warnings they're depreciated.

Warnings when running `docker compose up`
```
WARN[0003] The "HOST" variable is not set. Defaulting to a blank string.
WARN[0003] /Users/ray/workspace/openlibrary/compose.yaml: `version` is obsolete
```

#### Evidence / Screenshot
<img width="1004" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/5fe98d9b-44f3-41e9-ab62-d4f83b963913">

#### Proposal & constraints

Simple as removing those lines. An easy first issue for someone :)

**Comment by BaasanbayarOverflow** [comment]
Hello, can I be assigned to this issue?

**Comment by qwernot** [comment]
Which composite allows me to install it foolishly with just one click

**Comment by qwernot** [comment]
Which compose.yml allows me to install it foolishly with just one click
