### ISSUE TITLE
`i18n` syntax appears on offline error page

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#9097]
### Problem

In the development version of the site, the OL [static offline page](https://github.com/internetarchive/openlibrary/blob/master/static/offline.html) currently shows the internationalization (`i18n`) syntax function to the user.

This is likely because the page is static HTML, and does not have access to the Python `gettext` function that the `$_(" ")` is supposed to call, so there is no need to use the syntax.

#### Evidence / Screenshot
<img width="908" alt="OL_OfflinePage" src="https://github.com/internetarchive/openlibrary/assets/140550988/861e6213-f8b7-4775-bc09-801d16587cbf">

#### Relevant URL(s)
- `i18n` docs: https://github.com/internetarchive/openlibrary/wiki#Internationalization

### Reproducing the bug

1. Go to any page on the Open Library site (dev version)
2. Turn off your wifi

* Expected behavior (as in live site):
<img width="709" alt="OL_ProdOfflinePage" src="https://github.com/internetarchive/openlibrary/assets/140550988/6ee311e5-f489-468f-b5b3-3d65789c5b1d">

* Actual behavior:
(see above)

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): 
- Environment (prod, dev, local): dev/local

#### Proposal & constraints

Very simple fix! Simply removing the `$_(" ")` and `$_(' ')` from the lines below should solve the problem!
https://github.com/internetarchive/openlibrary/blob/e8ea2bacc63f491e619747437bc9b91006a222e8/static/offline.html#L16-L19

#### Related files

[static/offline.html](https://github.com/internetarchive/openlibrary/blob/master/static/offline.html)
[static/status-500.html](https://github.com/internetarchive/openlibrary/blob/master/static/status-500.html) - likely rendering with the same issue

**Comment by rebecca-shoptaw** [comment]
I'd be happy to do a quick fix for this myself, or leave it for someone else as a good first issue!

**Comment by Tzinapapadopoulou** [comment]
Hello! I am a beginner and i would like to work on good first issues, so this issue is ideal for me! Can I work on it?

**Comment by rebecca-shoptaw** [comment]
Hi @Tzinapapadopoulou! Yes, this should be a great first issue. I'm not officially the lead for it, but I'll go ahead and assign you for now, and you're welcome to comment here or message me on Slack if you have any questions!
