### ISSUE TITLE
Add an identifier for OpenAlex

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9100]
### Describe the problem that you'd like solved

I'd like to add an identifier for OpenAlex

### Proposal & Constraints

Visit https://openlibrary.org/config/edition.yml?m=edit, then add
```
-   label: OpenAlex
    name: open_alex
    notes: e.g. https://openalex.org/W1502163132
    url: https://openalex.org/@@@
```

### Additional context

This is pursuant to #8623.

### Stakeholders

@mekarpeles

**Comment by mekarpeles** [comment]
https://openlibrary.org/config/edition.yml updated
