### ISSUE TITLE
Move `ajax-loader.gif` for better caching

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9104]
### Problem

This PR can't be worked on until the following is merged: 
#8930

Currently we have different loader files:
- `/static/images/ajax-loader.gif` used nowhere
- `static/css/ajax-loader.gif` used in two places. But the it is only gif in this folder.
  - `static/css/lib/slick-theme.css`
  - `static/css/components/tagging-menu.less`

What we should do is:
1. Move `static/css/ajax-loader.gif` -> `/static/images/ajax-loader.gif` (overwriting/deleting the image previously there)
2. Update all the references from to reflect this new move

Why?
When I was working on the service worker caching PR (#8930) I had to make a special case to cache this gif because it is in a weird place.

**Comment by Spedi** [comment]
Hi!
Once #8930 is merged, is there any chance that I can tackle this issue?

**Comment by RayBB** [comment]
@Spedi you can go ahead and work on it now.
Since the PR I wanted merged first is taking longer than expected I think it is fine to just do this and I'll have to update the other PR later. Good luck!

**Comment by Spedi** [comment]
I suppose I solved the issue but, even if I created a new branch, when I try to push the changes the PR contains the changes about Issue #9065 too. Do you have any idea on how to keep the two PR separated? 
I supposed creating a new branch would solve the problem, but maybe I'm doing something wrong.
Thank you for helping!

**Comment by RayBB** [comment]
@Spedi please branch off master. I'll resolve things with my other branch later.

**Comment by RayBB** [comment]
@mekarpeles need staff to merge this one.
