### ISSUE TITLE
Should default return type for is_loaned_out_on_ia should be False not None?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9118]
#### Evidence / Screenshot
https://github.com/internetarchive/openlibrary/blob/ce273d84cf14f66c5e07b081247a1c3c342666ff/openlibrary/core/lending.py#L564-L572

This code returns `None`.
I'm fairly certain we should not return `None`. Based on how it is used, it is evaluating to `False`. As in "false, the book isn't loaned out because there was an error". In my opinion, we should probably default to returning `True` instead.

I've gotten a bit stumped a few times trying to follow the code. However, at least the code path ending here with waitinglists seems like it would get an error from this logic.

https://github.com/internetarchive/openlibrary/blob/1f614a196ae0fdc63b28f47539c85f2a7a93971a/openlibrary/templates/admin/waitinglists.html#L34-L39

### Context

Found during #9117

**Comment by mekarpeles** [comment]
There's an open question about what to do when a title is not borrowable at all, which is probably what None was trying to communicate. True is actually misleading in this case, because it's not the case that the item is lent out, it's the case that the title is simply not borrowable and we don't want the UI to communicate that the title is checked out.

**Comment by RayBB** [comment]
@mekarpeles I see what you mean.

In that case I think the solution is one level up is to check if `is_loaned_out_on_ia is True`.
This way it when we return None `is_loaned_out` doesn't think it's available.

Should we make that change?

https://github.com/internetarchive/openlibrary/blob/ce273d84cf14f66c5e07b081247a1c3c342666ff/openlibrary/core/lending.py#L543-L556

**Comment by mekarpeles** [comment]
Yes I think that's reasonable

**Comment by RayBB** [comment]
@mekarpeles I made a PR for this here https://github.com/internetarchive/openlibrary/pull/9139

Though I'm not totally sure how to test it.
