### ISSUE TITLE
Fix service worker caching

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9119]
### Problem

Retrospective issue for #8930 

In short, caching isn't working well because we never cache covers images with service workers.
In fact, we have it set to explicitly never cache covers. It is very annoying on my slow mobile connection.

**Comment by tfmorris** [comment]
> It is very annoying on my slow mobile connection.

It's annoying on ALL connections! I have a 200 Mb/s connection and I still see all the little chiclets scattered across my screen get filled in slowly at a rate of a few per second, attempting to drag my attention away from the focus task to these completely irrelevant screen updates.
