### ISSUE TITLE
Record details different from actual linked edition.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#915]
This might be more of a question than an issue...
Sometimes the details on the Open Library page do not match the borrow-able copy; easily fixed. However what about the situation where the Internet Archive record itself is incorrect? I've reported this here and there, but not sure if I'm being more of a nuisance then helpful.

for example: https://archive.org/details/shakespearescom67shakgoog

**Comment by mekarpeles** [comment]
@seabelis this is a long standing problem! Our OpenLibrary entries and Archive.org items can have mismatching metadata. We should (on a monthly or ongoing basis) attempt to do a sync to make sure this data is the same. We have a few similar issues open (tagging as `sync-ia-ol`)

**Comment by hornc** [comment]
These look like a job for @JeffKaplan to correct the archive.org items?

**Comment by guyjeangilles** [comment]
@hornc Have we established the sync process? Assigning you per slack discussions

**Comment by hornc** [comment]
Reporting these in the OL channel for them to be dealt with by Jeff is the current standard process. I can help out if there are issues at scale that need an automated data fix.
