### ISSUE TITLE
Add `min` of 0 to page count to prevent going negative.

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9169]
### Problem

Right now you can set the page count for a book negative.
Pretty sure we don't want that. We can fix it server side but would also be nice to fix client side.

We can use the min attribute:
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/min

#### Evidence / Screenshot
<img width="609" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/8beb2b53-3c23-465d-8e5e-74693d8b2058">

#### Relevant URL(s)
https://openlibrary.org/books/OL51673915M/White_Hat_UX/edit

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by aarasawa** [comment]
Hi, can I work on this issue?

**Comment by Spedi** [comment]
Hi there @RayBB!
Is this issue still open, is there any chance that I can work on it?

**Comment by RayBB** [comment]
@IlyaMckay has opened a PR (#9193) for it. But for some reason I cannot assign it so I'll just remove the good first issue label for now.
