### ISSUE TITLE
profile editing failing for users

### ISSUE THREAD

**Issue by JeffKaplan** [internetarchive/openlibrary#917]
trying to change Display Name at https://openlibrary.org/people/XXX?m=edit and after clicking "Save" it returns "None"

**Comment by kellyhogan** [comment]
Hello, I can confirm this error for Google Chrome Version 65.0.3325.181 (Official Build) (64-bit). Whenever I try to edit my profile, it redirects me to a page with the text "None".

I wonder if this relates to the form in the template for [type/user/edit.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/edit.html).

**Comment by kellyhogan** [comment]
Updating Google Chrome to Version 66.0.3359.139 (Official Build) (64-bit) resolved this issue for me.

**Comment by Num170R** [comment]
Is this still an issue?

**Comment by mekarpeles** [comment]
I'm not positive how many users are being impacted by this, though it isn't a very common user action (we don't get many emails about the issue and @JeffKaplan generally helps when people do hit a roadblock).

It looks like the issue may be javascript related and tied to the browser. Maybe this is one we mark as "will not fix" and then re-open if people continue to have problems.

**Comment by LeadSongDog** [comment]
There's still an issue. Changing user's email or password requires access to archive.org, without which it cannot be changed.  (Group policies sometimes block archive.org as a gaming, porn, or warez site.) There is no hint to the user that this off-site access is happening, so the failure looks like something more sinister has happened.

**Comment by mekarpeles** [comment]
@leadsongdog this is a separate issue; changing password if IA blocked. Can you open a separate issue for this?

**Comment by mekarpeles** [comment]
@dcapillae reported this issue again #971  -- also, noted both this #917 and  #613 are all duplicates so I'm keeping this issue closed and making #613 the canonical issue.
