### ISSUE TITLE
Is openlibrary/templates/contact/spam/sent.html dead code?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9174]
### Problem

Best I can tell openlibrary/templates/contact/spam/sent.html is dead code, not used anywhere.
If it is then lets delete it. If it's not, we might want to add internationalization to it?

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by harsh-kumar-patwa** [comment]
Hey @mekarpeles,
I've noticed that the file openlibrary/templates/contact/spam/sent.html appears to be unused. I would like to investigate this further to confirm if it's indeed dead code and, if so, proceed with its removal. Alternatively, if it is being used, I can look into adding internationalization support for it.

Could you please assign this issue to me?
Thank you!
