### ISSUE TITLE
Don't list /preferences in recentchanges since they can't be viewed

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9197]
### Reproducing the bug

1. Go to https://openlibrary.org/recentchanges
2. Click on one of the many /preferences links

* Expected behavior: Shows something
* Actual behavior: Errors with a 401 unauthorized

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win10
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

**Comment by SivanC** [comment]
@cdrini Hi again, I'd be happy to work on this if it's a good fit! There's a bit of a disconnect between the expected behavior and issue title, I assume the implied solution is to filter out recent user preference changes and not to make them accessible, right?

**Comment by mekarpeles** [comment]
@SivanC sure! Thank you! And @jimchamp, @cdrini, and I can answer questions if you have any :)

**Comment by SivanC** [comment]
@mekarpeles @jimchamp @cdrini Sorry to ping you all couldn't decide :sweat_smile: Wondering how I can access user preferences on a dummy account so I can test properly? I managed to set up the account but just like admin I get a template error when trying to access settings.

**Comment by jimchamp** [comment]
http://localhost:8080/people/openlibrary/preferences will take you to the preferences of the default dev account, if logged in.  If you get a 404, just change your `safe_mode` setting and revisit the page (if I recall, the preferences object doesn't exist until the patron modifies their preferences).

**Comment by jimchamp** [comment]
> I assume the implied solution is to filter out recent user preference changes and not to make them accessible, right?

Sorry that we missed this question!  This is correct.  Let me know if you need any help finding the related code for this.

**Comment by SivanC** [comment]
@jimchamp Thanks for the support!
>  If you get a 404, just change your safe_mode setting and revisit the page

Changing my safe mode brings me to the "Sorry. There seems to be a problem with what you were just looking at." page, and I still get the below error when trying to access settings on the admin account:
`/openlibrary/openlibrary/templates/account.html: error in processing template: UndefinedTable: relation "follows" does not exist LINE 1: SELECT count(*) as count FROM follows WHERE publisher='openl... ^ (falling back to default template)`

Any idea what I'm doing wrong? I should mention I wasn't getting a 404 before but instead also this template error. When I was creating a dummy account I had to use a REPL inside one of the docker containers to talk to the site, maybe there's a way to activate preferences in there?
