### ISSUE TITLE
Add lazy loading for covers in works merge tool

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9201]
The works merge page currently loads all book cover images upfront, even those that are not immediately visible in the viewport. This causes unnecessary network requests and slower page load times.

### Describe the problem that you'd like solved

We need to implement lazy loading for book cover images on the works merge page to:
- Only load images when they come into the viewport
- Reduce initial page load time
- Decrease unnecessary network requests
- Improve overall performance

<details>
  <summary>Screenshot showing multiple image requests on page load</summary>
  
  ![image](https://github.com/internetarchive/openlibrary/assets/921217/40ef8f6f-2931-4d42-a0bb-d8b64bccc60f)
  
</details>

### Proposal & Constraints
There was a previous PR [here](https://github.com/internetarchive/openlibrary/pull/9312) that started this but wasn't finished.
If you'd like to work on this please review that PR and all the comments on it and incorporate the feedback.

To be assigned to his issue comment saying that you have read this PR and will incorporate that feedback into your own PR.

To test locally you'll need to add data by running something like
`docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py /works/OL21868175W /works/OL41495W"`

### Additional context

Example merge page showing the issue:
https://openlibrary.org/works/merge?records=OL21868175W,OL41495W

### Stakeholders

@cdrini

**Comment by Realmbird** [comment]
@RayBB can I work on this

**Comment by RayBB** [comment]
@Realmbird you are assigned now.

**Comment by Realmbird** [comment]
@RayBB recreated problem docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py /works/OL21868175W /works/OL41495W"
![Screenshot from 2024-05-21 12-33-11](https://github.com/internetarchive/openlibrary/assets/56459277/0bc08896-8834-4966-821e-5065ed77732b)

**Comment by chongthepro** [comment]
Hi @RayBB, can I take on this issue?

**Comment by RayBB** [comment]
@chongthepro please read the full issue and follow the instructions in it to be assigned.

**Comment by chongthepro** [comment]
Hi @RayBB, I have read the feedback in the previous PR and will incorporate it into mine.

**Comment by RayBB** [comment]
@chongthepro thanks! You're assigned. Good luck!
