### ISSUE TITLE
Remove .github/workflows/ruff.yml

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9230]
### Problem

I think we can remove `.github/workflows/ruff.yml` now that we have ruff running in pre-commit on each PR anyway.

Any reason to keep this around?

#### Evidence / Screenshot
<img width="1002" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/6521f00d-cc4d-469c-9796-b4214ee17a49">

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Related files

https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/ruff.yml

#### Stakeholders

CC: @scottbarnes

**Comment by RayBB** [comment]
@scottbarnes any opinions on this one?

**Comment by scottbarnes** [comment]
I just cloned from `git@github.com:internetarchive/openlibrary.git`, made a branch, made a change, and committed it, and `pre-commit` doesn't look to run by default, so I think if we remove this, then `ruff` will only run for people who use `pre-commit`, and that's not everyone, so we may end up more likely to commit code that won't pass the linting.

If that's correct, and that's a big if, then I think we should probably keep this workflow around.

**Comment by RayBB** [comment]
@scottbarnes I think you're talking about the pre-commit hooks running locally on your machine.
This file should not impact them because it is only used by GitHub Actions.
https://github.com/internetarchive/openlibrary/blob/master/.github/workflows/ruff.yml

However, we have a different github CI that runs pre-commit which in turn runs ruff for us and commits the results to the branch. So I think that this ruff workflow is no longer needed as a separate workflow.
