### ISSUE TITLE
Refactor Open Library to use checked in source for adding New Identifiers

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9234]
Currently, the way that new Identifiers are added to Open Library books and authors is through editing https://openlibrary.org/config/edition.yml?m=edit via the infogami database, which requires super librarian or admin permission.

This is blocking lots of new identifier types listed in #8271.

Ideally, we'd use /plugin/openlibrary/editions.page which can be edited by community pull request submissions.

# UPDATE:

https://github.com/internetarchive/openlibrary/blob/ec3e569b7e2e473f6a9d1bf339f3eab7ac890e0c/openlibrary/plugins/upstream/utils.py#L1206-L1220

- Open Library currently loads editions.yml in our app.
- We want to simply move the current `identifiers` out of infogami into a yml file in openlibrary repo
- When we load infogami editions.yml, we will add in the identifiers from the book-identifiers.yml
- restrict access of edition.yml to only be admins -- librarians will submit PRs moving forward in github

**Comment by Freso** [comment]
Maybe I’m reading https://github.com/internetarchive/openlibrary/pull/9483 wrong, but that seems to only deal with _edition_ identifiers, and not identifiers for authors and works? If so, https://github.com/internetarchive/openlibrary/pull/9483 only completes ⅓ of this issue and this should probably get reopened.

**Comment by Freso** [comment]
A big reason `works` IDs are not really being used, is probably that [there’s no UI for adding them](https://github.com/internetarchive/openlibrary/issues/3430), meaning that most librarians are not able to actually add them… :upside_down_face: It would probably be good to use the same approach for all three, IMHO.

**Comment by Freso** [comment]
Guess I need to tag someone for a reply to https://github.com/internetarchive/openlibrary/issues/9234#issuecomment-2269721158 so… @mekarpeles :)
