### ISSUE TITLE
Expand "-- Move to a new work" option to Open Librarians

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#9235]
### Problem

Librarians should be/are stated to be able to move misassigned editions to new works if necessary. However, in practice only Super Librarians can do this.

#### Evidence / Screenshot
From the edition page on the edit screen:
![image](https://github.com/internetarchive/openlibrary/assets/97799591/9d721e48-2097-4404-ac06-08cfbe4a7baf)

#### Relevant URL(s)
https://openlibrary.org/help/faq/editing#move-edition

### Reproducing the bug

1. Click "Edit" button while viewing a work or edition
2. Scroll down to "What work is this an edition of?" on the edition editing page
3. Attempt to locate "-- Move to a new work" by typing part of all of the phrase & scrolling through the menu that appears

* Expected behavior: "-- Move to a new work" is available on the menu.
* Actual behavior: It isn't unless you're a Super Librarian.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by seabelis** [comment]
This is fine to open to those with librarian privs.
