### ISSUE TITLE
Use new search bar template on other pages

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9236]
After #9146 is merged 

Followup from: https://github.com/internetarchive/openlibrary/issues/9086#issuecomment-2093369982

    the Author page (https://openlibrary.org/authors/OL107911A/George_Bernard_Shaw)
    the My Books Reading Log page (https://openlibrary.org/people/mekBot/books/want-to-read)
    the Subject page (e.g. https://openlibrary.org/subjects/biology)

**Comment by schu96** [comment]
Hi @RayBB I'd like to take on this issue, it looks like the subject page is the only one that needs updating from the list 
![image](https://github.com/user-attachments/assets/bb1e1a84-7e50-4588-9762-88b06444b101)
![image](https://github.com/user-attachments/assets/5c924c59-5ac7-4a12-a0bb-77288cc1e820)
![image](https://github.com/user-attachments/assets/7085cf05-7b71-4ec7-bbe9-52bc6cd7d7d3)

**Comment by RayBB** [comment]
@schu96 seems you're right. I've assigned you. Good luck!
