### ISSUE TITLE
Remove usages of missing icon_cancel.png

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9237]
### Problem

Edit page tries to load a `icon_cancel.png` that doesn't exist.
I don't know when we deleted it, probably long ago, but it doesn't do anything.
So lets remove references to it.

#### Evidence / Screenshot
<img width="1226" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/ec439d65-6e95-4dc6-b7b2-57ce7ad6142a">
<img width="1075" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/ac1c9f42-710a-47b2-8414-8b3bebadbd58">

#### Relevant URL(s)
- https://openlibrary.org/authors/OL5046634A/John_Green/edit

**Comment by Spedi** [comment]
Hi there! @RayBB
Can I work on this issue?

**Comment by RayBB** [comment]
@Spedi yes, you're assigned.

**Comment by mekarpeles** [comment]
Just keep in mind, some images may not have references in our code but could be used in /type/page infogami wiki records.
