### ISSUE TITLE
Standardize Book Page "Edit" btn style 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9238]
### Problem

When one first lands on the book page, the edit button looks like this, which has the classes/styles we want:
<img width="860" alt="Screenshot 2024-05-08 at 7 39 43 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/d5e71d14-9452-4bf6-a468-ef0c0a222e45">

But when we scroll down, the Edit button changes styles to have a thinner boarder. We want to keep similar classes / visual design in this view:
<img width="858" alt="Screenshot 2024-05-08 at 7 40 05 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/7ed948c1-9446-4870-9e21-565ef73f9e30">

This only applies to the Edit button when the button transitions into the navigation header bar, nothing needs to change about the "Last edited by" text, etc.

#### Relevant URL(s)

https://openlibrary.org/books/OL30162974M/A_Court_of_Mist_and_Fury

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by IlyaMckay** [comment]
I can make necessary changes. Please, assign me.

**Comment by mekarpeles** [comment]
Thank you @IlyaMckay!
