### ISSUE TITLE
Viewing previous version of deleted work gives error: Unable to render this page.

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#924]
Example:
https://openlibrary.org/works/OL10061856W?v=1

with debug:
https://openlibrary.org/works/OL10061856W?v=1&debug=true

**Comment by seabelis** [comment]
Getting the same error trying to view the current version...
https://openlibrary.org/books/OL24239956M/Harry_Potter_and_the_Sorcerer's_Stone

**Comment by guyjeangilles** [comment]
@hornc Are you talking about no editions being found? If not I propose closing.
![version_no-bug](https://user-images.githubusercontent.com/7256157/68096059-4492ac00-fea6-11e9-8f49-c66bde91be42.png)

@seabelis I'm not seeing any errors for the work you linked
![edition_no-bug](https://user-images.githubusercontent.com/7256157/68096072-596f3f80-fea6-11e9-8ffd-45815bb47f69.png)

**Comment by seabelis** [comment]
I'm no longer seeing errors there. Must have been resolved.
