### ISSUE TITLE
Investigate Accessibility of Carousels

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9240]
### Describe the problem that you'd like solved

We need someone with accessibility knowledge to evaluate if we want the carousel to have "An updated role of list & listitem for the carousel & its contents"

This is a followup from: https://github.com/internetarchive/openlibrary/pull/5151#issuecomment-2100515629

We will know this is done when someone familiar with accessibility tools has tested the carousels and issues have been made for any problems found.

**Comment by mekarpeles** [comment]
Unclear to me how we'll know when to close this.

**Comment by RayBB** [comment]
Based on some ancient feedback and not clear how to know when we're done. Closing for now.
