### ISSUE TITLE
Can we remove the "in English" link from the editions list on a work page?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9253]
Having the link that just goes to this page (https://openlibrary.org/languages/eng) and is not useful to patrons as far as I can tell.

- https://openlibrary.org/languages/eng
- https://openlibrary.org/works/OL16092157W/Hello_Android_introducing_Google%E2%80%99s_mobile_development_platform?edition=helloandroidintr00burn

### Describe the problem that you'd like solved

<img width="902" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/17fd6723-a01e-490c-8e2f-449e623a03d3">

### Proposal & Constraints

I think we should **convert it to plain text** instead of a hyperlink.

**Comment by stopregionblocking** [comment]
Doesn't this display for every language, not just english? Maybe there's a different function it could be changed to that would be beneficial across languages.

**Comment by RayBB** [comment]
@stopregionblocking it does show for every language. What function do you propose changing it to?

**Comment by mekarpeles** [comment]
I think we just want to remove the link around the language -- not the language text itself. This change seems fine (+1 @mekarpeles , @jimchamp , @scottbarnes )

**Comment by jainish2222** [comment]
Hello! Could I please work on this issue?

**Comment by RayBB** [comment]
@jainish2222 yes you're assigned. Good luck!

**Comment by hornc** [comment]
I don't see that this is a valuable feature. This is special casing English to be the only language that doesn't get a link. 
Searching for books by language doesn't have a great user flow - as far as I can tell the advanced search page doesn't support languages. Language faceting on the other hand seems a lot better, but that supports a slightly different use case.

Improving searching by language, or making the language pages more useful for specific tasks would be better features.

This will add complexity in a way that doesn't seem generlizable If the website is being viewed in German is it still only English that doesn't have a link?

I vote to close this as "not planned"

**Comment by cdrini** [comment]
Oh to clarify I think the proposal is to remove _e.g._ the "in English" link. So all the "in {language}" links on the editions table, not specifically the English ones!

**Comment by hornc** [comment]
Remove the links to all language pages, but keep the text there?  I don't see what that adds either. I guess that's why this is confusing. 

For the recent work I've been doing on language codes the main way to get to view what languages OL has is by clicking on one of those links and then going back a level to https://openlibrary.org/languages

Language is one of the formal OL types https://openlibrary.org/type/language , removing the link will hide the specific catalog code used e.g. `fre` for French, which might be useful information for a patron to know.  When other type objects are used on the UI, they are linked. Removing the link here would be inconsistent.

**Comment by cdrini** [comment]
The reasoning is I believe that clicking on e.g. "English" leads you to the somewhat empty https://openlibrary.org/languages/eng page. It's kind of a strange way to discover the `/languages` page as well. I wonder if we should add "Languages" to the Browse dropdown... A lot of people use Open Library to find books in a specific language! Note we do currently also link to `/languages` from `/subjects`

Note the current edition e.g. "English" link will still link to `/languages/eng` (here: 
![image](https://github.com/internetarchive/openlibrary/assets/6251786/55e3ffe3-0192-4ee1-8ef7-76385ed9cf81)
)

But we also don't link to the e.g. publisher page from the editions table (which is arguably a more useful page).

I think the ideal UX for me would probably be:

1. Clicking eg "in English" should _filter_ the editions table for other editions in English.
    * Likely blocked by #8751
3. There should be a "Browse > By Languages" option that goes to `/languages`
    * Likely blocked on a few pieces:
         * The /languages page should be cached, it's rather slow
         * Browse is getting a little long... maybe we can drop "Advanced Search" from here (depending on what analytics says) since we also link to it in the search dropper/search page.
         * We need to fix the bug with large search result set (eg `languages:eng`) causing solr to timeout.


I think until that larger plan, removing the links seems ok to me, and makes the editions table a little simpler (and also opens the path forward for us to change the behaviour of the link a little more cleanly to filtering the table). But would love to hear others' thoughts as well!

**Comment by poojatalele** [comment]
I would like to work on this issue, kindly assign

**Comment by RayBB** [comment]
@poojatalele you are assigned. Good luck!

**Comment by poojatalele** [comment]
I have made some changes in the code, but those are not reflecting on my local system. not able to to figure out why?! kindly help

**Comment by RayBB** [comment]
@poojatalele please share your changes and what you see

**Comment by poojatalele** [comment]
Hey @RayBB, Actually I have made changes in [openlibrary/templates/type/work/editions.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/work/editions.html)
I tried adding some debugging lines and some changes but nothing is getting reflected on localhost.

**Comment by charanbhatia** [comment]
@RayBB hi, i want to work on this issue

**Comment by AbhinavKRN** [comment]
@RayBB  can you assign this issue to me?

**Comment by AbhinavKRN** [comment]
@RayBB I can see this issue is assigned to someone a long time ago
i have understand this issue and i think i can solve, if possible do assign me !

**Comment by RayBB** [comment]
@charanbhatia please choose an issue that isn't assigned to someone [here](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+-linked%3Apr+label%3A%22Good+First+Issue%22+no%3Aassignee).

@poojatalele First, I'm not sure if that is the right file (it could be) but it might also be `/openlibrary/templates/books/edition-sort.html`. Can you also share exactly what you changed that isn't being reflected on localhost? The way I usually check if my change is reflected is by adding something like `<h1>test</h1>` to the area I'm expecting to change.

**Comment by poojatalele** [comment]
@RayBB 
<div class="format">
  
  
  $book.physical_format.replace('[', '').replace(']','')
  $if book.languages:
    
    $:_('in %(languagelist)s', languagelist=', '.join(l.name for l in book.languages))
  $if book.edition_name:
    - $book.edition_name
</div>
this is the change I made

**Comment by scottbarnes** [comment]
Hi, @poojatalele. Just to make sure it's clear what's going on, you are now able to see the changes you've made, correct?

I copy/pasted your change into `openlibrary/templates/books/edition-sort.html` and as far as I can tell, that resolves the issue.
![image](https://github.com/user-attachments/assets/0f64cb05-e78a-4d9b-a628-41a45792ac44)

Assuming you can indeed see the outcome of your changes when you view the page in the local development environment, please follow the directions in [Making Changes and Creating a Pull Request](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to submit your pull request.

However, if I have misunderstood and you still can't see your changes when viewing the editions table in the local development environment, please let me know and we'll get it sorted. :)

**Comment by poojatalele** [comment]
> Hi, @poojatalele. Just to make sure it's clear what's going on, you are now able to see the changes you've made, correct?
> 
> I copy/pasted your change into `openlibrary/templates/books/edition-sort.html` and as far as I can tell, that resolves the issue. ![image](https://private-user-images.githubusercontent.com/26524678/355174781-0f64cb05-e78a-4d9b-a628-41a45792ac44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4Nzk4MDcsIm5iZiI6MTcyMjg3OTUwNywicGF0aCI6Ii8yNjUyNDY3OC8zNTUxNzQ3ODEtMGY2NGNiMDUtZTc4YS00ZDliLWE2MjgtNDFhNDU3OTJhYzQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDE3MzgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZWM4OTc1NDNkMjAwZmZjN2I1NTY1Y2Y3NzdkNDBhZDFmZDhhZjA3ODcwNWJmMmQ3MTAwZDFjMTMyMWQ1MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IbOqlKNYhc0O9qho5frDfItdgqxZ0RSFNcrTPbqyw_I)
> 
> Assuming you can indeed see the outcome of your changes when you view the page in the local development environment, please follow the directions in [Making Changes and Creating a Pull Request](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to submit your pull request.
> 
> However, if I have misunderstood and you still can't see your changes when viewing the editions table in the local development environment, please let me know and we'll get it sorted. :)

I am now able to see the changes in my local development environment as well.
