### ISSUE TITLE
Remove iconochive

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9262]
We include a decent amount of iconochive CSS which we don't use ; we don't use iconochive anywhere. Let's delete it.

Files to delete:

- static/css/components/iconochive.less
- static/fonts/Iconochive-*

References to delete (delete just where iconochive is mentioned not the whole file):

- static/css/legacy.less
- static/css/less/font-families.less

Evaluation:

- Before doing the deletions, do a `make less` and then run `du -sh static/build/page-*.css`. Then do the deletions, run the two commands again, and compare the sizes!
- Also update bundlesize.config.json for the css files to be the new size +1 kb.

**Comment by danwoods** [comment]
I'd like to grab this ✋

**Comment by danwoods** [comment]
Playing with getting the repo setup and encountering the following issues after getting things running in Docker and building the assets (via `docker compose run --rm home npm run build-assets`):

Running `make less` from the top level directory returns `make: *** No rule to make target `less'.  Stop.`
Running `du -sh static/build/page-*.css` from the top level directory returns `du: static/build/page-*.css: No such file or directory`

**Comment by danwoods** [comment]
Thanks @scottbarnes! Will check this out 👍

**Comment by scottbarnes** [comment]
I don't know why I said using `docker compose run` probably wouldn't work, because I think it probably would. Either way one or both will. :)
