### ISSUE TITLE
Add simple `git` instructions to GitHub issue templates

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#9269]
### Describe the problem that you'd like solved

There's an ongoing background issue on OL where contributors often have trouble keeping their branches up to date, and run into merge conflicts and rebasing issues that require staff intervention. The idea we've settled on to help prevent this is to add clear and simple git instructions in a high-visibility place, i.e. at the end of the issue template. This way, contributors will be reminded to update their master branches before making a new branch for the PR, and to update their PR branch before making new changes to it.

### Proposal & Constraints

Ideally, this would involve adding a git section to the issue template (perhaps above "Stakeholders") -- "Working with Git"? -- that includes:
- Suggested branch name: (optionally filled out by issue's lead)
- Instructions re: how to keep master branch updated, i.e.:
```
git switch master
git pull upstream master
git push origin master
```
- Instructions re: what to do next if starting a new branch vs. updating an old one:
```
git switch -c name-of-new-branch
```
vs. 
```
git switch name-of-existing-branch
git rebase master
```
- Link to rebase section of [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) for troubleshooting and more info

### Additional context

**Note:** Just tagging everyone who was in the conversation about this, feel free to un-tag yourself if you don't want notifications. 🙂  

Also, this will obviously add some length to the template and be redundant for more experienced contributors, but hopefully the benefits of reduced merge conflicts/contributor confusion would be worth it. 

### Stakeholders

@mekarpeles @jimchamp @scottbarnes @merwhite11

**Comment by rebecca-shoptaw** [comment]
I wrote up what I feel is a solid draft for the changes while working on the issue write-up, so I'd be happy to submit a PR with the relevant updates!

**Comment by mekarpeles** [comment]
Thank you @rebecca-shoptaw that would be great! We may want to add it to both the feature request and bug github template (but maybe not the others) for now.

**Comment by merwhite11** [comment]
Here are some additional details (aka gotchas that got me) we could add in to the template--

**KEEPING YOUR MASTER & BRANCH UP TO DATE WITH UPSTREAM**
_**Repeat these from above BEFORE EACH time you start working on your branch**_
`git switch master
git pull upstream master
git push origin master
git switch name-of-existing-branch
git rebase master
`
**_Confirm that your master and branch are up to date on your GitHub fork. It your master and/or branch are behind upstream, see [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) for troubleshooting_**

**Master**
<img width="793" alt="Screenshot 2024-05-14 at 7 47 36 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/5dc2ea60-f889-43ec-a3cf-5d47d1f2ec34">

**Your Branch**
<img width="803" alt="Screenshot 2024-05-14 at 7 48 16 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/e38f2b4d-cd89-4adb-94ab-3b376faf1725">

**See [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) for Troubleshooting**
<img width="791" alt="Screenshot 2024-05-14 at 7 49 19 PM" src="https://github.com/internetarchive/openlibrary/assets/79802377/9b493500-7335-4a82-ad52-ad6b243556b2">

**Comment by tfmorris** [comment]
I recommend adding the `--ff-only` switch to the pull command to make sure that you're not accidentally getting merge commits on top of a commit to `master` in your fork. Preventing this upfront will save a lot of heartache later.

**Comment by RayBB** [comment]
@rebecca-shoptaw I know last week you were also doing quite a bit of work to update the git cheatsheet.
How would you (and others) feel about adding a link to the docs in the templates instead of adding full instructions into every feature/bug report? That also gives us an opportunity to write in more detail and easily update it later (if we add to the issue template and then want to change later all the current issues will remain unchanged).

I feel moderately in favor of linking instead of in-lining these docs. Mostly because I think having docs like this in one place is easier to navigate and maintain.

**Comment by rebecca-shoptaw** [comment]
@RayBB That solution is fine by me, but I would want to run it by @mekarpeles first, as I know he was in favor of the issue template approach. Maybe a combo of putting a reminder re: staying up to date plus a link here, and putting the full instructions in the "how to find a good first issue" instructions or somewhere else high-visibility?

**Comment by merwhite11** [comment]
@rebecca-shoptaw @RayBB I think linking to the docs in the issue template makes sense as long as it's very explicit --something like: "Follow this Git guide to create a branch and begin working on this issue."
