### ISSUE TITLE
Remove dates for books with ISBNs with publish date < 1400

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9270]
### Problem

Some books that have ISBN have very old dates that may suggest a metadata inaccuracy. We should try to find a heuristic to remove dates from items that are clearly wrong (e.g. the date `1` in this set seems suspect)

#### Relevant URL(s)

https://openlibrary.org/search?q=publish_year%3A%5B*+TO+1400%5D+AND+isbn%3A*
### Notes from this Issue's Lead

@judec and @hornc should have more details

#### Proposal & constraints

NB! Some works were published pre 1400s and then were re-published as modern editions with ISBN so we may want a way to address this.

**Comment by scottbarnes** [comment]
4619 editions with pre-1400 publication years that had their dates removed: 
[pre-1400-publish-year-with-publisher--date-popped.jsonl.gz](https://github.com/user-attachments/files/15598839/pre-1400-publish-year-with-publisher--date-popped.jsonl.gz).

The criteria used were a publication year < 1400 and the record had a publisher listed. However, no publisher existed then, so these editions likely have incorrect dates. 123 editions were identified as Arabic by having `/languages/ara` or by the `title` field had >= 50% off its characters identified as Arabic unicode. These should be examined to see if their dates were likely entered in the format of the Solar Hijri calendar.
[arabic_records.jsonl.gz](https://github.com/user-attachments/files/15598846/arabic_records.jsonl.gz)
