### ISSUE TITLE
Fix description of alternative names on author edit page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9272]
### Problem

Right now it says:

> Does this author go by any other names? For example: Lev Nikolayevich Tolstoy; Yasnaya Polyana

However, we now separate authors by newline. So if you submit them separated by `;` it doesn't work.

#### Evidence / Screenshot
<img width="357" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/cd8592d7-1ae4-462c-b15c-16d3a102d6d5">

#### Relevant URL(s)
https://openlibrary.org/authors/OL1460595A/Serge_Chermayeff/edit

#### Proposal & constraints

We should update the text to reflect the new way of doing things.

For example:

> Does this author go by any other names? For example: Lev Nikolayevich Tolstoy was also known as Leo Tolstoy. Please list one name per line.

**Comment by pradyutf** [comment]
Hi @RayBB 

As I am new to the project, this seems like a good first issue for me to get started with. I would like to work on this and will raise a PR soon to address it.

Could you please assign this issue to me?

Thank you!

**Comment by RayBB** [comment]
@pradyutf you're assigned now. Good luck!

**Comment by pradyutf** [comment]
Hi @RayBB,

I have raised PR #9687  to update the placeholder text as mentioned. Apologies for the delay in addressing this issue. Please review and let me know if this fixes the issue or if any further changes are needed.

Thank you!
