### ISSUE TITLE
Can we get rid of tabs on the author edit page?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9280]
### A clear and concise description of what you want to happen
I want to get rid of the "Links" tab (move the content on to the main tab)

Why?
Because it makes the author edit page jump around a bunch.
I don't think it really is all that useful to have it on a separate tab.
It will simplify our code.
Make one less dependency on the jquery tabs 

### Expected behaviour / screenshots (ex: Figma design screenshots for UI feature)
It'll be faster and simpler.

### Additional Context
Example of the slow jumping:
https://github.com/internetarchive/openlibrary/assets/921217/2dc9c90f-203f-4e04-89c1-1deafa8b40f3

### What is the proposed solution / implementation?
Move the links section down under the identifiers.
Remove the tabs stuff.
Will need to remove `tabsAddauthor` from index.js as well.

### Is there a precedent of this approach succeeding elsewhere?
No

**Comment by mekarpeles** [comment]
Merge 'em

**Comment by mekarpeles** [comment]
@RayBB I may have put the cart before the horse here re: good first issue, feel free to mark it as such if you think it is!

**Comment by RayBB** [comment]
Opened a PR here #9305
