### ISSUE TITLE
System fails to recognize authors by their full name in author search functionality

### ISSUE THREAD

**Issue by SkywalkerSupreme** [internetarchive/openlibrary#9293]
### Problem

![Screenshot from 2024-05-16 15-45-54](https://github.com/internetarchive/openlibrary/assets/141163236/adfd461b-c542-4d30-b778-5e71b29162b1)
![Screenshot from 2024-05-16 15-45-35](https://github.com/internetarchive/openlibrary/assets/141163236/2cb74b7b-ec7c-40ce-9ca9-fe166514238d)

### Reproducing the bug

1. Go to the author search functionality on the Open Library website.
2. Enter the full name of the author "Richard Russell Riordan Jr." in the search bar.
3. Observe the system's response, which should include retrieving the author's biography.
4. Note that the system fails to recognize the author based on their full name and does not retrieve the expected information.
5. Enter only the first and last name of the author, "Richard Riordan," in the search bar.
6. Observe the system's response and confirm that it recognizes the author and retrieves the expected information.

**Expected Behavior:** The system should be able to recognize authors by their full name.

**Actual Behavior**: When inputting the full name "Richard Russell Riordan Jr." into the author search functionality, the system fails to recognize the author. However, the system correctly identifies the author when only their first and last name, "Richard Riordan," are provided. 

### Context

During testing of the author search functionality, an issue arose when assessing whether the system could recognize an author by their full name, rather than just their first and last name. Typically, the author "Richard Riordan" is recognized by the system. However, when inputting the full name "Richard Russell Riordan Jr.," expecting the system to retrieve the author's biography, an error occurred. The system failed to identify the author based on their full name.

**Comment by cdrini** [comment]
Added the alternate name, and it's now appearing in search ! https://openlibrary.org/search/authors?q=Richard+Russell+Riordan+Jr.&mode=everything
