### ISSUE TITLE
Can't borrow or remove author-less, title-less edtions from waiting list.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#930]
Borrow failed (already checked out). When I try to leave waiting list I'm redirected to page with the word "None".
 ![fullscreen capture 4132018 61139 pm bmp](https://user-images.githubusercontent.com/17739465/38745996-89666a72-3f46-11e8-8b05-f32428511565.jpg)

[It's this book](https://openlibrary.org/books/OL383855M/Harry_Potter_and_the_Chamber_of_Secrets).

**Comment by guyjeangilles** [comment]
@seabelis the book you linked has proper data now. I can't seem to find one with an unknown author. Is this still an issue?

On a tagential note. There is an author in the database, [Unknown](https://openlibrary.org/authors/OL2624611A/Unknown), with 3,224 works...making an issue

**Comment by seabelis** [comment]
This was a while back and I don't think I've encountered the issue since, so it can be closed for now and reopened if necessary.
