### ISSUE TITLE
Grafana IPs/bots/httpcodes missing some stats from May 4th on

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9300]
### Problem

It looks as if around May 4th some of the Grafana dashboards stopped recording data (e.g. Bot/Crawler Traffic, HTTP Status Codes, and several others).

#### Stakeholders

@cdrini

**Comment by cdrini** [comment]
Manually kicked off those scripts. The real fix will be to get #8795 fixed so we can merge it; then they will run automatically. But this is ok for now.
