### ISSUE TITLE
Add language to edition edit form: Swiss German

### ISSUE THREAD

**Issue by bilch** [internetarchive/openlibrary#9308]
### A clear and concise description of what you want to happen

Swiss German should be an option in the language autocomplete of the edition edit form.

### Additional Context

Here's an example where it's needed: https://openlibrary.org/works/OL19951728W exists as a Swiss German original (currently, and incorrectly, labeled "German"), a German translation (currently labeled "German", too) and a Scots translation (labeled "Scots").

Swiss German has a language code here https://www.loc.gov/marc/languages/language_code.html (it's "gsw")

### Stakeholders

@seabelis

**Comment by stopregionblocking** [comment]
Other missing languages are listed in #8127.

**Comment by hornc** [comment]
@bilch I believe this is fixed now
![image](https://github.com/internetarchive/openlibrary/assets/905545/1e23fd06-9825-41aa-a497-c574b33cd1d1)


from editing the item:
https://openlibrary.org/works/OL26453521W/Am_F%C3%A4%C3%A4hryscht%C3%A4%C3%A4g?edition=key%3A/books/OL35740440M

and language page here:
https://openlibrary.org/languages/gsw

Can you confirm whether everything looks correct to you?
I think the incorrect lang code is on this book: https://openlibrary.org/books/OL27132047M/Der_Goalie_bin_ig
I haven't corrected it yet (I'll let you confirm), but it looks like Swiss German is available in the drop down now.

**Comment by bilch** [comment]
Yes! Thank you!
