### ISSUE TITLE
joining waitlist shows erroneous position; off-by-1

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#931]
I think it's counting off-by-1 (e.g. saying you are #4 of 3 people waiting)

**Comment by mekarpeles** [comment]
I think this is just archive.org's ElasticSearch being a bit behind

**Comment by LeadSongDog** [comment]
Shouldn't https://github.com/internetarchive/openlibrary/blob/300aa6098890c938e9243efa81cb59693ce06c8b/openlibrary/macros/LoanStatus.html#L58 
be testing for zeroeth position on the waiting list rather than first?

**Comment by mekarpeles** [comment]
I think @LeadSongDog may be right about this (though I think several things may be broken here).

**Comment by guyjeangilles** [comment]
Labeling this as backlogged since there's been no updates since May. @mekarpeles @LeadSongDog @tabshaikh Does there need to be more investigation into what is the cause of this issue?

**Comment by mekarpeles** [comment]
Not sure this is a problem anymore now that info coming from loans API
