### ISSUE TITLE
Are we actually using http2 http/2 h2?

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9314]
### Problem

Are we actually using http/2 (h2)?

It seems to me that we are not but I found a PR that says we did enable it a while back.

At the very least, Firefox seems to be making the requests with http/1.1. Chrome on the other hand seems to be making them with h2. Well Chrome actually says `'Chrome' used a 'HTTP/3* connection induced by an ''Alt-Svc"' header without racing against establishing a connection using a different 'HTTP' version.`

Perhaps this is just a weird quirk where firefox is showing misleading info? But I do feel like firefox is significantly slower than chrome for first page loads.

However, as I was reading about the benefits of http2 recently it made me wonder if we are really getting them.

I'm not sure how all this works but could it have to do with the haproxy config?
Right now we have something like
```
frontend ol-web-app-in
    bind *:7072
    mode    http
```
We (according to my research) probably want something like:
```
frontend ol-web-app-in
    bind *:7072 ssl crt /path/to/your/certificate.pem alpn h2,http/1.1
    mode    http
```

Related docs:
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/load-balancing/http/

#### Evidence / Screenshot
Comparing OL vs MDN with http protocol in FF.
<img width="1512" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/a2cbc47a-ba23-47c6-ac2c-ff4fb2f9b864">

#### Relevant URL(s)
Original PR to enable it: https://github.com/internetarchive/openlibrary/issues/5418

#### Stakeholders

@cdrini who was talking to me about haproxy recently.
@jimchamp who created the original issue

**Comment by cdrini** [comment]
It should be ; I've found resources cached in the service worker incorrectly appear as http/1 in FF's networks panel ; if I do a fresh load in incognito it shows things as http/2. 
![image](https://github.com/internetarchive/openlibrary/assets/6251786/e1f1efc9-fc96-4367-a68a-4f6b5117a45a)

**Comment by RayBB** [comment]
Seems you're right thanks for clearing that up.

More info here
https://stackoverflow.com/questions/54513933/requests-served-from-serviceworker-are-downgraded-from-http-2-to-http-1-1
