### ISSUE TITLE
Remove jquery-validate from the critical path of JS

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9319]
### Problem

We could remove 7.51KB gzipped (124.38KB -> 116.87KB) on the critical path of all.js by only loading jquery-validate when needed (on pages with a html element with the class "validate").

Validate is only needed on pages where there are user inputs like editing/registration/etc.

**Comment by rebecca-shoptaw** [comment]
Big +1! I've even recently removed `validate` from registration, and I have the sense that perhaps before long we can start replacing the plugin other places, definitely no need for it to be loaded everywhere

**Comment by mekarpeles** [comment]
Let's add google page insights before/after to see how it goes!
