### ISSUE TITLE
Save button should be disabled on click

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#934]
I accidentally clicked the Save button a second time and created two identical edits here:

https://openlibrary.org/books/OL9286034M/A_First_Course_in_Database_Systems_(2nd_Edition)?m=history

The Save button should be disabled as soon as it's clicked and the update is submitted.

**Comment by Num170R** [comment]
I'd like to take a chance on this.

**Comment by tabshaikh** [comment]
@Num170R I looked into this issue you may not able to reproduce it but still after pressing the button once it should just be disabled 🙂
