### ISSUE TITLE
Accessing the site doesn't work 503 Service Unavailable error

### ISSUE THREAD

**Issue by GoWithTheFlow12** [internetarchive/openlibrary#9345]
#### Relevant URL(s)
When I access the website it loads very slow, and when it loads I have this error:
503 Service Unavailable
No server is available to handle this request. 
![image](https://github.com/internetarchive/openlibrary/assets/170943084/3b090e0f-2a3a-4c3d-bc40-9e9e2873162c)

### Reproducing the bug

1. Go to ...https://openlibrary.org
2. Do ...just wait for the page to load, it does not load

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc): tested on chrome and mozzila
- OS (Windows, Mac, etc): Windows
- Logged in (Y/N): I was logged in when the error occured, then I tested in other browser where I was not logged in and it didn't worked as well
- Environment (prod, dev, local): prod

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
Unfortunately archive.org is experiencing a DDOS attach; you can monitor the state here: https://x.com/internetarchive/status/1795117949499445554?t=zqku2Aj-neWfjdCruTvCgw

**Comment by vladimircicovic** [comment]
Hi people, 
This is CC attack. Could I help with this? 
Please provide me contact person - so I can share ways to stop this kind of attack 

I did have the same attack, then I investigated how to stop it - I also tested against the tools they are using. 

Most of IP are proxy servers and you have full log of this:
"GET /?search=AiMEppijD" 

So when you get this msg - contact me I am willing to help ASAP providing a script to "patch" against this attack.

**Comment by cdrini** [comment]
The problem has been resolved! Thanks for the offer @vladimircicovic ! We have staff who help resolve issues like these, but I'll forward your message along :+1:

**Comment by cdrini** [comment]
Hi @vladimircicovic thanks for the help! Yeah there's another event occurring now: Updates here https://x.com/internetarchive/status/1795451463465845141?s=46&t=zqku2Aj-neWfjdCruTvCgw

**Comment by mekarpeles** [comment]
@vladimircicovic thank you very much for sharing your insights and helping us. It's greatly appreciated. Would you be open to an invite to our internetarchive / openlibrary slack in case we have followup questions? Thank you again 

cc: @bfalling, closing this issue for now and

**Comment by bfalling** [comment]
@vladimircicovic: One option our security team is considering would be a synproxy recipe for linux ipvs in Direct Response mode, if we can find one. Is this something you would know about?

**Comment by vladimircicovic** [comment]
> @vladimircicovic: One option our security team is considering would be a synproxy recipe for linux ipvs in Direct Routing mode, if we can find one. Is this something you would know about?

Let us connect on Slack and I will share information with the team
