### ISSUE TITLE
Having  cors issue using partner api to use get request in local host, "http://openlibrary.org/api/volumes/brief/isbn/0596156715.json

### ISSUE THREAD

**Issue by RBRNFRVR** [internetarchive/openlibrary#9349]
<img width="589" alt="Screenshot 2024-05-28 at 1 43 25 AM" src="https://github.com/internetarchive/openlibrary/assets/33600829/00bea2b2-7edb-4637-a017-d5c511a16ac6">

issue only occurs in my local host, not when you google the URL or even when you use postman, any suggestions  would be really nice, I primarily am hoping to focus on using ISBN to search for information on books such as covers, author and any other related information.

**Comment by cdrini** [comment]
I'd recommend using this endpoint:

http://openlibrary.org/search.json?q=isbn:0596156715&fields=key,author_key,author_name,editions,editions.isbn,title,subtitle,editions.language,editions.title,editions.subtitle,edition_count

**Comment by RBRNFRVR** [comment]
> I'd recommend using this endpoint. This endpoint is more actively maintained. Apologies for the docs, I know they show examples of the volumes API first!
> 
> http://openlibrary.org/search.json?q=isbn:0596156715&fields=key,author_key,author_name,editions,editions.isbn,title,subtitle,editions.language,editions.title,editions.subtitle,edition_count

my only issue with this step is that I don't get the cover for said book look up but this way, any idea one what I can use instead or do I need to make two calls? @cdrini

**Comment by mekarpeles** [comment]
@RBRNFRVR see https://openlibrary.org/dev/docs/api/search

Section: **Using Thing IDs to get Images**

> You can use the olid (Open Library ID) for authors and books to fetch covers by olid https://covers.openlibrary.org/a/olid/{id}-M.jpg, e.g.:
- for author `OL23919A`: https://covers.openlibrary.org/a/olid/OL23919A-M.jpg
- for edition `OL24194264M`: https://covers.openlibrary.org/b/olid/OL24194264M-M.jpg

**Comment by cdrini** [comment]
Oh you can add `editions.cover_i` to get the cover of the matching edition! No second request needed :) 

http://openlibrary.org/search.json?q=isbn:0596156715&fields=key,author_key,author_name,editions,editions.isbn,title,subtitle,editions.language,editions.title,editions.subtitle,edition_count,editions.cover_i

**Comment by RBRNFRVR** [comment]
@cdrini i get a number for the cover not an actual URL for the cover image. "cover_i": 8619368 while in the original endpoint on postman I get access to "items": [
        {
            "enumcron": false,
            "match": "similar",
            "status": "full access",
            "fromRecord": "/books/OL24194264M",
            "ol-edition-id": "OL25379845M",
            "ol-work-id": "OL15058799W",
            "publishDate": "2012",
            "contributor": "",
            "itemURL": "http://www.archive.org/stream/ArtOfCommunitySecondEdition",
            "cover": {
                "small": "https://covers.openlibrary.org/b/id/7151878-S.jpg",
                "medium": "https://covers.openlibrary.org/b/id/7151878-M.jpg",
                "large": "https://covers.openlibrary.org/b/id/7151878-L.jpg"
            }
        } multiple sizes of the cover in jpg format

**Comment by RBRNFRVR** [comment]
i would like to access the cover images as well

**Comment by cdrini** [comment]
That number is the cover id; you can construct the cover image URL like so: 

`https://covers.openlibrary.org/b/id/{cover_id}-M.jpg`

Eg https://covers.openlibrary.org/b/id/14315081-M.jpg

See https://openlibrary.org/dev/docs/api/covers for more details
