### ISSUE TITLE
Add the Swedish library classification system (SAB) to classification options

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#9354]
### A clear and concise description of what you want to happen

Living in Sweden, I both borrow library books and otherwise come across former library books as well as search the library database for books (and other media), which means I get exposed to the [Swedish library classification (SAB) system](https://en.wikipedia.org/wiki/Swedish_library_classification_system) a bunch. I would love to be able to record these classifications in Open Library next to Dewey (DDS) et al.

### Expected behaviour / screenshots (ex: Figma design screenshots for UI feature)

![add Swedish library classification to the list of classifications](https://github.com/internetarchive/openlibrary/assets/177659/108fea70-f73d-4db9-8c17-e4d073344a21)

### Additional Context

The Swedish libraries as a whole decided to move from SAB to DDS a couple of years ago, but many (most?) non‐academic libraries are still using SAB. SAB will also still linger for a good while to come even after all libraries have transitioned, on used/discarded books and possibly even on shelved books. Open Library could potentially become a good future resource to compare SAB assignments with DDS ones.

### What is the proposed solution / implementation?

Add something like
```yaml
-   label: Swedish library classification (SAB)
    name: swedish_library_classification_system
    notes: ''
```
to https://openlibrary.org/config/edition.yml

### Is there a precedent of this approach succeeding elsewhere?

Elsewhere as in outside of Open Library? Or do all the classifications already in https://openlibrary.org/config/edition.yml  count? :)

### Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

This is not a code change. An OL admin needs to edit the infogami.

### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by mekarpeles** [comment]
https://openlibrary.org/config/edition.yml
