### ISSUE TITLE
Add Follow buttons to Patron Profile pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9358]
Currently, the patron profile page at https://openlibrary.org/people/ScarTissue has to follow button
<img width="820" alt="Screenshot 2024-05-29 at 8 32 17 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/47c2f119-ff20-499a-8063-c9a31dc61eeb">

But the My Books page at https://openlibrary.org/people/ScarTissue/books does <img width="815" alt="Screenshot 2024-05-29 at 8 33 15 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/cc505767-8259-49a4-90f6-1340f364108d">

In templates/account/view.html, you can see that the Follow button widget is rendered at https://github.com/internetarchive/openlibrary/blob/5d7898642014de55abd84f8b107f3dbf225dfb3f/openlibrary/templates/account/view.html#L39-L40 when the patron's account is `public`.

The issue requires you to add a Follow macro to the patron's profile page at https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/view.html

You will not have th e`mb` (my books) object available to you and so you will have to calculate
 
1. Whether the patron's account is public or private -- if it's private, don't render the widget!
2. Whether this profile page is the current visitor's profile page -- if so, don't render the widget!
3. Whether the visitor is subscribed or not to this patron

Most of this information is already accessible from the profile page:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/user/view.html#L5-L6

This code block shows how you might determine if this page is the patron's page and whether the visitor is subscribed to this patron:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/mybooks.py#L442-L447

**Comment by pidgezero-one** [comment]
Hello! Mind if I take this one on?

**Comment by pidgezero-one** [comment]
One small question, where should the Follow button in this template be placed? I was thinking either immediately below the user's name or next to where the "Edit" button is in the screenshot?
