### ISSUE TITLE
Include "cover service" vagrant

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#936]
We have the ability to run a dev openlibrary cover service (so we can test with working covers) by running:

`./scripts/coverstore-server conf/coverstore.yml 8080`

We may have to edit our nginx config, configure our openlibrary.yml etc in order to get the openlibrary service + dev cover service speaking with each other correctly.

**Comment by jdlrobson** [comment]
Vagrant is no more \o/. Closing, but please open if I've missed something here that needs to be fixed.
