### ISSUE TITLE
Existing `/collections` pages returning `404`s

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#9364]
### Problem

Many existing `/collections` pages are failing to load properly.  When such a failure occurs, we see a `404` page with the body:
`/install does not exist.`

#### Relevant URL(s)
https://openlibrary.org/collections

### Reproducing the bug

1. Go to openlibrary.org/collections
2. Do wait until the page loads

* Expected behavior: You see the main "Collections" page
* Actual behavior: You see a `404` page

### Context

- Browser (Chrome, Safari, Firefox, etc): Any
- OS (Windows, Mac, etc): All
- Logged in (Y/N): N
- Environment (prod, dev, local): prod

#### Proposal & constraints

This is likely an issue with the new `CacheablePathsProcessor`, and the way that `/type/i18n_page` pages are resolved.

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
Here's a dashboard we can use to monitor progress: https://sentry.archive.org/organizations/ia-ux/performance/summary/?environment=production&project=7&query=transaction.duration%3A%3C15m+http.url%3Ahttps%3A%2F%2Fopenlibrary.org%2Fcollections%2F%2A+http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=30d&transaction=%3Cother%3E&unselectedSeries=p100%28%29

![image](https://github.com/internetarchive/openlibrary/assets/6251786/bebb6ea1-daab-4639-a4a9-b239b1d8bb36)

Again correlated with deploy

**Comment by cdrini** [comment]
Dropping to P1 since @jimchamp 's hotfix PR is patch deployed :+1:
