### ISSUE TITLE
`/usergroup`, `/collections` isn't loading on production

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9371]
Related: #9364 (possibly related)

#### Relevant URL(s)
Visit https://openlibrary.org/usergroup/, and get:
```
504 Gateway Time-out
nginx/1.18.0 (Ubuntu)
```
### Reproducing the bug

1. Go to https://openlibrary.org/usergroup/

* Expected behavior: the page loads and displays the user groups.
* Actual behavior: the page does not load.

### Context

- Environment (prod, dev, local): prod

#### Related files

@jimchamp notes this may be relate to https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/PageList.html.

#### Stakeholders

@jimchamp 
@seabelis 

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
^ Seems near perfectly correlated with our last deploy: https://sentry.archive.org/organizations/ia-ux/performance/summary/?display=duration&end=2024-05-26T11%3A40%3A16&environment=production&project=7&query=transaction.duration%3A%3C15m+http.url%3Ahttps%3A%2F%2Fopenlibrary.org%2Fcollections+http.method%3AGET&referrer=performance-transaction-summary&start=2024-05-21T14%3A05%3A48&transaction=%3Cother%3E&unselectedSeries=p100%28%29

**Comment by cdrini** [comment]
Might be worth looking through the release to see if anything there looks suspect https://github.com/internetarchive/openlibrary/releases/tag/deploy-2024-05-23

**Comment by cdrini** [comment]
Also I'm less convinced now that this is related to @scottbarnes ' ILIKE changes in https://github.com/internetarchive/infogami/pull/217, since this works fine/quickly: http://openlibrary.org/query.json?type=/type/page&key~=/collections/*&limit=500

**Comment by cdrini** [comment]
This page can be used for testing now; @jimchamp hard-coded the collection page list in the mean time :+1: https://openlibrary.org/collections.en?v=28

**Comment by mekarpeles** [comment]
Should be closed by: https://github.com/internetarchive/infogami/pull/221
