### ISSUE TITLE
My Books: My Lists showcase breaking

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9380]
### Problem
This may be a case only when a list has no items (e.g. testing)

https://testing.openlibrary.org/people/ScarTissue/lists/OL229781L/Test_2023_d

<img width="986" alt="Screenshot 2024-06-03 at 12 40 19 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/a906c06a-e66e-424c-91c8-b9903d4147f0">

<img width="614" alt="Screenshot 2024-06-03 at 12 39 15 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/43af7307-24f7-4da8-ba55-854790a6b15e">

<img width="662" alt="Screenshot 2024-06-03 at 12 39 00 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/00666bc7-3d7c-49de-9091-0c2cf727d64f">

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by benbdeitch** [comment]
This issue seems to be based off of my work, so I'd love to have the chance to fix it. Mind assigning me to the task?

**Comment by cdrini** [comment]
Awesome, thanks @benbdeitch !
