### ISSUE TITLE
Weird issue template text

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#9394]
### Problem

Recently boilerplate text which appears to be intended for the PR template has started showing up at the bottom of issues

#### Evidence / Screenshot
![Screenshot 2024-06-05 at 12 52 54 PM](https://github.com/internetarchive/openlibrary/assets/82178/e293cac0-5079-4e23-ba95-785a1e88f4ad)

#### Relevant URL(s)
https://github.com/internetarchive/openlibrary/issues/9390

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
Developer tips are in the developer docs or PR template

* Actual behavior:
Issue template, which is intended for end users, contains irrelevant developer information.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by mekarpeles** [comment]
@tfmorris thank you -- this was an intentional choice that came out of a community call because leads were finding that frequently new contributors were not pulling code before starting to take an issue. It is meant to be instruction for the person who claims the issue so they don't end up with messy rebases. I think, if that answers your question, we may be able to close this issue? Noting that some may find this change strange or undesirable

**Comment by tfmorris** [comment]
Since these directions are specific to novice/junior coders and not any other kind of contributor, it seems like the trick is to find a place where those people see them, but they won't distract others (like they just did me -- again).

Some possibilities which come to mind:
- the instructions for new contributors
- the instructions on how to set up a development environment
- the instructions on how to get assigned an issue to work on (where they have to promise that they've read & followed the directions before getting assigned the issue)
- instructions on how to create your first pull request
- the pull request template
- probably a few others...

If they create a pull request that doesn't follow the instructions, the reviewer is not, to my mind, obligated to handhold them through fixing things -- and, the people who ignore the existing instructions aren't the ones who are going to read an additional line the bottom of an issue template.

This is also one more piece of irrelevant clutter in an already VERY cluttered issue template.

But of course you can close it, as you can any other issue.

**Comment by mekarpeles** [comment]
Will raise during next community call for discussion

**Comment by rebecca-shoptaw** [comment]
Completed by #9437.
