### ISSUE TITLE
List search should return partial matches

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#9416]
### Problem

Dear developers,
Can you please make book list search return partial matches?

Currently, book list search only returns lists whose names only include the exact words in the query, and not a word more.
Example:https://openlibrary.org/search/lists?q=books&mode=ebooks&has_fulltext=true

![20240609_141410](https://github.com/internetarchive/openlibrary/assets/19307323/197aecd8-7b9c-4231-8e2f-ed430c3c648e)

Can this please be fixed?
Thank you for looking into this.

### Is there a precedent of this approach succeeding elsewhere?
Pretty much everywhere else. A search engine only returning exact matches by default is certainly an outlier.

### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
Hi @el4ctr0n , thank you for creating an issue! We already have an issue tracking this one; I've added you as a stakeholder there :+1:

* #2723
