### ISSUE TITLE
User contributed data being overwritten by imports

### ISSUE THREAD

**Issue by agmckee** [internetarchive/openlibrary#9425]
### Problem

I noticed that a very well known book from a popular series has a nonsense "first published date" and tracked it down to a specific edition. Lisa previously manually corrected the issue in 2020 but the import bot has overwritten her change. It seems really, really inadvisable that the import bot is allowed to overwrite data provided by human contributors.

#### Evidence / Screenshot

![image](https://github.com/internetarchive/openlibrary/assets/722096/42d7c92c-5fe8-4a41-af7f-9700dceb4ddf)

![image](https://github.com/internetarchive/openlibrary/assets/722096/0ee27aff-6b72-43fe-b623-5db72a7eb00f)

#### Relevant URL(s)

https://openlibrary.org/books/OL11043844M/Harry_Potter_et_la_Coupe_de_Feu?b=11&a=10&_compare=Compare&m=diff

### Reproducing the bug

1. Go to https://openlibrary.org/works/OL82560W/Harry_Potter_and_the_Goblet_of_Fire?mode=all
2. Observe that there's a record for the edition with the ISBN 9780785998334 that states a false publication date. The bad data seems to be coming from Amazon. It cannot have been published at this date as the book wasn't even written yet.
3. This data seems to have been imported and overwritten a change by a human editor/contributor.
4. I would expect that if a real person has previously removed erroneous data, the bot should not reimport that same data again.

### Context

This isn't a bug with the frontend but instead an undesirable behaviour from the import bot.

#### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by hornc** [comment]
The issue says "user contributed data" is being overwritten, but the example shows an empty field being (re)populated, which is how the system is designed.

An import would not overwrite a pre-existing date (regardless of how correct it was), which is the current way to ensure user contributed data is respected.

The unrealistic date is coming from Amazon. 1993 seems to be associated with the Publisher, but Amazon has it in the publication date field too, so it's not OL misinterpreting the source. The source is wrong.

To prevent arbitrary dates being written to this item the correct date needs to be added. It's possible some version of `unknown` in the field would also stop the overwriting, but that's probably bad for other reasons. I don't know if there is a good value to use. The real date for the item is the most correct resolution.

**after a quick search:**
The ISBN, publisher, and page count (2112!) also appear incorrect on this item, these all belong to a dictionary from 1993:
http://www.google.com/books/edition/Grand_Dictionnaire_Francais_Anglais_Angl/tnZWAAAACAAJ

[French & European Pubns](https://openlibrary.org/publishers/French_&_European_Pubns) did not publish this mp3 audio book at all, and it does not have 2112 pages.

The correct publisher is Gallimard Jeunesse, and this looks like the item (same narrator):

https://www.gallimard-jeunesse.fr/9782075105118/harry-potter-et-la-coupe-de-feu.html 

published 2018, ISBN: 9782075105118

**Comment by mekarpeles** [comment]
> The issue says "user contributed data" is being overwritten, but the example shows an empty field being (re)populated, which is how the system is designed.

I think this is correct and closing accordingly
