### ISSUE TITLE
Translation contribution web interface is broken

### ISSUE THREAD

**Issue by RecurringError** [internetarchive/openlibrary#943]
when trying to contribute to translation i noticed this.
tested on Chrome 64x and firefox 64x (just in case).

![image](https://user-images.githubusercontent.com/37140481/39468809-3c2f9600-4d35-11e8-8c9d-5aaf99d99ebc.png)

Edit:
url on which this occurred: https://openlibrary.org/i18n/strings.nl?m=edit
I had to be logged in to access the page.

**Comment by LeadSongDog** [comment]
@RecurringError Could you tell a bit about how you got the above error, such as what page you were editing? There's no URL visible in the image.

**Comment by LeadSongDog** [comment]
So, looking at this it seems to come from somewhere in this area:
https://github.com/internetarchive/openlibrary/blame/d26ee001d6b849b080dce9bcc937abafa6e9ef8f/openlibrary/templates/type/i18n/edit.html#L41

I've got to say, it is pretty obscure what is supposed to be going on here. Whatever happened to commenting code?

**Comment by jdlrobson** [comment]
I found the fix here but I suspect many other pages are impacted and I'm not sure how this broke.

**Comment by tfmorris** [comment]
@RecurringError That translation mechanism isn't functional, as noted at the top of the [page](https://openlibrary.org/i18n) just before this one in the navigation path.

The existing NL (minimal) translation is available here: https://openlibrary.org/i18n/strings.nl.json and you can read more about the current translation process here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md

To be honest though, we still have more work to do to pull all this together, so you might want to hold off until we've got things a little bit better organized.

**Comment by mekarpeles** [comment]
@tfmorris notices that this is not closed by 2253

**Comment by jdlrobson** [comment]
Since this is infogami and deciding whether a feature is used, this is no longer my area of expertise @brad2014 can you help with finding someone better placed to assign to?

**Comment by cdrini** [comment]
The consensus on the PR was to deprecate the UI in favour of the flow here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md . Closing this as "Won't fix" and creating a new issue for deprecation: #2286
