### ISSUE TITLE
Promise item imports need to augment metadata by any ASIN/ISBN10 if only title + ASIN is provided

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#9440]
### Problem

https://openlibrary.org/books/OL51751249M/25_Melodic_and_Progressive_Studies was imported 12 hours ago.

It has no date, author, or publisher and is exactly the kind of record which is causing problems with imports as reported in #8977 and with scanning metadata,  and should have been fixed with #8903 / #9030 

This record has an ISBN-10 , and Amzon has additional metadata (date, author, and publisher) associated with the ISBN: 0825699770  https://www.amazon.com/dp/0825699770

Why weren't these added?

Here is another example:
https://openlibrary.org/books/OL51751279M/The_Adventures_of_Tom_Sawyer(Unabridged)

No date and no author, but metadata is available: https://www.amazon.com/dp/7500144237

ImportBot has many in its recent history, newly created 'publisher unknown' records.

Ah... I see the problem, the changes in the last PR only applied to non-ISBN ASINs.

The important aspect is to lookup missing metadata by ASIN if there is only an ASIN in the promise item.

We need a modification of #8903 where the record is augmented if the import **has insufficient metadata to be useful for matching** future imports or matching for scanned metadata.

#### Proposal & constraints

As an **Open Librarian**, 
**in order to**  ensure the catalog is useful for unambiguous matching to support all basic search/match based usecases of:
* material discovery by patrons, 
* re-imports,
* scanned item metadata population

**I require that** only '**_differentiable_**' and '**_sane_**' records are imported.

**Additionally, I'd also like** every imported record to eventually be '**_complete_**'.

**Definitions:**

To be '**_complete_**', a record:

_MUST_ have a title.
_MUST_ have an author or statement of responsibility _IF_ one exists
_MUST_ have a date _IF_ one exists
_SHOULD_ have a publisher
_SHOULD_ have one or more strong identifiers IF they are known
_MAY_ have one or more other identifiers
_MAY_ have other metadata, depending on the source 

A '**_differentiable_**' record has enough metadata to identify which edition it represents.
It must be either '**_complete_**', or have a '**_strong identifier_**' which could be used to reliably locate
metadata to make it complete.

A '**_strong identifier_**' is one such as an ISBN, LCCN, OCN, _(YMMV -- edition vs. work level representation and other practical issues may need to be considered here. ISBN is a clear good example, with multiple sources, and check digit reliability)_ which can generally be relied upon to locate all possible metadata for that edition.

Bookseller only identifiers (such as B0* ASINs)  are not generally reliable enough for this purpose. They frequently do not persist over time. A bookseller identifier may happen to locate enough metadata to complete a record,
but if it can't be done _now_, it's unlikely to give better results in future. Whether an ASIN is directly from Amazon or a 3rd party seller _may_ have some bearing on how useful that ASIN is, but _in general_ they are still less reliable than a strong identifier.

A '**_sane_**' record is one where every populated field also passes a basic sanity check that it contains an
accurate value. It is not good enough that each of the fields merely be populated. Records that combine all metadata into the title field (author + date + other notes or extraneous content) should fail.
 Also unrealistic dates such as `0000`, `1000`, `9000`, `9999` etc will also fail.

#### Related files
**Import candidate Completeness and id type:**
<img src="https://github.com/internetarchive/openlibrary/assets/905545/076dd934-2a58-431b-9cb4-a97873fb30da" width=300px>

**Suggested workflow:**
![import-flow drawio](https://github.com/internetarchive/openlibrary/assets/905545/813735ef-7a69-4442-b9a5-25bc2990d41f)

#### Stakeholders

@scottbarnes 
@mekarpeles

**Comment by hollermay** [comment]
can I work on this issue?

**Comment by scottbarnes** [comment]
@hollermay, thank you for your interest in this issue. I _think_ this issue will probably be tackled by a staff member so I am going to change the labels for the issue for now. It may be worth looking at [Good First Issues](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+-linked%3Apr+label%3A%22Good+First+Issue%22+no%3Aassignee) to see if any of those interest you.

**Comment by scottbarnes** [comment]
Per a discussion with @hornc and @judec, we will want to keep statistics about when BWB has incomplete data, and when AMZ has incomplete data. At this moment it's unclear whether this would be a separate PR, but I am writing this here to capture the need.

**Comment by scottbarnes** [comment]
#6555 should be revisited after this is completed.

**Comment by LeadSongDog** [comment]
> Per a discussion with @hornc and @judec, we will want to keep statistics about when BWB has incomplete data, and when AMZ has incomplete data. At this moment it's unclear whether this would be a separate PR, but I am writing this here to capture the need.

@scottbarnes,
Would it be useful to also track when they have bad data? This would seem imho to be as often as not, though that is purely subjective.

**Comment by scottbarnes** [comment]
@LeadSongDog, yes, that makes sense to me, though I confess off the top of my head I am not sure of great ways to do that, largely because I am unsure of how to mechanically determine a particular metadata field has 'bad' data, unless you're thinking, for example, when the `publish_date` is 'obviously' wrong (January 1, 1900, etc.).

Can you expand a bit more on what what metrics one might use?

**Comment by LeadSongDog** [comment]
Title conjoined with author and or date is a common case. Conjoined multiple authors is another (often with only surnames). Jan 1 of any year is almost always an artifact (what publisher works New Year’s Day?) Co-authors must be alive at the same time: if not the earlier should be the author and the later a contributor of some kind. When an author is named but not readily différentiable from others of the same name, that should be reflected as for “John Smith undifferentiated” to avoid automatic attribution to the wrong author.

**Comment by hornc** [comment]
@mek having clear test cases to demonstrate that this does the correct thing in all cases would have been very helpful. Can you please add them @scottbarnes? It looks like I got confused about adding `source_record` as a required field, but that's all the more reason to have clear test cases for each of the relevant cases we are trying to catch.

It looks like we will have to get 'sane' data examples of dates and authors defined on another PR. I think dates are handled, but again demonstrating and documenting the cases in tests will make it a lit clearer.

**Comment by scottbarnes** [comment]
@hornc, yes, I will add the tests. I agree it would help to have them more clear.

**Comment by LeadSongDog** [comment]
Additional considerations:
In cases where name-only authors (sans disambiguation) are attributed in the source record it would be helpful to check for title, subject, or publisher matches among books by any of the possible synonymous authors. The default behaviour of just creating a new author record just creates more merging work downstream.

An obvious sanity check would ensure that the work is created during the author’s lifespan, but I frequently see exceptions that need to be corrected, so I infer it is not being checked.
