### ISSUE TITLE
Addition of DOIs to the "ID Numbers" field

### ISSUE THREAD

**Issue by IAuser89** [internetarchive/openlibrary#9444]
### Problem

In Open Library, under a publication's tab "details", there is the field "ID Numbers". Most commonly that field is used to list the ISBN. I see there are other options such adding the LCCN. I don't see, however, the option to add the DOI (Digital Object Identifier).

### Proposal & Constraints

Since nowadays DOIs are becoming increasingly common, at least in academic publishing, I propose adding the DOI to the list of "ID Numbers" within the "details" of a publication catalogued in the Open Library. Thank you.

### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
Coincidentally just did this yesterday to support an experiment! Should be there now. :+1:

**Comment by IAuser89** [comment]
cdrini: Wow! That was impressively fast! Thank you!

**Comment by cdrini** [comment]
Haha I finished it in -1 days! That has to be a record 😁
