### ISSUE TITLE
New edition contributor roles for LibriVox: book coordinator, meta coordinator, & proof listener

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#9446]
### A clear and concise description of what you want to happen

Add the roles “Book Coordinator”, “Meta Coordinator”, and “Proof Listener” to the options of contributor roles (potentially with “LibriVox” prepended).

### Expected behaviour / screenshots (ex: Figma design screenshots for UI feature)

When editing an edition, it should be possible to add the LibriVox roles for Contributors.

### Additional Context

[<img alt="example of the roles listed on the LibriVox book page" src="https://github.com/internetarchive/openlibrary/assets/177659/e3a2a2b5-20f0-4fd0-9f4e-59cd069ad156" align="right">](https://librivox.org/the-moon-endureth-tales-and-fancies-by-john-buchan/)

LibriVox has [**proof listeners**](https://wiki.librivox.org/index.php/Main_Page#Proof_Listener_(PL)) who function much like proofreaders, [**book coordinators**](https://wiki.librivox.org/index.php/Main_Page#Book_Coordinator_(BC)) who <q>[manage] all the other volunteers who will record chapters for a LibriVox recording</q>, [**meta (or metadata) coordinators**](https://wiki.librivox.org/index.php/Main_Page#Metadata_Coordinator_(MC)) who <q>help and advise Book Coordinators, and take over the files with the completed recordings ([…]). The files are then prepared and uploaded to the LibriVox catalogue, in a lengthy and cumbersome process.</q> These roles are listed on LibriVox book pages, e.g., https://librivox.org/the-moon-endureth-tales-and-fancies-by-john-buchan/

These roles do not really have a proper equivalent in the current contributor roles (unlike readers/narrators and graphic designers) and as such there’s not currently a good structured way to add/store this data.

### What is the proposed solution / implementation?

I suggest adding the following to the `roles` part of https://openlibrary.org/config/edition.yml (as of this writing starting on line 403):

```yaml
- [LibriVox] Book Coordinator
- [LibriVox] Meta Coordinator
- Proof Listener
```

**Note:** Needs no code changes, just a site admin who can edit the infogami.

### Is there a precedent of this approach succeeding elsewhere?

Seems to work fine for the other roles in the list :)

### Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

- Should the coordinator roles be prefixed with “LibriVox” or not?
  - Doing this would make those roles very narrowly focused on LibriVox, but the roles might also not really be applicable to anything other than LibriVox (are there other LibriVox like projects following a similar workflow?).

### Related files

https://openlibrary.org/config/edition.yml

### Stakeholders

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by cdrini** [comment]
Seems good to me! Added to https://openlibrary.org/config/edition ; they should come into play after the next deploy :+1: 

(I think its only identifiers that are in the repo, so the roles are still edited via this endpoint. CC @jimchamp )
