### ISSUE TITLE
Add Star Ratings & Want To Read counts to Search Result Cards

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9463]
### A clear and concise description of what you want to happen

A line should be added below the byline which shows the `star ratings` and `want to read` counts

### Expected behaviour / screenshots (ex: Figma design screenshots for UI feature)

![image](https://github.com/internetarchive/openlibrary/assets/978325/6401f600-97bc-476a-8d33-686f87811aa8)

### Stakeholders

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by siddharthbaleja7** [comment]
@mekarpeles  Can you please assign this issue to me.

**Comment by wowthedoge** [comment]
@mekarpeles Hi, can I have a go at this?

**Comment by mekarpeles** [comment]
@wowthedoge, @merwhite11 is currently working on a PR for this one :) thank you so much for the kind offer.

Here are a few issues where contributions may be welcome!
https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Needs%3A+Breakdown%22%2C%22Needs%3A+Lead%22%2C%22Needs%3A+Designs%22%2C%22Needs%3A+Triage%22+label%3A%22Good+first+issue%22+no%3Aassignee+is%3Aopen+-linked%3Apr
