### ISSUE TITLE
Standardize and Clean Search Inside Results

### ISSUE THREAD

**Issue by merwhite11** [internetarchive/openlibrary#9479]
### Problem

To complement the effort in #1001 to redirect patrons to the Search Inside results, we need to standardize the Search Inside result cards. There are currently three types of result cards in Search Inside results with UI inconsistencies:

1. When result book is available to **Borrow**: Footer displays as **'Borrow & See All Results'**
     - Change footer to match case 2 below -> link to all matches highlighted in text reader
2. When result book is available to **Read**: Footer displays as **See All Results**
     - Reword 'See All Results' to more obviously signify link to all matches highlighted in text reader
2. When result book is **Preview Only**: No footer
     - TBD what the footer should be
 

#### Evidence / Screenshot
**Borrow** result:
![Screenshot 2024-06-24 at 8 53 10 AM](https://github.com/internetarchive/openlibrary/assets/79802377/77ab360f-7981-4f59-ba05-7da1d2c927bd)

**Read** result:
![Screenshot 2024-06-24 at 9 08 06 AM](https://github.com/internetarchive/openlibrary/assets/79802377/810a5327-7499-4934-bae6-34e4a9d90953)

**Preview only** result:
![Screenshot 2024-06-24 at 8 58 15 AM](https://github.com/internetarchive/openlibrary/assets/79802377/4a8a340f-57f5-4306-bf13-c8fff201e8c3)

For consistent UI across the site, we need to update the Search Inside results to more closely match the No results Fulltext Suggestion Card implemented in #1001. 
1. Change font of snippet to serif font
2. Add quotation marks around snippet
3. Add page number after each snippet
### Reproducing the bug

1. Go to Search Inside 
2. Search 'walter' and scroll down to see all 3 UI variations of the footer. 

* Expected behavior: There should be a consistent footer with language that more clearly leads to text reader
* Actual behavior: Inconsistent footer UI and unclear text

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by merwhite11** [comment]
@mekarpeles 

Here is a proposal of a modified Search Inside result card that carries over the design elements from Search Inside Suggestion Card (#1001). 

- 3 excerpts instead of 5
- Excerpt in serif font to distinguish from other text
- Excerpt in blue font to indicate clickability (links to text reader)
- Large quotes around excerpt
- Page number
- Reworded footer (still conditionally displayed)

Codepen: https://codepen.io/merwhite11/pen/NWVLXVa

**Comment by mekarpeles** [comment]
1. Stick with 1 or 2 quotes for this page
2. Padding on quote should be `10px 0` so it aligns left 
3. Author should be smaller than title (both on /search/inside **and** /search)
4. Let's try the copy "Explore all X matches" _and_ have it be within (not below) `sri__extra` to save height.
5. I think the quote should be black w/ blue hover (similar to Title and Author) and the page number should be on the same line w/ &mdash;

<img width="944" alt="Screenshot 2024-07-01 at 11 42 32 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/7804468b-d7e9-4b6e-b8f6-4ca3475b373a">


<img width="947" alt="Screenshot 2024-07-01 at 11 34 35 AM" src="https://github.com/internetarchive/openlibrary/assets/978325/74d53626-cc2a-4e58-9356-ed4f88a768cd">
