### ISSUE TITLE
Importing archive.org Favorites as an OpenLibrary book list

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#9484]
Dear developers,

I propose that Openlibrary.org patrons should be able to import their Archive.org Favorites to OpenLibrary as a book list.
Needless to say, this would only apply to archive.org items that are linked in the "ID Numbers" section of an OpenLibrary book record.

![Screenshot_2024Chrome](https://github.com/internetarchive/openlibrary/assets/19307323/dc0cc14a-ccfd-47e8-b6f7-d21df444ad41)

Thank you for considering my suggestion.

### Stakeholders

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
I think the idea of "favoriting" things on Open Library is interesting.

This feature request is a bit of a challenge because:
* Not every archive.org favorite will be a book or have an Open Library entry
* Many Open Library books that patrons may wish to favorite don't exist on archive.org

@el4ctr0n what is the thing you would ultimately like to do? e.g. share a list of your favorite books on Open Library? Someone could create a tool to go from Archive.org Favorites to Open Library list, but I think I may close as not-planned by staff.

**Comment by el4ctr0n** [comment]
> * Not every archive.org favorite will be a book or have an Open Library entry
> * Many Open Library books that patrons may wish to favorite don't exist on archive.org
> 
> @el4ctr0n what is the thing you would ultimately like to do? e.g. share a list of your favorite books on Open Library? Someone could create a tool to go from Archive.org Favorites to Open Library list, but I think I may close as not-planned by staff.

I want to import to a single OpenLibrary book list my archive.org favorite items that have OpenLibrary entries, so I can then move selected items from that imported book list to one of the many topical book lists I already have on OpenLibrary.

**Comment by el4ctr0n** [comment]
> * Not every archive.org favorite will be a book or have an Open Library entry
> * Many Open Library books that patrons may wish to favorite don't exist on archive.org
> 
> @el4ctr0n what is the thing you would ultimately like to do? e.g. share a list of your favorite books on Open Library? Someone could create a tool to go from Archive.org Favorites to Open Library list, but I think I may close as not-planned by staff.

@mekarpeles 
@I want to import to a single OpenLibrary book list my archive.org favorite items that have OpenLibrary entries, so I can then move selected items from that imported book list to one of the many topical book lists I already have on OpenLibrary.

**Comment by el4ctr0n** [comment]
@mekarpeles 
It would also be great if the imported book list included OpenLibrary book entries for favorited archive.org books that were later removed from archive.org due to a copyright complaint.
