### ISSUE TITLE
0 results search page doesn't show search facets

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#95]
See http://openlibrary.org/search?q=california+hiking&subject_facet=Lending+library

Should show the (removable) Lending Library [x] facet under the search box.

**Comment by hornc** [comment]
Current location of the work search template file: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/work_search.html

**Comment by rohitjain00** [comment]
I think this issue is resolved
![facet](https://user-images.githubusercontent.com/17525863/54286503-fc96e000-45c9-11e9-8013-7d6d6df5b785.png)
