### ISSUE TITLE
Problem with ImportBot Writebacks OL -> IA

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#950]
Discovered a somewhat confusing bug in `plugins/importapi/code.py` -> `openlibrary/catalog/add_book`:

*Background:*
We run a process called `Import Bot` (`scripts/manage-imports.py`) whose job is to discover new books within archive.org which are not within openlibrary.org and create a corresponding work + edition record for the book on OL. The final step in the process is to write back the resulting openlibrary work and edition ID of the book back into the source archive.org item's metadata.

It turns out,  `openlibrary/catalog/add_book` `load` was not hitting `update_ia_metadata_for_ol_edition` and this write-back code had to be moved instead to the end of `openlibrary/catalog/add_book` `load_data`

**Comment by hornc** [comment]
Update, looks like the writeback is not occurring for items which _update_ and existing OL item, but is when they are created. examples: https://openlibrary.org/admin/imports/2018-09-23  look for entries where STATUS == modified.
