### ISSUE TITLE
BookBrainz, MusicBrainz identifiers easily mislabeled as StoryGraph identifiers

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#9503]
### Problem

Because all 3 libraries use UUIDs & Storygraph identifiers were integrated into OL first, when adding author identifiers the menu which guesses what kind of identifier you're including will automatically guess StoryGraph. This makes mistakes far easier.

#### Relevant URL(s)
https://github.com/internetarchive/openlibrary/issues/8480#issuecomment-1806759638

### Reproducing the bug

1. Go to edit an author page.
2. Copy a BookBrainz or MusicBrainz author identifier.
3. Paste it into the identifier field.

* Expected behavior: The field either guesses it to be BookBrainz/MusicBrainz identifier (admittedly difficult) or does not attempt to guess the source.
* Actual behavior: The field guesses it to be a StoryGraph identifier.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
I think the solution may be to not try to guess if it's a UUID.

**Comment by Freso** [comment]
Isn’t @RayBB working on something with Wikidata data to "guess" identifiers using the whole URL? If that’s meant to replace the current simple system, that might also solve this issue. (Though, of course, I don’t know how far along that is, so it might be prudent to simply remove the UUID guessing until then… I can probably poke at the code and yoink that out.)

**Comment by RayBB** [comment]
Possible yes but not planned anytime soon for me
