### ISSUE TITLE
Ability to differentiate between what something is and what something is about

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#9522]
### A clear and concise description of what you want to happen

Being able to distinguish between whether some Work _is_ `something` or is _about_ `something`. E.g., is [The Dispossessed](https://openlibrary.org/works/OL59863W)  `science fiction` or about `science fiction`? Is [Drug Themes in Science Fiction](https://openlibrary.org/works/OL12032609W) `science fiction` or about `science fiction`? Is [How To Write Non-Fiction](https://openlibrary.org/works/OL20544005W) `non-fiction` or about `non-fiction` (or both!)?

### Additional Context

Right now there is no clear distinction within subjects whether something _is_ an example of a given subject or whether something is discussing or otherwise about this subject. This can to some degree be alleviated by combining subject tags – e.g., `"science fiction" AND "non-fiction"` should return “Drug Themes” but not “Dispossessed” and `"science fiction" -"non-fiction"` should return “Dispossessed” but not “Drug Themes” – but this is not really a good way to find all, say, `non-fiction` about `non-fiction`.

### What is the proposed solution / implementation?

I don’t have a single proposal in mind. I think there is already some attempt at a subject schema using e.g. `genre:` prefixes? This could work.

Another approach could be dedicated inputs (similar to how subjects, persons, places, and times are currently distinct). If this used the same “pool” of subjects, this might make it so, e.g., [`science fiction`](https://openlibrary.org/subjects/science_fiction) can present both Works that represent the subject and Works that are about the subject.

This probably needs a lot more discussion and planning, I just couldn’t find an issue about this to track it.

### Stakeholders

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
I think there simply need to be different tag types for these, e.g. `genre` versus `classification` versus `topic` / `subject`.

This is part of the #5738 #2819 / #7904 project (closing here)

**Comment by tfmorris** [comment]
Subjects are intended to be finding aids, so they should be viewed as inclusive, not necessarily precise, categories. Librarians have spent decades (nay, centuries) developing [cataloging practices](https://www.ala.org/pla/resources/tools/circulation-technical-services/cataloging-practices), so it's informative to look at things like WorldCat or the Library of Congress to see how they categorize things.

https://search.worldcat.org/title/51978024?oclcNum=51978024
https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part09.utf8:149392745:978
https://search.worldcat.org/title/1495329?tab=details
https://search.worldcat.org/title/1048899182?oclcNum=1048899182

Given the cooperative nature of shared cataloging, any deviation from existing cataloging standards will be overwhelmed by the volume of imported MARC data.
