### ISSUE TITLE
`web.archive.org` JS wrapper breaks JS `import`s

### ISSUE THREAD

**Issue by AlttiRi** [internetarchive/openlibrary#9529]
### Problem

_I'm not sure that it's the correct place to report bugs with [`web.archive.org`](https://web.archive.org/) site, however, I did not find the more appropriate place, so._

---

`web.archive.org` put JavaScript files' content into a wrapper.

For example: 
- https://web.archive.org/web/20240708020959jm_/https://alttiri.github.io/webpage-with-script-module/simple.js
- (from [here](https://web.archive.org/web/1/https://alttiri.github.io/webpage-with-script-module/simple.html))

Here is only `document.body.append("JS is working (One chunk JS)");` string is the original JS file's content, the other lines are a wrapper.

Usually it's OK. Until the JS code contains [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)s.

For example:
- https://web.archive.org/web/20240708020915jm_/https://alttiri.github.io/webpage-with-script-module/multi-modules.js
- (from [here](https://web.archive.org/web/1/https://alttiri.github.io/webpage-with-script-module/))

**Putting an import into a block scope is illegal:**
```js
{
  import {a} from "./a.js";
}
```
So, JS on such archived page is not working at all.

In Chrome' console you can see the follow error:
```
Uncaught SyntaxError: Unexpected token '{'
```
In Firefox:
```
Uncaught SyntaxError: import declarations may only appear at top level of a module
```

It's especial critical for SPA sites.
For example, "Hello World" Vue.js based site with the code splitting: 
- https://web.archive.org/web/2/https://alttiri.github.io/vite-vue-ts-example/

It does not works at all.

While with one chunk JS file is OK:
- https://web.archive.org/web/1/https://alttiri.github.io/vite-vue-ts-example/

---

**How to fix it?**

Do not put JS content of the files are loading the script as a module into a code block `{ }`.

It makes no sense for `script`s with [`type="module"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type#module).

### Reproducing the bug

- https://web.archive.org/web/2/https://alttiri.github.io/vite-vue-ts-example/
- https://web.archive.org/web/1/https://alttiri.github.io/webpage-with-script-module/

**Comment by AlttiRi** [comment]
BTW, files that should be loaded as sub modules **are** archived.
- https://web.archive.org/web/https://alttiri.github.io/webpage-with-script-module/module-a.js
- https://web.archive.org/web/https://alttiri.github.io/webpage-with-script-module/module-b.js
- https://web.archive.org/web/https://alttiri.github.io/vite-vue-ts-example/assets/index-tkRwBK2y.js
- https://web.archive.org/web/https://alttiri.github.io/vite-vue-ts-example/assets/vendor-DHt9uzVT.js

So, you just need to fix the wrapping. Already saved sites will work.

**Comment by mekarpeles** [comment]
@ibnesayeed I think this one is for you! Tagging team wayback and closing this issue here. Thank you @AlttiRi for raising!

**Comment by Lampe2020** [comment]
Any news on this?
