### ISSUE TITLE
Hide rest of registration form if third-party login used

### ISSUE THREAD

**Issue by rebecca-shoptaw** [internetarchive/openlibrary#9540]
Dependency to `epic` #7694. Subtask of #9315.

### Problem

As part of an ongoing effort to clarify the registration flow, we want to hide the rest of the OL registration form if the user selects "Sign in with Google" and the third party login form grows.

This way, users will know which form to submit, but will still be able to return to the regular form by selecting "Cancel"

### Expected behaviour / screenshots
<img width="455" alt="IA login screen" src="https://github.com/internetarchive/openlibrary/assets/140550988/601abb6e-cc65-4d4d-8115-b784f7dd87bc">

Like the above, but the "OR" and everything below it would no longer appear.

### Proposal & Constraints
Should hopefully be very simple, just intercepting the `resize` handler in `ia_thirdparty_logins.js` to add a quick `display: none` to the relevant divs. Similar to the approach in `covers.js` in #9418.

### Related files

`create.html`
`ia_thirdparty_logins.js`

### Stakeholders

@cdri

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
We chatted and since this will only affect the case where a user already has an IA account, but no OL account, which is preeeetty niche, and there are a number of edge cases related to how to detect the IA iframe has expanded, and if the user has already entered information into the registration form; it seems like it's not worth the code.
