### ISSUE TITLE
Search box only visible on "Want to read", not on Currently Reading/Already Read shelves

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9547]
#### Evidence / Screenshot

![image](https://github.com/internetarchive/openlibrary/assets/6251786/4366fc02-0e64-4573-bbfb-3ba8f324381b)

Expected:

![image](https://github.com/internetarchive/openlibrary/assets/6251786/6244a7c4-b0ca-4cc4-8780-61fa07f0f82b)

#### Relevant URL(s)

E.g. https://openlibrary.org/people/ScarTissue/books/already-read

### Reproducing the bug

1. Go to https://openlibrary.org/people/ScarTissue/books/already-read

* Expected behavior: A search box should be visible letting you search already read books
* Actual behavior: No search box visible!

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Related files
https://github.com/internetarchive/openlibrary/blob/d9e5424beb2cf524aaf30452e5a6254afce384b3/openlibrary/templates/account/reading_log.html#L45-L49

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by benbdeitch** [comment]
Hey, could you assign this to me?
