### ISSUE TITLE
Use new search box on reading log pages, author page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9557]
### Problem

The reading log pages, e.g. https://openlibrary.org/people/ScarTissue/books/want-to-read , and the author page, e.g. https://openlibrary.org/authors/OL33146A/Franz_Kafka , feature search boxes which should use the new updated style introduced in #9146

![image](https://github.com/internetarchive/openlibrary/assets/6251786/30b06851-f9e9-488b-9411-14d9c3fc4ed5)

![image](https://github.com/internetarchive/openlibrary/assets/6251786/e6a2e09e-3ad5-4d0e-9fe6-f1a669f144c0)

### Related files
Reading log pages:

https://github.com/internetarchive/openlibrary/blob/d9e5424beb2cf524aaf30452e5a6254afce384b3/openlibrary/templates/account/reading_log.html#L46-L49

Author pages:

https://github.com/internetarchive/openlibrary/blob/452943391f40d2d798d8a74b455f0493e0fc6333/openlibrary/templates/type/author/view.html#L138

### Stakeholders
@0simoo

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Souvik-Cyclic** [comment]
@cdrini I want to work on this, assign this issue to me.

**Comment by cdrini** [comment]
Apologies for the confusion folks, I didn't see the comments in time. I'm leaving this one with @dwrik since they opened a PR and are actively working on it, although for future reference @dwrik, if there are comments from other contributors on an issue please do wait for a maintainer to respond before beginning :+1:

**Comment by dwrik** [comment]
@cdrini

Apologies from my end as well. The issue wasn't assigned and there was no confirmation on whether someone had started working on it so I assumed it wasn't being worked on by anyone. Nonetheless, from next time onwards, will wait for a maintainer to respond before working on it. Thanks.

**Comment by educonnec** [comment]
thanks for sharing this coding [toutatice](https://educonnectnormandie.online/toutatice/).
