### ISSUE TITLE
Investigate auto-429ing high request IPs/DDOS

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9562]
### A clear and concise description of what you want to happen
We should investigate using the HAProxy or Nginx rate limiting to automatically block high requests.

### Additional Context
[Nginx documentation](https://blog.nginx.org/blog/rate-limiting-nginx).

### Related files

Here's a basic script to help simulate how many requests/IPs would be blocked under what conditions.
[main.py.gz](https://github.com/user-attachments/files/16195195/main.py.gz)

### Stakeholders

@cdrini 
<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
**Decisions**: On /api and covers, let's try an initial experiment of temporary (5 minutes) returning 429 requests to clients if there's more than 20 requests (mek unsure of 20 here) a second 

e.g. 

```
limit_req_zone $binary_remote_addr zone=mylimit:10m rate=20r/s;

location / {
    limit_req zone=mylimit burst=20 nodelay;
```

**Comment by mekarpeles** [comment]
# Requirements

* [ ] Remove bytespider 429 special case and have them be dealt via 429 rate limits
* [ ] We should be able to easily check how many IPs are getting rate limited (at a given time) -- grafana --> grep and filter for 429 requests
* [ ] 500 / minute; gauge for < 10 unique IPs / day hitting 429?
* [ ] ignore archive.org cluster IPs
