### ISSUE TITLE
Add Google Books support to BookWorm

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9574]
### A clear and concise description of what you want to happen
BookWorm (AKA 'the affiliate-server') should also look to Google Books for metadata. See https://developers.google.com/books for more.

### Additional Context
Note: this issue needs further updating to propose a strategy for integrating Google Books, but the first step is to record that this should be done.

### Stakeholders

<hr>
@mekarpeles, @judec, @hornc 

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by tfmorris** [comment]
The content removal clause of the ToS might be tricky to deal with: https://developers.google.com/books/terms#content-removal

**Comment by scottbarnes** [comment]
I will send this through whatever channel I have to and if it's not approved, there are sadly no shortage of other issues needing attention. :)
