### ISSUE TITLE
How to search for books in portuguese?

### ISSUE THREAD

**Issue by GHCMelo** [internetarchive/openlibrary#9583]
I would like to use the API to get books translated to portuguese. Is that possible?

**Comment by tfmorris** [comment]
It's kind of hidden, but you can find the syntax at the bottom of the search API [doc page](https://openlibrary.org/dev/docs/api/search)

You can use something like this as a starting point:
https://openlibrary.org/search.json?q=language%3Apor&fields=key,author,title,editions,editions.key,editions.title,editions.language,editions.publish_date

Note that this doesn't just include translations, but any edition which was published in Portuguese, including works which were originally in Portuguese.

**Comment by mekarpeles** [comment]
Thank you @tfmorris
