### ISSUE TITLE
Book title bar gets stuck to top of page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9584]
#### Evidence / Screenshot

https://github.com/user-attachments/assets/c5e9f3cb-ded7-4d80-b3ca-dc812d90d3d8

#### Relevant URL(s)
https://openlibrary.org/books/OL28727054M/Punk_Reader

### Reproducing the bug

1. Go to any book
2. Scroll up and down a bit erratically (as seen in video)

* Expected behavior: Top bar doesn't get stuck
* Actual behavior: Top bar gets stuck

### Context

- Browser (Chrome, Safari, Firefox, etc): Confirmed on FF 128 and Chrome 126
- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Doesn't matter
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by RayBB** [comment]
@nymishkash you're assigned. Good luck!

**Comment by nymishkash** [comment]
Hey @RayBB.

I seem to be having trouble with the commands to run the project after making possible changes to check whether the site is now behaving as intended. Could you please guide me with the commands. 

I am currently using `sudo docker-compose build` and then `sudo docker-compose up` after making changes to the `plugins/openlibrary/js/compact-title/index.js` file.

**Comment by RayBB** [comment]
Those commands look correct to me. Can you please share the error message you're getting?

**Comment by schu96** [comment]
Hi @RayBB if this issue is still up for grabs I'd like to look into it

**Comment by RayBB** [comment]
@schu96 you're assigned. Thanks for looking into it!
