### ISSUE TITLE
Add IA cover feature does not always display button

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#9589]
### Problem

The new cover feature that allows editor to add cover from IA item does not always display the relevant button. The modal frame size does not adjust to the size of the content and the button is hidden.

#### Evidence / Screenshot
<img width="648" alt="Screenshot 2024-07-19 at 09 19 08" src="https://github.com/user-attachments/assets/810ab59b-0093-41c7-bcf7-b1437982e879">

### Reproducing the bug

1. Go to ...an edition record with an OCAID
2. Do ...add the cover from the IA item

* Expected behavior: Button to perform this action should always be displayed.
* Actual behavior: Button is sometimes hidden.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

@rebecca-shoptaw 

<hr>
#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by rebecca-shoptaw** [comment]
@seabelis bizarre -- thanks for catching this! We had to set the size of the modal very specifically to accommodate all the fields, so I'll investigate when/why the custom sizing wouldn't be working!

**Comment by rebecca-shoptaw** [comment]
@seabelis update!! Having a little trouble replicating the issue -- if you have any more info re: which situations it is/isn't working in that would be wonderful, otherwise will keep experimenting trying to get the same error.

**Comment by cdrini** [comment]
Oh! I also actually noticed one of the webnodes was stuck on the old version of the code during the deploy! I just restarted it to "finalize" the deploy there. I wonder if that was what caused the sporadic failure? Cause that would be happening 33% of the time if it was related to that. Are you still having the issue, @seabelis ?

**Comment by seabelis** [comment]
It does seem better now. I'll close this and reopen if I encounter the problem again.
