### ISSUE TITLE
Subject & Publisher pages should add sort order as a URL parameter

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#96]
Please add "sort=datepublished" to the URL for these pages. So you can see carousels sorted by most recent and eBooks only through a link that someone IMs you.

**Comment by jdlrobson** [comment]
This bugs is a few years old now. @mekarpeles let's review this one and see if there's anything that applies to the 2018 version!

**Comment by mekarpeles** [comment]
Closing, subject pages are going to use the search UI
