### ISSUE TITLE
"Cancel" broken on author photos "manage" page

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9602]
### Problem

Clicking "Cancel" on the "Manage" tab of the "Author Photos" modal does nothing.

#### Evidence / Screenshot
![image](https://github.com/user-attachments/assets/a4b255de-611c-4b67-be5b-ab03684c6d65)
Clicking "Cancel" in the above image doesn't do as much as one might hope.

This may have happened as a result of a change in 2e387f5eaea7291b61ebdfdbb150096cdc4a3672.

#### Relevant URL(s)
http://localhost:8080/authors/OL20585A/Edwin_Abbott_Abbott

### Reproducing the bug

1. Go to the author photos modal -> manage tab (and optional drag a photo into the delete area).
2. Do click cancel.

* Expected behavior: Something happens.
* Actual behavior: Nothing happens

Having said all this, after discussing this issue with the OL team, the decision is to "solve" this by **removing the cancel button** to make it more consistent with the 'Add' tab.

### Context

- Browser (Chrome, Safari, Firefox, etc): Firefox
- OS (Windows, Mac, etc): Linux
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by sachan13harshit** [comment]
@scottbarnes  please assign this issue to me

**Comment by scottbarnes** [comment]
Although @RayBB was made lead, I have updated the issue to include the following important information:
> Having said all this, after discussing this issue with the OL team, the decision is to "solve" this by **removing the cancel button** to make it more consistent with the 'Add' tab.

I will also assign this to you, @Souvik-Cyclic, simply because you were first out of the gate in requesting to work on it. :)

**Comment by Souvik-Cyclic** [comment]
Can you once check in your local if you are able to add author photo for any of the authors ? @RayBB 
http://localhost:8080/authors/OL20585A/Edwin_Abbott_Abbott/edit
I am actually getting this pop up menu with no options to either add or manage 
![image](https://github.com/user-attachments/assets/18c47023-cafc-404b-8e00-bdf68a6aa9b7)

Earlier I was getting options to add and manage, if you are also unable to add I think it has something to do with #9607

**Comment by scottbarnes** [comment]
@Souvik-Cyclic, that looks like what would happen prior to the merging of #9565 (cf #9473).

If you've not done so in the past 24 hours or so, please update your master branch with something like `git fetch upstream master`, assuming your remote for `git@github.com:internetarchive/openlibrary.git` is named `upstream`, and then create your feature branch off that updated `master`.

For more, see the [Working on your Branch(https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) section of the wiki. See also the section in the issue description above named "Instructions for Contributors".
