### ISSUE TITLE
Move edition causes new works to be created

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#961]
For some reason, despite numerous attempts (from Chrome and Firefox, on iOS and on Windows), edition OL13763080M will not link to the work input : OL14853009W
Instead, edits alternate between deleting the existing work link and creating a brand new one from the edition data. Each time, the UI shows the correct title as a dropdown under "What work is this an edition of"  when I fill in OL14853009W, and clicking on that title populates the title: subtitle value.  Something very strange is going on.

**Comment by seabelis** [comment]
I've experienced this as well.

**Comment by LeadSongDog** [comment]
Seems it was a workless edition. Once I assigned an author a one-edition work was created https://openlibrary.org/books/OL13763080M/Histoire_illustr%C3%A9e_des_inventions?b=16&a=15&_compare=Compare&m=diff 
Then I could relink the edition to the proper work

**Comment by seabelis** [comment]
Adding the author doesn't always do the trick. Try moving [this edition](https://openlibrary.org/books/OL26390416M/El_Gen) to OL17762235W, for example.

**Comment by LeadSongDog** [comment]
You're right, @seabelis. And in the meanwhile new, unnecessary, redundant Work pages are created. Ugh!

**Comment by seabelis** [comment]
Yeah, I have a whole list of books with the tag "Not Good" just waiting for a resolution.

**Comment by LeadSongDog** [comment]
Wait, is that a tag on the edition/work record's "what's it about?" describing the record rather than the book, or a tag on a personal list?

**Comment by seabelis** [comment]
personal list

**Comment by LeadSongDog** [comment]
whew!

**Comment by LeadSongDog** [comment]
At some point we are going to need to clean up all these redundant delinked work records. Typically these show on title or author searches as having 1 or editions, but not consistently. For instance, 
https://openlibrary.org/works/OL17835670W is shown on https://openlibrary.org/authors/OL7396111A/Siddhartha_Mukherjee as having 1 edition, but internally it shows no editions. Either way, whether is shows 0 or 1, if it doesn't have editions, the work should be redirected to one that does.

**Comment by seabelis** [comment]
I think one cause of this is the presence of a subtitle in the work's title.

**Comment by seabelis** [comment]
The other thing I've noticed is that after author merges, the " stuck" editions can be moved. In the case you mention above, there are two profiles for the author: https://openlibrary.org/authors/OL7396111A/Siddhartha_Mukherjee and https://openlibrary.org/authors/OL6865237A/Siddhartha_Mukherjee. This might be the reason on that one.

**Comment by cdrini** [comment]
Ah; I believe this is the same issue as #730, correct, @LeadSongDog ? I think that was closed by accident.

**Comment by seabelis** [comment]
The issue now seems to be a new work-less edition is created which is then un-editable as in https://github.com/internetarchive/openlibrary/issues/1891.
