### ISSUE TITLE
Star ratings form IDs appear more than once on book page

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9632]
**Edit:** Description/scope update by Rebecca:
## Problem
Currently, `databarWork.html` renders the `modal_links` element for the work twice, once in the main page, and once in a special mobile-only div called `readers-stats__wrapper mobile`

![Code organization](https://github.com/user-attachments/assets/8fd0d23d-dca9-48d4-869a-25811125873f)

The `modal_links` element always renders the star ratings form (`StarRatings.html`) inside, which means that the page now has the id `#ratingsForm` and each of its sub-ID’s (`#star-1` and whatnot) listed twice in the page’s HTML.

To make matters worse, `databarWork` also renders the `list_widget` , which itself also renders the star rating form, adding a third set of duplicate ID’s to the mix.

The three duplicated ID sets are a problem both for accessibility (what prompted this issue) and for code cleanliness generally.

## Solution
The solution is luckily not too complicated, it will just involve using an existing ID parameter to distinguish the mobile version of the form, and at the same time decide whether or not to render the star ratings inside the mobile version of `modal_links`  (the star ratings should only be rendered in here if we’re in the mobile version).

**Comment by veronicamar** [comment]
From PageSpeed:
The value of an ARIA ID must be unique to prevent other instances from being overlooked by assistive technologies. 

<img width="908" alt="Screenshot 2024-07-27 at 2 51 08 pm" src="https://github.com/user-attachments/assets/2a27f162-3114-48cb-8f0c-1cb3d1098d15">

Rename any duplicate ID values.

Duplicate IDs are common validation errors that may break the accessibility of labels, e.g., form fields, table header cells.

To fix the problem, change an ID value if it is used more than once to be sure each is unique. Unique ID's differentiate each element from another and prevent invalid markup, wherein only the first instance gets acted upon by client-side scripting, or where assistive technologies typically only reference the first one accurately.

**Comment by kohantikanath** [comment]
Hi @veronicamar,

I’d love to work on resolving the duplicate ARIA IDs issue. Please assign me to this task!

**Comment by rebecca-shoptaw** [comment]
Hi @kohantikanath, we're working on figuring out the best scope for this issue and gathering some helpful info for you, but once that's done I'm happy to assign you if you're still interested!

**Comment by kohantikanath** [comment]
Hi @rebecca-shoptaw ,
That sounds great! I’d be happy to take on the new issue related to accessibility when it's ready. Thanks for considering me!
