### ISSUE TITLE
Download options appear for Editions with a 'bad' OCAID

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9637]
### Problem

If a book is no longer available on Internet Archive, but Open Library still has a record for the OCAID, download options may show on the left-hand side of the Edition page. E.g. https://openlibrary.org/books/OL25538791M/Programming_Scala

#### Evidence / Screenshot
![image](https://github.com/user-attachments/assets/91787c4f-fb48-45a6-a498-0f4e4df6ca7b)

#### Relevant URL(s)
https://openlibrary.org/books/OL25538791M/Programming_Scala

### Reproducing the bug

1. Go to https://openlibrary.org/books/OL25538791M/Programming_Scala
2. Observe there are download options on the left, e.g., ePub, and they don't work because there are in fact no download options for that Internet Archive item.

* Expected behavior: Open Library doesn't show download options when there aren't any.
* Actual behavior: Open Library does show download options when there aren't any.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

It's not clear what the best solution is at the moment, so as it stands, this issue would be hard to work on, absent someone proposing a solution that we can agree upon.

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by shubhiscoding** [comment]
Hey I'd like to work on it

**Comment by scottbarnes** [comment]
Hi @shubhiscoding, I would be happy to assign this to you, but as the issue mentions, it's not clear what the best solution is at the moment, so as it stands, this issue would be hard to work on, absent someone proposing a solution that we can agree upon.

Did you have a specific solution in mind? There are a few ways this could go, but I am not sure the 'best' way to tackle this.

**Comment by shubhiscoding** [comment]
> Hi @shubhiscoding, I would be happy to assign this to you, but as the issue mentions, it's not clear what the best solution is at the moment, so as it stands, this issue would be hard to work on, absent someone proposing a solution that we can agree upon.
> 
> Did you have a specific solution in mind? There are a few ways this could go, but I am not sure the 'best' way to tackle this.

Hii I think I found the fix, If you look into databarWork.html you'll see

```
        $if editions_page:
          $ render_times['databarWork: Book provider'] = time()
          $ book_provider = get_book_provider(page)
          $ availability = (page.availability or {}) if hasattr(page, 'availability') else {}
          $if book_provider:
            $:book_provider.render_download_options(page)
          $ render_times['databarWork: Book provider'] = time() - render_times['databarWork: Book provider']
```

and I found out that you guys are using this ``` (availability.get('is_readable') or availability.get('status') == 'open') ``` check for calling ReadButton function so If I do this

```
        $if editions_page:
          $ render_times['databarWork: Book provider'] = time()
          $ book_provider = get_book_provider(page)
          $ availability = (page.availability or {}) if hasattr(page, 'availability') else {}
          $if book_provider and (availability.get('is_readable') or availability.get('status') == 'open'):
            $:book_provider.render_download_options(page)
          $ render_times['databarWork: Book provider'] = time() - render_times['databarWork: Book provider']
```

then the download option will only be visible when the work is readable.

**Comment by shubhiscoding** [comment]
> > Hi @shubhiscoding, I would be happy to assign this to you, but as the issue mentions, it's not clear what the best solution is at the moment, so as it stands, this issue would be hard to work on, absent someone proposing a solution that we can agree upon.
> > Did you have a specific solution in mind? There are a few ways this could go, but I am not sure the 'best' way to tackle this.
> 
> Hii I think I found the fix, If you look into databarWork.html you'll see
> 
> ```
>         $if editions_page:
>           $ render_times['databarWork: Book provider'] = time()
>           $ book_provider = get_book_provider(page)
>           $ availability = (page.availability or {}) if hasattr(page, 'availability') else {}
>           $if book_provider:
>             $:book_provider.render_download_options(page)
>           $ render_times['databarWork: Book provider'] = time() - render_times['databarWork: Book provider']
> ```
> 
> and I found out that you guys are using this `(availability.get('is_readable') or availability.get('status') == 'open')` check for calling ReadButton function so If I do this
> 
> ```
>         $if editions_page:
>           $ render_times['databarWork: Book provider'] = time()
>           $ book_provider = get_book_provider(page)
>           $ availability = (page.availability or {}) if hasattr(page, 'availability') else {}
>           $if book_provider and (availability.get('is_readable') or availability.get('status') == 'open'):
>             $:book_provider.render_download_options(page)
>           $ render_times['databarWork: Book provider'] = time() - render_times['databarWork: Book provider']
> ```
> 
> then the download option will only be visible when the work is readable.

On trying the same I got the expected result

[Screencast from 2024-07-29 05-54-12.webm](https://github.com/user-attachments/assets/e6b558c6-47c7-406a-abe1-537c4527dd52)

**Comment by shubhiscoding** [comment]
created a Pull request on #9647 for you to review it easily and suggest any changes required
