### ISSUE TITLE
Web books incorrectly select provider + display incorrect toast

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9639]
#### Problem 1
When a patron clicks the Read button on a web book, a toast message is displayed about visiting an external site, etc.

When there are multiple results on a search, e.g., https://testing.openlibrary.org/search?q=format%3A%22Web+book%22&mode=everything&page=2, clicking to read a web book always renders the `direct_read_button.html` template, regardless of what template should be rendered (e.g. `openstax_read_button.html`.

#### Problem 2
Closely related, but, at least for `DirectProvider`s, the toast message for a subsequent `DirectProvider` result will display the toast message for the first one.

#### Relevant URL(s)
- https://testing.openlibrary.org/search?q=format%3A%22Web+book%22&mode=everything&page=2

### Reproducing the bug

1. Go to https://testing.openlibrary.org/search?q=format%3A%22Web+book%22&mode=everything&page=2
2. Click the Read button for a result that wouldn't use `direct_read_button.html`, such as OpenStax or Standard Ebooks.
3. Also click a result that would use the `DirectProvider`, other than the first result to use `DirectProvider`.

* Expected behavior: the toast displays the correct text.
* Actual behavior: the toast (1) always displays the text for a `DirectProvider` / `direct_read_button.html`, and (2) always displays the toast assocaited with the first rendering of the `direct_read_button.html` template.

Edited 2024-07-30 to
- correct the problem statement; and
- add another problem statement.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

@cdrini
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Bumping to P1 since this bug is also causing the direct book provider to be incorrectly selected at times, which is a deploy blocker.
