### ISSUE TITLE
Update contributing docs to mention to select an issue with no assignee.

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9646]
### Problem

Right now the docs link to the good first issue with no assignee by default.
However, quite often people still request to be assigned to an issue that is already assigned to someone.
Perhaps this can be curbed if we are a bit more explicit to pick an issue that isn't already assigned.

#### Relevant URL(s)
https://github.com/internetarchive/openlibrary/blob/master/CONTRIBUTING.md

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by BHAV0207** [comment]
hey @RayBB  I would like to work on this issue

**Comment by cdrini** [comment]
+1 No assignee or if 2w of no response/activity from assignee.

**Comment by GarvitDadheech** [comment]
> +1 No assignee or if 2w of no response/activity from assignee.

Hii @cdrini , I have updated the CONTRIBUTING.md file to include this additional condition also.
Please review the changes and let me know if any further updates are needed.
Thank you!
