### ISSUE TITLE
Delete unused templates and endpoints

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9655]
### A clear and concise description of what you want to happen
We should check if the following templates (and their associated endpoints) can be deleted:
- `openlibrary/admin/templates/admin/index.html`
- `openlibrary/templates/account/email/forgot.html`

We should also delete the `class loans_admin` endpoint, which was associated with the recently deleted `openlibrary/templates/admin/loans.html` (see #9507 for the PR where this was deleted, though it is likely not relevant).

It _appears_ that `openlibrary/templates/account/email/forgot.html` can be deleted, on the theory it is not linked to anywhere, though I only gave this a cursory glance. If it can be deleted, we should delete the endpoint as well. It is still functional and the template still works, so we should be certain it is no longer in use.

Another candidate for deletion is `openlibrary/admin/templates/admin/index.html`, which appears to be an older version of `openlibrary/templates/admin/index.html`.

### Additional Context
To complete this issue, please (1) check whether the templates and endpoints can be deleted and (2) articulate the testing/research you did to ensure the files/classes/functions can indeed be deleted.

### Stakeholders

@cdrini 
<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by kohantikanath** [comment]
Hi @scottbarnes,

I would love to work on this issue, can you assign me this issue

**Comment by scottbarnes** [comment]
I've assigned it to you, @kohantikanath. Please let me know if you have any questions. :)

**Comment by kohantikanath** [comment]
Thanks, @scottbarnes. I’ll start by checking if the templates and endpoints can be deleted and will document my findings and testing process. I'll keep you updated on the progress.

**Comment by lokendra005** [comment]
Is the issue closed @scottbarnes  or can I take this issue

**Comment by scottbarnes** [comment]
@kohantikanath, how are things going on this issue? Any questions?

**Comment by kohantikanath** [comment]
Hi @scottbarnes,
I’m actively working on it and will update you soon. Let me know if you have any questions in the meantime.

**Comment by scottbarnes** [comment]
Sounds good. Thanks for the update, @kohantikanath.

**Comment by kohantikanath** [comment]
Hi @scottbarnes,
I have raised a PR that addresses this issue; please review it.

**Comment by scottbarnes** [comment]
Thanks for this, @kohantikanath. We'll need to get a bit more feedback from some others, so hopefully I can have any final feedback for you later in the week.
