### ISSUE TITLE
Add # people who "have" or "want" to read book on books page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#966]
Right now there's no indicator of how many people have put a book on their reading log. On the book page, perhaps we want (somewhere) a line that says, e.g. "24 people have read this books, 15 want to read"

**Comment by maurachur** [comment]
I'm going to take a stab at this today! 🎉

**Comment by viccro** [comment]
Should this issue be closed?

**Comment by mekarpeles** [comment]
Yes, thank you!
