### ISSUE TITLE
Move config/author.yml out of infogami, into version controlled file

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9666]
### A clear and concise description of what you want to happen

This means moving the author identifiers out of infogami and into a separate file in our repo, similar to what we did with editions in #9234 and #9483

The process should be near identical to the solution we implemented in #9483 for editions.yml.

### Stakeholders

<hr>

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by jenish-thapa** [comment]
Hey @mekarpeles,

I would like to work on this issue. Can you please assign it me?

**Comment by charanbhatia** [comment]
@mekarpeles  can you assign this issue to me?

**Comment by Tim-Quattrochi** [comment]
@mekarpeles I am interested in contributing, can I take on this issue?

**Comment by lokendra005** [comment]
@mekarpeles can you please assign this issue to me

**Comment by jimchamp** [comment]
Thanks for your patience.  @jenish-thapa, do you still want to work on this issue?

**Comment by jimchamp** [comment]
@fakegithub01, you've been assigned.  Please let me know if you have any questions.

**Comment by fakegithub01** [comment]
@jimchamp I’m unable to locate the `config/author.yml` file in the specified path. The screenshots below show the directories and paths I’ve checked. Can you please provide further guidance or confirm if the file is missing?

![Screenshot 1](https://github.com/user-attachments/assets/1138c8a5-9971-408e-b496-756fbacf928e)
![Screenshot 2](https://github.com/user-attachments/assets/69d5061d-c542-4bb6-8062-2a548cdd3136)

**Comment by Freso** [comment]
`author.yml` doesn’t exist in the repository yet–the purpose of this PR is to make it. See https://github.com/internetarchive/openlibrary/pull/9483 for how that was done for `editions.yml`.

The current `author.yml` used by OL lives at https://openlibrary.org/config/author.yml

**Comment by fakegithub01** [comment]
@jimchamp please review this PR and let me know if there is any issue

**Comment by fakegithub01** [comment]
> @jimchamp please review this PR and let me know if there is any issue

Please  review this PR @jimchamp.

**Comment by fakegithub01** [comment]
@jimchamp please review the PR.
