### ISSUE TITLE
Subtitle in work's title should not be applied to editions if no edition subtitle present

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#967]
The subtitle is not usually applicable to all editions. Translations in particular. Example: https://openlibrary.org/books/OL26414568M/Farbenblind

**Comment by LeadSongDog** [comment]
@mekarpeles 
For illustration:
![transl_subt](https://user-images.githubusercontent.com/11435431/59943787-236a7b00-9431-11e9-8ec2-dfb87b1abf81.jpg)

**Comment by guyjeangilles** [comment]
@seabelis @LeadSongDog @mekarpeles I can not duplicate this bug. I'm marking it for proposed closure. Let me know if you agree or disagree.

**Comment by seabelis** [comment]
Still an issue. See this example, https://openlibrary.org/books/OL26414568M/Farbenblind. This is the German edition and does not have a subtitle. The subtitle from the work is appearing below the German edition title.

**Comment by mekarpeles** [comment]
I think I disagree with this issue. Especially given our goal is to have one page, considering the future that there will not be a fundamentally different Page between a work and edition. It seems like showing whatever information we have it's better than removing or hiding fields where our data is messy.

If anything I'd rather show the work title and subtitle I need action page and then show what this specific edition title is.

**Comment by cdrini** [comment]
The current implementation is broken as is, so this is fine. We can change it once we have a better plan. (See https://dev.openlibrary.org/books/OL26414568M/Farbenblind ). I don't see a reason to block the open PR on this. This isn't messy data; the data is entirely correct in this case.

**Comment by cdrini** [comment]
> If anything I'd rather show the work title and subtitle I need action page and then show what this specific edition title is.
Is there a typo here?

**Comment by tfmorris** [comment]
Independent of whether there's a single page style or two, editions and works will always be different types of things. Fusing data across multiple records, let alone multiple types of records is very tricky to get right. 

Some cases to consider:
* work has subtitle (delimited as expected by ':'), edition is the same language, has title in title field and no subtitle
* edition as subtitle in title field delimited by a ':'
* edition is in a different language
* edition as subtitle in subtitle field

Only the first case is improved in the current implementation. The last case is correct regardless. What's unknown is the distribution of prevalence for the first three cases which would be useful data to help decide what the best balance is here.

Not that when we migrate to a single page type, it'll probably be mostly an edition page, populated with some data from the work, but perhaps not the work title until we can make significant progress on multiple language titles for works.

**Comment by seabelis** [comment]
> Only the first case is improved in the current implementation. 
Only in cases where all editions of that language have the same subtitle and the title has never been changed. This is not always the case; [UK and US titles frequently vary](https://openlibrary.org/works/OL16654793W/Far_From_the_Tree); sometimes the publishers c[hange the title for later editions](https://openlibrary.org/works/OL5833520W/The_Flavor_Point_Diet) or drop the subtitle altogether (https://archive.org/details/adventhuckfinn00twairich/page/n11 vs https://archive.org/details/adventuresofhu00twai/page/n5). The edition record should always reflect that edition accurately.

**Comment by LeadSongDog** [comment]
For the above translation example, comparing https://openlibrary.org/books/OL6929275M/The_French_impressionists?v=3 to https://openlibrary.org/books/OL6929275M/The_French_impressionists?v=4
note that the presence of an edition subtitle will override the display of a work subtitle. The work subtitle is only seen on the edition if there is no edition-specific subtitle.
