### ISSUE TITLE
`feedparser` relies on `cgi` (slated for removal in Python 3.13)

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9678]
### Problem

`feedparser==6.0.10` (the pinned version in `requirements.txt`) relies on the deprecated `cgi` package, slated to be removed in Python 3.13.

#### Evidence / Screenshot
Noticed during a run of the Open Library Python test suite:
```
../home/openlibrary/.local/lib/python3.12/site-packages/feedparser/encodings.py:29
  /home/openlibrary/.local/lib/python3.12/site-packages/feedparser/encodings.py:29: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

Per the [changelog](https://feedparser.readthedocs.io/en/latest/changelog.html#id1) this is fixed in `6.0.11`:
> Resolve cgi module deprecation warnings. (#330)

The commit to close https://github.com/kurtmckee/feedparser/issues/330 says the `6.0.11` release only includes changes to address the `cgi` dependency, so it's likely a safe upgrade: https://github.com/kurtmckee/feedparser/pull/417.

However, `feedparser` is used in `scripts/import_standard_ebooks.py`, so running that import with `6.0.11` should give a definitive answer as to whether all that's required is a version bump.

#### Relevant URL(s)
- https://feedparser.readthedocs.io/en/latest/changelog.html#id1
- https://github.com/kurtmckee/feedparser/pull/417

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Breakdown: Proposal & constraints

Solution is to increment the version of the library to `6.0.11` and run tests

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by smitrami-123** [comment]
Hey @scottbarnes  If this issue is still not resolved, can you please assign it to me?

**Comment by scottbarnes** [comment]
Alas, @smitrami-123, @renovate-bot was too quick on the draw this time. [This query](https://github.com/internetarchive/openlibrary/issues?q=is%3Aopen+is%3Aissue+-label%3A%22Needs%3A+Breakdown%22%2C%22Needs%3A+Lead%22%2C%22Needs%3A+Designs%22%2C%22Needs%3A+Triage%22+label%3A%22Good+first+issue%22+no%3Aassignee+is%3Aopen+-linked%3Apr) for Good First Issues is a good place to check, though there are not many issues there just now.
