### ISSUE TITLE
Changes to import API to support importing from Koha/bots

### ISSUE THREAD

**Issue by nibrahim** [internetarchive/openlibrary#97]
The import API right now needs to be modified a bit to allow searching and importing in the way that Koha needs it. This issue tracks work on that. 

First task is to decouple search from import. 

The `load` method currently does both. We need to do these two separately. Work is being done on nibrahim/openlibrary in the ils-api branch

**Comment by brad2014** [comment]
@mekarpeles, is this stale?  Still an issue?

**Comment by guyjeangilles** [comment]
The [openlibrary-client](https://github.com/internetarchive/openlibrary-client) fixes a lot of not all of these issues. Closing. Feel free to reopen for a _specific_ feature that needs to be adde
