### ISSUE TITLE
Removed author lingers in edition record json after deletion from work record

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#970]
At https://openlibrary.org/works/OL9633997W/Old_New_York?b=3&a=2&_compare=Compare&m=diff
I removed the last use of a bogus (compound) author record, OL3630793A, but it still persists in the json of an edition record https://openlibrary.org/books/OL11437957M.json which reads
`{"publishers": ["B&R Samizdat Express"], "languages": [{"key": "/languages/eng"}], "classifications": {}, "weight": "1.6 ounces", "title": "Old New York", "identifiers": {"goodreads": ["2639320"]}, "isbn_13": ["9780917466755"], "covers": [2686044], "created": {"type": "/type/datetime", "value": "2008-04-30T09:38:13.731961"}, "physical_format": "CD-ROM", "authors": [{"key": "/authors/OL3630793A"}], "isbn_10": ["0917466756"], "latest_revision": 6, "key": "/books/OL11437957M", "last_modified": {"type": "/type/datetime", "value": "2018-05-25T04:02:58.906659"}, "publish_date": "January 7, 2007", "works": [{"key": "/works/OL9633997W"}], "type": {"key": "/type/edition"}, "subjects": ["Literature & Fiction / Literature"], "physical_dimensions": "5.5 x 4.8 x 0.2 inches", "revision": 6}`

It is not clear why the author record is mentioned at all in the edition record. Surely that is what the work record is for. 

The impact is that the bogus author record cannot be deleted.
`"This Author page cannot be deleted as 1 record(s) still reference this id. Please remove or reassign before trying again. Referenced by: ['/books/OL11437957M']"`

**Comment by hornc** [comment]
@LeadSongDog I have removed that hanging author from the edition record. You should be able to delete the bogus author now.

Before the work level records were created, authors were just on the edition record, so many still have authors, even though there isn't a UI for modifying them.

**Comment by LeadSongDog** [comment]
Seems like something that could be better automated.

**Comment by guyjeangilles** [comment]
@hornc Are there plans to remove this authors from edition records? As mentioned, it seems like an easy process to automate.

**Comment by cdrini** [comment]
Despite this being older, closing in favour of #2625 since that has more discussion/context
