### ISSUE TITLE
Lists created on search page initially appear checked in every dropper

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#9701]
### Background
Patrons are able to create lists of books using the "Create a new list" option found inside of the "My Books" droppers.  Each of these droppers contain a number of actions that can be taken one a single book.  Whenever a new list is created using the "Create a new list" option, the book that is associated with the dropper is automatically added to the new list and the list will appear in all "My Books" droppers on the page.

### Problem
On pages where there are multiple "My Books" droppers, like our work search results page, creating a new list causes the new list to appear with a checkmark in every dropper.  The checkmark indicates that the book associated with the dropper is on a list, and should only appear next to the list in the dropper where the list was created.
For example, if I were to use the "My Books" dropper in the first search result to create a list named `My Brand New List`, an entry for `My Brand New List` _should_ appear in all droppers, but only have a checkmark in the first dropper.

If the page is refreshed after creating a new list, the new list will only be checked in the expected dropper.  This indicates that everything is working as expected on the server-side when a new list is created.  The issue lies with the client-side code.

#### Relevant URL(s)

https://openlibrary.org/search

### Reproducing the bug

1. Go to the `/search` page, and ensure that there are multiple search results.
2. Using the "My Books" dropper found in the first search result, create a new list.

* Expected behavior: The new list appears in each dropper, but is only checked in the first dropper.
* Actual behavior: The new list appears in each dropper, and it is checked in each dropper.

### Context

- Browser (Chrome, Safari, Firefox, etc): Any
- OS (Windows, Mac, etc): Any
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Proposal & constraints

The [`createDropdownListAffordance`](https://github.com/internetarchive/openlibrary/blob/79dccb33ad74f3e9f16e69dce2bae7a568c8d3d0/openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper/ReadingLists.js#L336) function is used to add an entry for a new list to a "My Books" dropper.  This function has a boolean parameter named `isActive`, which, when true, indicates that the new entry should have a checkmark.

When a new list is created via a "My Books" dropper, the [`updateDroppersOnListCreation`](https://github.com/internetarchive/openlibrary/blob/79dccb33ad74f3e9f16e69dce2bae7a568c8d3d0/openlibrary/plugins/openlibrary/js/my-books/CreateListForm.js#L121) function is used to add the new list entry to every dropper on the page.  `isActive` is initially set here for each dropper, and passed along to the dropper's `createDropdownListAffordance` function via [`onListCreationSuccess`](https://github.com/internetarchive/openlibrary/blob/79dccb33ad74f3e9f16e69dce2bae7a568c8d3d0/openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper/ReadingLists.js#L308C5-L308C26).

Using this information, determine why `isActive` is never false when these new list entries are created.

#### Related files

Code for the list entries in "My Books" droppers:
https://github.com/internetarchive/openlibrary/blob/79dccb33ad74f3e9f16e69dce2bae7a568c8d3d0/openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper/ReadingLists.js

Code for list creation form:
https://github.com/internetarchive/openlibrary/blob/79dccb33ad74f3e9f16e69dce2bae7a568c8d3d0/openlibrary/plugins/openlibrary/js/my-books/CreateListForm.js

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by EdDiazGRS** [comment]
Hi, I would love to take a crack at this. This would be a great first issue for me.

**Comment by jimchamp** [comment]
@EdDiazGRS, you have been assigned.  Please let me know if you have any questions about anything.

**Comment by Suswetha6** [comment]
Hey,can i work on this issue ?

**Comment by jimchamp** [comment]
@Suswetha6, this issue is already assigned to @EdDiazGRS.

@EdDiazGRS, please update me on your progress.

**Comment by EdDiazGRS** [comment]
@jimchamp , I'm currently working on it and I anticipated to be done by Friday.

**Comment by TheBlueSummon** [comment]
@jimchamp Could you please assign me to this issue, I would love to try fixing!!!

**Comment by jimchamp** [comment]
You've been assigned, @TheBlueSummon.  Feel free to post any questions that you may have here.

**Comment by TheBlueSummon** [comment]
@jimchamp How do I test it locally to see if I actually fixed it (deploying the website locally ig)? I tried running $ docker compose run --rm home make test but after a while it just says "Validation passed!".

**Comment by jimchamp** [comment]
1. Before making any code changes, try to reproduce the bug in your local instance.
2. After reproducing the bug, make any necessary changes and rebuild the code.
3. Reload the search page and attempt to reproduce the bug.
4. Repeat steps 2 and 3 until you've arrived at a solution.

**Comment by EmilyIsCoding** [comment]
Hello, may I take on this issue? I believe it's a simple fix in `openlibrary\plugins\openlibrary\js\my-books\CreateListForm.js` line 127 where `isActive` and `coverUrl` need to be swapped to follow the order of `onListCreationSuccess(listKey, listTitle, isActive, coverUrl)`.

**Comment by jimchamp** [comment]
Go for it, @EmilyIsCoding.

**Comment by EmilyIsCoding** [comment]
Thanks Jim, I submitted the PR! Let me know if it looks good :) https://github.com/internetarchive/openlibrary/pull/9999
