### ISSUE TITLE
author auto complete having templating issues for counts and titles

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9718]
#### Evidence / Screenshot
<img width="727" alt="image" src="https://github.com/user-attachments/assets/cc7ad2a9-5ad6-41da-b283-9a7bd3f8734d">

#### Relevant URL(s)
https://openlibrary.org/books/OL26403554M/Journalism_after_Snowden/edit?work_key=/works/OL17814219W

### Reproducing the bug

See screenshot

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Mac 
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

@rebecca-shoptaw any ideas what this might come from?
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by rebecca-shoptaw** [comment]
Uh oh! Yes, me and @cdrini just encountered this `jsdef` issue with the `%s`/`%d` formatting, fixed another case of it in #9708. 

I'll do a quick scan to make sure there's no other new i18n-ed text that might be having the same effect, but fingers crossed this is the last of it!
