### ISSUE TITLE
Look up OL id given archive.org id

### ISSUE THREAD

**Issue by avidseeker** [internetarchive/openlibrary#9720]
### Problem

Currently, [bibkeys](https://openlibrary.org/dev/docs/api/books#data) only have: ISBN, OCLC, LCCN, OLID as identifiers. 

It might be argued that archive.org identifiers are not really identifiers for books since they actually identify is a scan of a book. What I'm requesting is to have a way to specify some 3rd party identifier in the API as in a query:

1. https://openlibrary.org/dev/docs/api/search
2. https://openlibrary.org/search/howto

Include examples like `title_suggest:"vitamin a"`

**Comment by cdrini** [comment]
You can use the search API:

For a single book: https://openlibrary.org/search?q=ia%3Agoody
For multiple books: https://openlibrary.org/search?q=ia%3A%28goody+OR+goodytwoshoes00newyiala%29&mode=everything

For the API, you can change to `search.json` and add the editions field to get metadata about the specific book. eg. https://openlibrary.org/search.json?q=ia%3A(goody+OR+goodytwoshoes00newyiala)&mode=everything&fields=key,title,author_key,author_name,editions,ia
