### ISSUE TITLE
Identify UI elements that are not yet covered by i18n

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#973]
Currently 
1) many, but not all, UI messages are wrapped in calls to Python's gettext, via `_("string")`
and 
2) not all pages are included in the i18n-messages builder script https://github.com/internetarchive/openlibrary/blob/master/scripts/i18n-messages

1 Will generally be unintentional, and should be remedied, 
2 Is currently deliberate to avoid translating many old templates that are no longer active.

The scope of this task is to review the main user facing pages and ensure all messages that should be translatable are.

This will ensure that when translators begin a translation, they are covering all messages on the site, and we will not need updates as more message are discovered and added.
 

The plan is to create a full site French translation, adding to the great work already in https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n/fr as the first full non-English message set.

*To review:*

- [x] New user sign-up
- [x] Login
- [x] Home page
- [x] Account Options
  - [x] Loans
  - [x] Lists
  - [x] Profile
  - [x] Settings
- [x] Search results
- [x] Work View
- [x] Edition View
- [x] Author View
- [x] Subjects page
- [ ] Add book flow
- [x] Edit pages for A/W/E
- [ ] Librarian mode edit messaging
- [x] History
- [ ] Site error messages

**Comment by nemobis** [comment]
Good plan! I would add that the deliberately escluded strings, if they're still in use anywhere, could be added to a lower priority web translation project, e.g. by [setting it up on translatewiki.net](https://translatewiki.net/wiki/Translating:New_project).

**Comment by brad2014** [comment]
We may also decide to do this as a part of #2190

**Comment by tfmorris** [comment]
Almost everything created or edited in the last few years has ignored internationalization. We should start with the most visible elements (e.g. the home page!) so that potential translators don't immediately get discouraged by not seeing anything change.

**Comment by justcomplaining** [comment]
Another big issue is the missing possibility to translate the _subjects_ and _places_!

**Comment by tfmorris** [comment]
Most of this is covered in #2442. I'll update the checklist above as I review the various pages.

**Comment by tfmorris** [comment]
> Another big issue is the missing possibility to translate the _subjects_ and _places_!

Subjects have been discussed a number of times both in the context of translation and search aliases, but I couldn't find a ticket that actually addressed it directly, so I've added #2819 

@justcomplaining Could you expand on your comment about places? In what context? Places as subjects or places of publication or ...? If you think it's an important feature, perhaps create a new ticket to describe your request in more detail.

**Comment by justcomplaining** [comment]
> @justcomplaining Could you expand on your comment about places? In what context? Places as subjects or places of publication or ...? If you think it's an important feature, perhaps create a new ticket to describe your request in more detail.

I was originally thinking about places as subjects, but places of publication are indeed also in need of translation, as are languages and even people (Jeanne D'Arc vs. Joan of Arc for example) or times (e.g. House of Lancaster, 1399-1461).

**Comment by tfmorris** [comment]
Fixing subjects will take care of all flavors of subjects (topics, people, places). Unclear whether subject time periods would get the same treatment or something special, but they'd be internationalized either way.

Publication places are very irregular, context dependent, and require a lot of heavy-duty matching/reconciliation on import. Additionally, I think they're low value, so they're pretty low on my priority list.
