### ISSUE TITLE
Book dimensions negative or equal to zero

### ISSUE THREAD

**Issue by manoelmour** [internetarchive/openlibrary#9731]
### Problem

Currently, the site allows the book dimensions to be negative or equal to zero.

### Proposal & Constraints

I believe it would be useful if, on the book editing screen, a pop-up appeared when the book dimensions are negative or zero, alerting the user that the dimensions need to be corrected.

**Comment by Souvik-Cyclic** [comment]
I would like to work on this.

**Comment by charanbhatia** [comment]
@manoelmour @gojomo @mekarpeles can you please assign this issue to me? I want to work on this issue.

**Comment by mekarpeles** [comment]
Thanks for the offer @charanbhatia! I've assigned @Souvik-Cyclic to this one as they asked earlier and have submitted a PR.
