### ISSUE TITLE
Want to remove learnawesome.org from the identifiers list but edition config has been removed

### ISSUE THREAD

**Issue by nileshtrivedi** [internetarchive/openlibrary#9747]
LearnAwesome.org was added to the identifiers list about 4 years ago in #3383 .

But this domain is no longer active. The devs of learnawesome project had recently discontinued work on it. The domain has now been taken over by some trash slot games site.

I wanted to remove this domain from the edition config file but this seems to have been removed by @mekarpeles a [few weeks ago](https://github.com/internetarchive/openlibrary/commit/af72a036b0beb9069ee428bf850b653a916d8335).

I'm not clear on how to remove this. Keep in mind that the "deployment" of these changes to identifiers list [was done manually](https://github.com/internetarchive/openlibrary/pull/3383#issuecomment-622569969) by @cdrini .

We should also remove the identifiers that were added over this period.

**Comment by jimchamp** [comment]
Deleting [these lines](https://github.com/internetarchive/openlibrary/blob/1a6fde92e3bbd921736d34581ad885c3e4d0e0a4/openlibrary/plugins/openlibrary/config/edition/identifiers.yml#L194-L197) will remove `learnawesome.org` from the editions identifiers list.

**Comment by nileshtrivedi** [comment]
@jimchamp Thanks. I can submit a PR for this. Do you know how to go about deleting the actual identifiers values that were added for various books?

**Comment by cdrini** [comment]
There were 6 identifiers added to the site: https://openlibrary.org/query.json?type=/type/edition&identifiers.learnawesome~=*& .

Note in general we do support having identifiers from no longer active sites, since they can still be useful. But since this site never really had an impact, I think we can drop it.
