### ISSUE TITLE
Creating Open Library records should trigger "already exist" checks

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#977]
Right now there are several ways to POST / create `thing`s on OpenLibrary.

ImportBot, Add Book, POSTing to `/edit` may potentially all produce different outputs and do different (or no) checks to see if Authors, Works, and Editions exist before.

This issue proposes it be a requirement that all methods of record creations should be routed through/to the (a single point of truth) same checks and prevent records from being created if they are presumed to result in a duplicate (i.e. return `{"warning": "already exists", "match": "OL...W"}`.

This change to the API should make it so Add Book, ImportBot, and any other author, edition, or work POST / create must run/obey these checks.

This change may provide an `override` param to either create or update an Author, Work, Edition, etc, if the creator is reasonable sure what they want to do. If the initial request results in (e.g.) a warning, one might add `override=update` to force an update or `override=create` to force creation of a new record.

**Comment by LeadSongDog** [comment]
Rather than "simulate" users will be more used to "preview", but yes, there's much to be gained by doing this

**Comment by mekarpeles** [comment]
@hornc is this fixed / can this be closed?

**Comment by hornc** [comment]
Current [import APIs](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/importapi/code.py) use `catalog.add_book` https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/add_book/__init__.py

which checks whether an edition is already in the system, and will add it, and a Work and Author if they do not already exist.

Currently the UI add book uses a different path. I thought we had an issue to deal with this but I can't find it right now. The closest I found is #1163

**Comment by guyjeangilles** [comment]
@hornc I added backlogged and refactor labels to this issue based on the thread. Let me know your thoughts

**Comment by hornc** [comment]
as in comment above

Current import APIs use catalog.add_book https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/add_book/__init__.py

which checks whether an edition is already in the system, and will add it, and a Work and Author if they do not already exist.

The add book UI also checks for existing editions:
https://github.com/internetarchive/openlibrary/blob/1aa081278c389cc9dce1c5a83c1eba62c98e013a/openlibrary/plugins/upstream/addbook.py#L261

At some point these should be combined as part of a greater refactor, but the checks exist.
