### ISSUE TITLE
Facets are inconsistently presented

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#978]
Comparing
https://openlibrary.org/search?q=homer&mode=everything
to
https://openlibrary.org/authors/OL6848355A/Homer
one sees that the facets offered for result filtering in the former case are not offered as filters in the latter but as independent searches, even though they would be very useful in filtering specific results.  Further, they appear very similar in both cases, leading to user confusion.

**Comment by tfmorris** [comment]
My interpretation is that the items listed on the author page aren't facets, so perhaps that distinction needs to be made clearer to the user.

**Comment by LeadSongDog** [comment]
@tfmorris That's kind of my point. They aren't implemented as facets on the latter page, but why not? The use-cases are, in one case, author specific, and in the other case all-works-on-this-subject-by-any-author.
Certainly I see both use cases having merit but why is it distinct between these two pages? Wouldn't it be better to offer users a choice between filter-by-facet or all-with-this-facet?

**Comment by jdlrobson** [comment]
@LeadSongDog sorry to be a newbie but can you clarify what you mean by facets here? Can you add some screenshots?

**Comment by LeadSongDog** [comment]
Sure. Facetted search (where it works) is a way of refining search results.

The search by author name yields:
![facets](https://user-images.githubusercontent.com/11435431/47225535-5503e180-d38c-11e8-9f9e-c73bdee1edec.jpg)

Selecting two "Subject" facets "In Library" and "Protected Daisy" yields:
![selected facets](https://user-images.githubusercontent.com/11435431/47225567-61883a00-d38c-11e8-9d19-fc0fbd176ef5.jpg)

But on the author page, the "Subject" list is not facetted:
![not facets](https://user-images.githubusercontent.com/11435431/47225623-841a5300-d38c-11e8-81eb-cd63806dcd24.png)

Clicking "Protected Daisy" in that subject list yields a null result message.

**Comment by jdlrobson** [comment]
Thank you for this detailed explanation @LeadSongDog !!

**Comment by LeadSongDog** [comment]
To me clear, faceting should be extended not just to author pages, but to the work, book, subject, etc. pages too. We may need to clear up the nature of the "Zoom in: Focus your results using these filters" action.

**Comment by guyjeangilles** [comment]
This issues is still relevent. Assigning jdlrobson (not tagging per request) per slack discussions since this is front-end related

**Comment by mekarpeles** [comment]
I think the idea of adding facets to the author page is reasonable as a feature request, but I just don't think we have the bandwidth to take this one on. I am going to tentative close as `Will Not Fix` though am glad for anyone who really cares passionately about this issue to revive, re-open and champion. I have a hunch this is actually quite a bit of work and our time may be better spent choosing something from https://github.com/internetarchive/openlibrary/milestone/33
