### ISSUE TITLE
Add Library of Congress Name Authority File (LC NAF) as identifier type

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#9791]
The Library of Congress Name Authority File is a strong identifier which should be supported for authors.

>> I'm not sure exactly where to extract these ids to in OL's data model.
>
> I think they go in `identifiers`. I'm not sure why LC NAF isn't one of OpenLibrary's identifier options, but that's where I'd put all the ones listed above (in their primitive, not URI, form i.e. nr92001540 not http://id.loc.gov/authorities/names/nr92001540), assuming that LC NAF gets added as a valid identifier.

_Originally posted by @tfmorris in https://github.com/internetarchive/openlibrary/issues/7724#issuecomment-1489516286_

**Comment by tfmorris** [comment]
pinging @mekarpeles for triage since it didn't get fancy template labels

**Comment by mekarpeles** [comment]
# Breakdown

Related files:
https://github.com/nileshtrivedi/openlibrary/blob/master/openlibrary/plugins/openlibrary/config/edition/identifiers.yml

**Comment by tfmorris** [comment]
Unblocked by the merge of #9769.

This could probably be expanded to include other national library identifiers like GND, BNF, etc in addition to LC NAF. It's weird that random outliers like Inventaire and Storygraph are included when national libraries aren't.

Of course, the first choice should be Wikidata, if an entry exists, since that forms the hub to all the other identifiers, but some authors have LCNAF, VIAF, GND, etc but not Wikidata.
