### ISSUE TITLE
Page rendering error when following ISBN link from Wikipedia

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#980]
This Wikipedia book source page: https://en.wikipedia.org/wiki/Special:BookSources/0-9540278-0-9
generates this link: https://openlibrary.org/search?isbn=0954027809&mode=everything
and clicking on it gave the error: 

> /opt/openlibrary/deploys/openlibrary/6c88916/openlibrary/templates/work_search.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'startswith' (falling back to default template)

Unfortunately (fortunately?) the error appears to have been transient, but if there was an underlying system error, a more reasonable message should be shown to the user (e.g. "Please retry").

The error happened about 5 minutes ago (2018-06-06:19:45 UTC) is someone wants to dig through the logs to see what happened.

**Comment by jdlrobson** [comment]
Can this still be replicated?

**Comment by guyjeangilles** [comment]
The link on Wikipedia is: https://openlibrary.org/search?isbn=0954027809&mode=everything
Which successfully resolves to: https://openlibrary.org/books/OL8478904M/My_Life_in_Science

Closing as the issues  appears fixed

**Comment by tfmorris** [comment]
Empty search results still break the UI, but we've got several other issues covering that, so this can remain closed as a duplicate.
