### ISSUE TITLE
Improve error handling for JSON syntax errors on `/api/import`

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9818]
### Problem

Invalid JSON (e.g. a trailing comma), causes `/api/import` to spew quite a lot of irrelevant HTML. It would be nice if we could return a more helpful error, e.g., from the failed JSON unmarshaling.

```
❯ curl -X POST http://localhost:8080/api/import -H "Content-Type: application/json" -b ~/cookies.txt -d '{
    "title": "A Game of Thrones",
    "source_records": ["promise:9780553381689"],
    "isbn_13": ["9780553381689"],
}'


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"> 
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="title" content="" />
    <meta name="keywords" content="free books, books to read, free ebooks, audio books, read books for free, read books online, online library">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="OpenLibrary.org" />
... full output omitted...
```

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ] Show a more meaningful error when an import fails via `/import/api` when an import fails due to invalid JSON.

#### Related files

* `openlibrary/plugins/importapi/code.py`

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by DebbieSan** [comment]
Hello @scottbarnes, could I please work on this issue? TIA!

**Comment by scottbarnes** [comment]
Thanks, @DebbieSan. I've assigned this to you.
