### ISSUE TITLE
Extracting 8+ million Works (Search API)

### ISSUE THREAD

**Issue by d-beauchamp** [internetarchive/openlibrary#9822]
### Question
Hello! I'm new to using APIs and wanted to use the Open LIbrary Search API for a personal data pipeline project.

Is there a way to fully extract the results of a search that returns ~8 million works into a JSON file without encountering HTTP 500 errors/going over API limits? 

### Additional context
The query I made with the search API (`publish_year:[* TO 1975]`) returned a little over 8 million records. I made sure to include the necessary User-Agent header in my Python script and was able to extract about 2 million books until the process came to a standstill due to repeated 500 errors. I understand that this is probably due to limitations on bulk download mentioned on the API webpage!

I attempted to use the Works data dump as an alternative, but that didn't include all of the fields that I wanted from the data (e.g., `first_publish_year,` rating information). 

### Issue resolution criteria
I'd just like a little clarity on any alternative methods for extracting this amount of data without encountering errors while also having access to all the fields provided in the Search API. I know the API isn't meant for bulk download, so I'm interested in seeing if there's a third option available, or if there's a way to optimize the extraction.

**Comment by cdrini** [comment]
Hmm there might be an easy way for us to get you a dump for that to save you some hassle! Could you provide the exact search.json URL you were using?

**Comment by hornc** [comment]
@d-beauchamp Open Library data dumps are available here: https://openlibrary.org/developers/dumps
Downloading the entire edition set and filtering on dates as you need using the JSON should be considerably faster and more direct that using the API.
