### ISSUE TITLE
Fix typo in field name of Edition dump

### ISSUE THREAD

**Issue by shivam-tripathi** [internetarchive/openlibrary#983]
One of the edition dump field is named `dewry_decimal_class`.  I think it should be `dewey_decimal_class`?

**Comment by guyjeangilles** [comment]
@tabshaikh per slack discussions, assigning you to this easy issue. Feel free to unassign yourself and ping me.

**Comment by mekarpeles** [comment]
@shivam-tripathi would you like to try to fix this one? It would be a PR of correcting the files @LeadSongDog listed above.

**Comment by Kaushl2208** [comment]
If this issue is still open, Can I start working on it? @mekarpeles

**Comment by guyjeangilles** [comment]
@kaushl2208 feel free to make a pull request if you have a fix

**Comment by tfmorris** [comment]
This seems to have drifted pretty far from the originally reported bug, which I interpret to be about ol_dump_editions_2020-01-31.txt.gz. @hornc fixed that (single record) problem with this edit: https://openlibrary.org/books/OL7254013M/Centennial_remembrance_100_years--and_counting?_compare=Compare&b=18&a=17&m=diff

The three files that @LeadSongDog stumbled across are, as far as I know, unused and should probably be removed so as not to cause additional confusion.

I suspect that the typo existed, briefly, in the code base in 2011 when it both corrupted a record and got extracted into the i18n message files of the day.

I'll submit a PR to remove the obsolete files.

**Comment by tfmorris** [comment]
#871 addresses removing the obsolete files.
