### ISSUE TITLE
Autorenew SSL Certs w/ new Network Security Policies (via DNS ACME challenge)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9855]
### Proposal

testing.openlibrary.org had its cert outdated; saw it was hooked to the old godaddy cert. Jenkins also expired. Switched it with the following:

> [!IMPORTANT]  
> Everything should now be updated until Dec.

The following done manually to delete the old certs...
```
# Select testing and jenkins for deletion
sudo certbot delete
```

Edit and add a `_` before the `testing.openlibrary.org` and `jenkins` server_names; e.g. `server_name _testing.openlibrary.org` . Needed to expore the /var/www/html directory so that certbot can use it to make a file publicly accessible that it can use to verify the server.

```
sudo vim /etc/nginx/sites-enabled/default
# Edits...
sudo systemctl restart nginx
```

Generate the new certs:
```
sudo certbot certonly   --noninteractive --agree-tos   -m openlibrary@archive.org   --webroot --webroot-path /var/www/html -d testing.openlibrary.org
# Same for Jenkins ...
```

```
sudo vim /etc/nginx/sites-enabled/default
# Edits...
sudo systemctl restart nginx
```

#### Requirements Checklist

* [ ]

#### Related files

*

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Note: Need to also do the same for testing.

**Comment by mekarpeles** [comment]
Certs may be slightly more complicated with our new network security policies. Bumping to P1 for us to make sure we have down for prod + testing.

**Comment by mekarpeles** [comment]
Done by @scottbarnes
