### ISSUE TITLE
Add IMDb identifier for Authors

### ISSUE THREAD

**Issue by Freso** [internetarchive/openlibrary#9856]
### Proposal

Allow for assigning an IMDb identifier to OL Authors.

### Justification

<blockquote>More identifiers is more better!</blockquote>

IMDb is the de facto standard anglosphere identifier for actors and other people in the movie business. Given that a number of actors, directors, and other movie business people are also authors—not to mention authors whose manuscripts get movie adaptations—it would be nice to be able to link them directly to this other database.

(I don’t know if there’s a way to query how many `imdb.com` links are currently in the database.)

#### Requirements Checklist

* [ ] Add entry to `openlibrary/plugins/openlibrary/config/author/identifiers.yml`
* [ ] Deploy

#### Related files
* `openlibrary/plugins/openlibrary/config/author/identifiers.yml`

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by tfmorris** [comment]
This was only open for a few hours, which isn't very much time to comment, but I would like to question the statement:

> More identifiers is more better!

There are a large number of identifiers in the world, beyond a few key ones like important national libraries, I think OpenLibrary would be much better off improving it's linkage to Wikidata which has a much bigger community maintaining crosslinking identifiers to all and sundry (including OpenLibrary). The OpenLibrary community will never be able to keep up with the Wikidata community in this regard.
