### ISSUE TITLE
Show language in top bar language selector

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9864]
### Problem

<img width="728" alt="Screenshot 2024-09-10 at 9 15 21 AM" src="https://github.com/user-attachments/assets/d4d9af45-85af-42ea-be4e-4a76c2ba1276">

Goal: something like...

<img width="980" alt="Screenshot 2024-09-10 at 9 19 10 AM" src="https://github.com/user-attachments/assets/f86144c6-6330-4be2-b72b-9a95ab440a7e">

### Breakdown

See breakdown here:
https://github.com/internetarchive/openlibrary/pull/9868#issuecomment-2351679761

#### Requirements Checklist
* [ ] full "native" language appears next to logo for selected language 

#### Related files

* See https://github.com/internetarchive/openlibrary/pull/9868#issuecomment-2351679761

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by AkshataABhat** [comment]
hi @mekarpeles pls assign me this issue. I would like to work on it.

**Comment by jnettek** [comment]
Hi, Please assign me this issue. I got my environment set up and would like to taggle this as my first issue.

**Comment by AkshataABhat** [comment]
hi can I be assigned this issue pls @mekarpeles

**Comment by mekarpeles** [comment]
Hi @jnettek and @AkshataABhat -- thank you for the offer, @ChinoUkaegbu has a good start on this already with #9868 so I think they should be assigned (I will do so once after they comment here, as I can only assign people who have left a comment).

Happy to help you two find a good first issue! Also, if you send me an email to mek@archive.org, I can happily invite you to our slack channel where we can discuss further if that's helpful! Thank you for your generous offer to contribute!

**Comment by ChinoUkaegbu** [comment]
Hi, commenting to be assigned!

**Comment by jnettek** [comment]
Commenting!

**Comment by jnettek** [comment]
@mekarpeles email sent! :)

**Comment by AkshataABhat** [comment]
@mekarpeles sent an email! Pls check.
