### ISSUE TITLE
Docker services.web.env_file.0 must be a string

### ISSUE THREAD

**Issue by schu96** [internetarchive/openlibrary#9875]
### Problem
**This issue was caused by using an older version of Docker and fixed by upgrading to version 27.2.0**
Edit: The HOST variable is not set warning turned out to be irrelevant to this issue. I looked around within the compose.yaml file and managed to run the commands again after commenting out this section of the code:
```
env_file:
  -path: "env/web.env"
   required: false
```

Unable to run ```docker compose up -d``` or any docker commands related to OpenLibrary. Confirmed that docker installation works by running ```docker run hello-world```.

![image](https://github.com/user-attachments/assets/8fcf2f58-832a-4e28-892b-35d23262dd62)

### Context

- OS (Windows, Mac, etc): Windows WSL
- Logged in (Y/N): N
- Environment (prod, dev, local): dev

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Hmm, could you give us the version of docker you have? `docker --version`

**Comment by schu96** [comment]
Will do, the latest version of docker should be ok? I'll update and close this issue after I try running it again with a newer version

**Comment by cdrini** [comment]
Yep that should do the trick! Sweet, assuming that did the trick! 🥳
