### ISSUE TITLE
ISBN search imports DVDs from Amazon.com

### ISSUE THREAD

**Issue by stopregionblocking** [internetarchive/openlibrary#9879]
### Problem

The feature which allows Amazon.com records to be imported into OpenLibrary via searching for ISBNs will, unfortunately, import DVDs with ISBNs from Amazon.com, even if they are clearly indicated as not being books.

This was confirmed using the example of https://www.amazon.com/gp/product/1621064298

### Reproducing the bug

1. Search OpenLibrary for the ISBN of a DVD available on Amazon.com, but not included on OpenLibrary.
2. Search for the same ISBN again (to attempt an import of the record from Amazon.com).

* Expected behavior: Nothing is imported, because there is no book with that ISBN.
* Actual behavior: A DVD is imported, because it has an ISBN.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### Breakdown

The solution will likely involve some minor modifications to https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py so that DVDs don't return values to `get_products()`.

For the above DVD/item, `get_products()` returns: `[{'url': 'https://www.amazon.com/dp/1621064298/?tag=internetarchi-20', 'source_records': ['amazon:1621064298'], 'isbn_10': ['1621064298'], 'isbn_13': ['9781621064299'], 'price': '$15.19', 'price_amt': 1519, 'title': 'Homeland Insecurity: Films by Bill Brown', 'cover': 'https://m.media-amazon.com/images/I/41FuCUj3kUL._SL500_.jpg', 'authors': [{'name': 'Brown, Bill'}], 'publishers': ['Microcosm Publishing'], 'number_of_pages': None, 'edition_num': None, 'publish_date': 'Aug 01, 2007', 'product_group': 'DVD', 'physical_format': 'dvd'}]
`.

Of interest is `product_group` and `physical_format`. To complete this issue one would likely want to look at https://webservices.amazon.com/paapi5/documentation/ and determine why we should use `product_group`, `physical_format`, both, either, or something else to determine something is a DVD. Or maybe it's better to focus on what _is_ allowed (e.g. books).

In any event, we'll likely want to want to modify `serialize()` or `get_product()` to filter out DVDs (or only allow whatever constitutes books, if the cases are clear).

#### Requirements Checklist
* [ ] Read through https://webservices.amazon.com/paapi5/documentation/ (or other relevant documentation) and make a case for why we should filter based on `product_group`, `physical_format`, both, either, or something else to determine something is a DVD.
* [ ] Filter using the above criteria (e.g. `physical_format`) such that `get_product()` or `serialize()` will no longer return metadata for DVDS (e.g. if modifying `serialize()`, it should return `{}` -- `serialize()` may be the better option).
* [ ] Update the unit tests to include a case of a DVD being excluded and a book included in the results.

#### Related files

* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py
* https://github.com/internetarchive/openlibrary/blob/d3bb158bb517b6c32e37abf65275ee0cef31bfe8/openlibrary/core/vendors.py#L127-L167
* https://github.com/internetarchive/openlibrary/blob/d3bb158bb517b6c32e37abf65275ee0cef31bfe8/openlibrary/core/vendors.py#L123-L125
* https://github.com/internetarchive/openlibrary/blob/d3bb158bb517b6c32e37abf65275ee0cef31bfe8/openlibrary/core/vendors.py#L170-L294
* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/tests/core/test_vendors.py

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by scottbarnes** [comment]
Hi, @krthkmgndm, it sounds as if this issue may be a bit too daunting. It may make more sense to try a Good First Issue: https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22+-linked%3Apr.

**Comment by DebbieSan** [comment]
Hi @scottbarnes. I would like to work on this. I have an idea on how to tackle this issue :) ty!
