### ISSUE TITLE
Internationalize /stats/readinglog page

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#988]
The relevant template is in [openlibrary/templates/stats/readinglog.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/stats/readinglog.html)

re: https://github.com/internetarchive/openlibrary/pull/987#issuecomment-398280374

**Comment by tfmorris** [comment]
This is a low visibility page (not sure if it's linked from anywhere), but should be internationalized unless it's admin-only (don't think it is).

The relevant template is in openlibrary/templates/stats/readinglog.html
