### ISSUE TITLE
Search index no longer updating

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#9884]
### Problem

These [three works](https://openlibrary.org/search?q=title%3A+%22Molecular+Genetics+for+the+Clinician%22&mode=everything) which were merged over 14 hours ago are still showing up separately in search. Additionally author merges done both last night and today are not showing a complete set of works for the merged author.

https://openlibrary.org/authors/OL1688742A
https://openlibrary.org/authors/OL538962A
https://openlibrary.org/authors/OL7143320A
https://openlibrary.org/authors/OL2957541A

### Reproducing the bug

1. Click any of the links above
2. Do ...

* Expected behavior: Search index updated within minutes, preferably seconds
* Actual behavior: Search index not updated for over 14 hours

### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome
- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
We were having a storage issue on one of our servers; the issue is now resolved I believe. I restarted solr-updater to work from the 15th, it should be caught up in ~1hr or so I reckon.

**Comment by cdrini** [comment]
Still catching up seems like there were a lot of edits. Up to 2024-09-16T18:19:15, so likely <2h left
