### ISSUE TITLE
I am getting notifications, but I think I'm the wrong person.

### ISSUE THREAD

**Issue by mek** [internetarchive/openlibrary#9890]
### Question

I hate to comment here on an unrelated issue, but I have been getting notifications (my GitHub handler is @mek) on PR reviews from this group for a while. I believe the notifications are intended for @mekarpeles(?!?), and it occurred to me that he may not be getting them. 

Just wanted to pass the information along.

**Comment by mekarpeles** [comment]
Thank you :) I've been getting them as well as a repo subscriber! We'll try to do better to tag the right person moving forward
