### ISSUE TITLE
Delete `around_the_library.html` and `get_random_recent_changes` if unused

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9896]
### Problem

We should delete `openlibrary/templates/site/around_the_library.html` and `get_random_recent_changes` from `openlibrary/plugins/upstream/utils.py` if unused.

#### Requirements Checklist
* [ ] Verify the two things above are not called by anything besides perhaps one another by looking at the code (perhaps with the help of `git grep`).
* [ ] **IF** they are unused, delete the file and function.

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by JorgeSanchez-Encora** [comment]
Hello!, can this issue be assigned to me?

**Comment by scottbarnes** [comment]
@JorgeSanchez-Encora, I've assigned this to you. Because of the nature of this task, it's a bit hard to demonstrate it had no adverse effects across the entire site, but **if** you determine these things can be deleted, please explain the steps you took and your rationale in making that determination.

**Comment by siddarth2810** [comment]
Hiiii, I did  a grep search and found `get_random_recent_changes` was only used in the `around_the_library.html`. I think its safe to remove the function. 
![grep](https://github.com/user-attachments/assets/f711c819-24c5-4a7c-af27-82a60ce6af8f)

just to be safe, i also search `around_the_library` in the whole repo and found its only referenced in the `messages.po`. 

![atl](https://github.com/user-attachments/assets/6c13d254-fa34-47e2-a6b4-63fb965ff998)

so i think we can delete the file and the function like you suggested. Would love to hear your thoughts on this @scottbarnes

**Comment by siddarth2810** [comment]
If its alright, would love to take this up 😄

**Comment by JorgeSanchez-Encora** [comment]
Im sorry I got a little busy at work, it seems that siddarth has figure it out

**Comment by scottbarnes** [comment]
No worries at all, @JorgeSanchez-Encora. @siddarth2810, I've assigned this to you. Please let me know if you have any questions.
