### ISSUE TITLE
 internet archive: Your account has hit a lending limit 

### ISSUE THREAD

**Issue by Ahmad612** [internetarchive/openlibrary#9899]
Borrowing books error 
Is it a restriction made on borrowing books nowadays? 
I searched the FAQS and did not see any restriction imposed 
 The message which I have never seen it before is : 
Your account has hit a lending limit. Please try again later or contact the info@archive.org

**Comment by mekarpeles** [comment]
@Ahmad612 if you think something was done in error, please do contact info@archive.org with info about your use case so the team can investigate what may be happening.

**Comment by Edwasue** [comment]
https://github.com/internetarchive/openlibrary/issues/9899

**Comment by Ahmad612** [comment]
This happened long ago and I solved in time     ( solved ) 
Thank you
