### ISSUE TITLE
Styling regression in infogami pages w/ navigation links

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#992]
Somewhere along the line, we had a regression where navigation links on infogami pages are not rendering correctly --
![2018-06-20-141407_1600x900_scrot](https://user-images.githubusercontent.com/978325/41685113-585f8020-7494-11e8-8e55-97f6b039ef4f.png)

e.g. https://openlibrary.org/data

**Comment by tabshaikh** [comment]
Yes we are looking for something a bit less messy which suits the open library interface very well
