### ISSUE TITLE
Add a carousel with last month of new books

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#993]
Requested by https://twitter.com/HippieWiccan

**Comment by mekarpeles** [comment]
called "Newest Arrivals"

**Comment by mekarpeles** [comment]
This is the query which can be added to: 
`openlibrary/plugins/openlibrary/home.py` + `templates/home/index.html`
https://archive.org/search.php?query=openlibrary_work%3A%28%2A%29+AND+date%3A%5B2000+TO+%2A%5D+AND+publicdate%3A%5B2018+TO+%2A%5D+AND+%28collection%3Ainlibrary%29&and%5B%5D=loans__status__status%3A%22AVAILABLE%22&sort=-publicdate

**Comment by cdrini** [comment]
That query isn't doing what the title of this issue says. Can you explain it?
```
openlibrary_work:(*) AND
date:[2000 TO *] AND
publicdate:[2018 TO *] AND
(collection:inlibrary)
```

**Comment by mekarpeles** [comment]
The query above says something along the lines of, anything that is on Open Library which is somewhat modern (post 2000) which has been made public in 2018 (which we could even limit to the last month) and is borrowable. I pasted that in after trying a handful of queries and finding one which seemed to return reasonable results.

**Comment by cdrini** [comment]
@mekarpeles What's the difference between `date`, `scandate`, and `publicdate`?

**Comment by mekarpeles** [comment]
scandate is the day the book was scanned. publicdate is when the book was made public on archive.org, date... is the date the work was published, presumably?

**Comment by jdlrobson** [comment]
Because of the associated performance issues with adding a new carousel and more images, I don't want to mark this as easy.

**Comment by mekarpeles** [comment]
@JeffKaplan requested -- may be worth swapping this in (in exchange for another carouse). The query would be:
`$:render_template("home/custom_ia_carousel", title="New Arrivals", key="new_arrivals", query="collection:(inlibrary)", sorts=["publicdate+desc",], limit=42, test=test)`

**Comment by mekarpeles** [comment]
Closing this on myself.
