### ISSUE TITLE
Data collection and privacy policy of OpenLibrary APIs

### ISSUE THREAD

**Issue by amitharjani93** [internetarchive/openlibrary#9945]
What data is collected by the APIs and what are the terms of use for that data? I plan to use the API for a project but need to be sure of the privacy policy.

**Comment by mekarpeles** [comment]
Can you ask a more specific question about what data you need, what data you're concerned about, and what you're trying to achieve? 

See:
https://web.archive.org/web/20240000000000*/https://openlibrary.org/developers/licensing
https://web.archive.org/web/20240000000000*/https://openlibrary.org/help/faq/using#ownership
