### ISSUE TITLE
Hide link to all editions in edition table when number of featured editions is equal to total editions

### ISSUE THREAD

**Issue by SivanC** [internetarchive/openlibrary#9946]
### What is the change?
In the edition table, if the number of currently featured editions is equal to the total number of editions, display editions as if `?mode=all` was in the URL (i.e. with no text on top about featured and total editions)

### Why is it necessary?
Currently, there is a confusing and meaningless distinction between "featured editions" and all editions when all editions of a work are featured. Clicking the link to view all editions does not change the amount of editions or anything else.

## Relevant Designs

Current view:
![image](https://github.com/user-attachments/assets/843a9513-99c4-4ac6-bc45-5911ecaa286b)

With change:
![image](https://github.com/user-attachments/assets/610d390d-a3d2-49f7-9ec1-d0f951cead63)

### Stakeholders

@mekarpeles - Possibly a good first issue?

**Comment by Spaarsh** [comment]
Can this issued be assigned to me? 

Here is my approach to execute this:
The openlibrary\templates\type\work\editions_datatable.html file is used to render this particular page. In this html code, adding an additional "if not editions_limit or (len(editions) < work.edition_count)" will skip the code that displays the text about featured and total editions if the condition is not fulfilled.

**Comment by SivanC** [comment]
@Spaarsh Go for it! Let me know if you have any questions

**Comment by SivanC** [comment]
@Spaarsh Nice investigation!

Because `work.get_sorted_editions()` (passed as `editions` to this template) does not always return all editions of a work, depending on the parameters, `len(editions)` is not always the same as `work.edition_count`. You could probably test this by importing [this work](https://openlibrary.org/works/OL17930368W/Atomic_Habit) to your local environment. Make sure you import the book and all its editions as described [here](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data).

I think what happened here is that at some point, adding `?mode=ebooks` was the default when visiting the books page. This would have set `editions_limit` to `None`, making the conditional work as intended based on its definition. However, `ebooks` is no longer the default mode, so `editions_limit` will always be 10. 

Since the intended default value is `None`, I suggest that the definition be updated so that `editions_limit` is `None` when `query_param('mode')` is `None`, in edition to the current logic. This should fix the problem.

**Comment by Spaarsh** [comment]
You were right. I simply modified [view.html#56](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/edition/view.html) line to the following the artifact stopped occuring:
```html
$ editions_limit = None if query_param('mode') in ['all', 'ebooks', None] else 10
```
![image](https://github.com/user-attachments/assets/3d0db290-2314-439f-9d62-3ac19a73fa39)
I will commit this. Thanks!

**Comment by SivanC** [comment]
@Spaarsh Nice work!

As far as making a new branch for your work, yes, go for it! Please check out these [Open Library git best practices](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet) when making your branch/PR. It should be looked at on Monday.
