### ISSUE TITLE
Is openlibrary down??

### ISSUE THREAD

**Issue by AbelSturm** [internetarchive/openlibrary#9947]
This may be a dumb question, but is openlibrary, I can get it to work, I'm from Spain.
I don't see any opened issue that addresses this problem, and I can find anywhere a status/health check for the project/web.

Thanks -_-

**Comment by scottbarnes** [comment]
Unfortunately it is currently down. I don't know of an ETA for things being made available again, but Twitter/X is likely the best place for updates: https://x.com/internetarchive.

**Comment by AbelSturm** [comment]
I hadn't thought about Twitter. Thanks!

**Comment by AbelSturm** [comment]
Thanks, I hadn't thought about Twitter. Thanks!
