### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by rajmanna-dev** [internetarchive/openlibrary#9948]
When I'm trying to visit any of page including 'https://openlibrary.org/' home page, It shows "Looks like you lost your connection. Please check it and try again."

My connections are pretty fine. I facing this issue only with this website.

### Screenshots
![Screenshot 2024-10-11 195526](https://github.com/user-attachments/assets/3434c6fc-1a21-4367-896e-7df8687a76a4)

**Comment by RydalWater** [comment]
Same here, looks like the Open Library site (plus all APIs) is offline. 

<img width="646" alt="image" src="https://github.com/user-attachments/assets/a20d1e75-c508-4405-ae76-dca765e7a9fd">

**Comment by scottbarnes** [comment]
Unfortunately most Internet Archive services, including Open Library, are currently down. I don't know of an ETA for things being made available again, but the best place for updates include:
- https://x.com/internetarchive
- https://bsky.app/profile/did:plc:73dpznbu4wqwtcyurwbiulov
- https://mastodon.archive.org/deck/@internetarchive

**Comment by RydalWater** [comment]
Thanks for the update, will keep an eye out for more info
