### ISSUE TITLE
Improved image validation

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#9964]
### Proposal

Currently, Open Library's uploaded image validation is lacking. Let's make the following improvements to the validation process:

- Limit uploaded image size to 10mb
- Add server-side file extension check
- Use `Pillow` to verify that the file is, in fact, an image

#### Requirements Checklist

- [ ] Uploaded image sizes are restricted to no more than 10mb
- [ ] Image upload handler only accepts files with the following extensions: `jpg`, `jpeg`, `gif`, and `png`
- [ ] Image can be opened with `Pillow` without error ([example](https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#identify-image-files))

#### Related files

* [Image upload handler](https://github.com/internetarchive/openlibrary/blob/9e236ac766cd5783c737deb3397b54dadd415a30/openlibrary/plugins/upstream/covers.py#L27-L100)

#### Stakeholders

*

<hr>

#### Instructions for Contributors

Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Souvik-Cyclic** [comment]
I would like to work on this.

**Comment by mekarpeles** [comment]
Thank you @Souvik-Cyclic, give it a shot! @jimchamp is here to help as you have questions :)
