### ISSUE TITLE
[dodgy link]

### ISSUE THREAD

**Issue by Jayfluffy46** [internetarchive/openlibrary#9969]
This keeps popping up when ever it wants to on my phone what is this 
![Screenshot_20241030-035114](https://github.com/user-attachments/assets/cb12a8f2-ea81-4478-85bf-b59c122bdb72)

**Comment by seabelis** [comment]
Hi, @Jayfluffy46 . Can you please explain how this is an Open Library related issue?

**Comment by Jayfluffy46** [comment]
I'm just trying to find out where it's coming from and why. Sorry to bother anyone

**Comment by jimchamp** [comment]
Closing this issue, as it seems like spam.
