### ISSUE TITLE
Adjust padding of Browse dropdown menu to avoid dead space

### ISSUE THREAD

**Issue by SivanC** [internetarchive/openlibrary#9971]
### Change
Adjust the padding of the buttons in the "Browse" header dropdown menu to avoid unclickable areas
### Necessity
Currently, it is harder than it should be to click buttons in the dropdown, as 10px per button of vertical space cannot be clicked.
### Considerations
Requires just two lines to be changed, probably a good first issue.

## Relevant Designs

Current, unclickable space on top and bottom (outside the purple area):
![image](https://github.com/user-attachments/assets/d44eab32-f7a6-48b0-ba99-19328f4a30b5)

Padding now conforms to visible button area:
![image](https://github.com/user-attachments/assets/d0b5aceb-4e44-480c-800b-78258b97f5fd)

**Comment by mekarpeles** [comment]
@SivanC which two lines need to be changed? And does it make sense to open a PR for this one? :)
