### ISSUE TITLE
Fix BookReaderAuth.php bridge for setting seamless borrow cookies between

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#9986]
### Problem

WAF rules and code audits blocking seamless UX lending bridge

We may also need to investigate BookReaderAuthProxy.php and the `ol-auth-url` cookie to see whether they are necessary

#### Requirements Checklist
* [x] WAF
* [x] Code audit

#### Related files

* https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/borrow.py#L930-L948

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
This has been fixed, but a new issue has arisen around outdated data in our db preventing some users from borrowing. They can resolve the issue by logging out/logging in, but we should handle that automatically, ideally.
